### ISSUE TITLE
In specific inboxes, wrong account selected for reply [$10]

### ISSUE THREAD

**Issue by jancborchardt** [nextcloud/mail#10]
I have 2 accounts configured. The first one has one alias.

When I am in the single inbox of the second one, whenever I open an email which has people in CC, the wrong email (the second one) is selected in the »from« dropdown. It’s fine when the mail is just sent to me without CC.

cc @tahaalibra since this appeared with the introduction of aliases.

**Comment by jancborchardt** [comment]
cc @tahaalibra let’s continue here – we moved repositories. :)

**Comment by tahaalibra** [comment]
can you provide screenshot or something. are others experiencing it too because i am not able to reproduce 
@jancborchardt

**Comment by hechi** [comment]
@jancborchardt i am also not able to reproduce it :(

**Comment by jancborchardt** [comment]
@ChristophWurst or anyone @nextcloud/mail are you not able to reproduce this? I have this issue _all the time_. :(

**Comment by plastikschnitzer** [comment]
I can reproduce it in the [pre-0.7 release](https://github.com/nextcloud/mail/releases/tag/nightly-20170823): Set up multiple email accounts, select the second one and write a reply to an email with people in CC, the from: address is the one from the first account. If there is no one in CC, its working fine!

**Comment by ChristophWurst** [comment]
@plastikschnitzer could you please file an issue for that? I'll have a look tomorrow :)
