### ISSUE TITLE
Mail without body preview but unread indicator has layout issue and is glitching on hover

### ISSUE THREAD

**Issue by jancborchardt** [nextcloud/mail#10031]
### Steps to reproduce

1. Find a mail without body preview in the list, e.g. any Nextcloud notification
2. Mark it as unread
3. Look at the unread indicator being on its own line
4. Hover over it to see it glitch too

### Expected behavior

The unread indicator not being off in the layout, and hover/focus not making it glitch.

Maybe an easy fix for this can be to put the unread indicator on the line of the sender instead?

### Actual behavior

Unread indicator takes whole row | Hover removes that row, making it glitch
-|-
![image](https://github.com/user-attachments/assets/dff66bfb-575e-4ca4-93d3-1bb3e7e63981)|![image](https://github.com/user-attachments/assets/f597bd5d-da5b-44b1-8f4e-6a9fe655cd22)

### Mail app version

4.0.0-beta.1

### PHP engine version

None

### Web server

None

### Database

None

**Comment by jancborchardt** [comment]
The reason why they have no body preview btw is that they do not exist but still show up in Mail. (Probably still good to fix this if people send a mail with subject only?)
![image](https://github.com/user-attachments/assets/2bb2a1bf-6b10-4771-8538-a301ecc45372)

**Comment by ChristophWurst** [comment]
@GretaD @GVodyanov could you have a look please?

**Comment by GretaD** [comment]
this is fixed by https://github.com/nextcloud/mail/pull/10022

will close it after testing again :)

**Comment by jancborchardt** [comment]
Awesome, thanks @GretaD! :)
