### ISSUE TITLE
List layout is not shown in one line

### ISSUE THREAD

**Issue by GretaD** [nextcloud/mail#10043]
### Steps to reproduce

1. Open mail app
2. Change the layout from mail settings to list layout
3. See the style

### Expected behavior

Messages are shown in one line

### Actual behavior

Messages are shown in 2 lines
![Screenshot from 2024-08-23 12-18-57](https://github.com/user-attachments/assets/d2c3b270-5907-45b8-a3e6-fe5577cdd889)

### PHP engine version

None

### Web server

None

### Database

None

**Comment by ChristophWurst** [comment]
This is important to be fixed before the final release

**Comment by GretaD** [comment]
@GVodyanov do you have some time to have a look at this one? You probably missed some styling when you created our own component, you can compare with my original pr: https://github.com/nextcloud-libraries/nextcloud-vue/pull/5209
it should be something like flex-direction: row and some width, that is missing. Otherwise i can have a look after my customer call.

**Comment by GVodyanov** [comment]
My bad, for some reason I remembered it having two lines and not just one
