### ISSUE TITLE
Error trying to open sent Items folder

### ISSUE THREAD

**Issue by vszadera** [nextcloud/mail#1007]
### Expected behavior
By clicking on the link Sent, you should open the folder with the sent mail

### Actual behavior
You receive a "problem downloading sent Items" message"

### Mail app

**Mail app version:** (see apps admin page, e.g. 0.5.3)
0.8.3

**Mailserver or service:** (e.g. Outlook, Yahoo, Gmail, Exchange,...)
mail.ru

**Number of accounts:** (e.g. 1 or 2)

### Server configuration

**Operating system**: (e.g. Debian 8)
Debian 9 and Ubuntu 16.04

**Web server:** (e.g. Apache, Nginx,...)
Apache2.4

**Database:** (e.g. MariaDB, SQLite, PostgreSQL,...)
MariaDB 10.1
**PHP version:** (e.g. 7.0)
7.0
**Nextcloud Version:** (see admin page, e.g. 13.0.2)
13.0.5
**Updated from an older version or fresh install:**
New install

**Comment by ChristophWurst** [comment]
The Nextcloud mail app offers an extensive logging system to make it easier identifying and tracking down bugs. Please enable [debug mode](https://docs.nextcloud.com/server/13/developer_manual/general/devenv.html#enabling-debug-mode) and set the log [level to debug](https://docs.nextcloud.com/server/13/admin_manual/configuration_server/logging_configuration.html) in your admin settings. Then, try to reproduce your issue and take another look at `data/nextcloud.log`, `data/horde_imap.log` and `data/horde_smtp.log`.

**Comment by ChristophWurst** [comment]
No info provided -> closing
