### ISSUE TITLE
*Reply to sender only* replies all

### ISSUE THREAD

**Issue by ChristophWurst** [nextcloud/mail#10089]
### Steps to reproduce

1. Receive an email with multiple recipients, or an email to a mailing list
2. Click *Reply to sender only*

### Expected behavior

The sender is selected as recipient of the reply.

### Actual behavior

All previous thread participants are selected, or the mailing list in case the original message went to a list.

### Mail app version

4.0.0

### PHP engine version

None

### Web server

None

### Database

None

**Comment by GretaD** [comment]
this is regression of https://github.com/nextcloud/mail/pull/9921
