### ISSUE TITLE
Need more message options

### ISSUE THREAD

**Issue by Luticus** [nextcloud/mail#1008]
### Feature Request

More message options!

#### Summary

We need more message options, like mark read/unread, mark spam.  We also need maybe a tool bar at the top with options that apply to multiple messages, like mark selected read/unread/trash and a clear folder button (especially in the trash folder) that lets you delete all messages. This may also imply that we need message multi select as well.

**Comment by Gatak** [comment]
Drag and drop messages between folders and account would be useful as well as multi select. 

I also think we perhaps need some more status on messages. 

RFC3501 specifies several message flags that could be useful. Currently there is starred, read and unread in Mail app.

''
        \Answered
           Message has been answered

        \Flagged
           Message is "flagged" for urgent/special attention

        \Deleted
           Message is "deleted" for removal by later EXPUNGE

        \Draft
           Message has not completed composition (marked as a draft).

        \Recent
           Message is "recently" arrived in this mailbox.  This session
           is the first session to have been notified about this
           message; if the session is read-write, subsequent sessions
           will not see \Recent set for this message.  This flag can not
           be altered by the client.
''
