### ISSUE TITLE
Do not automatically mark selected mail as read

### ISSUE THREAD

**Issue by Markoise** [nextcloud/mail#10109]
### Is your feature request related to a problem? Please describe.

When the inbox is opened, a mail from the list is automatically set to the focus. The content of the mail is displayed in the preview. If it is an unread mail, it is immediately marked as read, even if you have not read the text at all.

### Describe the solution you'd like

It would be great if you could set whether a mail is marked as read when the preview shows the content or not.

**Comment by p-try** [comment]
Duplicate: #7753

**Comment by kesselb** [comment]
Thanks for your feature request @Markoise 🙏 

> When the inbox is opened, a mail from the list is automatically set to the focus.

We are not opening the first message in the mailbox automatically anymore and therefore the problem is hopefully solved for you ;)
