### ISSUE TITLE
Mailserver not reachable in same Network

### ISSUE THREAD

**Issue by Dominik9798** [nextcloud/mail#10103]
### Steps to reproduce

1. Proxmox host 10.10.0.1/24
2. Mailcow dockerized 10.10.0.102/24
3. All mailports over iptables from 10.10.0.1 -> 10.10.0.102
4. Nextcloud AiO 10.10.0.6 behind reverseproxy 10.10.0.3
5. Verything is working, but i cannot connect my E-Mail account in the Mail app
6. Use 10.10.0.102 and my fqdn Mail-Server-Name isnt working

### Expected behavior

Mail account connect, like in other dockerized programs running in the same network.

### Actual behavior

<img width="351" alt="image" src="https://github.com/user-attachments/assets/3b28a6a7-e322-4c36-9612-4f89e3109fda">

<img width="334" alt="image" src="https://github.com/user-attachments/assets/2cccc412-57ca-44df-b5c1-9f1f115c0eab">

### Mail app version

3.7.8

### Mailserver or service

Mailcow

### Operating system

Debian 12

### PHP engine version

PHP 8.2

### Web server

Nginx

### Database

PostgreSQL

### Additional info

Nextcloud Hub 8 (29.0.4)

**Comment by kesselb** [comment]
Hi, it's probable that you'll need to allow local connections before proceeding: https://github.com/nextcloud/mail/blob/main/doc/admin.md#local-imap-and-smtp-servers

**Comment by Dominik9798** [comment]
it is already true

/var/lib/docker/volumes/nextcloud_aio_nextcloud/_data/config
line 89 ->   'allow_local_remote_servers' => true,

**Comment by Dominik9798** [comment]
A friend of mine told me to extend the start command by mounting the /etc/hosts file. That doesn't work either.

--mount type=bind,source=/etc/hosts,target=/etc/hosts

**Comment by kesselb** [comment]
Here are some additional steps to check the connectivity from your container: https://github.com/nextcloud/mail/blob/main/doc/admin.md#timeout-and-other-connectivity-issues

If that works, please enable the logging https://github.com/nextcloud/mail/blob/main/doc/admin.md#logging and share the logs with us. Please check them for sensitive information, they contain the traffic between mail and your imap/smtp server.

**Comment by Dominik9798** [comment]
Output from openssl s_time -connect 10.10.0.102:993
https://gist.github.com/Dominik9798/3b412588ac9070b4bb380981761da4dc

Logging in NC webinterface
![Image](https://github.com/user-attachments/assets/58f84ce8-db09-406b-9b26-7844b35d000d)

The logging in config.php doesn't exist. Should I create the  'debug' => true, manually?

**Comment by kesselb** [comment]
> The logging in config.php doesn't exist. Should I create the 'debug' => true, manually?

Yes please

**Comment by Dominik9798** [comment]
https://gist.github.com/Dominik9798/10493dcda72226126a4f509e9d78e0b2

https://gist.github.com/Dominik9798/a270254d7ec3beea9516fc7d83aa2907

**Comment by Dominik9798** [comment]
In the config.php?

**Comment by Dominik9798** [comment]
Thanks, it now works with 10.10.0.102.
mail.xxx.xx still does not work. But that's enough for me with the internal IP address
