### ISSUE TITLE
Sieve not working

### ISSUE THREAD

**Issue by sergiupapuc** [nextcloud/mail#10139]
### Steps to reproduce

1.open mail app
2.go to account setting sieve
3.sieve emty and save keep spinning

### Expected behavior

show sieve script made in roundcube...which is working with same mail server...on dovecot log, nextcloud mail do not send username(email address)...is empty!

### Actual behavior

not working!...log ...there is no auth protocol....it is plain login on dovecot...roundcube work

### Mail app version

3.7.8

### Mailserver or service

imap dovecot

### Operating system

ubuntu 24.04

### PHP engine version

PHP 8.3

### Web server

Apache (supported)

### Database

MariaDB

### Additional info

{"reqId":"eiVokYiILNU9BBRwlpRr","level":3,"time":"2024-09-12T17:00:51+00:00","remoteAddr":"2a00:5dc2:11:4::22","user":"015D1767-5A9A-415C-ABA1-E4A3CD2183D7","app":"mail","method":"GET","url":"/index.php/apps/mail/api/out-of-office/3709","message":"Connection to ManageSieve at mailsenat.senat.ro:4190 failed. No supported authentication method found. The server supports these methods: , but we only support: EXTERNAL, PLAIN, LOGIN","userAgent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/128.0.0.0 Safari/537.36 Edg/128.0.0.0","version":"29.0.7.1","exception":{"Exception":"OCA\\Mail\\Exception\\CouldNotConnectException","Message":"Connection to ManageSieve at mailsenat.senat.ro:4190 failed. No supported authentication method found. The server supports these methods: , but we only support: EXTERNAL, PLAIN, LOGIN","Code":0,"Trace":[{"file":"/var/www/nextcloud/apps/mail/lib/Service/SieveService.php","line":48,"function":"getClient","class":"OCA\\Mail\\Service\\SieveService","type":"->"},{"file":"/var/www/nextcloud/apps/mail/lib/Service/OutOfOfficeService.php","line":75,"function":"getActiveScript","class":"OCA\\Mail\\Service\\SieveService","type":"->"},{"file":"/var/www/nextcloud/apps/mail/lib/Controller/OutOfOfficeController.php","line":71,"function":"parseState","class":"OCA\\Mail\\Service\\OutOfOfficeService","type":"->"},{"file":"/var/www/nextcloud/lib/private/AppFramework/Http/Dispatcher.php","line":232,"function":"getState","class":"OCA\\Mail\\Controller\\OutOfOfficeController","type":"->"},{"file":"/var/www/nextcloud/lib/private/AppFramework/Http/Dispatcher.php","line":138,"function":"executeController","class":"OC\\AppFramework\\Http\\Dispatcher","type":"->"},{"file":"/var/www/nextcloud/lib/private/AppFramework/App.php","line":184,"function":"dispatch","class":"OC\\AppFramework\\Http\\Dispatcher","type":"->"},{"file":"/var/www/nextcloud/lib/private/Route/Router.php","line":331,"function":"main","class":"OC\\AppFramework\\App","type":"::"},{"file":"/var/www/nextcloud/lib/base.php","line":1058,"function":"match","class":"OC\\Route\\Router","type":"->"},{"file":"/var/www/nextcloud/index.php","line":49,"function":"handleRequest","class":"OC","type":"::"}],"File":"/var/www/nextcloud/apps/mail/lib/Service/SieveService.php","Line":90,"Previous":{"Exception":"Horde\\ManageSieve\\Exception","Message":"No supported authentication method found. The server supports these methods: , but we only support: EXTERNAL, PLAIN, LOGIN","Code":0,"Trace":[{"file":"/var/www/nextcloud/apps/mail/vendor/nextcloud/horde-managesieve/lib/Horde/ManageSieve.php","line":592,"function":"_getBestAuthMethod","class":"Horde\\ManageSieve","type":"->"},{"file":"/var/www/nextcloud/apps/mail/vendor/nextcloud/horde-managesieve/lib/Horde/ManageSieve.php","line":392,"function":"_cmdAuthenticate","class":"Horde\\ManageSieve","type":"->"},{"file":"/var/www/nextcloud/apps/mail/vendor/nextcloud/horde-managesieve/lib/Horde/ManageSieve.php","line":243,"function":"login","class":"Horde\\ManageSieve","type":"->","args":["*** sensitive parameters replaced ***"]},{"file":"/var/www/nextcloud/apps/mail/vendor/nextcloud/horde-managesieve/lib/Horde/ManageSieve.php","line":215,"function":"_handleConnectAndLogin","class":"Horde\\ManageSieve","type":"->"},{"file":"/var/www/nextcloud/apps/mail/lib/Sieve/SieveClientFactory.php","line":113,"function":"__construct","class":"Horde\\ManageSieve","type":"->"},{"file":"/var/www/nextcloud/apps/mail/lib/Sieve/SieveClientFactory.php","line":65,"function":"createClient","class":"OCA\\Mail\\Sieve\\SieveClientFactory","type":"->","args":["*** sensitive parameters replaced ***"]},{"file":"/var/www/nextcloud/apps/mail/lib/Service/SieveService.php","line":88,"function":"getClient","class":"OCA\\Mail\\Sieve\\SieveClientFactory","type":"->"},{"file":"/var/www/nextcloud/apps/mail/lib/Service/SieveService.php","line":48,"function":"getClient","class":"OCA\\Mail\\Service\\SieveService","type":"->"},{"file":"/var/www/nextcloud/apps/mail/lib/Service/OutOfOfficeService.php","line":75,"function":"getActiveScript","class":"OCA\\Mail\\Service\\SieveService","type":"->"},{"file":"/var/www/nextcloud/apps/mail/lib/Controller/OutOfOfficeController.php","line":71,"function":"parseState","class":"OCA\\Mail\\Service\\OutOfOfficeService","type":"->"},{"file":"/var/www/nextcloud/lib/private/AppFramework/Http/Dispatcher.php","line":232,"function":"getState","class":"OCA\\Mail\\Controller\\OutOfOfficeController","type":"->"},{"file":"/var/www/nextcloud/lib/private/AppFramework/Http/Dispatcher.php","line":138,"function":"executeController","class":"OC\\AppFramework\\Http\\Dispatcher","type":"->"},{"file":"/var/www/nextcloud/lib/private/AppFramework/App.php","line":184,"function":"dispatch","class":"OC\\AppFramework\\Http\\Dispatcher","type":"->"},{"file":"/var/www/nextcloud/lib/private/Route/Router.php","line":331,"function":"main","class":"OC\\AppFramework\\App","type":"::"},{"file":"/var/www/nextcloud/lib/base.php","line":1058,"function":"match","class":"OC\\Route\\Router","type":"->"},{"file":"/var/www/nextcloud/index.php","line":49,"function":"handleRequest","class":"OC","type":"::"}],"File":"/var/www/nextcloud/apps/mail/vendor/nextcloud/horde-managesieve/lib/Horde/ManageSieve.php","Line":1104},"message":"Connection to ManageSieve at mailsenat.senat.ro:4190 failed. No supported authentication method found. The server supports these methods: , but we only support: EXTERNAL, PLAIN, LOGIN","exception":[],"CustomMessage":"Connection to ManageSieve at mailsenat.senat.ro:4190 failed. No supported authentication method found. The server supports these methods: , but we only support: EXTERNAL, PLAIN, LOGIN"},"id":"66e31fbd4b1b2"}

**Comment by kesselb** [comment]
Hi, did you configure to use the same credentials as for IMAP or use own credentials? The log snippet shows that our mail app and your sieve server cannot agree on an authentication method.

**Comment by sergiupapuc** [comment]
....use the same user/pass....roundcube to the same imap server works flowless!

***@***.***

Sergiu Papuc
Consilier
Directia Generala Economica


Parlamentul României, SENAT
Calea 13 Septembrie, nr. 1-3, sector 5, Bucureşti, 050711
tel: (+40) 743.009.940
e-mail: ***@***.******@***.***>
web: www.senat.ro<http://www.senat.ro/>

**Comment by kesselb** [comment]
It appears that your Roundcube installation is hosted on the same server as Dovecot, which may require specific authentication configurations. Based on the exception provided, it seems that Dovecot is returning an empty list of available authentication methods. Could you please consult your system administrators to verify whether login for Sieve is permitted for external clients?

**Comment by sergiupapuc** [comment]
...no...is the same username and password, tested also from roundcube hosted on another server...works!

Trimis de pe Outlook pentru Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by kesselb** [comment]
I see, thanks for your prompt reply. 

Could you please turn on the debug mode, try to enable sieve and send the `horde_sieve.log` to danielk@nextcloud.com?

How to enable debug mode for mail: https://github.com/nextcloud/mail/blob/main/doc/admin.md#logging

**Comment by nextcloud-command** [comment]
Hi there! It looks like this issue hasn’t seen much activity for a while and might need a bit more information to move forward. If we don’t hear back soon, we may close it to keep things organized. Thanks again for your contributions – we really appreciate it!
