### ISSUE TITLE
Mail Folder/Mailbox rename failed

### ISSUE THREAD

**Issue by wriver4** [nextcloud/mail#10136]
### Steps to reproduce

1. Got to Mail Rename Folder/Mailbox
2. Change name from Archive to Archives
3.

### Expected behavior

It should rename.

### Actual behavior

It renames everywhere but the menu. Refresh, Logout, Flushing browser cache, still no change
![rename folder issue1](https://github.com/user-attachments/assets/e5480916-bfad-429c-b5d5-4b6b0abebc83)
![mail issue 2](https://github.com/user-attachments/assets/867e9c01-787e-4cf0-8e70-6dc883a21879)

### Mail app version

3.7.8

### Mailserver or service

Postfix/Dovecot

### Operating system

Ubuntu 22.04.4 LTS

### PHP engine version

PHP 8.3

### Web server

Apache (supported)

### Database

MariaDB

### Additional info

none now

**Comment by ChristophWurst** [comment]
Mail caches mailbox info for 2h

It's probably a bug that the new mailbox name is not saved

**Comment by the-djmaze** [comment]
Try renaming Junk or Trash or Sent.
Could be possible that Archive (just like the others i mention) is a server configure mailbox, and renaming is not possible.

**Comment by nextcloud-command** [comment]
Hi there! It looks like this issue hasn’t seen much activity for a while and might need a bit more information to move forward. If we don’t hear back soon, we may close it to keep things organized. Thanks again for your contributions – we really appreciate it!
