### ISSUE TITLE
Horizontal view should take us to the latest message

### ISSUE THREAD

**Issue by GretaD** [nextcloud/mail#10155]
### Steps to reproduce

1. Go to mail app and change the layout mode to horizontal layour
2. Open a thread with couple of threads
3. See the list of thread but not the latest one that is open

### Expected behavior

The latest message/ the opened message is shown on my view

### Actual behavior

The start of the list of the messages(thread) is shown instead

### PHP engine version

None

### Web server

None

### Database

None

**Comment by ChristophWurst** [comment]
Dup of https://github.com/nextcloud/mail/issues/7552
