### ISSUE TITLE
To allow more compach UI

### ISSUE THREAD

**Issue by ratermir** [nextcloud/mail#10186]
### Describe the solution you'd like

Mainly in the list (but also at other places ) there are too much "free space". I would appretiate more compach design, whichfocus to important content and provide more information on single page.

The compact design could be as an option. 

Google is very good inspiration how to create UI - they have many UX experts; why don't inspire there?

![image](https://github.com/user-attachments/assets/7e48fdbd-7348-41ab-9f7b-8c4a691b469b)
 

### Additional context

I know there is an option to create custom CSS (and I'd make it), I performed it for files app and also for calendar app several times, but after almost every NC version upgrade my changes stopped working. So this  is not a way.

**Comment by da-anda** [comment]
check latest version of Nextcloud which contains the new mail app version - spacing is waaaay better there
