### ISSUE TITLE
To add icon to the "resend" menu option

### ISSUE THREAD

**Issue by ratermir** [nextcloud/mail#10185]
### Steps to reproduce

Open mail app
Open context menu - will see missing icon

### Expected behavior

To see icon in the menu

### Actual behavior

In the context menu there is a missing icon for the "resend" options. 
The functionality works, but the UI looks inconsistent and non-profesional. 

![image](https://github.com/user-attachments/assets/2040f8ea-aaee-49d5-a326-648ac30b6126)

### Mail app version

3.7.8

### Mailserver or service

mailu

### Operating system

Docker

### PHP engine version

PHP 8.1

### Web server

Nginx

### Database

PostgreSQL

**Comment by kesselb** [comment]
Thanks for your report 👍 

I'm unable to reproduce with Mail 3.7.8.

Maybe a caching issue?

![Image](https://github.com/user-attachments/assets/458f2ee7-c3f1-4490-b066-fabd97dc0ad4)

**Comment by nextcloud-command** [comment]
Hi there! It looks like this issue hasn’t seen much activity for a while and might need a bit more information to move forward. If we don’t hear back soon, we may close it to keep things organized. Thanks again for your contributions – we really appreciate it!

**Comment by ratermir** [comment]
In new version it is OK.
