### ISSUE TITLE
Allow folders filering in the folder selection dialog 

### ISSUE THREAD

**Issue by ratermir** [nextcloud/mail#10183]
### Describe the solution you'd like

When I want to move mail into a folder by selecting target folder, it would be very useful to allow "filtering" folders by typing text fragment in the dialog, where I select target folder. 
If I have many folders, it isreally annoying to open all mails again and again to select target. 
It would be much faster to filter the list - most users usually know name of the target folder.

**Comment by ChristophWurst** [comment]
Thank you for your report!

This appears to be a duplicate of https://github.com/nextcloud/mail/issues/7536.

I'm closing this.
