### ISSUE TITLE
first email is marked as read on mobile device although it is not shown

### ISSUE THREAD

**Issue by jakobsack** [nextcloud/mail#102]
### Steps to reproduce
1. Have an unread email on top of the list
2. Open the mail app with your mobile device
3. The email will be marked as read but it is not shown
### Expected behaviour

Email should stay unread
### Actual behaviour

Email gets marked read
### Mail app

**Mail app version:** 0.5.3

**Number of accounts:** 1
### Server configuration

**Operating system**: Debian Jessie

**Web server:** apache

**Database:** mysql
#### Client configuration

**Browser:** Edge on Windows 10 mobile

**Operating system:** Windows 10 mobile

**Comment by jancborchardt** [comment]
Good point actually. We probably need some specific code on mobile which notices that the mail has not actually been shown.

**Comment by lcalaresu** [comment]
That one bothers me, I have "missed" a few emails for the past few days that were marked as read on my mobile.

Actually is there a reason why the first message is automatically open when we select a folder? (even on desktop)
I have several folders on my accounts, and often change the folder selection... I end up having the last received email marked as read.

**Comment by ChristophWurst** [comment]
summoning @jancborchardt here. He's our UX expert :)

**Comment by jancborchardt** [comment]
It's automatically opened to just get started faster, otherwise there's just a big space on the right. This way you are directly in there. Just like with the directly visible reply field on the bottom.

We could make the change to not mark the first one which gets opened automatically as read.

**Comment by lcalaresu** [comment]
@jancborchardt 

> We could make the change to not mark the first one which gets opened automatically as read.

Yeah but... in that case, since the message is open, it could still be read by the user but not marked like it was. Maybe that should stay like this on desktop then.

**Comment by jancborchardt** [comment]
@lcalaresu that's why I'd say we do what I mentioned above:

> We probably need some specific code on mobile which notices that the mail has not actually been shown.

**Comment by lcalaresu** [comment]
All right ;)
Just opened a pull request for that change on mobile phones.

**Comment by ChristophWurst** [comment]
Fixed by #395. Thanks @lcalaresu! :)

**Comment by jancborchardt** [comment]
Awesome work @lcalaresu! :)
