### ISSUE TITLE
163 email cannot be used

### ISSUE THREAD

**Issue by auxpd** [nextcloud/mail#10219]
### Steps to reproduce

-

### Expected behavior

-

### Actual behavior

I also have this problem and it cannot be used when using the 163 mailbox.
{message: "mailbox 32 is not cached", type: "OCA\Mail\Exception\MailboxNotCachedException"}

ServiceException
Can not get messages from mailbox INBOX: Could not open mailbox "INBOX".

### PHP engine version

None

### Web server

None

### Database

None

**Comment by ChristophWurst** [comment]
hi @auxpd! thanks for the report. is 163 the id or name of your mailbox? please update your report to tell us how this problem could possibly be reproduced.

**Comment by bluestar800** [comment]
> 你好 [@auxpd](https://github.com/auxpd)！感谢您的报告。 163是你邮箱的id还是名字？请更新您的报告，告诉我们如何重现此问题。

I have the same problem. [6196](https://github.com/nextcloud/mail/issues/6196)

mail application version is 3.7.8
nextcloud version is 29.0.8

163 is a mail service provider, providing mail services.

**Comment by Mareep-YANG** [comment]
> hi [@auxpd](https://github.com/auxpd)! thanks for the report. is 163 the id or name of your mailbox? please update your report to tell us how this problem could possibly be reproduced.

Same problem too
I can also add a 163 email account to the mail application; it can even load the number of right-clicked inboxes, but it cannot load any email content. The log shows an error:  

"ServiceException  
Can not get messages from mailbox INBOX: Could not open mailbox 'INBOX'."  

163 is a Chinese email service provider.  

My mail application version is 4.0.2.  
Nextcloud version is 30.0.2.

**Comment by nextcloud-command** [comment]
Hi there! It looks like this issue hasn’t seen much activity for a while and might need a bit more information to move forward. If we don’t hear back soon, we may close it to keep things organized. Thanks again for your contributions – we really appreciate it!

**Comment by zeronx798** [comment]
Same issue. I turned on debug mode, in file `horde_imap.log`, I noticed the following output:
```
>> Sun, 09 Feb 2025 02:29:25 +0000
>> Connection to: imap://imap.163.com:993/
>> Server connection took 0.1305 seconds.
S: * OK Coremail System IMap Server Ready(163com[10774b260cc7a37d26d71b52404dcf5c])
C: 1 CAPABILITY
S: * CAPABILITY IMAP4rev1 XLIST SPECIAL-USE ID LITERAL+ STARTTLS APPENDLIMIT=71680000 XAPPLEPUSHSERVICE UIDPLUS X-CM-EXT-1 SASL-IR AUTH=XOAUTH2
S: 1 OK CAPABILITY completed
>> Command 1 took 0.027 seconds.
C: 2 LOGIN <my_mail>@163.com [PASSWORD]
S: 2 OK LOGIN completed
>> Command 2 took 0.0695 seconds.
C: 3 CAPABILITY
S: * CAPABILITY IMAP4rev1 XLIST SPECIAL-USE ID LITERAL+ STARTTLS APPENDLIMIT=71680000 XAPPLEPUSHSERVICE UIDPLUS X-CM-EXT-1 SASL-IR AUTH=XOAUTH2
S: 3 OK CAPABILITY completed
>> Command 3 took 0.0272 seconds.
C: 4 EXAMINE INBOX
S: 4 NO EXAMINE Unsafe Login. Please contact kefu@188.com for help
>> Command 4 took 0.0269 seconds.
C: 5 LOGOUT
S: * BYE IMAP4rev1 Server logging out
S: 5 OK LOGOUT completed
>> Command 5 took 0.0272 seconds.
```
Refer to [this official document](https://help.mail.163.com/faqDetail.do?code=d7a5dc8471cd0c0e8b4b8f4f8e49998b374173cfe9171305fa1ce630d7f67ac2eda07326646e6eb0), not sending IMAP ID might be the reason. I wonder if it's possible to consider improving this part? Thank you!

**Comment by huochairener** [comment]
尝试了#12151的方法，依旧无法获取163邮箱的邮件，只能获取到邮件数量，用docker部署的，希望能尽快修复
