### ISSUE TITLE
[RTL] Broken radio + misaligned heading in account settings

### ISSUE THREAD

**Issue by hamza221** [nextcloud/mail#10226]
### Steps to reproduce

![Image](https://github.com/user-attachments/assets/e515f036-7453-45ae-9eb8-090baef00f90)

### Expected behavior

Good design

### Actual behavior

Bad design

### PHP engine version

None

### Web server

None

### Database

None

**Comment by GretaD** [comment]
will work this with an intern

**Comment by hamza221** [comment]
Assigning this to myself after discussing with Greta, as I'm trying to finish the RTL work asap

**Comment by hamza221** [comment]
done
