### ISSUE TITLE
More discoverable multi-select and bulk operations

### ISSUE THREAD

**Issue by ChristophWurst** [nextcloud/mail#10231]
**Problem:**

Users didn't know that it is possible to select multiple messages and perform bulk operations such as move, archive, marks as spam or delete.

**Comment by marcoambrosini** [comment]
@ChristophWurst wasn't this tracked in another issue?

**Comment by ChristophWurst** [comment]
It's https://github.com/nextcloud/mail/issues/10194

**Comment by jancborchardt** [comment]
@marcoambrosini @nimishavijay since neither @ChristophWurst nor me were in the brainstorming session, could you fill the description with more detail on what this is about? :)

**Comment by marcoambrosini** [comment]
Design call outcome:  
- On desktop: show checkbox on hover (either overlay or replace avatar)
- On mobile: click on avatar
- Remove select action from the actions menu
- Take important bulk actions out of the 3 dot menu

**Comment by GretaD** [comment]
> Design call outcome:
> 
> * On desktop: show checkbox on hover (either overlay or replace avatar)
> * On mobile: click on avatar
> * Remove select action from the actions menu
> * Take important bulk actions out of the 3 dot menu

can you please make a small mock up for the ones you can? Its a bit hard to imagine how it will look like. For example when you say take importand bulk out of 3 dot menu, where to put it if i take it out? Same for Remove select from actions menu.

**Comment by nimishavijay** [comment]
In Protonmail and Gmail replace the avatar with the checkbox, so we can also do something like that 

![Image](https://github.com/user-attachments/assets/b01e1e74-78e0-4f9d-96fe-fe89f58528f2)


> Remove select action from the actions menu

This would just mean don't show "Select" in the 3 dot menu of any mail, so it would look like this:

![Image](https://github.com/user-attachments/assets/aa289284-0600-40ba-836e-44f3402257bb)


> Take important bulk actions out of the 3 dot menu

![Image](https://github.com/user-attachments/assets/1837b959-40c4-4667-9de2-eb64d62ea55c)

Once you select something, these actions can be moved out of the menu and just shown up front as icons.

![Image](https://github.com/user-attachments/assets/0f7df0a5-78f6-43de-ba3e-70449bcf780e)

If all the icons don't fit in the width, they can be put into the a 3 dot menu.

**Comment by GretaD** [comment]
> In Protonmail and Gmail replace the avatar with the checkbox, so we can also do something like that
> 
> ![Image](https://github.com/user-attachments/assets/b01e1e74-78e0-4f9d-96fe-fe89f58528f2)


What part of the message is hovered/selected, only the avatar or the whole message?

**Comment by nimishavijay** [comment]
> What part of the message is hovered/selected, only the avatar or the whole message?

When the avatar is hovered, rest of the message has the normal hover feedback as it exists right now :) (ref hey mail and protonmail, same behaviour :) )

**Comment by GretaD** [comment]
> > What part of the message is hovered/selected, only the avatar or the whole message?
> 
> When the avatar is hovered, rest of the message has the normal hover feedback as it exists right now :) (ref hey mail and protonmail, same behaviour :) )

i dont have protonmail or hey mail, so i cannot check how it looks like, but my question was, if i hover the message, should the checkmark be shown? Or should it be shown only when i hover the avatar area?

**Comment by jancborchardt** [comment]
@GretaD Only when the avatar is hovered/focused – otherwise it would be too distracting if every time you hover a message, the avatar switches to a checkmark. :)
