### ISSUE TITLE
psr/log update in server/3rdparty broke ci for master

### ISSUE THREAD

**Issue by kesselb** [nextcloud/mail#10236]
### Steps to reproduce

1. Run CI against master
2. 💥 

### Actual behavior

```PHP Fatal error:  Declaration of Psr\Log\AbstractLogger::emergency($message, array $context = []) must be compatible with Psr\Log\LoggerInterface::emergency(Stringable|string $message, array $context = []): void in /home/runner/actions-runner/_work/mail/mail/nextcloud/apps/mail/vendor/psr/log/Psr/Log/AbstractLogger.php on line 22```

### Additional info

**Solution 1: Update psr/log to 3.0.2**

https://github.com/nextcloud/mail/pull/10237

Good: Package matches the version in 3rdparty
Bad: The version in stable29 and stable30 is still psr/log 1.x. 

**Solution 2: Remove psr/log**

https://github.com/nextcloud/mail/pull/10235

The package is bundled with nextcloud, and therefore it's actually wrong to have it here. We can utilize the composer replace function, but that's also tricky. 

For example, we need stubs for the logger interfaces otherwise psalm is not happy. Installing the package temporary (like we do with nextcloud/ocp) does not work because of the replace definition.

**Comment by the-djmaze** [comment]
Just a heads-up:

![Image](https://github.com/user-attachments/assets/35ab2301-aae7-47fc-94e1-cf606bb48466)
Taken from https://xkcd.com/927/
