### ISSUE TITLE
Remember expanded/collapsed state of navigation folders

### ISSUE THREAD

**Issue by trueshanti** [nextcloud/mail#1025]
Please add a option to autoexpand the 1st-level folder view.

Even with only the default (IMAP-)folders (favorites, sent, drafts, spam, trash) only the first 3 folders are visible .. i have to expand the view to see the rest on every reload.

#

Raising the visible entries from 3 to 6 is not what i would like to see .. i would prefer an option to show all folders that reside on the main-level.

thanks for support

**Comment by stefan-niedermann** [comment]
Maybe instead just remembering which folders are expanded is a better solution?

**Comment by trueshanti** [comment]
@stefan-niedermann that would be even more gorgeous
