### ISSUE TITLE
Mailbox actions are broken

### ISSUE THREAD

**Issue by hamza221** [nextcloud/mail#10270]
### Steps to reproduce

1.Open mail app 
2.click on mail box actions
3. (...) button disappears 
4. popover doesn't open 

### Expected behavior

popover opens, button doesn't disappears

### Actual behavior

1. (...) button disappears 
2. popover doesn't open 

[Bildschirmaufnahme_20241022_194043.webm](https://github.com/user-attachments/assets/15a03f9e-1df2-48d6-9cb2-fc35527c8125)

### PHP engine version

None

### Web server

None

### Database

None

### Additional info

appeared after c55089baf99f24e6cfa504ab573f3f76051e8534

**Comment by st3iny** [comment]
My findings (so far):
- Removing the nesting inside `NavigationMailbox` fixes the issue
- Removing the `menuOpen` prop from `NcAppNavigationItem` fixes the issue

**Comment by ChristophWurst** [comment]
4.1 fix at https://github.com/nextcloud/mail/pull/10351
