### ISSUE TITLE
Impossible to access the three dots menu with long email adresses

### ISSUE THREAD

**Issue by Aveyron-RetD** [nextcloud/mail#10297]
### Steps to reproduce

1. Have a big email address
2. Try to access the three dots menu of the inbox
3. Impossible, the three dots menu is not accessible
![Image](https://github.com/user-attachments/assets/f424a534-3ec4-4864-acd2-a714154cbbfb)

### Expected behavior

three dots menu should be accessible 

### Actual behavior

Three dots menu is missing and cannot click on it

### Mail app version

4.0

### Nextcloud version

30

### PHP engine version

None

### Web server

None

### Database

None

**Comment by GretaD** [comment]
this is fixed, but we need to updrade to nc/vue 8.17: https://github.com/nextcloud-libraries/nextcloud-vue/pull/5982

also, is a dublication of https://github.com/nextcloud/mail/issues/10151
