### ISSUE TITLE
HTML emails are shown in a small frame

### ISSUE THREAD

**Issue by jpschewe** [nextcloud/mail#10319]
### Steps to reproduce

This looks to be the same problem as issue #3696. 
In previous versions of mail I could see the whole email. Now I only get part of it and need to scroll despite the browser window having plenty of space.

![Image](https://github.com/user-attachments/assets/889c4165-1afc-4464-9f3f-2527d93e2c50)

### Expected behavior

I would expect the mail app to use all available space.

### Actual behavior

Only part of the browser window is used.

### Mail app version

4.0.2

### Nextcloud version

30.0.1

### Mailserver or service

IMAP

### Operating system

Linux

### PHP engine version

PHP 8.3

### Nextcloud memory caching

memcache.local

### Web server

Apache (supported)

### Database

PostgreSQL

**Comment by jpschewe** [comment]
I figured this out. I had a misconfiguration in my reverse proxy server that prevented the javascript that resizes the window from loading.

**Comment by ojpav** [comment]
i ve just realised i am only having the same issue when accessing the site through Nginx Proxy Manager can you let me know how you fixed this.

**Comment by silferas** [comment]
@jpschewe I also encountered the same issue while using Nginx Proxy Manager and would appreciate your insights on how you managed to resolve it.

**Comment by jpschewe** [comment]
I'm using haproxy, the configuration parameters I needed to make sure to set

- option forwardfor
- http-request add-header X-Forwarded-Proto https if { ssl_fc }
- http-request set-header X-Forwarded-Port %[dst_port]
- http-request add-header X-Forwarded-Host MY_SERVER

The last one is a by-product of how I'm doing my proxying. You probably don't need that last one. You'll watch to watch the traffic going to the backend and make sure that the frontend server name is passed back in headers.
