### ISSUE TITLE
Unable to sync calendar, data migration google.

### ISSUE THREAD

**Issue by Welved** [nextcloud/mail#10315]
### Steps to reproduce

1. Do a Google Drive data migration.
2. Click the radio button to sync calendar
3. Get met with a error 500

### Expected behavior

Clicky clicky radio button, sync calendar and changes.

### Actual behavior

Failed to register background job: Request failed with status code 500
Details
Nextcloud
Internal Server Error
The server was unable to complete your request.

If this happens again, please send the technical details below to the server administrator.

### Mail app version

n/a

### Nextcloud version

30.0.1

### Mailserver or service

google

### Operating system

Pi4

### PHP engine version

None

### Web server

None

### Database

None

### Additional info

Google Drive syncing doesn't appear to work as well.

**Comment by joshtrichards** [comment]
Not sure what app this is, but it's not this one. :-) I suggest checking your Nextcloud Server log and troubleshooting the underlying hints there regarding the cause of 500 error: https://help.nextcloud.com
