### ISSUE TITLE
Show overlay star only for favorited mails, and action inside 3-dot-menu

### ISSUE THREAD

**Issue by jancborchardt** [nextcloud/mail#1032]
Currently the list shows a favorite icon for every single mail:
![screenshot from 2018-08-14 13-25-55](https://user-images.githubusercontent.com/925062/44089023-98399b3e-9fc5-11e8-9764-f421e6dfc1d3.png)

This becomes crowded very quickly and it’s not easy to distinguish which mails are actually favorited.

Better would be to do it like in Files:
- The overlay icon (yellow) is only there for items which are actually favorited
- Favoriting and unfavoriting happens in the 3-dot menu
![screenshot from 2018-08-14 13-23-57](https://user-images.githubusercontent.com/925062/44089084-c96ff4b4-9fc5-11e8-915e-4ed9444913b2.png)

**Comment by ChristophWurst** [comment]
@skjnldsv do we have any (documented) standard for this? :wink:

**Comment by skjnldsv** [comment]
@ChristophWurst about the menu?
I don't like what @jancborchardt suggest because I feel like we keep adding steps to simple actions (click the menu, click the favorite...) But it's just a matter of adding the favorite entry in the menu and only displaying the favorited entry when on! ;)

**Comment by ChristophWurst** [comment]
No, about

> The overlay icon (yellow) is only there for items which are actually favorited

So that we can hide the inactive stars on desktop at least.

:-1: on moving the action to the menu, it's too important to add another step.

**Comment by skjnldsv** [comment]
@ChristophWurst I don't get your request, you want to just hide it totally by default?
What standard are you looking for?

**Comment by ChristophWurst** [comment]
Sorry. If I understand Jan's issue correctly, it bothers him that the star icon is shown for every message, even the ones that are not flagged. I would suggest to hide the icon on desktop browsers and just show it on hover. Does that make sense?

**Comment by skjnldsv** [comment]
Ah yes it does now! :)
I'll let you debate with Jan for this, but there is no standards, you need to add this manually ;)

**Comment by jancborchardt** [comment]
Sorry about adding steps and such, as you know I’m also not a fan of any unnecessary complexities.

But as said:

> it’s not easy to distinguish which mails are actually favorited.

And this unfortunately makes the entire feature kind of useless in the current form. ;)  And not only on desktop, also on mobile.

We can also talk about this at the conf.

**Comment by ChristophWurst** [comment]
> And this unfortunately makes the entire feature kind of useless in the current form. ;) And not only on desktop, also on mobile.

I disagree here. (For me) it's clearly distinguishable which messages are starred and which aren't.

**Comment by jancborchardt** [comment]
"Works for me" is not a good argument here. ;) That’s because you probably have no vision deficiencies and/or work on the Mail app all the time so you know how things are.

- "Color perception changes across the visual field. It is best in the fovea and declines in the periphery."  https://jov.arvojournals.org/article.aspx?articleid=2193447
- "color vision and form perception are concentrated in the center of the visual field" ref https://en.wikipedia.org/wiki/Field_of_view#Humans_and_animals
- The stars are already hard to distinguish as they are , but then for people with vision issues it becomes impossible:
![mail favorites](https://user-images.githubusercontent.com/925062/48842117-b6f0a600-ed93-11e8-8e43-eca94be6ce7f.png) ![mail favorites monochromatic](https://user-images.githubusercontent.com/925062/48842126-ba842d00-ed93-11e8-871a-5d757d999982.png)

Another useful enhancement could be "show favorite mails on top" #460.

**Comment by ChristophWurst** [comment]
>     * The stars are already hard to distinguish as they are , but then for people with vision issues it becomes impossible

Got it, thanks. Hadn't considered that.

**Comment by jancborchardt** [comment]
> > ```
> > * The stars are already hard to distinguish as they are , but then for people with vision issues it becomes impossible
> > ```
> 
> Got it, thanks. Hadn't considered that.

The pull request for this is at https://github.com/nextcloud/mail/pull/2278 – in there you disagreed again, much to my confusion. Could you check that out again?

**Comment by ChristophWurst** [comment]
Merged :)
