### ISSUE TITLE
t-online imap does not show entries properly in unified inbox

### ISSUE THREAD

**Issue by newhinton** [nextcloud/mail#1033]
### Expected behavior
Unified Inbox shows all Mails once.

### Actual behavior
Unified Inbox shows specific Mails once, and others are missing completely.

The first 10 entries on my t-online imap account are shown twice as seperate entries.
If i scroll down, new entries from web.de are loaded, but none from t-online.de

The normal inbox folder works flawless, except that there is a second inbox, which is not clickable. (The mouseover changes to "not-allowed")
This behavior is consistent over multiple accounts (from t-online).

I could not find a similar bug, is this a configuration-error on my part?

### Mail app

**Mail app version:**
 0.8.3

**Mailserver or service:** (e.g. Outlook, Yahoo, Gmail, Exchange,...)
t-online.de
web.de

**Number of accounts:** (e.g. 1 or 2)
6

**Operating system**: (e.g. Debian 8)
Ubuntu 16.04

**Web server:** (e.g. Apache, Nginx,...)
Apache 2.4

**Database:**
MySQL

**Nextcloud Version:** (see admin page, e.g. 13.0.2)
13.05

**Comment by ChristophWurst** [comment]
> 0.8.3

I'm closing this ticket because it hasn't received any updates in a long time. If this is still relevant, feel free to re-open or file a new ticket.

Thank you.
