### ISSUE TITLE
Allow sending to more than one recipient

### ISSUE THREAD

**Issue by mfnalex** [nextcloud/mail#1039]
### Feature Request

Right now, it is only possible to enter one address each for "To:", "CC" and "BCC". I would like to send a mail to several recipients. I think it is currently not possible.

**Comment by ChristophWurst** [comment]
Messages can be sent to multiple recipients already. If not, there's a bug :wink:

**Comment by mfnalex** [comment]
How? I tried it with commas and it did not seem to work. When sending only one message, it is working.

**Comment by ChristophWurst** [comment]
Please report this as a bug (with the corresponding issue template). Without a proper report it's *very* hard to tell what's going on on your setup.
