### ISSUE TITLE
Always: "Auto detect failed. Please use manual mode."

### ISSUE THREAD

**Issue by matiasdelellis** [nextcloud/mail#104]
### Steps to reproduce
1. Install mail apps.
2. Try to configure a account. 
### Expected behaviour

 Setting the mail account..
### Actual behaviour

Always return a message: "Auto detect failed. Please use manual mode." 
### Mail app

**Mail app version:** 0.6 from git

**Mailserver or service:** Outlook, Yahoo, and Gmail... etc..

**Transport security - IMAP:** None, especial configured. Fail autodetect.

**Transport security - SMTP:** None, especial configured. Fail autodetect.

**Number of accounts:** Zero..

**Mail app version build date:** From git now.
### Server configuration

**Operating system**: Fedora 24 kernel 4.7.2

**Web server:** Apache

**Database:** Mariadb 10.1

*_PHP version: *_ 5.6.25

**Version:** 9.1

**Updated from an older version or fresh install:** Update since 8.1

**List of activated apps:**

```
Enabled:
  - audioplayer: 1.2.2
  - calendar: 1.4.0
  - comments: 0.3.0
  - contacts: 1.4.0.0
  - dav: 0.2.5
  - federatedfilesharing: 0.3.0
  - federation: 0.1.0
  - files: 1.5.1
  - files_external: 0.6.0
  - files_sharing: 0.10.0
  - files_trashbin: 0.9.0
  - files_versions: 1.3.0
  - files_videoplayer: 0.9.8
  - gallery: 15.0.0
  - logreader: 1.1.5
  - mail: 0.6.0
  - notifications: 0.3.0
  - quicknotes: 0.1.1
  - richdocuments: 1.1.4
  - systemtags: 0.3.0
  - templateeditor: 0.1
Disabled:
  - activity
  - encryption
  - external
  - files_antivirus
  - files_pdfviewer
  - files_texteditor
  - firstrunwizard
  - provisioning_api
  - tasks
  - updatenotification
  - user_external
  - user_ldap

```

**The content of config/config.php:**

<details>

```
{
    "system": {
        "instanceid": "ocf419unlr9b",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "delellis.com.ar",
            "localhost",
            "owncloud-pc.local"
        ],
        "datadirectory": "\/var\/lib\/owncloud\/data",
        "overwrite.cli.url": "https:\/\/delellis.com.ar",
        "htaccess.RewriteBase": "\/",
        "dbtype": "mysql",
        "version": "9.1.0.15",
        "dbname": "owncloud",
        "dbhost": "127.0.0.1",
        "dbtableprefix": "oc_",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "logtimezone": "UTC",
        "installed": true,
        "theme": "example2",
        "default_language": "es",
        "appstoreenabled": true,
        "appstoreurl": "https:\/\/api.owncloud.com\/v1",
        "appstore.experimental.enabled": true,
        "memcache.local": "\\OC\\Memcache\\APCu",
        "app.mail.server-side-cache.enabled": true,
        "app.mail.smtp.timeout": 20,
        "asset-pipeline.enabled": false,
        "assetdirectory": "\/var\/www\/html\/owncloud",
        "maintenance": false,
        "loglevel": 2,
        "mail_smtpmode": "php"
    },
    "apps": {
        "activity": {
            "enabled": "no",
            "installed_version": "2.2.1",
            "types": "filesystem"
        },
        "audioplayer": {
            "enabled": "yes",
            "installed_version": "1.2.2",
            "ocsid": "174738",
            "signed": "true",
            "types": ""
        },
        "backgroundjob": {
            "lastjob": "87"
        },
        "calendar": {
            "enabled": "yes",
            "installed_version": "1.4.0",
            "ocsid": "168707",
            "signed": "true",
            "types": ""
        },
        "comments": {
            "enabled": "yes",
            "installed_version": "0.3.0",
            "types": "logging"
        },
        "contacts": {
            "enabled": "yes",
            "installed_version": "1.4.0.0",
            "ocsid": "168708",
            "types": ""
        },
        "core": {
            "OC_Channel": "stable",
            "backgroundjobs_mode": "cron",
            "incoming_server2server_share_enabled": "yes",
            "installedat": "1461934033.7049",
            "lastcron": "1474545605",
            "lastupdateResult": "[]",
            "lastupdatedat": "0",
            "oc.integritycheck.checker": "[]",
            "outgoing_server2server_share_enabled": "yes",
            "public_files": "files_sharing\/public.php",
            "public_richdocuments": "richdocuments\/public.php",
            "public_webdav": "dav\/appinfo\/v1\/publicwebdav.php",
            "remote_caldav": "dav\/appinfo\/v1\/caldav.php",
            "remote_calendar": "dav\/appinfo\/v1\/caldav.php",
            "remote_carddav": "dav\/appinfo\/v1\/carddav.php",
            "remote_contacts": "dav\/appinfo\/v1\/carddav.php",
            "remote_dav": "dav\/appinfo\/v2\/remote.php",
            "remote_files": "dav\/appinfo\/v1\/webdav.php",
            "remote_webdav": "dav\/appinfo\/v1\/webdav.php",
            "repairlegacystoragesdone": "yes",
            "shareapi_allow_group_sharing": "no",
            "shareapi_allow_mail_notification": "yes"
        },
        "dav": {
            "enabled": "yes",
            "installed_version": "0.2.5",
            "types": "filesystem"
        },
        "federatedfilesharing": {
            "enabled": "yes",
            "installed_version": "0.3.0",
            "types": ""
        },
        "federation": {
            "autoAddServers": "0",
            "enabled": "yes",
            "installed_version": "0.1.0",
            "types": "authentication"
        },
        "files": {
            "cronjob_scan_files": "500",
            "enabled": "yes",
            "installed_version": "1.5.1",
            "types": "filesystem"
        },
        "files_external": {
            "enabled": "yes",
            "installed_version": "0.6.0",
            "ocsid": "166048",
            "types": "filesystem"
        },
        "files_pdfviewer": {
            "enabled": "no",
            "installed_version": "0.8.1",
            "ocsid": "166049",
            "types": ""
        },
        "files_sharing": {
            "enabled": "yes",
            "incoming_server2server_share_enabled": "yes",
            "installed_version": "0.10.0",
            "outgoing_server2server_share_enabled": "yes",
            "types": "filesystem"
        },
        "files_texteditor": {
            "enabled": "no",
            "installed_version": "2.1",
            "ocsid": "166051",
            "types": ""
        },
        "files_trashbin": {
            "enabled": "yes",
            "installed_version": "0.9.0",
            "types": "filesystem"
        },
        "files_versions": {
            "enabled": "yes",
            "installed_version": "1.3.0",
            "types": "filesystem"
        },
        "files_videoplayer": {
            "enabled": "yes",
            "installed_version": "0.9.8",
            "types": ""
        },
        "firstrunwizard": {
            "enabled": "no",
            "installed_version": "1.1",
            "ocsid": "166055",
            "types": ""
        },
        "gallery": {
            "enabled": "yes",
            "installed_version": "15.0.0",
            "types": ""
        },
        "logreader": {
            "enabled": "yes",
            "installed_version": "1.1.5",
            "levels": "11111",
            "ocsid": "170871",
            "types": ""
        },
        "mail": {
            "enabled": "yes",
            "installed_version": "0.6.0",
            "ocsid": "169914",
            "types": ""
        },
        "matias": {
            "richdocuments": "save_path"
        },
        "music": {
            "enabled": "no",
            "installed_version": "0.3.11",
            "ocsid": "164319",
            "types": "filesystem"
        },
        "notifications": {
            "enabled": "yes",
            "installed_version": "0.3.0",
            "types": "logging"
        },
        "ownnotes": {
            "enabled": "no",
            "installed_version": "0.0.2",
            "types": ""
        },
        "provisioning_api": {
            "enabled": "no",
            "installed_version": "0.4.1",
            "types": "prevent_group_restriction"
        },
        "quicknotes": {
            "enabled": "yes",
            "installed_version": "0.1.1",
            "ocsid": "174716",
            "types": ""
        },
        "richdocuments": {
            "enabled": "yes",
            "installed_version": "1.1.4",
            "ocsid": "174727",
            "types": "",
            "wopi_url": "https:\/\/delellis.com.ar"
        },
        "serverinfo": {
            "enabled": "no",
            "installed_version": "1.1.1",
            "types": ""
        },
        "sketch": {
            "enabled": "no",
            "installed_version": "0.1.2",
            "ocsid": "174146",
            "types": ""
        },
        "systemtags": {
            "enabled": "yes",
            "installed_version": "0.3.0",
            "types": "logging"
        },
        "tasks": {
            "enabled": "no",
            "installed_version": "0.9.3",
            "ocsid": "164356",
            "signed": "true",
            "types": ""
        },
        "templateeditor": {
            "enabled": "yes",
            "installed_version": "0.1",
            "types": ""
        },
        "updatenotification": {
            "enabled": "no",
            "installed_version": "0.1.0",
            "types": ""
        }
    }
}
```

</details>
#### Client configuration

**Browser:** Firefox 49

**Operating system:**
##### Web server error log

```
Any relevant message.
```
##### Server log (data/nextcloud.log)

<details>

```
Any relevant info..
```

</details>
##### Horde IMAP log (data/horde_imap.log)

<details>

```
Insert your horde IMAP log here, see https://github.com/nextcloud/mail#debug-mode
```

</details>
##### Horde SMTP log (data/horde_smtp.log)

<details>

```
Insert your horde SMTP log here, see https://github.com/nextcloud/mail#debug-mode
```

</details>
##### Browser log

<details>

```
Insert your browser log here, this could for example include:

a) The javascript console log: Any message
b) The network log: Any relevant
c) ...
```

</details>

**Comment by ChristophWurst** [comment]
> Web server error log
> 
> Any relevant message.

Enable debug logging and try again, you'll see a lot of useful information in the nextcloud.log file :-)

**Comment by matiasdelellis** [comment]
Ok.. Change config.php to:
 * 'debug' = true,
 * 'loglevel' => 0,
And then try to configure an account:

`{"reqId":"V@UZ@uoTHrYnQCHjCi4ANgAAAAI","remoteAddr":"201.216.201.129","app":"mail","message":"setting up auto detected account","level":1,"time":"2016-09-23T12:03:07+00:00","method":"POST","url":"\/apps\/mail\/accounts","user":"matias"}
{"reqId":"V@UZ@uoTHrYnQCHjCi4ANgAAAAI","remoteAddr":"201.216.201.129","app":"mail","message":"IsbDb: querying <hotmail.com>","level":0,"time":"2016-09-23T12:03:07+00:00","method":"POST","url":"\/apps\/mail\/accounts","user":"matias"}
{"reqId":"V@UZ@uoTHrYnQCHjCi4ANgAAAAI","remoteAddr":"201.216.201.129","app":"mail","message":"IsbDb: querying <hotmail.com> via <https:\/\/autoconfig.hotmail.com\/mail\/config-v1.1.xml>","level":0,"time":"2016-09-23T12:03:07+00:00","method":"POST","url":"\/apps\/mail\/accounts","user":"matias"}
{"reqId":"V@UZ@uoTHrYnQCHjCi4ANgAAAAI","remoteAddr":"201.216.201.129","app":"PHP","message":"file_get_contents(): php_network_getaddresses: getaddrinfo failed: No address associated with hostname at \/var\/www\/html\/owncloud\/apps\/mail\/lib\/service\/autoconfig\/ispdb.php#59","level":0,"time":"2016-09-23T12:03:07+00:00","method":"POST","url":"\/apps\/mail\/accounts","user":"matias"}
{"reqId":"V@UZ@uoTHrYnQCHjCi4ANgAAAAI","remoteAddr":"201.216.201.129","app":"PHP","message":"file_get_contents(https:\/\/autoconfig.hotmail.com\/mail\/config-v1.1.xml): failed to open stream: php_network_getaddresses: getaddrinfo failed: No address associated with hostname at \/var\/www\/html\/owncloud\/apps\/mail\/lib\/service\/autoconfig\/ispdb.php#59","level":0,"time":"2016-09-23T12:03:07+00:00","method":"POST","url":"\/apps\/mail\/accounts","user":"matias"}
{"reqId":"V@UZ@uoTHrYnQCHjCi4ANgAAAAI","remoteAddr":"201.216.201.129","app":"mail","message":"IsbDb: <https:\/\/autoconfig.hotmail.com\/mail\/config-v1.1.xml> request timed out","level":0,"time":"2016-09-23T12:03:07+00:00","method":"POST","url":"\/apps\/mail\/accounts","user":"matias"}
{"reqId":"V@UZ@uoTHrYnQCHjCi4ANgAAAAI","remoteAddr":"201.216.201.129","app":"mail","message":"IsbDb: querying <hotmail.com> via <https:\/\/hotmail.com\/.well-known\/autoconfig\/mail\/config-v1.1.xml>","level":0,"time":"2016-09-23T12:03:07+00:00","method":"POST","url":"\/apps\/mail\/accounts","user":"matias"}
{"reqId":"V@UZ@uoTHrYnQCHjCi4ANgAAAAI","remoteAddr":"201.216.201.129","app":"PHP","message":"file_get_contents(): php_network_getaddresses: getaddrinfo failed: No address associated with hostname at \/var\/www\/html\/owncloud\/apps\/mail\/lib\/service\/autoconfig\/ispdb.php#59","level":0,"time":"2016-09-23T12:03:07+00:00","method":"POST","url":"\/apps\/mail\/accounts","user":"matias"}
{"reqId":"V@UZ@uoTHrYnQCHjCi4ANgAAAAI","remoteAddr":"201.216.201.129","app":"PHP","message":"file_get_contents(https:\/\/hotmail.com\/.well-known\/autoconfig\/mail\/config-v1.1.xml): failed to open stream: php_network_getaddresses: getaddrinfo failed: No address associated with hostname at \/var\/www\/html\/owncloud\/apps\/mail\/lib\/service\/autoconfig\/ispdb.php#59","level":0,"time":"2016-09-23T12:03:07+00:00","method":"POST","url":"\/apps\/mail\/accounts","user":"matias"}
{"reqId":"V@UZ@uoTHrYnQCHjCi4ANgAAAAI","remoteAddr":"201.216.201.129","app":"mail","message":"IsbDb: <https:\/\/hotmail.com\/.well-known\/autoconfig\/mail\/config-v1.1.xml> request timed out","level":0,"time":"2016-09-23T12:03:07+00:00","method":"POST","url":"\/apps\/mail\/accounts","user":"matias"}
{"reqId":"V@UZ@uoTHrYnQCHjCi4ANgAAAAI","remoteAddr":"201.216.201.129","app":"mail","message":"IsbDb: querying <hotmail.com> via <https:\/\/autoconfig.thunderbird.net\/v1.1\/hotmail.com>","level":0,"time":"2016-09-23T12:03:07+00:00","method":"POST","url":"\/apps\/mail\/accounts","user":"matias"}
{"reqId":"V@UZ@uoTHrYnQCHjCi4ANgAAAAI","remoteAddr":"201.216.201.129","app":"PHP","message":"file_get_contents(): php_network_getaddresses: getaddrinfo failed: No address associated with hostname at \/var\/www\/html\/owncloud\/apps\/mail\/lib\/service\/autoconfig\/ispdb.php#59","level":0,"time":"2016-09-23T12:03:07+00:00","method":"POST","url":"\/apps\/mail\/accounts","user":"matias"}
{"reqId":"V@UZ@uoTHrYnQCHjCi4ANgAAAAI","remoteAddr":"201.216.201.129","app":"PHP","message":"file_get_contents(https:\/\/autoconfig.thunderbird.net\/v1.1\/hotmail.com): failed to open stream: php_network_getaddresses: getaddrinfo failed: No address associated with hostname at \/var\/www\/html\/owncloud\/apps\/mail\/lib\/service\/autoconfig\/ispdb.php#59","level":0,"time":"2016-09-23T12:03:07+00:00","method":"POST","url":"\/apps\/mail\/accounts","user":"matias"}
{"reqId":"V@UZ@uoTHrYnQCHjCi4ANgAAAAI","remoteAddr":"201.216.201.129","app":"mail","message":"IsbDb: <https:\/\/autoconfig.thunderbird.net\/v1.1\/hotmail.com> request timed out","level":0,"time":"2016-09-23T12:03:07+00:00","method":"POST","url":"\/apps\/mail\/accounts","user":"matias"}
{"reqId":"V@UZ@uoTHrYnQCHjCi4ANgAAAAI","remoteAddr":"201.216.201.129","app":"mail","message":"IsbDb: querying <mx2.hotmail.com>","level":0,"time":"2016-09-23T12:03:07+00:00","method":"POST","url":"\/apps\/mail\/accounts","user":"matias"}
{"reqId":"V@UZ@uoTHrYnQCHjCi4ANgAAAAI","remoteAddr":"201.216.201.129","app":"mail","message":"IsbDb: querying <mx2.hotmail.com> via <https:\/\/autoconfig.mx2.hotmail.com\/mail\/config-v1.1.xml>","level":0,"time":"2016-09-23T12:03:07+00:00","method":"POST","url":"\/apps\/mail\/accounts","user":"matias"}
{"reqId":"V@UZ@uoTHrYnQCHjCi4ANgAAAAI","remoteAddr":"201.216.201.129","app":"PHP","message":"file_get_contents(): php_network_getaddresses: getaddrinfo failed: No address associated with hostname at \/var\/www\/html\/owncloud\/apps\/mail\/lib\/service\/autoconfig\/ispdb.php#59","level":0,"time":"2016-09-23T12:03:07+00:00","method":"POST","url":"\/apps\/mail\/accounts","user":"matias"}
{"reqId":"V@UZ@uoTHrYnQCHjCi4ANgAAAAI","remoteAddr":"201.216.201.129","app":"PHP","message":"file_get_contents(https:\/\/autoconfig.mx2.hotmail.com\/mail\/config-v1.1.xml): failed to open stream: php_network_getaddresses: getaddrinfo failed: No address associated with hostname at \/var\/www\/html\/owncloud\/apps\/mail\/lib\/service\/autoconfig\/ispdb.php#59","level":0,"time":"2016-09-23T12:03:07+00:00","method":"POST","url":"\/apps\/mail\/accounts","user":"matias"}
{"reqId":"V@UZ@uoTHrYnQCHjCi4ANgAAAAI","remoteAddr":"201.216.201.129","app":"mail","message":"IsbDb: <https:\/\/autoconfig.mx2.hotmail.com\/mail\/config-v1.1.xml> request timed out","level":0,"time":"2016-09-23T12:03:07+00:00","method":"POST","url":"\/apps\/mail\/accounts","user":"matias"}
{"reqId":"V@UZ@uoTHrYnQCHjCi4ANgAAAAI","remoteAddr":"201.216.201.129","app":"mail","message":"IsbDb: querying <mx2.hotmail.com> via <https:\/\/mx2.hotmail.com\/.well-known\/autoconfig\/mail\/config-v1.1.xml>","level":0,"time":"2016-09-23T12:03:07+00:00","method":"POST","url":"\/apps\/mail\/accounts","user":"matias"}
{"reqId":"V@UZ@uoTHrYnQCHjCi4ANgAAAAI","remoteAddr":"201.216.201.129","app":"PHP","message":"file_get_contents(): php_network_getaddresses: getaddrinfo failed: No address associated with hostname at \/var\/www\/html\/owncloud\/apps\/mail\/lib\/service\/autoconfig\/ispdb.php#59","level":0,"time":"2016-09-23T12:03:07+00:00","method":"POST","url":"\/apps\/mail\/accounts","user":"matias"}
{"reqId":"V@UZ@uoTHrYnQCHjCi4ANgAAAAI","remoteAddr":"201.216.201.129","app":"PHP","message":"file_get_contents(https:\/\/mx2.hotmail.com\/.well-known\/autoconfig\/mail\/config-v1.1.xml): failed to open stream: php_network_getaddresses: getaddrinfo failed: No address associated with hostname at \/var\/www\/html\/owncloud\/apps\/mail\/lib\/service\/autoconfig\/ispdb.php#59","level":0,"time":"2016-09-23T12:03:07+00:00","method":"POST","url":"\/apps\/mail\/accounts","user":"matias"}
{"reqId":"V@UZ@uoTHrYnQCHjCi4ANgAAAAI","remoteAddr":"201.216.201.129","app":"mail","message":"IsbDb: <https:\/\/mx2.hotmail.com\/.well-known\/autoconfig\/mail\/config-v1.1.xml> request timed out","level":0,"time":"2016-09-23T12:03:07+00:00","method":"POST","url":"\/apps\/mail\/accounts","user":"matias"}
{"reqId":"V@UZ@uoTHrYnQCHjCi4ANgAAAAI","remoteAddr":"201.216.201.129","app":"mail","message":"IsbDb: querying <mx2.hotmail.com> via <https:\/\/autoconfig.thunderbird.net\/v1.1\/mx2.hotmail.com>","level":0,"time":"2016-09-23T12:03:07+00:00","method":"POST","url":"\/apps\/mail\/accounts","user":"matias"}
{"reqId":"V@UZ@uoTHrYnQCHjCi4ANgAAAAI","remoteAddr":"201.216.201.129","app":"PHP","message":"file_get_contents(): php_network_getaddresses: getaddrinfo failed: No address associated with hostname at \/var\/www\/html\/owncloud\/apps\/mail\/lib\/service\/autoconfig\/ispdb.php#59","level":0,"time":"2016-09-23T12:03:07+00:00","method":"POST","url":"\/apps\/mail\/accounts","user":"matias"}
{"reqId":"V@UZ@uoTHrYnQCHjCi4ANgAAAAI","remoteAddr":"201.216.201.129","app":"PHP","message":"file_get_contents(https:\/\/autoconfig.thunderbird.net\/v1.1\/mx2.hotmail.com): failed to open stream: php_network_getaddresses: getaddrinfo failed: No address associated with hostname at \/var\/www\/html\/owncloud\/apps\/mail\/lib\/service\/autoconfig\/ispdb.php#59","level":0,"time":"2016-09-23T12:03:07+00:00","method":"POST","url":"\/apps\/mail\/accounts","user":"matias"}
{"reqId":"V@UZ@uoTHrYnQCHjCi4ANgAAAAI","remoteAddr":"201.216.201.129","app":"mail","message":"IsbDb: <https:\/\/autoconfig.thunderbird.net\/v1.1\/mx2.hotmail.com> request timed out","level":0,"time":"2016-09-23T12:03:07+00:00","method":"POST","url":"\/apps\/mail\/accounts","user":"matias"}
{"reqId":"V@UZ@uoTHrYnQCHjCi4ANgAAAAI","remoteAddr":"201.216.201.129","app":"mail","message":"IsbDb: querying <hotmail.com>","level":0,"time":"2016-09-23T12:03:07+00:00","method":"POST","url":"\/apps\/mail\/accounts","user":"matias"}
{"reqId":"V@UZ@uoTHrYnQCHjCi4ANgAAAAI","remoteAddr":"201.216.201.129","app":"mail","message":"IsbDb: querying <hotmail.com> via <https:\/\/autoconfig.hotmail.com\/mail\/config-v1.1.xml>","level":0,"time":"2016-09-23T12:03:07+00:00","method":"POST","url":"\/apps\/mail\/accounts","user":"matias"}
{"reqId":"V@UZ@uoTHrYnQCHjCi4ANgAAAAI","remoteAddr":"201.216.201.129","app":"PHP","message":"file_get_contents(): php_network_getaddresses: getaddrinfo failed: No address associated with hostname at \/var\/www\/html\/owncloud\/apps\/mail\/lib\/service\/autoconfig\/ispdb.php#59","level":0,"time":"2016-09-23T12:03:07+00:00","method":"POST","url":"\/apps\/mail\/accounts","user":"matias"}
{"reqId":"V@UZ@uoTHrYnQCHjCi4ANgAAAAI","remoteAddr":"201.216.201.129","app":"PHP","message":"file_get_contents(https:\/\/autoconfig.hotmail.com\/mail\/config-v1.1.xml): failed to open stream: php_network_getaddresses: getaddrinfo failed: No address associated with hostname at \/var\/www\/html\/owncloud\/apps\/mail\/lib\/service\/autoconfig\/ispdb.php#59","level":0,"time":"2016-09-23T12:03:07+00:00","method":"POST","url":"\/apps\/mail\/accounts","user":"matias"}
{"reqId":"V@UZ@uoTHrYnQCHjCi4ANgAAAAI","remoteAddr":"201.216.201.129","app":"mail","message":"IsbDb: <https:\/\/autoconfig.hotmail.com\/mail\/config-v1.1.xml> request timed out","level":0,"time":"2016-09-23T12:03:07+00:00","method":"POST","url":"\/apps\/mail\/accounts","user":"matias"}
{"reqId":"V@UZ@uoTHrYnQCHjCi4ANgAAAAI","remoteAddr":"201.216.201.129","app":"mail","message":"IsbDb: querying <hotmail.com> via <https:\/\/hotmail.com\/.well-known\/autoconfig\/mail\/config-v1.1.xml>","level":0,"time":"2016-09-23T12:03:07+00:00","method":"POST","url":"\/apps\/mail\/accounts","user":"matias"}
{"reqId":"V@UZ@uoTHrYnQCHjCi4ANgAAAAI","remoteAddr":"201.216.201.129","app":"PHP","message":"file_get_contents(): php_network_getaddresses: getaddrinfo failed: No address associated with hostname at \/var\/www\/html\/owncloud\/apps\/mail\/lib\/service\/autoconfig\/ispdb.php#59","level":0,"time":"2016-09-23T12:03:07+00:00","method":"POST","url":"\/apps\/mail\/accounts","user":"matias"}
{"reqId":"V@UZ@uoTHrYnQCHjCi4ANgAAAAI","remoteAddr":"201.216.201.129","app":"PHP","message":"file_get_contents(https:\/\/hotmail.com\/.well-known\/autoconfig\/mail\/config-v1.1.xml): failed to open stream: php_network_getaddresses: getaddrinfo failed: No address associated with hostname at \/var\/www\/html\/owncloud\/apps\/mail\/lib\/service\/autoconfig\/ispdb.php#59","level":0,"time":"2016-09-23T12:03:07+00:00","method":"POST","url":"\/apps\/mail\/accounts","user":"matias"}
{"reqId":"V@UZ@uoTHrYnQCHjCi4ANgAAAAI","remoteAddr":"201.216.201.129","app":"mail","message":"IsbDb: <https:\/\/hotmail.com\/.well-known\/autoconfig\/mail\/config-v1.1.xml> request timed out","level":0,"time":"2016-09-23T12:03:07+00:00","method":"POST","url":"\/apps\/mail\/accounts","user":"matias"}
{"reqId":"V@UZ@uoTHrYnQCHjCi4ANgAAAAI","remoteAddr":"201.216.201.129","app":"mail","message":"IsbDb: querying <hotmail.com> via <https:\/\/autoconfig.thunderbird.net\/v1.1\/hotmail.com>","level":0,"time":"2016-09-23T12:03:07+00:00","method":"POST","url":"\/apps\/mail\/accounts","user":"matias"}
{"reqId":"V@UZ@uoTHrYnQCHjCi4ANgAAAAI","remoteAddr":"201.216.201.129","app":"PHP","message":"file_get_contents(): php_network_getaddresses: getaddrinfo failed: No address associated with hostname at \/var\/www\/html\/owncloud\/apps\/mail\/lib\/service\/autoconfig\/ispdb.php#59","level":0,"time":"2016-09-23T12:03:07+00:00","method":"POST","url":"\/apps\/mail\/accounts","user":"matias"}
{"reqId":"V@UZ@uoTHrYnQCHjCi4ANgAAAAI","remoteAddr":"201.216.201.129","app":"PHP","message":"file_get_contents(https:\/\/autoconfig.thunderbird.net\/v1.1\/hotmail.com): failed to open stream: php_network_getaddresses: getaddrinfo failed: No address associated with hostname at \/var\/www\/html\/owncloud\/apps\/mail\/lib\/service\/autoconfig\/ispdb.php#59","level":0,"time":"2016-09-23T12:03:07+00:00","method":"POST","url":"\/apps\/mail\/accounts","user":"matias"}
{"reqId":"V@UZ@uoTHrYnQCHjCi4ANgAAAAI","remoteAddr":"201.216.201.129","app":"mail","message":"IsbDb: <https:\/\/autoconfig.thunderbird.net\/v1.1\/hotmail.com> request timed out","level":0,"time":"2016-09-23T12:03:07+00:00","method":"POST","url":"\/apps\/mail\/accounts","user":"matias"}
{"reqId":"V@UZ@uoTHrYnQCHjCi4ANgAAAAI","remoteAddr":"201.216.201.129","app":"mail","message":"found 4 MX records for host <hotmail.com>","level":0,"time":"2016-09-23T12:03:07+00:00","method":"POST","url":"\/apps\/mail\/accounts","user":"matias"}
{"reqId":"V@UZ@uoTHrYnQCHjCi4ANgAAAAI","remoteAddr":"201.216.201.129","app":"mail","message":"Auto detect failed","level":1,"time":"2016-09-23T12:03:07+00:00","method":"POST","url":"\/apps\/mail\/accounts","user":"matias"}`

**Comment by matiasdelellis** [comment]
ps: Before drop mail app from git and install the nightly version.
Also, reset the app as suggested by the readme and I notice that missing to report drop the table "oc_mail_aliases"

**Comment by ChristophWurst** [comment]
> Also, reset the app as suggested by the readme and I notice that missing to report drop the table "oc_mail_aliases"

Good catch! Could you please fix that and submit a PR? Thanks :-)

**Comment by matiasdelellis** [comment]
Of course.. :wink:

**Comment by matiasdelellis** [comment]
Well,
Migrating to nextcloud 10 (was still in owncloud 9.1) works properly..  :confused:

**Comment by Gomez** [comment]
I just started get release version 0.6 out and tested the autoconfig:

Unfortunately I cant add my web.de mail account (it works in manual config):

With correct password:
```
------------------------------
>> Sun, 09 Oct 2016 14:50:10 +0000
>> Connection to: imap://imap.web.de:993/
>> Server connection took 0.0873 seconds.
S: * OK [CAPABILITY IMAP4rev1 CHILDREN ENABLE ID IDLE LIST-EXTENDED LIST-STATUS LITERAL+ MOVE NAMESPACE QUOTA SASL-IR SORT SPECIAL-USE THREAD=ORDEREDSUBJECT UIDPLUS UNSELECT WITHIN AUTH=LOGIN AUTH=PLAIN] IMAP server ready H miweb111 2651323638 IMAP-0MTLMM-1bTdBH3nBH-00SFx2
C: 1 AUTHENTICATE PLAIN [INITIAL CLIENT RESPONSE (username: xxxxx)]
S: 1 OK AUTHENTICATE completed
>> Command 1 took 0.0537 seconds.
C: 2 CAPABILITY
S: * CAPABILITY IMAP4rev1 CHILDREN ENABLE ID IDLE LIST-EXTENDED LIST-STATUS LITERAL+ MOVE NAMESPACE QUOTA SASL-IR SORT SPECIAL-USE THREAD=ORDEREDSUBJECT UIDPLUS UNSELECT WITHIN APPENDLIMIT=27962027
S: 2 OK CAPABILITY completed
>> Command 2 took 0.0319 seconds.

==> data/owncloud.log <==
{"reqId":"JmrxVtToZP1ZkASEQMHI","remoteAddr":"::1","app":"mail","message":"Creating account failed: Server denied authentication.","level":3,"time":"2016-10-09T14:50:10+00:00","method":"POST","url":"\/core\/index.php\/apps\/mail\/accounts","user":"gomez"}
```
I changed to a wrong password and retried:
```
==> data/horde_imap.log <==
C: 3 LOGOUT
S: * BYE Server logging out
S: 3 OK LOGOUT completed
>> Command 3 took 0.0437 seconds.
------------------------------
>> Sun, 09 Oct 2016 14:50:32 +0000
>> Connection to: imap://imap.web.de:993/
>> Server connection took 0.0841 seconds.
S: * OK [CAPABILITY IMAP4rev1 CHILDREN ENABLE ID IDLE LIST-EXTENDED LIST-STATUS LITERAL+ MOVE NAMESPACE QUOTA SASL-IR SORT SPECIAL-USE THREAD=ORDEREDSUBJECT UIDPLUS UNSELECT WITHIN AUTH=LOGIN AUTH=PLAIN] IMAP server ready H miweb117 2651323638 IMAP-0M8HNO-1axYT93lTe-00vx36
C: 1 AUTHENTICATE PLAIN [INITIAL CLIENT RESPONSE (username: xxxxx)]
S: 1 NO authentication failed
>> Command 1 took 0.0737 seconds.
C: 2 LOGIN gomezr [PASSWORD]
S: 2 NO authentication failed
>> Command 2 took 0.0705 seconds.
------------------------------
```

I am on owncloud 9.1 / php7. Can some1 confirm? I tested the stable-060 branch.

**Comment by Gomez** [comment]
Ref:

**Comment by ChristophWurst** [comment]
I'll take a look tomorrow. If it's easy to fix I'll try to do so and if not we fix it in 0.6.1

**Comment by ChristophWurst** [comment]
Tested with GMail: works (config is found in the mozilla isp db)

**Comment by ChristophWurst** [comment]
Tested with my own provider and custom domain: worked (took a bit though since the parameters had to be *guessed*).

**Comment by ChristophWurst** [comment]
> Unfortunately I cant add my web.de mail account (it works in manual config):

What if they have changed the allowed auth methods and therefore it worked before but doesn't now? We have to adjust, of course, but it's not a bug per se then.

**Comment by ChristophWurst** [comment]
If someone can tell me a specific provider that fails where I can also create an account I can test it for 0.6.1.

**Comment by matiasdelellis** [comment]
> If someone can tell me a specific provider that fails where I can also create an account I can test it for 0.6.1.

Hi @ChristophWurst ,
In my expirence it is not a problem of an specific provider.. Configurations that seems correct, sporadically they stop working. 😞

**Comment by ChristophWurst** [comment]
I'm closing this ticket now due to the lack of activity.
