### ISSUE TITLE
Create Deck Item from Mail

### ISSUE THREAD

**Issue by KernSani** [nextcloud/mail#10422]
### Is your feature request related to a problem? Please describe.

I'm using Nextcloud Deck App a lot to track my tasks. Emails regularly contain "Tasks" to follow up. Right now I have to manually create a card in deck to track those tasks, thus it would be a great enhancement to create the deck card directly from mail.

### Describe the solution you'd like

It is already possible to create tasks or appointments from Mails. A similar function for deck items would be great. By clicking on the 3 dots I would expect an additional menu entry "Create Deck Card". This would open the "create deck card" dialog and auto-populate the card title with the email subject and the description with the email body.

### Describe alternatives you've considered

The only alternative is manual creation of the deck card

**Comment by ChristophWurst** [comment]
Dear @KernSani,
Thank you very much for your request!
This feature has already been requested at https://github.com/nextcloud/mail/issues/5900. I'm closing this ticket as duplicate.
