### ISSUE TITLE
PHP config in composer.json

### ISSUE THREAD

**Issue by pierlon** [nextcloud/mail#1042]
### Question

Seeing that [v0.9.0](https://github.com/nextcloud/mail/releases/tag/v0.9.0) now requires a minimum of PHP 7, shouldn't it be reflected in the [composer.json](https://github.com/nextcloud/mail/blob/master/composer.json) file also?

**Comment by ChristophWurst** [comment]
Hi, @pierlon,

yes, you're right. I forgot to update the file. Would you be interested in fixing this?

**Comment by pierlon** [comment]
Sure :smiley: .
