### ISSUE TITLE
Quota loads indefinitly

### ISSUE THREAD

**Issue by StefInP** [nextcloud/mail#10441]
### Steps to reproduce

1. At the right of the account name, click on '...'

### Expected behavior

The quota value should be displayed

### Actual behavior

![Image](https://github.com/user-attachments/assets/6c32e36a-9df3-4c71-a19f-39cd91d63129)

### Mail app version

4.0.7

### Nextcloud version

30.0.2 (AIO 10.0.0)

### Mailserver or service

OVH, Mailo

### PHP engine version

PHP 8.3

### Web server

Apache (supported)

### Database

PostgreSQL

### Additional info

The  issue appeared after updating from NC29.0.8/Mail 3.7 to NC30.0.2/Mail 4.07

**Comment by ChristophWurst** [comment]
Good catch @StefInP! We noticed this just two days ago. It must be a regression.

**Comment by ChristophWurst** [comment]
Fix is at https://github.com/nextcloud/mail/pull/10446.

Thank you for your report @StefInP!
