### ISSUE TITLE
SMTP connection failed

### ISSUE THREAD

**Issue by Sev6n** [nextcloud/mail#10490]
### Steps to reproduce

1. Use the manual mail-account setup.
2. Enter email account IMAP/SMTP settings (or any for that matter).
3. Attempt to "Connect".

### Expected behavior

Connects the email account

### Actual behavior

Fails with an error: SMTP connection failed, no matter which protocol or type. Does not work.
![Image](https://github.com/user-attachments/assets/0e44febc-e4a6-4c46-89d1-aa58c78a57c4)

### Mail app version

4.0.9

### Nextcloud version

30.0.2

### Mailserver or service

Namecheap cPanel Email Account

### Operating system

Kali Linux

### PHP engine version

None

### Web server

Apache (supported)

### Database

None

**Comment by SebastianKrupinski** [comment]
Hi @Sev6n 

Can you turn on debugging, 

https://docs.nextcloud.com/server/latest/developer_manual/digging_deeper/debugging.html

And perform the connection process again. This should generate a hored_imap.log and horde_smtp.log.

Would need to see the contents, to see the reason.

**Comment by Sev6n** [comment]
> Hi [@Sev6n](https://github.com/Sev6n)
> 
> Can you turn on debugging,
> 
> https://docs.nextcloud.com/server/latest/developer_manual/digging_deeper/debugging.html
> 
> And perform the connection process again. This should generate a hored_imap.log and horde_smtp.log.
> 
> Would need to see the contents, to see the reason.

Okay, debugging has been turned on. Here are the results.

horde_imap.log =
https://pastebin.com/P5LXCkuc

horde_smtp.log =
(empty)

**Comment by SebastianKrupinski** [comment]
> Okay, debugging has been turned on. Here are the results.

It seems to be a authentication failure... due to the mail client connecting to the wrong server.

```
>> Connection to: imap://premium195.web-hosting.com:993/
>> Server connection took 0.3207 seconds.
S: * OK [CAPABILITY IMAP4rev1 SASL-IR LOGIN-REFERRALS ID ENABLE IDLE NAMESPACE LITERAL+ AUTH=PLAIN AUTH=LOGIN] Dovecot ready.
C: 1 AUTHENTICATE PLAIN [INITIAL CLIENT RESPONSE (username: sev6n@outlook.com)]
S: 1 NO [AUTHENTICATIONFAILED] Authentication failed.
>> Command 1 took 1.8535 seconds.
C: 2 LOGIN sev6n@outlook.com [PASSWORD]
>> Slow Command: 5.006 seconds
>> ERROR: read timeout error.
S: 2 NO [AUTHENTICATIONFAILED] Authentication failed.
>> Command 2 took 6.2179 seconds.
```

Client is connecting to "premium195.web-hosting.com"

But the server for "*@outlook.com" should be "imap-mail.outlook.com"

**Comment by Sev6n** [comment]
> > Okay, debugging has been turned on. Here are the results.
> 
> It seems to be a authentication failure... due to the mail client connecting to the wrong server.
> 
> ```
> >> Connection to: imap://premium195.web-hosting.com:993/
> >> Server connection took 0.3207 seconds.
> S: * OK [CAPABILITY IMAP4rev1 SASL-IR LOGIN-REFERRALS ID ENABLE IDLE NAMESPACE LITERAL+ AUTH=PLAIN AUTH=LOGIN] Dovecot ready.
> C: 1 AUTHENTICATE PLAIN [INITIAL CLIENT RESPONSE (username: sev6n@outlook.com)]
> S: 1 NO [AUTHENTICATIONFAILED] Authentication failed.
> >> Command 1 took 1.8535 seconds.
> C: 2 LOGIN sev6n@outlook.com [PASSWORD]
> >> Slow Command: 5.006 seconds
> >> ERROR: read timeout error.
> S: 2 NO [AUTHENTICATIONFAILED] Authentication failed.
> >> Command 2 took 6.2179 seconds.
> ```
> 
> Client is connecting to "premium195.web-hosting.com"
> 
> But the server for "*@outlook.com" should be "imap-mail.outlook.com"

Sorry, I shared the wrong log file. Here is the log file for the email account i'm trying to setup.

horde_imap.log =
https://pastebin.com/grvw1ZwY

**Comment by SebastianKrupinski** [comment]
> Yes, it's the correct log. For some reason, despite there be having a successful connection as you pointed out, Nextcloud mail still returns with a "SMTP connection failed".

If the new error message is "SMTP connection failed" then I will need the horde_smtp.log, not the imap log

**Comment by Sev6n** [comment]
Unfortunately, the horde_smtp.log is empty. Even with debugging mode on and re-attempting the action multiple times.

![Image](https://github.com/user-attachments/assets/dc93b377-1332-4ddc-96eb-773d94e6fafc)

**Comment by Sev6n** [comment]
Okay, I have found the **solution**.

It seems that (atleast for me) the Nextcloud mail app **only accepts mail accounts from the same domain its hosted on.** So, if your Nextcloud instance is hosted on cloud.example.com, you can add an account as long as its tied to the **root domain**. (example.com)
or any subdomain tied to the root domain. (cloud2.example.com)

With the above, I was able to add the email account automatically instead of using the manual mode. It succeeded with no errors.

Case resolved!
