### ISSUE TITLE
Bug after upgrade to 4.1.0 - BadFunctionCallException mentionsMe is not a valid attribute

### ISSUE THREAD

**Issue by roko74** [nextcloud/mail#10519]
### Steps to reproduce

1. Use Nextcloud Hub 9 (30.0.4)
2. Have two mail accounts in use in Mail App below version 4.1.0
3. Upgrade app to version 4.1.0
4. Try to use the new mail app.

### Expected behavior

I expect to see my mails from both accounts.

### Actual behavior

I get the message "Could not open mailbox." and I've a lot of error entries inside the log:
mail: "BadFunctionCallException mentionsMe is not a valid attribute"

### Mail app version

4.1.0

### Nextcloud version

30.0.4

### Mailserver or service

Gmail, GMX

### Operating system

Raspberry Pi OS Bookworm with Apache2 - all updates installed.

### PHP engine version

PHP 8.3

### Web server

Apache (supported)

### Database

PostgreSQL

**Comment by nigelharpur** [comment]
I have the exact same issue since the last update too - same version of the app and NC - runniing on Ubuntu Server 22.04 and Nginx.
The error message accumulates/repeats on it's own, I gues as the app attempts to open my two mailboxes.

**Comment by SebastianKrupinski** [comment]
Hi, could you please post the full error from the nextcloud.log?

**Comment by roko74** [comment]
Here the log from my nextcloud instance:
[nextcloud.log](https://github.com/user-attachments/files/18203007/nextcloud.log)

**Comment by SebastianKrupinski** [comment]
Odd, looks like its related to a database column, "mentions_me" in the "mail_messages" table, can you confirm this column exists?

**Comment by otvoreno** [comment]
same bug for me.

every entry for column "mentions_me" in table "oc_mail_messages" seems to be 0. the column exists. 

Nextcloud Hub 9 (30.0.4)
PHP 8.2.26
Mail-App 4.1.0

**Comment by roko74** [comment]
Here an excerpt of my table 'oc_mail_messages' - all datasets have the column "mentions_me" with the value "false":
![Image](https://github.com/user-attachments/assets/4d5a8d90-c1aa-4a72-a86f-8c71f74c5391)

**Comment by otvoreno** [comment]
> same bug for me.
> 
> every entry for column "mentions_me" in table "oc_mail_messages" seems to be 0. the column exists.
> 
> Nextcloud Hub 9 (30.0.4) PHP 8.2.26 Mail-App 4.1.0 Mariadb 15.1 Debian 12

```

MariaDB [nextcloud]> select distinct mentions_me from oc_mail_messages;
+-------------+
| mentions_me |
+-------------+
|           0 |
+-------------+
1 row in set (0,017 sec)

```

**Comment by SebastianKrupinski** [comment]
okay, if the column exist then that means either the upgraded code is missing or its a opcache issue.

Restart php (php-fpm on most systems) this should recreate the opcache. If the error still exists can you confirm that the following line exists in your code.

https://github.com/nextcloud/mail/blob/a959a81e4a0f6db51a2b1637824e6ceba5c5ff2f/lib/Db/Message.php#L71

And

https://github.com/nextcloud/mail/blob/a959a81e4a0f6db51a2b1637824e6ceba5c5ff2f/lib/Db/Message.php#L114

**Comment by otvoreno** [comment]
> okay, if the column exist then that means either the upgraded code is missing or its a opcache issue.
> 
> Restart php (php-fpm on most systems) this should recreate the opcache. If the error still exists can you confirm that the following line exists in your code.
> 
> [mail/lib/Db/Message.php](https://github.com/nextcloud/mail/blob/a959a81e4a0f6db51a2b1637824e6ceba5c5ff2f/lib/Db/Message.php#L71)
> 
> Line 71 in [a959a81](/nextcloud/mail/commit/a959a81e4a0f6db51a2b1637824e6ceba5c5ff2f)
>   * @method bool getMentionsMe() 
> 
> And
> 
> [mail/lib/Db/Message.php](https://github.com/nextcloud/mail/blob/a959a81e4a0f6db51a2b1637824e6ceba5c5ff2f/lib/Db/Message.php#L114)
> 
> Line 114 in [a959a81](/nextcloud/mail/commit/a959a81e4a0f6db51a2b1637824e6ceba5c5ff2f)
>  protected $mentionsMe = false;

Restarting php-fpm helped. For me it was done with:

```
systemctl restart php8.2-fpm.service
```

So restarting the Server would have helped, too. Thanks for your time. Have a nice end of the year

**Comment by roko74** [comment]
Restart of the service helped also for me. Thank you!
