### ISSUE TITLE
Show images from sender does't always show images from sender

### ISSUE THREAD

**Issue by ashgoodman** [nextcloud/mail#1053]
### Expected behavior
Clicking show images from sender should show images from the sender

### Actual behavior
Sometimes it does and sometimes it doesn't. It never shows images from the sender with Nextcloud activity emails, even when using the default theme

Mail app
Mail app version: (see apps admin page, e.g. 0.5.3)
0.8.3
Mailserver or service: (e.g. Outlook, Yahoo, Gmail, Exchange,...)
Gmail (GSuite)
Number of accounts: (e.g. 1 or 2)
1

Server configuration
Operating system: (e.g. Debian 8)
Ubuntu 18,04
Web server: (e.g. Apache, Nginx,...)
Apache
Database: (e.g. MariaDB, SQLite, PostgreSQL,...)
MySQL
PHP version: (e.g. 7.0)
7.+
Nextcloud Version: (see admin page, e.g. 13.0.2)
13.0.5
Updated from an older version or fresh install:
Fresh Install

Client configuration
Browser: Chrome

Operating system: Ubuntu desktop 18.04

**Comment by ChristophWurst** [comment]
The Nextcloud mail app offers an extensive logging system to make it easier identifying and tracking down bugs. Please enable [debug mode](https://docs.nextcloud.com/server/13/developer_manual/general/devenv.html#enabling-debug-mode) and set the log [level to debug](https://docs.nextcloud.com/server/13/admin_manual/configuration_server/logging_configuration.html) in your admin settings. Then, try to reproduce your issue and take another look at `data/nextcloud.log`, `data/horde_imap.log` and `data/horde_smtp.log`.

**Comment by ashgoodman** [comment]
Hi, thanks for the feedback. I am a server novice and installed nextcloud using snap on Digitalocean. I'm struggling to find where to make the changes you recommend, it seems snap installs nextcloud and specifically extra apps differently?

**Comment by ashgoodman** [comment]
OK, I was able to duplicate. It happens with the nextcloud notification emails specifically it seems.

I'm getting a 500 Internal Server Error on the GET request. Digging deeper it's saying that I need JavaScript Enabled, which I do of course, so now I'm thinking it might be a Chrome extension causing a conflict. 

Testing again with extensions disbaled

**Comment by ashgoodman** [comment]
Fresh install of Nextcloud using snap, default theme. Extensions disabled. Tested in Chrome and Firefox

Activity notifications have the issue with images, specifically, the Nextcloud logo doesn't show when I click the show images button

Javascript console says 500 (Internal Server Error)

But, when I send a test email from the "Additional Settings" page, the logo will show when I click the show images button

And images show from non Nextcloud mails

So I'm thinking this could be an issue with the Activities or Notifications app (whichever sends out the emails), not the mail app?
