### ISSUE TITLE
Mailto links don't work, only "e.label is undefined" is shown at the top of the mail app

### ISSUE THREAD

**Issue by e-alfred** [nextcloud/mail#1055]
### Expected behavior
Mailto links from any browser should open a new mail with the receiver mail address preset in the mail app.

### Actual behavior
Only `e.label is undefined` is shown at the top of the mail app, no new mail is opened, the default view of the mail app opens. An error is logged in the browser console.

### Mail app

**Mail app version:** 0.10.0

**Mailserver or service:** Gmail, GMX, Hotmail

**Number of accounts:** 4

### Server configuration

**Operating system**: Ubuntu 16.04

**Web server:** Apache 2.4

**Database:** Mariadb 10

**PHP version:** 7.0

**Nextcloud Version:** 14 beta 4

**Updated from an older version or fresh install:** Updated from older beta

#### Client configuration
**Browser:** Firefox

**Operating system:** Debian 9

##### Browser log
```
TypeError: "e.label is undefined"                                           build.js:60:94
rhttps://my.domain/apps/mail/js/build/build.js?v=df66b9a0-4:75:21339
Ihttps://my.domain/apps/mail/js/build/build.js?v=df66b9a0-4:39:135940
Ihttps://my.domain/apps/mail/js/build/build.js?v=df66b9a0-4:39:135810
rhttps://my.domain/apps/mail/js/build/build.js?v=df66b9a0-4:75:21291
mainhttps://my.domain/apps/mail/js/build/build.js?v=df66b9a0-4:246:144709
chttps://my.domain/apps/mail/js/build/build.js?v=df66b9a0-4:246:150005
ahttps://my.domain/apps/mail/js/build/build.js?v=df66b9a0-4:246:150127
renderhttps://my.domain/apps/mail/js/build/build.js?v=df66b9a0-4:39:104468
_renderHtmlhttps://my.domain/apps/mail/js/build/build.js?v=df66b9a0-4:39:106040
_renderTemplatehttps://my.domain/apps/mail/js/build/build.js?v=df66b9a0-4:39:105907
renderhttps://my.domain/apps/mail/js/build/build.js?v=df66b9a0-4:39:105682
qhttps://my.domain/apps/mail/js/build/build.js?v=df66b9a0-4:39:141453
rhttps://my.domain/apps/mail/js/build/build.js?v=df66b9a0-4:39:141657
whttps://my.domain/apps/mail/js/build/build.js?v=df66b9a0-4:39:134807
rthttps://my.domain/apps/mail/js/build/build.js?v=df66b9a0-4:39:97111
showhttps://my.domain/apps/mail/js/build/build.js?v=df66b9a0-4:39:98184
showChildViewhttps://my.domain/apps/mail/js/build/build.js?v=df66b9a0-4:39:104118
onShowComposerhttps://my.domain/apps/mail/js/build/build.js?v=df66b9a0-4:283:10046
vhttps://my.domain/apps/mail/js/build/build.js?v=df66b9a0-4:39:155072
ghttps://my.domain/apps/mail/js/build/build.js?v=df66b9a0-4:39:154881
hhttps://my.domain/apps/mail/js/build/build.js?v=df66b9a0-4:39:152827
triggerhttps://my.domain/apps/mail/js/build/build.js?v=df66b9a0-4:39:154774
_handleMailtohttps://my.domain/apps/mail/js/build/build.js?v=df66b9a0-4:201:2991
report https://my.domain/apps/mail/js/build/build.js:60:94
```

**Comment by Simplexx38** [comment]
I've got the same issue on Nextcloud 15.0.7 if I try to send an e-mail with the poll-app to the user I've shared the poll. No solution?

**Comment by ChristophWurst** [comment]
> No solution?

No, I don't think so. In Mail 0.12 and newer this should work, though.

**Comment by alexanderdd** [comment]
fyi, the issue still occurs in mail 0.11.1, Nextcloud 16.0.4, Firefox 69.0

**Comment by jancborchardt** [comment]
Just tested with Nextcloud 18 (latest server) and Mail 1.1.2 (latest Mail app) and it works perfectly. :) → Closing
