### ISSUE TITLE
ResourceLocator can not find a web root

### ISSUE THREAD

**Issue by ashgoodman** [nextcloud/mail#1066]
Not entirely sure what is causing this as it doesn't seem to be affecting the ability of mail to function, outside of errors identified elsewhere regarding nextcloud notification email

### Expected behavior
Shouldn't see the error in logs

### Actual behavior
Seeing the following error repeatedly in logging

ResourceLocator can not find a web root (root: /var/snap/nextcloud/8267/nextcloud/extra-apps/mail, file: index.php/css/mail/c5f3-2561-mail.css, webRoot: , throw: true)

### Mail app

**Mail app version:** (see apps admin page, e.g. 0.5.3)
0.8.3
**Mailserver or service:** (e.g. Outlook, Yahoo, Gmail, Exchange,...)
Gmail
**Number of accounts:** (e.g. 1 or 2)
1

### Server configuration

**Operating system**: (e.g. Debian 8)
Ubuntu 18.04 LTS
**Web server:** (e.g. Apache, Nginx,...)
Apache
**Database:** (e.g. MariaDB, SQLite, PostgreSQL,...)
MySQL
**PHP version:** (e.g. 7.0)
7.1
**Nextcloud Version:** (see admin page, e.g. 13.0.2)
13.0.5
**Updated from an older version or fresh install:**
Fresh INstall
**List of activated apps:**
- activity: 2.6.1
  - announcementcenter: 3.2.1
  - apporder: 0.5.0
  - bookmarks: 0.12.1
  - bruteforcesettings: 1.1.0
  - calendar: 1.6.1
  - caniupdate: 0.1.3
  - checksum: 0.4.0
  - comments: 1.3.0
  - contacts: 2.1.5
  - dav: 1.4.7
  - deck: 0.4.1
  - external: 3.0.4
  - federatedfilesharing: 1.3.1
  - federation: 1.3.0
  - files: 1.8.0
  - files_external: 1.4.1
  - files_markdown: 2.0.4
  - files_pdfviewer: 1.2.1
  - files_rightclick: 0.8.4
  - files_sharing: 1.5.0
  - files_texteditor: 2.5.1
  - files_trashbin: 1.3.0
  - files_versions: 1.6.0
  - files_videoplayer: 1.2.0
  - firstrunwizard: 2.2.1
  - gallery: 18.0.0
  - groupfolders: 1.3.3
  - impersonate: 1.0.4
  - logreader: 2.0.0
  - lookup_server_connector: 1.1.0
  - mail: 0.8.3
  - metadata: 0.7.0
  - nextcloud_announcements: 1.2.0
  - notes: 2.4.1
  - notifications: 2.1.2
  - oauth2: 1.1.1
  - passman: 2.1.4
  - password_policy: 1.3.0
  - polls: 0.8.1
  - provisioning_api: 1.3.0
  - serverinfo: 1.3.0
  - sharebymail: 1.3.0
  - spreed: 3.2.5
  - survey_client: 1.1.0
  - systemtags: 1.3.0
  - tasks: 0.9.6
  - theming: 1.4.5
  - twofactor_backupcodes: 1.2.3
  - weather: 1.5.1
  - workflowengine: 1.3.0

If you have access to your command line run e.g.:
sudo -u www-data php occ app:list
from within your server installation folder
```

**The content of config/config.php:**
```
If you have access to your command line run e.g.:
sudo -u www-data php occ config:list system
from within your Nextcloud installation folder

or

Insert your config.php content here
Make sure to remove all sensitive content such as passwords. (e.g. database password, passwordsalt, secret, smtp password, …)
{
    "system": {
        "apps_paths": [
            {
                "path": "\/snap\/nextcloud\/current\/htdocs\/apps",
                "url": "\/apps",
                "writable": false
            },
            {
                "path": "\/var\/snap\/nextcloud\/current\/nextcloud\/extra-apps",
                "url": "\/extra-apps",
                "writable": true
            }
        ],
        "supportedDatabases": [
            "mysql"
        ],
        "memcache.locking": "\\OC\\Memcache\\Redis",
        "memcache.local": "\\OC\\Memcache\\Redis",
        "redis": {
            "host": "***REMOVED SENSITIVE VALUE***",
            "port": 0
        },
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "localhost",
            ""***REMOVED SENSITIVE VALUE***[the ip address of the server I hav nextcloud installed on",
            ""***REMOVED SENSITIVE VALUE***[the subdmain I have nextcloud installed on]",
            ""***REMOVED SENSITIVE VALUE***[the www version of the subdomain]"
        ],
        "datadirectory": "***REMOVED SENSITIVE VALUE***",
        "overwrite.cli.url": "http:\/\/localhost",
        "dbtype": "mysql",
        "version": "13.0.5.2",
        "dbname": "***REMOVED SENSITIVE VALUE***",
        "dbhost": "***REMOVED SENSITIVE VALUE***",
        "dbport": "",
        "dbtableprefix": "oc_",
        "mysql.utf8mb4": true,
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "installed": true,
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpmode": "smtp",
        "mail_smtpauthtype": "LOGIN",
        "mail_smtpsecure": "tls",
        "mail_from_address": "***REMOVED SENSITIVE VALUE***",
        "mail_domain": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpauth": 1,
        "mail_smtphost": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpport": "587",
        "mail_smtpname": "***REMOVED SENSITIVE VALUE***",
        "mail_smtppassword": "***REMOVED SENSITIVE VALUE***",
        "maintenance": false
    }
}

#### Client configuration
**Browser:** (e.g. Firefox 48)
Firefox 61.0.1
**Operating system:** (e.g. Arch Linux)
Ubuntu 18.04 Desktop

**Comment by ChristophWurst** [comment]
The Nextcloud mail app offers an extensive logging system to make it easier identifying and tracking down bugs. Please enable [debug mode](https://docs.nextcloud.com/server/13/developer_manual/general/devenv.html#enabling-debug-mode) and set the log [level to debug](https://docs.nextcloud.com/server/13/admin_manual/configuration_server/logging_configuration.html) in your admin settings. Then, try to reproduce your issue and take another look at `data/nextcloud.log`, `data/horde_imap.log` and `data/horde_smtp.log`.

**Comment by ashgoodman** [comment]
Have enabled debug and the the most detailed logging

Then I looked in /var/snap/nextcloud/common/nextcloud/data

and cannot find the files: data/nextcloud.log, data/horde_imap.log and data/horde_smtp.log

Am I looking at the wrong data directory?

**Comment by ChristophWurst** [comment]
Please see https://docs.nextcloud.com/server/13/admin_manual/configuration_server/logging_configuration.html.

**Comment by ChristophWurst** [comment]
If you can't find any files you might want to ask the maintainers of that snap package.

**Comment by ChristophWurst** [comment]
No info provided -> closing

If you happen to have figured out how to access the logs, let us know.

**Comment by ChristophWurst** [comment]
I can just repeat myself. Please report this to the package maintainer of the snap. As you can see from the error log, it's not just this app that triggers this error, but also the "spreed" app and others.

**Comment by the-sane** [comment]
FYI:  It has been determined that these errors are the result of a problem in the server: https://github.com/nextcloud/server/issues/13556

**Comment by ChristophWurst** [comment]
thanks
