### ISSUE TITLE
Fatal error moving emails

### ISSUE THREAD

**Issue by jcbdg18** [nextcloud/mail#1067]
### Expected behavior
When i mova an email with drag an drop to another imap folder, it should be moved.

### Actual behavior
When i move an email with drag and drop to another imap folder the email is deleted and i cannot find it again. It's for all deleted :-(

### Mail app

**newest in aug. 2018** (see apps admin page, e.g. 0.5.3)

**imap med ssl** (e.g. Outlook, Yahoo, Gmail, Exchange,...)

**1** (e.g. 1 or 2)

### Server configuration

****: (e.g. Debian 8)

**Web server:** (e.g. Apache, Nginx,...)

**Database:** (e.g. MariaDB, SQLite, PostgreSQL,...)

**7.1** (e.g. 7.0)

**13.05** (see admin page, e.g. 13.0.2)

**fresh install**

**List of activated apps:**
```
If you have access to your command line run e.g.:
sudo -u www-data php occ app:list
from within your server installation folder
```

**The content of config/config.php:**
```
If you have access to your command line run e.g.:
sudo -u www-data php occ config:list system
from within your Nextcloud installation folder

or

Insert your config.php content here
Make sure to remove all sensitive content such as passwords. (e.g. database password, passwordsalt, secret, smtp password, …)
```

#### Client configuration
**Browser:** (e.g. Firefox 48)

**Operating system:** (e.g. Arch Linux)

##### Web server error log
```
Insert your webserver log here (e.g. /var/log/apache2/...)
```

##### Server log (data/nextcloud.log)
```
Insert your server log here
```

##### IMAP log (data/horde_imap.log)
```
Enable debug mode and insert your horde IMAP log here, see https://docs.nextcloud.com/server/13/developer_manual/general/debugging.html#debug-mode
```

##### SMTP log (data/horde_smtp.log)
```
Enable debug mode and insert your horde IMAP log here, see https://docs.nextcloud.com/server/13/developer_manual/general/debugging.html#debug-mode
```

##### Browser log
```
Insert your browser log here, this could for example include:

a) The javascript console log
b) The network log 
```

**Comment by ChristophWurst** [comment]
The Nextcloud mail app offers an extensive logging system to make it easier identifying and tracking down bugs. Please enable [debug mode](https://docs.nextcloud.com/server/13/developer_manual/general/devenv.html#enabling-debug-mode) and set the log [level to debug](https://docs.nextcloud.com/server/13/admin_manual/configuration_server/logging_configuration.html) in your admin settings. Then, try to reproduce your issue and take another look at `data/nextcloud.log`, `data/horde_imap.log` and `data/horde_smtp.log`.

**Comment by ChristophWurst** [comment]
Please take the issue template serious and fill out *all* the information you've been asked for. Thanks.

**Comment by ChristophWurst** [comment]
No info provided -> closing
