### ISSUE TITLE
After updating to 0.8.3, app no longer connects to mail server.

### ISSUE THREAD

**Issue by mikejtl** [nextcloud/mail#1078]
Mail App was working great for me for months.  Then after an update it stopped connecting to my server.  I tried deleting my mail account and creating it again.  That did not work.  I tried removing the mail app from my NC instance and reinstalling it. That did not work either.  I have tried connecting to both my dreamhost mail server and my gmail account.  Neither one connects. I can connect with other mail clients and through the respective webmail. 

I have called Dreamhost who tell me they have no record of the Mail App trying to connect to their mail servers. 

### Expected behavior
App connects to mail server, retrieves mail and can send mail. 

### Actual behavior
I get the following message:
"Error while creating the account: Creating account failed: Error connecting to mail server."

### Mail app

**Mail app version:** 0.8.3

**Mailserver or service:**  Dreamhost and Gmail

**Number of accounts:** 2 accounts, tried one at a time

### Server configuration
I do not know, my NC instance is on oCloud so I don't know the details of the server. 

**Operating system**: (e.g. Debian 8)

**Web server:** (e.g. Apache, Nginx,...)

**Database:** (e.g. MariaDB, SQLite, PostgreSQL,...)

**PHP version:** (e.g. 7.0)

**Nextcloud Version:** 13.0.1

**Updated from an older version or fresh install:** Updated from previous version

**List of activated apps:** Mail, Tasks, Calendar, Notes, Contacts, Phone Sync, Files, Deck, Gallery, Activity

If you have access to your command line run e.g.: I don't have access to this.
sudo -u www-data php occ app:list
from within your server installation folder
```

**The content of config/config.php:** I do not know. 
```
If you have access to your command line run e.g.:
sudo -u www-data php occ config:list system
from within your Nextcloud installation folder

or

Insert your config.php content here
Make sure to remove all sensitive content such as passwords. (e.g. database password, passwordsalt, secret, smtp password, …)
```

#### Client configuration
**Browser:** (e.g. Firefox 48) Firefox 61.0.2, also tried on Chrome 68.0.3440.106

**Operating system:** (e.g. Arch Linux) macOS 10.13.3

#### Logs
##### Web server error log
```
Insert your webserver log here (e.g. /var/log/apache2/...)
```

##### Server log (data/nextcloud.log)
```
Insert your server log here
```

##### IMAP log (data/horde_imap.log)
```
Enable debug mode and insert your horde IMAP log here, see https://docs.nextcloud.com/server/13/developer_manual/general/debugging.html#debug-mode
```

##### SMTP log (data/horde_smtp.log)
```
Enable debug mode and insert your horde IMAP log here, see https://docs.nextcloud.com/server/13/developer_manual/general/debugging.html#debug-mode
```

##### Browser log
```
Insert your browser log here, this could for example include:

a) The javascript console log
b) The network log 
```

**Comment by ChristophWurst** [comment]
The Nextcloud mail app offers an extensive logging system to make it easier identifying and tracking down bugs. Please enable [debug mode](https://docs.nextcloud.com/server/13/developer_manual/general/devenv.html#enabling-debug-mode) and set the log [level to debug](https://docs.nextcloud.com/server/13/admin_manual/configuration_server/logging_configuration.html) in your admin settings. Then, try to reproduce your issue and take another look at `data/nextcloud.log`, `data/horde_imap.log` and `data/horde_smtp.log`.

**Comment by mikejtl** [comment]
I'm sorry, this may be beyond my knowledge/understanding.  I don't think I have access to the php files for my instance in order to enable debug mode.  I am able to find the logs in NC admin account and some of them are labeled as "debug level" and I can download them, but I don't understand where you want me to look for those data logs.
