### ISSUE TITLE
Passwords logged in plaintext when autoconfig fails

### ISSUE THREAD

**Issue by Bubu** [nextcloud/mail#1093]
### Expected behavior
NOT logging plaintext passwords(!)

### Actual behavior
Paswords logged in plaintext when autoconfig fails :cry: 

### Mail app

**Mail app version:** 0.10.0

```
	TypeError: Argument 5 passed to OCA\Mail\Service\AutoConfig\ImapConnector::connect() must be of the type integer, string given, called in /usr/share/webapps/nextcloud/apps/mail/lib/Service/AutoConfig/IspDbConfigurationDetector.php on line 166

    /usr/share/webapps/nextcloud/apps/mail/lib/Service/AutoConfig/IspDbConfigurationDetector.php - line 166:

    OCA\Mail\Service\AutoConfig\ImapConnector->connect("email@example.de", "SUPERSECUREPASSWORDHERE", "UserName", "imap", "993", "ssl", "email@example.de")
[...]
```

**Comment by ChristophWurst** [comment]
Dup of #1094

**Comment by ChristophWurst** [comment]
If there were no bug the password wouldn't be logged.

**Comment by Bubu** [comment]
> If there were no bug the password wouldn't be logged.

Bugs happen. There will certainly be bugs in the future. User passwords (and in this case even for external services) shouldn't end up in the log ever.

Apart from being visible to any instance admin it's also very easy to accidentally post user passwords into some bug report.

And what about non-bugs like (remote-)timeouts, unexpected server response, user entering unexpected things into some field?

I have no insight into how the logging is handled and if this could be done differently with reasonable effort but please reconsider this as at least something to think about.

**Comment by ChristophWurst** [comment]
See https://github.com/nextcloud/server/blob/844c7408686f2262aaab322f91fb61a18cbfa0ad/lib/private/Log/ExceptionSerializer.php. This should be possible to fix with low effort.

**Comment by Bubu** [comment]
I guess this is overlapping/duplicate with #823

**Comment by ChristophWurst** [comment]
Right! Dup of #823
