### ISSUE TITLE
Answer button is partially overlain by another div

### ISSUE THREAD

**Issue by cappuMUC** [nextcloud/mail#1096]
The answer button is partially overlain by another div and therefore partially not clickable.
![div_covering_send_button](https://user-images.githubusercontent.com/9985266/45345434-97c0e580-b5a6-11e8-95d7-17776c1c7048.png)

``` html
<div class="submit-message-wrapper">
		<input class="submit-message send primary" value="Antworten" type="submit">
		<div class="submit-message-wrapper-inside"></div>
	</div>
```
The second div in this snippet ist causing the problem.

App version: 0.10.0
Nextcloud version: 14.0.0

Tested on:
- Firefox  v61.0.2
- Chromium v68.0.3440.106

**Comment by ChristophWurst** [comment]
This might get fixed in the course of #1045.

**Comment by TimP4w** [comment]
What's the purpose of the submit-message-wrapper-inside div? Can it be removed altogether?

**Comment by ChristophWurst** [comment]
Good point. This got removed with the Vue rewrite. Closing.
