### ISSUE TITLE
Auto-responder for holidays

### ISSUE THREAD

**Issue by MrLaffer** [nextcloud/mail#1099]
### Feature Request

I would be pleased about an automatic reply function for incoming mails. That's a nice feature for vacation absences.

#### Summary

I would be pleased about an automatic reply function for incoming mails. That's a nice feature for vacation absences.

**Comment by ChristophWurst** [comment]
This can be done with [sieve](https://wiki2.dovecot.org/Pigeonhole/Sieve/Examples#Vacation_auto-reply) it seems, so I'd say this is a duplicate of https://github.com/nextcloud/mail/issues/44.

Thanks for reporting.
