### ISSUE TITLE
Navigation from account settings to new message composer is impossible [$10 awarded]

### ISSUE THREAD

**Issue by ChristophWurst** [nextcloud/mail#110]
Since the current code expects that a folder view is shown, nobody listens to the `composer:show` event when the account settings are currently shown.

**Comment by jancborchardt** [comment]
This issue still seems to occur on current master, getting this in the console:
```
TypeError: "this.folder is undefined"
    fetchData FolderContent.vue:108
    created FolderContent.vue:96
    VueJS 39
vue.runtime.esm.js:1888
[Vue warn]: Error in render: "TypeError: this.folder is undefined"

found in

---> <FolderContent> at src/components/FolderContent.vue
       <Content>
         <Home> at src/views/Home.vue
           <App> at src/App.vue
             <Root>
```
cc @kingjan1999

**Comment by kingjan1999** [comment]
@jancborchardt I'd rather say that it appears again (as the old issue occured in the pre-Vue version) ;). Nevertheless, I'd love to look into this, though I haven't followed this project closely during the last two years
