### ISSUE TITLE
Nextcloud mail app error

### ISSUE THREAD

**Issue by janarzz** [nextcloud/mail#1100]
Hey,
Its possible to use Nextcloud mail app IMAP ?
When i tryng, then error connect SMTP server.
I use mail app 0.10.0 version.

**Comment by Gatak** [comment]
Yes, it is.

IMAP is the protocol to download mail. 
SMTP is the protocol to send mail. 

You have you have the correct address for both of them. Usually imap.domain.com and smtp.domain.com, though it could be anything. In addition you need to have the port and security settings correct. 

Settings for Gmail is at support.google.com/mail/answer/7126229?hl=en

**Comment by janarzz** [comment]
Hmm wierd..when i used Nextcloud app older version works all perfectly..

**Comment by janarzz** [comment]
My mailserver IMAP and SMTP settings working thunderbird, outlook...

**Comment by Gatak** [comment]
Odd. I'm using it here on NC14.

**Comment by janarzz** [comment]
All settings are right and i get this error:
Error while creating the account: Error connecting to SMTP server.

**Comment by Datapanic** [comment]
I am also getting "Error while creating the account..." and the dovecot log entry says:
Sep 13 10:59:54 mail01 dovecot: imap-login: Disconnected (no auth attempts in 0 secs): user=<>, rip=10.0.1.10, lip=10.0.1.100, session=<apduecR1wXIKAAEK>

The user is null - I have tried %USERID% in config.php and entered manually in nextcloud and no matter what, it's always <> for user in dovecot.

**Comment by janarzz** [comment]
Please fix nextcloud mail app :)
Old version worked perfectly :)

**Comment by ChristophWurst** [comment]
> Please fix nextcloud mail app :)

Please file a proper bug report with a filled out issue template at https://github.com/nextcloud/mail/issues/new?template=bug.md. Otherwise it's *very* hard to fix this. Thanks.
