### ISSUE TITLE
Enhancement: mail filters

### ISSUE THREAD

**Issue by Gatak** [nextcloud/mail#1101]
It would be really useful with server side mail filters. This would allow me to move emails to specific folders within and between accounts, delete certain mail or tag them, etc. 

Some say filters are a mta thing, however if would be difficult to achieve email filters that span several accounts this way. It was the multi account support of the mail app that was the main feature for me to go for Nextcloud :)

Filters could be handled automatically in the main NC cron jobs, or as a separate cron job that is run at a higher / different frequency.

>occ mail:filters --run --filter "some filter" --user username
>occ mail:filters --run-all

**Comment by ChristophWurst** [comment]
Dup of https://github.com/nextcloud/mail/issues/44

**Comment by Gatak** [comment]
@ChristophWurst I had missed #44. I think that if the multi-account filtering support can be included in that issue, then we can close this. IMHO filtering across multiple accounts would be a very well received feature, which also would be relatively unique for Nextcloud. I believe that only desktop applications like Thunderbird, Outlook and Evolution has that possibility.

**Comment by je-vv** [comment]
Server side filters are not just a good thing to have, it's actually a must when accessing email through different mail clients (not all supporting filtering).  As an example the stock LineageOS email app doesn't support creating filters, and I suppose several other imap/smtp mobile clients don't (under the assumption the servers take care of filters).
So, automatic filters upon receiving new email on the server is really missing.
Thank !
