### ISSUE TITLE
Html Mail not displayed

### ISSUE THREAD

**Issue by simonbuehler** [nextcloud/mail#1105]
### Expected behavior
show the mailcontent

### Actual behavior
white page `<br><br>` is  the only content of the iframe

### Mail app

**Mail app version:** 0.10
**Mailserver or service:** imap
**Number of accounts:** 1

### Server configuration

**Operating system**: gentoo

**Web server:** apache
**Database:** mysql
**PHP version:** 7.0
**Nextcloud Version:** 14.0,0

**Updated from an older version or fresh install:** updated

**List of activated apps:**
```
Enabled:
  - accessibility: 1.0.1
  - activity: 2.7.0
  - admin_audit: 1.4.0
  - audioplayer: 2.3.2
  - calendar: 1.6.2
  - cloud_federation_api: 0.0.1
  - comments: 1.4.0
  - contacts: 2.1.6
  - dav: 1.6.0
  - federatedfilesharing: 1.4.0
  - federation: 1.4.0
  - files: 1.9.0
  - files_external: 1.5.0
  - files_pdfviewer: 1.3.2
  - files_retention: 1.3.0
  - files_rightclick: 0.8.4
  - files_sharing: 1.6.2
  - files_texteditor: 2.6.0
  - files_trashbin: 1.4.1
  - files_versions: 1.7.1
  - files_videoplayer: 1.3.0
  - firstrunwizard: 2.3.0
  - gallery: 18.1.0
  - impersonate: 1.1.0
  - logreader: 2.0.0
  - lookup_server_connector: 1.2.0
  - mail: 0.10.0
  - metadata: 0.7.0
  - nextcloud_announcements: 1.3.0
  - notifications: 2.2.1
  - oauth2: 1.2.1
  - password_policy: 1.4.0
  - provisioning_api: 1.4.0
  - quota_warning: 1.3.0
  - radio: 0.6.3
  - serverinfo: 1.4.0
  - sharebymail: 1.4.0
  - spreed: 4.0.0
  - support: 1.0.0
  - survey_client: 1.2.0
  - systemtags: 1.4.0
  - tasks: 0.9.7
  - theming: 1.5.0
  - twofactor_backupcodes: 1.3.1
  - updatenotification: 1.4.1
  - user_external: 0.4
  - workflowengine: 1.4.0
Disabled:
  - bruteforcesettings
  - circles
  - encryption
  - files_downloadactivity
  - unsplash
  - user_ldap

```

**The content of config/config.php:**
```
```

#### Client configuration
**Browser:** ff, chrome

**Operating system:** win, linux

##### Web server error log
```
no errors shown
```

##### Server log (data/nextcloud.log)
```
empty
```

##### IMAP log (data/horde_imap.log)
```
S: [LITERAL DATA: 32046 bytes]
S:  BINARY.SIZE[1] 23213 BODY[1.MIME] {115}
S: [LITERAL DATA: 115 bytes]
S: )
S: 5 OK Fetch completed (0.001 + 0.000 secs).
>> Command 5 took 0.0008 seconds.
C: 6 LOGOUT
S: * BYE Logging out
S: 6 OK Logout completed (0.000 + 0.000 secs).
>> Command 6 took 0.0004 seconds.
```

##### SMTP log (data/horde_smtp.log)
```
empty
```

##### Browser log
```
no errors
```

**Comment by ChristophWurst** [comment]
I see you've included relevant info/logs in your report. Still, I'm not able to comprehend the problem.

Please let us know if you can see any pattern in which emails are not displayed? Does this effect *all* your emails?

**Comment by simonbuehler** [comment]
oh sorry, 
its one email forwarded containing html content, i might send you a redacted copy of it if that helps

**Comment by ChristophWurst** [comment]
Any chance you could post the source of the redacted email here? Thanks!

**Comment by simonbuehler** [comment]
I'm afraid thats not allowed ;/

**Comment by simonbuehler** [comment]
where can i send you the .eml file

**Comment by ChristophWurst** [comment]
Too bad. If you send it to me via a private email it's likely to get lost because I've currently no time to look into this.

**Comment by simonbuehler** [comment]
i understand that, its a pitty.

i guess its because the content is only base64 party:
see that structure below
```
--_004_VI1PR07MB3359B642AAEC0616AE7814D2B41A0VI1PR07MB3359eurp_
Content-Type: multipart/alternative;
	boundary="_000_VI1PR07MB3359B642AAEC0616AE7814D2B41A0VI1PR07MB3359eurp_"

--_000_VI1PR07MB3359B642AAEC0616AE7814D2B41A0VI1PR07MB3359eurp_
Content-Type: text/plain; charset="utf-8"
Content-Transfer-Encoding: base64

xxx

--_000_VI1PR07MB3359B642AAEC0616AE7814D2B41A0VI1PR07MB3359eurp_
Content-Type: text/html; charset="utf-8"
Content-Transfer-Encoding: base64

xxx

--_000_VI1PR07MB3359B642AAEC0616AE7814D2B41A0VI1PR07MB3359eurp_--

--_004_VI1PR07MB3359B642AAEC0616AE7814D2B41A0VI1PR07MB3359eurp_
Content-Type: image/jpeg; name="image001.jpg"
Content-Description: image001.jpg
Content-Disposition: inline; filename="image001.jpg"; size=799;
	creation-date="Thu, 13 Sep 2018 09:27:51 GMT";
	modification-date="Thu, 13 Sep 2018 09:34:56 GMT"
Content-ID: <image001.jpg@01D44B54.BA2EEAC0>
Content-Transfer-Encoding: base64

XXX

--_004_VI1PR07MB3359B642AAEC0616AE7814D2B41A0VI1PR07MB3359eurp_--

```

**Comment by ChristophWurst** [comment]
> Content-Transfer-Encoding: base64

Good point. That could indeed be the issue.

**Comment by jhammons** [comment]
@simonbuehler I have two instances and one had the issue you describe and the other did not. Fortunately I was able to deduce it was a configuration issue on my end. I suggest you investigate setting following options in config.php:

>   'overwrite.cli.url' => 'https://sub.example.com',                                                                                                                          
  'overwritehost' => 'sub.example.com',                                                                                                                                      
  'overwriteprotocol' => 'https', 

The problematic instance I had was accidentally missing the last two. I hope this is helpful. Be well.

**Comment by ChristophWurst** [comment]
@jhammons the settings you're referring to look related to a reverse proxy setup: https://docs.nextcloud.com/server/14/admin_manual/configuration_server/reverse_proxy_configuration.html

**Comment by ChristophWurst** [comment]
This is fixed in https://github.com/nextcloud/mail/pull/1448

**Comment by thalman** [comment]
Hmm, interesting, 'overwriteprotocol' => 'https' helped me too despite not using reverse proxy (nextcloud 13.0.10 on centos 7 with php 7.0)
