### ISSUE TITLE
Address autocompletion does not work

### ISSUE THREAD

**Issue by ChristophWurst** [nextcloud/mail#1106]
### Expected behavior
The app should autocomplete addresses from contacts and collected addresses.

### Actual behavior
Autocomplete logic kicks in and sends ajax request but response is not used.

### Mail app

**Mail app version:** 0.10.0

### Server configuration

**Nextcloud Version:** 14 and 15

**Comment by Kugeleis** [comment]
can confirm this with nextcloud 14.0 + mail app 0.10.0

**Comment by g6094199** [comment]
also can confirm this with nextcloud 14.0 + mail app 0.10.0

**Comment by nickdbush** [comment]
Can I just confirm this is **not** supposed to autocomplete individual users (as, currently, it is only completing user groups from Nextcloud). Thanks for releasing this update, it's really helpful!
