### ISSUE TITLE
Search all folders/accounts

### ISSUE THREAD

**Issue by ashgoodman** [nextcloud/mail#1108]
### Feature Request

I would like to be able to search for emails in all folders/accounts

#### Summary

Currently, the search feature only searches emails in the folder you are currently viewing. For many users, this is not intuitive as they are used to searches either searching all folders or an option to search all folders

As a plus searching across all clients would be nice as well.

**Comment by zeigerpuppy** [comment]
It probably makes sense to offload this to the mail server as indexing mail for full-text-search (FTS) is a CPU and memory intensive process. Servers with FTS capability should advertise this in their IMAP header, then the extended search can be offloaded to the server.

The search is initiated by the IMAP command `SEARCH TEXT IMAP`

Some more documentation: 
- https://wiki2.dovecot.org/Plugins/FTS
- https://extremeshok.com/6622/enabling-apache-solr-4-10-using-jetty-with-dovecot-2-2-for-fulltext-search-results-on-centos-6-iredmail-compatible/
- I believe the roundcube client supports FTS search

**Comment by jancborchardt** [comment]
As for the interface, we should do it just like in the Files app – in the message list first show the results from the current folder, then a subheading "From other folders" with the results from those.

**Comment by StCyr** [comment]
This issue is not relevant anymore since the introduction of Nextcloud's unified search => closing
