### ISSUE TITLE
Add Prettier for consistent code formatting

### ISSUE THREAD

**Issue by kevgathuku** [nextcloud/mail#1130]
When making changes, I'm finding that most of the diffs are formatting changes rather than actual code changes
[Prettier](https://prettier.io/) is a nice tool we could use to have consistent formatting throughout the codebase

**Comment by kevgathuku** [comment]
What do you think @ChristophWurst ?
I'm thinking of doing this as part of the Vue rewrite

**Comment by skjnldsv** [comment]
Depends on the tech, eslint for js, stylelint for css :)
That's the two most used and they integrate nicely on webpack

**Comment by kevgathuku** [comment]
`Prettier` is concerned only with code formatting i.e. semicolons, tabs/spaces, etc.
`eslint` and `stylelint` are complementary tools for finding errors in the code in js/css

And as @skjnldsv they play well together 😄

**Comment by skjnldsv** [comment]
@kevgathuku eslint and stylelint also handle formatting ;)

**Comment by kevgathuku** [comment]
Closed in #1172
