### ISSUE TITLE
Configure which folders are visible 

### ISSUE THREAD

**Issue by brjhaverkamp** [nextcloud/mail#1175]
### Feature Request

Currently when I open the nextcloud mail app only the Inbox, favorites, draft and sent folders are visible.
In order to access the archive, I need to click "show all folders"
It would be good if one can configure which folders are visible at startup. In my case I would add the archive folder to the standard view, so I can drag mails from inbox to archive more easily.

Secondarily, it would be great to be able to edit the order of the folders in the tree view.

**Comment by stefan-niedermann** [comment]
maybe related to #1025 ?

**Comment by jancborchardt** [comment]
Yep, closing this in favor of **Remember expanded/collapsed state of navigation folders #1025**
This suffices and a more in-detail management of visibility is too much overhead.
