### ISSUE TITLE
Synchronize user created folders from IMAP source

### ISSUE THREAD

**Issue by AmonBune** [nextcloud/mail#1189]
### Feature Request

Currently, only predefined folders like "Archive" or "Outbox" are shown in the left pane of the nextcloud-mail app. I have a whole folder structure in my Outlook E-Mail, which the nextcloud-mail app does not recognize / synchronize and they do not show up on the left pane.

#### Summary

Synchronize the user created folders as well, not only predefined system folders.

**Comment by ChristophWurst** [comment]
There's a button at the end of the list to expand it. All folders are shown there.

**Comment by AmonBune** [comment]
There is a button, yes, and this button does not work for me. It doesn't show all folders I have in Outlook. I have attached pictures of my account for clarification. Note that some of the folders are inside the Inbox. If I click on the inbox in the mail-app, there are no folders under it. Hint: the "@live.de" address is my main address.

This is my outlook account with all the folders:
![capture1](https://user-images.githubusercontent.com/15927695/46532942-2de4e480-c8a3-11e8-9a32-65932ec702b1.png)


And this is the mail-app, which shows only some of the folders (the ones that were created by MS):
![capture2](https://user-images.githubusercontent.com/15927695/46532945-30473e80-c8a3-11e8-89dc-af574a3757b4.PNG)

**Comment by ChristophWurst** [comment]
> Note that some of the folders are inside the Inbox.

Try clicking the inbox icon (house).

**Comment by AmonBune** [comment]
@ChristophWurst This does not do anything. There are simply no folders under it. It simply loads the Inbox folder, which does not include the other messages in the subfolders.

**Comment by AmonBune** [comment]
See, no folders in the HTML as well:

![image](https://user-images.githubusercontent.com/15927695/46534509-a26e5200-c8a8-11e8-9d47-9ddfa186ca39.png)

**Comment by jernejs** [comment]
> Try clicking the inbox icon (house).

This definitely needs to be more discoverable - I went looking into bug reports because I couldn't see folders inside Inbox, and never expected that clicking the house would do anything other than clicking the "Inbox" text. At least change the house to ► when hovering.

**Comment by AmonBune** [comment]
@jernejs I am confused, When I click on the house icon, it loads the inbox, it's what I would expect to happen actually... What happens exactly on your end if you click the house icon?

Btw, I upgraded to the latest beta NC version (15.0.0 RC 3) and app version 0.11.0 right now and it doesn't change anything for me.

**Comment by jernejs** [comment]
Clicking the house reveals the subfolders inside Inbox for me (though the presentation could've been better, but that goes for all nested folders); it doesn't switch to Inbox if some other folder was selected.

**Comment by ChristophWurst** [comment]
assuming this has been fixed as there was no more comment.
