### ISSUE TITLE
Select multiple items/mails & bulk actions

### ISSUE THREAD

**Issue by AmonBune** [nextcloud/mail#1197]
### Feature Request

It would be great to be able to select multiple items (with checkboxes next to each mail, and also by selecting one item and pressing SHIFT + clicking another email to mark from the first selected item to the second selected + all between. Consider adding CTRL + clicking for selective choosing as well)

Further, there would have to be actions like "mark selected unread/read", "delete selected", "favourite selected", "move selected to...", "copy selected to..."

As a gimmick, it would be great to be able to drag & drop the selected mails/items to another folder.

**Comment by ChristophWurst** [comment]
Duplicate of https://github.com/nextcloud/mail/issues/1008.

Now that we're rewriting the front-end with Vue, these features should be easier to implement. For more info see #1045. If you happen to be a js developer, we'd appreciate if you'd help us with the development :wink: 

> As a gimmick, it would be great to be able to drag & drop the selected mails/items to another folder.

That should actually already work, but not across multiple accounts.

**Comment by digitalgraphit** [comment]
Hi Christophe, 
Any news about thoses features : multiple email selection, drag and drop to another folder ? 
Thanks sa lot for your great work !
Cheers
