### ISSUE TITLE
Sublists not correctly indented

### ISSUE THREAD

**Issue by jancborchardt** [nextcloud/mail#1213]
### Expected behavior
Sublists in an email are correctly indented.

### Actual behavior
They are not. See Thunderbird on left, and Nextcloud Mail on the right:
![screenshot from 2018-10-18 13-23-25](https://user-images.githubusercontent.com/925062/47152277-8c1aba00-d2dc-11e8-9a4a-62c5e75cf93a.png)

**Mail app version:** latest master

(Not sure, but maybe this is a good first issue?)

**Comment by StCyr** [comment]
Seems to work fine now (from gmail to Mail 1.8.1):

![image](https://user-images.githubusercontent.com/8179031/107279381-43600f80-6a57-11eb-9cec-ec68599a8dbb.png)
