### ISSUE TITLE
Folders are not visible

### ISSUE THREAD

**Issue by schorsch2** [nextcloud/mail#1228]
### Expected behavior
click on "show all folders" should open all imap- folders

### Actual behavior
only a part of a folder is visible, all other folders not visible bit clickable

### Mail app

Mail app version: 0.11.0

**Mailserver or service:** (e.g. Outlook, Yahoo, Gmail, Exchange,...)

cyrus imap

### Server configuration

docker container

Nginx-proxy

**Database:** PostgreSQL

**PHP version:** 7.2.11

**Nextcloud Version:** 14.0.3.0

**Updated from an older version or fresh install:** from older Version

**List of activated apps:**
Enabled:
  - accessibility: 1.0.1
  - activity: 2.7.0
  - bruteforcesettings: 1.1.0
  - calendar: 1.6.3
  - cloud_federation_api: 0.0.1
  - comments: 1.4.0
  - contacts: 2.1.6
  - dav: 1.6.0
  - deck: 0.4.1
  - encryption: 2.2.0
  - federatedfilesharing: 1.4.0
  - federation: 1.4.0
  - files: 1.9.0
  - files_pdfviewer: 1.3.2
  - files_sharing: 1.6.2
  - files_texteditor: 2.6.0
  - files_trashbin: 1.4.1
  - files_versions: 1.7.1
  - files_videoplayer: 1.3.0
  - firstrunwizard: 2.3.0
  - gallery: 18.1.0
  - logreader: 2.0.0
  - lookup_server_connector: 1.2.0
  - mail: 0.11.0
  - nextcloud_announcements: 1.3.0
  - notifications: 2.2.1
  - oauth2: 1.2.1
  - password_policy: 1.4.0
  - provisioning_api: 1.4.0
  - serverinfo: 1.4.0
  - sharebymail: 1.4.0
  - support: 1.0.0
  - survey_client: 1.2.0
  - systemtags: 1.4.0
  - theming: 1.5.0
  - twofactor_backupcodes: 1.3.1
  - updatenotification: 1.4.1
  - workflowengine: 1.4.0
Disabled:
  - admin_audit
  - files_external
  - user_external
  - user_ldap

**The content of config/config.php:**
-

#### Client configuration
**Browser:** Firefox 63

**Comment by schorsch2** [comment]
![mailfolderthunderbird](https://user-images.githubusercontent.com/13661057/47437556-1cf40880-d7a9-11e8-8d88-c1679b364f03.png)

**Comment by ChristophWurst** [comment]
Looks like your server is configured to have your mailboxes as subfolders of the inbox. Have you tried clicking the house icon on the inbox mailbox?

**Comment by schorsch2** [comment]
>Have you tried clicking the house icon on the inbox mailbox?
Yes, now I can see my folders. Important is to click on the *icon*. I expected to click on the word inbox near this icon.
Thanks!

**Comment by ChristophWurst** [comment]
Yeah, it's a bug :see_no_evil: 

I'm closing this because we're already tracking this in another issue (don't have the issue number at hand).
