### ISSUE TITLE
the character display encoding error when receiving mail with attachment

### ISSUE THREAD

**Issue by kxu1988** [nextcloud/mail#1255]
### Expected behavior
Tell us what should happen
1. receive mail without attachment, it's fine
2. receive mail with attachment, the mail body should display in right character
### Actual behavior
1. receive mail without attachment, it's fine
2. receive mail with attachment, mail title and attachent is OK, while the mail body could not display right(the character encoding  error)
![1](https://user-images.githubusercontent.com/2177603/47838429-5997b380-ddea-11e8-8c50-a333a858a69c.jpg)

### Mail app

**Mail app version:V0.11.0 (see apps admin page, e.g. 0.5.3)

### Server configuration

**Operating system**:Ubuntu18.04LTS

**Web server:Apache

**Database;MariaDB

**PHP version:7.0

**Nextcloud Version:14.0.3

**Updated from an older version or fresh install: fresh install

#### Client configuration
**Browser: Chrome

**Operating system:MAC & Windows10

**Comment by kxu1988** [comment]
@ChristophWurst Hi, I have debug the code, find more details:
1. when I receive mail without attachment, the encoding is "gbk2312"， which is 16bit
2. when I receive mai with attachment, the encoding is "gbk18030",which is 32bit

**Comment by kxu1988** [comment]
Hi @ChristophWurst , I just find that when I receive email with attachment which is write in English, there are some additional information, hope this info is helpful for you
![2](https://user-images.githubusercontent.com/2177603/48126016-18f0dc00-e2bb-11e8-8f8b-7a40226f4b12.jpg)

**Comment by ChristophWurst** [comment]
Dup of #1391, fixed in #1448
