### ISSUE TITLE
Vue bundle is huge

### ISSUE THREAD

**Issue by ChristophWurst** [nextcloud/mail#1274]
```
$ npm run build

> mail@1.0.0 build /home/christoph/workspace/nextcloud/apps/mail
> webpack --progress --hide-modules --config webpack.prod.js

Hash: 74d867d993d53f9a2444                                                           
Version: webpack 4.25.1
Time: 7520ms
Built at: 07.11.2018 11:51:30
      Asset      Size  Chunks                    Chunk Names
    mail.js  1.15 MiB       0  [emitted]  [big]  main
mail.js.map  4.37 MiB       0  [emitted]         main
Entrypoint main [big] = mail.js mail.js.map

WARNING in asset size limit: The following asset(s) exceed the recommended size limit (244 KiB).
This can impact web performance.
Assets: 
  mail.js (1.15 MiB)

WARNING in entrypoint size limit: The following entrypoint(s) combined asset size exceeds the recommended limit (244 KiB). This can impact web performance.
Entrypoints:
  main (1.15 MiB)
      mail.js


WARNING in webpack performance recommendations: 
You can limit the size of your bundles by using import() or require.ensure to lazy load some parts of your application.
For more info visit https://webpack.js.org/guides/code-splitting/
```

**Comment by kevgathuku** [comment]
(webpack-bundle-analyzer)[https://github.com/webpack-contrib/webpack-bundle-analyzer] is a good tool that shows exactly what's taking up the space in the bundle.
I can try using it to see if there's any more opportunities to trim down the bundle size

**Comment by ChristophWurst** [comment]
> I can try using it to see if there's any more opportunities to trim down the bundle size

Sounds good!

I've reduce the individual chunk size a lot with splitting per page: https://github.com/nextcloud/mail/pull/1277

**Comment by kevgathuku** [comment]
I tried out [webpack-bundle-analyzer](https://github.com/webpack-contrib/webpack-bundle-analyzer) in the `refactor/vue` branch and it gave me this visualization:
<img width="1440" alt="screen shot 2018-11-20 at 13 57 12" src="https://user-images.githubusercontent.com/3721994/48769539-f6a08a80-eccc-11e8-818c-3f156784128c.png">
It runs a local server that you can use to interactively check the bundle sizes of the various components.
You can also try it out in the [analyze-bundle](https://github.com/nextcloud/mail/tree/analyze-bundle) brunch.
I've included an npm script: `npm run bundle-analyzer`
It seems there's still some interesting opportunities for a smaller bundle size 😃

**Comment by ChristophWurst** [comment]
Wow. This is awesome! Thanks for looking into this and sharing that image!
