### ISSUE TITLE
Code formatting issues

### ISSUE THREAD

**Issue by pierlon** [nextcloud/mail#1293]
### Question

I'm creating a feature from the `refactor/vue` branch, but I'm being bombarded with formatting errors from `eslint` and `prettier`. Should I format the files that I edit, or leave them be?

**Comment by ChristophWurst** [comment]
Hey,

sorry, my fault. @kevgathuku added the linter but we do not yet enforce it and I have not found the time to properly format all the new code. This is still on my todo.

IMO the linter/formatter config should be tweaked ab it, e.g. I don't like the indentation and how some closing tags move to a new line.

I'd therefore suggest to just do your development without caring about the formatting too much. What is it that you're working on, btw?

**Comment by kevgathuku** [comment]
I'll second what @ChristophWurst has said. We have the linter/formatter in place but haven't really enforced it yet.

@ChristophWurst if we need to tweak the rules, we can definitely go for it 👍

**Comment by ChristophWurst** [comment]
Not enforce on CI yet -> reopening

**Comment by sahalsaad** [comment]
> Not enforced on CI yet -> reopening

Isn't better to create another ticket for this? Seems like different scope from this original issue

**Comment by ChristophWurst** [comment]
No, this ticket is about formatting the code consistently and enforcing that.
