### ISSUE TITLE
No mail shows up for one account

### ISSUE THREAD

**Issue by EtienneM** [nextcloud/mail#130]
### Steps to reproduce
1. Add a mail account from my ISP (http://www.free.fr/assistance/2513.html)
2. Successfully created it

I have other accounts and they work great. 
### Expected behaviour

I should see the list of email in the inbox
### Actual behaviour

The message "No messages in this folder" shows up instead of the list of emails.
### Mail app

**Mail app version:** (see apps admin page)

**Mailserver or service:** Free.fr, french ISP (http://www.free.fr/assistance/2513.html)

**Transport security - IMAP:** SSL

**Transport security - SMTP:** SSL

**Number of accounts:** 3
### Server configuration

I am hosted by [Indie Hosters](https://indiehosters.net) so I do not have a lot of information about the servers.

**Version:** 10.0
#### Client configuration

**Browser:** Firefox

**Operating system:** Windows and Linux
##### Browser log

JS log:
<details>

```
JQMIGRATE: Migrate is installed, version 1.4.0
```

</details>

Network log:
<details>

```
GET /index.php/apps/mail/accounts/97/folders/SU5CT1g%3D/messages?from=0&to=20&filter= HTTP/1.1
Host: cloud.indie.host
User-Agent: Mozilla/5.0 (Windows NT 10.0; WOW64; rv:49.0) Gecko/20100101 Firefox/49.0
Accept: */*
Accept-Language: fr-FR,fr;q=0.8,en-US;q=0.5,en;q=0.3
Accept-Encoding: gzip, deflate, br
requesttoken: HgcedR5TEzheHyYHPCYGTjgFHiMRAwodNn1AWxYCIXI=:zkL8hbkl6Roovvp4VRHAbPclgK3ouZkKS76gXgfkAHs=
OCS-APIREQUEST: true
X-Requested-With: XMLHttpRequest
Cookie: nc_sameSiteCookielax=true; nc_sameSiteCookiestrict=true; ocgrd6wpkg2l=6b55c24da16b0121c54d9413808021e3; oc_sessionPassphrase=PNHYVp2fVSYA%2F2YBobsXKwOleyXa0eEJsUl3s2rbwFqecum6YSTHwUxCbI0bT6QVBSKpzIuDvG3oNxM1W0S3LTGLvNs6%2FVeQ9dQ2w5KFWfi%2Ft9m%2Bjv1IeNYJqKSiFoBl; SERVERID=Server
DNT: 1
Connection: keep-alive

HTTP/1.1 200 OK
Server: nginx/1.11.4
Date: Sun, 02 Oct 2016 15:24:02 GMT
Content-Type: application/json; charset=utf-8
Content-Length: 2
Connection: close
X-Powered-By: PHP/5.6.25
Expires: Thu, 19 Nov 1981 08:52:00 GMT
Pragma: no-cache
x-xss-protection: 1; mode=block
x-content-type-options: nosniff
X-Frame-Options: Sameorigin
X-Robots-Tag: none
x-download-options: noopen
X-Permitted-Cross-Domain-Policies: none
Cache-Control: no-cache, must-revalidate
Content-Security-Policy: default-src 'none';script-src 'self' 'unsafe-eval';style-src 'self' 'unsafe-inline';img-src 'self' data: blob:;font-src 'self';connect-src 'self';media-src 'self'
strict-transport-security: max-age=15768000

[]
```

</details>

**Comment by plastikschnitzer** [comment]
I have the same issue. Nothing in the error log of OC/NC Seen on web.de mailboxes. 

Maybe related to this: This error appears on mailboxes, which are already set up in the Cloud and which contain (older) emails (from cache?). 
Strange thing: The mailboxes show the error just from time to time. Any idea how I can debug it further?

**Comment by ChristophWurst** [comment]
Please [enable imap logging](https://github.com/nextcloud/mail#imap-logging), retry and post your logs here. Remove any sensitive information if necessary. This should help us localize the bug.

**Comment by plastikschnitzer** [comment]
...I enabled logging and tried to rebuild the bug but now its gone :-( :-/ :-) :-D
I will keep an eye on it. All I changed in the meantime is updating to OC 9.1.2.

**Comment by ChristophWurst** [comment]
great! :-)

**Comment by plastikschnitzer** [comment]
Unfortunately, its not gone. Now I could reproduce it with Strato. I enter a new email account, the initial messages are loaded but no more. Every time I scroll to the end of the list, is sais "error loading messages" but the mailbox contains 500+ emails.
imap maillog is empty at that day and the logging itself seems to work as the log is filled with entries.

**Comment by ChristophWurst** [comment]
Any news? Is this still valid?

**Comment by ChristophWurst** [comment]
> Any news? Is this still valid?

I'm closing this now.

**Comment by plastikschnitzer** [comment]
Could not reproduce it any more but I will keep an eye on it.

**Comment by ChristophWurst** [comment]
Thanks @plastikschnitzer

**Comment by gringo1er** [comment]
Hello. I have the same issue with the same provider (Free). I have met the same issue, few years ago with the mail owncloud version.

**Comment by ecmu** [comment]
Hello,
I also still have the same problem with this provider (free.fr). 
I remember that the solution was given by this issue : https://github.com/owncloud/mail/issues/1152
Unfortunately, owncloud/mail have been archived without the issues...

Does anyone know how to retrieve this old issue ?

**Comment by ChristophWurst** [comment]
> Does anyone know how to retrieve this old issue ?

They are gone. Onwcloud apparently decided to disable the issues and thus nobody is able to access them.

For anything else, please file a new ticket. Thanks :)
