### ISSUE TITLE
Translation Bug in Chinese UI

### ISSUE THREAD

**Issue by Milokita** [nextcloud/mail#1305]
### Expected behavior
The sentence showing auto-download of image had been stopped to protect privacy should be "以保护您的隐私 "

### Actual behavior
"以包混您的隐私" 
包混 & 保护 is a typo

### Mail app

**Mail app version:** (see apps admin page, e.g. 0.5.3)
0.8.3
**Mailserver or service:** (e.g. Outlook, Yahoo, Gmail, Exchange,...)
QQ/Tencent
**Number of accounts:** 
1

### Server configuration

**Operating system**: (e.g. Debian 8)

**Web server:** (e.g. Apache, Nginx,...)

**Database:** (e.g. MariaDB, SQLite, PostgreSQL,...)

**PHP version:** (e.g. 7.0)
7.0

**Nextcloud Version:** (see admin page, e.g. 13.0.2)

**Updated from an older version or fresh install:**
fresh 
**List of activated apps:**
```
If you have access to your command line run e.g.:
sudo -u www-data php occ app:list
from within your server installation folder
```

**The content of config/config.php:**
```
If you have access to your command line run e.g.:
sudo -u www-data php occ config:list system
from within your Nextcloud installation folder

or

Insert your config.php content here
Make sure to remove all sensitive content such as passwords. (e.g. database password, passwordsalt, secret, smtp password, …)
```

#### Client configuration
**Browser:** (e.g. Firefox 48)

**Operating system:** (e.g. Arch Linux)

##### Web server error log
```
Insert your webserver log here (e.g. /var/log/apache2/...)
```

##### Server log (data/nextcloud.log)
```
Insert your server log here
```

##### IMAP log (data/horde_imap.log)
```
Enable debug mode and insert your horde IMAP log here, see https://docs.nextcloud.com/server/13/developer_manual/general/debugging.html#debug-mode
```

##### SMTP log (data/horde_smtp.log)
```
Enable debug mode and insert your horde IMAP log here, see https://docs.nextcloud.com/server/13/developer_manual/general/debugging.html#debug-mode
```

##### Browser log
```
Insert your browser log here, this could for example include:

a) The javascript console log
b) The network log 
```

**Comment by ChristophWurst** [comment]
Hey, @Milokita!

Thanks for your feedback. This should be fixed. May I ask you to directly report/change this at https://www.transifex.com/nextcloud/nextcloud/? This is the platform where we manage translations. The changes automatically flow back to this repository, but changes here aren't possible (one way data flow).

Thanks :v:
