### ISSUE TITLE
Action on long subject

### ISSUE THREAD

**Issue by mat-m** [nextcloud/mail#1362]
### Feature Request

When a mail is displayed, it is written full and unwrapped.
Although the full title is available in the hover box, mail still displays it full.

When the mail is HTML limited-width and centered, and the subject is 261 chars long, I could not see the mail content. And since there is no scrollbar, I could not see there was contents.

#### Summary

I have many options, but I don't know which one is better:

* Truncate the title to the message panel width, since we have it full in the hover
* Truncate with an ellipsis link to show it fully (and wrapped)
* Do not truncate but wrap it

**Comment by ChristophWurst** [comment]
How's that a feature request? Isn't this a bug?

Could you please provide a screenshots? That makes understanding and reproducing such tickets a lot easier. Thank you :v:

**Comment by ChristophWurst** [comment]
What's the issue now? The popover or the subject in the right column?
