### ISSUE TITLE
Undefined index: id at contactsintegration.php#55

### ISSUE THREAD

**Issue by MorrisJobke** [nextcloud/mail#138]
I see many of those errors:

```
Undefined index: id at apps/mail/lib/service/contactsintegration.php#55
```

See https://github.com/nextcloud/mail/blob/eb298be5c807b643d678e443065a181e858d5fb5/lib/service/contactsintegration.php#L55

It was triggered by @ChristophWurst via: `/apps/mail/autoComplete?term=christoph%40`

@ChristophWurst could you have a look at this?

**Comment by MorrisJobke** [comment]
@ChristophWurst I still see this in the logs ;)

**Comment by ChristophWurst** [comment]
This was apparently changed/fixed by @skjnldsv already: https://github.com/nextcloud/mail/commit/f04992fa5de7518ca5fccb883aa22b79520fbcbf

@skjnldsv do you remember why you changed it? Did you fix this issue?

**Comment by skjnldsv** [comment]
because we use uid and not id in the vcard guidelines iirc :)

**Comment by ChristophWurst** [comment]
alright, so I assume we can close this issue then. Thanks.
