### ISSUE TITLE
Autodetect failed

### ISSUE THREAD

**Issue by ppigmans** [nextcloud/mail#1380]
### Question

We are trying to add a mail account of a custom mail server we host, yet we always get Autodetect failed.
We tried with Gmail, that works, Hotmail/outlook doesnt, outlook too gets Autodetect failed.

**Comment by ChristophWurst** [comment]
Hi,

please use https://github.com/nextcloud/mail/issues/new?assignees=&labels=bug%2C+0.+to+triage&template=bug.md&title= and provide the info you're asked for, especially the logs. THanks.
