### ISSUE TITLE
Mail Server Error when sending email 

### ISSUE THREAD

**Issue by kdmitriy** [nextcloud/mail#1385]
### Expected behavior
Mail to be sent successfully.

### Actual behavior
Server Error reported when sending a message. Email does not get delivered. Receiving emails work and no issue with the auth, however fails at sending emails.

### Mail app

**Mail app version:** (see apps admin page, e.g. 0.5.3)
0.11.0
**Mailserver or service:** (e.g. Outlook, Yahoo, Gmail, Exchange,...)
Outlook/Yahoo

**Number of accounts:** (e.g. 1 or 2)
2

### Server configuration

**Operating system**: (e.g. Debian 8)

**Web server:** (e.g. Apache, Nginx,...)
Apache

**Database:** (e.g. MariaDB, SQLite, PostgreSQL,...)
MariaDB

**PHP version:** (e.g. 7.0)
7.2

**Nextcloud Version:** (see admin page, e.g. 13.0.2)
14.0.4

**Updated from an older version or fresh install:**
Fresh Install
**List of activated apps:**
```
If you have access to your command line run e.g.:
sudo -u www-data php occ app:list
from within your server installation folder
```

  - accessibility: 1.0.1
  - activity: 2.7.0
  - calendar: 1.6.4
  - checksum: 0.4.1
  - cloud_federation_api: 0.0.1
  - comments: 1.4.0
  - dav: 1.6.0
  - encryption: 2.2.0
  - end_to_end_encryption: 1.0.5
  - event_update_notification: 0.3.1
  - federatedfilesharing: 1.4.0
  - federation: 1.4.0
  - files: 1.9.0
  - files_accesscontrol: 1.4.0
  - files_external: 1.5.0
  - files_pdfviewer: 1.3.2
  - files_sharing: 1.6.2
  - files_texteditor: 2.6.0
  - files_versions: 1.7.1
  - files_videoplayer: 1.3.0
  - firstrunwizard: 2.3.0
  - gallery: 18.1.0
  - logreader: 2.0.0
  - lookup_server_connector: 1.2.0
  - mail: 0.11.0
  - nextcloud_announcements: 1.3.0
  - notes: 2.5.1
  - notifications: 2.2.1
  - oauth2: 1.2.1
  - ownpad: 0.6.9
  - password_policy: 1.4.0
  - passwords: 2018.12.0
  - provisioning_api: 1.4.0
  - qownnotesapi: 18.11.0
  - serverinfo: 1.4.0
  - sharebymail: 1.4.0
  - support: 1.0.0
  - survey_client: 1.2.0
  - systemtags: 1.4.0
  - tasks: 0.9.8
  - theming: 1.5.0
  - twofactor_backupcodes: 1.3.1
  - twofactor_totp: 1.5.0
  - updatenotification: 1.4.1
  - workflowengine: 1.4.0
Disabled:
  - admin_audit
  - files_trashbin
  - groupfolders
  - onlyoffice
  - user_external
  - user_ldap

**The content of config/config.php:**
```
`
    0 => 'localhost',
    1 => '192.168.4.12',
    2 => 'cloud.domain.com',
    3 => 'office.domain.com',
    4 => '192.168.3.13',
  ),
  'datadirectory' => '/var/www/nextcloud/data',
  'dbtype' => 'mysql',
  'version' => '14.0.4.2',
  'overwrite.cli.url' => 'https://cloud.domain.com/',
  'dbname' => 'nextcloud',
  'dbhost' => 'localhost',
  'dbport' => '',
  'dbtableprefix' => 'oc_',
  'dbuser' => 'snipped,
  'dbpassword' => snipped',
  'installed' => true,
  'maintenance' => false,
  'onlyoffice' =>
  array (
          'verify_peer_off' => TRUE,
  ),
);

`
#### Client configuration
**Browser:** (e.g. Firefox 48)
Firefox, Chrome
**Operating system:** (e.g. Arch Linux)
Ubuntu 18.0.4
#### Logs
##### Web server error log
```
`
[Wed Dec 12 06:25:02.563675 2018] [ssl:warn] [pid 23645] AH01909: domain.com:443:0 server certificate does NOT include an ID which matches the server name
[Wed Dec 12 06:25:02.564685 2018] [mpm_prefork:notice] [pid 23645] AH00163: Apache/2.4.29 (Ubuntu) OpenSSL/1.1.1 configured -- resuming normal operations
[Wed Dec 12 06:25:02.564697 2018] [core:notice] [pid 23645] AH00094: Command line: '/usr/sbin/apache2'
[Wed Dec 12 09:28:07.282180 2018] [php7:error] [pid 45925] [client 172.16.20.101:61909] PHP Fatal error:  Uncaught Error: Call to a member function getLogger() on null in /var/www/nextcloud/index.php:72\nStack trace:\n#0 {main}\n  thrown in /var/www/nextcloud/index.php on line 72
[Wed Dec 12 09:28:07.282455 2018] [php7:error] [pid 46611] [client 172.16.20.101:61910] PHP Fatal error:  Uncaught Error: Call to a member function getLogger() on null in /var/www/nextcloud/index.php:72\nStack trace:\n#0 {main}\n  thrown in /var/www/nextcloud/index.php on line 72
[Wed Dec 12 09:28:10.100686 2018] [mpm_prefork:notice] [pid 23645] AH00169: caught SIGTERM, shutting down
[Wed Dec 12 09:28:10.218229 2018] [ssl:warn] [pid 47101] AH01909: domain.com:443:0 server certificate does NOT include an ID which matches the server name
[Wed Dec 12 09:28:10.310547 2018] [ssl:warn] [pid 47114] AH01909: domain.com:443:0 server certificate does NOT include an ID which matches the server name
[Wed Dec 12 09:28:10.320359 2018] [mpm_prefork:notice] [pid 47114] AH00163: Apache/2.4.29 (Ubuntu) OpenSSL/1.1.1 configured -- resuming normal operations
[Wed Dec 12 09:28:10.320401 2018] [core:notice] [pid 47114] AH00094: Command line: '/usr/sbin/apache2'
[Wed Dec 12 09:28:20.396321 2018] [php7:error] [pid 47118] [client 172.16.20.101:61913] PHP Fatal error:  Uncaught Error: Call to a member function getLogger() on null in /var/www/nextcloud/index.php:72\nStack trace:\n#0 {main}\n  thrown in /var/www/nextcloud/index.php on line 72
[Wed Dec 12 09:28:21.396669 2018] [php7:error] [pid 47119] [client 172.16.20.101:61914] PHP Fatal error:  Uncaught Error: Call to a member function getLogger() on null in /var/www/nextcloud/index.php:72\nStack trace:\n#0 {main}\n  thrown in /var/www/nextcloud/index.php on line 72
[Wed Dec 12 09:28:23.877508 2018] [php7:emerg] [pid 47120] [client 172.16.20.101:61915] PHP Parse error:  syntax error, unexpected ''app.mail.imap.timeout'' (T_CONSTANT_ENCAPSED_STRING), expecting ')' in /var/www/nextcloud/config/config.php on line 27
[Wed Dec 12 09:28:24.124331 2018] [php7:error] [pid 47123] [client 172.16.20.101:61916] PHP Fatal error:  Uncaught Error: Call to a member function getLogger() on null in /var/www/nextcloud/index.php:72\nStack trace:\n#0 {main}\n  thrown in /var/www/nextcloud/index.php on line 72
[Wed Dec 12 09:28:25.418579 2018] [php7:error] [pid 47125] [client 172.16.20.101:61917] PHP Fatal error:  Uncaught Error: Call to a member function getLogger() on null in /var/www/nextcloud/index.php:72\nStack trace:\n#0 {main}\n  thrown in /var/www/nextcloud/index.php on line 72
[Wed Dec 12 09:28:26.462832 2018] [php7:error] [pid 47118] [client 172.16.20.101:61918] PHP Fatal error:  Uncaught Error: Call to a member function getLogger() on null in /var/www/nextcloud/index.php:72\nStack trace:\n#0 {main}\n  thrown in /var/www/nextcloud/index.php on line 72
[Wed Dec 12 09:28:27.927246 2018] [php7:error] [pid 47120] [client 172.16.20.101:61920] PHP Fatal error:  Uncaught Error: Call to a member function getLogger() on null in /var/www/nextcloud/index.php:72\nStack trace:\n#0 {main}\n  thrown in /var/www/nextcloud/index.php on line 72
[Wed Dec 12 09:28:28.141684 2018] [php7:error] [pid 47119] [client 172.16.20.101:61919] PHP Fatal error:  Uncaught Error: Call to a member function getLogger() on null in /var/www/nextcloud/index.php:72\nStack trace:\n#0 {main}\n  thrown in /var/www/nextcloud/index.php on line 72
[Wed Dec 12 09:28:34.914374 2018] [php7:error] [pid 47123] [client 172.16.20.101:61921] PHP Fatal error:  Uncaught Error: Call to a member function getLogger() on null in /var/www/nextcloud/index.php:72\nStack trace:\n#0 {main}\n  thrown in /var/www/nextcloud/index.php on line 72
[Wed Dec 12 09:28:35.039238 2018] [php7:error] [pid 47125] [client 172.16.20.101:61922] PHP Fatal error:  Uncaught Error: Call to a member function getLogger() on null in /var/www/nextcloud/index.php:72\nStack trace:\n#0 {main}\n  thrown in /var/www/nextcloud/index.php on line 72
[Wed Dec 12 09:28:35.559764 2018] [php7:error] [pid 47118] [client 172.16.20.101:61924] PHP Fatal error:  Uncaught Error: Call to a member function getLogger() on null in /var/www/nextcloud/index.php:72\nStack trace:\n#0 {main}\n  thrown in /var/www/nextcloud/index.php on line 72
[Wed Dec 12 09:28:35.673520 2018] [php7:error] [pid 47120] [client 172.16.20.101:61923] PHP Fatal error:  Uncaught Error: Call to a member function getLogger() on null in /var/www/nextcloud/index.php:72\nStack trace:\n#0 {main}\n  thrown in /var/www/nextcloud/index.php on line 72
[Wed Dec 12 09:28:36.272325 2018] [php7:error] [pid 47119] [client 172.16.20.101:61926] PHP Fatal error:  Uncaught Error: Call to a member function getLogger() on null in /var/www/nextcloud/index.php:72\nStack trace:\n#0 {main}\n  thrown in /var/www/nextcloud/index.php on line 72
[Wed Dec 12 09:28:36.372428 2018] [php7:error] [pid 47123] [client 172.16.20.101:61925] PHP Fatal error:  Uncaught Error: Call to a member function getLogger() on null in /var/www/nextcloud/index.php:72\nStack trace:\n#0 {main}\n  thrown in /var/www/nextcloud/index.php on line 72
[Wed Dec 12 09:30:26.252234 2018] [mpm_prefork:notice] [pid 47114] AH00169: caught SIGTERM, shutting down
[Wed Dec 12 09:30:26.374993 2018] [ssl:warn] [pid 47154] AH01909: domain.com:443:0 server certificate does NOT include an ID which matches the server name
[Wed Dec 12 09:30:26.467529 2018] [ssl:warn] [pid 47166] AH01909: domain.com:443:0 server certificate does NOT include an ID which matches the server name
[Wed Dec 12 09:30:26.477471 2018] [mpm_prefork:notice] [pid 47166] AH00163: Apache/2.4.29 (Ubuntu) OpenSSL/1.1.1 configured -- resuming normal operations
[Wed Dec 12 09:30:26.477521 2018] [core:notice] [pid 47166] AH00094: Command line: '/usr/sbin/apache2'
[Wed Dec 12 09:30:32.185812 2018] [php7:error] [pid 47171] [client 172.16.20.101:61938] PHP Fatal error:  Uncaught Error: Call to a member function getLogger() on null in /var/www/nextcloud/index.php:72\nStack trace:\n#0 {main}\n  thrown in /var/www/nextcloud/index.php on line 72
[Wed Dec 12 09:30:32.390082 2018] [php7:error] [pid 47172] [client 172.16.20.101:61939] PHP Fatal error:  Uncaught Error: Call to a member function getLogger() on null in /var/www/nextcloud/index.php:72\nStack trace:\n#0 {main}\n  thrown in /var/www/nextcloud/index.php on line 72
[Wed Dec 12 09:30:33.546152 2018] [php7:error] [pid 47176] [client 172.16.20.101:61942] PHP Fatal error:  Uncaught Error: Call to a member function getLogger() on null in /var/www/nextcloud/index.php:72\nStack trace:\n#0 {main}\n  thrown in /var/www/nextcloud/index.php on line 72
[Wed Dec 12 09:30:33.651345 2018] [php7:error] [pid 47173] [client 172.16.20.101:61943] PHP Fatal error:  Uncaught Error: Call to a member function getLogger() on null in /var/www/nextcloud/index.php:72\nStack trace:\n#0 {main}\n  thrown in /var/www/nextcloud/index.php on line 72
[Wed Dec 12 09:31:12.532222 2018] [mpm_prefork:notice] [pid 47166] AH00169: caught SIGTERM, shutting down
[Wed Dec 12 09:31:12.655569 2018] [ssl:warn] [pid 47203] AH01909: domain.com:443:0 server certificate does NOT include an ID which matches the server name
[Wed Dec 12 09:31:12.749566 2018] [ssl:warn] [pid 47214] AH01909: domain.com:443:0 server certificate does NOT include an ID which matches the server name
[Wed Dec 12 09:31:12.759268 2018] [mpm_prefork:notice] [pid 47214] AH00163: Apache/2.4.29 (Ubuntu) OpenSSL/1.1.1 configured -- resuming normal operations
[Wed Dec 12 09:31:12.759317 2018] [core:notice] [pid 47214] AH00094: Command line: '/usr/sbin/apache2'
`
```

##### Server log (data/nextcloud.log)
```
`
Error | mail | Horde_Imap_Client_Exception: Mail server denied authentication./var/www/nextcloud/apps/mail/vendor/pear-pear.horde.org/Horde_Imap_Client/Horde/Imap/Client/Base.php - line 833: Horde_Imap_Client_Socket->_login("*** sensiti ... *")/var/www/nextcloud/apps/mail/vendor/pear-pear.horde.org/Horde_Imap_Client/Horde/Imap/Client/Base.php - line 1593: Horde_Imap_Client_Base->login("*** sensiti ... *")/var/www/nextcloud/apps/mail/vendor/pear-pear.horde.org/Horde_Imap_Client/Horde/Imap/Client/Base.php - line 4033: Horde_Imap_Client_Base->status(Horde_Imap_Client_Mailbox {}, 8713)/var/www/nextcloud/apps/mail/vendor/pear-pear.horde.org/Horde_Imap_Client/Horde/Imap/Client/Base.php - line 3627: Horde_Imap_Client_Base->_syncStatus(Horde_Imap_Client_Mailbox {})/var/www/nextcloud/apps/mail/lib/IMAP/Sync/Synchronizer.php - line 61: Horde_Imap_Client_Base->sync(Horde_Imap_Client_Mailbox {}, "U339738,V1344528618,M6768", { ids: Horde ... }})/var/www/nextcloud/apps/mail/lib/Service/MailManager.php - line 104: OCA\Mail\IMAP\Sync\Synchronizer->sync(Horde_Imap_C ... e}, OCA\Mail\IMAP\Sync\Request {})/var/www/nextcloud/apps/mail/lib/Controller/FoldersController.php - line 100: OCA\Mail\Service\MailManager->syncMessages(OCA\Mail\Account {}, OCA\Mail\IMAP\Sync\Request {})/var/www/nextcloud/lib/private/AppFramework/Http/Dispatcher.php - line 166: OCA\Mail\Controller\FoldersController->sync(1, "SU5CT1g=", "VTMzOTczOCx ... =", [ "339737"," ... "])/var/www/nextcloud/lib/private/AppFramework/Http/Dispatcher.php - line 99: OC\AppFramework\Http\Dispatcher->executeController(OCA\Mail\Con ... {}, "sync")/var/www/nextcloud/lib/private/AppFramework/App.php - line 118: OC\AppFramework\Http\Dispatcher->dispatch(OCA\Mail\Con ... {}, "sync")/var/www/nextcloud/lib/private/AppFramework/Routing/RouteActionHandler.php - line 47: OC\AppFramework\App::main("OCA\\Mail\\ ... r", "sync", OC\AppFramew ... {}, { accountId: ... "})OC\AppFramework\Routing\RouteActionHandler->__invoke({ accountId: ... "})/var/www/nextcloud/lib/private/Route/Router.php - line 297: call_user_func(OC\AppFramew ... {}, { accountId: ... "})/var/www/nextcloud/lib/base.php - line 987: OC\Route\Router->match("/apps/mail/ ... c")/var/www/nextcloud/index.php - line 42: OC::handleRequest() | 7 minutes ago
-- | -- | -- | --
Error | mail | Horde_Imap_Client_Exception: Mail server denied authentication./var/www/nextcloud/apps/mail/vendor/pear-pear.horde.org/Horde_Imap_Client/Horde/Imap/Client/Base.php - line 833: Horde_Imap_Client_Socket->_login("*** sensiti ... *")/var/www/nextcloud/apps/mail/vendor/pear-pear.horde.org/Horde_Imap_Client/Horde/Imap/Client/Base.php - line 1593: Horde_Imap_Client_Base->login("*** sensiti ... *")/var/www/nextcloud/apps/mail/vendor/pear-pear.horde.org/Horde_Imap_Client/Horde/Imap/Client/Base.php - line 4033: Horde_Imap_Client_Base->status(Horde_Imap_Client_Mailbox {}, 8713)/var/www/nextcloud/apps/mail/vendor/pear-pear.horde.org/Horde_Imap_Client/Horde/Imap/Client/Base.php - line 3627: Horde_Imap_Client_Base->_syncStatus(Horde_Imap_Client_Mailbox {})/var/www/nextcloud/apps/mail/lib/IMAP/Sync/Synchronizer.php - line 61: Horde_Imap_Client_Base->sync(Horde_Imap_Client_Mailbox {}, "U339737,V1344528618,M6767", { ids: Horde ... }})/var/www/nextcloud/apps/mail/lib/Service/MailManager.php - line 104: OCA\Mail\IMAP\Sync\Synchronizer->sync(Horde_Imap_C ... e}, OCA\Mail\IMAP\Sync\Request {})/var/www/nextcloud/apps/mail/lib/Controller/FoldersController.php - line 100: OCA\Mail\Service\MailManager->syncMessages(OCA\Mail\Account {}, OCA\Mail\IMAP\Sync\Request {})/var/www/nextcloud/lib/private/AppFramework/Http/Dispatcher.php - line 166: OCA\Mail\Controller\FoldersController->sync(1, "SU5CT1g=", "VTMzOTczNyx ... =", [ "339736"," ... "])/var/www/nextcloud/lib/private/AppFramework/Http/Dispatcher.php - line 99: OC\AppFramework\Http\Dispatcher->executeController(OCA\Mail\Con ... {}, "sync")/var/www/nextcloud/lib/private/AppFramework/App.php - line 118: OC\AppFramework\Http\Dispatcher->dispatch(OCA\Mail\Con ... {}, "sync")/var/www/nextcloud/lib/private/AppFramework/Routing/RouteActionHandler.php - line 47: OC\AppFramework\App::main("OCA\\Mail\\ ... r", "sync", OC\AppFramew ... {}, { accountId: ... "})OC\AppFramework\Routing\RouteActionHandler->__invoke({ accountId: ... "})/var/www/nextcloud/lib/private/Route/Router.php - line 297: call_user_func(OC\AppFramew ... {}, { accountId: ... "})/var/www/nextcloud/lib/base.php - line 987: OC\Route\Router->match("/apps/mail/ ... c")/var/www/nextcloud/index.php - line 42: OC::handleRequest() | 11 minutes ago
Error | mail | Horde_Imap_Client_Exception: Error when communicating with the mail server./var/www/nextcloud/apps/mail/vendor/pear-pear.horde.org/Horde_Imap_Client/Horde/Imap/Client/Socket.php - line 4537: Horde_Imap_Client_Socket_Connection_Socket->read()/var/www/nextcloud/apps/mail/vendor/pear-pear.horde.org/Horde_Imap_Client/Horde/Imap/Client/Socket.php - line 4309: Horde_Imap_Client_Socket->_getLine(Horde_Imap_C ... }})/var/www/nextcloud/apps/mail/vendor/pear-pear.horde.org/Horde_Imap_Client/Horde/Imap/Client/Socket.php - line 4237: Horde_Imap_Client_Socket->_sendCmdChunk(Horde_Imap_C ... }}, [ Horde_Imap ... }])/var/www/nextcloud/apps/mail/vendor/pear-pear.horde.org/Horde_Imap_Client/Horde/Imap/Client/Socket.php - line 1231: Horde_Imap_Client_Socket->_sendCmd(Horde_Imap_C ... }})/var/www/nextcloud/apps/mail/vendor/pear-pear.horde.org/Horde_Imap_Client/Horde/Imap/Client/Base.php - line 1046: Horde_Imap_Client_Socket->_openMailbox(Horde_Imap_Client_Mailbox {}, 1)/var/www/nextcloud/apps/mail/vendor/pear-pear.horde.org/Horde_Imap_Client/Horde/Imap/Client/Base.php - line 2803: Horde_Imap_Client_Base->openMailbox(Horde_Imap_Client_Mailbox {}, 1)/var/www/nextcloud/apps/mail/vendor/pear-pear.horde.org/Horde_Imap_Client/Horde/Imap/Client/Data/Sync.php - line 244: Horde_Imap_Client_Base->vanished(Horde_Imap_Client_Mailbox {}, 1, { ids: Horde ... }})/var/www/nextcloud/apps/mail/vendor/pear-pear.horde.org/Horde_Imap_Client/Horde/Imap/Client/Base.php - line 3629: Horde_Imap_Client_Data_Sync->__construct(Horde_Imap_C ... e}, Horde_Imap_Client_Mailbox {}, { U: "339737 ... "}, { U: 339737, ... 7}, 64, Horde_Imap_C ... e})/var/www/nextcloud/apps/mail/lib/IMAP/Sync/Synchronizer.php - line 61: Horde_Imap_Client_Base->sync(Horde_Imap_Client_Mailbox {}, "U339737,V1344528618,M6767", { ids: Horde ... }})/var/www/nextcloud/apps/mail/lib/Service/MailManager.php - line 104: OCA\Mail\IMAP\Sync\Synchronizer->sync(Horde_Imap_C ... e}, OCA\Mail\IMAP\Sync\Request {})/var/www/nextcloud/apps/mail/lib/Controller/FoldersController.php - line 100: OCA\Mail\Service\MailManager->syncMessages(OCA\Mail\Account {}, OCA\Mail\IMAP\Sync\Request {})/var/www/nextcloud/lib/private/AppFramework/Http/Dispatcher.php - line 166: OCA\Mail\Controller\FoldersController->sync(1, "SU5CT1g=", "VTMzOTczNyx ... =", [ "339736"," ... "])/var/www/nextcloud/lib/private/AppFramework/Http/Dispatcher.php - line 99: OC\AppFramework\Http\Dispatcher->executeController(OCA\Mail\Con ... {}, "sync")/var/www/nextcloud/lib/private/AppFramework/App.php - line 118: OC\AppFramework\Http\Dispatcher->dispatch(OCA\Mail\Con ... {}, "sync")/var/www/nextcloud/lib/private/AppFramework/Routing/RouteActionHandler.php - line 47: OC\AppFramework\App::main("OCA\\Mail\\ ... r", "sync", OC\AppFramew ... {}, { accountId: ... "})OC\AppFramework\Routing\RouteActionHandler->__invoke({ accountId: ... "})/var/www/nextcloud/lib/private/Route/Router.php - line 297: call_user_func(OC\AppFramew ... {}, { accountId: ... "})/var/www/nextcloud/lib/base.php - line 987: OC\Route\Router->match("/apps/mail/ ... c")/var/www/nextcloud/index.php - line 42: OC::handleRequest() | 18 minutes ago
Error | mail | Horde_Imap_Client_Exception_ServerResponse: IMAP error reported by server./var/www/nextcloud/apps/mail/vendor/pear-pear.horde.org/Horde_Imap_Client/Horde/Imap/Client/Socket.php - line 4309: Horde_Imap_Client_Socket->_getLine(Horde_Imap_C ... }})/var/www/nextcloud/apps/mail/vendor/pear-pear.horde.org/Horde_Imap_Client/Horde/Imap/Client/Socket.php - line 4230: Horde_Imap_Client_Socket->_sendCmdChunk(Horde_Imap_C ... }}, [ Horde_Imap ... }])/var/www/nextcloud/apps/mail/vendor/pear-pear.horde.org/Horde_Imap_Client/Horde/Imap/Client/Socket.php - line 1941: Horde_Imap_Client_Socket->_sendCmd(Horde_Imap_C ... "})/var/www/nextcloud/apps/mail/vendor/pear-pear.horde.org/Horde_Imap_Client/Horde/Imap/Client/Base.php - line 1841: Horde_Imap_Client_Socket->_append(Horde_Imap_Client_Mailbox {}, [ { data: "F ... }], [])/var/www/nextcloud/apps/mail/lib/Mailbox.php - line 434: Horde_Imap_Client_Base->append(Horde_Imap_Client_Mailbox {}, [ { data: "F ... }])/var/www/nextcloud/apps/mail/lib/Account.php - line 220: OCA\Mail\Mailbox->saveMessage("From: Yahoo ... t", [ "\\seen"])/var/www/nextcloud/apps/mail/lib/Service/MailTransmission.php - line 116: OCA\Mail\Account->sendMessage(OCA\Mail\Model\Message {}, Horde_Mail_T ... "}, 0)/var/www/nextcloud/apps/mail/lib/Controller/AccountsController.php - line 277: OCA\Mail\Service\MailTransmission->sendMessage("user", OCA\Mail\Mod ... {}, OCA\Mail\Mod ... {}, null, 0)/var/www/nextcloud/lib/private/AppFramework/Http/Dispatcher.php - line 166: OCA\Mail\Controller\AccountsController->send(1, "test", "test", "email@yahoo.com", "", "", 0, null, null, [], 0)/var/www/nextcloud/lib/private/AppFramework/Http/Dispatcher.php - line 99: OC\AppFramework\Http\Dispatcher->executeController(OCA\Mail\Con ... {}, "send")/var/www/nextcloud/lib/private/AppFramework/App.php - line 118: OC\AppFramework\Http\Dispatcher->dispatch(OCA\Mail\Con ... {}, "send")/var/www/nextcloud/lib/private/AppFramework/Routing/RouteActionHandler.php - line 47: OC\AppFramework\App::main("OCA\\Mail\\ ... r", "send", OC\AppFramew ... {}, { accountId: ... "})OC\AppFramework\Routing\RouteActionHandler->__invoke({ accountId: ... "})/var/www/nextcloud/lib/private/Route/Router.php - line 297: call_user_func(OC\AppFramew ... {}, { accountId: ... "})/var/www/nextcloud/lib/base.php - line 987: OC\Route\Router->match("/apps/mail/ ... d")/var/www/nextcloud/index.php - line 42: OC::handleRequest() | 19 minutes ago
Error | mail | Sending mail failed: IMAP error reported by server. | 19 minutes ago
Error | mail | OCA\Mail\Exception\ServiceException: Could not save draft message/var/www/nextcloud/apps/mail/lib/Controller/AccountsController.php - line 309: OCA\Mail\Service\MailTransmission->saveDraft(OCA\Mail\Mod ... {}, 0)/var/www/nextcloud/lib/private/AppFramework/Http/Dispatcher.php - line 166: OCA\Mail\Controller\AccountsController->draft(1, "test", "test", "email@yahoo.com", "", "", 0)/var/www/nextcloud/lib/private/AppFramework/Http/Dispatcher.php - line 99: OC\AppFramework\Http\Dispatcher->executeController(OCA\Mail\Con ... {}, "draft")/var/www/nextcloud/lib/private/AppFramework/App.php - line 118: OC\AppFramework\Http\Dispatcher->dispatch(OCA\Mail\Con ... {}, "draft")/var/www/nextcloud/lib/private/AppFramework/Routing/RouteActionHandler.php - line 47: OC\AppFramework\App::main("OCA\\Mail\\ ... r", "draft", OC\AppFramew ... {}, { accountId: ... "})OC\AppFramework\Routing\RouteActionHandler->__invoke({ accountId: ... "})/var/www/nextcloud/lib/private/Route/Router.php - line 297: call_user_func(OC\AppFramew ... {}, { accountId: ... "})/var/www/nextcloud/lib/base.php - line 987: OC\Route\Router->match("/apps/mail/ ... t")/var/www/nextcloud/index.php - line 42: OC::handleRequest()Cased by Horde_Imap_Client_Exception_ServerResponse: IMAP error reported by server./var/www/nextcloud/apps/mail/vendor/pear-pear.horde.org/Horde_Imap_Client/Horde/Imap/Client/Socket.php - line 4309: Horde_Imap_Client_Socket->_getLine(Horde_Imap_C ... }})/var/www/nextcloud/apps/mail/vendor/pear-pear.horde.org/Horde_Imap_Client/Horde/Imap/Client/Socket.php - line 4230: Horde_Imap_Client_Socket->_sendCmdChunk(Horde_Imap_C ... }}, [ Horde_Imap ... }])/var/www/nextcloud/apps/mail/vendor/pear-pear.horde.org/Horde_Imap_Client/Horde/Imap/Client/Socket.php - line 1941: Horde_Imap_Client_Socket->_sendCmd(Horde_Imap_C ... "})/var/www/nextcloud/apps/mail/vendor/pear-pear.horde.org/Horde_Imap_Client/Horde/Imap/Client/Base.php - line 1841: Horde_Imap_Client_Socket->_append(Horde_Imap_Client_Mailbox {}, [ { data: "F ... }], [])/var/www/nextcloud/apps/mail/lib/Mailbox.php - line 455: Horde_Imap_Client_Base->append(Horde_Imap_Client_Mailbox {}, [ { data: "F ... }])/var/www/nextcloud/apps/mail/lib/Account.php - line 258: OCA\Mail\Mailbox->saveDraft("From: Yahoo ... t")/var/www/nextcloud/apps/mail/lib/Service/MailTransmission.php - line 147: OCA\Mail\Account->saveDraft(OCA\Mail\Model\Message {}, 0)/var/www/nextcloud/apps/mail/lib/Controller/AccountsController.php - line 309: OCA\Mail\Service\MailTransmission->saveDraft(OCA\Mail\Mod ... {}, 0)/var/www/nextcloud/lib/private/AppFramework/Http/Dispatcher.php - line 166: OCA\Mail\Controller\AccountsController->draft(1, "test", "test", "email@yahoo.com", "", "", 0)/var/www/nextcloud/lib/private/AppFramework/Http/Dispatcher.php - line 99: OC\AppFramework\Http\Dispatcher->executeController(OCA\Mail\Con ... {}, "draft")/var/www/nextcloud/lib/private/AppFramework/App.php - line 118: OC\AppFramework\Http\Dispatcher->dispatch(OCA\Mail\Con ... {}, "draft")/var/www/nextcloud/lib/private/AppFramework/Routing/RouteActionHandler.php - line 47: OC\AppFramework\App::main("OCA\\Mail\\ ... r", "draft", OC\AppFramew ... {}, { accountId: ... "})OC\AppFramework\Routing\RouteActionHandler->__invoke({ accountId: ... "})/var/www/nextcloud/lib/private/Route/Router.php - line 297: call_user_func(OC\AppFramew ... {}, { accountId: ... "})/var/www/nextcloud/lib/base.php - line 987: OC\Route\Router->match("/apps/mail/ ... t")/var/www/nextcloud/index.php - line 42: OC::handleRequest() | 20 minutes ago
Error | mail | Saving draft failed: Could not save draft message
`
```

##### IMAP log (data/horde_imap.log)
```
Enable debug mode and insert your horde IMAP log here, see https://docs.nextcloud.com/server/13/developer_manual/general/debugging.html#debug-mode
```

##### SMTP log (data/horde_smtp.log)
```
Enable debug mode and insert your horde IMAP log here, see https://docs.nextcloud.com/server/13/developer_manual/general/debugging.html#debug-mode
```

##### Browser log
```
N/A
```

**Comment by ChristophWurst** [comment]
> Mail server denied authentication.

I assume something's not working with SMTP although IMAP is fine.

**Comment by kdmitriy** [comment]
It's interesting because incoming emails are working, however just appears to be an issue with outgoing mail

**Comment by kdmitriy** [comment]
Any updates on this?

**Comment by kevin147147** [comment]
Same problem here. I used the automatic email setup, which seemed to work fine since the account get created and receives mail. I tried sending mail and it failed.

My second try was manual setup (setting smtp by hand). This then failed at account creation.

**Comment by northorsouth** [comment]
I'm getting the same "mail server denied authentication" error in the browser console when I try and add my Outlook account. I created issue 2059.
