### ISSUE TITLE
Nextcloud 14 failed to share by mail - 403

### ISSUE THREAD

**Issue by vipera7** [nextcloud/mail#1388]
### Expected behavior
I want to share folders and files throught email.

### Actual behavior
I can't share files and folders, I have the error :
`POST https://DOMAIN/files/ocs/v2.php/apps/files_sharing/api/v1/shares?format=json 403 (Forbidden)`

### Server configuration

**Operating system**: (e.g. Debian 8)
CentOS 6.10

**Web server:** 
Apache

**Database:**
MariaDB

**PHP version:**
7.1.23

**Nextcloud Version:** 
14.0.4

**Updated from an older version or fresh install:**
Fresh install

**List of activated apps:**
```
If you have access to your command line run e.g.:
sudo -u www-data php occ app:list
from within your server installation folder
```

**The content of config/config.php:**
```

<?php
$CONFIG = array (
  'passwordsalt' => 'SALT',
  'secret' => 'SECRET',
  'trusted_domains' =>
  array (
    0 => 'DOMAIN',
  ),
  'datadirectory' => '/var/www/html/files/data',
  'overwrite.cli.url' => 'https://DOMAIN/files',
  'dbtype' => 'mysql',
  'version' => '14.0.4.2',
  'integrity.check.disabled' => true,
  'dbname' => 'nextcloud',
  'dbhost' => 'HOST',
  'dbport' => '',
  'dbtableprefix' => 'oc_',
  'dbuser' => 'nc_user',
  'dbpassword' => 'PASS',
  'logtimezone' => 'UTC',
  'installed' => true,
  'memcache.local' => '\\OC\\Memcache\\Redis',
  'memcache.locking' => '\\OC\\Memcache\\Redis',
  'redis' =>
  array (
    'host' => 'HOST',
    'port' => PORT,
    'password' => PASS',
  ),
  'mail_smtpmode' => 'sendmail',
  'mail_from_address' => 'noreply',
  'mail_domain' => 'DOMAIN',
  'knowledgebaseenabled' => false,
  0 => 18,
  'loglevel' => 1,
  'maintenance' => false,
  'instanceid' => 'ID',
);



```
#### Client configuration
**Browser:**
CHROME 
**Operating system:** 
WINDOWS 7
```

**Comment by ChristophWurst** [comment]
Hi,

you're reporting a problem with a feature of the Nextcloud server. May I ask you to open a ticket at https://github.com/nextcloud/server/issues/new?labels=bug%2C+0.+Needs+triage&template=Bug_report.md instead? Thanks a lot!

Please make sure you give us the information that is asked for in the template. This makes it a lot easier for other to reproduce the problem.
