### ISSUE TITLE
General Settings (e.g. top/bottom-replies)

### ISSUE THREAD

**Issue by Quix0r** [nextcloud/mail#14]
The application currently only allows top-replies which are considered by most people as egositic. It also turns the conversation flow up-side-down. Maybe still some people want to have top-replies (I was told by a German employer that top-replies are needed in "business mails", bla bla bla) so best option is to provide settings to configure it.

Also other common options (e.g. Thunderbird has) should be included.

**Comment by ChristophWurst** [comment]
> It also turns the conversation flow up-side-down.

Hm, that actually makes sense cc @jancborchardt

**Comment by zeugmatis** [comment]
Although I don't like top-replies either, in favor of inline - yes, most business types are going to top reply in their workflow.  Trying to convince them otherwise is a waste of time, it is what people have become used to using Outlook for decades now.  Default top-reply for me.

**Comment by Quix0r** [comment]
Well, sad think is that Outlook (Microsoft again) is the "standard" (default) but okay with me when there is an option to switch.

**Comment by zeugmatis** [comment]
@Quix0r Although I agree with you 100%, top-reply is the normal case.  
An option to change that would be good!  

I think the devs should look at things like Apple Mail, and pretty much emulate the UI.

**Comment by Quix0r** [comment]
I think it is better to have own version of a web mailer and not duplicate from companies which are writing proprietary software. :-)

**Comment by jancborchardt** [comment]
There are two other issues here:
- replying in itself is not clean yet. We just have an unwieldy giant quoted text. Which you don’t even need in many cases.
- the real solution to turning the conversation flow the right way is proper threading: https://github.com/nextcloud/mail/issues/17

I do not think that introducing this option solves a real problem which is not better solved by other means.

**Comment by Quix0r** [comment]
Some people delete mails. If they do, they still want to read the conversation (yes, it sounds strange) what quotes are for. :-)

**Comment by jancborchardt** [comment]
I do also delete mails and use quoting. That doesn’t contradict with what I said above.
