### ISSUE TITLE
Unread messages counter

### ISSUE THREAD

**Issue by ChristophWurst** [nextcloud/mail#1400]
Leftover from https://github.com/nextcloud/mail/projects/4

**Comment by ChristophWurst** [comment]
I'll accept this as a known feature regression of v0.12 because I don't know how to do it right now without the very same issues we had before

**Comment by GretaD** [comment]
What else missing here, isnt this done already? :arrow_down: 
![inbox counter](https://user-images.githubusercontent.com/12728974/77931125-0dd18e00-72ac-11ea-85ef-7ec823bc7a7a.png)

**Comment by ChristophWurst** [comment]
No, there should be a counter next to the mailbox name, which is shown all the time. This was removed with the Vue rewrite as the old implementation was very fragile (got to negative numbers and such fun)

**Comment by st3iny** [comment]
> No, there should be a counter next to the mailbox name, which is shown all the time. This was removed with the Vue rewrite as the old implementation was very fragile (got to negative numbers and such fun)

As someone who wasn't using mail before the vue rewrite I wonder what it looked liked. I'm currently experimenting with bringing back this feature and made a quick mockup:

![Screenshot_2021-04-13 Mail - Nextcloud](https://user-images.githubusercontent.com/1479486/114578808-89b33400-9c7d-11eb-86ac-8f4e2a214252.png)

Did it look like this?

**Comment by ChristophWurst** [comment]
Nope the counter was on the right: https://docs.nextcloud.com/server/latest/developer_manual/design/navigation.html#counter :)
