### ISSUE TITLE
Can only see 20 imported mails

### ISSUE THREAD

**Issue by arsors** [nextcloud/mail#1408]
### Expected behavior
Can see/load all imported mails in list

### Actual behavior
Can only see 20 mails and it didn't load more.
When I import the mails via Thunderbird and have nextcloud mail open in my browser I see how all mails are loaded bit by bit. After a reload the mail list is limited to 20 items. Also when scrolling down to reload no further mails are added.
However, if I send 30 new emails after importing the (100) mails, I can reload all messages in my inbox by scrolling.

### Mail app

**Mail app version:** 0.11.0

**Mailserver or service:** own imap server

**Number of accounts:** 3

### Server configuration

**Operating system**: linux

**Web server:** Apache

**Database:** 10.2.19-MariaDB-log-cll-lve

**PHP version:** 7.1.25

**Nextcloud Version:** 15.0.0.10

**Updated from an older version or fresh install:** fresh install

**List of activated apps:**
```
Accessibility	1.1.0	Offiziell	
Activity	2.8.2	Offiziell	
AppOrder	0.6.0		
Collaborative tags	1.5.0	Offiziell	
Comments	1.5.0	Offiziell	
Deleted files	1.5.0	Offiziell	
Federation	1.5.0	Offiziell	
File sharing	1.7.0	Offiziell	
Files Right Click	0.8.5		
First run wizard	2.4.0	Offiziell	
Gallery	18.2.0	Offiziell	
Log Reader	2.0.0	Offiziell	
Mail	0.11.0	Offiziell	
Monitoring	1.5.0	Offiziell	
Nextcloud announcements	1.4.0	Offiziell	
Notifications	2.3.0	Offiziell	
Password policy	1.5.0	Offiziell	
PDF viewer	1.4.0	Offiziell	
Share by mail	1.5.0	Offiziell	
Support	1.0.0	Offiziell	
Tasks	0.9.8		
Text editor	2.7.0	Offiziell	
Theming	1.6.0	Offiziell	
Update notification	1.5.0	Offiziell	
Usage survey	1.3.0	Offiziell	
Versions	1.8.0	Offiziell	
Video player	1.4.0	Offiziell	
Auditing / Logging	1.5.0	Offiziell	
Default encryption module	2.3.0	Offiziell	
External storage support	1.6.0	Offiziell	
External user support	0.4	Offiziell	
LDAP user and group backend	1.5.0	Offiziell
```

**The content of config/config.php:**
```
nothing changed
```

#### Client configuration
**Browser:** Chrome 71.0.3578.98 (Offizieller Build) (64-Bit)

**Operating system:** macOS Sierra Version 10.12.6

##### Web server error log
```
nothing special
```

##### Server log (data/nextcloud.log)
```
nothing special
```

##### IMAP log (data/horde_imap.log)
```
Works without problems in horde
```

##### SMTP log (data/horde_smtp.log)
```
Works without problems in horde
```

##### Browser log
```
Nothing
```

**Comment by ChristophWurst** [comment]
This could be fixed with the new frontend in 0.12.
