### ISSUE TITLE
Keyboard shortcuts don’t work anymore

### ISSUE THREAD

**Issue by jancborchardt** [nextcloud/mail#1412]
With latest master of the Mail app, the keyboard shortcuts like <kbd>Delete</kbd> for removing an email does not work anymore.

I guess also because of the Vue rewrite?

**Comment by ChristophWurst** [comment]
> I guess also because of the Vue rewrite?

I optimized it away. Soon ML will delete emails for you. Deleting by hand was done in the 90s.
