### ISSUE TITLE
"to" section in composer not properly aligned

### ISSUE THREAD

**Issue by jancborchardt** [nextcloud/mail#1413]
In the new message or reply composer, the "to" elements are not left-aligned with "from" and Subject, too far to left. Also don’t have the "to" label anymore:
![mail to align](https://user-images.githubusercontent.com/925062/50154392-81bf7100-02c9-11e9-9e55-9c8d71d4a8d4.png)

**Comment by ChristophWurst** [comment]
Fix it ;)

**Comment by jancborchardt** [comment]
Sorry, this actually seems fixed on master! :)
