### ISSUE TITLE
Menu wording "Seen" is confusing

### ISSUE THREAD

**Issue by jancborchardt** [nextcloud/mail#1415]
The mail action menu says "Seen" which is confusing, and doesn’t change depending on state either. Should be "Mark unread" if it’s read, and "Mark read" if the mail is unread to reflect the action which will happen:
![mail seen](https://user-images.githubusercontent.com/925062/50154395-82580780-02c9-11e9-9bef-8baa22d6d0a4.png)

**Comment by ChristophWurst** [comment]
Fixed in #1443
