### ISSUE TITLE
"Content-type" and other code stuff at top and bottom of some mails

### ISSUE THREAD

**Issue by jancborchardt** [nextcloud/mail#1416]
Some mails have this strange code stuff on the top and bottom (see @skjnldsv’s recent mails for example):
```
--Q0iKeM0xJGawfT3eP9mlXvmFLnd9pMDe0
Content-Type: text/plain; charset=utf-8
Content-Language: en-US
Content-Transfer-Encoding: quoted-printable
```

We should not show these technical details at all.

**Comment by ChristophWurst** [comment]
Duplicate of #1391 

Wanted to fix this today but, obviously, couldn't reproduce on my dev instance …
