### ISSUE TITLE
Left navigation design regressions

### ISSUE THREAD

**Issue by jancborchardt** [nextcloud/mail#1418]
Left how it currently is, right how it should be / used to be:
- [ ] Some whitespace between the different accounts (and the unified inbox). For the mockup I used an empty `<li>` with `height: 22px;`. Ideally we should either standardize this spacer, or have a class on the account which adds some margin-top. @skjnldsv what do you think?
- [x] The "Show all folders" is less important than the others, so the opacity should be a bit lower. Use `color: var(--color-text-maxcontrast);` here.
![nextcloud mail navigation](https://user-images.githubusercontent.com/925062/50293074-03063780-0473-11e9-92b7-93b84afe2e96.png)

**Comment by skjnldsv** [comment]
> * Ideally we should either standardize this spacer, or have a class on the account which adds some margin-top. @skjnldsv what do you think?

That should already work with the caption? But yes, it make sense to have a dedicated spacer if we do half-height entries :)
