### ISSUE TITLE
Support with PHP 7.3

### ISSUE THREAD

**Issue by mudumat** [nextcloud/mail#1425]
Just installed nextcloud and wanted to test this email addon but it says lower than 7.2 needed. So much changes beetween 7.1 and 7.3? Or just a entry in a dependency file?

Thanks
mudu

**Comment by ann0see** [comment]
Had the same problem with my nextcloud installation. Maybe some quotes have to be different?

**Comment by under-score** [comment]
+1
![bildschirmfoto 2019-01-05 um 09 09 25](https://user-images.githubusercontent.com/2796454/50722061-c6207e80-10c9-11e9-9336-f80495c0cc53.png)

**Comment by ChristophWurst** [comment]
See https://github.com/nextcloud/mail/pull/1323 and the referenced upstream library PRs. This app currently triggers a lot of php warnings with php7.3 and is therefore unusable. We have to wait for the Horde libraries to get fixed.

**Comment by under-score** [comment]
thank you - going back to 7.2 cured most problems

**Comment by ChristophWurst** [comment]
Fixed by https://github.com/nextcloud/mail/pull/1323
