### ISSUE TITLE
Contact photo does not show up

### ISSUE THREAD

**Issue by dusscloud** [nextcloud/mail#1435]
### Expected behavior
For all mails sent by people existing in Nextcloud contacts, contact photo should appear in the message list.

### Actual behavior
Only the icon with the first letter of contact is displayed. This happens for all contacts.

### Mail app

**Mail app version:** 0.11.0

### Server configuration

**Nextcloud Version:** 14.0.4

![mail](https://user-images.githubusercontent.com/31505866/50573907-1d2e0700-0ddd-11e9-8f2f-8e0623fa6fa3.jpg)

**Comment by ChristophWurst** [comment]
Did you disable contacts images in the settings menu on the bottom left?

**Comment by dusscloud** [comment]
I tried enabled / disabled. 
The effect was only for logos on emails sent by services like Facebook (gravatar?), But no effects on emails sent by contacts

**Comment by ChristophWurst** [comment]
Are there any errors logged in your browser, network console or nextcloud.log?

**Comment by dusscloud** [comment]
From the Network console I can see that for all senders, it tries to get the pictures using url like https://myNextCloudInstance.com/index.php/apps/mail/api/avatars/url/sender%40mail.com
Some are with HTTP 200 (usually favicon if it's a mail from a website), But 404 from any of my contacts.

Nothing on nextcloud.log.

Note : I am now using Nextcloud 15.0.2

**Comment by jakobroehrl** [comment]
The contact photo doesn't show up on my installation neither. 
I only see colored circles with the first letter of the name. 
Maybe it's not a mail topic. I don't see int the contact search the photos neither. Only in the contact app:
![grafik](https://user-images.githubusercontent.com/24530680/66465594-6fddd300-ea81-11e9-8f57-3992fa503d0d.png)
![grafik](https://user-images.githubusercontent.com/24530680/66465665-96037300-ea81-11e9-85cc-9f767f29e438.png)

**Comment by Discostu36** [comment]
The issue seems to still exist and should therefore be reopened. I also don't have any avatars from my contacts in mail app. 

Nextcloud 20.0.9.1
Mail: unknown (managed Nextcloud)

**Comment by ChristophWurst** [comment]
Please open a new ticket.
