### ISSUE TITLE
Enable deleting an account

### ISSUE THREAD

**Issue by kevgathuku** [nextcloud/mail#1436]
During the Vue rewrite, it seems that the functionality to delete an account was not ported. 

I noticed this since I had added a few duplicate accounts during testing and after updating to the latest version in `master` after the Vue rewrite there's no option to delete an account.

**Comment by kevgathuku** [comment]
Alternatively, does it make sense to move deleting an account to the account settings page?
Deleting an account seems like the kind of thing that should be in the account settings

Any ideas on this @ChristophWurst?

**Comment by ChristophWurst** [comment]
Whoops, yeah, this slipped through.

:+1: on moving that the the account settings.
