### ISSUE TITLE
Address of avatars seems to be cached which breaks access through different addresses.

### ISSUE THREAD

**Issue by RobertZenz** [nextcloud/mail#1437]
The avatars seem to be cached with their first seen address, which breaks if you access the NextCloud instance through a different domain/address.

I have hosted my own NextCloud instance which resides inside my network. When accessing NextCloud from inside my network I use something like `https://192.168.1.128/`, when I'm abroad I'm using an external domain like `https://mycloud.mydomain.net` which directs me to my NextCloud instance (obviously). Now when I'm assigning an avatar to a contact, the avatar works correctly in the Contacts application. When accessing the Mail application it also works there. However, when I'm accessing the Mail application through the other address, the avatar is still being loaded from the old/first address.

 1. Have a server which is accessible through two different addresses.
 2. Create a contact and have an email from that contact.
 3. Access the NextCloud instance through one address (`https://192.168.1.128/`).
 4. Add an avatar to the contact.
 5. Open the Mail application, the avatar is being correctly displayed.
 6. Access the NextCloud instance through the second address (`https://mycloud.mydomain.net`).
 7. Open the mail application, the avatar does not load because the Mail app is trying to load it from the `https://192.168.1.128/` address.

This also works the other way around, so it is not a problem with the configured server address.

**Comment by RobertZenz** [comment]
For two reasons:

 1. I don't want to route my network traffic over half the continent if the machine sits right next to me (physically).
 2. I can't connect to/through my external IP from inside the network (ISP limitation, as it seems).

**Comment by ChristophWurst** [comment]
>     1. I don't want to route my network traffic over half the continent if the machine sits right next to me (physically)

So just configure your local DNS (or even just your machine) to resolve to the local IP.

> Oh, right, because of the Gravatar support, right?

They are generally cached for performance, and not just the Gravatar ones.

**Comment by RobertZenz** [comment]
> So just configure your local DNS (or even just your machine) to resolve to the local IP.

Not sure I can, at least not network wide. But sure, something like that would be a solution.

 > They are generally cached for performance, and not just the Gravatar ones.

Which raises the question, how does that cache handle server movements? If the server is moved from domain A to domain B, or from directory X to directory C?

Because my first thought was to cache the contact-avatars with a relative address, but that does also break if the installation is being moved.

**Comment by ChristophWurst** [comment]
I don't think moving domains is supported. There are many other code paths that rely on a consistent domain, like your federated sharing IDs.

I'm closing this ticket now. For general help with your setup see the documentation or ask for help at https://help.nextcloud.com/.

Cheers

**Comment by RobertZenz** [comment]
Great. Next question, can I disable the cache?
