### ISSUE TITLE
Opening large mailbox takes ages

### ISSUE THREAD

**Issue by beccon4** [nextcloud/mail#1454]
### Expected behavior
Opening should show the list of new and current mails within a couple of seconds even if there are thousands of messages in the box.

### Actual behavior
The application shows the "please wait" circle for almost 60 seconds. Other parts of Nextcloud work fine and quite fluidly.

### Mail app
**Mail app version:** 
0.11.0
Nextcloud Server on Ubuntu 16.04 with 50MBits downstream connection.

**Mailserver or service:** (e.g. Outlook, Yahoo, Gmail, Exchange,...)
dovecot or exim

**Comment by beccon4** [comment]
Would you please reopen this issue. I still (or once again) have a very large email box and when I connect it to the mail app it takes ca. 30-45sec spinning after clicking until I can read my mail. It looks like the mail app scans all the mails in the INBOX folder - and not only the newly arrived.

Neither Horde nor Rainloop show that kind of behaviour with this very mailbox.

**Comment by ChristophWurst** [comment]
Please file a new ticket as I have to assume the information is not up to date anymore. If it is than you should update to the latest versions of our software.

Cheers.

**Comment by ChristophWurst** [comment]
This is also something we're working on right now #2064, though the initial scan might still be slow.

**Comment by ChristophWurst** [comment]
When you send a new report please include the diagnose info as per new occ command #2319

**Comment by ChristophWurst** [comment]
@beccon4 please see https://help.nextcloud.com/t/call-for-testers-mail-v1-3/75825. We'd appreciate if you could help us test the upcoming release :v:
