### ISSUE TITLE
Missing signatures for some files

### ISSUE THREAD

**Issue by benediktg** [nextcloud/mail#146]
Is it possible that there are some code signatures missing in the mail app?

### Steps to reproduce
1. update the mail app
2. look at the security and setup warnigs on the admin page

### Expected behaviour
There should be no issues with code signatures.

### Actual behaviour
![screenshot_20161011_202622](https://cloud.githubusercontent.com/assets/14795615/19283520/792b0050-8ff2-11e6-8824-595941848923.png)

Side note: at first I did not see an update button for the mail app in the apps overview so that I downloaded the tar archive and extracted it. Then there was an update button for the mail app and I clicked on it. After that the upgrade assistant did the upgrade in nextcloud (the "web version" of `occ`). As the update was finished the warning in the picture above appeared ("errors in the code integrity check occured"). I tried to fix it by extracting the tar archive again but it didn't help.

### Mail app

**Mail app version:** 0.6.0

### Server configuration
**Operating system**: Debian 8 (jessie)

**Web server:** Apache 2.4.10

**Database:** MariaDB 10.0.27

**PHP version:** 5.6.26

**Version:** Nextcloud 10.0.1

**Updated from an older version or fresh install:** updated from Nextcloud 10 (which again is migrated from Nextcloud 9 and Owncloud)

**Comment by MorrisJobke** [comment]
cc @ChristophWurst 

Why are there test files in the tar ball?

**Comment by Gomez** [comment]
I do the releases. Will check it soon.

**Comment by MorrisJobke** [comment]
> I do the releases. Will check it soon.

Ah :) Good to know 👍

**Comment by Gomez** [comment]
I can reproduce. Have you downloaded the mail.tar.gz from https://github.com/nextcloud/mail/releases/tag/v0.6.0 ? This one is the release with signature, the others are source tars.

**Comment by MorrisJobke** [comment]
> I can reproduce.

Have you forgotten a "not"?

**Comment by ChristophWurst** [comment]
Weird. I tested it with the tar from the app store and my nc did not find any code signing errors

**Comment by Gomez** [comment]
@MorrisJobke Yes :) I can not reproduce.

**Comment by benediktg** [comment]
@Gomez What I did was
```sh
wget https://github.com/nextcloud/mail/releases/download/v0.6.0/mail.tar.gz
tar xf mail.tar.gz
```
as the user `www-data` in the `apps` directory.

**Comment by benediktg** [comment]
I did 
```sh
cd ~www/nextcloud/apps
rm mail/appinfo/version mail/js/vendor/es6-promise/test/browserify.js mail/js/vendor/es6-promise/test/es6-promise.js mail/js/vendor/es6-promise/test/es6-promise.min.js mail/js/vendor/es6-promise/test/index.html mail/js/vendor/es6-promise/test/json3.js mail/js/vendor/es6-promise/test/mocha.css mail/js/vendor/es6-promise/test/mocha.js mail/js/vendor/es6-promise/test/worker.js mail/js/vendor/es6-promise/promise.min.js mail/js/vendor/es6-promise/promise.js mail/js/views/messages.js mail/js/views/messagecontent.js mail/js/views/app.js
sudo -u www-data tar -xf mail.tar.gz
```
now and after that it seems to be fine again. My assumption is that these signature issues occured because I had deployed Next/Owncloud as well as some apps out of a cloned git repository and these test files were (of course) not deleted by unzipping the tar archive. Hence closing this issue. ;)

**Comment by MorrisJobke** [comment]
> now and after that it seems to be fine again. My assumption is that these signature issues occured because I had deployed Next/Owncloud as well as some apps out of a cloned git repository and these test files were (of course) not deleted by unzipping the tar archive. Hence closing this issue. ;)

That's the reason you should always delete and then extract and not simply extract ontop of existing files. This was also the reason for the signature check - to determine if this has gone wrong 😉
