### ISSUE TITLE
read confirmation & acknowledgment of receipt

### ISSUE THREAD

**Issue by Zayccmar** [nextcloud/mail#1467]
### Feature Request

Hello i use the mail app by my nextcloud enviorment, and i must say that is a wonderfull app but what i missing are a funktion to set a  read confirmation & or a  acknowledgment of receipt when i type an new Mail or i get a reply to a mail

it is possible to integrate this fetures by the next release?

best regrads 

Markus

**Comment by ChristophWurst** [comment]
> it is possible to integrate this fetures by the next release?

Sure. Pull request are welcome anytime :v:

**Comment by ChristophWurst** [comment]
You can find more information about app development in the manual: https://docs.nextcloud.com/server/15/developer_manual/

Cheers

**Comment by Zayccmar** [comment]
> > it is possible to integrate this fetures by the next release?
> 
> Sure. Pull request are welcome anytime ✌️

Hi thank you
can you help me i don´t have do a pull request before and this are my first visit at github as a member

best regrads 

Markus

**Comment by ChristophWurst** [comment]
You can find great GitHub docs at https://help.github.com/.

**Comment by Zayccmar** [comment]
> You can find great GitHub docs at https://help.github.com/.

Thank you

but when i understand it right the pull request are for developer, but i am not a developer and so i can not make a example for the right source code, by this i have made a issue with a feature request.

so now i don´t know what i must do.

best regrads

**Comment by ChristophWurst** [comment]
I you're not a developer than the chances of this feature being added to the next release are quite low. Maybe you know a friend who is a coder than they can help :)

You can try to add a bounty at https://www.bountysource.com/issues/68667195-read-confirmation-acknowledgment-of-receipt but there is no guarantee that anyone will have a look. But it sometimes helps.

**Comment by ChristophWurst** [comment]
PR is at https://github.com/nextcloud/mail/pull/4343 :rocket:
