### ISSUE TITLE
E-Mail with paintext and http links shows up with invalid http links

### ISSUE THREAD

**Issue by pamapa** [nextcloud/mail#147]
### Steps to reproduce
1. Create E-Mail with plain text and add a http link "https://domain.com/track/direct.php?Nr=1020&EP=100"
2. Watch E-Mail with Nextcloud Mail
### Expected behaviour

``` html
<a href="https://domain.com/track/direct.php?Nr=1020&EPLZ=8006" rel="noreferrer" target="_blank">https://domain.com/track/direct.php?Nr=1020&EPLZ=8006</a>
```
### Actual behaviour

Looks like the code, which creates the link stops at the "&", but it should not.

``` html
<a href="https://domain.com/track/direct.php?Nr=1020" rel="noreferrer" target="_blank">https://domain.com/track/direct.php</a>&EPLZ=8006
```
### Mail app

**Mail app version:** 0.5.3
### Server configuration

**Operating system**: webhoster

**Web server:** apache

**Database:** MySQL

**PHP version:** 5.6

**Version:** 10.0.1

**Updated from an older version or fresh install:** updated from Nextcloud 9.x

**List of activated apps:**
#### Client configuration

**Browser:** Firefox 45.4.0

**Operating system:** Linux

**Comment by ChristophWurst** [comment]
cc @nickvergessen 😉

**Comment by Maulwurf16** [comment]
ah, and by handling urls correctly, don't forget ports :)

an url http://url.de:12345/index.php is converted into: http://url.de/index.php

**Comment by FlorianFranzen** [comment]
I am not sure why part of the link is hidden at all. If I view a plain text mail, I want to see all of the plain text. That is one of the main reasons to use plain text mail.

Based on this I think two things should be fixed:
 * Fix Link detection by including & and : in regexp
 * Display full link even when link is autodetected

**Comment by ChristophWurst** [comment]
Fixed by https://github.com/nextcloud/mail/pull/923
