### ISSUE TITLE
Logout with mail app "active" returns "Internal server error"

### ISSUE THREAD

**Issue by timewindSE** [nextcloud/mail#1472]
### Expected behavior
Tell us what should happen
_No error messages if I logout from nextcloud with Mail app "active"._

### Actual behavior
Tell us what happens instead
_Error message is shown "Internal server error. the server could not perform your request"_

### Mail app

**Mail app version:** (see apps admin page, e.g. 0.5.3)
_0.11.0_

**Mailserver or service:** (e.g. Outlook, Yahoo, Gmail, Exchange,...)
_"Private mail server" and a local mailserver._

### Server configuration
_IMAP on both accounts. Local account without encryption._

**Operating system**: (e.g. Debian 8)
_FreeBSD 11.2 (32-bit)_

**Web server:** (e.g. Apache, Nginx,...)
_Apache 2.4.37_

**Database:** (e.g. MariaDB, SQLite or PostgreSQL)
_MySQL 5.6.42_

**PHP version:** (e.g. 7.0)
_7.2_

**Nextcloud Version:** (see admin page, e.g. 13.0.2)
_15.0.2_

#### Client configuration
_Firefox, Edge_

**Operating system:** (e.g. Arch Linux)
_Win10_

**I am adding a screenshot, text in swedish, sorry**
![internalerror](https://user-images.githubusercontent.com/46166010/51205664-afb6c600-1906-11e9-9ed6-9a4675c0dc0c.png)

**Comment by sphxx** [comment]
I can confirm this error, same here.

I just updated to Nextcloud 15.0.2 and when i logout from the mail app, an "internal server error" is shown.

Logout from any other Nextcloud app or page works fine!

My mail app version is 0.11.0.

The error message also mentions to check the server logfile for further details. I'm running Nextcloud on a webhost where i can't access this server logs.

The problem occured a few versions ago, it's not really new.

**Comment by Himra** [comment]
I have the same
Nextcloud 15.0.2 , Mail  0.11.0

**Log:**
[index] Error: TypeError: Argument 7 passed to OCA\Mail\Controller\PageController::__construct() must be of the type string, null given at <<closure>>

 0. <<closure>>
    __construct("mail", OC\AppFramework\Http\Request {}, OC\URLGenerator {}, OC\AllConfig {}, OCA\Mail\Service\AccountService {}, OCA\Mail\Service\AliasesService {}, null, OC\User\Session {}, OCA\Mail\Service\UserPreferenceSevice {})
 1. /home/sites/site67/web/nc/lib/private/AppFramework/Utility/SimpleContainer.php line 81
    newInstanceArgs(["mail",OC\AppFr ... }])
 2. /home/sites/site67/web/nc/lib/private/AppFramework/Utility/SimpleContainer.php line 98
    buildClass(ReflectionClass  ... "})
 3. /home/sites/site67/web/nc/lib/private/AppFramework/Utility/SimpleContainer.php line 119
    resolve("OCA\\Mail\\Controller\\PageController")
 4. /home/sites/site67/web/nc/lib/private/AppFramework/DependencyInjection/DIContainer.php line 425
    query("OCA\\Mail\\Controller\\PageController")
 5. /home/sites/site67/web/nc/lib/private/AppFramework/DependencyInjection/DIContainer.php line 396
    queryNoFallback("OCA\\Mail\\Controller\\PageController")
 6. /home/sites/site67/web/nc/lib/private/AppFramework/App.php line 105
    query("OCA\\Mail\\Controller\\PageController")
 7. /home/sites/site67/web/nc/lib/private/AppFramework/Routing/RouteActionHandler.php line 47
    main("OCA\\Mail\\Controller\\PageController", "index", OC\AppFramework\ ... {}, {_route: "mail.page.index"})
 8. <<closure>>
    __invoke({_route: "mail.page.index"})
 9. /home/sites/site67/web/nc/lib/private/Route/Router.php line 297
    call_user_func(OC\AppFramework\ ... {}, {_route: "mail.page.index"})
10. /home/sites/site67/web/nc/lib/base.php line 987
    match("/apps/mail/")
11. /home/sites/site67/web/nc/index.php line 42
    handleRequest()

GET /index.php/apps/mail/
from 93.241.239.243 at 2019-01-24T09:02:33+00:00

**Comment by ChristophWurst** [comment]
Fixed at https://github.com/nextcloud/mail/pull/1489.

**Comment by sphxx** [comment]
Good to see it's fixed now - but when will the updated version be available?

Meanwhile, Nextcloud had some updates but this error is still there, the mail app is still the same version. 

Where can i find when this "0.12 milestone" will be released?

Thank you!

**Comment by ChristophWurst** [comment]
It will be releases when it's ready.

**Comment by sphxx** [comment]
Oh, okay - i thought tere is some "Timeline" or something like a set release date, which i just couldn't find.
Thanks for the info, anyway!

**Comment by ChristophWurst** [comment]
No, we don't have any strict release plan for this app :wink:
