### ISSUE TITLE
Error message when sharing files if second mail account is added

### ISSUE THREAD

**Issue by timewindSE** [nextcloud/mail#1473]
### Expected behavior
Tell us what should happen
_No error message should be shown when sharing files if two mail accounts are configured in the mail app._

### Actual behavior
Tell us what happens instead
_When another mail account is added, there is an error message at the top of the page when a file is shared with another user in the main application: "Expected response code 354 but got code “503”, with message "503 5.0.0 Need RCPT (recipient) ". The mail is not sent._

### Mail app

**Mail app version:** (see apps admin page, e.g. 0.5.3)
_0.11.0_

**Mailserver or service:** (e.g. Outlook, Yahoo, Gmail, Exchange,...)
"Private mail server" and a local mailserver. IMAP. Local mailserver communication is not encrypted.

### Server configuration

**Operating system**: (e.g. Debian 8)
_FreeBSD 11.2 (32-bit)_

**Web server:** (e.g. Apache, Nginx,...)
_Apache 2.4.37_

**Database:** (e.g. MariaDB, SQLite or PostgreSQL)
_MySQL 5.6.42_

**PHP version:** (e.g. 7.0)
_7.2_

**Nextcloud Version:** (see admin page, e.g. 13.0.2)
_15.0.2_

#### Client configuration
**Browser:** (e.g. Firefox 48)
_Firefox 64, Edge_

**Operating system:** (e.g. Arch Linux)
_Win10._

**Comment by ChristophWurst** [comment]
well, did you set a recipient on that message? :)

**Comment by timewindSE** [comment]
Well! It works when only one mailaccout is configured -> No error message and a mail is sent. But when I add another mail account in the mail app ->  this error message occurs. If I remove the account, it works again. 

Best regards
Stefan Sundberg

**Comment by timewindSE** [comment]
Error found in mail server configuration so no bug.
