### ISSUE TITLE
SMTP server configuration (not ecrypted)

### ISSUE THREAD

**Issue by timewindSE** [nextcloud/mail#1474]
### Expected behavior
Tell us what should happen
_When choosing to connect to a SMTP server without encryption (changing from "TLS/SSL" to "none), the port number should change to "25" in the mail account configuration._

### Actual behavior
Tell us what happens instead
_The port number is still "587" but can be changed manually._

### Mail app

**Mail app version:** (see apps admin page, e.g. 0.5.3)
_0.11.0_

**Mailserver or service:** (e.g. Outlook, Yahoo, Gmail, Exchange,...)
_"Private mailserver" and local mailserver without encryption. IMAP (and SMTP)._

### Server configuration

**Operating system**: (e.g. Debian 8)
_FreeBSD 11.2 (32-bit)_

**Web server:** (e.g. Apache, Nginx,...)
_Apache 2.4.37_

**Database:** (e.g. MariaDB, SQLite or PostgreSQL)
_MySQL 5.6.42_

**PHP version:** (e.g. 7.0)
_7.2_

**Nextcloud Version:** (see admin page, e.g. 13.0.2)
_15.0.2_

#### Client configuration
**Browser:** (e.g. Firefox 48)
_Firefox 64.0, Edge_

**Operating system:** (e.g. Arch Linux)
_Win10_

**Comment by ChristophWurst** [comment]
Should be fixed with the Vue rewrite #1045 but let's keep it open until 0.12 has been released.
