### ISSUE TITLE
Can't install

### ISSUE THREAD

**Issue by csanszan1** [nextcloud/mail#1478]
### Expected behavior
Tell us what should happen
Installing software

### Actual behavior
Tell us what happens instead
https://pastebin.com/Ri34NbYa

### Mail app

**Mail app version:** (see apps admin page, e.g. 0.5.3)
???
**Mailserver or service:** (e.g. Outlook, Yahoo, Gmail, Exchange,...)
Self hosted

### Server configuration

**Operating system**: (e.g. Debian 8)
Ubuntu 16.04
**Web server:** (e.g. Apache, Nginx,...)
Apache2
**Database:** (e.g. MariaDB, SQLite or PostgreSQL)
MariaDB
**PHP version:** (e.g. 7.0)
7.0
**Nextcloud Version:** (see admin page, e.g. 13.0.2)
???
**Nodejs version:**
6.16.0
#### Client configuration
**Browser:** (e.g. Firefox 48)
None
**Operating system:** (e.g. Arch Linux)
Windows 10

**Comment by ChristophWurst** [comment]
> Installing software

Please offer reproducible instructions.
