### ISSUE TITLE
Can't save all attachments to cloud folder

### ISSUE THREAD

**Issue by g6094199** [nextcloud/mail#1483]
### Expected behavior
Hit the button "save all attachments", select the cloud folder where to save them. Hit ok.

### Actual behavior
Hit the button "save all attachments", select the cloud folder where to save them. Hit ok. An error message pops in where it says it wasnt able to save the attachments.
But when i save all attachments one by one to the same folder it works! So i guess  there is a regression somewhere.

### Mail app

**Mail app version:** 
0.11.0

**Mailserver or service:**
IMAP Server

### Server configuration

**Operating system**: 
Ubuntu 18.04

**Web server:** 
Nginx

**Database:** 
MariaDB

**PHP version:** 
php 7.4 FPM

**Nextcloud Version:** 
15.0.2

#### Client configuration
**Browser:** 
FF 64

**Operating system:** 
Ubuntu 18.10

**Comment by ChristophWurst** [comment]
Could you please add the relevant entries from you nextcloud.log when that happens? Thanks!

**Comment by g6094199** [comment]
`{"reqId":"HHiFfZmrSNSfLWrRkxTk","level":3,"time":"2019-01-26T15:45:16+01:00","remoteAddr":"IPADDRESS","user":"XUSERX","app":"index","method":"POST","url":"\/index.php\/apps\/mail\/api\/accounts\/9\/folders\/SU5CT1guSW1tbw%3D%3D\/messages\/52\/attachment\/0","message":{"Exception":"TypeError","Message":"Argument 2 passed to OCA\\Mail\\Mailbox::getAttachment() must be of the type integer, string given, called in \/var\/www\/nextcloud\/apps\/mail\/lib\/Controller\/MessagesController.php on line 296","Code":0,"Trace":[{"file":"\/var\/www\/nextcloud\/apps\/mail\/lib\/Controller\/MessagesController.php","line":296,"function":"getAttachment","class":"OCA\\Mail\\Mailbox","type":"->","args":[52,"2"]},{"file":"\/var\/www\/nextcloud\/lib\/private\/AppFramework\/Http\/Dispatcher.php","line":166,"function":"saveAttachment","class":"OCA\\Mail\\Controller\\MessagesController","type":"->","args":[9,"SU5CT1guSW1tbw==",52,"2","\/Bilder"]},{"file":"\/var\/www\/nextcloud\/lib\/private\/AppFramework\/Http\/Dispatcher.php","line":99,"function":"executeController","class":"OC\\AppFramework\\Http\\Dispatcher","type":"->","args":[{"__class__":"OCA\\Mail\\Controller\\MessagesController"},"saveAttachment"]},{"file":"\/var\/www\/nextcloud\/lib\/private\/AppFramework\/App.php","line":118,"function":"dispatch","class":"OC\\AppFramework\\Http\\Dispatcher","type":"->","args":[{"__class__":"OCA\\Mail\\Controller\\MessagesController"},"saveAttachment"]},{"file":"\/var\/www\/nextcloud\/lib\/private\/AppFramework\/Routing\/RouteActionHandler.php","line":47,"function":"main","class":"OC\\AppFramework\\App","type":"::","args":["OCA\\Mail\\Controller\\MessagesController","saveAttachment",{"__class__":"OC\\AppFramework\\DependencyInjection\\DIContainer"},{"accountId":"9","folderId":"SU5CT1guSW1tbw==","messageId":"52","attachmentId":"0","_route":"mail.messages.saveAttachment"}]},{"function":"__invoke","class":"OC\\AppFramework\\Routing\\RouteActionHandler","type":"->","args":[{"accountId":"9","folderId":"SU5CT1guSW1tbw==","messageId":"52","attachmentId":"0","_route":"mail.messages.saveAttachment"}]},{"file":"\/var\/www\/nextcloud\/lib\/private\/Route\/Router.php","line":297,"function":"call_user_func","args":[{"__class__":"OC\\AppFramework\\Routing\\RouteActionHandler"},{"accountId":"9","folderId":"SU5CT1guSW1tbw==","messageId":"52","attachmentId":"0","_route":"mail.messages.saveAttachment"}]},{"file":"\/var\/www\/nextcloud\/lib\/base.php","line":987,"function":"match","class":"OC\\Route\\Router","type":"->","args":["\/apps\/mail\/api\/accounts\/9\/folders\/SU5CT1guSW1tbw%3D%3D\/messages\/52\/attachment\/0"]},{"file":"\/var\/www\/nextcloud\/index.php","line":42,"function":"handleRequest","class":"OC","type":"::","args":[]}],"File":"\/var\/www\/nextcloud\/apps\/mail\/lib\/Mailbox.php","Line":421,"CustomMessage":"--"},"userAgent":"Mozilla\/5.0 (X11; Ubuntu; Linux x86_64; rv:64.0) Gecko\/20100101 Firefox\/64.0","version":"15.0.2.0"}
{"reqId":"HHiFfZmrSNSfLWrRkxTk","level":0,"time":"2019-01-26T15:45:16+01:00","remoteAddr":"IPADDRESS","user":"XUSERX","app":"core","method":"POST","url":"\/index.php\/apps\/mail\/api\/accounts\/9\/folders\/SU5CT1guSW1tbw%3D%3D\/messages\/52\/attachment\/0","message":"Scss is disabled for \/var\/www\/nextcloud\/core\/css\/jquery-ui-fixes.scss, ignoring","userAgent":"Mozilla\/5.0 (X11; Ubuntu; Linux x86_64; rv:64.0) Gecko\/20100101 Firefox\/64.0","version":"15.0.2.0"}
{"reqId":"HHiFfZmrSNSfLWrRkxTk","level":0,"time":"2019-01-26T15:45:16+01:00","remoteAddr":"IPADDRESS","user":"XUSERX","app":"core","method":"POST","url":"\/index.php\/apps\/mail\/api\/accounts\/9\/folders\/SU5CT1guSW1tbw%3D%3D\/messages\/52\/attachment\/0","message":"Scss is disabled for \/var\/www\/nextcloud\/core\/css\/server.scss, ignoring","userAgent":"Mozilla\/5.0 (X11; Ubuntu; Linux x86_64; rv:64.0) Gecko\/20100101 Firefox\/64.0","version":"15.0.2.0"}
{"reqId":"HHiFfZmrSNSfLWrRkxTk","level":0,"time":"2019-01-26T15:45:16+01:00","remoteAddr":"IPADDRESS","user":"XUSERX","app":"core","method":"POST","url":"\/index.php\/apps\/mail\/api\/accounts\/9\/folders\/SU5CT1guSW1tbw%3D%3D\/messages\/52\/attachment\/0","message":"Scss is disabled for \/var\/www\/nextcloud\/core\/css\/css-variables.scss, ignoring","userAgent":"Mozilla\/5.0 (X11; Ubuntu; Linux x86_64; rv:64.0) Gecko\/20100101 Firefox\/64.0","version":"15.0.2.0"}
{"reqId":"HHiFfZmrSNSfLWrRkxTk","level":0,"time":"2019-01-26T15:45:16+01:00","remoteAddr":"IPADDRESS","user":"XUSERX","app":"core","method":"POST","url":"\/index.php\/apps\/mail\/api\/accounts\/9\/folders\/SU5CT1guSW1tbw%3D%3D\/messages\/52\/attachment\/0","message":"Scss is disabled for \/var\/www\/nextcloud\/apps\/notifications\/css\/styles.scss, ignoring","userAgent":"Mozilla\/5.0 (X11; Ubuntu; Linux x86_64; rv:64.0) Gecko\/20100101 Firefox\/64.0","version":"15.0.2.0"}
{"reqId":"HHiFfZmrSNSfLWrRkxTk","level":0,"time":"2019-01-26T15:45:16+01:00","remoteAddr":"IPADDRESS","user":"XUSERX","app":"core","method":"POST","url":"\/index.php\/apps\/mail\/api\/accounts\/9\/folders\/SU5CT1guSW1tbw%3D%3D\/messages\/52\/attachment\/0","message":"Scss is disabled for \/var\/www\/nextcloud\/core\/css\/jquery.ocdialog.scss, ignoring","userAgent":"Mozilla\/5.0 (X11; Ubuntu; Linux x86_64; rv:64.0) Gecko\/20100101 Firefox\/64.0","version":"15.0.2.0"}
{"reqId":"HHiFfZmrSNSfLWrRkxTk","level":0,"time":"2019-01-26T15:45:16+01:00","remoteAddr":"IPADDRESS","user":"XUSERX","app":"core","method":"POST","url":"\/index.php\/apps\/mail\/api\/accounts\/9\/folders\/SU5CT1guSW1tbw%3D%3D\/messages\/52\/attachment\/0","message":"Scss is disabled for \/var\/www\/nextcloud\/core\/search\/css\/results.scss, ignoring","userAgent":"Mozilla\/5.0 (X11; Ubuntu; Linux x86_64; rv:64.0) Gecko\/20100101 Firefox\/64.0","version":"15.0.2.0"}
{"reqId":"HHiFfZmrSNSfLWrRkxTk","level":0,"time":"2019-01-26T15:45:16+01:00","remoteAddr":"IPADDRESS","user":"XUSERX","app":"core","method":"POST","url":"\/index.php\/apps\/mail\/api\/accounts\/9\/folders\/SU5CT1guSW1tbw%3D%3D\/messages\/52\/attachment\/0","message":"Scss is disabled for \/var\/www\/nextcloud\/core\/css\/styles.scss, ignoring","userAgent":"Mozilla\/5.0 (X11; Ubuntu; Linux x86_64; rv:64.0) Gecko\/20100101 Firefox\/64.0","version":"15.0.2.0"}
{"reqId":"HHiFfZmrSNSfLWrRkxTk","level":0,"time":"2019-01-26T15:45:16+01:00","remoteAddr":"IPADDRESS","user":"XUSERX","app":"core","method":"POST","url":"\/index.php\/apps\/mail\/api\/accounts\/9\/folders\/SU5CT1guSW1tbw%3D%3D\/messages\/52\/attachment\/0","message":"Scss is disabled for \/var\/www\/nextcloud\/core\/css\/header.scss, ignoring","userAgent":"Mozilla\/5.0 (X11; Ubuntu; Linux x86_64; rv:64.0) Gecko\/20100101 Firefox\/64.0","version":"15.0.2.0"}
{"reqId":"kPgvWOo69I0Pg6QGdH6n","level":0,"time":"2019-01-26T15:45:25+01:00","remoteAddr":"","user":"--","app":"files_antivirus","method":"","url":"--","message":"Scan is done File: 12723 Account: XUSERX Path: \/XUSERX\/files\/Buecher\/art_of_deception_controlling_the_human_element_of_security.pdf","userAgent":"--","version":"15.0.2.0"}
{"reqId":"kPgvWOo69I0Pg6QGdH6n","level":0,"time":"2019-01-26T15:45:27+01:00","remoteAddr":"","user":"--","app":"files_antivirus","method":"","url":"--","message":"Exit code :: 1 Response :: stdin: Sanesecurity.Phishing.Auction.1690.UNOFFICIAL FOUND\n\n----------- SCAN SUMMARY -----------\nKnown viruses: 6927932\nEngine version: 0.100.2\nScanned directories: 0\nScanned files: 1\nInfected files: 1\nData scanned: 1.10 MB\nData read: 2.88 MB (ratio 0.38:1)\nTime: 24.074 sec (0 m 24 s)\n","userAgent":"--","version":"15.0.2.0"}
{"reqId":"kPgvWOo69I0Pg6QGdH6n","level":4,"time":"2019-01-26T15:45:27+01:00","remoteAddr":"","user":"--","app":"files_antivirus","method":"","url":"--","message":"File is infected. Sanesecurity.Phishing.Auction.1690.UNOFFICIAL File: 12723Account: XUSERX Path: \/XUSERX\/files\/Buecher\/art_of_deception_controlling_the_human_element_of_security.pdf","userAgent":"--","version":"15.0.2.0"}
{"reqId":"kPgvWOo69I0Pg6QGdH6n","level":0,"time":"2019-01-26T15:45:27+01:00","remoteAddr":"","user":"--","app":"cron","method":"","url":"--","message":"Finished OCA\\Files_Antivirus\\BackgroundJob\\BackgroundScanner job with ID 1136 in 25 seconds","userAgent":"--","version":"15.0.2.0"}
`
```

**Comment by ChristophWurst** [comment]
> Argument 2 passed to OCA\\Mail\\Mailbox::getAttachment() must be of the type integer, string given

IIRC I fixed this recently on the master branch. Please re-test when the version 0.12 is released.

**Comment by Ricks-ha** [comment]
When is 0.12 about to be released as this issue persists.

**Comment by ChristophWurst** [comment]
When it's ready.

**Comment by ChristophWurst** [comment]
Fixed with #2349
