### ISSUE TITLE
Error messages when changing password

### ISSUE THREAD

**Issue by ghofman** [nextcloud/mail#1484]
I am using Nextcloud 14.0.6 with version 0.11.0 of mail on PHP 7.2.11
I have never before had to change the password due to a password change in the remote mail server.

Upon changing the account password in Account settings the following message appears:

_Error while updating the account: Internal Server Error_

The logs in the Nextcloud admin pages say the following:

_TypeError: Argument 5 passed to OCA\Mail\Controller\AccountsController::update() must be of the type string, null given, called in /storage/html/cloud.deontdekkers.nl/nextcloud/lib/private/AppFramework/Http/Dispatcher.php on line 166_

**Comment by ChristophWurst** [comment]
In general, please use the issue template: https://github.com/nextcloud/mail/issues/new?assignees=&labels=bug%2C+0.+to+triage&template=bug.md&title=. Unstructured reports make it a lot hard to quickly triage reports.

**Comment by rullzer** [comment]
Closing in favor of https://github.com/nextcloud/mail/issues/1485
