### ISSUE TITLE
Can't read mail (other clients work fine)

### ISSUE THREAD

**Issue by msbt** [nextcloud/mail#1486]
### Expected behavior
Show contents of email

### Actual behavior
This is shown:
![mail](https://user-images.githubusercontent.com/8767096/51595219-82fe4200-1ef6-11e9-9146-504adf29c1c4.jpg)

This is the only/first mail with that error, others work fine. Probably an exotic header?

### Mail app

**Mail app version:** 0.11.0

**Mailserver or service:** Random ISPs imap server

### Server configuration

**Operating system**: Ubuntu 18.04

**Web server:** Apache + Nginx reverse proxy

**Database:** Postgres

**PHP version:** 7.2

**Nextcloud Version:** 14.0.4

#### Client configuration
**Browser:** Firefox 64.0.2

**Operating system:** Win 7

**Comment by ChristophWurst** [comment]
This might be fixed with 0.12. Let us know once that version has been released and you tested again. Thanks!

**Comment by msbt** [comment]
sure thing, will do!
