### ISSUE TITLE
Autoconfig internal server error

### ISSUE THREAD

**Issue by vondrt4** [nextcloud/mail#1492]
### Expected behavior
A meaningful validation error

### Actual behavior
Error while creating the account: Internal Server Error

### Mail app

**Mail app version: 0.11

There is a problem with insufficient validation of inputs in the function detectImapAndSmtp. When a new user enters an "e-mail address" that doesn't contain the character '@' in the setup form, this happens:
```
TypeError: Argument 1 passed to OCA\Mail\Service\AutoConfig\IspDb::query() must be of the type string, null given, called in /usr/share/nextcloud/apps/mail/lib/Service/AutoConfig/IspDbConfigurationDetector.php on line 94

    /usr/share/nextcloud/apps/mail/lib/Service/AutoConfig/IspDbConfigurationDetector.php - line 94:

    OCA\Mail\Service\AutoConfig\IspDb->query(null)

    /usr/share/nextcloud/apps/mail/lib/Service/AutoConfig/AutoConfig.php - line 53:

    OCA\Mail\Service\AutoConfig\IspDbConfigurationDetector->detectImapAndSmtp("a.b.com", "password", "A B")
...
```

**Comment by ChristophWurst** [comment]
This was reworked in #2259. Please test with a recent version.
