### ISSUE TITLE
Error: e[0] is undefined.

### ISSUE THREAD

**Issue by trite2k3** [nextcloud/mail#1514]
### Expected behavior
Load e-mails in Inbox.

### Actual behavior
Page is blank and displays error at top of page:
"Error: e[0] is undefined."

### Mail app

**Mail app version:** (see apps admin page, e.g. 0.5.3)
Mail 0.11.0

**Mailserver or service:** (e.g. Outlook, Yahoo, Gmail, Exchange,...)
Self-hosted Sendmail on CentOS.

### Server configuration
Standard CentOS Sendmail conf. with IMAP added.

**Operating system**: (e.g. Debian 8)
Docker image

**Web server:** (e.g. Apache, Nginx,...)
Nginx reverse proxy to Docker image

**Database:** (e.g. MariaDB, SQLite or PostgreSQL)
SQLite, but same problem if I try with MariaDB or MySQL.

**PHP version:** (e.g. 7.0)
Dont know, I use official Docker image.

**Nextcloud Version:** (see admin page, e.g. 13.0.2)
Nextcloud 15.0.2
Docker image: nextcloud
NAME                            DESCRIPTION                                     STARS     OFFICIAL   AUTOMATED
nextcloud                       A safe home for all your data                   803       [OK] 

#### Client configuration
**Browser:** (e.g. Firefox 48)
Firefox Quantum 60.4.0esr 64-bit
If I try with chrome I get "An unknown error has occured." and "Error: Cannot read property 'label' of undefined."

**Operating system:** (e.g. Arch Linux)
Official Docker image

####Other
This works when I get new e-mails, but when it tries to load some old ones I get this error 100% of the time. With new e-mails it seems to be random if its works or not, some e-mails seems to trigger this error and some not. Some e-mails that trigger this seems to be spam but the old ones that I want saved that is always causing this is not spam.

**Comment by ChristophWurst** [comment]
This should be fixed with the upcoming v0.12

**Comment by trite2k3** [comment]
It disappears if either I get a lot of email that works so it doesnt try and load the bad emails. I just wiped my inbox folder and it is loading just fine after that.

Thanks I'll wait for the next version. Prolly need better spamfilter but I cba to fix.
