### ISSUE TITLE
Settingspage not loaded if authentication failed

### ISSUE THREAD

**Issue by hechi** [nextcloud/mail#152]
### Steps to reproduce
1. change settings to not valid once (example change sslMode)
2. save changes in DB or late with #132
3. reload page
### Expected behaviour

The Settingspage tells me that it doesn't work, but i am able to change settings.
### Actual behaviour

Spinner appears and nothing happens.
### Mail app

**Mail app version:** git branch issue_16_editAccountSettings, but i guess its in the current master

**Mailserver or service:** own

**Transport security - IMAP:** (None, SSL, TLS, STARTTLS) 

**Transport security - SMTP:** (None, SSL, TLS, STARTTLS)

**Number of accounts:** 1

**Mail app version build date:** my branch
### Server configuration

**Operating system**: Debian

**Web server:** Nginx 

**Database:** sqlite

**PHP version:** 7

**Version:** current git

**Updated from an older version or fresh install:** fresh

**List of activated apps:** mail, files

```
If you have access to your command line run e.g.:
sudo -u www-data php occ app:list
from within your server installation folder
```

<details>
{"reqId":"uIfvXXyPa3dVZUvguhh8","remoteAddr":"192.168.56.1","app":"index","message":"Exception: {\"Exception\":\"Horde_Imap_Client_Exception\",\"Message\":\"No supported IMAP authentication method could be found.\",\"Code\":101,\"Trace\":\"#0 \\/media\\/sf_nextcloud\\/mail\\/vendor\\/pear-pear.horde.org\\/Horde_Imap_Client\\/Horde\\/Imap\\/Client\\/Base.php(831): Horde_Imap_Client_Socket->_login(**\* sensitive parameters replaced **_)\n#1 \\/media\\/sf_nextcloud\\/mail\\/lib\\/Account.php(166): Horde_Imap_Client_Base->login(**_ sensitive parameters replaced ***)\n#2 \\/media\\/sf_nextcloud\\/mail\\/lib\\/Account.php(299): OCA\\Mail\\Account->getImapConnection()\n#3 \\/media\\/sf_nextcloud\\/mail\\/lib\\/Account.php(345): OCA\\Mail\\Account->listMailboxes()\n#4 \\/media\\/sf_nextcloud\\/mail\\/lib\\/Account.php(358): OCA\\Mail\\Account->getMailboxes()\n#5 \\/media\\/sf_nextcloud\\/mail\\/lib\\/Controller\\/FoldersController.php(62): OCA\\Mail\\Account->jsonSerialize()\n#6 [internal function]: OCA\\Mail\\Controller\\FoldersController->index(2)\n#7 \\/media\\/sf_nextcloud\\/server\\/lib\\/private\\/AppFramework\\/Http\\/Dispatcher.php(160): call_user_func_array(Array, Array)\n#8 \\/media\\/sf_nextcloud\\/server\\/lib\\/private\\/AppFramework\\/Http\\/Dispatcher.php(90): OC\\AppFramework\\Http\\Dispatcher->executeController(Object(OCA\\Mail\\Controller\\FoldersController), 'index')\n#9 \\/media\\/sf_nextcloud\\/server\\/lib\\/private\\/AppFramework\\/App.php(114): OC\\AppFramework\\Http\\Dispatcher->dispatch(Object(OCA\\Mail\\Controller\\FoldersController), 'index')\n#10 \\/media\\/sf_nextcloud\\/server\\/lib\\/private\\/AppFramework\\/Routing\\/RouteActionHandler.php(47): OC\\AppFramework\\App::main('FoldersControll...', 'index', Object(OC\\AppFramework\\DependencyInjection\\DIContainer), Array)\n#11 [internal function]: OC\\AppFramework\\Routing\\RouteActionHandler->__invoke(Array)\n#12 \\/media\\/sf_nextcloud\\/server\\/lib\\/private\\/Route\\/Router.php(298): call_user_func(Object(OC\\AppFramework\\Routing\\RouteActionHandler), Array)\n#13 \\/media\\/sf_nextcloud\\/server\\/lib\\/base.php(994): OC\\Route\\Router->match('\\/apps\\/mail\\/acco...')\n#14 \\/media\\/sf_nextcloud\\/server\\/index.php(40): OC::handleRequest()\n#15 {main}\",\"File\":\"\\/media\\/sf_nextcloud\\/mail\\/vendor\\/pear-pear.horde.org\\/Horde_Imap_Client\\/Horde\\/Imap\\/Client\\/Socket.php\",\"Line\":497}","level":3,"time":"2016-10-14T13:03:02+00:00","method":"GET","url":"\/index.php\/apps\/mail\/accounts\/2\/folders","user":"root","version":"9.2.0.4"}

</details>

**Comment by Yamakasi** [comment]
What is the status here ? as the app is actually unusable with thisissue and I wonder if someone actually uses it now and why this is not fixed.

**Comment by ChristophWurst** [comment]
> What is the status here ? as the app is actually unusable with thisissue and I wonder if someone actually uses it now and why this is not fixed.

Hi @Yamakasi,

you may have noticed that we're developing this app in our free time. Therefore our resources are limited and we cannot respond to bug reports as fast as we'd like to. I am sorry that the app is unusable at the moment from your point of view.

If you or someone else could actually help us fix this bug, you would be very welcome to do so 😉

**Comment by Yamakasi** [comment]
@ChristophWurst yes I understand but I think it's mayor to get fixed if we want to keep NextCloud as an success.

I need to read myself into what is done and how the plugin works, but we could temporary publish some fix maybe to manually cleanup the DB for it.

**Comment by ChristophWurst** [comment]
Found it! We start Backbone history only we can load accounts and folder successfully (which we don't in case of an authentication error): https://github.com/nextcloud/mail/blob/29dd3ee2d2cf05d88bea61337885e3ff139cbdc4/js/app.js#L84-L89

**Comment by Yamakasi** [comment]
Cool, so we need some if statement when that errors?

2017-01-23 11:27 GMT+01:00 Christoph Wurst <notifications@github.com>:

**Comment by ChristophWurst** [comment]
Nope, we just have to register a `then` handler on that promise that is executed in any case. I will try to fix this ASAP :-)

**Comment by Yamakasi** [comment]
OK, great let me know if you need some help :)

2017-01-23 15:47 GMT+01:00 Christoph Wurst <notifications@github.com>:

**Comment by ChristophWurst** [comment]
Just found out that this actually does already work as I've added an error handler in the account controller https://github.com/nextcloud/mail/blob/be8c8eff74f5745c9d2f6c062d2aa2c23f2fa7c6/js/controller/accountcontroller.js#L50-L52. Therefore, the code in app.js is executed in all cases and initializes the Backbone router properly 🚀

**Comment by Yamakasi** [comment]
I need to test it but that does not load the actual setting page as far as
I can see ? As that is what we need, we need to change out password or so @
nextcloud side, not fix anything serverside.

2017-02-06 9:52 GMT+01:00 Christoph Wurst <notifications@github.com>:

**Comment by ChristophWurst** [comment]
@Yamakasi that is a different problem. This ticket was about showing the settings page. You're requesting a feature that @hechi is working on in #16 😉

**Comment by Yamakasi** [comment]
As i would show the same page every time I would say it's the "same" issue.

2017-02-06 10:11 GMT+01:00 Christoph Wurst <notifications@github.com>:
