### ISSUE TITLE
View Headers support

### ISSUE THREAD

**Issue by jgoerzen** [nextcloud/mail#1522]
### Feature Request

Mail app needs a "view headers" feature.  This is important for:

- People trying to differentiate scam from legitimate mail
- People making abuse reports of spam or phishing email

These are both related to the security and integrity of mail accounts and are quite important.

**Comment by ChristophWurst** [comment]
Sounds like a nice enhancement!

**Comment by ChristophWurst** [comment]
> ... are quite important.

Contributions are welcome any time!

**Comment by jancborchardt** [comment]
Is this part of **View raw message source #2264** @StCyr? Sounds like it belongs together. :)

**Comment by StCyr** [comment]
Sure, « view raw message » let you see its headers, obviously :)
