### ISSUE TITLE
mail setting

### ISSUE THREAD

**Issue by charwavid** [nextcloud/mail#1523]
I used the 163.com and qq.com mailboxes for configuration, and they could not succeed.
Error message：
Error while creating the account: Failed to create account: Error connecting to mail server.

help me.
![shot20190208015](https://user-images.githubusercontent.com/7514841/52470347-d811a780-2bc8-11e9-84eb-ca42d68b8936.png)

**Comment by ChristophWurst** [comment]
The Nextcloud mail app offers an extensive logging system to make it easier identifying and tracking down bugs. Please enable [debug mode](https://docs.nextcloud.com/server/13/developer_manual/general/devenv.html#enabling-debug-mode) and set the log [level to debug](https://docs.nextcloud.com/server/13/admin_manual/configuration_server/logging_configuration.html) in your admin settings. Then, try to reproduce your issue and take another look at `data/nextcloud.log`, `data/horde_imap.log` and `data/horde_smtp.log`.
