### ISSUE TITLE
Drag n drop (move) from Inbox to subfolder doesnt work

### ISSUE THREAD

**Issue by g6094199** [nextcloud/mail#1538]
### Expected behavior
Drag n drop from Inbox to subfolder

### Actual behavior
Doesnt work.

### Mail app

0.12.0 Beta2

**Mailserver or service:** 
Freenet, GMX

### Server configuration

**Operating system**: Ubuntu 18.04 HWE

**Web server:** NGinx

**Database:** MariaDB

**PHP version:** 7.2

**Nextcloud Version:** 15.0.4

#### Client configuration
**Browser:** FF65, Chromium 71.0

**Operating system:** Ubuntu 18.10

**Comment by ChristophWurst** [comment]
Yeah, unfortunately we had to drop the feature because I could not achieve the same behavior with any Vue drag and drop library. We will definitely add the feature back once we figured out how.

**Comment by ChristophWurst** [comment]
PR: https://github.com/nextcloud/mail/pull/1243

**Comment by g6094199** [comment]
ok, will keep an eye on this ;-)

**Comment by dkumor** [comment]
Is there any alternate way to move to a subfolder? I used to use this feature extensively, and can't figure out how to move emails to subfolders at all in the new version.

**Comment by ChristophWurst** [comment]
No, not with Nextcloud Mail at the moment.

**Comment by avanc** [comment]
Two suggestions:

- Delete _ 0.12.0 Beta2_ from the title as the issue is a general problem and this distracts.
- Add "_(move to another folder)_" to the title as history indicates many persons search for _move_ instead of _drag and drop_.

**Comment by LeoSum8** [comment]
I understand there is a problem with implementing the drag and drop part of this feature. 

Would it be easier to implement the move function via a context menu, similar to the files app? This would also help the touchscreen-friendlyness of the app.

I consider this a core feature for any mail app for anyone who practices empty inbox :)

**Comment by ChristophWurst** [comment]
> Nevermind, I just found that exactly that is already being discussed here: #255 and #2834

Yep. Biggest blocker for the (non d-n-d) move is the mailbox picker component. The rest is easy :)

**Comment by liquidat** [comment]
Just for a better understanding: why does the [approach of the tasks app](https://github.com/nextcloud/tasks/blob/master/src/components/TaskDragContainer.vue) in Nextcloud does not work here? Drag&Drop seems to work rather well there, their challenge is also to drag objects from a detailed view on the right to a list view on the left.

**Comment by ChristophWurst** [comment]
See #2834

**Comment by st3iny** [comment]
See #4048 for the new drag and drop feature.
