### ISSUE TITLE
0.12.0 Beta2: Several accounts share the same indicator color

### ISSUE THREAD

**Issue by g6094199** [nextcloud/mail#1539]
### Expected behavior
Every account has its own color.

### Actual behavior
Several account share the same colour. 3 in my case, but the the 3rd is out of side at the screenshot

![grafik](https://user-images.githubusercontent.com/37833326/53090800-bb526980-3510-11e9-8922-6ef9e6ec398c.png)

### Mail app

0.12.0 Beta2

**Mailserver or service:** 
Freenet, GMX

### Server configuration

**Operating system**: Ubuntu 18.04 HWE

**Web server:** Nginx

**Database:** MariaDB

**PHP version:** 7.2

**Nextcloud Version:** 15.0.4

#### Client configuration
**Browser:** FF65, Chromium 71.0

**Operating system:** Ubuntu 18.10

**Comment by ChristophWurst** [comment]
I've seen that as well. This seems to be a bug as it used to work when I rewrote that code.

**Comment by ChristophWurst** [comment]
If anybody is interested in helping with a fix you can find the code here: https://github.com/nextcloud/mail/blob/202c442a163966122378eb75f0f94450dbb4cdb8/src/mixins/SidebarItems.js#L21and https://github.com/nextcloud/mail/blob/202c442a163966122378eb75f0f94450dbb4cdb8/src/util/AccountColor.js#L25-L31

**Comment by ChristophWurst** [comment]
Oh, I think I know what the bug is. We use the acount *name* (e.g. "Christoph Wurst") and not the email address for the color. That's why you see two accounts with the same color as the name is identical ;)
