### ISSUE TITLE
0.12.0 Beta2: Accounts/subfolders are shown duplicated

### ISSUE THREAD

**Issue by g6094199** [nextcloud/mail#1540]
### Expected behavior
Every account is shown once

### Actual behavior
My GMX account is shown twice **sometimes**, also it hat duplicated INBOX and subfolders.
I have seen this only on FF up to now. 

![grafik](https://user-images.githubusercontent.com/37833326/53091139-7549d580-3511-11e9-8a0f-47212753fb76.png)

### Mail app

0.12.0 Beta2

**Mailserver or service:** 
Freenet, GMX

### Server configuration

**Operating system**: Ubuntu 18.04 HWE

**Web server:** NGinx

**Database:** MariaDB

**PHP version:** 7.2

**Nextcloud Version:** 15.0.4

#### Client configuration
**Browser:** FF65

**Operating system:** Ubuntu 18.10

**Comment by ChristophWurst** [comment]
First of all, thank you very much for testing the beta :raised_hands: 

> sometimes

Let me guess: it happened when you switched to the account settings page and back? This was fixed in https://github.com/nextcloud/mail/pull/1488 ;)

**Comment by g6094199** [comment]
> Let me guess: it happened when you switched to the account settings page and back? This was fixed in #1488 ;)

hmmm...maybe.....i'll check the next beta

thx
