### ISSUE TITLE
0.12.0 Beta2: Not possible to reply to mails from subfolders

### ISSUE THREAD

**Issue by g6094199** [nextcloud/mail#1554]
### Expected behavior
Reply to sender even if the emails are located in subfolders.

### Actual behavior
On hitting "send" the following error occours.

![grafik](https://user-images.githubusercontent.com/37833326/53341851-f1c32680-390c-11e9-9f22-b9748355194c.png)

In this case its a subfolder of the INBOX from an freenet.de account

### Mail app

0.12.0 Beta2

**Mailserver or service:** 
Freenet, GMX

### Server configuration

**Operating system**: Ubuntu 18.04 HWE

**Web server:** Nginx

**Database:** MariaDB

**PHP version:** 7.2

**Nextcloud Version:** 15.0.5 RC

#### Client configuration
**Browser:** FF65, Chromium 71.0

**Operating system:** Ubuntu 18.10

**Comment by ChristophWurst** [comment]
Could you check your nextcloud.log? Error 500s are usually logged in detail. Thanks :v:

**Comment by g6094199** [comment]
`



{"reqId":"bbxyw8gzU4CDGO3HnRjr","level":1,"time":"2019-02-26T10:14:08+01:00","remoteAddr":"93.104.117.121","user":"xxxxx","app":"mail","method":"POST","url":"\/index.php\/apps\/mail\/api\/accounts\/6\/draft","message":"Updating
draft <759> in account <6>","userAgent":"Mozilla\/5.0 (X11; Ubuntu;
Linux x86_64; rv:65.0) Gecko\/20100101 Firefox\/65.0","version":"15.0.5.1"}
{"reqId":"QRBCGF6Q8U2eQF52umXr","level":4,"time":"2019-02-26T10:14:10+01:00","remoteAddr":"93.104.117.121","user":"xxx","app":"mail","method":"POST","url":"\/index.php\/apps\/mail\/api\/accounts\/6\/send","message":"Sending
mail failed: Could not open mailbox
\"INBOX.Fluessig\".","userAgent":"Mozilla\/5.0 (X11; Ubuntu; Linux
x86_64; rv:65.0) Gecko\/20100101 Firefox\/65.0","version":"15.0.5.1"}
{"reqId":"QRBCGF6Q8U2eQF52umXr","level":3,"time":"2019-02-26T10:14:10+01:00","remoteAddr":"93.104.117.121","user":"xxxx","app":"mail","method":"POST","url":"\/index.php\/apps\/mail\/api\/accounts\/6\/send","message":{"Exception":"Horde_Imap_Client_Exception","Message":"Could
not open mailbox
\"INBOX.Fluessi\".","Code":200,"Trace":[{"file":"\/var\/www\/nextcloud\/apps\/mail\/vendor\/pear-pear.horde.org\/Horde_Imap_Client\/Horde\/Imap\/Client\/Base.php","line":1046,"function":"_openMailbox","class":"Horde_Imap_Client_Socket","type":"->","args":[{"__class__":"Horde_Imap_Client_Mailbox"},1]},{"file":"\/var\/www\/nextcloud\/apps\/mail\/vendor\/pear-pear.horde.org\/Horde_Imap_Client\/Horde\/Imap\/Client\/Base.php","line":2506,"function":"openMailbox","class":"Horde_Imap_Client_Base","type":"->","args":[{"__class__":"Horde_Imap_Client_Mailbox"},1]},{"file":"\/var\/www\/nextcloud\/apps\/mail\/vendor\/pear-pear.horde.org\/Horde_Imap_Client\/Horde\/Imap\/Client\/Base.php","line":2473,"function":"_fetchWrapper","class":"Horde_Imap_Client_Base","type":"->","args":[{"__class__":"Horde_Imap_Client_Mailbox"},{"__class__":"Horde_Imap_Client_Fetch_Query"},{"ids":{"duplicates":false,"__class__":"Horde_Imap_Client_Ids"}}]},{"file":"\/var\/www\/nextcloud\/apps\/mail\/lib\/Model\/IMAPMessage.php","line":330,"function":"fetch","class":"Horde_Imap_Client_Base","type":"->","args":[{"__class__":"Horde_Imap_Client_Mailbox"},{"__class__":"Horde_Imap_Client_Fetch_Query"},{"ids":{"duplicates":false,"__class__":"Horde_Imap_Client_Ids"}}]},{"file":"\/var\/www\/nextcloud\/apps\/mail\/lib\/Model\/IMAPMessage.php","line":96,"function":"loadMessageBodies","class":"OCA\\Mail\\Model\\IMAPMessage","type":"->","args":[]},{"file":"\/var\/www\/nextcloud\/apps\/mail\/lib\/Mailbox.php","line":228,"function":"__construct","class":"OCA\\Mail\\Model\\IMAPMessage","type":"->","args":[{"cacheFields":{"9":"HICenv","10":"HICflags","8":"HIChdrs","11":"HICdate","12":"HICsize","1":"HICstruct"},"changed":true,"statuscache":true,"__class__":"Horde_Imap_Client_Socket"},{"__class__":"Horde_Imap_Client_Mailbox"},77,null,false]},{"file":"\/var\/www\/nextcloud\/apps\/mail\/lib\/Service\/MailTransmission.php","line":167,"function":"getMessage","class":"OCA\\Mail\\Mailbox","type":"->","args":[77]},{"file":"\/var\/www\/nextcloud\/apps\/mail\/lib\/Service\/MailTransmission.php","line":100,"function":"buildReplyMessage","class":"OCA\\Mail\\Service\\MailTransmission","type":"->","args":[{"__class__":"OCA\\Mail\\Account"},{"__class__":"OCA\\Mail\\Model\\NewMessageData"},{"__class__":"OCA\\Mail\\Model\\RepliedMessageData"}]},{"file":"\/var\/www\/nextcloud\/apps\/mail\/lib\/Controller\/AccountsController.php","line":269,"function":"sendMessage","class":"OCA\\Mail\\Service\\MailTransmission","type":"->","args":["xxxx",{"__class__":"OCA\\Mail\\Model\\NewMessageData"},{"__class__":"OCA\\Mail\\Model\\RepliedMessageData"},null,760]},{"file":"\/var\/www\/nextcloud\/lib\/private\/AppFramework\/Http\/Dispatcher.php","line":166,"function":"send","class":"OCA\\Mail\\Controller\\AccountsController","type":"->","args":[6,"RE:
AW: Gaspreis","test\n\n\", xxxxx\" <xxxxxxe.de> \u2013
5. Mai 2017 17:29\n> 

....BODY....

"\"'xxxxx.de'\"
<xxxxx.de>, \"xxxxx\"
<xxxxxx.de>","","",760,"SU5CT1guRmx1ZXNzaWdnYXM=",77,[],null]},{"file":"\/var\/www\/nextcloud\/lib\/private\/AppFramework\/Http\/Dispatcher.php","line":99,"function":"executeController","class":"OC\\AppFramework\\Http\\Dispatcher","type":"->","args":[{"__class__":"OCA\\Mail\\Controller\\AccountsController"},"send"]},{"file":"\/var\/www\/nextcloud\/lib\/private\/AppFramework\/App.php","line":118,"function":"dispatch","class":"OC\\AppFramework\\Http\\Dispatcher","type":"->","args":[{"__class__":"OCA\\Mail\\Controller\\AccountsController"},"send"]},{"file":"\/var\/www\/nextcloud\/lib\/private\/AppFramework\/Routing\/RouteActionHandler.php","line":47,"function":"main","class":"OC\\AppFramework\\App","type":"::","args":["OCA\\Mail\\Controller\\AccountsController","send",{"__class__":"OC\\AppFramework\\DependencyInjection\\DIContainer"},{"accountId":"6","_route":"mail.accounts.send"}]},{"function":"__invoke","class":"OC\\AppFramework\\Routing\\RouteActionHandler","type":"->","args":[{"accountId":"6","_route":"mail.accounts.send"}]},{"file":"\/var\/www\/nextcloud\/lib\/private\/Route\/Router.php","line":297,"function":"call_user_func","args":[{"__class__":"OC\\AppFramework\\Routing\\RouteActionHandler"},{"accountId":"6","_route":"mail.accounts.send"}]},{"file":"\/var\/www\/nextcloud\/lib\/base.php","line":987,"function":"match","class":"OC\\Route\\Router","type":"->","args":["\/apps\/mail\/api\/accounts\/6\/send"]},{"file":"\/var\/www\/nextcloud\/index.php","line":42,"function":"handleRequest","class":"OC","type":"::","args":[]}],"File":"\/var\/www\/nextcloud\/apps\/mail\/vendor\/pear-pear.horde.org\/Horde_Imap_Client\/Horde\/Imap\/Client\/Socket.php","Line":1239,"CustomMessage":"--"},"userAgent":"Mozilla\/5.0
(X11; Ubuntu; Linux x86_64; rv:65.0) Gecko\/20100101
Firefox\/65.0","version":"15.0.5.1"}
`

**Comment by ChristophWurst** [comment]
> Could
> not open mailbox
> "INBOX.Fluessi".

This could mean it just fails when it tries to flag the original messge as replied. Could you check if the mail is sent regardless of the error?

**Comment by g6094199** [comment]
Nope,

since i'm in cc i  should receive a copy, but no copy arrives. Tested with the subfolder. In the inbox it works, incl. copy.

**Comment by g6094199** [comment]
seems to be fixed. tested with v 0.17
