### ISSUE TITLE
app.mail.accounts.default in config not working as expected

### ISSUE THREAD

**Issue by Pammetje** [nextcloud/mail#1555]
This admin config is not working as expected.

'app.mail.accounts.default' => [
    'email' => '%EMAIL%',
    'imapHost' => 'mail.domain.tld',
    'imapPort' => 993,
    'imapUser' => '%USERID%',
    'imapSslMode' => 'ssl',
    'smtpHost' => 'mail.domain.tld',
    'smtpPort' => 25,
    'smtpUser' => '%USERID%',
    'smtpSslMode' => 'tls',
  ],

When I choose %EMAIL% in the 'email' variable I also get the email variable values configured in the 'imapUser' and smtpUser' variable, and not the %USERID% value as expected.

Is this a bug ? or please let me know how to fix this

Kr,

Pammetje

**Comment by ChristophWurst** [comment]
You can find the logic here: https://github.com/nextcloud/mail/blob/master/lib/Service/DefaultAccount/Config.php
