### ISSUE TITLE
"Scrambled message"

### ISSUE THREAD

**Issue by adi-dev** [nextcloud/mail#1579]
### Expected behavior
Open email -> normal text displayed

### Actual behavior
Open email -> something like: "HY?[H?]?[Y?Y܈??X?]Y???H\????\?H܈[?]]ܚ\?Y\?K\?[XZ[[??۝[??" is shown

### Mail app

**Mail app version:** 0.11.0

**Mailserver or service:** cPanel and GMX

### Server configuration

**Operating system:** Ubuntu 18.04.2 LTS

**Web server:** Apache 2

**Database:** PostgreSQL

**PHP version:** 7.2.15

**Nextcloud Version:** 15.0.5.3

#### Client configuration
**Browser:** Firefox 65.0.2 and Chrome 72

**Operating system:** Client: Windows 10, Server: Ubuntu 18.04.2 LTS

**Screenshot:**

![screenshot 2019-03-05 1](https://user-images.githubusercontent.com/7880069/53836578-43605680-3f88-11e9-8489-f0f5fafc7822.png)

**Comment by dkumor** [comment]
I also have this issue, specifically when receiving verification emails from mozilla account services (adding device/etc).

![image](https://user-images.githubusercontent.com/5931166/53843889-ea85c380-3f71-11e9-8877-7d6f3323166b.png)

I have attached the raw underlying email that caused this on my server:
[ffmail.txt](https://github.com/nextcloud/mail/files/2933533/ffmail.txt)

**Comment by ChristophWurst** [comment]
You could try the patch at https://github.com/nextcloud/mail/pull/1396

**Comment by ChristophWurst** [comment]
But I think this is fixed with the upcoming v0.12. You can also try that with a beta from the github releases page

**Comment by Heracles31** [comment]
Hey Christoph,

Any hint on how long before v0.12 ? These scrambled messages are pretty annoying :-)

I will not install beta or dev versions in my Nextcloud because I now rely too much on it for everything I have and also for people around me...

In all cases, congrats for your great work

**Comment by ChristophWurst** [comment]
You'll be pleasantly surprised what Mail can do once you update to Nextcloud 16: https://github.com/nextcloud/mail/releases
