### ISSUE TITLE
Can't seem to connect o Office365 mail

### ISSUE THREAD

**Issue by ConorIA** [nextcloud/mail#158]
### Steps to reproduce
1. Add new account firstname.lastname@mail.utoronto.ca
2. Set up incoming to: outlook.office365.com:993; outgoing to: smtp.office365.com:587

### Expected behaviour
School account should be added

### Actual behaviour
Adding account fails with a `Creating account failed: Server denied authentication.`	

### Mail app

**Mail app version:** 0.6.0

**Mailserver or service:** Office365 with school domain

**Transport security - IMAP:** SSL

**Transport security - SMTP:** STARTTLS

**Number of accounts:** 1

### Server configuration
**Operating system**: Linux/Docker

**Web server:** Nginx

**Database:** Mysql 7.0.11

**PHP version:** 7.0.11

**Version:** 10.0.1

**Updated from an older version or fresh install:** Upgrade, but didn't work on a fresh install either.

**List of activated apps:** 
- bookmarks
- calendar
- tasks
- mail
- contacts
- documents
- files
- gallery 
- notes

**The content of config/config.php:**

```
<?php
$CONFIG = array (
  'datadirectory' => '/data',
...
  'trusted_domains' => 
  array (
...
  ),
  'overwrite.cli.url' => 'https://172.17.0.7:8888',
  'dbtype' => 'mysql',
  'version' => '9.1.1.5',
  'dbname' => 'nextcloud',
  'dbhost' => 'db_nextcloud',
  'dbport' => '',
  'dbtableprefix' => 'oc_',
...
  'logtimezone' => 'UTC',
  'installed' => true,
  'overwriteprotocol' => 'https',
  'appstore.experimental.enabled' => true,
  'loglevel' => 3,
  'apps_paths' => 
  array (
    0 => 
    array (
      'path' => '/nextcloud/apps',
      'url' => '/apps',
      'writable' => false,
    ),
    1 => 
    array (
      'path' => '/apps2',
      'url' => '/apps2',
      'writable' => true,
    ),
  ),
  'memcache.local' => '\\OC\\Memcache\\APCu',
  'theme' => '',
  'maintenance' => false,
...
  'updater.release.channel' => 'stable',
);
```

#### Client configuration
**Browser:** Brave 0.12.4

**Operating system:** Manjaro Linux x64

##### Web server error log
_nothing relevant_

##### Server log (data/owncloud.log or data/nextcloud.log)
[nextcloud.txt](https://github.com/owncloudarchive/mail/files/531496/nextcloud.txt)

##### Horde IMAP log (data/horde_imap.log)
```
$ cat horde_imap.log
------------------------------
>> Sun, 16 Oct 2016 17:34:01 +0000
>> Connection to: imap://outlook.office365.com:993/
>> Server connection took 0.0992 seconds.
S: * OK The Microsoft Exchange IMAP4 service is ready. [QgBMAFUAUABSADEAOABDAEEAMAAwADMAMAAuAG4AYQBtAHAAcgBkADEAOAAuAHAAcgBvAGQALgBvAHUAdABsAG8AbwBrAC4AYwBvAG0A]
C: 1 CAPABILITY
S: * CAPABILITY IMAP4 IMAP4rev1 AUTH=PLAIN AUTH=XOAUTH2 SASL-IR UIDPLUS ID UNSELECT CHILDREN IDLE NAMESPACE LITERAL+
S: 1 OK CAPABILITY completed.
>> Command 1 took 0.0382 seconds.
C: 2 AUTHENTICATE PLAIN [INITIAL CLIENT RESPONSE (username: firstname.lastname@mail.utoronto.ca)]
S: 2 OK AUTHENTICATE completed.
>> Command 2 took 0.9628 seconds.
C: 3 CAPABILITY
S: * CAPABILITY IMAP4 IMAP4rev1 AUTH=PLAIN AUTH=XOAUTH2 SASL-IR UIDPLUS MOVE ID UNSELECT CLIENTACCESSRULES CLIENTNETWORKPRESENCELOCATION BACKENDAUTHENTICATE CHILDREN IDLE NAMESPACE LITERAL+
S: 3 OK CAPABILITY completed.
>> Command 3 took 0.0334 seconds.
>> CACHE: Using the OCA\Mail\Cache\Cache storage driver.
C: 4 LOGOUT
S: * BYE Microsoft Exchange Server 2016 IMAP4 server signing off.
S: 4 OK LOGOUT completed.
>> Command 4 took 0.0328 seconds.
```

##### Horde SMTP log (data/horde_smtp.log)
```
$ cat horde_smtp.log
------------------------------
>> Sun, 16 Oct 2016 17:34:03 +0000
>> Connection to: smtp://smtp.office365.com:587
S: 220 BLUPR16CA0058.outlook.office365.com Microsoft ESMTP MAIL Service ready at Sun, 16 Oct 2016 17:34:02 +0000
C: EHLO b7bd451673ca
S: 250-BLUPR16CA0058.outlook.office365.com Hello [142.1.106.105]
S: 250-SIZE 157286400
S: 250-PIPELINING
S: 250-DSN
S: 250-ENHANCEDSTATUSCODES
S: 250-STARTTLS
S: 250-8BITMIME
S: 250-BINARYMIME
S: 250 CHUNKING
C: STARTTLS
S: 220 2.0.0 SMTP server ready
>> Successfully completed TLS negotiation.
C: EHLO b7bd451673ca
S: 250-BLUPR16CA0058.outlook.office365.com Hello [ser.ver.ip.add]
S: 250-SIZE 157286400
S: 250-PIPELINING
S: 250-DSN
S: 250-ENHANCEDSTATUSCODES
S: 250-AUTH LOGIN
S: 250-8BITMIME
S: 250-BINARYMIME
S: 250 CHUNKING
C: AUTH LOGIN
S: 334 VXNlcm5hbWU6
C: Y29ub3IuYW5kZXJzb25AbWFpbC51dG9yb250by5jYQ==
S: 334 UGFzc3dvcmQ6
[AUTH Command - method: LOGIN; username: firstname.lastname@mail.utoronto.ca]
>> ERROR: Server read/timeout error.
C: QUIT
S: 235 2.7.0 Authentication successful target host DM5PR03MB3050.namprd03.prod.outlook.com
```

**Comment by ChristophWurst** [comment]
Hi @ConorIA,

please enable IMAP logging and post the content of your data/horde_imap.log file (only entries that are generating while adding the account are relevant). This should give us more insights on why the server denies your authentication attempt. See https://github.com/nextcloud/mail#imap-timeout for how to enable logging.

**Comment by ConorIA** [comment]
@ChristophWurst, your comment directed me to the right place, but in the end, it was the heading under logging that helped! It turned out to be an SMTP timeout issue. I have changed timeout to 20s, and adding the account and sending mail works as expected! It seems it is just a slow SMTP server. 

I have also stuck the logs into the original comment for completeness.

**Comment by ChristophWurst** [comment]
Great that it's working now. Thanks for updating the original post. This will potentially help other users who experience the same problem :-)

**Comment by pbek** [comment]
I can confirm this fixed my issue:

```
  'app.mail.imap.timeout' => 25,
  'app.mail.smtp.timeout' => 10,
```

Thanks a lot!
