### ISSUE TITLE
Cannot load mailbox (Error: Cannot read property 'toRgb' of null)

### ISSUE THREAD

**Issue by Hanover96** [nextcloud/mail#1590]
### Expected behavior
Loading the folder/mails in the folder "Inbox".

### Actual behavior
NC Mail App is no loading the folder/mails in the folder "Inbox" - it returns the error "Cannot read property 'toRgb' of null". All other folders/mails in other folders are loading.

### Mail app

**Mail app version:**
0.11.0

**Mailserver or service:**
alfahosting.de IMAP-Server
IMAP c-Client Version 2007f

### Server configuration

**Operating system**:
Linux 4.15.18-11-pve #1 SMP PVE 4.15.18-33 (Tue, 05 Feb 2019 07:36:16 +0100) x86_64

**Web server:**
Apache

**Database:**
MySQL 5.7.25, libmysql - mysqlnd 5.0.11-dev

**PHP version:**
PHP 7.1.26

**Nextcloud Version:**
15.0.5 (stable)

#### Client configuration
**Browser:**
Chrome, MS edge

**Operating system:**
Windows 10

**Comment by ChristophWurst** [comment]
This whould be fixed with the upcoming v0.12.

**Comment by Hanover96** [comment]
Ok, thanks for the info 👍
