### ISSUE TITLE
Account settings editable [$50]

### ISSUE THREAD

**Issue by Quix0r** [nextcloud/mail#16]
Currently you can only "edit" them by deleting and re-adding them. There should be a 2nd option in drop down navigation (under the 3 dots) to edit account settings

**Comment by hechi** [comment]
@ChristophWurst i will try to solve this issue if you want, but it can take time :)

**Comment by ChristophWurst** [comment]
@hechi sure, that would be great ;-)

I've sent you an invitation for the repo, you'll have to be a collaborator before I can assign you

**Comment by Quix0r** [comment]
Yes, usually you don't need to edit them as they are being tested on adding them. But somtimes you need to change password or maybe the host has changed (due to restructuring). Then you need to have an edit function.

**Comment by hechi** [comment]
done https://github.com/nextcloud/mail/pull/163 waiting for review :)
