### ISSUE TITLE
Error in Horde Mime when sending email

### ISSUE THREAD

**Issue by r4sas** [nextcloud/mail#1601]
### Expected behavior
Attachments must be processed without errors

### Actual behavior
PHP error taken in NC logs.
```
[PHP] Error: fwrite(): Unable to create temporary file, Check permissions in temporary files directory. at /apps/mail/vendor/pear-pear.horde.org/Horde_Mime/Horde/Mime/Part.php#1772

POST /apps/mail/api/accounts/1/send
from IP by r4sas at 2019-03-13T10:41:40+00:00
```

### Mail app

**Mail app version:** 0.11.0

**Mailserver or service:** postfix

### Server configuration

**Operating system**: Debian 9

**Web server:** nginx

**Database:** MariaDB

**PHP version:** 7.1

**Nextcloud Version:** 15.0.5

**Additional info:**
PHP works in FPM mode with pool'ed configuration.
Pool for NC has setting to use separated folder for temporary files:
`php_admin_value[upload_tmp_dir] = /home/www/$pool/tmp`

`/home/www/$pool/tmp` directory rights and owner set same as for used in php pool configuration www-data:www-data.

**Comment by ChristophWurst** [comment]
Are you sure this is the temporary directory Nextcloud uses?

**Comment by r4sas** [comment]
If you mean about upload directory - yes, I'm sure.
But which other directories NC can use instead this one for temporary files?

**Comment by ChristophWurst** [comment]
> https://docs.nextcloud.com/server/stable/admin_manual/configuration_server/config_sample_php_parameters.html

> Override where Nextcloud stores temporary files. Useful in situations where the system temporary directory is on a limited space ramdisk or is otherwise restricted, or if external storages which do not support streaming are in use.

Please have a look and experiment with that :)

**Comment by r4sas** [comment]
Ah, I already have that setting in config, which is set to same directory as PHP's temp directory.

**Comment by ChristophWurst** [comment]
Great to hear you could resolve the problem!
