### ISSUE TITLE
Default account messages won't load in v0.12 RC1

### ISSUE THREAD

**Issue by tpkarras** [nextcloud/mail#1603]
### Expected behavior
Message should show in the right hand box.

### Actual behavior
Console returns "TypeError: Cannot read property '1' of null".

### Mail app

**Mail app version:** 0.12 RC1

**Mailserver or service:** Self hosted

### Server configuration

**Operating system**: Debian

**Web server:** Nginx

**Database:** MariaDB

**PHP version:** 7.3

**Nextcloud Version:** 15

#### Client configuration
**Browser:** Chrome 72

**Operating system:** Windows 10 Home

**Comment by ChristophWurst** [comment]
Could you please post the full error trace? Thanks!

**Comment by tpkarras** [comment]
This is it.

mail.js?v=60dc4ddd-1:15 TypeError: Cannot read property '1' of null
    at a (mail.js?v=60dc4ddd-1:15)
    at ee.fetchMessage (mail.js?v=60dc4ddd-1:79)
    at Array.<anonymous> (mail.js?v=60dc4ddd-1:52)
    at ee.dispatch (mail.js?v=60dc4ddd-1:58)
    at ee.dispatch (mail.js?v=60dc4ddd-1:52)
    at a.fetchMessage (6.mail.js:44)
    at a.$route (6.mail.js:44)
    at dn.run (mail.js?v=60dc4ddd-1:15)
    at ln (mail.js?v=60dc4ddd-1:15)
    at Array.<anonymous> (mail.js?v=60dc4ddd-1:15)

**Comment by ChristophWurst** [comment]
Does your webserver serve `.js.map` files? I was hoping we'd see the stack trace of the actual source code

**Comment by snopy234** [comment]
Mail does not support PHP 7.3 yet. This could be the problem. Downgrade to 7.2 or try again with updates for mail in future.

**Comment by ChristophWurst** [comment]
0.12 does.

**Comment by tpkarras** [comment]
Here's the updated error trace, just added something to my nginx config and walla!

```
vue.runtime.esm.js:1887 TypeError: Cannot read property '1' of null
    at a (EnvelopeUidParser.js:28)
    at ee.fetchMessage (actions.js:429)
    at Array.<anonymous> (vuex.esm.js:721)
    at ee.dispatch (vuex.esm.js:428)
    at ee.dispatch (vuex.esm.js:322)
    at a.fetchMessage (Message.vue:125)
    at a.created (Message.vue:109)
    at Ht (vue.runtime.esm.js:1854)
    at en (vue.runtime.esm.js:4194)
    at a.t._init (vue.runtime.esm.js:4973)
Wt @ vue.runtime.esm.js:1887
qt @ vue.runtime.esm.js:1878
zt @ vue.runtime.esm.js:1839
Ht @ vue.runtime.esm.js:1861
en @ vue.runtime.esm.js:4194
t._init @ vue.runtime.esm.js:4973
a @ vue.runtime.esm.js:5119
(anonymous) @ vue.runtime.esm.js:3276
init @ vue.runtime.esm.js:3107
(anonymous) @ vue.runtime.esm.js:5943
l @ vue.runtime.esm.js:5890
(anonymous) @ vue.runtime.esm.js:6181
E @ vue.runtime.esm.js:6284
(anonymous) @ vue.runtime.esm.js:6447
t._update @ vue.runtime.esm.js:3923
r @ vue.runtime.esm.js:4041
dn.get @ vue.runtime.esm.js:4444
dn.run @ vue.runtime.esm.js:4519
ln @ vue.runtime.esm.js:4275
(anonymous) @ vue.runtime.esm.js:1979
Yt @ vue.runtime.esm.js:1905
Promise.then (async)
Vt @ vue.runtime.esm.js:1932
ee @ vue.runtime.esm.js:1989
(anonymous) @ vue.runtime.esm.js:4367
dn.update @ vue.runtime.esm.js:4509
lt.notify @ vue.runtime.esm.js:730
set @ vue.runtime.esm.js:1055
hn.set @ vue.runtime.esm.js:4596
(anonymous) @ FolderContent.vue:92
Promise.then (async)
fetchData @ FolderContent.vue:88
created @ FolderContent.vue:73
Ht @ vue.runtime.esm.js:1854
en @ vue.runtime.esm.js:4194
t._init @ vue.runtime.esm.js:4973
a @ vue.runtime.esm.js:5119
(anonymous) @ vue.runtime.esm.js:3276
init @ vue.runtime.esm.js:3107
(anonymous) @ vue.runtime.esm.js:5943
l @ vue.runtime.esm.js:5890
h @ vue.runtime.esm.js:6018
l @ vue.runtime.esm.js:5919
(anonymous) @ vue.runtime.esm.js:6181
E @ vue.runtime.esm.js:6284
(anonymous) @ vue.runtime.esm.js:6447
t._update @ vue.runtime.esm.js:3923
r @ vue.runtime.esm.js:4041
dn.get @ vue.runtime.esm.js:4444
dn.run @ vue.runtime.esm.js:4519
ln @ vue.runtime.esm.js:4275
(anonymous) @ vue.runtime.esm.js:1979
Yt @ vue.runtime.esm.js:1905
Promise.then (async)
Vt @ vue.runtime.esm.js:1932
ee @ vue.runtime.esm.js:1989
(anonymous) @ vue.runtime.esm.js:4367
dn.update @ vue.runtime.esm.js:4509
lt.notify @ vue.runtime.esm.js:730
set @ vue.runtime.esm.js:1055
(anonymous) @ vue-router.esm.js:2503
(anonymous) @ vue-router.esm.js:2502
Ct.updateRoute @ vue-router.esm.js:1989
(anonymous) @ vue-router.esm.js:1867
(anonymous) @ vue-router.esm.js:1976
r @ vue-router.esm.js:1706
r @ vue-router.esm.js:1713
bt @ vue-router.esm.js:1717
(anonymous) @ vue-router.esm.js:1971
r @ vue-router.esm.js:1706
(anonymous) @ vue-router.esm.js:1710
(anonymous) @ vue-router.esm.js:1956
(anonymous) @ vue-router.esm.js:1749
(anonymous) @ vue-router.esm.js:1825
Promise.then (async)
(anonymous) @ vue-router.esm.js:1772
(anonymous) @ vue-router.esm.js:1793
(anonymous) @ vue-router.esm.js:1793
xt @ vue-router.esm.js:1792
(anonymous) @ vue-router.esm.js:1728
p @ vue-router.esm.js:1935
r @ vue-router.esm.js:1709
r @ vue-router.esm.js:1713
r @ vue-router.esm.js:1713
bt @ vue-router.esm.js:1717
Ct.confirmTransition @ vue-router.esm.js:1964
Ct.transitionTo @ vue-router.esm.js:1866
e.replace @ vue-router.esm.js:2279
Dt.replace @ vue-router.esm.js:2533
created @ Home.vue:45
Ht @ vue.runtime.esm.js:1854
en @ vue.runtime.esm.js:4194
t._init @ vue.runtime.esm.js:4973
a @ vue.runtime.esm.js:5119
(anonymous) @ vue.runtime.esm.js:3276
init @ vue.runtime.esm.js:3107
(anonymous) @ vue.runtime.esm.js:5943
l @ vue.runtime.esm.js:5890
(anonymous) @ vue.runtime.esm.js:6481
t._update @ vue.runtime.esm.js:3923
r @ vue.runtime.esm.js:4041
dn.get @ vue.runtime.esm.js:4444
dn.run @ vue.runtime.esm.js:4519
ln @ vue.runtime.esm.js:4275
(anonymous) @ vue.runtime.esm.js:1979
Yt @ vue.runtime.esm.js:1905
Promise.then (async)
Vt @ vue.runtime.esm.js:1932
ee @ vue.runtime.esm.js:1989
(anonymous) @ vue.runtime.esm.js:4367
dn.update @ vue.runtime.esm.js:4509
lt.notify @ vue.runtime.esm.js:730
set @ vue.runtime.esm.js:1055
(anonymous) @ vue-router.esm.js:2503
(anonymous) @ vue-router.esm.js:2502
Ct.updateRoute @ vue-router.esm.js:1989
(anonymous) @ vue-router.esm.js:1867
(anonymous) @ vue-router.esm.js:1976
r @ vue-router.esm.js:1706
r @ vue-router.esm.js:1713
bt @ vue-router.esm.js:1717
(anonymous) @ vue-router.esm.js:1971
r @ vue-router.esm.js:1706
(anonymous) @ vue-router.esm.js:1710
(anonymous) @ vue-router.esm.js:1956
(anonymous) @ vue-router.esm.js:1749
(anonymous) @ vue-router.esm.js:1825
Promise.then (async)
(anonymous) @ vue-router.esm.js:1772
(anonymous) @ vue-router.esm.js:1793
(anonymous) @ vue-router.esm.js:1793
xt @ vue-router.esm.js:1792
(anonymous) @ vue-router.esm.js:1728
p @ vue-router.esm.js:1935
r @ vue-router.esm.js:1709
r @ vue-router.esm.js:1713
bt @ vue-router.esm.js:1717
Ct.confirmTransition @ vue-router.esm.js:1964
Ct.transitionTo @ vue-router.esm.js:1866
Dt.init @ vue-router.esm.js:2494
beforeCreate @ vue-router.esm.js:539
Ht @ vue.runtime.esm.js:1854
en @ vue.runtime.esm.js:4194
t._init @ vue.runtime.esm.js:4969
En @ vue.runtime.esm.js:5050
(anonymous) @ main.js:79
o @ bootstrap:63
(anonymous) @ bootstrap:195
(anonymous) @ bootstrap:195
vue.runtime.esm.js:1887 TypeError: Cannot read property '1' of null
    at a (EnvelopeUidParser.js:28)
    at ee.fetchMessage (actions.js:429)
    at Array.<anonymous> (vuex.esm.js:721)
    at ee.dispatch (vuex.esm.js:428)
    at ee.dispatch (vuex.esm.js:322)
    at a.fetchMessage (Message.vue:125)
    at a.$route (Message.vue:105)
    at dn.run (vue.runtime.esm.js:4533)
    at ln (vue.runtime.esm.js:4275)
    at Array.<anonymous> (vue.runtime.esm.js:1979)
```

**Comment by ChristophWurst** [comment]
Thanks a lot @tpkarras! I think I've seen this bug before, but at some point I thought it was fixed. Are there any specific steps you're taking before this shows up (or better: falls apart)?

**Comment by tpkarras** [comment]
@ChristophWurst no specific steps, I just load the mail app and I get the error stack in the console and the message doesn't get shown; shows a spinning loading icon that goes on forever.

**Comment by ChristophWurst** [comment]
[mail.tar.gz](https://github.com/nextcloud/mail/files/3013840/mail.tar.gz)

^ please try this patched version and reproduce the problem. It should log the faulty UID it cannot parse. Thanks :v:

**Comment by tpkarras** [comment]
Hi. I installed the patched version yet I get a different error. "ReferenceError: uid is not defined"

Error stack below.

`vue.runtime.esm.js:1888 ReferenceError: uid is not defined
    at a (EnvelopeUidParser.js:28)
    at ee.fetchMessage (actions.js:440)
    at Array.<anonymous> (vuex.esm.js:721)
    at ee.dispatch (vuex.esm.js:428)
    at ee.dispatch (vuex.esm.js:322)
    at a.fetchMessage (Message.vue:125)
    at a.created (Message.vue:109)
    at Ht (vue.runtime.esm.js:1854)
    at en (vue.runtime.esm.js:4213)
    at a.t._init (vue.runtime.esm.js:5002)
Wt @ vue.runtime.esm.js:1888
qt @ vue.runtime.esm.js:1879
zt @ vue.runtime.esm.js:1839
Ht @ vue.runtime.esm.js:1862
en @ vue.runtime.esm.js:4213
t._init @ vue.runtime.esm.js:5002
a @ vue.runtime.esm.js:5148
(anonymous) @ vue.runtime.esm.js:3283
init @ vue.runtime.esm.js:3114
(anonymous) @ vue.runtime.esm.js:5972
l @ vue.runtime.esm.js:5919
(anonymous) @ vue.runtime.esm.js:6210
E @ vue.runtime.esm.js:6313
(anonymous) @ vue.runtime.esm.js:6476
t._update @ vue.runtime.esm.js:3942
r @ vue.runtime.esm.js:4060
hn.get @ vue.runtime.esm.js:4473
hn.run @ vue.runtime.esm.js:4548
pn @ vue.runtime.esm.js:4304
(anonymous) @ vue.runtime.esm.js:1980
Yt @ vue.runtime.esm.js:1906`

**Comment by ChristophWurst** [comment]
Oh, this is embarrassing. The line I've added in https://github.com/nextcloud/mail/pull/1633/files contained a new bug. Please try one more time with 
[mail.tar.gz](https://github.com/nextcloud/mail/files/3033957/mail.tar.gz)

**Comment by tpkarras** [comment]
I tried it, works as intended; as in it gives me a UID is invalid message finally. Here's the error stack.

```
Error: UID -2-SU5CT1g=-288 is invalid
    at a (EnvelopeUidParser.js:29)
    at ee.fetchMessage (actions.js:440)
    at Array.<anonymous> (vuex.esm.js:721)
    at ee.dispatch (vuex.esm.js:428)
    at ee.dispatch (vuex.esm.js:322)
    at a.fetchMessage (Message.vue:125)
    at a.$route (Message.vue:105)
    at hn.run (vue.runtime.esm.js:4562)
    at pn (vue.runtime.esm.js:4304)
    at Array.<anonymous> (vue.runtime.esm.js:1980)
Wt @ vue.runtime.esm.js:1888
```

**Comment by ChristophWurst** [comment]
Bingo! You're using the *default account* feature, right? That account is set up automatically, hence the special ID *-2*.

**Comment by ChristophWurst** [comment]
I have to test it, but I guess changing the regex to allow a negative number at the beginning will be the fix.

**Comment by ChristophWurst** [comment]
Please test with the new RC3: https://github.com/nextcloud/mail/releases/tag/v0.12.0-RC3

Thanks for the feedback! :)
