### ISSUE TITLE
.app-content-list too narrow to make sense of subjects or mail addresses

### ISSUE THREAD

**Issue by j-4** [nextcloud/mail#1604]
Please set `.app-content-list` `max-width` to `500px` to avoid heavy truncation of almost any mail address and subject line.

Thanks!

**Comment by ChristophWurst** [comment]
Please use the issue template and post screen shots.

https://github.com/nextcloud/mail/issues/new?assignees=&labels=bug%2C+0.+to+triage&template=bug.md&title=

Thanks!
