### ISSUE TITLE
Mail settings on default account failing

### ISSUE THREAD

**Issue by andreas-p** [nextcloud/mail#1612]
On the default mail account, the standard settings are presented but will fail since the settings are configured in config.php. Only the alias is stored.
For the default account, only aliases should be available.

**Comment by ChristophWurst** [comment]
Please use the issue template when filing bug reports: https://github.com/nextcloud/mail/issues/new?assignees=&labels=bug%2C+0.+to+triage&template=bug.md&title=

Thanks
