### ISSUE TITLE
Disabling add new account, only allowing default account

### ISSUE THREAD

**Issue by andreas-p** [nextcloud/mail#1613]
It might be unwanted to allow a user to configure non-default mail accounts, so presenting the "Add mail account" button should be configurable.

**Comment by ChristophWurst** [comment]
Plase use the feature request issue template. It just makes understanding and triaging request easier for everyone: https://github.com/nextcloud/mail/issues/new?assignees=&labels=enhancement%2C+0.+to+triage&template=feature_request.md&title=

The change is subtle here, so just update your ticket.

Thanks
