### ISSUE TITLE
Sent emails are saved in drafts folder

### ISSUE THREAD

**Issue by kovacim** [nextcloud/mail#1616]
### Expected behavior
Sent emails should not be saved in drafts folder

### Actual behavior
After sending an email, it is also saved to the drafts folder

### Mail app

**Mail app version: 0.11.0

**Mailserver or service: Gmail

### Server configuration

**Operating system**: Ubuntu 18.04.2 LTS

**Web server: Apache

**Database: MySql  5.7.25

**PHP version: 7.2.15

**Nextcloud Version: 15.0.5

**Comment by ChristophWurst** [comment]
Could you check if it's really the sent email and not a leftover draft while you were typing?

**Comment by kovacim** [comment]
It's not a leftover draft, but a sent email. The same email is saved to the draft folder and sent folder also.

**Comment by xh3n1** [comment]
@kovacim good to see you here 😍

**Comment by xh3n1** [comment]
@kovacim Also, feel free to contribute since you are familiar with Vue ❤️

**Comment by rubo77** [comment]
the problem is still there!

**Comment by ChristophWurst** [comment]
Ok !

**Comment by jancborchardt** [comment]
@kovacim @rubo77 
- Does this still occur with the latest Mail app?
- Does it happen when you have a single account configured, or multiaccount?
- Is issue https://github.com/nextcloud/mail/issues/2511 the same as this?

Thanks! :)
