### ISSUE TITLE
Email content not showing

### ISSUE THREAD

**Issue by ellis** [nextcloud/mail#1617]
### Expected behavior

When I click on an email, I expect to see the email contents.

### Actual behavior

The `iframe` source is blocked, somehow related to using http instead of https.  In Chrome, I can get the message to display by going to the developer tools and changing the iframe src to use https:

- from http://nextcloud.***.com/apps/mail/api/accounts/1/folders/*******=/messages/**/html
- to https://nextcloud.***.com/apps/mail/api/accounts/1/folders/*******=/messages/**/html

Then it displays fine.

If I don't do that, Firefox shows a rotating circle, and Chrome and Chromium show a grey box with a frowny face and the message "Requests to the server have been blocked by an extension." (NOTE: I have ensured that no extensions are enabled)  I have tried this on multiple computers, multiple browsers, in Private/Incognito mode, and with all extensions turned off, but none of them are working.

Any suggestions?

### Mail app

**Mail app version:** (see apps admin page, e.g. 0.5.3)

0.11.0

**Mailserver or service:** (e.g. Outlook, Yahoo, Gmail, Exchange,...)

Mailcow

### Server configuration

**Operating system**: Ubuntu 18.04

**Web server:** Nginx

**Database:** ?

**PHP version:** ?

**Nextcloud Version:** 15.0.3

#### Client configuration

**Browser:** Google Chrome 73.0.3683.75, Brave Version 0.61.51 Chromium: 73.0.3683.75, Firefox 65.0.1

**Operating system:** Ubuntu 18.04

**Comment by ChristophWurst** [comment]
Have you set a `overwrite.cli.url` in your `config/config.php` or using a proxy?

**Comment by ellis** [comment]
1) I didn't explicitly set `overwrite.cli.url` myself, but its value in `config/config.php` is `'http://localhost'`.

2) My NextCloud is running as a Docker container and it's behind an nginx proxy to manage SSH and the Let's Encrypt certificate.

In case it's relevant: when I open the iframe URL in a new browser window, it automatically directs to https and displays fine.

**Comment by ChristophWurst** [comment]
See https://docs.nextcloud.com/server/stable/admin_manual/configuration_server/config_sample_php_parameters.html#proxy-configurations. Your instance isn't configured properly.

**Comment by ellis** [comment]
Thanks for the very helpful reference, @ChristophWurst!
In case anyone else comes here experiencing the same problem, I had to add `'overwriteprotocol' => 'https'` in `config/config.php`.  I first set `overwrite.cli.url` to my full domain name, but that didn't seem to have an impact.

**Comment by ChristophWurst** [comment]
Great to hear it's working now!

**Comment by epifanio** [comment]
I am having a similar issue - My e-mail account seems to be set up correctly (I can send messages) but the mail contents are not rendered - selecting the inbox - I get: No messages in this folder 
but If I hold the mouse on the inbox and click on the '...' - it shows the number of unread/total messages :( 
 
I have a similar setup, nextcloud running in a docker container and using traefik as a https reverse proxy.

My config.php looks like:

```php
<?php
$CONFIG = array (
  'htaccess.RewriteBase' => '/',
  'memcache.local' => '\\OC\\Memcache\\APCu',
  'apps_paths' => 
  array (
    0 => 
    array (
      'path' => '/var/www/html/apps',
      'url' => '/apps',
      'writable' => false,
    ),
    1 => 
    array (
      'path' => '/var/www/html/custom_apps',
      'url' => '/custom_apps',
      'writable' => true,
    ),
  ),
  'instanceid' => 'oc22dh8feh8o',
  'passwordsalt' => -----------------------------------------------------------',
  'secret' => '--------------------------------------------------------------------',
  'trusted_domains' => 
  array (
    0 => 'ubdomain.domain.com',
  ),
  'datadirectory' => '/var/www/html/data',
  'dbtype' => 'pgsql',
  'version' => '20.0.0.9',
  'overwrite.cli.url' => 'https://subdomain.domain.com',
  'overwriteprotocol' => 'https',
  'dbname' => 'nextcloud',
  'dbhost' => 'db',
  'dbport' => '',
  'dbtableprefix' => 'oc_',
  'dbuser' => 'oc_nextcloud',
  'dbpassword' => '-------------------------------------------------------------',
  'installed' => true,
  'app_install_overwrite' => 
  array (
    0 => 'drawio',
  ),
  'maintenance' => false,
);

```

Any clue on what I am missing in the config, or how to debug the issue?

**Comment by ChristophWurst** [comment]
Open a new bug report with the infos asked in the template.
