### ISSUE TITLE
Scrolling down on mobile doesn't load more mail (Chrome/Android 8.0/Samsung S7)

### ISSUE THREAD

**Issue by jospoortvliet** [nextcloud/mail#1619]
### Expected behavior
When you scroll down in the list of mails, more emails should load.

### Actual behavior
No more emails are loaded after initial batch

### Mail app

**Mail app version:** (see apps admin page, e.g. 0.5.3)
The one on cloud.nextcloud.com... Not sure what version it is.

**Mailserver or service:** (e.g. Outlook, Yahoo, Gmail, Exchange,...)
Nextcloud setup

### Server configuration
cloud.nextcloud.com

#### Client configuration
Latest Chrome on Android 8.0 running on the Samsung S7.

Also, the app when loading initially has the right zoom, but when it shows the list of emails, it gets too wide.
Two screenshots, one showing the screen being too wide, the other the not-loading-more thing.

![screenshot](https://user-images.githubusercontent.com/551757/54700098-9282bb80-4b32-11e9-8eaa-3446f61d608e.png)
![screenshot 2](https://user-images.githubusercontent.com/551757/54700407-4126fc00-4b33-11e9-8078-61a2601610da.png)

**Comment by ChristophWurst** [comment]
Yep, also reported by @rullzer the other week. I have to look into this. The scrolling detection unfortunately doesn't work reliably on mobile. This also breaks the *scroll up to refresh*.

**Comment by ChristophWurst** [comment]
Still the case according to @rullzer

**Comment by GretaD** [comment]
confirm also for priority inbox.
