### ISSUE TITLE
Long from/to mail header text makes content extend horizontally

### ISSUE THREAD

**Issue by dcrobertson01** [nextcloud/mail#1641]
### Expected behavior
email message body should wrap into the space available

### Actual behavior
When an email has a lot of recipients in the 'To:' field, the app-content-details div gets stretched too wide, and the message body does not wrap. 

### Mail app

**Mail app version:** 0.11.0

**Mailserver or service:** Linux server - Postfix and IMAP

### Server configuration

**Operating system**: Nethserver/CentOS 7

**Web server:** Apache

**Database:** MariaDB

**PHP version:** 7.2

**Nextcloud Version:** 15.05

#### Client configuration
**Browser:** Vivaldi, Chromium, Firefox

**Operating system:** Kubuntu

I have had a dig about in the css - the best I can do is use Vivaldi's Page Actions to modify the CSS. Adding 
```
#mail-message-header {
        width: 600px;
}
```
fixes the problem for me.

**Comment by ChristophWurst** [comment]
Please add a screenshot. Thank you.

**Comment by dcrobertson01** [comment]
![nextcloud mail](https://user-images.githubusercontent.com/283012/55920032-597aca00-5c4c-11e9-9bc9-719f153f9db5.png)
![nextcloud mail 2](https://user-images.githubusercontent.com/283012/55920039-60094180-5c4c-11e9-88f2-63b7cd1e1b50.png)

**Comment by dcrobertson01** [comment]
hmm - okay. I have installed the custom ccs app and added: 

```
#mail-message-header {padding: 30px 30px 0 30px;
                        height: inherit;
}
#mail-message-header p {whitespace: inherit;}
.app-content-details {max-width: 650px;}
```
Which works for  me. I cannot see how to avoid using an absolute width here. I would have thought wrapping the recipients would have been enough.

**Comment by ChristophWurst** [comment]
yes we should add ellipsis to this text

**Comment by jancborchardt** [comment]
@dcrobertson01 could you actually open a pull request with your fix? :) That would be much appreciated.

**Comment by StCyr** [comment]
recipient list has been totaly changed in mail version 1.7.

This issue doesn't apply anymore => closing in favor of https://github.com/nextcloud/mail/issues/3743
