### ISSUE TITLE
Backport PHP 7.3 support for NextCloud 15

### ISSUE THREAD

**Issue by J0WI** [nextcloud/mail#1658]
#### Summary

[v0.12.0](https://github.com/nextcloud/mail/releases/tag/v0.12.0) introduces PHP 7.3 support, but raised the required NextCloud version to 16.
Since PHP 7.3 support has been announced for NextCloud 15 it would be great to have a minor backporting this feature.

See also https://github.com/nextcloud/mail/pull/1323#issuecomment-480933498 https://github.com/nextcloud/docker/pull/706#pullrequestreview-223917430

**Comment by ChristophWurst** [comment]
Backport branch with a few fixes is online at https://github.com/nextcloud/mail/tree/stable0.11. I'm now waiting for Dependabot to update the composer packages for the Horde php7.3 compatibility.

**Comment by ChristophWurst** [comment]
Hey @dependabot @feelepxyz @greysteil the initial bump of the stable0.11 branch at https://app.dependabot.com/accounts/nextcloud/repos/66762220 has now taken almost an hour I think. Has it timed out? Will it eventually succeed or show an error?

**Comment by ChristophWurst** [comment]
now it has finished. I don't have any insights into the magic dependabot does but I have the feeling this is a :bug: as there are no PRs for the outdated composer dependencies on that branch

**Comment by feelepxyz** [comment]
@ChristophWurst nice one!

**Comment by GanimanSwift** [comment]
I've just updated to 0.11.1 and this still happens:

This app cannot be installed because the following dependencies are not fulfilled:

    PHP with a version lower than 7.2 is required.
