### ISSUE TITLE
Add support for HTML signatures [$15]

### ISSUE THREAD

**Issue by ChristophWurst** [nextcloud/mail#1659]
### Feature Request

This app will soon support signatures (#1657), but they are plaintext only as our current editor does not speak HTML.

#### Summary

Requires https://github.com/nextcloud/mail/issues/210

**Comment by ChristophWurst** [comment]
I would like to finish this. @jancborchardt any ideas for the interface? Should it be two separate text inputs? We either need two separate signatures or convert the HTML one dynamically (which can remove some advanced stuff like links)

**Comment by jancborchardt** [comment]
Simplest would be one field. Then you can insert HTML stuff just like in the composer. And if you write plaintext mails it will strip HTML elements.

Also we could show a notice about that when you add HTML elements to your signature but use plain text writing mode.

"Plain text writing mode will cause rich text elements to be removed from the signature."

**Comment by Jouwhost** [comment]
I am just a user with a small company, but just wanted to respond to this anyways.

I would really like to have html putt directly in the field. I really do not need an html editor if this means the complete functionality will take longer.
Maybe a simple switch between html and plain text would be enough for now, or the system should recognize this and handle accoridngly.

Having links and an image in the footer is pretty normal these days, It's strange it's not possible for users. They don't understand :)
The footer functionality is not really that usefull at this point. I hope this functionality will improve soon.

Is there any way for me to improve how quickly this may be done?

**Comment by ChristophWurst** [comment]
Please submit at https://github.com/nextcloud/mail/issues/new?assignees=&labels=enhancement%2C+0.+to+triage&template=feature_request.md&title=.

The editor has to strip any unknown HTML elements. Hence letting users edit raw HTML in their signature and then then removing that once used in a new message is a mess. Thus we use the same editor, to have a consistent user experience.

> Is there any way for me to improve how quickly this may be done?

Contribute the change (after discussing it with us) or find someone who can contribute it :v:

**Comment by Jouwhost** [comment]
> Please submit at https://github.com/nextcloud/mail/issues/new?assignees=&labels=enhancement%2C+0.+to+triage&template=feature_request.md&title=.
> 
> The editor has to strip any unknown HTML elements. Hence letting users edit raw HTML in their signature and then then removing that once used in a new message is a mess. Thus we use the same editor, to have a consistent user experience.
> 
> > Is there any way for me to improve how quickly this may be done?
> 
> Contribute the change (after discussing it with us) or find someone who can contribute it ✌️

Thanks. Such a shame i'm not a (good) developer :)
