### ISSUE TITLE
Allow switching account&signature

### ISSUE THREAD

**Issue by ChristophWurst** [nextcloud/mail#1660]
### Feature Request

With the implementation at https://github.com/nextcloud/mail/pull/1657, signatures are added to the prefilled message body. Hence a change of the alias/account won't update the signature.

#### Summary

n/a

**Comment by dumblob** [comment]
Raising my hand for this as otherwise having multiple email accounts with corresponding signatures doesn't work and effectively only one signature (of the default/top-most account?) can be used.

**Comment by ChristophWurst** [comment]
@dumblob please don't comment on all the tickets but leave your 👍 on the original request
