### ISSUE TITLE
Remember last used folder (do not always start in unified inbox)

### ISSUE THREAD

**Issue by yafp** [nextcloud/mail#1665]
### Feature Request

It would be great if users using mail in nextcloud with > 1 account would have an option to either disable or hide the unified inbox.

#### Summary

Add setting to hide / disable the unified inbox (user setting)

**Comment by ChristophWurst** [comment]
Why?

**Comment by yafp** [comment]
Well, there is a reason why i am using multiple email accounts in the first place.  Each account has an individual inbox (which it still has using this extension i know)

But showing the unified inbox in addition to the individual ones is at least for me:

* wasting space (as i am not using it anyways)
* tends to confuse me if i accidentally select it

**Comment by bpcurse** [comment]
Hopefully this request will be considered, as the unified inbox is confusing.
I do not use it in any other software solution, only mail forces me to. Please also see #745

**Comment by yafp** [comment]
puh .... using a stale bot it really far away from community friendly.

I do understand that you want to keep the issue situation sorted, but this leads to users having ideas, which just gets closed without a final feedback.

**Comment by ChristophWurst** [comment]
lol

**Comment by jancborchardt** [comment]
The proper solution here seems to be to simply remember the last used folder. That way the unified inbox is not shoved into people’s faces if they do not want to use it.

**Comment by bpcurse** [comment]
I agree with @jancborchardt, that this would solve the issue in an elegant way.

But please implement it in a permanent way using the db, not like for example the server user management is trying to save show last login (yes/no) in the browser.
People are growing more privacy aware and clean they browser data regularly. They are also using multiple devices/browsers.

Trying to save settings permanently on the client (browser) side is an increasingly outdated and bad concept in my opinion, at least if it relates to registered users.

**Comment by jancborchardt** [comment]
Yep, this should be remembered on the server so it’s also working across all devices someone may use.

**Comment by thstyl2000** [comment]
Would be great to have that feature. The tasks app for example does that. Thanks for all your work!

**Comment by ChristophWurst** [comment]
PR is at https://github.com/nextcloud/mail/pull/7133
