### ISSUE TITLE
Suggestion: Provide an API/way to add mailboxes programatically

### ISSUE THREAD

**Issue by Zahlii** [nextcloud/mail#168]
Hello,

I am searching for a way to use nextcloud as "the" groupware for my association here.
What I currently have is nextcloud 10 using an ldap backend and Courier/IMAP working with that backend too.

I am able to add new users with a name and password to ldap, however I would like them to be able to directly access their mails too (without adding them manually in the frontend). As I see this would require inserting the data into oc_mail_accounts - this however requires me to be able to use the decrypt/encrypt functionality, and I haven't yet found a way how to implement that without writing a whole new nextcloud app.

Is there any chance to either way implement such a functionality (similar to the nextcloud provisioning api), or to insert the data myself using an external php script?

Kind regards,
Zahlii

**Comment by MariusBluem** [comment]
Would this help you: https://github.com/nextcloud/mail/pull/28

**Comment by ChristophWurst** [comment]
basically #28 implements what you're looking for, but there's currently the problem that we're not persisting that automatically created account. We store the password to the encrypted session on login and use that later on to authenticate against the IMAP server. The main problem is that when remember-me is used, session values can be lost at some point, which means the account would magically disappear.

I've not yet found a proper way to fix this, therefore I paused that PR.

**Comment by Zahlii** [comment]
So this means that a default account is created the first time someone opens the mail app? Or as soon as a user logs in to nextcloud (normal or LDAP account)? In the second case, wouldn't it only be necessary to run one MySQL command to persist the IMAP settings given that we have access to uuid, name and password?

Even if this requires me to install the mail app via git I could live with it...

**Comment by Zahlii** [comment]
@ChristophWurst I ended up implementing my own "app" which takes over this task since we will most likely need some more customizations going, as such I'll close this issue now. Thanks for your efforts anyway :)
