### ISSUE TITLE
Recpient picker does not work with tab

### ISSUE THREAD

**Issue by small1** [nextcloud/mail#1687]
### Expected behavior
When sending a new email in the to section write an email address and press tab to move to the next field the email adress should still be in the to section

### Actual behavior
After entering the address in the to section and press tab. The field is empty.  And it seems like the whole to field is broken.  If i type a new email and press to early i just get  user@ and not user@domain

### Mail app
0.13.0

Nextcloud Version: 16.0RC1

#### Client configuration
**Browser:** Chrome  71.0.3578.98 (Official Build) (64-bit)

**Operating system:**  ubuntu 18.04

**Comment by ChristophWurst** [comment]
Was that working with 0.12?

**Comment by small1** [comment]
Hmmm. Unsure. I only added email in 0.16 beta .. i don't think i tried to send in 0.12 only 0.11.1 on my production servers.

But as it is now in 0.13 it is a struggle to send emails if they arent in the addressbook

**Comment by ChristophWurst** [comment]
Got it! I guess this is a regression with the new Vue multiselect address picker then.

What does work: type in the recipient and then click it in the dropdown menu. This selects the new value. But I agree that <kbd>tab</kbd> should work as well.

**Comment by small1** [comment]
Well. The recipient picker doesnt always continue to add the whole email. It stops at random times after the  @ sign.

**Comment by small1** [comment]
![Screenshot from 2019-04-12 11-13-11](https://user-images.githubusercontent.com/317830/56026234-02d8c300-5d14-11e9-982d-80897eefeae8.png)

**Comment by small1** [comment]
And if you press on the picker on incomplete email the picker breaks.

![Screenshot from 2019-04-12 11-16-52](https://user-images.githubusercontent.com/317830/56026492-8abecd00-5d14-11e9-8097-617ca8ebc094.png)
![Screenshot from 2019-04-12 11-16-41](https://user-images.githubusercontent.com/317830/56026494-8abecd00-5d14-11e9-8885-7eb1914400a0.png)

**Comment by ChristophWurst** [comment]
> Well. The recipient picker doesnt always continue to add the whole email. It stops at random times after the @ sign.

How can I reproduce this? What are the keyboard inputs to get there?

I gave this another test. You're right in that just tabbing through the inputs won't add the recipient. BUT: you can focus the input, type in the email and add it with <kbd>Enter</kbd>, then add another recipient or move to the next tabbable element. This also allows you to go back and deselect recipients with your keyboard. It's a bit different to how the old Mail recipient selector worked, but I think this solution is also nice, especially given that it works great with keyboard-only.

Without the keyboard you have to click the newly entered email address to add it to the list.

**Comment by small1** [comment]
I did a check right now. It wasnt working in nc16rc2 with the latest mail a week ago. But now when i upgraded to NC 16 stable on that test server and tested it is working as it should. And i dont have the same javascript errors. Ill do some more testing. But i think it is safe to close this now anyway

**Comment by ChristophWurst** [comment]
Perfect! That is great to hear. To be honest I haven't touched that code inside this app, but the multiselect component might have received a bugfix recently.
