### ISSUE TITLE
UI Improvements

### ISSUE THREAD

**Issue by C4rizz** [nextcloud/mail#1689]
Is it possible to improve the UI on the right grid (messages and replys)?
It would be nice to **separate messages and answers** with the **reply textarea** underneath so that they can be somehow separated by light boxes or a line.
Also the **horizontal scroll** is horrible and it would be better to replace it with a stronger one similar to the one on the left vertical scrollbar.
Also when there are many mail addressards the horizontal scroll is annoying, so it would be better to add **linebreaks for the mail header** or a resposive max-with to the message boxes.
If there is a simple template system i can also try to look over the implementation details myself if it is not too complicated to follow.

Cheers Chris.

**Comment by ChristophWurst** [comment]
Hi,

could you please file separate tickets for separate issues/feature requests? If you do, in it's about design it's usually best to add some quick and dirty mockups so people understand the problem better. Would that be possible?

Yes, the templates are rather easy to edit. It's all Vue.js and you can find the components in `src/components`.
