### ISSUE TITLE
Problem with cyrillic name of folders

### ISSUE THREAD

**Issue by pzverr** [nextcloud/mail#170]
I can not get into the folder with the name in Cyrillic get the error:

> Not Found
> The requested URL /index.php/apps/mail/accounts/7/folders/0J7RgtC/0YDQsNCy0LvQtdC90L3Ri9C1/messages was not found on this server.

folderId - is base64 encoded string, right ?

I think the problem is that the basе64 creates a folderId without slashes ( in some cases ), and my request does not reach to the controller ( routes.php `/accounts/{accountId}/folders/{folderId}/messages` ).
I tried to escape slashes so:

> /index.php/apps/mail/accounts/7/folders/0J7RgtC**\/**0YDQsNCy0LvQtdC90L3Ri9C1/messages

But still, I do not get the desired result...

Mail app version: 0.6.0

**Comment by pzverr** [comment]
Folder names for example: Новая, Отправленные

**Comment by ChristophWurst** [comment]
Fixed with #2163
