### ISSUE TITLE
Unable to download/view attachment

### ISSUE THREAD

**Issue by Byorun** [nextcloud/mail#1709]
Nextcloud 15.0.7
Mail 0.11.1

Every time I try to download or view an attachment I get an "Internal Server Error"
URL: ..../apps/mail/api/accounts/2/folders/SU5CT1g=/messages/7036/attachment/2.1

> {"reqId":"68Qjg68IBQ7cwHnSaQt8","level":3,"time":"2019-04-24T07:16:04+00:00","remoteAddr":"hidden","user":"hidden","app":"index","method":"GET","url":"\/apps\/mail\/api\/accounts\/2\/folders\/SU5CT1g=\/messages\/7036\/attachment\
/2.1","message":{"Exception":"TypeError","Message":"Argument 2 passed to OCA\\Mail\\Http\\AttachmentDownloadResponse::__construct() must be of the type string, null given, called in \/var\/www\/nextcloud\/apps\/mail\/lib\/Controller\/Mes
sagesController.php on line 266","Code":0,"Trace":[{"file":"\/var\/www\/nextcloud\/apps\/mail\/lib\/Controller\/MessagesController.php","line":266,"function":"__construct","class":"OCA\\Mail\\Http\\AttachmentDownloadResponse","type":"->"
,"args":["\r\n----boundary_8_28dd3cf7-2f1c-48f0-804c-05ac4ee74d9d\r\nContent-Type: application\/pdf;....

**Comment by ChristophWurst** [comment]
Fix in 0.12 and later.

Also, please use the issue template next time.

**Comment by Byorun** [comment]
@ChristophWurst sorry for not using the template but Github didn't offer the templates if your are not logged in while creating an issue

**Comment by ChristophWurst** [comment]
Okay, no problem :)
