### ISSUE TITLE
nextcloud mail app fail under php 7

### ISSUE THREAD

**Issue by mesro09** [nextcloud/mail#172]
### Steps to reproduce
1.
2.
3.

### Expected behaviour
Tell us what should happen

### Actual behaviour
Tell us what happens instead

### Mail app

**Mail app version:** (see apps admin page)

**Mailserver or service:** (e.g. Outlook, Yahoo, Gmail, Exchange,...)

**Transport security - IMAP:** (None, SSL, TLS, STARTTLS) 

**Transport security - SMTP:** (None, SSL, TLS, STARTTLS)

**Number of accounts:**

**Mail app version build date:** (only if you are using a Nightly Build)

### Server configuration
**Operating system**:

**Web server:**

**Database:**

**PHP version:**

**Version:** (see admin page)

**Updated from an older version or fresh install:**

**List of activated apps:**

```
If you have access to your command line run e.g.:
sudo -u www-data php occ app:list
from within your server installation folder
```

**The content of config/config.php:**

<details>
```
If you have access to your command line run e.g.:
sudo -u www-data php occ config:list system
from within your server installation folder

or 

Insert your config.php content here
(Without the database password, passwordsalt and secret)
```
</details>

#### Client configuration
**Browser:**

**Operating system:**

##### Web server error log
```
Insert your webserver log here
```

##### Server log (data/nextcloud.log)
<details>
```
Insert your server log here
```
</details>

##### Horde IMAP log (data/horde_imap.log)
<details>
```
Insert your horde IMAP log here, see https://github.com/nextcloud/mail#debug-mode
```
</details>

##### Horde SMTP log (data/horde_smtp.log)
<details>
```
Insert your horde SMTP log here, see https://github.com/nextcloud/mail#debug-mode
```
</details>

##### Browser log
<details>
```
Insert your browser log here, this could for example include:

a) The javascript console log
b) The network log 
c) ...
```
</details>

**Comment by mesro09** [comment]
here is my log file 
when i use same configuration but with php 5.6 any error 
but when i use mail app with php 7 i receive error "error while loading messages"
many thanks for all helps


Exception: {"Exception":"Exception","Message":"HMAC does not match.","Code":0,"Trace":"#0 \/var\/www\/html\/nextcloud\/apps\/mail\/lib\/account.php(131): OC\\Security\\Crypto->decrypt(*** sensitive parameters replaced ***)\n#1 \/var\/www\/html\/nextcloud\/apps\/mail\/lib\/account.php(693): OCA\\Mail\\Account->getImapConnection()\n#2 \/var\/www\/html\/nextcloud\/apps\/mail\/lib\/controller\/folderscontroller.php(172): OCA\\Mail\\Account->getChangedMailboxes(Array)\n#3 [internal function]: OCA\\Mail\\Controller\\FoldersController->detectChanges('1', Array)\n#4 \/var\/www\/html\/nextcloud\/lib\/private\/AppFramework\/Http\/Dispatcher.php(160): call_user_func_array(Array, Array)\n#5 \/var\/www\/html\/nextcloud\/lib\/private\/AppFramework\/Http\/Dispatcher.php(90): OC\\AppFramework\\Http\\Dispatcher->executeController(Object(OCA\\Mail\\Controller\\FoldersController), 'detectChanges')\n#6 \/var\/www\/html\/nextcloud\/lib\/private\/AppFramework\/App.php(111): OC\\AppFramework\\Http\\Dispatcher->dispatch(Object(OCA\\Mail\\Controller\\FoldersController), 'detectChanges')\n#7 \/var\/www\/html\/nextcloud\/lib\/private\/AppFramework\/Routing\/RouteActionHandler.php(47): OC\\AppFramework\\App::main('OCA\\\\Mail\\\\Contro...', 'detectChanges', Object(OC\\AppFramework\\DependencyInjection\\DIContainer), Array)\n#8 [internal function]: OC\\AppFramework\\Routing\\RouteActionHandler->__invoke(Array)\n#9 \/var\/www\/html\/nextcloud\/lib\/private\/Route\/Router.php(293): call_user_func(Object(OC\\AppFramework\\Routing\\RouteActionHandler), Array)\n#10 \/var\/www\/html\/nextcloud\/lib\/base.php(983): OC\\Route\\Router->match('\/apps\/mail\/acco...')\n#11 \/var\/www\/html\/nextcloud\/index.php(48): OC::handleRequest()\n#12 {main}","File":"\/var\/www\/html\/nextcloud\/lib\/private\/Security\/Crypto.php","Line":129}

**Comment by MariusBluem** [comment]
May I ask you to fill out the whole issue template, so that we have more information about your instance, your problem and how we are able to reproduce your bug. Only then, we are able to assist you in the best way 😅 THX 🙈

**Comment by mesro09** [comment]
here above is my log

Expected behaviour i was expecting that it work as same as version php 5.6 but usung php7  :(

Tell us what should happen

Actual behaviour
error while loading messages
Tell us what happens instead
error while loading messages
also i tried to test without use ssl configuration but same result
Mail app (on nextcloud i am trying to use it)

Mail app version: 
 0.6.0
Mailserver or service: (go daddy)

Transport security - IMAP: ( SSL)

Transport security - SMTP: ( SSL)

Number of accounts: (1 account per user total 20 )

Mail app version build date: ()
 0.6.0
Server configuration rs02.hostingdepago.com (for imap,smtp,and pop) port 465, 995,993

Operating system: ubuntu 16.10

Web server: apache 2.4

Database: maria db

PHP version: php 7.0

Version: (see admin page)

Updated from an older version or fresh install: fresh install but i did 2 fresh install when i use phph 5.6 mail app working perfectly


List of activated apps: spreedme, collabora, calendar, gallery

Detalles
any error in the installation 
my problem is compatibility with php version

**Comment by mesro09** [comment]
Exception: {"Exception":"TypeError","Message":"Argument 1 passed to OCA\\Mail\\Model\\IMAPMessage::hordeToAssoc() must be an instance of Horde_Mail_Rfc822_Address, instance of Horde_Mail_Rfc822_Group given, called in \/var\/www\/html\/nextcloud\/apps\/mail\/lib\/model\/convertaddresses.php on line 74","Code":0,"Trace":"#0 \/var\/www\/html\/nextcloud\/apps\/mail\/lib\/model\/convertaddresses.php(74): OCA\\Mail\\Model\\IMAPMessage->hordeToAssoc(Object(Horde_Mail_Rfc822_Group))\n#1 \/var\/www\/html\/nextcloud\/apps\/mail\/lib\/model\/imapmessage.php(216): OCA\\Mail\\Model\\IMAPMessage->convertAddressList(Object(Horde_Mail_Rfc822_List))\n#2 \/var\/www\/html\/nextcloud\/apps\/mail\/lib\/model\/imapmessage.php(485): OCA\\Mail\\Model\\IMAPMessage->getToList(true)\n#3 \/var\/www\/html\/nextcloud\/apps\/mail\/lib\/mailbox.php(190): OCA\\Mail\\Model\\IMAPMessage->getListArray()\n#4 \/var\/www\/html\/nextcloud\/apps\/mail\/lib\/controller\/messagescontroller.php(137): OCA\\Mail\\Mailbox->getMessages(0, 21, '')\n#5 [internal function]: OCA\\Mail\\Controller\\MessagesController->index(50, 'SU5CT1g=', 0, 20, '', NULL)\n#6 \/var\/www\/html\/nextcloud\/lib\/private\/AppFramework\/Http\/Dispatcher.php(160): call_user_func_array(Array, Array)\n#7 \/var\/www\/html\/nextcloud\/lib\/private\/AppFramework\/Http\/Dispatcher.php(90): OC\\AppFramework\\Http\\Dispatcher->executeController(Object(OCA\\Mail\\Controller\\MessagesController), 'index')\n#8 \/var\/www\/html\/nextcloud\/lib\/private\/AppFramework\/App.php(111): OC\\AppFramework\\Http\\Dispatcher->dispatch(Object(OCA\\Mail\\Controller\\MessagesController), 'index')\n#9 \/var\/www\/html\/nextcloud\/lib\/private\/AppFramework\/Routing\/RouteActionHandler.php(47): OC\\AppFramework\\App::main('OCA\\\\Mail\\\\Contro...', 'index', Object(OC\\AppFramework\\DependencyInjection\\DIContainer), Array)\n#10 [internal function]: OC\\AppFramework\\Routing\\RouteActionHandler->__invoke(Array)\n#11 \/var\/www\/html\/nextcloud\/lib\/private\/Route\/Router.php(293): call_user_func(Object(OC\\AppFramework\\Routing\\RouteActionHandler), Array)\n#12 \/var\/www\/html\/nextcloud\/lib\/base.php(983): OC\\Route\\Router->match('\/apps\/mail\/acco...')\n#13 \/var\/www\/html\/nextcloud\/index.php(48): OC::handleRequest()\n#14 {main}","File":"\/var\/www\/html\/nextcloud\/apps\/mail\/lib\/model\/convertaddresses.php","Line":34}

**Comment by mesro09** [comment]
Could not load Inbox :-|

**Comment by ChristophWurst** [comment]
dup of https://github.com/nextcloud/mail/issues/53. this is unrelated to the php version.

**Comment by mesro09** [comment]
dear sir i didnt understant your answer 
i already know problem caused by php version because i am using php 7 but you aready said that your mail app is compatible with php 7 
so i have php 7.0.11
which php 7 that i must use ????

**Comment by ChristophWurst** [comment]
Your issues has nothing to do with the php version, but is a bug that is triggered by one of your messages of your inbox. See issue https://github.com/nextcloud/mail/issues/53. Others have reported the same error log, therefore I am pretty sure it's the very same bug.

**Comment by mesro09** [comment]
so mail app it is not compatible still with php 7.**

**Comment by ChristophWurst** [comment]
It is. You will also see that error if you use php 5.6 because the bug is **independent of the php verson**

**Comment by mesro09** [comment]
yes but when i use php 5.6 mail app also working 
but with php 7 not working

**Comment by ChristophWurst** [comment]
Well, then please post all the info asked in the issue template. And provide us log entries that actually show an stack trace of that "php7 error". Thanks

**Comment by mesro09** [comment]
i returned to php 5.6 andeverything is working 
your mail app is not compatible with php7

**Comment by ChristophWurst** [comment]
thanks for letting me know.

**Comment by Gomez** [comment]
lol
