### ISSUE TITLE
Unable to specify alias

### ISSUE THREAD

**Issue by onny** [nextcloud/mail#1722]
### Actual behavior
Hey,
I'm using the latest version 0.14 and somehow the alias feature has vanished. I'm unable to define or select an alias for my account.

Best regards,
Jonas

**Comment by ardarandir** [comment]
Is this regression planned to be solved anytime soon? It is probably causing a couple of follow-up problems with aliases set up on the mailserver through other ways, e.g. sent mails ending up in inbox instead of sent-folder.

**Comment by ChristophWurst** [comment]
Planned: yes. But I can't give you an ETA.

**Comment by duesseldorferjung** [comment]
Good Day Everyone, still new to github and trying to understand what different lables means.
Do I understand that regression means "feature got missing is not working anymore"?
I just started using Nextcloud 18 with the mail app and would really like to use the feature of different identities.

**Comment by ChristophWurst** [comment]
Yes, regression is something that used to work but broke.

**Comment by duesseldorferjung** [comment]
Allright. What do you call the stage after, when it is working again ? Hope to see that soon :) If some help in terms of testing is required I can help out.

Just for everyone who might have the same issue. Adding second mail account works as a workaround for me. I added the account with a different name, the same main emailaddress. Afterwards in the settings of the account I changed the emailaddress to the aliase.

**Comment by JasMich** [comment]
Is there any work on?

**Comment by duesseldorferjung** [comment]
Is there an estimation on when this can be fixed? I can offer some testing support of course.

**Comment by ChristophWurst** [comment]
In the open source world we say it will be done when it is ready :)

I've added it to the end of the roadmap. This does not mean much, but eventually we will work on it.

There are at least three ways to speed this up

* Deliver the code as a pull request
* Ask (pay) someone else to do the work
* Get a Nextcloud subscription and have the feature prioritized

**Comment by ChristophWurst** [comment]
Thanks to @IchbinkeinReh we'll have aliases with v1.5 https://github.com/nextcloud/mail/pull/3338 :)
