### ISSUE TITLE
Email Body Images not displayed

### ISSUE THREAD

**Issue by MattSpec** [nextcloud/mail#1734]
### Expected behavior
Tell us what should happen
mail messages loaded, images displayed after clicking 'show images' button

### Actual behavior
Tell us what happens instead
no images are loaded in email body.

### Mail app

**Mail app version:** (see apps admin page, e.g. 0.5.3)
0.14.0
**Mailserver or service:** (e.g. Outlook, Yahoo, Gmail, Exchange,...)
xo2.x10hosting.com  - x10hosting mail  - imap

### Server configuration

**Operating system**: (e.g. Debian 8)
kubuntu
**Web server:** (e.g. Apache, Nginx,...)
Apache
**Database:** (e.g. MariaDB, SQLite or PostgreSQL)
MariaDB
**PHP version:** (e.g. 7.0)
7.2
**Nextcloud Version:** (see admin page, e.g. 13.0.2)
16.0.0
#### Client configuration
**Browser:** (e.g. Firefox 48)
Chrome

**My Server**

![mine](https://user-images.githubusercontent.com/5439413/57209912-83ec4880-6fa8-11e9-8580-8081f4e49055.PNG)
![myfoot](https://user-images.githubusercontent.com/5439413/57209913-83ec4880-6fa8-11e9-979d-22d92b2328d1.PNG)

**Webo.hosting shared instance**

![webo](https://user-images.githubusercontent.com/5439413/57209922-88186600-6fa8-11e9-8032-78edaca8b64b.PNG)
![webofoot](https://user-images.githubusercontent.com/5439413/57209923-88186600-6fa8-11e9-825d-199c591eb7dc.PNG)

**Comment by bd8392** [comment]
Same Error here...

**Comment by temesinko** [comment]
Eventually this is the same error like I found. Therefore I won't create a new issue, but share some detailed information:

### Client side (after click on "show images")

Internal Server Error (500) when calling URL ```https://REDACTED/apps/mail/proxy?src=REDACTED&requesttoken=REDACTED```

### Server side (Nextcloud log)
```
TypeError: Argument 1 passed to OCA\Mail\Controller\ProxyController::proxy() must be of the type string, null given, called in /var/www/vhosts/REDACTED/lib/private/AppFramework/Http/Dispatcher.php on line 166
/var/www/vhosts/REDACTED/lib/private/AppFramework/Http/Dispatcher.php - line 166:OCA\Mail\Controller\ProxyController->proxy(null)
/var/www/vhosts/REDACTED/lib/private/AppFramework/Http/Dispatcher.php - line 99:OC\AppFramework\Http\Dispatcher->executeController(OCA\Mail\Con ... {}, "proxy")
/var/www/vhosts/REDACTED/lib/private/AppFramework/App.php - line 126:OC\AppFramework\Http\Dispatcher->dispatch(OCA\Mail\Con ... {}, "proxy")
/var/www/vhosts/REDACTED/lib/private/AppFramework/Routing/RouteActionHandler.php - line 47:OC\AppFramework\App::main("OCA\\Mail\\ ... r", "proxy", OC\AppFramew ... {}, { _route: "mail.proxy.proxy"})
<<closure>>OC\AppFramework\Routing\RouteActionHandler->__invoke({ _route: "mail.proxy.proxy"})
/var/www/vhosts/REDACTED/lib/private/Route/Router.php - line 297:call_user_func(OC\AppFramew ... {}, { _route: "mail.proxy.proxy"})
/var/www/vhosts/REDACTED/lib/base.php - line 975:OC\Route\Router->match("/apps/mail/proxy")
/var/www/vhosts/REDACTED/index.php - line 42:OC::handleRequest()
```

**Comment by bd8392** [comment]
Was anyone able to resolve the issue?

**Comment by Nikhos** [comment]
I've got this Error, too.
NC 16.0.1
Mail 0.15.1

**Comment by ChristophWurst** [comment]
At least on @temesinko's instance it's strange that the `src` URL parameter is not passed into Nextcloud. Do you have any URL rewriting in place? Is there a reverse proxy in front of your Nextcloud?

**Comment by bd8392** [comment]
I have traefik in place...

**Comment by temesinko** [comment]
> At least on @temesinko's instance it's strange that the `src` URL parameter is not passed into Nextcloud. Do you have any URL rewriting in place? Is there a reverse proxy in front of your Nextcloud?

I'm using Plesk with Nextcloud running on Apache with nginx in proxy mode in front of it.

**Comment by ChristophWurst** [comment]
Okay, then please make sure your proxies do not remove the parameter.

**Comment by ChristophWurst** [comment]
Dup of https://github.com/nextcloud/mail/issues/1341#issuecomment-493894749

**Comment by temesinko** [comment]
I can verify that disabling nginx completely does not fix the issue.

**Comment by MattSpec** [comment]
I've been trying to find an error message anywhere. There just doesn't seem to be one. When I click on show images I see them all coming in to the browser with 200 but they're not displayed on the page.

**Comment by Lawkss** [comment]
I have the same problem.

**Comment by ChristophWurst** [comment]
> I disabled the official Mail App and use AfterLogic Webmail. No problems with images in html mail.

Thank you for your comment. I'm sure a lot of users in this thread will benefit from this solution.

**Comment by JensKillermann** [comment]
same problem. AfterLogic Webmail isn't an alternative for me.

**Comment by ChristophWurst** [comment]
> AfterLogic Webmail isn't an alternative for me.

my other comment was meant to be sarcastic :)

**Comment by bd8392** [comment]
Issue persists... don't see that traefik removes any parameters...

**Comment by temesinko** [comment]
In the meantime I migrated my Nextcloud from a Plesk subscription (nginx in front of Apache) to it's own VM on a Proxmox host. At this moment it is using no reverse web proxy in front of Apache but the issue still persists. With nginx I had errors with status 500, now I get status 200 but with empty response data. Running on: Apache 2.4 with PHP 7.3 FPM

**Comment by charlessteiner** [comment]
I have the same issue on two centos 7 setups (apache, php 7.1 & php 7.2, current nextcloud and mail) no proxies. I've tried with two email providers: namecheap and self hosted mail-in-a-box. 

Anyone have luck?

**Comment by user7466** [comment]
I see this problem also, on my setup what is happening is that the images are downloaded ok, but the img tag in the html has style="display:none;" set.  If I toggle that off in dev console the image displays.
Currently poking around to find out why...

**Comment by user7466** [comment]
It is line 76 in lib/Service/HtmlPurify/TransformImageSrc.php that is setting it to none:
$attr = $this->setDisplayNone($attr);

js event onShowBlockedContent() is not explicitly removing display:none
It is, however, replacing style with data-original-style, but TransformImageSrc does not set that.

This can be fixed by either not hiding blocked images at all in TransformImageSrc or by getting it to set data-original-style:
$attr['data-original-style'] = $attr['style'];

**Comment by user7466** [comment]
This is on nextcloud 17 btw.  I can't work out how it is could be working for some people and not others

**Comment by JensKillermann** [comment]
great, it works. Testet with nextcloud 17

**Comment by autoize** [comment]
Great comment @user7466. 
Commenting out line 76 `$attr = $this->setDisplayNone($attr);` in `$nextcloud_dir/apps/mail//lib/Service/HtmlPurify/TransformImageSrc.php`, disabling, then reenabling the Mail app resolves the problem with allowing images in NextCloud 17.0.
