### ISSUE TITLE
Inbox and other folder do not show with NC 15 & PHP 7.1

### ISSUE THREAD

**Issue by Kugeleis** [nextcloud/mail#1736]
Mail app runs fine with PHP 7.0 on web server!
see issue #765 for earlier discussions on this persisting issue

### Expected behavior
1 open nexcloud mail app
2 see & read mails

### Actual behavior
0. switch web server to PHP 7.1
1. open nextcloud mail app
2. mail folder list visible but can't show any mail

### Mail app

**Mail app version: 0.11.1

**Mailserver or service: posteo.de

### Server configuration

**Operating system**: unknown

**Web server: Apache

**Database:** MySQL

**PHP version:** 7.1

**Nextcloud Version:** 15.0.7

#### Client configuration
**Browser:** Opera, Firefox, Chrome (latest)

**Operating system:** Windows 10

attached nextcloud-log with mail app 
[nextcloud.log](https://github.com/nextcloud/mail/files/3147116/nextcloud.log)
access section when PHP7.1 active.

**Comment by ChristophWurst** [comment]
nextcloud.log is clean. Any error shown in your browser console?

**Comment by Kugeleis** [comment]
[nextcloud-1557146016825.log](https://github.com/nextcloud/mail/files/3147915/nextcloud-1557146016825.log)
[nextcloud-1557146039118.log](https://github.com/nextcloud/mail/files/3147916/nextcloud-1557146039118.log)
[nextcloud-1557146044775.log](https://github.com/nextcloud/mail/files/3147917/nextcloud-1557146044775.log)

**Comment by ChristophWurst** [comment]
> build.js?v=26c890b8-7:39 GET https://nextcloud.org/index.php/apps/mail/api/accounts/3/folders/SU5CT1g%3D/messages?filter= 502 (Bad Gateway)

Do you run a reverse proxy in front of your Nextcloud?

**Comment by Kugeleis** [comment]
No, straight forward web space @ webgo.de. No special config.

**Comment by ChristophWurst** [comment]
Okay. Then check your server's logs to find out why it's returning a 502.

**Comment by Kugeleis** [comment]
I found this in the access.log:
IP_Log_deaktiviert - - [06/May/2019:09:59:34 +0200] "GET /apps/mail/css/mobile.css HTTP/1.0" 200 502 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/71.0.3578.98 Safari/537.36 OPR/58.0.3135.132" nextcloud.org

**Comment by Kugeleis** [comment]
Is there anything going on here? Can I contribute more? This issue blocks migrating to NC 16.

**Comment by ChristophWurst** [comment]
On Nextcloud 16 you'll get a different version of Mail. I don't see how this is blocknig.

**Comment by Kugeleis** [comment]
The issue vanished upgrading NC from 16.05 to 16.0.6 keeping mail app version 0.17.0.

**Comment by ChristophWurst** [comment]
Great! Thanks for the feedback!

**Comment by Kugeleis** [comment]
Writing the lines above I updated to NC 17.0.1 and mail 0.18.1 and I'm back no mails loading ;~(
