### ISSUE TITLE
Cannot download attachments

### ISSUE THREAD

**Issue by ostasevych** [nextcloud/mail#1738]
### Expected behavior
When I click the download icon (arrow down) under the text of the received message I have to be prompted to download a file.

### Actual behavior
Instead of I am getting error on the web-page indicating:
```
The server was unable to complete your request.
If this happens again, please send the technical details below to the server administrator.
More details can be found in the server log.

Technical details
Remote Address: xxx.xxx.xxx.xxx
Request ID: swzZpzchV0RK9SLMVSOk
```

In the Logging section I see: 
`TypeError: Argument 2 passed to OCA\Mail\Http\AttachmentDownloadResponse::__construct() must be of the type string, null given, called in /var/www/html/test/apps/mail/lib/Controller/MessagesController.php on line 257
`
### Mail app

**Mail app version:** 0.14.00
**Mailserver or service:** local hosted Postfix+Dovecot

### Server configuration

**Operating system**: CentOS 6.10
**Web server:** Apache
**Database:** MySQL
**PHP version:** 7.2.18
**Nextcloud Version:** 16.0.0

#### Client configuration
**Browser:** Google Chrome 74.0.3729
**Operating system:** Windows 10, 64-bit

**Comment by ChristophWurst** [comment]
Sounds like on some attachments the content type is either not set or unknown. A possible fix would be to set the MIME to `application/octet-stream` as a fallback at https://github.com/nextcloud/mail/blob/251b3b3e58c0b636e0f5346ae6d67a8c93fc39af/lib/Http/AttachmentDownloadResponse.php#L42.

@ostasevych would you be interested in contributing a fix?

**Comment by ostasevych** [comment]
> Sounds like on some attachments the content type is either not set or unknown. A possible fix would be to set the MIME to `application/octet-stream` as a fallback at
> 
> https://github.com/nextcloud/mail/blob/251b3b3e58c0b636e0f5346ae6d67a8c93fc39af/lib/Http/AttachmentDownloadResponse.php#L42
> 
> .
> @ostasevych would you be interested in contributing a fix?

Hi! Thank you for the response. How to set this MIME? I am more tester rather than programmer.... If you explain, how to set the MIME, I may test the patch.

**Comment by ChristophWurst** [comment]
>  I am more tester rather than programmer

No problem. Thanks for testing and writing bug reports. This is highly appreciated :raised_hands: 

It's not something that you could set. Does this only happen with specific emails or with all that have attachments?

**Comment by der-peer** [comment]
Hi,
is there anything new about the issue?

I can confirm, that the problem still persists. My setup:
- Nextcloud 16.0.3, selfhosted on Apache 2.4
- Mail 0.15.2
- External User Support 0.6.4
- external Postfix Mail server with IMAP, 
- Users are authenticated against IMAP, Mail accounts automatically created based on IMAP authentication. 

Single attachments seem to work in most cases. Image attachments are shown inline with thumbnail and can be downloaded. PDFs or other attachments can be downloaded.

I can confirm at least this case, where I am sure that leads to the mentioned error: if the received Mail is PGP signed, then display of the attachment is broken (thumbnail can not be displayed, image not shown inline). The same email without PGP signature displays fine.

![attachment broken](https://user-images.githubusercontent.com/13415398/63089648-d5698380-bf58-11e9-931a-9430840af2b7.JPG)

**Comment by herrep** [comment]
Hi,

I encounter the same problem with Nextcloud 16.0.4 and Mail 0.15.2.

However, when looking onto the error message and the code, it appears that the attachment file name is null:

/var/www/html/nextcloud/apps/mail/lib/Controller/MessagesController.php, lines 256-257:

```
AttachmentDownloadResponse(
                        $attachment->getContents(), $attachment->getName(), $attachment->getType());
```

The log files reads:

```
TypeError: Argument 2 passed to OCA\Mail\Http\AttachmentDownloadResponse::__construct() must be of the type string, null given, called in /var/www/html/nextcloud/apps/mail/lib/Controller/MessagesController.php on line 257

/var/www/html/nextcloud/apps/mail/lib/Controller/MessagesController.php - line 257:
OCA\Mail\Http\AttachmentDownloadResponse->__construct("\r\n--Apple ... n", null, "application/octet-stream")
```

According to my log file, the MIME content type is set to "application/octet-stream", but the file name is null.

Does anybody know as how to overcome this issue?

Best regards,
Peter

**Comment by herrep** [comment]
It is not sufficient to set the null file name to a default value. When setting the file name to a default, I am able to store the file, but it contents is not readable while I verified from another mail client that the content is valid.

**Comment by StCyr** [comment]
I have the same problem here with a .doc file.

Nextcloud: 16.0.4
Mail: 0.17.0

**Comment by StCyr** [comment]
The bug doesn't occur for me when I change `Attachment::getName()`  function as follow:

```php
        public function getName() {
//              return $this->mimePart->getName();
                return 'attachment';
        }
```

But this is just a dirty hack :-)

**Comment by herrep** [comment]
When I manipulated the name of a test attachment (PDF file), I realized that the downloaded file was at least incomplete, as the file size was much smaller than it should be. On other mail clients, I could download the attachment, it had a bigger file size and was opened correctly by the PDF viewer. So it appears that the problem does not only concern the proper naming of the attachment, but rather the entire decoding of the attachment which does not only result in a wrong file name, but also in not correctly decoded content.

**Comment by StCyr** [comment]
this seems to cause problem also:

```
--Apple-Mail-E382DA81-E442-483A-90B0-C7A37692073D
Content-Type: application/pdf;
	name="Reservation fete d'anniversaire-10342.pdf";
	x-apple-part-url=0E476D1D-BE3F-4E66-8D0D-B9964DD29E88
Content-Disposition: inline;
	filename*=utf-8''R%C3%A9servation%20f%C3%AAte%20d%27anniversaire%2D10342.pdf
Content-Transfer-Encoding: base64
```

**Comment by ChristophWurst** [comment]
Please see https://github.com/nextcloud/mail/pull/2213
