### ISSUE TITLE
From-address should be bound to currently selected mailbox

### ISSUE THREAD

**Issue by Quix0r** [nextcloud/mail#175]
I have multiple mail-boxes setup in Mail application. If I reply back to my own mails, my other email account is being choosen:

1. Setup 2 different mailboxes
2. Send email from B to A and to B in CC header
3. Go to B inbox folder, "From" line switched to A as sender (and not B as expected)

**Comment by jancborchardt** [comment]
@Quix0r yeah, maybe it’s a similar or the same problem as https://github.com/nextcloud/mail/issues/10

**Comment by Quix0r** [comment]
I bumped again into this. Now it also happens when you go to e.g. Inbox and click on _Reply_. Then always the first (no `selected="selected"` in HTML code found) is always the `From` line.

I manage my private and work mails here. Now always my work mails got sent with my private account because of this bug which is not intended and wanted (of course). Please consider fixing this in next release.

**Comment by ChristophWurst** [comment]
> I manage my private and work mails here. Now always my work mails got sent with my private account because of this bug which is not intended and wanted (of course). Please consider fixing this in next release.

I will consider it, because it happened to me too and it's pretty annoying. Would be great if anybody could help with this though :-)

**Comment by jancborchardt** [comment]
Same here, this often happens to me still. :\

cc @nextcloud/mail @nextcloud/javascript anyone up for helping here? :)

**Comment by Quix0r** [comment]
I think `selected="selected"` (to not have value-less attributes) would fix this.

**Comment by jancborchardt** [comment]
@quix0r do you want to submit a pull request to fix this? :) Would be awesome!

**Comment by Quix0r** [comment]
Little short on time. ... :-(

**Comment by ChristophWurst** [comment]
Dup of https://github.com/nextcloud/mail/issues/10 IMO, thus closing this one.
