### ISSUE TITLE
Completely blank after upgrade to 1.5.0

### ISSUE THREAD

**Issue by scarleo** [nextcloud/mail#1754]
### Expected behavior
I should see my emails when clicking on Mail icon i NextCloud

### Actual behavior
It is blank below the top menu with the icons, nothing shows up. I tried reinstalling the app but same behaviour. In Chrome console I see:

TypeError: Cannot read property 'call' of undefined
    at o (bootstrap:63)
    at Module.595 (Home.vue?e358:37)
    at o (bootstrap:63)
i @ vue-router.esm.js:1921

(anonymous) @ vue-router.esm.js:1963
(anonymous) @ vue-router.esm.js:1784
(anonymous) @ vue-router.esm.js:1849
Promise.then (async)
(anonymous) @ vue-router.esm.js:1796
(anonymous) @ vue-router.esm.js:1817
(anonymous) @ vue-router.esm.js:1817
xt @ vue-router.esm.js:1816
(anonymous) @ vue-router.esm.js:1752
p @ vue-router.esm.js:1959
r @ vue-router.esm.js:1733
r @ vue-router.esm.js:1737
bt @ vue-router.esm.js:1741
kt.confirmTransition @ vue-router.esm.js:1988
kt.transitionTo @ vue-router.esm.js:1890
Dt.init @ vue-router.esm.js:2546
beforeCreate @ vue-router.esm.js:553
qt @ vue.runtime.esm.js:1854
en @ vue.runtime.esm.js:4213
t._init @ vue.runtime.esm.js:4998
jn @ vue.runtime.esm.js:5079
(anonymous) @ main.js:77
o @ bootstrap:63
(anonymous) @ bootstrap:195
(anonymous) @ bootstrap:195

### Mail app

**Mail app version:** (see apps admin page, e.g. 0.5.3)
1.5.0

**Mailserver or service:** (e.g. Outlook, Yahoo, Gmail, Exchange,...)
Self hosted, same server as NextCloud. Runs Postfix + Dovecot

### Server configuration

**Operating system**: (e.g. Debian 8)
Ubuntu 16.04

**Web server:** (e.g. Apache, Nginx,...)
Apache

**Database:** (e.g. MariaDB, SQLite or PostgreSQL)
MySQL

**PHP version:** (e.g. 7.0)
PHP-FPM 7.3

**Nextcloud Version:** (see admin page, e.g. 13.0.2)
16.0.0

#### Client configuration
**Browser:** (e.g. Firefox 48)
Google Chrome Version 75.0.3770.18

**Operating system:** (e.g. Arch Linux)
Arch linux

**Comment by ChristophWurst** [comment]
This sounds similar to #1752. Does the error persist after a forced refresh of the page?

The vue-router was updated for v0.15.0. This could be a bug in that lib: https://github.com/nextcloud/mail/compare/v0.14.0...v0.15.0

**Comment by scarleo** [comment]
I actually solved it just now by cleaning browser cache, so case closed for my part, sorry for not testing that prior to reporting.
