### ISSUE TITLE
Turn Off Preview Pane / Pop-Out Message

### ISSUE THREAD

**Issue by LibertyTalk** [nextcloud/mail#1757]
### Feature Request

Love, love, love how NextCloud is becomming a full-service office in the cloud. That said, it would be helpful if there existed an option to turn off the "preview-pane/reading-pane" on a folder-by-folder basis. Whereas, perusing one's junk folder is sometime necessary, but merely "previewing" an email can and does provide an attack vector for some malicious email.

This would also then require the ability to double-click a message that would then pop-out into its own window.

#### Summary

Turn off Reading/Preview Pane on Folder by Folder Basis
Allow email message to pop-out to new window on double-click

**Comment by stefan-niedermann** [comment]
**Yes** to the possibility to toggle the preview on and off (and gibe the subject more space in the overview) - but **no** to doubleclick as an action. This is hard to discover for something such important as actually displaying the message. We should find another way, like display an "open"-button on selected mails, if we want to do this.

**Comment by LibertyTalk** [comment]
For sure, the Double-Click to open is an option perhaps only familiar to those who use Microsoft's Outlook desktop app or the new O365 outlook web app, whereas most web-based internet email I have seen is hyperlinked [read: Yahoo]

Maybe then if not a double-click action to view the message, perhaps an expanding triangle, similar to the expanding folder hierarchy seen in Mac OS dating back to the classic OS.

**Comment by ChristophWurst** [comment]
@nextcloud/mail what do you think?

**Comment by jancborchardt** [comment]
What’s the use-case here really – I have to say I don’t see it. Let’s keep it simple and direct.

> Whereas, perusing one's junk folder is sometime necessary, but merely "previewing" an email can and does provide an attack vector for some malicious email.

If it’s about that – we do not show images by default. Which other vectors are there, and how can we handle those otherwise?
