### ISSUE TITLE
The name of the imap folders are badly encoded

### ISSUE THREAD

**Issue by Zefling** [nextcloud/mail#1758]
### Expected behavior
Before I update NextCloud and this extension, the accents were encoded correctly.

### Actual behavior
Now the UTF-8 code is directly visible, for example "Réduction" is now "RÃ©duction":

![Sélection_074](https://user-images.githubusercontent.com/3032555/57728727-e6be9d80-7694-11e9-9dcd-34e8c8b61872.png)

### Mail app

**Mail app version:** 0.15.1

**Mailserver or service:** Sendmail

### Server configuration

**Operating system**: Ubuntu Serveur 16.4

**Web server:** Apache

**Database:**  MariaDB

**PHP version:** 7.3

**Nextcloud Version:** 16.0.0

#### Client configuration
**Browser:** Waterfox 56 / Firefox 67

**Operating system:** Minux Mint

**Comment by ChristophWurst** [comment]
Fixed by https://github.com/nextcloud/mail/pull/2163
