### ISSUE TITLE
Also show »Sent« folder in the reduced list of folders?

### ISSUE THREAD

**Issue by jancborchardt** [nextcloud/mail#176]
This is the only folder I find myself looking through often and opening the »Show al folders« expander for. Maybe we should show it by default as well in the reduced list of folders?

cc @nextcloud/mail what do you think?

**Comment by skjnldsv** [comment]
Agreed too!

**Comment by ChristophWurst** [comment]
Simply adjust https://github.com/nextcloud/mail/blob/8ed4897393a32fe7715cc59f70b10e7db24a41fb/js/views/account.js#L21-L25. I assume the special folder type is something like 'sent'

**Comment by jancborchardt** [comment]
@ChristophWurst will do, thanks a lot for the pointer! :)
