### ISSUE TITLE
Mail deletion animation has issues with the menu popover

### ISSUE THREAD

**Issue by jancborchardt** [nextcloud/mail#1761]
When you open the 3-dot-menu of a message and delete it, it seems the menu flickers, reappears, and then also gets animated/compressed. And the animation compresses the entry until a certain stage, then the last 10px are not animated. Looks quite strange:
![mail deletion animation](https://user-images.githubusercontent.com/925062/57962052-9a34c580-7913-11e9-9291-f38beee5c839.gif)

Instead the menu should vanish right away, and the deletion animation fast and smooth.

Not sure whether it’s an issue with @nextcloud/mail or @nextcloud/vue though?

**Comment by skjnldsv** [comment]
Probably on the new standards here: https://github.com/nextcloud/nextcloud-vue/pull/382 :)

**Comment by ChristophWurst** [comment]
I would love to remove/replace that animation anyway. The collapse never appealed to me.

**Comment by jancborchardt** [comment]
We do need some feedback on deletion though, and collapsing is a great non-flamboyant way of doing that, which doesn't just jerk the entries below up.

Yes, we can improve the animation, like easing in and out, and making it quicker. But we do need an animation. :)

**Comment by ChristophWurst** [comment]
:+1: on animation

:-1: on collapse :wink:

**Comment by jancborchardt** [comment]
Fixed by @GretaD via https://github.com/nextcloud/mail/pull/2130 :balloon:
