### ISSUE TITLE
Adding new Mailaccount was going wrong

### ISSUE THREAD

**Issue by SwenSteinmann** [nextcloud/mail#1768]
### Expected behavior
After a fresh installation, i add the mail app. in the mail app i add one account sucessfull. Adding a second GMX account was not possible. 
Expected: a second mail account like the screenshots of the app.

### Actual behavior
in both "adding new mail account" screen (the simple an the expert way) the "Verbinden" (or connect) button will ghosted out for a while. after a minute the button is shown in full color. No account was add, no error message was shown. 
In the "nextcloud.log" ther e couple of error-messages.

### Mail app

**Mail app version:** 0.15.1

**Mailserver or service:** GMX

### Server configuration

**Operating system**: Hosting an Stato: SunOS localhost 5.10 Generic_142901-13 i86pc

**Web server:** Apache 2.4.39

**Database:** MariaDB

**PHP version:** 7.2.17

**Nextcloud Version:** 16.0.1

#### Client configuration
**Browser:** Firefox 66.0.5

**Operating system:** Windows 10
[nextcloud.log](https://github.com/nextcloud/mail/files/3195539/nextcloud.log)

**Comment by ChristophWurst** [comment]
> **Mail app version:** 0.15.1

I'm pretty sure this is a problem I fixed for the latest release. Please try again with Nextcloud 17 and the most up to date version of Mail :)
