### ISSUE TITLE
Make root folder path configurable

### ISSUE THREAD

**Issue by Patta** [nextcloud/mail#1769]
### Steps to reproduce
Add a mail account which has subfolders in inbox. Try to show all folders / collapse folders.

### Expected behaviour
Subfolders can be collapsed / uncollapsed by the collapse link.

### Actual behaviour
Subfolders in the inbox are not displayed and can't collapsed with the collpase link anymore. The collapse arrow on the inbox works, but the state is lost after reload.

It would be nice if the root folder could be set to e.g. INBOX.

![SharedScreenshot](https://user-images.githubusercontent.com/2151127/58006005-4975c600-7ae7-11e9-8996-adb070034cc8.jpg)

## Server configuration detail

**Operating system:** Linux 3.16.0-042stab134.8 #1 SMP Fri Dec 7 17:16:09 MSK 2018 x86_64

**Webserver:** nginx/1.14.2 (fpm-fcgi)

**Database:** mysql 10.0.38

**PHP version:** 

7.3.5
Modules loaded: Core, date, libxml, openssl, pcre, zlib, bz2, calendar, ctype, hash, filter, ftp, gettext, gmp, SPL, iconv, Reflection, session, standard, SimpleXML, sockets, mbstring, tokenizer, xml, cgi-fcgi, mysqlnd, bcmath, curl, dba, dom, enchant, fileinfo, gd, imagick, imap, intl, json, ldap, exif, memcached, mysqli, odbc, PDO, pdo_mysql, PDO_ODBC, pdo_pgsql, pdo_sqlite, pgsql, Phar, posix, pspell, redis, soap, sodium, sqlite3, sysvmsg, sysvsem, sysvshm, tidy, xmlreader, xmlrpc, xmlwriter, xsl, zip, ionCube Loader, Zend OPcache

**Nextcloud version:** 16.0.1 - 16.0.1.1

**Updated from an older Nextcloud/ownCloud or fresh install:** 

**Where did you install Nextcloud from:** unknown

<details><summary>Signing status</summary>

Array
(
)

</details>

<details><summary>List of activated apps</summary>

```
Enabled:
 - accessibility: 1.2.0
 - apporder: 0.7.1
 - bruteforcesettings: 1.3.0
 - calendar: 1.7.0
 - cloud_federation_api: 0.2.0
 - comments: 1.6.0
 - contacts: 3.1.1
 - dav: 1.9.2
 - deck: 0.6.2
 - encryption: 2.4.0
 - federatedfilesharing: 1.6.0
 - files: 1.11.0
 - files_pdfviewer: 1.5.0
 - files_rightclick: 0.13.0
 - files_sharing: 1.8.0
 - files_texteditor: 2.8.0
 - files_trashbin: 1.6.0
 - files_versions: 1.9.0
 - files_videoplayer: 1.5.0
 - firstrunwizard: 2.5.0
 - gallery: 18.3.0
 - issuetemplate: 0.5.0
 - logreader: 2.1.0
 - lookup_server_connector: 1.4.0
 - mail: 0.15.1
 - news: 13.1.6
 - nextcloud_announcements: 1.5.0
 - notes: 2.6.0
 - notifications: 2.4.1
 - oauth2: 1.4.2
 - password_policy: 1.6.0
 - privacy: 1.0.0
 - provisioning_api: 1.6.0
 - ransomware_protection: 1.4.0
 - recommendations: 0.4.0
 - serverinfo: 1.6.0
 - sharebymail: 1.6.0
 - support: 1.0.0
 - survey_client: 1.4.0
 - systemtags: 1.6.0
 - theming: 1.7.0
 - twofactor_backupcodes: 1.5.0
 - twofactor_totp: 2.1.2
 - updatenotification: 1.6.0
 - viewer: 1.0.0
 - workflowengine: 1.6.0
Disabled:
 - activity
 - admin_audit
 - federation
 - files_external
 - user_ldap

```
</details>

<details><summary>Configuration (config/config.php)</summary>

```
{
    "debug": false,
    "instanceid": "***REMOVED SENSITIVE VALUE***",
    "passwordsalt": "***REMOVED SENSITIVE VALUE***",
    "secret": "***REMOVED SENSITIVE VALUE***",
    "trusted_domains": [
        "***REMOVED SENSITIVE VALUE***"
    ],
    "datadirectory": "***REMOVED SENSITIVE VALUE***",
    "overwrite.cli.url": "***REMOVED SENSITIVE VALUE***",
    "dbtype": "mysql",
    "version": "16.0.1.1",
    "dbname": "***REMOVED SENSITIVE VALUE***",
    "dbhost": "***REMOVED SENSITIVE VALUE***",
    "dbtableprefix": "oc_",
    "dbuser": "***REMOVED SENSITIVE VALUE***",
    "dbpassword": "***REMOVED SENSITIVE VALUE***",
    "logtimezone": "UTC",
    "installed": true,
    "mail_from_address": "***REMOVED SENSITIVE VALUE***",
    "mail_smtpmode": "sendmail",
    "mail_domain": "***REMOVED SENSITIVE VALUE***",
    "loglevel": 4,
    "appstore.experimental.enabled": true,
    "maintenance": false,
    "theme": "",
    "mysql.utf8mb4": true,
    "mail_smtpauthtype": "LOGIN",
    "memcache.local": "\\OC\\Memcache\\Memcached",
    "memcache.distributed": "\\OC\\Memcache\\Memcached"
}
```
</details>

**Are you using external storage, if yes which one:** local/smb/sftp/...

**Are you using encryption:** 1

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...

## Client configuration

**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/74.0.3729.157 Safari/537.36

**Operating system:** 

## Logs

<details><summary>Web server error log</summary>

```
Insert your web server log here 
```
</details>

<details><summary>Nextcloud log</summary>

```
Insert your Nextcloud log here
```
</details>

<details><summary>Browser log</summary>

Insert your browser log here, this could for example include:

	a) The javascript console log
	b) The network log
	c) ...
</details>

**Comment by ChristophWurst** [comment]
Please use the bug template when reporting bugs.

**Comment by Patta** [comment]
Sorry, done.

**Comment by Patta** [comment]
Still open. Additional, mails can't be moved via drag and drop to a subfolder.
Nextcloud 17.0.1
Mail 0.18.1

**Comment by GretaD** [comment]
Collapsing subfolders its now fixed, you click the icon of a certain folder to collapse the subfolders of that folder. @Patta please follow updates here related to drag and drop feature: [1753](https://github.com/nextcloud/mail/issues/1538)
