### ISSUE TITLE
Mail 0.15.1 in Nextcloud 16.0.1 shows some mails several times

### ISSUE THREAD

**Issue by yafp** [nextcloud/mail#1770]
### Expected behavior
Mail should show each mail once

### Actual behavior
Some mails are displayed several times.

* Currently it affects 2 mails in the inbox of 1 mail-account. 
* Sometimes i see each of those 2 mails 4 times, sometimes only each twice. 
* This behaviour does not affects all mails
* It affects the single inbox and the universal inbox

Is that a known issue as i am using Mail 0.15.1 on Nextcloud 16.0.1?

### Mail app

**Mail app version:**  0.15.1

**Mailserver or service:** private hosted

### Server configuration

**Nextcloud Version:** 16.0.1

#### Client configuration
**Browser:** Firefox 66.0.5

**Operating system:** Ubuntu

**Comment by ChristophWurst** [comment]
> Is that a known issue as i am using Mail 0.15.1 on Nextcloud 16.0.1?

Not yet. But the unified inbox is a tricky feature and it wouldn't surprise me if I made a mistake in the new implementation :)

Please keep an eye on the issue. Would be great to detect the pattern that triggers this issue.

**Comment by yafp** [comment]
The only pattern (not sure if it is a pattern - or just randomness) i realize so far is that it affects 2 mails which are in direct order and both from the same sender.

I'll update here if i have more informations.

**Comment by yafp** [comment]
I've realized the same effect again .... and the pattern seems to be the same:

Requirements: Inbox has 2 mails in direct order from the same sender with the same subject
May result in: endless list of this email in the mail list

see attached screenshot:
![nextcloud-mail](https://user-images.githubusercontent.com/67605/58940921-053b2480-877b-11e9-9b03-38c5c3fd241a.png)

**Comment by ChristophWurst** [comment]
>     * Requirements: Inbox has 2 mails in direct order from the same sender with the same subject

Thanks for the feedback. We never compare messages by sender or subject but always by their UID, so this is a bit surprising. I'll think about it.

**Comment by Snaptags** [comment]
I have the same problem, but in my case only the account's inbox is affected. I don't get the duplicated entries in the universal inbox…

**Comment by ChristophWurst** [comment]
Good point. I have to test that case. I use the unified inbox 95% of the time.
