### ISSUE TITLE
Avatar images (from NextCloud) are not correctly rendered (damaged content)

### ISSUE THREAD

**Issue by Quix0r** [nextcloud/mail#179]
E.g. the following URL is being rendered when the sender email address matches with the one from the user (here mine):

https://owncloud.mxchange.org/remote.php/dav/addressbooks/system/system/system/Database:roland.vcf?photo

This didn't happen in ownCloud/mail. Strange here is the repeated _system/_ path.

**Comment by ChristophWurst** [comment]
Is this maybe a dup of https://github.com/nextcloud/mail/issues/131? Do contact avatars work for you?

**Comment by Quix0r** [comment]
Yes, this is a dup.
