### ISSUE TITLE
Avatars with transparency shown with avatar placeholder background

### ISSUE THREAD

**Issue by jancborchardt** [nextcloud/mail#1821]
### Expected behavior
Avatars with transparent background are shown with the avatar circle being either white (or transparent, but likely doesn’t look good in dark mode) so that the logos / icons are shown correctly.

### Actual behavior
The randomly generated color from the avatar placeholder shows through in the background. This happens for quite a lot of mails:
![avatars with transparent background](https://user-images.githubusercontent.com/925062/59931586-9978dd00-9445-11e9-9e74-cfbf7bbe2d84.png) ![avatar transparency](https://user-images.githubusercontent.com/925062/59931585-9978dd00-9445-11e9-88bc-79c1c14047b5.png) 
Shown are e.g. Meetup.com, Mattermost, FSFE, Open Source Initiative, Tito, Pretix, Eventbrite and Twitter.

### Info

**Mail app version:** current master
**Nextcloud Version:** current master

**Comment by ChristophWurst** [comment]
I wonder if this is coming from the nc-vue lib or our code. We actually show either the placeholder **or** the image: https://github.com/nextcloud/mail/blob/374ad54ea0c1956d77b032817111b3a0af10e1cc/src/components/Avatar.vue#L23-L24

**Comment by jancborchardt** [comment]
@skjnldsv @juliushaertl can you shed light on that? ^

**Comment by juliushaertl** [comment]
Not sure if that is set somewhere, but I also cannot reproduce

**Comment by skjnldsv** [comment]
@juliushaertl on mail Jan showed it to me. :man_shrugging:

**Comment by jancborchardt** [comment]
Can’t reproduce it on cloud.nextcloud.com either so if you can’t reproduce it on your local installs, I guess it might be some misconfiguration of my dev instance. :)

**Comment by jancborchardt** [comment]
Can reproduce it again, on cloud.nc, also same issue as in Contacts at https://github.com/nextcloud/contacts/issues/1066

Pull request to fix this by @hanzi at https://github.com/nextcloud/contacts/pull/1415
