### ISSUE TITLE
Setting up Dev Environment

### ISSUE THREAD

**Issue by developerrespig** [nextcloud/mail#183]
### Steps to reproduce
1. git clone https://github.com/nextcloud/mail.git mail (in apps directory)
2. make install-composer-deps
3. make optimize-js

### Expected behaviour
Installation routine finishes without any error

### Actual behaviour
 dateformat@1.0.12 (get-stdin@4.0.1, meow@3.7.0)
 js-yaml@3.5.5 (esprima@2.7.3, argparse@1.0.9)
 grunt-legacy-util@1.0.0 (getobject@0.1.0, which@1.2.11, hooker@0.2.3, async@1.5.2, underscore.string@3.2.3, lodash@4.3.0)
 grunt-legacy-log@1.0.0 (hooker@0.2.3, colors@1.1.2, underscore.string@3.2.3, lodash@3.10.1, grunt-legacy-log-utils@1.0.0)
 
bower@1.7.9 node_modules/bower
./node_modules/bower/bin/bower install
make: *** [install-bower-deps] Error 1
developer@respig:/var/www/html/nextcloud/apps/mail$

### Mail app

**Mail app version:** 0.6.0

### Server configuration
**Operating system**: Ubuntu 14.04.2 LTS

**Web server:** apache2

**Database:** mysql

**PHP version:** 5.5

**Version:** 10.0.1

**Updated from an older version or fresh install:** fresh install

**List of activated apps:** standard

```
Enabled:
  - activity: 2.3.2
  - comments: 1.0.0
  - dav: 1.0.1
  - federatedfilesharing: 1.0.1
  - federation: 1.0.1
  - files: 1.5.2
  - files_pdfviewer: 0.8.1
  - files_sharing: 1.0.0
  - files_texteditor: 2.1
  - files_trashbin: 1.0.0
  - files_versions: 1.3.0
  - files_videoplayer: 0.9.8
  - firstrunwizard: 1.1
  - gallery: 15.0.0
  - notifications: 0.3.0
  - password_policy: 1.0.0
  - provisioning_api: 1.0.0
  - serverinfo: 1.1.1
  - survey_client: 0.1.5
  - systemtags: 1.0.2
  - theming: 1.0.1
  - updatenotification: 1.0.1
  - workflowengine: 1.0.1
Disabled:
  - admin_audit
  - encryption
  - external
  - files_accesscontrol
  - files_automatedtagging
  - files_external
  - files_retention
  - mail
  - templateeditor
  - user_external
  - user_ldap
  - user_saml
```

**The content of config/config.php:**

<details>
```
<?php
$CONFIG = array (
  'instanceid' => '',
  'passwordsalt' => '',
  'secret' => '',
  'trusted_domains' => 
  array (
    0 => '',
  ),
  'datadirectory' => '/var/www/html/nextcloud/data',
  'overwrite.cli.url' => 'http://xxxx/nextcloud',
  'dbtype' => 'mysql',
  'version' => '9.1.1.5',
  'dbname' => 'nextcloud',
  'dbhost' => 'localhost',
  'dbport' => '',
  'dbtableprefix' => 'oc_',
  'dbuser' => '',
  'dbpassword' => '',
  'logtimezone' => 'UTC',
  'installed' => true,
);
```
</details>

#### Client configuration
**Browser:** Chrome

**Operating system:** Windows 10

I have the feeling that this is a newbie error, but anyway I can't find a way to fix it.

**Comment by developerrespig** [comment]
Used a container of codeanywhere. I installed node and npm für ubuntu, a nextcloud and then pulled your app and followed the steps of how to setup a dev environment. Still, I get the same error and I start getting frustrated. Does anyone have an idea how I can solve the above problem? Or can anyone provide steps on how to setup a fresh developer environment?

I would really help you to fix Bugs or develop new features, but this is actually a big blocker since a few weeks for me!

**Comment by ChristophWurst** [comment]
> ./node_modules/bower/bin/bower install
> make: *** [install-bower-deps] Error 1
> developer@respig:/var/www/html/nextcloud/apps/mail$

This looks strange. Can you try running that command from your CLI directly? 
```
./node_modules/bower/bin/bower install
```
or ``bower install`` if you have bower installed locally.

**Comment by ChristophWurst** [comment]
ping :-)

**Comment by developerrespig** [comment]
Hey. Sorry that I answer that late. Had to work on a few stuff for my exam :) Will be in touch with you soon. Hope this is ok? Btw I tried running the command you mentioned and it worked without a problem.

**Comment by ChristophWurst** [comment]
I assume we can close this ticket now. Let me know if you need help with getting started 😉
