### ISSUE TITLE
Messages marked read become unread again

### ISSUE THREAD

**Issue by 151henry151** [nextcloud/mail#1839]
### Expected behavior
Messages that are marked read should stay marked read

### Actual behavior
Two particular messages keep reverting to "unread"
Two particular emails keep reverting to "unread" after being marked "read." I tried marking them read from the individual inbox, and from the "All inboxes" joined inbox, and either way, a few minutes later if i refresh the page, they are once again "bold" indicating an unread status.

Screenshot shows the two emails (sorry for all the censored bits, just trying to respect the privacy of the people emailing me):

![Screenshot_2019-07-03_20-20-35](https://user-images.githubusercontent.com/6581719/60632130-da6fda80-9dd1-11e9-811e-a4b0d0daa59a.png)

Bizarrely, it seems that if I log in to my https://mail.zoho.com account, and mark the message as read there in their webmail interface, then the problem goes away. 

### Mail app

**Mail app version:** 0.11.1

**Mailserver or service:** Zohomail

### Server configuration

**Operating system:** Debian 9

**Web server:** Apache2

**Database:** MySQL

**PHP version:** 7.0.33

**Nextcloud Version:** 15.0.8

#### Client configuration
**Browser:** Mozilla Firefox 60.7.2 "firefox-esr"

**Operating system:** Debian 9

**Comment by ChristophWurst** [comment]
Please update to the latest version of Mail. The 0.11 series is not supported anymore. You'll need Nextcloud 16 to get more recent versions of Mail, though.
