### ISSUE TITLE
Subfolders doens't display email content anymore

### ISSUE THREAD

**Issue by bin101** [nextcloud/mail#1847]
### Expected behavior
If I navigate into a subfolder I can see the emails, can click on a single mail and see the content.

### Actual behavior
If I click on a mail, I cannot see the content and it doesn't get marked as read.
Edit: For mails on root level this works like a charm, I only experienced this in subfolders.

### Mail app

**Mail app version:** v0.15.1

**Mailserver or service:** "self-hosted" at my webhoster (all-inkl.com/)

### Server configuration

**Operating system**: Debian 9

**Web server:** Nginx

**Database:** MariaDB

**PHP version:** 7.2

**Nextcloud Version:** 16.0.3

#### Client configuration
**Browser:** Firefox 67.0.4 

**Operating system:** Arch Linux

**Comment by ChristophWurst** [comment]
what does the URL look like? Do you get any browser or server errors?

**Comment by bin101** [comment]
Sorry for the late answer, I was on vacation the last 2 weeks.
With v0.15.2 one part of the problem seems to be gone: I can now read my mails in sub-folders but only with a workaround:
If I click on a sub-folder the envelopes gets fetched and I can see the envelopes in the middle pane:

[DEBUG] mail: envelopes fetched 
Object { 0: {…}, 1: {…}, app: "mail", uid: "bin101" }

But if I click on a envelope itself it doesn't get opened on the right pane 

url i.e.:
https://mynextcloud/apps/mail/#/accounts/3/folders/R2VmaWx0ZXJ0L2RlY2tib3g=/message/3-R2VmaWx0ZXJ0L2RlY2tib3g=-1

If I now switch to any other folder and navigate back to the first I can read the mails.
I don't get any errors neither on client (browser) or server side...

Maybe I have to mention my folder structure?:

* root
  * standard folders like inbox, trash, etc.
  * filtered
    * filtered/*over 100 folders*

I have a catch-all address and some automatic filter rules on my mail-server to create a sub-folder inside the filtered folder the first appearing To header. For example a mail to test@mycatchalladdress.com will create the folder test inside filtered and moves the mail into it.

**Comment by ChristophWurst** [comment]
Can confirm. Will have a look ASAP.

**Comment by ChristophWurst** [comment]
So. It's complicated. We use a computed prop to check if there are messages in a folder. On first render this is false. But even if messages/envelopes are fetched later, the prop does not update. So this is something about Vue's reactivity. Either we use it wrong or it's triggering an edge case that is not covered. Funnily, if I add debug log statements the code starts to work because more magic getters are used during the access of the computed prop and thus Vue tracks more dependencies.
