### ISSUE TITLE
Wrong dutch translation: "Mark as unread" translated as "Mark as read"

### ISSUE THREAD

**Issue by freekvh** [nextcloud/mail#1849]
### Expected behavior
I click mark as read on a read message, the message should remain read.

### Actual behavior
Instead the message is marked as unread (usually what I want)

### Mail app

**Mail app version:** 0.15.1

### Server configuration

**Ubuntu 18.04**: (e.g. Debian 8)

**NGINX** (e.g. Apache, Nginx,...)

**MYSQL:** (e.g. MariaDB, SQLite or PostgreSQL)

**PHP version:** (e.g. 7.0)
7.0

**Nextcloud Version:** (see admin page, e.g. 13.0.2)
16.03 (latest as of now)

#### Client configuration
**Browser:** (e.g. Firefox 48)
Firefox 64

**Operating system:** (e.g. Arch Linux)
Windows

**Comment by ChristophWurst** [comment]
could you please check if this is really related to the translation or incorrect English string? Just switch your language to English and try again. I think there was a bug with updating the label. this might be fixed with the next version.

**Comment by rullzer** [comment]
Yes seems to be fixed
