### ISSUE TITLE
iCal Import does not work with calender series

### ISSUE THREAD

**Issue by SchoolGuy** [nextcloud/mail#186]
### Steps to reproduce
1. From Outlook (and I think any other E-Mail program) you send to your configured Mailacc an appointment with a serial.
2. Open the E-Mail app and click on the +-button
3. No appointment added

### Expected behaviour
The serial should appear for the time the user set in Outlook/...

### Actual behaviour
Nothing happens.

### Mail app

**Mail app version: 0.6.0** (see apps admin page)

**Mailserver or service: Outlook** (e.g. Outlook, Yahoo, Gmail, Exchange,...)

**Transport security - IMAP: SSL** (None, SSL, TLS, STARTTLS) 

**Transport security - SMTP: SSL** (None, SSL, TLS, STARTTLS)

**Number of accounts: 1**

**Mail app version build date: - (stable)** (only if you are using a Nightly Build)

### Server configuration
**Operating system**: Ubuntu 16.04 LTS

**Web server:** Apache2

**Database:** MaraiDB

**PHP version:** 7.0

**Version:** (see admin page): latest stable (10.0.1)

**Updated from an older version or fresh install:** Deleted Owncloud and made a fresh Nextcloud installation

**List of activated apps:**

```
If you have access to your command line run e.g.:
{
    "system": {
        "instanceid": "ocqmdqub9coz",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "mydomains"
        ],
        "datadirectory": "mydir",
        "overwrite.cli.url": "mydomain...",
        "dbtype": "mysql",
        "version": "9.1.1.5",
        "dbname": "mysql",
        "dbhost": "localhost",
        "dbport": "",
        "dbtableprefix": "oc_",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "logtimezone": "UTC",
        "installed": true,
        "appstore.experimental.enabled": true,
        "ldapIgnoreNamingRules": false,
        "ldapProviderFactory": "\\OCA\\User_LDAP\\LDAPProviderFactory",
        "loglevel": 3,
        "memcache.local": "\\OC\\Memcache\\Redis",
        "redis": {
            "host": "localhost",
            "port": port
        },
        "mail_from_address": "info",
        "mail_smtpmode": "smtp",
        "mail_domain": "mydomain.de",
        "mail_smtpsecure": "ssl",
        "mail_smtpauthtype": "LOGIN",
        "mail_smtphost": "smtp.host.de",
        "mail_smtpport": "port",
        "mail_smtpauth": 1,
        "mail_smtpname": "***REMOVED SENSITIVE VALUE***",
        "mail_smtppassword": "***REMOVED SENSITIVE VALUE***"
    }
}
```

**The content of config/config.php:**
```

---
```

#### Client configuration
**Browser:** Firefox (latest version)

**Operating system:** Windows 10

I think that should be enough to determine the problem.

Thx,
SchoolGuy

**Comment by SchoolGuy** [comment]
@ChristophWurst Thx for deleting sensetive intel (if you need more information, pls be so kind and tell me)

Support also available in German

**Comment by ChristophWurst** [comment]
@SchoolGuy you're welcome. Is anything in the logs? e.g. nextcloud.log or the browser's js console log?

**Comment by SchoolGuy** [comment]
Nothing, so really nothing because I am a newbie I was thinking it is my fault, but nothing is there. As soon as possible I will add them to the original post.

**Comment by SchoolGuy** [comment]
Ok this is a strange thing. BUT it is only Outlook related. Calender series are imported right, when you do the following:
1. Right click on the event.
2. Forward
3. Forward as iCalender
4. Forward Eventseries
5. Send

When you do the following steps from above the event is correctly placed into the calendar.
