### ISSUE TITLE
Multiple recipients → horizontal scrollbar

### ISSUE THREAD

**Issue by floeschie** [nextcloud/mail#1861]
When you add multiple email addresses into the "To" field or open an email with many recipients in the "To" field, and the width of the right content pane thus exceeds the available space, the browser displays a horizontal scrollbar and moves some UI parts into the invisible space.

### Expected behavior
When multiple email recipients are added to the "TO/CC/BCC" field, avoid horizontal scrollbars. Instead, allow line breaks or hide the recipient list (maybe make it accessible via a "…" button). The content of the email should be visible completely instead of being expanded into the non-visible area.

### Actual behavior
When many emails are added to the TO(CC/BCC field, the message composer/detail pane overflows the visible space and thus the browser shows a scrollbar. As a result, the content of an email is also partly hidden, because the message body pane is also expanded.

### Mail app
- **Mail app version:** 0.15.1
- **Mailserver or service:** IMAP/SMTP (Posteo)

### Server configuration
- **Nextcloud Version:** 16.0.3

#### Client configuration
- **Browser:** Firefox Quantum 68 64bit
- **Operating system:** Fedora Linux

**Comment by ChristophWurst** [comment]
could you please share a screenshot? there should be something like a +1, +2, ... icon in that case cc @skjnldsv

**Comment by floeschie** [comment]
Sure! Here's a screenshot of the browser window after I opened the mail app:

![Nextcloud Mail Screenshot from 2019-08-06 09-23-47](https://user-images.githubusercontent.com/1119719/62521285-a011b700-b82f-11e9-83f3-99b3b68d7d9c.png)

This is what it looks like when I scroll horizontally to the right end:

![Nextcloud Mail Screenshot from 2019-08-06 09-46-35](https://user-images.githubusercontent.com/1119719/62521357-cc2d3800-b82f-11e9-9d7b-d46c44908ab8.png)

The +n option is also not shown when I create a new email and add mulitple recipients:

![Nextcloud Mail Screenshot from 2019-08-06 09-56-35](https://user-images.githubusercontent.com/1119719/62521750-8886fe00-b830-11e9-86da-ad507ab349d6.png)

Hope this helps?

**Comment by ChristophWurst** [comment]
Mind retesting with the latest Mail app? The new message view got a design overhaul recently. Please reopen if this is still an issue.
