### ISSUE TITLE
No refresh in the "Trash" folder

### ISSUE THREAD

**Issue by Valdnet** [nextcloud/mail#1864]
### Expected behavior
Refresh of deleted messages when deleting in the "Trash" folder.

### Actual behavior
No refresh of deleted messages when deleting in the "Trash" folder.

### Steps to reproduce
1. Delete messages to "Trash".
2. Go to the "Trash" folder.
3. Delete one message.
**ERROR: No list refreshes. The deleted message is still visible.**

### Mail app

**Mail app version:** (see apps admin page, e.g. 0.5.3)
0.15.1

**Nextcloud Version:** (see admin page, e.g. 13.0.2)
16.0.3

#### Client configuration
**Browser:** (e.g. Firefox 48)
Firefox 68.0.1

**Operating system:** (e.g. Arch Linux)
Win10

**Comment by ChristophWurst** [comment]
logs?

Thank you for your report. It looks like your report is missing some important sections of your [issue template](https://raw.githubusercontent.com/nextcloud/mail/master/.github/ISSUE_TEMPLATE/bug.md). Please complete it so that we get a better understanding of your setup and the problem to be able to fix the issue.

Thank you.

**Comment by ChristophWurst** [comment]
The Nextcloud mail app offers an extensive logging system to make it easier identifying and tracking down bugs. Please enable [debug mode](https://docs.nextcloud.com/server/13/developer_manual/general/devenv.html#enabling-debug-mode) and set the log [level to debug](https://docs.nextcloud.com/server/13/admin_manual/configuration_server/logging_configuration.html) in your admin settings. Then, try to reproduce your issue and take another look at `data/nextcloud.log`, `data/horde_imap.log` and `data/horde_smtp.log`.

**Comment by ChristophWurst** [comment]
Please remove sensitive information before posting.

**Comment by Valdnet** [comment]
@ChristophWurst In data/nextcloud.log, data/horde_imap.log and data/horde_smtp.log there were no errors in reproducing your issue.

**Comment by ChristophWurst** [comment]
are there any browser errors in the console?
