### ISSUE TITLE
internal error when i send sharing of file by mail from my nextcloud

### ISSUE THREAD

**Issue by pwepwe973** [nextcloud/mail#1886]
#242 # Expected behavior
send the file share url by mailto by clicking on the postage link from nextcloud mail, window below for example.

![image](https://user-images.githubusercontent.com/37281042/62001262-e4dd7580-b0ec-11e9-9e8d-72fe4ccf3a81.png)

### Actual behavior
the internal error page gets affixed.

url : https://Cloud.MyNextcloudUrl.net/apps/mail/compose?uri=mailto%3A%3Fsubject%3DI shared a file with you%26body%3Dhttps%3A%2F%2Fcloud.mynextcloudurl.net%2Fs%2FZBCPW76BtXQrcki

![image](https://user-images.githubusercontent.com/37281042/62001298-8238a980-b0ed-11e9-9953-73057b2cd193.png)

### Mail app
**Mail app version:  0.11.1

**Mailserver or service:**: 
personal server on synology

### Server configuration

**Operating system**: 

openmediaault 4 (debian 9)

**Web server:** : 
 Nginx

**Database:** : 

MariaDB 

**PHP version:** 
PHP 7.0

**Nextcloud Version:**

15.0.10

#### Client configuration
Firefox 68.0.1

**Operating system:** (e.g. Arch Linux)
ubuntu

#### newspaper

The Journal TypeError: urlencode() expects parameter 1 to be string, null given
    0. /s/web/nextcloud/apps/mail/lib/Controller/PageController.php - line 146: 
       urlencode("*** sensiti ... *")
    1. <<closure>>
       OCA\Mail\Controller\PageController->OCA\Mail\Controller\{closure}("*** sensiti ... *")
    2. /s/web/nextcloud/apps/mail/lib/Controller/PageController.php - line 147: 
       array_walk({ to: "*** s ... "}, Closure {})
    3. /s/web/nextcloud/lib/private/AppFramework/Http/Dispatcher.php - line 166: 
       OCA\Mail\Controller\PageController->compose("mailto:?sub ... i")
    4. /s/web/nextcloud/lib/private/AppFramework/Http/Dispatcher.php - line 99: 
       OC\AppFramework\Http\Dispatcher->executeController(OCA\Mail\Con ... {}, "compose")
    5. /s/web/nextcloud/lib/private/AppFramework/App.php - line 118: 
       OC\AppFramework\Http\Dispatcher->dispatch(OCA\Mail\Con ... {}, "compose")
    6. /s/web/nextcloud/lib/private/AppFramework/Routing/RouteActionHandler.php - line 47: 
       OC\AppFramework\App::main("OCA\\Mail\\ ... r", "compose", OC\AppFramew ... {}, { _route: "mail.page.compose"})
    7. <<closure>>
       OC\AppFramework\Routing\RouteActionHandler->__invoke({ _route: "mail.page.compose"})
    8. /s/web/nextcloud/lib/private/Route/Router.php - line 297: 
       call_user_func(OC\AppFramew ... {}, { _route: "mail.page.compose"})
    9. /s/web/nextcloud/lib/base.php - line 987: 
       OC\Route\Router->match("/apps/mail/compose")
    10. /s/web/nextcloud/index.php - line 42: 
       OC::handleRequest()

Error | PHP | Undefined index: path at /s/web/nextcloud/apps/mail/lib/Controller/PageController.php#135

{"reqId":"ozVo8i7IKcrq9fSGLGuO","level":3,"time":"2019-07-28T03:14:34+00:00","remoteAddr":"192.168.2.232","user":"user1","app":"PHP","method":"GET","url":"/apps/mail/compose?uri=mailto%3A%3Fsubject%3DI%20shared%20a%20file%20with%20you","message":"Undefined index: path at /s/web/nextcloud/apps/mail/lib/Controller/PageController.php#135","userAgent":"Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:68.0) Gecko/20100101 Firefox/68.0","version":"15.0.10.0","id":"5d3d131a874ab"}

**Comment by ChristophWurst** [comment]
could you please update to the latest nextcloud and also the latest nextcloud mail app version and try again?

**Comment by wenzler** [comment]
Same with nextcloud - 15.0.11 - I assume you want us to upgrade to 16.0?

**Comment by ChristophWurst** [comment]
I see two issues here

* The generated mailto link seems false
* The Mail app should handle these errors more gracefully. I guess just ignoring empty parameters should be good enough. So a ``array_filter($params);`` at https://github.com/nextcloud/mail/blob/05004347abf1920b8bd55134b494af1248103cd0/lib/Controller/PageController.php#L156

**Comment by wenzler** [comment]
The mailto link came from the webpage itself when opening it in the old version 
Firefox asked whether you want to add it as a protocol handler. 
This seems inactive in the current release as Im unable to retrigger it.

**Comment by ChristophWurst** [comment]
Yep, but the link was not generated by the mail app but the Nextcloud server component ;-)

**Comment by ChristophWurst** [comment]
Oh no actually it is https://apps.nextcloud.com/apps/socialsharing_email

**Comment by wenzler** [comment]
Your code

./mail/js/app.js

```
  registerProtocolHandler: function() {
                        if (window.navigator.registerProtocolHandler) {
                                var url = window.location.protocol + '//' +
                                                window.location.host +
                                                OC.generateUrl('apps/mail/compose?uri=%s');
                                try {
                                        window.navigator
                                                        .registerProtocolHandler('mailto', url, OC.theme.name + ' Mail');
                                } catch (e) {
                                }
                        }
                },

```

**Comment by ChristophWurst** [comment]
Yes, but no. The mailto part (`mailto%3A%3Fsubject%3DI`) is generated elsewhere

**Comment by ChristophWurst** [comment]
>     * The Mail app should handle these errors more gracefully

in any case this might be a good solution. would you mind giving that a try?
