### ISSUE TITLE
Continuously connect and disconnect to imap when refreshing mailbox

### ISSUE THREAD

**Issue by moraus** [nextcloud/mail#1887]
### Expected behavior
The mail app should connect and login to IMAP only once.

### Actual behavior
When the the app is displaying the Inbox (or any other mail box), the app continuously login and logout from imap when the "spinning load more wheel" is active.
This do not happen until you scroll to the bottom of the mail list, and the app should load more messages.

### Mail app

**Mail app version:** (see apps admin page, e.g. 0.5.3)
15.1

**Mailserver or service:** (e.g. Outlook, Yahoo, Gmail, Exchange,...)
Self hosted MTA with Exim 4.90.1-1ubuntu1.3 and Courier-imap-ssl 4.18.1+0.78.0-2ubuntu2

### Server configuration

**Operating system**: (e.g. Debian 8)
Distributor ID:	Ubuntu
Description:	Ubuntu 18.04.2 LTS
Release:	18.04
Codename:	bionic

**Web server:** (e.g. Apache, Nginx,...)
apache2                               2.4.29-1ubuntu4.6

**Database:** (e.g. MariaDB, SQLite or PostgreSQL)
mysql-server                          5.7.27-0ubuntu0.18.04.1

**PHP version:** (e.g. 7.0)
php7.2                                7.2.19-0ubuntu0.18.04.1

**Nextcloud Version:** (see admin page, e.g. 13.0.2)
16.0.3.0

#### Client configuration
**Browser:** (e.g. Firefox 48)
Chrome, Version 75.0.3770.142 (Official Build) (64-bit)
**Operating system:** (e.g. Arch Linux)
Distributor ID:	Ubuntu
Description:	Ubuntu 18.04.2 LTS
Release:	18.04
Codename:	bionic

**Comment by ChristophWurst** [comment]
could you check if there is more than one HTTP requests to the server when this happens? I'm wondering if we just have to reuse a connection within one request or do connection pooling across requests

**Comment by moraus** [comment]
Hi,

See the attached imapd log and the "almost" corresponding netstat

[imapd-ssl-final.log](https://github.com/nextcloud/mail/files/3470822/imapd-ssl-final.log)
[netstat.log](https://github.com/nextcloud/mail/files/3470823/netstat.log)
