### ISSUE TITLE
Dyslexia + dark theme makes unread emails almost unidentifiable

### ISSUE THREAD

**Issue by nickvergessen** [nextcloud/mail#1889]
### Expected behavior
You should be able to easily spot the unread emails in the list

### Actual behavior
With the heavy weighted OpenDyslexic font, the different between bold and normal is too small and it's not easy enough to spot the difference:

> ![dyslexia-dark-theme](https://user-images.githubusercontent.com/213943/62360440-0ee1ce00-b519-11e9-952a-bdc6e86744a5.png)

After a quick chat with @jancborchardt we think that a colored dot behind the email would be the best way to identify them.

**Comment by jancborchardt** [comment]
So yes, iOS uses a colored dot, and we also have this "unread count bubble" in Talk and other places.

I’m still not sure yet what’s the best way to do this as it would be yet another indicator and it’s not self-descriptive as meaning "unread". Bold and non-bold is used pretty universally in chat apps.

Another option, because this is unique to the Dyslexia font, is to have the solution specific to it. Something like having a border around the image of the sender, or indeed a dot, or something like that. It’s not the best solution though.

**Comment by ChristophWurst** [comment]
> So yes, iOS uses a colored dot

screenshots please :)

**Comment by jancborchardt** [comment]
> > So yes, iOS uses a colored dot
> 
> screenshots please :)

From image search:
![apple mail unread](https://user-images.githubusercontent.com/925062/62654633-8328d100-b960-11e9-9123-444e28a54e31.png)

**Comment by ChristophWurst** [comment]
okay but where would you put that? this conflicts with our avatar, no?

**Comment by jancborchardt** [comment]
> okay but where would you put that? this conflicts with our avatar, no?

As said above ;)

> I’m still not sure yet what’s the best way to do this as it would be yet another indicator and it’s not self-descriptive as meaning "unread". Bold and non-bold is used pretty universally in chat apps.

**Comment by intika** [comment]
nc 7.0.1 + mail 0.19 + chrome/firefox
On dark or light there there is no difference at all with read/unread mail... i only can see a light difference when using Dyslexia font, like the capture of the op

**Comment by jancborchardt** [comment]
After thinking about this a bit more, this is probably rather something to file as upstream issue with OpenDyslexic: https://github.com/antijingoist/opendyslexic/issues

(Related to https://github.com/nextcloud/news/issues/579 where the issue also lies with the Ubuntu font, or font rendering on a specific operating system or browser, not with Nextcloud.)

**Comment by intika** [comment]
@jancborchardt i know the op posted about Dyslexia font not being too bold but this should not be closed.

With normal font the system is not working (bold/normal) all mails read and unread are displayed without bold state, i tested this on many system/browsers and the new mail are not displayed in bold (only when using Dyslexia the new mail are bold)

**Comment by jancborchardt** [comment]
@intika that would be a separate issue then though. :) And I can’t reproduce it here? Clear difference between unread in bold and read below:
![read-unread](https://user-images.githubusercontent.com/925062/69931369-9e17e600-14f9-11ea-978b-35f599247fc0.png)

**Comment by intika** [comment]
@jancborchardt thanks indeed i see... there may be a bug in the opensource linux font am using... i'll investigate that in deep later on and post back the fix ;) ... but it's kind a weird i have the same issue on mobile with bromite... but not with chrome mobile now that i tested with it... anyway i am just using a quick fix with [font changer](https://chrome.google.com/webstore/detail/font-changer-with-google/jgjhhoglgjdklldfgoffdiaceffijeke?hl=en) until i have the time to investigate ;)
