### ISSUE TITLE
Infinite spinner

### ISSUE THREAD

**Issue by tblake84** [nextcloud/mail#189]
### Steps to reproduce
1. Cloned repo
2. "Make"
3. Enable in OwnCloud and try accessing page, spinner keeps spinning infinitely.

### Expected behaviour
The mail page should load.

### Actual behaviour
Spinner keeps spinning, page does not actually load

### Mail app

**Mail app version:** 0.6.0 (cloned latest master)

### Server configuration
**Operating system**: Ubuntu 14.04

**Web server:** Apache2

**Database:**

**PHP version:**

**Version:** (see admin page)

**Updated from an older version or fresh install:**

**List of activated apps:**

```
root@cloud:/var/www/owncloud# sudo -u www-data php occ app:list
Enabled:
  - calendar: 1.4.0
  - comments: 0.3.0
  - contacts: 1.4.0.0
  - dav: 0.2.6
  - documents: 0.13.1
  - external: true
  - federatedfilesharing: 0.3.0
  - files: 1.5.1
  - files_external: 0.6.0
  - files_pdfviewer: 0.8.1
  - files_sharing: 0.10.0
  - files_texteditor: 2.1
  - files_trashbin: 0.9.0
  - files_versions: 1.3.0
  - files_videoplayer: 0.9.8
  - firstrunwizard: 1.1
  - mail: 0.6.0
  - notifications: 0.3.0
  - provisioning_api: 0.5.0
  - systemtags: 0.3.0
  - tasks: 0.9.3
  - templateeditor: 0.1
  - updatenotification: 0.2.1
Disabled:
  - activity
  - encryption
  - federation
  - files_antivirus
  - gallery
  - ownnote
  - user_external
  - user_ldap

```

**The content of config/config.php:**

<details>
```
<?php
$CONFIG = array (
  'updatechecker' => false,
  'instanceid' => 'ocvul7ojidh3',
  'passwordsalt' => '',
  'secret' => '',
  'trusted_domains' =>
  array (
    0 => 'cloud.intelligentintercept.com',
  ),
  'datadirectory' => '/var/www/owncloud/data',
  'overwrite.cli.url' => 'http://cloud.intelligentintercept.com/owncloud',
  'dbtype' => 'sqlite3',
  'version' => '9.1.1.3',
  'logtimezone' => 'UTC',
  'installed' => true,
  'mail_smtpmode' => 'php',
  'mail_from_address' => 'cloud',
  'mail_domain' => 'corrections.com',
  'maintenance' => false,
  'theme' => '',
  'loglevel' => 2,
);

```
</details>

#### Client configuration
**Browser:** Firefox

**Operating system:** Windows 10

### Relevant owncloud.log file output:

{"reqId":"+b2byDJiIZ6NgHRG\/RkC","remoteAddr":"75.144.155.9","app":"mail","message":"Could not find resource file \"\/owncloud\/apps\/mail\/js\/vendor\/autosize\/jquery.autosize.js\"","level":3,"time":"2016-11-07T22:30:17+00:00","method":"GET","url":"\/owncloud\/index.php\/apps\/mail\/","user":"tblake"}
{"reqId":"+b2byDJiIZ6NgHRG\/RkC","remoteAddr":"75.144.155.9","app":"mail","message":"Could not find resource file \"\/owncloud\/apps\/mail\/js\/vendor\/jquery-storage-api\/jquery.storageapi.js\"","level":3,"time":"2016-11-07T22:30:17+00:00","method":"GET","url":"\/owncloud\/index.php\/apps\/mail\/","user":"tblake"}
{"reqId":"+b2byDJiIZ6NgHRG\/RkC","remoteAddr":"75.144.155.9","app":"mail","message":"Could not find resource file \"\/owncloud\/apps\/mail\/js\/vendor\/jquery-visibility\/jquery-visibility.js\"","level":3,"time":"2016-11-07T22:30:17+00:00","method":"GET","url":"\/owncloud\/index.php\/apps\/mail\/","user":"tblake"}
{"reqId":"+b2byDJiIZ6NgHRG\/RkC","remoteAddr":"75.144.155.9","app":"mail","message":"Could not find resource file \"\/owncloud\/apps\/mail\/js\/vendor\/requirejs\/require.js\"","level":3,"time":"2016-11-07T22:30:17+00:00","method":"GET","url":"\/owncloud\/index.php\/apps\/mail\/","user":"tblake"}
{"reqId":"VAZV3fCWEIXcJT2l+gVR","remoteAddr":"75.144.155.9","app":"mail","message":"Could not find resource file \"\/owncloud\/apps\/mail\/js\/vendor\/autosize\/jquery.autosize.js\"","level":3,"time":"2016-11-07T22:30:24+00:00","method":"GET","url":"\/owncloud\/index.php\/apps\/mail\/","user":"tblake"}
{"reqId":"VAZV3fCWEIXcJT2l+gVR","remoteAddr":"75.144.155.9","app":"mail","message":"Could not find resource file \"\/owncloud\/apps\/mail\/js\/vendor\/jquery-storage-api\/jquery.storageapi.js\"","level":3,"time":"2016-11-07T22:30:24+00:00","method":"GET","url":"\/owncloud\/index.php\/apps\/mail\/","user":"tblake"}
{"reqId":"VAZV3fCWEIXcJT2l+gVR","remoteAddr":"75.144.155.9","app":"mail","message":"Could not find resource file \"\/owncloud\/apps\/mail\/js\/vendor\/jquery-visibility\/jquery-visibility.js\"","level":3,"time":"2016-11-07T22:30:24+00:00","method":"GET","url":"\/owncloud\/index.php\/apps\/mail\/","user":"tblake"}
{"reqId":"VAZV3fCWEIXcJT2l+gVR","remoteAddr":"75.144.155.9","app":"mail","message":"Could not find resource file \"\/owncloud\/apps\/mail\/js\/vendor\/requirejs\/require.js\"","level":3,"time":"2016-11-07T22:30:24+00:00","method":"GET","url":"\/owncloud\/index.php\/apps\/mail\/","user":"tblake"}
{"reqId":"akbijBfX3PHxHIxm29Yn","remoteAddr":"75.144.155.9","app":"PHP","message":"Exception: Cannot include autoload. Did you run install dependencies using composer? at \/var\/www\/owncloud\/apps\/mail\/appinfo\/app.php#27","level":3,"time":"2016-11-07T22:38:07+00:00","method":"GET","url":"\/owncloud\/ocs\/v2.php\/apps\/notifications\/api\/v1\/notifications?format=json","user":"tblake"}

**Comment by tblake84** [comment]
{"reqId":"+b2byDJiIZ6NgHRG\/RkC","remoteAddr":"75.144.155.9","app":"mail","message":"Could not find resource file \"\/owncloud\/apps\/mail\/js\/vendor\/autosize\/jquery.autosize.js\"","level":3,"time":"2016-11-07T22:30:17+00:00","method":"GET","url":"\/owncloud\/index.php\/apps\/mail\/","user":"tblake"}
{"reqId":"+b2byDJiIZ6NgHRG\/RkC","remoteAddr":"75.144.155.9","app":"mail","message":"Could not find resource file \"\/owncloud\/apps\/mail\/js\/vendor\/jquery-storage-api\/jquery.storageapi.js\"","level":3,"time":"2016-11-07T22:30:17+00:00","method":"GET","url":"\/owncloud\/index.php\/apps\/mail\/","user":"tblake"}
{"reqId":"+b2byDJiIZ6NgHRG\/RkC","remoteAddr":"75.144.155.9","app":"mail","message":"Could not find resource file \"\/owncloud\/apps\/mail\/js\/vendor\/jquery-visibility\/jquery-visibility.js\"","level":3,"time":"2016-11-07T22:30:17+00:00","method":"GET","url":"\/owncloud\/index.php\/apps\/mail\/","user":"tblake"}
{"reqId":"+b2byDJiIZ6NgHRG\/RkC","remoteAddr":"75.144.155.9","app":"mail","message":"Could not find resource file \"\/owncloud\/apps\/mail\/js\/vendor\/requirejs\/require.js\"","level":3,"time":"2016-11-07T22:30:17+00:00","method":"GET","url":"\/owncloud\/index.php\/apps\/mail\/","user":"tblake"}
{"reqId":"VAZV3fCWEIXcJT2l+gVR","remoteAddr":"75.144.155.9","app":"mail","message":"Could not find resource file \"\/owncloud\/apps\/mail\/js\/vendor\/autosize\/jquery.autosize.js\"","level":3,"time":"2016-11-07T22:30:24+00:00","method":"GET","url":"\/owncloud\/index.php\/apps\/mail\/","user":"tblake"}
{"reqId":"VAZV3fCWEIXcJT2l+gVR","remoteAddr":"75.144.155.9","app":"mail","message":"Could not find resource file \"\/owncloud\/apps\/mail\/js\/vendor\/jquery-storage-api\/jquery.storageapi.js\"","level":3,"time":"2016-11-07T22:30:24+00:00","method":"GET","url":"\/owncloud\/index.php\/apps\/mail\/","user":"tblake"}
{"reqId":"VAZV3fCWEIXcJT2l+gVR","remoteAddr":"75.144.155.9","app":"mail","message":"Could not find resource file \"\/owncloud\/apps\/mail\/js\/vendor\/jquery-visibility\/jquery-visibility.js\"","level":3,"time":"2016-11-07T22:30:24+00:00","method":"GET","url":"\/owncloud\/index.php\/apps\/mail\/","user":"tblake"}
{"reqId":"VAZV3fCWEIXcJT2l+gVR","remoteAddr":"75.144.155.9","app":"mail","message":"Could not find resource file \"\/owncloud\/apps\/mail\/js\/vendor\/requirejs\/require.js\"","level":3,"time":"2016-11-07T22:30:24+00:00","method":"GET","url":"\/owncloud\/index.php\/apps\/mail\/","user":"tblake"}
{"reqId":"akbijBfX3PHxHIxm29Yn","remoteAddr":"75.144.155.9","app":"PHP","message":"Exception: Cannot include autoload. Did you run install dependencies using composer? at \/var\/www\/owncloud\/apps\/mail\/appinfo\/app.php#27","level":3,"time":"2016-11-07T22:38:07+00:00","method":"GET","url":"\/owncloud\/ocs\/v2.php\/apps\/notifications\/api\/v1\/notifications?format=json","user":"tblake"}

**Comment by pafcioooo** [comment]
Same issue exists on my Ubuntu 16.04, apache 2.4.18, php7, nextcloud version 10 (upgraded from owncloud), nexcloud log error messages are:
"Error	mail	Could not find resource file "/apps/mail/js/mail.min.js"
Error	mail	Could not find resource file "/apps/mail/js/vendor/requirejs/require.js"
Error	mail	Could not find resource file "/apps/mail/js/vendor/jquery-visibility/jquery-visibility.js"
Error	mail	Could not find resource file "/apps/mail/js/vendor/jquery-storage-api/jquery.storageapi.js"	
Error	mail	Could not find resource file "/apps/mail/js/vendor/autosize/jquery.autosize.js"

**Comment by ChristophWurst** [comment]
Hi,

either set up the project as documented in the readme https://github.com/nextcloud/mail#developer-setup-info or use a packaged version from the app store.
