### ISSUE TITLE
Ability to add signature to all messages [$235]

### ISSUE THREAD

**Issue by HLFH** [nextcloud/mail#190]
Hi,

Am I wrong or are we not able to add signature to our messages with Nextcloud mail?
See: https://github.com/owncloudarchive/mail/issues/654

Thanks,

**Comment by ChristophWurst** [comment]
It's still missing. Wanna help implement it? 😉

**Comment by Gomez** [comment]
Most of the work is already done: https://github.com/owncloudarchive/mail/pull/1616

**Comment by JakubSs** [comment]
What about now? its available?

**Comment by ChristophWurst** [comment]
@JakubSs AFAIK nobody is working on it at the moment, so feel free to dive into the code and help finish this feature ;-)

**Comment by JakubSs** [comment]
@ChristophWurst I am not so good at it... :D but I am interested... its only thing I miss on this app...

**Comment by DoubleMalt** [comment]
@ChristophWurst Is there a standard way of moving over a pull request from owncloudarchive/mail to here?

**Comment by ChristophWurst** [comment]
> @ChristophWurst Is there a standard way of moving over a pull request from owncloudarchive/mail to here?

Add both repos as origin. Pull the branch/changes from one repo and push to the other. Something like
```bash
git remote add owncloud …
git remote add origin git@github.com:/nextcloud/mail.git
git fetch owncloud
git checkout owncloud/branch -b branch
git push branch nextcloud/branch
```

**Comment by alexanderdd** [comment]
Great, looks like a lot of work has already been done. Sorry I dont have the skills to actually carry on =)

**Comment by alexanderdd** [comment]
Oh and it would be awesome if HTML signatures are possible (HTML hasn't been mentioned here yet).
HTML signatures are industry standard these days, and actually very few ways exist to send emails with HTML signatures on mobile devices. So this would be a killer feature.

Thanks for your work everyone!

**Comment by jlabegg** [comment]
another suggestion, because you can add different email account, you should be able to have signature within the mail account parameters.... one account, one signature?
And sorry, i don't have the skill for coding that. Maybe if you need french translation?
Thank you for your work!

**Comment by zamashal** [comment]
How far done is this feature? I only know little php, and I am new to github, but if you can guide me on how to help with implementing this feature I would like to start learning and helping right away.

**Comment by ChristophWurst** [comment]
> but if you can guide me on how to help with implementing this feature I would like to start learning and helping right away.

https://docs.nextcloud.com/server/13/developer_manual/app/tutorial.html might be a good starting point :)

**Comment by accima** [comment]
Without this feature many of us will not be able to upgrade to version 14 of nextcloud. How far done is this feature?

**Comment by ChristophWurst** [comment]
> How far done is this feature?

There had been some efforts in developing this in the past, but the code seems outdated, so I'd estimate roughly 0%.

**Comment by RuudschMaHinda** [comment]
I'll talk to someone in the club I want to implement mail, but can't without signature support. Hoping they can maybe increase the bounty by some. This is a make or break feature for this app to be used in professional use cases.

**Comment by omocinteractive** [comment]
"professional use cases." This is the only reason we don't use the nextcloud mailer. It's a absolut must-have business feature.

**Comment by rullzer** [comment]
@RuudschMaHinda @omocinteractive do you have an [Enterprise Subscription](https://nextcloud.com/enterprise/)? Because if so reach out to your account manager and we can see if we can get this prioritized.

**Comment by omocinteractive** [comment]
@rullzer no, because we are only 2 person and 1900€/year is al lot of money ...

I very good online-mailer with many features (like thunderbird) is https://github.com/jasonmunro/cypht, maybe the developer will support the nextcloud-mailer team. I ask him to integrate the mailer into nextcloud, but he is scared off the nextcloud specifications ...

**Comment by RuudschMaHinda** [comment]
@rullzer same here. No Enterprise subscription. I am supporting non profit clubs who got to report on every cent they spent. There is no public  money allocated to software, let alone maintenance unfortunately. But sometimes there is a bit of surplus. I fear the answer will be a "no" though.

**Comment by rullzer** [comment]
Valid reasons :)

In that case other ways to try to get this sped up are:
- 💻 Get involved https://github.com/nextcloud/mail#development-setup
- 💸 Donate to the bounty at https://www.bountysource.com/issues/37682663-add-files-from-nextcloud-as-link

**Comment by ann0see** [comment]
Like many others said: that's the only feature I miss.

**Comment by esbeeb** [comment]
Here's a crazy idea.  It's simplicity will astound you. 
How about if the end user uploads a plain-text file with exactly the name "sig.txt" and puts it in the root folder of their Nextcloud files, then the Mail app notices the existence of this file, and appends the contents of said sig.txt to the bottom of all new emails (after stripping out potentially malicious characters like "<", ">", "#!", etc).

**Comment by esbeeb** [comment]
Here's an idea that will incentivize this feature.  New installations of the Mail app should create the sig.txt for all existing and new users, if they don't already have one (in their root folders).  And inside those default sig.txt files could be a little advertisement for Nextcloud, saying something like "sent from Nextcloud, which is awesome. Check it out at http://nextcloud.com".  

The end user gets to change the sig.txt if course, with, say, the Nextcloud "Text editor" app.

**Comment by small1** [comment]
This has been asked about from my clients. They are not large enough to be able to pay for an enterprise subscription at this point tho. To small. But ill see if i can toss in money for the bounty.

**Comment by ChristophWurst** [comment]
PR is at https://github.com/nextcloud/mail/pull/1657. Please help test and review.
