### ISSUE TITLE
Error connecting to mail server.

### ISSUE THREAD

**Issue by EM50L** [nextcloud/mail#1905]
## Steps to reproduce
1. only with nextcloud 16 debian8 with ip6 enable
2. with nextcloud 16 ip4 works
3. with nextcloud 15 ip6 enable works

{"reqId":"By5GpVozMR1QtJj6lten","level":3,"time":"2019-08-05T15:57:43+00:00","remoteAddr":"79.109.2.200","user":"jejo","app":"mail","method":"GET","url":"/jcloud/index.php/apps/mail/api/accounts/9/folders/SU5CT1g%3D/sync?syncToken=VTE1NDM2LFYxNCxNMjU3NA%3D%3D&uids[]=15434&uids[]=15432&uids[]=15430&uids[]=15428&uids[]=15425&uids[]=15423&uids[]=15401&uids[]=15395&uids[]=15393&uids[]=15391&uids[]=15389&uids[]=15387&uids[]=15385&uids[]=15383&uids[]=15381&uids[]=15379&uids[]=15377&uids[]=15374&uids[]=15372&uids[]=15370&uids[]=15368&uids[]=15366","message":{"Exception":"Horde_Imap_Client_Exception","Message":"Error connecting to mail server.","Code":11,"Trace":[{"file":"/var/www/html/jcloud/apps/mail/vendor/pear-pear.horde.org/Horde_Imap_Client/Horde/Imap/Client/Socket.php","line":375,"function":"_connect","class":"Horde_Imap_Client_Socket","type":"->","args":[]},{"file":"/var/www/html/jcloud/apps/mail/vendor/pear-pear.horde.org/Horde_Imap_Client/Horde/Imap/Client/Base.php","line":838,"function":"_login","class":"Horde_Imap_Client_Socket","type":"->","args":["*** sensitive parameters replaced ***"]},{"file":"/var/www/html/jcloud/apps/mail/vendor/pear-pear.horde.org/Horde_Imap_Client/Horde/Imap/Client/Base.php","line":1598,"function":"login","class":"Horde_Imap_Client_Base","type":"->","args":["*** sensitive parameters replaced ***"]},{"file":"/var/www/html/jcloud/apps/mail/vendor/pear-pear.horde.org/Horde_Imap_Client/Horde/Imap/Client/Base.php","line":4038,"function":"status","class":"Horde_Imap_Client_Base","type":"->","args":[{"__class__":"Horde_Imap_Client_Mailbox"},8713]},{"file":"/var/www/html/jcloud/apps/mail/vendor/pear-pear.horde.org/Horde_Imap_Client/Horde/Imap/Client/Base.php","line":3632,"function":"_syncStatus","class":"Horde_Imap_Client_Base","type":"->","args":[{"__class__":"Horde_Imap_Client_Mailbox"}]},{"file":"/var/www/html/jcloud/apps/mail/lib/IMAP/Sync/Synchronizer.php","line":61,"function":"sync","class":"Horde_Imap_Client_Base","type":"->","args":[{"__class__":"Horde_Imap_Client_Mailbox"},"U15436,V14,M2574",{"ids":{"duplicates":false,"__class__":"Horde_Imap_Client_Ids"}}]},{"file":"/var/www/html/jcloud/apps/mail/lib/Service/MailManager.php","line":110,"function":"sync","class":"OCA\\Mail\\IMAP\\Sync\\Synchronizer","type":"->","args":[{"cacheFields":{"1":"HICstruct","8":"HIChdrs","9":"HICenv","10":"HICflags","11":"HICdate","12":"HICsize"},"changed":true,"statuscache":true,"__class__":"Horde_Imap_Client_Socket"},{"__class__":"OCA\\Mail\\IMAP\\Sync\\Request"}]},{"file":"/var/www/html/jcloud/apps/mail/lib/Controller/FoldersController.php","line":102,"function":"syncMessages","class":"OCA\\Mail\\Service\\MailManager","type":"->","args":[{"__class__":"OCA\\Mail\\Account"},{"__class__":"OCA\\Mail\\IMAP\\Sync\\Request"}]},{"file":"/var/www/html/jcloud/lib/private/AppFramework/Http/Dispatcher.php","line":166,"function":"sync","class":"OCA\\Mail\\Controller\\FoldersController","type":"->","args":[9,"SU5CT1g=","VTE1NDM2LFYxNCxNMjU3NA==",["15434","15432","15430","15428","15425","15423","15401","15395","15393","15391","15389","15387","15385","15383","15381","15379","15377","15374","15372","15370","15368","15366"]]},{"file":"/var/www/html/jcloud/lib/private/AppFramework/Http/Dispatcher.php","line":99,"function":"executeController","class":"OC\\AppFramework\\Http\\Dispatcher","type":"->","args":[{"__class__":"OCA\\Mail\\Controller\\FoldersController"},"sync"]},{"file":"/var/www/html/jcloud/lib/private/AppFramework/App.php","line":126,"function":"dispatch","class":"OC\\AppFramework\\Http\\Dispatcher","type":"->","args":[{"__class__":"OCA\\Mail\\Controller\\FoldersController"},"sync"]},{"file":"/var/www/html/jcloud/lib/private/AppFramework/Routing/RouteActionHandler.php","line":47,"function":"main","class":"OC\\AppFramework\\App","type":"::","args":["OCA\\Mail\\Controller\\FoldersController","sync",{"__class__":"OC\\AppFramework\\DependencyInjection\\DIContainer"},{"accountId":"9","folderId":"SU5CT1g=","_route":"mail.folders.sync"}]},{"function":"__invoke","class":"OC\\AppFramework\\Routing\\RouteActionHandler","type":"->","args":[{"accountId":"9","folderId":"SU5CT1g=","_route":"mail.folders.sync"}]},{"file":"/var/www/html/jcloud/lib/private/Route/Router.php","line":297,"function":"call_user_func","args":[{"__class__":"OC\\AppFramework\\Routing\\RouteActionHandler"},{"accountId":"9","folderId":"SU5CT1g=","_route":"mail.folders.sync"}]},{"file":"/var/www/html/jcloud/lib/base.php","line":975,"function":"match","class":"OC\\Route\\Router","type":"->","args":["/apps/mail/api/accounts/9/folders/SU5CT1g%3D/sync"]},{"file":"/var/www/html/jcloud/index.php","line":42,"function":"handleRequest","class":"OC","type":"::","args":[]}],"File":"/var/www/html/jcloud/apps/mail/vendor/pear-pear.horde.org/Horde_Imap_Client/Horde/Imap/Client/Socket.php","Line":605,"CustomMessage":"--"},"userAgent":"Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:67.0) Gecko/20100101 Firefox/67.0","version":"16.0.3.0","id":"5d4851fc6e09d"}

**Comment by EM50L** [comment]
fail with ip [2603:1026:3:64::2]:imaps outlook.office365.com

**Comment by ChristophWurst** [comment]
isn't this a configuration problem of your server?
