### ISSUE TITLE
99% of mails no show pictures 

### ISSUE THREAD

**Issue by CHazz** [nextcloud/mail#1906]
### Expected behavior
Tell us what should happen

any mail with pictures

permission to view pictures from the sender does not work

### Actual behavior
Tell us what happens instead

### Mail app

**Mail app version:** (see apps admin page, e.g. 0.5.3)
 0.15.2
**Mailserver or service:** (e.g. Outlook, Yahoo, Gmail, Exchange,...)
 own 

### Server configuration

**Operating system**: (e.g. Debian 8)
ubuntu 16.04
**Web server:** (e.g. Apache, Nginx,...)
nginx
**Database:** (e.g. MariaDB, SQLite or PostgreSQL)
mariaDB
**PHP version:** (e.g. 7.0)
7.3
**Nextcloud Version:** (see admin page, e.g. 13.0.2)
16.0.3
#### Client configuration
**Browser:** (e.g. Firefox 48)
all
**Operating system:** (e.g. Arch Linux)
all

**Comment by ChristophWurst** [comment]
anything in the browser logs? are requests sent?

**Comment by JensKillermann** [comment]
Hi, same problem here. I used the edge developertools to see what happend.
After "show pictures" I've got many request to /apps/mail/proxy. But in my browser I can't see the pictures. If I copy one oft the https://xxxx/apps/mail/proxy?src=.... links into the adressfeld from the browser, I can see the picture.

I hope it helps. You can see details from the developertolls at the attachement.
![Unbenannt](https://user-images.githubusercontent.com/15939580/62757888-ffb0d200-ba7c-11e9-9881-31c7d7bbc483.png)
