### ISSUE TITLE
Lots of errors in log after update to Mail 0.15.2, remains also in mail 0.17.0

### ISSUE THREAD

**Issue by rollanders** [nextcloud/mail#1907]
### Steps to reproduce
Updated Mail
Got lots of errors in log - see below. Have not tested the Mail app and dont know if it works or not

### Expected behaviour
Should not be errors

### Actual behaviour
[PHP] Error: Cannot retrieve value of undefined directive Core.AllowParseManyTags invoked on line 72 in file /var/www/nextcloud/apps/mail/vendor/ezyang/htmlpurifier/library/HTMLPurifier/Lexer/DOMLex.php at /var/www/nextcloud/apps/mail/vendor/ezyang/htmlpurifier/library/HTMLPurifier/Config.php#901

## Server configuration detail

**Operating system:** Linux 4.15.0-50-generic #54-Ubuntu SMP Mon May 6 18:46:08 UTC 2019 x86_64

**Webserver:** nginx/1.15.9 (fpm-fcgi)

**Database:** mysql 10.3.15

**PHP version:** 

7.3.5-1+ubuntu18.04.1+deb.sury.org+1
Modules loaded: Core, date, libxml, openssl, pcre, zlib, filter, hash, Reflection, SPL, sodium, session, standard, cgi-fcgi, mysqlnd, PDO, xml, apcu, bz2, calendar, ctype, curl, dom, mbstring, fileinfo, ftp, gd, gettext, iconv, igbinary, imagick, intl, json, ldap, exif, mysqli, pdo_mysql, apc, posix, readline, redis, shmop, SimpleXML, sockets, sysvmsg, sysvsem, sysvshm, tokenizer, wddx, xmlreader, xmlwriter, xsl, zip, Phar, Zend OPcache

**Nextcloud version:** 16.0.3 - 16.0.3.0

**Updated from an older Nextcloud/ownCloud or fresh install:** 

**Where did you install Nextcloud from:** unknown

<details><summary>Signing status</summary>

Array
(
)

</details>

<details><summary>List of activated apps</summary>

```
Enabled:
 - activity: 2.9.1
 - admin_audit: 1.6.0
 - apporder: 0.7.1
 - calendar: 1.7.0
 - cloud_federation_api: 0.2.0
 - cms_pico: 0.9.8
 - comments: 1.6.0
 - contacts: 3.1.3
 - dav: 1.9.2
 - external: 3.3.0
 - federatedfilesharing: 1.6.0
 - files: 1.11.0
 - files_markdown: 2.0.6
 - files_pdfviewer: 1.5.0
 - files_readmemd: 1.1.1
 - files_rightclick: 0.13.0
 - files_sharing: 1.8.0
 - files_texteditor: 2.8.0
 - files_trashbin: 1.6.0
 - files_versions: 1.9.0
 - groupfolders: 4.0.4
 - issuetemplate: 0.5.0
 - logreader: 2.1.0
 - lookup_server_connector: 1.4.0
 - mail: 0.15.1 (rolled back to this) 
 - notes: 3.0.1
 - oauth2: 1.4.2
 - onlyoffice: 2.4.0
 - password_policy: 1.6.0
 - provisioning_api: 1.6.0
 - registration: 0.4.6
 - richdocuments: 3.3.14
 - sharebymail: 1.6.0
 - theming: 1.7.0
 - theming_customcss: 1.3.0
 - twofactor_backupcodes: 1.5.0
 - updatenotification: 1.6.0
 - workflowengine: 1.6.0
Disabled:
 - accessibility
 - announcementcenter
 - audioplayer
 - carnet
 - circles
 - encryption
 - federation
 - files_clipboard
 - files_external
 - files_videoplayer
 - firstrunwizard
 - gallery
 - group_everyone
 - nextcloud_announcements
 - notifications
 - polls
 - privacy
 - recommendations
 - serverinfo
 - support
 - survey_client
 - systemtags
 - user_ldap
 - viewer

```
</details>

<details><summary>Configuration (config/config.php)</summary>

```
{
    "passwordsalt": "***REMOVED SENSITIVE VALUE***",
    "secret": "***REMOVED SENSITIVE VALUE***",
    "trusted_domains": [
        "vmi259531.contaboserver.net",
        "korskyrkan-intra.se"
    ],
    "datadirectory": "***REMOVED SENSITIVE VALUE***",
    "dbtype": "mysql",
    "version": "16.0.3.0",
    "overwrite.cli.url": "https:\/\/korskyrkan-intra.se",
    "dbname": "***REMOVED SENSITIVE VALUE***",
    "dbhost": "***REMOVED SENSITIVE VALUE***",
    "dbport": "",
    "dbtableprefix": "oc_",
    "mysql.utf8mb4": true,
    "dbuser": "***REMOVED SENSITIVE VALUE***",
    "dbpassword": "***REMOVED SENSITIVE VALUE***",
    "installed": true,
    "instanceid": "***REMOVED SENSITIVE VALUE***",
    "activity_expire_days": 14,
    "auth.bruteforce.protection.enabled": true,
    "blacklisted_files": [
        ".htaccess",
        "Thumbs.db",
        "thumbs.db"
    ],
    "cron_log": true,
    "defaultapp": "apporder",
    "enable_previews": true,
    "enabledPreviewProviders": [
        "OC\\Preview\\PNG",
        "OC\\Preview\\JPEG",
        "OC\\Preview\\GIF",
        "OC\\Preview\\BMP",
        "OC\\Preview\\XBitmap",
        "OC\\Preview\\Movie",
        "OC\\Preview\\PDF",
        "OC\\Preview\\MP3",
        "OC\\Preview\\TXT",
        "OC\\Preview\\MarkDown"
    ],
    "filesystem_check_changes": 0,
    "filelocking.enabled": "true",
    "htaccess.RewriteBase": "\/",
    "integrity.check.disabled": false,
    "knowledgebaseenabled": false,
    "log_rotate_size": 104857600,
    "logfile": "\/var\/nc_data\/nextcloud.log",
    "logtimezone": "Europe\/Berlin",
    "memcache.local": "\\OC\\Memcache\\APCu",
    "memcache.locking": "\\OC\\Memcache\\Redis",
    "preview_max_x": 1024,
    "preview_max_y": 768,
    "preview_max_scale_factor": 1,
    "redis": {
        "host": "***REMOVED SENSITIVE VALUE***",
        "port": 0,
        "timeout": 0
    },
    "rewrite_url": true,
    "quota_include_external_storage": false,
    "share_folder": "\/Shares",
    "skeletondirectory": "",
    "trashbin_retention_obligation": "auto, 7",
    "mail_from_address": "***REMOVED SENSITIVE VALUE***",
    "mail_smtpmode": "smtp",
    "mail_sendmailmode": "smtp",
    "mail_domain": "***REMOVED SENSITIVE VALUE***",
    "mail_smtpauthtype": "PLAIN",
    "mail_smtpauth": 1,
    "mail_smtphost": "***REMOVED SENSITIVE VALUE***",
    "mail_smtpport": "587",
    "mail_smtpname": "***REMOVED SENSITIVE VALUE***",
    "mail_smtppassword": "***REMOVED SENSITIVE VALUE***",
    "maintenance": false,
    "theme": "",
    "loglevel": 2,
    "app_install_overwrite": [
        "files_clipboard",
        "files_reader"
    ],
    "has_rebuilt_cache": true
}
```
</details>

**Are you using external storage, if yes which one:** local/smb/sftp/...

**Are you using encryption:** 

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...

## Client configuration

**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/75.0.3770.142 Safari/537.36

**Operating system:** Windows 10 - updated

## Logs

<details><summary>Web server error log</summary>

```
Insert your web server log here 
```
</details>

<details><summary>Nextcloud log</summary>

```
I[PHP] Error: Cannot retrieve value of undefined directive Core.AllowParseManyTags invoked on line 72 in file /var/www/nextcloud/apps/mail/vendor/ezyang/htmlpurifier/library/HTMLPurifier/Lexer/DOMLex.php at /var/www/nextcloud/apps/mail/vendor/ezyang/htmlpurifier/library/HTMLPurifier/Config.php#901


```
</details>

<details><summary>Browser log</summary>

Insert your browser log here, this could for example include:

	a) The javascript console log
	b) The network log
	c) ...
</details>

### Expected behavior
Tell us what should happen

### Actual behavior
Tell us what happens instead

### Mail app

**Mail app version:** (see apps admin page, e.g. 0.5.3)

**Mailserver or service:** (e.g. Outlook, Yahoo, Gmail, Exchange,...)

### Server configuration

**Operating system**: (e.g. Debian 8)

**Web server:** (e.g. Apache, Nginx,...)

**Database:** (e.g. MariaDB, SQLite or PostgreSQL)

**PHP version:** (e.g. 7.0)

**Nextcloud Version:** (see admin page, e.g. 13.0.2)

#### Client configuration
**Browser:** (e.g. Firefox 48)

**Operating system:** (e.g. Arch Linux)

**Comment by ChristophWurst** [comment]
please check if those errors are coming from a specific message. the URL should tell you

**Comment by rollanders** [comment]
I restored the previous version from a snapshot, and updated and now no errors so far. I dont know what happened.

**Comment by rollanders** [comment]
When I look at the unformatted log I see a reference to an URL "/apps/mail/api/accounts/6/folders/SU5CT1g%3D/messages/461" but I do not have any api-folder under var/www/nextcloud/apps/mail/

**Comment by rollanders** [comment]
..but it seems you were right about an offending message. I found a HTML-coded message in a users mailbox. Tried to forward it before deleting but got an error 
[mail] Error: Horde_Mime_Exception: Error: need RCPT command at <<closure>>

 0. /var/www/nextcloud/apps/mail/vendor/pear-pear.horde.org/Horde_Mime/Horde/Mime/Mail.php line 479
    Horde_Mime_Part->send("", Horde_Mime_Headers {}, Horde_Mail_Trans ... "})
 1. /var/www/nextcloud/apps/mail/lib/Account.php line 214
    Horde_Mime_Mail->send(Horde_Mail_Trans ... "}, false, false)
 2. /var/www/nextcloud/apps/mail/lib/Service/MailTransmission.php line 117
    OCA\Mail\Account->sendMessage(OCA\Mail\Model\Message {}, Horde_Mail_Trans ... "}, null)
 3. /var/www/nextcloud/apps/mail/lib/Controller/AccountsController.php line 282
    OCA\Mail\Service\MailTransmission->sendMessage("NCadmin", OCA\Mail\Model\NewMessageData {}, OCA\Mail\Model\RepliedMessageData {}, null, null)
 4. /var/www/nextcloud/lib/private/AppFramework/Http/Dispatcher.php line 166
    OCA\Mail\Controller\AccountsController->send(6, "FWD: Office 2019 för endast 1299 kr!", "\n\n\"FixarIT.s ... .", "", "", "", null, null, null, [], null)
 5. /var/www/nextcloud/lib/private/AppFramework/Http/Dispatcher.php line 99
    OC\AppFramework\Http\Dispatcher->executeController(OCA\Mail\Controller\AccountsController {}, "send")
 6. /var/www/nextcloud/lib/private/AppFramework/App.php line 126
    OC\AppFramework\Http\Dispatcher->dispatch(OCA\Mail\Controller\AccountsController {}, "send")
 7. /var/www/nextcloud/lib/private/AppFramework/Routing/RouteActionHandler.php line 47
    OC\AppFramework\App::main("OCA\\Mail\\Cont ... r", "send", OC\AppFramework\ ... {}, {accountId: "6", ... "})
 8. <<closure>>
    OC\AppFramework\Routing\RouteActionHandler->__invoke({accountId: "6", ... "})
 9. /var/www/nextcloud/lib/private/Route/Router.php line 297
    undefinedundefinedcall_user_func(OC\AppFramework\ ... {}, {accountId: "6", ... "})
10. /var/www/nextcloud/lib/base.php line 975
    OC\Route\Router->match("/apps/mail/api/accounts/6/send")
11. /var/www/nextcloud/index.php line 42
    OC::handleRequest()

POST /apps/mail/api/accounts/6/send
from 94.254.30.246 by NCadmin at 2019-08-10T18:14:46+02:00

Have now deleted that message, restarted with a snapshot, updated, and now those errors are gone.

**Comment by rollanders** [comment]
Sorry. I was to fast. The errors remain. I have returned to the snapshot.

**Comment by rollanders** [comment]
Update to NC 16.0.4. Mail was updated at the same time. Once again I have lots of errors in the log. Mail works however, both ways. 

The errors now looks like this

{"reqId":"FgHaXwIF4cwY7BJH09cv","level":3,"time":"2019-08-15T21:29:56+02:00","remoteAddr":"xxxxxxx","user":"user","app":"PHP","method":"GET","url":"/apps/mail/api/accounts/1/folders/SU5CT1g%3D/messages/54","message":"Cannot retrieve value of undefined directive Core.AllowParseManyTags invoked on line 72 in file /var/www/nextcloud/apps/mail/vendor/ezyang/htmlpurifier/library/HTMLPurifier/Lexer/DOMLex.php at /var/www/nextcloud/apps/mail/vendor/ezyang/htmlpurifier/library/HTMLPurifier/Config.php#901","userAgent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/76.0.3809.100 Safari/537.36","version":"16.0.4.1","id":"5d55b2f96b7c9"}

**Comment by ChristophWurst** [comment]
So downgrading Nextcloud from 16.0.3 to 16.0.4 with the same Mail app and the same IMAP data fixed the problem?

**Comment by rollanders** [comment]
Yes. I have a snapshot based on 16.0.3 and mail lower than 0.15.2. Updating Mail cause the problem. 
I tried upgrade to NC 16.0.4 (which included updating mail) and got the error. I reversed to NC 16.0.3 and Mail 0.15.1 solved the issue. 
I know updated mail to 0.15.5 (still NC 16.0.3). I sent one mail . This time got only two of these errores in the log. 

{"reqId":"BhfMaAp4i9rYkzBRj6wq","level":3,"time":"2019-08-28T21:11:46+02:00","remoteAddr":"xx.xx.xx..xx.","user":"NCadmin","app":"PHP","method":"GET","url":"/apps/mail/api/accounts/1/folders/SU5CT1g%3D/messages/65","message":"Cannot retrieve value of undefined directive Core.AllowParseManyTags invoked on line 72 in file /var/www/nextcloud/apps/mail/vendor/ezyang/htmlpurifier/library/HTMLPurifier/Lexer/DOMLex.php at /var/www/nextcloud/apps/mail/vendor/ezyang/htmlpurifier/library/HTMLPurifier/Config.php#901","userAgent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/76.0.3809.100 Safari/537.36","version":"16.0.3.0","id":"5d66d44ee9d65"}

**Comment by rollanders** [comment]
Sending another e-mail (with å ä ö  in it. Got once again an errror. But now only one - before lots of them.

**Comment by rollanders** [comment]
Sent two other nails - one withhout scandinavian letters and otother with . No new errors.

**Comment by rollanders** [comment]
Upgraded to NC 16.0.4  Now many errors like this
{"reqId":"bZbVgKeYdi9GLTKjMAEu","level":3,"time":"2019-08-28T21:33:33+02:00","remoteAddr":"xxxxxxxxxxx","user":"NCadmin","app":"PHP","method":"GET","url":"/apps/cms_pico/pico/nyheter","message":"Cannot retrieve value of undefined directive Core.AllowParseManyTags invoked on line 72 in file /var/www/nextcloud/apps/mail/vendor/ezyang/htmlpurifier/library/HTMLPurifier/Lexer/DOMLex.php at /var/www/nextcloud/apps/mail/vendor/ezyang/htmlpurifier/library/HTMLPurifier/Config.php#901","userAgent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/76.0.3809.100 Safari/537.36","version":"16.0.4.1","id":"5d66d717f1a7f"}

I decided to roll back the snapshot

**Comment by ChristophWurst** [comment]
This could have to do with the recent update of the htmlpurifier https://github.com/nextcloud/mail/commit/5dec66d5a19015a18428e2da8067f038213dcfaa

**Comment by rollanders** [comment]
Same error with NC 16.0.3 and mail 0.16

This error 
{"reqId":"7nfKBpDfw0iQ060Kasdr","level":3,"time":"2019-08-30T10:43:09+02:00","remoteAddr":"xxxxxxxxxxx","user":"NCadmin","app":"PHP","method":"GET","url":"/apps/mail/api/accounts/6/folders/SU5CT1g%3D/messages/477/html","message":"Cannot retrieve value of undefined directive Core.AllowParseManyTags invoked on line 72 in file /var/www/nextcloud/apps/mail/vendor/ezyang/htmlpurifier/library/HTMLPurifier/Lexer/DOMLex.php at /var/www/nextcloud/apps/mail/vendor/ezyang/htmlpurifier/library/HTMLPurifier/Config.php#901","userAgent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/76.0.3809.100 Safari/537.36","version":"16.0.3.0","id":"5d68e21f89089"}

**Comment by ChristophWurst** [comment]
It's still the same version of htmlpurifier.

**Comment by rollanders** [comment]
Should I upgrade and not bother about the errors? Or wait for an new version of the htmlpurifier?

**Comment by ChristophWurst** [comment]
We'll upgrade once there is a newer version. But so far there hasn't been one. There is also the chance that this app uses the lib in an incorrect way but only newer versions are verbose about it. Someone has to dive into this.

**Comment by ChristophWurst** [comment]
Haven't seen this on my instances so far btw

**Comment by rollanders** [comment]
I  tried to update once again - same result. As a consequence I cannot update to NC 16.0.5 need to remain on 16.0.2. Or can I downgrade mail after updating the rest?

**Comment by rollanders** [comment]
Here is my current configuration that had the errors. I swapped back to the previous,

### Steps to reproduce
1. Update Mail
2. Check the log
3. Lots of errors. Mail works as expected


### Expected behaviour
1. Update Mail
2. Check log
3. No errors

### Actual behaviour
Lots of errors filling up. Mail works

{"reqId":"9koU4jUawZ81aECKLMqa","level":3,"time":"2019-09-30T23:34:16+02:00","remoteAddr":"173.249.32.218","user":"NCadmin","app":"PHP","method":"GET","url":"/apps/cms_pico/pico/nyheter","message":"Cannot retrieve value of undefined directive Core.AllowParseManyTags invoked on line 72 in file /var/www/nextcloud/apps/mail/vendor/ezyang/htmlpurifier/library/HTMLPurifier/Lexer/DOMLex.php at /var/www/nextcloud/apps/mail/vendor/ezyang/htmlpurifier/library/HTMLPurifier/Config.php#901","userAgent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/77.0.3865.90 Safari/537.36","version":"16.0.5.1","id":"5d9275281e6d8"}


## Server configuration detail

**Operating system:** Linux 4.15.0-50-generic #54-Ubuntu SMP Mon May 6 18:46:08 UTC 2019 x86_64

**Webserver:** nginx/1.15.9 (fpm-fcgi)

**Database:** mysql 10.3.15

**PHP version:** 

7.3.5-1+ubuntu18.04.1+deb.sury.org+1
Modules loaded: Core, date, libxml, openssl, pcre, zlib, filter, hash, Reflection, SPL, sodium, session, standard, cgi-fcgi, mysqlnd, PDO, xml, apcu, bz2, calendar, ctype, curl, dom, mbstring, fileinfo, ftp, gd, gettext, iconv, igbinary, imagick, intl, json, ldap, exif, mysqli, pdo_mysql, apc, posix, readline, redis, shmop, SimpleXML, sockets, sysvmsg, sysvsem, sysvshm, tokenizer, wddx, xmlreader, xmlwriter, xsl, zip, Phar, Zend OPcache

**Nextcloud version:** 16.0.5 - 16.0.5.1

**Updated from an older Nextcloud/ownCloud or fresh install:** 

**Where did you install Nextcloud from:** unknown

<details><summary>Signing status</summary>

Array
(
)

</details>

<details><summary>List of activated apps</summary>

```
Enabled:
 - activity: 2.9.1
 - admin_audit: 1.6.0
 - apporder: 0.7.1
 - calendar: 1.7.1
 - circles: 0.17.7
 - cloud_federation_api: 0.2.0
 - cms_pico: 0.9.8
 - comments: 1.6.0
 - contacts: 3.1.4
 - dav: 1.9.2
 - external: 3.3.0
 - federatedfilesharing: 1.6.0
 - files: 1.11.0
 - files_markdown: 2.1.0
 - files_pdfviewer: 1.5.0
 - files_rightclick: 0.15.1
 - files_sharing: 1.8.0
 - files_texteditor: 2.8.0
 - files_trashbin: 1.6.0
 - files_versions: 1.9.0
 - groupfolders: 4.1.3
 - issuetemplate: 0.5.0
 - logreader: 2.1.0
 - lookup_server_connector: 1.4.0
 - mail: 0.17.0
 - oauth2: 1.4.2
 - onlyoffice: 3.0.2
 - password_policy: 1.6.0
 - provisioning_api: 1.6.0
 - registration: 0.4.7
 - richdocuments: 3.4.2
 - sharebymail: 1.6.0
 - theming: 1.7.0
 - theming_customcss: 1.3.0
 - twofactor_backupcodes: 1.5.0
 - updatenotification: 1.6.0
 - workflowengine: 1.6.0
Disabled:
 - accessibility
 - announcementcenter
 - audioplayer
 - carnet
 - encryption
 - federation
 - files_clipboard
 - files_external
 - files_external_onedrive
 - files_readmemd
 - files_videoplayer
 - firstrunwizard
 - gallery
 - group_everyone
 - nextcloud_announcements
 - notes
 - notifications
 - polls
 - privacy
 - recommendations
 - serverinfo
 - support
 - survey_client
 - suspicious_login
 - systemtags
 - user_ldap
 - viewer

```
</details>

<details><summary>Configuration (config/config.php)</summary>

```
{
    "passwordsalt": "***REMOVED SENSITIVE VALUE***",
    "secret": "***REMOVED SENSITIVE VALUE***",
    "trusted_domains": [
        "vmi259531.contaboserver.net",
        "korskyrkan-intra.se"
    ],
    "datadirectory": "***REMOVED SENSITIVE VALUE***",
    "dbtype": "mysql",
    "version": "16.0.5.1",
    "overwrite.cli.url": "https:\/\/korskyrkan-intra.se",
    "dbname": "***REMOVED SENSITIVE VALUE***",
    "dbhost": "***REMOVED SENSITIVE VALUE***",
    "dbport": "",
    "dbtableprefix": "oc_",
    "mysql.utf8mb4": true,
    "dbuser": "***REMOVED SENSITIVE VALUE***",
    "dbpassword": "***REMOVED SENSITIVE VALUE***",
    "installed": true,
    "instanceid": "***REMOVED SENSITIVE VALUE***",
    "activity_expire_days": 14,
    "auth.bruteforce.protection.enabled": true,
    "blacklisted_files": [
        ".htaccess",
        "Thumbs.db",
        "thumbs.db"
    ],
    "cron_log": true,
    "defaultapp": "apporder",
    "enable_previews": true,
    "enabledPreviewProviders": [
        "OC\\Preview\\PNG",
        "OC\\Preview\\JPEG",
        "OC\\Preview\\GIF",
        "OC\\Preview\\BMP",
        "OC\\Preview\\XBitmap",
        "OC\\Preview\\Movie",
        "OC\\Preview\\PDF",
        "OC\\Preview\\MP3",
        "OC\\Preview\\TXT",
        "OC\\Preview\\MarkDown"
    ],
    "filesystem_check_changes": 0,
    "filelocking.enabled": "true",
    "htaccess.RewriteBase": "\/",
    "integrity.check.disabled": false,
    "knowledgebaseenabled": false,
    "log_rotate_size": 104857600,
    "logfile": "\/var\/nc_data\/nextcloud.log",
    "logtimezone": "Europe\/Berlin",
    "memcache.local": "\\OC\\Memcache\\APCu",
    "memcache.locking": "\\OC\\Memcache\\Redis",
    "preview_max_x": 1024,
    "preview_max_y": 768,
    "preview_max_scale_factor": 1,
    "redis": {
        "host": "***REMOVED SENSITIVE VALUE***",
        "port": 0,
        "timeout": 0
    },
    "rewrite_url": true,
    "quota_include_external_storage": false,
    "share_folder": "\/Shares",
    "skeletondirectory": "",
    "trashbin_retention_obligation": "auto, 7",
    "mail_from_address": "***REMOVED SENSITIVE VALUE***",
    "mail_smtpmode": "smtp",
    "mail_sendmailmode": "smtp",
    "mail_domain": "***REMOVED SENSITIVE VALUE***",
    "mail_smtpauthtype": "PLAIN",
    "mail_smtpauth": 1,
    "mail_smtphost": "***REMOVED SENSITIVE VALUE***",
    "mail_smtpport": "587",
    "mail_smtpname": "***REMOVED SENSITIVE VALUE***",
    "mail_smtppassword": "***REMOVED SENSITIVE VALUE***",
    "maintenance": false,
    "theme": "",
    "loglevel": 2,
    "app_install_overwrite": [
        "files_clipboard",
        "files_reader"
    ],
    "has_rebuilt_cache": true,
    "updater.secret": "***REMOVED SENSITIVE VALUE***"
}
```
</details>

**Are you using external storage, if yes which one:** local/smb/sftp/...

**Are you using encryption:** 

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...

## Client configuration

**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/77.0.3865.90 Safari/537.36

**Operating system:** Windows 10 - updated

## Logs

<details><summary>Web server error log</summary>

```
Insert your web server log here 
```
</details>

<details><summary>Nextcloud log</summary>

```
{"reqId":"9koU4jUawZ81aECKLMqa","level":3,"time":"2019-09-30T23:34:16+02:00","remoteAddr":"173.249.32.218","user":"NCadmin","app":"PHP","method":"GET","url":"/apps/cms_pico/pico/nyheter","message":"Cannot retrieve value of undefined directive Core.AllowParseManyTags invoked on line 72 in file /var/www/nextcloud/apps/mail/vendor/ezyang/htmlpurifier/library/HTMLPurifier/Lexer/DOMLex.php at /var/www/nextcloud/apps/mail/vendor/ezyang/htmlpurifier/library/HTMLPurifier/Config.php#901","userAgent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/77.0.3865.90 Safari/537.36","version":"16.0.5.1","id":"5d9275281e6d8"}
```
</details>

<details><summary>Browser log</summary>

Insert your browser log here, this could for example include:

	a) The javascript console log
	b) The network log
	c) ...
</details>

**Comment by ChristophWurst** [comment]
> cms_pico

Please disable that app and try again.

**Comment by ChristophWurst** [comment]
We might have run into a dependency hell https://github.com/nextcloud/cms_pico/blob/37354513985f195c9739875b8b0cea9e5eb764b5/composer.json#L14

**Comment by rollanders** [comment]
Yes. There it was. After deactivating PICOcms I could upgrade Mail with no errors, but when reactivating PICOcms the errors started again. But I have Pico_CMS 0.9.8 in my official setup. In an experimental setup with NC17 I have Pico_cms 1.0 and there is no problem. I will check how it works out if I upgrade PICO_cms on my official site.

**Comment by ChristophWurst** [comment]
Okay, good to hear you could resolve the problems. I think this is helpful to know for future reports.

However, we might run into the same problems again once there is another version mismatch between htmlpurifier in Mail and PicoCMS.
