### ISSUE TITLE
SSL only server (security?) issue. 

### ISSUE THREAD

**Issue by knutztar** [nextcloud/mail#191]
### Steps to reproduce
1. Added email account with succes.
2. Can fetch all folders
3. Try to open any HTML content email on SSL only server.

### Expected behaviour
I should be able to fetch my email content. 

### Actual behaviour
When trying to open an email containing HTML content the app, as you of cause know, embeds the mesasge in an iframe. But this iframe's "src" is always HTTP even when accessing my nextcloud server via HTTPS. My nextcloud server is not accessible via HTTP thus my HTML email content cannot be fetched (unless changing the address to https via Firebug or something similar)

### Mail app

**Mail app version:** (see apps admin page)
0.6.0

**Mailserver or service:** (e.g. Outlook, Yahoo, Gmail, Exchange,...)
kolabnow

**Transport security - IMAP:** (None, SSL, TLS, STARTTLS) 
SSL

**Transport security - SMTP:** (None, SSL, TLS, STARTTLS)
STARTTLS

**Number of accounts:**
1

**Mail app version build date:** (only if you are using a Nightly Build)

### Server configuration
**Operating system**:
Debian

**Web server:**
Apache

**Database:**
Mysql

**PHP version:**
5.6

**Version:** (see admin page)
Nextcloud 10.0.1

**Updated from an older version or fresh install:**
Fresh

**List of activated apps:**

```
 Activity 2.3.2
 Collaborative tags 1.0.2
Comments 1.0.0
 Deleted files 1.0.0
 Federation 1.0.1
File sharing 1.0.0
 First run wizard 1.1
Gallery 15.0.0
Notifications 0.3.0
Password policy 1.0.0
 PDF viewer 0.8.1
 Provisioning API 1.0.0
 Server info 1.1.1
Text editor 2.1
 Theming 1.0.1
Update notification 1.0.1
Usage report 0.1.5
 Versions 1.3.0
Video player 0.9.8
Documents 0.13.1
 Mail 0.6.0
```

**The content of config/config.php:**

```
<?php
$CONFIG = array (
  'instanceid' => '',
  'passwordsalt' => '',
  'secret' => '',
  'trusted_domains' =>
  array (
    0 => '192.168.137.219',
    1 => 'domain.dk',
  ),
  'datadirectory' => '/media/cloud/nextcloud0',
  'overwrite.cli.url' => 'http://192.168.137.219/nextcloud',
  'dbtype' => 'mysql',
  'version' => '9.1.1.5',
  'dbname' => 'nextcloud',
  'dbhost' => 'localhost',
  'dbport' => '',
  'dbtableprefix' => 'oc_',
  'dbuser' => 'nextcloud',
  'dbpassword' => '',
  'logtimezone' => 'UTC',
  'installed' => true,
  'mail_smtpmode' => 'php',
  'appstore.experimental.enabled' => true,
);
```

#### Client configuration
**Browser:**

**Operating system:**

##### Server log (data/nextcloud.log)
```
{"reqId":"rz5dCX9w1ojSnZsQIiTN","remoteAddr":"192.168.137.254","app":"core","message":"Login failed: 'skn' (Remote IP: '192.168.137.254')","level":2,"time":"2016-11-09T08:43:31+00:00","method":"POST","url":"\/nextcloud\/index.php\/login","user":"--"}
```

##### Horde IMAP log (data/horde_imap.log)
<details>
```
Insert your horde IMAP log here, see https://github.com/nextcloud/mail#debug-mode
```
</details>

##### Horde SMTP log (data/horde_smtp.log)
<details>
```
Insert your horde SMTP log here, see https://github.com/nextcloud/mail#debug-mode
```
</details>

##### Browser log

```
Content Security Policy: Sidens indstillinger blokerede for hentning af ressourcen på http://domain.dk/nextcloud/index.php/apps/mail/accounts/1/folders/SU5CT1g=/messages/1312/html ("frame-src https://domain.dk").
```

**Comment by ChristophWurst** [comment]
Please fill out the full issue template

**Comment by knutztar** [comment]
Filled in more information.
I've used firebug to check the javascript console and it seems that "Content Security Policy" is blocking the HTTP request.

**Comment by ChristophWurst** [comment]
> 'overwrite.cli.url' => 'http:///nextcloud',

Fix that url and then run ``sessionStorage.clear()`` and your browser. that should fix it.

**Comment by knutztar** [comment]
Sorry I should have been clear on that. The domain have been redacted.

**Comment by ChristophWurst** [comment]
> 'http://192.168.137.219/nextcloud'

is that the URL you access your nextcloud with or the internal address behind the proxy? Check your browser's network console, does it try to request the proxy when loading the message or your nextcloud installation directly?

**Comment by knutztar** [comment]
That is the internal address behind the proxy. 
I access my nextcloud via *https://domain.dk*. My browser (Firefox 49.0.2) block the iframe request (src="**http**://domain.dk/nextcloud/index.php/apps/mail/accounts/1/folders/SU5CT1g=/messages/1314/html").

**Comment by knutztar** [comment]
If I use Firbug to change the iframe src into src="**https**://domain.dk/nextcloud/ind..." the email content appears correctly.

**Comment by ChristophWurst** [comment]
Maybe you can try something like https://github.com/owncloudarchive/mail/issues/1504#issuecomment-226932413. The problems look similar.

**Comment by ChristophWurst** [comment]
See https://docs.nextcloud.com/server/10/admin_manual/configuration_server/config_sample_php_parameters.html#proxy-configurations

**Comment by knutztar** [comment]
Thanks @ChristophWurst! Adding the following to config.php fixed the issue for me.
```
'overwriteprotocol' => 'https',
```

**Comment by ChristophWurst** [comment]
Perfect :-)
