### ISSUE TITLE
Sometimes CSP forbids loading HTML message

### ISSUE THREAD

**Issue by okulev** [nextcloud/mail#193]
I have Nextcloud installation behind ssl proxy. The problem is that sometimes message iframe src urls use 'http' protocol scheme instead of 'https' and thus CSP forbids loading the message. (The rest of the url is OK.)

I tried to track down where these urls are generated but I have not used these specific frameworks.

Please help me where message iframe urls are generated so that I can find the cause. Or fix the bug yourself :-)

**Comment by ChristophWurst** [comment]
Hi,
this probably happens due to misconfiguration. See https://github.com/nextcloud/mail/issues/191#issuecomment-259692015 or the Nextcloud admin manual for instructions.

**Comment by okulev** [comment]
Thank you. I already had the parameters listed in the other issue but I did some changes to the config and it somehow started to work.
