### ISSUE TITLE
Screenshots missing in Nextcloud appstore entry

### ISSUE THREAD

**Issue by olantrust** [nextcloud/mail#194]
Currently there is no image present for the entry for this app, which doesn't look great, and an image (or better images) would help appstore users get a feel for what the app is.

**Comment by ChristophWurst** [comment]
There will be a screenshot in the next release https://github.com/nextcloud/mail/blob/73ffb64767739e606d972233dc352264e2c23c82/appinfo/info.xml#L22 😉
