### ISSUE TITLE
Can you translate forward button in your own language?

### ISSUE THREAD

**Issue by tigernero79** [nextcloud/mail#1943]
Can translate forward button in the language one has? 

example forward in Italian as button send already translated based on your language?

I attach button in English and one in Italian translated well in its own language.

forward= "Inoltrare" or "Rispondere"

![Immagine](https://user-images.githubusercontent.com/35575744/63763082-4c413d80-c8c4-11e9-92d0-23e7fa846500.png)

same problem for selection option and lists is empty I enclose second image

![Immagine2](https://user-images.githubusercontent.com/35575744/63763405-f3be7000-c8c4-11e9-8502-2d6264204bba.png)

**Comment by ChristophWurst** [comment]
Forward button is translatable since #1944, but will take some time for the translators to pick up the new string. The other one is caused by https://github.com/nextcloud/nextcloud-vue
