### ISSUE TITLE
menu opening icon above the first email icon in the mobile version

### ISSUE THREAD

**Issue by tigernero79** [nextcloud/mail#1957]
mail application in the mobile version from this annoying overlap of the 3 lines that make the menu open with the first readable email.  

I attach screenshot

![Screenshot_20190829-072543](https://user-images.githubusercontent.com/35575744/63912980-e1f8dc00-ca2e-11e9-9b25-7bf53d05005c.png)

**Comment by ChristophWurst** [comment]
Yes, this button is used to show the left sidebar.

Please use the bug template for bug reports next time. This makes it easier for us to triage and understand reports. THanks.
