### ISSUE TITLE
Name of a mail folder is displayed incorrectly

### ISSUE THREAD

**Issue by vzahradnik** [nextcloud/mail#1959]
### Expected behavior
When I add a new mail folder and name it "Internetové účty", it should be displayed exactly with these characters.

### Actual behavior
A folder is created, but its name is displayed incorrectly. See a screenshot.
![mail-incorrect-display-name](https://user-images.githubusercontent.com/4460766/63926168-ab7d8a00-ca4b-11e9-93d6-6710c5fdf855.png)

### Mail app

**Mail app version:** 0.15.5

**Mailserver or service:** Dovecot 2.3.7.2

### Server configuration

**Operating system**: Arch Linux

**Web server:** Nginx 1.16.1

**Database:** PostgreSQL 11.5

**PHP version:** 7.3.8

**Nextcloud Version:** 16.0.4

#### Client configuration
**Browser:** Firefox 68.0.2

**Operating system:** Arch Linux

**Comment by ChristophWurst** [comment]
Can confirm, just saw this today with an ü. It's possibly caused by base64 decoding the folder name and assuming it's utf8 while it might be utf7

**Comment by ChristophWurst** [comment]
Found it: the mailbox ID is utf8. Which we then encode base64. Then it's sent to the client, where we decode it. The problem is that the browser treats the string as ASCII, not utf8, hence the weird letters.

But no idea for a solution.

**Comment by ChristophWurst** [comment]
Found a fix https://github.com/nextcloud/mail/pull/2163 :)
