### ISSUE TITLE
Add a "refresh mailboxes" button

### ISSUE THREAD

**Issue by ChristophWurst** [nextcloud/mail#1962]
### Feature Request

Make it possible to force refresh the mailbox list

#### Summary

As of https://github.com/nextcloud/mail/pull/1956 we cache the list of mailboxes for performance reasons since they hardly change. For the rare case that the users adds/removes/changes a mailbox with another client it might make sense to offer a button for this in the account's action menu.

cc @rullzer

**Comment by szaimen** [comment]
Yes, that would be really nice since the "r" button is not really discoverable and would solve many issues after caching.

The button could sit on the right of the "New message" buton.

**Comment by ChristophWurst** [comment]
What you want is *refresh this mailbox* but I was talking about *refresh the list of mailboxes* :P

**Comment by szaimen** [comment]
ah oh, didn't know, that there is a difference :D
shall I open a new ticket for that one?

**Comment by ChristophWurst** [comment]
Yes please, especially since this needs design changes :)

**Comment by szaimen** [comment]
> Yes please, especially since this needs design changes :)

done 👍

**Comment by ChristophWurst** [comment]
Dup of https://github.com/nextcloud/mail/issues/4456
