### ISSUE TITLE
Upgrade to 0.16 stopped with sql error

### ISSUE THREAD

**Issue by martindiphoorn** [nextcloud/mail#1966]
### Expected behavior
Is should have update the module

### Actual behavior
It failed on an sql error

```sql
Set log level to debug
Turned on maintenance mode
Updating database schema
Updated database
Updating <mail> ...
Doctrine\DBAL\Exception\DriverException: An exception occurred while executing 'CREATE TABLE oc_mail_mailboxes (id VARCHAR(255) NOT NULL, account_id INT NOT NULL, sync_token VARCHAR(255) NOT NULL, attributes VARCHAR(255) DEFAULT '[]' NOT NULL, delimiter VARCHAR(1) NOT NULL, messages INT NOT NULL, unseen INT NOT NULL, selectable TINYINT(1) DEFAULT '1' NOT NULL, PRIMARY KEY(account_id, id)) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_bin ENGINE = InnoDB ROW_FORMAT = compressed':

SQLSTATE[42000]: Syntax error or access violation: 1071 Specified key was too long; max key length is 767 bytes
Update failed
Maintenance mode is kept active
Reset log level

```

### Mail app

**Mail app version:** 0.16 is displayed, but the install did not finish

**Mailserver or service:** IMAP

### Server configuration

**Operating system**: Ubuntu 18.04

**Web server:** Apache

**Database:** MariaDB

**PHP version:** 7.2.19

**Nextcloud Version:** 16.04

#### Client configuration
**Browser:** Firefox

**Operating system:** Linux

**Comment by ChristophWurst** [comment]
Hi,

sounds like your DB isn't configured properly. Please follow https://docs.nextcloud.com/server/stable/admin_manual/configuration_database/mysql_4byte_support.html and report back if that has helped.

Thanks.

**Comment by martindiphoorn** [comment]
Yes that fixed the issue. Thanks for the quick response!
