### ISSUE TITLE
Caching mails across NC accounts

### ISSUE THREAD

**Issue by plastikschnitzer** [nextcloud/mail#198]
### Steps to reproduce
1. Log in with NC user A and load mails
2. Log out
3. Log in with user B and go to the mail app

### Expected behaviour
User B should only see his mails

### Actual behaviour
User B sees the first mail from user A (I guess from cache). 

I consider this as little security issue if multiple users are using the same device.

### Mail app

**Mail app version:**

0.6.0

**Comment by ChristophWurst** [comment]
Well, that unfortunately happens if you log in right after logging out. We use *session storage* as a short-lived cache for messages. Since it has only a tiny gain in performance we can actually remove it.

**Comment by plastikschnitzer** [comment]
Typical case where this happens: You go to a colleagues desk to help and compare/look at it with another account... ;-)

**Comment by ChristophWurst** [comment]
Actually, I already removed that recently https://github.com/nextcloud/mail/pull/127 🙈
