### ISSUE TITLE
add new mailfolders [$50]

### ISSUE THREAD

**Issue by Happyfeet01** [nextcloud/mail#199]
is it possible to add the option to add new mailfolders to an account?
or is it already possible and i can´t find out how?

**Comment by ChristophWurst** [comment]
This is not possible yet. Pull requests are welcome :-)

**Comment by Happyfeet01** [comment]
okay, thanks for reply

**Comment by phsc** [comment]
Do the PRs #326 and #271 help with this issue?

**Comment by ChristophWurst** [comment]
> Do the PRs #326 and #271 help with this issue?

No, that would be a separate feature. Wanna help implement this? I can give you some pointers :)

**Comment by ChristophWurst** [comment]
- [ ] Mandatory refactoring: move all mailbox handling to the client (sorting, translation, hierarchy building)

**Comment by ChristophWurst** [comment]
FYI the PR is at https://github.com/nextcloud/mail/pull/1698 and this basically works. There might be a few edge cases that are not yet handled but I just created a folder and a subfolder.
