### ISSUE TITLE
Deleting an account does not redirect to setup page

### ISSUE THREAD

**Issue by skjnldsv** [nextcloud/mail#1990]
### Expected behavior
Deleting the last account did not redirected me somewhere else
Also I can still access the old account url and it doesn't load the setup page
https://xxxxx.xxx/apps/mail/#/accounts/0/folders/aW5ib3g=/message/1-SU5CT1g=-247

### Actual behavior
If no account configured, it should redirect to the setup page? Or show an error?

### Mail app

**Mail app version:** master

**Mailserver or service:** Outlook

### Server configuration

**Operating system**: I use Arch

**Web server:** Nginx

**Database:** MariaDB

**PHP version:** 7.2

**Nextcloud Version:** 17

#### Client configuration
**Browser:** Chromium 76

**Operating system:** still Arch

**Comment by ChristophWurst** [comment]
> **Operating system:** still Arch

:heart:

**Comment by ChristophWurst** [comment]
I fixed this like a month ago: #2161  :)
