### ISSUE TITLE
"No messages in this folder" and inbox doesn't work

### ISSUE THREAD

**Issue by robbieh** [nextcloud/mail#1995]
### Expected behavior
I would expect to see some messages.

### Actual behavior
I see the home icon and "Inbox" on the left, then "No messages in this folder" in the middle, and "All inboxes" on the right. But no actual messages or folders. 

If I click the Inbox's three dots, the pop-up just says "Loading..."

Strangely enough I can actually send email, though.

I think it's also important to note that Dovecot shows me logging in and out, as well as "Namespace inbox: type=private, prefix=, sep=, inbox=yes, hidden=no, list=yes, subscriptions=yes location=mbox:~/mail:INBOX=/var/mail/robbie"

I tried turning on Netxcloud debug mode, log level 0, and what I see when accessing the mail app is: "message":"no default config found".

When I try to re-save my current settings, I get three messages:
"Setting up manually configured account"
"Connecting to account [user@addr]"
"account created 1"

So...it seems like everything should be working.

### Mail app

**Mail app version:** 0.17.0

**Mailserver or service:** Private instance of Dovecot 2.2.27

### Server configuration

**Operating system**: Debian Stretch

**Web server:** Apache 2.4.25

**Database:** Maria 10.1.26

**PHP version:** 7.3

**Nextcloud Version:** 16.0.4

#### Client configuration
**Browser:** Firefox 48 and Chromium 76.0.3809.100

**Operating system:** Ubuntu Xenial

**Comment by ChristophWurst** [comment]
Do you have your folders as subfolders of INBOX? Then there might be a hidden triange under the INBOX house icon to expand.

**Comment by robbieh** [comment]
If there is a triangle, it is very well hidden :) I also noticed this morning that the account has an ( ! ) icon next to it. So I deleted and recreated it. Same behavior as before, including seeing the logins to Dovecot from mail server log. What else can I do to help debug?

![mailbug](https://user-images.githubusercontent.com/2595315/64347177-76c88000-cfc1-11e9-9e96-8c608b6c36ca.png)

**Comment by ChristophWurst** [comment]
Try adding some logging: https://github.com/nextcloud/mail/issues/1969#issuecomment-526588564

**Comment by robbieh** [comment]
I upgraded to 18.0.1. Same problem I migrated a new server. Same problem. Just an exclamation mark, but no errors I can work with.

I've been throwing debug statements all over, but don't know where I should be focusing. What does the exclamation point mean? What triggers it?

**Comment by robbieh** [comment]
In `apps/mail/vendor/pear-pear.horde.org/Horde_Imap_Client/Horde/Imap/Client/Socket.php` around the line beginning `throw new Horde_Imap_Client_Exception_ServerResponse`, I just took out the throw block. Everything seems to work fine now. I don't know what to make of that.
