### ISSUE TITLE
Log an object to console with Logger

### ISSUE THREAD

**Issue by nicolas-san** [nextcloud/mail#1999]
How can I log an Object to the console using Logger ?

I have tried:

 * Logger.debug(event)
 * Logger.debug('event: ', event)

But no luck so far

**Comment by ChristophWurst** [comment]
Context? Have you rebuilt the bundles?

**Comment by nicolas-san** [comment]
Sorry for the lack of context ... to deep in my code ^^
I try to work on the drag and drop, and I want to log the events triggered.

I have a dev branch, I have built with the make setup-dev and I build with the make command each time I modify something

I can log every message withe the logger:

`[DEBUG] mail: ##  DRAG START ## ` for example,
but when I just try to log the event, I am inside Home.vue, in a method, I have this in the console:

`[DEBUG] mail: [object Object]`
