### ISSUE TITLE
installation procedure composer and additional libraries needed

### ISSUE THREAD

**Issue by pafcioooo** [nextcloud/mail#200]
### Steps to reproduce
1. download mail app
2. go to apps in nexcloud 
3. enable mail app

### Expected behaviour
Application should be enabled

### Actual behaviour
Nextcloud applications error "this application makes server unstable"

### Mail app

**Mail app version:** 0.6.0

**Mailserver or service:** none

**Transport security - IMAP:** not applicable

**Transport security - SMTP:** not applicable

**Number of accounts:** not applicable

**Mail app version build date:** not applicable

### Server configuration
**Operating system**:
Ubuntu 16.04
**Web server:**
2.4.18
**Database:**
5.7.16
**PHP version:**
7
**Version:** (see admin page)
10.0.1
**Updated from an older version or fresh install:**
from owncloud 9.1
**List of activated apps:**
Enabled:
  - activity: 2.3.2
  - admin_audit: 1.0.0
  - calendar: 1.4.0
  - comments: 1.0.0
  - contacts: 1.4.0.0
  - dav: 1.0.1
  - direct_menu: 0.9.2
  - external: 1.2
  - federatedfilesharing: 1.0.1
  - federation: 1.0.1
  - files: 1.5.2
  - files_accesscontrol: 1.1.2
  - files_automatedtagging: 1.1.1
  - files_external: 1.0.2
  - files_mv: 0.8.2
  - files_pdfviewer: 0.8.1
  - files_sharing: 1.0.0
  - files_texteditor: 2.1
  - files_trashbin: 1.0.0
  - files_versions: 1.3.0
  - files_videoplayer: 0.9.8
  - mail: 0.6.0
  - notifications: 0.3.0
  - password_policy: 1.0.0
  - passwords: 20-beta6
  - provisioning_api: 1.0.0
  - richdocuments: 1.1.13
  - serverinfo: 1.1.1
  - survey_client: 0.1.5
  - systemtags: 1.0.2
  - templateeditor: 0.1
  - theming: 1.0.1
  - updatenotification: 1.0.1
  - user_external: 0.4
  - workflowengine: 1.0.1
Disabled:
  - audioplayer
  - bookmarks
  - encryption
  - files_retention
  - firstrunwizard
  - gallery
  - notes
  - rainloop
  - shorten
  - user_ldap

**The content of config/config.php:**
{
    "system": {
        "instanceid": "oc0iyzw01wxw",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "chmurka.wiicp.pl"
        ],
        "datadirectory": "\/home\/data\/Owncloud\/",
        "overwrite.cli.url": "http:\/\/chmurka.wiicp.pl",
        "dbtype": "mysql",
        "version": "9.1.1.5",
        "dbname": "chmurka",
        "dbhost": "localhost",
        "dbtableprefix": "oc_",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "logtimezone": "UTC",
        "installed": true,
        "mail_smtpmode": "smtp",
        "mail_smtpsecure": "tls",
        "loglevel": 2,
        "maintenance": false,
        "htaccess.RewriteBase": "\/",
        "mail_from_address": "info",
        "filelocking.enabled": true,
        "memcache.local": "\\OC\\Memcache\\APCu",
        "memcache.locking": "\\OC\\Memcache\\Redis",
        "redis": {
            "host": "\/var\/run\/redis\/redis.sock",
            "port": 0,
            "timeout": 0
        },
        "mail_domain": "wiicp.pl",
        "mail_smtpauthtype": "LOGIN",
        "mail_smtpauth": 1,
        "mail_smtphost": "wiicp.pl",
        "mail_smtpport": "587",
        "mail_smtpname": "***REMOVED SENSITIVE VALUE***",
        "mail_smtppassword": "***REMOVED SENSITIVE VALUE***",
        "updater.release.channel": "stable"
}
}
```
#### Client configuration
**Browser:** 
not applicable
**Operating system:**
not applicable
#### Logs
##### Web server error log
empty

##### Server log (data/nextcloud.log)
Exception: {"Exception":"Exception","Message":"Cannot include autoload. Did you run install dependencies using composer?","Code":0,"Trace":"#0 \/home\/chmurka.wiicp.pl\/public_html\/nextcloud\/lib\/private\/legacy\/app.php(195): require_once()\n#1 \/home\/chmurka.wiicp.pl\/public_html\/nextcloud\/lib\/private\/legacy\/app.php(153): OC_App::requireAppFile('mail')\n#2 \/home\/chmurka.wiicp.pl\/public_html\/nextcloud\/lib\/private\/legacy\/app.php(123): OC_App::loadApp('mail')\n#3 \/home\/chmurka.wiicp.pl\/public_html\/nextcloud\/lib\/base.php(967): OC_App::loadApps()\n#4 \/home\/chmurka.wiicp.pl\/public_html\/nextcloud\/index.php(48): OC::handleRequest()\n#5 {main}","File":"\/home\/chmurka.wiicp.pl\/public_html\/nextcloud\/apps\/mail\/appinfo\/app.php","Line":27}

##### Horde IMAP log (data/horde_imap.log)
not applicable

##### Horde SMTP log (data/horde_smtp.log)
not applicable

##### Browser log
not applicable

**Comment by pafcioooo** [comment]
To enable app:
1., one hast to install composer
# apt-get install composer

2. install required dependencies with composer (as application owner) in mail application directory
$ cd <application directory>/apps/mail
$  composer install --no-dev

3. Then one can go to application in nextcloud and successfully enable mail app

**Comment by ChristophWurst** [comment]
https://github.com/nextcloud/mail#developer-setup-info 😉
