### ISSUE TITLE
No Subfolders with Cyrus Server

### ISSUE THREAD

**Issue by ghost** [nextcloud/mail#2000]
### Question

Is there a special config I have to tweak to show subfolders with cyrus-imap Server?
(I see "open all folders" but nothing happens)

#### Summary

My cyrus-Server works with thunderbird/clawsmail/roundcube/squirrel but never worked with nextcloud-mailapp (since V14). That wasn't too important as all other clients work.
But now upgrading to 16 I really would like to find out, what is going wrong.
Could you give a hint maybe?

**Comment by ChristophWurst** [comment]
Do you know the raw mailbox IDs of your account? Does it use any prefixes?

**Comment by panspektrum** [comment]
The raw ID?
No prefixes. 
Personal namespace "INBOX."...

**Comment by ChristophWurst** [comment]
Okay, then "namespace" it is.

**Comment by brrrrrrrt** [comment]
very similar here, never got mail app working with our cyrus mailserver, subfolders are not nested but shown as "INBOX.Subfolder1.Subfolder2" and so on.

not sure if it helps, if i issue **LIST % %** i get the top level folders:
```
a LIST % %
* LIST (\HasChildren) "." INBOX
* LIST (\HasChildren) "." Projekte
```
"Projekte" is a shared Folder which is accessed by all users, it is not a namespace, the **NAMESPACE** command shows:
```
a NAMESPACE
* NAMESPACE (("INBOX." ".")) (("user." ".")) (("" "."))
```

if i issue **LIST \* \*** i get all folders like this:
```
a LIST * *
* LIST (\HasChildren) "." INBOX
* LIST (\HasChildren) "." INBOX.Archive
* LIST (\HasNoChildren) "." INBOX.Archive.2013
* LIST (\HasNoChildren) "." INBOX.Archive.2014
* LIST (\HasNoChildren) "." INBOX.Archive.2015
* LIST (\HasNoChildren) "." INBOX.Archive.2016
* LIST (\HasNoChildren) "." INBOX.Archive.2017
* LIST (\HasNoChildren) "." INBOX.Archive.2018
* LIST (\HasNoChildren) "." INBOX.Entwurf
* LIST (\HasNoChildren) "." INBOX.Gesendet
* LIST (\HasNoChildren) "." INBOX.Papierkorb
* LIST (\HasNoChildren) "." INBOX.Spam
* LIST (\HasNoChildren) "." INBOX.fail2ban
* LIST (\HasChildren) "." Projekte
* LIST (\HasChildren) "." "Projekte.01 - MSF"
* LIST (\HasNoChildren) "." "Projekte.01 - MSF.MSF-2018"
* LIST (\HasNoChildren) "." "Projekte.02 - SAMSUNG"
* LIST (\HasNoChildren) "." "Projekte.03 - MHS"
* LIST (\HasNoChildren) "." Projekte.034
```

**Comment by ChristophWurst** [comment]
Hm. Okay. Our current logic works like this: we check if all folders start with `INBOX.`, then we assume there is a prefix. But if you also have some mailboxes that that don't have it, it will show all `INBOX.` mailboxes as children of `INBOX`.

How do other IMAP clients handle this account?

**Comment by brrrrrrrt** [comment]
Gnome Evolution Mail:
![Bildschirmfoto von 2019-12-21 23-25-26](https://user-images.githubusercontent.com/4489013/71314528-25e27780-244a-11ea-96d6-e4d7c20d6a73.png)

Mozilla Thunderbird:
![Bildschirmfoto von 2019-12-21 23-29-03](https://user-images.githubusercontent.com/4489013/71314530-398dde00-244a-11ea-9a93-b28a1706cee4.png)

Outlook:
![Bildschirmfoto von 2019-12-21 23-31-14](https://user-images.githubusercontent.com/4489013/71314537-4b6f8100-244a-11ea-8ebf-6b9e43fb2ec8.png)

Roundcube:
![Bildschirmfoto von 2019-12-21 23-31-45](https://user-images.githubusercontent.com/4489013/71314540-53c7bc00-244a-11ea-9474-f69ae2f4d4b5.png)

Never hat problems with any mailclient so far, the structure is detected, everything works perfectly.

in thunderbird i had to set the Public (shared) namespace to "Projekte" to make it work:
![Bildschirmfoto von 2019-12-21 23-45-16](https://user-images.githubusercontent.com/4489013/71314675-06991980-244d-11ea-8004-6bf898b50dd7.png)

we have our Cyrus configured with `altnamespace: off` 

we could change this to on, that would allow us to specify a sharedprefix, i assume with this setting it would be possible to make thunderbird work out of the box, but 1) it is not needed, 2) this would change the folder structure for all the users folders which are now INBOX. prefixed -> a full resync on all mailclients. most of the mailboxes are 20-50GB, that won't be very funny for the users.

the structure Cyrus returns varies with this setting, you will find the full documentation here:
https://www.cyrusimap.org/imap/concepts/features/namespaces.html

altnamespace:off with a . separator:
```
INBOX
INBOX.folder-1
INBOX.folder-2 (etc)
user.spock (this is INBOX for “spock”)
user.spock.folder-x
user.kirk.folder-y (“kirk” hasn’t shared their INBOX)
commandcrew
```


altnamespace:on with a / separator:
```
INBOX (INBOX is special in IMAP and is always the users Inbox)
folder-1
folder-2 (etc)
Other Users/spock
Other Users/spock/folder-x
Other Users/kirk/folder-y
Shared Folders/commandcrew
```

**Comment by ChristophWurst** [comment]
Okay, thanks for the details. Guess I have to dig deeper on the specifications of that RFC and fix our logic.
