### ISSUE TITLE
Better handling of temporary server downtime or maintenance

### ISSUE THREAD

**Issue by ChristophWurst** [nextcloud/mail#2008]
I just updated an app on my instance. While waiting for the update to finish I checked my email and wondered why the Mail app does not respond.

### Expected behavior

The app should catch 503s and similar errors, wait a bit and retry. If the server does not respond we can still fall back to an error message, but the short downtime should not cause a problem.
At some point the app should also force a reload of the page as it could be the Mail app that was updated and thus the client-side app might not be compatible to the server APIs.

### Actual behavior

The app shows loading spinners that never vanish. It doesn't even do basic error handling.

### Mail app

**Mail app version:** master as of today

**Comment by rullzer** [comment]
> At some point the app should also force a reload of the page as it could be the Mail app that was updated and thus the client-side app might not be compatible to the server APIs.

Ah yes. The general issue. It would be good to have this general as well. Somehow an itnernal version number for the app or something. So that we could show a message 'You are not running the latest version of the app, please reload" or something

**Comment by ChristophWurst** [comment]
Done in https://github.com/nextcloud/nextcloud-axios/pull/510
