### ISSUE TITLE
Update failed - specified key too long

### ISSUE THREAD

**Issue by deusoz** [nextcloud/mail#2009]
I'm on NC 16.  After click "update" for Mail app, it failed and mail will no long open. 
This is detailed log:

Preparing update

Set log level to debug

Turned on maintenance mode

Repair step: Repair MySQL collation

Repair info: All tables already have the correct collation -> nothing to do

Repair step: Repair SQLite autoincrement

Repair step: Copy data from accounts table when migrating from ownCloud

Repair step: Drop account terms table when migrating from ownCloud

Updating database schema

Updated database

Doctrine\DBAL\Exception\DriverException: An exception occurred while executing 'CREATE TABLE oc_mail_mailboxes (id VARCHAR(255) NOT NULL, account_id INT NOT NULL, sync_token VARCHAR(255) NOT NULL, attributes VARCHAR(255) DEFAULT '[]' NOT NULL, delimiter VARCHAR(1) NOT NULL, messages INT NOT NULL, unseen INT NOT NULL, selectable TINYINT(1) DEFAULT '1' NOT NULL, PRIMARY KEY(account_id, id)) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_bin ENGINE = InnoDB ROW_FORMAT = compressed': SQLSTATE[42000]: Syntax error or access violation: 1071 Specified key was too long; max key length is 767 bytes

The update was unsuccessful. Please report this issue to the Nextcloud community.

**Comment by deusoz** [comment]
It actually broke my whole nextcloud installation.

**Comment by deusoz** [comment]
I'm going to try this... https://help.nextcloud.com/t/solved-syntax-error-or-access-violation-1071-specified-key-was-too-long-max-key-length-is-767-bytes/34740

**Comment by ChristophWurst** [comment]
Not a bug, you have to fix your setup: deprecated the `Event` class, use `Symfony\Contracts\EventDispatcher\Event` instead

**Comment by deusoz** [comment]
OK thanks Christoph.  Strangely for me, I had already set my db to barracuda, etc.  I had to upgrade to MariaDB 10.2 in order to get this upgrade to work. I'm on Centos 7.  We're all good now,, be well and MANY thanks for your efforts.
