### ISSUE TITLE
Database error after latest update

### ISSUE THREAD

**Issue by Venom0ne** [nextcloud/mail#2010]
After the latest app update I get database errors, despite the database being set up for extended keys. Completly removing the app and reinstalling reproduces the results. Second server runs perfectly fine without the update. Couldnt find anything on the issue elsewhere as this is exclusively for the Mail App and not for all of NextCloud.

An exception occurred while executing 'CREATE TABLE oc_mail_mailboxes (id INT AUTO_INCREMENT NOT NULL, name VARCHAR(255) NOT NULL, account_id INT NOT NULL, sync_token VARCHAR(255) DEFAULT NULL, attributes VARCHAR(255) DEFAULT '[]' NOT NULL, delimiter VARCHAR(1) NOT NULL, messages INT NOT NULL, unseen INT NOT NULL, selectable TINYINT(1) DEFAULT '1' NOT NULL, UNIQUE INDEX UNIQ_22DEBD839B6B5FBA5E237E06 (account_id, name), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_bin ENGINE = InnoDB ROW_FORMAT = compressed': SQLSTATE[42000]: Syntax error or access violation: 1071 Specified key was too long; max key length is 767 bytes

**Comment by nordcomputer** [comment]
Im still messing arround with this issue. Trying to actiate the app leads to this error:

`An exception occurred while executing 'CREATE TABLE oc_mail_mailboxes (id VARCHAR(255) NOT NULL, account_id INT NOT NULL, sync_token VARCHAR(255) NOT NULL, attributes VARCHAR(255) DEFAULT '[]' NOT NULL, delimiter VARCHAR(1) NOT NULL, messages INT NOT NULL, unseen INT NOT NULL, selectable TINYINT(1) DEFAULT '1' NOT NULL, PRIMARY KEY(account_id, id)) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_bin ENGINE = InnoDB ROW_FORMAT = compressed': SQLSTATE[HY000]: General error: 1709 Index column size too large. The maximum column size is 767 bytes.`

Nextcloud-Version: 16.05
mysql  Ver 14.14 Distrib 5.5.62
PHP 7.3.0 (Apache2)

**Comment by ChristophWurst** [comment]
I'm still convinced this can be solved by following https://docs.nextcloud.com/server/stable/admin_manual/configuration_database/mysql_4byte_support.html. That is how a lot of people resolved it.

**Comment by ChristophWurst** [comment]
> mysql Ver 14.14 Distrib 5.5.62

You might also want to update to a more recent version of MySQL or MariaDB.
