### ISSUE TITLE
Error on upgrade

### ISSUE THREAD

**Issue by Venom0ne** [nextcloud/mail#2012]
### Expected behavior
Upgrade Mail App without errors.

### Actual behavior
Upgrading Mail App leads to the following error:

`An exception occurred while executing 'CREATE TABLE oc_mail_mailboxes (id VARCHAR(255) NOT NULL, account_id INT NOT NULL, sync_token VARCHAR(255) NOT NULL, attributes VARCHAR(255) DEFAULT '[]' NOT NULL, delimiter VARCHAR(1) NOT NULL, messages INT NOT NULL, unseen INT NOT NULL, selectable TINYINT(1) DEFAULT '1' NOT NULL, PRIMARY KEY(account_id, id)) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_bin ENGINE = InnoDB ROW_FORMAT = compressed': SQLSTATE[42000]: Syntax error or access violation: 1071 Specified key was too long; max key length is 767 bytes`

### Mail app

**Mail app version:** 0.17.0

**Mailserver or service:** gmx.net

### Server configuration

**Operating system**: Ubuntu 18.04.3

**Web server:** Apache2

**Database:** MariaDB

**PHP version:** 7.2

**Nextcloud Version:** 16.0.4

#### Client configuration
**Browser:** Firefox 69.0

**Operating system:** Windows 10 / Ubuntu 18.04.3

## Additional Info
A quick google makes believe this would be a 4-byte issue commonly known in Nextcloud, yet the server was installed fresh with the 4-byte fix applied as per Nextcloud 16 guideline and no other errors with 4-byte related topics occur, not in the Nextcloud systemcheck, nor in any other app.
 
edit: forgot to mention, this is on a fresh server as well as an old one, both of which ran fine up until the update.

**Comment by nickvergessen** [comment]
It sounds like the step 2b from https://docs.nextcloud.com/server/16/admin_manual/configuration_database/mysql_4byte_support.html was not executed.
