### ISSUE TITLE
Show envelopes' recipient addresses when in a Send folder rather than sender.

### ISSUE THREAD

**Issue by StCyr** [nextcloud/mail#2019]
### Feature Request

In the envelopes list, the email address mentioned is always the sender. But, wouldn't it be nice to rather show the recipients addresses?

![image](https://user-images.githubusercontent.com/8179031/65244928-e5dac400-daeb-11e9-8365-51e2ff0e6d91.png)

#### Summary

1. Detect that we are showing the envelopes of a "sent" folder
2. Show recipients addresses (ellipsed when space is short) in such case.

**Comment by StCyr** [comment]
fixed by  #2020

**Comment by ChristophWurst** [comment]
If you add "Fixes #2019" to the PR description it closes the ticket automatically :)
