### ISSUE TITLE
Parent-Folders are not selectable, only expanding [non-existent] favorites-folder

### ISSUE THREAD

**Issue by jsielemann** [nextcloud/mail#2022]
I'm having dovecot as backend running.
When I try to click on the inbox of a mailaccount, it only expands a [non-existent] favorites-folder and the inbox is not clickable. All mails are shown in a global inbox.

**Comment by ChristophWurst** [comment]
Please see https://github.com/nextcloud/mail/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aopen+dovecot for existing tickets and use https://github.com/nextcloud/mail/issues/new?assignees=&labels=bug%2C+0.+to+triage&template=bug.md&title= if your problem is new. Thanks.

**Comment by PhieF** [comment]
same problem here, also with gmail

**Comment by ChristophWurst** [comment]
> Please see https://github.com/nextcloud/mail/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aopen+dovecot for existing tickets and use https://github.com/nextcloud/mail/issues/new?assignees=&labels=bug%2C+0.+to+triage&template=bug.md&title= if your problem is new. Thanks.
