### ISSUE TITLE
Auto-import of ICS invitations into the calendar

### ISSUE THREAD

**Issue by ulysse26** [nextcloud/mail#2026]
### Feature Request

Hello,
I'd love to have ICS attachments received in mails (event invitations) be directly imported in my calendar.  
Thx

#### Summary

In parameters options, one could specify :
- the calendar to be used (calDAV name)
- the attachments (ICS=yes - tickbox , ...)

**Comment by ulysse26** [comment]
Hi Christopher,
Check if this one can be groupped with #2524 ? Regards

**Comment by ChristophWurst** [comment]
how?

**Comment by jgonsior** [comment]
I guess implementing #2823 makes this issue obsolete?

**Comment by ChristophWurst** [comment]
Good point. I would actually favor that over custom routines (and the settings options that come with that) in this app :+1:

**Comment by stylefieber** [comment]
This feature is important in my eyes. Currently, if you get an answer for an invitation for example from googlemail, then the appointment is not updated. Thunderbird, Outlook and em Client can do this by connecting a calendar with a mail-account.
Without this feature mail and calendar are just two separated apps without using the advantage being in the same eco system.

**Comment by ChristophWurst** [comment]
This ticket was purely about an auto import of ICS. What you are looking for is https://github.com/nextcloud/mail/issues/160, I think.
