### ISSUE TITLE
problem with "new mail" notifications

### ISSUE THREAD

**Issue by StCyr** [nextcloud/mail#2027]
### Expected behavior

I'm working on implementing a drag&drop functionality for classifying emails.

When I reload my page and go a little bit too fast with testing my changes, a "new mail" notification window may appear while I'm busy dragging an envelope. 

This shouldn't have any effect on the D&D experience.

### Actual behavior

In such case though, drag&drop stops functioning: I can't start draggin any envelope anymore until I **completly restart my browser**.

Also, the following debug message pops up in the js console: 

`[DEBUG] mail: browser is active. notification request is ignored`

### Mail app

master branch

### Server configuration

**Operating system**: Debian 10

**Web server:** Apache

**Database:** MariaDB

**PHP version:** 7.3

**Nextcloud Version:** 16.0.4.1

#### Client configuration

**Browser:** FF 69.0.1

**Operating system:** Windows 10

**Comment by ChristophWurst** [comment]
> Also, the following debug message pops up in the js console:

This just indicates that a new message was fetched in the background and the notification is suppressed -> unrelated

**Comment by ChristophWurst** [comment]
> When I reload my page and go a little bit too fast with testing my changes, a "new mail" notification window may appear while I'm busy dragging an envelope.

Do you mean like a desktop notification? Or just the message being added to the list?

**Comment by StCyr** [comment]
> 
> 
> > When I reload my page and go a little bit too fast with testing my changes, a "new mail" notification window may appear while I'm busy dragging an envelope.
> 
> Do you mean like a desktop notification? Or just the message being added to the list?

I don't exatcly know what causes my D&D functionality to fail until I restart my browser, but, yes, I see a "new mail" desktop notification just before it starts failing.

PS: Do you have an IRC channel where we can discuss more easily?

**Comment by ChristophWurst** [comment]
> I don't exatcly know what causes my D&D functionality to fail until I restart my browser, but, yes, I see a "new mail" desktop notification just before it starts failing.

Guess the notification then removes focus from the browser window and thus the drag/drop evens stop? Could that be the case?

The app should not show you a notification when the document is active. With that line in the logs it's even more weird that you see one.

> PS: Do you have an IRC channel where we can discuss more easily?

Nope, stopped using IRC as there were too many channels to be active on. We can discuss here.

**Comment by StCyr** [comment]
yes, let's close it
