### ISSUE TITLE
TypeError: Argument 2 passed to OCA\Mail\Http\AttachmentDownloadResponse::__construct() must be of the type string, null given

### ISSUE THREAD

**Issue by yafp** [nextcloud/mail#2029]
### Expected behavior
Selecting a single mail-account does show the settings of this account, but gives no access to the actual mails

### Actual behavior
I have no option to see the content of an individual mail account.
only the unified inbox is working for me.

I get the following output in the logs
```

[index] Error: TypeError: Argument 2 passed to OCA\Mail\Http\AttachmentDownloadResponse::__construct() must be of the type string, null given, called in /www/htdocs/xyz/mynextcloud/apps/mail/lib/Controller/MessagesController.php on line 257 at <<closure>>

0. /www/htdocs/xyz/mynextcloud/apps/mail/lib/Controller/MessagesController.php line 257
   OCA\Mail\Http\AttachmentDownloadResponse->__construct("This is a multi ... n", null, "application/octet-stream")
1. /www/htdocs/xyz/mynextcloud/lib/private/AppFramework/Http/Dispatcher.php line 166
   OCA\Mail\Controller\MessagesController->downloadAttachment(2, "SU5CT1g=", 7700, 1)
2. /www/htdocs/xyz/mynextcloud/lib/private/AppFramework/Http/Dispatcher.php line 99
   OC\AppFramework\Http\Dispatcher->executeController(OCA\Mail\Controller\MessagesController {}, "downloadAttachment")
3. /www/htdocs/xyz/mynextcloud/lib/private/AppFramework/App.php line 126
   OC\AppFramework\Http\Dispatcher->dispatch(OCA\Mail\Controller\MessagesController {}, "downloadAttachment")
4. /www/htdocs/xyz/mynextcloud/lib/private/AppFramework/Routing/RouteActionHandler.php line 47
   OC\AppFramework\App::main("OCA\\Mail\\Cont ... r", "downloadAttachment", OC\AppFramework\ ... {}, {accountId: "2", ... "})
5. <<closure>>
   OC\AppFramework\Routing\RouteActionHandler->__invoke({accountId: "2", ... "})
6. /www/htdocs/xyz/mynextcloud/lib/private/Route/Router.php line 297
   undefinedundefinedcall_user_func(OC\AppFramework\ ... {}, {accountId: "2", ... "})
7. /www/htdocs/xyz/mynextcloud/lib/base.php line 975
   OC\Route\Router->match("/apps/mail/api/ ... 1")
8. /www/htdocs/xyz/mynextcloud/index.php line 42
   OC::handleRequest()

GET /index.php/apps/mail/api/accounts/2/folders/SU5CT1g=/messages/7700/attachment/1
from 217.7.201.17 by fidel at 2019-09-19T12:03:00+00:00
```

### Mail app

**Mail app version:** 0.17.0

**Mailserver or service:** 
* several mailservers

### Server configuration

**Operating system**: (e.g. Debian 8)

**Web server:** (e.g. Apache, Nginx,...)

**Database:** MySQL

**PHP version:**  7

**Nextcloud Version:**  16.0.1

#### Client configuration
** Firefox 69.0

**Operating system:** 
* Arch Linux
* Ubuntu 18.04

**Comment by ChristophWurst** [comment]
Dup of https://github.com/nextcloud/mail/issues/1738

**Comment by yafp** [comment]
Sorry, i haven't seen the other issue.

One question is still open:
Is my problem that i can't select single mail-accounts related to this attachment problem? Or should i open another issue focusing only on this specific problem?


Problem:
If i do select a single mail-account or its inbox (in the sidebar) i always end up in the configuration view of this mail account, but never see the actual content of the account/folder/inbox.

**Comment by ChristophWurst** [comment]
> If i do select a single mail-account or its inbox (in the sidebar) i always end up in the configuration view of this mail account, but never see the actual content of the account/folder/inbox.

If you click the account (email) then this is expected. But not for the inbox -> please file a new ticket for that.
