### ISSUE TITLE
Local folder has no envelopes, cannot determine cursor 

### ISSUE THREAD

**Issue by Zefling** [nextcloud/mail#2030]
### Question

Yesterday my mailbox works, today I have this message in the console: 
_Local folder has no envelopes, cannot determine cursor_ 
Now, I have this symbol ![image](https://user-images.githubusercontent.com/3032555/65671144-00122600-e047-11e9-96a9-4ca804bccc43.png) on the left of my mail address.
Renew password and config does not work. 
I have 2 others addresses on the same server without this problem.

What should I change to correct this?

**Comment by ChristophWurst** [comment]
> What should I change to correct this?

Follow the issue reporting guidelines https://github.com/nextcloud/mail/issues/new?assignees=&labels=bug%2C+0.+to+triage&template=bug.md&title=
