### ISSUE TITLE
Remove \OCA\Mail\Account::createMailbox

### ISSUE THREAD

**Issue by ChristophWurst** [nextcloud/mail#2031]
It's only used for testing. It should die.

This will help remove  `\OCA\Mail\Account::getMailbox`

**Comment by yihyang** [comment]
HI @ChristophWurst I would like to take this up.
Can I confirm the task is to remove https://github.com/nextcloud/mail/blob/master/lib/Account.php#L154-L164 along with all of it's references?

Thanks.

**Comment by ChristophWurst** [comment]
Yep, there should only be one usage: tests. But we should be able to directly use the Horde libraries to create the test mailbox
![Bildschirmfoto von 2019-09-30 19-09-49](https://user-images.githubusercontent.com/1374172/65900307-02151580-e3b6-11e9-9aa3-1984d988f6ab.png)

Hint: something like `$mailbox = $this->getTestAccount()->getImapConnection()->createMailbox(.....)` could work
