### ISSUE TITLE
Possibility to add a task from a mail

### ISSUE THREAD

**Issue by jakobroehrl** [nextcloud/mail#2034]
### Feature Request

If the Tasks App is enabled, the option would be nice to add a new Task from an email.
With Subject, first x lines of the Body and maybe the link to the mail.

#### Summary

Function to add a new Task from a mail

**Comment by ChristophWurst** [comment]
FYI the issue templates are there for a reason and shall not be ignored: https://github.com/nextcloud/mail/issues/new?assignees=&labels=enhancement%2C+0.+to+triage&template=feature_request.md&title=

**Comment by ChristophWurst** [comment]
https://github.com/nextcloud/mail/blob/master/.github/CONTRIBUTING.md#submitting-issues

**Comment by jakobroehrl** [comment]
@ChristophWurst Sorry, updated it.

**Comment by David100mark** [comment]
I would really love this feature!
We mostly use the deck-app in our organisation, so maybe you could aswell add the option to add it to a board.

**Comment by ChristophWurst** [comment]
As far as I know there are some unification efforts going on to combine what Tasks and Deck do

**Comment by ilippert** [comment]
@jakobroehrl  

if I may, I would suggest to slightly alter the feature request:
from
> With Subject, first x lines of the Body and maybe the link to the mail.

to

Select/mark a text segment of an email, then click a button to generate task, using subject line for task name, the marked text segment for the task's details and add a link to the email.

**Comment by ChristophWurst** [comment]
I'd say the first implementation can be a bit simplistic with an automated way of picking the data, in the second iteration we can refine this and offer a dialogue.

@ilippert would you be interested in learning more about how to contribute code to Nextcloud Mail?

**Comment by ilippert** [comment]
Thanks @ChristophWurst for asking. Definitively would love to learn - but maybe after I give up on my current career as a social scientist. But do let me know if I can be of help with my expertise as somebody who can design research projects on the use of and reading/writing of emails in everyday life.

**Comment by ChristophWurst** [comment]
let's continue in https://github.com/nextcloud/mail/issues/3064
