### ISSUE TITLE
Possibility to choose special folders role for existing folders

### ISSUE THREAD

**Issue by getriebesand** [nextcloud/mail#2035]
### Feature Request

I have an existing account with folders for sent, draft and trash. But the names are different. Wenn I add this account to nextcloud, nextcloud mail creates new special folders and didn't use the existing folders.

#### Summary

It would be nice if I can give existing folders a special folder role.

**Comment by ChristophWurst** [comment]
Makes sense.

Please use the issue template next time.

**Comment by CATER-COM** [comment]
+1
It's a very important feature as IMAP account are often used with various client. Actualy when I send a message with Mail app the sent message don't go in the same folder as the one in Thunderbird or from my phone

**Comment by ChristophWurst** [comment]
PR is done and waiting for testers and reviewers: https://github.com/nextcloud/mail/pull/3820
