### ISSUE TITLE
Problem downloading Images in Mails

### ISSUE THREAD

**Issue by bd8392** [nextcloud/mail#2041]
### Expected behavior
Pictures in Mail are downloaded

### Actual behavior
Pictures in mail are **NOT** downloaded, even on klick.

### Mail app

**Mail app version:** (see apps admin page, e.g. 0.5.3)
0.17.0

**Mailserver or service:** (e.g. Outlook, Yahoo, Gmail, Exchange,...)
all

### Server configuration

**Operating system**: (e.g. Debian 8)
Docker

**Web server:** (e.g. Apache, Nginx,...)
Docker

**Database:** (e.g. MariaDB, SQLite or PostgreSQL)
MariaDB

**PHP version:** (e.g. 7.0)
Docker

**Nextcloud Version:** (see admin page, e.g. 13.0.2)
17.0

#### Client configuration
**Browser:** (e.g. Firefox 48)
all

**Operating system:** (e.g. Arch Linux)
windows

**Comment by ChristophWurst** [comment]
Dup of https://github.com/nextcloud/mail/issues/1734?
