### ISSUE TITLE
Automatically setup imap stuff when a new user is added

### ISSUE THREAD

**Issue by benclarkk** [nextcloud/mail#2049]
### Feature Request

When you add an account on nextcloud, if their email on their account is from a specific domain it should automatically populate their imap settings. this is handy for people who use nextcloud for their business who use their own imap servers.

#### Summary

when i add an account, it should look at their email, and if their email is from a doman (such as example.com) it should setup their email automatically so when they open up mail for the first time, they'll see their account already there.

**Comment by ChristophWurst** [comment]
https://github.com/nextcloud/mail/blob/master/doc/admin.md#automatic-account-creation :)
