### ISSUE TITLE
Be able to "unread" an email after reading it. [$10]

### ISSUE THREAD

**Issue by pierreozoux** [nextcloud/mail#205]
Some people like to filter their messages this way.

**Comment by ChristophWurst** [comment]
That is possible via the 'u' shortcut already, but we are still lacking a button for that action.

**Comment by pierreozoux** [comment]
Amazing thanks :)

**Comment by ChristophWurst** [comment]
@lcalaresu FYI once you've got your setup up and running again, this might be interesting for you. All it needs is a popover menu on the message in the message list. The server-side functionality is all there already, you just have to wire it up :)

**Comment by kevgathuku** [comment]
Hi @ChristophWurst
Not sure if anyone is working on this but I would like to pick up this task.

**Comment by rullzer** [comment]
Go for it @kevgathuku :rocket:

**Comment by danger89** [comment]
@ChristophWurst Thanks. Maybe good to put a link to the docs in the main while: https://github.com/nextcloud/mail/blob/master/doc/user.md

**Comment by kevgathuku** [comment]
Going to go for this style of dropdown menu in order to add the `mark as unread` action
<img width="192" alt="screen shot 2018-07-15 at 20 40 02" src="https://user-images.githubusercontent.com/3721994/42736433-99d249a4-886f-11e8-9e76-159c5ddc0282.png">

**Comment by danger89** [comment]
Love it..!

**Comment by kevgathuku** [comment]
I've submitted a fix for this over at #973
