### ISSUE TITLE
IMAP sync not working; Undefined index: H

### ISSUE THREAD

**Issue by ExternalDatabase** [nextcloud/mail#2065]
**Expected behavior**
1. Mail app should be able to send e-mails.
2. Mail app should be able to **sync** folders with remote server.

**Actual behavior**
1. I get an error message: "[...] TypeError: this is undefined" with 2 buttons "Back" and "Retry".
When I'm trying to retry - nothing happens (same error after page blink).
2. Mail app can download messages from Inbox folder from both accounts, BUT cannot sync with server that messages have been read.
It's not able to save drafts too.

**Mail app**
Mail app version: 0.17.0
Mailserver or service: zoho.eu

**Server configuration**
Operating system: Ubuntu 18.04.3 LTS
Web server: Apache/2.4.29
Database: mysql 5.7.27
PHP version: 7.2.19
Nextcloud Version: 16.0.5.1

**Client configuration**
Browser: Firefox 69, Chrome, Chromium
Operating system: Fedora 30 x64, Windows 10
(all software up-to-date)

**Comment by ExternalDatabase** [comment]
Mostly repetitive info from logs:
_Undefined index: H at /var/www/nextcloud/apps/mail/vendor/pear-pear.horde.org/Horde_Imap_Client/Horde/Imap/Client/Data/Sync.php#209

**Comment by ExternalDatabase** [comment]
[mail] Error: OCA\Mail\Exception\ServiceException: Could not save draft message at <<closure>>

0. /var/www/nextcloud/apps/mail/lib/Controller/AccountsController.php line 314
   OCA\Mail\Service\MailTransmission->saveDraft(OCA\Mail\Model\NewMessageData {}, null)
1. /var/www/nextcloud/lib/private/AppFramework/Http/Dispatcher.php line 166
   OCA\Mail\Controller\AccountsController->draft(1, "CENSORED", "", "CENSORED", "", "", null)
2. /var/www/nextcloud/lib/private/AppFramework/Http/Dispatcher.php line 99
   OC\AppFramework\Http\Dispatcher->executeController(OCA\Mail\Controller\AccountsController {}, "draft")
3. /var/www/nextcloud/lib/private/AppFramework/App.php line 126
   OC\AppFramework\Http\Dispatcher->dispatch(OCA\Mail\Controller\AccountsController {}, "draft")
4. /var/www/nextcloud/lib/private/AppFramework/Routing/RouteActionHandler.php line 47
   OC\AppFramework\App::main("OCA\\Mail\\Cont ... r", "draft", OC\AppFramework\ ... {}, {accountId: "1", ... "})
5. <<closure>>
   OC\AppFramework\Routing\RouteActionHandler->__invoke({accountId: "1", ... "})
6. /var/www/nextcloud/lib/private/Route/Router.php line 297
   undefinedundefinedcall_user_func(OC\AppFramework\ ... {}, {accountId: "1", ... "})
7. /var/www/nextcloud/lib/base.php line 975
   OC\Route\Router->match("/apps/mail/api/accounts/1/draft")
8. /var/www/nextcloud/index.php line 42
   OC::handleRequest()
POST /index.php/apps/mail/api/accounts/1/draft

[mail] Fatal: Saving draft failed: Could not save draft message
POST /index.php/apps/mail/api/accounts/1/draft

**Comment by ChristophWurst** [comment]
anything informative in your imap logs?

**Comment by ExternalDatabase** [comment]
I use app-specific passwords in that mail server and there are no errors/warnings for this account or appID.
I'm wondering what causes PHP errors mentioned above (_Undefined index: H_)...
And I don't know if you noticed: I'm using 2 accounts in your Mail app - maybe that's the problem with server syncing.

**Comment by ChristophWurst** [comment]
The Nextcloud mail app offers an extensive logging system to make it easier identifying and tracking down bugs. Please enable [debug mode](https://docs.nextcloud.com/server/13/developer_manual/general/devenv.html#enabling-debug-mode) and set the log [level to debug](https://docs.nextcloud.com/server/13/admin_manual/configuration_server/logging_configuration.html) in your admin settings. Then, try to reproduce your issue and take another look at `data/nextcloud.log`, `data/horde_imap.log` and `data/horde_smtp.log`.
