### ISSUE TITLE
Sending not working to groups and new users

### ISSUE THREAD

**Issue by wdfee** [nextcloud/mail#2066]
### Expected behavior
1. When typing an existing user into the "To" field, it should autocomplete the username.
2. When typing a group name into the "To" field, it should autocomplete the group name. When clicking the "send" button, it should send this mail to all users of this group.

### Actual behavior
1. The autosuggestion only works for users, who are already registered for some time. Autosuggestion does not work for new users, who were added today (and already logged in).
2. The autosuggestion for group names is working. But on sending, it breaks with error:
Error: Request failed with status code 500
(Sending to single users is working.)

### Mail app

**Mail app version:** 0.17.0

**Mailserver or service:** ionos + hosteurope

### Server configuration

**Operating system**: Ubuntu 18.0.4

**Web server:** Nginx

**Database:** MariaDB

**PHP version:** 7.3

**Nextcloud Version:** 16.0.4 + 16.0.5

#### Client configuration
**Browser:** Firefox 69.0.1

**Operating system:** Mac OS 10.14.6

**Comment by wdfee** [comment]
ok
1. solved: in the settings "sharing" section I had to to untick "Allow username autocompletion in share dialog. If this is disabled the full username or email address needs to be entered." and then reactivate this option again. Now the new users are found by autosuggestion.

**Comment by wdfee** [comment]
2. log entries for failed sending:

[mail] Fatal: Sending mail failed: valid RCPT command must precede DATA
POST /index.php/apps/mail/api/accounts/4/send
from *** by *** at 2019-10-02T23:20:31+02:00

[mail] Error: Horde_Mime_Exception: valid RCPT command must precede DATA at <<closure>>

 0. /var/www/vhosts/[domain]/httpdocs/apps/mail/vendor/pear-pear.horde.org/Horde_Mime/Horde/Mime/Mail.php line 479
    Horde_Mime_Part->send("", Horde_Mime_Headers {}, Horde_Mail_Trans ... "})
 1. /var/www/vhosts/[domain]/httpdocs/apps/mail/lib/Account.php line 214
    Horde_Mime_Mail->send(Horde_Mail_Trans ... "}, false, false)
 2. /var/www/vhosts/[domain]/httpdocs/apps/mail/lib/Service/MailTransmission.php line 117
    OCA\Mail\Account->sendMessage(OCA\Mail\Model\Message {}, Horde_Mail_Trans ... "}, 105)
 3. /var/www/vhosts/[domain]/httpdocs/apps/mail/lib/Controller/AccountsController.php line 282
    OCA\Mail\Service\MailTransmission->sendMessage("***", OCA\Mail\Model\NewMessageData {}, OCA\Mail\Model\RepliedMessageData {}, null, 105)
 4. /var/www/vhosts/[domain]/httpdocs/lib/private/AppFramework/Http/Dispatcher.php line 166
    OCA\Mail\Controller\AccountsController->send(4, "***", "***", "\"Testgroup ... >", "", "", 105, null, null, [], null)
 5. /var/www/vhosts/[domain]/httpdocs/lib/private/AppFramework/Http/Dispatcher.php line 99
    OC\AppFramework\Http\Dispatcher->executeController(OCA\Mail\Controller\AccountsController {}, "send")
 6. /var/www/vhosts/[domain]/httpdocs/lib/private/AppFramework/App.php line 126
    OC\AppFramework\Http\Dispatcher->dispatch(OCA\Mail\Controller\AccountsController {}, "send")
 7. /var/www/vhosts/[domain]/httpdocs/lib/private/AppFramework/Routing/RouteActionHandler.php line 47
    OC\AppFramework\App::main("OCA\\Mail\\Cont ... r", "send", OC\AppFramework\ ... {}, {accountId: "4", ... "})
 8. <<closure>>
    OC\AppFramework\Routing\RouteActionHandler->__invoke({accountId: "4", ... "})
 9. /var/www/vhosts/[domain]/httpdocs/lib/private/Route/Router.php line 297
    undefinedundefinedcall_user_func(OC\AppFramework\ ... {}, {accountId: "4", ... "})
10. /var/www/vhosts/[domain]/httpdocs/lib/base.php line 975
    OC\Route\Router->match("/apps/mail/api/accounts/4/send")
11. /var/www/vhosts/[domain]/httpdocs/index.php line 42
    OC::handleRequest()

POST /index.php/apps/mail/api/accounts/4/send
from *** by *** at 2019-10-02T23:20:31+02:00

**Comment by wdfee** [comment]
ok, I kept on testing: This problem (2.) only appears if there are spaces in the group name, e.g. "Test group with spaces". I think there is a bug in step 4, where the group name is called `"\"Test group wi ... >"` - there should be a closing `\"`.

```
 4. /var/www/vhosts/cloud.waldorfschule-groebenzell.de/httpdocs/lib/private/AppFramework/Http/Dispatcher.php line 166
    OCA\Mail\Controller\AccountsController->send(2, "testmail", "trsztd iguoig igiug igiug iz", "\"Test group wi ... >", "", "", 29, null, null, [], null)
```

**Comment by wdfee** [comment]
I send the complete new log entry again as code:

```
[mail] Error: Horde_Mime_Exception: Syntax error in parameters or arguments at <<closure>>

 0. /var/www/vhosts/[domain]/httpdocs/apps/mail/vendor/pear-pear.horde.org/Horde_Mime/Horde/Mime/Mail.php line 479
    Horde_Mime_Part->send("[address], \">\"", Horde_Mime_Headers {}, Horde_Mail_Trans ... "})
 1. /var/www/vhosts/[domain]/httpdocs/apps/mail/lib/Account.php line 214
    Horde_Mime_Mail->send(Horde_Mail_Trans ... "}, false, false)
 2. /var/www/vhosts/[domain]/httpdocs/apps/mail/lib/Service/MailTransmission.php line 117
    OCA\Mail\Account->sendMessage(OCA\Mail\Model\Message {}, Horde_Mail_Trans ... "}, 29)
 3. /var/www/vhosts/[domain]/httpdocs/apps/mail/lib/Controller/AccountsController.php line 282
    OCA\Mail\Service\MailTransmission->sendMessage("CloudMaster", OCA\Mail\Model\NewMessageData {}, OCA\Mail\Model\RepliedMessageData {}, null, 29)
 4. /var/www/vhosts/[domain]/httpdocs/lib/private/AppFramework/Http/Dispatcher.php line 166
    OCA\Mail\Controller\AccountsController->send(2, "testmail", "trsztd iguoig igiug igiug iz", "\"Test group wi ... >", "", "", 29, null, null, [], null)
 5. /var/www/vhosts/[domain]/httpdocs/lib/private/AppFramework/Http/Dispatcher.php line 99
    OC\AppFramework\Http\Dispatcher->executeController(OCA\Mail\Controller\AccountsController {}, "send")
 6. /var/www/vhosts/[domain]/httpdocs/lib/private/AppFramework/App.php line 126
    OC\AppFramework\Http\Dispatcher->dispatch(OCA\Mail\Controller\AccountsController {}, "send")
 7. /var/www/vhosts/[domain]/httpdocs/lib/private/AppFramework/Routing/RouteActionHandler.php line 47
    OC\AppFramework\App::main("OCA\\Mail\\Cont ... r", "send", OC\AppFramework\ ... {}, {accountId: "2", ... "})
 8. <<closure>>
    OC\AppFramework\Routing\RouteActionHandler->__invoke({accountId: "2", ... "})
 9. /var/www/vhosts/[domain]/httpdocs/lib/private/Route/Router.php line 297
    undefinedundefinedcall_user_func(OC\AppFramework\ ... {}, {accountId: "2", ... "})
10. /var/www/vhosts/[domain]/httpdocs/lib/base.php line 975
    OC\Route\Router->match("/apps/mail/api/accounts/2/send")
11. /var/www/vhosts/[domain]/httpdocs/index.php line 42
    OC::handleRequest()

POST /index.php/apps/mail/api/accounts/2/send
from 2003:dc:df2c:c7a:bce4:62da:15f6:fa97 by CloudMaster at 2019-10-03T08:38:09+02:00
```

**Comment by ChristophWurst** [comment]
Thanks for the report and the detailed debugging!

> Sending mail failed: valid RCPT command must precede DATA

That's the error that ususaly pops up if no recipient is set. So I guess the group with spaces is not detected and the message is sent to nobody.

**Comment by wdfee** [comment]
Yes, but there are different errors, sorry I missed that. The fatal error for the last entry is:

`[mail] Fatal: Sending mail failed: Syntax error in parameters or arguments
POST /index.php/apps/mail/api/accounts/2/send
from *** by *** at 2019-10-03T08:38:09+02:00`

But I guess the cause is the same.

**Comment by ChristophWurst** [comment]
Where's that log from? The browser? Would be interesting to know if it's a php or IMAP syntax error :thinking:

**Comment by wdfee** [comment]
The log is from Nextcloud interface Settings -> Logging

**Comment by wdfee** [comment]
in server's error.log are a lot of errors from mail app with code 412, including a lot of user ids , token and account folder hash I guess. Can I send it privately to you?

**Comment by wdfee** [comment]
Another error appears if brackets ("[", “]“) are used in group name:
`[mail] Fatal: Sending mail failed: Bad sequence of commands`

In all mentioned (nextcloud) log entries the error starts at the very first step (0.): Either the recipient list is empty or has encoding errors like in example `"[address], \">\""`. (In this example I replaced the email address with "[address]" to not expose it publicly here.)

There must be a bug in encoding in the Horde_Mime package. I took a look at the code, but didn't find an information about the used vendor package version. They are not included here on github, too. 
Can you please check if there is an updated version of the used Horde Package available? Maybe they solved the bug already.

**Comment by wdfee** [comment]
Characters like "ä", "ö", "ü" in group name result in another error:
`[mail] Error: OCA\Mail\Exception\ServiceException: Test (Nextcloud) does not exist at`

The chosen group's name has not been "Test" but "Testöak", so the script cutted out everything after and with character "ö".

This explains the empty recipient in the first error case. The chosen group's name started with an opening bracket "[", so the script cutted out the whole name, resulting in:
`[mail] Error: Horde_Mime_Exception: valid RCPT command must precede DATA at <>`

In my last post I tried group names with brackets in the middle of the name plus spaces like "Test [group]", this resulted in error
`[mail] Fatal: Sending mail failed: Bad sequence of commands`

Using spaces (but no brackets) in group name resulted in
`[mail] Fatal: Sending mail failed: Syntax error in parameters or arguments`

So I guess spaces and brackets are replaced with incorrect opening or ending `\"` and destroys the parameters list. 

Can you reproduce any of these errors?

**Comment by wdfee** [comment]
console log from browser console:
```[ERROR] mail: could not send message 
Object { app: "mail", uid: "adminname", error: Error }
ConsoleLogger.js:56:18
    value ConsoleLogger.js:56
    value ConsoleLogger.js:82
    onSend Composer.vue:334
```
references: 
webpack:///node_modules/nextcloud-logger/dist/ConsoleLogger.js
https://[domain]/apps/mail/js/mail.3.c2b981da60db282fe3f8.js

**Comment by ChristophWurst** [comment]
> Characters like "ä", "ö", "ü" in group name result in another error:

I think there is a ticket for that.



> Can you reproduce any of these errors?

I haven't tried yet but will try to do so soon :crossed_fingers: 

also cc @myrho, the author of the group sending feature :)

**Comment by wdfee** [comment]
> > Characters like "ä", "ö", "ü" in group name result in another error: 
>
> I think there is a ticket for that.

Maybe this one? https://github.com/nextcloud/mail/issues/1907

> > Can you reproduce any of these errors?
>
> I haven't tried yet but will try to do so soon 🤞

So, what does "soon" mean in Nextcloud development? 🤔
(Sorry for my impatience but my roots are in WordPress development where bug reports usually are tested within hours if there are clear steps to reproduce.)
The group mail sending is one of the most important features for us. 

It could also be a javascript issue, maybe a bug in escaping characters that crashes the json array.

**Comment by ChristophWurst** [comment]
I can confirm the bug. It's the server-side. The *to* field is not expanded by the groups integration.

**Comment by ChristophWurst** [comment]
Tests confirm it's not working: https://github.com/nextcloud/mail/pull/2127.
