### ISSUE TITLE
Use BCC instead of TO when sending a mail to group members

### ISSUE THREAD

**Issue by benkinooby** [nextcloud/mail#2067]
At the moment, an e-mail to a nextcloud user group will fill the mail's TO: field with all individual members of that group, thus exposing the e-mail address of all members to all other members.

It would be useful to optionally have the recipients in the BCC: field of the mail instead, to keep mail addresses of members protected and private.

**Comment by ChristophWurst** [comment]
Just select the group in bcc?

**Comment by ChristophWurst** [comment]
Please use our issue templates for bug reports https://github.com/nextcloud/mail/issues/new/choose

**Comment by benkinooby** [comment]
Thanks for the hint and sorry for the noise.

**Comment by ChristophWurst** [comment]
no worries

**Comment by hansimausisteffiwurstbrot** [comment]
This is related:
https://github.com/nextcloud/mail/issues/3132
