### ISSUE TITLE
App doesn’t load

### ISSUE THREAD

**Issue by jancborchardt** [nextcloud/mail#207]
@nextcloud/mail currently I only see this (no server log errors or so):
![capture du 2016-11-24 16-06-55](https://cloud.githubusercontent.com/assets/925062/20603076/29ab0efe-b260-11e6-95ef-cfa89fef0556.png)

How can I debug?

**Comment by ChristophWurst** [comment]
on master?

**Comment by jancborchardt** [comment]
Yep, master and the #202 branch too. make compile-js runs in both cases.

**Comment by ChristophWurst** [comment]
Could not reproduce that on different branches. Could you please check the network tab? The error might indicate that a file was not loaded for some reason.

**Comment by jancborchardt** [comment]
Yeah, it seems to be the initi.js file:
![capture du 2016-11-30 09-55-14](https://cloud.githubusercontent.com/assets/925062/20745788/262f1e6e-b6e3-11e6-8996-8d9d74d61e7c.png)
Any pointer how I can debug or fix this?

@plastikschnitzer is this maybe the same issue you had with https://github.com/nextcloud/mail/pull/211#issuecomment-263256763 ?

**Comment by ChristophWurst** [comment]
confirmed.

**Comment by jancborchardt** [comment]
@ChristophWurst any way I can help debugging further?

**Comment by ChristophWurst** [comment]
I have no idea, maybe it's related to the js optimization. Does it work with enabled debug mode maybe?

**Comment by ChristophWurst** [comment]
Will try to fix this ASAP

**Comment by jancborchardt** [comment]
Nice, with debug mode it works again. My accounts were removed but now it’s proper. :D 

Just had some issues with setup:
![capture du 2016-12-02 15-19-07](https://cloud.githubusercontent.com/assets/925062/20837181/37d3cd10-b8a3-11e6-9db9-52a53d3c3586.png)
- the account doesn’t load automatically because of this error, have to refresh
- if I refresh, it keeps /#setup in the domain and shows the »Add account« view again. Instead I’d expect to see the unified inbox

**Comment by jancborchardt** [comment]
Aaand setting »debug« to false causes the error with init.js again :)
