### ISSUE TITLE
Add support for pEp (pretty Easy privacy)

### ISSUE THREAD

**Issue by 4jNsY6fCVqZv** [nextcloud/mail#2074]
### Feature Request

what it says on the tin!

I don't want to feel the need to install/use Thunderbird just to make my communication more secure and sustainable.
This could be solved by adding privacy by design support for pEp in Mail.
Guess the pEp developement team would love to support your implementation if you just ask them!

I would love to see it as an privacy by design and default enabled, build in plugin, that secures my future communication out of the box, after installing &amp; running Mail as my primary mail client.

**Comment by Gatak** [comment]
Is this a pgp solution?

**Comment by jancborchardt** [comment]
Since we already support Mailvelope (which also supports Autocrypt as per https://github.com/nextcloud/mail/issues/648) it seems this is rather something to do on their end. They in fact have an open issue about it: https://github.com/mailvelope/mailvelope/issues/464

Closing this hence as it’s not our area of focus.

**Comment by BuZZ-dEE** [comment]
@jancborchardt Mailvelope is a third party browser extension. It would be great if this is directly supported by Nextcloud mail. Could you please open this issue again?

**Comment by ChristophWurst** [comment]
Would you have the resources to deliver the implementation?

**Comment by 4jNsY6fCVqZv** [comment]
@ChristophWurst My idea would be, that you as Nextcloud Mail team simply ask the p=p developers directly. For example Volker @fdik.
I think they are open-minded and very happy to explore a common way to realize p=p support for Mail.

**Comment by ChristophWurst** [comment]
You're free to establish that communication. I don't have time for this right now. As soon as someone who has the skills to deliver the integration is found please ping me and we can discuss the design details.
