### ISSUE TITLE
Sieve support

### ISSUE THREAD

**Issue by flionet89** [nextcloud/mail#2085]
Please add support for filter management sieve or some analogue.

**Comment by ChristophWurst** [comment]
Please use the issue search before opening new ones: https://github.com/nextcloud/mail/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aopen+sieve

And *please* follow the issue template. It's there to make tickets more manageable and easier to triage. Ignoring it will just make it less likely that a request is picked up.
