### ISSUE TITLE
Can't open Large text email

### ISSUE THREAD

**Issue by rikmos** [nextcloud/mail#209]
### Steps to reproduce
1. receive email from logwatch (format text file is about 6mb)
2. select email 
3. watch spinner (while watch do spinning)
4. Every other mail will open AND logwatch formatted in html 
5. I'm going to suggest it's a php.ini option that needs to be upp'd
### Expected behaviour
Tell us what should happen
Display the text body email
### Actual behaviour
Tell us what happens instead
The End of the World as we know it (I feel fine)
### Mail app

**Mail app version:** (see apps admin page)
0.6.0
**Mailserver or service:** (e.g. Outlook, Yahoo, Gmail, Exchange,...)
localhost / postfix / cyrus-imap
**Transport security - IMAP:** (None, SSL, TLS, STARTTLS) 
SSL
**Transport security - SMTP:** (None, SSL, TLS, STARTTLS)
SSL
**Number of accounts:**
6
**Mail app version build date:** (only if you are using a Nightly Build)

### Server configuration
**Operating system**:
Gentoo /kernel ver 4.8.10
**Web server:**
apache2 2.4.23
**Database:**
sqlite3 3.13
**PHP version:**
5.6
**Version:** (see admin page)
10.1.1 nextcloud
**Updated from an older version or fresh install:**
fresh
**List of activated apps:**
stock+email only 
```
If you have access to your command line run e.g.:
sudo -u www-data php occ app:list
from within your server installation folder
```

**The content of config/config.php:**

<details>
```
If you have access to your command line run e.g.:
sudo -u www-data php occ config:list system
from within your server installation folder

or 

Insert your config.php content here
(Without the database password, passwordsalt and secret)
```<?php
$CONFIG = array (
  'instanceid' => 'Iknowwhatitis
  'datadirectory' => '/var/www/localhost/htdocs/NX/data',
  'dbtype' => 'sqlite3',
  'version' => '9.1.1.5',
  'installed' => true,
  'trusted_domains' =>
  array (
    0 => sanatized
    1 => 'sanatiztized more
    2 => 'sanitized again
  ),
  'default_language' => 'en',
  'overwrite.cli.url' => '/NX',
  'logtimezone' => 'PST',
  'defaultapp' => 'files',
  'enable_avatars' => true,
  'allow_user_to_change_display_name' => true,
  'remember_login_cookie_lifetime' => 1296000,
  'session_lifetime' => 86400,
  'session_keepalive' => true,
  'token_auth_enforced' => false,
  'mail_domain' => 'sanitized cuz youknow spam
  'mail_from_address' => 'nx',
  'mail_smtpdebug' => false,
  'mail_smtpmode' => 'sendmail',
  'mail_smtphost' => 'sanitized more
  'mail_smtpport' => '465',
  'mail_smtptimeout' => 10,
  'mail_smtpsecure' => 'ssl',
  'mail_smtpauth' => 1,
  'mail_smtpauthtype' => 'LOGIN',
  'mail_smtpname' => '',
  'mail_smtppassword' => '',
  'htaccess.RewriteBase' => '/NX
  'trashbin_retention_obligation' => 'auto',
  'versions_retention_obligation' => 'auto',
  'appcodechecker' => true,
  'updatechecker' => true,
  'updater.server.url' => 'https://updates.owncloud.com/server/',
  'has_internet_connection' => true,
  'check_for_working_webdav' => true,
  'check_for_working_wellknown_setup' => true,
  'check_for_working_htaccess' => true,
  'config_is_read_only' => false,
  'log_type' => 'owncloud',
  'loglevel' => 1,
  'memcache.local' => '\\OC\\Memcache\\APCu',
  'syslog_tag' => 'ownCloud',
  'cron_log' => true,
  'maintenance' => false,
  'singleuser' => false,
  'openssl' =>
  array (
    'config' => '/etc/ssl/openssl.cnf',
  ),
  'sqlite.journal_mode' => 'DELETE',
  'supportedDatabases' =>
  array (

</details>

#### Client configuration
**Browser:**
IE or Chrome , same effect
**Operating system:**

#### Logs
##### Web server error log
`nothing
Insert your webserver log here
```

##### Server log (data/nextcloud.log)
<details>
```
Insert your server log here
```
</details>

##### Horde IMAP log (data/horde_imap.log)
<details>
```
Insert your horde IMAP log here, see https://github.com/nextcloud/mail#debug-mode
```
</details>

##### Horde SMTP log (data/horde_smtp.log)
<details>
```
Insert your horde SMTP log here, see https://github.com/nextcloud/mail#debug-mode
```
</details>

##### Browser log
<details>
```
Insert your browser log here, this could for example include:

a) The javascript console log
b) The network log 
c) ...
```
</details>

**Comment by ChristophWurst** [comment]
> ``` Insert your server log here ```

Hi. Could you please enable debug mode and IMAP logging and post your logs here? The browser's console log would be interesting too in case it's a client-side issue. Thanks

**Comment by ChristophWurst** [comment]
I'm closing this now due to lack of activity. If you can provide the information I've asked for we can re-open this of course.
