### ISSUE TITLE
Some messages fail to decode properly

### ISSUE THREAD

**Issue by StCyr** [nextcloud/mail#2092]
### Expected behavior
Messages should be displayed nicely on screen

### Actual behavior
Some messages are not displayed nicely (probably not decoded properly) though they are displayed nicely on another webmail app.

Issue with `text/plain` content-type?

(source [email.txt](https://github.com/nextcloud/mail/files/3711370/email.txt))

mail formating: 

![image](https://user-images.githubusercontent.com/8179031/66552098-0923ec80-eb49-11e9-893b-f350d03d6729.png)

ovh formating: 

![image](https://user-images.githubusercontent.com/8179031/66552742-27d6b300-eb4a-11e9-9536-af04b7b9b215.png)

### Mail app

**Mail app version:** 0.17.0

**Mailserver or service:** OVH

### Server configuration

**Operating system**: Debian Buster/10/stable

**Web server:** Apache

**Database:** MariaDB

**PHP version:** (e.g. 7.0)

**Nextcloud Version:** 17

#### Client configuration
**Browser:** Firefox Quantum stable

**Operating system:** Windows 10

**Comment by StCyr** [comment]
so, yeah, that's an issue with a plain text message. Here's the message as received by the front-end:

![image](https://user-images.githubusercontent.com/8179031/66748373-4ceb5e80-ee87-11e9-9f14-fe37236ef0ba.png)

The problem comes from the `\n` characters, but I don't know where this should be fixed (backend/frontend). Any idea @nextcloud/mail ?

**Comment by ChristophWurst** [comment]
> Content-Transfer-Encoding: 8bit

Usually transfer encoding is taken into account IIRC. And Horde should thus handle it properly.

**Comment by StCyr** [comment]
> 
> 
> > Content-Transfer-Encoding: 8bit
> 
> Usually transfer encoding is taken into account IIRC. And Horde should thus handle it properly.

Sorry, I don't understand: Do you mean that horde have already translated the `\n` into `<br>`?!?

**Comment by ChristophWurst** [comment]
I have to attach a debugger and step through the code to give a qualified answer. I don't understand the problem either at the moment. It could be an encoding issue. It could be this app changing some text. I don't know.

**Comment by StCyr** [comment]
> I have to attach a debugger and step through the code to give a qualified answer. 

That's already a good answer :-) 

This means backend should be verified first.
