### ISSUE TITLE
Mail App not working under Nextcloud 17.0.0

### ISSUE THREAD

**Issue by hillebr** [nextcloud/mail#2094]
### Expected behavior
Maill app stopped loading Mails on all added accounts after update to Nextcloud 17.0.0
Removing and re-adding the app won't solve the issue
When starting the app, the circle keeps spinning an nothing happens (see attached schreenshot)
![2019-10-10 14_56_24-E-Mail - Cloud](https://user-images.githubusercontent.com/28733806/66570671-5f575680-eb6e-11e9-8328-c75e6adfa9f2.png)

and the following error shows up in log:

Exception: The requested uri(/index.php/apps/mail/api/accounts/20/folders/SU5CT1g%3D/messages) cannot be processed by the script '/nextcloud/index.php')

    /var/www/html/nextcloud/lib/base.php - line 943:

    OC\AppFramework\Http\Request->getRawPathInfo()

    /var/www/html/nextcloud/index.php - line 42:

    OC::handleRequest()

### Actual behavior
...it should just work as under Nexcloud 16.0.5

### Mail app

**Mail app version:**  0.17.0

**Mailserver or service:** Gmail, web.de, t-online.de & own debian based mailserver

### Server configuration

**Operating system**: Debian 9

**Web server:** Apache

**Database:** MariaDB 	10.3.18

**PHP version:** 	7.3.10

**Nextcloud Version:** 17.0.0

#### Client configuration
**Browser:** Firefox 69 but independent from browser type

**Operating system:** Windows 10

**Comment by ChristophWurst** [comment]
Please share the line from nextcloud.log that pops up when this error is triggered.

**Comment by hillebr** [comment]
{"reqId":"XaA5X38AAQEAACP0FkUAAAAB","level":3,"time":"2019-10-11T09:12:15+01:00","remoteAddr":"212.211.165.69","user":"rene","app":"index","method":"GET","url":"\/index.php\/apps\/mail\/api\/accounts\/20\/folders\/SU5CT1g%3D\/messages","message":{"Exception":"Exception","Message":"The requested uri(\/index.php\/apps\/mail\/api\/accounts\/20\/folders\/SU5CT1g%3D\/messages) cannot be processed by the script '\/nextcloud\/index.php')","Code":0,"Trace":[{"file":"\/var\/www\/html\/nextcloud\/lib\/base.php","line":943,"function":"getRawPathInfo","class":"OC\\AppFramework\\Http\\Request","type":"->","args":[]},{"file":"\/var\/www\/html\/nextcloud\/index.php","line":42,"function":"handleRequest","class":"OC","type":"::","args":[]}],"File":"\/var\/www\/html\/nextcloud\/lib\/private\/AppFramework\/Http\/Request.php","Line":780,"CustomMessage":"--"},"userAgent":"Mozilla\/5.0 (Windows NT 10.0; Win64; x64; rv:69.0) Gecko\/20100101 Firefox\/69.0","version":"17.0.0.9"}

**Comment by ChristophWurst** [comment]
Related to https://github.com/nextcloud/server/issues/11913 https://github.com/PhieF/CarnetNextcloud/issues/14. Do you use that app?

**Comment by hillebr** [comment]
No, I do not use the carnet app

**Comment by ChristophWurst** [comment]
This is strange. I have never seen an error like this. Could you temporarily disable other 3rdparty apps?

**Comment by ChristophWurst** [comment]
Any warning on your admin settings overview page? Does the integrity check pass?

**Comment by hillebr** [comment]
...no warnings an yes, the check did pass!

**Comment by hillebr** [comment]
Hi there,
after update to Nextcloud 17.0.1.1 the issue is fixed!

Thanks a lot!

René
