### ISSUE TITLE
Answer emails on top of the email instead of at the bottom

### ISSUE THREAD

**Issue by enoch85** [nextcloud/mail#212]
As it is now you have to scroll to answer any email. This is a bit annoying when you have long conversations, and I think that it would be better design to answer the emails on top instead, as most of the email vendors do it today.

cc @nextcloud/designers

**Comment by eppfel** [comment]
But how would this look in the UI? Right now, If you hit the reply button, you are scrolled to the bottom. So, instead opening the Form above of the conversation?
Can you give some examples? I mainly use Apple Mail and Gmail on Android.

**Comment by jancborchardt** [comment]
> answer the emails on top instead, as most of the email vendors do it today.

@enoch85 who is »most of the vendors«? ;) Both Gmail and Google Inbox have the reply box on the bottom, as that’s the conversational flow.

**Comment by enoch85** [comment]
@jancborchardt Ok, sorry for not checking first. I just had the impression that "most vendors" (Gmail) was doing so, but it turns out they scroll to the reply box for you, so you don't have to scroll as @eppfel mentioned. Must have been a glitch when I tried it. 

Anyway, this issue is about unnecessary scrolling and that includes answering on the top of each mail, like "other vendors" do it. :) Not the bottom.

**Comment by eppfel** [comment]
> Anyway, this issue is about unnecessary scrolling and that includes answering on the top of each mail, like "other vendors" do it. :) Not the bottom.

I still don't get it 😁

**Comment by enoch85** [comment]
@eppfel When hitting "answer" you get to the bottom of the email, not the top of the email. So as most vendors answer on top, the mail app answer at the bottom.

**Comment by jancborchardt** [comment]
@enoch85 clicking »Reply« should scroll you to the reply field. With the first line being focused, and the first 3 lines being blank for you to put your reply. And the previous email should be _below_ as quoted text.

**Comment by enoch85** [comment]
> clicking »Reply« should scroll you to the reply field.
:heavy_check_mark:

>And the previous email should be below as quoted text. 
:-1: 

So we have a bug. This happens when answering a not previously answered message. Messages that has been replied before works as expected.

**Comment by ChristophWurst** [comment]
Please fill out the issue template :-)

**Comment by enoch85** [comment]
### Steps to reproduce
1. Press the "Answer" button in a new message (not answered before) 

### Expected behaviour
Previous email should be **below** as quoted text.

### Actual behaviour
Previous email is **above** as quoted text.

### Mail app

**Mail app version:** (see apps admin page)
0.6.0

**Mailserver or service:** (e.g. Outlook, Yahoo, Gmail, Exchange,...)
Citynetwork (Domain based email)

**Transport security - IMAP:** (None, SSL, TLS, STARTTLS) 
SSL/TLS

**Transport security - SMTP:** (None, SSL, TLS, STARTTLS)
SSL/TLS

**Number of accounts:**
1

### Server configuration
**Operating system**:
Ubuntu 16.04 Server
**Web server:**
Apache 2.4
**Database:**
MySQL 5.7
**PHP version:**
7.0.8
**Version:** (see admin page)
10.0.1
**Updated from an older version or fresh install:**
Fresh install
**List of activated apps:**
<details>
```
Enabled:
  - activity: 2.3.2
  - calendar: 1.4.1
  - comments: 1.0.0
  - contacts: 1.4.0.0
  - dav: 1.0.1
  - documents: 0.13.1
  - federatedfilesharing: 1.0.1
  - federation: 1.0.1
  - files: 1.5.2
  - files_external: 1.0.2
  - files_pdfviewer: 0.8.1
  - files_sharing: 1.0.0
  - files_texteditor: 2.1
  - files_trashbin: 1.0.0
  - files_versions: 1.3.0
  - files_videoplayer: 0.9.8
  - firstrunwizard: 1.1
  - gallery: 15.0.0
  - mail: 0.6.0
  - notifications: 0.3.0
  - password_policy: 1.0.0
  - provisioning_api: 1.0.0
  - serverinfo: 1.1.1
  - spreedme: 0.3.4
  - survey_client: 0.1.5
  - systemtags: 1.0.2
  - tasks: 0.9.3
  - theming: 1.0.1
  - updatenotification: 1.0.1
  - user_external: 0.4
  - workflowengine: 1.0.1
Disabled:
  - admin_audit
  - encryption
  - external
  - files_accesscontrol
  - files_automatedtagging
  - files_retention
  - templateeditor
  - user_ldap
  - user_saml
```
</details>

**The content of config/config.php:**

<details>
```
{
    "system": {
        "instanceid": "oczset2i2y1m",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "demo.orestad-linux.se"
        ],
        "datadirectory": "\/var\/ncdata_demo\/",
        "overwrite.cli.url": "https:\/\/demo.orestad-linux.se",
        "dbtype": "mysql",
        "version": "9.1.1.5",
        "dbname": "nextcloud_demo",
        "dbhost": "localhost",
        "dbport": "",
        "dbtableprefix": "oc_",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "logtimezone": "Europe\/Stockholm",
        "installed": true,
        "preview_libreoffice_path": "\/usr\/bin\/libreoffice",
        "memcache.local": "\\OC\\Memcache\\Redis",
        "filelocking.enabled": true,
        "memcache.distributed": "\\OC\\Memcache\\Redis",
        "memcache.locking": "\\OC\\Memcache\\Redis",
        "redis": {
            "host": "\/var\/run\/redis\/redis.sock",
            "port": 0,
            "timeout": 0,
            "dbindex": 0
        },
        "mail_smtpmode": "smtp",
        "mail_smtpauth": 1,
        "mail_smtpport": "587",
        "mail_smtphost": "mail.citynetwork.se",
        "mail_smtpauthtype": "LOGIN",
        "mail_from_address": "orestadlinux",
        "mail_domain": "techandme.se",
        "mail_smtpname": "***REMOVED SENSITIVE VALUE***",
        "mail_smtppassword": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpsecure": "tls",
        "maintenance": false,
        "appstore.experimental.enabled": true
    }
}
```
</details>

#### Client configuration
**Browser:**
Chrome (Denbian)
**Operating system:**
Deepin 15.3
#### Logs
##### Web server error log
```
Insert your webserver log here
```

##### Server log (data/nextcloud.log)
<details>
```
Insert your server log here
```
</details>

##### Horde IMAP log (data/horde_imap.log)
<details>
```
Insert your horde IMAP log here, see https://github.com/nextcloud/mail#debug-mode
```
</details>

##### Horde SMTP log (data/horde_smtp.log)
<details>
```
Insert your horde SMTP log here, see https://github.com/nextcloud/mail#debug-mode
```
</details>

##### Browser log
<details>
```
Insert your browser log here, this could for example include:

a) The javascript console log
b) The network log 
c) ...
```
</details>

**Comment by jancborchardt** [comment]
> Previous email is above as quoted text.

Are you sure this is even the case? Can you take a screenshot?

I’m beginning to think that this is a duplicate of https://github.com/nextcloud/mail/issues/195

**Comment by enoch85** [comment]
This is what I get when pressing "Answer" in the email:

![deepinscreenshot20161201105658](https://cloud.githubusercontent.com/assets/4511254/20789495/eedb9898-b7b4-11e6-9ae4-169356d4011b.png)

**Comment by jancborchardt** [comment]
That’s indeed very strange. What should happen is the same as when you just scroll down: The first few lines being blank, and then the quoted message displayed. Clicking »reply« should focus the first line.

cc @nextcloud/javascript any idea?

**Comment by vslonska** [comment]
Hello,

I have the same problem with Nextcloud 13.0.2 and css plugin installed. I have to scroll manually to reply.

**Comment by vslonska** [comment]
https://github.com/nextcloud/mail/issues/846#issuecomment-376693674
