### ISSUE TITLE
Not possible to mark a mesage as unread via action menu

### ISSUE THREAD

**Issue by jancborchardt** [nextcloud/mail#2128]
When you use the action menu to "Mark unread", the message is actually opened … marking it read. :D It only works using the shortcut, but when you use the action menu it undoes itself.

**Comment by ChristophWurst** [comment]
cc @GretaD :)

**Comment by GretaD** [comment]
@jancborchardt i cannot reproduce it. Am i doing it right? See gif

![mailappp](https://user-images.githubusercontent.com/12728974/67214285-c6eb8c80-f41f-11e9-811c-8fe29f7d11cf.gif)

**Comment by ChristophWurst** [comment]
Try with a message other than the active one ;)

**Comment by GretaD** [comment]
ah right, i can reproduce it now. Thank you

**Comment by jancborchardt** [comment]
Fixed by @ChristophWurst via https://github.com/nextcloud/mail/pull/2162 :eyeglasses:
