### ISSUE TITLE
Mail App can´t activated in Nextcloud 11 beta 2

### ISSUE THREAD

**Issue by Happyfeet01** [nextcloud/mail#213]
I updated my Cloud to Nextcloud 11 beta 2. But the Bookmarks App only support lower Version of nextcloud.

### Steps to reproduce
1. running Nextcloud 10
2. make an update to Nextcloud 11 beta 2
3. Bookmarks App can´t activated

### Expected behaviour
![apps_cant_activated](https://cloud.githubusercontent.com/assets/3295104/20744094/2e73fabc-b6da-11e6-863c-9e3769c920be.png)

### Server configuration
**Operating system**:
ubuntu 16.04 LTS

**Web server:**
Apache2
**Database:**
MySQL
**PHP version:**
PHP 7.0.13
**nextcloud Version:** 
Nextcloud 11 beta 2
**Mail version:** 
0.6.0
**Updated from an older ownCloud or fresh install:**

**Where did you install ownCloud from:**
installed with the updater (beta Channel)

**Comment by jancborchardt** [comment]
cc the relevant other app developers too: @blizzz for Bookmarks, @paulijar for Music, @irgendwie for Notes, @raimund-schluessler for Tasks :)

**Comment by enoch85** [comment]
Can confirm this. Changing the version number in info.xml did the trick.

**Comment by enoch85** [comment]
Also, the Documents app doesn't work at all, but IDK who is in charge for that app and where I should report it?

**Comment by jancborchardt** [comment]
@enoch85 or @Happyfeet01 can you submit pull requests to the apps to fix it? :) That would be awesome. And you can even do that from the Github web interface if you don’t have a local dev environment.

@enoch85 the Documents app is not maintained anymore, all focus is on the Collabora documents app.

**Comment by ChristophWurst** [comment]
> @enoch85 or @Happyfeet01 can you submit pull requests to the apps to fix it? :) That would be awesome. And you can even do that from the Github web interface if you don’t have a local dev environment.

Nothing to fix. The master branch is ready for NC11 😉

**Comment by enoch85** [comment]
@jancborchardt Well, if the Collabora App was as easy to install as the Documents app I would stay quiet. But seriously, how can you (we) drop support for an app that is installed by one click, to another one which requires several steps? 

I mean, if Collabora is integrated in Nextcloud by a one click install (not the docker) then I can understand. But if "drop in replacment" for Documents is Collabora, that's a fail IMHO. :)

I'm pretty oriented in Linux, Apache and installing things, but the Collabora app + docker beats me to it. Imagine a "regular user". With the Documents app you at least get *some* editing capabilites.

But, this is a different topic and I'm happy to discuss it in #nextcloud-dev.

**Comment by jancborchardt** [comment]
> But seriously, how can you (we) drop support for an app that is installed by one click, to another one which requires several steps?

Because Documents was based on WebODF, which is discontinued.

I understand your concerns and totally agree, but it is simply not something we have the resources to maintain.

**Comment by ChristophWurst** [comment]
I packaged and released a NC11 compatible version of 0.6 on the app store: https://apps.nextcloud.com/apps/mail

**Comment by blizzz** [comment]
> I updated my Cloud to Nextcloud 11 beta 2. But the Bookmarks App only support lower Version of nextcloud.

> cc the relevant other app developers too: @blizzz for Bookmarks,

For the record, Bookmarks got also a release and is available through the app store https://apps.nextcloud.com/apps/bookmarks
