### ISSUE TITLE
Add plural form to messages

### ISSUE THREAD

**Issue by rakekniven** [nextcloud/mail#2132]
Please add plural handling for i18n work.

https://github.com/nextcloud/mail/blob/1e2521a23ada7d9ba630accb25dfa1965c1cb126/src/components/NavigationFolder.vue#L126

https://github.com/nextcloud/mail/blob/1e2521a23ada7d9ba630accb25dfa1965c1cb126/src/components/NavigationFolder.vue#L130

**Comment by ChristophWurst** [comment]
@jancborchardt something for you as you also touched https://github.com/nextcloud/mail/pull/2129? :)

**Comment by nickvergessen** [comment]
https://github.com/nextcloud/mail/blob/f2ab6e378ebb745e050466ea38489bb3b8f22bc1/src/components/NavigationFolder.vue#L88

Similar problem. You need to split up the string even, as "messages" and "unread" might have different plurals

**Comment by ChristophWurst** [comment]
How's that possible in a way that does not break arbitrary languages?

Is it save to assume that concatenating two translated strings makes sense in all languages?

**Comment by nickvergessen** [comment]
```js
					actions.push({
						icon: 'icon-info',
						text: atob(this.folder.id),
						longtext: n('mail', '{total} message ({unreadString})', '{total} messages ({unreadString})', this.folderStats.total, {
							total: this.folderStats.total,
							unreadString: n('mail', '{unread} unread', '{unread} unread', this.folderStats.unread, {
								unread: this.folderStats.unread,
							}),
						}),
					})
```

**Comment by ChristophWurst** [comment]
Clever!

**Comment by GretaD** [comment]
The code changed ever since this ticket was open. @rakekniven does this still need plural handling? 
https://github.com/nextcloud/mail/blob/9289709058104b55632aa02d58bd2c529d08a931/src/components/NavigationFolder.vue#L132-L140

**Comment by nickvergessen** [comment]
Yes `{unread} unread` is  short of `{unread} unread mail(s)`
