### ISSUE TITLE
.ics (iCal) file sent as mail attachment is not imported into calendar

### ISSUE THREAD

**Issue by tbdt** [nextcloud/mail#2134]
### Expected behavior
When you click the "Import into calendar" button in mail app to import an appointment that was sent as an attached .ics (iCal) file the following should happen:
1. a menu opens to choose a calendar 
2. After choosing a calendar the appointment is imported into that calendar

### Actual behavior
After clicking the button the + icon, it changes into the spinning icon and nothing more happens.

### Mail app
Mail app version: 0.17.0

### Server configuration
Nextcloud Version: Tried on two different versions: 16.0.5 / 17.0.0

Mail app version 0.11.0 on Nextcloud version 15.0.7 had no problems and worked as expected.

**Comment by ChristophWurst** [comment]
logs? sounds like there might be an error in the browser console. Please check and post the logs here.
