### ISSUE TITLE
[Enhancement] Make the answer button text white

### ISSUE THREAD

**Issue by enoch85** [nextcloud/mail#214]
The answer button is gray and it almost seems like it's disabled. It makes much more sense to make the text white instead.

Before:
![deepinscreenshot20161130094313](https://cloud.githubusercontent.com/assets/4511254/20745390/70b4bffe-b6e1-11e6-9343-0e32de331924.png)

After:
![deepinscreenshot20161130094217](https://cloud.githubusercontent.com/assets/4511254/20745373/603e33b2-b6e1-11e6-9b48-47f54f67a3ea.png)

Couldn't find the CSS for it, so I created an issue instead.

cc @nextcloud/designers

**Comment by ChristophWurst** [comment]
> seems like it's disabled

It *is* disabled as long as you don't put anything into "to", "subject" and the message body. cc @jancborchardt

**Comment by enoch85** [comment]
But if your intention is to answer the email you press "Answer" to come to the message area.

**Comment by jancborchardt** [comment]
@enoch85 update to the latest version of the Mail app. Can’t check right now because of https://github.com/nextcloud/mail/issues/207 but I’m pretty sure with the new nicer layout (and bigger buttons) I also fixed the color of that text. :)

**Comment by enoch85** [comment]
@jancborchardt 0.6.0 isn't the latest version?

This is on Chrome btw.

**Comment by jancborchardt** [comment]
@enoch85 it is the latest release, but it’s from September. :) Test with the latest nighly: https://github.com/nextcloud/mail/releases or just do it via git, I’m always on master. ;)

**Comment by enoch85** [comment]
> but I’m pretty sure with the new nicer layout (and bigger buttons) I also fixed the color of that text. :)

So if this is fixed in 0.6.1 (or current master) then we can close this one.
