### ISSUE TITLE
Cannot delete emails, after i filter them into a different folder.

### ISSUE THREAD

**Issue by GretaD** [nextcloud/mail#2141]
I cannot delete emails after i filter them into a different folder. Right now i can only delete emails in my inbox.

**Comment by ChristophWurst** [comment]
Do you mean server-side filtering? What happens if you delete? Do you get an error? Browser console? Anything in nextcloud.log?

**Comment by GretaD** [comment]
Console: 
>[DEBUG] mail: other message open, not jumping to the next/previous message 
{…}

>app: "mail"
>uid: "greta"
​
> <prototype>: Object { … }
>ConsoleLogger.js:44:18
>envelope does not exist 1 SU5CT1guV29yayBSZXBvcnQ= 565 mutations.js:144:11
>message removed actions.js:485:12

Nothing it is shown at nextcloud.log, and no i dont get any error. Nothing happens after the delete button is clicked.

It happens locally and at cloud.nextcloud.com

**Comment by ChristophWurst** [comment]
Okay, so a client-side error. What are your reproduction steps?

**Comment by ChristophWurst** [comment]
Actually the `envelope does not exist` is fine. This means the app tries to delete a local message which doesn't even exist anymore.

**Comment by GretaD** [comment]
> Okay, so a client-side error. What are your reproduction steps?

Sorry, I should have done this when i opened the ticket.

Reproduction steps:
I guess everyone has at least one folder where you filter certain emails. If yes, than go to one of them and try to delete an email from this folder.
If not:

- Create a folder under inbox i.e Work report
- Filter certain emails to go directly to this folder.
- After all the emails moved to the new folder, try to delete one of them.

**Comment by ChristophWurst** [comment]
Where do you define the rule? In another client? :) Does the message show up in the inbox first before it vanishes?

**Comment by GretaD** [comment]
> Where do you define the rule? In another client? :) 

Yes, from thunderbird, because you cannot filter emails from our mail app.

>Does the message show up in the inbox first before it vanishes?

Im not sure if I understood the question..sorry. You mean after the filter?

**Comment by ChristophWurst** [comment]
Do I understand correctly that

* New message arrives in inbox
* Mail app shows it there
* Thunderbird moves it
* Mail app still shows it
* You can't delete it

?

**Comment by GretaD** [comment]
> Do I understand correctly that
> 
> * New message arrives in inbox
> * Mail app shows it there
> * Thunderbird moves it

Yes.

> * Mail app still shows it

no, the email is moved to the new folder and it is only shown in the new folder, just like it is suppose to.

> * You can't delete it

I cannot delete if from the new folder, when i try to delete it from our mail.

**Comment by GretaD** [comment]
Update: I fixed my thunderbird and noticed that all the emails that I try to delete while testing locally are deleted. What actually happens is that the email is deleted, but it doesn't disappear right away after delete button is clicked. If you refresh the page, then it is gone.

**Comment by GretaD** [comment]
fixed with the new updates
