### ISSUE TITLE
Signature shown in single line

### ISSUE THREAD

**Issue by jancborchardt** [nextcloud/mail#2148]
### Expected behavior
Signatures should be appeneded to the message as they appear in the signature settings field, that is multiline if defined as multiline. Also there should _always_ be a line break after the "--" and the beginning of the signature.

### Actual behavior
This is the signature setting:
![Signature setting](https://user-images.githubusercontent.com/925062/67278642-aaa42a00-f4c9-11e9-8aa9-30766c6de8d7.png)

This is how it actually shows:
![Signature shown plain text no breaks](https://user-images.githubusercontent.com/925062/67278641-aaa42a00-f4c9-11e9-907c-a0265ba805b6.png)

### Mail app
Latest master

**Comment by ChristophWurst** [comment]
Ref #2147 where I had to touch similar code. It's because we use the rich editor and it treats the text as HTML, where newlines do not have any semantics. We have to convert line breaks to `<br>`.
