### ISSUE TITLE
Delete key shortcut behaves differently than action menu "Delete" action

### ISSUE THREAD

**Issue by jancborchardt** [nextcloud/mail#2154]
1. Open the very first mail in a mailbox
2. Hit the delete key on your keyboard
3. Current message gets deleted as expected, but:

### Expected behavior
It should switch to the next most recent message below as the active one. (Only when you are at the very top of course. When you are in any other message below, it will move to the next newer message, as intended.)

This works fine when you use "Delete" from the action menu.

### Actual behavior
When you use the delete key shortcut, the already deleted mail keeps being active and shown in the content view.

### Mail app

**Mail app version:** current master

**Comment by jancborchardt** [comment]
The relevant code which gets run on using the delete keyboard shortcut is in this block:
https://github.com/nextcloud/mail/blob/master/src/components/EnvelopeList.vue#L207-L213

It seems what is missing there is the action to go to the next newest unread mail. :)

**Comment by ChristophWurst** [comment]
To fix this discrepancy we should unify the code and use the same logic for both the shortcut and the action menu.
