### ISSUE TITLE
Mails unexpectedly get line breaks

### ISSUE THREAD

**Issue by jancborchardt** [nextcloud/mail#2181]
Whenever you write a mail and then save it as draft, it is saved with line breaks after 80 characters. This is very annoying as it basically destroys your text in an unfinished state.

Same thing when sending mail. You don’t expect it to be broken, and it also leads to issues when e.g. people have narrower displays or when people quote. Then it looks like this:

> Hey look at me I am writing
> an
> email and I sent it with an
> email
> app which does automatic line
> breaking
> looks great right?

**Comment by StCyr** [comment]
This seems to come from https://github.com/nextcloud/mail/blob/538eedbb3a902afddaf43d65a57dcb9f1911fe22/src/util/HtmlHelper.js#L20

No idea why it's needed though

Note that this only happens with plain text messages, and, that you can also reproduce the issue with the following steps:

1- click on "+ New message"
2- turn the message into its non-plain text version by clicking on the "..." (message options) button and unchecking the "Plain text" box
3- type a very long line in the message's body (more than 80 characters)
4- turn the message into plain text by checking back the "Plain text" box
5- see the line wrapping 

![Mail - Nextcloud - Mozilla Firefox 2019-11-12 12-16-17](https://user-images.githubusercontent.com/8179031/68671828-91cee780-0550-11ea-8c8d-9d370b2d139b.gif)

**Comment by ChristophWurst** [comment]
I think this is somewhat related to https://tools.ietf.org/html/rfc2646#section-4.1. IIRC someone from Horde also told us that we should use flowed formatting as otherwise there are problems with interoperability and other clients. So, this is there for a reason.

**Comment by jancborchardt** [comment]
> wordwrap: 78, // 80 minus '> ' prefix for replies

This breaks down as soon as the second person replies though.

And if there’s screens which show less than 80 characters → that is a lot of smartphones.


Let’s test with a bunch of other apps what they do, will update as I go along, feel free to test and comment or edit this list:
- Geary: does _not_ force break when sending
- iOS Mail: 
- Apple Mail: 
- Gmail: 
- Android mail:

**Comment by ChristophWurst** [comment]
> This breaks down as soon as the second person replies though.

Yes: https://tools.ietf.org/html/rfc2646#section-4.1

**Comment by StCyr** [comment]
So, if the problem is just a matter of line length, the RFC seems to advice wrapping at 72 characters, or even less (« As suggested values, any paragraph longer than 79 characters in total length could be wrapped using lines of 72 or fewer characters. » ).

Cyrille

**Comment by jancborchardt** [comment]
It's not just a matter of line length, but a matter of expectation.

Fastmail wrote a good article on it:
https://fastmail.blog/2016/12/17/format-flowed/

This and the reality that no big app supports it, and mails sent or replied to using Nextcloud Mail get butchered, should be enough of an argument for us to remove this.

**Comment by StCyr** [comment]
I’m not sure I fully understand the matter, but, if you’re willing to remove lines wrapping entirely, know that I support this idea 100% :)

**Comment by jancborchardt** [comment]
Fix at https://github.com/nextcloud/mail/pull/2271, please review. :)
