### ISSUE TITLE
"To" recipient field is not automatically focused for new message

### ISSUE THREAD

**Issue by jancborchardt** [nextcloud/mail#2187]
On writing a new message via the "+ New message" button, the "to" recipient field should receive the focus so people can directly start typing the recipient.

The code in question is at https://github.com/nextcloud/mail/blob/master/src/components/Composer.vue#L96 → the autofocus needs to be removed from the subject and moved to the "to" field, and tested if it works. (Because it did not when it was on the subject field.)

**Comment by ChristophWurst** [comment]
Why would that actually be the first input to focus? Who doesn't start with the recipient?

**Comment by jancborchardt** [comment]
Good point. You are right, it should focus the "to" field first. :) Changed the title and text accordingly.
