### ISSUE TITLE
Support of new version in at least n-1 nextcloud version

### ISSUE THREAD

**Issue by Flaburgan** [nextcloud/mail#2195]
Congratulations for the just released v18.

If I get it correctly, it unfortunately looks like this new version is only available for users running nextcloud v17, released less than one month ago. Is there any reason to be that aggressive about nextcloud dependency? I run my own nextcloud using the snap package and it is usually months behind the last release. I'm sure I'm not the only one in that case. Supporting at least the previous stable version of nextcloud would make your last version accessible to many more users.

**Comment by ChristophWurst** [comment]
> If I get it correctly, it unfortunately looks like this new version is only available for users running nextcloud v17, released less than one month ago. Is there any reason to be that aggressive about nextcloud dependency?

The general answer is: I release this app for the versions I test on, which is usually the latest stable and the current development version. If there were more people that helped test, I'd be more than happy to widen this range.

The specific answer right now: the latest code depends on an API that was just added to Nextcloud 17. So, even if we wanted to support older versions, there is not technical way. Except not adding new features to the app until the API is available for all non-EOL major versions. But that only scales for apps that are *done*, as in, not under heavy development. And this app is under very heavy development right now. Keeping the feature PRs coming *and* maintaining multiple stable versions for x major Nextcloud versions is something I can't do with the time available.

So, yeah, I totally see your point and I do understand that this isn't ideal. If you and others are available to occasionally help with testing/reviewing patches, it would be possible to wide the support range.

In any case, thanks a lot for taking the time to write the feedback. I highly appreciate it!

**Comment by ChristophWurst** [comment]
also cc @wdfee who also recently brought this up :)

**Comment by Flaburgan** [comment]
>his app is under very heavy development right now

Yeah I noticed that, thank you for your work as many things still need to be done on it. But that's also the reason why I'm so eager about being able to use the new version.

I suspected that if you targeted something as recent as nextcloud 17 it was because of a new API, and I also understand the time constraints you have. I can gladly take more time to submit bug reports when I found some but... for that I would need to run the last version :p Back to the beginning.

I'm sure you had that in mind, I just wanted to give you some feedback, as I got stuck with the v11 for months because [v16 was taking a long time](https://github.com/nextcloud/nextcloud-snap/issues/972) to be [released](https://github.com/nextcloud/nextcloud-snap/releases). Thank you for what you're doing anyway ;)

**Comment by ChristophWurst** [comment]
I guess this can be closed. We will always support version ranges as far as possible. But if there is a blocker for a new feature then we'll bump the min version.

With v1.x there've been also a lot more backports to stable releases. So you get some of the essential fixes for older versions as well.
