### ISSUE TITLE
[0.18.0] Blank page after update

### ISSUE THREAD

**Issue by delete-exe** [nextcloud/mail#2206]
**### Expected behavior**
I should see my five email post inboxes and accounts when clicking on the mail app (0.18.0) in my 17.0.0.9 Ubuntu 19.10 based Nextcloud.

**### Actual behavior**
I only see a white, blank page inframe of my NC.

**### Mail app**
Updated this morning from working 0.17.0 to 0.18.0.

****Mailserver or service:** (e.g. Outlook, Yahoo, Gmail, Exchange,...)**
Hotmail, Web.de, GMX, Google, Strato

**### Server configuration**
**Operating system**: Ubuntu 19.10
**Web server:** Apache 2
**Database:** MariaDB 10.3.18
**PHP version:** 7.3.11
**Nextcloud Version:** 17.0.0.9

**#### Client configuration**
Chrome, Edge, Firefox, IE11
**Operating system:** Windows 10 19.03

Updatet the host system, restarted the Ubuntu host system, restarted the web server, deactivated and removed the mail app, restarted and re-installed it. Flushed al the temporary files on several systems and Browsers. Still a blank, white page.

**Comment by ChristophWurst** [comment]
Check your nextcloud.log. Does it contain anything related to the issue?

**Comment by delete-exe** [comment]
No, unfortunately the nextcloud.log is empty regarding this issue. I have a lot of info about other apps, but no warnings or errors with the subject mail.

**Comment by ChristophWurst** [comment]
Then check the webserver/php error logs. Blank page ususaly means something's badly broken.

**Comment by delete-exe** [comment]
Just the mail app? Strange. All other apps working correctly and fast.
_apachectl configtest_ doesn't show anything.

The error log has: 
cat: /etc/ntp.conf: No such file or directory
[Lots of GET]
127.0.0.1 - - [29/Oct/2019:16:05:29 +0100] "GET /server-status?auto HTTP/1.1" 200 1503 "-" "-"
127.0.0.1 - - [29/Oct/2019:16:05:30 +0100] "GET /server-status?auto HTTP/1.1" 200 1504 "-" "-"
127.0.0.1 - - [29/Oct/2019:16:05:31 +0100] "GET /server-status?auto HTTP/1.1" 200 1505 "-" "-"
93.240.173.102 - - [29/Oct/2019:16:05:28 +0100] "GET /cron.php HTTP/1.1" 200 998 "https://www.MYDOMAIN.com/index.php/apps/mail/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/64.0.3282.140 Safari/537.36 Edge/18.17763"
127.0.0.1 - - [29/Oct/2019:16:05:32 +0100] "GET /server-status?auto HTTP/1.1" 200 1506 "-" "-"
127.0.0.1 - - [29/Oct/2019:16:05:33 +0100] "GET /server-status?auto HTTP/1.1" 200 1507 "-" "-"

I've started the web server now a couple of times. No change, still blank.

**Comment by ChristophWurst** [comment]
No HTTP500?

**Comment by ChristophWurst** [comment]
Anything in the browser console? Have you inspected the returned HTML? Is it *completely* empty?

**Comment by mw80** [comment]
Same issue here with Edge browser. 

Console: 
SCRIPT1028: SCRIPT1028: Expected identifier, string or number
mail.js (170,30)

**Comment by ChristophWurst** [comment]
Which browser is this specifically?

**Comment by mw80** [comment]
Microsoft Edge 44.17763.771.0
Microsoft EdgeHTML 18.17763

**Comment by ChristophWurst** [comment]
Found it.

**Comment by delete-exe** [comment]
Just the add that I can reproduce this with any browser I use: Chrome, IE, Edge, Firefox, Opera … on any device.

**Comment by ChristophWurst** [comment]
Well, the issue @mw80 will be fixed with #2212.

For yours I still got no answer to https://github.com/nextcloud/mail/issues/2206#issuecomment-547506210.
