### ISSUE TITLE
[0.18.0] App Upgrade available but update do not work

### ISSUE THREAD

**Issue by ralfi** [nextcloud/mail#2209]
### Question

My NC 17 shows me that the update to 0.18 is avaible but the mail app self could not be upgraded. I know that there are some probs with the new version but how can i disable this announcement in my config?

**Comment by ChristophWurst** [comment]
Please ask at https://help.nextcloud.com/c/support :)

**Comment by ralfi** [comment]
Thanks, after upgrade nextcloud docker image everything works ...
