### ISSUE TITLE
Unified inbox should be labeled "Unified inbox"

### ISSUE THREAD

**Issue by jancborchardt** [nextcloud/mail#2217]
Currently the unified inbox is just called "Inbox", which is a bit confusing or unclear. Ideally it should be labeled "Unified inbox" so that you directly know what it is. :)

@ChristophWurst if you point out the code where this needs to be changed, this would be a great good first issue.

**Comment by StCyr** [comment]
Can be fixed easily, but what's strange is that this folder has a `name` property which doesn't seem to be used:

```
                folders: {
                        [UNIFIED_INBOX_UID]: {
                                id: UNIFIED_INBOX_ID,
                                accountId: 0,
                                isUnified: true,
                                specialUse: ['inbox'],
                                specialRole: 'inbox',
here ===>                       name: t('mail', 'All inboxes'), // TODO,
                                unread: 0,
                                folders: [],
                                envelopes: [],
                                searchEnvelopes: [],
                        },
```

**Comment by jancborchardt** [comment]
Ah interesting, right it was called "All inboxes", remember now. :D Must have fell over during some rewrite @ChristophWurst?

**Comment by ChristophWurst** [comment]
Yeah, @StCyr, I found out the same when @jancborchardt first opened the ticket. Didn't have the time to check where it's coming from. Guess our logic to localize (translate) mailboxes then magically makes it an *Inbox* because of the special use. In that logic, we could just add an ``if`` for the case of finding the ``isUnified === true``.
