### ISSUE TITLE
Avatars in "Sent" mails are all the same of yourself

### ISSUE THREAD

**Issue by jancborchardt** [nextcloud/mail#2224]
The avatars in "Sent" are of very limited use cause they are all of yourself :D

Instead, in the Sent folder the avatars should be the one of the first recipent.
![sent folder avatars all the same](https://user-images.githubusercontent.com/925062/68418897-7737ef80-0199-11ea-8fdc-ff071a26a5c6.png)

**Comment by ChristophWurst** [comment]
:man_facepalming:

**Comment by ChristophWurst** [comment]
cc @StCyr

**Comment by StCyr** [comment]
Didn't I fix that?

**Comment by StCyr** [comment]
should be fixed by https://github.com/nextcloud/mail/pull/2020

**Comment by StCyr** [comment]
> 
> 
> should be fixed by #2020

Oh no, I've just fixed the label not the avatar?!?

**Comment by ChristophWurst** [comment]
Yep ;)

**Comment by StCyr** [comment]
I've a patch but it can't show a local user's avatar (because it's using recipients' email addresses to generate the avatar)

Is it possible to easily find a user's ID based on his email address?

**Comment by ChristophWurst** [comment]
It should be done just like the avatars in other folders
