### ISSUE TITLE
Open attachments with the viewer app

### ISSUE THREAD

**Issue by szaimen** [nextcloud/mail#2225]
### Feature Request
It would be really nice beeing able to open attachments with the viewer app.

#### Summary
Now that https://github.com/nextcloud/viewer/pull/271 is implemented this could be consideres imo.

**Comment by ChristophWurst** [comment]
@skjnldsv do it!

**Comment by skjnldsv** [comment]
No! :grin:

**Comment by szaimen** [comment]
Maybe caching could help? 
So maybe you could implement a setting to enable automatically downloading all attached files to appdata? And then view them the normal way with the viewer?

**Comment by szaimen** [comment]
> More seriously, it will require a new api to be able to open the viewer differently than from a dav endpoint :)
> Any clue how we should do this @ChristophWurst ?
> Because we require a lot of infos. mimetype, direct download url, previews links (if it's a file supported by the IPreview api)

Maybe @juliushaertl has ideas to share on this topic?

**Comment by szaimen** [comment]
> More seriously, it will require a new api to be able to open the viewer differently than from a dav endpoint :)
> Any clue how we should do this @ChristophWurst ?
> Because we require a lot of infos. mimetype, direct download url, previews links (if it's a file supported by the IPreview api)

Maybe @juliushaertl has some ideas to share on this topic?

**Comment by juliushaertl** [comment]
> So maybe you could implement a setting to enable automatically downloading of all attached files to appdata? And then view them the normal way with the viewer?

The viewer also won't work with appdata in its current state, just for files that are located in the user directory (though webdav) Also we cannot just expose appdata as not all files in there should be available to all users.

**Comment by szaimen** [comment]
> The viewer also won't work with appdata in its current state, just for files that are located in the user directory (though webdav) Also we cannot just expose appdata as not all files in there should be available to all users.

Then maybe they should get cached for each user in his/her user folder:
Data/Username/mail/
Would that be possible?

**Comment by ChristophWurst** [comment]
IMO we should rather make the viewer more versatile so it can also work with arbitrary (local and/or from an URL) data than doing some other hacks. Then it will be a lot easier to integrate in other apps as well.

**Comment by skjnldsv** [comment]
> IMO we should rather make the viewer more versatile so it can also work with arbitrary (local and/or from an URL) data than doing some other hacks. Then it will be a lot easier to integrate in other apps as well.

Agree :)
Is providing an array of fileinfo (path, filename, mime...) would work for you Christoph?

I'm concern about trying to support two technologies in the viewer. Not sure about having this dual dav/array thing :thinking: 
Does it bother anyone else? Does it seems ok to you ?

**Comment by mario** [comment]
@skjnldsv doesn't DAV provide this anyway? So you can abstract it on top as a Map and then have providers (like DAV) which would fill in all the data.

**Comment by szaimen** [comment]
Would the viewer work for mail attachments as soon as https://github.com/nextcloud/mail/pull/2064 is implemented?

**Comment by ChristophWurst** [comment]
No, #2064 won't change anything on the front-end.

**Comment by ChristophWurst** [comment]
Let's continue in https://github.com/nextcloud/mail/issues/5701. The Viewer can't be used for this as @GretaD found out.

**Comment by skjnldsv** [comment]
Or that require some stuff to be adapted from the viewer and dav endpoint :thinking:

**Comment by ChristophWurst** [comment]
Can someone elaborate?
