### ISSUE TITLE
Avatars broken

### ISSUE THREAD

**Issue by jancborchardt** [nextcloud/mail#223]
They work in Contacts itself, but in the Mail app only the icon for broken image is shown for contacts with a picture. In the mail list as well as in the »to« dropdowns.

@nextcloud/mail these are the errors:
```
http://localhost/nextcloud/remote.php/dav/addressbooks/users/jan/contacts/f6dc8fc0-1369-4fbe-a21b-c067d04fb805.vcf?photo Failed to load resource: net::ERR_RESPONSE_HEADERS_MULTIPLE_CONTENT_DISPOSITION
http://localhost/nextcloud/remote.php/dav/addressbooks/users/jan/contacts/a941b37e-b632-4cd2-8221-beae1a6c2a7c.vcf?photo Failed to load resource: net::ERR_RESPONSE_HEADERS_MULTIPLE_CONTENT_DISPOSITION
```
cc @Henni @irgendwie @nextcloud/contacts as well

**Comment by ChristophWurst** [comment]
> http://localhost/nextcloud/remote.php/dav/addressbooks/users/jan/contacts/a941b37e-b632-4cd2-8221-beae1a6c2a7c.vcf?photo Failed to load resource: net::ERR_RESPONSE_HEADERS_MULTIPLE_CONTENT_DISPOSITION

Looks like a server bug. Could you please take a screenshot of the network tab's response headers?

**Comment by jancborchardt** [comment]
@ChristophWurst like this?
![capture du 2016-12-05 23-55-07](https://cloud.githubusercontent.com/assets/925062/20905958/490b496e-bb46-11e6-9154-33e4c1f453d7.png)
The two requests are the two avatars (no other in the view) which fail.

**Comment by jancborchardt** [comment]
Might very well be related to make failing, although it happened before and I only did make to try and fix it: https://github.com/nextcloud/contacts/issues/47

**Comment by ChristophWurst** [comment]
Could you please try with `curl` and post your full output (I hope it's an error)?
``curl -u user:user http://localhost:8080/remote.php/dav/addressbooks/users/user/contacts/8e3f4413-9f59-40aa-a127-b523f8ea2705.vcf?photo`` (of course, replace the URL with yours)

**Comment by ChristophWurst** [comment]
Nvm, can now reproduce here too.

**Comment by ChristophWurst** [comment]
This is what I get:
```
< HTTP/1.1 200 OK
< Date: Thu, 08 Dec 2016 10:10:08 GMT
< Server: Apache/2.4.10 (Debian)
< Strict-Transport-Security: max-age=15768000; includeSubDomains; preload
< Set-Cookie: oc7434cf7ac3=s0b91qt9j1puu6te2pvc7699d7; path=/; HttpOnly
< Expires: Thu, 19 Nov 1981 08:52:00 GMT
< Cache-Control: no-store, no-cache, must-revalidate, post-check=0, pre-check=0
< Pragma: no-cache
< Set-Cookie: oc_sessionPassphrase=dxMcNcDJ2kXlgyPV1GY%2Fa2JLpyFp1Tj5A6%2FJlRGbD2LkC5PXNbNMHuF%2BzKbZrVSurV%2BBn%2BoKIhGp%2Fvk5Mr6%2F9J3LdZdD8%2F55MU3%2FrdMiHaFtnsmT0EnoovLRjhgMICMc; path=/; secure; httponly
< Content-Security-Policy: default-src 'none';
< Set-Cookie: xxx
< Set-Cookie: yyy
< Set-Cookie: zzz
< Content-Disposition: attachment
< Content-Disposition: attachment; filename*=UTF-8''608a86f9-fc49-4f1b-b263-1459bb04ae9e.vcf; filename="608a86f9-fc49-4f1b-b263-1459bb04ae9e.vcf"
< X-Content-Type-Options: nosniff
< X-XSS-Protection: 1; mode=block
< X-Robots-Tag: none
< X-Frame-Options: SAMEORIGIN
< X-Download-Options: noopen
< X-Permitted-Cross-Domain-Policies: none
< Content-Length: 3612
< Content-Type: image/jpeg
<
```

**Comment by ChristophWurst** [comment]
It's a server bug: https://github.com/nextcloud/server/issues/1992

**Comment by ChristophWurst** [comment]
This is actually a duplicate of https://github.com/nextcloud/mail/issues/131

**Comment by jancborchardt** [comment]
Whoops, sorry!
