### ISSUE TITLE
Error deleting mail from search view

### ISSUE THREAD

**Issue by jancborchardt** [nextcloud/mail#225]
1. search for something
2. try to delete an email from the resulting list

```
TypeError: this.replyComposer is undefined[show more]  message.js:127:4
[message] "delete" Array [ Object, Object, Object ]  backbone.radio.js:159:7
DELETE 
XHR 
http://localhost/nextcloud/index.php/apps/mail/accounts/-1/folders/YWxsLWluYm94ZXM%3D/messages/WzEsMTcyMTVd [HTTP/1.1 412 Precondition failed 42 ms]
[ui] "error:show" Array [ "Error while deleting message." ]  backbone.radio.js:159:7

```

@nextcloud/mail can you reproduce?

**Comment by ChristophWurst** [comment]
> @nextcloud/mail can you reproduce?

No 😉 



> 412 Precondition failed

Maybe the greatly feared CSRF-check has struck again? Are you able to reproduce after refreshing the page? 🙊

**Comment by jancborchardt** [comment]
This seems to be fixed now, probably with the bunch of PRs recently. :)
