### ISSUE TITLE
Open Attachment directly with build-in viewer

### ISSUE THREAD

**Issue by schiessle** [nextcloud/mail#2276]
### Feature Request

I talked recently with some Nextcloud Mail users and they had a nice idea. At the moment I have two options for attachments: "Download" or "Save to Files". It would be nice to also have a "Open" button for all file types where a build-in viewer exists so that you can directly look at the file without the need to first store it somewhere. This could be a image, video and PDF but also office documents in case of OnlyOffice or Collabora is installed.

#### Summary

Detect which document types can be opened directly within Nextcloud and provide a "open" action for these kind of attachments so that the user can directly view them without the need of first download/store them somewhere.

**Comment by ChristophWurst** [comment]
Dup of https://github.com/nextcloud/mail/issues/2225 :)
