### ISSUE TITLE
Autologin for user authentication with IMAP

### ISSUE THREAD

**Issue by sim6** [nextcloud/mail#229]
Hello,

Firstly, thanks for your work.

I am using the nextcloud with user authentication with IMAP. Please, could you add support to direct access to mail app without login to IMAP server again, like autologin feature of rainloop app?

Thanks again.

**Comment by ChristophWurst** [comment]
Hi,

thank you for reporting this. I've implemented most of this feature in https://github.com/nextcloud/mail/pull/28. I'll have to finish my work in the Nextcloud server. If all goes well it could be available with NC12 :-)

**Comment by sim6** [comment]
Ok, thanks.
