### ISSUE TITLE
mail not working with gmail

### ISSUE THREAD

**Issue by magrinicristian** [nextcloud/mail#2291]
i have configured with successfull the client mail with my account gmail. But when i try to open the inbox the system load in a infinite loop the list of mail without opening

Can help me?

**Comment by ChristophWurst** [comment]
Yes, I might. But please open a proper bug report with the info asked for in the template: https://github.com/nextcloud/mail/issues/new?assignees=&labels=bug%2C+0.+to+triage&template=bug.md&title=
