### ISSUE TITLE
Flag messages as spam/ham (not spam) [$15]

### ISSUE THREAD

**Issue by Quix0r** [nextcloud/mail#23]
An easy and common way to move messages to "Junk" folder or from there back to "Inbox" folder.

Original ticket: #15

**Comment by ChristophWurst** [comment]
@GretaD possibly something for you to work on?

I think we need these things (can be done in separate PRs)

1) Visual distinction of spam mails: all emails that have the spam flag should have a distinguishable styling so a user knows to treat the message with caution. I think this is particularly helpful for when the IMAP server flags the message for you but does not move it to a dedicated junk folder. Then the spam messages will still show with your other messages.
2) Make it possible to mark a message as spam/not spam via the action menu\*
3) Move flagged messages to a dedicated junk/spam mailbox

\* interesting enough the IMAP specification has a flag `junk` and `notjunk`, so there are three possible states: undefined, junk and not junk. We might want to do a quick research on how other clients handle this.

**Comment by GretaD** [comment]
> @GretaD possibly something for you to work on?
> 
> I think we need these things (can be done in separate PRs)
> 
> 1. Visual distinction of spam mails: all emails that have the spam flag should have a distinguishable styling so a user knows to treat the message with caution. I think this is particularly helpful for when the IMAP server flags the message for you but does not move it to a dedicated junk folder. Then the spam messages will still show with your other messages.

In short, to have another icon smth like this: [spam icon](https://image.flaticon.com/icons/svg/1000/1000965.svg) after we mark an email as spam? And add more styling except the icon(different color of the text or smth?)?
After we(@nextcloud/designers ) decide for the the icon and other styling, i can start right away with it.

**Comment by Bugsbane** [comment]
I would suggest red text, which suggests not safe, but making it faded as these are not the emails a user would be wanting to read first, so we don't want to give them the strongest visual emphasis.

An icon would help as well. To be honest there doesn't seem to be a universal or even particularly great icon for spam.

Personally I would suggest not going with the exclamation with an octogon around it, as this kind of thing is typically more associated with error messages. If you want to signify either something dangerous or something that you don't want more of, either using the [triangle with an exclamation mark icon](https://imageog.flaticon.com/icons/png/512/10/10190.png?size=1200x630f&pad=10,10,10,10&ext=png&bg=FFFFFFFF) or a [circle with a bar icon](https://thumbs.dreamstime.com/b/block-cancel-email-spam-icon-vector-flat-illustration-block-cancel-email-spam-icon-108630173.jpg) respectively.

**Comment by jancborchardt** [comment]
> In short, to have another icon smth like this: [spam icon](https://image.flaticon.com/icons/svg/1000/1000965.svg) after we mark an email as spam? And add more styling except the icon(different color of the text or smth?)?
> After we(@nextcloud/designers ) decide for the the icon and other styling, i can start right away with it.

We do have `icon-junk`, so this is the one we should use. :) It is like icon-error and that is fine, cause it’s warning people to open a message. It could overlay a corner of the avatar (like the "Important" marker). Additionally we could show it in red so it’s more obvious.

**Comment by ChristophWurst** [comment]
> There is a **[$15 open bounty](https://www.bountysource.com/issues/37490538-flag-messages-as-spam-ham-not-spam?utm_campaign=plugin&utm_content=tracker%2F44154351&utm_medium=issues&utm_source=github)** on this issue

@GretaD :money_mouth_face:

**Comment by GretaD** [comment]
> > There is a **[$15 open bounty](https://www.bountysource.com/issues/37490538-flag-messages-as-spam-ham-not-spam?utm_campaign=plugin&utm_content=tracker%2F44154351&utm_medium=issues&utm_source=github)** on this issue
> 
> @GretaD

First of all we did it together ;)
secondly, the link doesnt work so i guess its not available anymore, but if its still available I'm fine to transfer the amount to another ticket.

**Comment by ChristophWurst** [comment]
Just claim it and put it onto another ticket indeed :)

And please send an email to support@bountysource.com about the broken link https://www.bountysource.com/issues/37490538-flag-messages-as-spam-ham-not-spam

For me it returns

```
{"error":"Internal server error."}
```

**Comment by ChristophWurst** [comment]
Oh wow, their website issues have been going on for two weeks already. And that is not the only time that happened recently https://twitter.com/Bountysource/status/1255733844805734400
