### ISSUE TITLE
Add "Create new folder"-Button to save to files

### ISSUE THREAD

**Issue by Kakiaki** [nextcloud/mail#2312]
### Feature Request

I would like to have the possibility to create a folder from the mailapp.
![2019-12-02_16-44-20](https://user-images.githubusercontent.com/58434670/69973206-6756c580-1523-11ea-9b02-0cdc08ca0d1f.png)

The core function Copy/Move has this plus icon. Possibly you could use the function and add it to the file handler.

![chrome_2019-12-02_16-45-21](https://user-images.githubusercontent.com/58434670/69973188-5dcd5d80-1523-11ea-8cef-a5af11b17f15.png)

**Comment by ChristophWurst** [comment]
Good point!

Since we use the same file picker, this option *should* be available for our app as well.

**Comment by ChristophWurst** [comment]
For the dev that want to look into this: https://github.com/nextcloud/mail/blob/1e23d041ffc6a147dc378b26d0768c60952fb756/src/components/MessageAttachment.vue#L135-L140

**Comment by Kakiaki** [comment]
I am pushing here for my own sake. 
Would love to see the feature after the fixed "Save all attachment" function (ty for that Christoph)

**Comment by StCyr** [comment]
This works on 1.8.1
