### ISSUE TITLE
Wrong folders encoding

### ISSUE THREAD

**Issue by ValentinBilokobylkyi** [nextcloud/mail#2313]
### Expected behavior
Tell us what should happen
We need to get folder names have cyrillic name. Something like "Вхідні" (Inbox in Ukrainian), but getting folders like "ÐÐ¸Ð´Ð°Ð»ÐµÐ½Ñ". When you click it you get only loading

Mail app version: 0.17.0
Mailserver: MS Exchange 2013

#### Client configuration
Browsers: all

[Screen](https://files.sies.gov.ua/s/9H8MDA3ZXJ5CDTo)

**Comment by ChristophWurst** [comment]
Duplicate of https://github.com/nextcloud/mail/issues/1758
