### ISSUE TITLE
No more warnings on Redirects

### ISSUE THREAD

**Issue by Heracles31** [nextcloud/mail#2318]
### Expected behavior
Tell us what should happen

When an e-mail contains a link, clicking it should present the user with a warning message about that he is leaving the server and going to wherever the link points to.

This behavior was the way the mail app was working so far.

### Actual behavior
Tell us what happens instead

Since my last update, the mail app stopped presenting the warning and now takes the user right to the final destination. The warning was a good protection against phishing scams and various email attacks. Even basic users were able to observe the warning presented and recognize that this was not where they expected to go.

For a professional guy, clicking the link was also safe and a simpler way to decode the malicious link received by mail.

### Mail app

**Mail app version:** (see apps admin page, e.g. 0.5.3)

Latest (0.20.0)

**Mailserver or service:** (e.g. Outlook, Yahoo, Gmail, Exchange,...)

Using a local IMAP service based on Dovecot

### Server configuration

**Operating system**: (e.g. Debian 8)

Alpine / Docker / Official Nextcloud Docker

**Web server:** (e.g. Apache, Nginx,...)

Apache

**Database:** (e.g. MariaDB, SQLite or PostgreSQL)

Maria

**PHP version:** (e.g. 7.0)

**Nextcloud Version:** (see admin page, e.g. 13.0.2)

17.0.1

#### Client configuration
**Browser:** (e.g. Firefox 48)

Chrome

**Operating system:** (e.g. Arch Linux)

Windows 10 and Mac OS X

**Comment by ChristophWurst** [comment]
Not a bug. The bug was that we didn't redirect automatically. This was a regression. See https://github.com/nextcloud/mail/pull/2153 for details.
