### ISSUE TITLE
PHP updated but mail on nextcloud wont open.

### ISSUE THREAD

**Issue by dpaoliveira** [nextcloud/mail#2323]
Hello, I updated my php version to php 7.3, but the mail box wont install, can you please help me.

Error: https://snipboard.io/m3RApc.jpg

**Comment by ChristophWurst** [comment]
Hi,

please see https://help.nextcloud.com/c/support for support. I think you installed php7.3 but apache still uses 7.1. You might have to disable the module or restart the web server.

Cheers
