### ISSUE TITLE
Emails with special characters (äöüß...) are not shown in the combined Mailbox

### ISSUE THREAD

**Issue by msbt** [nextcloud/mail#233]
### Steps to reproduce
1. Add multiple email accounts
2. Receive mails with "Umlaute" or other special characters in the subject line
3. Don't see them in the combined mailbox, if you go to the mailbox where you received it, it will be shown

### Expected behaviour
See all mails

### Actual behaviour
See only mails without special chars

### Mail app

**Mail app version:** Can't check now, but should be the latest stable

**Mailserver or service:** Hosted & own

**Transport security - IMAP:** TLS

**Transport security - SMTP:** TLS

**Number of accounts:** 3

**Mail app version build date:** (only if you are using a Nightly Build)

### Server configuration
**Operating system**: Ubuntu 16.04

**Web server:** Nginx

**Database:** MariaDB

**PHP version:** 7.something

**Updated from an older version or fresh install:** fresh

**List of activated apps:** Gallery, Documents, News, Mail, Contacts, Calendar, Audioplayer

#### Client configuration
**Browser:** Firefox 50

**Operating system:** Win7 Professional

I would also like to mention that drafts still don't save äöü either (mentioned [here](https://github.com/nextcloud/mail/issues/9) - as soon as you save the draft and open it again, all those characters have disappeared and makes texts unusable/readable.

**Comment by plastikschnitzer** [comment]
Now they show up in the combined mailbox, but there is no avatar aside the email.

Saving drafts with special characters does not work, the draft just does not exist.

**Comment by plastikschnitzer** [comment]
Edit: The avatar issue is not related to this problem.

**Comment by plastikschnitzer** [comment]
I was able to rebuild the problem again:

Steps to reproduce/result:
1. Create new folder "test"
2. Moved email with an "ä" in the subject into the folder
3. try to load the folder "test" inside the mail app
4. results in error message "Could not load Test :'-|"

Any folder which contained this email (inbox, combined inbox, other individual folders) were not able to load.

IMAP-log:


>> Sat, 04 Mar 2017 13:52:29 +0000
>> Connection to: imap://serverdomain.net/
>> Server connection took 0.0017 seconds.
S: * OK [CAPABILITY IMAP4rev1 LITERAL+ SASL-IR LOGIN-REFERRALS ID ENABLE IDLE STARTTLS LOGINDISABLED] Dovecot ready.
C: 1 STARTTLS
S: 1 OK Begin TLS negotiation now.
>> Command 1 took 0.0015 seconds.
>> Successfully completed TLS negotiation.
C: 2 CAPABILITY
S: * CAPABILITY IMAP4rev1 LITERAL+ SASL-IR LOGIN-REFERRALS ID ENABLE IDLE AUTH=PLAIN
S: 2 OK Pre-login capabilities listed, post-login capabilities have more.
>> Command 2 took 0.0029 seconds.
C: 3 AUTHENTICATE PLAIN [INITIAL CLIENT RESPONSE (username: user@domain.tld)]
S: 3 OK [CAPABILITY IMAP4rev1 LITERAL+ SASL-IR LOGIN-REFERRALS ID ENABLE IDLE SORT SORT=DISPLAY THREAD=REFERENCES THREAD=REFS THREAD=ORDEREDSUBJECT MULTIAPPEND URL-PARTIAL CATENATE UNSELECT CHILDREN NAMESPACE UIDPLUS LIST-EXTENDED I18NLEVEL=1 CONDSTORE QRESYNC ESEARCH ESORT SEARCHRES WITHIN CONTEXT=SEARCH LIST-STATUS BINARY MOVE SPECIAL-USE QUOTA] Logged in
>> Command 3 took 0.0148 seconds.
C: 4 EXAMINE Test
S: * FLAGS (\Answered \Flagged \Deleted \Seen \Draft)
S: * OK [PERMANENTFLAGS ()] Read-only mailbox.
S: * 1 EXISTS
S: * 0 RECENT
S: * OK [UIDVALIDITY 1465485645] UIDs valid
S: * OK [UIDNEXT 2] Predicted next UID
S: * OK [HIGHESTMODSEQ 1] Highest
S: 4 OK [READ-ONLY] Examine completed (0.000 + 0.000 secs).
>> Command 4 took 0.0043 seconds.
C: 5 UID SORT RETURN (ALL COUNT) (DATE) US-ASCII UNDELETED
S: * ESEARCH (TAG "5") UID ALL 1 COUNT 1
S: 5 OK Sort completed (0.002 + 0.000 secs).
>> Command 5 took 0.0031 seconds.
C: 6 UID FETCH 1 (ENVELOPE FLAGS RFC822.SIZE INTERNALDATE BODYSTRUCTURE BODY.PEEK[HEADER.FIELDS (IMPORTANCE LIST-POST X-PRIORITY CONTENT-TYPE)])
S: * 1 FETCH (UID 1 FLAGS (\Seen) RFC822.SIZE 14748 INTERNALDATE "03-Mar-2017 13:11:33 +0100" ENVELOPE ("Fri, 03 Mar 2017 13:11:15 +0100" "=?utf-8?Q?Thanatos_Informationen_M=C3=A4rz_2017?=" (("Name" NIL "name" "icloud.com")) (("Name" NIL "name" "icloud.com")) (("Name" NIL "name" "icloud.com")) ((NIL NIL "Undisclosed recipients" NIL)(NIL NIL NIL NIL)) NIL NIL NIL "<namehash@icloud.com>") BODYSTRUCTURE (("text" "plain" ("charset" "utf-8") NIL NIL "quoted-printable" 4215 89 NIL NIL NIL NIL)("text" "html" ("charset" "utf-8") NIL NIL "quoted-printable" 7489 114 NIL NIL NIL NIL) "alternative" ("boundary" "Apple-Mail=_A3B7B568-D567-44F5-9125-32E9409A6E78") NIL NIL NIL) BODY[HEADER.FIELDS (IMPORTANCE LIST-POST X-PRIORITY CONTENT-TYPE)] {102}
S: [LITERAL DATA: 102 bytes]
S: )
S: 6 OK Fetch completed (0.002 + 0.000 secs).
>> Command 6 took 0.0242 seconds.
C: 7 LOGOUT
S: * BYE Logging out
S: 7 OK Logout completed.
>> Command 7 took 0.0025 seconds.

**Comment by plastikschnitzer** [comment]
Its solved in the upcoming 0.7 release, tested it successfully with an email with "ä" as subject.

**Comment by ChristophWurst** [comment]
Awesome, @plastikschnitzer. Thanks for testing :)

**Comment by msbt** [comment]
thanks indeed!
