### ISSUE TITLE
App not loading when installing from app store

### ISSUE THREAD

**Issue by juliushaertl** [nextcloud/mail#234]
### Steps to reproduce
1. Install mail 0.6.2 from the Nc app store
2. Open the mail app

### Expected behaviour
It should load

### Actual behaviour
It doesn't load

##### Browser log

![2016-12-13-133506_1916x754_scrot](https://cloud.githubusercontent.com/assets/3404133/21140668/ab619b10-c139-11e6-8791-dd2c3631949d.png)

**Comment by juliushaertl** [comment]
vendor/.../build/ directories are not existent in the released packages.

**Comment by ChristophWurst** [comment]
Could the markdown editor somehow interfere with our js files? Apparently something breaks requirejs.

> vendor/.../build/ directories are not existent in the released packages.

Which file/directory is needed?

**Comment by ChristophWurst** [comment]
Oh, do you have debug mode enabled? Indeed some files are missing, but it should not affect the bundled mail.min.js file as it includes everything.

**Comment by juliushaertl** [comment]
@ChristophWurst Ah thanks. It works fine after disabling files_markdown and debug mode. 

> Which file/directory is needed?

When debug mode is enabled it tries to fetch js/vendor/backbone.radio/build.backbone.radio.js and js/vendor/ical.js/build/ical.min.js which do not exist.

The following errors appear with disabled debug mode and enabled files_markdown app:

![2016-12-13-141038_728x107_scrot](https://cloud.githubusercontent.com/assets/3404133/21141609/6a0cce46-c13e-11e6-9416-aa642815dd77.png)
![2016-12-13-141044_672x146_scrot](https://cloud.githubusercontent.com/assets/3404133/21141614/6d162c5e-c13e-11e6-944f-f649dd4cc2b2.png)

**Comment by ChristophWurst** [comment]
> The following errors appear with disabled debug mode and enabled files_markdown app:

I'd say that's a bug of the files_markdown app. Its js should not be loaded on other app's pages.

> When debug mode is enabled it tries to fetch js/vendor/backbone.radio/build.backbone.radio.js and js/vendor/ical.js/build/ical.min.js which do not exist.

I messed up the rsync command in the Makefile, apparently excludes are not relative paths but patterns. I wanted to exclude the build directory of the app, but that also excluded *any* build dir in the directory tree.

**Comment by eppfel** [comment]
Jep, had exactly the same. Deactivated `debug` now.

**Comment by plastikschnitzer** [comment]
Same here, mail app version 0.6.2. is not loading after update, I tested in ownCloud 9.1.3, this is the error log from the browser console: 

Die Ressource von "https://domain.tld/apps/files/" wurde auf Grund eines nicht übereinstimmenden MIME-Typs blockiert (X-Content-Type-Options: nosniff).
Error: Script error for "ical", needed by: service/davservice
http://requirejs.org/docs/errors.html#scripterror

**Comment by ChristophWurst** [comment]
> Die Ressource von "https://domain.tld/apps/files/" wurde auf Grund eines nicht übereinstimmenden MIME-Typs blockiert (X-Content-Type-Options: nosniff).
> Error: Script error for "ical", needed by: service/davservice
> http://requirejs.org/docs/errors.html#scripterror

Is debug mode enabled? Do you use the markdown app too?

**Comment by plastikschnitzer** [comment]
Loglevel was set to 2 in config.php.

But I think my testing cloud is broken, I did updates to ownCloud 9.1.3 in production clouds which also included mail update to 0.6.2 and here the app is loading. 

My nextCloud is not up to date (yet) …

**Comment by ChristophWurst** [comment]
> Loglevel was set to 2 in config.php.

Log level and debug more are two different config values. The latter is enabled/disabled by ``'debug' => true,`` in config.php.

**Comment by plastikschnitzer** [comment]
Yes, debug is set to true.
I have to re-order all my testing and production clouds. They are too many and I am loosing the overview … ;-)

**Comment by ChristophWurst** [comment]
I've uploaded a fresh nightly build that contains the fix for this issue to https://apps.nextcloud.com/apps/mail 🚀🚤💨

**Comment by Sanookmakmak** [comment]
I can't enable Mail 0.6.2 (cloned from Githaub)

Error: it makes the server unstable

![auswahl_002](https://cloud.githubusercontent.com/assets/24833757/22205428/21a54af8-e177-11e6-9b51-242573a1659b.png)

**Comment by ChristophWurst** [comment]
> I can't enable Mail 0.6.2 (cloned from Githaub)
> 
> Error: it makes the server unstable

That's no surprise. You're missing a lot of stuff if you just clone the repo. Check the readme on how to set things up for development. If you just want to use the app either use a release or a nightly build.

**Comment by Sanookmakmak** [comment]
I don't know how to install a nightly build, sorry.
How can i achive that?

**Comment by ChristophWurst** [comment]
1. download the archive
2. unpack it in the `apps` dir of your Nextcloud (make sure to remove any previous version first)

Installing apps via the app store is the recommended way though :-)

**Comment by ChristophWurst** [comment]
any further questions should be asked in the forum https://help.nextcloud.com. This is the issue tracker. Thanks

**Comment by Sanookmakmak** [comment]
OK.

```
cd /var/www/nextcloud/apps/
rm -rf mail
git clone https://github.com/nextcloud/mail
```

makes the server unstable as mentioned above.

Unpacking the zip file

![auswahl_003](https://cloud.githubusercontent.com/assets/24833757/22222381/e5a149d6-e1b6-11e6-8ee8-77374064eabe.png)

to
`
/var/www/nextcloud/apps`

creates a folder

`/var/www/nextcloud/apps/mail-master`

Next step is the update from 0.6.2 to 0.6.2

![auswahl_004](https://cloud.githubusercontent.com/assets/24833757/22222607/d17b488e-e1b7-11e6-8ed3-359ff3edb813.png)

After updating and enabling the mail app, it still does not work. Still 2 hourglasses. debug=false in config.php, Mardown editor is disabled.

![auswahl_006](https://cloud.githubusercontent.com/assets/24833757/22222933/41374668-e1b9-11e6-9698-53389da753b4.png)

With enbled Markdown editor

![auswahl_007](https://cloud.githubusercontent.com/assets/24833757/22223094/d8045e50-e1b9-11e6-996f-7fa7dea88b04.png)
![auswahl_008](https://cloud.githubusercontent.com/assets/24833757/22223096/d95999aa-e1b9-11e6-9f7e-e9d39b5d03db.png)
![auswahl_009](https://cloud.githubusercontent.com/assets/24833757/22223238/72f972ec-e1ba-11e6-9bba-dbbe84c986eb.png)

Disabling Piwik does not make an enhancement.

**Comment by ChristophWurst** [comment]
Please use a release from the appstore apps.nextcloud.com. Downloading the source zip is more or less the same as doing a git cone – you're missing many important files.

**Comment by Sanookmakmak** [comment]
Also not working. Still 2 hourglasses.
![auswahl_001](https://cloud.githubusercontent.com/assets/24833757/22243191/8a33475a-e226-11e6-87f1-98dc87819cd9.png)

**Comment by PeterEdens** [comment]
I tried enabling the app on a Spreedbox running Nextcloud 12 and I get the two hourglasses:
﻿
jsxc.js:183 [WARN] Unable to create user prefix
jsxc.js:183 [WARN] Unable to create user prefix
daemon.js:42 Spreedbox: plugin loaded
daemon.js:42 Spreedbox: login detected
daemon.js:93 Uncaught ReferenceError: spreedboxNotify is not defined
    at daemon.js:93
    at HTMLDocument.<anonymous> (daemon.js:116)
    at j (jquery.min.js:sourcemap:2)
    at Object.fireWith [as resolveWith] (jquery.min.js:sourcemap:2)
    at Function.ready (jquery.min.js:sourcemap:2)
    at HTMLDocument.I (jquery.min.js:sourcemap:2)
