### ISSUE TITLE
How to add mailvelope?

### ISSUE THREAD

**Issue by Merith-TK** [nextcloud/mail#2346]
### Question

What are the steps to add mailvelop to my nextcloud mail client, i have it installed on my browser.

#### Summary

I dont know how to add the extension into my nextcloud email instance

**Comment by ChristophWurst** [comment]
Hi,

you  have to whitelist the domain in the mailvelope settings. But now that you ask I gave it a go and something seems to have broken. We use a new editor. But Mailvelope also had a bigger change. Either of the two might have broken the integration.

Let me know if you have any more insights once the domain is added.

**Comment by Merith-TK** [comment]
The domain is added, it took about 3 refreshes (`ctrl+f5`) to load, but it works

**Comment by tacruc** [comment]
I have the same problem, but multiple tries of ctrl+f5 didn't solved it. Viewing the original message  Mailvelope ask me if it should be decrypted.

**Comment by ChristophWurst** [comment]
Mailvelope is not very reliable. Tested it recently, and it chokes a bit on our rich text editor. Like the mailvelope bubble renders countless times. You notice that by the shadow getting darker and darker.

**Comment by tacruc** [comment]
@ChristophWurst  So there is not much we can do?
I'm not realy using mailvelope, I'm just developing the gpgmailer app and I just wanted to check if the encripted emails can be read, with nextcloud mail in combination with mailvelope.
Turns out that it is complicated. (You can read them, if you go to the menu and click view original message)

**Comment by meichthys** [comment]
This still seems to be an issue. Is there a reason why this issue has been closed?

**Comment by ChristophWurst** [comment]
Because this ticket is about the old integration. https://github.com/nextcloud/mail/pull/3052 is the new one. Things work differently now.

If you face a problem then please file a new report. Thanks.

**Comment by meichthys** [comment]
Ok, Thanks, it does work eventually when viewing the source of the email. I was incorrectly assuming it would work without needing to view source.
