### ISSUE TITLE
Error sending your message, but mail was sent

### ISSUE THREAD

**Issue by brrrrrrrt** [nextcloud/mail#2350]
### Expected behavior
If email has been sent successfully, no error should show up.

### Actual behavior
When sending a message this error shows up:
![Bildschirmfoto von 2019-12-12 21-11-06](https://user-images.githubusercontent.com/4489013/70745709-a73c5a80-1d24-11ea-944f-58b9974bac2a.png)

despite the message has been sent. every time you hit "retry" another mail goes out.

### Mail app

**Mail app version:** 0.20.1

**Mailserver or service:** 
local Postfix (Debian Stretch) with and without authentification, without encryption, SSL, STARTTLS
external Postfix (Debian Jessie) SSL, STARTTLS
external Postfix (Debian Buster) SSL, STARTTLS

### Server configuration

**Operating system**: Debian 9.11 "Stretch" 

**Web server:** Apache

**Database:** MariaDB

**PHP version:** 7.3.12

**Nextcloud Version:** 17.0.1

#### Client configuration
**Browser:** Chromium Version 79.0.3945.79

**Operating system:** Arch Linux

I already removed the account and created it from scratch, tried all possible variations of smtp-settings, with and without authentification (local mailserver), different mailservers, the result was always the same.

i also noticed, saving the password seems to work, but whenever i go back to the account settings the password field of the smtp server is empty and has a red border. on every change to the account i also have to re-enter the smtp password. 

Maybe this is related to #2000 as we have also Cyrus and the mailfolder-structure is a total mess:

![Bildschirmfoto von 2019-12-12 21-57-11](https://user-images.githubusercontent.com/4489013/70748507-6d6e5280-1d2a-11ea-8150-647bd377c9eb.png)

it looks like it does not recognise the folders correctly, like the one for sent mail, drafts, etc.

all other mailclients like outlook2010/2013/2016/365, thunderbird, roundcubemail work without problems.

this is our xlist configuration part:

```
xlist-archive: Archive
xlist-drafts: Entwurf
xlist-sent: Gesendet
xlist-spam: Spam
xlist-trash: Papierkorb
xlist-flagged: Flagged

autocreate_inbox_folders: Archive|Entwurf|Gesendet|Papierkorb
autocreate_subscribe_folders: Archive|Entwurf|Gesendet|Papierkorb
```

**Comment by brrrrrrrt** [comment]
i did some more testing

if i use list to return special-use i get:
```
 a LIST INBOX "*" RETURN (SPECIAL-USE)                                                                                                                          
* LIST (\HasChildren) "." INBOX                                                                                                                                
* LIST (\HasChildren \Archive) "." INBOX.Archive                                                                                                               
* LIST (\HasNoChildren \Archive) "." INBOX.Archive.2013                                                                                                        
* LIST (\HasNoChildren) "." INBOX.Archive.2014                                                                                                                 
* LIST (\HasNoChildren) "." INBOX.Archive.2015                                                                                                                 
* LIST (\HasNoChildren) "." INBOX.Archive.2016                                                                                                                 
* LIST (\HasNoChildren) "." INBOX.Archive.2017
* LIST (\HasNoChildren) "." INBOX.Archive.2018
* LIST (\HasNoChildren \Drafts) "." INBOX.Entwurf
* LIST (\HasNoChildren \Sent) "." INBOX.Gesendet
* LIST (\HasNoChildren \Trash) "." INBOX.Papierkorb
* LIST (\HasNoChildren \Junk) "." INBOX.Spam
* LIST (\HasNoChildren) "." INBOX.fail2ban
```
the \Archive Flag has been set by the cyrus at the time of the account creation, after that the subfolders were added using mailclient. it looks like cyrus does not automatically set the flag to subfolders, i also do not know of any mail client capable of doing this. out of curiosity i used telnet/imap commands to set the flag to all the Archive.* subfolders, to see what happens in the app.

list with special use now returns this:
```
a LIST INBOX "*" RETURN (SPECIAL-USE)
* LIST (\HasChildren) "." INBOX
* LIST (\HasChildren \Archive) "." INBOX.Archive
* LIST (\HasNoChildren \Archive) "." INBOX.Archive.2013
* LIST (\HasNoChildren \Archive) "." INBOX.Archive.2014
* LIST (\HasNoChildren \Archive) "." INBOX.Archive.2015
* LIST (\HasNoChildren \Archive) "." INBOX.Archive.2016
* LIST (\HasNoChildren \Archive) "." INBOX.Archive.2017
* LIST (\HasNoChildren \Archive) "." INBOX.Archive.2018
* LIST (\HasNoChildren \Drafts) "." INBOX.Entwurf
* LIST (\HasNoChildren \Sent) "." INBOX.Gesendet
* LIST (\HasNoChildren \Trash) "." INBOX.Papierkorb
* LIST (\HasNoChildren \Junk) "." INBOX.Spam
* LIST (\HasNoChildren) "." INBOX.fail2ban
```

and voila! 
the mail app now recognizes Draft, Trash and Sent, great!
even sending mail works without error,... 

BUT now all Archive-Subfolders are shown with the same name:
![Bildschirmfoto von 2019-12-12 23-39-20](https://user-images.githubusercontent.com/4489013/70754955-d3fa6d00-1d38-11ea-9ecc-f7744fbe2900.png)

i think a structured archive, or sent folder will not be that unusual and the app can not rely on having the special use flag on every subfolder. further more the app should not throw a more specific error if it is unable to "find the sent folder" (it should be able to check that even **before** sending the message)

**Comment by brrrrrrrt** [comment]
on a second server i use dovecot with a INBOX-namespace configured to maintain backwards compatibility to clients with the former courier mailserver. 

the special folders are recognised correctly, no problem with sending mail, but the subfolders are still not recognized correctly.

the output of the list command is a little bit different though:
```
a LIST INBOX "*" RETURN (SPECIAL-USE)
* LIST () "." INBOX
* LIST (\UnMarked) "." INBOX.sudkraft
* LIST (\UnMarked) "." INBOX.Bld
* LIST (\UnMarked \Trash) "." INBOX.Trash
* LIST (\UnMarked \Junk) "." INBOX.Junk
* LIST (\UnMarked \Drafts) "." INBOX.Drafts
* LIST (\UnMarked \Sent) "." INBOX.Sent
* LIST (\UnMarked \Archive) "." INBOX.Archiv
* LIST (\UnMarked) "." INBOX.Archiv.2009
* LIST (\UnMarked) "." INBOX.Archiv.2011
* LIST (\UnMarked) "." INBOX.Archiv.2012
* LIST (\UnMarked) "." INBOX.Archiv.2013
* LIST (\UnMarked) "." INBOX.Archiv.Bld
* LIST (\UnMarked) "." INBOX.Archiv.Bld.2010
* LIST (\UnMarked) "." INBOX.Archiv.Bld.2012
* LIST (\UnMarked) "." INBOX.Archiv.Bld.2011
* LIST (\UnMarked) "." INBOX.Archiv.Bld.2013
```
this is how the folders look like in the mail app on this server:
![Bildschirmfoto von 2019-12-13 00-10-18](https://user-images.githubusercontent.com/4489013/70756522-145bea00-1d3d-11ea-8856-c7d1c7e96278.png)

on an older mailserver using dovecot without INBOX namespace subfolders are nested but always include the parent foldername, like this:
![Bildschirmfoto von 2019-12-13 00-28-03](https://user-images.githubusercontent.com/4489013/70757361-93522200-1d3f-11ea-8333-8aca619a162a.png)

**Comment by ChristophWurst** [comment]
The Nextcloud mail app offers an extensive logging system to make it easier identifying and tracking down bugs. Please enable [debug mode](https://docs.nextcloud.com/server/13/developer_manual/general/devenv.html#enabling-debug-mode) and set the log [level to debug](https://docs.nextcloud.com/server/13/admin_manual/configuration_server/logging_configuration.html) in your admin settings. Then, try to reproduce your issue and take another look at `data/nextcloud.log`, `data/horde_imap.log` and `data/horde_smtp.log`. Sanitize the logs before posting. They might contain sensitive information like passwords.
