### ISSUE TITLE
No pointer cursor when hovering attachment images

### ISSUE THREAD

**Issue by schiessle** [nextcloud/mail#2365]
If I receive a attachment it looks like this:

![image](https://user-images.githubusercontent.com/1589737/70907212-959ad180-2008-11ea-9a8b-95b93d8d6bba.png)

There are the two buttons of the obvious actions "download" and "save to files" but the whole attachment is also clickable. 

First, the option to click on the attachment is only indicated by a mouse pointer change over the empty area, there is no hover effect if I point at the picture but I can still click it.

Second, the click triggers a download. Would it make sense to change it to "save to files" as the default behavior? Is there any way to configure the behavior?

**Comment by ChristophWurst** [comment]
Expected behavior. You click the file and you can view it. Super useful for images like you have in your example while we don't have a viewer integration #2225.



> there is no hover effect if I point at the picture but I can still click it

That is the only actual bug here. @GretaD maybe something for you? :)



> Second, the click triggers a download. Would it make sense to change it to "save to files" as the default behavior? Is there any way to configure the behavior?

IMO no. cc @nextcloud/mail

**Comment by GretaD** [comment]
> Expected behavior. You click the file and you can view it. Super useful for images like you have in your example while we don't have a viewer integration #2225.
> 
> > there is no hover effect if I point at the picture but I can still click it
> 
> That is the only actual bug here. @GretaD maybe something for you? :)

Should I add the hover and the mouse pointer also at the image area, just like it is on the empty aria? Is this is what you expect me to do @ChristophWurst ?

**Comment by ChristophWurst** [comment]
Yes!

**Comment by ChristophWurst** [comment]
Basically everything inside the grey border is clickable. The cursor should reflect that.

**Comment by jancborchardt** [comment]
> > Second, the click triggers a download. Would it make sense to change it to "save to files" as the default behavior? Is there any way to configure the behavior?
> 
> IMO no. cc @nextcloud/mail

Agreed. Clicking should trigger a "view" type action, and until we have Viewer support the closest to that is downloading the file.
