### ISSUE TITLE
Hide 'mark all as read' action from unified inbox

### ISSUE THREAD

**Issue by ChristophWurst** [nextcloud/mail#2370]
The server doesn't know about the unified account/inbox. We should remove the action and only offer it for individual mailboxes.

cc @mario 

@GretaD maybe something for you? :)

**Comment by mario** [comment]
What I would prefer is that we iterate over the existing mailboxes and trigger "Mark as read" on each one rather than hiding this functionality. Maybe with a nice indeterminate progress bar next to the action while it's running :)

This is highly beneficial, at least from my POV.

**Comment by mario** [comment]
Why would you do this to me? XD Any plan to bring it back with proper functionality?

**Comment by ChristophWurst** [comment]
Sure. but first it's important to remove the broken action :)
