### ISSUE TITLE
can't open mail app after update to 0.21

### ISSUE THREAD

**Issue by tsonntig** [nextcloud/mail#2372]
### Expected behavior
the mail app opens

### Actual behavior
failure

### Mail app

**Mail app version: 0.21

**Mailserver or service: gmail,mail.de

`Server configuration detail

Operating system: Linux 5.4.2-gnu-1 #1 SMP PREEMPT Fri, 06 Dec 2019 00:53:00 +0000 x86_64

Webserver: Apache/2.4.41 (Unix) mod_wsgi/4.6.8 Python/3.8 OpenSSL/1.1.1d (fpm-fcgi)

Database: pgsql PostgreSQL 12.1 on x86_64-pc-linux-gnu, compiled by gcc (GCC) 9.2.0, 64-bit

PHP version: 7.4.0

Modules loaded: Core, date, libxml, openssl, pcre, zlib, ctype, dom, fileinfo, filter, hash, json, mbstring, pcntl, SPL, PDO, session, posix, readline, Reflection, standard, SimpleXML, Phar, tokenizer, xml, xmlreader, xmlwriter, mysqlnd, cgi-fcgi, curl, exif, ftp, gd, iconv, imagick, intl, ldap, mysqli, pdo_mysql, pdo_pgsql, pgsql, sockets, zip, apcu, Zend OPcache

Nextcloud version: 17.0.1 - 17.0.1.1

Updated from an older Nextcloud/ownCloud or fresh install:

Where did you install Nextcloud from: unknown

<details><summary>Signing status</summary>

Array ( )

</details>

<details><summary>List of activated apps</summary>

Enabled:
 - accessibility: 1.3.0
 - activity: 2.10.1
 - admin_audit: 1.7.0
 - apporder: 0.8.0
 - bruteforcesettings: 1.4.0
 - calendar: 1.7.1
 - carnet: 0.18.12
 - checksum: 0.4.3
 - cloud_federation_api: 1.0.0
 - comments: 1.7.0
 - contacts: 3.1.6
 - dav: 1.13.0
 - federatedfilesharing: 1.7.0
 - federation: 1.7.0
 - files: 1.12.0
 - files_external: 1.8.0
 - files_fulltextsearch: 1.3.6
 - files_pdfviewer: 1.6.0
 - files_rightclick: 0.15.1
 - files_sharing: 1.9.0
 - files_trashbin: 1.7.0
 - files_versions: 1.10.0
 - files_videoplayer: 1.6.0
 - firstrunwizard: 2.6.0
 - flowupload: 0.1.7
 - fulltextsearch: 1.3.6
 - fulltextsearch_elasticsearch: 1.4.0
 - groupfolders: 5.0.4
 - logreader: 2.2.0
 - lookup_server_connector: 1.5.0
 - mail: 0.21.0
 - maps: 0.1.2
 - nextcloud_announcements: 1.6.0
 - notifications: 2.5.0
 - oauth2: 1.5.0
 - password_policy: 1.7.0
 - previewgenerator: 2.2.0
 - privacy: 1.1.0
 - provisioning_api: 1.7.0
 - recommendations: 0.5.0
 - serverinfo: 1.7.0
 - sharebymail: 1.7.0
 - social: 0.2.101
 - spreed: 7.0.2
 - support: 1.0.1
 - survey_client: 1.5.0
 - systemtags: 1.7.0
 - text: 1.1.1
 - theming: 1.8.0
 - twofactor_backupcodes: 1.6.0
 - updatenotification: 1.7.0
 - viewer: 1.2.0
 - workflowengine: 1.7.0
Disabled:
 - encryption
 - gallery
 - user_ldap

</details>

<details><summary>Configuration (config/config.php)</summary>

{
    "trusted_proxies": "***REMOVED SENSITIVE VALUE***",
    "overwrite.cli.url": "https:\/\/sonntig.spdns.de\/",
    "overwriteprotocol": "https",
    "overwritehost": "sonntig.spdns.de",
    "htaccess.RewriteBase": "\/",
    "instanceid": "***REMOVED SENSITIVE VALUE***",
    "passwordsalt": "***REMOVED SENSITIVE VALUE***",
    "secret": "***REMOVED SENSITIVE VALUE***",
    "datadirectory": "***REMOVED SENSITIVE VALUE***",
    "dbtype": "pgsql",
    "version": "17.0.1.1",
    "dbname": "***REMOVED SENSITIVE VALUE***",
    "dbhost": "***REMOVED SENSITIVE VALUE***",
    "dbport": "",
    "dbtableprefix": "oc_",
    "dbuser": "***REMOVED SENSITIVE VALUE***",
    "logtimezone": "UTC",
    "installed": true,
    "loglevel": 0,
    "memcache.local": "\\OC\\Memcache\\APCu",
    "updater.release.channel": "stable",
    "maintenance": false,
    "preview_libreoffice_path": "\/usr\/bin\/libreoffice",
    "appstore.experimental.enabled": true,
    "log_type": "file",
    "logfile": "\/data\/nextcloud\/nextcloud.log",
    "logdateformat": "F d, Y H:i:s",
    "log_rotate_size": 10485760,
    "theme": "",
    "preview_max_x": 512,
    "preview_max_y": 512,
    "preview_max_scale_factor": 10,
    "auth.bruteforce.protection.enabled": false,
    "activity_expire_days": 90,
    "has_rebuilt_cache": true
}

</details>

External storages: yes

<details><summary>External storage configuration</summary>

+----------+-----------------+---------+---------------------+---------------------------+-----------------+------------------+-------------------+-------+
| Mount ID | Mount Point     | Storage | Authentication Type | Configuration             | Options         | Applicable Users | Applicable Groups | Type  |
+----------+-----------------+---------+---------------------+---------------------------+-----------------+------------------+-------------------+-------+
| 1        | /Bildersammlung | Lokal   | Keine               | datadir: "\/data\/Bilder" | readonly: false |                  | family            | Admin |
+----------+-----------------+---------+---------------------+---------------------------+-----------------+------------------+-------------------+-------+

</details>

Encryption: no

User-backends:

OC\User\Database

Browser: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:68.0) Gecko/20100101 Firefox/68.0`

**LOG**

`[mail] Error: BadFunctionCallException: order is not a valid attribute at <<closure>>

 0. /srv/http/nextcloud/lib/public/AppFramework/Db/Entity.php line 146
    OCP\AppFramework\Db\Entity->setter("order", [1])
 1. /srv/http/nextcloud/lib/public/AppFramework/Db/Entity.php line 70
    OCP\AppFramework\Db\Entity->__call("setOrder", [1])
 2. /srv/http/nextcloud/lib/public/AppFramework/Db/QBMapper.php line 284
    OCP\AppFramework\Db\Entity::fromRow({id: 3,user_id:  ... 1})
 3. /srv/http/nextcloud/lib/public/AppFramework/Db/QBMapper.php line 321
    OCP\AppFramework\Db\QBMapper->mapRowToEntity({id: 3,user_id:  ... 1})
 4. /srv/http/nextcloud/apps/mail/lib/Db/MailAccountMapper.php line 59
    OCP\AppFramework\Db\QBMapper->findEntity(OC\DB\QueryBuilder\QueryBuilder {})
 5. /srv/http/nextcloud/apps/mail/lib/Service/AccountService.php line 86
    OCA\Mail\Db\MailAccountMapper->find("thomas", 3)
 6. /srv/http/nextcloud/apps/mail/lib/Controller/FoldersController.php line 96
    OCA\Mail\Service\AccountService->find("thomas", 3)
 7. /srv/http/nextcloud/lib/private/AppFramework/Http/Dispatcher.php line 170
    OCA\Mail\Controller\FoldersController->sync(3, "SU5CT1g=", "VTQ0ODUsVjE0MTc4NTY0ODgsSDExODU3", ["4484","4483"," ... "])
 8. /srv/http/nextcloud/lib/private/AppFramework/Http/Dispatcher.php line 99
    OC\AppFramework\Http\Dispatcher->executeController(OCA\Mail\Controller\FoldersController {}, "sync")
 9. /srv/http/nextcloud/lib/private/AppFramework/App.php line 126
    OC\AppFramework\Http\Dispatcher->dispatch(OCA\Mail\Controller\FoldersController {}, "sync")
10. /srv/http/nextcloud/lib/private/AppFramework/Routing/RouteActionHandler.php line 47
    OC\AppFramework\App::main("OCA\\Mail\\Cont ... r", "sync", OC\AppFramework\ ... {}, {accountId: "3", ... "})
11. <<closure>>
    OC\AppFramework\Routing\RouteActionHandler->__invoke({accountId: "3", ... "})
12. /srv/http/nextcloud/lib/private/Route/Router.php line 297
    undefinedundefinedcall_user_func(OC\AppFramework\ ... {}, {accountId: "3", ... "})
13. /srv/http/nextcloud/lib/base.php line 1000
    OC\Route\Router->match("/apps/mail/api/ ... c")
14. /srv/http/nextcloud/index.php line 42
    OC::handleRequest()

GET /apps/mail/api/accounts/3/folders/SU5CT1g=/sync?syncToken=VTQ0ODUsVjE0MTc4NTY0ODgsSDExODU3&uids[]=4484&uids[]=4483&uids[]=4482&uids[]=4481&uids[]=4480&uids[]=4479&uids[]=4478&uids[]=4477&uids[]=4476&uids[]=4475&uids[]=4474&uids[]=4473&uids[]=4472&uids[]=4471&uids[]=4470&uids[]=4469&uids[]=4468&uids[]=4467&uids[]=4466&uids[]=4465&uids[]=4464&uids[]=4463&uids[]=4462
from 31.16.248.77 by thomas at 2019-12-17T14:36:43+00:00`

**Comment by ChristophWurst** [comment]
Please share the output of ``php occ migrations:status mail``

**Comment by tsonntig** [comment]
`migrations:status mail                                    :(
App:                                                mail
Version Table
Name:                                 oc_migrations
Migrations
Namespace:                               OCA\Mail\Migration
Migrations
Directory:                               /srv/http/nextcloud/apps/mail/
lib/Migration
Previous
Version:                                   0190Date20191118160843
Current
Version:                                    0210Date20191212144925
Next Version:                                       Already at
latest migration step
Latest
Version:                                     0210Date20191212144925
Executed Migrations:                                11
Executed Unavailable Migrations:                    11
Available Migrations:                               11
New Migrations:                                     11
Pending Migrations:                                 None

`

**Comment by ChristophWurst** [comment]
Okay, that seems right. So the `oc_accounts` table should have the `ordered` column. Could you compare https://github.com/nextcloud/mail/blob/master/lib/Db/MailAccount.php to the local file on your machine.

It looks like this could be an issue with opcache. Restarting the webserver might help.

**Comment by tsonntig** [comment]
Thank you ! 
This was the right direction. After restarting php-fpm the mail app is working again.
It would be create if we have a better Error Message.

**Comment by ChristophWurst** [comment]
Yeah, sorry, this is out of scope for a php application. We have yet to find out when this happens. It's usually showing when you expect it the least …
