### ISSUE TITLE
Reply issues

### ISSUE THREAD

**Issue by jancborchardt** [nextcloud/mail#2373]
When you reply to an email, there are some small issues which are quite annoying when summed up:

- [x] The "To" field is focused, even though the recipient is already filled
- [x] You are prefilled in the "cc" field and need to manually remove yourself
- [ ] The text body has no space above and you need to insert newlines yourself. Expected would be focus on the first line, and 2 empty lines below until the original message.
- [ ] ~~If you are replying from the unified inbox, the wrong account is selected. This might be related to yourself being prefilled in cc~~ → separated out into https://github.com/nextcloud/mail/issues/2428

cc @nextcloud/mail I’d say this is some crucial polishing for 18.

**Comment by StCyr** [comment]
point "You are prefilled in the "cc" field and need to manually remove yourself" is to be resolved by https://github.com/nextcloud/mail/pull/2454

**Comment by ChristophWurst** [comment]
Yep, could also be a side effect of https://github.com/nextcloud/mail/pull/2447 as the reply recipient logic depends on the account used.

**Comment by StCyr** [comment]
Regarding the 2 last points ('The "To" field is focused, even though the recipient is already filled' and 'The text body has no space above and you need to insert newlines yourself. Expected would be focus on the first line, and 2 empty lines below until the original message.'),

It's easy to not set the focus on the 'To' field when it's already filled but it's more difficult to set the focus on the body: It seems ckeditor5 doesn't support the `startupFocus` config parameter anymore :(

See https://ckeditor.com/docs/ckeditor5/latest/api/index.html and https://ckeditor.com/docs/ckeditor4/latest/api/CKEDITOR_config.html#cfg-startupFocus

**Comment by ChristophWurst** [comment]
> The "To" field is focused, even though the recipient is already filled

@GretaD you can use https://github.com/ckeditor/ckeditor5/issues/714#issuecomment-351351518 at https://github.com/nextcloud/mail/blob/b2cce62492cd7bef397cfc668deb18ffe9ab2a61/src/components/TextEditor.vue#L111-L136 with an `if` only for replies ;)

**Comment by GretaD** [comment]
i can and i did :)

**Comment by jancborchardt** [comment]
Very nice! :) Can we also fix the issue of not having extra empty lines on the top when you reply? :balloon:

**Comment by GretaD** [comment]
> having extra empty lines on the top
