### ISSUE TITLE
"New message" button not working when composing a reply

### ISSUE THREAD

**Issue by jancborchardt** [nextcloud/mail#2374]
With latest master:

When you are composing a reply, clicking the "New message" button does nothing. Clicking it again shows an error in the console:
```
uncaught exception: Object
```

Instead, when you click the "New message" button, the current reply should be saved as draft and a new message composer should be opened.

**Comment by IchbinkeinReh** [comment]
Just tested this and its definitly fixed on master branch. Can someone please close this issue. If i understand correctly this was fixed by https://github.com/nextcloud/mail/pull/2480/
