### ISSUE TITLE
Some unnecessary spaces in sender/recipient subline

### ISSUE THREAD

**Issue by jancborchardt** [nextcloud/mail#2376]
In the subline of the heading, there are some unnecessary spaces:
![Spaces in recipients](https://user-images.githubusercontent.com/925062/71020048-2fa86a00-212e-11ea-93c6-c5104d77d471.png)

- [ ] Before the comma in the "to" list
- [ ] Same for the comma in the "cc" list
- [ ] Space before the closing parentheses of the "cc" list

@nextcloud/mail if someone points out where this would need to be changed, this would make for a nice "good first issue". :)

**Comment by GretaD** [comment]
The changes for the space before comma, should be done here: https://github.com/nextcloud/mail/blob/5f44f0373b295102d963357bc171d0aeb00084bb/src/components/Address.vue#L3

The space before the cc, should be done here: https://github.com/nextcloud/mail/blob/5f44f0373b295102d963357bc171d0aeb00084bb/src/components/Message.vue#L21

**Comment by StCyr** [comment]
Hmmm.... I had a quick look, and the problem seems to be a CSS problem: I can't see any blank space character in the text

**Comment by GretaD** [comment]
> Hmmm.... I had a quick look, and the problem seems to be a CSS problem: I can't see any blank space character in the text

its the space before the closing tag  </router-link>  and before cc we should add a space.

**Comment by jancborchardt** [comment]
> before cc we should add a space.

There’s no extra spaces needed, just things to be removed:

> Space before the **closing** parentheses of the "cc" list

**Comment by GretaD** [comment]
> > before cc we should add a space.
> 
> There’s no extra spaces needed, just things to be removed:

sorry, i read it wrong, so remove the space before the closing and not add after the opening :)
anyway, its the same line to be fixed.

**Comment by StCyr** [comment]
I don't see how things should be fixed: I don't see any superfluous blank space.

**Comment by StCyr** [comment]
> 
> 
> I don't see how things should be fixed: I don't see any superfluous blank space.

In the code, I mean (I do see the spaces in the UI)

**Comment by jancborchardt** [comment]
Is it maybe newlines which create the blank spaces?

**Comment by jancborchardt** [comment]
Removing the spaces in Address.vue as @GretaD mentioned in https://github.com/nextcloud/mail/issues/2376#issuecomment-567576722 does the trick! :)

**Comment by StCyr** [comment]
cool :-)
