### ISSUE TITLE
Newlines seem to be cut from drafts

### ISSUE THREAD

**Issue by jancborchardt** [nextcloud/mail#2377]
1. Write a draft or reply and save as draft
2. Go to drafts
3. Open the mail

You will see all newlines removed, effectively having the draft function not usable.

cc @nextcloud/mail @ChristophWurst @GretaD as this would be important to fix for 18.

**Comment by ChristophWurst** [comment]
Just to be sure I'm looking into the issue you described, please composer a new email with the content you had when this happened. But before closing the draft inspect the editor and copy the HTML structure. Usually that is a bunch of paragraphs. Or `br` if you use <kbd>Shift</kbd><kbd>Enter</kbd>.

**Comment by jancborchardt** [comment]
Hmmmm, here is it tested with all 3 Enter, Ctrl-Enter and Shift-Enter:

```
<div data-v-9d740ee6="" data-v-9872de0c="" name="body" class="message-body ck ck-content ck-editor__editable ck-rounded-corners ck-editor__editable_inline ck-blurred" dir="ltr" role="textbox" aria-label="Rich Text Editor, main" lang="en" contenteditable="true"><p data-placeholder="Write message …">Let’s see if this draft loses the newlines, I’ll use only Enter for these first ones</p><p>testing</p><p>testing</p><p>testing</p><p><br data-cke-filler="true"></p><p>Now let me check with some ctrl-Enter newlines</p><p>testing</p><p>testing</p><p><br data-cke-filler="true"></p><p>And here with some shift-enter<br>as this seems to work&nbsp;<br>testing</p><p><br data-cke-filler="true"></p></div>
```

Any and all newlines were lost, didn’t matter where they were. The initial opening of the draft looked a bit like this:
```
First line

Second line

Third line




Another line

another

another



Theser are the last block of lines with Shift-Enter
No extra empty lines between
Testing
```

But then when really opening the edit draft view, all newlines were lost.

**Comment by joris-willems** [comment]
still an issue
