### ISSUE TITLE
Message sending experience [$40]

### ISSUE THREAD

**Issue by jancborchardt** [nextcloud/mail#238]
Currently we show a small notification up top »Message sent!« and empty all the fields. This is very small and strange.

Instead let’s do this:
- Vanish all the fields by animating them upwards, like the text is being sent off. Mail.app does this for example.
- Replace them with an emptycontent view with a big checkmark icon saying »Mail sent to christoph@bla.com :-)«
- Second line should have a button »Send another message« which shows the new message form again. For replies, just make it say »Send another reply« and that fades in the reply fields again.

**Comment by tevon456** [comment]
was this issue fixed or is it still open?

**Comment by willianveiga** [comment]
@jancborchardt, could you please attach a gif with this animation that happens in Mail.app?

**Comment by rainerzufall** [comment]
just posted $10 more bounty

**Comment by ChristophWurst** [comment]
This was actually fixed with https://github.com/nextcloud/mail/pull/1237.
