### ISSUE TITLE
Mails not listed from individual Mailboxes' Inbox folders

### ISSUE THREAD

**Issue by nerdyanorak** [nextcloud/mail#2397]
### Expected behavior
Having multiple email accounts configured in the Mail app the combined Inbox is shown as well as the individual Inbox folders under each configured email account. Selecting the combined Inbox folder all mails of all email accounts' inboxes are shown in the right-side pane.

If I click on any of the individual email accounts' Inbox folders I expect that in the right-side pane only the emails of the selected Inbox are shown.

### Actual behavior
Selecting any of the individual email accounts' Inbox folders there is no change in the view of the right-side pane. I.e., if previously the combined Inbox was shown this will still be shown after clicking on the Inbox folder of an individual email account.

On the other hand, if I click on a different folder of such an individual email account, like Sent, Trash, Junk, Archive, etc. the content of those folders is listed in the right-side pane as expected. It is just the Inbox folder that behaves unexpectedly.

This used to work in earlier version of the Mail app and / or Nextcloud.

### Mail app

**Mail app version:** 0.17.0

**Mailserver or service:** Gmail and various email services from webhosting (stackmail.com, vmcaltendorf.ch)

### Server configuration

**Operating system**: CentOS 7

**Web server:** Apache

**Database:** MariaDB 10.3.21

**PHP version:** 7.3.12

**Nextcloud Version:** 16.0.4.1

#### Client configuration
**Browser:** Firefox 71.0, Chrome 79.0.3945.79

**Operating system:** Windows 10, opensuse leap 42.3, opensuse tumbleweed

**Comment by ChristophWurst** [comment]
> This used to work in earlier version of the Mail app and / or Nextcloud.

Do you have a version or time frame in mind?

Does the URL change when you navigate from unified to individual inbox? Could you open the browser console and network tab to see which URL(s) it uses to fetch the messages of individual inboxes?

**Comment by nerdyanorak** [comment]
Hi Christoph,

This was still working on the Production update channel for Nextcloud until the last 15.x.x version before switching to the 16.x.x version. Unfortunately I don't know what the corresponding Mail app versions were, but I always updated all enabled apps when they became available.

As soon having switched to the first 16.x.x Nextcloud version that feature in the Mail app did not work anymore. I only report this now because it did not get "magically" fixed ;)

Hope this helps.

**Comment by ChristophWurst** [comment]
so somehting after https://github.com/nextcloud/mail/releases/tag/v0.12.0 as that was the first version with support for 16. but also when the app received a new front-end.

Will try to get more info once you provided the information I asked in my other reply :)

**Comment by nerdyanorak** [comment]
Regarding your second question about URL. If I hover the mouse over individual mailboxes Inbox folder the URL changes. E.g. to

https://my.host.com/nextcloud/index.php/apps/mail/#/accounts/6/folders/SU5CT1g=

Whereas, the URL of the consolidated Inbox folder shows like:

https://my.host.com/nextcloud/index.php/apps/mail/#/accounts/0/folders/aW5ib3g=

**Comment by nerdyanorak** [comment]
Klicking on an individual mailbox's Inbox folder does not trigger any action within the browser console and network tab. But under the Inbox folder there is as well an Favourites folder, with URL

https://my.host.com/nextcloud/index.php/apps/mail/#/accounts/6/folders/SU5CT1gvRkxBR0dFRA==

Clicking this folder loads the content of it in the right-side pane as expected.

**Comment by ChristophWurst** [comment]
> Regarding your second question about URL. If I hover the mouse over individual mailboxes Inbox folder the URL changes. E.g. to

:+1: as expected



> Klicking on an individual mailbox's Inbox folder does not trigger any action within the browser console and network tab.

This is strange. So when you click the individual inbox, you stay on the same page? The active mailbox shows a little highlight in the navigation. Does it move from unified to individual inbox when you click it?

**Comment by nerdyanorak** [comment]
I think the problem is, that when I am clicking on an individuals mailbox's  Inbox folder it does not load the emails contained in the folder, but expands/collapses the folder tree under the Inbox folder (as I mentioned above these individual Inbox folders contain all a "Favourites" folder as well).  Hence, instead of the "loading emails from folder" action the "expand/collapse folder tree" action is carried out.
Unfortunately, there is no option in the UI available that would allow to remove these "Favourites" folders in order to check if this is really the problem. See attached screenshots.
![Nextcloud-Mail-Individual-Inbox-Collapsed](https://user-images.githubusercontent.com/56198893/71182014-908e8a00-2275-11ea-93ad-3713c66e2897.png)
![Nextcloud-Mail-Individual-Inbox-Expanded](https://user-images.githubusercontent.com/56198893/71182015-908e8a00-2275-11ea-89a5-61b6273851db.png)

**Comment by ChristophWurst** [comment]
Oh, I read your comment but in a wrong way. I see the problem now. This was actually fixed recently. Do you have any plans for an upgrade to Nextcloud 17? Then you'll get the latest and greatest Mail and this problem should be resolved :)

**Comment by nerdyanorak** [comment]
As soon 17 is available on the Production update channel. That's the reason for being on that channel to avoid issues as above as much as possible. There is still a new 16er version (16.0.7) available for update, which I am probably going to apply in the next few days.

**Comment by laurentiu2** [comment]
In 16.0.7 I get the same behavior. No individual inbox messages, instead it expands the folders..
Show all folders/collapse folders does nothing.
