### ISSUE TITLE
Generic moving of messages

### ISSUE THREAD

**Issue by Quix0r** [nextcloud/mail#24]
It should be possible to move messages from one folder (within same account) to another with only a few clicks.

Original ticket: #15

**Comment by jancborchardt** [comment]
So I decided to just pledge 50$ to this issue! https://www.bountysource.com/issues/37490593-generic-moving-of-messages

Consider funding it as well if you would like to see this implemented. :) Also cc @plastikschnitzer @seal20 @pierreozoux @MeCias @djibux @GIT-STATA who requested this before. :rocket:

**Comment by pierreozoux** [comment]
Added 30$ to the pot \o/

**Comment by ChristophWurst** [comment]
The high level design of the implementation should consist of a generic action on the server that allows to move message M1 from account A1 and folder F1 to account A2, folder F2.
The client-side can then use that action (~REST route) to move stuff around on different actions (e.g. popover menu or drag-and-drop).

**Comment by jancborchardt** [comment]
@connium @pierreozoux we just noticed that this Bounty hadn’t been paid out but @ChristophWurst solved it. :) Make sure to approve the claim at https://www.bountysource.com/issues/37490593-generic-moving-of-messages
