### ISSUE TITLE
gmail inbox is loading infinitely.

### ISSUE THREAD

**Issue by tmsd2001** [nextcloud/mail#2413]
Mail Version 0.21.0 and I think all other too.

I think i have a large inbox and Mail ist trying to load all emails from the there.
If I use a labelled folder the Mails are loading.

**Comment by ChristophWurst** [comment]
> I think i have a large inbox

Any rough numbers? On servers with poor IMAP capability support we indeed have to fetch a lot of data in order to sort by date. That could be the reason it runs into a timeout on your instance.

#2064 might help, but it will still be problematic on first import.

**Comment by tmsd2001** [comment]
imap.gmail.com at port 993 .
At the info box "18 unread from 76723"

**Comment by ChristophWurst** [comment]
> #2064 might help, but it will still be problematic on first import.

We fixed the problematic import in #2688, so please see https://help.nextcloud.com/t/call-for-testers-mail-v1-3/75825. We'd appreciate if you could help us test the upcoming release. I hope this helps with your problem :v:
