### ISSUE TITLE
About the iframe tag 

### ISSUE THREAD

**Issue by medivh-jay** [nextcloud/mail#2424]
### Feature Request
Can you make the iframe on the right adapt to the width and height of the right? the current iframe is very small, and the email display feels incomplete. In fact, there is a lot of blank space available.

#### Summary
Can you make the iframe on the right adapt to the width and height of the right? the current iframe is very small, and the email display feels incomplete. In fact, there is a lot of blank space available.

**Comment by medivh-jay** [comment]
It seems that class has a div named app-content-details, which limits the maximum width.

**Comment by jancborchardt** [comment]
This seems to be a duplicate of https://github.com/nextcloud/mail/issues/658 where there is a pull request in progress to fix it at https://github.com/nextcloud/mail/pull/2222 :)

**Comment by medivh-jay** [comment]
> 这似乎是[＃658](https://github.com/nextcloud/mail/issues/658)的副本，其中有一个提取请求正在进行中，将其修复为[＃2222](https://github.com/nextcloud/mail/pull/2222) :)
Indeed, thank you very much for your work
