### ISSUE TITLE
Inbox Content is empty

### ISSUE THREAD

**Issue by flonowa** [nextcloud/mail#243]
### Steps to reproduce
1. Open the app and go in the Inbox Folder
### Expected behaviour
Tell us what should happen
See the Content of my Mails
### Actual behaviour
Tell us what happens instead
When you go on all Mails in the Inbox the Content is empty and a circle spin but this bug is not in all folders. The sent Folder are ok!
### Mail app

**Mail app version:** (see apps admin page)
0.6.2
**Mailserver or service:** (e.g. Outlook, Yahoo, Gmail, Exchange,...)
Domainfactory
**Transport security - IMAP:** (None, SSL, TLS, STARTTLS) 
none SSL auto
**Transport security - SMTP:** (None, SSL, TLS, STARTTLS)
none SSL auto
**Number of accounts:**
2
**Mail app version build date:** (only if you are using a Nightly Build)

0.6.2
### Server configuration
**Operating system**:
Ubuntu 16.04
**Web server:**
Nginx
**Database:**
MariaDB
**PHP version:**
7
**Version:** (see admin page)

**Updated from an older version or fresh install:**
fresh install
**List of activated apps:**
collaboraonline
```
If you have access to your command line run e.g.:
sudo -u www-data php occ app:list
from within your server installation folder

"system": {
        "instanceid": "ocf1lv2u949m",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "cloud.mydomain.net"
        ],
        "datadirectory": "\/var\/www\/nextcloud_data",
        "overwrite.cli.url": "http:\/\/cloud.mydomain.net\/nextcloud",
        "dbtype": "mysql",
        "version": "9.1.2.2",
        "dbname": "nextcloud_db",
        "dbhost": "localhost",
        "dbport": "",
        "dbtableprefix": "oc_",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "logtimezone": "UTC",
        "installed": true,
        "memcache.local": "\\OC\\Memcache\\APCu",
        "theme": "",
        "loglevel": 0,
        "maintenance": false,
        "mail_smtpmode": "smtp",
        "mail_smtpsecure": "ssl",
        "mail_from_address": "flo",
        "mail_smtpauthtype": "LOGIN",
        "mail_smtpauth": 1,
        "mail_smtpport": "465",
        "mail_smtpname": "***REMOVED SENSITIVE VALUE***",
        "mail_smtppassword": "***REMOVED SENSITIVE VALUE***"
    }
}


**The content of config/config.php:**

<details>
```
If you have access to your command line run e.g.:
sudo -u www-data php occ config:list system
from within your server installation folder

or 

Insert your config.php content here
(Without the database password, passwordsalt and secret)
```
</details>

#### Client configuration
Chrome or Firefox doesent matter

**Operating system:**
Windows or Linux dosent matter
#### Logs
##### Web server error log
```
Insert your webserver log here
2016/12/15 00:16:53 [warn] 13471#13471: *75462 an upstream response is buffered to a temporary file /var/cache/nginx/proxy_temp/0/22/0000011220 while reading upstream, client: 95.91.209.134, server: cloud.mydomian.net, request: "GET /nextcloud/apps/theming/loginbackground?v=13 HTTP/2.0", upstream: "http://127.0.0.1:82/nextcloud/apps/theming/loginbackground?v=13", host: "cloud.mydomain.net"
2016/12/15 00:18:54 [warn] 13471#13471: *75462 an upstream response is buffered to a temporary file /var/cache/nginx/proxy_temp/1/22/0000011221 while reading upstream, client: 95.91.209.134, server: cloud.mydomain.net, request: "GET /nextcloud/apps/mail/js/vendor/requirejs/require.js?v=dcdd83cfbd196b5a80b0c609d859d92b HTTP/2.0", upstream: "http://127.0.0.1:82/nextcloud/apps/mail/js/vendor/requirejs/require.js?v=dcdd83cfbd196b5a80b0c609d859d92b", host: "cloud.mydomain.net"
2016/12/15 00:18:54 [warn] 13471#13471: *75462 an upstream response is buffered to a temporary file /var/cache/nginx/proxy_temp/2/22/0000011222 while reading upstream, client: 95.91.209.134, server: cloud.mydomain.net, request: "GET /nextcloud/apps/mail/js/mail.min.js?v=dcdd83cfbd196b5a80b0c609d859d92b HTTP/2.0", upstream: "http://127.0.0.1:82/nextcloud/apps/mail/js/mail.min.js?v=dcdd83cfbd196b5a80b0c609d859d92b", host: "cloud.´mydomain.net"

##### Server log (data/nextcloud.log)
<details>
```
Insert your server log here
```
</details>

##### Horde IMAP log (data/horde_imap.log)
<details>
```
Insert your horde IMAP log here, see https://github.com/nextcloud/mail#debug-mode
```
</details>

##### Horde SMTP log (data/horde_smtp.log)
<details>
```
Insert your horde SMTP log here, see https://github.com/nextcloud/mail#debug-mode
```
</details>

##### Browser log
<details>
```
Insert your browser log here, this could for example include:

a) The javascript console log
b) The network log 
c) ...
```
</details>

**Comment by duckunix** [comment]
Hello, I recently upgraded from 9.1.0.16 to 11.0.0.10.
I followed the direction from the read-me to clear out the database, disabled and deleted the app.
I get the same behavior as describe.  I cannot get in to configure anything.

**Comment by ChristophWurst** [comment]
Hi,

please provide the contents of log files (nextcloud.log, horde_imap.log) and your browser log. Thanks.

**Comment by ChristophWurst** [comment]
No response -> closing this now.
