### ISSUE TITLE
Undefined offset in socket.php line 1783

### ISSUE THREAD

**Issue by Rychu-Pawel** [nextcloud/mail#2431]
From time to time (like once a week) i'm seeing 
> Undefined offset: 11 at /srv/www/nextcloud/apps/mail/vendor/pear-pear.horde.org/Horde_Imap_Client/Horde/Imap/Client/Socket.php#1783

Where offset 11 is a random number. Do you know why and is it something I should be worry about?

**Comment by ChristophWurst** [comment]
Mind sharing the URL of the request that causes the warning?

**Comment by Rychu-Pawel** [comment]
How can I find that URL? I do not see any URL in the logs:
![obraz](https://user-images.githubusercontent.com/22656474/72260326-e48d5400-3612-11ea-8f0f-ec6e42ff5464.png)

**Comment by ChristophWurst** [comment]
Check `data/nextcloud.log` directly

**Comment by Rychu-Pawel** [comment]
All of them looks the same. And looks like all of them are only for one user (removed it from the example):
```
{
  "level": 3,
  "time": "2020-01-12T11:15:28+00:00",
  "app": "PHP",
  "method": "GET",
  "url": "\\/apps\\/mail\\/",
  "message": "Undefined offset: 11 at \\/srv\\/www\\/nextcloud\\/apps\\/mail\\/vendor\\/pear-pear.horde.org\\/Horde_Imap_Client\\/Horde\\/Imap\\/Client\\/Socket.php#1780",
  "userAgent": "Mozilla\\/5.0 (Android 10; Mobile; rv:68.0) Gecko\\/68.0 Firefox\\/68.0",
  "version": "17.0.2.1"
}
```
