### ISSUE TITLE
No folder creation or mail moving options

### ISSUE THREAD

**Issue by TheFoxStudio** [nextcloud/mail#2441]
Hello,

I noticed that I do have the option "create new folder" or "create new subfolder" but after doing so it does not show up in the list. After creating a folder I am not able to create another with the same name which makes me believe the folder was created somewhere in the background.
I also have no options for mails other then "Mark unread" and "Delete".

### Mail app
**Mail app version: 0.21.0
**Mailserver or service: Webmail from my Domain. Hoster is Ionos

### Server configuration
**Operating system: Ubuntu 18.04
**Web server: Apache2
**Database:** Mysql 5.7
**PHP version: 7.2
**Nextcloud Version: 17.0.2

#### Client configuration
**Browser: Firefox 71
**Operating system: Windows 10

**Comment by StCyr** [comment]
>I noticed that I do have the option "create new folder" or "create new subfolder" but after doing so it >does not show up in the list. After creating a folder I am not able to create another with the same >name which makes me believe the folder was created somewhere in the background.

I guess the folder appears once you reload the page. does it?

>I also have no options for mails other then "Mark unread" and "Delete".

For the "mail moving option": I've work on this a bit. If someone wants to help, it's here: https://github.com/nextcloud/mail/pull/1753

**Comment by TheFoxStudio** [comment]
Actually it did not. That was my first thought. Just refreshing the site. Today I checked and the Sub-folders are there but regular folders are still not. And it took multiple hours till they appeared. I worked on the system the whole day yesterday, checking it ever 30-ish minutes. Super strange.

I am gonna look into #1753. Drag and drop would be a neat addition to the app. 
Thanks for your reply!

**Comment by ChristophWurst** [comment]
Huh, I think we create the folder on IMAP but don't update the database cache. Thus you don't see it but can also not update it. After 2h a miracle happens and the new folder shows. Was that the case? :D

**Comment by TheFoxStudio** [comment]
That sounds a lot like what could have happend. So I see this problem as solved. 

I am just very confused in gerneral. For every problem with the mail app that I search it seems like there are fixes and these problems were from earlier versions and got fixed, e.g. in Dark Mode all my mail text is still black and I do not have the "move to folder" option for any mail at all. Is there anything I can do about this?
I love nextcloud and basically de-googled completly with it so now I'd love to make it run smooth to lurk my wife away from google as well with a shiny nice nextcloud. :D

Thanks for the feedback so far tho!

**Comment by ChristophWurst** [comment]
Sounds like you ran into rare regressions. Like stuff that we fixed but that got broken again. If there is no open ticket for it, feel free to create one. But always make sure you're using the latest version :) Also sometimes things are fixed for the master branch and not released yet.

**Comment by TheFoxStudio** [comment]
Alright. I will have a look at the open issues / possible fixes and their release date and then might open something. It's working which is the most important bit, everything else I am sure will be figured out over time :)

**Comment by StCyr** [comment]
> and I do not have the "move to folder" option for any mail at all

Does a such thing even exist in nextcloud/mail???

**Comment by ChristophWurst** [comment]
Not yet

**Comment by TheFoxStudio** [comment]
> 
> 
> > and I do not have the "move to folder" option for any mail at all
> 
> Does a such thing even exist in nextcloud/mail???

How do you move mails into the folders then?
That might be a case of missinformation then as I read it and assumed this is the current native way to move mails.

**Comment by StCyr** [comment]
> How do you move mails into the folders then?

You can't.

If you're interested, you might have a look at my PR: https://github.com/nextcloud/mail/pull/1753

**Comment by henry-nicolas** [comment]
@ChristophWurst what is blocking the merge of @StCyr PR?

**Comment by ChristophWurst** [comment]
Four unresolved issues.
