### ISSUE TITLE
Message pane on big screen does not use all screen space

### ISSUE THREAD

**Issue by feutl** [nextcloud/mail#2449]
The message pane on previous and the latest published release does not make use of the full screen size.

NC: 17.0.2
NC Mail: 0.21.1
Firefox: 71

![2020-01-08 08_39_53-](https://user-images.githubusercontent.com/8522012/71959467-1bb6cc00-31f3-11ea-845e-b88fd70e1f2f.png)

**Comment by ChristophWurst** [comment]
Not a bug a design decision. See https://github.com/nextcloud/mail/pull/2429#issuecomment-571901535

**Comment by feutl** [comment]
thanks, actually the width is fine, the height is what disturbs me most. and if the width stays this way, I would appreciate a wider email overview pane :) or an adjustable one.

**Comment by ChristophWurst** [comment]
Then see #658 and https://github.com/nextcloud/mail/pull/2222 :)

**Comment by bitsandnumbers** [comment]
@ChristophWurst And what about a way to resize the email overview pane as suggested above ? The issues you mention do not cover this aspect...

**Comment by ChristophWurst** [comment]
^ @jancborchardt

**Comment by jancborchardt** [comment]
@bitsandnumbers currently there are no plans to make it adjustable, and many other things are there to be fixed before. But if anyone wants to contribute, we are happy to guide. :)

This should then ideally be done in the Vue library at https://github.com/nextcloud/nextcloud-vue

**Comment by jayhybrid** [comment]
As I already mentioned here https://github.com/nextcloud/mail/pull/2429, I recommend to at least make the heading full width.

![email](https://user-images.githubusercontent.com/44577029/76070528-fc3ee400-5f94-11ea-9720-1c8487669577.png)

Also, as @jancborchardt mentioned, I am also in favour of having the scrollbar fixed to the right of the screen.

> What would be nice though is if the scrollbar would move to the very right side, so it doesn’t float in mid-air.
