### ISSUE TITLE
Email sent but not recorded

### ISSUE THREAD

**Issue by sirohiparag** [nextcloud/mail#2456]
### Steps to reproduce
Compose and send email

### Expected behaviour
Should show the message as Email sent successfully and store the email in the sent items. 

### Actual behaviour
Error on the screen is the following and the sent email is not in the sent items folder but the email actually gets sent to the recipient. 

Error sending your message
Error: Request failed with status code 500

## Server configuration detail

**Operating system:** Linux 3.10.0-1062.4.3.el7.x86_64 #1 SMP Wed Nov 13 23:58:53 UTC 2019 x86_64

**Webserver:** Apache (cgi-fcgi)

**Database:** mysql 10.1.43

**PHP version:** 

7.3.13
Modules loaded: Core, date, libxml, openssl, pcre, zlib, filter, hash, pcntl, readline, Reflection, SPL, session, standard, cgi-fcgi, bcmath, bz2, calendar, ctype, curl, dba, dom, enchant, mbstring, fileinfo, ftp, gd, gettext, gmp, iconv, intl, json, ldap, exif, mysqlnd, PDO, Phar, posix, pspell, shmop, SimpleXML, snmp, soap, sockets, sqlite3, sysvmsg, sysvsem, sysvshm, tokenizer, xml, xmlwriter, xsl, zip, mysqli, pdo_mysql, pdo_sqlite, wddx, xmlreader, xmlrpc, Zend OPcache

**Nextcloud version:** 17.0.2 - 17.0.2.1

**Updated from an older Nextcloud/ownCloud or fresh install:** 

**Where did you install Nextcloud from:** unknown

<details><summary>Signing status</summary>

Integrity checker has been disabled. Integrity cannot be verified.
</details>

<details><summary>List of activated apps</summary>

```
Enabled:
 - activity: 2.10.1
 - announcementcenter: 3.6.1
 - apporder: 0.9.0
 - calendar: 1.7.2
 - cloud_federation_api: 1.0.0
 - comments: 1.7.0
 - contacts: 3.1.6
 - dav: 1.13.0
 - deck: 0.7.0
 - federatedfilesharing: 1.7.0
 - files: 1.12.0
 - files_pdfviewer: 1.6.0
 - files_sharing: 1.9.0
 - files_trashbin: 1.7.0
 - files_versions: 1.10.0
 - issuetemplate: 0.6.0
 - logreader: 2.2.0
 - lookup_server_connector: 1.5.0
 - mail: 0.21.1
 - notifications: 2.5.0
 - oauth2: 1.5.0
 - provisioning_api: 1.7.0
 - quicknotes: 0.2.2
 - ransomware_detection: 0.6.0
 - ransomware_protection: 1.5.1
 - serverinfo: 1.7.0
 - sharebymail: 1.7.0
 - spreed: 7.0.2
 - tasks: 0.11.3
 - text: 1.1.1
 - twofactor_backupcodes: 1.6.0
 - updatenotification: 1.7.0
 - workflowengine: 1.7.0
Disabled:
 - accessibility
 - admin_audit
 - encryption
 - federation
 - files_external
 - files_rightclick
 - files_videoplayer
 - firstrunwizard
 - gallery
 - nextcloud_announcements
 - ojsxc
 - password_policy
 - passwords
 - privacy
 - recommendations
 - support
 - survey_client
 - systemtags
 - theming
 - user_ldap
 - viewer

```
</details>

<details><summary>Configuration (config/config.php)</summary>

```
{
    "instanceid": "***REMOVED SENSITIVE VALUE***",
    "passwordsalt": "***REMOVED SENSITIVE VALUE***",
    "secret": "***REMOVED SENSITIVE VALUE***",
    "trusted_domains": [
        "team.aqusagtechnologies.com"
    ],
    "datadirectory": "***REMOVED SENSITIVE VALUE***",
    "dbtype": "mysql",
    "version": "17.0.2.1",
    "overwrite.cli.url": "https:\/\/team.aqusagtechnologies.com",
    "dbname": "***REMOVED SENSITIVE VALUE***",
    "dbhost": "***REMOVED SENSITIVE VALUE***",
    "dbport": "",
    "dbtableprefix": "oc_",
    "dbuser": "***REMOVED SENSITIVE VALUE***",
    "dbpassword": "***REMOVED SENSITIVE VALUE***",
    "installed": true,
    "theme": "team",
    "loglevel": 2,
    "maintenance": false,
    "default_language": "en",
    "default_locale": "en_IN",
    "defaultapp": "mail",
    "overwriteprotocol": "https",
    "knowledgebaseenabled": false,
    "allow_user_to_change_display_name": true,
    "auth.bruteforce.protection.enabled": true,
    "integrity.check.disabled": true,
    "updater.release.channel": "stable",
    "app_install_overwrite": [
        "ojsxc"
    ],
    "mail_smtpmode": "sendmail",
    "mail_sendmailmode": "smtp",
    "mail_from_address": "***REMOVED SENSITIVE VALUE***",
    "mail_domain": "***REMOVED SENSITIVE VALUE***"
}
```
</details>

**Are you using external storage, if yes which one:** local/smb/sftp/...

**Are you using encryption:** 

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...

## Client configuration

**Browser:** Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/79.0.3945.117 Safari/537.36

**Operating system:** Same behavior on Linux, Windows and Mac as well. 

## Logs

<details><summary>Web server error log</summary>

```
I just sent an email which resulted in the same from NC but here is the log for the same from my IMAP server:

Event:	success success
Sender User:	aqusaaqe
Sender Domain:	myurl.com
From Address:	email@myurl.com
Sender:	email@myurl.com
Sent Time:	Jan 10, 2020, 2:38:14 PM
Sender Host:	team.myurl.com
Sender IP:	192.249.121.192
Authentication:	dovecot_plain
Spam Score:	-1
Recipient:	client@email.com
Delivered To:	client@email.com
Delivery User:	-remote-
Delivery Domain:	
Router:	dkim_lookuphost
Transport:	dkim_remote_smtp
Out Time:	Jan 10, 2020, 2:38:14 PM
ID:	1ipqHU-0002Ra-0o
Delivery Host:	d116560b.ess.barracudanetworks.com
Delivery IP:	209.222.82.138
Size:	1.8 KB
Result:	Accepted
```
</details>

<details><summary>Nextcloud log</summary>

```
[mail] Fatal: Sending mail failed: Could not send message

POST /index.php/apps/mail/api/accounts/2/send
from 122.160.41.169 by surabhi at 2020-01-10T09:08:41+00:00

[mail] Error: OCA\Mail\Exception\ServiceException: Could not send message at <<closure>>

0. /home/aqusaaqe/public_html/team.aqusagtechnologies.com/apps/mail/lib/Controller/AccountsController.php line 332
   OCA\Mail\Service\MailTransmission->sendMessage("surabhi", OCA\Mail\Model\NewMessageData {}, null, null, 2554)
1. /home/aqusaaqe/public_html/team.aqusagtechnologies.com/lib/private/AppFramework/Http/Dispatcher.php line 170
   OCA\Mail\Controller\AccountsController->send(2, "Call today", "<p>Hi Jesse,</p ... >", "\"Jesse Klein ( ... >", "", "", true, 2554, null, null, [], null)
2. /home/aqusaaqe/public_html/team.aqusagtechnologies.com/lib/private/AppFramework/Http/Dispatcher.php line 99
   OC\AppFramework\Http\Dispatcher->executeController(OCA\Mail\Controller\AccountsController {}, "send")
3. /home/aqusaaqe/public_html/team.aqusagtechnologies.com/lib/private/AppFramework/App.php line 126
   OC\AppFramework\Http\Dispatcher->dispatch(OCA\Mail\Controller\AccountsController {}, "send")
4. /home/aqusaaqe/public_html/team.aqusagtechnologies.com/lib/private/AppFramework/Routing/RouteActionHandler.php line 47
   OC\AppFramework\App::main("OCA\\Mail\\Cont ... r", "send", OC\AppFramework\ ... {}, {accountId: "2", ... "})
5. <<closure>>
   OC\AppFramework\Routing\RouteActionHandler->__invoke({accountId: "2", ... "})
6. /home/aqusaaqe/public_html/team.aqusagtechnologies.com/lib/private/Route/Router.php line 297
   undefinedundefinedcall_user_func(OC\AppFramework\ ... {}, {accountId: "2", ... "})
7. /home/aqusaaqe/public_html/team.aqusagtechnologies.com/lib/base.php line 997
   OC\Route\Router->match("/apps/mail/api/accounts/2/send")
8. /home/aqusaaqe/public_html/team.aqusagtechnologies.com/index.php line 42
   OC::handleRequest()

POST /index.php/apps/mail/api/accounts/2/send
from 122.160.41.169 by surabhi at 2020-01-10T09:08:41+00:00
```
</details>

<details><summary>Browser log</summary>

Uncaught (in promise) Error: Request failed with status code 406
    at t.exports (createError.js:16)
    at t.exports (settle.js:17)
    at XMLHttpRequest.p.onreadystatechange (xhr.js:59)

xhr.js:172 POST https://team.aqusagtechnologies.com/index.php/apps/mail/api/accounts/2/send 500 (Internal Server Error)
(anonymous) @ xhr.js:172
t.exports @ xhr.js:11
t.exports @ dispatchRequest.js:57
Promise.then (async)
u.request @ Axios.js:53
r.forEach.u.<computed> @ Axios.js:78
(anonymous) @ bind.js:9
p @ MessageService.js:86
sendMessage @ NewMessageDetail.vue:264
(anonymous) @ Composer.vue:414
Promise.then (async)
onSend @ Composer.vue:414
Wt @ vue.runtime.esm.js:1854
n @ vue.runtime.esm.js:2179
i._wrapper @ vue.runtime.esm.js:6917

ConsoleLogger.js:56 [ERROR] mail: could not send message {app: "mail", uid: "surabhi", error: Error: Request failed with status code 500
    at t.exports (https://team.aqusagtechnologies.com/ap…}
value @ ConsoleLogger.js:56
value @ ConsoleLogger.js:82
(anonymous) @ Composer.vue:418
Promise.catch (async)
onSend @ Composer.vue:417
Wt @ vue.runtime.esm.js:1854
n @ vue.runtime.esm.js:2179
i._wrapper @ vue.runtime.esm.js:6917

</details>

**Comment by ChristophWurst** [comment]
> sent email is not in the sent items folder but the email actually gets sent

Interesting. I would assume that SMTP transmission succeeds but storing the sent message on IMAP fails. But the "Could not send message" error is thrown in the transmission code. 

The Nextcloud mail app offers an extensive logging system to make it easier identifying and tracking down bugs. Please enable [debug mode](https://docs.nextcloud.com/server/13/developer_manual/general/devenv.html#enabling-debug-mode) and set the log [level to debug](https://docs.nextcloud.com/server/13/admin_manual/configuration_server/logging_configuration.html) in your admin settings. Then, try to reproduce your issue and take another look at `data/horde_smtp.log`. Does that show any kind of error?

**Comment by ChristophWurst** [comment]
Also please patch your https://github.com/nextcloud/mail/blob/bc495aff638f532870575f8646fe4ad14375183c/lib/Service/MailTransmission.php#L177 to ``throw new ServiceException('Could not send message: ' . $e->getMessage(), 0, $e);`` then the nextcloud.log should also show the exception message of the `Horde` library used to sent the message.

**Comment by sirohiparag** [comment]
Hi Chris,

Thank you, I will do these steps and then get back with the details.

**Comment by sirohiparag** [comment]
Meanwhile, do you think this might also have something to do with my mail app running extremely slow?

**Comment by ChristophWurst** [comment]
Do you have a cache configured? https://docs.nextcloud.com/server/stable/admin_manual/configuration_server/caching_configuration.html

**Comment by ChristophWurst** [comment]
What you can try as well is get the account ID of the slow account (via the database and `oc_mail_accounts` or by looking at the URLs of the individual mailboxes) and run ``php occ mail:account:diagnose <id>`` on the cli. Then we know which capabilities your IMAP server has.
