### ISSUE TITLE
If you like the Mail app, rate it on apps.nextcloud.com <3

### ISSUE THREAD

**Issue by jancborchardt** [nextcloud/mail#247]
You can do so by going to [our app store](https://apps.nextcloud.com/), registering, and then leaving a nice review at:
https://apps.nextcloud.com/apps/mail

Thanks a lot! Let’s make Mail the highest-rated app on the store. :)

:tada: :smiley: :heart: 
cc @nextcloud/mail

**Comment by ChristophWurst** [comment]
Thanks everyone who rated the app ❤️
