### ISSUE TITLE
When impersonating a user (from admin), logout function doesn't return to admin session

### ISSUE THREAD

**Issue by ukb-33** [nextcloud/mail#2470]
### Expected behavior
Tell us what should happen
As for some others modules, logout function from an impersonated user session, should return to original admin session

### Actual behavior
Tell us what happens instead
When loging out from impersonated, full logout is done (even admin session is logged out)

Cd. #2469 is also about impersonating

### Mail app

**Mail app version:** 0.21.1

### Server configuration

**Operating system**: Ubuntu 18.04

**Web server:** Apache 2.4

**Database:** MariaDB 10.1

**PHP version:**: PHP7.2

**Nextcloud Version:**: Latest 17

#### Client configuration
**Browser:** Firefox 72

**Operating system:** Ubuntu 16.04

**Comment by ChristophWurst** [comment]
What happens on logout is out of scope for this app. This is an issue about the server component or the impersonation app.

**Comment by ukb-33** [comment]
Thank for your reply.
Didn't know that there was an impersonation app. Will try to create a new specific issue.
But, four your information, most of apps we're running dont suffer this problem (may looks like a specific mail component pb)
