### ISSUE TITLE
DateTime::__construct(): Failed to parse time string; Double timezone specification;

### ISSUE THREAD

**Issue by Rychu-Pawel** [nextcloud/mail#2472]
### Description
I'm seeing a lot of entries as below in my log:

> DateTime::__construct(): Failed to parse time string (Thu, 5 May 2016 08:04:24 +0800 (GMT+08:00)) at position 35 (+): Double timezone specification at /srv/www/nextcloud/apps/mail/vendor/pear-pear.horde.org/Horde_Imap_Client/Horde/Imap/Client/DateTime.php#51

Found this stackoverflow thread suggesting a different way of parsing datetimes with offset: https://stackoverflow.com/questions/13421635/failed-to-parse-time-string-at-position-41-i-double-timezone-specification

### Mail app

**Mail app version:** 0.21.0

**Mailserver or service:** Gmail, other

### Server configuration

**Operating system**: Ubuntu 18.04

**Web server:** Nginx

**Database:** MariaDB

**PHP version:** 7.2.24

**Nextcloud Version:** 17.0.2

**Comment by ChristophWurst** [comment]
Hmm. Would be interesting to know which client sends these time stamps. Do you have the source of such a message?

**Comment by Rychu-Pawel** [comment]
Unfortunatly no. These are some random dates like
`Thu, 22 Sep 2011 13:47:47 +0200 (Œrodkowoeuropejski czas letni)`
`Thu, 5 May 2016 08:04:24 +0800 (GMT+08:00)`
`29 lis 2019 13:51:34 +0100` (this one looks fine btw)
...

**Comment by ChristophWurst** [comment]
Could you check which client sends those?

We have to be a bit more tolerant, apparently, but would be nice to know who sends invalid date so that could be reported there (if it's a FLOSS product)

**Comment by LostinSpacetime** [comment]
I get this problem with E-Mails sent with Fairmail. None can be opened.

**Comment by cmuench** [comment]
I have the same issue and the mails are also sent by Fairmail.

**Comment by cmuench** [comment]
The issue can be fixed by changing the `lib/private/AppFramework/Utility/TimeFactory.php`.

```php
public function getDateTime(string $time = 'now', ?\DateTimeZone $timezone = null): \DateTime {
    // General cleanup: Remove any second timezone or additional information in parentheses
    $time = preg_replace('/\s*\([^)]*\)/', '', $time);
    return new \DateTime($time, $timezone);
}
```
