### ISSUE TITLE
17.0.3 deleted messages (apart from inbox) do not disappear from UI

### ISSUE THREAD

**Issue by laurentiu2** [nextcloud/mail#2487]
### Expected behavior
When a message is deleted from inbox, it disappears from UI and the others below would shift up.

### Actual behavior
When a message is deleted from Drafts, Trash, Sent, ecc it does not dissapear, although the message is erased.. Really annoying!! 

Only after performing 'reload current page' would go.
[Screen Recording 2020-01-16 at 20.22.02.mov.zip](https://github.com/nextcloud/mail/files/4073056/Screen.Recording.2020-01-16.at.20.22.02.mov.zip)

### Mail app

**Mail app version:** 0.17.0

**Mailserver or service:** Hetzner

### Server configuration

**Operating system**: Ubuntu 18.0.4
**Web server:** Apache

**Database:** MariaDB
**PHP version:** 7.3

**Nextcloud Version:** 16.0.7

#### Client configuration
**Browser:** Firefox 72.0.1

**Operating system:** MacOS Catalina 10.15.2

**Comment by jancborchardt** [comment]
Can’t confirm this, messages directly disappear from the UI here, regardless of the folder.

Could you provide more info and logs:
- Is there any error in the browser console?
- Any logging output in the Nextcloud log in the settings?
- Does it work in a different browser?

Thank you! :)

**Comment by laurentiu2** [comment]
>     * Is there any error in the browser console?

Yes. See thiis file:
[firefox_console_output.txt](https://github.com/nextcloud/mail/files/4087103/firefox_console_output.txt)

>     * Any logging output in the Nextcloud log in the settings?
No. None.


>     * Does it work in a different browser?
No. I've tried Chrome on my Apple, same result. I've tried firefox and chromium on another linux machine, same result.

I suppose something is missing or is misconfigured on my server, but cannot figure out what is.
Regards, Laurentiu

**Comment by ChristophWurst** [comment]
```envelope does not exist 3 SU5CT1guU2VudA== 59 mutations.js:144:11``` is the relevant error

**Comment by laurentiu2** [comment]
Is there a workaround for this? It's almost impossible using Mail..
Thanks.
Regards,

**Comment by ChristophWurst** [comment]
I highly recommend updating Nextcloud. On 17 and 18 you'll get the latest and greatest Mail. I think this is fixed now.

**Comment by laurentiu2** [comment]
Updated to 17.0.2 :(
Same problem, see recording (trash, not inbox) They disappear only after refreshing the page.
[Screen Recording 2020-01-25 at 18.54.42.mov.zip](https://github.com/nextcloud/mail/files/4112267/Screen.Recording.2020-01-25.at.18.54.42.mov.zip)

**Comment by ChristophWurst** [comment]
Thanks a lot for the recording. I suspect this has something to do with the mailbox ID `INBOX.Sent`. But I'm not sure. Would it be possible to get a test account on that specific server?

**Comment by laurentiu2** [comment]
Sure. What do you need? A user account, admin account or access to server?
Where to send the credentials?

**Comment by ChristophWurst** [comment]
Just a user account on the IMAP server. You can send it to firstname dot lastname at nextcloud dot com :)

**Comment by laurentiu2** [comment]
I've send the credentials, hope it works :) Did you find anything unusual?

**Comment by laurentiu2** [comment]
@ChristophWurst 
any chance to look into this?

**Comment by ChristophWurst** [comment]
No, not yet unfortunately.

**Comment by GretaD** [comment]
This is fixed on 18+

**Comment by laurentiu2** [comment]
nothing changed for me, NC 18.0.4 Mail 1.3.5

[Screen Recording 2020-05-23 at 21.00.23.mov.zip](https://github.com/nextcloud/mail/files/4672277/Screen.Recording.2020-05-23.at.21.00.23.mov.zip)

**Comment by GretaD** [comment]
I cannot reproduce it, everything looks fine on my 18.4 instance :/. Can you please check the webconsole when you click delete, if it shows any error?

**Comment by laurentiu2** [comment]
I've tried both firefox and chrome. The latest is showing some errors. Please see recordings.
[firefox.mov.zip](https://github.com/nextcloud/mail/files/4677812/firefox.mov.zip)
[chrome.mov.zip](https://github.com/nextcloud/mail/files/4677813/chrome.mov.zip)

**Comment by laurentiu2** [comment]
Can confirm also. NC 19.04 Firefox 83

**Comment by laurentiu2** [comment]
updated from 19.06 to 20.0.4 and it works fine.
