### ISSUE TITLE
Warning "KItinerary binary adapter is not available, can't extract information" in nextcloud.log after update to version 1.0.0

### ISSUE THREAD

**Issue by Nils160988** [nextcloud/mail#2489]
### Expected behavior
Everything runs smooth after update of mail-app.

### Actual behavior
After app-update to version 1.0.0 the warning "KItinerary binary adapter is not available, can't extract information" shows up in the server-log, twice for each mail I open.
Also the white space in the app looks a bit odd (don't know if related).

### Mail app

**Mail app version:** 1.0.0

**Mailserver or service:** self hosted

### Server configuration

**Operating system**: Ubuntu 18.04

**Web server:** Apache 2.4.29

**Database:** mariadb 10.1.43

**PHP version:** 7.2.24

**Nextcloud Version:** 17.0.2

#### Client configuration
**Browser:** Firefox 72.0.1

**Operating system:** Ubuntu 18.04

**Comment by ChristophWurst** [comment]
It's a warning. Do you have your log level set too low maybe?

**Comment by Nils160988** [comment]
I have set loglevel 2.
Just thought about reporting, because I don't expect a warning for a pretty much standard installation.
But of course, I can ignore it, if not important.

**Comment by ChristophWurst** [comment]
We can make it a debug mode, but yeah, seeing more entries if the log level is low is kinda expected.

**Comment by Nils160988** [comment]
Found some additional error message in the apache-log:
```
sh: 1: /var/www/nextcloud/apps/mail/vendor/christophwurst/kitinerary-bin/src/../bin/kitinerary-extractor: Permission denied
sh: 1: flatpak: not found
```
Did you introduce some new dependency?

**Comment by ChristophWurst** [comment]
Yes, https://packagist.org/packages/christophwurst/kitinerary-bin and https://packagist.org/packages/christophwurst/kitinerary-flatpak

**Comment by ChristophWurst** [comment]
Is there any more details on what line this fails?

**Comment by Nils160988** [comment]
No, sorry. I changed loglevel to debug and also no more information.
The kitinerary-extractor binary has 644 permission, not sure if this is intended.

**Comment by mzeiher** [comment]
I had the same Issue, I had to manually `chmod +x` the file `<...>vendor/christophwurst/kitinerary-bin/bin/kitinerary-extractor`, not I don't get the warning anymore, maybe the extraction does not preserve the execution permission

**Comment by ChristophWurst** [comment]
Interesting! I have 744 here :thinking:

**Comment by Nils160988** [comment]
Depending whether a zip-archive or a tarball has been used to install/update?

**Comment by ChristophWurst** [comment]
I installed via the app store. How did you?

**Comment by ChristophWurst** [comment]
It should always be a tarball as we don't use zip for app releases.

**Comment by Nils160988** [comment]
Also via app store (updated).
Just updated another installation which also has 644...

**Comment by mzeiher** [comment]
I installed also via the app store

**Comment by ChristophWurst** [comment]
I'm using traditional Apache with the php7 module. What do you use? Could be related to a php setting.

**Comment by mzeiher** [comment]
My Nextcloud runs on Apache2 and php7.3 what command does nextcloud use to untar? PharData::extractTo should preserve the permissions, I also did not find something in the php.ini to chnage that behaviour

**Comment by ChristophWurst** [comment]
Inspection of the release tarball with `tar -tvf mail.tar.gz`:

```
...
-rwxr-xr-x 1000/1000  15697272 2020-01-13 19:19 mail/vendor/christophwurst/kitinerary-bin/bin/kitinerary-extractor
...
```

And as far as I can tell we use
* https://github.com/nextcloud/server/blob/ddf6942d90097b909edac07513bb95c7107b9f4c/lib/private/Installer.php#L287
* https://github.com/nextcloud/server/blob/ddf6942d90097b909edac07513bb95c7107b9f4c/lib/private/Archive/TAR.php#L283
* https://github.com/nextcloud/3rdparty/blob/c6d97ae32edcfc3703a63c838c2accc8d9fa6c57/pear/archive_tar/Archive/Tar.php#L319

for extraction.

**Comment by mzeiher** [comment]
interesting, the "preserve" flag defaults to false in the last function... maybe this is the issue

**Comment by ChristophWurst** [comment]
Apparently @icewind1991's app had the same issue until https://github.com/nextcloud/documentserver_community/commit/c1e6c63774107437b2aa2df87970a294d9e94f6b. But I don't want this as a temporary solution.

I wish this bug was reproducible. It puzzles me a bit that on some installations you get the executable flag and on others you don't :thinking:

**Comment by Nils160988** [comment]
Tried for two more installations: The executable bit is never set in my cases (update of app as well as new installation and for php7.2 and also php7.3).

**Comment by ChristophWurst** [comment]
Thanks for testing.

**Comment by ChristophWurst** [comment]
Tried with the `$p_preserve = true` but that doesn't help. This option is about the ownership only

> Preserve user/group ownership of files

**Comment by ChristophWurst** [comment]
Workaround until we have fix for the extraction: https://github.com/nextcloud/mail/pull/2534

**Comment by Nils160988** [comment]
Thanks, it is working with mail version 1.1.1.
Just to be sure: I looked up the permissions again and it showed "--wxr-x--T" for the binary, is this intended?

**Comment by ChristophWurst** [comment]
https://github.com/nextcloud/mail/pull/2534 tries to set permissions to 744. You can retrigger the repair step with ``occ maintenance:repair``. Watch out for the "Make Mail itinerary extractor executable" line. Anything shown for this step?

**Comment by ChristophWurst** [comment]
In case of an error the exception is written to `data/nextcloud.log`.

**Comment by Nils160988** [comment]
> #2534 tries to set permissions to 744.

That's why I was confused...

Repair works as expected and does not show any error in the logs. The mail app works as expected and the warning is gone, because with these permissions the binary is now executable for everyone. But still, not the expected permissions.

**Comment by ChristophWurst** [comment]
But 744 means `rwxr--r--`. Am I missing something?

**Comment by Nils160988** [comment]
> But 744 means `rwxr--r--`.
I know, also tried another installation, also shows "--wxr-x--T" after a fresh installation.
Maybe the leading zero is important and it has to be "0744" in the workaround? Or there might be another issue with it.

**Comment by ChristophWurst** [comment]
I get `-rwxr-xr-x` on a simple Debian installation. Guess it might also depend on the directory permissions of the parent directories. SELinux or similar could also have an effect.

Your T indicates that sticky bit is in place.

**Comment by Nils160988** [comment]
Rechecked again, with update and also with new install of the mail app (on raspbian/debian with php7.3 as well as ubuntu and php7.2). Never changed anything of the permissions of the parent folders, especially not with the sticky bit.
@mzeiher, could you also test it on your installation?

**Comment by timo12357** [comment]
My upgrade from 17.0.2 to 17.0.3 hangs on this error, too.

**Comment by scanno** [comment]
Just wanted to upgrade from 17.0.2 to 17.0.3 and it fails during backing up.

**Comment by ChristophWurst** [comment]
To understand the problem better: which version of Mail where you at the Nextcoud upgrade? v1.0.0 or v1.1.1?

**Comment by ChristophWurst** [comment]
I've created #2575 to make the permission change more explicit. Not sure if this really makes a difference but it's recommended to specify the number this way by the php docs.

**Comment by scanno** [comment]
I am on v1.1.1

**Comment by ChristophWurst** [comment]
Please do the following

* Check the current file permissions
* Run `occ maintenance:repair` on the CLI
  + Look out for the "Make Mail itinerary extractor executable"
* Check the permissions again

**Comment by scanno** [comment]
Make Mail itinerary extractor executable is in the output of occ maintenance:repair. But updating still fails. permissions are --wxr-x--T

**Comment by ChristophWurst** [comment]
Ugh. I wanted the before and after. And the output of the command. It will tell you if it doesn't change anything.

**Comment by ChristophWurst** [comment]
To be honest I don't know how you get to these permissions. We extract the file just like any other. And if it's not executable we change that. But we never drop read permissions for the user.

So, please open a fresh bug report and describe your setup in detail.

**Comment by scanno** [comment]
Ah well manually adding read permissions worked fine and the update to 17.0.3 went through fine.

**Comment by ChristophWurst** [comment]
Chances are you'll run into this again. Then please file a new ticket, so we can actually fix this for everyone.
