### ISSUE TITLE
Favorites bugs

### ISSUE THREAD

**Issue by republicus** [nextcloud/mail#2493]
### Expected behavior
1. Marking message as Favorite will appear in Favorites box.
2. Removing Favorite designation should remove the message from Favorites box.
3. Favorites are not always retained.

### Actual behavior
1. Messages marked as Favorite appears in Favorites box **as well as all prior messages**.
2. Removing the message as a Favorite remains in Favorites box (and also all erroneous previous messages never marked as Favorites).
3. I'm having to "_Apply and create/update for all users_" in **Settings > Groupware > Account provisioning** after each user is created (expected behavior? I'm using the external IMAP user authentication). Favorites are lost when applying Account provisioning.

### Mail app

**Mail app version:** 1.0.0
**Mailserver or service:** Postfix/Dovecot

### Server configuration

**Operating system**: Debian 10
**Web server:** Apache
**Database:** MariaDB
**PHP version:** PHP 7.3.11-1
**Nextcloud Version:** 17.0.2

#### Client configuration
**Browser:** Chrome 74.0.3729.169
**Operating system:** Windows 10

**Comment by ChristophWurst** [comment]
> Messages marked as Favorite appears in Favorites box **as well as all prior messages**.

Yes, because the unified inbox contains all.

> Removing the message as a Favorite remains in Favorites box (and also all erroneous previous messages never marked as Favorites).

It only remains until you refresh, no?

> I'm having to "_Apply and create/update for all users_" in **Settings > Groupware > Account provisioning** after each user is created (expected behavior? I'm using the external IMAP user authentication). Favorites are lost when applying Account provisioning.

As favorites are stored in IMAP and not in Nextcloud, I would be surprised this is the case.
