### ISSUE TITLE
All Inboxes: not showing all messages

### ISSUE THREAD

**Issue by republicus** [nextcloud/mail#2494]
### Expected behavior
**All Inboxes** should show all messages in Inboxes.

### Actual behavior
**All Inboxes** fails to load all items from single Inbox.
1. Main Inbox has 27 messages and properly displayed in Inbox;
2. **All Inboxes** only displays 19 of single Inbox items with continuous spinning.

![image](https://user-images.githubusercontent.com/47370709/72672674-b3a28a00-3a2b-11ea-8151-b4cf656f1845.png)

### Mail app

**Mail app version:** 1.0.0
**Mailserver or service:** Postfix/Dovecot

### Server configuration

**Operating system**: Debian 10
**Web server:** Apache
**Database:** MariaDB
**PHP version:** PHP 7.3.11-1
**Nextcloud Version:** 17.0.2

#### Client configuration
**Browser:** Chrome 74.0.3729.169
**Operating system:** Windows 10

**Comment by jancborchardt** [comment]
This seems to need more info from logs like server logs, IMAP logs, Nextcloud logs etc. :) Does something there look off?

**Comment by ChristophWurst** [comment]
Nah I think this is the pagination logic that is fragile in edge cases. https://github.com/nextcloud/mail/blob/e820d907a971ebffa9b53a6f43c40f4337ad781c/src/store/actions.js#L145-L215 if anyone wants to dig deeper (yes, it's very complex).
