### ISSUE TITLE
Automatic link redirect

### ISSUE THREAD

**Issue by jancborchardt** [nextcloud/mail#250]
I’m getting these interstitial pages again recently:
![capture du 2016-12-16 16-59-31](https://cloud.githubusercontent.com/assets/925062/21268940/13834788-c3b1-11e6-97eb-b162bf3b250e.png)
Didn’t we auto-redirect here @nextcloud/mail? And if we didn’t do it so far, why shouldn’t we? It’s quite a pain needing to click again.

**Comment by ChristophWurst** [comment]
I remember to fix that once. Maybe the browser behavior changed (we trigger a click event)?

**Comment by skjnldsv** [comment]
Maybe should you use `window.location = $('#redirectLink').prop('href');` instead? 
https://github.com/nextcloud/mail/blob/master/js/autoredirect.js

**Comment by jancborchardt** [comment]
@skjnldsv does that work? If so, can you open a pull request? :)

**Comment by skjnldsv** [comment]
It works fine.
But I think the issue here is that the script isn't loaded anymore.
I will pr this asap.

**Comment by skjnldsv** [comment]
No, actually, this is related to this function: https://github.com/nextcloud/mail/blob/master/lib/Controller/ProxyController.php#L88

The automatic redirection only works for the same domain.

**Comment by skjnldsv** [comment]
Otherwise, the script works fine. It's not the best thing to do (use click) but if it works, it ain't stupid! ;)

However, what we can do is adding a countdown for différents domain so that we still have an auto redirection, but the user can cancel it! :)

**Comment by ChristophWurst** [comment]
I assume https://github.com/nextcloud/mail/pull/187 removed the referrer

**Comment by skjnldsv** [comment]
Arf, what do we do then?

**Comment by jancborchardt** [comment]
Let’s just make the countdown be 0 then, because people don’t need to cancel it. The link gets opened in a new tab anyway. :)

**Comment by skjnldsv** [comment]
So what is the point of a redirect page if we don't have time to read what's written on it. :D

**Comment by jancborchardt** [comment]
I think it’s for some security reason. Not for the people checking the domain. :) At least no one will do that anyway and just be annoyed by the interstitial page.
 cc @LukasReschke can you clarify?

**Comment by plastikschnitzer** [comment]
I like the behavior now, great!

**Comment by leandro-lucarella-sociomantic** [comment]
I'm getting these annoying redirects in 0.7.3. Is this a regression or is it intended?

**Comment by ChristophWurst** [comment]
> I'm getting these annoying redirects in 0.7.3. Is this a regression or is it intended?

Please file a new ticket if there's possibly a regression. Thanks :)
