### ISSUE TITLE
Possibility to attach local files [$50]

### ISSUE THREAD

**Issue by jancborchardt** [nextcloud/mail#251]
(Carrying over the tasks from https://github.com/nextcloud/mail/pull/4 so we don’t forget it ;)

client-side TODO
- [ ] upload files asynchronously
- [ ] add uploaded files to list of attachments
- [ ] show loading and/or progress indicator
- [ ] lock 'Send'/'Reply' button until all local attachments have been uploaded successfully
- [ ] handle errors (remove faulty attachment from list)
- [ ] add special property to attachment so that server can distinguish between local and cloud attachments 

server-side TODO
- [ ] add attachment store for asynchronously uploaded files
- [ ] move uploaded attachments to temp dir (use core's temp manager)
- [ ] limit uploaded file size to a sane size (e.g. a few MBs)
- [ ] distinguish between local and cloud attachments when sending a message and load local attachments from the attachment store

cc @nextcloud/mail

**Comment by rakshazi** [comment]
Hello!
Any updates here?

**Comment by jancborchardt** [comment]
@rakshazi unfortunately not yet, no. Since you are a developer it would be awesome if you can contribute a part of this via pull request – any contribution is welcome and much appreciated! :) We need more people working on the Mail app.

**Comment by ChristophWurst** [comment]
@lcalaresu FYI put a bounty on this long awaited feature 🤑
