### ISSUE TITLE
"New message" button does not work in "Message sent" view

### ISSUE THREAD

**Issue by jancborchardt** [nextcloud/mail#2510]
1. You just sent an email and are in the "Message sent" view
2. Then try to compose a new message – but not via the primary button "Write another message"
3. You click "New message" in the top left

→ Nothing happens, and `uncaught exception: Object` in the console.

**Comment by IchbinkeinReh** [comment]
Can someone please close this issue. If i understand correctly this was fixed by https://github.com/nextcloud/mail/pull/2480
