### ISSUE TITLE
Moving mail to folders and marking as spam

### ISSUE THREAD

**Issue by gucu** [nextcloud/mail#2512]
### Question

How do I move mail into folders or mark it for spam please?

#### Summary

I am using Rainloop at the moment to manage mail but it doesn't have all the features I would like. What it does have is spam management and being able to move mail to folders. I cannot see how to do this, if I could I think I would stop using rainloop.

Thanks

Rich

**Comment by ChristophWurst** [comment]
Drag and drop: https://github.com/nextcloud/mail/issues/1538
Spam: https://github.com/nextcloud/mail/issues/23

Thanks for reporting :)
