### ISSUE TITLE
Pasting plain text inserts newlines

### ISSUE THREAD

**Issue by jancborchardt** [nextcloud/mail#2513]
When you paste in plain text from a text editor amd your Mail app is also set to plain text, there's still 2 line breaks inserted for every single break.

Meaning that this message:
```
Tasks
- Bla
- Test
```

Pasted into Mail and sent will turn to
```
Tasks

- Bla

- Test
```

Related to https://github.com/nextcloud/mail/issues/2481

**Comment by ChristophWurst** [comment]
:+1: IIRC there were a few issues in the CKEditor5 repo. So chances are good this has to be fixed upstream.

**Comment by jancborchardt** [comment]
This is fixed in master! :) Possibly through #2538
