### ISSUE TITLE
New Mail Notification

### ISSUE THREAD

**Issue by olpo24** [nextcloud/mail#2516]
### Question

Should be anywhere a ntotification badge or pop-up on incoming mail? I can't find anything.
If yes, how to debug and find the issue? (NexrCloud 18.0.1 an Mail 1.0.0)

**Comment by ChristophWurst** [comment]
Yes, that should work if you allow them. But only on the Mail page, not on any other Nextcloud pages.

If it doesn't please submit a bug report: https://github.com/nextcloud/mail/issues/new?assignees=&labels=bug%2C+0.+to+triage&template=bug.md&title=

**Comment by olpo24** [comment]
ah ok....i thought there were an global notification.

Thank you @ChristopWurst
