### ISSUE TITLE
cannot build master branch

### ISSUE THREAD

**Issue by StCyr** [nextcloud/mail#2517]
Here's the build's output. Can you help (Building on Debian 10.2)?

root@vps612142:/var/www/nextcloud/apps/mail# make dev-setup
php composer.phar install -o
Do not run Composer as root/super user! See https://getcomposer.org/root for details
Loading composer repositories with package information
Installing dependencies (including require-dev) from lock file
Package operations: 0 installs, 5 updates, 0 removals
  - Updating arthurhoaro/favicon (v1.2.2 => v1.3.0): Downloading (100%)
  - Updating christophwurst/kitinerary-bin (0.2.0 => 0.2.2): Downloading (100%)
  - Updating christophwurst/kitinerary-flatpak (0.2.0 => 0.2.2): Downloading (100%)
  - Updating composer/semver (1.5.0 => 1.5.1): Downloading (100%)
  - Updating myclabs/deep-copy (1.9.4 => 1.9.5): Downloading (100%)
Generating optimized autoload files
npm install
npm WARN npm npm does not support Node.js v10.15.2
npm WARN npm You should probably upgrade to a newer version of node as we
npm WARN npm can't make any promises that npm will work with this version.
npm WARN npm Supported releases of Node.js are the latest release of 4, 6, 7, 8, 9.
npm WARN npm You can find the latest version at https://nodejs.org/
npm WARN notice [SECURITY] node-sass has the following vulnerability: 1 low. Go here for more details: https://www.npmjs.com/advisories?search=node-sass                                                           &version=4.13.1 - Run `npm i npm@latest -g` to upgrade your npm version, and then `npm audit` to get more info.

> node-sass@4.13.1 install /var/www/nextcloud/apps/mail/node_modules/node-sass
> node scripts/install.js

Downloading binary from https://github.com/sass/node-sass/releases/download/v4.13.1/linux-x64-64_binding.node
Download complete .] - :
Binary saved to /var/www/nextcloud/apps/mail/node_modules/node-sass/vendor/linux-x64-64/binding.node
Caching binary to /root/.npm/node-sass/4.13.1/linux-x64-64_binding.node

> core-js@3.6.4 postinstall /var/www/nextcloud/apps/mail/node_modules/core-js
> node -e "try{require('./postinstall')}catch(e){}"

Thank you for using core-js ( https://github.com/zloirock/core-js ) for polyfilling JavaScript standard library!

The project needs your help! Please consider supporting of core-js on Open Collective or Patreon:
> https://opencollective.com/core-js
> https://www.patreon.com/zloirock

Also, the author of core-js ( https://github.com/zloirock ) is looking for a good job -)

> node-sass@4.13.1 postinstall /var/www/nextcloud/apps/mail/node_modules/node-sass
> node scripts/build.js

Binary found at /var/www/nextcloud/apps/mail/node_modules/node-sass/vendor/linux-x64-64/binding.node
Testing binary
Binary is fine
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.9 (node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.9: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch                                                           ":"x64"})

added 164 packages from 71 contributors, removed 10 packages and updated 180 packages in 46.143s
npm run build
npm WARN npm npm does not support Node.js v10.15.2
npm WARN npm You should probably upgrade to a newer version of node as we
npm WARN npm can't make any promises that npm will work with this version.
npm WARN npm Supported releases of Node.js are the latest release of 4, 6, 7, 8, 9.
npm WARN npm You can find the latest version at https://nodejs.org/

> nextcloud-mail@1.0.0 build /var/www/nextcloud/apps/mail
> NODE_ENV=production webpack --progress --hide-modules --config webpack.prod.js

66% building 1326/1405 modules 79 active /var/www/nextcloud/apps/mail/node_modules/lodash-es/identity.jsBrowserslist: caniuse-lite is outdated. Please r                                                           un next command `npm update`
92% chunk asset optimization TerserPluginKilled
npm ERR! code ELIFECYCLE
npm ERR! errno 137
npm ERR! nextcloud-mail@1.0.0 build: `NODE_ENV=production webpack --progress --hide-modules --config webpack.prod.js`
npm ERR! Exit status 137
npm ERR!
npm ERR! Failed at the nextcloud-mail@1.0.0 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2020-01-21T09_44_17_162Z-debug.log
make: *** [Makefile:39: optimize-js] Error 137
root@vps612142:/var/www/nextcloud/apps/mail# vi /root/.npm/_logs/2020-01-21T09_44_17_162Z-debug.log
root@vps612142:/var/www/nextcloud/apps/mail#

**Comment by StCyr** [comment]
Damned! I can't even build my old branch neither (((

App seems completly broken (((

**Comment by ChristophWurst** [comment]
> npm WARN npm npm does not support Node.js v10.15.2
> npm WARN npm You should probably upgrade to a newer version of node as we
> npm WARN npm can't make any promises that npm will work with this version.
> npm WARN npm Supported releases of Node.js are the latest release of 4, 6, 7, 8, 9.
> npm WARN npm You can find the latest version at https://nodejs.org/

Guess that explains it.

**Comment by StCyr** [comment]
it was working before ;(

Strange that Debian ships a version of npm (5.8.0) that's not compatible with the version of Node.js they ship!?!

**Comment by StCyr** [comment]
@ChristophWurst 

I've upgraded to npm from Debian 11  but the problem's still there (The versions incompatibility warning isn't there anymore though).

Here's the full log:

```
0 info it worked if it ends with ok
1 verbose cli [ '/usr/bin/node', '/usr/bin/npm', 'run', 'build' ]
2 info using npm@6.13.4
3 info using node@v10.15.2
4 verbose run-script [ 'prebuild', 'build', 'postbuild' ]
5 info lifecycle nextcloud-mail@0.21.1~prebuild: nextcloud-mail@0.21.1
6 info lifecycle nextcloud-mail@0.21.1~build: nextcloud-mail@0.21.1
7 verbose lifecycle nextcloud-mail@0.21.1~build: unsafe-perm in lifecycle true
8 verbose lifecycle nextcloud-mail@0.21.1~build: PATH: /usr/share/npm/node_modules/npm-lifecycle/node-gyp-bin:/var/www/nextcloud/apps/mail/node_modules/.bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
9 verbose lifecycle nextcloud-mail@0.21.1~build: CWD: /var/www/nextcloud/apps/mail
10 silly lifecycle nextcloud-mail@0.21.1~build: Args: [ '-c',
10 silly lifecycle   'NODE_ENV=production webpack --progress --hide-modules --config webpack.prod.js' ]
11 silly lifecycle nextcloud-mail@0.21.1~build: Returned: code: 137  signal: null
12 info lifecycle nextcloud-mail@0.21.1~build: Failed to exec build script
13 verbose stack Error: nextcloud-mail@0.21.1 build: `NODE_ENV=production webpack --progress --hide-modules --config webpack.prod.js`
13 verbose stack Exit status 137
13 verbose stack     at EventEmitter.<anonymous> (/usr/share/npm/node_modules/npm-lifecycle/index.js:332:16)
13 verbose stack     at EventEmitter.emit (events.js:189:13)
13 verbose stack     at ChildProcess.<anonymous> (/usr/share/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
13 verbose stack     at ChildProcess.emit (events.js:189:13)
13 verbose stack     at maybeClose (internal/child_process.js:970:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:259:5)
14 verbose pkgid nextcloud-mail@0.21.1
15 verbose cwd /var/www/nextcloud/apps/mail
16 verbose Linux 4.19.0-6-amd64
17 verbose argv "/usr/bin/node" "/usr/bin/npm" "run" "build"
18 verbose node v10.15.2
19 verbose npm  v6.13.4
20 error code ELIFECYCLE
21 error errno 137
22 error nextcloud-mail@0.21.1 build: `NODE_ENV=production webpack --progress --hide-modules --config webpack.prod.js`
22 error Exit status 137
23 error Failed at the nextcloud-mail@0.21.1 build script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 137, true ]
```

**Comment by ChristophWurst** [comment]
> 18 verbose node v10.15.2

Still an outdated node? As far as I can see there are newer releases: https://nodejs.org/dist/latest-v10.x/

**Comment by ChristophWurst** [comment]
And it says v0.21.1. This isn't master? Master is v1.0.0

**Comment by StCyr** [comment]
thanks :-)

I've upgraded my whole system to Debian 11 and it works now

**Comment by ChristophWurst** [comment]
Great!

**Comment by StCyr** [comment]
For some reason I can't compile master branch anymore again.

All I explicitly did is try to compile another branch. And, since then, even the master branch won't compile anymore.

Here's the log:

```
0 info it worked if it ends with ok
1 verbose cli [ '/usr/bin/node', '/usr/bin/npm', 'run', 'build' ]
2 info using npm@6.13.4
3 info using node@v10.17.0
4 verbose run-script [ 'prebuild', 'build', 'postbuild' ]
5 info lifecycle nextcloud-mail@1.0.0~prebuild: nextcloud-mail@1.0.0
6 info lifecycle nextcloud-mail@1.0.0~build: nextcloud-mail@1.0.0
7 verbose lifecycle nextcloud-mail@1.0.0~build: unsafe-perm in lifecycle true
8 verbose lifecycle nextcloud-mail@1.0.0~build: PATH: /usr/share/npm/node_modules/npm-lifecycle/node-gyp-bin:/var/www/nextcloud/apps/mail/node_modules/.bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
9 verbose lifecycle nextcloud-mail@1.0.0~build: CWD: /var/www/nextcloud/apps/mail
10 silly lifecycle nextcloud-mail@1.0.0~build: Args: [ '-c',
10 silly lifecycle   'NODE_ENV=production webpack --progress --hide-modules --config webpack.prod.js' ]
11 silly lifecycle nextcloud-mail@1.0.0~build: Returned: code: 137  signal: null
12 info lifecycle nextcloud-mail@1.0.0~build: Failed to exec build script
13 verbose stack Error: nextcloud-mail@1.0.0 build: `NODE_ENV=production webpack --progress --hide-modules --config webpack.prod.js`
13 verbose stack Exit status 137
13 verbose stack     at EventEmitter.<anonymous> (/usr/share/npm/node_modules/npm-lifecycle/index.js:332:16)
13 verbose stack     at EventEmitter.emit (events.js:198:13)
13 verbose stack     at ChildProcess.<anonymous> (/usr/share/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
13 verbose stack     at ChildProcess.emit (events.js:198:13)
13 verbose stack     at maybeClose (internal/child_process.js:982:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:259:5)
14 verbose pkgid nextcloud-mail@1.0.0
15 verbose cwd /var/www/nextcloud/apps/mail
16 verbose Linux 5.4.0-2-amd64
17 verbose argv "/usr/bin/node" "/usr/bin/npm" "run" "build"
18 verbose node v10.17.0
19 verbose npm  v6.13.4
20 error code ELIFECYCLE
21 error errno 137
22 error nextcloud-mail@1.0.0 build: `NODE_ENV=production webpack --progress --hide-modules --config webpack.prod.js`
22 error Exit status 137
23 error Failed at the nextcloud-mail@1.0.0 build script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 137, true ]
```

any ideas? @ChristophWurst ?

**Comment by ChristophWurst** [comment]
> code: 137

Is your machine running out of memeory?

**Comment by StCyr** [comment]
> 
> 
> > code: 137
> 
> Is your machine running out of memeory?

Might be that: after several tries it eventually worked.

Thanks for the help )
