### ISSUE TITLE
keyboard shortcut and jsxc conflict, cannot use "s" in chat message

### ISSUE THREAD

**Issue by nicolas-san** [nextcloud/mail#2519]
### Expected behavior
I want to use all the letters on my keyboard to write messages in the xmpp chat ^^

### Actual behavior
I can't use "s" because it's attach to the bookmark email action

### Mail app

**Mail app version:** (see apps admin page, e.g. 0.5.3)
1.0.0
**Mailserver or service:** (e.g. Outlook, Yahoo, Gmail, Exchange,...)

### Server configuration

**Operating system**: (e.g. Debian 8)
debian 8
**Web server:** (e.g. Apache, Nginx,...)
apache
**Database:** (e.g. MariaDB, SQLite or PostgreSQL)
mysql
**PHP version:** (e.g. 7.0)
7.1
**Nextcloud Version:** (see admin page, e.g. 13.0.2)
17.0.2
#### Client configuration
**Browser:** (e.g. Firefox 48)
firefox 72.0.1
**Operating system:** (e.g. Arch Linux)
ubuntu

**Comment by ChristophWurst** [comment]
What type of element does the chat use for the input?

We handle the shortkeys with `vue-shortkey` at https://github.com/nextcloud/mail/blob/a98bdc9490c1c6b386d8c2df7f327f6ad81db974/src/components/EnvelopeList.vue#L6.

We might need https://github.com/iFgR/vue-shortkey#avoided-fields. Are you a js dev by any chance? :)

**Comment by nicolas-san** [comment]
> What type of element does the chat use for the input?
> 
I not sure that I correctly get the sense of your question

> We handle the shortkeys with `vue-shortkey` at
> 
> https://github.com/nextcloud/mail/blob/a98bdc9490c1c6b386d8c2df7f327f6ad81db974/src/components/EnvelopeList.vue#L6
> .
> 
> We might need https://github.com/iFgR/vue-shortkey#avoided-fields. Are you a js dev by any chance? :)

I could, it's not my specialty, but it is the time I miss the most :) 
I will look at the link of vue-shortkey to see if something feel like a simple fix

**Comment by ChristophWurst** [comment]
> I not sure that I correctly get the sense of your question

The type of HTML input. Like `input`, `textarea` or editable `div`. Because then it should be possible to tell vue-shortkey to exclude that.
