### ISSUE TITLE
Messages Send without recipient: Error 500

### ISSUE THREAD

**Issue by republicus** [nextcloud/mail#2522]
### Expected behavior
Sending a message without a recipient, user should not be able to click send.

1) Send button becomes activated only if To: field has a recipient. 
2) An informative error telling user a message cannot be sent without recipient.

### Actual behavior
User clicks send having forgot to enter recipient address returns:

**Error: Request failed with status code 500** 

![image](https://user-images.githubusercontent.com/47370709/72866787-9b8c6e00-3caa-11ea-8c3d-38a1273181ca.png)

### Mail app

**Mail app version:** 1.0.0
**Mailserver or service:** Postfix/Dovecot

### Server configuration

**Operating system**: Debian 10
**Web server:** Apache
**Database:** MariaDB
**PHP version:** PHP 7.3.11-1
**Nextcloud Version:** 17.0.2

#### Client configuration
**Browser:** Chrome 74.0.3729.169
**Operating system:** Windows 10

**Comment by ChristophWurst** [comment]
Yep, also ran into this the other day.

@GretaD could you disable the submit button as long as `to`, `cc` and `bcc` are empty?

**Comment by ChristophWurst** [comment]
Fixed with https://github.com/nextcloud/mail/pull/2527
