### ISSUE TITLE
"All inboxes" not translated

### ISSUE THREAD

**Issue by ChristophWurst** [nextcloud/mail#2530]
### Expected behavior
Get "All mailboxes" (the unified inbox) translated

### Actual behavior
See English text

@rakekniven I tried to find the string on Transifex but failed. Is it missing there? :thinking:

**Comment by rakekniven** [comment]
I cannot find the string in this repo either? Which file should contain the source?

**Comment by ChristophWurst** [comment]
At https://github.com/nextcloud/mail/blob/c8d90e539cb0ac41d23eee31e5d869201d5b71f7/src/l10n/MailboxTranslator.js#L44

**Comment by ChristophWurst** [comment]
oh it's "All inboxes" and not "All mailboxes". Sorry.

**Comment by rakekniven** [comment]
Ok, string is actually not present at Transifex.

**Comment by ChristophWurst** [comment]
Okidoke. I have to check our extraction tool.

**Comment by ChristophWurst** [comment]
Related: https://github.com/nextcloud/mail/issues/2290

**Comment by ChristophWurst** [comment]
It's back https://github.com/nextcloud/mail/commit/88bdce8a1ffe669e5452bce001d45e766082ccb1 :rocket:
