### ISSUE TITLE
Cannot see LDAP group Users

### ISSUE THREAD

**Issue by profinfodev** [nextcloud/mail#2536]
### Expected behavior
Until the version 0.21.1 it was possible to choose LDAP group (in Users not in Contacts) in any field.

![Screenshot 2020-01-23 at 23 14 09](https://user-images.githubusercontent.com/48761610/73028747-7462a780-3e36-11ea-962f-273d938cfb14.png)

### Actual behavior
Now with this version 1.0.0, LDAP group Users have disappeared.

### Mail app

**Mail app version:** 1.0.0
**Mailserver or service:** ovh

### Server configuration

**Operating system**: ubuntu 18.04 LTS
**Web server:** Apache
**Database:** mysql 5.7.28
**PHP version:** 7.2.24
**Nextcloud Version:** 17.0.2

#### Client configuration
**Browser:** Safari - Chrome - Firefox
**Operating system:** macOS

**Comment by ChristophWurst** [comment]
Is it just Mail did you updated or have you also upgraded Nextcloud to a newer version?

I don't recall any change regarding Nextcloud group integration [in this version range](https://github.com/nextcloud/mail/compare/v0.21.1...v1.0.0).

**Comment by profinfodev** [comment]
Just mail. I restored a backup with mail v0.21.1, did the update of all apps (without mail) + OS to match with my current vm (with mail 1.0.0).
So now the only different between these vm is mail version and I still have the problem.

**Comment by ChristophWurst** [comment]
The screenshot is from 0.21.1, I guess?

**Comment by profinfodev** [comment]
Yes

**Comment by profinfodev** [comment]
In this screenshot we see a lot of blank space (bugs ?), but it's clean in the new version of mail.

**Comment by profinfodev** [comment]
OK so the problem is from this file : lib/AppInfo/BootstrapSingleton.php
2 changes since 0.21.1

Without these changes (v0.21.1) the field search is very buggy but you can find your LDAP group.
With these changes (v1.0.0) the field is clean but your LDAP group disappeared ...
