### ISSUE TITLE
Drag-and-drop animation

### ISSUE THREAD

**Issue by ChristophWurst** [nextcloud/mail#254]
As described in of https://github.com/nextcloud/mail/pull/211, we should add an animation to the message list whenever a message is moved to another folder, e.g. collapsing it.

**Comment by skug67** [comment]
Not a huge issue, but would be great to be able to pull up context menus with a right click. You say the code is based on Horde which has this functionality, so hopefully it wouldn't be too hard to re-enabled it.

**Comment by st3iny** [comment]
See #4048 for the new drag and drop feature.
