### ISSUE TITLE
Send Cloud-Files also as a shared Link

### ISSUE THREAD

**Issue by develth** [nextcloud/mail#2540]
### Feature Request

When adding a Cloud-File as Attachment, let the User select (predefined in Settings or while selection in composer) if the file should be attached or if a LinkShare should be created and placed into the composer. 
That will also reduce the Mail-Traffic and the multiple location of Files (Sent folder, Inbox, Mail-Archive, ...).

**Comment by ChristophWurst** [comment]
Duplicate of https://github.com/nextcloud/mail/issues/52
