### ISSUE TITLE
"Could not load message" on all messages. Except for those with attatchments. Protonmail Bridge only - confirmed working w/ other clients.

### ISSUE THREAD

**Issue by th3raid0r** [nextcloud/mail#2545]
## Steps to reproduce
1. Get a ProtonMail account
2. Get the ProtonMail bridge for Linux.
3. Run the Bridge on the same server as Nextcloud in either combined or separated mode (for multiple addresses) - doesn't seem to matter.
4. Open the necessary ports to connect on 127.0.0.1
5. Configure the account in Nextcloud Mail
6. Browse to any email without an attachment - plain-text or rich text - doesn't seem to matter.
7. This error does not occur on emails with attachments.
8. This issue does not occur with other email clients. (Thunderbird, Outlook)

## Expected behaviour
I should be able to view the email. 

## Actual behaviour
I get the "Could not load message" dialog. 

## Error
```
OCA\Mail\Exception\ServiceException: Could not load message
  at OCA\Mail\Service\MailManager::getMessage
     /usr/share/webapps/nextcloud/apps/mail/lib/Controller/MessagesController.php, line 181
  at OCA\Mail\Controller\MessagesController::show
     /usr/share/webapps/nextcloud/lib/private/AppFramework/Http/Dispatcher.php, line 170
  at OC\AppFramework\Http\Dispatcher::executeController
     /usr/share/webapps/nextcloud/lib/private/AppFramework/Http/Dispatcher.php, line 99
  at OC\AppFramework\Http\Dispatcher::dispatch
     /usr/share/webapps/nextcloud/lib/private/AppFramework/App.php, line 125
  at OC\AppFramework\App::main
     /usr/share/webapps/nextcloud/lib/private/AppFramework/Routing/RouteActionHandler.php, line 47
  at OC\AppFramework\Routing\RouteActionHandler::__invoke
  at call_user_func
     /usr/share/webapps/nextcloud/lib/private/Route/Router.php, line 299
  at OC\Route\Router::match
     /usr/share/webapps/nextcloud/lib/base.php, line 1008
  at OC::handleRequest
     /usr/share/webapps/nextcloud/index.php, line 38

```

**Comment by ChristophWurst** [comment]
> Error

Could you please post the full nextcloud.log entry? It *should* also contain the inner exception (ServiceException is where we catch & rethrow)

**Comment by brogers-navex** [comment]
I'll try it again this evening and report back with the contents of nextcloud.log

**Comment by th3raid0r** [comment]
Got the update to 1.1.1 - no change in behavior. The weirdest part is that simply having an attachment seems to allow an email to come through.

Here's the full error:

```
[mail] Error: OCA\Mail\Exception\ServiceException: Could not load message at <<closure>>

0. /usr/share/webapps/nextcloud/apps/mail/lib/Controller/MessagesController.php line 181
   OCA\Mail\Service\MailManager->getMessage(OCA\Mail\Account {}, OCA\Mail\Db\Mailbox {id: 31}, 116, true)
1. /usr/share/webapps/nextcloud/lib/private/AppFramework/Http/Dispatcher.php line 170
   OCA\Mail\Controller\MessagesController->show(11, "SU5CT1g=", 116)
2. /usr/share/webapps/nextcloud/lib/private/AppFramework/Http/Dispatcher.php line 99
   OC\AppFramework\Http\Dispatcher->executeController(OCA\Mail\Controller\MessagesController {}, "show")
3. /usr/share/webapps/nextcloud/lib/private/AppFramework/App.php line 125
   OC\AppFramework\Http\Dispatcher->dispatch(OCA\Mail\Controller\MessagesController {}, "show")
4. /usr/share/webapps/nextcloud/lib/private/AppFramework/Routing/RouteActionHandler.php line 47
   OC\AppFramework\App::main("OCA\\Mail\\Cont ... r", "show", OC\AppFramework\ ... {}, {accountId: "11" ... "})
5. <<closure>>
   OC\AppFramework\Routing\RouteActionHandler->__invoke({accountId: "11" ... "})
6. /usr/share/webapps/nextcloud/lib/private/Route/Router.php line 299
   call_user_func(OC\AppFramework\ ... {}, {accountId: "11" ... "})
7. /usr/share/webapps/nextcloud/lib/base.php line 1008
   OC\Route\Router->match("/apps/mail/api/ ... 6")
8. /usr/share/webapps/nextcloud/index.php line 38
   OC::handleRequest()

GET /apps/mail/api/accounts/11/folders/SU5CT1g%3D/messages/116
from 192.168.1.1 by th3raid0r at 2020-01-29T04:43:30+00:00
```

**Comment by th3raid0r** [comment]
`sudo tail -n 5000 /home/http/nextcloud/data/nextcloud.log | grep \"mail\" > out.txt`

[errors.txt](https://github.com/nextcloud/mail/files/4126256/errors.txt)

**Comment by ChristophWurst** [comment]
> Mail body for this mail(121) could not be loaded

This is strange. Like as if the message is there when we fetch the list, but not when the body is accessed. Unless some parameters are mixed up and we fetch a UID from an unrelated mailbox.

**Comment by th3raid0r** [comment]
Normally, I'd chalk this up to the Protonmail Bridge software, but the fact that both Outlook and Thunderbird work _fine_ has me scratching my head.

Here's the PKGBUILD for Arch/Manjaro - it links to a .deb file - https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=protonmail-bridge . I think you'd need an actual account to use it, but maybe others can also test or decompile it? There isn't much documentation at all, so I can't seem to locate any decent logs from that side.

**Comment by th3raid0r** [comment]
Oh, one more datapoint! I have an option to run this software in a _combined_ and _separate_ mode. Combined places all of my Protonmail addresses in the same inbox. Separate mode creates unique port/password combinations for each account. Both modes seem to have the issue.

I mention this, because I could imagine a scenario where this only affects "combined" mode by mixing up the aliases.

**Comment by ChristophWurst** [comment]
Can you set up any other IMAP accounts? If that is the case we can at least rule out issues with the instance in general before we go any deeper.

**Comment by GLaDTheresCake** [comment]
I just confirmed this doesn't work on my system either, and setting up an IMAP to my other (outlook) account works just fine and shows the message body.

**Comment by th3raid0r** [comment]
@GLaDTheresCake - How about emails with attachments? Do those open like they do for me?

**Comment by GLaDTheresCake** [comment]
Yes, they do.

**Comment by th3raid0r** [comment]
This appears to still be an issue. (I just check in on this occasionally)

`

  | mail | OCA\Mail\Exception\ServiceException: Could not load message/var/www/html/apps/mail/lib/Controller/MessagesController.php - line 219: OCA\Mail\Service\MailManager->getMessage(OCA\Mail\Account {}, OCA\Mail\Db\Mailbox { id: 74}, 767, true)/var/www/html/lib/private/AppFramework/Http/Dispatcher.php - line 170: OCA\Mail\Controller\MessagesController->getBody(13, "QWxsIE1haWw=", 767)/var/www/html/lib/private/AppFramework/Http/Dispatcher.php - line 100: OC\AppFramework\Http\Dispatcher->executeController(OCA\Mail\Con ... {}, "getBody")/var/www/html/lib/private/AppFramework/App.php - line 137: OC\AppFramework\Http\Dispatcher->dispatch(OCA\Mail\Con ... {}, "getBody")/var/www/html/lib/private/AppFramework/Routing/RouteActionHandler.php - line 47: OC\AppFramework\App::main("OCA\\Mail\\ ... r", "getBody", OC\AppFramew ... {}, { accountId: ... "})<<closure>>OC\AppFramework\Routing\RouteActionHandler->__invoke({ accountId: ... "})/var/www/html/lib/private/Route/Router.php - line 297: call_user_func(OC\AppFramew ... {}, { accountId: ... "})/var/www/html/lib/base.php - line 1012: OC\Route\Router->match("/apps/mail/ ... y")/var/www/html/index.php - line 37: OC::handleRequest()Caused by OCP\AppFramework\Db\DoesNotExistException: Mail body for this mail(767) could not be loaded/var/www/html/apps/mail/lib/Model/IMAPMessage.php - line 521: OCA\Mail\Model\IMAPMessage->loadBodyData(Horde_Mime_Part { parent: null}, 1)/var/www/html/apps/mail/lib/Model/IMAPMessage.php - line 394: OCA\Mail\Model\IMAPMessage->handleHtmlMessage(Horde_Mime_Part { parent: null}, 1)/var/www/html/apps/mail/lib/Model/IMAPMessage.php - line 343: OCA\Mail\Model\IMAPMessage->getPart(Horde_Mime_Part { parent: null}, 1)/var/www/html/apps/mail/lib/Model/IMAPMessage.php - line 94: OCA\Mail\Model\IMAPMessage->loadMessageBodies()/var/www/html/apps/mail/lib/IMAP/MessageMapper.php - line 211: OCA\Mail\Model\IMAPMessage->__construct(Horde_Imap_C ... e}, "All Mail", 767, null, true)<<closure>>OCA\Mail\IMAP\MessageMapper->OCA\Mail\IMAP\{closure}("*** sensiti ... *")/var/www/html/apps/mail/lib/IMAP/MessageMapper.php - line 225: array_map(Closure {}, [ "*** sensi ... "])/var/www/html/apps/mail/lib/IMAP/MessageMapper.php - line 63: OCA\Mail\IMAP\MessageMapper->findByIds(Horde_Imap_C ... e}, "All Mail", [ 767], true)/var/www/html/apps/mail/lib/Service/MailManager.php - line 152: OCA\Mail\IMAP\MessageMapper->find(Horde_Imap_C ... e}, "All Mail", 767, true)/var/www/html/apps/mail/lib/Controller/MessagesController.php - line 219: OCA\Mail\Service\MailManager->getMessage(OCA\Mail\Account {}, OCA\Mail\Db\Mailbox { id: 74}, 767, true)/var/www/html/lib/private/AppFramework/Http/Dispatcher.php - line 170: OCA\Mail\Controller\MessagesController->getBody(13, "QWxsIE1haWw=", 767)/var/www/html/lib/private/AppFramework/Http/Dispatcher.php - line 100: OC\AppFramework\Http\Dispatcher->executeController(OCA\Mail\Con ... {}, "getBody")/var/www/html/lib/private/AppFramework/App.php - line 137: OC\AppFramework\Http\Dispatcher->dispatch(OCA\Mail\Con ... {}, "getBody")/var/www/html/lib/private/AppFramework/Routing/RouteActionHandler.php - line 47: OC\AppFramework\App::main("OCA\\Mail\\ ... r", "getBody", OC\AppFramew ... {}, { accountId: ... "})<<closure>>OC\AppFramework\Routing\RouteActionHandler->__invoke({ accountId: ... "})/var/www/html/lib/private/Route/Router.php - line 297: call_user_func(OC\AppFramew ... {}, { accountId: ... "})/var/www/html/lib/base.php - line 1012: OC\Route\Router->match("/apps/mail/ ... y")/var/www/html/index.php - line 37: OC::handleRequest()
-- | -- | --


`

**Comment by th3raid0r** [comment]
I finally found a workaround. 

https://github.com/emersion/hydroxide 

This open source implementation of the ProtonMail-Bridge is slow, but it gets the job done. 

I suppose this really indicates that the issue is with the ProtonMail-Bridge application (perhaps something to do with TLS).

For those who are also looking for a working protonmail solution, try hydroxide instead.

@ChristophWurst - With these findings, you could probably close this.
