### ISSUE TITLE
Move mails on mobile/touch devices

### ISSUE THREAD

**Issue by plastikschnitzer** [nextcloud/mail#255]
#211 gives the option to move mails, but not on mobile/touch devices. 

We need to discuss and find a way how to implement this feature here. 

Here is an example how its solved in the samsung mail app, moving an email to the side opens some additional options like move mail, mark as unread and others:

![screenshot_20161218-174638](https://cloud.githubusercontent.com/assets/10254335/21295614/432355f6-c559-11e6-9ea3-35b59e557d6a.png)

---------------------------

Another way to implement is to give the option to select (multiple) emails and then have a menu which offers options like move mails, mark as …, delete and maybe others.

Best regards,
Plastikschnitzer

**Comment by ChristophWurst** [comment]
summoning @jancborchardt @eppfel @juliushaertl 😀

**Comment by 1337sup3rh4x0r** [comment]
How about a simple "move" button below the email (next to answer / forward buttons) that offers that list of folders when it is clicked this could also be used by people on desktops who are not that safe with drag and drop (thinking of my grandmother)

**Comment by stefan-niedermann** [comment]
@plastikschnitzer nice idea but those kinds of swipe gestures are very hard to discover for a user. also swipe is often used to delete an item and users could be scared of do it.

**Comment by jancborchardt** [comment]
We should do it exactly how we do it in the mobile interface of the Files app: A 3-dot-icon with the menu entries. The delete action etc can also go in there then.

**Comment by plastikschnitzer** [comment]
@stefan-niedermann Yes you are right, I discovered the swipe gesture by accident ...
@jancborchardt Thats good! May we also have an option for mass-select like in the file app if you delete files? Moving mails one by will get annoying if you have lots of emails.

**Comment by jancborchardt** [comment]
We now have a 3-dot action menu on every message, and a "Move" entry could just be added there, between "Mark read/unread" and "Delete".

This would open a modal picker with the list of folders to pick, much like the "Move or copy" action in Files which shows a file picker.


------------

> May we also have an option for mass-select like in the file app if you delete files? Moving mails one by will get annoying if you have lots of emails.

Yes, but multiselect is separate and discussed at https://github.com/nextcloud/mail/issues/890 :)

**Comment by jancborchardt** [comment]
Some more points:

- In the action menu in the message list, as well as in the header in the detail view.
- Both times, the action should be directly below the "Mark read/unread" action
- It should open a modal with the folder list to pick the destination folder,
- Ideally also separated by accounts so you could move messages between different accounts, if that is possible. In that case it would be good if the account where the mail is currently in is sorted up top so if you just want to move inside of that account, you can quickly do that without scrolling.

**Comment by ChristophWurst** [comment]
Hey there,

I'd just like to let you know that due to the [ongoing issue with Bountysource](https://help.nextcloud.com/t/dont-use-bountysource-anymore/84943) we're discussing ways to move to a different platform. As it looks right now, Bountysource might claim some of the money that was contributed by the community. We will try our best to prevent that. Historically we – the Nextcloud GmbH employees – simply put the claimed bounties back to other tickets until one was solved by a community member. So the money was always *from the community* and *for the community*. We'll therefore move to a better platform and currently don't post any new bounties until this situation is resolved. The current goal is to move/donate the money to [Nextcloud include](https://nextcloud.com/include/) but details will follow in the [forum post](https://help.nextcloud.com/t/dont-use-bountysource-anymore/84943).

Hope this makes sense. If you have any questions please ask them on the forum. This comment will be copy-pasted to all open issues with bounties.

Christoph and the Mail team

**Comment by HLFH** [comment]
Besides forum post, see main GitHub discussion about BS here: https://github.com/nextcloud/mail/issues/44#issuecomment-645487878.

**Comment by st3iny** [comment]
I'm willing to implement the move context menu item and the folder selection modal. I searched the nextcloud server repository for the file move modal code but couldn't find it. Does anyone here know if it is reusable or do I have to start from scratch?

**Comment by ChristophWurst** [comment]
Hi @st3iny :)

You can find our current component library at https://github.com/nextcloud/nextcloud-vue. But we indeed do not have a folder picker yet, this is still the biggest blocker for this feature. However, there is a modal component that should be easy to use for this.

**Comment by dehnhardt** [comment]
I created a [folderpicker](https://github.com/nextcloud/mail/blob/1896b03874f2dc65daf8a04e1e42be9a8fffe8e7/src/components/MailboxPicker.vue) for https://github.com/nextcloud/mail/pull/3334. It is based on @riophae/vue-treeselect. 
Maybe this is a starting point - and maybe we should create a separate branch for that.

**Comment by ChristophWurst** [comment]
@dehnhardt awesome! Some quick remarks: let's use the term mailboxes consistently, I recently started to abandon "folder" to reduce the confusion, we'll only use this in user-facing strings. And you might want to change the method invoked by the mounted lifecycle hook into a simple computed property. That will also ensure that changes in the mailbox hierarchy propagate automagically :)

**Comment by st3iny** [comment]
@dehnhardt Your component seems to be a good starting point. Should I wait for the associated pull request to be merged or can you merge it separately?

**Comment by ChristophWurst** [comment]
> maybe we should create a separate branch for th

Yeah and of course feel free to push that as a separate branch, though I'm unsure how we could test the component without making use of it yet

**Comment by dehnhardt** [comment]
@st3iny: To wait for that pull request would mean to wait several weeks. That's the reason why I suggested to make a separate branch with only that component. 
@ChristophWurst: Yeah, hard to test on a separate branch. How is this done with other components?

**Comment by ChristophWurst** [comment]
We typically only add them if we need them. Like on the feature branch directly.

**Comment by dehnhardt** [comment]
see PR: https://github.com/nextcloud/mail/pull/3571

**Comment by dehnhardt** [comment]
Christoph recently merged the component into the master branch.

**Comment by st3iny** [comment]
Awesome! I will start to work on the move feature as soon as possible.
