### ISSUE TITLE
Collect user interaction data

### ISSUE THREAD

**Issue by ChristophWurst** [nextcloud/mail#2558]
For https://github.com/nextcloud/mail/projects/7 we need data about important interactions of a user.

- [x] Requires https://github.com/nextcloud/mail/issues/2559

As a start we should focus on the people who interacted, hence only consider the email addresses. In a step we can extend the logic to also collect subject or even the message content.

* Messages read -> save sender email
* Messages starred -> save sender email
* Messages deleted -> save sender email
* Message sent -> save all recipients (should also work for replies)

I would propose to do this in two parts
* Emit events with https://nextcloud.github.io/nextcloud-event-bus/ for the actions above -> @GretaD 
* Debounce and combine events and send to back-end -> @ChristophWurst

**Comment by republicus** [comment]
Will this also work with drafts as I reported in #2850 ?

**Comment by ChristophWurst** [comment]
I don't think drafts should be taken into consideration. Also that ticket is about a bug, not a feature.

We might not need this expensive data collection at all. #2796 does it with just the cached data.

**Comment by ChristophWurst** [comment]
For the first version of https://github.com/nextcloud/mail/pull/2796 we won't need any of this as we have that data locally already.
