### ISSUE TITLE
Can not access IMAP account

### ISSUE THREAD

**Issue by schinni15** [nextcloud/mail#2570]
### Expected behavior
Mail account creation failed when password starts with exclammation mark (!)

### Mail app

**Mail app version:** (see apps admin page, e.g. 0.5.3)
1.1.1

**Mailserver or service:** (e.g. Outlook, Yahoo, Gmail, Exchange,...)
Dovecot 

### Server configuration

**Operating system**: (e.g. Debian 8)
Ubuntu 19.10

**Web server:** (e.g. Apache, Nginx,...)
Apache

**Database:** (e.g. MariaDB, SQLite or PostgreSQL)
MariaDB

**PHP version:** (e.g. 7.0)
7.3

**Nextcloud Version:** (see admin page, e.g. 13.0.2)
18.0

**Comment by ChristophWurst** [comment]
The Nextcloud mail app offers an extensive logging system to make it easier identifying and tracking down bugs. Please enable [debug mode](https://docs.nextcloud.com/server/13/developer_manual/general/devenv.html#enabling-debug-mode) and set the log [level to debug](https://docs.nextcloud.com/server/13/admin_manual/configuration_server/logging_configuration.html) in your admin settings. Then, try to reproduce your issue and take another look at `data/nextcloud.log`, `data/horde_imap.log` and `data/horde_smtp.log`.

Please remove any sensitive information before posting.

**Comment by schinni15** [comment]
Log attached
[syslog_part.log](https://github.com/nextcloud/mail/files/4123376/syslog_part.log)
[horde_imap.log](https://github.com/nextcloud/mail/files/4123377/horde_imap.log)
[horde_smtp.log](https://github.com/nextcloud/mail/files/4123378/horde_smtp.log)

**Comment by ChristophWurst** [comment]
Strange. Both IMAP and SMTP show successful logins.

**Comment by ChristophWurst** [comment]
End the nextcloud error about the IMAP error is from a URl that is only fetched once the account is set up.

**Comment by ChristophWurst** [comment]
Please tell us your steps and how far you get with the setup.

**Comment by schinni15** [comment]
After click on connect I get following error message.
Request failed with status code 500
The mail account is created but does not show any folders or mails.
Any other mailbox works fine.

**Comment by ChristophWurst** [comment]
> C: 28 STATUS Archiv.b&APY-sch (MESSAGES UIDNEXT UIDVALIDITY HIGHESTMODSEQ)
> S: 28 NO Mailbox doesn't exist: Archiv.bösch (0.001 + 0.000 secs).

Happens when the app tries to read all mailboxes initially. Is there anything special about this mailbox? Can other clients open it?

**Comment by schinni15** [comment]
Roundcube, Outlook, Apple Mail are reading this mailbox well

**Comment by schinni15** [comment]
I've renamed this mailbox and removed the german umlaut 'ö'.  Everything is working fine. Changed back with umlaut. Still working now. I can't see any difference. Thanks for your help
