### ISSUE TITLE
update to 18 blocked because of BinaryAdapter permissions

### ISSUE THREAD

**Issue by pieter-groeneweg** [nextcloud/mail#2574]
I am updating 17 to 18 and this is the message I received in the queue:
Just before I updated the mail app. from 1.1.0 to 1.1.1

> X Create backup
> Could not copy "/home/****/public_html/apps/mail/vendor/christophwurst/kitinerary-bin/bin/kitinerary-extractor" to "/mnt/disk_b/data/updater-******/backups/nextcloud-17.0.2.1/apps/mail/vendor/christophwurst/kitinerary-bin/bin/kitinerary-extractor". Source /home/****/public_html/apps/mail/vendor/christophwurst/kitinerary-bin/bin/kitinerary-extractor is not readable. Destination /mnt/disk_b/data/updater-******/backups/nextcloud-17.0.2.1/apps/mail/vendor/christophwurst/kitinerary-bin/bin/kitinerary-extractor is not writable

Checking I see the permissions for /apps/mail/vendor/christophwurst/kitinerary-bin/bin/kitinerary-extractor is set to 1350

I expect this to be 0644.

Is that correct?

Thanks

**Comment by ChristophWurst** [comment]
Should be fixed with https://github.com/nextcloud/mail/pull/2534. We set it to 744.

**Comment by ChristophWurst** [comment]
Reading https://www.php.net/manual/en/function.chmod.php it looks like we might want to add a 0 prefix. But I'm surprised this would even make a difference in php.

**Comment by probastaller** [comment]
Had the same problem updating 17.0.2 to 17.0.3.
Removed mail app and used the automatic updater.
Just had to reinstall the mail app after.

**Comment by ChristophWurst** [comment]
Please try again with 1.1.2, where we set to 0744 (instead of 744). And if you still face the permission problems please file a bug report with all the details about your setup. Thanks!

**Comment by gehkah** [comment]
updating the mail app solved the same problem when i tried to upgrade from 17.0.2 to 17.0.3
