### ISSUE TITLE
Show first line of message as preview

### ISSUE THREAD

**Issue by ChristophWurst** [nextcloud/mail#2579]
### Feature Request

As any other decent IMAP client would do, our should also show the start of the first line of each message in the message list.

#### Summary

See above

---

Caveat: this operation is expensive. We have to fetch the body part. HTML message need special care.

In a later stage we can optimize to omit stuff like greetings or quoted text for bottom replies. For a start, the first line is good enough.

## Implementation idea

We should fetch this data on demand, similar to the avatars. The data should then be written to the message cache #2064 (or memcache? :thinking:) as it is immutable.

**Comment by ChristophWurst** [comment]
# Other products

## Gmail

![](https://lh3.googleusercontent.com/qIbkEqS8l67IApLtveAc5GG8a192K-_4D9xi4f_qDK1aOFiyYUcjPyeBH-vEDnZK7-cIvvuhi0sEuFi_cEeOBU8_NYjHhko3NQ6kpQ=w0)
![](https://lh3.googleusercontent.com/Ql93EuAI4GE0mW1lg7PCOobsoRvkcIpAWYn8Ei108HTHs8icVeehbYGJbBz5TrMWY-6a6wGD=w640-h400-e365)

## Outlook

![](https://www.windowscentral.com/sites/wpcentral.com/files/styles/w830/public/field/image/2017/05/microsoft-outlook-actionable-messages.jpg?itok=zlpWpUFz)

## Apple mail

![](https://d31v04zdn5vmni.cloudfront.net/blog/wp-content/uploads/2015/04/apple-mail1.png)
![](https://d31v04zdn5vmni.cloudfront.net/blog/wp-content/uploads/2014/09/inbox-iphone6-plus.png)

## Android

![](https://d31v04zdn5vmni.cloudfront.net/blog/wp-content/uploads/2015/04/android-gmail-app1.png)

---

Source: https://litmus.com/blog/the-ultimate-guide-to-preview-text-support and google image search

**Comment by miaulalala** [comment]
so this would actually work well with the propsed solution for the iMIP issues I'm fighting with at the moment:

https://github.com/nextcloud/mail/issues/6802#issuecomment-1204351165

**Comment by ChristophWurst** [comment]
Backend part is done via https://github.com/nextcloud/mail/pull/6962

**Comment by ChristophWurst** [comment]
@nimishavijay @jancborchardt I believe we had mockups for this feature but I'm not able to find them. Could you post them here please for the frontend engineer?

**Comment by nimishavijay** [comment]
> I believe we had mockups for this feature but I'm not able to find them. 

Actually we didn't. I'd say there should be one line under the subject in the same font size as the subject and in normal text (not bold) regardless of whether the email is unread or read.

![image](https://user-images.githubusercontent.com/52440189/183673030-e02885c1-68f5-4dfe-930b-3c962da9e038.png)

cc @jancborchardt on this

**Comment by ChristophWurst** [comment]
Frontend done via https://github.com/nextcloud/mail/pull/6966

**Comment by ChristophWurst** [comment]
@jancborchardt @nimishavijay where should the preview show on the right pane?

![Bildschirmfoto vom 2022-08-17 11-17-07](https://user-images.githubusercontent.com/1374172/185082509-7c857a81-29dc-4303-bf53-e2f842fcbec8.png)

I'm tempted to put it left of the date but the space is precious https://github.com/nextcloud/mail/issues/7010

**Comment by jancborchardt** [comment]
Preview should:
- go in the subline below the sender
- be in color-text-maxcontrast
- only show for collapsed mails cause for expanded ones it would duplicate otherwise

Regarding soace, see my comment on the issue you linked.

**Comment by meichthys** [comment]
It would be nice if this was a configurable option. Most imap clients default to 1 line but have the option to disable or change the number of preview lines (usually between 0 and 3)

**Comment by ChristophWurst** [comment]
Frontend part 2/2 done in https://github.com/nextcloud/mail/pull/7021
