### ISSUE TITLE
Authenticate Gmail directly in the app

### ISSUE THREAD

**Issue by enoch85** [nextcloud/mail#259]
### Steps to reproduce
1. Add a new Gmail account

### Expected behaviour
A pop up should show up that authenticate the user to Gmail and allows 3:dparty apps. Something like this:
![](https://developer.chrome.com/static/images/identity-api-ui.png)

### Actual behaviour
As a user you have to manually authenticate the mail app to allow access to Gmail. https://github.com/nextcloud/mail#gmail

### Mail app

**Mail app version:** (see apps admin page)
0.6.2
**Mailserver or service:** (e.g. Outlook, Yahoo, Gmail, Exchange,...)
Gmail
**Transport security - IMAP:** (None, SSL, TLS, STARTTLS) 
TLS
**Transport security - SMTP:** (None, SSL, TLS, STARTTLS)
TLS
**Number of accounts:**
2

### Server configuration
**Operating system**:
Ubuntu Server 16.04
**Web server:**
Apache 2.4
**Database:**
MySQL 5.7
**PHP version:**
7.0
**Version:** (see admin page)
Nextcluud 11
**Updated from an older version or fresh install:**
Fresh install

#### Client configuration
**Browser:**
Chrome
**Operating system:**
Ubuntu Desktop 16.04

**Comment by ColdSphinX** [comment]
In my case Gmail denies access to the app due to it's classification as less secure app.

**Comment by ChristophWurst** [comment]
OAuth and other special authentication schemes are out of scope right now IMO. We will stick to class IMAP/SMTP authentication.

**Comment by ChristophWurst** [comment]
It's also not really usable with a self-hosted service because everyone would have to create an app I presume, just like when you want to mount Dropbox in Nextcloud. Not very pleasant to use IMO. I'm closing this ticket now.

**Comment by tomastd** [comment]
And won't be interesting a combo box with some mail service providers standard setup?

**Comment by ChristophWurst** [comment]
> And won't be interesting a combo box with some mail service providers standard setup?

We do have autoconfig in place and it works fairly well with both the famous providers and custom ones. If it doesn't work for you, just open an issue 😉
