### ISSUE TITLE
Non-square avatars are stretched 

### ISSUE THREAD

**Issue by juliushaertl** [nextcloud/mail#26]
### Steps to reproduce
1. Add a contact with email address and avatar that is not square (contacts app)
2. Open mail-folder with email from this contact
### Expected behaviour

The avatar should be fit into the circle.
### Actual behaviour

The avatar is stretched to the size of the circle.
### Mail app

**Mail app version:** 0.5.4

**Comment by vkolova** [comment]
Claiming this!

**Comment by sagorika1996** [comment]
I would like to work on this!

**Comment by ChristophWurst** [comment]
> I would like to work on this!

Thanks!
