### ISSUE TITLE
Vendor JS fails integrity check

### ISSUE THREAD

**Issue by kaffeeringe** [nextcloud/mail#260]
### Steps to reproduce
1. I downloaded Mail 0.6.2 for NC10 from https://apps.nextcloud.com/apps/mail and installed it. It works well.
2. NC10 reports a failed integrity check on one of the JavaScript-files.
3. I unpacked it again and reuploaded it. Same result:

Results
=======
- mail
	- INVALID_HASH
		- js/vendor/jquery-visibility/jquery-visibility.js

Raw output
==========
Array
(
    [mail] => Array
        (
            [INVALID_HASH] => Array
                (
                    [js/vendor/jquery-visibility/jquery-visibility.js] => Array
                        (
                            [expected] => 5f31ebdd4eae884d716fe42aaccb4576dff304317c6680778e2fedd8f7532797cc9cc762b0d8abd88bd51414b6670d1a87d0146a26d5f4b219b59ba10b1354a2
                            [current] => 04f9124c3ad73ee9f0228a5a8ee88200998335cbf1de033baa801b43dd08922ac363507b11bc1c64b5b1b7c65a9fb75deb15f2dba383461f88773a2aaa50c648
                        )

                )

        )

)

**Comment by ChristophWurst** [comment]
This should be resolved with newer versions of the app. Please re-open if you still get the error.

**Comment by ripper17** [comment]
I got this after the update to 0.7.3:

`Technical information
=====================
The following list covers which files have failed the integrity check. Please read
the previous linked documentation to learn more about the errors and how to fix
them.

Results
=======
- mail
	- INVALID_HASH
		- vendor/doctrine/instantiator/src/Doctrine/Instantiator/Exception/UnexpectedValueException.php

Raw output
==========
Array
(
    [mail] => Array
        (
            [INVALID_HASH] => Array
                (
                    [vendor/doctrine/instantiator/src/Doctrine/Instantiator/Exception/UnexpectedValueException.php] => Array
                        (
                            [expected] => 472909b8419ce9621486019580610aba1f4c607fb82e8ce3114516b7f2c5eb3d623e25d1e2aaf16b3e1ccbaf6fbe345e40d28164e03802c76f4ec4af6c0a470e
                            [current] => cf83e1357eefb8bdf1542850d66d8007d620e4050b5715dc83f4a921d36ce9ce47d0d13c5d85f2b0ff8318d2877eec2f63b931bd47417a81a538327af927da3e
                        )

                )

        )

)`

**Comment by ChristophWurst** [comment]
@ripper17 please file a new issue. Thanks
