### ISSUE TITLE
Writing mode

### ISSUE THREAD

**Issue by ramikilany** [nextcloud/mail#2611]
### Feature Request

In the nextcloud mail, there is an option which is the writing mode when I switch to Rich text mode nothing happens in the newly created message. In the end, I need to have a tool menu like the Wordpad or the menu which has the align-left, center and right for example text bold, italic and underline, and so on. and if would be an option to write from right-to--left message (Arabic for example)
#### Summary
Text menu toolbar (rich text mode)

**Comment by ChristophWurst** [comment]
It's an inline editor. Focus some text and a magic toolbar will appear :)

**Comment by StCyr** [comment]
there's no text-alignment and heading tools though :(

**Comment by ChristophWurst** [comment]
-> https://github.com/nextcloud/mail/pull/2623

**Comment by ChristophWurst** [comment]
> and if would be an option to write from right-to--left message (Arabic for example)

The editor *should* do this automatically: https://ckeditor.com/docs/ckeditor5/latest/features/ui-language.html#righttoleft-rtl-languages-support. But right now there seems to be an issue with translations.
