### ISSUE TITLE
Unable to load imap directory which name contains specific characters.

### ISSUE THREAD

**Issue by r0d0dendr0n** [nextcloud/mail#2614]
### Expected behavior
I expected that the IMAP mail folder called "Bezpośrednie" (Polish for "Direct") would be properly displayed, showing it's messages list. All other folders are displayed, even the one called "Wysłane" (Polish for "Sent").

### Actual behavior
The selected folder ("Bezpośrednie") does not display. Instead I get an error message saying that the folder cannot be displayed. See attached screenshot for visual details.

### Mail app

**Mail app version:** 0.11.1

**Mailserver or service:** Dovecot 2.2.22

### Server configuration

**Operating system**: Ubuntu 16.04.5 LTS

**Web server:** Apache 2.4.18

**Database:** PostgreSQL 9.5

**PHP version:** 7.0.33-0ubuntu0.16.04.9

**Nextcloud Version:** 15.0.12

#### Client configuration
**Browser:** Firefox 72.0.1 (64 bity)

**Operating system:** Arch Linux rolling

![nextcloud-mail](https://user-images.githubusercontent.com/41265927/73759809-c5469a00-476c-11ea-8d2e-c09e395bdb74.png)
(My test server domain name has been edited out.)

**Comment by ChristophWurst** [comment]
> **Nextcloud Version:** 15.0.12

This version has reached EOL. Please try again with 16, or preferably 17 for the latest Mail version. THanks.

**Comment by r0d0dendr0n** [comment]
Wow, I didn't realize that 15 is EOL. I will perform an upgrade and check this issue after.

**Comment by r0d0dendr0n** [comment]
I have upgraded to:
PHP 7.2.27-5+ubuntu16.04.1+deb.sury.org+2
Nextcloud 17.0.3
Mail app 1.1.2

The update suprisingly smooth.

I have removed the mail account from the Mail app and recreated it. Unfortunately I still can't open the "Bezpośrednie" folder. The "Wysłane" still works. However the error I get is different now.

The request for "(nextcloud server)/apps/mail/api/accounts/8/folders/QmV6cG%2FFm3JlZG5pZQ%3D%3D/messages" gives status HTTP 404 Not Found. The developers console gives an error, which is visible in the screenshot. No matter how long I wait, the loading animation persists.
![nextcloud-mail2](https://user-images.githubusercontent.com/41265927/73770349-8d475300-477c-11ea-9c5f-8b54c6118ad3.png)

**Comment by r0d0dendr0n** [comment]
I have fiddled with this for a while and it occurs that if I create a folder called "test_folder_ś" I can easily see it's messages (It was empty, but the content was displayed). However if I add a folder "test_ś_folder" then I can't see it's content. Funny, because "ś_test_folder" also works. Even funnier, because "ś_test_ś_folder" doesn't work :-). This means that this bug works when the "ś" is not the first, nor the last character in the folder name.
