### ISSUE TITLE
CKEditor not translated

### ISSUE THREAD

**Issue by ChristophWurst** [nextcloud/mail#2624]
### Expected behavior
We tell CKEditor to use the Nextcloud language if we can find locales. All UI text should be translated, thus. This used to work.

### Actual behavior
UI is always in English.

### Mail app

**Mail app version:**

master

**Comment by StCyr** [comment]
I think it works now. At least it does for French on master (1.8.1)

**Comment by ChristophWurst** [comment]
Totally, I fixed that with come webpack config fix IIRC
