### ISSUE TITLE
Avatars Fehler 404

### ISSUE THREAD

**Issue by ThorstenUm** [nextcloud/mail#2626]
Ich fange wegen Hacker 404 Fehlercodes ab. Sperre mich selber aus, wenn ich die Mail App öffne, da die Avatare von Usern ohne Bilder im Kontakt wohl Fehler produzieren, Fehlermeldung in Apache:+
`[06/Feb/2020:18:27:13 +0100] "GET /index.php/apps/mail/api/avatars/url/fail2ban%40sv6.fritz.box HTTP/1.1" 404 821 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:72.0) Gecko/20100101 Firefox/72.0"
`

**Comment by ChristophWurst** [comment]
404 is a valid HTTP code. We use HTTP codes semantically, thus this is fine.

**Comment by ThorstenUm** [comment]
Aber das kann doch nicht richtig sein, dass die Mail App Fehler ausgibt, wenn ein Avatar nicht verfügbar ist. Dann muss ich wohl zu einem anderen Mailer wechseln, der keine unnötigen Fehler ausgibt?

Es gibt im Netz zig Bots die eigenen Seiten nach offenen Lücken durchsuchen. Dadurch produzieren sie Fehlermeldungen, die ich wiederum dann sperre. Da kommt mir die Mail App mit den unnötigen Fehlern in die Quere und stört unnötig die Gefahrenabwehr.
