### ISSUE TITLE
cant install mail

### ISSUE THREAD

**Issue by bhart2489** [nextcloud/mail#2627]
### Expected behavior
Tell us what should happen

### Actual behavior
The table with name 'nextcloud.oc_mail_mailboxes' already exists.
when trying to install mail it hung ( i let it do its thing for an hour) after refreshing the page i got the error above

### Mail app

**Mail app version:** (see apps admin page, e.g. 0.5.3)
1.1.2

**Mailserver or service:** (e.g. Outlook, Yahoo, Gmail, Exchange,...)

### Server configuration

**Operating system**: (e.g. Debian 8)
unraid docker
**Web server:** (e.g. Apache, Nginx,...)

**Database:** (e.g. MariaDB, SQLite or PostgreSQL)
MariaDB
**PHP version:** (e.g. 7.0)

**Nextcloud Version:** (see admin page, e.g. 13.0.2)
18
#### Client configuration
**Browser:** (e.g. Firefox 48)
chrome 
**Operating system:** (e.g. Arch Linux)

**Comment by ChristophWurst** [comment]
Which version was installed before? Did you update via the app store? Did you ever try to set up a development version from Github?
