### ISSUE TITLE
Creating account failed: Could not open secure TLS connection to the server

### ISSUE THREAD

**Issue by guzzard** [nextcloud/mail#264]
Issue seem to be related to smtp.fsdata.se specifically. Is it possible to pinpoint the issue somehow?

### Steps to reproduce
1. Try to create account without 'app.mail.transport' => 'php-mail' in config.php 
2. Try to send email without 'app.mail.transport' => 'php-mail' in config.php

### Expected behaviour
Should be possible to create account and send email.

### Actual behaviour
- Error when trying to create account. Possible to create account with 'app.mail.transport' => 'php-mail' in config.php
- Error when trying to send email without 'app.mail.transport' => 'php-mail' in config.php

### Mail app

**Mail app version:** 0.6.2

**Mailserver or service:**
imap: Microsoft Exchange 2013 IMAP4 service
smtp: Microsoft ESMTP MAIL Service

**Transport security - IMAP:** SSL (port 993)

**Transport security - SMTP:** STARTTLS (port 587)

**Number of accounts:** 1

### Server configuration
**Operating system**: Arch Linux, kernel 4.8.13

**Web server:** apache 2.4.25

**Database:** mariadb 10.1.20

**PHP version:** php 7.0.14

**Version:** Nextcloud 11.0.0 (stable)

**Updated from an older version or fresh install:** fresh install

**List of activated apps:**
- admin_audit: 1.1.0
- comments: 1.1.0
- contacts: 1.5.2
- dav: 1.1.1
- federatedfilesharing: 1.1.1
- federation: 1.1.1
- files: 1.6.1
- files_pdfviewer: 1.0.1
- files_sharing: 1.1.1
- files_texteditor: 2.2
- files_trashbin: 1.1.0
- files_versions: 1.4.0
- files_videoplayer: 1.0.0
- gallery: 16.0.0
- logreader: 2.0.0
- lookup_server_connector: 1.0.0
- mail: 0.6.2
- news: 10.1.0
- nextcloud_announcements: 1.0
- notifications: 1.0.1
- password_policy: 1.1.0
- provisioning_api: 1.1.0
- serverinfo: 1.1.1
- sharebymail: 1.0.1
- survey_client: 0.1.5
- systemtags: 1.1.3
- templateeditor: 0.2
- theming: 1.1.1
- twofactor_backupcodes: 1.0.0
- updatenotification: 1.1.1
- workflowengine: 1.1.1

**The content of config/config.php:**
{
    "system": {
        "instanceid": "oc8bdcgjcwom",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "***REMOVED SENSITIVE VALUE***",
            "***REMOVED SENSITIVE VALUE***",
            "localhost"
        ],
        "memcache.local": "\\OC\\Memcache\\APCu",
        "overwrite.cli.url": "***REMOVED SENSITIVE VALUE***",
        "dbtype": "mysql",
        "version": "11.0.0.10",
        "dbname": "owncloud",
        "dbhost": "localhost",
        "dbtableprefix": "oc_",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "installed": true,
        "loglevel": 2,
        "mail_from_address": "noreply",
        "mail_domain": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpauthtype": "LOGIN",
        "mail_smtpname": "***REMOVED SENSITIVE VALUE***",
        "mail_smtppassword": "***REMOVED SENSITIVE VALUE***",
        "mail_smtphost": "smtp.fsdata.se",
        "mail_smtpport": "587",
        "mail_smtpauth": 1,
        "mail_smtpsecure": "tls",
        "mail_smtpmode": "php",
        "forcessl": true,
        "theme": "",
        "maintenance": false,
        "trashbin_retention_obligation": "auto",
        "app.mail.imaplog.enabled": true,
        "app.mail.smtplog.enabled": true,
        "app.mail.imap.timeout": 20,
        "app.mail.smtp.timeout": 20,
        "singleuser": false,
        "htaccess.RewriteBase": "\/nextcloud",
        "updater.release.channel": "stable"
    }
}

#### Client configuration
**Browser:** Same issue regardless of browser.

**Operating system:**

##### Web server error log
No errors shown in the apache log.

##### Server log (data/nextcloud.log)
{"reqId":"\/Q2FauUWP55UphPb1Vre","remoteAddr":"192.168.1.1","app":"mail","message":"Creating account failed: Could not open secure TLS connection to the server.","level":3,"time":"2016-12-27T15:27:23+00:00","method":"POST","url":"\/nextcloud\/apps\/mail\/accounts","user":"REMOVED","version":"11.0.0.10"}
{"reqId":"WW0IZ0jTHKZIV+N8lQy+","remoteAddr":"192.168.1.1","app":"mail","message":"Sending mail failed: Could not open secure TLS connection to the server.","level":3,"time":"2016-12-27T15:56:37+00:00","method":"POST","url":"\/nextcloud\/apps\/mail\/accounts\/2\/send","user":"REMOVED","version":"11.0.0.10"}

##### Horde IMAP log (data/horde_imap.log)
------------------------------
>> Tue, 27 Dec 2016 15:41:53 +0000
>> Connection to: imap://imap.fsdata.se:993/
>> Server connection took 0.1097 seconds.
S: * OK The Microsoft Exchange 2013 IMAP4 service is ready (P01).
C: 1 CAPABILITY
S: * CAPABILITY IMAP4 IMAP4rev1 AUTH=PLAIN UIDPLUS CHILDREN IDLE NAMESPACE LITERAL+
S: 1 OK CAPABILITY completed.
>> Command 1 took 0.0169 seconds.
C: 2 [INITIAL CLIENT RESPONSE (username: [removed])]
S: +
C: [password removed]
S: 2 OK AUTHENTICATE completed.
>> Command 2 took 0.3008 seconds.
C: 3 CAPABILITY
S: * CAPABILITY IMAP4 IMAP4rev1 AUTH=PLAIN UIDPLUS ID CHILDREN IDLE NAMESPACE LITERAL+
S: 3 OK CAPABILITY completed.
>> Command 3 took 0.0136 seconds.
>> CACHE: Using the OCA\Mail\Cache\Cache storage driver.
C: 4 LOGOUT
S: * BYE Microsoft Exchange Server 2013 IMAP4 server signing off.
S: 4 OK LOGOUT completed.
>> Command 4 took 0.0128 seconds.
------------------------------

##### Horde SMTP log (data/horde_smtp.log)
------------------------------
>> Tue, 27 Dec 2016 15:41:53 +0000
>> Connection to: smtp://smtp.fsdata.se:587
S: 220 smtp.fsdata.se Microsoft ESMTP MAIL Service ready at Tue, 27 Dec 2016 16:41:26 +0100
C: EHLO archserver
S: 250-smtp.fsdata.se Hello [85.224.208.244]
S: 250-SIZE 52428800
S: 250-PIPELINING
S: 250-DSN
S: 250-ENHANCEDSTATUSCODES
S: 250-STARTTLS
S: 250-AUTH LOGIN
S: 250-8BITMIME
S: 250-BINARYMIME
S: 250 CHUNKING
C: STARTTLS
S: 220 2.0.0 SMTP server ready
C: QUIT
**>> ERROR: Server closed the connection.**
------------------------------

##### Browser log
On send: POST https://removed/nextcloud/apps/mail/accounts/2/send 500 (Internal Server Error)

**Comment by ChristophWurst** [comment]
> C: STARTTLS
> S: 220 2.0.0 SMTP server ready
> C: QUIT

To me that looks like a valid response from the server according to https://tools.ietf.org/html/rfc3207#section-4

**Comment by guzzard** [comment]
I'm not entirely sure but I suspect that it might be related to the certificate. The certificate used is for fsdata.se or imap.fsdata.se but but smtp.fsdata.se is not included in the domains in the certificate. Not 100% sure if that's the problem thought.

**Comment by fskale** [comment]
Hi,
perhaps i can update your problem since i ran into it too.
The problem is, that the swiftmailer doesn'z check for DNS ALT Names but only for the CN.
So, if you use e.g letsencrtypt and use DNS ALT names it only will work for the CN but not the DNS ALT name.
So swiftmailer should take care about DNS ALT NAMES.
Rgds.
Franz

**Comment by ChristophWurst** [comment]
> So swiftmailer should take care about DNS ALT NAMES.

FYI we don't use switfmailer but Horde.
