### ISSUE TITLE
Question about privacy and security of this app.

### ISSUE THREAD

**Issue by GammaPi** [nextcloud/mail#2646]
### Question

How secure is this app? Isn't it possible that a malicious email would perform an XSS attack to steal my login token. What is done to ensure the security mail app since it introduces external content.

#### Summary

How secure is this app?

**Comment by ChristophWurst** [comment]
The HTML is sanitized and displayed in a sandboxed iframe. External resources are blocked by default. Links go through a redirection page to strip any referrers.

If you think that we missed something please head over to https://hackerone.com/nextcloud and report it.
