### ISSUE TITLE
Mail app cannot find users o Groups

### ISSUE THREAD

**Issue by rollanders** [nextcloud/mail#2668]
### Expected behavior
When I start writing the name or group of recipient the app should propose the Group o user.

### Actual behavior
The app does not propose a name o Group

I I write the name of the Group the message is not sent 
I get an error in the log - see further down

### Mail app

**Mail app version:** (see apps admin page, e.g. 0.5.3)
Mail 1.1.2
**Mailserver or service:** (e.g. Outlook, Yahoo, Gmail, Exchange,...)
IMAP SMTP 

### Server configuration

**Operating system**: (e.g. Debian 8)
Ubuntu 18.0.4
**Web server:** (e.g. Apache, Nginx,...)
Nginx
**Database:** (e.g. MariaDB, SQLite or PostgreSQL)
MariadB
**PHP version:** (e.g. 7.0)
7.3.11
**Nextcloud Version:** (see admin page, e.g. 13.0.2)
17.0.3
#### Client configuration
**Browser:** (e.g. Firefox 48)
Chrome
**Operating system:** (e.g. Arch Linux)
Windows 10
******************************
Error log

[mail] Error: OCA\Mail\Exception\ServiceException: Could not sync messages at <<closure>>

0. /var/www/nextcloud/apps/mail/lib/Controller/FoldersController.php line 102
   OCA\Mail\Service\MailManager->syncMessages(OCA\Mail\Account {}, OCA\Mail\IMAP\Sync\Request {})
1. /var/www/nextcloud/lib/private/AppFramework/Http/Dispatcher.php line 170
   OCA\Mail\Controller\FoldersController->sync(6, "SU5CT1g=", "VTY0MyxWMTUxNzg0MzMwNCxIMTkxNw==", ["642","641","64 ... "])
2. /var/www/nextcloud/lib/private/AppFramework/Http/Dispatcher.php line 99
   OC\AppFramework\Http\Dispatcher->executeController(OCA\Mail\Controller\FoldersController {}, "sync")
3. /var/www/nextcloud/lib/private/AppFramework/App.php line 126
   OC\AppFramework\Http\Dispatcher->dispatch(OCA\Mail\Controller\FoldersController {}, "sync")
4. /var/www/nextcloud/lib/private/AppFramework/Routing/RouteActionHandler.php line 47
   OC\AppFramework\App::main("OCA\\Mail\\Cont ... r", "sync", OC\AppFramework\ ... {}, {accountId: "6", ... "})
5. <<closure>>
   OC\AppFramework\Routing\RouteActionHandler->__invoke({accountId: "6", ... "})
6. /var/www/nextcloud/lib/private/Route/Router.php line 297
   undefinedundefinedcall_user_func(OC\AppFramework\ ... {}, {accountId: "6", ... "})
7. /var/www/nextcloud/lib/base.php line 997
   OC\Route\Router->match("/apps/mail/api/ ... c")
8. /var/www/nextcloud/index.php line 42
   OC::handleRequest()

GET /apps/mail/api/accounts/6/folders/SU5CT1g%3D/sync?syncToken=VTY0MyxWMTUxNzg0MzMwNCxIMTkxNw%3D%3D&uids[]=642&uids[]=641&uids[]=640&uids[]=639&uids[]=638&uids[]=637&uids[]=636&uids[]=635&uids[]=634&uids[]=633&uids[]=632&uids[]=631&uids[]=630&uids[]=629&uids[]=628&uids[]=627&uids[]=626&uids[]=625&uids[]=624&uids[]=623
from  at 2020-02-20T08:36:36+01:00

**Comment by ChristophWurst** [comment]
That error has nothing to do with the problem described. Anything else in the logs? Does the autocomplete reqeust show up in the network tab? Does it return any results?

**Comment by rollanders** [comment]
The autocomplete only works for individual adresses. Not for Groups - as it used to.
I created a Group Test. Tried to send a mail to Test and also to Test(Group). Normally autocomplete should recognise an propose the group but it does not. And when I send a message to Test or to Test(Group) I get an error. 

  {"reqId":"r2Zi1ritnZMLlJIBpWRp","level":3,"time":"2020-02-21T17:56:04+01:00","remoteAddr":"94.254.30.246","user":"NCadmin","app":"mail","method":"POST","url":"/apps/mail/api/accounts/1/send","message":{"Exception":"OCA\\Mail\\Exception\\ServiceException","Message":"Could not send message","Code":0,"Trace":[{"file":"/var/www/nextcloud/apps/mail/lib/Controller/AccountsController.php","line":332,"function":"sendMessage","class":"OCA\\Mail\\Service\\MailTransmission","type":"->","args":["NCadmin",{"__class__":"OCA\\Mail\\Model\\NewMessageData"},null,null,3095]},{"file":"/var/www/nextcloud/lib/private/AppFramework/Http/Dispatcher.php","line":170,"function":"send","class":"OCA\\Mail\\Controller\\AccountsController","type":"->","args":[1,"Test","Test","Test(Group)","","",false,3095,null,null,[],null]},{"file":"/var/www/nextcloud/lib/private/AppFramework/Http/Dispatcher.php","line":99,"function":"executeController","class":"OC\\AppFramework\\Http\\Dispatcher","type":"->","args":[{"__class__":"OCA\\Mail\\Controller\\AccountsController"},"send"]},{"file":"/var/www/nextcloud/lib/private/AppFramework/App.php","line":126,"function":"dispatch","class":"OC\\AppFramework\\Http\\Dispatcher","type":"->","args":[{"__class__":"OCA\\Mail\\Controller\\AccountsController"},"send"]},{"file":"/var/www/nextcloud/lib/private/AppFramework/Routing/RouteActionHandler.php","line":47,"function":"main","class":"OC\\AppFramework\\App","type":"::","args":["OCA\\Mail\\Controller\\AccountsController","send",{"__class__":"OC\\AppFramework\\DependencyInjection\\DIContainer"},{"accountId":"1","_route":"mail.accounts.send"}]},{"function":"__invoke","class":"OC\\AppFramework\\Routing\\RouteActionHandler","type":"->","args":[{"accountId":"1","_route":"mail.accounts.send"}]},{"file":"/var/www/nextcloud/lib/private/Route/Router.php","line":297,"function":"call_user_func","args":[{"__class__":"OC\\AppFramework\\Routing\\RouteActionHandler"},{"accountId":"1","_route":"mail.accounts.send"}]},{"file":"/var/www/nextcloud/lib/base.php","line":997,"function":"match","class":"OC\\Route\\Router","type":"->","args":["/apps/mail/api/accounts/1/send"]},{"file":"/var/www/nextcloud/index.php","line":42,"function":"handleRequest","class":"OC","type":"::","args":[]}],"File":"/var/www/nextcloud/apps/mail/lib/Service/MailTransmission.php","Line":177,"Previous":{"Exception":"Horde_Mime_Exception","Message":"Bad recipient address syntax","Code":205,"Trace":[{"file":"/var/www/nextcloud/apps/mail/vendor/pear-pear.horde.org/Horde_Mime/Horde/Mime/Mail.php","line":479,"function":"send","class":"Horde_Mime_Part","type":"->","args":["\"Test(Group)\"",{"__class__":"Horde_Mime_Headers"},{"send8bit":false,"sep":"\r\n","__class__":"Horde_Mail_Transport_Smtphorde"}]},{"file":"/var/www/nextcloud/apps/mail/lib/Service/MailTransmission.php","line":175,"function":"send","class":"Horde_Mime_Mail","type":"->","args":[{"send8bit":false,"sep":"\r\n","__class__":"Horde_Mail_Transport_Smtphorde"},false,false]},{"file":"/var/www/nextcloud/apps/mail/lib/Controller/AccountsController.php","line":332,"function":"sendMessage","class":"OCA\\Mail\\Service\\MailTransmission","type":"->","args":["NCadmin",{"__class__":"OCA\\Mail\\Model\\NewMessageData"},null,null,3095]},{"file":"/var/www/nextcloud/lib/private/AppFramework/Http/Dispatcher.php","line":170,"function":"send","class":"OCA\\Mail\\Controller\\AccountsController","type":"->","args":[1,"Test","Test","Test(Group)","","",false,3095,null,null,[],null]},{"file":"/var/www/nextcloud/lib/private/AppFramework/Http/Dispatcher.php","line":99,"function":"executeController","class":"OC\\AppFramework\\Http\\Dispatcher","type":"->","args":[{"__class__":"OCA\\Mail\\Controller\\AccountsController"},"send"]},{"file":"/var/www/nextcloud/lib/private/AppFramework/App.php","line":126,"function":"dispatch","class":"OC\\AppFramework\\Http\\Dispatcher","type":"->","args":[{"__class__":"OCA\\Mail\\Controller\\AccountsController"},"send"]},{"file":"/var/www/nextcloud/lib/private/AppFramework/Routing/RouteActionHandler.php","line":47,"function":"main","class":"OC\\AppFramework\\App","type":"::","args":["OCA\\Mail\\Controller\\AccountsController","send",{"__class__":"OC\\AppFramework\\DependencyInjection\\DIContainer"},{"accountId":"1","_route":"mail.accounts.send"}]},{"function":"__invoke","class":"OC\\AppFramework\\Routing\\RouteActionHandler","type":"->","args":[{"accountId":"1","_route":"mail.accounts.send"}]},{"file":"/var/www/nextcloud/lib/private/Route/Router.php","line":297,"function":"call_user_func","args":[{"__class__":"OC\\AppFramework\\Routing\\RouteActionHandler"},{"accountId":"1","_route":"mail.accounts.send"}]},{"file":"/var/www/nextcloud/lib/base.php","line":997,"function":"match","class":"OC\\Route\\Router","type":"->","args":["/apps/mail/api/accounts/1/send"]},{"file":"/var/www/nextcloud/index.php","line":42,"function":"handleRequest","class":"OC","type":"::","args":[]}],"File":"/var/www/nextcloud/apps/mail/vendor/pear-pear.horde.org/Horde_Mime/Horde/Mime/Part.php","Line":1642,"Previous":{"Exception":"Horde_Mail_Exception","Message":"Bad recipient address syntax","Code":205,"Trace":[{"file":"/var/www/nextcloud/apps/mail/vendor/pear-pear.horde.org/Horde_Mime/Horde/Mime/Part.php","line":1620,"function":"send","class":"Horde_Mail_Transport_Smtphorde","type":"->","args":["\"Test(Group)\"",{"From":"intra@korskyrkan-jkpg.se","To":"\"Test(Group)\"","Cc":"","Subject":"Test","Message-ID":"<20200221165604.Horde.n5-59HMZlySBFBZYl81a3Zt@korskyrkan-intra.se>","User-Agent":"Horde Application Framework 5","Date":"Fri, 21 Feb 2020 16:56:04 +0000","Content-Type":"text/plain; charset=utf-8","MIME-Version":"1.0"},null]},{"file":"/var/www/nextcloud/apps/mail/vendor/pear-pear.horde.org/Horde_Mime/Horde/Mime/Mail.php","line":479,"function":"send","class":"Horde_Mime_Part","type":"->","args":["\"Test(Group)\"",{"__class__":"Horde_Mime_Headers"},{"send8bit":false,"sep":"\r\n","__class__":"Horde_Mail_Transport_Smtphorde"}]},{"file":"/var/www/nextcloud/apps/mail/lib/Service/MailTransmission.php","line":175,"function":"send","class":"Horde_Mime_Mail","type":"->","args":[{"send8bit":false,"sep":"\r\n","__class__":"Horde_Mail_Transport_Smtphorde"},false,false]},{"file":"/var/www/nextcloud/apps/mail/lib/Controller/AccountsController.php","line":332,"function":"sendMessage","class":"OCA\\Mail\\Service\\MailTransmission","type":"->","args":["NCadmin",{"__class__":"OCA\\Mail\\Model\\NewMessageData"},null,null,3095]},{"file":"/var/www/nextcloud/lib/private/AppFramework/Http/Dispatcher.php","line":170,"function":"send","class":"OCA\\Mail\\Controller\\AccountsController","type":"->","args":[1,"Test","Test","Test(Group)","","",false,3095,null,null,[],null]},{"file":"/var/www/nextcloud/lib/private/AppFramework/Http/Dispatcher.php","line":99,"function":"executeController","class":"OC\\AppFramework\\Http\\Dispatcher","type":"->","args":[{"__class__":"OCA\\Mail\\Controller\\AccountsController"},"send"]},{"file":"/var/www/nextcloud/lib/private/AppFramework/App.php","line":126,"function":"dispatch","class":"OC\\AppFramework\\Http\\Dispatcher","type":"->","args":[{"__class__":"OCA\\Mail\\Controller\\AccountsController"},"send"]},{"file":"/var/www/nextcloud/lib/private/AppFramework/Routing/RouteActionHandler.php","line":47,"function":"main","class":"OC\\AppFramework\\App","type":"::","args":["OCA\\Mail\\Controller\\AccountsController","send",{"__class__":"OC\\AppFramework\\DependencyInjection\\DIContainer"},{"accountId":"1","_route":"mail.accounts.send"}]},{"function":"__invoke","class":"OC\\AppFramework\\Routing\\RouteActionHandler","type":"->","args":[{"accountId":"1","_route":"mail.accounts.send"}]},{"file":"/var/www/nextcloud/lib/private/Route/Router.php","line":297,"function":"call_user_func","args":[{"__class__":"OC\\AppFramework\\Routing\\RouteActionHandler"},{"accountId":"1","_route":"mail.accounts.send"}]},{"file":"/var/www/nextcloud/lib/base.php","line":997,"function":"match","class":"OC\\Route\\Router","type":"->","args":["/apps/mail/api/accounts/1/send"]},{"file":"/var/www/nextcloud/index.php","line":42,"function":"handleRequest","class":"OC","type":"::","args":[]}],"File":"/var/www/nextcloud/apps/mail/vendor/pear-pear.horde.org/Horde_Mail/Horde/Mail/Transport/Smtphorde.php","Line":145,"Previous":{"Exception":"Horde_Smtp_Exception_Recipients","Message":"Bad recipient address syntax","Code":205,"Trace":[{"file":"/var/www/nextcloud/apps/mail/vendor/pear-pear.horde.org/Horde_Smtp/Horde/Smtp.php","line":650,"function":"_getResponse","class":"Horde_Smtp","type":"->","args":[[250,251],{"error":null,"exception":"Horde_Smtp_Exception_Recipients"}]},{"file":"/var/www/nextcloud/apps/mail/vendor/pear-pear.horde.org/Horde_Mail/Horde/Mail/Transport/Smtphorde.php","line":143,"function":"send","class":"Horde_Smtp","type":"->","args":[{"comment":[],"mailbox":"intra","__class__":"Horde_Mail_Rfc822_Address"},{"__class__":"Horde_Mail_Rfc822_List"},null]},{"file":"/var/www/nextcloud/apps/mail/vendor/pear-pear.horde.org/Horde_Mime/Horde/Mime/Part.php","line":1620,"function":"send","class":"Horde_Mail_Transport_Smtphorde","type":"->","args":["\"Test(Group)\"",{"From":"intra....se","To":"\"Test(Group)\"","Cc":"","Subject":"Test","Message-ID":"<20200221165604.Horde.n5-59HMZlySBFBZYl81a3Zt@korskyrkan-intra.se>","User-Agent":"Horde Application Framework 5","Date":"Fri, 21 Feb 2020 16:56:04 +0000","Content-Type":"text/plain; charset=utf-8","MIME-Version":"1.0"},null]},{"file":"/var/www/nextcloud/apps/mail/vendor/pear-pear.horde.org/Horde_Mime/Horde/Mime/Mail.php","line":479,"function":"send","class":"Horde_Mime_Part","type":"->","args":["\"Test(Group)\"",{"__class__":"Horde_Mime_Headers"},{"send8bit":false,"sep":"\r\n","__class__":"Horde_Mail_Transport_Smtphorde"}]},{"file":"/var/www/nextcloud/apps/mail/lib/Service/MailTransmission.php","line":175,"function":"send","class":"Horde_Mime_Mail","type":"->","args":[{"send8bit":false,"sep":"\r\n","__class__":"Horde_Mail_Transport_Smtphorde"},false,false]},{"file":"/var/www/nextcloud/apps/mail/lib/Controller/AccountsController.php","line":332,"function":"sendMessage","class":"OCA\\Mail\\Service\\MailTransmission","type":"->","args":["NCadmin",{"__class__":"OCA\\Mail\\Model\\NewMessageData"},null,null,3095]},{"file":"/var/www/nextcloud/lib/private/AppFramework/Http/Dispatcher.php","line":170,"function":"send","class":"OCA\\Mail\\Controller\\AccountsController","type":"->","args":[1,"Test","Test","Test(Group)","","",false,3095,null,null,[],null]},{"file":"/var/www/nextcloud/lib/private/AppFramework/Http/Dispatcher.php","line":99,"function":"executeController","class":"OC\\AppFramework\\Http\\Dispatcher","type":"->","args":[{"__class__":"OCA\\Mail\\Controller\\AccountsController"},"send"]},{"file":"/var/www/nextcloud/lib/private/AppFramework/App.php","line":126,"function":"dispatch","class":"OC\\AppFramework\\Http\\Dispatcher","type":"->","args":[{"__class__":"OCA\\Mail\\Controller\\AccountsController"},"send"]},{"file":"/var/www/nextcloud/lib/private/AppFramework/Routing/RouteActionHandler.php","line":47,"function":"main","class":"OC\\AppFramework\\App","type":"::","args":["OCA\\Mail\\Controller\\AccountsController","send",{"__class__":"OC\\AppFramework\\DependencyInjection\\DIContainer"},{"accountId":"1","_route":"mail.accounts.send"}]},{"function":"__invoke","class":"OC\\AppFramework\\Routing\\RouteActionHandler","type":"->","args":[{"accountId":"1","_route":"mail.accounts.send"}]},{"file":"/var/www/nextcloud/lib/private/Route/Router.php","line":297,"function":"call_user_func","args":[{"__class__":"OC\\AppFramework\\Routing\\RouteActionHandler"},{"accountId":"1","_route":"mail.accounts.send"}]},{"file":"/var/www/nextcloud/lib/base.php","line":997,"function":"match","class":"OC\\Route\\Router","type":"->","args":["/apps/mail/api/accounts/1/send"]},{"file":"/var/www/nextcloud/index.php","line":42,"function":"handleRequest","class":"OC","type":"::","args":[]}],"File":"/var/www/nextcloud/apps/mail/vendor/pear-pear.horde.org/Horde_Smtp/Horde/Smtp.php","Line":1058}}},"CustomMessage":"--"},"userAgent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/80.0.3987.106 Safari/537.36","version":"17.0.3.1","id":"5e500c0bc7ff4"}

**Comment by doc75** [comment]
This is a regression I saw on my side when migrating from 16.0.8 to 17.0.4.
It was working fine with NC16 and right after the upgrade it is not working anymore (I am sure as I am using a group to send mail just before upgrade starts and right after upgrade is done).

**Comment by ChristophWurst** [comment]
> Probably a regression between v0.17 (NC16 compatible) and current v1.1.3.

That or a change in logic for the code that provides the suggestions. Someone has to investigate. Are you familiar with xdebug?

**Comment by doc75** [comment]
@ChristophWurst I have never used xdebug, but I am ready to try.
I installed it in the php-fpm container and added the line mentionned at the end of `pecl install xdebug` in a .conf file located in /usr/local/etc/php-fpm.d/` directory.

But after I do not know where to find the information from XDebug.
I'll try to learn how to use it to see if I can help on debugging this.

**Comment by rollanders** [comment]
Autocomplete works as expected in Talk and when sharing a Calendar but is not consistent when sharing a folder or a file.

**Comment by ChristophWurst** [comment]
The idea is to step through the code to inspect the values. So you'll need an IDE like VSCode, Netbeans or PhpStorm. Then configure the xdebug to send debugging requests to the IDEs port.

**Comment by rollanders** [comment]
The autocomplete seems to works differently in Talk and för sharing things. Do you use different algorithms?

**Comment by ChristophWurst** [comment]
Yes, it's different because we also use contacts data and similar.

**Comment by doc75** [comment]
@ChristophWurst I finally succeeded in setting up Xdebug with Codium.

I can notice that the group integration seems to query only the Contact groups. It seems that no code is looking for the groups created by the admin in the page containing all the NC users.

I have no clue on how we can search for groups created by the admin in the user panel. Any idea on where I can find such information ?

I might be wrong as this is my first debug ever in PHP and  XDebug, sorry if this is the case.

**Comment by ChristophWurst** [comment]
Nextcloud groups should be resovled by `\OCA\Mail\Service\Group\NextcloudGroupService`. Was that class ever contacted?

**Comment by ChristophWurst** [comment]
Found it!

**Comment by ChristophWurst** [comment]
https://github.com/nextcloud/mail/pull/2972

**Comment by doc75** [comment]
I just tested this on NC18 + Mail 1.4.1 and it is working fine again. I am not sure on which version it has been solved. Good news.
