### ISSUE TITLE
Some images display are broken

### ISSUE THREAD

**Issue by el3ctrician** [nextcloud/mail#2671]
### Expected behavior
Create a new email from Outlook inserting some images in the text and send it to another address that show it using nextcloud mail app. When you open it you should see the images displayed as formatted by the original mail

### Actual behavior
Image is linked to broken HTML link but found as attachment as shown in the image. Iguess that it should point to where the images are stored in nextcloud

![mail_nextcloud](https://user-images.githubusercontent.com/17578910/75020517-34253200-5493-11ea-9621-0674a8e4c908.png)

### Mail app

**Mail app version:** 1.1.2

**Mailserver or service:** Custom

### Server configuration

**Operating system**: Ubuntu 16.04 & docker 

**Nextcloud Version:** 17.0.1

#### Client configuration
**Browser:** Google Chrome Version 79.0.3945.130 (Official Build) (64-bit)

**Operating system:** Windows 10 64-bit

**Comment by ChristophWurst** [comment]
Anything in the browser console? Like js error or failing HTTP requests for the images? Anything in nextcloud.log that could be related?

**Comment by el3ctrician** [comment]
some more infos are the following : 

1. **img attribute:** 
```<img width="795" height="396" style="width:8.2812in;height:4.125in;" src="https://MY_NEXTCLOUD_ADDRESS/index.php/apps/mail/api/accounts/7/folders/U1U1Q1QxZz0=/messages/51749654/attachment/3" alt="cid:image002.png@01D5E66A.CE690A90"> ```
2. **HTTP Request Headers:** 
```
GET /index.php/apps/mail/api/accounts/7/folders/U1U1Q1QxZz0=/messages/51749654/attachment/3 HTTP/1.1
Host: MY_NEXTCLOUD_ADDRESS
Connection: keep-alive
User-Agent: Mozilla/5.0 (Linux; Android 6.0; Nexus 5 Build/MRA58N) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/80.0.3987.116 Mobile Safari/537.36
Sec-Fetch-Dest: image
Accept: image/webp,image/apng,image/*,*/*;q=0.8
Sec-Fetch-Site: same-origin
Sec-Fetch-Mode: no-cors
Accept-Encoding: gzip, deflate, br
Accept-Language: en-US,en;q=0.9
Cookie: __Host-nc_sameSiteCookielax=true; __Host-nc_sameSiteCookiestrict=true; nc_username=MY_USER_NAME; oc_sessionPassphrase=Z2Hap%2BFWFfq0AMvqPyH7je66PnzAmm68NDAOyakv%2F9dMgA3vJBmE2CxBA4u6M8J2IZcpvPnsC3%2F%2Fr8vHu1UXBkxokgkUf2gIDJSCc887CXmfsj6rddm4FYKBkHgRNYxu; oc7eek48spk8=512eca9b39e2a8c28680823ecfb0f9f9; nc_token=QHGLWZVfJ3DzWmMn%2F5gQMDumO8XTsJYU; nc_session_id=512eca9b39e2a8c28680823ecfb0f9f9
```
3. **HTTP Response Headers:** 
```
HTTP/1.1 500 Internal Server Error
Date: Fri, 21 Feb 2020 11:20:45 GMT
Server: Apache/2.4.38 (Debian)
Strict-Transport-Security: max-age=15552000; includeSubDomains
X-Powered-By: PHP/7.3.11
Expires: Thu, 19 Nov 1981 08:52:00 GMT
Cache-Control: no-cache, no-store, must-revalidate
Pragma: no-cache
Content-Security-Policy: default-src 'none';base-uri 'none';manifest-src 'self'
Referrer-Policy: no-referrer
X-Content-Type-Options: nosniff
X-Download-Options: noopen
X-Frame-Options: SAMEORIGIN
X-Permitted-Cross-Domain-Policies: none
X-Robots-Tag: none
X-XSS-Protection: 1; mode=block
x-mail-error: true
Feature-Policy: autoplay 'none';camera 'none';fullscreen 'none';geolocation 'none';microphone 'none';payment 'none'
Content-Length: 2
Content-Type: application/json; charset=utf-8
Connection: close
```
4. **HTTP Response:**
```
data:application/json,[]
```
5. **JS Console:** 
```
html:26 GET https://MY_NEXTCLOUD_ADDRESS/index.php/apps/mail/api/accounts/7/folders/U1U1Q1QxZz0=/messages/51749654/attachment/2 500 (Internal Server Error)
The resource https://MY_NEXTCLOUD_ADDRESS/custom_apps/mail/js/mail.9.b6f152a880ad62a9ac8a.js was preloaded using link preload but not used within a few seconds from the window's load event. Please make sure it has an appropriate `as` value and it is preloaded intentionally.
globals.js:26 The escapeHTML library is deprecated! It will be removed in nextcloud 19.
```
6. **Correct image URL (seen as thumbnail):***
```
https://MY_NEXTCLOUD_ADDRESS/index.php/apps/mail/api/accounts/7/folders/SU5CT1g=/messages/51749654/attachment/3
```


If i go to the element inspection in chrome and substitute the broken image link with the extracted from the attachment everything works fine. Even the relative link without the MY_NEXTCLOUD_ADDRESS part works fine ...

**Comment by el3ctrician** [comment]
Hello, are the information enough to diagnostic the problem or you still need me to provide something else ?

**Comment by ChristophWurst** [comment]
This is plenty of information, thanks a lot :)
