### ISSUE TITLE
Cannot activate app on NC 11 with PHP 7.1

### ISSUE THREAD

**Issue by DavidMStraub** [nextcloud/mail#268]
### Steps to reproduce
1. Open the App Store and try to activate Mail app.

### Expected behaviour
Button activate should not be greyed out

### Actual behaviour
Button activate is greyed out and error message: "PHP with a version lower than 7.0 is required."

![screenshot_20170102_135458](https://cloud.githubusercontent.com/assets/10965193/21589651/51fb84d0-d0f4-11e6-9d2d-ee283c8863a6.png)

### Mail app

N/A

### Server configuration
**Operating system**: shared hosting

**Web server:** shared hosting

**Database:** SQLite

**PHP version:** 7.1

**Version:** 11.0.0

**Updated from an older version or fresh install:** fresh

Sorry for not filling in the rest of the template but I doubt it's relevant.

**Comment by ChristophWurst** [comment]
Hi,

this has been fixed in https://github.com/nextcloud/mail/pull/248. The next release will be compatible with php 7.1.

**Comment by yopsolo79** [comment]
Hi,

Any idea when the next release will be available for the users ?
Is there another way to get this nice app to work with php 7.1 in the meantime ?

Regards

**Comment by ChristophWurst** [comment]
> Any idea when the next release will be available for the users ?

It’s done, when it’s done 😉 

You can try a nightly from either here https://apps.nextcloud.com/apps/mail or the link in the readme. The latter are generated automatically and thus might be less stable than the ones I upload to the app store manually.
