### ISSUE TITLE
HTML messages don’t extend to full height

### ISSUE THREAD

**Issue by szaimen** [nextcloud/mail#2694]
### Feature Request

Currently there is much available space on the right side where more of long messages could get shown. But instead of using the space, there is a scroll bar.
![image](https://user-images.githubusercontent.com/42591237/75349633-72608e00-58a5-11ea-95b3-a3527f73b28f.png)

BTW: on mobile, it is much worse and in this state nearly unusable:
![image](https://user-images.githubusercontent.com/42591237/75349702-96bc6a80-58a5-11ea-8aac-5942133d948b.png)

And another BTW: the white background of the back arrow here on mobile cuts something off the mail title which doesn't look really pleasing to the eyes.

I am currently on NC 18.0.1 and have the mail app 1.1.2 installed.

#### Summary

Please use all available space on the right side for a message preview.

**Comment by ChristophWurst** [comment]
This is a duplicate. @jancborchardt ?

**Comment by szaimen** [comment]
If that will get fixed by https://github.com/nextcloud/mail/pull/2222 I can close that issue.

**Comment by szaimen** [comment]
it seems like https://github.com/nextcloud/mail/pull/2693 will also close the issue with the arrow.

**Comment by jancborchardt** [comment]
We can keep this open as https://github.com/nextcloud/mail/issues/658 is not really the proper issue to describe this problem.

In any case, #2222 would fix this – @szaimen please review and check if that fixes it for you, or what is missing. :)

**Comment by szaimen** [comment]
@jancborchardt Hm, I guess I am not able to review/test this since there is no test build. And I am not able to understand this in theory. :/

**Comment by StCyr** [comment]
I've just tested #2222 and got the following error:

Mar 18 08:34:26 vps612142 Nextcloud[7092]: {"reqId":"6L3GzbNSzJ0H9VnVNENQ","level":0,"time":"2020-03-18T07:34:26+00:00","remoteAddr":"8.8.8.8","user":"cyrille","app":"no app in context","method":"GET","url":"/index.php/apps/files/","message":"Deprecated event type for OCA\\Files::loadAdditionalScripts: Symfony\\Component\\EventDispatcher\\GenericEvent","userAgent":"Mozilla/5.0 (Macintosh; Intel Mac OS X 10.13; rv:74.0) Gecko/20100101 Firefox/74.0","version":"18.0.1.3"}

**Comment by violoncelloCH** [comment]
@StCyr have you tried a `make dev-setup`? I've got a similar error after rebasing #2222 which went away after reinstalling the composer deps...

**Comment by Bajotaz** [comment]
Any news?
My mail opens good on width but only about 3cm in height.
