### ISSUE TITLE
When editing an account, it creates a new instance of the account instead of changing the current account

### ISSUE THREAD

**Issue by szaimen** [nextcloud/mail#2695]
### Expected behavior
it should edit the current account
(e.g. I try to edit the default rich text settings from that account)

### Actual behavior
it creates a second account (that is visible after a reload of the website)

### Mail app

**Mail app version:** (see apps admin page, e.g. 0.5.3)
1.1.2
**Mailserver or service:** (e.g. Outlook, Yahoo, Gmail, Exchange,...)
isn't important

### Server configuration

**Operating system**: (e.g. Debian 8)
ubuntu 18.0.1
**Web server:** (e.g. Apache, Nginx,...)
apache2
**Database:** (e.g. MariaDB, SQLite or PostgreSQL)
PGSQL
**PHP version:** (e.g. 7.0)
7.2
**Nextcloud Version:** (see admin page, e.g. 13.0.2)
18.0.1
#### Client configuration
**Browser:** (e.g. Firefox 48)
Chromium 80 based browser
**Operating system:** (e.g. Arch Linux)
Windows 10

**Comment by ChristophWurst** [comment]
We use the same routine as for a new account. But as we set an ID, the DB abstraction should update the existing account. Smells like a bug.

**Comment by szaimen** [comment]
Actually this happens only if I enter the password again and click on "save changes".
Because if I just e.g. change the settings for the default editing mode, they doesn't get saved instantly.

**Comment by szaimen** [comment]
I have tested it a bit further and found out that the changes to the default editing mode apparenly get saved automatically but are only visible after you reload the page (if you edit this imap account setting -> navigate away and e.g. edit an email -> view the account settings again: now it seems like your change wasn't saved, but if you hard-reload the page, it show that the change was acutallly saved.

On the other hand, the bug that I first reported is still occuring.
so e.g. edit the imap account settings -> change the password -> save the changes -> reload the page: you can see now, that the mail app created a new account instead of saving the changes to the first account.

**Comment by ChristophWurst** [comment]
> I have tested it a bit further and found out that the changes to the default editing mode apparenly get saved automatically but are only visible after you reload the page (if you edit this imap account setting -> navigate away and e.g. edit an email -> view the account settings again: now it seems like your change wasn't saved, but if you hard-reload the page, it show that the change was acutallly saved.

That was fixed recently :)
