### ISSUE TITLE
Please provide an option to save/close/delete the current draft

### ISSUE THREAD

**Issue by szaimen** [nextcloud/mail#2696]
### Feature Request

Hi, would be really nice if you could add the option to manually save/close and most important delete the current preview. 

#### Summary

it could get added to the list here:
![image](https://user-images.githubusercontent.com/42591237/75350658-30384c00-58a7-11ea-9991-9615f461b9b7.png)

**Comment by ChristophWurst** [comment]
Could you add that info to https://github.com/nextcloud/mail/issues/2492. I think that other ticket goes into the same direction.

**Comment by szaimen** [comment]
I've done that 👍
