### ISSUE TITLE
Custom domain address hosted on mailfence.com doesn't load e-mails with images or attachments.

### ISSUE THREAD

**Issue by m4nnerheim** [nextcloud/mail#2705]
### Expected behavior
My gmail and my custom domain outlook works as it should. Images and attachments load. 

### Actual behavior
However, I also have a custom domain e-mail hosted on mailfence.com which didn't auto-configure after following [this guide](https://kb.mailfence.com/kb/auto-configuration-custom-domain/) (that might be a separate issue). This address doesn't load e-mails with images or attachments. I just get an endless loading loop. On top of that when I hop around different inboxes and return to this address' inbox the messages duplicate themselves. If I select one of the duplicated e-mails, it selects every single duplicate of that mail. Going to ex. `files` and back to `mail` resets the view of this particular inbox to a normal state without duplicates. I'm seeing a lot of `KItinerary binary adapter is not available, can't extract information` messages in settings>admin>logging, perhaps it has something to do with it?

### Mail app

**Mail app version:** 1.1.2

**Mailserver or service:** mailfence.com

### Server configuration

**Operating system**: docker 19.03.6 on Ubuntu server 18.04

**Web server:** Nginx

**Database:** mysql

**PHP version:** 7.3.14

**Nextcloud Version:** 18.0.1

#### Client configuration
**Browser:** Firefox 73.0.1

**Operating system:** Manjaro Linux

**Comment by ChristophWurst** [comment]
Could you try v1.3.3?
