### ISSUE TITLE
UX improvement: Show Inbox after clicking on account name

### ISSUE THREAD

**Issue by nekromoff** [nextcloud/mail#2731]
### Feature Request

UX improvement: Show Inbox after clicking on account name

#### Summary

Currently when user clicks on an account name, settings for that account are displayed. Inbox display is definitely more useful and likely more needed than some settings that could be available via click on three dots / settings anyway.

**Comment by ChristophWurst** [comment]
This should be straight forward to fix. Would you be interested in learning more about contributing?

**Comment by nekromoff** [comment]
Sure

**Comment by ChristophWurst** [comment]
Awesome!

We have https://nextcloud.com/developer/ as an overview to get started. You can read/work through the [app tutorial](https://docs.nextcloud.com/server/latest/developer_manual//app/tutorial.html) to get a better understanding of how our *apps* work.

This app's development setup is documented [here](https://github.com/nextcloud/mail/#development-setup).

The front-end is written in Vue.js and you can find the source file for the account [here](https://github.com/nextcloud/mail/blob/master/src/components/NavigationAccount.vue).

**Comment by nekromoff** [comment]
Sorry, I don't have much experience with Vue.js. I also think the file
linked for the account is actually just for the navigation (hamburger)
menu, if I read it right.

**Comment by ChristophWurst** [comment]
No, that is the account entry in the navigation ;)

Where we set the route https://github.com/nextcloud/mail/blob/f90224a76387f886f6ece6f8dde24a548610ff42/src/components/NavigationAccount.vue#L30
The current route https://github.com/nextcloud/mail/blob/f90224a76387f886f6ece6f8dde24a548610ff42/src/components/NavigationAccount.vue#L99-L106

Vue is really simple to get into. Just browse through https://vuejs.org/ a bit :v:
