### ISSUE TITLE
Create a convenient way to reorganize the mail folders

### ISSUE THREAD

**Issue by LeoBoudet** [nextcloud/mail#2734]
- By clicking and dragging for example, ;
- or an option such as go up/go down option in a contextual menu ;
- by adding an option to create/delete some folders (with a possibility to cancel if a mistake is made) ;
- by offering the possibilty to file a folder in another folder,
- etc.

It is not something that seems like an emergency, I'd just be pleased to see Nextcloud mail become a complete mail solution for my company and my customers, due to the nice integration it has in the Nextcloud environment.

Cheers!

**Comment by ChristophWurst** [comment]
These are existing feature request. Tickets like https://github.com/nextcloud/mail/issues/2441 track these.
