### ISSUE TITLE
Deleted Message is not moved to trash folder (IMAP)

### ISSUE THREAD

**Issue by kenthinson** [nextcloud/mail#274]
### Steps to reproduce
1. Setup mail inside nextcloud
2. delete mail
3. can't find deleted mail in trash

### Expected behaviour
Clicking the Trash can icon on a email should move it on my imap server to the trash folder

### Actual behaviour
the email is deleted can't find it anywhere

### Mail app

**Mail app version:** (see apps admin page)
0.6.2

**Mailserver or service:** (e.g. Outlook, Yahoo, Gmail, Exchange,...)
dovecot

**Transport security - IMAP:** (None, SSL, TLS, STARTTLS) 
TLS/SSL

**Transport security - SMTP:** (None, SSL, TLS, STARTTLS)
TLS/SSL
**Number of accounts:**
All
**Mail app version build date:** (only if you are using a Nightly Build)

### Server configuration
**Operating system**:
Ubuntu
**Web server:**
Apache
**Database:**
MySql
**PHP version:**

**Version:** (see admin page)
11.0 Stable
**Updated from an older version or fresh install:**
Fresh Install
**List of activated apps:**
Default Selection + Mail Calendar and Contacts
```
If you have access to your command line run e.g.:
sudo -u www-data php occ app:list
from within your server installation folder
```

**The content of config/config.php:**

<details>
```
If you have access to your command line run e.g.:
sudo -u www-data php occ config:list system
from within your server installation folder

or 

Insert your config.php content here
(Without the database password, passwordsalt and secret)
```
</details>

#### Client configuration
**Browser:**

**Operating system:**

##### Web server error log
```
Insert your webserver log here
```

##### Server log (data/nextcloud.log)
<details>
```
Insert your server log here
```
</details>

##### Horde IMAP log (data/horde_imap.log)
<details>
```
Insert your horde IMAP log here, see https://github.com/nextcloud/mail#debug-mode
```
</details>

##### Horde SMTP log (data/horde_smtp.log)
<details>
```
Insert your horde SMTP log here, see https://github.com/nextcloud/mail#debug-mode
```
</details>

##### Browser log
<details>
```
Insert your browser log here, this could for example include:

a) The javascript console log
b) The network log 
c) ...
```
</details>

**Comment by ChristophWurst** [comment]
Hi,
please fill out the *full* issue template. I'm curious which commands are sent to the IMAP server.

**Comment by ChristophWurst** [comment]
ping

**Comment by kenthinson** [comment]
Hey sorry I've been really busy. I noticed that my other clients were having the same issue(apple mail). I restarted the map server and the issue is resolved. Not a nextcloud issue. Thanks for the help!
