### ISSUE TITLE
Show mail header in threads for every mail

### ISSUE THREAD

**Issue by Amerlander** [nextcloud/mail#2748]
### Feature Request

In threads with several mails there is only one header on top. If the mails in this thread are having different mail headers they are not shown, so its not possible to see whether they all have the same recipients or if they are changing in some mails in this thread.
Its also impossible to forward an older email. Only the newest email can be forwarded.
If there is an email with an attachment the attachments are shown, but you cannot forward this email to others when there is a newer email in this thread.

#### Summary

Provide information about the recipients above every email in threads. Also show forward & reply buttons for every mail.

**Comment by ChristophWurst** [comment]
Hm. We don't have message threads right now. Are you sure you're using this app?

**Comment by Amerlander** [comment]
Ok, I see.

Then the behavior is different, but still confusing, so that I thought there were threads.

1) I receive an email with attachment.
2) I get a reply to that email from another person without an attachment. The attachments from the first email are shown in this email too. That lead me to the idea that there are threads.
I have now two emails in my inbox, both shown with attachments but only one of them was actually sent with attachment.
3) But forwarding doesn't keep the attachment in both emails. So this might be a separate issue, but I wonder how I can forward attachments at all.

Showing attachments of all previous emails in an conversation might be confusing when a long conversation has lots of different emails with attachments and it might get confusing who actually added an attachment and when.

This one was by B. with attachment:
![image](https://user-images.githubusercontent.com/3764089/77250306-5901f600-6c47-11ea-91b2-920baaba8b12.png)


And this one is a reply without any attachment, but it shows the attachment of the first email (like I would only expect in a thread view). Without thinking about I would consider J. has sent the same files again and will wonder whats the difference to the files B. sent:
![image](https://user-images.githubusercontent.com/3764089/77250301-556e6f00-6c47-11ea-999f-a778e2e2d0ce.png)

**Comment by ChristophWurst** [comment]
Replies that show with an attachment icon – were those sent with this app or another? Does the message maybe have the original one attached as embedded message?

**Comment by Amerlander** [comment]
In the case above the email has been sent out of the app and the answer was sent by a windows program called mailbird.
Other programs doesn't show an attachment in the replied email and there is no image placed inline as well as no pdf.

**Comment by ChristophWurst** [comment]
> Does the message maybe have the original one attached as embedded message?

Please inspect the headers and see if it is an RFC822 message.
