### ISSUE TITLE
Send throught servers mail account

### ISSUE THREAD

**Issue by maaeps** [nextcloud/mail#2750]
### Feature Request

It would be create if selected user (such as admins) could send mails through the server smtp settings.

#### Summary

Inside the Email settings of the server, users should get permission, to select this noreply mail to send there mail.

In addition it would be create if selected users would be able to select the receiver based on the NextCloud users, too. (Just like people from their address book.

**Comment by ChristophWurst** [comment]
> In addition it would be create if selected users would be able to select the receiver based on the NextCloud users, too. (Just like people from their address book.

Needs more info. But please keep separate feature requests in separate tickets.

**Comment by ChristophWurst** [comment]
> It would be create if selected user (such as admins) could send mails through the server smtp settings.

This is quite an edge case. I don't think we'd have anything like that in the foreseeable future. @nextcloud/mail for triage.

**Comment by jancborchardt** [comment]
Agree with @ChristophWurst that this is not really something we are likely to implement.

> In addition it would be create if selected users would be able to select the receiver based on the NextCloud users, too. (Just like people from their address book.

This is a separate thing, please open a new issue for that – thank you! :)

**Comment by maaeps** [comment]
By combining the noreply SMTP settings and other IMAP settings, users can send mails through the servers noreply mail address. Niche solution for niche problem :-)
