### ISSUE TITLE
Nextcloud Accountgroups not anymore available in "TO" Field

### ISSUE THREAD

**Issue by tim-krehan** [nextcloud/mail#2760]
I Upgraded Yesterday from Nextloud 16.0.4 to the most recent "produktive" Nextcloudbuild (18.0.2).

Since this Version I can't send Mails to Nextcloudgroups anymore. Can anyone help me, where I start debugging this?

**Comment by doc75** [comment]
Seems similar to #2668

**Comment by GretaD** [comment]
Hello @BlueCaos, can you please tell us a bit more about the error you're having? You cannot send the email at all? Is any error showing after you click send?

**Comment by BlueCaos** [comment]
Hello @GretaD !
The problem isn't, that I cannot send mails. This works perfectly fine.
But prior to the update, while typing in the "TO" field, I got next to emails, that matched the already typed, also Nextcloud-Groups as suggestions.

So I have a Nextcloudgroup named "everyone", and I type that in said field, the App would send a Mail to everyone in that group.

Now that behavior isn't happening anymore.

**Comment by BlueCaos** [comment]
@GretaD also there isn't any error related to that in the Nextcloudlog, sadly. Is there Anywhere where I con look further into that?

**Comment by ChristophWurst** [comment]
> But prior to the update, while typing in the "TO" field, I got next to emails, that matched the already typed, also Nextcloud-Groups as suggestions.

Indeed a duplicate https://github.com/nextcloud/mail/issues/2760#issuecomment-599267484

**Comment by GretaD** [comment]
hey @BlueCaos ca you please send us here a screenshot of your sharing settings?

**Comment by BlueCaos** [comment]
![image](https://user-images.githubusercontent.com/39102356/77422056-27b33280-6dcd-11ea-8d61-7b09762d3815.png)
@GretaD

**Comment by doc75** [comment]
I just tested this on NC18 + Mail 1.4.1 and it is working fine again. I am not sure on which version it has been solved. Good news.
