### ISSUE TITLE
Special folders not as subfolders of inbox

### ISSUE THREAD

**Issue by OhSoGood** [nextcloud/mail#2761]
Hi,

A new user of nextcloud, I tested your excellent mail app - thanks a lot for it. Yet I found out that special folders (spam, draft, etc.) appears as subfolders of inbox. 

This happens whatever the real organisations of folders on the imap server: 
1. They were once as subfolders on the imap server and were appearing as such in nextcloud, which shouldn't: in such case, nextcloud's mail should display them on same level as inbox like do many (all?) email clients.
2. I then removed the account in nextcloud, changed on the imap server the subfolders as folders at the same level as inbox, recreated the account on nextcloud, and the special folders still appears as subfolders of inbox. Again, that shouldn't be.

From my little IMAP knowledge, I guess it is more or less linked with issue https://github.com/nextcloud/mail/issues/2725

Is it an issue with my nextcloud, with my email provider (OVH), or with the mail app ?
Thank you!

**Comment by ChristophWurst** [comment]
Could you give us a list of all mailbox IDs. Are they all prefixed? What is the prefix?

**Comment by OhSoGood** [comment]
For a brand new account, the imap folders were:
INBOX, INBOX/Drafts,  INBOX/Sent,  INBOX/Junk, INBOX/Trash

As described in my initial post, I removed my nextcloud mail config and
removed these folders, and then created that structures:
INBOX, Drafts,  Sent,  Junk, Trash (all top levels so)

In both cases, once the account is added to Nextcloud, I see them (see
attached picture) as
- Inbox (actually translated)
       - INBOX."Sent" (actually translated)
       - INBOX."Trash" (actually translated)
       - INBOX."Drafts" (actually translated)
       - INBOX."Junk" (actually translated)



Le 23/04/2020 à 08:47, Christoph Wurst a écrit :

**Comment by ChristophWurst** [comment]
> As described in my initial post, I removed my nextcloud mail config and removed these folders, and then created that structures: INBOX, Drafts,  Sent,  Junk, Trash (all top levels so)

But the app won't add the INBOX. prefix. I think your IMAP server adds them automatically.

**Comment by OhSoGood** [comment]
Yes, I think so it's the Imap server, but I can't do anything at that
level (it's my webhost's server).
Maybe Nexcloud mail app could do like Thunderbird or Outlook, offering
an optional parameter to specify the prefix used byt the Imap server?
If I'm not wrong, the imap server is supposed (or has the possibility)
to expose this value through the Imap specifications, but that's for
sure not the case of a number of imap servers since both Outlook and
Thunderbird offer the possibility to fix it manually...

Is that possible to do the same with nexcloud/mail ?

Le 23/04/2020 à 11:11, Christoph Wurst a écrit :

**Comment by beccon4** [comment]
It would a lot help to be able to manage the Sent/Drafts/Trash Folders and individually assign them to existing IMAP Folders in the mailbox. That would help a lot in the case of multiple mail clients connecting to the same mailbox and solve the problem of those folders nested in INBOX.

**Comment by benjamindahl** [comment]
similar issue here

![Bildschirmfoto 2020-09-30 um 12 01 02](https://user-images.githubusercontent.com/2698024/94678759-4ca9d480-031f-11eb-9625-ed1d0cd1280c.png)
![Bildschirmfoto 2020-09-30 um 12 08 52](https://user-images.githubusercontent.com/2698024/94678765-4fa4c500-031f-11eb-939e-ca4c51333685.png)

**Comment by ChristophWurst** [comment]
Please be patient. Mail v1.5 will be release soon and it's very likely this issue is fixed now :v:

**Comment by ChristophWurst** [comment]
Fixed via https://github.com/nextcloud/mail/pull/3147

See also https://github.com/nextcloud/mail/issues/3272 for a feature request to change the personal namespace manually.
