### ISSUE TITLE
mail provisioning email password

### ISSUE THREAD

**Issue by Fuseteam** [nextcloud/mail#2762]
### Question
if i use the mail app account provisioning what password is used to access the imap host? can we have the user input their own password?

**Comment by ChristophWurst** [comment]
it uses the login password

**Comment by Fuseteam** [comment]
ah cool, so they can't use separate passwords for their email and for their nextcloud account?

**Comment by ChristophWurst** [comment]
no, they can't right now. the concept behind provisioned mail accounts is that the nextcloud uses the same user back-end as the IMAP server, thus the password is typically the same.

users can add their own accounts. then they can pick a password.

**Comment by Fuseteam** [comment]
alright thanks

**Comment by ChristophWurst** [comment]
I have the feeling there was an existing ticket for this. maybe it was asked on https://help.nextcloud.com/. maybe you're more lucky with search

**Comment by Fuseteam** [comment]
i don't like relying on luck tbh :x
