### ISSUE TITLE
Tip / topic about whole NC mail concept

### ISSUE THREAD

**Issue by rarapost** [nextcloud/mail#2763]
Hello guys

It is a good idea to create mail client integrated to NC, but (by my opinion) the way  how the team does it is questionable. There is a lot of useful (and more or less working) open source web mail client.  There is already Rainloop NC app existing. Rainloop is user friendly, even if its development slowed down and there is a lot of unfixed issues.  Also another option - Mailpile - has clean and well usable UI. 
Isn't it better to adopt one of them, participate on its development (and so enhance its community), than develop new one from scratch? Or at least clone it and  modify it according NC needs ?
NC mail app UI is a bit "spartan" to me and is is hard for daily usage. There is a lot of issues and unfinished things. It will need big development until it reaches maturity level, that today have both mentioned clients. 
O know a lot of work has been done on the app, but still ... isn't it worth to think about change of this concept ?
I am fan of NC, I support you and appreciate your work. This my post is not criticism, only and idea and my thinking

**Comment by ChristophWurst** [comment]
The simple answer is that we want to have something tightly integrated. Not just *some* mail client. Those already exist.

See https://github.com/nextcloud/mail/issues/2250. This was brought up before. And for the high-level goal see https://github.com/nextcloud/mail/issues/65 :)

Thanks for taking the time to send this message.

**Comment by rarapost** [comment]
Thank you for your respnse, I really welcome good mail client in NC, but it would have to be matured enough for daily usage. And, of course, tight integration with NC is crucial.

I understand the point you wrote. But still ... I cant get rid of impression that you're trying reinvent thing already exist (at least in case od UI). There are many open source mail solutions (for example already mentioned Carnet) that have UI similar to well-known UIs (Google, MS).  Google's approach (although maybe not the best possible) is proven, it works and lots of people are used to use it. MS Use similar layout. Google (and MS) have teams of UX experts ... so why invent any other things? 

As a (former) SW developer I know the most work is on the side of UI/UX (abd surrounding - input treatment, output formatting, layout, event reacting ... etc). If you develop everything from scratch, you need all these things develop once again. I gues better is use something already existing, either join to the community ot creaate clone of it and continue development this way. That's my point I wanted to share.

**Comment by ChristophWurst** [comment]
You can check out the existing integration of FLOSS webmail. They are subpar. It's very hard to integrate an existing but completely independent solution into ours. Also think about maintainability. Maybe we could take one of the php solution and adjust it design-wise and add features for the integration. But would we be able to update to the changes upstream? I doubt it. They are not designed as application components but standalone applications.
