### ISSUE TITLE
Register not formatting links well

### ISSUE THREAD

**Issue by JamJarChris** [nextcloud/mail#2764]
### Question

Links in Email messages appear badly formatted when using register

#### Summary

Hi there - hope someone can help. Issue that has been bugging me a week or so. Installed NC 18 on shared hosting, all dependencies met afaik. Receive an email, links show as OK, except when redirect is called. As an example https://next1.jamjarchris.com/index.php/apps/mail/redirect?src=https%3A%2F%2Farchive.org%2F when trying to access a link which should be www.archive.org.
Have looked everywhere logical to me - sorry to be a pain, and many TIA

**Comment by ChristophWurst** [comment]
what is "register"?

**Comment by JamJarChris** [comment]
Sorry, I meant redirect, not register (been a hell of a day here) .

**Comment by ChristophWurst** [comment]
> As an example https://next1.jamjarchris.com/index.php/apps/mail/redirect?src=https%3A%2F%2Farchive.org%2F when trying to access a link which should be [www.archive.org](http://www.archive.org).
> Have looked everywhere logical to me - sorry to be a pain, and many TIA

That looks fine. The original URL is just url encoded. See the decoded: https://duckduckgo.com/?q=url+decode+https%253A%252F%252Farchive.org%252F&ia=answer

**Comment by JamJarChris** [comment]
Thank you. Thought this would be the area to look at. At present I cannot click on these links in an email message - I get the following:
Internal Server Error
The server was unable to complete your request.

If this happens again, please send the technical details below to the server administrator.

More details can be found in the server log.

Technical details
Remote Address: 5.10.204.228
Request ID: Z4AQEtkbJSIEbTE9l8pifkxY

I would be very grateful if you could let me know where I have gone wrong.
Thank you

**Comment by ChristophWurst** [comment]
> More details can be found in the server log.

Please open a bug report using https://github.com/nextcloud/mail/issues/new?assignees=&labels=bug%2C+0.+to+triage&template=bug.md&title= and provide use with the relevant entries from nextcloud.log.

**Comment by JamJarChris** [comment]
Will do and thank you for your help.
FYI - the log shows:
Exception: Argument 1 passed to OCA\Mail\Controller\ProxyController::redirect() must be of the type string, null given, called in /home/jamjarch/next1.jamjarchris.com/lib/private/AppFramework/Http/Dispatcher.php on line 170
