### ISSUE TITLE
What is KItinerary for ?

### ISSUE THREAD

**Issue by doc75** [nextcloud/mail#2765]
### Question

I have found that since I mgrated from Nextcloud 16.0.8 to 17.0.4, I have now after each usage of Mail App (1.1.3) the following warning:
```
KItinerary binary adapter is not available, can't extract information
```
I have 2 questions:

1. What is Kitinerary for ? I have not found in the mail app what could be its usage (sorry for the dummy question)
2. Is there any reason for this message:
```
KItinerary binary adapter is not available, can't extract information
```
knowing that I can found in my installation:
```
vendor/christophwurst/kitinerary-bin/bin/kitinerary-extractor
```
with permission `744` (seems correct according to https://github.com/nextcloud/mail/issues/2489#issuecomment-575910677)

**Comment by ChristophWurst** [comment]
It's a tool to extract ticket, event and travel information from emails. Do you use a 64bit Linux? The binary can't be used otherwise.

Please note that this log entry should have a low log level, like warning or debug. Is that not the case?

**Comment by doc75** [comment]
@ChristophWurst thanks for taking the time to answer.

I am using the official docker image `fpm-alpine-production` and `uname -m` inside the container is returning `x86_64`

Could this be related to the fact that this is alpine ?
Does it need extra dependencies that might be missing ?

Yes, this is just a warning, but I was trying to check why I got it as it never appears before on NC16.

**Comment by ChristophWurst** [comment]
Here's the code that does the checks: https://github.com/ChristophWurst/kitinerary-bin/blob/eaafa040b404651cb4ab75a2d7a53c71b55d2395/src/BinaryAdapter.php#L67-L94

So, if you lower your log level to warning, you *should* see info about why it does not run.

Alpine could be the problem. You could try running the binary directly like `echo "" | ./apps/mail/vendor/christophwurst/kitinerary-bin/bin/kitinerary-extractor`. The static binary runs on almost all distros. But could be that we expect a shared lib that is not there on Alpine.

**Comment by doc75** [comment]
@ChristophWurst thanks for the advice.
Indeed, this is really really strange as I can find the binary:
```sh
$ ls -al ./custom_apps/mail/vendor/christophwurst/kitinerary-bin/bin/kitinerary-extractor
-rwxr--r--    1 www-data www-data  15697272 Mar 24 21:39 ./custom_apps/mail/vendor/christophwurst/kitinerary-bin/bin/kitinerary-extractor
```
but when I try to launch it I get this:
```sh
$ echo "" | ./custom_apps/mail/vendor/christophwurst/kitinerary-bin/bin/kitinerary-extractor
sh: ./custom_apps/mail/vendor/christophwurst/kitinerary-bin/bin/kitinerary-extractor: not found
$ ./custom_apps/mail/vendor/christophwurst/kitinerary-bin/bin/kitinerary-extractor
sh: ./custom_apps/mail/vendor/christophwurst/kitinerary-bin/bin/kitinerary-extractor: not found
```
I have never seen a case like that on a Linux system. So I searched a bit and actually you guess right.

Here is what I did:
```sh
$ apk add binutils
$ readelf -l ./custom_apps/mail/vendor/christophwurst/kitinerary-bin/bin/kitinerary-extractor |  grep "program interpreter"
      [Requesting program interpreter: /lib64/ld-linux-x86-64.so.2]
$ find / -name ld-linux-x86-64.*
```
This library does not exist on alpine linux.

I found out that there is a [kitinerary build](https://pkgs.alpinelinux.org/packages?name=kitinerary&branch=edge) but on the edge version of Alpine, and not on the 3.11.
It might come in the next stable version of Alpine by mid of this year.
Let's see.

I propose to keep this issue opened wiating for next Alpine version and see if it solves the issue. This information might be useful to others.

Thanks again for you adivces it helped me a lot to investigate (even if at the end I cannot solve itfor now).

**Comment by ChristophWurst** [comment]
> I found out that there is a [kitinerary build](https://pkgs.alpinelinux.org/packages?name=kitinerary&branch=edge) but on the edge version of Alpine, and not on the 3.11.
> It might come in the next stable version of Alpine by mid of this year.
> Let's see.

Oh, interesting. What our app already does is test which adapter is available: https://github.com/nextcloud/mail/blob/dd69da96af1e174bc07935d6ecc4dc758c09bcd8/lib/Integration/KItinerary/ItineraryExtractor.php#L57-L66. We could have a third one that invokes the binary from `PATH`. Then it should work on systems like yours as well if the admin installs the binary manually.



> I propose to keep this issue opened wiating for next Alpine version and see if it solves the issue. This information might be useful to others.

Just a binary for Alpine won't fix the issue here as we ship our own. As mentioned above, we need an additional adapter to detect and use that binary.

**Comment by sunjam** [comment]
fyi, Seeing this error in my logs on [NextcloudPi](https://github.com/nextcloud/nextcloudpi/), running off an Odroid C2.  This project is the official one for running Nextcloud on all sorts of ARM devices, but also x86 and x86-64bit as well.
![Screenshot_20200501_172900](https://user-images.githubusercontent.com/1787238/80850566-504ef900-8bd1-11ea-8217-de088af92d30.png)

**Comment by ChristophWurst** [comment]
> Seeing this error

this is a **warning**

**Comment by junpet** [comment]
The warning (still) shows up. I use `nextcloud:fpm-alpine` (version `20` currently) and Mail version `1.5.0`

**Comment by ChristophWurst** [comment]
Yes. A debug log entry is generated.

**Comment by thomas-mc-work** [comment]
I'd suggest demoting the log level to `info`, as `warning` seems misleading to me and some others too. For me a warning is something that informs about things that should be taken care of. Also, [from a dictionary](https://dictionary.cambridge.org/de/worterbuch/englisch/warning):

> something that makes you understand there is a possible danger or problem, especially one in the future

---

Another thing about your referenced source code:

> Here's the code that does the checks: ChristophWurst/kitinerary-bin@eaafa04/src/BinaryAdapter.php#L67-L94

I get this message too on arm64. But I wonder why [this block](https://github.com/ChristophWurst/kitinerary-bin/blob/eaafa040b404651cb4ab75a2d7a53c71b55d2395/src/BinaryAdapter.php#L72-L76) doesn't catch:

		if (php_uname('s') !== 'Linux' || php_uname('m') !== 'x86_64') {
			// The binary only support Linux x86_64
			$this->logger->warning('kitinerary-extractor requires Linux x86_64');
			return false;
		}

**Comment by doc75** [comment]
#5999 will decrease the logging level to info (and reduce amount of logging message)
