### ISSUE TITLE
Mail - Redirect causing a problem with links in message body

### ISSUE THREAD

**Issue by JamJarChris** [nextcloud/mail#2766]
### Expected behavior
When I receive a message in mail, some links within the message are fine, and behave as expected. 

### Actual behavior
When links within the message body use 'redirect' they do not work. Instead, upon clicking on these links, I receive a internal server error, as below:
"Internal Server Error
The server was unable to complete your request.

If this happens again, please send the technical details below to the server administrator.

More details can be found in the server log.

Technical details
Remote Address: 5.10.204.228
Request ID: J@beWzuwMMI3Tt4sXakKZf1E"

Server log shows:
Exception: Argument 1 passed to OCA\Mail\Controller\ProxyController::redirect() must be of the type string, null given, called in /home/jamjarch/next1.jamjarchris.com/lib/private/AppFramework/Http/Dispatcher.php on line 170

This occurred when I clicked on a link that had been created by Mail within a message. It gave me the link as 
https://next1.jamjarchris.com/index.php/apps/mail/redirect?src=https%3A%2F%2Farchive.org%2F

**Mail app version:** 1.1.3

Nextcloud 18.0.1 on shared hosting.

**Comment by ChristophWurst** [comment]
Please check the existing tickets: https://github.com/nextcloud/mail/issues?q=is%3Aissue+%22ProxyController%3A%3Aredirect%22+is%3Aclosed

is there a reverse proxy in front of the instance?

**Comment by JamJarChris** [comment]
Hi there - revisiting this as I would really like this to work - installed NC version 19 on shared hosting.
### Expected behavior
Tell us what should happen
Links in email body should be clickable and take one to the correct destination.
e.g. http://www.google.com takes you to google.com


### Actual behavior
Tell us what happens instead
Some links in the email message do not work as expected.
Hovering over a link to www.bcestudioarchitects.com shows 
https://next11.jamjarchris.com/index.php/apps/mail/redirect?src=http://www.bcestudioarchitects.com 
but when I click on the link it takes me to 
https://next11.jamjarchris.com/index.php/apps/mail/redirect?src=http%3A%2F%2Fwww.bcestudioarchitects.com%2F - which fails, giving and internal server error- Technical details

    Remote Address: 185.242.251.69
    Request ID: 6IVSnaWVWwF@afi4scxwy3S1


### Mail app

**Mail app version:** 1.41

**Mailserver or service:** shared hosting - 


### Server configuration

**Operating system**: Linux given

**Web server:** Apache

**Database:** Maria

**PHP version:** 7.2

**Nextcloud Version:** 19.0.0

#### Client configuration
**Browser:** Firefox 68.1 ESR
**Operating system:** Debian 10

Logging showed: 
[index] Error: Exception: Argument 1 passed to OCA\Mail\Controller\ProxyController::redirect() must be of the type string, null given, called in /home/jamjarch/next11.jamjarchris.com/lib/private/AppFramework/Http/Dispatcher.php on line 170 at <<closure>>

0. /home/jamjarch/next11.jamjarchris.com/lib/private/AppFramework/App.php line 137
   OC\AppFramework\Http\Dispatcher->dispatch(OCA\Mail\Controller\ProxyController {}, "redirect")
1. /home/jamjarch/next11.jamjarchris.com/lib/private/AppFramework/Routing/RouteActionHandler.php line 47
   OC\AppFramework\App::main("OCA\\Mail\\Controller\\ProxyController", "redirect", OC\AppFramework\ ... {}, {_route: "mail.proxy.redirect"})
2. <<closure>>
   OC\AppFramework\Routing\RouteActionHandler->__invoke({_route: "mail.proxy.redirect"})
3. /home/jamjarch/next11.jamjarchris.com/lib/private/Route/Router.php line 297
   call_user_func(OC\AppFramework\ ... {}, {_route: "mail.proxy.redirect"})
4. /home/jamjarch/next11.jamjarchris.com/lib/base.php line 1007
   OC\Route\Router->match("/apps/mail/redirect")
5. /home/jamjarch/next11.jamjarchris.com/index.php line 37
   OC::handleRequest()

GET /index.php/apps/mail/redirect?src=http%3A%2F%2Fwww.bcestudioarchitects.com%2F
from 185.242.251.69 by next11 at 2020-07-15T11:02:11+00:00

**Comment by ChristophWurst** [comment]
Could you inspect the request in the browser? Is the `src` parameter sent?

**Comment by JamJarChris** [comment]
Hi there - thanks for your reply - unsure of how to 'inspect the request in browser' - rather than waste your time, please let me know - thanks.

**Comment by ChristophWurst** [comment]
No worries :) Open the browser developer console and reproduce the bug. When you land on the page with the error you should see the GET request sent to `/index.php/apps/mail/redirect?src=...`. Your browser should be able to show which parameters have been sent. Alternatively check if the URL is OK and correctly encoded.

**Comment by JamJarChris** [comment]
Thanks. Unsure what I am looking for exactly, but the first message I see in the Console is:
Content Security Policy: The page's settings blocked the loading of a resource at inline ("script-src").
Do not see any GET parameters with  src in them.

**Comment by ChristophWurst** [comment]
Check the network tab, not the console.

**Comment by JamJarChris** [comment]
Nothing but a bunch of style related files all with status 200, sorry

**Comment by JamJarChris** [comment]
Something that may help - when an email is composed in plain text, the links within it work fine, inline or plain typed.
When the message is sent as HTML, none of the links work - extra characters are put in as blow:
Plain text email link - http://www.google.com/ - does not use redirect.php
HTML Email link - https://next11.jamjarchris.com/index.php/apps/mail/redirect?src=http%3A%2F%2Fwww.google.com
Uses redirect and replaces :// with %3A etc

**Comment by ChristophWurst** [comment]
The parameter is URL encoded: https://duckduckgo.com/?q=url+decode+http%253A%252F%252Fwww.google.com

**Comment by ChristophWurst** [comment]
The weird thing is that the server code expects one parameter: `src`. And for some reason the server does not receive it, despite the URL having it. The only things I could think of removing this are browser extensions, proxies, web firewalls or misconfigured web servers.

**Comment by JamJarChris** [comment]
Many thanks. I had turned off all browser extensions (and used another browser).
I do not use any proxies that I know of. 
No firewall that I know of. There is a problem with the security certificate which I could investigate, but I ignored it as this is for testing purposes and therefore there is only me that is using it.
The url encoding bothers me this.

On 15 July 2020 18:47:42 CEST, Christoph Wurst <notifications@github.com> wrote:
>The weird thing is that the server code expects one parameter: `src`.
>And for some reason the server does not receive it, despite the URL
>having it. The only things I could think of removing this are browser
>extensions, proxies, web firewalls or misconfigured web servers.

Many thanks,
Chris Dav
@jjc: elsmussols.net

**Comment by ChristophWurst** [comment]
You're not the first one who runs into this. Please check the other tickets again. There was something that I can't recall and lack the time to dig into this again.

**Comment by JamJarChris** [comment]
Will do. Many thanks for all your help. When I get there I will let you know.
Thanks again

On 15 July 2020 19:46:48 CEST, Christoph Wurst <notifications@github.com> wrote:
>You're not the first one who runs into this. Please check the other
>tickets again. There was something that I can't recall and lack the
>time to dig into this again.

Many thanks,
Chris Dav
@jjc: elsmussols.net
