### ISSUE TITLE
There are no archive, delete or spam buttons.

### ISSUE THREAD

**Issue by michaelberg79** [nextcloud/mail#2767]
Hi,

I am using Nextcloud 18.0.2 and Mail 1.0.0. There are no updates in the stable channel. I am missing the archive, move or spam buttons for my emails. Is this function not implemented or i am doing something wrong? Within the 3 dotted button i can only delete my messages.

best regards
Michael

**Comment by ChristophWurst** [comment]
> There are no updates in the stable channel

There are https://apps.nextcloud.com/apps/mail

> I am missing the archive, move or spam buttons

Not there, but you can use the issue search functionality to find the existing tickets: https://github.com/nextcloud/mail/issues?q=is%3Aissue+is%3Aopen+spam

Please don't open arbitrary tickets. Use Github issues only for real bug reports and feature requests when there is no existing ticket. For anything else use the forums.

Cheers
