### ISSUE TITLE
Autoconfig doesn't work

### ISSUE THREAD

**Issue by admin-pcngroup** [nextcloud/mail#2780]
### Expected behavior
Tell us what should happen
I configured the autoconfig features as follow in the ```config/config.php```
```
  'app.mail.accounts.default' => [
    'email' => '%USERID%@pcngroup.ch',
    'imapHost' => 'mail.pcngroup.ch',
    'imapPort' => 993,
    'imapUser' => '%USERID%@pcngroup.ch',
    'imapSslMode' => 'ssl',
    'smtpHost' => 'mail.pcngroup.ch',
    'smtpPort' => 465,
    'smtpUser' => '%USERID%@pcngroup.ch',
    'smtpSslMode' => 'ssl',
  ],
```
I authenticate to Nextcloud against the same IMAP server as above.

### Actual behavior
When I open the Mail App, I see the configuration page.
![image](https://user-images.githubusercontent.com/48631855/77296578-3673e980-6ce8-11ea-90eb-7a354a39eb36.png)

### Mail app

**Mail app version:** (see apps admin page, e.g. 0.5.3)
1.1.3
**Mailserver or service:** (e.g. Outlook, Yahoo, Gmail, Exchange,...)
IMAP (hMailServer for Windows)

### Server configuration

**Operating system**: (e.g. Debian 8)
CentOS 7
**Web server:** (e.g. Apache, Nginx,...)
Apache
**Database:** (e.g. MariaDB, SQLite or PostgreSQL)
MySQL (on Windows 10 - another server)
**PHP version:** (e.g. 7.0)
7.2.29
**Nextcloud Version:** (see admin page, e.g. 13.0.2)
18.0.2
#### Client configuration
**Browser:** (e.g. Firefox 48)
Chrome 80
**Operating system:** (e.g. Arch Linux)
Client: Windows 10

**Comment by ChristophWurst** [comment]
Go to your admin settings on the web ui. Under groupware you'll find the new settings.

**Comment by admin-pcngroup** [comment]
Thank you. This solved my problem. Kr.

**Comment by marcopalumbo** [comment]
@ChristophWurst  I see that now the old config/config.php method is deprecated and that all settings are available on WebUI. There's still the chance to manually tweak settings on a config file to make tests on weird setup like labs or other things? (likely having SMTP with no authentication or Self Signed SSL that needs to have Verification Skipped)

**Comment by ChristophWurst** [comment]
No, that is not possible. Please use https://help.nextcloud.com/c/apps/mail/35 for questions.
