### ISSUE TITLE
BCC not working with 'app.mail.transport' => 'php-mail'

### ISSUE THREAD

**Issue by maaeps** [nextcloud/mail#2790]
### Expected behavior
Mail addresses entered in BCC should not see the other addresses entered in BCC.

### Actual behavior
When adding `'app.mail.transport' => 'php-mail'` into config.php, BCC is ignored and every mail address entered in the BCC flield receives a mail with all the other addresses being visible as sent if entered in CC.

### Mail app

**Mail app version:** 1.1.4

**Mailserver or service:** [custom](https://thomas-leister.de/mailserver-debian-stretch/) (tested with other Providers too)

### Server configuration

**Operating system**: (Ubuntu 18.04

**Web server:** Apache2

**Database:** MariaDB

**PHP version:** 7.2

**Nextcloud Version:** 18.0.2

#### Client configuration
**Browser:** Firefox 74.0

**Operating system:** Windows 10

**Maybe it's not an issue with this repo but everybody should check if he is affected by this, too. As this is a problem with some countries law.**

**Comment by ChristophWurst** [comment]
I think this is out of scope for this application. We don not differentiate between different transmission channels. BCC is handled the same for SMTP and sendmail. So I would assume this is either Horde or your mailer deamon that transforms the message. You might be able to enable logging for the daemon.
