### ISSUE TITLE
Ability to rename folder

### ISSUE THREAD

**Issue by jancborchardt** [nextcloud/mail#2799]
Currently it is not possible to rename a folder. How we could do it:

- In the actions menu of a folder, directly below "Mark all as read" can be an action "Rename folder"
- Icon can be `icon-rename`
- Clicking it will replace the entry with an input field (just like the proposal for adding a folder at https://github.com/nextcloud/mail/issues/2798)
- The input field should have the current folder name prefilled, completely selected so you can choose to adjust the name, or just start typing to replace it.

**Comment by GretaD** [comment]
I think this is a duplication of #3058

**Comment by ChristophWurst** [comment]
I think actually #3058 is the duplicate. But the other one is already tagged and assigned, so let's use that one.

**Comment by GretaD** [comment]
my bad, i thought this was May 26th and the other one May 5th.

**Comment by jancborchardt** [comment]
When closing an issue with design spec please make sure to transfer that spec. :) I copied it over as comment into the duplicate.
