### ISSUE TITLE
Mail doesn't work in next cloud

### ISSUE THREAD

**Issue by yoyomimo** [nextcloud/mail#2824]
Hello the mail work pefectly in Sogo, but not in Nextcloud. I've got tow domaine.

[mail] Error: Exception: Argument 3 passed to OCA\Mail\Controller\FoldersController::sync() must be of the type string, null given, called in /var/www/nextcloud/lib/private/AppFramework/Http/Dispatcher.php on line 170 at <<closure>>

0. /var/www/nextcloud/lib/private/AppFramework/App.php line 125
   OC\AppFramework\Http\Dispatcher->dispatch(OCA\Mail\Controller\FoldersController {}, "sync")
1. /var/www/nextcloud/lib/private/AppFramework/Routing/RouteActionHandler.php line 47
   OC\AppFramework\App::main("OCA\\Mail\\Cont ... r", "sync", OC\AppFramework\ ... {}, {accountId: "7", ... "})
2. <<closure>>
   OC\AppFramework\Routing\RouteActionHandler->__invoke({accountId: "7", ... "})
3. /var/www/nextcloud/lib/private/Route/Router.php line 299
   call_user_func(OC\AppFramework\ ... {}, {accountId: "7", ... "})
4. /var/www/nextcloud/lib/base.php line 1008
   OC\Route\Router->match("/apps/mail/api/ ... c")
5. /var/www/nextcloud/index.php line 38
   OC::handleRequest()

GET /nc/apps/mail/api/accounts/7/folders/SU5CT1g%3D/sync?syncToken=VTEsVjE1ODU0ODQyOTQsSDE%3D
from 90.91.152.131 by test at 2020-03-29T14:16:57+00:00

Instead, I'm fucking love YunoHost! <3

**Comment by ChristophWurst** [comment]
Hi,

please use the bug report template for bug reports. Unstructured reports are very hard to process. See https://github.com/nextcloud/mail/issues/new?assignees=&labels=bug%2C+0.+to+triage&template=bug.md&title=

**Comment by ChristophWurst** [comment]
And please use the search to check the existing tickets: https://github.com/nextcloud/mail/issues?q=is%3Aissue+is%3Aopen+OCA%5CMail%5CController%5CFoldersController%3A%3Async

**Comment by yoyomimo** [comment]
Cool thank you I just did. :)

Le lun. 30 mars 2020 à 09:34, Christoph Wurst <notifications@github.com> a
écrit :
