### ISSUE TITLE
Display of subject in message list

### ISSUE THREAD

**Issue by GretaD** [nextcloud/mail#2827]
When the email is FWD or RE and belongs to a certain mailing list [MailingListName] you cannot read the subject and it gets confusing when you're trying to find an email.

![screen](https://user-images.githubusercontent.com/12728974/77929892-7c155100-72aa-11ea-8ac3-1e8f1fc26d03.png)

**Comment by ChristophWurst** [comment]
cc @jancborchardt

**Comment by jancborchardt** [comment]
Some steps to improve the display of subject in the list:
- The ellipsis seems to start too early
- We should cut any `Re: ` or `Fwd: ` prefixes here in this very short display which we have for showing the subject. It will show in full when you open the message. (We can use our list of translated `Re: ` and `Fwd: ` prefixes for that. They have to be either in the beginning of the subject, or preceded by a space so we can make sure we don’t cut content.)
- Same for any text which is in `[Brackets]` as usually it is non-essential.

**Comment by ChristophWurst** [comment]
> The ellipsis seems to start too early

I assume we break on words. If we do on character, more should be shown.

> Same for any text which is in `[Brackets]` as usually it is non-essential

This is an assumption. I don't think this is always non-essential. Especially with your example I would like to know the context of the message and that it was sent. Examples

* `[Ticket#20814438] Auftragsverarbeitung DSGVO`
* `[discuss.pixls.us] Summary`

What could work is removing the text in brackets from the subject line, but show them like tags underneath. Then the user still knows the context. But that requires more vertical space.

**Comment by jancborchardt** [comment]
> I assume we break on words. If we do on character, more should be shown.

No, ellipsis happens whenever it happens. But I found why it ellipsizes too early and opened an issue for it in the components repo: [
App content list item layout detail
#979](https://github.com/nextcloud/nextcloud-vue/issues/979).

> > Same for any text which is in `[Brackets]` as usually it is non-essential
> 
> This is an assumption. I don't think this is always non-essential.

You’re right – I meant to focus on the first 2 points and prefix the 3rd one with "if needed". :)

-------------------

So what we could specifically do in the Mail app is the 2nd point, which is cutting the `Re: ` and `Fwd: ` prefixes from there. Or we only do that when there’s something in [Brackets] present as mostly that necessitates cutting text, but that might be inconsistent.

**Comment by jancborchardt** [comment]
Opened a pull request to fix the ellipsis starting too early: https://github.com/nextcloud/mail/pull/2836

**Comment by mat-m** [comment]
ALso, we can add min-width and max-width to allow wide screens to have more room in the messages list

**Comment by CATER-COM** [comment]
I agree with @mat-m to allow larger max-with. With the actual max value of  300px, even without, RE: FWD or Braket subject prefix, I have only 3 or 4 words of the subject. I confirm 500 or 550px in max-width is more usable.

**Comment by jancborchardt** [comment]
> Also, we can add min-width and max-width to allow wide screens to have more room in the messages list, while maintaining an acceptable view for small displays.

@mat-m sounds very good! We use this 3-column design in Mail and Contacts. Do you want to prepare a pull request for both apps with values which work for both, and across screen sizes? :) We can then further test, discuss and adjust in the pull request.

**Comment by CATER-COM** [comment]
We wil also (soon ?) take advantage of the free space gained on the hidden left panel #2937 👍

**Comment by GretaD** [comment]
fixed here #2936
