### ISSUE TITLE
New tab briefly opens when clicking download on an attachment

### ISSUE THREAD

**Issue by jancborchardt** [nextcloud/mail#283]
In Chrome at least, when you click download on an attachment, for 1–2 seconds a new tab opens, and then closes as the download starts.

Is that technically necessary? It’s really a bit strange and rips out of the flow. Especially when there’s multiple attachments, the wait time is a bit much.

cc @nextcloud/mail

**Comment by ChristophWurst** [comment]
> Is that technically necessary? It’s really a bit strange and rips out of the flow. Especially when there’s multiple attachments, the wait time is a bit much.

Yup, I've added that because otherwise the browser cancelled other pending request of the current tab (e.g. anything else that was loading).

**Comment by jancborchardt** [comment]
Is there a different way to do this? Like remember what was loading and continue afterwards, or not have it block? Cause when you do want to download something and there is nothing else loading it really seems annoying.

**Comment by ChristophWurst** [comment]
> Is there a different way to do this? Like remember what was loading and continue afterwards, or not have it block? Cause when you do want to download something and there is nothing else loading it really seems annoying.

Not that I know of, but of course there could be a way. If someone knows how to do it, let me know :-)

**Comment by jancborchardt** [comment]
cc @nextcloud/javascript for help :)

**Comment by skjnldsv** [comment]
With a blob? Like I'm doing with the download image in contacts?
https://github.com/nextcloud/contacts/blob/master/js/components/avatar/avatar_controller.js#L13
