### ISSUE TITLE
Add an option to open a message in a new window

### ISSUE THREAD

**Issue by GretaD** [nextcloud/mail#2830]
### Feature Request
Add an option to open a message in a new window

#### Summary
We dont have an option to open the message in a new window

**Comment by ChristophWurst** [comment]
I think we'd just need an entry in the actions menu. We have the deep URL for a message. You can already open it in a new tab with <kbd>Ctrl</kbd>+click

**Comment by jancborchardt** [comment]
Closing as we won’t introduce this action for now:
- No clear problem statement
- Way less important than the other actions
- We have more actions which are way more important still to come (like Select and Move, and more)
