### ISSUE TITLE
Nextcloud Mail Error: cant'n send email

### ISSUE THREAD

**Issue by jh537** [nextcloud/mail#284]
### Steps to reproduce
1.subscribbe mail
2. send mail
3.

### Expected behaviour
Tell us what should happen
send email

### Actual behaviour
Tell us what happens instead
servererror
### Mail app
0.6.2
**Mail app version:** (see apps admin page)

**Mailserver or service:** (e.g. Outlook, Yahoo, Gmail, Exchange,...)
private gleisnetze.de
**Transport security - IMAP:** (None, SSL, TLS, STARTTLS) 
tls 143
**Transport security - SMTP:** (None, SSL, TLS, STARTTLS)
tls 587
**Number of accounts:**
1
**Mail app version build date:** (only if you are using a Nightly Build)

### Server configuration
**Operating system**:
ubuntu 16.04
**Web server:**
apache2
**Database:**
mariadb
**PHP version:**
Version: 7.0.13

Memory Limit: 512.0 MB

Max Execution Time: 3600

Upload max size: 511.0 MB
**Version:** (see admin page)

**Updated from an older version or fresh install:**
old
**List of activated apps:**
kalender, kontacts
```
If you have access to your command line run e.g.:
sudo -u www-data php occ app:list
from within your server installation folder
Enabled:
  - activity: 2.4.1
  - calendar: 1.4.1
  - comments: 1.1.0
  - contacts: 1.5.2
  - dav: 1.1.1
  - federatedfilesharing: 1.1.1
  - federation: 1.1.1
  - files: 1.6.1
  - files_pdfviewer: 1.0.1
  - files_sharing: 1.1.1
  - files_texteditor: 2.2
  - files_trashbin: 1.1.0
  - files_versions: 1.4.0
  - files_videoplayer: 1.0.0
  - firstrunwizard: 2.0
  - gallery: 16.0.0
  - logreader: 2.0.0
  - lookup_server_connector: 1.0.0
  - mail: 0.6.2
  - nextcloud_announcements: 1.0
  - notifications: 1.0.1
  - password_policy: 1.1.0
  - piwik: 0.2.0
  - provisioning_api: 1.1.0
  - serverinfo: 1.1.1
  - sharebymail: 1.0.1
  - survey_client: 0.1.5
  - systemtags: 1.1.3
  - tasks: 0.9.4
  - theming: 1.1.1
  - twofactor_backupcodes: 1.0.0
  - updatenotification: 1.1.1
  - workflowengine: 1.1.1
Disabled:
  - admin_audit
  - encryption
  - external
  - files_accesscontrol
  - files_automatedtagging
  - files_external
  - files_retention
  - templateeditor
  - user_external
  - user_ldap
  - user_saml


**The content of config/config.php:**

<?php
$CONFIG = array (
  'instanceid' => 'fffffffffffffffffffff',
  'passwordsalt' => 'fffffffffffffffffffffffffffff',
  'secret' => 'fffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff',
  'trusted_domains' =>
  array (
    0 => 'www.gleisnetze.de',
  ),
  'datadirectory' => '/var/www/html/nextcloud/data',
  'overwrite.cli.url' => 'https://www.gleisnetze.de/nextcloud',
  'dbtype' => 'mysql',
  'version' => '11.0.0.10',
  'dbname' => 'nc1',
  'dbhost' => 'localhost',
  'dbport' => '',
  'dbtableprefix' => 'oc_',
  'dbuser' => 'ffffff,
  'dbpassword' => 'fffffffff',
  'logtimezone' => 'UTC',
  'installed' => true,
  'maintenance' => false,
  'mail_from_address' => 'webmaster',
  'mail_smtpmode' => 'php',
  'mail_domain' => 'gleisnetze.de',
  'memcache.local' => '\\OC\\Memcache\\Redis',
  'redis' =>
  array (
    'host' => 'localhost',
    'port' => 6379,
  ),
  'memcache.locking' => '\\OC\\Memcache\\Redis',
);
~                                                                               
~                                                                               
~                                                     
If you have access to your command line run e.g.:
sudo -u www-data php occ config:list system
from within your server installation folder

{
    "system": {
        "instanceid": "oczobm73nmvi",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "www.gleisnetze.de"
        ],
        "datadirectory": "\/var\/www\/html\/nextcloud\/data",
        "overwrite.cli.url": "https:\/\/www.gleisnetze.de\/nextcloud",
        "dbtype": "mysql",
        "version": "11.0.0.10",
        "dbname": "nc1",
        "dbhost": "localhost",
        "dbport": "",
        "dbtableprefix": "oc_",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "logtimezone": "UTC",
        "installed": true,
        "maintenance": false,
        "mail_from_address": "webmaster",
        "mail_smtpmode": "php",
        "mail_domain": "gleisnetze.de",
        "memcache.local": "\\OC\\Memcache\\Redis",
        "redis": {
            "host": "localhost",
            "port": 6379
        },
        "memcache.locking": "\\OC\\Memcache\\Redis"
    }
}


Insert your config.php content here
(Without the database password, passwordsalt and secret)
```
</details>

#### Client configuration
**Browser:**

**Operating system:**

##### Web server error log
```
Insert your webserver log here
```

##### Server log (data/nextcloud.log)
Error	index	Exception: Authenticated ciphertext could not be decoded.

    /var/www/html/nextcloud/apps/mail/lib/Account.php - line 385: OC\Security\Crypto->decrypt(*** sensitive parameters replaced ***)
    /var/www/html/nextcloud/apps/mail/lib/Account.php - line 208: OCA\Mail\Account->createTransport()
    /var/www/html/nextcloud/apps/mail/lib/Controller/AccountsController.php - line 333: OCA\Mail\Account->sendMessage(Object(OCA\Mail\Model\Message), 78)
    [internal function] OCA\Mail\Controller\AccountsController->send(2, NULL, 'Testung', 'Prfung\nd\ndddddd', '"J. Franz" <jhf...', '09113jhf@gmail....', '', 78, NULL, NULL, '')
    /var/www/html/nextcloud/lib/private/AppFramework/Http/Dispatcher.php - line 160: call_user_func_array(Array, Array)
    /var/www/html/nextcloud/lib/private/AppFramework/Http/Dispatcher.php - line 90: OC\AppFramework\Http\Dispatcher->executeController(Object(OCA\Mail\Controller\AccountsController), 'send')
    /var/www/html/nextcloud/lib/private/AppFramework/App.php - line 114: OC\AppFramework\Http\Dispatcher->dispatch(Object(OCA\Mail\Controller\AccountsController), 'send')
    /var/www/html/nextcloud/lib/private/AppFramework/Routing/RouteActionHandler.php - line 47: OC\AppFramework\App main('OCA\\Mail\\Contro...', 'send', Object(OC\AppFramework\DependencyInjection\DIContainer), Array)
    [internal function] OC\AppFramework\Routing\RouteActionHandler->__invoke(Array)
    /var/www/html/nextcloud/lib/private/Route/Router.php - line 299: call_user_func(Object(OC\AppFramework\Routing\RouteActionHandler), Array)
    /var/www/html/nextcloud/lib/base.php - line 1010: OC\Route\Router->match('/apps/mail/acco...')
    /var/www/html/nextcloud/index.php - line 40: OC handleRequest()
    {main}
Insert your server log here
```
</details>

##### Horde IMAP log (data/horde_imap.log)
<details>
```
Insert your horde IMAP log here, see https://github.com/nextcloud/mail#debug-mode
```
</details>

##### Horde SMTP log (data/horde_smtp.log)
<details>
```
Insert your horde SMTP log here, see https://github.com/nextcloud/mail#debug-mode
```
</details>

##### Browser log
<details>
```
Insert your browser log here, this could for example include:

a) The javascript console log
b) The network log 
c) ...
```
</details>

**Comment by ChristophWurst** [comment]
> Error index Exception: Authenticated ciphertext could not be decoded.

This should not have happened. Did you maybe change the secret in config.php or import data from an old installation?

**Comment by jh537** [comment]
I am not sure that the config.php has been safely re-installed but I have the database will not be deleted.

**Comment by ChristophWurst** [comment]
What do you mean? Did you change the value of 'secret' in config/config.php?

**Comment by jh537** [comment]
I have in the config.php no values changed. There may be a problem because I am the database when reinstalling will not be deleted, since I have tried with the old database continues to work. But it may also be that I have deleted it. In the config.php I just inserted at the end of the cache.

Ich habe in der config.php keine Werte geändert. Möglicherweise besteht ein Problem, weil ich die Datenbank beim Neuinstallieren nicht gelöscht habe, da ich versucht habe mit der alten Datenbank weiter zu arbeiten. Es kann aber auch sein, dass ich sie doch gelöscht habe. In der config.php habe ich nur am Ende den Cache eingefügt.

**Comment by jh537** [comment]
Vielleicht habe ich doch auch die alte config.php vom Backup wieder eingefügt. Wie kann ich vorgehen? Hilft nur eine Neuinstallation?

Maybe I but also the old config.php from the backup once inserted. What can i do? Only helps a new installation?

**Comment by ChristophWurst** [comment]
> Ich habe in der config.php keine Werte geändert. Möglicherweise besteht ein Problem, weil ich die Datenbank beim Neuinstallieren nicht gelöscht habe, da ich versucht habe mit der alten Datenbank weiter zu arbeiten. Es kann aber auch sein, dass ich sie doch gelöscht habe. In der config.php habe ich nur am Ende den Cache eingefügt.

Okay, das erklärt das Problem. 'secret' wird als Passwort für die Accounts benutz, darum kann es bei dir nicht mehr entschlüsselt werden. Du kannst es mit dem alten Secret versuchen. Kann funktionieren, oder auch nicht. Eine Installation dieser Art wird nicht unterstützt, eine Neuinstallation macht hier sinn, da du auch noch andere Probleme haben wirst.

**Comment by ChristophWurst** [comment]
I'm closing this ticket now because the problem is caused by an unsupported installation/upgrade path

**Comment by jh537** [comment]
okay, many thks ...

**Comment by jh537** [comment]
Ich habe alles neu installiert und die DB auch neu gemacht. Leider mit gleichem Ergebnis.

**Comment by jh537** [comment]
Beim Öffnen des Postausgang gibt es leider auch Fehler:

Error	index	TypeError: Argument 1 passed to OCA\Mail\Model\IMAPMessage::hordeToAssoc() must be an instance of Horde_Mail_Rfc822_Address, instance of Horde_Mail_Rfc822_Group given, called in /var/www/html/nextcloud/apps/mail/lib/Model/ConvertAddresses.php on line 74

    /var/www/html/nextcloud/apps/mail/lib/Model/ConvertAddresses.php - line 74: OCA\Mail\Model\IMAPMessage->hordeToAssoc(Object(Horde_Mail_Rfc822_Group))
    /var/www/html/nextcloud/apps/mail/lib/Model/IMAPMessage.php - line 225: OCA\Mail\Model\IMAPMessage->convertAddressList(Object(Horde_Mail_Rfc822_List))
    /var/www/html/nextcloud/apps/mail/lib/Model/IMAPMessage.php - line 494: OCA\Mail\Model\IMAPMessage->getToList(true)
    /var/www/html/nextcloud/apps/mail/lib/Mailbox.php - line 190: OCA\Mail\Model\IMAPMessage->jsonSerialize()
    /var/www/html/nextcloud/apps/mail/lib/Controller/MessagesController.php - line 137: OCA\Mail\Mailbox->getMessages(0, 21, '')
    [internal function] OCA\Mail\Controller\MessagesController->index(1, 'U2VudA==', 0, 20, '', NULL)
    /var/www/html/nextcloud/lib/private/AppFramework/Http/Dispatcher.php - line 160: call_user_func_array(Array, Array)
    /var/www/html/nextcloud/lib/private/AppFramework/Http/Dispatcher.php - line 90: OC\AppFramework\Http\Dispatcher->executeController(Object(OCA\Mail\Controller\MessagesController), 'index')
    /var/www/html/nextcloud/lib/private/AppFramework/App.php - line 114: OC\AppFramework\Http\Dispatcher->dispatch(Object(OCA\Mail\Controller\MessagesController), 'index')
    /var/www/html/nextcloud/lib/private/AppFramework/Routing/RouteActionHandler.php - line 47: OC\AppFramework\App main('OCA\\Mail\\Contro...', 'index', Object(OC\AppFramework\DependencyInjection\DIContainer), Array)
    [internal function] OC\AppFramework\Routing\RouteActionHandler->__invoke(Array)
    /var/www/html/nextcloud/lib/private/Route/Router.php - line 299: call_user_func(Object(OC\AppFramework\Routing\RouteActionHandler), Array)
    /var/www/html/nextcloud/lib/base.php - line 1010: OC\Route\Router->match('/apps/mail/acco...')
    /var/www/html/nextcloud/index.php - line 40: OC handleRequest()
    {main}

**Comment by jh537** [comment]
Das Senden funktioniert: Ich habe die Serverangaben manuell eingetragen.
