### ISSUE TITLE
Create Sent and Draft folders if they don't exist

### ISSUE THREAD

**Issue by p-jo** [nextcloud/mail#2842]
### Feature Request

My email providers newly created accounts don't have Sent and Draft folders, so I get an error message on sending or saving messages (but they are still sent). Would want to have Mail create those folders if they don't exist.

#### Summary

Have Mail create Sent and Draft folders on sending and saving messages, if they don't exist.

**Comment by ChristophWurst** [comment]
We actually do that :thinking: 

Which version of the app do you use? Any errors in nextcloud.log?

**Comment by p-jo** [comment]
Ok good to know :) There seems to be some other problem that I can't figure out. But the email is still sending.
I'm using Mail 1.1.4 and Nextcloud 18.0.1. Here is the log message:

`{"reqId":"MdvHP5sAl8XbyLDdvrVT","level":2,"time":"2020-04-01T19:31:16+00:00","remoteAddr":"213.65.166.149","user":"test1","app":"mail","method":"POST","url":"/apps/mail/api/accounts/8/send","message":{"Exception":"Horde_Imap_Client_Exception_ServerResponse","Message":"IMAP error reported by server.","Code":0,"Trace":[{"file":"/var/www/nextcloud/apps/mail/vendor/pear-pear.horde.org/Horde_Imap_Client/Horde/Imap/Client/Socket.php","line":4314,"function":"_getLine","class":"Horde_Imap_Client_Socket","type":"->","args":[{"data":{"modseqs":[],"modseqs_nouid":[]},"fetch":{"__class__":"Horde_Imap_Client_Fetch_Results"},"__class__":"Horde_Imap_Client_Interaction_Pipeline"}]},{"file":"/var/www/nextcloud/apps/mail/vendor/pear-pear.horde.org/Horde_Imap_Client/Horde/Imap/Client/Socket.php","line":4242,"function":"_sendCmdChunk","class":"Horde_Imap_Client_Socket","type":"->","args":[{"data":{"modseqs":[],"modseqs_nouid":[]},"fetch":{"__class__":"Horde_Imap_Client_Fetch_Results"},"__class__":"Horde_Imap_Client_Interaction_Pipeline"},[{"debug":[],"literalplus":true,"literal8":false,"on_error":{"__class__":"Closure"},"on_success":null,"pipeline":{"data":{"modseqs":[],"modseqs_nouid":[]},"fetch":{"__class__":"Horde_Imap_Client_Fetch_Results"},"__class__":"Horde_Imap_Client_Interaction_Pipeline"},"response":{"tag":"2","responseCode":null,"status":4,"token":{"__class__":"Horde_Imap_Client_Tokenize"},"__class__":"Horde_Imap_Client_Interaction_Server_Tagged"},"tag":"2","__class__":"Horde_Imap_Client_Interaction_Command"},{"debug":[],"literalplus":true,"literal8":false,"on_error":null,"on_success":null,"pipeline":{"data":{"modseqs":[],"modseqs_nouid":[]},"fetch":{"__class__":"Horde_Imap_Client_Fetch_Results"},"__class__":"Horde_Imap_Client_Interaction_Pipeline"},"response":{"tag":"3","responseCode":null,"status":3,"token":{"__class__":"Horde_Imap_Client_Tokenize"},"__class__":"Horde_Imap_Client_Interaction_Server_Tagged"},"tag":"3","__class__":"Horde_Imap_Client_Interaction_Command"}]]},{"file":"/var/www/nextcloud/apps/mail/vendor/pear-pear.horde.org/Horde_Imap_Client/Horde/Imap/Client/Socket.php","line":1276,"function":"_sendCmd","class":"Horde_Imap_Client_Socket","type":"->","args":[{"debug":[],"literalplus":true,"literal8":false,"on_error":null,"on_success":null,"pipeline":{"data":{"modseqs":[],"modseqs_nouid":[]},"fetch":{"__class__":"Horde_Imap_Client_Fetch_Results"},"__class__":"Horde_Imap_Client_Interaction_Pipeline"},"response":{"tag":"3","responseCode":null,"status":3,"token":{"__class__":"Horde_Imap_Client_Tokenize"},"__class__":"Horde_Imap_Client_Interaction_Server_Tagged"},"tag":"3","__class__":"Horde_Imap_Client_Interaction_Command"}]},{"file":"/var/www/nextcloud/apps/mail/vendor/pear-pear.horde.org/Horde_Imap_Client/Horde/Imap/Client/Base.php","line":1148,"function":"_createMailbox","class":"Horde_Imap_Client_Socket","type":"->","args":[{"__class__":"Horde_Imap_Client_Mailbox"},[]]},{"file":"/var/www/nextcloud/apps/mail/lib/Listener/SaveSentMessageListener.php","line":107,"function":"createMailbox","class":"Horde_Imap_Client_Base","type":"->","args":["Sent",[]]},{"file":"/var/www/nextcloud/apps/mail/lib/Listener/SaveSentMessageListener.php","line":79,"function":"createSentMailbox","class":"OCA\\Mail\\Listener\\SaveSentMessageListener","type":"->","args":[{"__class__":"OCA\\Mail\\Account"}]},{"file":"/var/www/nextcloud/lib/private/EventDispatcher/ServiceEventListener.php","line":76,"function":"handle","class":"OCA\\Mail\\Listener\\SaveSentMessageListener","type":"->","args":[{"__class__":"OCA\\Mail\\Events\\MessageSentEvent"}]},{"file":"/var/www/nextcloud/3rdparty/symfony/event-dispatcher/EventDispatcher.php","line":247,"function":"__invoke","class":"OC\\EventDispatcher\\ServiceEventListener","type":"->","args":[{"__class__":"OCA\\Mail\\Events\\MessageSentEvent"},"OCA\\Mail\\Events\\MessageSentEvent",{"__class__":"Symfony\\Component\\EventDispatcher\\EventDispatcher"}]},{"file":"/var/www/nextcloud/3rdparty/symfony/event-dispatcher/EventDispatcher.php","line":73,"function":"callListeners","class":"Symfony\\Component\\EventDispatcher\\EventDispatcher","type":"->","args":[[{"__class__":"Closure"},{"__class__":"Closure"},{"__class__":"Closure"},{"__class__":"Closure"}],"OCA\\Mail\\Events\\MessageSentEvent",{"__class__":"OCA\\Mail\\Events\\MessageSentEvent"}]},{"file":"/var/www/nextcloud/lib/private/EventDispatcher/EventDispatcher.php","line":80,"function":"dispatch","class":"Symfony\\Component\\EventDispatcher\\EventDispatcher","type":"->","args":[{"__class__":"OCA\\Mail\\Events\\MessageSentEvent"},"OCA\\Mail\\Events\\MessageSentEvent"]},{"file":"/var/www/nextcloud/apps/mail/lib/Service/MailTransmission.php","line":182,"function":"dispatch","class":"OC\\EventDispatcher\\EventDispatcher","type":"->","args":["OCA\\Mail\\Events\\MessageSentEvent",{"__class__":"OCA\\Mail\\Events\\MessageSentEvent"}]},{"file":"/var/www/nextcloud/apps/mail/lib/Controller/AccountsController.php","line":332,"function":"sendMessage","class":"OCA\\Mail\\Service\\MailTransmission","type":"->","args":["test1",{"__class__":"OCA\\Mail\\Model\\NewMessageData"},null,null,null]},{"file":"/var/www/nextcloud/lib/private/AppFramework/Http/Dispatcher.php","line":170,"function":"send","class":"OCA\\Mail\\Controller\\AccountsController","type":"->","args":[8,"test1","testnr1","xxxxx","","",false,null,null,null,[],null]},{"file":"/var/www/nextcloud/lib/private/AppFramework/Http/Dispatcher.php","line":99,"function":"executeController","class":"OC\\AppFramework\\Http\\Dispatcher","type":"->","args":[{"__class__":"OCA\\Mail\\Controller\\AccountsController"},"send"]},{"file":"/var/www/nextcloud/lib/private/AppFramework/App.php","line":125,"function":"dispatch","class":"OC\\AppFramework\\Http\\Dispatcher","type":"->","args":[{"__class__":"OCA\\Mail\\Controller\\AccountsController"},"send"]},{"file":"/var/www/nextcloud/lib/private/AppFramework/Routing/RouteActionHandler.php","line":47,"function":"main","class":"OC\\AppFramework\\App","type":"::","args":["OCA\\Mail\\Controller\\AccountsController","send",{"__class__":"OC\\AppFramework\\DependencyInjection\\DIContainer"},{"accountId":"8","_route":"mail.accounts.send"}]},{"function":"__invoke","class":"OC\\AppFramework\\Routing\\RouteActionHandler","type":"->","args":[{"accountId":"8","_route":"mail.accounts.send"}]},{"file":"/var/www/nextcloud/lib/private/Route/Router.php","line":299,"function":"call_user_func","args":[{"__class__":"OC\\AppFramework\\Routing\\RouteActionHandler"},{"accountId":"8","_route":"mail.accounts.send"}]},{"file":"/var/www/nextcloud/lib/base.php","line":1008,"function":"match","class":"OC\\Route\\Router","type":"->","args":["/apps/mail/api/accounts/8/send"]},{"file":"/var/www/nextcloud/index.php","line":38,"function":"handleRequest","class":"OC","type":"::","args":[]}],"File":"/var/www/nextcloud/apps/mail/vendor/pear-pear.horde.org/Horde_Imap_Client/Horde/Imap/Client/Socket.php","Line":4602,"CustomMessage":"Could not create sent mailbox"},"userAgent":"Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_3) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/64.0.3282.186 Safari/537.36","version":"18.0.1.3","id":"5e84ed99b2ac1"}`

**Comment by ChristophWurst** [comment]
> Could you open a bug report instead so we can have a more structured overview of your setup?

-> https://github.com/nextcloud/mail/issues/new?assignees=&labels=bug%2C+0.+to+triage&template=bug.md&title=

**Comment by p-jo** [comment]
I'll do that, thanks!
