### ISSUE TITLE
Mail app cant connet to imap server after upgrade to NC 18

### ISSUE THREAD

**Issue by sonic42** [nextcloud/mail#2844]
The configured account after upgrade is not more working and adding a new account is not more possible with error: 
"Could not open secure TLS connection to the server" 
The app from NC 17 works fine. No dovecot or postfix settings are changed.
A parallel installed Roundcube 1.4.1 works perfectly with the same server (same php version that runs nextcloud)

Dovecot Log:
TLS handshaking: SSL_accept() failed: error:14094418:SSL routines:ssl3_read_bytes:tlsv1 alert unknown ca: SSL alert number 48

Postfix Log:
smtpd[27353]: warning: TLS library problem: error:14094418:SSL routines:ssl3_read_bytes:tlsv1 alert unknown ca:ssl/record/rec_layer_s3.c:1543:SSL alert number 48

### Mail app
Mail app version: 1.1.4
Mailserver or service: local dovecot 2.3.9.2 and postfix 3.4.9 offers only TLS 1.2 and TLS 1.3
Web server: Apache 2.4.41
Database: MariaDB
PHP version: 7.4.4
Nextcloud Version: 18.0.3
Browser: actual Firefox or Palemoon

**Comment by ChristophWurst** [comment]
Hi,

I'm sorry for the inconveniences. This is due to a security hardening in our code. You can check https://github.com/nextcloud/mail/releases/tag/v1.1.4 for instructions on how to get the old behavior back.

#2785 exists in case you were wondering if we planned a user setting :)

Cheers
