### ISSUE TITLE
Probleme LOCAL email server NEXTCLOUD 18

### ISSUE THREAD

**Issue by yoyomimo** [nextcloud/mail#2847]
Hello Every Bodies!

I use NextCloud (18) on YunoHost server (3.7). 

With SoGo i have access automatycli on my "localhost " mail server. But on Nextclou email app, I  can't have access to the mail.

This is nexcloud log:

[mail] Error: Exception: Argument 3 passed to OCA\Mail\Controller\FoldersController::sync() must be of the type string, null given, called in /var/www/nextcloud/lib/private/AppFramework/Http/Dispatcher.php on line 170 at <>

    /var/www/nextcloud/lib/private/AppFramework/App.php line 125
    OC\AppFramework\Http\Dispatcher->dispatch(OCA\Mail\Controller\FoldersController {}, "sync")
    /var/www/nextcloud/lib/private/AppFramework/Routing/RouteActionHandler.php line 47
    OC\AppFramework\App::main("OCA\Mail\Cont ... r", "sync", OC\AppFramework\ ... {}, {accountId: "7", ... "})
    <>
    OC\AppFramework\Routing\RouteActionHandler->__invoke({accountId: "7", ... "})
    /var/www/nextcloud/lib/private/Route/Router.php line 299
    call_user_func(OC\AppFramework\ ... {}, {accountId: "7", ... "})
    /var/www/nextcloud/lib/base.php line 1008
    OC\Route\Router->match("/apps/mail/api/ ... c")
    /var/www/nextcloud/index.php line 38
    OC::handleRequest()

GET /nc/apps/mail/api/accounts/7/folders/SU5CT1g%3D/sync?syncToken=VTEsVjE1ODU0ODQyOTQsSDE%3D
from 90.91.152.131 by test at 2020-03-29T14:14:22+00:00

Thank You really much!

**Comment by ChristophWurst** [comment]
See https://github.com/nextcloud/mail/issues/2824#issuecomment-605832767. You ignored the template and omitted important information.

**Comment by ChristophWurst** [comment]
And this still smells like on of the known problems https://github.com/nextcloud/mail/issues?q=is%3Aissue+is%3Aopen+OCA%5CMail%5CController%5CFoldersController%3A%3Async

**Comment by yoyomimo** [comment]
> 
> 
> See [#2824 (comment)](https://github.com/nextcloud/mail/issues/2824#issuecomment-605832767). You ignored the template and omitted important information.

Sorry I forgive, But this post is more precise, and I didn't any awnser and I tri since 8 day and didn't found where is the probleme. :'(

thank you

**Comment by ChristophWurst** [comment]
No worries.

Have you compared your problem to the existing tickets? Any common denominator?

**Comment by yoyomimo** [comment]
I close the other one, but have still has the issue.

**Comment by ChristophWurst** [comment]
Check https://github.com/nextcloud/server/issues/16252 for a possibly related problem.

Due to the lack of information provided I'm afraid I can't offer further debugging help.

> GET /nc/apps/mail/api/accounts/7/folders/SU5CT1g%3D/sync?syncToken=VTEsVjE1ODU0ODQyOTQsSDE%3D

`syncToken` is set, but it does not arrive at https://github.com/nextcloud/mail/blob/v1.1.4/lib/Controller/FoldersController.php. This indicates a problem with your web server configuration.

**Comment by yoyomimo** [comment]
> 
> 
> Check [nextcloud/server#16252](https://github.com/nextcloud/server/issues/16252) for a possibly related problem.
> 
> Due to the lack of information provided I'm afraid I can't offer further debugging help.
> 
> > GET /nc/apps/mail/api/accounts/7/folders/SU5CT1g%3D/sync?syncToken=VTEsVjE1ODU0ODQyOTQsSDE%3D
> 
> `syncToken` is set, but it does not arrive at https://github.com/nextcloud/mail/blob/v1.1.4/lib/Controller/FoldersController.php. This indicates a problem with your web server configuration.

What more do need, the log is not enough?

**Comment by ChristophWurst** [comment]
I asked for the issue template twice. It would tell me your web server and php version, for example.

Anyhow, I think it's better if you consult https://help.nextcloud.com/ for community support. This strongly smells like a setup issue and not one with our code as all, so I'm prioritizing other things.
