### ISSUE TITLE
Sent folder not created when sending email

### ISSUE THREAD

**Issue by p-jo** [nextcloud/mail#2848]
### Expected behavior
When using new email accounts I expect Mail to create the Drafts and Sent folders if they don't exist.

### Actual behavior
I get an error message "Error sending your message Error: Request failed with status code 404", (see also errors in the log below) and the Sent folder is not created when I send a message, but the message is still sent. And the Draft folder is not created when I try to save a message.

### Mail app

**Mail app version:**  1.1.4

**Mailserver or service:** IMAP from hosting company (glesys.com)

### Server configuration

**Operating system**: Debian 10

**Web server:** Apache

**Database:** MariaDB

**PHP version:** 7.3

**Nextcloud Version:** 18.0.1

#### Client configuration
**Browser:** Firefox 74

**Operating system:** OSX

### Nextcloud log

`{"reqId":"MdvHP5sAl8XbyLDdvrVT","level":2,"time":"2020-04-01T19:31:16+00:00","remoteAddr":"213.65.166.149","user":"test1","app":"mail","method":"POST","url":"/apps/mail/api/accounts/8/send","message":{"Exception":"Horde_Imap_Client_Exception_ServerResponse","Message":"IMAP error reported by server.","Code":0,"Trace":[{"file":"/var/www/nextcloud/apps/mail/vendor/pear-pear.horde.org/Horde_Imap_Client/Horde/Imap/Client/Socket.php","line":4314,"function":"_getLine","class":"Horde_Imap_Client_Socket","type":"->","args":[{"data":{"modseqs":[],"modseqs_nouid":[]},"fetch":{"__class__":"Horde_Imap_Client_Fetch_Results"},"__class__":"Horde_Imap_Client_Interaction_Pipeline"}]},{"file":"/var/www/nextcloud/apps/mail/vendor/pear-pear.horde.org/Horde_Imap_Client/Horde/Imap/Client/Socket.php","line":4242,"function":"_sendCmdChunk","class":"Horde_Imap_Client_Socket","type":"->","args":[{"data":{"modseqs":[],"modseqs_nouid":[]},"fetch":{"__class__":"Horde_Imap_Client_Fetch_Results"},"__class__":"Horde_Imap_Client_Interaction_Pipeline"},[{"debug":[],"literalplus":true,"literal8":false,"on_error":{"__class__":"Closure"},"on_success":null,"pipeline":{"data":{"modseqs":[],"modseqs_nouid":[]},"fetch":{"__class__":"Horde_Imap_Client_Fetch_Results"},"__class__":"Horde_Imap_Client_Interaction_Pipeline"},"response":{"tag":"2","responseCode":null,"status":4,"token":{"__class__":"Horde_Imap_Client_Tokenize"},"__class__":"Horde_Imap_Client_Interaction_Server_Tagged"},"tag":"2","__class__":"Horde_Imap_Client_Interaction_Command"},{"debug":[],"literalplus":true,"literal8":false,"on_error":null,"on_success":null,"pipeline":{"data":{"modseqs":[],"modseqs_nouid":[]},"fetch":{"__class__":"Horde_Imap_Client_Fetch_Results"},"__class__":"Horde_Imap_Client_Interaction_Pipeline"},"response":{"tag":"3","responseCode":null,"status":3,"token":{"__class__":"Horde_Imap_Client_Tokenize"},"__class__":"Horde_Imap_Client_Interaction_Server_Tagged"},"tag":"3","__class__":"Horde_Imap_Client_Interaction_Command"}]]},{"file":"/var/www/nextcloud/apps/mail/vendor/pear-pear.horde.org/Horde_Imap_Client/Horde/Imap/Client/Socket.php","line":1276,"function":"_sendCmd","class":"Horde_Imap_Client_Socket","type":"->","args":[{"debug":[],"literalplus":true,"literal8":false,"on_error":null,"on_success":null,"pipeline":{"data":{"modseqs":[],"modseqs_nouid":[]},"fetch":{"__class__":"Horde_Imap_Client_Fetch_Results"},"__class__":"Horde_Imap_Client_Interaction_Pipeline"},"response":{"tag":"3","responseCode":null,"status":3,"token":{"__class__":"Horde_Imap_Client_Tokenize"},"__class__":"Horde_Imap_Client_Interaction_Server_Tagged"},"tag":"3","__class__":"Horde_Imap_Client_Interaction_Command"}]},{"file":"/var/www/nextcloud/apps/mail/vendor/pear-pear.horde.org/Horde_Imap_Client/Horde/Imap/Client/Base.php","line":1148,"function":"_createMailbox","class":"Horde_Imap_Client_Socket","type":"->","args":[{"__class__":"Horde_Imap_Client_Mailbox"},[]]},{"file":"/var/www/nextcloud/apps/mail/lib/Listener/SaveSentMessageListener.php","line":107,"function":"createMailbox","class":"Horde_Imap_Client_Base","type":"->","args":["Sent",[]]},{"file":"/var/www/nextcloud/apps/mail/lib/Listener/SaveSentMessageListener.php","line":79,"function":"createSentMailbox","class":"OCA\\Mail\\Listener\\SaveSentMessageListener","type":"->","args":[{"__class__":"OCA\\Mail\\Account"}]},{"file":"/var/www/nextcloud/lib/private/EventDispatcher/ServiceEventListener.php","line":76,"function":"handle","class":"OCA\\Mail\\Listener\\SaveSentMessageListener","type":"->","args":[{"__class__":"OCA\\Mail\\Events\\MessageSentEvent"}]},{"file":"/var/www/nextcloud/3rdparty/symfony/event-dispatcher/EventDispatcher.php","line":247,"function":"__invoke","class":"OC\\EventDispatcher\\ServiceEventListener","type":"->","args":[{"__class__":"OCA\\Mail\\Events\\MessageSentEvent"},"OCA\\Mail\\Events\\MessageSentEvent",{"__class__":"Symfony\\Component\\EventDispatcher\\EventDispatcher"}]},{"file":"/var/www/nextcloud/3rdparty/symfony/event-dispatcher/EventDispatcher.php","line":73,"function":"callListeners","class":"Symfony\\Component\\EventDispatcher\\EventDispatcher","type":"->","args":[[{"__class__":"Closure"},{"__class__":"Closure"},{"__class__":"Closure"},{"__class__":"Closure"}],"OCA\\Mail\\Events\\MessageSentEvent",{"__class__":"OCA\\Mail\\Events\\MessageSentEvent"}]},{"file":"/var/www/nextcloud/lib/private/EventDispatcher/EventDispatcher.php","line":80,"function":"dispatch","class":"Symfony\\Component\\EventDispatcher\\EventDispatcher","type":"->","args":[{"__class__":"OCA\\Mail\\Events\\MessageSentEvent"},"OCA\\Mail\\Events\\MessageSentEvent"]},{"file":"/var/www/nextcloud/apps/mail/lib/Service/MailTransmission.php","line":182,"function":"dispatch","class":"OC\\EventDispatcher\\EventDispatcher","type":"->","args":["OCA\\Mail\\Events\\MessageSentEvent",{"__class__":"OCA\\Mail\\Events\\MessageSentEvent"}]},{"file":"/var/www/nextcloud/apps/mail/lib/Controller/AccountsController.php","line":332,"function":"sendMessage","class":"OCA\\Mail\\Service\\MailTransmission","type":"->","args":["test1",{"__class__":"OCA\\Mail\\Model\\NewMessageData"},null,null,null]},{"file":"/var/www/nextcloud/lib/private/AppFramework/Http/Dispatcher.php","line":170,"function":"send","class":"OCA\\Mail\\Controller\\AccountsController","type":"->","args":[8,"test1","testnr1","xxxxx","","",false,null,null,null,[],null]},{"file":"/var/www/nextcloud/lib/private/AppFramework/Http/Dispatcher.php","line":99,"function":"executeController","class":"OC\\AppFramework\\Http\\Dispatcher","type":"->","args":[{"__class__":"OCA\\Mail\\Controller\\AccountsController"},"send"]},{"file":"/var/www/nextcloud/lib/private/AppFramework/App.php","line":125,"function":"dispatch","class":"OC\\AppFramework\\Http\\Dispatcher","type":"->","args":[{"__class__":"OCA\\Mail\\Controller\\AccountsController"},"send"]},{"file":"/var/www/nextcloud/lib/private/AppFramework/Routing/RouteActionHandler.php","line":47,"function":"main","class":"OC\\AppFramework\\App","type":"::","args":["OCA\\Mail\\Controller\\AccountsController","send",{"__class__":"OC\\AppFramework\\DependencyInjection\\DIContainer"},{"accountId":"8","_route":"mail.accounts.send"}]},{"function":"__invoke","class":"OC\\AppFramework\\Routing\\RouteActionHandler","type":"->","args":[{"accountId":"8","_route":"mail.accounts.send"}]},{"file":"/var/www/nextcloud/lib/private/Route/Router.php","line":299,"function":"call_user_func","args":[{"__class__":"OC\\AppFramework\\Routing\\RouteActionHandler"},{"accountId":"8","_route":"mail.accounts.send"}]},{"file":"/var/www/nextcloud/lib/base.php","line":1008,"function":"match","class":"OC\\Route\\Router","type":"->","args":["/apps/mail/api/accounts/8/send"]},{"file":"/var/www/nextcloud/index.php","line":38,"function":"handleRequest","class":"OC","type":"::","args":[]}],"File":"/var/www/nextcloud/apps/mail/vendor/pear-pear.horde.org/Horde_Imap_Client/Horde/Imap/Client/Socket.php","Line":4602,"CustomMessage":"Could not create sent mailbox"},"userAgent":"Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_3) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/64.0.3282.186 Safari/537.36","version":"18.0.1.3","id":"5e84ed99b2ac1"}`

**Comment by ChristophWurst** [comment]
The code actually fails *when it tries to create the folder*. From the logs I can not tell why the IMAP server reports an error. Could be that the mailbox already exists, but let's find out.

Please apply the patch https://patch-diff.githubusercontent.com/raw/nextcloud/mail/pull/2849.patch.

The Nextcloud mail app offers an extensive logging system to make it easier identifying and tracking down bugs. Please enable [debug mode](https://docs.nextcloud.com/server/stable/developer_manual/general/devenv.html#enabling-debug-mode) and set the log [level to debug](https://docs.nextcloud.com/server/stable/admin_manual/configuration_server/logging_configuration.html) in your admin settings. Then, try to reproduce your issue and take another look at `data/nextcloud.log`, `data/horde_imap.log` and `data/horde_smtp.log`.

**Comment by p-jo** [comment]
Ok I've done that now, the debug message  says that it creates the sent mailbox... And the only other error message I can find is the one from before. Or should I be looking for something else?

`{"reqId":"lfYV7kaZBfTD8KT60R9c","level":0,"time":"2020-04-02T16:42:57+00:00","remoteAddr":"213.65.166.149","user":"andreas","app":"mail","method":"POST","url":"/apps/mail/api/accounts/3/send","message":"creating sent mailbox","userAgent":"Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:74.0) Gecko/20100101 Firefox/74.0","version":"18.0.1.3","id":"5e8616115190d"}`

**Comment by ChristophWurst** [comment]
Could you remove the account from the app, delete the folder with another client and try again?

**Comment by p-jo** [comment]
Still the same error message. The log says that it creates the draft folder, but it doesn't happen. So the log messages looks like this:

```
Warning	mail	Horde_Imap_Client_Exception_ServerResponse: IMAP error reported by server.	
2020-04-08T18:43:01+0200
Debug	mail	creating sent mailbox	
2020-04-08T18:43:00+0200
Debug	mail	collecting 1 email addresses	
2020-04-08T18:43:00+0200
Debug	mail	Drafts mailbox created	
2020-04-08T18:42:59+0200
Debug	mail	Creating drafts mailbox	
2020-04-08T18:42:59+0200
Debug	mail	Drafts mailbox created	
2020-04-08T18:42:57+0200
Debug	mail	Creating drafts mailbox	
2020-04-08T18:42:57+0200
Debug	mail	Drafts mailbox created	
2020-04-08T18:42:51+0200
```

This is from the horde_imap log

```
>> Wed, 08 Apr 2020 16:42:59 +0000
>> Connection to: imap://mail.glesys.se:993/
>> Server connection took 0.0574 seconds.
S: * OK [CAPABILITY IMAP4rev1 LITERAL+ SASL-IR LOGIN-REFERRALS ID ENABLE IDLE STARTTLS AUTH=PLAIN AUTH=LOGIN] Dovecot ready.
C: 1 AUTHENTICATE PLAIN [INITIAL CLIENT RESPONSE (username: xxxxxxxx)]
S: 1 OK [CAPABILITY IMAP4rev1 LITERAL+ SASL-IR LOGIN-REFERRALS ID ENABLE IDLE SORT SORT=DISPLAY THREAD=REFERENCES THREAD=REFS THREAD=ORDEREDSUBJECT MULTIAPPEND URL-PARTIAL CATENATE UNSELECT CHILDREN NAMESPACE UIDPLUS LIST-EXTENDED I18NLEVEL=1 CONDSTORE QRESYNC ESEARCH ESORT SEARCHRES WITHIN CONTEXT=SEARCH LIST-STATUS BINARY MOVE SPECIAL-USE QUOTA] Logged in
>> Command 1 took 0.072 seconds.
>> CACHE: Using the OCA\Mail\Cache\Cache storage driver.
C: 2 ENABLE QRESYNC
C: 3 CREATE Drafts
S: * ENABLED QRESYNC
S: 2 OK Enabled (0.000 + 0.000 secs).
>> Command 2 took 0.0184 seconds.
S: 3 NO Client tried to access nonexistent namespace. (Mailbox name should probably be prefixed with: INBOX.) (0.000 + 0.000 secs).
>> Command 3 took 0.0355 seconds.
C: 4 LIST () "" (*) RETURN (SPECIAL-USE)
S: * LIST () "." INBOX
S: 4 OK List completed (0.000 + 0.000 secs).
>> Command 4 took 0.0186 seconds.
C: 5 STATUS INBOX (MESSAGES UIDNEXT UIDVALIDITY HIGHESTMODSEQ)
S: * STATUS INBOX (MESSAGES 0 UIDNEXT 1 UIDVALIDITY 1586363829 HIGHESTMODSEQ 1)
S: 5 OK Status completed (0.000 + 0.000 secs).
>> Command 5 took 0.0188 seconds.
C: 6 STATUS INBOX (MESSAGES UIDNEXT UIDVALIDITY HIGHESTMODSEQ)
S: * STATUS INBOX (MESSAGES 0 UIDNEXT 1 UIDVALIDITY 1586363829 HIGHESTMODSEQ 1)
S: 6 OK Status completed (0.000 + 0.000 secs).
>> Command 6 took 0.0189 seconds.
C: 7 STATUS INBOX (MESSAGES RECENT UIDNEXT UIDVALIDITY UNSEEN)
S: * STATUS INBOX (MESSAGES 0 RECENT 0 UIDNEXT 1 UIDVALIDITY 1586363829 UNSEEN 0)
S: 7 OK Status completed (0.000 + 0.000 secs).
>> Command 7 took 0.0189 seconds.
C: 8 LOGOUT
S: * BYE Logging out
S: 8 OK Logout completed (0.000 + 0.000 secs).
>> Command 8 took 0.0182 seconds.
------------------------------
>> Wed, 08 Apr 2020 16:43:00 +0000
>> Connection to: imap://mail.glesys.se:993/
>> Server connection took 0.0572 seconds.
S: * OK [CAPABILITY IMAP4rev1 LITERAL+ SASL-IR LOGIN-REFERRALS ID ENABLE IDLE STARTTLS AUTH=PLAIN AUTH=LOGIN] Dovecot ready.
C: 1 AUTHENTICATE PLAIN [INITIAL CLIENT RESPONSE (username: xxxxxx)]
S: 1 OK [CAPABILITY IMAP4rev1 LITERAL+ SASL-IR LOGIN-REFERRALS ID ENABLE IDLE SORT SORT=DISPLAY THREAD=REFERENCES THREAD=REFS THREAD=ORDEREDSUBJECT MULTIAPPEND URL-PARTIAL CATENATE UNSELECT CHILDREN NAMESPACE UIDPLUS LIST-EXTENDED I18NLEVEL=1 CONDSTORE QRESYNC ESEARCH ESORT SEARCHRES WITHIN CONTEXT=SEARCH LIST-STATUS BINARY MOVE SPECIAL-USE QUOTA] Logged in
>> Command 1 took 0.074 seconds.
>> CACHE: Using the OCA\Mail\Cache\Cache storage driver.
C: 2 ENABLE QRESYNC
C: 3 CREATE Sent
S: * ENABLED QRESYNC
S: 2 OK Enabled (0.000 + 0.000 secs).
>> Command 2 took 0.0183 seconds.
S: 3 NO Client tried to access nonexistent namespace. (Mailbox name should probably be prefixed with: INBOX.) (0.000 + 0.000 secs).
>> Command 3 took 0.0353 seconds.
C: 4 LIST () "" (*) RETURN (SPECIAL-USE)
S: * LIST () "." INBOX
S: 4 OK List completed (0.000 + 0.000 secs).
>> Command 4 took 0.0183 seconds.
C: 5 STATUS INBOX (MESSAGES UIDNEXT UIDVALIDITY HIGHESTMODSEQ)
S: * STATUS INBOX (MESSAGES 0 UIDNEXT 1 UIDVALIDITY 1586363829 HIGHESTMODSEQ 1)
S: 5 OK Status completed (0.000 + 0.000 secs).
>> Command 5 took 0.0188 seconds.
C: 6 STATUS INBOX (MESSAGES UIDNEXT UIDVALIDITY HIGHESTMODSEQ)
S: * STATUS INBOX (MESSAGES 0 UIDNEXT 1 UIDVALIDITY 1586363829 HIGHESTMODSEQ 1)
S: 6 OK Status completed (0.000 + 0.000 secs).
>> Command 6 took 0.0189 seconds.
C: 7 STATUS INBOX (MESSAGES RECENT UIDNEXT UIDVALIDITY UNSEEN)
S: * STATUS INBOX (MESSAGES 0 RECENT 0 UIDNEXT 1 UIDVALIDITY 1586363829 UNSEEN 0)
S: 7 OK Status completed (0.000 + 0.000 secs).
>> Command 7 took 0.0187 seconds.
C: 8 LOGOUT
S: * BYE Logging out
S: 8 OK Logout completed (0.000 + 0.000 secs).
>> Command 8 took 0.0192 seconds.
```

**Comment by ChristophWurst** [comment]
> but it doesn't happen

Huh. This *is* strange. Are you 100% sure these are the IMAP logs that correspond to the other logs? I don't see any path where the `createMailbox` call to Horde wouldn't send an IMAP command.

**Comment by p-jo** [comment]
Yes from what I can see, but I'm not sure which commands I'm looking for... Here is my log file, maybe you can find something else?

[horde_imap.log](https://github.com/nextcloud/mail/files/4456052/horde_imap.log)

**Comment by ChristophWurst** [comment]
```
C: 3 CREATE Sent
S: * ENABLED QRESYNC
S: 2 OK Enabled (0.000 + 0.000 secs).
>> Command 2 took 0.0182 seconds.
S: 3 NO Client tried to access nonexistent namespace. (Mailbox name should probably be prefixed with: INBOX.) (0.000 + 0.000 secs).
```

Bingo!

**Comment by ChristophWurst** [comment]
I guess the problem is that Horde does not necessarily check the result of the create.

**Comment by p-jo** [comment]
Great! So is there anything we could do now? Would be happy to sponsor a fix for this if possible?

**Comment by ChristophWurst** [comment]
> So is there anything we could do now?

Even if I have some ideas about fixes, I don't have time for this right now. So the easiest would be if you or someone else could look into the details and propose a fix.

> Would be happy to sponsor a fix for this if possible?

You *could* put a bounty on this ticket via bountysource. But in our experience that neither speeds up the time until someone picks it up (especially with this specific issue) nor can we, as employees of Nextcloud Gmbh, take the bounty if we fix the issue. We always put it back on another ticket so eventually the community can earn it. Hence there is no way to sponsor this except getting a Nextcloud enterprise subscrition with the groupware option. Then we can prioritize this on our roadmap. Hope this makes sense.

**Comment by p-jo** [comment]
Thanks for your help so far anyway!
