### ISSUE TITLE
Account creation failure

### ISSUE THREAD

**Issue by sjreilly1960** [nextcloud/mail#2853]
Hi,
I'm running Mail 1.1.4 on Nextcloud 18.0.3, fully patched Ubuntu 18.04.4 LTS.
After the most recent update to Mail I was unable to use the app as it would fail to connect to my home server.
I have deleted the account in Mail and I'm unable to create an account as I get the message "Creating account failed: Error connecting to mail server"
I just confirmed my config/creds by setting up Thunderbird on another PC to my server and it worked.

**Comment by ChristophWurst** [comment]
see the changelog for the changes https://github.com/nextcloud/mail/releases/tag/v1.1.4

for support topics use https://help.nextcloud.com/ and for bug reports the bug report template

**Comment by sjreilly1960** [comment]
Perfect!! Thanks for the quick response.
Steve
