### ISSUE TITLE
Error to add new account in Mail App 1.1.4 in Nextcloud 18

### ISSUE THREAD

**Issue by box18box** [nextcloud/mail#2869]
### Question
I have the same problem in Nextcloud 18 to add a new account in Mail App 1.1.4. My server use STARTTLS The error is: "Creating account failed: Could not open secure TLS connection to the IMAP server." The error in logging: Fatal | mail | Creating account failed: Could not open secure TLS connection to the IMAP server"

**Comment by pamapa** [comment]
have you tried what is written in the release notes https://github.com/nextcloud/mail/releases/tag/v1.1.4:

Security: verify TLS host by default. This can be a breaking change for self-hosted servers. If you want to return to the old insecure behavior, set `app.mail.verify-tls-peer` to `false` in `config.php`.

**Comment by box18box** [comment]
Yes, it works after adding 'app.mail.verify-tls-peer' => false, 
Thank you.

**Comment by matejak** [comment]
Is this issue supposed to apply also to servers that use Let's Encrypt certificates? I had it as well, and the fix here helped. I am not sure whether my setup is worked, or the issuer is simply not trusted by default.

**Comment by ChristophWurst** [comment]
If the system can verify the cert from the certificate chain I guess it's fine with LE. It depends on your setup.

Closing as the question is answered. Please use https://help.nextcloud.com/ next time as we noted in the issue template you've used to open this ticket.
