### ISSUE TITLE
MAIL 0.6.2

### ISSUE THREAD

**Issue by cheesewizz** [nextcloud/mail#287]
### Steps to reproduce
1. Reply Button
2.
3.

### Expected behaviour
Tell us what should happen
Unable to click Reply button

### Actual behaviour
Tell us what happens instead
Reply button not working cannot click

### Mail app

**Mail app version:** (see apps admin page)

**Mailserver or service:** (e.g. Outlook, Yahoo, Gmail, Exchange,...)

**Transport security - IMAP:** (None, SSL, TLS, STARTTLS) 

**Transport security - SMTP:** (None, SSL, TLS, STARTTLS)

**Number of accounts:**

**Mail app version build date:** (only if you are using a Nightly Build)

### Server configuration
**Operating system**:
Centos 7
**Web server:**
Apache
**Database:**
MariaDB
**PHP version:**
5.6w
**Version:** (see admin page)

**Updated from an older version or fresh install:**
Fresh
**List of activated apps:**

```
If you have access to your command line run e.g.:
sudo -u www-data php occ app:list
from within your server installation folder
```

**The content of config/config.php:**

<details>
```
If you have access to your command line run e.g.:
sudo -u www-data php occ config:list system
from within your server installation folder

activity     contacts              files                   files_sharing      logreader                previewgenerator  templateeditor         workflowengine
admin_audit  dav                   files_accesscontrol     files_texteditor   lookup_server_connector  provisioning_api  theming
apporder     direct_menu           files_automatedtagging  files_trashbin     mail                     serverinfo        twofactor_backupcodes
audioplayer  encryption            files_downloadactivity  files_versions     nextcloud_announcements  sharebymail       updatenotification
bookmarks    external              files_external          files_videoplayer  notes                    survey_client     user_external
calendar     federatedfilesharing  files_pdfviewer         firstrunwizard     notifications            systemtags        user_ldap
comments     federation            files_retention         gallery            password_policy          tasks             user_saml


or 

Insert your config.php content here
(Without the database password, passwordsalt and secret)
```
<?php
$CONFIG = array (
  'instanceid' => 'ocvd7lc4nr62',
  'passwordsalt' => 'nUEbyW14RIz9+2zeBVtW5EqAf7acaL',
  'secret' => 'gHB2p11Ccyb4ZljbhOciF0UKwXi8pU992mal+Qho3f/SKZbz',
  'trusted_domains' =>
  array (
    0 => 'nextcloud200.tailinsubic.com',
  ),
  'datadirectory' => '/var/www/html/nextcloud/data',
  'overwrite.cli.url' => 'http://nextcloud200.localhost.com',
  'dbtype' => 'mysql',
  'version' => '11.0.0.10',
  'dbname' => 'db_nextcloud_test',
  'dbhost' => 'localhost',
  'dbport' => '',
  'dbtableprefix' => 'oc_',
  'dbuser' => 'oc_adminroot',
  'dbpassword' => 'h5szU+JqNQ9ByQVOsIcrc7WYmFj+IT',
  'logtimezone' => 'UTC',
  'installed' => true,
  'mail_smtpmode' => 'smtp',
  'mail_from_address' => 'xxxx',
  'mail_domain' => 'localhost.php',
  'mail_smtpauth' => 1,
  'mail_smtphost' => 'mx.localhost.php',
  'mail_smtpport' => '25',
  'mail_smtpname' => 'xxxx',
  'mail_smtppassword' => 'xxxx',
  'updater.release.channel' => 'stable',
  'mail_smtpauthtype' => 'LOGIN',
);

</details>

#### Client configuration
**Browser:**

**Operating system:**

##### Web server error log
```
Insert your webserver log here
```

##### Server log (data/nextcloud.log)
<details>
```
Insert your server log here
```
</details>

##### Horde IMAP log (data/horde_imap.log)
<details>
```
Insert your horde IMAP log here, see https://github.com/nextcloud/mail#debug-mode
```
</details>

##### Horde SMTP log (data/horde_smtp.log)
<details>
```
Insert your horde SMTP log here, see https://github.com/nextcloud/mail#debug-mode
```
</details>

##### Browser log
<details>
```
Insert your browser log here, this could for example include:

a) The javascript console log
b) The network log 
c) ...
```
</details>

**Comment by cheesewizz** [comment]
Hello

No idea if its a BUG, can i download previous version lower than 6.

thanks

**Comment by ChristophWurst** [comment]
Hey @cheesewizz,

did you try to click into the reply textarea and type something? The button should get enabled then

**Comment by cheesewizz** [comment]
Hello ChristophWurst

Hahaha its my mistake Yes you are correct the button is disabled when your not typing any text at the body message, when I type any text the button get enabled.


Thanks

**Comment by ChristophWurst** [comment]
Great to hear that :-)
