### ISSUE TITLE
Address input design issues

### ISSUE THREAD

**Issue by jancborchardt** [nextcloud/mail#2875]
The "To" and "Cc/Bcc" fields have some UX issues when compared to other mail apps:

- [ ] You should not need to click into the dropdown to have the email you put in accepted. The dropdown is for suggestions, not the reflection of the list.
- [ ] When you have content in the "to" field and click in it, the dropdown shows but the content vanishes from the field, very strange.
- [ ] Just putting in emails separated by comma should work, but now it seems to error as the app thinks it’s all one email
- [ ] When you have nothing in the field, it doesn’t make sense to show the dropdown at all

Probably more – any input @nextcloud/mail?

**Comment by ChristophWurst** [comment]
Could you move this into https://github.com/nextcloud/mail/issues/2769?

**Comment by jancborchardt** [comment]
Seems like it will be confusing and get lost in the already long issue, but moved it there → closing.
