### ISSUE TITLE
add a "refresh imap folder" button

### ISSUE THREAD

**Issue by szaimen** [nextcloud/mail#2890]
### Feature Request

Please add a "refresh imap folder" button.

#### Summary

That button would be really nice since the "r" button is not really discoverable and would solve many issues after caching.

The button could sit on the right of the "New message" buton (I would then make the "New message" button a bit smaller)

**Comment by ChristophWurst** [comment]
@jancborchardt for the design part :)

**Comment by jancborchardt** [comment]
> The button could sit on the right of the "New message" buton (I would then make the "New message" button a bit smaller)

As soon as we move the "New message" button to the top of the message list as specified at https://github.com/nextcloud/server/issues/16934#issuecomment-542201187 we can do that, yes. :)
