### ISSUE TITLE
Provisioned profiles do not list account contents but also show no errors

### ISSUE THREAD

**Issue by b52** [nextcloud/mail#2896]
### Expected behavior

As I consider the "provisioned profiles" being the replacement for the [automatic account creation](https://github.com/nextcloud/mail/commit/ad29c8a46cc0bc6e783e82cc81ea5c701c66fb98#diff-375419274b7e27e069f6e9ed73ccffa9), I assumed this would work right out of the box when I specify the options in the admin interface and run it.

### Actual behavior

I see that an account is being created, since I have that account when I visit the mail app, but it is simply empty.

When I check the mail server logs, I see a lot of "`imap-login: Disconnected (no auth attempts in 0 secs)`" messages.

My previous working configuration in the `config.php` was:
```
'app.mail.accounts.default' => array(
  'email' => '%EMAIL%',
  'imapHost' => 'localhost',
  'imapPort' => 993,
  'imapSslMode' => 'ssl',
  'smtpHost' => 'localhost',
  'smtpPort' => 587,
  'smtpSslMode' => 'tls',
)
```

### Mail app

**Mail app version:** 1.1.4

**Mailserver or service:** dovecot

### Server configuration

**Operating system**: Debian 10
**Web server:** nginx
**Database:** MariaDB
**PHP version:** 7.3

**Nextcloud Version:** 18.0.3

#### Client configuration
**Browser:** Firefox latest
**Operating system:** Win10

**Comment by ChristophWurst** [comment]
> but it is simply empty.

What does empty mean? Does it show a ! next to the email address?

**Comment by b52** [comment]
Yeah, there is a `!` on the left hand side of the email address. However, no additional information is shown.

**Comment by ChristophWurst** [comment]
> Yeah, there is a `!` on the left hand side of the email address. However, no additional information is shown.

Then check your nextcloud.log. The error is written there.

**Comment by b52** [comment]
See the log below. I had to manually copy half of the message as the built-in copy mechanism did not copy the whole two-part message.

```
[mail] Fatal: OCA\Mail\Exception\ServiceException: IMAP errorError connecting to mail server. at <<closure>>

0. /var/www/nextcloud/apps/mail/lib/Service/MailManager.php line 102
   OCA\Mail\IMAP\MailboxSync->sync(OCA\Mail\Account {})
1. /var/www/nextcloud/apps/mail/lib/Controller/PageController.php line 119
   OCA\Mail\Service\MailManager->getFolders(OCA\Mail\Account {})
2. /var/www/nextcloud/lib/private/AppFramework/Http/Dispatcher.php line 170
   OCA\Mail\Controller\PageController->index()
3. /var/www/nextcloud/lib/private/AppFramework/Http/Dispatcher.php line 99
   OC\AppFramework\Http\Dispatcher->executeController(OCA\Mail\Controller\PageController {}, "index")
4. /var/www/nextcloud/lib/private/AppFramework/App.php line 125
   OC\AppFramework\Http\Dispatcher->dispatch(OCA\Mail\Controller\PageController {}, "index")
5. /var/www/nextcloud/lib/private/AppFramework/Routing/RouteActionHandler.php line 47
   OC\AppFramework\App::main("OCA\\Mail\\Controller\\PageController", "index", OC\AppFramework\ ... {}, {_route: "mail.page.index"})
6. <<closure>>
   OC\AppFramework\Routing\RouteActionHandler->__invoke({_route: "mail.page.index"})
7. /var/www/nextcloud/lib/private/Route/Router.php line 299
   call_user_func(OC\AppFramework\ ... {}, {_route: "mail.page.index"})
8. /var/www/nextcloud/lib/base.php line 1008
   OC\Route\Router->match("/apps/mail/")
9. /var/www/nextcloud/index.php line 38
   OC::handleRequest()

Verursacht durchHorde_Imap_Client_Exception: Error connecting to mail server.

    /var/www/nextcloud/apps/mail/vendor/pear-pear.horde.org/Horde_Imap_Client/Horde/Imap/Client/Socket.php - line 375:

    Horde_Imap_Client_Socket->_connect()

    /var/www/nextcloud/apps/mail/vendor/pear-pear.horde.org/Horde_Imap_Client/Horde/Imap/Client/Base.php - line 838:

    Horde_Imap_Client_Socket->_login("*** sensiti ... *")

    /var/www/nextcloud/apps/mail/vendor/pear-pear.horde.org/Horde_Imap_Client/Horde/Imap/Client/Base.php - line 1389:

    Horde_Imap_Client_Base->login("*** sensiti ... *")

    /var/www/nextcloud/apps/mail/lib/IMAP/FolderMapper.php - line 60:

    Horde_Imap_Client_Base->listMailboxes("*", 4, { delimiter: ... e})

    /var/www/nextcloud/apps/mail/lib/IMAP/MailboxSync.php - line 85:

    OCA\Mail\IMAP\FolderMapper->getFolders(OCA\Mail\Account {}, Horde_Imap_C ... e})

    /var/www/nextcloud/apps/mail/lib/Service/MailManager.php - line 102:

    OCA\Mail\IMAP\MailboxSync->sync(OCA\Mail\Account {})

    /var/www/nextcloud/apps/mail/lib/Controller/PageController.php - line 119:

    OCA\Mail\Service\MailManager->getFolders(OCA\Mail\Account {})

    /var/www/nextcloud/lib/private/AppFramework/Http/Dispatcher.php - line 170:

    OCA\Mail\Controller\PageController->index()

    /var/www/nextcloud/lib/private/AppFramework/Http/Dispatcher.php - line 99:

    OC\AppFramework\Http\Dispatcher->executeController(OCA\Mail\Con ... {}, "index")

    /var/www/nextcloud/lib/private/AppFramework/App.php - line 125:

    OC\AppFramework\Http\Dispatcher->dispatch(OCA\Mail\Con ... {}, "index")

    /var/www/nextcloud/lib/private/AppFramework/Routing/RouteActionHandler.php - line 47:

    OC\AppFramework\App::main("OCA\\Mail\\ ... r", "index", OC\AppFramew ... {}, { _route: "mail.page.index"})

    <<closure>>

    OC\AppFramework\Routing\RouteActionHandler->__invoke({ _route: "mail.page.index"})

    /var/www/nextcloud/lib/private/Route/Router.php - line 299:

    call_user_func(OC\AppFramew ... {}, { _route: "mail.page.index"})

    /var/www/nextcloud/lib/base.php - line 1008:

    OC\Route\Router->match("/apps/mail/")

    /var/www/nextcloud/index.php - line 38:

    OC::handleRequest()

```

**Comment by ChristophWurst** [comment]
>  I had to manually copy half of the message as the built-in copy mechanism did not copy the whole two-part message.

You can also just get the line from `data/nextcloud.log`.

"Error connecting to mail server" does not tell me the exact reason for the connection failure. But it sounds like the host is either not reachabe, or it's the wrong or a blocked port. Could you look into that?

**Comment by b52** [comment]
The values being used are exactly the ones I used with the old configuration approach. Furthermore, I do so connection attempts at `dovecot`.

**Comment by ChristophWurst** [comment]
Then I can only assume that this is about failing TLS verification. See https://github.com/nextcloud/mail/releases/tag/v1.1.4.

**Comment by b52** [comment]
Indeed, it seems it was related to the TLS verification. When I use the domain associated with the mail server instead of `127.0.0.1` the connection works and I can access the mails.

Maybe it would make sense to catch the exception (see above) and handle it properly by logging a related error message? I guess it is expected behavior for some servers to run into this so it is not really an exception but a legitimate error case. Similar to server not reachable, in which case I also would not expect to see exception logs as this is a common error case.

**Comment by ChristophWurst** [comment]
See https://github.com/nextcloud/mail/issues/3006
