### ISSUE TITLE
Returning to folder after having searched not possible without refresh

### ISSUE THREAD

**Issue by jancborchardt** [nextcloud/mail#290]
1. Open any folder
2. Search a term
3. Try going back to the non-filtered folder, either by clicking on the folder again in the navigation, or clicking the X on the search field (in Chrome at least where they have that)

Expectation: The normal folder opens.

But actually, only the search results load again. Even when you click on another folder and then return to the first one it doesn’t work. Only a page refresh solves the issue. Regression as far as I know since this used to work.

cc @nextcloud/mail

**Comment by ChristophWurst** [comment]
I *think* this should be fixed by #326. Please check.

**Comment by ChristophWurst** [comment]
Indeed, this will be fixed by merging #326 🚀 

On that PR's branch you can return to the unfiltered folder by clicking it in the sidebar.

**Comment by ChristophWurst** [comment]
> Indeed, this will be fixed by merging #326 🚀

Closing this ticket now.
