### ISSUE TITLE
Mail Close button 

### ISSUE THREAD

**Issue by cheesewizz** [nextcloud/mail#291]
### Steps to reproduce
1. Click Mail
2. Click Compose or Reply existing message
3. Click Attachment button

### Expected behaviour
Tell us what should happen
After I click attachment the dialog box appeared and the close button its hard to click

### Actual behaviour
Tell us what happens instead
After the dialog box appeared the close button should be visible no overlapping any text

### Mail app

**Mail app version:** (see apps admin page)
0.6.2

**Mailserver or service:** (e.g. Outlook, Yahoo, Gmail, Exchange,...)
Postfix Mail Server

**Transport security - IMAP:** (None, SSL, TLS, STARTTLS) 
IMAP (none)
**Transport security - SMTP:** (None, SSL, TLS, STARTTLS)
SMTP (None)

**Number of accounts:**
I have 25 Active users

**Mail app version build date:** (only if you are using a Nightly Build)

### Server configuration
**Operating system**:
Centos 7
**Web server:**
Apache version 2.4.6 
**Database:**
MariaDB version 5.5.52
**PHP version:**
5.6.29
**Version:** (see admin page)
11.0.6
**Updated from an older version or fresh install:**
Fresh Install

**List of activated apps:**
Enabled:
  - activity: 2.4.1
  - admin_audit: 1.1.0
  - apporder: 0.3.3
  - calendar: 1.5.0
  - comments: 1.1.0
  - contacts: 1.5.2
  - dav: 1.1.1
  - direct_menu: 0.10.0
  - external: true
  - federatedfilesharing: 1.1.1
  - federation: 1.1.1
  - files: 1.6.1
  - files_accesscontrol: 1.1.2
  - files_automatedtagging: 1.1.1
  - files_clipboard: 0.5.0
  - files_downloadactivity: 1.0.0
  - files_external: 1.1.2
  - files_pdfviewer: 1.0.1
  - files_retention: 1.0.1
  - files_sharing: 1.1.1
  - files_texteditor: 2.2
  - files_trashbin: 1.1.0
  - files_versions: 1.4.0
  - files_videoplayer: 1.0.0
  - firstrunwizard: 2.0
  - gallery: 16.0.0
  - logreader: 2.0.0
  - lookup_server_connector: 1.0.0
  - mail: 0.6.2
  - nextcloud_announcements: 1.0
  - notifications: 1.0.1
  - password_policy: 1.1.0
  - previewgenerator: 1.0.1
  - provisioning_api: 1.1.0
  - serverinfo: 1.1.1
  - sharebymail: 1.0.1
  - survey_client: 0.1.5
  - systemtags: 1.1.3
  - templateeditor: 0.2
  - theming: 1.1.1
  - twofactor_backupcodes: 1.0.0
  - updatenotification: 1.1.1
  - user_external: 0.4
  - workflowengine: 1.1.1
Disabled:
  - encryption
  - files_markdown
  - notes
  - user_ldap
  - user_saml

```
If you have access to your command line run e.g.:
sudo -u www-data php occ app:list
from within your server installation folder
```

**The content of config/config.php:**

<details>
```
If you have access to your command line run e.g.:
sudo -u www-data php occ config:list system
from within your server installation folder

or 

Insert your config.php content here
(Without the database password, passwordsalt and secret)
```
</details>

<?php
$CONFIG = array (
  'instanceid' => 'ocnvab58cfem',
  'passwordsalt' => 'Pw0J3rnz3M3Gk1WkUdB9uzV8BKZGMm',
  'secret' => 'II3reh7dRB62zgfjh+I1I/LcPeMDy48dSv9019a8892Kptoo',
  'trusted_domains' =>
  array (
    0 => 'cloud.localhost.com',
  ),
  'datadirectory' => '/home/data',
  'overwrite.cli.url' => 'http://cloud.localhost.com',
  'dbtype' => 'mysql',
  'version' => '11.0.1.2',
  'dbname' => 'database_cloud',
  'dbhost' => 'localhost',
  'dbport' => '',
  'dbtableprefix' => 'oc_',
  'dbuser' => 'root',
  'dbpassword' => 'secret',
  'logtimezone' => 'UTC',
  'installed' => true,
  'mail_smtpmode' => 'smtp',
  'mail_from_address' => 'server1',
  'mail_domain' => 'localhost.php',
  'mail_smtpauthtype' => 'LOGIN',
  'mail_smtpauth' => 1,
  'mail_smtphost' => 'mx.localhost.php',
  'mail_smtpport' => '25',
  'mail_smtpname' => 'mail',
  'mail_smtppassword' => 'secret',
  'theme' => '',
  'loglevel' => 2,
  'maintenance' => false,
);

#### Client configuration
**Browser:**

Mozillw Firefox and Chrome

**Operating system:**
Ubuntu, Xubuntu
Windows 7, 8, 10

##### Web server error log
```
Insert your webserver log here
```

##### Server log (data/nextcloud.log)
<details>
```
Insert your server log here
```
</details>

##### Horde IMAP log (data/horde_imap.log)
<details>
```
Insert your horde IMAP log here, see https://github.com/nextcloud/mail#debug-mode
```
</details>

##### Horde SMTP log (data/horde_smtp.log)
<details>
```
Insert your horde SMTP log here, see https://github.com/nextcloud/mail#debug-mode
```
</details>

##### Browser log
<details>
```
Insert your browser log here, this could for example include:

a) The javascript console log
b) The network log 
c) ...
```
</details>

**Comment by cheesewizz** [comment]
![error button](https://cloud.githubusercontent.com/assets/14123082/22088877/39713e56-de22-11e6-9f45-cd4b208d659e.png)

**Comment by ChristophWurst** [comment]
dup of https://github.com/nextcloud/mail/issues/269 :-)
