### ISSUE TITLE
Loading messages takes "forever" since upgrade to 1.3.0

### ISSUE THREAD

**Issue by loppanloppis** [nextcloud/mail#2910]
### Expected behavior
My e-mails should load and show

### Actual behavior
It seems stuck on "Loading Messages. Indexing your messages. This can take a bit longer for larger mailboxes."

### Mail app

**Mail app version:** 1.3.0

**Mailserver or service:** one.com (IMAP)

### Server configuration

**Operating system**: Ubuntu 18.04

**Web server:** Apache

**Database:** MariaDB

**PHP version:** 7.2.24

**Nextcloud Version:** 18.0.3

#### Client configuration
**Browser:** Chromium 79.0.3945.130

**Operating system:** Ubuntu 18.04

Hi, I'm fairly sure this issue is not identical to #2909 or #2908. Please excuse me if it is.

I'd like to mention that this e-mail account holds a few GB so I except it would take time to index, but the errors give me hints that it's not indexing at all :

[mail] Error: OCA\Mail\Exception\ServiceException: Sync failed:  at <<closure>>

0. /var/www/nextcloud/apps/mail/lib/Service/Sync/SyncService.php line 107
   OCA\Mail\Service\Sync\ImapToDbSynchronizer->sync(OCA\Mail\Account {}, OCA\Mail\Db\Mailbox {id: 118}, 42, [], true)
1. /var/www/nextcloud/apps/mail/lib/Controller/FoldersController.php line 131
   OCA\Mail\Service\Sync\SyncService->syncMailbox(OCA\Mail\Account {}, "INBOX", 42, [], false, null)
2. /var/www/nextcloud/lib/private/AppFramework/Http/Dispatcher.php line 170
   OCA\Mail\Controller\FoldersController->sync(4, "SU5CT1g=", [], true, null)
3. /var/www/nextcloud/lib/private/AppFramework/Http/Dispatcher.php line 99
   OC\AppFramework\Http\Dispatcher->executeController(OCA\Mail\Controller\FoldersController {}, "sync")
4. /var/www/nextcloud/lib/private/AppFramework/App.php line 125
   OC\AppFramework\Http\Dispatcher->dispatch(OCA\Mail\Controller\FoldersController {}, "sync")
5. /var/www/nextcloud/lib/private/AppFramework/Routing/RouteActionHandler.php line 47
   OC\AppFramework\App::main("OCA\\Mail\\Cont ... r", "sync", OC\AppFramework\ ... {}, {accountId: "4", ... "})
6. <<closure>>
   OC\AppFramework\Routing\RouteActionHandler->__invoke({accountId: "4", ... "})
7. /var/www/nextcloud/lib/private/Route/Router.php line 299
   call_user_func(OC\AppFramework\ ... {}, {accountId: "4", ... "})
8. /var/www/nextcloud/lib/base.php line 1008
   OC\Route\Router->match("/apps/mail/api/ ... c")
9. /var/www/nextcloud/index.php line 38
   OC::handleRequest()

POST /index.php/apps/mail/api/accounts/4/folders/SU5CT1g%3D/sync
from 85.226.167.78 by peterlondon at 2020-04-15T21:44:20+00:00

From nextcloud.log the error looks like this :

`{"reqId":"9cHCMDgOJbSI3Cuznv0H","level":3,"time":"2020-04-15T21:33:37+00:00","remoteAddr":"85.226.167.78","user":"peterlondon","app":"mail","method":"POST","url":"/index.php/apps/mail/api/accounts/4/folders/SU5CT1g%3D/sync","message":{"Exception":"OCA\\Mail\\Exception\\ServiceException","Message":"Sync failed: ","Code":0,"Trace":[{"file":"/var/www/nextcloud/apps/mail/lib/Service/Sync/SyncService.php","line":107,"function":"sync","class":"OCA\\Mail\\Service\\Sync\\ImapToDbSynchronizer","type":"->","args":[{"__class__":"OCA\\Mail\\Account"},{"id":118,"__class__":"OCA\\Mail\\Db\\Mailbox"},42,[],true]},{"file":"/var/www/nextcloud/apps/mail/lib/Controller/FoldersController.php","line":131,"function":"syncMailbox","class":"OCA\\Mail\\Service\\Sync\\SyncService","type":"->","args":[{"__class__":"OCA\\Mail\\Account"},"INBOX",42,[],false,null]},{"file":"/var/www/nextcloud/lib/private/AppFramework/Http/Dispatcher.php","line":170,"function":"sync","class":"OCA\\Mail\\Controller\\FoldersController","type":"->","args":[4,"SU5CT1g=",[],true,null]},{"file":"/var/www/nextcloud/lib/private/AppFramework/Http/Dispatcher.php","line":99,"function":"executeController","class":"OC\\AppFramework\\Http\\Dispatcher","type":"->","args":[{"__class__":"OCA\\Mail\\Controller\\FoldersController"},"sync"]},{"file":"/var/www/nextcloud/lib/private/AppFramework/App.php","line":125,"function":"dispatch","class":"OC\\AppFramework\\Http\\Dispatcher","type":"->","args":[{"__class__":"OCA\\Mail\\Controller\\FoldersController"},"sync"]},{"file":"/var/www/nextcloud/lib/private/AppFramework/Routing/RouteActionHandler.php","line":47,"function":"main","class":"OC\\AppFramework\\App","type":"::","args":["OCA\\Mail\\Controller\\FoldersController","sync",{"__class__":"OC\\AppFramework\\DependencyInjection\\DIContainer"},{"accountId":"4","folderId":"SU5CT1g=","_route":"mail.folders.sync"}]},{"function":"__invoke","class":"OC\\AppFramework\\Routing\\RouteActionHandler","type":"->","args":[{"accountId":"4","folderId":"SU5CT1g=","_route":"mail.folders.sync"}]},{"file":"/var/www/nextcloud/lib/private/Route/Router.php","line":299,"function":"call_user_func","args":[{"__class__":"OC\\AppFramework\\Routing\\RouteActionHandler"},{"accountId":"4","folderId":"SU5CT1g=","_route":"mail.folders.sync"}]},{"file":"/var/www/nextcloud/lib/base.php","line":1008,"function":"match","class":"OC\\Route\\Router","type":"->","args":["/apps/mail/api/accounts/4/folders/SU5CT1g%3D/sync"]},{"file":"/var/www/nextcloud/index.php","line":38,"function":"handleRequest","class":"OC","type":"::","args":[]}],"File":"/var/www/nextcloud/apps/mail/lib/Service/Sync/ImapToDbSynchronizer.php","Line":151,"Previous":{"Exception":"OCA\\Mail\\Exception\\IncompleteSyncException","Message":"","Code":0,"Trace":[{"file":"/var/www/nextcloud/apps/mail/lib/Service/Sync/ImapToDbSynchronizer.php","line":146,"function":"runInitialSync","class":"OCA\\Mail\\Service\\Sync\\ImapToDbSynchronizer","type":"->","args":[{"__class__":"OCA\\Mail\\Account"},{"id":118,"__class__":"OCA\\Mail\\Db\\Mailbox"}]},{"file":"/var/www/nextcloud/apps/mail/lib/Service/Sync/SyncService.php","line":107,"function":"sync","class":"OCA\\Mail\\Service\\Sync\\ImapToDbSynchronizer","type":"->","args":[{"__class__":"OCA\\Mail\\Account"},{"id":118,"__class__":"OCA\\Mail\\Db\\Mailbox"},42,[],true]},{"file":"/var/www/nextcloud/apps/mail/lib/Controller/FoldersController.php","line":131,"function":"syncMailbox","class":"OCA\\Mail\\Service\\Sync\\SyncService","type":"->","args":[{"__class__":"OCA\\Mail\\Account"},"INBOX",42,[],false,null]},{"file":"/var/www/nextcloud/lib/private/AppFramework/Http/Dispatcher.php","line":170,"function":"sync","class":"OCA\\Mail\\Controller\\FoldersController","type":"->","args":[4,"SU5CT1g=",[],true,null]},{"file":"/var/www/nextcloud/lib/private/AppFramework/Http/Dispatcher.php","line":99,"function":"executeController","class":"OC\\AppFramework\\Http\\Dispatcher","type":"->","args":[{"__class__":"OCA\\Mail\\Controller\\FoldersController"},"sync"]},{"file":"/var/www/nextcloud/lib/private/AppFramework/App.php","line":125,"function":"dispatch","class":"OC\\AppFramework\\Http\\Dispatcher","type":"->","args":[{"__class__":"OCA\\Mail\\Controller\\FoldersController"},"sync"]},{"file":"/var/www/nextcloud/lib/private/AppFramework/Routing/RouteActionHandler.php","line":47,"function":"main","class":"OC\\AppFramework\\App","type":"::","args":["OCA\\Mail\\Controller\\FoldersController","sync",{"__class__":"OC\\AppFramework\\DependencyInjection\\DIContainer"},{"accountId":"4","folderId":"SU5CT1g=","_route":"mail.folders.sync"}]},{"function":"__invoke","class":"OC\\AppFramework\\Routing\\RouteActionHandler","type":"->","args":[{"accountId":"4","folderId":"SU5CT1g=","_route":"mail.folders.sync"}]},{"file":"/var/www/nextcloud/lib/private/Route/Router.php","line":299,"function":"call_user_func","args":[{"__class__":"OC\\AppFramework\\Routing\\RouteActionHandler"},{"accountId":"4","folderId":"SU5CT1g=","_route":"mail.folders.sync"}]},{"file":"/var/www/nextcloud/lib/base.php","line":1008,"function":"match","class":"OC\\Route\\Router","type":"->","args":["/apps/mail/api/accounts/4/folders/SU5CT1g%3D/sync"]},{"file":"/var/www/nextcloud/index.php","line":38,"function":"handleRequest","class":"OC","type":"::","args":[]}],"File":"/var/www/nextcloud/apps/mail/lib/Service/Sync/ImapToDbSynchronizer.php","Line":192},"CustomMessage":"--"},"userAgent":"Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/79.0.3945.130 Safari/537.36","version":"18.0.3.0"}`

Tried changing to debug mode in config.php to get more info but once I do it spits out such a crazy amount of entries from all my other apps and it's difficult to navigate through. So I hope the info above is enough.

I believe the credentials are correct because I don't see nextcloud mail complaining about that?

I have another, very small account, that sync just fine, on another server though (my own).

Please let me know if there's any other info I can provide and I'll be glad to.

Thanks!

Best

Peter

**Comment by rmkeen** [comment]
Identical setup here and error logs look the same. Was working this morning until I updated  to 1.3.  Makes the connection and some folders sync, but inbox does not. It gets an accurate count of messages for the inbox. Eventually comes up with 'Could not open mailbox'.

I have another instance running on a Centos 7 server syncing to the same mailbox but I haven't attempted to update that one.

**Comment by schu-r** [comment]
Same Here 

### Steps to reproduce
Open Mail Account


### Expected behaviour
See all Mails

### Actual behaviour
Tries to sync Mails but does not finish


## Server configuration detail

**Operating system:** Linux 4.9.0-11-amd64 #1 SMP Debian 4.9.189-3+deb9u2 (2019-11-11) x86_64

**Webserver:** Apache/2.4.25 (Debian) (apache2handler)

**Database:** mysql 10.1.44

**PHP version:** 

7.4.2
Modules loaded: Core, date, libxml, openssl, pcre, zlib, filter, hash, Reflection, SPL, session, standard, sodium, apache2handler, mysqlnd, PDO, xml, apcu, calendar, ctype, curl, dom, enchant, mbstring, FFI, fileinfo, ftp, gd, gettext, iconv, igbinary, imagick, imap, intl, json, exif, memcache, mysqli, pdo_mysql, pdo_sqlite, apc, posix, readline, redis, shmop, SimpleXML, sockets, sqlite3, sysvmsg, sysvsem, sysvshm, tokenizer, xmlreader, xmlrpc, xmlwriter, xsl, zip, Phar, Zend OPcache

**Nextcloud version:** 18.0.3 - 18.0.3.0

**Updated from an older Nextcloud/ownCloud or fresh install:** from 16.x updated every time

**Where did you install Nextcloud from:** unknown

<details><summary>Signing status</summary>

Array
(
)

</details>

<details><summary>List of activated apps</summary>

```
Enabled:
 - accessibility: 1.4.0
 - activity: 2.11.0
 - audioplayer: 2.10.0
 - audioplayer_editor: 0.2.2
 - breezedark: 18.0.11
 - calendar: 2.0.3
 - cloud_federation_api: 1.1.0
 - comments: 1.8.0
 - contacts: 3.2.0
 - dav: 1.14.0
 - deck: 0.8.2
 - documentserver_community: 0.1.5
 - event_update_notification: 1.0.1
 - federatedfilesharing: 1.8.0
 - federation: 1.8.0
 - files: 1.13.1
 - files_automatedtagging: 1.8.2
 - files_pdfviewer: 1.7.0
 - files_rightclick: 0.15.2
 - files_sharing: 1.10.1
 - files_trashbin: 1.8.0
 - files_versions: 1.11.0
 - files_videoplayer: 1.7.0
 - firstrunwizard: 2.7.0
 - impersonate: 1.5.0
 - issuetemplate: 0.6.0
 - logreader: 2.3.0
 - lookup_server_connector: 1.6.0
 - mail: 1.3.0
 - maps: 0.1.6
 - metadata: 0.11.1
 - nextcloud_announcements: 1.7.0
 - notifications: 2.6.0
 - oauth2: 1.6.0
 - onlyoffice: 4.1.4
 - password_policy: 1.8.0
 - photos: 1.0.0
 - piwik: 0.5.4
 - polls: 1.3.0
 - privacy: 1.2.0
 - provisioning_api: 1.8.0
 - radio: 0.6.6
 - recommendations: 0.6.0
 - serverinfo: 1.8.0
 - settings: 1.0.0
 - sharebymail: 1.8.0
 - spreed: 8.0.7
 - support: 1.1.0
 - systemtags: 1.8.0
 - tasks: 0.12.1
 - text: 2.0.0
 - theming: 1.9.0
 - theming_customcss: 1.5.0
 - twofactor_backupcodes: 1.7.0
 - updatenotification: 1.8.0
 - viewer: 1.2.0
 - workflow_pdf_converter: 1.3.1
 - workflowengine: 2.0.0
Disabled:
 - admin_audit
 - encryption
 - files_external
 - survey_client
 - user_ldap

```
</details>

<details><summary>Configuration (config/config.php)</summary>

```
{
    "instanceid": "***REMOVED SENSITIVE VALUE***",
    "passwordsalt": "***REMOVED SENSITIVE VALUE***",
    "secret": "***REMOVED SENSITIVE VALUE***",
    "trusted_domains": [
        "it-open.at",
        "jenkins.it-open.at"
    ],
    "datadirectory": "***REMOVED SENSITIVE VALUE***",
    "memcache.local": "\\OC\\Memcache\\APCu",
    "skeletondirectory": "",
    "dbtype": "mysql",
    "version": "18.0.3.0",
    "overwrite.cli.url": "https:\/\/it-open.at\/cloud",
    "dbname": "***REMOVED SENSITIVE VALUE***",
    "dbhost": "***REMOVED SENSITIVE VALUE***",
    "dbport": "",
    "dbtableprefix": "oc_",
    "dbuser": "***REMOVED SENSITIVE VALUE***",
    "dbpassword": "***REMOVED SENSITIVE VALUE***",
    "installed": true,
    "mail_smtpmode": "sendmail",
    "mail_smtpsecure": "ssl",
    "mail_sendmailmode": "pipe",
    "mail_from_address": "***REMOVED SENSITIVE VALUE***",
    "mail_domain": "***REMOVED SENSITIVE VALUE***",
    "mail_smtpauthtype": "PLAIN",
    "mail_smtphost": "***REMOVED SENSITIVE VALUE***",
    "redis": {
        "host": "***REMOVED SENSITIVE VALUE***",
        "port": 6379
    },
    "maintenance": false,
    "theme": "",
    "loglevel": 2,
    "app_install_overwrite": [
        "impersonate",
        "piwik",
        "mindmap_app",
        "ocdownloader"
    ],
    "updater.release.channel": "stable",
    "has_rebuilt_cache": true
}
```
</details>

**Are you using external storage, if yes which one:** local

**Are you using encryption:** 

**Are you using an external user-backend, if yes which one:** 

## Client configuration

**Browser:** Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:75.0) Gecko/20100101 Firefox/75.0

**Operating system:** Ubuntu

## Logs

<details><summary>Web server error log</summary>

```
Insert your web server log here 
```
</details>

<details><summary>Nextcloud log</summary>

```
{"reqId":"fgmVOfQpCEmzRJ1P9SC0","level":3,"time":"2020-04-16T07:30:33+00:00","remoteAddr":"82.149.107.2","user":"roland","app":"mail","method":"POST","url":"/cloud/index.php/apps/mail/api/accounts/1/folders/SU5CT1g%3D/sync","message":{"Exception":"OCA\\Mail\\Exception\\ServiceException","Message":"Sync failed: ","Code":0,"Trace":[{"file":"/var/www-itopen/cloud/apps/mail/lib/Service/Sync/SyncService.php","line":107,"function":"sync","class":"OCA\\Mail\\Service\\Sync\\ImapToDbSynchronizer","type":"->"},{"file":"/var/www-itopen/cloud/apps/mail/lib/Controller/FoldersController.php","line":124,"function":"syncMailbox","class":"OCA\\Mail\\Service\\Sync\\SyncService","type":"->"},{"file":"/var/www-itopen/cloud/lib/private/AppFramework/Http/Dispatcher.php","line":170,"function":"sync","class":"OCA\\Mail\\Controller\\FoldersController","type":"->"},{"file":"/var/www-itopen/cloud/lib/private/AppFramework/Http/Dispatcher.php","line":99,"function":"executeController","class":"OC\\AppFramework\\Http\\Dispatcher","type":"->"},{"file":"/var/www-itopen/cloud/lib/private/AppFramework/App.php","line":125,"function":"dispatch","class":"OC\\AppFramework\\Http\\Dispatcher","type":"->"},{"file":"/var/www-itopen/cloud/lib/private/AppFramework/Routing/RouteActionHandler.php","line":47,"function":"main","class":"OC\\AppFramework\\App","type":"::"},{"function":"__invoke","class":"OC\\AppFramework\\Routing\\RouteActionHandler","type":"->"},{"file":"/var/www-itopen/cloud/lib/private/Route/Router.php","line":299,"function":"call_user_func"},{"file":"/var/www-itopen/cloud/lib/base.php","line":1008,"function":"match","class":"OC\\Route\\Router","type":"->"},{"file":"/var/www-itopen/cloud/index.php","line":38,"function":"handleRequest","class":"OC","type":"::"}],"File":"/var/www-itopen/cloud/apps/mail/lib/Service/Sync/ImapToDbSynchronizer.php","Line":151,"Previous":{"Exception":"OCA\\Mail\\Exception\\IncompleteSyncException","Message":"","Code":0,"Trace":[{"file":"/var/www-itopen/cloud/apps/mail/lib/Service/Sync/ImapToDbSynchronizer.php","line":146,"function":"runInitialSync","class":"OCA\\Mail\\Service\\Sync\\ImapToDbSynchronizer","type":"->"},{"file":"/var/www-itopen/cloud/apps/mail/lib/Service/Sync/SyncService.php","line":107,"function":"sync","class":"OCA\\Mail\\Service\\Sync\\ImapToDbSynchronizer","type":"->"},{"file":"/var/www-itopen/cloud/apps/mail/lib/Controller/FoldersController.php","line":124,"function":"syncMailbox","class":"OCA\\Mail\\Service\\Sync\\SyncService","type":"->"},{"file":"/var/www-itopen/cloud/lib/private/AppFramework/Http/Dispatcher.php","line":170,"function":"sync","class":"OCA\\Mail\\Controller\\FoldersController","type":"->"},{"file":"/var/www-itopen/cloud/lib/private/AppFramework/Http/Dispatcher.php","line":99,"function":"executeController","class":"OC\\AppFramework\\Http\\Dispatcher","type":"->"},{"file":"/var/www-itopen/cloud/lib/private/AppFramework/App.php","line":125,"function":"dispatch","class":"OC\\AppFramework\\Http\\Dispatcher","type":"->"},{"file":"/var/www-itopen/cloud/lib/private/AppFramework/Routing/RouteActionHandler.php","line":47,"function":"main","class":"OC\\AppFramework\\App","type":"::"},{"function":"__invoke","class":"OC\\AppFramework\\Routing\\RouteActionHandler","type":"->"},{"file":"/var/www-itopen/cloud/lib/private/Route/Router.php","line":299,"function":"call_user_func"},{"file":"/var/www-itopen/cloud/lib/base.php","line":1008,"function":"match","class":"OC\\Route\\Router","type":"->"},{"file":"/var/www-itopen/cloud/index.php","line":38,"function":"handleRequest","class":"OC","type":"::"}],"File":"/var/www-itopen/cloud/apps/mail/lib/Service/Sync/ImapToDbSynchronizer.php","Line":192},"CustomMessage":"--"},"userAgent":"Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/81.0.4044.113 Safari/537.36","version":"18.0.3.0","id":"5e980ae955528"}
```
</details>

<details><summary>Browser log</summary>


</details>

**Comment by ChristophWurst** [comment]
> "Previous":{"Exception":"OCA\\Mail\\Exception\\IncompleteSyncException"

Okay, this gives me a bit of a clue. We abort the initial sync after ~10k messages. Give that info back to the client. And the client will send follow-up requests until that mailbox has been fully cached. This sounds weirdly complex but we have to have a way to avoid timeouts with the initial indexing on large mailboxes.

I'm digging into this now.

**Comment by ChristophWurst** [comment]
Bingo! There is a little :bug:.

**Comment by ChristophWurst** [comment]
Fix is at https://github.com/nextcloud/mail/pull/2912. Please help me verify the fix by applying the path as https://patch-diff.githubusercontent.com/raw/nextcloud/mail/pull/2912.patch :pray:

**Comment by ChristophWurst** [comment]
Some insights for the curious: an expected edge case was not handled as expected due to wrapping into a more generic error type. Thus the hard failure and HTTP 500.

I could reproduce the bug on my test account with 50k messages. After the change it syncs correctly. After ~1m of initial sync the mailbox shows.

**Comment by ChristophWurst** [comment]
v1.3.1 was just released. Please update :v:

**Comment by raspbeguy** [comment]
I've got 1.4.1 and I have the same problem.

**Comment by ChristophWurst** [comment]
Mind creating a new ticket?

**Comment by raspbeguy** [comment]
Currently last stable version is 19.0.4.2. I do not want to use beta release channel. I'll create a new ticket.

**Comment by dejoebad** [comment]
i got mail v2.2.6, opening gmail loading messages forever
