### ISSUE TITLE
New sent msgs doesn't get displayed in sent folder anymore (1.3.0) but are saved there

### ISSUE THREAD

**Issue by tjareson** [nextcloud/mail#2915]
### Expected behavior
Sent mail should show up in sent-folder.

### Actual behavior
Sent mail do not get displayed in sent folder.
But: they are stored there. If I check the same mail account with e.g. thunderbird or iphone they are visible in sent-folder.
But: in nextcloud-mail folder info these sent mails are counted correctly, but just not displayed in the list.

That is creating a bit of confusion for the users right now, as they are not sure, if they have sent a message or not and also cannot forward anything they have sent out. 

**Mail app**
Mail app version: 1.3.0

**Mailserver or service:** MXRoute (IMAP)

**Server configuration**
**Operating system:** Ubuntu server 16.04

**Web server**: Apache (Nextcloud Docker) and nginx reverse proxy

**Database:** MySQL 10.0.38

**PHP version**: 7.3.16

**Nextcloud Version:** official Nextcloud Docker 18.0.3

**Client configuration**
**Browser:** Opera, Google Chrome, Firefox

**Operating system:** Ubuntu 16.04, Win 10

**Comment by tjareson** [comment]
Additional comment: the sent mails showed up in the sent folder meanwhile. Unfortunately I cannot tell, after how long. 
I wrote another test mail, again it doesn't show up in sent on nextcloud mail (since 5 min...), but with all other mail clients. 
So far I couldn't find any link to cron times. cron.php is handled by crontab in my system setup.

**Comment by ChristophWurst** [comment]
What happens if you press `r` in the sent messages list? Will it pop up?

**Comment by ChristophWurst** [comment]
My guess is that the database cache is not updated immediately. But your cron might trigger the sync. The next time you open the folder, the message will be there.

**Comment by tjareson** [comment]
It gets visible within like 10-20 minutes (couldn't check it every minute...)
With 'r' it gets loaded immediately indeed. 
The confusing part is: it does not update when I switch from inbox to send for some reason.

**Comment by tjareson** [comment]
If I send myself an email from another account, the inbox folder gets updated on the spot (I tested it twice to be sure that it wasn't happened shortly before a cron job kicks in)
So somehow inbox folder seems to be handled differently than e.g. sent folder.

**Comment by beccon4** [comment]
Version 1.3.1 still suffers from that: I write an email - send it off and it disappears entirely.

**Comment by tjareson** [comment]
oh, I was still on 1.3.0. My bad...

**Comment by tjareson** [comment]
So, I've just checked it with 1.3.1
The behavior related to this issue here didn't change. But the other delays disappeared. :-)

**Comment by ChristophWurst** [comment]
> So somehow inbox folder seems to be handled differently than e.g. sent folder.

That is correct. For inboxes there is an automatic background job to fetch changes every 30s.

I guess we need either or both of the following things
* Also update the current folder in the background if it's not an inbox
* Update a mailbox when you switch to it, e.g. when you navigate form inbox to sent

> Version 1.3.1 still suffers from that

Yeah, we fixed just three critical bugs. This one has not been addressed.

> Pressing r helps indeed

Thanks for the confirmation. So it's just the sync between browser and nextcloud.

> Is there a way to select the Sent folder (to bring it in line with my other mail programs)?

Not yet: https://github.com/nextcloud/mail/issues/2035

**Comment by szaimen** [comment]
> * Update a mailbox when you switch to it, e.g. when you navigate form inbox to sent

I would vote for that 👍

**Comment by tjareson** [comment]
From user perspective I would think it is important that I 
- either see the mail I've sent in the send-folder immediately or
- see that sent mails are getting updated/loaded the moment I look into the sent folder. 

From that perspective even a regular update of sent folder via cron job would be second choice in my opinion. 
If people are also using MS Outlook or Thunderbird etc. they are used to immediate updates (actually from/to all devices)
Of course that is technically still not given if you send via iPhone and would expect to see it showing up in sent folder of Nextcloud Mail immediately, as there would be no "navigating to folder"-event, but I guess that is a rare problem...
So I would think the sent folder needs to be updated in two situations:
- when navigating to it (as mail can be sent also by other clients) and
- after sending an mail in nextcloud mail (because you could sent out a mail while in sent folder already).

**Comment by ChristophWurst** [comment]
So I guess what ticks most boxes is an automatic update of the current mailbox independent of whether it is a inbox. Then

* the sent folder will show the sent messages ~instantly
* mailboxes with server-side filtering update automatically
* drafts update

> If people are also using MS Outlook or Thunderbird etc. they are used to immediate updates

That is correct. The problem for us is the technical barrier. Like these client apps can typically keep the IMAP connection open and get notified on changes instantly. With our application architecture we have to poll for the change. As a user it won't matter *that much* if the sent message shows up after 5s or 20s in most cases.

**Comment by tjareson** [comment]
> That is correct. The problem for us is the technical barrier. Like these client apps can typically keep the IMAP connection open and get notified on changes instantly. With our application architecture we have to poll for the change. 

Oh ok, I see. 
Or just leave polling with inbox only and just create one "poll-event" for the current folder when either
- message is sent out or
- a folder is opened/selected?
I was just wondering if the mailprovider will deny access again because of too much polling, assuming that all those requests are coming from the same IP on top?

**Comment by ChristophWurst** [comment]
> I was just wondering if the mailprovider will deny access again because of too much polling,

The change detection is very efficient. It just asks for a few attributes. Based on that it either does nothing (no changes) or only fetches the diff. See https://tools.ietf.org/html/rfc4549 for the full details.

**Comment by rcargnelutti** [comment]
In the conversation at https://github.com/nextcloud/mail/pull/2934, the synchronization of emails in the Sent Box was reported as resolved (https://github.com/nextcloud/mail/issues/2915 ), however I am using the following versions below and I am facing the same problems already reported.

Mail app
Mail app version: **1.4.1**

Mailserver or service: MXRoute (IMAP)

Nextcloud Version:  **19.0.3**

Client configuration (has been tested)
Browser: Google Chrome, Firefox

Operating system: Ubuntu 20.04, Win 10

Sent emails are taking too long to be displayed in the outbox using the Mail App;

The emails sent by App Mail are immediately available in the Sent Box using other RainLoop or Afterlogic App, in App Mail it takes about 10 minutes to be available. Pressing the "R" key resolves, however, that it is not feasible for every email sent or accessing the Sent Box to be necessary to press the "R" key; Even after logging out of Nextcloud and login, when accessing the Sent Box, synchronization has not yet occurred.

After sending an email it is crucial that it be made available in the Sent Box in a reasonable time (5s to 20s);

Is it possible to implement update time for Sent Box equal to Inbox?

**Comment by ChristophWurst** [comment]
@rcargnelutti I assume this is answered by your other feature request that I commented on earlier.
