### ISSUE TITLE
UniqueConstraintViolationException

### ISSUE THREAD

**Issue by maurerle** [nextcloud/mail#2918]
### Expected behavior
Unique constraint should not get violated.

Inbox is only correctly synced in one Nextcloud Account, if two NC Accounts have the same Mail-Account added.

### Actual behavior
I didn't verify this, but I think that I got this error because I have the same mail account admin@example.org added in two nextcloud accounts, my nc-admin account and my personal account.
Otherwise I don't know why it would add the same folder twice..?
I think this is related to the Mail App showing nothing in one of the inboxes (of the same mail account).

This does not stop the Mail App from working. We should handle this event just differently so that other people aren't wondering if something is wrong on their instance.

Log
```
[mail] Fatal: Doctrine\DBAL\Exception\UniqueConstraintViolationException: An exception occurred while executing 'INSERT INTO "mail_mailboxes" ("name", "account_id", "attributes", "delimiter", "messages", "unseen", "selectable", "special_use") VALUES(?, ?, ?, ?, ?, ?, ?, ?)' with params ["Trash", 12, "[\"\\\\marked\",\"\\\\hasnochildren\"]", "\/", 0, 0, true, "[\"trash\"]"]:

SQLSTATE[23505]: Unique violation: 7 ERROR:  duplicate key value violates unique constraint "uniq_45754ff89b6b5fba5e237e06"
DETAIL:  Key (account_id, name)=(12, Trash) already exists. at <<closure>>

 0. /var/www/html/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/DBALException.php line 169
    Doctrine\DBAL\Driver\AbstractPostgreSQLDriver->convertException("An exception oc ... .", Doctrine\DBAL\Dr ... ]})
 1. /var/www/html/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/DBALException.php line 145
    Doctrine\DBAL\DBALException::wrapException(Doctrine\DBAL\Driver\PDOPgSql\Driver {}, Doctrine\DBAL\Dr ... ]}, "An exception oc ... .")
 2. /var/www/html/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/Connection.php line 1063
    Doctrine\DBAL\DBALException::driverExceptionDuringQuery(Doctrine\DBAL\Driver\PDOPgSql\Driver {}, Doctrine\DBAL\Dr ... ]}, "INSERT INTO \"m ... )", {1: "Trash",2: 1 ... "})
 3. /var/www/html/lib/private/DB/Connection.php line 220
    Doctrine\DBAL\Connection->executeUpdate("INSERT INTO \"m ... )", ["Trash",12,"[\" ... "], [2,1,2,2,1,1,5,2])
 4. /var/www/html/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/Query/QueryBuilder.php line 203
    OC\DB\Connection->executeUpdate("INSERT INTO \"m ... )", {dcValue1: "Tras ... "}, {dcValue1: 2,dcV ... 2})
 5. /var/www/html/lib/private/DB/QueryBuilder/QueryBuilder.php line 215
    Doctrine\DBAL\Query\QueryBuilder->execute()
 6. /var/www/html/lib/public/AppFramework/Db/QBMapper.php line 126
    OC\DB\QueryBuilder\QueryBuilder->execute()
 7. /var/www/html/custom_apps/mail/lib/IMAP/MailboxSync.php line 148
    OCP\AppFramework\Db\QBMapper->insert(OCA\Mail\Db\Mailbox {id: null})
 8. /var/www/html/custom_apps/mail/lib/IMAP/MailboxSync.php line 111
    OCA\Mail\IMAP\MailboxSync->createMailboxFromFolder(OCA\Mail\Account {}, OCA\Mail\Folder {})
 9. /var/www/html/custom_apps/mail/lib/IMAP/MailboxSync.php line 100
    OCA\Mail\IMAP\MailboxSync->persist(OCA\Mail\Account {}, {Archive: OCA\Ma ... }}, {INBOX/FLAGGED:  ... }})
10. /var/www/html/custom_apps/mail/lib/Service/MailManager.php line 102
    OCA\Mail\IMAP\MailboxSync->sync(OCA\Mail\Account {})
11. /var/www/html/custom_apps/mail/lib/Controller/PageController.php line 119
    OCA\Mail\Service\MailManager->getFolders(OCA\Mail\Account {})
12. /var/www/html/lib/private/AppFramework/Http/Dispatcher.php line 170
    OCA\Mail\Controller\PageController->index()
13. /var/www/html/lib/private/AppFramework/Http/Dispatcher.php line 99
    OC\AppFramework\Http\Dispatcher->executeController(OCA\Mail\Controller\PageController {}, "index")
14. /var/www/html/lib/private/AppFramework/App.php line 125
    OC\AppFramework\Http\Dispatcher->dispatch(OCA\Mail\Controller\PageController {}, "index")
15. /var/www/html/lib/private/AppFramework/Routing/RouteActionHandler.php line 47
    OC\AppFramework\App::main("OCA\\Mail\\Controller\\PageController", "index", OC\AppFramework\ ... {}, {_route: "mail.page.index"})
16. <<closure>>
    OC\AppFramework\Routing\RouteActionHandler->__invoke({_route: "mail.page.index"})
17. /var/www/html/lib/private/Route/Router.php line 299
    call_user_func(OC\AppFramework\ ... {}, {_route: "mail.page.index"})
18. /var/www/html/lib/base.php line 1008
    OC\Route\Router->match("/apps/mail/")
19. /var/www/html/index.php line 38
    OC::handleRequest()

GET /apps/mail/
```
### Server configuration

**Operating system**: Docker-Alpine

**Web server:** Nginx

**Database:** PostgreSQL

**PHP version:** (e.g. 7.0)

**Nextcloud Version:** 18.0.3

#### Client configuration
**Browser:** Firefox 75

**Operating system:** Win10

**Comment by ChristophWurst** [comment]
This is the critical logic: https://github.com/nextcloud/mail/blob/7f32cfe6570d112fb748c9a97590e2b9d6e8aafb/lib/IMAP/MailboxSync.php#L105-L114. So it goes into the create path, as it hasn't found the mailbox before: https://github.com/nextcloud/mail/blob/7f32cfe6570d112fb748c9a97590e2b9d6e8aafb/lib/IMAP/MailboxSync.php#L110-L113.

I suspect this is a race condition. Like either two web requests or web request and cron both run into the same code section concurrently, both see that a mailbox is new and both try to insert the row. Hence the error.

If that is the case than the problem should be "solved" now. One of the processes one, the other threw an error. Can you confirm that everything works fine now?

> I didn't verify this, but I think that I got this error because I have the same mail account [admin@example.org](mailto:admin@example.org) added in two nextcloud accounts, my nc-admin account and my personal account.

That doesn't matter. Each of the accounts with get a unique id. The conflict only shows if the mailbox is inserted twice for a single account.

> I think this is related to the Mail App showing nothing in one of the inboxes (of the same mail account).

Could be related. But I'm not sure.

**Comment by maurerle** [comment]
I can't reproduce this anymore
