### ISSUE TITLE
1.3.1 the ability to create new folder while saving attachments has disappeared

### ISSUE THREAD

**Issue by laurentiu2** [nextcloud/mail#2922]
### Expected behavior
while saving attachments to server, it was possible to create new folder

### Actual behavior
that has disappeared since 1.3.1

### Mail app

**Mail app version:** 1.3.1
**Mailserver or service:** Hetzner

### Server configuration

**Operating system**: Debian 9

**Web server:** Apache

**Database:** MariaDB

**PHP version:** 7.3.2
**Nextcloud Version:** 18.0.3
#### Client configuration
**Browser:** Firefox 75

**Operating system:** Mac Catalina 10.15.3
![Screenshot 2020-04-16 at 17 02 19](https://user-images.githubusercontent.com/29857699/79475209-0d592700-8010-11ea-92f4-f24abf432d73.png)

**Comment by ChristophWurst** [comment]
The file picker is actually part of Nextcloud server, not this app. So the app update alone can't be the reason for this change. Did you also update Nextcloud?

**Comment by laurentiu2** [comment]
No, I only updated Mail (to 1.3.0) and afterwards to 1.3.1 File picker was present in 1.3.0 it disappeared in 1.3.1
I also updated Contacts.

**Comment by miceno** [comment]
I followed the issue and the point is that the button is there, but it is hidden.

See attached image:
![image](https://user-images.githubusercontent.com/315830/84576047-0a7d7700-adb2-11ea-8e7f-6bd8d4220508.png)

See also rendered HTML, it shows an explicit `display: none`:

```javascript
<span class="actions creatable"><a href="#" class="icon icon-add button button-add" style="display: none;"></a>
			<nav class="menu popovermenu bubble menu-left newFolderMenu">
				<ul><li>
				<form class="filenameform">
					<input type="text" value="New folder">
					<input class="icon-confirm" type="submit" value="">
				</form>
				</li></ul>
			</nav>
		</span>
```

The picker is created with `type = 1` here:

The point is that `1 == FILEPICKER_TYPE_CHOOSE`, so having a look at the picker code in Nextcloud, if type is 1, it will not show the add folder button. So I suggest changing the type to FILEPICKER_TYPE_COPY in nextcloud mail.

I am already preparing a PR for it :)
