### ISSUE TITLE
UTF8-Encoding error on drafts folder name

### ISSUE THREAD

**Issue by maurerle** [nextcloud/mail#2926]
### Expected behavior
Show Entwürfe as UTF8-Encoding instead of ANSII in folder context menu.

### Actual behavior
On german Mail-Hosts the drafts folder shows "EntwÃ¼rfe" in the context menu. (Tested with GMX and my university)
On english Mail-Hosts it shows "Entwürfe" and then "Drafts" in the context menu (gmail & outlook) (which is okay, but we shouldn't have encoding errors)

![grafik](https://user-images.githubusercontent.com/25026204/79542886-b6456780-808c-11ea-87fd-f5540b4ced42.png)

### Mail app

**Mail app version:** 1.3.2

**Mailserver or service:** stated above

**Comment by ChristophWurst** [comment]
Duplicate of https://github.com/nextcloud/mail/issues/2525
