### ISSUE TITLE
Draft saving: One big/bug laggy mess

### ISSUE THREAD

**Issue by Ornias1993** [nextcloud/mail#2933]
### Expected behavior
Typing a message should be smooth

### Actual behavior
Every time draft saving triggers, it freezes for a few seconds. When typing this results in input lag-spikes.
Possibly because draft saving is done over IMAP and the server being somewhere else slows it down.

Draft saving shouldn't in any way, shape or form influence the typing. Simply put: It seems draft saving and input processing isn't being done async.
It seems to have become worse the past month or so, but that might not be nextcloud related.

### Mail app
Latest, 1.3.2

**Mailserver or service:**
TransIP (offsite mail service, different site than nextcloud)

### Server configuration

**Operating system**: 
FreeBSD

**Web server:** (e.g. Apache, Nginx,...)
Caddy

**Database:** (e.g. MariaDB, SQLite or PostgreSQL)
MariaDB

**PHP version:** (e.g. 7.0)
7.3? I guess

**Nextcloud Version:** (see admin page, e.g. 13.0.2)
Latest 18. something

#### Client configuration
**Browser:** (e.g. Firefox 48)
Firefox and Chrome, all recent versions

**Operating system:** (e.g. Arch Linux)
Windows 10

**Comment by ChristophWurst** [comment]
> Possibly because draft saving is done over IMAP

While that is the case, the request is sent async, so it should not block any other processing in your browser.

> It seems to have become worse the past month or so, but that might not be nextcloud related.

Have you ever tried with a clean profile or disabled extensions? https://github.com/nextcloud/mail/issues/1973 sounds a bit similar.

**Comment by Ornias1993** [comment]
Interesting, overnight it magically disappeared. It seems pretty random for some reason. Gonna get back to it if I can have it reappear...
