### ISSUE TITLE
Left panel could be hidden

### ISSUE THREAD

**Issue by CATER-COM** [nextcloud/mail#2937]
As in the Deck app, it could be nice to hide the left panel (with accounts and folders) to bring more space for messages list and message on little screen.

Thanks

**Comment by jancborchardt** [comment]
This will be in one of the next releases, just needs the change from the Vue components to come in. Correct @skjnldsv @ma12-co?

**Comment by skjnldsv** [comment]
Yes, still not released! :)

**Comment by CATER-COM** [comment]
Nice ! Thank you :-)

**Comment by ma12-co** [comment]
The support for it will come in that pr, but each app has to keep track of the user's preference on this and handle the navigation open state. So this needs to be done in mail!

Also in the component we still haven't provided an `initialState` prop, so the closing for now has to happen right after mounting the navigation by emitting an event, which is weird in my opinion!

**Comment by skjnldsv** [comment]
> The support for it will come in that pr, but each app has to keep track of the user's preference on this and handle the navigation open state.

Nope, we said we'll tackle this in the vue components too :)
Seems better this way I think.

**Comment by ma12-co** [comment]
Atm the navigation is collapsible but the user's choice is not remembered.
