### ISSUE TITLE
Cannot Connect to External Mail Server

### ISSUE THREAD

**Issue by Changer90** [nextcloud/mail#294]
### Steps to reproduce
1. Try adding a Account
2. Enter Credentials incl. Manual Mode
3. try to login

### Expected behaviour
Connection to Mail Account Successful

### Actual behaviour
Error: Error connecting to mail server

### Additional
Connecting to Mailserver in local network works
Only External Mail Servers are not working
Problem exists since update

### Mail app

**Mail app version:** 0.6.2

**Mailserver or service:** web.de

**Transport security - IMAP:** SSL, TLS, STARTTLS)

**Transport security - SMTP:**  SSL, TLS, STARTTLS

**Number of accounts:** 1

### Server configuration
**Operating system**: Linux

**Web server:** Apache/2.4.25 (Unix)

**Database:** mysql  Ver 14.14 Distrib 5.6.35

**PHP version:** PHP 7.0.15

**Version:**  11.0.1

**Updated from an older version or fresh install:** Update

**List of activated apps:**

<details>
Enabled:
  - activity: 2.4.1
  - admin_audit: 1.1.0
  - apporder: 0.3.3
  - audioplayer: 1.4.0
  - bookmarks: 0.9.1
  - calendar: 1.5.0
  - comments: 1.1.0
  - contacts: 1.5.2
  - dav: 1.1.1
  - encryption: 1.4.1
  - external: 1.2
  - federatedfilesharing: 1.1.1
  - federation: 1.1.1
  - files: 1.6.1
  - files_accesscontrol: 1.1.2
  - files_external: 1.1.2
  - files_pdfviewer: 1.0.1
  - files_sharing: 1.1.1
  - files_texteditor: 2.2
  - files_trashbin: 1.1.0
  - files_versions: 1.4.0
  - files_videoplayer: 1.0.0
  - firstrunwizard: 2.0
  - gallery: 16.0.0
  - logreader: 2.0.0
  - lookup_server_connector: 1.0.0
  - mail: 0.6.2
  - news: 10.1.0
  - nextcloud_announcements: 1.0
  - notifications: 1.0.1
  - password_policy: 1.1.0
  - provisioning_api: 1.1.0
  - serverinfo: 1.1.1
  - sharebymail: 1.0.1
  - spreed: 1.2.0
  - survey_client: 0.1.5
  - systemtags: 1.1.3
  - tasks: 0.9.4
  - templateeditor: 0.2
  - theming: 1.1.1
  - twofactor_backupcodes: 1.0.0
  - twofactor_totp: 0.5.0
  - twofactor_u2f: 0.1.0
  - updatenotification: 1.1.1
  - workflowengine: 1.1.1
Disabled:
  - files_automatedtagging
  - files_markdown
  - files_retention
  - keeweb
  - rainloop
  - user_external
  - user_ldap
  - user_saml
</details>

**The content of config/config.php:**
<details>
"system": {
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "***URL***",
            "***URL***",
            "***URL***",
            "***URL***"
        ],
        "datadirectory": "\/opt\/nextcloud\/data",
        "overwrite.cli.url": "https:\/\/***URL***",
        "overwriteprotocol": "https",
        "dbtype": "mysql",
        "version": "11.0.1.2",
        "dbname": "***REMOVED SENSITIVE VALUE***",
        "dbhost": "localhost",
        "dbtableprefix": "oc_",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "logtimezone": "UTC",
        "installed": true,
        "mail_smtpmode": "smtp",
        "maintenance": false,
        "mail_smtpauth": 1,
        "mail_smtphost": "localhost",
        "mail_smtpport": "25",
        "mail_smtpname": "***REMOVED SENSITIVE VALUE***",
        "mail_smtppassword": "***REMOVED SENSITIVE VALUE***",
        "mail_from_address": "nextcloud",
        "mail_domain": "wechsler.xyz",
        "debug": false,
        "loglevel": 0,
        "htaccess.RewriteBase": "\/",
        "theme": "",
        "appstore.experimental.enabled": true,
        "auth.bruteforce.protection.enabled": false,
        "app.mail.smtplog.enabled": true,
        "app.mail.imaplog.enabled": true,
        "app.mail.imap.timeout": 30
    }
</details>

#### Client configuration
**Browser:** Google Chrome, Firefox

**Operating system:** Linux, Windows 7, 10

##### Web server error log
<details>
[Sun Jan 22 18:01:59.392276 2017] [mpm_event:notice] [pid 2570:tid 140694962907008] AH00489: Apache/2.4.25 (Unix) OpenSSL/1.0.2j PHP/7.0.15 configured -- resuming normal operations
[Sun Jan 22 18:01:59.392337 2017] [core:notice] [pid 2570:tid 140694962907008] AH00094: Command line: '/usr/sbin/apache2 -D DEFAULT_VHOST -D INFO -D SSL -D SSL_DEFAULT_VHOST -D LANGUAGE -D SECURITY -D PHP -D FOREGROUND'
zend_mm_heap corrupted
zend_mm_heap corrupted
zend_mm_heap corrupted

</details>

##### Server log (data/nextcloud.log)
<details>
{"reqId":"***","remoteAddr":"192.168.100.1","app":"core","message":"Default encryption module not loaded","level":3,"time":"2017-01-23T08:17:53+00:00","method":"GET","url":"\/ocs\/v2.php\/apps\/notifications\/api\/v2\/notifications","user":"***USER***","version":"11.0.1.2"}
{"reqId":"***" remoteAddr":"192.168.100.1","app":"core","message":"Default encryption module not loaded","level":3,"time":"2017-01-23T08:18:09+00:00","method":"GET","url":"\/ocs\/v2.php\/apps\/notifications\/api\/v2\/notifications","user":"***USER***","version":"11.0.1.2"}
</details>

##### Horde IMAP log (data/horde_imap.log)
<details>
>> Mon, 23 Jan 2017 07:59:39 +0000
>> Connection to: imap://imap.web.de:993/
>> Slow Command: 20.055 seconds
>> Connection failed: Error connecting to server.
------------------------------
>> Mon, 23 Jan 2017 08:00:13 +0000
>> Connection to: imap://imap.web.de:993/
>> Slow Command: 20.049 seconds
>> Connection failed: Error connecting to server.
------------------------------
>> Mon, 23 Jan 2017 08:03:23 +0000
>> Connection to: imap://imap.web.de:993/
>> Slow Command: 30.045 seconds
>> Connection failed: Error connecting to server.
</details>

##### Horde SMTP log (data/horde_smtp.log)
Not Available

##### Browser log
<details>
[ui] "sidebar:accounts" Array[0]
mail.min.js?v=ad2e312…:178 [ui] "composer:leave" Array[0]
mail.min.js?v=ad2e312…:178 [ui] "navigation:hide" Array[0]
mail.min.js?v=ad2e312…:178 [ui] "setup:show" Array[0]
mail.min.js?v=ad2e312…:178 [keyboard] "keyup" Array[2]
mail.min.js?v=ad2e312…:178 [keyboard] "keyup" Array[2]
mail.min.js?v=ad2e312…:178 [keyboard] "keyup" Array[2]
mail.min.js?v=ad2e312…:178 [keyboard] "keyup" Array[2]
mail.min.js?v=ad2e312…:178 [keyboard] "keyup" Array[2]
mail.min.js?v=ad2e312…:178 [keyboard] "keyup" Array[2]
mail.min.js?v=ad2e312…:178 [account] "create" Array[1]
mail.min.js?v=ad2e312…:178 [keyboard] "keyup" Array[2]
https://cloud.swechsler.de/apps/mail/accounts Failed to load resource: the server responded with a status of 400 (Bad request)
mail.min.js?v=ad2e312…:178 [ui] "error:show" Array[1]
</details>

**Comment by ChristophWurst** [comment]
> >> Mon, 23 Jan 2017 07:59:39 +0000 >> Connection to: imap://imap.web.de:993/ >> Slow Command: 20.055 seconds >> Connection failed: Error connecting to server. ------------------------------ >> Mon, 23 Jan 2017 08:00:13 +0000 >> Connection to: imap://imap.web.de:993/ >> Slow Command: 20.049 seconds >> Connection failed: Error connecting to server. ------------------------------ >> Mon, 23 Jan 2017 08:03:23 +0000 >> Connection to: imap://imap.web.de:993/ >> Slow Command: 30.045 seconds >> Connection failed: Error connecting to server.

Wow, it took the server really long to respond. Maybe the connection timed out. You can try setting a higher IMAP timeout https://github.com/nextcloud/mail/blob/cf544641e5926e5cf0b73f4ad5611edb964f2b13/README.md#imap-timeout

**Comment by Changer90** [comment]
I have tried setting it to 120 Seconds. Unforutnately no success

imap Log
<details>
>> Mon, 23 Jan 2017 08:32:07 +0000
>> Connection to: imap://imap.web.de:993/
>> Slow Command: 120.06 seconds
>> Connection failed: Error connecting to server.
</details>

my ping is okay
# ping imap.web.de
PING imap.web.de (212.227.17.178) 56(84) bytes of data.
64 bytes from imap.web.de (212.227.17.178): icmp_seq=1 ttl=248 time=11.5 ms
64 bytes from imap.web.de (212.227.17.178): icmp_seq=2 ttl=248 time=11.6 ms
64 bytes from imap.web.de (212.227.17.178): icmp_seq=3 ttl=248 time=11.6 ms
64 bytes from imap.web.de (212.227.17.178): icmp_seq=4 ttl=248 time=11.7 ms
^C
--- imap.web.de ping statistics ---
4 packets transmitted, 4 received, 0% packet loss, time 3004ms
rtt min/avg/max/mdev = 11.581/11.662/11.734/0.054 ms

**Comment by ChristophWurst** [comment]
😨 this shouldn't happen. Do you maybe have the possibility to test other IMAP applications from that host? Maybe the IP is blocked due to a brute-force protection or similar.

**Comment by Changer90** [comment]
Other Users in my cloud have the same problem with gmail.com and yahoo.com. I can send you my log with gmail if you need it

**Comment by ChristophWurst** [comment]
I see. So the connection to the IMAP servery is unacceptably slow for some reason. Did you check the internet connection and your firewall?
I don't think that other logs help right now, but thanks :-)

**Comment by Changer90** [comment]
Yes internet speed is fine on the server. I haven't changed anything on that vm besides an update of nextcloud. All other apps work fine. I had the infinite houreglass bug before this issue. But after disabling the Markdown app and deleting the mysql info of the mail app. I can enter the login credentials again.

**Comment by ChristophWurst** [comment]
Could you please try to isolate this issue by starting a shell (local terminal or ssh session) in that VM and connect to an IMAP server? You'll find some howtos on the internet on how to do that. Simply log in and list folders or something. I'm curious if there the connection is slow too. Thanks

**Comment by Changer90** [comment]
I found my problem. In fact it was really a error in my iptables config on my host machine. Sorry for the inconvenience and thank you for your help. This Issue can be closed.

Best regards Changer

**Comment by ChristophWurst** [comment]
I'm glad you could resolve the issue 😉
