### ISSUE TITLE
Navigation in small windows mode doesn't work

### ISSUE THREAD

**Issue by Bubu** [nextcloud/mail#2942]
When the browser window gets small enough (i.e. by opening the web console pinned to the left side) the app switches to a folder/message only view

### Expected behavior
When pressing the back arrow from a message I get back to the folder list

### Actual behavior
Nothing happens with the following warning in the console logged:

[WARN] mail: navigation from a message to just the folder. we don't want that, do we? let's go back And this:
[DEBUG] mail: navigated but the message is still the same 

### Mail app

**Mail app version:** 1.3.2
**PHP version:** 7.4.5

**Nextcloud Version:** 18.0.3
#### Client configuration
**Browser:** Firefox 75

**Operating system:** Ubuntu 18.04

**Comment by ChristophWurst** [comment]
> [WARN] mail: navigation from a message to just the folder. we don't want that, do we? let's go back And this:
> [DEBUG] mail: navigated but the message is still the same

Possible regression of #2893

**Comment by jancborchardt** [comment]
@ChristophWurst why am I assigned, seems to be a JS fix? :) If it’s about my input: Can confirm that when you are in a message and press the back button, the folder list should show again. Can also confirm that it currently doesn’t, with the console logs @Bubu wrote.

**Comment by ChristophWurst** [comment]
Right. I was too fast with the triage :)
