### ISSUE TITLE
occ upgrade must be run twice (manually)

### ISSUE THREAD

**Issue by enoch85** [nextcloud/mail#2954]
### Expected behavior
The mail app should be updated when the other apps are updated using `./occ upgrade` as usual.

### Actual behavior
Several users reported to me that their cloud is in an update stage and they can't update because automatic updates are disabled (the VM use CLI).

In the VM there's an update script which runs `./occ upgrade` to update Nextcloud, in a regular manner.

Now as it turns out, all users with the mail app enabled is greeted with this after the upgrade:

![image](https://user-images.githubusercontent.com/4511254/79695876-8313fb80-8279-11ea-8e36-c9b95e7ccd5c.png)

After som investigation I found that running `./occ upgrade` a *second* time did the trick, and mail got updated.

Is this really how it should be?

This is some of the occ output:
```
Purify and migrate collected mail addresses

 Done
    0/0 [>---------------------------]   0%
Insert sync background job for all accounts
 Done
 1/1 [============================] 100%
Updated <mail> to 1.3.2
```

### Mail app

After the upgrade its 1.3.2, I don't know the version before that.

### Server configuration

**Operating system**: (e.g. Debian 8)
Ubuntu Server 18.04

**Web server:** (e.g. Apache, Nginx,...)
Apache

**Database:** (e.g. MariaDB, SQLite or PostgreSQL)
PostgreSQL

**PHP version:** (e.g. 7.0)
7.2

**Nextcloud Version:** (see admin page, e.g. 13.0.2)
18.0.3

**Comment by enoch85** [comment]
It happened again. Some additional info:

```
An unhandled exception has been thrown:
Error: Call to undefined method OCA\Mail\Db\MailAccountMapper::getAllAccounts() in /var/www/nextcloud/apps/mail/lib/Migration/FixAccountSyncs.php:53
Stack trace:
#0 /var/www/nextcloud/lib/private/Repair.php(104): OCA\Mail\Migration\FixAccountSyncs->run(Object(OC\Repair))
#1 /var/www/nextcloud/lib/private/legacy/app.php(981): OC\Repair->run()
#2 /var/www/nextcloud/lib/private/legacy/app.php(918): OC_App::executeRepairSteps('mail', Array)
#3 /var/www/nextcloud/lib/private/Installer.php(205): OC_App::updateApp('mail')
#4 /var/www/nextcloud/core/Command/App/Update.php(109): OC\Installer->updateAppstoreApp('mail')
#5 /var/www/nextcloud/3rdparty/symfony/console/Command/Command.php(255): OC\Core\Command\App\Update->execute(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#6 /var/www/nextcloud/3rdparty/symfony/console/Application.php(915): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#7 /var/www/nextcloud/3rdparty/symfony/console/Application.php(272): Symfony\Component\Console\Application->doRunCommand(Object(OC\Core\Command\App\Update), Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#8 /var/www/nextcloud/3rdparty/symfony/console/Application.php(148): Symfony\Component\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#9 /var/www/nextcloud/lib/private/Console/Application.php(214): Symfony\Component\Console\Application->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#10 /var/www/nextcloud/console.php(99): OC\Console\Application->run()
#11 /var/www/nextcloud/occ(11): require_once('/var/www/nextcl...')
#12 {main}
```

**Comment by ChristophWurst** [comment]
@rullzer I think that is the same issue you ran into.

The thing is, that method does exist. So my only explanation for this error is that the old app code is loaded before the upgrade. Then a migration code invokes the new code, but that does not exist. @nickvergessen could that be the case?

**Comment by nickvergessen** [comment]
Yeah basically we need to download the new app code and then start a new process, as otherwise the old classes are already loaded

**Comment by ChristophWurst** [comment]
Is there a possible workaround for us? It's important that his repair step is run. So a catch-all-and-ignore feels risky.

**Comment by enoch85** [comment]
This seems to be fixed.
