### ISSUE TITLE
The list of messages should not move when the spinner is loading

### ISSUE THREAD

**Issue by GretaD** [nextcloud/mail#2964]
ref https://github.com/nextcloud/mail/pull/2648#issuecomment-602470230
When the window focus is lost and acquired again, we trigger a sync to make sure any messages from background notifications are there. This is a technical requirement, there is currently no way around.

We should show the spinner here. Otherwise the list will update as you attempt to perform an action, e.g. a message is deleted, the list shrinks and you click on another message.

We should enhance the spinner to not move the list instead of hiding the spinner.

**Comment by jancborchardt** [comment]
This was fixed by **Make loading spinner not move all messages #3068** :)
