### ISSUE TITLE
Cannot connect to Mailserver

### ISSUE THREAD

**Issue by Trimilur** [nextcloud/mail#2966]
### Expected behavior
Connection should be established

### Actual behavior
"level":4,"time":"2020-04-21T20:08:53+00:00","remoteAddr":"5.61.***.***","user":"**","app":"mail","method":"PUT","url":"/nextcloud/apps/mail/api/accounts/1","message":"Updating account failed: Could not connect to IMAP: Authentication failed.","userAgent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:75.0) Gecko/20100101 Firefox/75.0","version":"18.0.3.0"}

### Mail app

**Mail app version: 1.3.3

**Mailserver or service: Postfix/Dovecot local

### Server configuration

**Operating system Ubuntu 20.4

**Web server: Nginx 

**Database MariaDb

**PHP version: 7.4.3

**Nextcloud Version: 18.0.3

#### Client configuration
**Browser: Firefox, Opera, Chrome

**Operating system: Windows/Linux

**Comment by ChristophWurst** [comment]
> Authentication failed

Is the password correct? Have you tried using just the user part for the IMAP user vs the full email address?

**Comment by Trimilur** [comment]
Yes. I tried also the Nextcloud SMTP data, which are working.

**Comment by ChristophWurst** [comment]
The Nextcloud mail app offers an extensive logging system to make it easier identifying and tracking down bugs. Please enable [debug mode](https://docs.nextcloud.com/server/stable/developer_manual/general/devenv.html#enabling-debug-mode) and set the log [level to debug](https://docs.nextcloud.com/server/stable/admin_manual/configuration_server/logging_configuration.html) in your admin settings. Then, try to reproduce your issue and take another look at `data/nextcloud.log`, `data/horde_imap.log` and `data/horde_smtp.log`.

**Comment by Trimilur** [comment]
data/horde_imap.log and data/horde_smtp.log these files do not exist. and the nextcloud log is spammed with RuntimeException “is not set up via query() but directly” but there is basically no further info than the error code i gave already.

**Comment by ChristophWurst** [comment]
1) The original report has an authentication error
2) No auth error in imap log
3) No auth error in smtp log
4) Unrelated error about the WFE

**Comment by ChristophWurst** [comment]
from the logs provided I assume everything's working now
