### ISSUE TITLE
Add compatibility with PHP 7

### ISSUE THREAD

**Issue by avanc** [nextcloud/mail#297]
### Steps to reproduce
1. Upgrade PHP to version 7.0.0
2. Go to app manager
3. Select mail app

### Expected behaviour
It should be possible to activate mail app.

### Actual behaviour
Mail app cannot be activated. It is written that current version is not compatible with PHP 7.0

### Mail app

**Mail app version:** (see apps admin page)
0.6.2 

### Server configuration
**Operating system**:
Arch Linux

**Web server:**
Apache

**Database:**
Mysql

**PHP version:**
PHP 7.0

**Version:** (see admin page)
11.0.1

**Updated from an older version or fresh install:**
Updated

**Comment by ChristophWurst** [comment]
Fixed in https://github.com/nextcloud/mail/pull/248. Will be available with the next release :-)

**Comment by avanc** [comment]
Great to hear :-)
