### ISSUE TITLE
Broken Style with macOS Safari

### ISSUE THREAD

**Issue by clementhk** [nextcloud/mail#2973]
### Expected behavior
Nice style that could read whole email in a page.
<img width="1167" alt="Screenshot 2020-04-23 at 14 08 19" src="https://user-images.githubusercontent.com/3030930/80098933-fa91a580-856d-11ea-81f0-ddb83dc01658.png">

### Actual behavior
Reading area is so small I could almost not read anything
<img width="1293" alt="Screenshot 2020-04-23 at 14 08 10" src="https://user-images.githubusercontent.com/3030930/80098949-01201d00-856e-11ea-84f4-427ee8833ebf.png">

### Mail app

**Mail app version:** (see apps admin page, e.g. 0.5.3)
1.3.3

**Mailserver or service:** (e.g. Outlook, Yahoo, Gmail, Exchange,...)
IMAP Server

### Server configuration

**Operating system**: (e.g. Debian 8)
Debian 10

**Web server:** (e.g. Apache, Nginx,...)
Nginx

**Database:** (e.g. MariaDB, SQLite or PostgreSQL)
MariaDB

**PHP version:** (e.g. 7.0)
7.3

**Nextcloud Version:** (see admin page, e.g. 13.0.2)
18.0.4

#### Client configuration
**Browser:** (e.g. Firefox 48)
Safari

**Operating system:** (e.g. Arch Linux)
macOS

**Comment by clementhk** [comment]
#2222 is maybe not tested under macOS Safari?

**Comment by ChristophWurst** [comment]
Long time no see @clementhk. Great to see you still use this app :)

> #2222 is maybe not tested under macOS Safari?

Ouch. Yes, was about to look up that ticket :) @violoncelloCH you're on linux, right? :)

**Comment by violoncelloCH** [comment]
well, yes... tested under firefox and chromium on linux... I would have the possibility to check something on Windows, but Mac... :upside_down_face: 
but as far as I remember @StCyr is on Mac... maybe he can check this?

**Comment by clementhk** [comment]
> Long time no see @clementhk. Great to see you still use this app :)
> 
> > #2222 is maybe not tested under macOS Safari?
> 
> Ouch. Yes, was about to look up that ticket :) @violoncelloCH you're on linux, right? :)

👋 Good to see you still being active. Just checking again if NextCloud is the right tool for me like last time, it wasn't ready before, but now it looks much better, so I might actually start using it.
Great work!
