### ISSUE TITLE
No translated description in the settings

### ISSUE THREAD

**Issue by Valdnet** [nextcloud/mail#2987]
### Expected behavior
Translated description of the setting.

### Actual behavior
No translated description in the settings.
**Not available for translation on Transifex**.

![obraz](https://user-images.githubusercontent.com/47037905/80219766-39ddf600-8643-11ea-99b5-b75ba8c93429.png)

### Mail app

**Mail app version:** (see apps admin page, e.g. 0.5.3)
1.3.3

**Comment by ChristophWurst** [comment]
Attempted fix is at https://github.com/nextcloud/mail/pull/3028. Let's see if the bot will pick up the string now. This will take 1-2 days.

**Comment by ChristophWurst** [comment]
It's there now https://github.com/nextcloud/mail/blob/724956b26077a05b87c81c2cb49e5083e8dbf8c2/l10n/pl.js#L37

**Comment by Valdnet** [comment]
@ChristophWurst Cool. Thanks a lot 😉.
