### ISSUE TITLE
Change folder to display content/body

### ISSUE THREAD

**Issue by cerelli** [nextcloud/mail#2988]
### Expected behavior
If navigating from 'All Inboxes' directly to 'Sent' in any account, the list of emails is visible, but not the content/body.
You have to go to 'Inbox' first, and only after that to 'Sent' to display the content/body.
No errors in Logging.

The first time I select the sent folder,
[DEBUG] mail: using cached value for envelope ... not appear in firefox console

### Mail app

**Mail app version:** 1.3.3

### Server configuration

**Operating system**: Debian 10

**Web server:** Nginx

**Database:** MariaDB

**PHP version:** 7.4

**Nextcloud Version:** 18.0.4

#### Client configuration
**Browser:** ALL

**Operating system:** ALL

**Comment by mat-m** [comment]
Can't reproduce with NC 18.0.4 and mail 1.3.3 on a Raspbian 10 (in Firefox 75)
Can you check with another browser ?

**Comment by cerelli** [comment]
I tried with firefox, edge and chrome: same problem on all.

**Comment by cerelli** [comment]
I have updated to version 1.3.4 but the problem remains.
It looks the same as what was written here: https://github.com/nextcloud/mail/issues/2917#issuecomment-614669628

**Comment by cerelli** [comment]
This is my logs:

> eqId":"t9xz02YpaH6jRt6j5BcD","level":3,"time":"2020-04-29T17:16:47+02:00","remoteAddr":"151.20.146.125","user":"admin","app":"PHP","method":"GET","url":"/apps/mail/","message":"Trying to access array offset on value of type null at /var/www/html/nextcloud/3rdparty/leafo/scssphp/src/Compiler.php#5230","userAgent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/81.0.4044.129 Safari/537.36","version":"18.0.4.2"}
{"reqId":"t9xz02YpaH6jRt6j5BcD","level":3,"time":"2020-04-29T17:16:47+02:00","remoteAddr":"151.20.146.125","user":"admin","app":"PHP","method":"GET","url":"/apps/mail/","message":"Trying to access array offset on value of type null at /var/www/html/nextcloud/3rdparty/leafo/scssphp/src/Compiler.php#5230","userAgent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/81.0.4044.129 Safari/537.36","version":"18.0.4.2"}
{"reqId":"t9xz02YpaH6jRt6j5BcD","level":3,"time":"2020-04-29T17:16:47+02:00","remoteAddr":"151.20.146.125","user":"admin","app":"PHP","method":"GET","url":"/apps/mail/","message":"Trying to access array offset on value of type null at /var/www/html/nextcloud/3rdparty/leafo/scssphp/src/Compiler.php#5230","userAgent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/81.0.4044.129 Safari/537.36","version":"18.0.4.2"}
{"reqId":"t9xz02YpaH6jRt6j5BcD","level":3,"time":"2020-04-29T17:16:47+02:00","remoteAddr":"151.20.146.125","user":"admin","app":"PHP","method":"GET","url":"/apps/mail/","message":"Trying to access array offset on value of type null at /var/www/html/nextcloud/3rdparty/leafo/scssphp/src/Compiler.php#5230","userAgent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/81.0.4044.129 Safari/537.36","version":"18.0.4.2"}
{"reqId":"t9xz02YpaH6jRt6j5BcD","level":3,"time":"2020-04-29T17:16:47+02:00","remoteAddr":"151.20.146.125","user":"admin","app":"PHP","method":"GET","url":"/apps/mail/","message":"Trying to access array offset on value of type null at /var/www/html/nextcloud/3rdparty/leafo/scssphp/src/Compiler.php#5230","userAgent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/81.0.4044.129 Safari/537.36","version":"18.0.4.2"}
{"reqId":"MiKu1RQ3a9jgcCcNa7k5","level":2,"time":"2020-04-29T17:17:52+02:00","remoteAddr":"151.20.146.125","user":"admin","app":"mail","method":"GET","url":"/apps/mail/api/accounts/1/folders/SU5CT1g%3D/messages/5956/body","message":"KItinerary binary adapter is not available, can't extract information","userAgent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/81.0.4044.129 Safari/537.36","version":"18.0.4.2"}
{"reqId":"MiKu1RQ3a9jgcCcNa7k5","level":2,"time":"2020-04-29T17:17:52+02:00","remoteAddr":"151.20.146.125","user":"admin","app":"mail","method":"GET","url":"/apps/mail/api/accounts/1/folders/SU5CT1g%3D/messages/5956/body","message":"KItinerary binary adapter is not available, can't extract information","userAgent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/81.0.4044.129 Safari/537.36","version":"18.0.4.2"}
{"reqId":"zO8YJ7ZaijlxGNNzTe2l","level":2,"time":"2020-04-29T17:17:55+02:00","remoteAddr":"151.20.146.125","user":"admin","app":"mail","method":"GET","url":"/apps/mail/api/accounts/1/folders/SU5CT1g%3D/messages/5251/body","message":"KItinerary binary adapter is not available, can't extract information","userAgent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/81.0.4044.129 Safari/537.36","version":"18.0.4.2"}
{"reqId":"zO8YJ7ZaijlxGNNzTe2l","level":2,"time":"2020-04-29T17:17:55+02:00","remoteAddr":"151.20.146.125","user":"admin","app":"mail","method":"GET","url":"/apps/mail/api/accounts/1/folders/SU5CT1g%3D/messages/5251/body","message":"KItinerary binary adapter is not available, can't extract information","userAgent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/81.0.4044.129 Safari/537.36","version":"18.0.4.2"}
{"reqId":"zO8YJ7ZaijlxGNNzTe2l","level":2,"time":"2020-04-29T17:17:55+02:00","remoteAddr":"151.20.146.125","user":"admin","app":"mail","method":"GET","url":"/apps/mail/api/accounts/1/folders/SU5CT1g%3D/messages/5251/body","message":"KItinerary binary adapter is not available, can't extract information","userAgent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/81.0.4044.129 Safari/537.36","version":"18.0.4.2"}
{"reqId":"zO8YJ7ZaijlxGNNzTe2l","level":2,"time":"2020-04-29T17:17:55+02:00","remoteAddr":"151.20.146.125","user":"admin","app":"mail","method":"GET","url":"/apps/mail/api/accounts/1/folders/SU5CT1g%3D/messages/5251/body","message":"KItinerary binary adapter is not available, can't extract information","userAgent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/81.0.4044.129 Safari/537.36","version":"18.0.4.2"}
{"reqId":"9AEPf7N2jHLoYqFHf56c","level":3,"time":"2020-04-29T17:18:13+02:00","remoteAddr":"151.20.146.125","user":"admin","app":"PHP","method":"GET","url":"/settings/user","message":"Trying to access array offset on value of type null at /var/www/html/nextcloud/3rdparty/leafo/scssphp/src/Compiler.php#5230","userAgent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/81.0.4044.129 Safari/537.36","version":"18.0.4.2"}
{"reqId":"9AEPf7N2jHLoYqFHf56c","level":3,"time":"2020-04-29T17:18:13+02:00","remoteAddr":"151.20.146.125","user":"admin","app":"PHP","method":"GET","url":"/settings/user","message":"Trying to access array offset on value of type null at /var/www/html/nextcloud/3rdparty/leafo/scssphp/src/Compiler.php#5230","userAgent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/81.0.4044.129 Safari/537.36","version":"18.0.4.2"}
{"reqId":"9AEPf7N2jHLoYqFHf56c","level":3,"time":"2020-04-29T17:18:13+02:00","remoteAddr":"151.20.146.125","user":"admin","app":"PHP","method":"GET","url":"/settings/user","message":"Trying to access array offset on value of type null at /var/www/html/nextcloud/3rdparty/leafo/scssphp/src/Compiler.php#5230","userAgent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/81.0.4044.129 Safari/537.36","version":"18.0.4.2"}
{"reqId":"9AEPf7N2jHLoYqFHf56c","level":3,"time":"2020-04-29T17:18:13+02:00","remoteAddr":"151.20.146.125","user":"admin","app":"PHP","method":"GET","url":"/settings/user","message":"Trying to access array offset on value of type null at /var/www/html/nextcloud/3rdparty/leafo/scssphp/src/Compiler.php#5230","userAgent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/81.0.4044.129 Safari/537.36","version":"18.0.4.2"}
{"reqId":"9AEPf7N2jHLoYqFHf56c","level":3,"time":"2020-04-29T17:18:13+02:00","remoteAddr":"151.20.146.125","user":"admin","app":"PHP","method":"GET","url":"/settings/user","message":"Trying to access array offset on value of type null at /var/www/html/nextcloud/3rdparty/leafo/scssphp/src/Compiler.php#5230","userAgent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/81.0.4044.129 Safari/537.36","version":"18.0.4.2"}
{"reqId":"bB0WDH5DPOHoXxpq8bx5","level":2,"time":"2020-04-29T17:18:43+02:00","remoteAddr":"151.20.146.125","user":"admin","app":"mail","method":"GET","url":"/apps/mail/api/accounts/1/folders/SU5CT1guU2VudA%3D%3D/messages/137/body","message":"KItinerary binary adapter is not available, can't extract information","userAgent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/81.0.4044.129 Safari/537.36","version":"18.0.4.2"}
{"reqId":"bB0WDH5DPOHoXxpq8bx5","level":2,"time":"2020-04-29T17:18:43+02:00","remoteAddr":"151.20.146.125","user":"admin","app":"mail","method":"GET","url":"/apps/mail/api/accounts/1/folders/SU5CT1guU2VudA%3D%3D/messages/137/body","message":"KItinerary binary adapter is not available, can't extract information","userAgent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/81.0.4044.129 Safari/537.36","version":"18.0.4.2"}
{"reqId":"wDsrJZZ9hJZkjfVEkbkQ","level":2,"time":"2020-04-29T17:18:43+02:00","remoteAddr":"151.20.146.125","user":"admin","app":"mail","method":"GET","url":"/apps/mail/api/accounts/1/folders/SU5CT1guU2VudA%3D%3D/messages/132/body","message":"KItinerary binary adapter is not available, can't extract information","userAgent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/81.0.4044.129 Safari/537.36","version":"18.0.4.2"}
{"reqId":"wDsrJZZ9hJZkjfVEkbkQ","level":2,"time":"2020-04-29T17:18:43+02:00","remoteAddr":"151.20.146.125","user":"admin","app":"mail","method":"GET","url":"/apps/mail/api/accounts/1/folders/SU5CT1guU2VudA%3D%3D/messages/132/body","message":"KItinerary binary adapter is not available, can't extract information","userAgent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/81.0.4044.129 Safari/537.36","version":"18.0.4.2"}

**Comment by ChristophWurst** [comment]
Logs are clean. Nothing suspicious here.
