### ISSUE TITLE
PHP7.1 - not yet compatible

### ISSUE THREAD

**Issue by raneon** [nextcloud/mail#299]
### Steps to reproduce
1. Install PHP7.1
2. Try to activate mail in nextcloud

### Expected behaviour
Mail can be activated

### Actual behaviour
Mail can't be activated

### Mail app

Not installed yet, as not compatible with PHP7.1

**Mail app version build date:** (only if you are using a Nightly Build)

### Server configuration
Arch Linux 4.9.6
Apache 2.4.25-1
MariaDB 10.1.21
PHP 7.1.1

**Comment by ChristophWurst** [comment]
dup of https://github.com/nextcloud/mail/issues/297 😉

**Comment by Tealk144** [comment]
@ChristophWurst #297 is for php 7.0 and @raneon mean php 7.1
i need an app update to php7.1 too

**Comment by ChristophWurst** [comment]
@Tealk144 that's right. But master is already compatible with 7.1 https://github.com/nextcloud/mail/blob/0f4a7dcab225b8a082466f455461feb92098b0eb/appinfo/info.xml#L24 😉

**Comment by Tealk144** [comment]
Hmm, i get this message
![image](https://cloud.githubusercontent.com/assets/12276250/23130282/1f3ba1fc-f786-11e6-8fc5-a34b8e9b19bf.png)

**Comment by ChristophWurst** [comment]
@Tealk144 with which version of the app? The latest release?

**Comment by Tealk144** [comment]
i think, the webside does not give me a update request

**Comment by ChristophWurst** [comment]
Please be patient, we'll try to push a new release soon. That should fix your problem.
