### ISSUE TITLE
Mail Sync is stucked

### ISSUE THREAD

**Issue by doc75** [nextcloud/mail#2991]
This is a split from #2976 to focus on the partial Sync part.
Following #2980 it appears in the warning message that my Sync is stucked.

**Warning**: The test were done with patch #2978, #2979 and #2980 on top of v1.3.3

### Expected behavior
Background job shall end the sync.

### Actual behavior
Every hour I can see that the number of message cached is not moving:  33989

<details>
  <summary>OCA\Mail\Exception\IncompleteSyncException</summary>

```
{
  "reqId": "XKTFd95F3tvowpUdhaGs",
  "level": 2,
  "time": "2020-04-24T22:16:03+00:00",
  "remoteAddr": "",
  "user": "--",
  "app": "mail",
  "method": "",
  "url": "--",
  "message": {
    "Exception": "OCA\\Mail\\Exception\\IncompleteSyncException",
    "Message": "Initial sync is not complete for 4:INBOX (33989 of 52533 messages cached).",
    "Code": 0,
    "Trace": [
      {
        "file": "/var/www/html/custom_apps/mail/lib/Service/Sync/ImapToDbSynchronizer.php",
        "line": 193,
        "function": "runInitialSync",
        "class": "OCA\\Mail\\Service\\Sync\\ImapToDbSynchronizer",
        "type": "->",
        "args": [
          {
            "__class__": "OCA\\Mail\\Account"
          },
          {
            "id": 72,
            "__class__": "OCA\\Mail\\Db\\Mailbox"
          }
        ]
      },
      {
        "file": "/var/www/html/custom_apps/mail/lib/Service/Sync/ImapToDbSynchronizer.php",
        "line": 108,
        "function": "sync",
        "class": "OCA\\Mail\\Service\\Sync\\ImapToDbSynchronizer",
        "type": "->",
        "args": [
          {
            "__class__": "OCA\\Mail\\Account"
          },
          {
            "id": 72,
            "__class__": "OCA\\Mail\\Db\\Mailbox"
          },
          42,
          null,
          false
        ]
      },
      {
        "file": "/var/www/html/custom_apps/mail/lib/BackgroundJob/SyncJob.php",
        "line": 86,
        "function": "syncAccount",
        "class": "OCA\\Mail\\Service\\Sync\\ImapToDbSynchronizer",
        "type": "->",
        "args": [
          {
            "__class__": "OCA\\Mail\\Account"
          }
        ]
      },
      {
        "file": "/var/www/html/lib/public/BackgroundJob/Job.php",
        "line": 77,
        "function": "run",
        "class": "OCA\\Mail\\BackgroundJob\\SyncJob",
        "type": "->",
        "args": [
          {
            "accountId": 4
          }
        ]
      },
      {
        "file": "/var/www/html/lib/public/BackgroundJob/TimedJob.php",
        "line": 59,
        "function": "execute",
        "class": "OCP\\BackgroundJob\\Job",
        "type": "->",
        "args": [
          {
            "__class__": "OC\\BackgroundJob\\JobList"
          },
          {
            "__class__": "OC\\Log"
          }
        ]
      },
      {
        "file": "/var/www/html/cron.php",
        "line": 124,
        "function": "execute",
        "class": "OCP\\BackgroundJob\\TimedJob",
        "type": "->",
        "args": [
          {
            "__class__": "OC\\BackgroundJob\\JobList"
          },
          {
            "__class__": "OC\\Log"
          }
        ]
      }
    ],
    "File": "/var/www/html/custom_apps/mail/lib/Service/Sync/ImapToDbSynchronizer.php",
    "Line": 256,
    "CustomMessage": "--"
  },
  "userAgent": "--",
  "version": "17.0.5.0"
}
```

</details>

### Mail app

**Mail app version:** 1.3.3 (plus  #2978, #2979 and #2980)

**Mailserver or service:** Dovecot (personal installation)

### Server configuration

**Operating system**: Alpine Linux (official Nextcloud docker image)

**Web server:** Nginx

**Database:** PostgreSQL

**PHP version:** 7.3.16

**Nextcloud Version:** 17.0.5 (official docker image)

#### Client configuration
**Browser:** Firefox 75.0

**Operating system:** Ubuntu 18.04

**Comment by ChristophWurst** [comment]
> Every hour I can see that the number of message cached is not moving: 33989

That is unexpected. Could you lower the log level to 0/debug again so we see which ranges of messages are fetched for the next sync attempt? It's a line that starts with `Built range for findAll` followed by the parameter values..

**Comment by doc75** [comment]
@ChristophWurst any possibility to activate debug mode only for mail app or the only way is to activate it globally for the Nextcloud instance as mentioned [here](https://docs.nextcloud.com/server/17/admin_manual/issues/general_troubleshooting.html?highlight=debug#nextcloud-logfiles) ?

**Comment by ChristophWurst** [comment]
You can only set it globally.

**Comment by doc75** [comment]
Here is the log with `loglevel=0`:
[nextcloud.log](https://github.com/nextcloud/mail/files/4541800/nextcloud.log)

I just changed some directory name into `Dir1`, `Dir3`, etc....
Not sure if there are enough new information to help you understand the reason for the failure.

**Comment by ChristophWurst** [comment]
> Built range for findAll: min=3 max=301081 total=52572 totalRange=301079 estimatedPageSize=28635 lower=88343 upper=116978 highestKnownUid=88342

That's what I was looking for. Thanks!

**Comment by ChristophWurst** [comment]
I figured it out. I think https://github.com/nextcloud/mail/pull/3013 will fix this :)
