### ISSUE TITLE
Support multiple identities

### ISSUE THREAD

**Issue by skadge** [nextcloud/mail#301]
Following what exist in most other webmails (including open-source ones, like mailpile), it would be great if nextcloud could support multiple identities associated to the same email account.

It would allow to select different 'From' field, depending on the recipient.

Ideally, this could be managed from the Personal page by allowing more user to create more than one personal email address. The email app could then reuse these email address to let the user choose his/her identity when composing an email.

**Comment by ChristophWurst** [comment]
Hey @skadge,

this is already supported, called 'aliases'. Check out the settings page of your mail account (see the three-dots-menu in the sidbar next to your account's email address) and add your identities 😉

**Comment by severin-lemaignan** [comment]
Great! [not super easy to discover, though! maybe it should belong to the settings that appear when you click on the 'gear'?]

**Comment by ChristophWurst** [comment]
Well, it's account specific,  therefore we've put it to the account's menu ;-)

**Comment by stweil** [comment]
Was the alias setting removed in Nextcloud 16? I cannot find it in "Konto-Einstellungen" of my mail accounts. I even searched the source code, saw the alias code but no alias text in the localized strings.

Unrelated: I saw that the wrong German text "Verbinde Deine E-Mail-Konto" is in the source code although it was fixed on Transifex several months ago.

**Comment by ChristophWurst** [comment]
> Was the alias setting removed in Nextcloud 16? I cannot find it in "Konto-Einstellungen" of my mail accounts. I even searched the source code, saw the alias code but no alias text in the localized strings.

https://github.com/nextcloud/mail/issues/1722

> Unrelated: I saw that the wrong German text "Verbinde Deine E-Mail-Konto" is in the source code although it was fixed on Transifex several months ago.

Could you double-check? The transifex job is still active and updates https://github.com/nextcloud/mail/blob/3b4cbb40ccae7cfa8092822e562f38cbdb0029cc/l10n/de.js regularily.

**Comment by stweil** [comment]
I saw that the latest update of the mail app included an update from Transifex, but it did not fix the 2 years old wrong German text, so I am not sure what is transferred by the Transifex job. On Transifex I see the correct text.

Thank you for the pointer to the new issue.

**Comment by ChristophWurst** [comment]
Turns out `de` is incorrect while `de_DE` is correct. So the sync works, but translations on transifex are outdated for `de`.

**Comment by stweil** [comment]
Thanks for checking. I wonder whether we really need both variants...
