### ISSUE TITLE
Exception: Authenticated ciphertext could not be decoded. at <<closure>>

### ISSUE THREAD

**Issue by dehnhardt** [nextcloud/mail#3015]
### Actual behavior
Every time the Nextcloud background job is executet (per cron) the following error occurs:

[mail] Error: Exception: Authenticated ciphertext could not be decoded. at <<closure>>

0. /var/www/nextcloud/apps/mail/lib/IMAP/IMAPClientFactory.php line 66
   OC\Security\Crypto->decrypt("*** sensitive parameters replaced ***")
1. /var/www/nextcloud/apps/mail/lib/IMAP/MailboxSync.php line 82
   OCA\Mail\IMAP\IMAPClientFactory->getClient(OCA\Mail\Account {})
2. /var/www/nextcloud/apps/mail/lib/BackgroundJob/SyncJob.php line 91
   OCA\Mail\IMAP\MailboxSync->sync(OCA\Mail\Account {}, true)
3. /var/www/nextcloud/lib/public/BackgroundJob/Job.php line 79
   OCA\Mail\BackgroundJob\SyncJob->run({accountId: 16})
4. /var/www/nextcloud/lib/public/BackgroundJob/TimedJob.php line 61
   OCP\BackgroundJob\Job->execute(OC\BackgroundJob\JobList {}, OC\Log {})
5. /var/www/nextcloud/cron.php line 125
   OCP\BackgroundJob\TimedJob->execute(OC\BackgroundJob\JobList {}, OC\Log {})

at 2020-04-28T09:30:01+00:00

### Mail app

**Mail app version:** 
1.3.4

**Mailserver or service:** 
dovecot 2.3.8 
Pigeonhole version 0.5.8 (b7b03ba2)

### Server configuration

**Operating system**: 
OS: Linux 5.4.6-xen x86_64 Debian 8.11 

**Web server:** 
Apache 2.4.10-10+deb8u16

**Database:** 
Postgresql 12+213.pgdg80+1

**PHP version:** 
PHP 7.3.16-1

**Nextcloud Version:** 
Nextcloud 18.0.4

#### Client configuration
**Browser:** 
Chrome Version 79.0.3945.79 (Offizieller Build) (64-Bit)

**Operating system:** 
Debian 10

Mail search does not work and this might be the reason...

**Comment by ChristophWurst** [comment]
Did you migrate your Nextcloud from one installation to another? The secret in config.php does not match the one that was used to encrypt the mail account password. Does the decryption fails.

**Comment by dehnhardt** [comment]
I only used the internal nextcloud updater. I did not migrate for the last 2 years or longer.

**Comment by ChristophWurst** [comment]
I don't know any other scenario where that error would be thrown. You may consult https://help.nextcloud.com/ for similar tickets. Otherwise you may remove the account and re-add it.

> I did not migrate for the last 2 years or longer.

Mail has had an accounts table for years. Only recently we added the background job. What if that is caused by a user that never logged in since?

**Comment by dehnhardt** [comment]
Thanks for your tipps,!
> I don't know any other scenario where that error would be thrown. You may consult https://help.nextcloud.com/ for similar tickets. Otherwise you may remove the account and re-add it.

That's someting I already did (only the e-Mail account)
> Mail has had an accounts table for years. Only recently we added the background job. What if that is caused by a user that never logged in since?

That could be. In fact, I have a test user who has not been logged in since the mail client started collecting information in the database.
But login as that user did not change anything. Would it be possible to add the problematic user in the error message?

**Comment by ChristophWurst** [comment]
If you lower the log level you'll see which background job caused this. Then you can check the `oc_jobs` table for the entry and find the account id. In `oc_mail_accounts` you'll see which ID and user_id belong together.

**Comment by dehnhardt** [comment]
@ChristophWurst, you where right. 
The error came from unused mail accounts. I deleted them, allowed the mail-app only for a specific group (so no mailboxes accounts are created for 'non mail users') and the error disapperaed! 
Thank you for your help, I will close this issue.
