### ISSUE TITLE
Can't connect to localhost without TLS

### ISSUE THREAD

**Issue by MilchreisMitZimt** [nextcloud/mail#3017]
Hey!

The Mail App tries to use STARTLS for a localhost Connection, althought I have choose "None" at SMTP Security.

I logically have no Certificate for "localhost" and i think it's very inefficient, connecting to the Mailserver on the same Machine through the Internet. 

![image](https://user-images.githubusercontent.com/64473481/80482513-a400de80-8954-11ea-8279-e83254da7716.png)

Mailserver Log:
Apr 28 13:32:12 postfix/postscreen[25864]: CONNECT from [::1]:46340 to [::1]:25
Apr 28 13:32:12 postfix/postscreen[25864]: WHITELISTED [::1]:46340
Apr 28 13:32:12 postfix/smtpd[25869]: connect from localhost[::1]
**Apr 28 13:32:12 postfix/smtpd[25869]: Anonymous TLS connection established from localhost[::1]: TLSv1.2 with cipher ECDHE-RSA-AES128-GCM-SHA256 (128/128 bits)**
**Apr 28 13:32:12 postfix/smtpd[25869]: lost connection after STARTTLS from localhost[::1]**
Apr 28 13:32:12 postfix/smtpd[25869]: disconnect from localhost[::1] ehlo=1 starttls=1 commands=2

![image](https://user-images.githubusercontent.com/64473481/80482648-ddd1e500-8954-11ea-8018-e5023f74914b.png)

**Comment by ChristophWurst** [comment]
See https://github.com/nextcloud/mail/releases/tag/v1.1.4

I don't know why it attempts to switch to StartTLS. That could be a "feature" of the IMAP implementation so it automatically switches to a more secure transport if possible.
