### ISSUE TITLE
Cant see inbox emails after upgrade - Mailboxlockerror

### ISSUE THREAD

**Issue by ChristianPauly** [nextcloud/mail#3019]
### Expected behavior
See the inbox emails without problems.

### Actual behavior
After the last updates the inbox is no longer visible. I only see an endless loading animation. In the logs I have:
```
[INFO] mail: Mailbox is locked Object { app: "mail", uid: "krille", error: MailboxLockedError }
```
Other directories in my email account are visible like "sent" or the delta chat directory.

IMAP and SMTP for my posteo.de address are correct. I have tried SSL and STARTLS.

### Mail app

**Mail app version:** 1.3.4

**Mailserver or service:** Posteo.de

### Server configuration

**Operating system**: Ubuntu 18.04 Raspberry PI

**Web server:** Nextcloud Snap

**Database:** Nextcloud Snap

**PHP version:** Nextcloud Snap

**Nextcloud Version:**  Nextcloud Snap

#### Client configuration
**Browser:** Firefox 75

**Operating system:** Ubuntu 20.04

**Comment by ChristophWurst** [comment]
The Nextcloud mail app offers an extensive logging system to make it easier identifying and tracking down bugs. Please enable [debug mode](https://docs.nextcloud.com/server/stable/developer_manual/general/devenv.html#enabling-debug-mode) and set the log [level to debug](https://docs.nextcloud.com/server/stable/admin_manual/configuration_server/logging_configuration.html) in your admin settings. Then, try to reproduce your issue and take another look at `data/nextcloud.log`, `data/horde_imap.log` and `data/horde_smtp.log`.

**Comment by pete-dawgg** [comment]
i experience the same error and posted about it [nc-forum](https://help.nextcloud.com/t/mail-app-1-3-4-causes-ssl-error-in-dovecot-retrieving-email-impossible/80897/2)
setting `app.mail.verify-tls-peer to false in config.php `allows to (re)create accounts, but the same ssl-error persists (but does not show up in dovcot.log anymore). nextcloud.log is not showing anything of interest.
can i supply any additional info?
(nc 18.0.4 on Debian Buster)

**Comment by ChristophWurst** [comment]
@pete-dawgg I think you should open a new ticket as @ChristianPauly's issue is not related to SSL.

**Comment by krodelabestiole** [comment]
I have the same issue.

```
  'debug' => true,
  'log_type' => 'file',
  'loglevel' => 0,
  'logdateformat' => 'F d, Y H:i:s',
```
using these settings I don't get any data/horde_imap.log or data/horde_smtp.log.
just the same old data/nextcloud.log except it grows extremely fast.

I can't find any relevant info though. nothing with `grep locked`,  `grep imap` or `grep smtp`, and way too much with `grep mail`.

Do you want me to send the log somewhere ? (private)

**Comment by ChristophWurst** [comment]
Please open a separate ticket for the logging issue. It should definitely write the horde files once debug mode is on.
