### ISSUE TITLE
Mail shown twice

### ISSUE THREAD

**Issue by LIyoai** [nextcloud/mail#3021]
### Expected behavior
I see a mail once

### Actual behavior
I see it twice. It is also marked twice when I select one.
![image](https://user-images.githubusercontent.com/6205123/80574913-00bad280-8a03-11ea-9499-ee005e1e875c.png)

### Mail app

**Mail app version:** 1.3.4

**Mailserver or service:** Courier IMAP

### Server configuration

**Operating system**: Debian 10

**Web server:** Apache

**Database:** MariaDB

**PHP version:** 7.3

**Nextcloud Version:** 18.0.4

#### Client configuration
**Browser:** Firefox 75 & Chrome 81

**Operating system:** Windows 10

**Comment by LIyoai** [comment]
And content is sometime from another mail...
I select a mail from cron and see the content from a github reply.
With Roundcube as mail client I have no issues.

**Comment by ChristophWurst** [comment]
I think I fixed this recently when working on https://github.com/nextcloud/mail/pull/2648. We could backport a fix.

> With Roundcube as mail client I have no issues.

What's that supposed to tell us?

**Comment by LIyoai** [comment]
> I think I fixed this recently when working on #2648. We could backport a fix.

good news. Thanks.

> > With Roundcube as mail client I have no issues.

> What's that supposed to tell us?

Just that it's working with another client and that I don't think that it's an issue of my mail server.
