### ISSUE TITLE
add multiple files as attachments from within nextcloud

### ISSUE THREAD

**Issue by mipxx** [nextcloud/mail#3023]
### Feature Request

when creating a new mail, there should be an option to select multiple files from nextcloud

#### Summary
when selecting "Anhang von Dateien hinzufügen"
![Screenshot_20200429_155124](https://user-images.githubusercontent.com/13769683/80604294-d8969800-8a31-11ea-8ebe-5e3df89388e5.png)
you have to repeat the process for every file you want to send.
![Screenshot_20200429_155043](https://user-images.githubusercontent.com/13769683/80604977-bcdfc180-8a32-11ea-840b-28ba5587202e.png)

With an option to select multiple files (from the same Folder) you wouldn't have to navigate to the folder again and again.

**Comment by doc75** [comment]
I just tested and holding Ctrl key during file selection allows to select multiple files at once (tested on Windows).

Do we need to have something specific ? If Yes, then I would suggest to have a drag & drop capability.

**Comment by mipxx** [comment]
holding CTRL isn't working for me (Firefox 75 on Fedora 32)
![Screenshot_20200429_182758](https://user-images.githubusercontent.com/13769683/80621222-4ac5a780-8a47-11ea-9fcd-13872cc9cc4a.png)
only one file is added
![Screenshot_20200429_182807](https://user-images.githubusercontent.com/13769683/80621238-4dc09800-8a47-11ea-8468-d7a6202a6501.png)

**Comment by doc75** [comment]
@mipxx Sorry I missed the fact that you were trying to attach documents from Nextcloud Files application (my fault). I was doing it from my PC instead.

**Comment by ChristophWurst** [comment]
We either have to enable multi select in the file picker if that is supported already or it has to be added there first.

**Comment by ChristophWurst** [comment]
PR is at https://github.com/nextcloud/mail/pull/4136 :)
