### ISSUE TITLE
Dynamic Resizing for 3 main columns

### ISSUE THREAD

**Issue by azon2111** [nextcloud/mail#3030]
### Feature Request

Ability to resize dynamically like other mail apps so you can get more of the email list info and/or turn off email preview as well.

#### Summary

Ability to resize dynamically like other mail apps so you can get more of the email list info and/or turn off email preview as well.

**Comment by jancborchardt** [comment]
Soon it should be possible to hide the navigation/folders part on the left even on desktop, which will give more space.
