### ISSUE TITLE
Updating account failed: Could not connect to IMAP: Authentication failed.

### ISSUE THREAD

**Issue by sunjam** [nextcloud/mail#3031]
### Expected behavior
Account is fully setup

### Actual behavior
Mail is unable to store credentials for IMAP & SMTP password.  I have to constantly re-enter them, even within the same session.
![Screenshot_20200502_080722](https://user-images.githubusercontent.com/1787238/80867937-f9d2d080-8c4b-11ea-9713-73cf7db32124.png)
![Screenshot_20200502_080658](https://user-images.githubusercontent.com/1787238/80867941-fe978480-8c4b-11ea-88b2-e9ebd48e2178.png)

`Fatal Error Updating account failed: Could not connect to IMAP: Authentication failed.`

### Mail app

**Mail app version:**
1.3.4 to hosted cpanel email service on NextcloudPi 19.0.0 beta5
Accessing from Manjaro Linux Stable with Firefox 75

**Comment by ChristophWurst** [comment]
> Mail is unable to store credentials for IMAP & SMTP password.

That is not quite the case. but when we update the account we value every attribute that is transmitted, hence the empty password causes authentication errors. The database remembers the password just fine. But we won't transmit it to the browser as that could allow someone to capture it.
