### ISSUE TITLE
Move mail into another folder does not work (drag and drop)

### ISSUE THREAD

**Issue by avanc** [nextcloud/mail#3050]
### Expected behavior
Select a mail and drag it into another folder should move the mail to that folder.

### Actual behavior
Selecting the mail (click and hold) works and the object is dragable. However, while dropping it, nothing happens and the mail is still in the previous folder.

Tested with Firefox and Chromium.

### Mail app

**Mail app version:** 1.3.3
It seems that no relevant commit for this issue was done between 1.3.3 and 1.3.4

**Mailserver or service:** Domain Factory

### Server configuration

**Operating system**: Arch Linux

**Web server:** Apache

**Database:**  MariaDB

**PHP version:** 7.4.5

**Nextcloud Version:** 18.0.4

#### Client configuration
**Browser:** Firefox 75.0 and Chromium 81.0.4044.129

**Operating system:** Arch Linux

**Comment by ChristophWurst** [comment]
Please use the issue search before opening new tickets: https://github.com/nextcloud/mail/issues?q=is%3Aissue+is%3Aopen+drag+drop

**Comment by avanc** [comment]
Unfortunately, I searched for _move_ instead of _drag an drop_ and reviewed all 37 search results.
Thus I didn't found https://github.com/nextcloud/mail/issues/1538.

Thanks for the hint.
