### ISSUE TITLE
incorrect sender information

### ISSUE THREAD

**Issue by dutch666** [nextcloud/mail#3051]
the listed sender in inbox does not corrospond with the actual sender, 

example i got an email from my grandmother about my ovh account, 
when i open email the sender is ovh

**Comment by ChristophWurst** [comment]
Please use the issue template when reporting bugs and possibly share a screenshot so we can understand the problem better https://github.com/nextcloud/mail/issues/new?assignees=&labels=bug%2C+0.+to+triage&template=bug.md&title=
