### ISSUE TITLE
incorrect senders listed in inbox.

### ISSUE THREAD

**Issue by dutch666** [nextcloud/mail#3053]
### Expected behavior
Tell us what should happen

in your inbox usually an emails sender is listed such as above subject line

github
dutch your posted was closed

### Actual behavior
Tell us what happens instead

instead
it is grabbing random contacts and placing them in the sender section aboce subject line

ex-wife
your ovh server is ready

### Mail app

this only occured after latest update, prior it was presenting properly

**Mail app version:** (see apps admin page, e.g. 0.5.3)

**Mailserver or service:** (e.g. Outlook, Yahoo, Gmail, Exchange,...)

webmail, via horde 

### Server configuration

**Operating system**: (e.g. Debian 8)

linux

**Web server:** (e.g. Apache, Nginx,...)

apache

**Database:** (e.g. MariaDB, SQLite or PostgreSQL)

mysql

**PHP version:** (e.g. 7.0)

7.2

**Nextcloud Version:** (see admin page, e.g. 13.0.2)

18.0.4

#### Client configuration
**Browser:** (e.g. Firefox 48)

all browsers

**Operating system:** (e.g. Arch Linux)

all os, mobile as well

![95033465_593420444604966_4626895678738530304_n](https://user-images.githubusercontent.com/36723240/80986858-2713b000-8dff-11ea-950f-0051641f5df3.jpg)

hope i did this right :)

**Comment by ChristophWurst** [comment]
@nickvergessen you had that once, right?

**Comment by nickvergessen** [comment]
yes, after I reset the mailboxes manually in the database it was reusing entries in other tables which I hadn't purged, but can#t recall which tables were affected
