### ISSUE TITLE
Renaming folders

### ISSUE THREAD

**Issue by ChristophWurst** [nextcloud/mail#3058]
### Feature Request

A user should be able to rename mailboxes.

#### Summary

n/a

**Comment by jancborchardt** [comment]
Design spec:

- In the actions menu of a folder, directly below "Mark all as read" can be an action "Rename folder"
- Icon can be `icon-rename`
- Clicking it will replace the entry with an input field (just like the proposal for adding a folder at https://github.com/nextcloud/mail/issues/2798)
- The input field should have the current folder name prefilled, completely selected so you can choose to adjust the name, or just start typing to replace it.
