### ISSUE TITLE
Forward as attachment

### ISSUE THREAD

**Issue by ChristophWurst** [nextcloud/mail#3060]
### Feature Request

We currently only support cited forwards, but it would be helpful to also allow the original message to be attached.

#### Summary

n/a

**Comment by bernatnan** [comment]
Hi, with this "feature", the attached message will not lost the "links"?

Now, when a mail is forwarded, it lost the "html" (links and others)

**Comment by ChristophWurst** [comment]
yes, the attachment will have the unmodified original message.

**Comment by bernatnan** [comment]
Perfect! Will be a great improve. If you need any test, tell me. Thanks!

**Comment by ChristophWurst** [comment]
WIP PR is at https://github.com/nextcloud/mail/pull/4251

**Comment by bernatnan** [comment]
Hi @ChristophWurst , if I haven't understood wrong, this "issue" has been added int he new release 1.8.0, but I don't see it. I'm wrong?

**Comment by ChristophWurst** [comment]
Please use https://help.nextcloud.com/c/apps/mail/35 for questions. You find the forward option in the multiselect menu.
