### ISSUE TITLE
Edit/compose as new

### ISSUE THREAD

**Issue by ChristophWurst** [nextcloud/mail#3061]
### Feature Request

Allow users to compose a new message based on an existing one. Should most likely be an action on the envelope or the actions in the message details.

#### Summary

n/a

**Comment by ChristophWurst** [comment]
1) Proof that THunderbird has this 
![Bildschirmfoto vom 2020-11-03 20-13-14](https://user-images.githubusercontent.com/1374172/98030487-5b4d4500-1e11-11eb-8228-8a852a86084d.png)

2) Proof that Evolution has this
![Bildschirmfoto vom 2020-11-03 20-13-40](https://user-images.githubusercontent.com/1374172/98030503-64d6ad00-1e11-11eb-8160-ee49fc001923.png)

3) Proof that outlooks has this: https://superuser.com/a/579642
4) Proof that iMail has this:
![](https://ericleeclark.com/wp-content/uploads/2018/11/Screen-Shot-2018-11-10-at-6.43.36-AM-854x385.png)

**Comment by jancborchardt** [comment]
Thanks for the references! Then let’s call it "Edit as new message".

(Also from a list we take as references, let’s remove Evolution and instead take Gmail.)
