### ISSUE TITLE
Display IMAP quota

### ISSUE THREAD

**Issue by ChristophWurst** [nextcloud/mail#3062]
### Feature Request

As a user I want to know how much storage my emails are taking up and how much more space my server allows me to consume. Should go into the account's actions menu or the settings. cc @jancborchardt 

#### Summary

n/a

**Comment by jancborchardt** [comment]
Yep – it would make sense in the account’s actions menu as it is account-specific. :)
First we could just display text, and we can also think about showing a bar like in the bottom left of Files.
