### ISSUE TITLE
Store importance flag on IMAP, if possible

### ISSUE THREAD

**Issue by ChristophWurst** [nextcloud/mail#3069]
### Feature Request

Since #2796 a user can mark messages as important. To make this feature more useful and to improve the integration with other clients (or just another Nextcloud Mail with the same IMAP account), it would be best if we could store the importance flag on IMAP as well. Right now this is only stored in the local cache. This, in turn, means that on a UID change we currently lose these flags. This can be improved in the future with something like a temporary storage and mapping back based on message-ids, but that requires additional work.

Ref https://superuser.com/a/504078/258408
Ref https://tools.ietf.org/html/rfc3501#section-2.3.2
Ref https://tools.ietf.org/html/rfc3501#section-7.1
Ref https://www.rfc-editor.org/rfc/rfc8457.html

#### Summary

Store the importance flag as IMAP keyword if possible.

**Comment by ChristophWurst** [comment]
the only two practical things to do is
* custom keyword. 
  + upside: we could be interoperable when the account is confiugred on more than one nextcloud instance, as well as other IMAP clients
  + downside: it's not supported on all IMAP servers
* a separate table with a mapping of the message-id to the flag
  + downside: possibly the performance as it requires an additional join for every operation on the messages table. but it should be possible. and I'm not 100% if *all* IMAP messages have a truly unique message-id
  + downside: works only one one instance, not interoperable with other clients

**Comment by jancborchardt** [comment]
> the only two practical things to do

If we think about doing both, that would leave these downsides:
- possible performance impact
- if the IMAP server does not support custom keywords, it will not work on non-Nextcloud mail clients

Seeing how point 2 is already the case for the custom keyword anyway and it’s not fixed by the separate table, it makes sense to go with the custom keyword only, and the separate table brings little benefit, right?

**Comment by ChristophWurst** [comment]
> Seeing how point 2 is already the case for the custom keyword anyway and it’s not fixed by the separate table, it makes sense to go with the custom keyword only, and the separate table brings little benefit, right?

I don't get this. We do not have a separate table for this right now. And we can use the custom keyword on only a few IMAP servers.

> If we think about doing both, that would leave these downsides

Sure, just that it's a lot of work. This will generally not happen anytime soon.

**Comment by ChristophWurst** [comment]
Related proposal: https://github.com/nextcloud/mail/issues/3664
