### ISSUE TITLE
CRAM-MD5 authentication

### ISSUE THREAD

**Issue by temuccio** [nextcloud/mail#3070]
### Question
Hi all, 
how I add CRAM-MD5 authetication support for IMAP and SMTP?
For SMTP of Nextcloud system I have added 'mail_smtpauthtype' => 'cram-md5' in accordion of Swfitmailer documentation.
Thanks

**Comment by ChristophWurst** [comment]
> For SMTP of Nextcloud system I have added 'mail_smtpauthtype' => 'cram-md5' in accordion of Swfitmailer documentation.

You are mixing *Nextcloud* and *Nextcloud Mail*. The repo is for the latter. We only support password authentication right now, while *Nextcloud* (for notification and system mail) support more schemes.

**Comment by ChristophWurst** [comment]
Also, as you must have seen questions are supposed to be asked on help.nextcloud.com.

Cheers

**Comment by temuccio** [comment]
Hi @ChristophWurst, I don't mixed _Nextcloud_ with _Nextcloud Mail_, I have ask with the example of _Nextcloud_ but I have understand that this post is for _Nextcloud Mail_.
I have asked here because I have read **question** tags, sorry if I have wrong.
The cram-md5 is an crypted method with password authetication, sorry again

**Comment by ChristophWurst** [comment]
> I have asked here because I have read **question** tags, sorry if I have wrong.

![Bildschirmfoto von 2020-05-07 18-48-54](https://user-images.githubusercontent.com/1374172/81321900-7245f100-9093-11ea-9fed-f6e83a4b71e9.png)

Please open it as a feature request, though someone (you) will have to do as there is currently only you who requested this authentication method: https://github.com/nextcloud/mail/issues/new?assignees=&labels=enhancement%2C+0.+to+triage&template=feature_request.md&title=
