### ISSUE TITLE
New IMAP accounts don't auto populate folders like drafts, trash, etc.

### ISSUE THREAD

**Issue by TheTimeWalker** [nextcloud/mail#3073]
### Expected behavior
When you add in a new IMAP account to the mail app that hasn't done specific actions like sending mails, saving drafts or removing mails then it should auto populate them on the IMAP server so that the left sidebar also has Drafts, Trash, etc. included.

### Actual behavior
Adding such an IMAP account doesn't show any folders like Drafts, Trash, Sent, etc. which means that at specific actions it can force some weird behaviors. For example trying to save a draft fails with an error as it can't find a draft folder: `OCA\Mail\Exception\ServiceException: Drafts mailbox does not exist` or when trying to send a mail it successfully sends but gives an error that it failed with 404 since Sent folder is missing.

The user technically can workaround by manually adding these folders in their account on the Mail app

### Mail app

**Mail app version:** 1.3.4

**Mailserver or service:** One.com

### Server configuration

**Operating system**: Manjaro Linux

**Web server:** NGINX 1.17.7

**Database:** MariaDB

**PHP version:** 7.2

**Nextcloud Version:** 18.0.4

#### Client configuration
**Browser:** Firefox 76

**Operating system:** Manjaro Linux

**Comment by ChristophWurst** [comment]
So you only see the inbox? is it possibly using prefixes and the app wrongly detects your other mailboxes as children of the mailbox? does the house icon of the inbox change into a triange when you hover it?

**Comment by TheTimeWalker** [comment]
After chatting a bit with Christoph, we found out that this mailbox uses an INBOX prefix. There's already an existing issue #2848 which has the exact same problem and behavior with failing to create a drafts folder and showing sending mail as failed even though it worked. So I'm going to close this as duplicate.
