### ISSUE TITLE
Some issues with HTML mail display

### ISSUE THREAD

**Issue by jancborchardt** [nextcloud/mail#3076]
## Border-radius
In the new Nextcloud notification mails, the logo should be in a blue circle. In Nextcloud Mail, it’s a box. Left Geary, right Nextcloud Mail:
![Notification mail](https://user-images.githubusercontent.com/925062/81433761-6165b000-9165-11ea-8c32-67b823144f61.png)

## Images
In the Nextcloud newsletters, images are shown in full, and not as they are scaled. Left Geary, right Nextcloud Mail:
![Mail newsletter images](https://user-images.githubusercontent.com/925062/81433756-5f9bec80-9165-11ea-862c-61019153ac97.png)

**Comment by ChristophWurst** [comment]
Weird. In all browsers?

**Comment by jancborchardt** [comment]
> Weird. In all browsers?

Yep, screenshots are from Firefox, and just tested and confirmed with Chromium – looks exactly the same.

**Comment by MrManor** [comment]
In general I would like to point out that Mails limited and error prone html rendering, is one of the main reasons my users states for preferring the Rainloop mail app. Although it hurts an old text only preferring mailadmin like me, the mail app must be able to render newsletters and such stuff correctly.
