### ISSUE TITLE
.

### ISSUE THREAD

**Issue by barrydegraaff** [nextcloud/mail#3079]

**Comment by barrydegraaff** [comment]
It looks like this is triggered when a mail address is used with a very long length, for example I hit the Unsubscribe on a mailing list from an iphone, this generates and email with the following recipient:

v3_GVRTEZDFMU2DSYRQMMZGEZJSGU4DONJRMQYWEN27GVRTEZDFMU2DSYRQMMZGEZJSGU4DONJRMQYWGN27GVSDENBUMFSGCNBTMMYTSZBQGU2TIMDCMQYTGOC7JZLVM2KNKRTXQWSHJV5E43KSNJHHUZZTJUZES6KOK5LGWWL2MMYVQ6KSMZMTETLNLJDWWOK2NVGTKWSEKJUU2R2WNNHVIRTLJZDVE3KNIRLGWWTKNMZU4RDDGNMWU2DILJCGO6KONVGW2YSYLE4U4V2WNFGVIZ3YLJDU26SONVJGUTT2M4ZU2MSJPFHFOVTLLF5FKMKKNZBHAUCYMRWWG6K2GNIFIVTMLFVEKNCNK5JGUTL2LJVVS6TDGRHHUTTJJVVFM3C2I5GTAWTJLIZWI2RQGFNFOSLYJ5CEM22ZPJGTEWSHJUZU6RDDPJMWUSJRLJLVE2SONVKT2@unsubscribe.emailinboundprocessing.eu

This seems to hammer the performance in the mail app to a point where it can no longer be used.

Perhaps the column in the db is shorter than what is defined in the email spec?

**Comment by barrydegraaff** [comment]
When I remove the message using a different email client, all goes back to normal!

**Comment by ChristophWurst** [comment]
There is no need to clear tickets. Leaving the original report will allow people to find similar problems.
