### ISSUE TITLE
Unified search

### ISSUE THREAD

**Issue by ChristophWurst** [nextcloud/mail#3094]
### Feature Request

Offer a search provider to the unified search in Nextcloud 20+.

Ref https://github.com/orgs/nextcloud/projects/38

#### Summary

n/a

**Comment by severin-lemaignan** [comment]
I believe this is closed by #3433 .

However, the resulting user experience is not great: when you are in the mail app and you are search for an email, your search results are 'polluted' by results from others nextcloud apps that are irrelevant in the context or searching an email.

Worst, in many cases, these other apps are faster to return a result, which means that the first visible results are not even related to the task ('searching for an email').

Power-users might be aware of `in:mail`, but you should not need to be a power user to search in your emails.

=> It seems to me that, while nice on the paper, the 'unified search' approach has some real downsides in practice.

Possible ways forward:
- when in the mail app, the unified search bar _only_ returns results from emails *by default* (with the option to extend to the other apps via eg clicking a buttom)
- have a dedicate search bar for the emails
- ...?

**Comment by ChristophWurst** [comment]
It's indeed done.

And the results from other places is quite literally what unified search is about.

The search will already show Mail results on top.

If there is any follow up issue please open a new ticket.

**Comment by severin-lemaignan** [comment]
Done in #4037 (note that the email results do *not* always show up at the top -- cf screenshot in linked issue)
