### ISSUE TITLE
Delete action behaving differently in priority inbox

### ISSUE THREAD

**Issue by jancborchardt** [nextcloud/mail#3096]
The delete action does nothing in the priority inbox. Or rather it does delete, but there’s no feedback collapse animation as in the unified inbox. A refresh is needed to see the effect.

**Comment by ChristophWurst** [comment]
It's because of https://github.com/nextcloud/mail/blob/1735091174545a41fa0570568d72474525dc6f8e/src/store/actions.js#L586. There we do not use `query` for the messages list, hence it's deleted from the individual (unfiltered) mailbox but not from the filtered list that we use for priority inbox.

**Comment by laurentiu2** [comment]
Isn't this similar to #2487?

**Comment by ChristophWurst** [comment]
This should be fixed by https://github.com/nextcloud/mail/pull/3109
