### ISSUE TITLE
Fix Translation of "All Inboxes" and "New Message"

### ISSUE THREAD

**Issue by MariusBluem** [nextcloud/mail#31]
Ref: https://github.com/owncloud/mail/issues/1545

cc @ChristophWurst @MorrisJobke (for Transifex)

**Comment by ChristophWurst** [comment]
"All Inboxes" is correctly translated for me

"New message" still isn't translated. Apparently it's part of the generated `translations.js` file, however it's missing in the L10n files from Transifex

maybe something we can debug once Transifex has been enabled on this repo. cc @MorrisJobke

**Comment by MorrisJobke** [comment]
Fix for this is in #42

**Comment by MorrisJobke** [comment]
BTW: I already pushed the english versions so the translation can already start ;)

**Comment by MorrisJobke** [comment]
@MariusBluem This can now be translated on transifex. Feel free to ping me if this somehow doesn't work :)

**Comment by ChristophWurst** [comment]
Thanks @MorrisJobke
