### ISSUE TITLE
Mail body doesn't show

### ISSUE THREAD

**Issue by brantje** [nextcloud/mail#310]
### Steps to reproduce
1. Add a mail account
2. Select a mail
3. Message spinner keeps spinning for ever

### Expected behaviour
I would see my mail (html formatted)

### Actual behaviour
An infinite loading spinner:   
![image](https://cloud.githubusercontent.com/assets/2758767/23097418/8c463540-f633-11e6-95fc-5ecd61772915.png)

### Mail app

**Mail app version:** (see apps admin page)
0.6.2

**Mailserver or service:** (e.g. Outlook, Yahoo, Gmail, Exchange,...)
Gandi

**Transport security - IMAP:** (None, SSL, TLS, STARTTLS) 
Imap SSL 993
**Transport security - SMTP:** (None, SSL, TLS, STARTTLS)
imap 587 starttls

**Number of accounts:**
1

**Mail app version build date:** (only if you are using a Nightly Build)

### Server configuration
**Operating system**:
Alpine linux
**Web server:**
nginx
**Database:**
mysql
**PHP version:**
7
**Version:** (see admin page)
11.0.1
**Updated from an older version or fresh install:**
Fresh

#### Client configuration
**Browser:**
Chrome
**Operating system:**
Linux
##### Browser log
<details>

```
mail.min.js?v=839c1c6…:149 Refused to frame 'https://xxxx/apps/mail/accounts/1/folders/SU5CT1g=/messages/73/html' because it violates the following Content Security Policy directive: "frame-src 'self'".

Uncaught DOMException: Failed to read the 'contentDocument' property from 'HTMLIFrameElement': Blocked a frame with origin "https://xxxx" from accessing a cross-origin frame.(…)

```
</details>

**Comment by szilardx** [comment]
I had the same problem with a fresh nginx install.
My issue was bad configuration for https, and setting multiple headers because of not a fresh nginx install.
add_header X-Frame-Options "SAMEORIGIN" 
add_header X-Frame-Options DENY

You could check if this is the problem in the browsers developer tool's console.

**Comment by brantje** [comment]
Response headers:
```
Cache-Control:no-cache, must-revalidate
Connection:keep-alive
Content-Encoding:gzip
Content-Security-Policy:default-src 'none';script-src 'nonce-SlA3SWFNWko0VmdUY2x4bXdyVUtxNnZDMW9Dd1d1YkxsR0pkWmxkK0w1TT06VE1hQlBwNDhyeTRtRVR0U3R2bEc3TWFtNU5uQU5iK1M5azFvSUFVb2R2WT0=' 'unsafe-eval';style-src 'self' 'unsafe-inline';img-src 'self' data: blob:;font-src 'self';connect-src 'self';media-src 'self';frame-src 'self'
Content-Type:text/html; charset=UTF-8
Date:Tue, 21 Feb 2017 16:03:51 GMT
Expires:Thu, 19 Nov 1981 08:52:00 GMT
Pragma:no-cache
Server:nginx/1.6.2
Strict-Transport-Security:max-age=15768000; includeSubDomains; preload
Strict-Transport-Security:max-age=31536000; includeSubDomains
Transfer-Encoding:chunked
X-Content-Type-Options:nosniff
X-Download-Options:noopen
X-Permitted-Cross-Domain-Policies:none
X-Robots-Tag:none
X-XSS-Protection:1; mode=block
```

**Comment by szilardx** [comment]
I am no expert, but expire date could cause the problem here?

**Comment by zincarla** [comment]
In case it helps, I had the same issue behind an nginx proxy. The url I was hitting for the app itself was https, but the inner frame was being attempted as http. (So the frame was being hit by CSP for being a different origin, I guess) I am not sure how to fix this with nextcloud's config, but in nginx, you can add the following to the server element concerning the nextcloud app.
`if ($scheme = http) {
	return 301 https://$server_name$request_uri;
}`
This will force the client browsers to retry all http urls with https. Fixed the issue for me.

**Comment by ChristophWurst** [comment]
Make sure you configure your Nextcloud correctly then a reverse proxy shouldn't be an issue: https://docs.nextcloud.com/server/13/admin_manual/configuration_server/reverse_proxy_configuration.html

**Comment by vlladdrakk** [comment]
I had the a similar issue, the link from @ChristophWurst helped me. I had to add `'overwriteprotocol' => 'https',` to my config.php

**Comment by ChristophWurst** [comment]
Closing as assume this has been resolved.
