### ISSUE TITLE
Spamassassin reports invalid msgid on mails sent by the Mail app

### ISSUE THREAD

**Issue by jaksi** [nextcloud/mail#311]
### Steps to reproduce
1. Open https://www.mail-tester.com
2. Send a mail to the displayed temporary address using Nextcloud Mail
3. Check the results

### Expected behaviour
No spamassassin errors caused by the mail itself

### Actual behaviour
**-1.167** INVALID_MSGID *Message-Id is not valid, according to RFC 2822*

### Mail app

**Mail app version:** (see apps admin page)
0.6.2 (Installed from nightly-20170117)

**Mailserver or service:** (e.g. Outlook, Yahoo, Gmail, Exchange,...)
Dovecot 2.2.27
Postfix 3.1.4

**Transport security - IMAP:** (None, SSL, TLS, STARTTLS) 
TLS

**Transport security - SMTP:** (None, SSL, TLS, STARTTLS)
STARTTLS

**Number of accounts:**
1

**Mail app version build date:** (only if you are using a Nightly Build)
20170117

**Comment by Quix0r** [comment]
How is the mail delivery done? Bare `mail()` command or some other higher functions used? I would't then maybe recommend to use PHPMailer: https://github.com/PHPMailer/PHPMailer to let it do the low-level work.

**Comment by rullzer** [comment]
Just tested this. This seems to be fixed now.
