### ISSUE TITLE
Add menu entry to discard draft

### ISSUE THREAD

**Issue by mat-m** [nextcloud/mail#3115]
### Feature Request

When I create, reply to or forward a message, The current folder is still displayed. I don't have an option to discard the draft and remove it from the Drafts folder.
If I dismissed the draft, it fills the Drafts folder of the matching sender's mailbox.
I would like to have an entry to discard my draft without havong to dismiss, my email, going to the Drafts folder of the matching account and delete the draft.
This way, dismissing the draft keep it saved in Drafts. Discarding should be a clear action and not implied.

#### Summary

Ability to discard a draft from the create Message window

Some leads:
* One more entry in the 3-dots drop-down
* A smaller button after the **Send** one, named "Discard" or "Cancel" or with a recycle bin icon
* A cross symbol or a recycle bin symbol at the top-right corner of the message window

**Comment by ChristophWurst** [comment]
Good point. This is tracked in https://github.com/nextcloud/mail/issues/2492 :)
