### ISSUE TITLE
comming from: evey new version is worse.

### ISSUE THREAD

**Issue by bgman111111** [nextcloud/mail#3127]
comming from here: https://github.com/nextcloud/jsxc.nextcloud/issues/149

This is csecond time IM GONNA COMPLAINT. FCUK. YOURSELF. im not developer AND I NEED DAYS TO SOLVE developers bugs. LOOKING IN INTERNET. EVERY new version of nextcloud mail and nextcloud jxs ARE WROSE. they don't work. WHY developers DON'T PUT THEY GLASSES AND TEST IT BEFORE IT RELEASE. MAKE TO CHOOSE BEETWEEN cram-md5 or plain EVERY TIME PERSON CHOOSE IT. not server decice OR IF IT IS in localhost THEY USE plain, IT WILL COME ERROR.  THERE IS MORE GOOD FROM plain. CRAM-MD5 SASL AND ETC. i want to use them. I TRY CHANGE use_cram-md5 AND again it comment PLAIN now i an't use it on server INCLUDE IT DONT wqork in gmail it comment error. IM COMPLAINING nextcloud it speak for you BAD how ytou make this wonderfully server and there is STUPID women developers WHO BROKE nexrtcloud. THIS IS INSULTING ALL peoples. if they release new version TEST IT FUCK YOURSELF.

**Comment by ChristophWurst** [comment]
https://nextcloud.com/code-of-conduct/

**Comment by rullzer** [comment]
I'm not even going to quote our code of conduct because this violates even the basic level of decent interaction. I ask everybody to communicate in a respectful manner. Such offensive, sexist and out of place posts will not be tollerated.
