### ISSUE TITLE
Unified folders for other special folders (Favorites, Drafts, Sent, Trash)

### ISSUE THREAD

**Issue by jancborchardt** [nextcloud/mail#313]
I mostly work in the unified inbox. When going to another folder like Trash for recovering a deleted message, I regularly don’t know where that message went to because I deleted it out of the unified inbox. Same for favorites and sent. Much nicer would be unified folders for these other special-use folders too.

@nextcloud/mail

**Comment by ChristophWurst** [comment]
Can be added easily as soon as I have rewritten the unified inbox. #271 kinda blocks this.

**Comment by jancborchardt** [comment]
Ah cool, so that’s safe for testing now? Will try it! :)

**Comment by ChristophWurst** [comment]
I hope so 😉

**Comment by jancborchardt** [comment]
@ChristophWurst let me know as soon as something for this is testable! :) Looking forward a lot to it.

**Comment by jancborchardt** [comment]
Closing in favor of https://github.com/nextcloud/mail/issues/45 by the way, @quix0r was quicker! :)
