### ISSUE TITLE
Mail app disabled at every docker restart.

### ISSUE THREAD

**Issue by Ornias1993** [nextcloud/mail#3130]
### Expected behavior
All apps should stay the way they are (enabled/disabled) with every docker reboot. (as app status isn't kept in docker anyway.

### Actual behavior
Mail keeps getting disabled at every docker restart

### Mail app
1.3.5

### Server configuration

**Operating system**: 
Host: deb 10.
docker: latest

**Web server:** (e.g. Apache, Nginx,...)
Apache (docker)

**Database:** (e.g. MariaDB, SQLite or PostgreSQL)
MariaDB (external)

**PHP version:** (e.g. 7.0)
docker version (I think 7.3 or 7.4)

**Nextcloud Version:** (see admin page, e.g. 13.0.2)
Latest, 8.0.4 (I think)

#### Client configuration
**Browser:** 
All (problem is browser agnostic)

**Operating system:** (e.g. Arch Linux)
All (problem is OS/client agnostic)

**Comment by ChristophWurst** [comment]
Nextcloud won't disable an app "just so". There is always a reason. Check your logs.

**Comment by Ornias1993** [comment]
@ChristophWurst

Whoops missed your response.
There is nothing in the logs, even not in debug... Thats what is the weird thing.

**Comment by ChristophWurst** [comment]
Lower your log level. There has to be something.

**Comment by Ornias1993** [comment]
Couldn't reproduce last reboot... closing...
