### ISSUE TITLE
Orphaned mail accounts throw errors after removing a user

### ISSUE THREAD

**Issue by florianwgnr** [nextcloud/mail#3135]
### Actual behavior

_IMAP errorAuthentication failed_ error are logged and i could not explain why.

### what i did
i removed the mail accounts of all users (except mine) but the mail app keeps throwing these errors. 

### what i found 

the "oc_mail_accounts" table in my installation contains - beside my mail accounts - two orphaned mail accounts related to recently deleted users.

While i removed these users from my nextcloud installation, i also disabled their mailboxes at our provider. I thought that nextcloud mail accounts are automatically removed while removing a users account but it is not the case. 

### what is causing the problem

maybe the cronjob tries to check these orphaned accounts on a regular basis and therefore throws up these errors, because the credentials for these accounts are not working anymore. 

Might be linked to #2929 as well.

### Expected behavior

removing nextcloud accounts should automatically remove the corresponding mail account. 

### Mail app

**Mail app version:** 1.3.5

**Mailserver or service:** own

### Server configuration

**Operating system**: debian

**Web server:** apache

**Database:** mysql

**PHP version:** 7.3

**Nextcloud Version:** latest

**Comment by ChristophWurst** [comment]
This should be fixed with #3009/https://github.com/nextcloud/mail/pull/3102

**Comment by ChristophWurst** [comment]
Unless the user was deleted before v1.3.5, the logic should work.

**Comment by florianwgnr** [comment]
> 
> 
> Unless the user was deleted before v1.3.5, the logic should work.

I updated the mail app half an hour ago (to 1.3.5) and tried it with new accounts and it did not remove the added mailboxes.

Procedure with current version: add user -> run cron -> add mailbox  -> run cron -> delete user -> run cron -> checked database -> mail account is still there.

**Comment by ChristophWurst** [comment]
What version of Nextcloud are you running? Latest is very vague.

Please use our issue template next time :pray:

**Comment by ChristophWurst** [comment]
I can confirm the bug. Please check out https://github.com/nextcloud/mail/pull/3137.
