### ISSUE TITLE
Email hosting provider does not require IMAP or SMTP security and this seems to be a problem

### ISSUE THREAD

**Issue by CrazyEyesPete** [nextcloud/mail#3143]
Operating system: Linux 3.10.0-962.3.2.lve1.5.33.el7.x86_64 #1 SMP Fri Mar 13 09:20:40 EDT 2020 x86_64

Webserver: Apache (litespeed)

Database: mysql 10.3.23

PHP version: 7.3.17

Modules loaded: Core, date, libxml, openssl, pcre, zlib, filter, hash, Reflection, SPL, session, standard, litespeed, bcmath, bz2, calendar, ctype, curl, dba, dom, enchant, mbstring, fileinfo, ftp, gd, gettext, iconv, imap, intl, json, ldap, exif, mysqlnd, odbc, PDO, pgsql, Phar, posix, pspell, shmop, SimpleXML, snmp, soap, sockets, sqlite3, sysvmsg, sysvsem, sysvshm, tokenizer, xml, xmlwriter, xsl, zip, mysqli, pdo_mysql, PDO_ODBC, pdo_pgsql, pdo_sqlite, wddx, xmlreader, xmlrpc, imagick, redis, ionCube Loader, Zend OPcache

Nextcloud version: 18.0.3 - 18.0.3.0

Steps to replicate it:

    Try to enter my email server details and credentials.

My email hosting provider does not require any IMAP/SMTP security - only username and password. I am able to access and use this particular email account in Thunderbird, Outlook, GMail, and K9 Mail on my phone but I can not get Nextcloud Mail app to work. I get a very generic “Unexpected Error” when trying to add the email account.

I have both IMAP and SMTP security set to NONE in the manual creation and use the same settings/ports that successfully work with Thunderbird, Outlook, K9, etc)

##server log##
Fatal mail Creating account failed: Could not open secure TLS connection to the server.
2020-05-19T17:39:14-0400
Debug mail Connecting to account eric.meadows@wvlandgroup.com	
2020-05-19T17:39:13-0400
Info mail Setting up manually configured account

When I set up the email settings in “Basic Settings” of the Admin section and use the same credentials it successfully sends the test email. I set the SMTP encryption to ‘None’ and Authentication to ‘Login’ and I get the email delivered to my gmail account.

But, alas, I can not get the mail app to work with our email hosting provider - we are a small business and have 4-5 employees wanting to use Nextcloud with their email.

This has been happening for 3 months through 2-3 Nextcloud and Mail app updates. Any thoughts would be appreciated.

**Comment by CrazyEyesPete** [comment]
Anyone have an idea on this one? It looks as if I'm selecting to choose 'none' in the authentication, but the Mail App is still looking for something to authenticate against.

**Comment by ChristophWurst** [comment]
> Could not open secure TLS connection to the server.

See https://github.com/nextcloud/mail/releases/tag/v1.1.4. YOu have to disable the TLS verification.
