### ISSUE TITLE
Load folders with slash in folderId

### ISSUE THREAD

**Issue by hartois** [nextcloud/mail#3157]
### Expected behavior
Load messages in folder

### Actual behavior
Request 
```
https://cloud.local/apps/mail/api/accounts/418/folders/0J7RgtC%2F0YDQsNCy0LvQtdC90L3Ri9C1/messages
```
is redirected to /apps/files/ because "%2F" is rewriten to "/" in 
```
Symfony\Component\Routing\Matcher\UrlMatcher::match()
```
by rawurldecode() function
Source: 
```
3rdparty/symfony/routing/Matcher/UrlMatcher.php:88
```
and route pattern not found

Localized folderId: Отправленные
Encoded folderId: 0J7RgtC/0YDQsNCy0LvQtdC90L3Ri9C1

![image](https://user-images.githubusercontent.com/11641656/83000069-8b96e900-a012-11ea-986f-38ba0a215098.png)

### Mail app

**Mail app version:** 1.3.5

**Mailserver or service:** Kopano

### Server configuration

**Operating system**: CentOS 7

**Web server:** Nginx+PHP-FPM

**Database:** MariaDB

**PHP version:** 7.3

**Nextcloud Version:** 18.0.4

#### Client configuration
**Browser:** YandexBrowser 20.3.2.282 (Chrome engine)

**Operating system:** Fedora

**Comment by ChristophWurst** [comment]
> folders/0J7RgtC%2F0YDQsNCy0LvQtdC90L3Ri9C1/messages

So the raw mailbox name is `Отправленные`. Base64 encoded that gives `0J7RgtC/0YDQsNCy0LvQtdC90L3Ri9C1`.

**Comment by ChristophWurst** [comment]
Duplicate of https://github.com/nextcloud/mail/issues/170, actually. I wrongly closed the other one apparently as I identified and fixed a related issue.

**Comment by hartois** [comment]
Is there any news on this bug?

**Comment by ChristophWurst** [comment]
No

**Comment by hartois** [comment]
Latest version (1.7.0) work fine, thanks
