### ISSUE TITLE
Mail app 0.6.2 won't enable Error: this app cannot be enabled because it makes the server unstable

### ISSUE THREAD

**Issue by TheHulk000** [nextcloud/mail#316]
### Steps to reproduce
1. uploaded to /app/mail
2. changed ownership to www-data
3. found app in not enabled category (it was not in Productivity) and enabled 

### Actual behaviour
after i enable the app it says Error: this app cannot be enabled because it makes the server unstable
and disables it self. 
I have tried it with the nightly builds and then nextcloud loads a blank screen. 
### Mail app

**Mail app version:0.6.2

Nexcloud version 11.0.1

**Comment by jancborchardt** [comment]
Any idea @nextcloud/mail @LukasReschke @schiessle?

**Comment by ChristophWurst** [comment]
The app was probably installed wrongly, with a git clone. Please use a release from the app store instead.

**Comment by ChristophWurst** [comment]
> uploaded to /app/mail

Please provide more details for this step 😉

**Comment by TheHulk000** [comment]
The mail app is nowhere to be found in any of the categories on a fresh install. i can see and enable the other apps. 

I followed this guide 
Nightly builds

Instead of setting everything up manually, you can just download the nightly builds instead. These builds are updated every 24 hours, and are pre-configured with all the needed dependencies.

    Download
    Extract the tar archive to 'path-to-nextcloud/apps'
    Navigate to »Apps«, choose the category »Productivity«, find the Mail app and enable it.

The nightly builds are provided by Portknox.net

Like i said when i upload the nightly build nextcloud will not load all i get is a blank page.

**Comment by ChristophWurst** [comment]
It should be available there. Where did you install Nextcloud from? Could you provide all the steps required to reproduce the problem?

**Comment by TheHulk000** [comment]
I used this guide : https://www.linux.com/learn/how-install-nextcloud-server-ubuntu
There was one thing i had to do differently.

This command in the guide did not work : CREATE USER nextclouduser@localhost IDENTIFIED BY ‘PASSWORD’; 
I used webmin to create the user name and password. 

The rest is exactly according to the guide.

**Comment by ChristophWurst** [comment]
So you're on NC9 right?

**Comment by TheHulk000** [comment]
Nexcloud version 11.0.1 currently

**Comment by TheHulk000** [comment]
So i upgraded to version 11.0.1 which i originally thought i was on and all is working dine now. 
Thanks for the responses i appreciate the help.

**Comment by ChristophWurst** [comment]
Great to hear it's working now!
