### ISSUE TITLE
Can not enable formatting in composer

### ISSUE THREAD

**Issue by ChristophWurst** [nextcloud/mail#3163]
### Expected behavior
No errors. Formatting can be enabled.

### Actual behavior
:boom:  ``Computed property "editorPlainText" was assigned to but it has no setter.``

### Mail app

**Mail app version:** master (v1.4.x)

**Comment by wiswedel** [comment]
Duplicate of https://github.com/nextcloud/mail/issues/3114

**Comment by ChristophWurst** [comment]
I'm aware of the other one. However, #3114 did not show a Vue error while this one did. But on a second thought that's most likely because I tested the other one on a production system and this one with a dev build.

Thanks.
