### ISSUE TITLE
Improve caching & preloading for better performance [$25]

### ISSUE THREAD

**Issue by jancborchardt** [nextcloud/mail#317]
Often when I use the search and go through mails (mostly deleting them), it takes a lot of time to load the next mail after I delete one. It would be cool if when you open a view, or make a search, the content of the batch of mails is actually preloaded.

**Comment by ChristophWurst** [comment]
Agreed. Still, we have to work on the server-side implementation too, I have the feeling we could do a lot better there in terms of performance.

**Comment by ChristophWurst** [comment]
To potential bounty hunters:

1. Let us know when you plan working on this
2. Let's discuss the implementation together
3. …
4. Profit

**Comment by RNCTX** [comment]
```
107.202.13.161 - - [02/Apr/2020:12:47:14 -0500] "GET /apps/mail/ HTTP/2.0" 200 8587 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_3) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/80.0.3987.149 Safari/537.36"
127.0.0.1 - - [02/Apr/2020:12:47:14 -0500] "GET /stub_status HTTP/1.1" 200 104 "-" "-"
107.202.13.161 - - [02/Apr/2020:12:47:14 -0500] "GET /ocs/v2.php/apps/notifications/api/v2/notifications HTTP/2.0" 200 74 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_3) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/80.0.3987.149 Safari/537.36"
127.0.0.1 - - [02/Apr/2020:12:47:15 -0500] "GET /stub_status HTTP/1.1" 200 104 "-" "-"
127.0.0.1 - - [02/Apr/2020:12:47:16 -0500] "GET /stub_status HTTP/1.1" 200 104 "-" "-"
127.0.0.1 - - [02/Apr/2020:12:47:17 -0500] "GET /stub_status HTTP/1.1" 200 104 "-" "-"
127.0.0.1 - - [02/Apr/2020:12:47:18 -0500] "GET /stub_status HTTP/1.1" 200 104 "-" "-"
127.0.0.1 - - [02/Apr/2020:12:47:19 -0500] "GET /stub_status HTTP/1.1" 200 104 "-" "-"
127.0.0.1 - - [02/Apr/2020:12:47:20 -0500] "GET /stub_status HTTP/1.1" 200 104 "-" "-"
127.0.0.1 - - [02/Apr/2020:12:47:21 -0500] "GET /stub_status HTTP/1.1" 200 104 "-" "-"
127.0.0.1 - - [02/Apr/2020:12:47:22 -0500] "GET /stub_status HTTP/1.1" 200 104 "-" "-"
127.0.0.1 - - [02/Apr/2020:12:47:23 -0500] "GET /stub_status HTTP/1.1" 200 104 "-" "-"
127.0.0.1 - - [02/Apr/2020:12:47:24 -0500] "GET /stub_status HTTP/1.1" 200 104 "-" "-"
127.0.0.1 - - [02/Apr/2020:12:47:25 -0500] "GET /stub_status HTTP/1.1" 200 104 "-" "-"
107.202.13.161 - - [02/Apr/2020:12:47:26 -0500] "GET /apps/mail/api/accounts/1/folders/SU5CT1g%3D/messages HTTP/2.0" 200 2164 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_3) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/80.0.3987.149 Safari/537.36"
127.0.0.1 - - [02/Apr/2020:12:47:26 -0500] "GET /stub_status HTTP/1.1" 200 104 "-" "-"
127.0.0.1 - - [02/Apr/2020:12:47:27 -0500] "GET /stub_status HTTP/1.1" 200 104 "-" "-"
107.202.13.161 - - [02/Apr/2020:12:47:28 -0500] "GET /apps/mail/api/accounts/1/folders/SU5CT1g%3D/messages/35530 HTTP/2.0" 200 368 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_3) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/80.0.3987.149 Safari/537.36"
127.0.0.1 - - [02/Apr/2020:12:47:28 -0500] "GET /stub_status HTTP/1.1" 200 104 "-" "-"
127.0.0.1 - - [02/Apr/2020:12:47:29 -0500] "GET /stub_status HTTP/1.1" 200 104 "-" "-"
127.0.0.1 - - [02/Apr/2020:12:47:30 -0500] "GET /stub_status HTTP/1.1" 200 104 "-" "-"
127.0.0.1 - - [02/Apr/2020:12:47:31 -0500] "GET /stub_status HTTP/1.1" 200 104 "-" "-"
```


![ezgif com-video-to-gif](https://user-images.githubusercontent.com/13775820/78283268-28417c80-74e3-11ea-9452-8109f218c916.gif)

This is on a gmail account with ~9000 messages. The above netdata log is immediately after clicking the mail tab in the header, and waiting until the load finishes. Current nextcloud (18.0.3), without any other users on the system, just the admin logged in on a fresh install, on a 2 CPU / 4GB RAM linode VPS.  OnlyOffice is installed and Postgres is tuned for 2gb of available memory.

**Comment by RNCTX** [comment]
Just installed the beta linked in the help forums, after initial caching the performance is GREATLY improved :D.

**Comment by ChristophWurst** [comment]
> Just installed the beta linked in the help forums, after initial caching the performance is GREATLY improved.

Thanks so much. I really appreciate the feedback!

**Comment by ChristophWurst** [comment]
I guess this feature is mostly done via https://github.com/nextcloud/mail/pull/1956 and https://github.com/nextcloud/mail/pull/2064

**Comment by ChristophWurst** [comment]
> This is on a gmail account with ~9000 messages.

Was that with 1.1.4 or the beta?

**Comment by RNCTX** [comment]
That was on 1.1.4.

On the beta the performance is only slightly less performant for me than Gmail's web interface.  I can only tell a difference when scrolling down past the default number that are initially prefetched, and when loading an actual message (which is probably a function of my low-end server hardware more than the software).

**Comment by ChristophWurst** [comment]
So if I interpret these measurements correctly, the load was decreased significantly :fireworks:

**Comment by RNCTX** [comment]
Yeah I know they're hard to see scaled down but the moving meters are, left to right... disk I/O, CPU, and network traffic.

After the initial cache of existing mail, what was 50-55% CPU on initial page load went down to 4%, and peak bandwidth usage during page load went down from 6 Mbps to about 500 Kbps.

I'm using Redis, the disk usage of course will vary depending on each user's cache setup I suppose.

**Comment by ChristophWurst** [comment]
> It's not _quite_ as snappy as the Gmail web interface but close ;).

haha guess they have like 50x as many people working on their app but fair enough :grin:

**Comment by RNCTX** [comment]
Yeah, I meant that as a compliment.  I'm sure if you could cache every single image on the internet like Google can, you could probably find 250ms here and there too!

**Comment by ChristophWurst** [comment]
Btw you're famous now: https://nextcloud.com/blog/mail-1-3-introduces-mail-cache-improved-signatures-link-shares-mark-all-read-and-more/ :)

**Comment by ChristophWurst** [comment]
Done via #1956 and #2064

**Comment by ChristophWurst** [comment]
hey @johanlives the ticket at https://www.bountysource.com/issues/42324763-improve-caching-preloading-for-better-performance does not close. can you help?
