### ISSUE TITLE
error connecting to mail server

### ISSUE THREAD

**Issue by guygro** [nextcloud/mail#3173]
Hi,

the mail app works as long as I'm logged in as an **admin**. I can send and receive test mails.

When I log in as a **user** my access data seem to be correct, as there is no error notification and the account is shown on the left side. But it fails to connect to the e-mail server. It just starts loading and never stops. 

Has anyone got an idea what I'm doing wrong? Is it because of user rights and restrictions?

I'm currently using Nextcloud 18 and Mail 1.3.5

Guy

**Comment by guygro** [comment]
Could it be that there are too many mails in the account?

**Comment by guygro** [comment]
Could it be that there are too many mails in the account?

**Comment by ChristophWurst** [comment]
Is this a support request? Then please use https://help.nextcloud.com/.


If you want to report a bug then you should also use the appropriate template as you saw the picker at https://github.com/nextcloud/mail/issues/new/choose.
