### ISSUE TITLE
size of email account restricted?

### ISSUE THREAD

**Issue by guygro** [nextcloud/mail#3174]
Hi,
is there a limit to the size of email accounts? As I am not able to use your mail app, even though all the login data seem to be correct. The account however comprises 1600 MB.

**Comment by ChristophWurst** [comment]
Questions should still be raised at the forums as you should have just read in the template
![Bildschirmfoto von 2020-06-02 11-22-15](https://user-images.githubusercontent.com/1374172/83503456-60554380-a4c3-11ea-916f-40c03ec4b1fe.png)

and no, there is no limit. It might just take longer to initially read your data. Run `occ mail:account:diagnose <account ID>` and share the results with us on the forums. We can discuss possible issues then. The storage consumption of an account does not really matter for this app. We only really care about the number of messages.
