### ISSUE TITLE
Change attachments icon to paper-clip

### ISSUE THREAD

**Issue by wiswedel** [nextcloud/mail#3177]
The existence of an attachment is currently marked with a link icon:

![image](https://user-images.githubusercontent.com/1804221/83570790-f4a4c200-a526-11ea-9600-ea613a0d455d.png)

I suggest to change it to the worldwide standard icon: the paper-clip

![image](https://user-images.githubusercontent.com/1804221/83570947-303f8c00-a527-11ea-9830-ba37cbfe1153.png)
.

**Comment by ChristophWurst** [comment]
@GretaD @jancborchardt what do you think?

We use the icon consistently throughout our interface. If we change it here, it also has to change in the message list and so on.

**Comment by alexanderdd** [comment]
I suggest to close this in favor of https://github.com/nextcloud/mail/issues/4181 - there they also talk about the icon, but also about better display of attachments.

**Comment by GretaD** [comment]
Lets continue here: #4181
