### ISSUE TITLE
Attachments indicator improvements

### ISSUE THREAD

**Issue by wiswedel** [nextcloud/mail#3178]
The attachments indicator icon/button in the reading view is quite hard to find while it's sticking at the emails bottom. For better visibility, why not put it somewhere in the header area?

**Comment by ChristophWurst** [comment]
@jancborchardt @GretaD

**Comment by jancborchardt** [comment]
The implementation does not reflect the intended design yet. It should not be just a circular button with icon, but also have text like "2 attachments", and ideally also small previews of the attachments on the left of the text.

**Comment by ChristophWurst** [comment]
Let's continue in https://github.com/nextcloud/mail/issues/4181
