### ISSUE TITLE
JS error when adding a second account

### ISSUE THREAD

**Issue by ChristophWurst** [nextcloud/mail#320]
While testing https://github.com/nextcloud/mail/pull/271 I noticed that sometimes a js error is thrown after adding a second account. Once I reloaded the page, everything worked like a charm, so I suspect it's just the transition that has some issues.

**Comment by jancborchardt** [comment]
Same here:

> Error while loading the accounts.
> TypeError: Cannot read property 'first' of undefined

Then I end in this state:
![capture du 2017-03-29 17-28-21](https://cloud.githubusercontent.com/assets/925062/24462782/3404ea80-14a5-11e7-8240-f4fb49414c83.png)

**Comment by ChristophWurst** [comment]
Fix is in https://github.com/nextcloud/mail/pull/390
