### ISSUE TITLE
Folder list should be sorted alphabetical

### ISSUE THREAD

**Issue by avanc** [nextcloud/mail#321]
### Steps to reproduce
1. Configure mail
2. Expand Inbox to show all sub-folders

### Expected behaviour
The list of folders should be sorted alphabetical

### Actual behaviour
The sorting looks randomly

### Mail app

**Mail app version:** (see apps admin page)
0.6.2

**Mailserver or service:** (e.g. Outlook, Yahoo, Gmail, Exchange,...)
Domain Factory

**Transport security - IMAP:** (None, SSL, TLS, STARTTLS) 
SSL

**Transport security - SMTP:** (None, SSL, TLS, STARTTLS)
SSL

**Number of accounts:**
2

**Mail app version build date:** (only if you are using a Nightly Build)
n/a

### Server configuration
**Operating system**:
Arch Linux

**Web server:**
Apache

**Database:**
MariaDB

**PHP version:**
7.X

**Version:** (see admin page)
11.0.1

**Updated from an older version or fresh install:**
updated

**Comment by ChristophWurst** [comment]
Could you maybe post a screenshot of the folder list (if that doesn't contain any personal information you don't want to share publicly)?

**Comment by avanc** [comment]
This is a snipped of some of my folders:
![folders](https://cloud.githubusercontent.com/assets/2905029/23263216/d6b6d474-f9dd-11e6-8053-f37039d06772.PNG)

**Comment by avanc** [comment]
Problem not reproducable with latest version (0.6.3)
