### ISSUE TITLE
a11y: Leverage Mail app accessibility

### ISSUE THREAD

**Issue by yplassiard** [nextcloud/mail#3213]
### Feature Request

Although non critical, it could speed up the way blind and visually impaired users can use this app. With fewchanges within templates, the mail app navigation could change from "somewhat difficult to use" to "smooth and handy".

#### Summary

Using ARIA attributes, it could be very easy to make this app  more accessible.

##### Message list

- Adds a role="heading" aria-level="2" to the div containing the list of messages so that the user can quickly skip to the list.
- For each list item, encapsulate the From, Subject and Date into a role="heading" aria-level="3" to quickly jump to a specific message.
- In the same element, add the "Unread" text before the sender's name if the message is unread.
- Identify the global action buttons (new message, delete, ...) within either a complementary region or add a level 5 heading before the button bar.

##### Message content

- Encapsulate the message's body within a region explicitly named "message body" (to be localized), or prepend the message body with a h3 title.

##### behavior

- when a message is open, setting the focus to its subject(currently marked as "h2" title) could be a good way to save time. Note that you'd need to use the tabindex attribute to make this element focusable for screen reader. If you do not want to explicitly set a tab index order for all elements of the page, a tabindex="0" is fine.
- Make loading and error template appear with a role="alert" so that screen reader can read them when the message is visible. This can also be good to have this role="alert" for any error or information messages that are present on the page, like "message sent" for example.

Should you need any help implementing this, feel free to contact me.

**Comment by jancborchardt** [comment]
Hi @yplassiard, awesome list of improvements, thank you so much! Sorry for the late reply – since you offered your help, is this still something you are interested in doing for example contributing via a pull request?

Also cc @GretaD who could help regarding frontend.

**Comment by GretaD** [comment]
Hello @yplassiard, I started a PR here #4211 with your first 2 points, you can check it out and push changes if you have some time. I will check it out later this week again.

**Comment by GretaD** [comment]
The only point here left to be done is > _the "Unread" text before the sender's name if the message is unread._
