### ISSUE TITLE
Showing two Junk Links in the side navigation bar

### ISSUE THREAD

**Issue by RajatJain4061** [nextcloud/mail#3222]
### Expected behavior
Tell us what should happen
It should show only 1 Junk Folder link

### Actual behavior
Tell us what happens instead
It is showing two junk folders. The second one is the actual junk folder.

### Mail app

**Mail app version:** (see apps admin page, e.g. 0.5.3)
1.3.5

**Mailserver or service:** (e.g. Outlook, Yahoo, Gmail, Exchange,...)
Custom

### Server configuration

**Operating system**: (e.g. Debian 8)
Ubuntu 18+

**Web server:** (e.g. Apache, Nginx,...)
Apache
**Database:** (e.g. MariaDB, SQLite or PostgreSQL)
MySql
**PHP version:** (e.g. 7.0)
7+
**Nextcloud Version:** (see admin page, e.g. 13.0.2)
18.x
#### Client configuration
**Browser:** (e.g. Firefox 48)
All Browsers
**Operating system:** (e.g. Arch Linux)
All

![Screenshot from 2020-06-08 21-01-55](https://user-images.githubusercontent.com/10336073/84051058-38d30f00-a9cc-11ea-8047-30d8bbbea0ed.png)

**Comment by ChristophWurst** [comment]
Does it possibly localize them? There should be a ... menu for each mailbox. If you click it, it will show the real mailbox name as the first entry in the menu. I hope that helps clear the confusion about why this is shown twice.

**Comment by RajatJain4061** [comment]
I tried to check the localization files but not found anything duplicate there related to Junk. I have only 1 mailbox connected.

**Comment by ChristophWurst** [comment]
What is the raw IMAP name of both Junk mailboxes?

On one of my accounts I have this:
![Bildschirmfoto von 2020-06-15 08-36-10](https://user-images.githubusercontent.com/1374172/84625309-4a904700-aee3-11ea-9e25-4ce4dccdf6d1.png)
![Bildschirmfoto von 2020-06-15 08-36-02](https://user-images.githubusercontent.com/1374172/84625310-4b28dd80-aee3-11ea-9347-1eae1544b7cc.png)

So there is *draft* and *drafts*. Please check if you also have a similar constellation.
