### ISSUE TITLE
Cant send emails, 530 5.7.0 Must issue a STARTTLS command first

### ISSUE THREAD

**Issue by GitKalle** [nextcloud/mail#3223]
### Expected behavior
Send an email.

### Actual behavior
Error message:
_Error sending your message
Error: Request failed with status code 500_

### Mail app

**Mail app version:** 1.3.5

**Mailserver or service:** Posteo.de

**Configuration:** automatic

### Server configuration

**Operating system**: Debian 10 (Docker)

**Web server:** Apache

**Database:** MariaDB

**PHP version:** 7.3.18

**Nextcloud Version:** 18.0.5

#### Client configuration
**Browser:** Firefox 76.0.1

**Operating system:** Arch Linux

### Description
Imap works fine. I have only problems with SMTP.

data/horde_smtp.log
`
>> Mon, 08 Jun 2020 16:18:50 +0000
>> Connection to: smtp://posteo.de:587
S: 220 submission01.posteo.de ESMTP Postfix
C: EHLO cloud.nextcloud.de
S: 250-submission01.posteo.de
S: 250-PIPELINING
S: 250-SIZE 76800000
S: 250-VRFY
S: 250-ETRN
S: 250-STARTTLS
S: 250-ENHANCEDSTATUSCODES
S: 250-8BITMIME
S: 250 DSN
C: MAIL FROM:<xyz@posteo.de> SIZE=384 BODY=7BIT
C: RCPT TO:<abc@yahoo.de>
S: 530 5.7.0 Must issue a STARTTLS command first
S: 530 5.7.0 Must issue a STARTTLS command first
C: RSET
S: 530 5.7.0 Must issue a STARTTLS command first
C: QUIT
S: 221 2.0.0 Bye
`

But something is strange in the configuration of the email account. When I select the SMTP Security SSL/TLS or STARTTLS in the SMTP Settings the corresponding button switch to blue and the SMTP port changed. After that I save the settings and make a refresh of the page. All buttons are grey. I try to set the configuration of SMTP server to SSL/TLS with port 465 but after a refresh of the settings page the SMTP Port switch back to 587.

Greets
GitKalle

**Comment by ChristophWurst** [comment]
>  When I select the SMTP Security SSL/TLS or STARTTLS in the SMTP Settings the corresponding button switch to blue and the SMTP port changed. After that I save the settings and make a refresh of the page. All buttons are grey. I try to set the configuration of SMTP server to SSL/TLS with port 465 but after a refresh of the settings page the SMTP Port switch back to 587.

Could you share screenshots please?

**Comment by GitKalle** [comment]
> Could you share screenshots please?

Current SMTP settings (all buttons are grey):
![email_1_pub](https://user-images.githubusercontent.com/18066460/84701449-50267500-af55-11ea-9ac9-8734acbd0af1.png)

Set to SSL by pressing the button (the button is light blue and the port is 465):
![email_2_pub](https://user-images.githubusercontent.com/18066460/84701564-8532c780-af55-11ea-8830-d47d63e76785.png)

Press save (the blue of the button becomes darker):
![email_3_pub](https://user-images.githubusercontent.com/18066460/84701697-be6b3780-af55-11ea-8595-1aa1f0c254cb.png)

Refresh the page (all buttons are grey again and the port switch back to 587):
![email_1_pub](https://user-images.githubusercontent.com/18066460/84701791-e5c20480-af55-11ea-83a0-178a552c2fe7.png)

**Comment by ChristophWurst** [comment]
We'll have to have a look, but the gray button is not an indication of a *disabled* input but just the way it's displayed, right?

**Comment by GitKalle** [comment]
> We'll have to have a look, but the gray button is not an indication of a _disabled_ input but just the way it's displayed, right?

What does it mean: "... _disabled_ input ..."?

**Comment by ChristophWurst** [comment]
https://www.w3schools.com/TAGS/att_input_disabled.asp

**Comment by DjSlash** [comment]
Chiming in, because I have the same issue.

The buttons are indeed _not disabled_. You can select them just fine, but it doesn't stick. Reload the settings and they'll be all grayed out again.

In webconsole I see errors:
````
[FATAL][object Object] undefined ConsoleLogger.js:58:18
    value ConsoleLogger.js:58
    onSave AccountSettings.vue:75
    saveChanges AccountForm.vue:361
    onSubmit AccountForm.vue:372
    click AccountForm.vue:1
    VueJS 3
        He
        n
        _wrapper
[ERROR] mail: account update failed: 
Object { app: "mail", uid: "<REDACTED>", error: Error }
ConsoleLogger.js:54:18
    value ConsoleLogger.js:54
    value ConsoleLogger.js:80
    onSave AccountSettings.vue:83
[ERROR] mail: could not save account details 
Object { app: "mail", uid: "<REDACTED>", error: Error }
ConsoleLogger.js:54:18
    value ConsoleLogger.js:54
    value ConsoleLogger.js:80
    onSubmit AccountForm.vue:373
````

**Comment by DjSlash** [comment]
Addition: when filling in the passwords in both imap and smtp section, saving succeeds and than you can send mail.

**Comment by DjSlash** [comment]
About autoconfiguration is also discussed in #2599.
