### ISSUE TITLE
Folder icons in dark mode

### ISSUE THREAD

**Issue by nickvergessen** [nextcloud/mail#3224]
### Expected behavior
Icons are visible

### Actual behavior
Icons are black

![Bildschirmfoto von 2020-06-09 10-17-16](https://user-images.githubusercontent.com/213943/84123856-b3d30e80-aa3a-11ea-93df-ee9ae732649f.png)

### Mail app

**Mail app version:**
1.4.0-rc2 I think

**Comment by ChristophWurst** [comment]
cc @GretaD @jancborchardt @violoncelloCH

**Comment by nickvergessen** [comment]
https://github.com/nextcloud/mail/blob/master/css/mail.scss#L22

This also hurts in the eyes, but not sure how to trigger it

**Comment by nickvergessen** [comment]
https://github.com/nextcloud/mail/blob/master/css/mail.scss#L321-L344

Don't use `$color-black`

**Comment by GretaD** [comment]
I'll check it out
