### ISSUE TITLE
Mark as junk vs mark as spam

### ISSUE THREAD

**Issue by georgehrke** [nextcloud/mail#3225]
The label for marking an email as spam is inconsistent.
In the email list its called "Mark as spam":
![F90F5795-ACF8-4D8E-BC71-634920054E0A-2](https://user-images.githubusercontent.com/1250540/84157085-9453da00-aa6a-11ea-81b2-02a46d75678c.jpg)

In the message view it's called "Mark junk":
![A2F2634D-6337-4853-A9D5-26AA07293210-2](https://user-images.githubusercontent.com/1250540/84157117-a03f9c00-aa6a-11ea-8cf8-49b7239dd4ac.jpg)

**Comment by georgehrke** [comment]
I would be happy to send a PR if you tell me which one to use ;)

**Comment by ChristophWurst** [comment]
https://github.com/nextcloud/mail/blob/a5bf179939b53277e270435191def9ea13c9405d/src/components/Message.vue#L47 should be the one. https://github.com/nextcloud/mail/blob/fcf2fd0b444af2f8fb9b03fff18d324f5d10ed8e/src/components/Envelope.vue#L59 is the desired wording :)
