### ISSUE TITLE
Further dark theme fixes

### ISSUE THREAD

**Issue by jancborchardt** [nextcloud/mail#3231]
These are left over – the primary button icons should always be the same as the text color, which depends on theming color, not light/dark theme. 
- [x] Reply button icon
  ![](https://user-images.githubusercontent.com/1374172/84179513-5fee1700-aa86-11ea-81c7-735a52591d6d.png)
- [x] Send button icon
  ![](https://user-images.githubusercontent.com/925062/84189034-dc87f200-aa94-11ea-9ba0-b137318241f5.png)
- [x] "Add mail account" button in settings
   ![](https://user-images.githubusercontent.com/925062/84188967-bd896000-aa94-11ea-9505-78cf1bb4dde0.png)

~~Also possibly something to look into is this menu, which might have an integrated dark theme?~~ https://github.com/nextcloud/mail/issues/6378
![](https://user-images.githubusercontent.com/925062/84189118-0214fb80-aa95-11ea-9652-f81104a5b513.png)

**Comment by kartikcho** [comment]
Hey @jancborchardt! Great to see you again in another awesome project. I'd like to provide a patch for this, could you link to where these icons are rendered from or any other relevant information as I'm new to the codebase but would love to help :)
Thanks!

**Comment by mat-m** [comment]
Also the display image icon, even on dark theme is on a white background. you can find it when you know it is somewhere after the sentence, but playing "Where's Wally" each time is not my goal :)

![image](https://user-images.githubusercontent.com/1039753/111888243-18b09180-89db-11eb-8dfc-aa1ccbd3659d.png)

**Comment by ChristophWurst** [comment]
> Also the display image icon

https://github.com/nextcloud/mail/pull/4713
