### ISSUE TITLE
Show important/junk/favorite icon in the message detail view

### ISSUE THREAD

**Issue by GretaD** [nextcloud/mail#3237]
### Feature Request

Right now, the important/junk/favorite icon, it is shown only at the avatar of the contact.  Since we can mark as important/junk/favorite also from the message action menu, would be nice to have them shown somewhere in the message detail view?

@nextcloud/designers any ideas?

**Comment by jancborchardt** [comment]
Yes, good point! :) To not cut off from the message title and to always keep that at the same position, we could show these indicators to the left of the "from … to …" line?

**Comment by ChristophWurst** [comment]
Dup of https://github.com/nextcloud/mail/issues/3626
