### ISSUE TITLE
Updating the inbox

### ISSUE THREAD

**Issue by Helium314** [nextcloud/mail#3241]
When I expect some mail (e.g. confirmation code) it usually takes some time to be displayed in the inbox.
I do not expect the new message to be shown instantly, so in principle this is not a problem.

However, when clicking the 3 dots next to "Inbox", usually it already shows there is an unread message, which is not shown when opening the inbox. It only appears after waiting some ~20 seconds; reloading in the browser does not accelerate this.
I find this behavior quite annoying, after all if the mail app knows there is a new message, why doesn't it show that message in the inbox?

Not sure if I should consider this a bug, but it seems very strange to me. Is this normal, or some issue related to server configuration?

Nextcloud 18.0.6
Mail 1.3.5

**Comment by ChristophWurst** [comment]
> I find this behavior quite annoying, after all if the mail app knows there is a new message, why doesn't it show that message in the inbox?

To shed some light on this *inconsistency*: what you see in the ... menu is the result of a direct query of the STATUS of an IMAP mailbox. What you see in the mailbox of Nextcloud Mail is what is currently known to the *message cache*. So these two are quite independent and query distinct data sources.

You can use the shortcut <kbd>r</kbd> to manually trigger a sync.

Please read the issue template more carefully next time. It explicitly says that questions should be asked at https://help.nextcloud.com/c/apps/mail for questions. Put any follow-up questions there, please.
