### ISSUE TITLE
Logmessage with either invalid text or invalid conclusion.

### ISSUE THREAD

**Issue by noci2012** [nextcloud/mail#3243]
### Expected behavior
No log messages...

### Actual behavior
A log message claiming a receipent address has no dateformat... (which does seem obvious...) 

OCA\Mail\Exception\ServiceException: Sync failed for 1:xxxxxxxxxxxxxx An exception occurred while executing 'INSERT INTO `oc_mail_recipients` (`message_id`, `type`, `label`, `email`) VALUES(?, ?, ?, ?)' with params [177679, 1, "\x42\xf6\x72\x6e\x65\x72\x40\x77\x77\x77\x6d\x61\x69\x6c\x2e\x63\x61\x63\x65\x72\x74\x2e\x6f\x72\x67", "\x42\xf6\x72\x6e\x65\x72\x40\x77\x77\x77\x6d\x61\x69\x6c\x2e\x63\x61\x63\x65\x72\x74\x2e\x6f\x72\x67"]: SQLSTATE[22007]: Invalid datetime format: 1366 Incorrect string value: '\xF6rner@...' for column `nextcloud`.`oc_mail_recipients`.`label` at row 1

OCA\Mail\Exception\ServiceException: Sync failed for 2:xxxxxxxxxxxxxx: An exception occurred while executing 'INSERT INTO `oc_mail_recipients` (`message_id`, `type`, `label`, `email`) VALUES(?, ?, ?, ?)' with params [177002, 1, "\x42\xf6\x72\x6e\x65\x72\x40\x77\x77\x77\x6d\x61\x69\x6c\x2e\x63\x61\x63\x65\x72\x74\x2e\x6f\x72\x67", "\x42\xf6\x72\x6e\x65\x72\x40\x77\x77\x77\x6d\x61\x69\x6c\x2e\x63\x61\x63\x65\x72\x74\x2e\x6f\x72\x67"]: SQLSTATE[22007]: Invalid datetime format: 1366 Incorrect string value: '\xF6rner@...' for column `nextcloud`.`oc_mail_recipients`.`label` at row 1
### Mail app

**Mail app version:** (see apps admin page, e.g. 0.5.3)
1.3.5

**Mailserver or service:** (e.g. Outlook, Yahoo, Gmail, Exchange,...)
Dovecot internal server

### Server configuration

**Operating system**: (e.g. Debian 8)
Gentoo 

**Web server:** (e.g. Apache, Nginx,...)
Nginx 

**Database:** (e.g. MariaDB, SQLite or PostgreSQL)
MariaDB

**PHP version:** (e.g. 7.0)
7.3

**Nextcloud Version:** (see admin page, e.g. 13.0.2)
18.0.6

#### Client configuration
**Browser:** (e.g. Firefox 48)
Chromium

**Operating system:** (e.g. Arch Linux)
Gentoo Linux

**Comment by ChristophWurst** [comment]
> MariaDB

I'm confident this is about https://docs.nextcloud.com/server/stable/admin_manual/configuration_database/mysql_4byte_support.html. Please read and follow these instructions carefully. It will most likely resolve your issues. The database simply doesn't understand the encoding of the data that is inserted.

**Comment by noci2012** [comment]
Procedure to convert FAILS with step 3: 
```
MariaDB [(none)]> SELECT NAME, SPACE, FILE_FORMAT FROM INFORMATION_SCHEMA.INNODB_SYS_TABLES WHERE NAME like "nextcloud%";
ERROR 1054 (42S22): Unknown column 'FILE_FORMAT' in 'field list'
```
MariaDB is v10.4, and the mysql_upgrade procedure has been run a few weeks ago.
```
MariaDB [information_schema]> describe INNODB_SYS_TABLES ;             
+---------------+---------------------+------+-----+---------+-------+
| Field         | Type                | Null | Key | Default | Extra |
+---------------+---------------------+------+-----+---------+-------+
| TABLE_ID      | bigint(21) unsigned | NO   |     | 0       |       |
| NAME          | varchar(655)        | NO   |     |         |       |
| FLAG          | int(11)             | NO   |     | 0       |       |
| N_COLS        | int(11)             | NO   |     | 0       |       |
| SPACE         | int(11)             | NO   |     | 0       |       |
| ROW_FORMAT    | varchar(12)         | YES  |     | NULL    |       |
| ZIP_PAGE_SIZE | int(11) unsigned    | NO   |     | 0       |       |
| SPACE_TYPE    | varchar(10)         | YES  |     | NULL    |       |
+---------------+---------------------+------+-----+---------+-------+
8 rows in set (0.011 sec)

```

**Comment by ChristophWurst** [comment]
Please use https://help.nextcloud.com/c/support for community help and check the existing topics because this might be something others have run into as well.

**Comment by noci2012** [comment]
https://help.nextcloud.com/t/upgrade-mariadb-to-4-byte-support/69870
Which point to:
https://github.com/nextcloud/documentation/issues/513

The next step command does convert the tables. No validation on the storage engine though.
On Nextcloud forums same Query, on MariaDB site no mentioing ... So mysql_upgrade still misses a thing since 10.0.38.

**Comment by ChristophWurst** [comment]
Might be worth reporting to mysql then

**Comment by noci2012** [comment]
Question: Miising FILE_FORMAT column in INNODB_SYS_TABLES 
     Title: Re: Missing FILE_FORMAT column in INNODB_SYS_TABLES
      User: Marko Mäkelä
-------------------------------------
INFORMATION_SCHEMA.INNODB_SYS_TABLES is a hard-coded view that is provided to the InnoDB internal data dictionary table SYS_TABLES that resides in the system tablespace. The column FILE_FORMAT does not have any direct counterpart in SYS_TABLES.
The configuration parameters innodb_file_format and innodb_large_prefix were deprecated in MariaDB 10.2.2 when the InnoDB changes from MySQL 5.7.9 were merged. The motivation for the deprecation and removal was that originally these parameters were introduced to supposedly allow downgrading to older versions than MySQL 5.5. To make matters worse, the default values of these parameters caused the files to remain in the backward-compatible format. Only MySQL 5.7 and MariaDB 10.2 would change the defaults to sane values and deprecate these useless parameters. (The predecessors of MySQL 5.5 were already EOL at that point, and besides, we do not really support downgrades.)
Those 2 deprecated parameters were removed in MariaDB 10.3, but they were put back later in MDEV-18399, because the sane defaults were explicitly specified in commonly used configuration files.
I do not think that it makes sense to carry the column in INNODB_SYS_TABLES.
Note: In MariaDB 10.3 and MariaDB 10.4, InnoDB file formats were extended by MDEV-11369 and MDEV-15562. You can disable those format changes by
SET GLOBAL innodb_instant_alter_column_allowed=never;
which was implemented in MDEV-20590.

So the manual needs some adjusting from MariaDB 10.3.0 onward.

**Comment by ChristophWurst** [comment]
Got it. Could you please open a ticket about this at https://github.com/nextcloud/documentation/ so it's not forgotten, or – if you have a few minutes – send us a PR that updates the relevant section in the manual? That would help other users immensely.

**Comment by noci2012** [comment]
Done: https://github.com/nextcloud/documentation/issues/2153

**Comment by ChristophWurst** [comment]
Thanks a lot! I appreciate the time taken.
