### ISSUE TITLE
Unexpected error during account creation

### ISSUE THREAD

**Issue by eglyn** [nextcloud/mail#3245]
Hi everybody, 

I have an issue with mail app, i can't add any account, i have this error msg: 
`Unexpected error during account creation`

When i enable debug log, I have just this: 
![image](https://user-images.githubusercontent.com/24936778/84507984-f4908900-acc1-11ea-82ea-1a124035523f.png)

There is "authentification failed" but my pwd is ok :/ and every account has same msg.

I tried to set app.mail.verify-tls-peer to false, but same error.

Any idea ? 

thx :)

**Comment by benoitjy** [comment]
Same error for me
two errors in the logs:
`Error | PHP | Uninitialized  string offset: 1 at  /var/www/html/nextcloud/apps/mail/vendor/pear-pear.horde.org/Horde_Smtp/Horde/Smtp/Exception.php#238
Fatal | mail | Creating account failed: Could not open secure TLS connection to the server.
`
And on the mail server side:
dovecot: imap-login: Disconnected (no auth attempts in 1 secs): user=<>, rip=43.245.222.163, lip=173.212.242.105, TLS handshaking: SSL_accept() failed: error:1420918C:SSL routines:tls_early_post_process_client_hello:version too low, session=<oXxUvuOnvMMr9d6j>
`
no username send... perhaps not the same error as eglyn?
`

**Comment by ChristophWurst** [comment]
> Any idea ?

Not quite. The only thing I remember is that when using MS Exchange, you have to experiment with `/` vs `\` if there is a domain in your username.

> every account has same msg

Are they all hosted by Microsoft?
