### ISSUE TITLE
Porque solo me muestra ultimo correo recibido y los otros desaparecen?

### ISSUE THREAD

**Issue by daus007** [nextcloud/mail#3259]
### Question

Al entrar en la bandeja de entrada solo me muestra los correos nuevos por unos instantes y despues desaparecen, solo me deja el ultimo correo recibido.

En la carpeta de enviados el mismo caso, solo me muestra el ultimo correo enviado.

Alguien me puede ayudar a solucionar por favor?!!

Gracias

**Comment by ChristophWurst** [comment]
Hi,

please ask your support question at https://help.nextcloud.com/c/apps/mail in English or at https://help.nextcloud.com/c/international/espanol-spanish/162. Note that most of us don't speak Spanish, so we can not help you in the latter category, unfortunately.
