### ISSUE TITLE
No Favorites should show up when selecting "Priority Inbox"

### ISSUE THREAD

**Issue by jasond2020** [nextcloud/mail#3268]
It would be great, if there were some preferences for choosing what is shown when "Priority Inbox" is selected. Status Quo: Priority Inbox, Favorites, Other (Inboxes). It would be good to be able to select if one only wants the see Priority Inox and Inbox. In my opinion the 'Favorites' are more of long-term interest and should not be visible all the time.

_Originally posted by @jasond2020 in https://github.com/nextcloud/mail/issues/3265#issuecomment-645213716_

**Comment by ChristophWurst** [comment]
it this a big deal? because we show only 5 messages by default, so those shouldn't take up too much space.

**Comment by jasond2020** [comment]
In my opinion this is not a question of 'space', it is a question of convenience and a question for what purpose the 'Priority Inbox' (as default landing page) is used. I would think, it is used to make it easier to (visually) filter important and not-so-important mails: The important ones show up at the top of the page, the less important show up under 'Other'. The Favorites are not part of this 'filtering', because they are 'stored' for some reason, but not for the immediate filtering of the inbox(es). 

So, big deal yes or no? It Depends... 
A big deal for two reasons: Many times i use 'not-so-big' screens and most of the time mobile phones to access the mail-app - in this cases it is a bit frustrating to scroll through the 'stored' (put away but for a reason/purpose remembered/marked favorites-) messages all the time to get from more important to less important but non-the-less of immediate interest e-mails. And this is also the second reason: favorites are (in my opinion) displaced in the context of the 'priority inbox'-filtering of mails.

On bigger screens - or if i don't have any favorites: no big deal.

**Comment by ChristophWurst** [comment]
Thanks for the explanation. I'll think about it. cc @jancborchardt as our interaction design expert.

If there is one thing I've learned in the time I've worked on the app it's that there are 1000 ways people use email :speak_no_evil: 

For this priority inbox we've had a closer :eye: at gmail. They have three similar sections. The only difference is that the important one shows only unread.

**Comment by jasond2020** [comment]
Thank you for thinking about it! What i am asking for is 'just' a possibility to customize the 'priority inbox' in so far, as it would be good to choose what to see and by this adjust the behavior of the mail app - the default could still be the current behavior/design

**Comment by seventer** [comment]
To support @jasond2020 request I would like to add that we use the mail-app happily for a long time now. Unfortunately now "Favorites" are shown with irrelevant months old messages and "Important" shows not important messages. The real mail list where our users are interested in is disappeared from the screen. Yes you could scroll down but that is a bit annoying when refreshing mail.

So from our users you would get multiple +1 if there was an option to disable Favorites and Important categorization. 

Thanks for considering the option and all the great work you do!

**Comment by ChristophWurst** [comment]
> "Important" shows not important messages

Could you open a separate ticket about this? I'd like to know more about the classification that doesn't work.

**Comment by seventer** [comment]
Sorry, I wasn't clear and assumed the issue was already known which also is (somewhat) mentioned in #3265. 

To respect all the great work you do we all, in different words, do kindly ask to add the option to either remove Priority completely or at least move it to somewhere where it is not hindering the users daily use of the mail-app.

**Comment by jancborchardt** [comment]
> The only difference is that the important one shows only unread.

So then maybe this is something we should additionally adjust @ChristophWurst?

> add the option to either remove Priority completely or at least move it to somewhere where it is not hindering the users daily use of the mail-app

So you basically want the "All inboxes" and that’s it, correct? This would be fixed by opening the last selected folder across devices, no?

**Comment by jasond2020** [comment]
> So you basically want the "All inboxes" and that’s it, correct? This would be fixed by opening the last selected folder across devices, no? Then the priority inbox is still there, just not used if people aren’t opening it.

This is not what I originally meant! What I would like to have is the option to toggle what to see when the Priority Inbox is selected (regardless of wether it is the default landing page or not for the mail app); the other way around: I would like to be able to de-select the favorites for the default view of the Priority Inbox.

Antother question would be, if it weren't a good idea to let the user choose what default view (all inboxes, any special inbox or directory, or priority inbox) he wants to see, when openeing the mail app (from any device). 

And yet another thing is, that the Priority Inbox does not seem to work as expected for me - but maybe this is another issue.

**Comment by ChristophWurst** [comment]
> And yet another thing is, that the Priority Inbox does not seem to work as expected for me - but maybe this is another issue.

Again, *please* open a ticket for this and we'll debug it together.
