### ISSUE TITLE
Add a setting for personal namespaces

### ISSUE THREAD

**Issue by deibertf** [nextcloud/mail#3272]
#### Summary
In outlook I have a setting like this:

![grafik](https://user-images.githubusercontent.com/24978665/85110757-a9233100-b213-11ea-9f3a-62c54cada7fd.png)
 
Without this setting my inbox looks like this:

![grafik](https://user-images.githubusercontent.com/24978665/85111329-775e9a00-b214-11ea-8657-b4fcb2bcea16.png)

Which duplicates draft/sent/etc.

**Comment by ChristophWurst** [comment]
One day I want to know how this thing is really called. Some say it is a *prefix*, some *namespace* and then there is *root folder path*. Ugh.

This is a problem, yes. We tried to fix this a few times but there is always new edge cases that are not covered.

**Comment by CCRDude** [comment]
That would be great!
My folders all show up under inbox as INBOX.Folder.SubFolder etc., and since the column cannot be resized, it's unusable for longer folder names.
Plus, my Sent, Drafts, Trash etc are also subfolders of Inbox, not appearing at all on main level.

**Comment by brrrrrrrt** [comment]
> One day I want to know how this thing is really called. Some say it is a prefix, some namespace and then there is root folder path. Ugh.

just to clarify:

actually you are talking about **the personal namespace**, but some emailclients, like outlook call this the "**root folder path**". every namespace acts as a **prefix**-folder to its containing foldernames. 

within thunderbird for example you have the option to enter 3 different namespaces:

- Personal Namespace = "INBOX" = root folder path
- Public (shared)
- Other Users

IMAP servers like courier or cyrus, per default, use "INBOX" as the namespace for personal folders of the user. nowadays all decent mailclients, detect "INBOX" automatically. i remember long time a go you had to enter "INBOX" to your mailclients root-folder-path setting to make the "INBOX-Prefix" disappear in your folderlist, Outlook 2008+, thunderbird or iOS Mail App do not need this anymore.

our cyrus mailserver uses three namespaces by default:

- "INBOX." for the users **personal folders**
- "" (empty) for **public shares**
- "user." for shares from **other users**

"public shares" are folders which are not owned by any user, but users may have access to them defined by access control lists.

"other users" contains folders from other users personal namespace, which are shared with the current user via acces control list. any user can grant access to one of its personal folders to any other user, this is the namespace where those folders will be listed.

the imap command "NAMESPACE" will list all namespaces on the server, if it has that capability which is usually revealed after login, i think all IMAP servers support this.

you can read more about namespaces in the corresponding RFC
[RFC-2342 IMAP4 Namespace](https://tools.ietf.org/html/rfc2342)

**Comment by ChristophWurst** [comment]
@brrrrrrrt thanks a again for these details. I looked into this for https://github.com/nextcloud/mail/pull/3147 and found that horde has some logic to read the namespaces from IMAP, ans some fallback when it's not supported. The PR now persists the personal namespace with each account and hides the prefix for the displayed name of each mailbox. Let's re-evaluate later if we really need a setting for this or if the detection works well enough to cover 99% of the setups.

**Comment by brrrrrrrt** [comment]
@ChristophWurst sounds great! I am looking forward to review the next version and i am curious how well the changes will work in our enviroment. I followed #3147 - great efforts - big thanks to you and @dehnhardt !
