### ISSUE TITLE
Please push last Updates to apps.nextcloud

### ISSUE THREAD

**Issue by Berndinox** [nextcloud/mail#328]
I'm not able to install mail via the nativ nextcloud install routine cause atm only PHP Version 7.0 is supported. However the last update on the nextcloud apps store war on December 12th the Code change to make PHP 7.1 possible in the github repo was on the 16th of December...

Could someone do that?

Thanks

**Comment by Gomez** [comment]
Yes, we try to release soon. 
Meanwhile you can use the Nightly-builds: https://github.com/nextcloud/mail#nightly-builds

Report back if you find any issues, thanks!

**Comment by ChristophWurst** [comment]
@Berndinox would be great if you could help test the current state of the app. When we push to the app store, we usually try to only do that if the app is in an almost stable condition. I'm not sure we're there ATM, unfortunately.

**Comment by Berndinox** [comment]
With the latest build, when connecting tvial/docker-mailserver via STARTSLL i got the following error:
`TypeError: Cannot read property 'first' of undefined`

However, the Mailbox is connected successfully, but i could not display any item, or write new mails.

When leaving the App, and opening again there is:
` "error while loading account"`

From my iphone i've got connected successfully my mailbox. So mailserver seems to be fine.

**Comment by Berndinox** [comment]
@ChristophWurst @Gomez: Error still exists in the last build (07-Mar-2017 07:37)
