### ISSUE TITLE
visible Imatges into mail app

### ISSUE THREAD

**Issue by profeinteri** [nextcloud/mail#3284]
### Feature Request

I'm woring with a corporative mail and need to insert some imatges in the body of the message and also , that's the most important part, in the signature, where I need to put de logo's Company.

#### Summary

Insert visibles imatge in the body and the signature of the message in mail's accounts

Thank you so much!
This is an incredibble work , we all apreciate your app !!!!

**Comment by ChristophWurst** [comment]
Sounds like a duplicate of https://github.com/nextcloud/mail/issues/2733

**Comment by ChristophWurst** [comment]
> Thank you so much!
> This is an incredibble work , we all apreciate your app !!!!

@nextcloud/mail :eyes: 

:heart: thanks!
