### ISSUE TITLE
All Inboxes shown when only one account exists

### ISSUE THREAD

**Issue by mjog** [nextcloud/mail#3285]
### Expected behavior

When there is only a single account, show only the account's inbox.

### Actual behavior

When there is only a single account, two inboxes are shown - All Inboxes and the account's inbox, which are the same.

### Mail app

**Mail app version:** 1.4.0

**Mailserver or service:** Dovecot

### Server configuration

**Operating system**: Debian 10

**Web server:** Apache

**Database:** MariaDB

**PHP version:** Whatever comes with Debian 10

**Nextcloud Version:** 19.0.0

#### Client configuration
**Browser:** GNOME Web 3.36.2

**Operating system:** Ubuntu 20.04

**Comment by ChristophWurst** [comment]
See https://github.com/nextcloud/mail/pull/3329#issuecomment-684911514. It was decided that we won't hide this for now.
