### ISSUE TITLE
Display issues since priority inbox release

### ISSUE THREAD

**Issue by umrath** [nextcloud/mail#3288]
### Expected behavior
The inbox and folders should show up.

### Actual behavior
Parts of the mailboxes and mails are hidden or hiding.

### Mail app

**Mail app version:** 1.4.0

**Mailserver or service:** posteo.de

### Server configuration

**Operating system**: Ubuntu 18.04

**Web server:** Apache

**Database:** MySQL

**PHP version:** 7.2

**Nextcloud Version:** 19.0.0

#### Client configuration
**Browser:** Firefox 76

**Operating system:** Windows 10
![Unbenannt](https://user-images.githubusercontent.com/1010437/85252583-6acc8280-b45c-11ea-91de-042ffbcf4acb.PNG)

**Comment by umrath** [comment]
This behavious is new since 1.4.0.

**Comment by ChristophWurst** [comment]
> Parts of the mailboxes and mails are hidden or hiding.

Like specific messages? Are they in the *Other* section possibly? Have you tried scrolling down?

**Comment by umrath** [comment]
It's affecting any message and (as the screenshot shows) mostly the mail overview and the folders, not the mail itself. Actually, I can only blindly click on folders because they are not shown at all (or use the tool tip). Clicking a different folder does not change the behaviour.
I can scroll down. This will not remove the effect but affect the then visible mails.

**Comment by umrath** [comment]
This issue is reproducible in Firefox private mode as well.
It is not reproducible in Chrome.

**Comment by ChristophWurst** [comment]
Wait … you're referring to that white overlay? I thought you just tried to mask sensitive information … am I understanding right?

Mind taking a screenshot in Chrome for comparison? Thanks

**Comment by umrath** [comment]
Yep, that's what I meants.
Here a screenshot of the same view side-by-side with Chrome (left) and Firefox (right):
![Unbenannt](https://user-images.githubusercontent.com/1010437/85545219-0bb56c00-b61c-11ea-95d3-0e07b1932ce4.PNG)

**Comment by umrath** [comment]
Yes, that's what I meant.
Here a screenshot side-by-side of Chrome (left) and Firefox (right) with the same view:
![Unbenannt](https://user-images.githubusercontent.com/1010437/85545542-5505bb80-b61c-11ea-9806-28faf1cae441.PNG)

**Comment by ChristophWurst** [comment]
Could you inspect the element to see if it has any ID it class that tells us where it's from?

**Comment by umrath** [comment]
I have difficulties to pick the right element. Especially, because it tends to toggle when I mouse over it.
![Unbenannt](https://user-images.githubusercontent.com/1010437/85564399-85eeec00-b62e-11ea-997a-4d4c67d23427.PNG)

**Comment by umrath** [comment]
Without any recognizable reason this behaviour has new stopped, completely.
So, the display of the inbox, the folders, etc. is back to normal.

I cannot really pinpoint this to anything, because nothing has changed. Firefox has not been updated, etc.

Closing it, as it might be likely just a local browser glitch.

**Comment by ChristophWurst** [comment]
Oh, ok. We were also a bit clueless so far but please let us know when this occurs again :v:
