### ISSUE TITLE
Add action menu for subfolders

### ISSUE THREAD

**Issue by GretaD** [nextcloud/mail#3289]
### Expected behavior
All the folders/subfolders we create should have an action menu, so we can be able to edit them.

### Actual behavior
No action menu

![subfolders](https://user-images.githubusercontent.com/12728974/85273566-0c180080-b47e-11ea-80ed-36ecbfb93610.png)

**Comment by GretaD** [comment]
@ChristophWurst is this a feature request or a bug, im not sure.

**Comment by ChristophWurst** [comment]
Bug, I guess :)
