### ISSUE TITLE
Account setup form broken with Nextcloud master

### ISSUE THREAD

**Issue by ChristophWurst** [nextcloud/mail#329]
* Hovered border looks odd
* Port and ssl selection should be in one row

![bildschirmfoto von 2017-03-06 14-02-31](https://cloud.githubusercontent.com/assets/1374172/23611055/ab8415b4-0275-11e7-923d-51796a0f3aa6.png)

^ I assume this might have been broken by one of the many (s)css changes that were merged into the nextcloud server recently.

cc @skjnldsv @nextcloud/mail any volunteers? :-)

**Comment by ChristophWurst** [comment]
https://twitter.com/brokencodebot/status/838737294601375744 🙈 🙊 🙉

**Comment by ChristophWurst** [comment]
cc @jancborchardt

**Comment by jancborchardt** [comment]
The fix is in https://github.com/nextcloud/mail/pull/298 as https://github.com/nextcloud/mail/pull/298/commits/67733639d57b1f9bd30a9936342ff808d4695ee3 :)
