### ISSUE TITLE
Behavior of 'Priority Inbox' (no Refreshing, algorithm ...)

### ISSUE THREAD

**Issue by jasond2020** [nextcloud/mail#3293]
Bug: The Priority inbox ist not refreshing with the 30s backgorund job; one has to manually refresh the site to see new mails in the priority inbox
(regardless: new mails show up in the 'other' section below)

Question: Why is every Mail 'Important' - why not the other way around. (faster learning...) This way i have to tell the Mail app every time, that this mail and this mail and this mail is not important... annoying. 

Question/Bug/Improvement (?): What's the algortihm? How does the app learn whats important and what not? Until now every new mail is important (regardloss of my choices i made before (most of the mails i marked as not important; the other way around: only really few mails got the marking 'important'); i don't see the reason for doing this if the app then still marks every new mail important

[is there already any discussion about these questions?]

**Comment by ChristophWurst** [comment]
> Question: Why is every Mail 'Important' - why not the other way around. (faster learning...) This way i have to tell the Mail app every time, that this mail and this mail and this mail is not important... annoying.

There are to phases in the classification of the priority inbox: if there are less than 30 messages, some primitive rules with threshold are used to determine if a message is important – this is rather biased towards important, and after at least 30 important messages are there, the some ML-based algorithm kicks in to do the "better" classification.

How many important messages do you have, roughly?

The bias was intended (:eyes: @jancborchardt) so a user would rather have to perform the action of unmarking something that isn't really important and having to find important messages in the *Others* section and flagging them the other way around.

The issue with the rules, of course, is that they work better on some accounts and worse on others. So yours might just be one of those with poor quality. Ideally once the ML is active it should get better.

It's still on my todo to write a blog about *how* this new priority inbox works. There is a bit of a marketing summary at https://nextcloud.com/blog/nextcloud-mail-introduces-machine-learning-for-priority-inbox/, not sure if that helps.

**Comment by ChristophWurst** [comment]
Btw can we move the discussion to https://help.nextcloud.com/c/apps/mail?

**Comment by jasond2020** [comment]
First: Thank you for the explanations! Iam eager to learn more about your algorithm!

After 2 more days of 'learning' the filtering in my priority inbox acutally does what it should and is not marking everything as important anymore. Not sure if it is getting everything right - but it is getting in the right direction now!

The better the priority inbox works the more annoying is the 'feature' of seeing (having to see) the favorites all the time: https://github.com/nextcloud/mail/issues/3268

**Comment by ChristophWurst** [comment]
> After 2 more days of 'learning' the filtering in my priority inbox acutally does what it should and is not marking everything as important anymore. Not sure if it is getting everything right - but it is getting in the right direction now!

This makes me happy. Thanks for sharing the good news :)

**Comment by ChristophWurst** [comment]
Also see https://github.com/nextcloud/mail/issues/3299 for a related change.

**Comment by jancborchardt** [comment]
> The bias was intended (eyes @jancborchardt) so a user would rather have to perform the action of unmarking something that isn't really important and having to find important messages in the _Others_ section and flagging them the other way around.

You know more about how it works, but maybe we can slightly adjust the threshold here? Comparing to Hey as well here, this would kind of make it more like:
- "Important and unread": is absolutely always important
- "Other": is a bit more like the "Screen first-time senders" where you can decide if it’s important or not

Does that make sense?

**Comment by ChristophWurst** [comment]
> "Other": is a bit more like the "Screen first-time senders" where you can decide if it’s important or not

But also the read important ones, so not quite the same.
