### ISSUE TITLE
Layout of the UI

### ISSUE THREAD

**Issue by ostasevych** [nextcloud/mail#3294]
### Feature Request
For user convenience, it should be possible to change the layout of the elements placed on the main window. By now the width of columns is fixed, and it is not possible to adjust the layout, eg showing the text of the message on the bottom, hide the Important and Favourites, rearrange the columns.

#### Summary

Please, add the possibility at least to change the width of  columns, and add different layouts.
![image](https://user-images.githubusercontent.com/5199030/85435134-b3d12380-b58f-11ea-976f-178f50d75d92.png)

**Comment by ChristophWurst** [comment]
@jancborchardt :eyes:

**Comment by jancborchardt** [comment]
> add different layouts

This is unlikely to happen, as every layout will have to be tested and maintained. We already have limited resources to spend here and need to laser focus on the essentials.

Hence I’ll be closing this since I don’t see this happening any time soon. Especially the different layouts we’ll likely never do. The layout is responsive and that’s it.

**Comment by ostasevych** [comment]
> > add different layouts
> 
> This is unlikely to happen, as every layout will have to be tested and maintained. We already have limited resources to spend here and need to laser focus on the essentials.
> 
> Hence I’ll be closing this since I don’t see this happening any time soon. Especially the different layouts we’ll likely never do. The layout is responsive and that’s it.

Thank you for clarifications. At least, please, add the possibility to change dynamically the width of panes. Now they look like very strange and not comfortable... See below.

![image](https://user-images.githubusercontent.com/5199030/85794107-bd4cbe00-b73e-11ea-8870-7c139dd93040.png)
