### ISSUE TITLE
PHP7.1 compatibility

### ISSUE THREAD

**Issue by totalprogrammi** [nextcloud/mail#330]
### Steps to reproduce
1. run docker image wonderfall/nextcloud:latest
2. Try to install Mail app
3. The app store says "PHP with a version lower than 7.0 is required".

### Expected behaviour
The app will install , as (apparently) all other apps.

### Actual behaviour
Cannot install Mail app

### Mail app

**Mail app version: 0.6.2

### Server configuration
**Operating system:alpine

**Web server:apache

**Database:mariadb 10

**PHP version:7.1

**Version:11.0.2

**Updated from an older version or fresh install:fresh install

**List of activated apps: default

```
If you have access to your command line run e.g.:
sudo -u www-data php occ app:list
from within your server installation folder
```

**The content of config/config.php:**

<details>
```
If you have access to your command line run e.g.:
sudo -u www-data php occ config:list system
from within your server installation folder

or 

Insert your config.php content here
(Without the database password, passwordsalt and secret)
```
</details>

#### Client configuration
**Browser:**

**Operating system:**

##### Web server error log
```
Insert your webserver log here
```

##### Server log (data/nextcloud.log)
<details>
```
Insert your server log here
```
</details>

##### Horde IMAP log (data/horde_imap.log)
<details>
```
Insert your horde IMAP log here, see https://github.com/nextcloud/mail#debug-mode
```
</details>

##### Horde SMTP log (data/horde_smtp.log)
<details>
```
Insert your horde SMTP log here, see https://github.com/nextcloud/mail#debug-mode
```
</details>

##### Browser log
<details>
```
Insert your browser log here, this could for example include:

a) The javascript console log
b) The network log 
c) ...
```
</details>

**Comment by ChristophWurst** [comment]
Dup of https://github.com/nextcloud/mail/issues/299. Basically the problem has been solved (the app is compatible now) but we did not manage to release a new version yet.

**Comment by ChristophWurst** [comment]
We're working on finishing up some work, see the open pull request. As always, any help (coding, testing, reporting bugs) is very welcome :-)
