### ISSUE TITLE
Can't drag & drop emails to folders

### ISSUE THREAD

**Issue by pierrelegeay49** [nextcloud/mail#3301]
### Expected behavior
I want to put my emails to the right folder by using drag and drop

### Actual behavior
I can't drag and drop the emails, I just can see the folders but can't do anything with them.

### Mail app

**Mail app version:** 1.4.0

**Mailserver or service:** OVH

### Server configuration

**Operating system**: Ubuntu 18.04

**Web server:** Apache

**Database:** Mysql 5.7.24

**PHP version:** 7.2.24

**Nextcloud Version:** 18.0.3

#### Client configuration
**Browser:** Firefox 77

**Operating system:** MacOs Catalina

**Comment by ChristophWurst** [comment]
#1753
