### ISSUE TITLE
Use same color for mailbox and message markup

### ISSUE THREAD

**Issue by rasos** [nextcloud/mail#3308]
### Feature Request

Each mailbox has a color ball. Each message is marked up with a thin color line. 

The colors of the messages should be related to the mailbox ball color.

#### Current behaviour

Colors of mailbox and message are different in 

![pasted-image](https://user-images.githubusercontent.com/485723/85839415-337f0e00-b79b-11ea-9479-aee48cdac262.png)

#486 #1922

**Comment by ChristophWurst** [comment]
@GretaD can you reproduce? The *should* be the same of course. We might use the wrong input for the color generation

**Comment by GretaD** [comment]
All looks good on my inbox.
![colorpicker](https://user-images.githubusercontent.com/12728974/86459016-75bdc780-bd26-11ea-9369-9355a8705088.jpeg)

@rasos what OS are you using and what version of NC?

**Comment by ChristophWurst** [comment]
I can't reproduce either.
