### ISSUE TITLE
Remove the parent folder name from the subfolder name.

### ISSUE THREAD

**Issue by GretaD** [nextcloud/mail#3309]
### Feature Request
Remove the parent folder name from the subfolder name.

#### Summary
The subfolder looks like this:
![subfoldersss](https://user-images.githubusercontent.com/12728974/85872942-bcfd0300-b7d0-11ea-98ff-995945b24edd.png)

This happens because thats how IMAP mailboxes are organized, but It would look nicer if only the subfolder name would be shown.

**Comment by ChristophWurst** [comment]
would you also like to work on this while your brain is filled with all the folder management knowledge? :)

**Comment by dehnhardt** [comment]
Sorry to interfere. This is exactly the problem I've solved with this PR:
https://github.com/nextcloud/mail/pull/3147

**Comment by ChristophWurst** [comment]
Duplicate  of https://github.com/nextcloud/mail/issues/689

**Comment by ChristophWurst** [comment]
And https://github.com/nextcloud/mail/issues/2833#issuecomment-651259403 :grimacing:
