### ISSUE TITLE
"Fehler beim Laden des Kontos" 

### ISSUE THREAD

**Issue by Manuelibt** [nextcloud/mail#331]
### Steps to reproduce
1.Installed Mail App in Nextcloud
2.Filled in account Data (IMAP Account)
3.

### Expected behaviour
At this point I wanted to use the app 

### Actual behaviour
errormessage "Fehler beim Laden des Kontos"
### Mail app

**Mail app version: 0.6.2 (see apps admin page)

**Mailserver or service: All-Inkl (e.g. Outlook, Yahoo, Gmail, Exchange,...)

**Transport security - IMAP:STARTTLS (None, SSL, TLS, STARTTLS) 

**Transport security - SMTP: STARTTLS (None, SSL, TLS, STARTTLS)

**Number of accounts:1

**Mail app version build date:** (only if you are using a Nightly Build)

### Server configuration
**Operating system**: don t know 

**Web server:**

**Database: mysql 5.6.33**

**PHP version:7.0.14

**Version:**  Nextcloud Vers. 11.0.2 stable

**Updated from an older version or fresh install:**

**List of activated apps:*files, activity, galery, videocalls, mail, contact, calendar, notes, bookmarks, polls, todo*

```
If you have access to your command line run e.g.:
sudo -u www-data php occ app:list
from within your server installation folder
```

**The content of config/config.php:*

<?php
$CONFIG = array (
'instanceid' => 'xxxx',
'passwordsalt' => 'xxxx',
'secret' => 'xxxx',
'trusted_domains' =>
array (
0 => 'xxxx',
),
'datadirectory' => '/www/htdocs/xxxx/nextcloud/data',
'overwrite.cli.url' => 'xxxx',
'dbtype' => 'mysql',
'version' => '11.0.2.7',
'dbname' => 'xxxx',
'dbhost' => 'localhost',
'dbport' => '',
'dbtableprefix' => 'ELQu8_',
'dbuser' => 'xxxx',
'dbpassword' => 'xxxx',
'logtimezone' => 'Europe/Berlin',
'installed' => true,
'tempdirectory' => '/www/htdocs/xxxx/nextcloud/tmp/',
'maintenance' => false,
'theme' => '',
'loglevel' => 2,
'appstore.experimental.enabled' => true,
'updater.release.channel' => 'stable',
);
 *

<details>
```
If you have access to your command line run e.g.:
sudo -u www-data php occ config:list system
from within your server installation folder

or 

Insert your config.php content here
(Without the database password, passwordsalt and secret)
```
</details>

#### Client configuration
**Browser:*firefox, chromium, Opera*

**Operating system:*debian, mac os, windows*

##### Web server error log
```
Insert your webserver log here
```

##### Server log (data/nextcloud.log)
	Horde_Imap_Client_Exception_ServerResponse: IMAP error reported by server.
/www/htdocs/xxx/nextcloud/apps/mail/vendor/pear-pear.horde.org/Horde_Imap_Client/Horde/Imap/Client/Socket.php - line 4302: Horde_Imap_Client_Socket->_getLine(Object(Horde_Imap_Client_Interaction_Pipeline))
/www/htdocs/xxx/nextcloud/apps/mail/vendor/pear-pear.horde.org/Horde_Imap_Client/Horde/Imap/Client/Socket.php - line 4230: Horde_Imap_Client_Socket->_sendCmdChunk(Object(Horde_Imap_Client_Interaction_Pipeline), Array)
/www/htdocs/xxx/nextcloud/apps/mail/vendor/pear-pear.horde.org/Horde_Imap_Client/Horde/Imap/Client/Socket.php - line 1749: Horde_Imap_Client_Socket->_sendCmd(Object(Horde_Imap_Client_Interaction_Pipeline))
/www/htdocs/xxx/nextcloud/apps/mail/vendor/pear-pear.horde.org/Horde_Imap_Client/Horde/Imap/Client/Base.php - line 1726: Horde_Imap_Client_Socket->_status(Array, 1)
/www/htdocs/xxx/nextcloud/apps/mail/lib/Mailbox.php - line 223: Horde_Imap_Client_Base->status(Array, 1)
/www/htdocs/xxx/nextcloud/apps/mail/lib/Mailbox.php - line 230: OCA\Mail\Mailbox->getStatus(1)
/www/htdocs/xxx/nextcloud/apps/mail/lib/Account.php - line 546: OCA\Mail\Mailbox->getTotalMessages()
/www/htdocs/xxx/nextcloud/apps/mail/lib/Account.php - line 577: OCA\Mail\Account->guessBestMailBox(Array)
/www/htdocs/xxx/nextcloud/apps/mail/lib/Account.php - line 415: OCA\Mail\Account->getSpecialFolder('archive', true)
/www/htdocs/xxx/nextcloud/apps/mail/lib/Account.php - line 611: OCA\Mail\Account->getSpecialFoldersIds(false)
/www/htdocs/xxx/nextcloud/apps/mail/lib/Account.php - line 340: OCA\Mail\Account->localizeSpecialMailboxes()
/www/htdocs/xxx/nextcloud/apps/mail/lib/Account.php - line 570: OCA\Mail\Account->getMailboxes()
/www/htdocs/xxx/nextcloud/apps/mail/lib/Account.php - line 448: OCA\Mail\Account->getSpecialFolder('inbox', false)
/www/htdocs/xxx/nextcloud/apps/mail/lib/Service/UnifiedAccount.php - line 88: OCA\Mail\Account->getInbox()
/www/htdocs/xxx/nextcloud/apps/mail/lib/Service/UnifiedAccount.php - line 71: OCA\Mail\Service\UnifiedAccount->buildInbox()
/www/htdocs/xxx/nextcloud/apps/mail/lib/Controller/FoldersController.php - line 62: OCA\Mail\Service\UnifiedAccount->jsonSerialize()
[internal function] OCA\Mail\Controller\FoldersController->index(-1)
/www/htdocs/xxx/nextcloud/lib/private/AppFramework/Http/Dispatcher.php - line 160: call_user_func_array(Array, Array)
/www/htdocs/xxx/nextcloud/lib/private/AppFramework/Http/Dispatcher.php - line 90: OC\AppFramework\Http\Dispatcher->executeController(Object(OCA\Mail\Controller\FoldersController), 'index')
/www/htdocs/xxx/nextcloud/lib/private/AppFramework/App.php - line 114: OC\AppFramework\Http\Dispatcher->dispatch(Object(OCA\Mail\Controller\FoldersController), 'index')
/www/htdocs/xxx/nextcloud/lib/private/AppFramework/Routing/RouteActionHandler.php - line 47: OC\AppFramework\App main('OCA\\Mail\\Contro...', 'index', Object(OC\AppFramework\DependencyInjection\DIContainer), Array)
[internal function] OC\AppFramework\Routing\RouteActionHandler->__invoke(Array)
/www/htdocs/xxx/nextcloud/lib/private/Route/Router.php - line 299: call_user_func(Object(OC\AppFramework\Routing\RouteActionHandler), Array)
/www/htdocs/xxx/nextcloud/lib/base.php - line 1010: OC\Route\Router->match('/apps/mail/acco...')
/www/htdocs/xxx/nextcloud/index.php - line 40: OC handleRequest()
{main}```
Insert your server log here
```
</details>

##### Horde IMAP log (data/horde_imap.log)
<details>
```
Insert your horde IMAP log here, see https://github.com/nextcloud/mail#debug-mode
```
</details>

##### Horde SMTP log (data/horde_smtp.log)
<details>
```
Insert your horde SMTP log here, see https://github.com/nextcloud/mail#debug-mode
```
</details>

##### Browser log
<details>
```
Insert your browser log here, this could for example include:

a) The javascript console log
b) The network log 
c) ...
```
</details>


What else do we need?

**Comment by ChristophWurst** [comment]
Hey,

please fill out the full issue template. Apparently some useful information is missing. Thanks :)

**Comment by Manuelibt** [comment]
updated my last comment.

**Comment by Bullnados** [comment]
### Steps to reproduce
1.Create new account
2. Load Inbox(Lot of Mails ~1000)

### Expected behaviour
Mails should be loaded

### Actual behaviour
Fehler beim Laden

### Mail app

**Mail app version:**
0.6.2

**Mailserver or service:**
gmx.com

**Number of accounts:**
1

### Server configuration
**Operating system**:

**Web server:**
MYSQL
**Database:**
5.7.15
**PHP version:**
7.0

**Version:** (see admin page)
11.0.2


#### Logs

##### Server log (data/nextcloud.log)
<details>
``` 

    TypeError: Argument 1 passed to OCA\Mail\Model\IMAPMessage::hordeToAssoc() must be an instance of Horde_Mail_Rfc822_Address, instance of Horde_Mail_Rfc822_Group given, called in /www/Folder/SubFolder//apps/mail/lib/Model/ConvertAddresses.php on line 74
    /www/Folder/SubFolder//apps/mail/lib/Model/ConvertAddresses.php - line 74: OCA\Mail\Model\IMAPMessage->hordeToAssoc(Object(Horde_Mail_Rfc822_Group))
    /www/Folder/SubFolder//apps/mail/lib/Model/IMAPMessage.php - line 225: OCA\Mail\Model\IMAPMessage->convertAddressList(Object(Horde_Mail_Rfc822_List))
    /www/Folder/SubFolder//apps/mail/lib/Model/IMAPMessage.php - line 494: OCA\Mail\Model\IMAPMessage->getToList(true)
    /www/Folder/SubFolder//apps/mail/lib/Mailbox.php - line 190: OCA\Mail\Model\IMAPMessage->jsonSerialize()
    /www/Folder/SubFolder//apps/mail/lib/Controller/MessagesController.php - line 137: OCA\Mail\Mailbox->getMessages(0, 21, '')
    [internal function] OCA\Mail\Controller\MessagesController->index(1, 'SU5CT1g=', 0, 20, '', NULL)
    /www/Folder/SubFolder//lib/private/AppFramework/Http/Dispatcher.php - line 160: call_user_func_array(Array, Array)
    /www/Folder/SubFolder//lib/private/AppFramework/Http/Dispatcher.php - line 90: OC\AppFramework\Http\Dispatcher->executeController(Object(OCA\Mail\Controller\MessagesController), 'index')
    /www/Folder/SubFolder//lib/private/AppFramework/App.php - line 114: OC\AppFramework\Http\Dispatcher->dispatch(Object(OCA\Mail\Controller\MessagesController), 'index')
    /www/Folder/SubFolder//lib/private/AppFramework/Routing/RouteActionHandler.php - line 47: OC\AppFramework\App main('OCA\\Mail\\Contro...', 'index', Object(OC\AppFramework\DependencyInjection\DIContainer), Array)
    [internal function] OC\AppFramework\Routing\RouteActionHandler->__invoke(Array)
    /www/Folder/SubFolder//lib/private/Route/Router.php - line 299: call_user_func(Object(OC\AppFramework\Routing\RouteActionHandler), Array)
    /www/Folder/SubFolder//lib/base.php - line 1010: OC\Route\Router->match('/apps/mail/acco...')
    /www/Folder/SubFolder//index.php - line 40: OC handleRequest()
    {main}
```
</details>

**Comment by ChristophWurst** [comment]
> TypeError: Argument 1 passed to OCA\Mail\Model\IMAPMessage::hordeToAssoc() must be an instance of Horde_Mail_Rfc822_Address, instance of Horde_Mail_Rfc822_Group given, called in /www/Folder/SubFolder//apps/mail/lib/Model/ConvertAddresses.php on line 74

Fixed by https://github.com/nextcloud/mail/pull/339
