### ISSUE TITLE
Answering email from second account does not select the right identity

### ISSUE THREAD

**Issue by grubshka** [nextcloud/mail#333]
### Steps to reproduce
1. Configure multiple email account
2. Answer an email from the second account

### Expected behaviour
The selected identity should be the one matching the email account

### Actual behaviour
The selected identity is the one from the first account

### Mail app

**Mail app version:** 0.6.2

**Mailserver or service:** Postfix 2.11.3

**Transport security - IMAP:** STARTTLS

**Transport security - SMTP:** STARTTLS

**Number of accounts:** 3

### Server configuration
**Operating system**: Debian 8

**Web server:** Nginx 1.10.3

**Database:** MariaDB 10.0.29

**PHP version:** 7.0.16

**Version:** 11.0.2

**Updated from an older version or fresh install:** fresh install

**List of activated apps:**
  - activity: 2.4.1
  - bookmarks: 0.9.1
  - calendar: 1.5.1
  - comments: 1.1.0
  - contacts: 1.5.3
  - dav: 1.1.1
  - direct_menu: 0.10.0
  - federatedfilesharing: 1.1.1
  - federation: 1.1.1
  - files: 1.6.1
  - files_pdfviewer: 1.0.1
  - files_sharing: 1.1.1
  - files_texteditor: 2.2
  - files_trashbin: 1.1.0
  - files_versions: 1.4.0
  - files_videoplayer: 1.0.0
  - firstrunwizard: 2.0
  - gallery: 16.0.0
  - logreader: 2.0.0
  - lookup_server_connector: 1.0.0
  - mail: 0.6.2
  - nextcloud_announcements: 1.0
  - notes: 2.2.0
  - notifications: 1.0.1
  - password_policy: 1.1.0
  - provisioning_api: 1.1.0
  - serverinfo: 1.1.1
  - sharebymail: 1.0.1
  - spreed: 1.2.0
  - survey_client: 0.1.5
  - systemtags: 1.1.3
  - tasks: 0.9.5
  - theming: 1.1.1
  - twofactor_backupcodes: 1.0.0
  - updatenotification: 1.1.1
  - workflowengine: 1.1.1

**The content of config/config.php:**

<details>
{
    "system": {
        "instanceid": "ociq7ill3rgk",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "***REMOVED SENSITIVE VALUE***",
        ],
        "datadirectory": "***REMOVED SENSITIVE VALUE***",
        "overwrite.cli.url": "***REMOVED SENSITIVE VALUE***",
        "dbtype": "mysql",
        "version": "11.0.2.7",
        "dbname": "sys_nextcloud",
        "dbhost": "localhost",
        "dbport": "",
        "dbtableprefix": "oc_",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "logtimezone": "UTC",
        "installed": true,
        "mail_smtpmode": "php",
        "mail_smtpsecure": "tls",
        "mail_smtpauthtype": "LOGIN",
        "mail_smtpauth": 1,
        "mail_from_address": "webmaster",
        "mail_domain": "***REMOVED SENSITIVE VALUE***",
        "defaultapp": "mail",
        "app.mail.imaplog.enabled": true,
        "app.mail.smtplog.enabled": true
    }
}
</details>

#### Client configuration
**Browser:** Firefox 51.0.1

**Operating system:** Debian testing

##### Web server error log
Nothing here

##### Server log (data/nextcloud.log)
Nothing here

##### Horde IMAP log (data/horde_imap.log)
Not relevant

##### Horde SMTP log (data/horde_smtp.log)
Not relevant

##### Browser log
Probably not relevant, but here it is :
<details>
[ui] "search:set" Array [ "" ]  mail.min.js:148:14867
[ui] "content:loading" Array [ "Chargement de Boîte de réception" ]  mail.min.js:148:14867
[ui] "composer:leave" Array [  ]  mail.min.js:148:14867
[folder] "setactive" Array [ Object, Object ]  mail.min.js:148:14867
[message] "entities" Array [ Object, Object, Object ]  mail.min.js:148:14867
[ui] "foldercontent:show" Array [ Object, Object, Object ]  mail.min.js:148:14867
[ui] "folder:changed" Array [  ]  mail.min.js:148:14867
[ui] "title:update" Array [  ]  mail.min.js:148:14867
[ui] "messagesview:message:setactive" Array [ null ]  mail.min.js:148:14867
[message] "bodies" Array [ Object, Object, Array[10] ]  mail.min.js:148:14867
[message] "fetch:bodies" Array [ Object, Object, Array[10] ]  mail.min.js:148:14867
[ui] "composer:leave" Array [  ]  mail.min.js:148:14867
[ui] "message:loading" Array [  ]  mail.min.js:148:14867
[ui] "title:update" Array [  ]  mail.min.js:148:14867
[ui] "messagesview:message:setactive" Array [ Object ]  mail.min.js:148:14867
[message] "entity" Array [ Object, Object, 4548 ]  mail.min.js:148:14867
[ui] "composer:events:undelegate" Array [  ]  mail.min.js:148:14867
[message] "flag" Array [ Object, Object, Object, "unseen", false ]  mail.min.js:148:14867
[ui] "messagesview:messageflag:set" Array [ 4548, "unseen", false ]  mail.min.js:148:14867
[ui] "message:show" Array [ Object ]  mail.min.js:148:14867
[message] "load" Array [ Object, Object, Object ]  mail.min.js:148:14867
[message] "entities" Array [ Object, Object, Object ]  mail.min.js:148:14867
[ui] "messagesview:messages:update" Array [  ]  mail.min.js:148:14867
[folder] "setactive" Array [ Object, Object ]  mail.min.js:148:14867
[navigation] "folder" Array [ 9, "SU5CT1g=", false ]  mail.min.js:148:14867
[ui] "document:click" Array [ Object ]  mail.min.js:148:14867
[ui] "document:click" Array [ Object ]  mail.min.js:148:14867
GET 
https://XXX/apps/mail/accounts/9/folders/SU5CT1g=/messages/4548/html [HTTP/1.1 200 OK 0 ms]
GET 
XHR 
https://XXX/apps/mail/accounts/9/folders/SU5CT1g%3D/messages [HTTP/1.1 200 OK 321 ms]
[ui] "title:update" Array [  ]  mail.min.js:148:14867
[ui] "messagesview:message:setactive" Array [ Object ]  mail.min.js:148:14867
Content Security Policy: Les paramètres de la page ont empêché le chargement d’une ressource à self (« script-src 'nonce-VGhGVFFDbU9xN0E2WmNPdGp0TW1jbkgrL2VYTHhjWnJDaUxkdUs0NU82Zz06RmtWbEltVC82dlJQSUt5WS9lcGpSMGVYeWRLcWphZ1laaHF4L2VKVGJzdz0=' »).
</details>

**Comment by ChristophWurst** [comment]
Dup of https://github.com/nextcloud/mail/issues/175 :-)

**Comment by grubshka** [comment]
Sorry
