### ISSUE TITLE
Mail not loading.

### ISSUE THREAD

**Issue by hobleyd** [nextcloud/mail#3330]
### Expected behavior
The email isn't getting loaded - many stacktraces appear in the logs:

### Actual behavior
OCA\Mail\Exception\ServiceException: Sync failed for 1:INBOX: Argument 3 passed to OCA\Mail\Model\IMAPMessage::__construct() must be of the type int, null given, called in /var/snap/nextcloud/21796/nextcloud/extra-apps/mail/lib/IMAP/MessageMapper.php on line 219

    /var/snap/nextcloud/21796/nextcloud/extra-apps/mail/lib/Service/Sync/SyncService.php - line 126:

    OCA\Mail\Service\Sync\ImapToDbSynchronizer->sync(OCA\Mail\Account {}, OCA\Mail\Db\Mailbox { id: 92}, 42, [], true)

    /var/snap/nextcloud/21796/nextcloud/extra-apps/mail/lib/Controller/FoldersController.php - line 124:

    OCA\Mail\Service\Sync\SyncService->syncMailbox(OCA\Mail\Account {}, "INBOX", 42, [], false, "is:important")

    /snap/nextcloud/21796/htdocs/lib/private/AppFramework/Http/Dispatcher.php - line 170:

    OCA\Mail\Controller\FoldersController->sync(1, "SU5CT1g=", [], true, "is:important")

    /snap/nextcloud/21796/htdocs/lib/private/AppFramework/Http/Dispatcher.php - line 100:

    OC\AppFramework\Http\Dispatcher->executeController(OCA\Mail\Con ... {}, "sync")

    /snap/nextcloud/21796/htdocs/lib/private/AppFramework/App.php - line 137:

    OC\AppFramework\Http\Dispatcher->dispatch(OCA\Mail\Con ... {}, "sync")

    /snap/nextcloud/21796/htdocs/lib/private/AppFramework/Routing/RouteActionHandler.php - line 47:

    OC\AppFramework\App::main("OCA\\Mail\\ ... r", "sync", OC\AppFramew ... {}, { accountId: ... "})

    <<closure>>

    OC\AppFramework\Routing\RouteActionHandler->__invoke({ accountId: ... "})

    /snap/nextcloud/21796/htdocs/lib/private/Route/Router.php - line 297:

    call_user_func(OC\AppFramew ... {}, { accountId: ... "})

    /snap/nextcloud/21796/htdocs/lib/base.php - line 1007:

    OC\Route\Router->match("/apps/mail/ ... c")

    /snap/nextcloud/21796/htdocs/index.php - line 37:

    OC::handleRequest()

Caused by TypeError: Argument 3 passed to OCA\Mail\Model\IMAPMessage::__construct() must be of the type int, null given, called in /var/snap/nextcloud/21796/nextcloud/extra-apps/mail/lib/IMAP/MessageMapper.php on line 219

    /var/snap/nextcloud/21796/nextcloud/extra-apps/mail/lib/IMAP/MessageMapper.php - line 219:

    OCA\Mail\Model\IMAPMessage->__construct(Horde_Imap_C ... e}, "INBOX", null, "*** sensiti ... *")

    <<closure>>

    OCA\Mail\IMAP\MessageMapper->OCA\Mail\IMAP\{closure}("*** sensiti ... *")

    /var/snap/nextcloud/21796/nextcloud/extra-apps/mail/lib/IMAP/MessageMapper.php - line 225:

    array_map(Closure {}, [ "*** sensi ... }])

    /var/snap/nextcloud/21796/nextcloud/extra-apps/mail/lib/IMAP/MessageMapper.php - line 181:

    OCA\Mail\IMAP\MessageMapper->findByIds(Horde_Imap_C ... e}, "INBOX", [ 90486,9049 ... 8])

    /var/snap/nextcloud/21796/nextcloud/extra-apps/mail/lib/Service/Sync/ImapToDbSynchronizer.php - line 241:

    OCA\Mail\IMAP\MessageMapper->findAll(Horde_Imap_C ... e}, "INBOX", 5000, 0)

    /var/snap/nextcloud/21796/nextcloud/extra-apps/mail/lib/Service/Sync/ImapToDbSynchronizer.php - line 199:

    OCA\Mail\Service\Sync\ImapToDbSynchronizer->runInitialSync(OCA\Mail\Account {}, OCA\Mail\Db\Mailbox { id: 92})

    /var/snap/nextcloud/21796/nextcloud/extra-apps/mail/lib/Service/Sync/SyncService.php - line 126:

    OCA\Mail\Service\Sync\ImapToDbSynchronizer->sync(OCA\Mail\Account {}, OCA\Mail\Db\Mailbox { id: 92}, 42, [], true)

    /var/snap/nextcloud/21796/nextcloud/extra-apps/mail/lib/Controller/FoldersController.php - line 124:

    OCA\Mail\Service\Sync\SyncService->syncMailbox(OCA\Mail\Account {}, "INBOX", 42, [], false, "is:important")

    /snap/nextcloud/21796/htdocs/lib/private/AppFramework/Http/Dispatcher.php - line 170:

    OCA\Mail\Controller\FoldersController->sync(1, "SU5CT1g=", [], true, "is:important")

    /snap/nextcloud/21796/htdocs/lib/private/AppFramework/Http/Dispatcher.php - line 100:

    OC\AppFramework\Http\Dispatcher->executeController(OCA\Mail\Con ... {}, "sync")

    /snap/nextcloud/21796/htdocs/lib/private/AppFramework/App.php - line 137:

    OC\AppFramework\Http\Dispatcher->dispatch(OCA\Mail\Con ... {}, "sync")

    /snap/nextcloud/21796/htdocs/lib/private/AppFramework/Routing/RouteActionHandler.php - line 47:

    OC\AppFramework\App::main("OCA\\Mail\\ ... r", "sync", OC\AppFramew ... {}, { accountId: ... "})

    <<closure>>

    OC\AppFramework\Routing\RouteActionHandler->__invoke({ accountId: ... "})

    /snap/nextcloud/21796/htdocs/lib/private/Route/Router.php - line 297:

    call_user_func(OC\AppFramew ... {}, { accountId: ... "})

    /snap/nextcloud/21796/htdocs/lib/base.php - line 1007:

    OC\Route\Router->match("/apps/mail/ ... c")

    /snap/nextcloud/21796/htdocs/index.php - line 37:

    OC::handleRequest()

### Mail app

**Mail app version:** 1.4.0

**Mailserver or service:** Kopano 8.7.0-7ubuntu1

### Server configuration

**Operating system**: Ubuntu 20.04

**Web server:** Whatever is in the snap. Apache I think.

**Database:** MariaDB

**PHP version:** Whatever is in the snap (not sure, sorry).

**Nextcloud Version:** 19.0.0 (snap distribution)

#### Client configuration
**Browser:** Firefox 77.0.1

**Operating system:** Ubuntu 18.04

**Comment by ChristophWurst** [comment]
> Argument 3 passed to OCA\Mail\Model\IMAPMessage::__construct() must be of the type int, null given

Phew. This is a tricky one. It basically means there is an IMAP message without a UID. Could you check Kopano related issues?

**Comment by ChristophWurst** [comment]
We definitely request the UID. But if it's not there, Horde will give us `null`.
![Bildschirmfoto von 2020-06-29 10-18-57](https://user-images.githubusercontent.com/1374172/85990270-0d9f7680-b9f2-11ea-8075-81f6144218d9.png)

My guess is that the IMAP server does not behave correctly.

**Comment by hobleyd** [comment]
Magic, thanks. I'll follow up with Kopano.

**Comment by LicoMonch** [comment]
@hobleyd 
It would be helpful, if you could at least mention a reference of how and where you 'followed up' 🥺

**Comment by LicoMonch** [comment]
As an addition I want to mention a few things:
1. I face the same problem (bet you didn't know that :D )
2. I use kopano which was formerly a zarafa install
3. I see mails .. but not all and I cannot see a pattern, which are affected and which are not (thats a bit hard on a mailbox with >100k mails :) ). Some folders just work, some not, some have all the same origin, some not .. also some folder are shown twice

If anyone has an idea, I'd be happy to try ;)

I'll keep this updated, if I find something.

**Comment by hobleyd** [comment]
> @hobleyd
> It would be helpful, if you could at least mention a reference of how and where you 'followed up' pleading_face

https://forum.kopano.io/topic/3274/imap-messages-without-uid
