### ISSUE TITLE
Backgroundcolor missing when there's no account yet

### ISSUE THREAD

**Issue by DjSlash** [nextcloud/mail#3340]
### Expected behavior
When the mail-app is opened and there are no accounts defined, there's a form presented to add an account. There should be a backgroundcolor on that page.

### Actual behavior

That page is missing a background-color, where the default browser-backgroundcolor takes place. If this is not what one would expect, colors may not match. Screenshot to present the case:
![2020-07-03-11:12:22](https://user-images.githubusercontent.com/538802/86454758-06dd7000-bd20-11ea-8a9d-943b28b966b7.png)

### Mail app

**Mail app version:** 1.4.0

### Server configuration

**Nextcloud Version:** 18.0.6

###

 Client configuration
**Browser:** Firefox 77

**Comment by ChristophWurst** [comment]
does that also happen on another browser? is this possibly caused by one of you browser extensions

**Comment by DjSlash** [comment]
It is a preference you can set in your browser. At least in Firefox this is the case.
![2020-07-03-13:25:13](https://user-images.githubusercontent.com/538802/86465193-7a3bad80-bd31-11ea-8a84-570b804dc6c7.png)

**Comment by ChristophWurst** [comment]
:eyes: @nextcloud/designers because I doubt we handle this any better in other contexts.

**Comment by juliushaertl** [comment]
We have a background color set on the body, so I don't see how the browser default could overwrite this:

![image](https://user-images.githubusercontent.com/3404133/125403361-bb8b8200-e3b5-11eb-98ea-d22a5b005ef8.png)

**Comment by DjSlash** [comment]
Well, this issue was about Mail-app version 1.4.0 and NC 18. There have been several releases with both that might have resolved the issue. With NC 20.0.11 and Mail 1.10.1, it doesn't have the behavior as mentioned in my original post. Since that is the case, I'll be closing the issue.
