### ISSUE TITLE
Could not extract app mail

### ISSUE THREAD

**Issue by arnesgurda** [nextcloud/mail#3354]
At the beginning of Nextcloud installation I didn't choose to install recommended apps. Now, I have installed Contacts, Calendar and I want to install Email but unsuccessful. I am getting a message "Could not extract app mail". What is the problem?

**Comment by ChristophWurst** [comment]
The Nextcloud mail app offers an extensive logging system to make it easier identifying and tracking down bugs. Please set the log [level to debug](https://docs.nextcloud.com/server/stable/admin_manual/configuration_server/logging_configuration.html) in your admin settings. Then, try to reproduce your issue and take another look at `data/nextcloud.log.
