### ISSUE TITLE
after upgrading to 1.4.1 all inbox messages collapsed into one

### ISSUE THREAD

**Issue by aol-nnov** [nextcloud/mail#3365]
### Expected behavior
inbox content should be displayed

### Actual behavior
<img width="644" alt="image" src="https://user-images.githubusercontent.com/43190/87302086-6b1ae380-c519-11ea-852b-666bc340cf65.png">

when item with question mark is selected, the pane on the right displays random email message contents.

### Mail app

**Mail app version:** 1.4.1

**Mailserver or service:** Zimbra (not sure how to tell the version. I do not control the server)

### Server configuration

official nextcloud docker image

**Nextcloud Version:** 18.0.4

#### Client configuration
**Browser:** Chrome 83.0.4103.116 (Official Build) (64-bit)

**Operating system:** MacOS

**Comment by ChristophWurst** [comment]
You can try to enable debug mode, then from the menu that is visible on the screenshot a new entry "Clear cache" will appear. After the page load I'd like to know if the same issue persists.

Also, is there any errors in nextcloud.log?

**Comment by aol-nnov** [comment]
@ChristophWurst please tell me, how to enable debug mode?

I'll look into nextcloud.log shortly.

**Comment by aol-nnov** [comment]
Jh, you were referring to system-wide debug flag, gotcha.

Clearing cache helped. but it is not available to the ordinary user, unfortunately..

**Comment by ChristophWurst** [comment]
of course, but I just wanted to know if that was possibly an issue with the migration. 1.4.1 didn't change much in regards to how we sync – are you 100% sure this happened when you upgraded? Is there a chance this was already in that state before?

**Comment by aol-nnov** [comment]
@ChristophWurst yes, it happened after update, definitely. But I'm not sure from what version I was updating..

As for now, I'm using nc mail from time to time and can't help waiting when you roll out threading feature! ))

I must admit, mail app improved drastically over the past year, thank you for your commitment!

**Comment by GretaD** [comment]
All good with this one, should we close it?
