### ISSUE TITLE
Documentation does not list features and configuration documentation (e.g. admin documentation) is very vague and seems like it might be incomplete

### ISSUE THREAD

**Issue by lelutin** [nextcloud/mail#3372]
### Expected behavior
I don't know how to configure NextCloud Mail and what it can and cannot do. What are the expected use cases (e.g. can admins pre-configure a mailbox for nextcloud users with a certain pattern or are users expected to configure an account from scratch?)

### Actual behavior
More documentation would be needed

**Comment by ChristophWurst** [comment]
For the most part there is no admin config needed really. That is more of a thing that enterprise users need.

Are you missing anything specific?

**Comment by lelutin** [comment]
sorry I should've been more specific.
there's two settings I can find in the code that aren't mentioned in the documentation: `app.mail.verify-tls-peer` and `app.mail.accounts.default`

**Comment by ChristophWurst** [comment]
> app.mail.verify-tls-peer

Yeah, that one should be documented indeed. Would you like to send a little PR that adds a note? The setting will simply turn off TLS verfication for IMAP/SMTP. This happens globally for all accounts and is only needed in edge cases like with email servers that have a self-signed certificate.

> app.mail.accounts.default

This is a deprecated setting. The code only has it to run an automated migration to the new settings. This must not be used these days.

**Comment by lelutin** [comment]
> > app.mail.verify-tls-peer
> 
> Yeah, that one should be documented indeed. Would you like to send a little PR that adds a note? The setting will simply turn off TLS verfication for IMAP/SMTP. This happens globally for all accounts and is only needed in edge cases like with email servers that have a self-signed certificate.

I unfortunately don't think I'll continue using nextcloud mail since it doesn't answer the needs we have for our project. So in this sense, I don't intend to dedicate efforts to making documentation better anymore.

> > app.mail.accounts.default
> 
> This is a deprecated setting. The code only has it to run an automated migration to the new settings. This must not be used these days.

oh that's a bummer.. is it possible to have somewhat the same functionality from the new settings? e.g. define some kind of template for username so that email accounts can be somewhat pre-configured for nextcloud users?
