### ISSUE TITLE
Content Security Policy prevents loading HTML emails

### ISSUE THREAD

**Issue by pixelipo** [nextcloud/mail#338]
Hello,

I'm sometimes accessing my Nextcloud instance through a secure tunnel-based service. This causes the problem with loading body of HTML-formatted emails in the Mail app:

```
<div id="mail-content">
    ...
    <div class="icon-loading">
        <iframe src="http://*.*.io/apps/mail/accounts/-1/folders/*/messages/*/html" seamless=""></iframe>
    </div>
</div>
```

Since HTML emails are rendered using an iframe, the get blocked by CSP:

> Content Security Policy: The page’s settings blocked the loading of a resource at https://***.***.io/apps/mail/accounts/-1/folders/***/messages/***/html (“frame-src https://***.***.io”).

Is there a special reason for `{{#if hasHtmlBody}}`?

P.S. Thanks for developing this app :smiley:

**Comment by ChristophWurst** [comment]
> Is there a special reason for {{#if hasHtmlBody}}?

There are also plain text messages, which can be rendered directly without an iframe :)

**Comment by SentToDevNull** [comment]
The fix for this is fairly easy. Just change "http" to "https" if the server the nextcloud instance is running on uses https. That way it won't break non-https installs, and it won't violate the CSP for https installs.

**Comment by ChristophWurst** [comment]
@SentToDevNull URLs should be generated with the correct http/https prefix. Are you using a reverse proxy? If so, please see the admin manual on how to set up Nextcloud to work correctly with it. Basically, you have to tell it which scheme is used for the connection to the proxy.

**Comment by pixelipo** [comment]
@ChristophWurst I set up reverse proxy as per admin [instructions](https://docs.nextcloud.com/server/11/admin_manual/configuration_server/reverse_proxy_configuration.html) and I get correct prefix (https), but I'm still getting these errors:

> Load denied by X-Frame-Options: https://***.***.io/apps/mail/accounts/-1/folders/***/messages/***/html does not permit framing.  (unknown)
> TypeError: t is undefined[Learn More]  mail.min.js:152:20388

Network status of the object is 200, but Response is empty, but when I try resending the exact same request (without modifying headers), I get a full htmlBody in response...

**Comment by ChristophWurst** [comment]
cc @LukasReschke

**Comment by SentToDevNull** [comment]
@ChristophWurst I did not configure any reverse proxy. My entire nextcloud setup just involved unzipping the nextcloud tarball and following the instructions to configure a mysql database, and then installing apps from the app store.

**Comment by SentToDevNull** [comment]
@ChristophWurst To load html mail on an https server, a reverse proxy is needed, so when the app installs on an ssl-enabled server, it should probably ensure that `'overwriteprotocol' => 'https',` is found in nextcloud/config/config.conf and add that line if it's not there already.

**Comment by ChristophWurst** [comment]
Hm. So you're **not** using a reverse proxy but you had to overwrite the protocol to https? Interesting. I have some instances using SSL, I've never had to set that config flag.

**Comment by DoubleMalt** [comment]
@SentToDevNull Did you restart apache after adding the config line?
I added it, but it still creates a frame with a http src :(

**Comment by SentToDevNull** [comment]
@DoubleMalt It took a `service apache2 restart` for me.

**Comment by pixelipo** [comment]
Works for me as well. We can mark this as Closed as far as I'm concerened

**Comment by ChristophWurst** [comment]
> Works for me as well

Great to hear it's working. Closing this ticket thus. Please re-open if someone encounters this problem again and the provided solution doesn't work.
