### ISSUE TITLE
Account Creation error: 64-byte password

### ISSUE THREAD

**Issue by Amgine0** [nextcloud/mail#340]
### Steps to reproduce
1. Attempt to create account for e-mail account secured with 64B password

### Expected behaviour
Account should be created, e-mail server accessed.

### Actual behaviour
Creating account failed: An exception occurred while executing 'INSERT INTO ...: SQLSTATE[22001]: String data, right truncated: 1406 Data too long for column 'inbound_password' at row 1

### Mail app

**Mail app version:** 0.6.2

**Mailserver or service:** Gmail

**Transport security - IMAP:** SSL

**Transport security - SMTP:** SSL

**Number of accounts:** First

**Mail app version build date:** (only if you are using a Nightly Build)

### Server configuration
**Operating system**: Ubuntu 16.04

**Web server:** Apache2

**Database:** MySQL

**PHP version:** 7.0.whatever

**Version:** 11.0.1

**Updated from an older version or fresh install:** Older

**List of activated apps:**

```
If you have access to your command line run e.g.:
sudo -u www-data php occ app:list
from within your server installation folder
```

**The content of config/config.php:**

<details>
```
If you have access to your command line run e.g.:
sudo -u www-data php occ config:list system
from within your server installation folder

or 

Insert your config.php content here
(Without the database password, passwordsalt and secret)
```
</details>

#### Client configuration
**Browser:**

**Operating system:**

##### Web server error log
```
Insert your webserver log here
```

##### Server log (data/nextcloud.log)
<details>
```
Insert your server log here
```
</details>

##### Horde IMAP log (data/horde_imap.log)
<details>
```
Insert your horde IMAP log here, see https://github.com/nextcloud/mail#debug-mode
```
</details>

##### Horde SMTP log (data/horde_smtp.log)
<details>
```
Insert your horde SMTP log here, see https://github.com/nextcloud/mail#debug-mode
```
</details>

##### Browser log
<details>
```
Insert your browser log here, this could for example include:

a) The javascript console log
b) The network log 
c) ...
```
</details>

**Comment by verwilst** [comment]
Had the same issue with a long password. 

alter table oc_mail_accounts modify `outbound_password` varchar(512) COLLATE utf8_bin DEFAULT NULL;
alter table oc_mail_accounts modify `inbound_password` varchar(512) COLLATE utf8_bin DEFAULT NULL;

fixed it for me in the meantime.

**Comment by ChristophWurst** [comment]
Could one of you create a pull request for this? :-)

The schema is defined in https://github.com/nextcloud/mail/blob/6ca4597723658fc2977560cdb9c65c77f9c29e9c/appinfo/database.xml#L72 and increasting the version number in `info.xml` will trigger a migration.

**Comment by toolstack** [comment]
I ran in to this error as well so I created a PR for it.
