### ISSUE TITLE
Account-Setting not full loaded

### ISSUE THREAD

**Issue by omocinteractive** [nextcloud/mail#3403]
### Expected behavior
When i click on "Edit Account" on different accounts, all account-settings should be show.

### Actual behavior
When i click on "Edit Account" on different accounts, only name and mail-adress on the top are reloaded, not the rest like signature - it's show the setting from the account before.

### Mail app

1.4.1
### Server configuration

Ubuntu

Apache, NGINX

MySQL

PHP 7.3

newest

Firefox, Chrome
Windows 10

**Comment by IchbinkeinReh** [comment]
I just tested this and the issue is already fixed on the master branch

**Comment by omocinteractive** [comment]
... okay, thx!
