### ISSUE TITLE
NONE for authentication type doesn't work. Defaults to SASL anyways

### ISSUE THREAD

**Issue by IMbiea** [nextcloud/mail#3406]
### Expected behavior
NONE, on TCP port 25, should be allowed, and without the password/username field being required

### Actual behavior
This used to work. But now, you cannot complete the webform to use NONE for authentication 

### Mail app

**1.4.1 of the app

** Using NextCloud webmail via Nextcloud 18.0.7

### Server configuration

**Gentoo - Stable **

**apache 2.4.43 :**

**mariadb-10.4.13** 
**php 7.3 **
**Nextcloud Version:** (see admin page, e.g. 13.0.2)

#### Client configuration
**Firefox 78.0.2**
**Gentoo Stable **

**Comment by ChristophWurst** [comment]
> This used to work

We always had password auth as only authentication method.

https://github.com/nextcloud/mail/issues/3146 will add more auth possibilities, and that should also make it possible to use **none**.
