### ISSUE TITLE
Inline image in mail discarded without chance of loading it

### ISSUE THREAD

**Issue by JensErat** [nextcloud/mail#3419]
### Expected behavior

Deutsche Post Briefankündigung sends envelope pictures as email. They use rather uncommon HTML mails with inline images though.

```html
        <div id=3D"avis-email-body">
            <p>Lieber Herr ...,</p>
            <p class=3D"vertical-spacer">
                ein Brief ist unterwegs zu Ihnen und wird in K=C3=BCrze in =
Ihren Briefkasten zugestellt.
            </p>
            <p class=3D"vertical-spacer">
               <img src=3D"data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAABA=
AAAAH+CAIAAACN3+saAACAAElEQVR42uzdebxN1f/48Y8MRZkyT4UkRBKFZkkyFUmmjIXKXHwiS=
dGnPpU0iCR8GmQMJSSZ8kEImedyzfN0zS73/NbvvL93fZa999n33HPOvfcMr+cf97HvOvvss897=
        ...
```

Inline-images have no privacy issues, display them (or at least show the load images button).

### Actual behavior

Nextcloud mail is not displaying this image, nor does it show the "load images" button. By checking the 

![image](https://user-images.githubusercontent.com/628441/89616212-43a10780-d888-11ea-886f-9c63c645cf88.png)

By checking the HTML in Firefox developer tools, I see that Nextcloud completely removed the image:

```html
          <div>
            <p>Lieber Herr REDACTED,</p>
            <p class="vertical-spacer">
                ein Brief ist unterwegs zu Ihnen und wird in Kürze in Ihren Briefkasten zugestellt.
            </p>
            <p class="vertical-spacer">
               </p>
            <p>
                Viele Grüße
                <br><br>
                Ihre Deutsche Post
            </p>
```
        
### Mail app

**Mail app version:** 1.4.1

**Mailserver or service:** Dovecot IMAP server

### Server configuration

**Operating system**: Ubuntu 18.04 on host / official Docker container

**Web server:** Apache

**Database:** MariaDB

**PHP version:** 7.4.6

**Nextcloud Version:** 1.19.0

#### Client configuration
**Browser:** Firefox 79.0

**Operating system:** Ubuntu 20.04

**Comment by ChristophWurst** [comment]
Whoops. We'll have a look. If you're interested in contributing some debug info or even a fix, let us know and we'll give a few pointers :)

It would also be helpful if you could export such an email as .eml or .mbox, so people that want to debug this can import the email :)
