### ISSUE TITLE
Avatars in unified search

### ISSUE THREAD

**Issue by jancborchardt** [nextcloud/mail#3432]
Right now we show the Mail app icon for each search result, which doesn’t add any additional information. Ideally it should look exactly like in the Mail app, showing avatars/Gravatars/favicons/placeholders etc.

![89879971-f5f80800-dbc3-11ea-804d-74d2925c61ab](https://user-images.githubusercontent.com/925062/89880255-538c5480-dbc4-11ea-9d04-3f083f06ee87.png)

cc @skjnldsv for unified search.

**Comment by skjnldsv** [comment]
Maybe srcset @ChristophWurst ?
So you could provide multiple thumbnailsUrl and it would automatically fallback to the second one if not available?

**Comment by skjnldsv** [comment]
Or you implement your own avatarProvider endpoint that fallback, that way this is just a long request from the front showing an icon while the avatar is loading.

**Comment by ChristophWurst** [comment]
Something like that, yes. But the fallback should probably be a colored two-letter avatar to be in line with the design of the message ist in main app view.

I'll have to analyze the current logic before I can make any plans for a solution. Let's finish the base search implementation first.

**Comment by StCyr** [comment]
closed by https://github.com/nextcloud/mail/pull/3563
