### ISSUE TITLE
add attachment from files sorting list

### ISSUE THREAD

**Issue by pafcioooo** [nextcloud/mail#345]
### Steps to reproduce
1. I have just created file added to some folders in files
2. Now I create an email and I choose add attachement from files
3. I need to search for file to choose it

### Expected behaviour
There should be an option to sort files by last modification

### Actual behaviour
Files are automaticall sorted by name thus choosing lastly added file with name ending some end of alphabet letters needs a lotf of scrolling and searching.

### Mail app

**Mail app version:** (see apps admin page)
0.6.2

I do not put any more details since this is new feature not bug.

**Comment by jancborchardt** [comment]
This has been fixed some time ago in the server through https://github.com/nextcloud/server/pull/12350 :) → closing
