### ISSUE TITLE
After message sending experience

### ISSUE THREAD

**Issue by jancborchardt** [nextcloud/mail#3453]
Currently when you send an email, you get
1. A blocking loading screen where you feel you have to wait
2. A rather empty confirmation screen with a not-so-relevant primary action:
![image](https://user-images.githubusercontent.com/925062/90408593-52699480-e0a8-11ea-9625-65fefb2da283.png)

Instead, what we should do:
- Show the loading and confirmation message as top right notification
- In the content area, show whatever was shown before the composer was opened

As discussed @ChristophWurst @violoncelloCH :) cc @GretaD

**Comment by StCyr** [comment]
Using toastify-js (as in nextcloud/server)?

**Comment by jancborchardt** [comment]
This has been fixed with the new notification for "Message sent" with "Undo" button now. :)
