### ISSUE TITLE
Dashboard widget empty state improvements

### ISSUE THREAD

**Issue by jancborchardt** [nextcloud/mail#3476]
As per https://github.com/nextcloud/server/issues/22339

- [ ] Mail: The image is a bit out of place, should use an icon instead. cc @ChristophWurst @GretaD 
    - [ ] When no accounts are set up: `icon-archive` from Mail, and text "No accounts configured".
    - [ ] When accounts are set up but there’s no important mails: `icon-checkmark`, "No important mails". If there are any other mails, we could also have that message be only 2 entries high and show other mails below like we do in Talk.

cc @ChristophWurst @GretaD

**Comment by GretaD** [comment]
fixed here: #3479
