### ISSUE TITLE
No message body shown

### ISSUE THREAD

**Issue by avanc** [nextcloud/mail#348]
### Steps to reproduce
1. Install mail app from git
2. Select a message
3.

### Expected behaviour
Mail body should be shown

### Actual behaviour
Nothing is shown, the area for the message is empty.
This is for all messages on my IMAP server. Get the following error message:

    Error	PHP	Undefined index: messages at /usr/share/webapps/nextcloud/apps/mail/lib/Folder.php#163	2017-03-28T22:03:08+0200

### Mail app

**Mail app version:** (see apps admin page)
0.6.2 build from git: https://github.com/nextcloud/mail/commit/3733b1b62193827d1022cc4c476bdffea899060d
I thought that this commit solves my problem of empty messages.

**Mail app version build date:** (only if you are using a Nightly Build)
Today build, see above.

### Server configuration
**Operating system**:
Linux 

**Web server:**
Apache 

**Database:**
MariaDB

**PHP version:**
7.1.2

**Version:** (see admin page)
11.0.2

**Comment by avanc** [comment]
Just some thoughts: Do I need to initiate some migration steps after installing a new version of mail app?
I was thinking that the older app maybe cached some information in file or in database and the new installation uses this old data? Or is everything newly fetched every time from IMAP?

**Comment by avanc** [comment]
Sorry, I missed some (maybe) usefull log information:

    Error	PHP	Undefined index: messages at /usr/share/webapps/nextcloud/apps/mail/lib/Folder.php#163	2017-03-28T22:03:08+0200
    Error	PHP	Undefined index: messages at /usr/share/webapps/nextcloud/apps/mail/lib/Folder.php#162	2017-03-28T22:03:08+0200
    Error	PHP	Undefined index: unseen at /usr/share/webapps/nextcloud/apps/mail/lib/Folder.php#161	2017-03-28T22:03:08+0200

**Comment by ChristophWurst** [comment]
> Just some thoughts: Do I need to initiate some migration steps after installing a new version of mail app?
> I was thinking that the older app maybe cached some information in file or in database and the new installation uses this old data? Or is everything newly fetched every time from IMAP?

No, it should migrate automatically.

**Comment by ChristophWurst** [comment]
Thanks for checking out the the latest development snapshot. This looks like a bug, hence something we have to fix. Feel free to dive into the code and fix this bug, shouldn't be too hard to find I presume 😉

**Comment by avanc** [comment]
Problem cannot be reproduces with latest version (0.6.3).
