### ISSUE TITLE
Adding a new account a bit buggy at the moment

### ISSUE THREAD

**Issue by jancborchardt** [nextcloud/mail#349]
When I add a new account, I get the notification

> Error while loading the accounts.
> TypeError: Cannot read property 'first' of undefined

Then I end in this state:
![capture du 2017-03-29 17-28-21](https://cloud.githubusercontent.com/assets/925062/24462782/3404ea80-14a5-11e7-8240-f4fb49414c83.png)

Any idea @nextcloud/mail, can you reproduce? I also had a similar thing when adding the first account.

@ChristophWurst is this possibly fixed by https://github.com/nextcloud/mail/pull/298 ?

**Comment by jancborchardt** [comment]
A simple refresh resolves the issue, but lands me on the setup page again.

The real flow of course should be:
- After adding an account, directly open that inbox and load it
- If it’s the second account or more, directly open the unified inbox and load it

**Comment by ChristophWurst** [comment]
Dup of https://github.com/nextcloud/mail/issues/320 ;-)

**Comment by jancborchardt** [comment]
Ah, sorry :) Added the relevant info there
