### ISSUE TITLE
Design of sidebar broken on Safari

### ISSUE THREAD

**Issue by MariusBluem** [nextcloud/mail#35]
Copy of https://github.com/owncloud/mail/issues/1598 😉 
### Expected behaviour

<img width="96" alt="ff" src="https://cloud.githubusercontent.com/assets/19711361/17303110/9419b6c8-581f-11e6-9edd-b84d269afe3c.png">
### Actual behaviour

<img width="89" alt="safari" src="https://cloud.githubusercontent.com/assets/19711361/17303116/9c2ed3fc-581f-11e6-8b96-308d2b07e9dc.png">
### ownCloud Mail

**ownCloud Mail version:** (see ownCloud apps admin page)
0.5.2
#### Server configuration

**PHP version:**
7.0.8
**ownCloud version:** (see ownCloud admin page)
Nextcloud 9.0.53
#### Client configuration

**Browser:**
Safari 9.1.1
**Operating system:**
OS X El Capitan

As discussed with @jancborchardt

**Comment by ChristophWurst** [comment]
Damn, happens in Gnome's web browser too
![nc_mail_06_search](https://cloud.githubusercontent.com/assets/1374172/18732824/6c451092-8066-11e6-8483-f303d1736920.png)

Now we have a reason to fix it

**Comment by ChristophWurst** [comment]
Fixed by https://github.com/nextcloud/mail/pull/357 thanks to @cubefoo :)
