### ISSUE TITLE
Support for PHP 7

### ISSUE THREAD

**Issue by kopfbild** [nextcloud/mail#350]
I have installed Nextcloud 11.0.2 with PHP 7.1.0. But i can't install Mail because the App-Installer tells me, that its not made for PHP 7:

> Die App kann nicht installiert werden, weil die folgenden Abhängigkeiten nicht erfüllt sind:
> PHP with a version lower than 7.0 is required.

Future PHP 7 Support would be great!

**Comment by ChristophWurst** [comment]
> Future PHP 7 Support would be great!

Sure 😉 

Dup of #299 #300 

Any help to get out a new release is very much appreciated. We still have some bugs on master that need to be fixed before we push out the next version.
