### ISSUE TITLE
option to de-activate the “important box”

### ISSUE THREAD

**Issue by tasstra** [nextcloud/mail#3503]
an option to de-activate the “important box” would be nice :)

and show "favorites box" only when there are favourites.

Thanks!

**Comment by StCyr** [comment]
Do you mean the "priority inbox" @tasstra ?

**Comment by ChristophWurst** [comment]
yes

**Comment by mase76** [comment]
I agree. I don't use that box, too.

**Comment by ChristophWurst** [comment]
duplicate of https://github.com/nextcloud/mail/issues/3265

**Comment by ChristophWurst** [comment]
@tasstra @mase76 please see https://github.com/nextcloud/mail/issues/3968 :v:
