### ISSUE TITLE
Error whilst deleting account

### ISSUE THREAD

**Issue by anpestud** [nextcloud/mail#351]
### Steps to reproduce
1. I have added my private mail server from all-inkl.com
2. Due to some issues, I added the same account a second time, but with different settings
3. Now I can't delete one of those accounts

### Expected behaviour
Mail account deleted 

### Actual behaviour
Error message "Error whilst deleting account"

### Mail app

**Mail app version:** (see apps admin page)

**Mailserver or service:** .....all-inkl.com

**Transport security - IMAP:** STARTTLS

**Transport security - SMTP:** STARTTLS

**Number of accounts:** 2

**Mail app version build date:** (only if you are using a Nightly Build)

#### Client configuration
**Browser:** Chrome

**Operating system:** Windows 10

**Comment by ChristophWurst** [comment]
Hey,

please fill out the full issue template. Especially the server logs (nextcloud.log) will be helpful. Thanks.

**Comment by ChristophWurst** [comment]
I'm closing this ticket now due to the lack of activity.
