### ISSUE TITLE
why only PHP versions lower than 7.0?

### ISSUE THREAD

**Issue by lowtower** [nextcloud/mail#352]
Hi,

is there any reason why only PHP versions LOWER than 7.0 are supported?

I have PHP 7.1.2 installed and get the following notice on the "apps-store":
"Die App kann nicht installiert werden, weil die folgenden Abhängigkeiten nicht erfüllt sind:
PHP with a version lower than 7.0 is required."

Cheers,
LT.

**Comment by ChristophWurst** [comment]
> is there any reason why only PHP versions LOWER than 7.0 are supported?

We support php >= 7.0, but the latest release doesn't. Will be fixed with the next release on the app store.

Dup of #299 #330 #350
