### ISSUE TITLE
Remove main folder name from sub-folder names in left pane

### ISSUE THREAD

**Issue by j-ed** [nextcloud/mail#3527]
## Expected behavior
The mail app shouldn't show main folder names in front of each sub-folder name to improve the readability of the folder list.

## Current behavior
The mail app always shows the main folder name in front of each sub-folder name. This wastes space which could be used to display the original sub-folder name.

![grafik](https://user-images.githubusercontent.com/2572764/91980678-edf53900-ed27-11ea-83f1-7c039b727df5.png)

### Steps to reproduce
1. Open the Mail app.
2. Check open a folder with sub folders.
3. Check how sub-folders are being displayed.

#### Server Configuration
OS: Linux 4.9.218
Web server: Apache2 2.4.46
Database: MariaDB 10.2.24
PHP version: 7.4.8
Nextcloud version: 19.0.2
Nextcloud Mail app version: 1.4.1
IMAP mail daemon: Panda IMAP

#### Client Configuration
Browser: Mozilla Firefox 80.0.1
Operating system: Windows 10

**Comment by ChristophWurst** [comment]
This was just tackled with #3147 :)
