### ISSUE TITLE
Error while creating the account

### ISSUE THREAD

**Issue by Shuvi-Hub** [nextcloud/mail#3534]
### Expected behavior
Tell us what should happen
Login/Create my Acc

### Actual behavior
Tell us what happens instead
Nothing just a little message that my acc can't created
![image](https://user-images.githubusercontent.com/66522712/92122626-f74fd580-edfb-11ea-84e9-ffc55e61b5a1.png)

### Mail app

**Mail app version:** (see apps admin page, e.g. 0.5.3)
1.4.1
**Mailserver or service:** (e.g. Outlook, Yahoo, Gmail, Exchange,...)
Gmail

### Server configuration

**Operating system**: (e.g. Debian 8)
Raspian OS
**Web server:** (e.g. Apache, Nginx,...)
Apache2
**Database:** (e.g. MariaDB, SQLite or PostgreSQL)
MariaDB
**PHP version:** (e.g. 7.0)
7.3
**Nextcloud Version:** (see admin page, e.g. 13.0.2)
19.0.2
#### Client configuration
**Browser:** (e.g. Firefox 48)
Crome
**Operating system:** (e.g. Arch Linux)
Win10

ps: my server has an Warning to: Your web server is not properly configured to resolve "/.well-known/webfinger"
i hardly believe it but maybe that has something to do with it... even if not would be great if you could help me with that as I spend about 3 days on it and I can't find a solution...

**Comment by ChristophWurst** [comment]
The Nextcloud mail app offers an extensive logging system to make it easier identifying and tracking down bugs. Please enable [debug mode](https://docs.nextcloud.com/server/stable/developer_manual/general/devenv.html#enabling-debug-mode) and set the log [level to debug](https://docs.nextcloud.com/server/stable/admin_manual/configuration_server/logging_configuration.html) in your admin settings. Then, try to reproduce your issue and take another look at `data/nextcloud.log`, `data/horde_imap.log` and `data/horde_smtp.log`.

**Comment by Shuvi-Hub** [comment]
Ohh... ok I was just too stupid. this has helped me xD (https://www.youtube.com/watch?v=Rj3p3b_Bz5I)
