### ISSUE TITLE
Settings navigation menu entry should be pushed to the far bottom of the navigation pane

### ISSUE THREAD

**Issue by StCyr** [nextcloud/mail#3535]
### Expected behavior
The navigation pane should leave as much space as possible for the mailbox entries

### Actual behavior
There's a lot of empty spaces below the Settings navigation menu entry while some mailbox entries are hidden:

![image](https://user-images.githubusercontent.com/8179031/92126078-08024a80-ee00-11ea-8359-0604707fef23.png)
![image](https://user-images.githubusercontent.com/8179031/92125942-e3a66e00-edff-11ea-8dae-ad3489252d7c.png)

### Mail app

**Mail app version:** master

### Server configuration

**Nextcloud Version:** NC20beta2

#### Client configuration
**Browser:** Firefox latest (80.0.1 64bits)

**Operating system:** MacOS

**Comment by ChristophWurst** [comment]
Fixed in  #3533
