### ISSUE TITLE
display error in folder structure

### ISSUE THREAD

**Issue by Tived** [nextcloud/mail#3545]
I have an display error with my folder structure from wevserver.

### Expected behavior
Screenshot from Webmail:
![image](https://user-images.githubusercontent.com/32328596/92303633-1f177880-ef77-11ea-8a6f-b88f90b9ae7f.png)

### Actual behavior
Screenshot from the Webmail App in Nextcloud:
![image](https://user-images.githubusercontent.com/32328596/92303784-7cf89000-ef78-11ea-90a3-c9cf698661c3.png)

### Mail app

**Mail app version:** 1.4.1
**Mailserver or service:** Roundcube 1.4.7

### Server configuration

**Operating system**: ‪Debian 9.13‬
**Web server:** (e.g. Apache, Nginx,...)
**Database:** MariaDB
**PHP version:** 7.3.21
**Nextcloud Version:** 19.0.0 and 19.0.2

#### Client configuration
**Browser:** Google Chrome 
**Operating system:** Windows 10 Home

**Comment by dehnhardt** [comment]
Fixed with https://github.com/nextcloud/mail/pull/3147.
