### ISSUE TITLE
Cannot activate app: "PHP with a version lower than 7.0 is required"

### ISSUE THREAD

**Issue by sscherfke** [nextcloud/mail#355]
### Steps to reproduce
1. Spawn a new Demo instance or run the current [Docker image](https://github.com/nextcloud/docker/tree/master/11.0/apache)
2. Go to *Apps / Communication*
3. Try to activate *Mail*

### Expected behaviour
*Activate* button is enabled and activates the app

### Actual behaviour
I get the error “PHP with a version lower than 7.0 is required”. The Docker image (and presumably the Demo instance, too) is using PHP 7.1.

### Mail app

**Mail app version:** 0.6.2

### Server configuration

See https://github.com/nextcloud/docker/blob/master/11.0/fpm/Dockerfile

**Comment by MariusBluem** [comment]
The next version of `nextcloud/mail` will support PHP 7.1 and 7.0 😉 Ref: https://github.com/nextcloud/mail/blob/master/appinfo/info.xml#L24

**Comment by sscherfke** [comment]
:)

It there an ETA?

**Comment by ChristophWurst** [comment]
> Is there an ETA?

Nope

**Comment by cmtonkinson** [comment]
Is there any workaround in the meantime? Just deployed NC 7.0.2 via Docker images and would love to get started with nextcloud/mail, since it appears to stand head and shoulders above the 3rd party mail apps.
