### ISSUE TITLE
mail 'search function doesn't search in senders' address and name

### ISSUE THREAD

**Issue by StCyr** [nextcloud/mail#3562]
### Expected behavior
Searching for the name of the sender of an email should match the corresponding email

### Actual behavior
Searching for the name of the sender of an email doesn't return any result

### Mail app

**Mail app version:** master

**Mailserver or service:** (e.g. Outlook, Yahoo, Gmail, Exchange,...)

### Server configuration

**Operating system**: (e.g. Debian 8)

**Web server:** (e.g. Apache, Nginx,...)

**Database:** (e.g. MariaDB, SQLite or PostgreSQL)

**PHP version:** (e.g. 7.0)

**Nextcloud Version:** NC20beta2

#### Client configuration
**Browser:** (e.g. Firefox 48)

**Operating system:** (e.g. Arch Linux)

**Comment by ChristophWurst** [comment]
right … only if you use `from:user@domain.com`

**Comment by StCyr** [comment]
would be cool if it'd it automagicaly: The `from:...` syntax only works with email adresses not names, and doesn't support partial match (ie: "cyrille" for matching "cyrille@bollu.be")

**Comment by StCyr** [comment]
Ohoh... The search function doesn't seem to search in mails' body neither...

I guess you don't want to accept the performance penalty of such extended search functions.

(FYI, I believe the search happens here: https://github.com/nextcloud/mail/blob/7edf71937ce86ab4642ef617649e45305ef7a1ba/lib/Db/MessageMapper.php#L564)

Possible solutions/workarounds that I imagine:

1. (easy) Document mail 'search function in the Settings pane (same as for the keyboard shortcuts documentation);
2. (hard) Add a FULLTEXT index for the messages' body and add support for fulltext search;
3. (bad idea) Add an administrator option to allow searching in mails' body and use `LIKE '%foobar%'` queries to actually search in messages' body. (I was thinking about this idea for small NC instances, but, eventually, I've noticed my small instance, with only me as mail user, as already about 11000 messages in its DB)

Same possible workaround/solutions probably apply for searching in sender addresses and names.

**Comment by ChristophWurst** [comment]
This is known and I put down some possible solutions at https://github.com/nextcloud/mail/issues/3481.

**Comment by StCyr** [comment]
> 
> 
> Ohoh... The search function doesn't seem to search in mails' body neither...
> 
> I guess you don't want to accept the performance penalty of such extended search functions.
> 
> (FYI, I believe the search happens here:
> 
> https://github.com/nextcloud/mail/blob/7edf71937ce86ab4642ef617649e45305ef7a1ba/lib/Db/MessageMapper.php#L564
> )
> 
> Possible solutions/workarounds that I imagine:
> 
>     1. (easy) Document mail 'search function in the Settings pane (same as for the keyboard shortcuts documentation);
> 
>     2. (hard) Add a FULLTEXT index for the messages' body and add support for fulltext search;
> 
>     3. (bad idea) Add an administrator option to allow searching in mails' body and use `LIKE '%foobar%'` queries to actually search in messages' body. (I was thinking about this idea for small NC instances, but, eventually, I've noticed my small instance, with only me as mail user, as already about 11000 messages in its DB)
> 
> 
> Same possible workaround/solutions probably apply for searching in sender addresses and names.

mail body is not even cached localy, so it's only possible to crawl the messages' body on the IMAP server (via IMAP)

**Comment by stoamandl** [comment]
> right … only if you use `from:user@domain.com`

Ok, this is a workaround.
It's a bit sad that you can't search for components of a sender mail address.
But I just noticed that the search does not work if you search with upper and lower case. This makes no sense with email addresses!
Example: 
Test@test.com -> no result
test@test.com -> search works
Testet with Mail 1.10.1 NC 21.0.3 php8

**Comment by StCyr** [comment]
> But I just noticed that the search does not work if you search with upper and lower case. This makes no sense with email addresses!

Well, it actually makes sense: The local part of an email address is case sensitive 

I know it's a pain in the a** though

**Comment by stoamandl** [comment]
> > But I just noticed that the search does not work if you search with upper and lower case. This makes no sense with email addresses!
> 
> Well, it actually makes sense: The local part of an email address is case sensitive
> 
> I know it's a pain in the a** though

And that's just what's confusing!
In the mail app, the address is listed in the history and overview in Case sensitive.
If the user now copy this address and wants to search all mails of this address, this does not work of course.
For example, if I have already mentioned this mail address in the chat (talk), I will find this conversation regardless of whether test@test.com or Test@test.com.
Explain this to a NC user :-)

**Comment by ChristophWurst** [comment]
PR at https://github.com/nextcloud/mail/pull/8645
