### ISSUE TITLE
train classifier disabled but called / logging regardless

### ISSUE THREAD

**Issue by relikd** [nextcloud/mail#3564]
Not sure if this is a bug or intended behaviour.

I do get the same warnings as in #3292 
'not enough messages to train a classifier'

This bug has been 'fixed' by changing log-level from warning to info.
However, my understanding is the following:

If I disable the checkbox in mail settings saying "Allow this app to collect data about interactions ...", I would assume the training should not take place at all. Thus `train(Account, ILogger)` should not even be called, right?

If my assumption is correct, then this is a bug. If my assumption is wrong I'd like to open a feature request to completely disable the training. Also, I wish there was an admin setting to disable the learning system wide.

### Mail app

**Mail app version:** 1.4.1

**Mailserver or service:** own

**Nextcloud Version:** 19.0.1

**Comment by ChristophWurst** [comment]
No, the checkbox is about recently contacted email addresses that are collected. For the priority inbox training we don't need any collected data, it simply uses the cached data from IMAP :)

So … not a bug
