### ISSUE TITLE
notmuch + muchsync support

### ISSUE THREAD

**Issue by matthiasbeyer** [nextcloud/mail#3565]
### Feature Request

It would be really nice if the nextcloud email app could use notmuch, and possibly even muchsync. Not sure whether this is even possible, but it would be really, really nice.
Maybe notmuch and muchsync can be compiled to WASM to make this possible, I don't know...

#### Summary

notmuch and muchsync support for nextcloud/mail.

**Comment by ChristophWurst** [comment]
what's the benefit for the wider user audience?

**Comment by matthiasbeyer** [comment]
notmuch: extremely fast mail search and categorize functionality based on tags. If automagic (sic!) tagging based on rules is added, auto-categorization and even simpler filtering.
muchsync: Integration with existing setups based on notmuch / The user does not have to rely on IMAP/etc for mail sync.

I admit that the latter is more of a power-user feature, as most people sync their mail over IMAP these days, not SSH, ... but it would be easy enough to add after notmuch is added (I assume, because all functionality that would be needed for muchsync is also needed for notmuch anyways), so why not?

**Comment by ChristophWurst** [comment]
> so why not?

Because it's effort.

**Comment by matthiasbeyer** [comment]
Fair point.

**Comment by matthiasbeyer** [comment]
Let me add: I'm also not sure whether it is actually possible to include muchsync support, as muchsync relies on ssh access to the email server.

The setup works as follows:

* On a server, emails get delivered to a Maildir via (for example) maildrop.
* On this server, maildrop forwards mails through notmuch, which puts the mail into its database, adds tags based on rules and so on.
* emails _can_ be synced to the desktop via muchsync, which is only a tool for syncing two notmuch databases. It does not rely on IMAP, but on SSH access to the server.

My setup right now is, that my server does some initial tagging based on rules and I sync mails to my desktop and my notebook via muchsync as described above. I can also sync mails from my notebook to my desktop this way.

Point is, that it might not be possible to have SSH access from nextcloud to the email server - I'm not sure about this as I don't know how nextcloud works, but it would be a requirement for muchsync.
Notmuch without muchsync only makes sense if there is only one instance that is used to view/handle email - as soon as a user uses multiple clients, syncing of tags is not only a nice-to-have, but a thing that a user actually _wants_.

---

Either way, having notmuch for fast search and email tagging is a really nice thing, as notmuch can _easily_ handle thousands of emails (I myself have about 50k mails in the notmuch database, a friend of mine is about to reach 350k mails - without scaling problems)!
