### ISSUE TITLE
Input submit button has different size

### ISSUE THREAD

**Issue by GretaD** [nextcloud/mail#3567]
### Expected behavior
The button has the same size as input field

### Actual behavior

![Screenshot from 2020-09-08 13-08-18](https://user-images.githubusercontent.com/12728974/92469007-6484b180-f1d4-11ea-9c6e-259608b6585c.png)

**Comment by ChristophWurst** [comment]
as per https://github.com/nextcloud/mail/pull/3607#issuecomment-700617433
