### ISSUE TITLE
Unhelpful repetetice messages fill up nextcloud log

### ISSUE THREAD

**Issue by timreeves** [nextcloud/mail#3572]
### Expected behavior
The mail app should not write to the nextcloud log unless something is really wrong (I have scripts checking its size every night so I keep getting a mail every morning)

### Actual behavior
{"reqId":"E1IptDh3KfS14H65es5B","level":2,"time":"2020-09-10T05:30:55+00:00","remoteAddr":"","user":"--","app":"mail","method":"","url":"--","message":"not enough messages to train a classifier","userAgent":"--","version":"19.0.2.2"}

### Mail app
**Mail app version:** 1.4.1
**Mailserver or service:** Dovecot (current version configured by current Plesk)

### Server configuration
**Operating system**: Debian 9
**Web server:** Nginx
**Database:** MariaDB
**PHP version:** 7.3
**Nextcloud Version:** 19.0.2

#### Client configuration
**Browser:** Firefox 80.0.1
**Operating system:** Ubuntu 18.4

**Comment by ChristophWurst** [comment]
Fixed by https://github.com/nextcloud/mail/pull/3292 and was actually backported. I just didn't have the time yet to prepare a patch release for the v1.4 branch.
