### ISSUE TITLE
CSP eval

### ISSUE THREAD

**Issue by acsfer** [nextcloud/mail#3573]
Here is the Sentry log:

```
{
  "csp-report": {
    "line_number": 931,
    "blocked_uri": "eval",
    "referrer": "",
    "violated_directive": "script-src",
    "document_uri": "https://hostname/apps/mail/",
    "original_policy": "default-src 'none'; base-uri 'none'; manifest-src 'self'; script-src 'nonce-eVl4dmJscUhBQkZHdWZGQUhHNmwvZDdHRHRldEowNmtwZkZ6ZWNNbldNYz06K2M5RUJTMzlSSGh4d2JjQ1h3Ylcwcm13WWJUVlV3RGkzNmNpUGFWZE5JMD0='; style-src 'self' 'unsafe-inline'; img-src 'self' data: blob:; font-src 'self' data:; connect-src 'self' https://stun.nextcloud.com:443; media-src 'self'; frame-src 'self'; frame-ancestors 'self'; worker-src 'self' blob:; form-action 'self'; report-uri https://ingest.sentry.io/api/5425369/security/",
    "source_file": "https://hostname/apps/mail/js/mail.js?v=8a7410d3-49",
    "column_number": 1189,
    "effective_directive": "script-src"
  }
}
```

**Comment by ChristophWurst** [comment]
Do you know where it was raised? I've seen similar "errors" but for me they were always caused by firefox extensions that can't deal with Nextcloud's CSP.

**Comment by ChristophWurst** [comment]
Try with private mode (without extension), another browser or a clean profile.

**Comment by acsfer** [comment]
I've tried with another browser without any extension installed and error is triggered when clicking on the mail icon on the top bar.
Also reproducible with Chrome on Android. Sentry warns about it immediately.

**Comment by ChristophWurst** [comment]
Does Chrome tell you which script it is?

**Comment by acsfer** [comment]
No, sorry. Same as Sentry (`line` 931, `col` 1189 of `mail.js`).

**Comment by barzog** [comment]
See the same behavior on NC v20.0.3 on URL https://<NS address>/apps/mail/box/priority
I'd expect that unsafe-eval should be added to CSP in the same way as unsafe-inline is added

**Comment by barzog** [comment]
/apps/mail/js/mail.js:1532	script-src	blocked

**Comment by ChristophWurst** [comment]
it this still happening?

**Comment by acsfer** [comment]
Not here.
