### ISSUE TITLE
App store version higher than git version

### ISSUE THREAD

**Issue by MorrisJobke** [nextcloud/mail#358]
* appinfo.xml says 0.6.2
* App Store and git tag says 0.6.3

cc @Gomez @ChristophWurst 😉

**Comment by ChristophWurst** [comment]
> appinfo.xml says 0.6.2

Well, depends on which one you're looking: https://github.com/nextcloud/mail/blob/v0.6.3/appinfo/info.xml 😉 

Today, I've published a tiny release, basically it's 0.6.2 with the php7.1 and nc12 compatibility. The git version should be 0.6.4 now, will create a PR soonish.

**Comment by ChristophWurst** [comment]
Fixed in #359
