### ISSUE TITLE
Undefined index: i at /var/www/html/apps/mail/lib/Service/Classification/ImportanceClassifier.php#366

### ISSUE THREAD

**Issue by nickvergessen** [nextcloud/mail#3592]
1. Install app
2. Run the cronjob

### Expected behavior
Everything works, all good

### Actual behavior
Error in the log file
https://github.com/nextcloud/mail/blob/c0bb9697c8de4f096fcce9efd04d05abbd57ab63/lib/Service/Classification/ImportanceClassifier.php#L364-L366
```
Undefined index: i at /var/www/html/apps/mail/lib/Service/Classification/ImportanceClassifier.php#366
```

### Mail app

**Mail app version:** 1.4.1

### Server configuration

Company instance

**Comment by ChristophWurst** [comment]
Fixed by https://github.com/nextcloud/mail/pull/3655
