### ISSUE TITLE
Refresh sent mailbox after sending an email

### ISSUE THREAD

**Issue by rcargnelutti** [nextcloud/mail#3598]
**Expected behavior**
After sending a message, it will appear “instantly” in the “Sent” box.

**Actual behavior**
When sending email, it becomes available “instantly” in the “Sent” box, while using RainLoop, Afterlogic, and the Mail Android App version 6.1.22.3 on a smartphone with Android 10, but that isn’t the case using the Mail app.
Using the Mail App you would have to wait for an automatic refresh (like 30 seconds or so) OR you can press the R key, and force the update. Even if I logout of Nextcloud and login again, the mail that I’ve sent still won’t show in the “Sent” box.
After sending an email, it is essential that it become available in the “Sent” Box within a reasonable period, similar to what happens in the “Inbox”.
Is it possible to implement an update time for the “Sent” box similar to what is used in the “Inbox”?
Or maybe you could use the same call that is used when you press the R in the keyboard, and make it run when you change boxes.
Looking forward to your guidance on that matter. Thanks!

**Mail app version**: 1.4.1
**Mail Server or service**: MXRoute (IMAP)
**Server configuration**
**Operating system**: CentOS 7.6
**Web server**: Apache Version 2.4.46
**Database**: MySQL 10.3.24
**PHP version**: 7.3.6
**Nextcloud Version**: 19.0.3
**Client configuration**
**Browser**: Google Chrome Version 84 / 85 (official) 64 bits and Firefox Version 80.0.1 (64-bits)
**Operating system**: Ubuntu 20.04, Mint 20, Debian 10 (buster) and Windows 10 Pro

**Comment by ChristophWurst** [comment]
Yeah, I think that is reasonable. But it's not a bug. It's a feature request :)
