### ISSUE TITLE
Does not activate formatting

### ISSUE THREAD

**Issue by rcargnelutti** [nextcloud/mail#3599]
**Expected behavior**
Activate the format options, while writing a new mail.

**Actual behavior**
When creating a new message, completing “to”, “subject”, and writing some content in the message, when trying to use the “Enable Formatting” option, nothing happens and the context menu gets stuck. If I click out of the context menu, and open it again, the “Enable Formatting” is still unchecked.
In other words I can’t enable formatting in my app.

**Mail app version**: 1.4.1
**Mail Server or service**: MXRoute (IMAP)
**Server configuration**
**Operating system**: CentOS 7.6
**Web server**: Apache Version 2.4.46
**Database**: MySQL 10.3.24
**PHP version**: 7.3.6
**Nextcloud Version**: 19.0.3
**Client configuration**
**Browser**: Google Chrome Version 84 / 85 (official) 64 bits and Firefox Version 80.0.1 (64-bits)
**Operating system**: Ubuntu 20.04, Mint 20, Debian 10 (buster) and Windows 10 Pro

**Comment by ChristophWurst** [comment]
any errors in your browser dev console?

**Comment by rasos** [comment]
Same here on NC 19.03 with Mail App 1.4.1: I can not activate Formatting, and there is no relevant message in the console.

Duplicate of https://github.com/nextcloud/mail/issues/3114#issuecomment-638013896

Isn't there also a general server-wide setting for formatting? Can't find that.

**Comment by ChristophWurst** [comment]
use Mail 1.5 or later

**Comment by rasos** [comment]
Using now Mail 1.7.2 on NC 20.0.2. 
I can now set "Activate formatting" at each new message, but there is no formatting bar or an explanation, if markdown could work (it does not, tested). Nothing gets formatted. And yes, sending messages in Rich-Text has been activated with that account.

**Comment by ChristophWurst** [comment]
Are you looking for an edting toolbar? We use a seamless rich editor with an editor balloon. If you select some text, the balloon should appear.

**Comment by rasos** [comment]
Indeed, it does. A colleague just discovered it by chance - I was not able to. Nice!      
Maybe adapt the text at the checkbox text in the option menu: 
`highlight to format`  or in german `markieren um zu formatieren `.

**Comment by ChristophWurst** [comment]
we were recently discussing switching to a real toolbar because of this bad discoverability

**Comment by TCB13** [comment]
Can formatting be enabled by default for all messages? Preferably with a fixed bar at the top that users can use not something that only appears on select?
