### ISSUE TITLE
MDN and DSN

### ISSUE THREAD

**Issue by MariusBluem** [nextcloud/mail#36]
Sometimes you want to recive an information that a mail was delivered successfully or that somebody has read a mail.  
- **MDN** (Message Disposition Notification) 
- **DSN** (Delivery Status Notification)

Should be easy to integrate according to the Horde Library 😉 (https://github.com/owncloud/mail/issues/1365) 

cc @ChristophWurst

**Comment by ChristophWurst** [comment]
MDN was done via https://github.com/nextcloud/mail/pull/4343
