### ISSUE TITLE
Automatic replication of messages Drafts

### ISSUE THREAD

**Issue by rcargnelutti** [nextcloud/mail#3600]
**Actual behavior**
When accessing a message in the “Drafts” box to edit, a new message is automatically added to each change in the text, causing the “Drafts” to have several messages from just one.
 
**Expected behavior**
Changes made to a message in the “Drafts” box must be applied to the message itself, that is, do not create new messages.
 
**Mail app version**: 1.4.1
**Mail Server or service**: MXRoute (IMAP)
**Server configuration**
**Operating system**: CentOS 7.6
**Web server**: Apache Version 2.4.46
**Database**: MySQL 10.3.24
**PHP version**: 7.3.6
**Nextcloud Version**: 19.0.3
**Client configuration**
**Browser**: Google Chrome Version 84 / 85 (official) 64 bits and Firefox Version 80.0.1 (64-bits)
**Operating system**: Ubuntu 20.04, Mint 20, Debian 10 (buster) and Windows 10 Pro

**Comment by ChristophWurst** [comment]
> Changes made to a message in the “Drafts” box must be applied to the message itself, that is, do not create new messages.

That is not possible. IMAP messages are immutable. We have to create a new version for every change.
