### ISSUE TITLE
创建账号时发生意外错误 Error occured when creating account

### ISSUE THREAD

**Issue by wxf26054** [nextcloud/mail#3603]
![image](https://user-images.githubusercontent.com/22016320/93582887-af24db80-f9d5-11ea-934e-b3962eee7273.png)

**Comment by ChristophWurst** [comment]
what is the response?

**Comment by ChristophWurst** [comment]
please use https://github.com/nextcloud/mail/issues/new?assignees=&labels=bug%2C+0.+to+triage&template=bug.md&title= to file a proper bug report
