### ISSUE TITLE
remove CSRF Token from API for 3rd Party Apps

### ISSUE THREAD

**Issue by ItzYanick** [nextcloud/mail#3609]
### Feature Request

Remove the CSRF Token from the API to develop 3rd Party Apps. Hopefully added in v1.4.2 so that you can use it on Nextcloud 19.x too. And maybe add a API Documentation too, to make it easier to use it.

**Comment by ChristophWurst** [comment]
what are you trying to achieve?

The APIs are not meant to be accessible outside the browser.

**Comment by ItzYanick** [comment]
I would like to develop a native app for iOS and Android that you can use to send emails. I hate using a normal email app where I have to sign into every account i have (i have like 5 mail accounts). Using a unified E-Mail App would help out a lot. There is already something like this called Spark, but 1. it doesn't have a windows client yet and 2. my login data for my mail accounts are uploaded into a AWS, which I do not really trust. A Nextcloud Mobile E-Mail App would make the same, but just self-hosted.

**Comment by ChristophWurst** [comment]
I see. We can discuss a public API. How far is your client? Is this just an idea or do you have a prototype?

**Comment by ItzYanick** [comment]
I did the login flow part with Nextcloud. Next step would be to implement the API. That's where I realized that the API is private. I could change it in my personal Nextcloud Instance for development purpose, but in the next update it would automatically change back and I do not want to change the code everytime I do an update.

**Comment by ChristophWurst** [comment]
For the experimental phase I would suggest the manual patching. Building a decent API won't happen in a day or two, this needs lots of discussion. You'll be better off working with an experimental API, then we can iterate on that. Hope this makes sense.

**Comment by ItzYanick** [comment]
Okay. Yea that makes sense. I will just fork this repo and do my work on there then for experimenting. Is the branch stable1.4 the newest release version?

**Comment by ChristophWurst** [comment]
Yes v1.4 is the latest released version.
