### ISSUE TITLE
[Feature Request] Add Filter System to Move and Mark new E-Mails.

### ISSUE THREAD

**Issue by Mannshoch** [nextcloud/mail#361]
Please add a Filter option to filter about specific rules like by content,mail address, address-book. etc.
with possible actions like Mark as spam, move to directory, etc.
I hate to create Filters for every Mail client on every PC.

**Comment by ChristophWurst** [comment]
> I hate to create Filters for every Mail client on every PC.

Pro tip: https://en.wikipedia.org/wiki/Sieve_(mail_filtering_language) 😉

**Comment by ChristophWurst** [comment]
Dup of https://github.com/nextcloud/mail/issues/44
