### ISSUE TITLE
Authentication errors - HMAC mismatch - hex2bin(), hash_equals()

### ISSUE THREAD

**Issue by cmtonkinson** [nextcloud/mail#362]
### Steps to reproduce
1. Install NextCloud 11.0.3 via Docker (https://github.com/nextcloud/docker)
2. Install / enable Mail app
3. Enter credentials for new IMAP-enabled account

### Expected behaviour
Show IMAP folder list

### Actual behaviour
Message `Error while loading the selected account.` and 3 `Error` level log entries (in order of appearance):

  * `Exception: HMAC does not match.`
  * `hash_equals(): Expected user_string to be a string, boolean given at /var/www/html/lib/private/Security/Crypto.php#128`
  * `hex2bin(): Hexadecimal input string must have an even length at /var/www/html/lib/private/Security/Crypto.php#124`

Same installation works when accessing a Gmail account. I know you've closed an HMAC-related issue (#172) before as a dupe of #53, but I don't believe this to be the case, since those other issues do not report implication of the same `hex2bin`/`hash_equals` errors.

### Mail app

**Mail app version:** `0.6.3`

**Mailserver or service:** `postfix / dovecot`

**Transport security - IMAP:** `STARTTLS`

**Transport security - SMTP:** `STARTTLS`

**Number of accounts:** `1`

**Mail app version build date:** `N/A`

### Server configuration
**Operating system**: Linux 4e1f69f91ae6 3.13.0-57-generic #95-Ubuntu SMP Fri Jun 19 09:28:15 UTC 2015 x86_64

**Web server:** Apache/2.4.10 (Debian) (apache2handler)

**Database:** mysql 5.5.54

**PHP version:** 7.1.4
Modules loaded: Core, date, libxml, openssl, pcre, sqlite3, zlib, ctype, curl, dom, fileinfo, filter, ftp, hash, iconv, json, mbstring, SPL, PDO, session, posix, Reflection, standard, SimpleXML, pdo_sqlite, Phar, tokenizer, xml, xmlreader, xmlwriter, mysqlnd, apache2handler, apcu, exif, gd, intl, ldap, mcrypt, memcached, mysqli, pdo_mysql, pdo_pgsql, pgsql, redis, zip, Zend OPcache

**Nextcloud version:** 11.0.3 (stable) - 11.0.3.2

**Updated from an older Nextcloud/ownCloud or fresh install:** Began with 11.0.2

**Where did you install Nextcloud from:** Docker (https://github.com/nextcloud/docker)

**Signing status:** What is this?

**List of activated apps:**
<details>
	<summary>App list</summary>
Enabled:

 - activity: 2.4.1
 - admin_audit: 1.1.0
 - apporder: 0.3.3
 - audioplayer: 1.5.1
 - calendar: 1.5.2
 - checksum: 0.3.4
 - comments: 1.1.0
 - contacts: 1.5.3
 - dav: 1.1.1
 - direct_menu: 0.10.1
 - encryption: 1.4.1
 - federatedfilesharing: 1.1.1
 - federation: 1.1.1
 - files: 1.6.1
 - files_pdfviewer: 1.0.1
 - files_reader: 1.0.4
 - files_retention: 1.0.1
 - files_sharing: 1.1.1
 - files_texteditor: 2.2
 - files_trashbin: 1.1.0
 - files_versions: 1.4.0
 - files_videoplayer: 1.0.0
 - firstrunwizard: 2.0
 - gallery: 16.0.0
 - issuetemplate: 0.2.1
 - logreader: 2.0.0
 - lookup_server_connector: 1.0.0
 - mail: 0.6.3
 - news: 10.2.0
 - notifications: 1.0.1
 - password_policy: 1.1.0
 - previewgenerator: 1.0.5
 - provisioning_api: 1.1.0
 - survey_client: 0.1.5
 - systemtags: 1.1.3
 - theming: 1.1.1
 - twofactor_backupcodes: 1.0.0
 - updatenotification: 1.1.1
 - workflowengine: 1.1.1

Disabled:
 - external
 - files_accesscontrol
 - files_automatedtagging
 - files_external
 - nextcloud_announcements
 - serverinfo
 - sharebymail
 - templateeditor
 - user_external
 - user_ldap
 - user_saml
</details>

**The content of config/config.php:**
<details>
	<summary>Config report</summary>

```
{
    "instanceid": "ocdpaok51koy",
    "passwordsalt": "***REMOVED SENSITIVE VALUE***",
    "secret": "***REMOVED SENSITIVE VALUE***",
    "trusted_domains": [
        "nextcloud.example.com"
    ],
    "datadirectory": "\/var\/www\/html\/data",
    "overwrite.cli.url": "https:\/\/nextcloud.example.com",
    "dbtype": "mysql",
    "version": "11.0.3.2",
    "dbname": "nextcloud",
    "dbhost": "localhost:\/run\/mysqld\/mysqld.sock",
    "dbtableprefix": "oc_",
    "dbuser": "***REMOVED SENSITIVE VALUE***",
    "dbpassword": "***REMOVED SENSITIVE VALUE***",
    "logtimezone": "UTC",
    "installed": true,
    "mail_smtpmode": "smtp",
    "mail_from_address": "nextcloud",
    "mail_domain": "example.com",
    "mail_smtpauthtype": "PLAIN",
    "mail_smtpauth": 1,
    "mail_smtphost": "mail.example.com",
    "mail_smtpsecure": "tls",
    "mail_smtpname": "***REMOVED SENSITIVE VALUE***",
    "mail_smtppassword": "***REMOVED SENSITIVE VALUE***",
    "mail_smtpport": "587",
    "memcache.local": "\\OC\\Memcache\\APCu",
    "memcache.distributed": "\\OC\\Memcache\\Redis",
    "memcache.locking": "\\OC\\Memcache\\Redis",
    "redis": {
        "host": "\/run\/redis\/redis.sock",
        "port": 0,
        "dbindex": 1
    },
    "maintenance": false,
    "loglevel": 0,
    "auth.bruteforce.protection.enabled": false,
    "theme": ""
}
```
</details>

**Are you using external storage, if yes which one:** files_external is disabled

**Are you using encryption:** yes

**Are you using an external user-backend, if yes which one:** N/A

### Client configuration
**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:53.0) Gecko/20100101 Firefox/53.0

**Operating system:** Windows 10 x64

#### Nextcloud log (data/nextcloud.log)
<details>
	<summary>Nextcloud log</summary>

```text
{"reqId":"VG6fy+3XozN+c32DpTfy","remoteAddr":"172.17.0.1","app":"PHP","message":"hex2bin(): Hexadecimal input string must have an even length at \/var\/www\/html\/lib\/private\/Security\/Crypto.php#124","level":3,"time":"2017-04-27T13:36:46+00:00","method":"GET","url":"\/index.php\/apps\/mail\/accounts\/4\/folders","user":"chris","version":"11.0.3.2"}
{"reqId":"VG6fy+3XozN+c32DpTfy","remoteAddr":"172.17.0.1","app":"PHP","message":"hash_equals(): Expected user_string to be a string, boolean given at \/var\/www\/html\/lib\/private\/Security\/Crypto.php#128","level":3,"time":"2017-04-27T13:36:46+00:00","method":"GET","url":"\/index.php\/apps\/mail\/accounts\/4\/folders","user":"chris","version":"11.0.3.2"}
{"reqId":"VG6fy+3XozN+c32DpTfy","remoteAddr":"172.17.0.1","app":"index","message":"Exception: {\"Exception\":\"Exception\",\"Message\":\"HMAC does not match.\",\"Code\":0,\"Trace\":\"#0 \\\/var\\\/www\\\/html\\\/apps\\\/mail\\\/lib\\\/Account.php(134): OC\\\\Security\\\\Crypto->decrypt(*** sensitive parameters replaced ***)\\n#1 \\\/var\\\/www\\\/html\\\/apps\\\/mail\\\/lib\\\/Account.php(292): OCA\\\\Mail\\\\Account->getImapConnection()\\n#2 \\\/var\\\/www\\\/html\\\/apps\\\/mail\\\/lib\\\/Account.php(338): OCA\\\\Mail\\\\Account->listMailboxes()\\n#3 \\\/var\\\/www\\\/html\\\/apps\\\/mail\\\/lib\\\/Account.php(351): OCA\\\\Mail\\\\Account->getMailboxes()\\n#4 \\\/var\\\/www\\\/html\\\/apps\\\/mail\\\/lib\\\/Controller\\\/FoldersController.php(62): OCA\\\\Mail\\\\Account->jsonSerialize()\\n#5 [internal function]: OCA\\\\Mail\\\\Controller\\\\FoldersController->index(4)\\n#6 \\\/var\\\/www\\\/html\\\/lib\\\/private\\\/AppFramework\\\/Http\\\/Dispatcher.php(160): call_user_func_array(Array, Array)\\n#7 \\\/var\\\/www\\\/html\\\/lib\\\/private\\\/AppFramework\\\/Http\\\/Dispatcher.php(90): OC\\\\AppFramework\\\\Http\\\\Dispatcher->executeController(Object(OCA\\\\Mail\\\\Controller\\\\FoldersController), 'index')\\n#8 \\\/var\\\/www\\\/html\\\/lib\\\/private\\\/AppFramework\\\/App.php(114): OC\\\\AppFramework\\\\Http\\\\Dispatcher->dispatch(Object(OCA\\\\Mail\\\\Controller\\\\FoldersController), 'index')\\n#9 \\\/var\\\/www\\\/html\\\/lib\\\/private\\\/AppFramework\\\/Routing\\\/RouteActionHandler.php(47): OC\\\\AppFramework\\\\App::main('OCA\\\\\\\\Mail\\\\\\\\Contro...', 'index', Object(OC\\\\AppFramework\\\\DependencyInjection\\\\DIContainer), Array)\\n#10 [internal function]: OC\\\\AppFramework\\\\Routing\\\\RouteActionHandler->__invoke(Array)\\n#11 \\\/var\\\/www\\\/html\\\/lib\\\/private\\\/Route\\\/Router.php(299): call_user_func(Object(OC\\\\AppFramework\\\\Routing\\\\RouteActionHandler), Array)\\n#12 \\\/var\\\/www\\\/html\\\/lib\\\/base.php(1010): OC\\\\Route\\\\Router->match('\\\/apps\\\/mail\\\/acco...')\\n#13 \\\/var\\\/www\\\/html\\\/index.php(40): OC::handleRequest()\\n#14 {main}\",\"File\":\"\\\/var\\\/www\\\/html\\\/lib\\\/private\\\/Security\\\/Crypto.php\",\"Line\":129}","level":3,"time":"2017-04-27T13:36:46+00:00","method":"GET","url":"\/index.php\/apps\/mail\/accounts\/4\/folders","user":"chris","version":"11.0.3.2"}
```
</details>

#### Browser log
<details>
	<summary>Browser log</summary>

```text
[keyboard] "keyup" Array [ Object, 13 ]  mail.min.js:148:14867
Content Security Policy: Directive ‘frame-src’ has been deprecated. Please use directive ‘child-src’ instead.  (unknown)
Content Security Policy: The page’s settings blocked the loading of a resource at self (“script-src 'nonce-dUJRQS82K08wV1V0NWowN0xHNGMyTWE5OThlR3Mya1k5Qkcydlh4ZEdEMD06N1ZCamgrNjZueEZwMVdrTUJ4OHV1NUxseHBMTHlSaGluanFDNURFdVhtUT0=' 'unsafe-eval'”). Source: onsubmit attribute on DIV element.  mail
Content Security Policy: The page’s settings blocked the loading of a resource at self (“script-src 'nonce-dUJRQS82K08wV1V0NWowN0xHNGMyTWE5OThlR3Mya1k5Qkcydlh4ZEdEMD06N1ZCamgrNjZueEZwMVdrTUJ4OHV1NUxseHBMTHlSaGluanFDNURFdVhtUT0=' 'unsafe-eval'”). Source: onchange attribute on DIV element.  mail
Content Security Policy: The page’s settings blocked the loading of a resource at self (“script-src 'nonce-dUJRQS82K08wV1V0NWowN0xHNGMyTWE5OThlR3Mya1k5Qkcydlh4ZEdEMD06N1ZCamgrNjZueEZwMVdrTUJ4OHV1NUxseHBMTHlSaGluanFDNURFdVhtUT0=' 'unsafe-eval'”). Source: onfocusin attribute on DIV element.  mail
JQMIGRATE: Migrate is installed, version 1.4.0  jquery-migrate.min.js:2:542
Starting Mail …  mail.min.js:157:26485
initializing cache…  mail.min.js:152:21641
[ui] "content:loading" Array [  ]  mail.min.js:148:14867
[ui] "notification:request" Array [  ]  mail.min.js:148:14867
[account] "entities" Array [  ]  mail.min.js:148:14867
[ui] "sidebar:loading" Array [  ]  mail.min.js:148:14867
[ui] "error:show" Array [ "Error while loading the selected ac…" ]  mail.min.js:148:14867
[ui] "navigation:newmessage:show" Array [  ]  mail.min.js:148:14867
[ui] "sidebar:accounts" Array [  ]  mail.min.js:148:14867
```
</details>

**Comment by cmtonkinson** [comment]
This is a blocker for me. What can I do to move this along?

**Comment by cmtonkinson** [comment]
Looks as if the `hex2bin()` call at `lib/private/Security/Crypto.php:124` is returning `bool` instead of `string`:

```php
    $hmac = hex2bin($parts[2]);
```

Running

```sql
  SELECT inbound_password FROM oc_mail_accounts WHERE id = X;
```

Returns a value where the lengths of the component ASCII ciphertext, IV, and HMAC are, respectively, 224, 16, and 13. Dunno if that's helpful.

**Comment by ChristophWurst** [comment]
https://github.com/nextcloud/mail/pull/375 should fix this problem!

**Comment by cmtonkinson** [comment]
... which makes this an exact duplicate of #340. Thanks @ChristophWurst!
