### ISSUE TITLE
Important *i* popover its not correctly format 

### ISSUE THREAD

**Issue by GretaD** [nextcloud/mail#3622]
![infoimportan](https://user-images.githubusercontent.com/12728974/93757925-d7941c00-fc07-11ea-83b5-77bc0a489261.png)

**Comment by GretaD** [comment]
@ma12-co we need your help here :)
The popover is broken and i have no idea why, I tried to _force_ style .popover, .popover__inner and wrapper, and nothing happens. The only thing that worked was if i add `max-width=xxx;` but then you need to fix a lot of other things and that defeats the purpose of using popover.

**Comment by ChristophWurst** [comment]
https://github.com/nextcloud/nextcloud-vue/commit/6721935f3dea33033dba185b2282fedc0bd08724#diff-14e3a3e00c1ab75657b21af1459b20d8 is the one commit that changed the component recently

**Comment by nickvergessen** [comment]
https://github.com/nextcloud/spreed/commit/5edeed2cf50b23be24574dcdb1371e2f7466d6a4

**Comment by GretaD** [comment]
fixed ##3682
