### ISSUE TITLE
mail often fails to load messages

### ISSUE THREAD

**Issue by StCyr** [nextcloud/mail#3624]
### Expected behavior
When clicking on an envelope in the envelope list, coresponding message details should display in the Message detail pane.

### Actual behavior
Often, mail fails to display the message details and instead the loading spinner keeps spinning forever.

Opening the priority inbox and then opening the offending folder again often resolves the issue.

In the network pane of FF's developper tool, everything seems loaded:

![Untitled](https://user-images.githubusercontent.com/8179031/93764531-9570d780-fc13-11ea-8a73-42a02cac652c.png)

### Mail app

**Mail app version:** master

**Mailserver or service:** OVH

### Server configuration

**Operating system**: Debian 10

**Web server:** Apache

**Database:** MariaDB

**PHP version:** 7.4

**Nextcloud Version:** NC202beta2

#### Client configuration
**Browser:** FF latest

**Operating system:** MacOS

**Comment by ChristophWurst** [comment]
@GretaD is that the issue you experienced?

**Comment by GretaD** [comment]
> @GretaD is that the issue you experienced?

yes. This is the second step i told you, the first one its that the _first_ message doesnt open automatically. After i click a message, this happens as shown in this ticket.
