### ISSUE TITLE
0.6.3 is out, but changelog not updated

### ISSUE THREAD

**Issue by Maulwurf16** [nextcloud/mail#363]
Every time a new version is pushed to the store, I go and look for changes - are there some which could create issues, etc...
Thus, the changelog
https://github.com/nextcloud/mail/blob/master/CHANGELOG.md
is my first go-to address as it says: "All notable changes to this project will be documented in this file."

But 0.6.3 is not listed. What exactly was changed?

**Comment by ChristophWurst** [comment]
Whoops, forgot to forward-port the changelog. Check out the comit referenced in the GitHub release. Basically I just made the app compatible with php7.1 and Nextcloud 12, nothing more :-)
