### ISSUE TITLE
Not compatible with Nextcloud 12

### ISSUE THREAD

**Issue by LukasReschke** [nextcloud/mail#364]
> {"reqId":"e8g8k4svx1JdoeoJDIKp","level":3,"time":"2017-05-01T21:21:14+00:00","remoteAddr":"XXXX","user":"lukas","app":"index","method":"GET","url":"\/apps\/mail\/","message":"Exception: {\"Exception\":\"OCP\\\\AppFramework\\\\QueryException\",\"Message\":\"Could not resolve appName! Class appName does not exist\",\"Code\":0,\"Trace\":\"#0 \\\/var\\\/www\\\/html\\\/lib\\\/private\\\/AppFramework\\\/Utility\\\/SimpleContainer.php(117): OC\\\\AppFramework\\\\Utility\\\\SimpleContainer->resolve('appName')\\n#1 \\\/var\\\/www\\\/html\\\/lib\\\/private\\\/ServerContainer.php(116): OC\\\\AppFramework\\\\Utility\\\\SimpleContainer->query('appName')\\n#2 \\\/var\\\/www\\\/html\\\/lib\\\/private\\\/AppFramework\\\/Utility\\\/SimpleContainer.php(66): OC\\\\ServerContainer->query('appName')\\n#3 \\\/var\\\/www\\\/html\\\/lib\\\/private\\\/AppFramework\\\/Utility\\\/SimpleContainer.php(96): OC\\\\AppFramework\\\\Utility\\\\SimpleContainer->buildClass(Object(ReflectionClass))\\n#4 \\\/var\\\/www\\\/html\\\/lib\\\/private\\\/AppFramework\\\/Utility\\\/SimpleContainer.php(117): OC\\\\AppFramework\\\\Utility\\\\SimpleContainer->resolve('OCA\\\\\\\\Mail\\\\\\\\Contro...')\\n#5 \\\/var\\\/www\\\/html\\\/lib\\\/private\\\/ServerContainer.php(116): OC\\\\AppFramework\\\\Utility\\\\SimpleContainer->query('OCA\\\\\\\\Mail\\\\\\\\Contro...')\\n#6 \\\/var\\\/www\\\/html\\\/lib\\\/private\\\/AppFramework\\\/DependencyInjection\\\/DIContainer.php(410): OC\\\\ServerContainer->query('OCA\\\\\\\\Mail\\\\\\\\Contro...')\\n#7 \\\/var\\\/www\\\/html\\\/lib\\\/private\\\/AppFramework\\\/App.php(101): OC\\\\AppFramework\\\\DependencyInjection\\\\DIContainer->query('OCA\\\\\\\\Mail\\\\\\\\Contro...')\\n#8 \\\/var\\\/www\\\/html\\\/lib\\\/private\\\/AppFramework\\\/Routing\\\/RouteActionHandler.php(47): OC\\\\AppFramework\\\\App::main('OCA\\\\\\\\Mail\\\\\\\\Contro...', 'index', Object(OC\\\\AppFramework\\\\DependencyInjection\\\\DIContainer), Array)\\n#9 [internal function]: OC\\\\AppFramework\\\\Routing\\\\RouteActionHandler->__invoke(Array)\\n#10 \\\/var\\\/www\\\/html\\\/lib\\\/private\\\/Route\\\/Router.php(299): call_user_func(Object(OC\\\\AppFramework\\\\Routing\\\\RouteActionHandler), Array)\\n#11 \\\/var\\\/www\\\/html\\\/lib\\\/base.php(976): OC\\\\Route\\\\Router->match('\\\/apps\\\/mail\\\/')\\n#12 \\\/var\\\/www\\\/html\\\/index.php(40): OC::handleRequest()\\n#13 {main}\",\"File\":\"\\\/var\\\/www\\\/html\\\/lib\\\/private\\\/AppFramework\\\/Utility\\\/SimpleContainer.php\",\"Line\":102}","userAgent":"Mozilla\/5.0 (Macintosh; Intel Mac OS X 10_12_4) AppleWebKit\/537.36 (KHTML, like Gecko) Chrome\/58.0.3029.81 Safari\/537.36","version":"12.0.0.15"}

**Comment by ChristophWurst** [comment]
To be precise: 0.6.3 doesn't work with NC12. https://github.com/nextcloud/mail/pull/242 seems to be the missing fix to be compatible with NC12. The stack trace is kinda misleading here 🙊

**Comment by ChristophWurst** [comment]
[mail.tar.gz](https://github.com/nextcloud/mail/files/969628/mail.tar.gz) <- 0.6.3 with the necessary backport.

**Comment by LukasReschke** [comment]
> mail.tar.gz <- 0.6.3 with the necessary backport.

Make a 0.6.4 then and push that to the appstore? 😜

**Comment by ChristophWurst** [comment]
Without testing? 😨

**Comment by ChristophWurst** [comment]
0.6.4 is compatible with nc12
