### ISSUE TITLE
Firefox with Nextcloud Mail as registered source fails when sending a page link.

### ISSUE THREAD

**Issue by ToeJet** [nextcloud/mail#3643]
### Expected behavior
Register the Nextcloud Mail client as a mail destination in Firefox.   Navigate to any page on internet.   Select Email link.  Should launch a new tab with nextcloud email client awaiting you to fill in recipient....

### Actual behavior
New tab opens with nextcloud showing internal server error.  

I was able to correct the operation by making the following change

```
diff /var/www/nextcloud/apps/mail/lib/Controller/PageController.php.orig /var/www/nextcloud/apps/mail/lib/Controller/PageController.php
169c169
< 		$params = ['to' => $parts['path']];
---
> 		$params = ['to' => $parts['path'] . ""];
```

### Mail app

Mail app version: 1.4.1

Mailserver or service: SMTP 

### Server configuration

Operating system: Fedora 32

Web server: Apache

Database: PostgreSQL

PHP version: 7.4.10

Nextcloud Version: 19.0.3

Client configuration
Browser: Firefox 80

Operating system: Fedora 32

**Comment by ChristophWurst** [comment]
Duplicate of https://github.com/nextcloud/mail/issues/3760 I think and fixed with https://github.com/nextcloud/mail/pull/4128
