### ISSUE TITLE
unified search repeats last entry in the list when loading more results

### ISSUE THREAD

**Issue by StCyr** [nextcloud/mail#3658]
### Expected behavior
Unified search should show correct results

### Actual behavior
When you load more results, unified search repeats the last entry in the list:

![image](https://user-images.githubusercontent.com/8179031/94288145-6205b400-ff57-11ea-8d5a-319d3e7432eb.png)

### Mail app

**Mail app version:** master

**Comment by ChristophWurst** [comment]
Oh, I think that might be because the app search logic that is also used to load the ordinary envelope list assumes that the cursor element is not visible, hence the overlap is OK there.

I will have a look.

**Comment by StCyr** [comment]
I can't reproduce this issue anymore
