### ISSUE TITLE
Threading message headers background colors and feedbacks

### ISSUE THREAD

**Issue by marcoambrosini** [nextcloud/mail#3665]
1) Could we make the expanded message's header in the thread light primary? Like the selected conversation in talk

2) I think that we could use the a more pronounced border radius for the hover feedback, either --border-radius-large or even --border-radius-pill

ref for current state https://github.com/nextcloud/mail/pull/3651

**Comment by ma12-co** [comment]
cc @jancborchardt @ChristophWurst @GretaD

**Comment by GretaD** [comment]
I agree to do this but it can be done only after we merge the threading envelopes. Right now the threading gets it active state from the envelope. So active is consider always the message that you have open first. Even though you can go through threading, the active one is the one you have clicked.
See pics: i clicked Julius from the envelope(second column). Even if i click Jos or Christoph now that the threading is open, the active one will be Julius.
1.
![active_threading](https://user-images.githubusercontent.com/12728974/94429015-f9eee200-0191-11eb-971e-2ab866baa174.png)



2.
![acive2](https://user-images.githubusercontent.com/12728974/94429016-fa877880-0191-11eb-867e-e786e9612a63.png)

**Comment by GretaD** [comment]
This a quick "update", this cannot be done till we merge all the threads in one envelope. As I am trying to explain in my first comment, the active state is "inherit" from the envelope and the message we open will always be active, even when i switch to the next/previews one.
