### ISSUE TITLE
Signature/mentions not collapsed correctly

### ISSUE THREAD

**Issue by StCyr** [nextcloud/mail#3667]
### Expected behavior
A newly introduced feature collapses signatures and mentions.

### Actual behavior
I've a case where the signature is not collapsed properly:

![image](https://user-images.githubusercontent.com/8179031/94415193-8e027e80-017d-11eb-9d01-0a16e41609f0.png)

### Mail app

**Mail app version:** master

**Comment by StCyr** [comment]
another one:

![image](https://user-images.githubusercontent.com/8179031/94446059-6c6abc80-01a8-11eb-9ab1-7a667e2d5122.png)

**Comment by ChristophWurst** [comment]
Could you export those emails? That would make reproduction a lot easier for me :)

**Comment by StCyr** [comment]
> Could you export those emails? That would make reproduction a lot easier for me :)

Sure:

Return-Path: <nextcloudfr-owner@framalistes.org>
Delivered-To: cyrille@bollu.be
Received: from localhost (HELO queue) (127.0.0.1)
	by localhost with SMTP; 28 Sep 2020 16:32:22 +0200
Received: from unknown (HELO output40.mail.ovh.net) (10.108.1.169)
  by mail259.mgra1.mail.ovh.net with AES256-GCM-SHA384 encrypted SMTP; 28 Sep 2020 16:32:22 +0200
Received: from vr11.mail.ovh.net (unknown [10.101.8.11])
	by out40.mail.ovh.net (Postfix) with ESMTP id 4C0Q2t1l5czBgGtYm
	for <cyrille@bollu.be>; Mon, 28 Sep 2020 14:32:22 +0000 (UTC)
Received: from in11.mail.ovh.net (unknown [10.101.4.11])
	by vr11.mail.ovh.net (Postfix) with ESMTP id 4C0Q2n0kTVz5KhTP
	for <cyrille@bollu.be>; Mon, 28 Sep 2020 14:32:17 +0000 (UTC)
Received-SPF: Pass (mailfrom) identity=mailfrom; client-ip=176.9.118.242; helo=rod3.framasoft.org; envelope-from=nextcloudfr-owner@framalistes.org; receiver=cyrille@bollu.be 
Authentication-Results: in11.mail.ovh.net;
	dkim=pass (2048-bit key; unprotected) header.d=framalistes.org header.i=@framalistes.org header.b="bOVA4gOI";
	dkim=pass (2048-bit key) header.d=framalistes.org header.i=nextcloudfr-request@framalistes.org header.b="dJKoC1Ja";
	dkim-atps=neutral
Received: from rod3.framasoft.org (rod3.framasoft.org [176.9.118.242])
	by in11.mail.ovh.net (Postfix) with ESMTPS id 4C0Q2n04rHzFpX3
	for <cyrille@bollu.be>; Mon, 28 Sep 2020 14:32:16 +0000 (UTC)
Received: by rod3.framasoft.org (Postfix, from userid 1009)
	id C5255A2C44; Mon, 28 Sep 2020 16:32:11 +0200 (CEST)
DKIM-Signature: v=1; a=rsa-sha256; c=relaxed/relaxed; d=framalistes.org;
	s=dkim2; t=1601303536;
	h=from:from:sender:sender:reply-to:reply-to:subject:subject:date:date:
	 message-id:message-id:to:to:cc:mime-version:mime-version:
	 content-type:content-type:in-reply-to:in-reply-to:
	 references:references:list-id:list-help:list-owner:list-unsubscribe:
	 list-subscribe:list-post:autocrypt:autocrypt;
	bh=/DdbobJXim/AxX3PZYdg2Gs3nWkoptaNJg9wAsH0Ppc=;
	b=bOVA4gOIGvSkoGPehHgTm03KhcNhkU03q4kXLWvLIbv2gN8aShF5clpnZy6J1NyNELF2sF
	kLglAxOIB/3bGg6VI8bXeP0Y3utdh/l1psXlZd0eYAptAR49ijTG+2Us/SKMdKkrk5aGoz
	m1sxa/kWH3/sP4LgDh14WgMl4bDYl9HA1OYLNnfAPCwaCUj+FMVCWfhyiTY9H5kBa8wMsN
	NH599QfD7KTrZinr9gf1FcUjl3YwoG5jGlCjixKRYHKzNPu6qKjZ/3hOEYRXIttLNKtaYB
	e6Bm0yWxLG5Sf/ZT0K+HU4/sRUM9D84HN2RyiIW8N8BL8jGGL9V53dza/cEnGw==
DKIM-Signature: v=1; a=rsa-sha256; c=relaxed; d=framalistes.org; h=to
	:references:from:message-id:date:mime-version:in-reply-to
	:content-type:subject:reply-to:sender:list-id:list-help
	:list-subscribe:list-unsubscribe:list-post:list-owner
	:list-archive; s=dkim2; i=nextcloudfr-request@framalistes.org;
	 bh=lN6KW1zQZa9+sR1hKQwTydseMjxFi5qpMGt00dLCImE=; b=dJKoC1JaKicn
	tM/0Y4Vk9Fe+2ZrPtu+ysLEVY6nzYzx0K4EK7goaTPRisst8TJD4zmIVB942stVz
	XGCzFZ9oHs40V8s/iBnFbdapxGvNn1xiuummSvXKteXq6kXyRM4X1hHqSXw7gilU
	31tQHnFjOjA3nkoYW8DQkIa82FN0eOyE8n4U1bom5PCGjwxKBIYqjzAWnz/gJp72
	Uq3SgvMgfQMvUMDSMUSqybMl7BlAlHK/niDn7MBiok8r6zK/9tFlUnVUhlyuKj0r
	iBDysBodHz8VQXNZtMc9j9YOS2NpGyap0GCJh6PBARb0EmotNqZb7p6GwLwbrNqK
	YkNp6azLeg==
X-Original-To: nextcloudfr@framalistes.org
Delivered-To: nextcloudfr@framalistes.org
Received: from deblan.fr (deblan.fr [82.237.165.150])
	(using TLSv1.3 with cipher TLS_AES_256_GCM_SHA384 (256/256 bits)
	 key-exchange X25519 server-signature RSA-PSS (4096 bits) server-digest SHA256)
	(No client certificate requested)
	by rod3.framasoft.org (Postfix) with ESMTPS id B843DA1642
	for <nextcloudfr@framalistes.org>; Mon, 28 Sep 2020 16:31:01 +0200 (CEST)
Received: from [192.168.1.34] (unknown [77.245.136.169])
	(using TLSv1.3 with cipher TLS_AES_128_GCM_SHA256 (128/128 bits))
	(No client certificate requested)
	by deblan.fr (Postfix) with ESMTPSA id D96802E11A4;
	Mon, 28 Sep 2020 16:31:01 +0200 (CEST)
To: chatons@ilinux.fr, nextcloudfr@framalistes.org
References: <d38b8541-41ee-b13f-40c7-f6bb155f8860@ilinux.fr>
 <4a0d259c-1247-b28d-4a16-b1ddbdbc5e55@gendem5.me>
 <79c70f65-29d7-c8eb-31ef-1afc1d05f4e4@ilinux.fr>
From: "Simon Vieille" (via nextcloudfr Mailing List) <nextcloudfr@framalistes.org>
Autocrypt: addr=simon@deblan.fr; prefer-encrypt=mutual; keydata=
 mQENBFOyY+kBCACxiYvSZpfwjt+Rf3qkbsbJLMOoHzebcs+g6Ru4PiRvW7r85dK7Uv9kAa/C
 T29c2WRe+VA/HypBLiYXp01jwtKXVmMFyUTpmmMjWRhGVg+Y4oKvLHRm72/oKvkOskR0dcCX
 5YFlKDQ2NuPnJyzhvMoo26BOUYoPrwIOljRAxP5NdYiwrorNdMQ83JL5fA8rHByR3tcBnlTB
 P+fCdGm8lGVAa2CBh8+vxXTmWlwD+klw323CY1SRzcmusxdae9JRkngvqBijQHyyNfOkyQ00
 iDswZrYwl7T+TkLMyP0ryGpWbmAD1hVkzTTmyup2/DSEPhDuw9whabowtglc6WrWVCe9ABEB
 AAG0H1NpbW9uIFZpZWlsbGUgPHNpbW9uQGRlYmxhbi5mcj6JAVUEEwECAD8CGyMGCwkIBwMC
 BhUIAgkKCwQWAgMBAh4BAheAFiEE024VoWDKnrR4WzyNAzg9FaHTF0UFAlwswnAFCQ4d+QcA
 CgkQAzg9FaHTF0XlBQf/QLUCgDXCT2re6ts8Z9V5BrdERm5Eh4N5V70VSBmYH3RwgskcLBCD
 /bH8FCfTkQu+qyf7/U7YL1c+Ykshba837odhU9MPxy3PO4txtLVqw+m1MSOTz9XLFq8kYWSP
 BcKSqZeXa6e7R1np0zDpkzb+aobc7WtF4HmUe/SDPsuETMm8Jr3ToUtZpbaefKlPTXyka7t3
 5U70ZwHHbFhGJpgdk0gYadeRXS3kvTgQS461xISBPAyQtWmoSgCTl7qdoUlRJbJQrPc/I1na
 zGmQT7IQwT84s2wLl7P2Krl3DQ9w5/KRwyehyq/1J2Z4/7s9+JsBNLIXtLzGxt88K3Yx7Tcy
 NrkBDQRTsmPpAQgAzsWJbiOeL8QVz1OmeZ/UvcyAhQuWaFx7W0dRAXHfQRTTEcRme9hEZD4z
 +xev98IBjvZgTRWDHEc2dXOMZH0/dOSgoboJjK7qtaRZCX2vj5ozJ+ejwagJdR+oD4bzEVQ0
 pXnIVJOss7xSPTMQsb59STDzIOXWGSLtHO0zkFbPMvEetvCdawbAbYQ3bWmffrsQJZMaKumg
 DnyZtnP3kVoJZjD6nWq+pWPYGmxQ/MDYcCQQb1ov+RkG5ZUPf/ZuKEx7rHGU+ghdx0yDAC9c
 NcjE9B12VS6VUoBT2vEGp0wsBK7rbs1AmlvFCzsxiGnMX3qoTHzUcA+sZ/OB3lI4hrFzAwAR
 AQABiQE8BBgBAgAmAhsMFiEE024VoWDKnrR4WzyNAzg9FaHTF0UFAlwswnAFCQ4d+QcACgkQ
 Azg9FaHTF0Xp2Af9FSsgb0yJGXJc/puF8vjYP5VK4VqdzXgnDxx/OSwKEhkLm/Pj/x3fSkxU
 rEgEWwpxdTl+xiauEZsFC0P5MLkAlmnosIXeOb1T9k3bDnTEdj8M33zIQZtZX4HV3olj1JS0
 a/e2VUq4uk/2BHghMsRsxB3FKRuTkHmMTeGQwluqYsA8Nxp2/fNd/fCb0H45IRDKwyekmgLJ
 y4EiaJKN1tk6ctxGA6WuEIX2uqr93otg7TOKoip1GhTBtIW2BB9LjidZ9Yu67YKdM48Umi4n
 raGjT7BRpuTwg493Hu4OG6z442Xx75aVwPdkya0b3AxrKg/f1ArwEwlYNxnZsO/M8KY4rQ==
Message-ID: <83844b81-549c-5c25-c609-f29b09e4c5c4@deblan.fr>
Date: Mon, 28 Sep 2020 16:31:00 +0200
User-Agent: Mozilla/5.0 (X11; Linux x86_64; rv:68.0) Gecko/20100101
 Thunderbird/68.12.0
MIME-Version: 1.0
In-Reply-To: <79c70f65-29d7-c8eb-31ef-1afc1d05f4e4@ilinux.fr>
Content-Type: multipart/signed; micalg=pgp-sha512;
 protocol="application/pgp-signature";
 boundary="B4QuPG7tABWQTI9jXUJHicA6m1TXWSMFx"
X-Rspamd-Queue-Id: B843DA1642
X-Spamd-Result: default: False [-2.10 / 30.00];
	 RCVD_VIA_SMTP_AUTH(0.00)[];
	 ARC_NA(0.00)[];
	 R_DKIM_ALLOW(-0.20)[deblan.fr:s=mail];
	 MID_RHS_MATCH_FROM(0.00)[];
	 FROM_HAS_DN(0.00)[];
	 R_SPF_ALLOW(-0.20)[+mx];
	 MIME_GOOD(-0.20)[multipart/signed,multipart/mixed,text/plain];
	 HAS_ATTACHMENT(0.00)[];
	 TO_DN_NONE(0.00)[];
	 TO_MATCH_ENVRCPT_SOME(0.00)[];
	 DKIM_TRACE(0.00)[deblan.fr:+];
	 RCPT_COUNT_TWO(0.00)[2];
	 DMARC_POLICY_ALLOW(-0.50)[deblan.fr,none];
	 SIGNED_PGP(-2.00)[];
	 FROM_EQ_ENVFROM(0.00)[];
	 MIME_TRACE(0.00)[0:+,1:+,2:+,3:~];
	 SUBJECT_ENDS_QUESTION(1.00)[];
	 ASN(0.00)[asn:12322, ipnet:82.224.0.0/12, country:FR];
	 RCVD_COUNT_TWO(0.00)[2];
	 RCVD_TLS_ALL(0.00)[]
X-Rspamd-Server: rod3
Subject: Re: [nextcloudfr] Nextcloud devient lourd et de plus en
 =?UTF-8?Q?buggu=C3=A9?= , est-moi ?
Reply-To: Simon Vieille <simon@deblan.fr>
X-Loop: nextcloudfr@framalistes.org
X-Sequence: 312
Errors-To: nextcloudfr-owner@framalistes.org
Precedence: list
Precedence: bulk
Sender: nextcloudfr-request@framalistes.org
X-no-archive: yes
List-Id: <nextcloudfr.framalistes.org>
List-Help: <mailto:sympa@framalistes.org?subject=help>
List-Subscribe: <mailto:sympa@framalistes.org?subject=subscribe%20nextcloudfr>
List-Unsubscribe: <mailto:sympa@framalistes.org?subject=unsubscribe%20nextcloudfr>
List-Post: <mailto:nextcloudfr@framalistes.org>
List-Owner: <mailto:nextcloudfr-request@framalistes.org>
List-Archive: <https://framalistes.org/sympa/arc/nextcloudfr>
Archived-At: <https://framalistes.org/sympa/arcsearch_id/nextcloudfr/2020-09/83844b81-549c-5c25-c609-f29b09e4c5c4%40deblan.fr>
X-Original-DKIM-Signature: v=1; a=rsa-sha256; c=relaxed/simple; d=deblan.fr; s=mail;
	t=1601303461; bh=lN6KW1zQZa9+sR1hKQwTydseMjxFi5qpMGt00dLCImE=;
	h=Subject:To:References:From:Date:In-Reply-To:From;
	b=dOnl8tN4cNes6GQCvJMNqGrb3OozquMLutiYsnKyp5D3v0/jXeTfmszcKT+kKsGLM
	 5FtSh+n9Ffq6/6azRCel808FuQmncG7AcgxFOU/fO2/lJoPhzptOfjgbahOWun2Khu
	 HkBVO+WVcI6Y+myFXudOi5dY5N09Tog15w/inG0w=
X-Original-From: Simon Vieille <simon@deblan.fr>
X-Ovh-Remote: 176.9.118.242 (rod3.framasoft.org)
X-Ovh-Tracer-Id: 17577830824566724519
X-VR-SPAMSTATE: OK
X-VR-SPAMSCORE: 0
X-VR-SPAMCAUSE: gggruggvucftvghtrhhoucdtuddrgedujedrvdeigdehkecutefuodetggdotefrodftvfcurfhrohhfihhlvgemucfqggfjpdevjffgvefmvefgnecuuegrihhlohhuthemucehtddtnecunecujfgurhepvfhfhffkffgfgggjtgfurhgvphhpshejfedtjfduvdegsehgtderofdtfeejnecuhfhrohhmpedfufhimhhonhcugghivghilhhlvgdfucdlvhhirgcunhgvgihttghlohhuughfrhcuofgrihhlihhnghcunfhishhtmdcuoehnvgigthgtlhhouhgufhhrsehfrhgrmhgrlhhishhtvghsrdhorhhgqeenucggtffrrghtthgvrhhnpeetgfejveeihfegtdehueettdevveeukeelvddutefgvdejleeitdetkedujeetueenucffohhmrghinhepihhlihhnuhigrdhfrhdpjhgrsggsvghrfhhrrdhorhhgpdguvggslhgrnhdrfhhrnecukfhppedujeeirdelrdduudekrddvgedvpdejjedrvdeghedrudefiedrudeileenucevlhhushhtvghrufhiiigvpedtnecurfgrrhgrmhepmhhouggvpehsmhhtphdphhgvlhhopehinhduuddrmhgrihhlrdhovhhhrdhnvghtpdhinhgvthepudejiedrledruddukedrvdegvddpmhgrihhlfhhrohhmpehnvgigthgtlhhouhgufhhrqdhofihnvghrsehfrhgrmhgrlhhishhtvghsrdhorhhgpdhrtghpthhtoheptgihrhhilhhlvgessgholhhluhdrsggv
X-Ovh-Spam-Status: OK
X-Ovh-Spam-Reason: vr: OK; dkim: disabled; spf: disabled
X-Ovh-Message-Type: OK

This is an OpenPGP/MIME signed message (RFC 4880 and 3156)
--B4QuPG7tABWQTI9jXUJHicA6m1TXWSMFx
Content-Type: multipart/mixed; boundary="wldd9WwL7qsUT0QCdwLSLyHw11yivNGce"

--wldd9WwL7qsUT0QCdwLSLyHw11yivNGce
Content-Type: text/plain; charset=utf-8
Content-Language: fr
Content-Transfer-Encoding: quoted-printable

Le 28/09/2020 =C3=A0 15:59, Chatons iLinux (via nextcloudfr Mailing List)=
 a
=C3=A9crit=C2=A0:
>=20
> Merci pour vos avis.
>=20
>=20
> moi je passais par l'update web.
>=20
> mais j'ai des timeout a tout va ...
>=20
> ..., via le cli , c'est pass=C3=A9 comme une cr=C3=A8me ...
>=20
>=20
> Cette instance de NC date de 6 ans mini ...
>=20
>=20
> - no title specified
>=20
> Librement,
>=20
> Contact administratif(iLinux)
>=20
> =C2=A0
>=20
> =E2=80=8BAssociation Issoire Linux: AMAP du num=C3=A9rique
> H=C3=A9bergeur alternatif militant pour le partage du savoir et la prom=
otion
> des logiciels libres
>=20
> Site: https://www.ilinux.fr/
> Courriel=C2=A0:contact@ilinux.fr <mailto:contact@ilinux.fr>
> Chat: ilinux@chat.ilinux.fr
> <https://chat.jabberfr.org/converse.js/ilinux@chat.ilinux.fr>
>=20
> =C2=A0
>=20
> Le 28/09/2020 =C3=A0 15:01, Gilles Mioni a =C3=A9crit=C2=A0:
>>
>> J'ai un nuage en auto-h=C3=A9bergement mais je dispense des services
>> de type professionnel en b=C3=A9n=C3=A9vole pour une association 1901.=

>>
>> En Nextcloud V-19. Je n'ai pas remarqu=C3=A9 de d=C3=A9gradation, au c=
ontraire.
>>
>> L'upgrade de la 18 vers la 19, a =C3=A9t=C3=A9 r=C3=A9alis=C3=A9 avec =
le paquet compress=C3=A9.
>> Le changement de version de php ne me permettait pas la mise =C3=A0
>> jour depuis l'interface d'administration web.
>>
>>
>>
>> Le 26/09/2020 =C3=A0 23:10, Chatons iLinux (via nextcloudfr Mailing Li=
st) a
>> =C3=A9crit=C2=A0:
>>>
>>> Depuis la 18 .. ou les version s=E2=80=99encha=C3=AEnent , c'est des =
bug en rafale
>>> (erreur 403, move, sabre etc etc)=C2=A0 et surtout une lourdeur.
>>>
>>> M=C3=AAme sur des petites=C2=A0 instances.
>>>
>>>
>>> Avez-vous ce ressenti ?
>>>
>>>
>>>
>>> --=20
>>> - no title specified
>>>
>>> Librement,
>>>
>>> Contact administratif(iLinux)
>>>
>>> =C2=A0
>>>
>>> =E2=80=8BAssociation Issoire Linux: AMAP du num=C3=A9rique
>>> H=C3=A9bergeur alternatif militant pour le partage du savoir et la
>>> promotion des logiciels libres
>>>
>>> Site: https://www.ilinux.fr/
>>> Courriel=C2=A0:contact@ilinux.fr <mailto:contact@ilinux.fr>
>>> Chat: ilinux@chat.ilinux.fr
>>> <https://chat.jabberfr.org/converse.js/ilinux@chat.ilinux.fr>
>>>
>>> =C2=A0
>>>
>>>
>>
>=20
>=20

Il faut abandonner l'outil de mise =C3=A0 jour graphique car il ajoute un=
e
couche risqu=C3=A9e lors de la mise =C3=A0 jour (d=C3=A9pendance au serve=
ur web).

Hormis des probl=C3=A8mes li=C3=A9es =C3=A0 des certaines applications ti=
ers, je trouve
que Nextcloud tient bien debout.
Cependant, suite =C3=A0 un d=C3=A9convenue (car une application a plant=C3=
=A9 une
prod), je test syst=C3=A9matiquement les mises =C3=A0 jour sur des pr=C3=A9=
-productions
(pour du perso et du pro).

--=20
	=09
*Simon Vieille*
DevOp libriste, DSI =C3=A0 Zenitude Groupe
https://www.deblan.fr



--wldd9WwL7qsUT0QCdwLSLyHw11yivNGce--

--B4QuPG7tABWQTI9jXUJHicA6m1TXWSMFx
Content-Type: application/pgp-signature; name="signature.asc"
Content-Description: OpenPGP digital signature
Content-Disposition: attachment; filename="signature.asc"

-----BEGIN PGP SIGNATURE-----

iQEzBAEBCgAdFiEE024VoWDKnrR4WzyNAzg9FaHTF0UFAl9x86QACgkQAzg9FaHT
F0WqJAgAjqjP5aHZOhVMvc3vAuoEB/knmJA5rFqn+B3Z82WnAI3sj/rOpy5De1Lw
cDHGCNSkoa4fmb4Kl+hSGQoy0yumjI3jhX/h6E7xoCzDKaMD4P8Fn31ZwwFivvsN
AF5gRAHcd7+/+Kwx+M1qbWD7fxlqQ9p1Js2MDuRA6pTN1ws5xBTPEFAdqjVj3fvF
wurfmVj9/ZEpBLpXQa70v8gsPWY56RPSUNPN31ajudyHaMbiVOuHYXzNeth1qG8Q
25i0xvMgw6jEuCLx4EJUHgUo1RGisaw9RRDJOGLQB4gNCNe0iNNpd37ms7/8AdZu
t5pvhmGYCJMhCftVHAbIReP/E0NsqA==
=I11I
-----END PGP SIGNATURE-----

--B4QuPG7tABWQTI9jXUJHicA6m1TXWSMFx--

**Comment by ChristophWurst** [comment]
See https://github.com/nextcloud/mail/pull/3670 for the message you posted the sources.

I think the github one is different. There it's about printing escaped text vs printing HTML into the details summary. Export that messages as well and I'll try to fix :)

**Comment by StCyr** [comment]
Here you go (and thanks)!:

Return-Path: <noreply@github.com>
Delivered-To: cyrille@bollu.be
Received: from localhost (HELO queue) (127.0.0.1)
	by localhost with SMTP; 28 Sep 2020 11:15:32 +0200
Received: from unknown (HELO output52.mail.ovh.net) (10.108.20.51)
  by mail268.mgra1.mail.ovh.net with AES256-GCM-SHA384 encrypted SMTP; 28 Sep 2020 11:15:32 +0200
Received: from vr18.mail.ovh.net (unknown [10.101.8.18])
	by out52.mail.ovh.net (Postfix) with ESMTP id 4C0H1J4BB0zBgFrB2
	for <cyrille@bollu.be>; Mon, 28 Sep 2020 09:15:32 +0000 (UTC)
Received: from in69.mail.ovh.net (unknown [10.101.4.69])
	by vr18.mail.ovh.net (Postfix) with ESMTP id 4C0H1J2HxJz1H9jKR
	for <cyrille@bollu.be>; Mon, 28 Sep 2020 09:15:32 +0000 (UTC)
Received-SPF: Softfail (mailfrom) identity=mailfrom; client-ip=178.32.228.77; helo=mo77.mail-out.ovh.net; envelope-from=noreply@github.com; receiver=cyrille@bollu.be 
Authentication-Results: in69.mail.ovh.net;
	dkim=pass (1024-bit key; unprotected) header.d=github.com header.i=@github.com header.b="riIlBAnX";
	dkim-atps=neutral
Received: from mo77.mail-out.ovh.net (mo77.mail-out.ovh.net [178.32.228.77])
	by in69.mail.ovh.net (Postfix) with ESMTPS id 4C0H1J1xLNzq2NhG
	for <cyrille@bollu.be>; Mon, 28 Sep 2020 09:15:32 +0000 (UTC)
Received: from mx1.ovh.net (unknown [10.110.208.181])
	by mo77.mail-out.ovh.net (Postfix) with SMTP id EEB931230D1
	for <cyrille@bollu.be>; Mon, 28 Sep 2020 11:15:31 +0200 (CEST)
Received: from localhost (HELO queueout) (127.0.0.1)
	by localhost with SMTP; 28 Sep 2020 11:15:31 +0200
Delivered-To: bollu.be-cyrpub@bollu.be
Received: from localhost (HELO queue) (127.0.0.1)
	by localhost with SMTP; 28 Sep 2020 11:15:31 +0200
Received: from unknown (HELO output6.mail.ovh.net) (10.108.42.175)
  by mail258.mgra1.mail.ovh.net with AES256-GCM-SHA384 encrypted SMTP; 28 Sep 2020 11:15:31 +0200
Received: from vr43.mail.ovh.net (unknown [10.101.8.43])
	by out6.mail.ovh.net (Postfix) with ESMTP id 4C0H1G68cMz1K9DX
	for <cyrpub@bollu.be>; Mon, 28 Sep 2020 09:15:30 +0000 (UTC)
Received: from in64.mail.ovh.net (unknown [10.101.4.64])
	by vr43.mail.ovh.net (Postfix) with ESMTP id 4C0H1G44Kgz1Gn824
	for <cyrpub@bollu.be>; Mon, 28 Sep 2020 09:15:30 +0000 (UTC)
Received-SPF: Pass (mailfrom) identity=mailfrom; client-ip=192.30.252.210; helo=out-27.smtp.github.com; envelope-from=noreply@github.com; receiver=cyrpub@bollu.be 
Authentication-Results: in64.mail.ovh.net;
	dkim=pass (1024-bit key; unprotected) header.d=github.com header.i=@github.com header.b="riIlBAnX";
	dkim-atps=neutral
Received: from out-27.smtp.github.com (out-27.smtp.github.com [192.30.252.210])
	by in64.mail.ovh.net (Postfix) with ESMTPS id 4C0H1G2DjYztmQCx
	for <cyrpub@bollu.be>; Mon, 28 Sep 2020 09:15:30 +0000 (UTC)
Received: from github-lowworker-5fb2734.va3-iad.github.net (github-lowworker-5fb2734.va3-iad.github.net [10.48.19.27])
	by smtp.github.com (Postfix) with ESMTP id E030290002F
	for <cyrpub@bollu.be>; Mon, 28 Sep 2020 02:15:22 -0700 (PDT)
DKIM-Signature: v=1; a=rsa-sha256; c=relaxed/relaxed; d=github.com;
	s=pf2014; t=1601284522;
	bh=3cVLFdX3RKFKemy9OS07azFNZbGHOIfm73gbOlWM1Sg=;
	h=Date:From:Reply-To:To:Cc:Subject:List-ID:List-Archive:List-Post:
	 List-Unsubscribe:From;
	b=riIlBAnXojgQVDhqfX218JTln73wkEaDk4LYInUC3EYFi6QSZGOM7XO2VeD5sQ8Dw
	 coMH9YtDsL6t6Js1XYwbsUMru7cffUWHBZ/sSuYf/V1Pep/GDHpKEabeccovOL7BXL
	 8oLpUdpllqvX4a4Il4aUOBhPW9MWN1FeP83VLWVc=
Date: Mon, 28 Sep 2020 02:15:22 -0700

**Comment by ChristophWurst** [comment]
Thx! This is now fixed in my PR as well
