### ISSUE TITLE
Horizontal Reading pane option

### ISSUE THREAD

**Issue by dugite-code** [nextcloud/mail#367]
Enhancement request:
It would be great if we could optionally set the reading pane to horizontal underneath the message list like you can do in Thunderbird/Outlook.

I'm currently fudging this by modifying my mail.css as below (note: lots of problems with this fudge-up)
```
#mail-messages {
	width: 100%;
	height: 50%;
	border-bottom: 1px solid #ebebeb;
}

#mail-message-header {
	position: relative;
        height: 100px;
        width: 80% !important;
        background: rgba(255,255,255,100);

}

#mail-message {
	position: Relative;
	width: 100%;
}

.container {
	overflow: hidden;
}
```

**Comment by ChristophWurst** [comment]
cc @jancborchardt

**Comment by jancborchardt** [comment]
This is not something we are likely to implement. There are several other way more important things to fix and also this would mean that we need to test _everything_ in two different layouts. This will take so many resources away from us it's not feasible. :)

@dugite-code feel free to write a blog post with the code on how to achieve that different layout with the Mail app though! :)

**Comment by dugite-code** [comment]
For followup: [I did a gist](https://gist.github.com/dugite-code/ce068c75110e08cd669f016be65bf55e) of my css I am using in the [custom css app](https://github.com/juliushaertl/theming_customcss). So far it looks like I haven't broken anything but early days.
