### ISSUE TITLE
Opening an envelope action menu navigates to that envelope

### ISSUE THREAD

**Issue by ChristophWurst** [nextcloud/mail#3676]
### Expected behavior
It should be possible to open the actions menu of an envelope without opening the thread.

### Actual behavior
The click event triggers a navigation.

### Mail app

**Mail app version:** (see apps admin page, e.g. 0.5.3)

Latest master

**Comment by GretaD** [comment]
@juliushaertl yesterday during the mail call, we tried to fix this but we couldnt find a way how to. Can you please have a look, this is why we wanted you to join the call :)
