### ISSUE TITLE
Select corresponding account while reply

### ISSUE THREAD

**Issue by avanc** [nextcloud/mail#368]
### Steps to reproduce
1. Configure two mail accounts
2. Receive a mail sent to the second account
3. Reply to that message

### Expected behaviour
In the Reply area, the From-Address should be set automatically to the address which initially received the mail. 

### Actual behaviour
By default, the first account is always selected and you have to change it manually.

### Mail app

**Mail app version:** (see apps admin page)
0.6.3

**Mailserver or service:** (e.g. Outlook, Yahoo, Gmail, Exchange,...)

**Transport security - IMAP:** (None, SSL, TLS, STARTTLS) 
SSL

**Transport security - SMTP:** (None, SSL, TLS, STARTTLS)
SSL

**Number of accounts:**
2

**Comment by ChristophWurst** [comment]
Dup of https://github.com/nextcloud/mail/issues/175 :-)
