### ISSUE TITLE
"Add Attachment" closing "X" and Filedate overlaps

### ISSUE THREAD

**Issue by samweisgamdschie** [nextcloud/mail#369]
### Steps to reproduce
1. new mail or answer.
2. Click "Add attachment from files."
3. I cannot close this dialog without picking a file.

### Expected behaviour
File Dates are shown properly as column and the closing "X" is usable.

### Actual behaviour
File Date entries are shown in the top right corner of the file picker dialog, overlapping the closing "X".

### Mail app

**Mail app version:** 1.5.2

**Mailserver or service:** 2 different. One is hosteurope.de

**Transport security - IMAP:** TLS

**Transport security - SMTP:** TLS

**Number of accounts:** 2

**Mail app version build date:** ..

### Server configuration

**Operating system**: Debian 8 64bit

**Web server:** Apache 2.4.10

**Database:** 10.0.29-MariaDB

**PHP version:** 5.6.29-0+deb8u1

**Version:** 11.0.2

**Updated from an older version or fresh install:** updating since owncloud 5.

**List of activated apps:**

Enabled:
  - activity: 2.4.1
  - admin_audit: 1.1.0
  - calendar: 1.5.1
  - comments: 1.1.0
  - contacts: 1.5.3
  - dav: 1.1.1
  - direct_menu: 0.10.1
  - federatedfilesharing: 1.1.1
  - federation: 1.1.1
  - files: 1.6.1
  - files_pdfviewer: 1.0.1
  - files_sharing: 1.1.1
  - files_texteditor: 2.2
  - files_trashbin: 1.1.0
  - files_versions: 1.4.0
  - files_videoplayer: 1.0.0
  - firstrunwizard: 2.0
  - gallery: 16.0.0
  - issuetemplate: 0.2.1
  - logreader: 2.0.0
  - lookup_server_connector: 1.0.0
  - mail: 0.6.4
  - mozilla_sync: true
  - news: 10.1.0
  - nextcloud_announcements: 1.0
  - notes: 2.2.0
  - notifications: 1.0.1
  - password_policy: 1.1.0
  - provisioning_api: 1.1.0
  - serverinfo: 1.1.1
  - sharebymail: 1.0.1
  - spreed: 1.2.0
  - survey_client: 0.1.5
  - systemtags: 1.1.3
  - tasks: 0.9.5
  - templateeditor: 0.2
  - theming: 1.1.1
  - twofactor_backupcodes: 1.0.0
  - updatenotification: 1.1.1
  - workflowengine: 1.1.1
Disabled:
  - encryption
  - external
  - files_accesscontrol
  - files_automatedtagging
  - files_external
  - files_retention
  - user_external
  - user_ldap
  - user_saml

**The content of config/config.php:**

<details>
{
    "system": {
        "datadirectory": "\/var\/www\/web\/owncloud.rroot.org\/data",
        "dbtype": "mysql",
        "version": "11.0.2.7",
        "dbname": "ownclouddb",
        "dbhost": "localhost",
        "dbtableprefix": "oc_",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "installed": true,
        "loglevel": 1,
        "instanceid": "50767a2281a3b",
        "maintenance": false,
        "singleuser": false,
        "theme": "",
        "updatechecker": "true",
        "asset-pipeline.enabled": false,
        "trusted_domains": [
            "dom1.org",
            "dom2.org",
            "dom3.org"
        ],
        "secret": "***REMOVED SENSITIVE VALUE***",
        "share_folder": "\/Shared",
        "appstore.experimental.enabled": true,
        "trashbin_retention_obligation": "30, auto",
        "check_for_working_htaccess": true,
        "enable_avatars": true,
        "mail_from_address": "notification",
        "mail_smtpmode": "smtp",
        "mail_domain": "mydom.at",
        "mail_smtphost": "dom.at",
        "mail_smtpport": "587",
        "mail_smtpauthtype": "LOGIN",
        "mail_smtpauth": 1,
        "mail_smtpname": "***REMOVED SENSITIVE VALUE***",
        "mail_smtppassword": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpsecure": "tls",
        "updater.release.channel": "stable"
    }
}

</details>

#### Client configuration
**Browser:**
Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:52.0) Gecko/20100101 Firefox/52.0

**Operating system:**
Ubuntu 16.04.2 LTS

and 

**Browser:**
Mozilla/5.0 (Windows NT 6.3; WOW64; rv:53.0) Gecko/20100101 Firefox/53.0

**Operating system:**
Windows Server 2012 R2 Standard 64bit

##### Web server error log
no relevant logs.

##### Server log (data/nextcloud.log)
no relevant logs.

##### Horde IMAP log (data/horde_imap.log)
no relevant logs.

##### Horde SMTP log (data/horde_smtp.log)
no relevant logs.

##### Browser log
<details>

13:45:50.816 GET 
XHR 
https://dom1.at/core/templates/filepicker.html [HTTP/1.1 200 OK 0ms]
13:45:50.834 PROPFIND 
XHR 
https://dom1.at/remote.php/webdav/ [HTTP/1.1 207 Multi-Status 170ms]
13:45:50.929 GET 
https://dom1.at/core/img/actions/close.svg [HTTP/1.1 200 OK 0ms]
13:45:51.149 GET 
https://dom1.at/index.php/core/preview.png [HTTP/1.1 404 Not Found 205ms]
13:45:51.161 GET 
https://dom1.at/index.php/core/preview.png [HTTP/1.1 404 Not Found 123ms]
13:45:51.174 GET 
https://dom1.at/index.php/core/preview.png [HTTP/1.1 404 Not Found 1034ms]
13:45:51.185 GET 
https://dom1.at/index.php/core/preview.png [HTTP/1.0 200 Connection established 1966ms]
13:45:51.198 GET 
https://dom1.at/index.php/core/preview.png [HTTP/1.0 200 Connection established 3904ms]
13:45:51.211 GET 
https://dom1.at/index.php/core/preview.png [HTTP/1.0 200 Connection established 3947ms]
13:45:51.221 GET 
https://dom1.at/index.php/core/preview.png [HTTP/1.1 404 Not Found 192ms]
13:45:51.232 GET 
https://dom1.at/index.php/core/preview.png [HTTP/1.1 404 Not Found 242ms]
13:45:51.240 GET 
https://dom1.at/index.php/core/preview.png [HTTP/1.1 404 Not Found 291ms]
13:45:51.247 GET 
https://dom1.at/index.php/core/preview.png [HTTP/1.1 404 Not Found 343ms]
13:45:51.255 GET 
https://dom1.at/index.php/core/preview.png [HTTP/1.1 404 Not Found 401ms]
13:45:51.427 GET 
https://dom1.at/index.php/apps/theming/img/core/filetypes/video.svg [HTTP/1.1 200 OK 0ms]
13:45:51.430 GET 
https://dom1.at/index.php/apps/theming/img/core/filetypes/application-pdf.svg [HTTP/1.1 200 OK 0ms]
13:45:51.434 GET 
https://dom1.at/index.php/apps/theming/img/core/filetypes/text-calendar.svg [HTTP/1.1 200 OK 0ms]
13:45:51.466 GET 
https://dom1.at/index.php/apps/theming/img/core/filetypes/x-office-spreadsheet.svg [HTTP/1.1 200 OK 0ms]
13:45:51.470 GET 
https://dom1.at/index.php/apps/theming/img/core/filetypes/file.svg [HTTP/1.1 200 OK 0ms]
13:45:51.473 GET 
https://dom1.at/index.php/apps/theming/img/core/filetypes/package-x-generic.svg [HTTP/1.1 200 OK 0ms]
13:45:51.484 GET 
https://dom1.at/core/img/places/home.svg [HTTP/1.1 200 OK 0ms]
13:45:51.776 GET 
XHR 
https://dom1.at/ocs/v2.php/apps/notifications/api/v2/notifications [HTTP/1.1 200 OK 134ms]
13:46:21.590 GET 
XHR 
https://dom1.at/ocs/v2.php/apps/notifications/api/v2/notifications [HTTP/1.1 200 OK 189ms]

</details>

**Comment by lcalaresu** [comment]
Forgot to close that one.
Fixed with PR #380
