### ISSUE TITLE
0.6.4 on NC 11.0.3: backbone.radio.js & ical.min.js missing

### ISSUE THREAD

**Issue by blizzz** [nextcloud/mail#371]
### Steps to reproduce
1. Update Mail app to 0.6.4
2. Open Mail app

### Expected behaviour

On a fresh account you should be able to connect to a mail account

### Actual behaviour

Spinning wheels.

Error console:

```
GET https://my.server/apps/mail/js/vendor/backbone.radio/build/backbone.radio.js [HTTP/1.1 404 Not Found 42ms]

13:13:38.171 Error: Script error for "backbone.radio", needed by: marionette, radio
http://requirejs.org/docs/errors.html#scripterror 1 require.js:168:17
	makeError https://my.server/apps/mail/js/vendor/requirejs/require.js:168:17
	onScriptError https://my.server/apps/mail/js/vendor/requirejs/require.js:1735:36

GET https://my.server/apps/mail/js/vendor/ical.js/build/ical.min.js [HTTP/1.1 404 Not Found 36ms]

13:13:40.260 Error: Script error for "ical", needed by: service/davservice
http://requirejs.org/docs/errors.html#scripterror 1 require.js:168:17
	makeError https://my.server/apps/mail/js/vendor/requirejs/require.js:168:17
	onScriptError https://my.server/apps/mail/js/vendor/requirejs/require.js:1735:36
```

It seems some build magic was missed before packing the release

### Mail app

**Mail app version:** 0.6.4

### Server configuration

**Operating system**: Ubuntu 16.04

**Web server:** Apache2

**Database:** MySQL 5.7.18

**PHP version:** 7.0.15

**Version:** 11.0.3

**Updated from an older version or fresh install:** Updated

#### Client configuration
**Browser:** Firefox 53

**Operating system:** Antergos

##### Browser log

see above

**Comment by ChristophWurst** [comment]
I guess the build script does not copy over those two files because they are in a `build` subdir. But this shouldn't be a problem unless you have enabled debug mode. It shouldn't happen if debug mode is switched *off*. Can you confirm that?

**Comment by blizzz** [comment]
> It shouldn't happen if debug mode is switched off. Can you confirm that?

Oh, indeed. Yes, with debug mode disabled the issue does not occur.

**Comment by ChristophWurst** [comment]
I actually fixed this already: https://github.com/nextcloud/mail/pull/253 :)
