### ISSUE TITLE
Do not auto read mark

### ISSUE THREAD

**Issue by jookk** [nextcloud/mail#3723]
### Feature Request
Open mail app in Nextcloud. If you have new unread messages, it is actually
automatically shown / opened and marked as read. Very easy can be that
message unseen.

#### Summary

n/a

**Comment by ChristophWurst** [comment]
?

**Comment by jookk** [comment]
Open mail app in Nextcloud. If you have new unread messages, it is actually 
automatically shown / opened and marked as read. Very easy can be that 
message unseen.

Dňa 5. októbra 2020 14:42:25 používateľ Christoph Wurst 
<notifications@github.com> napísal:

**Comment by StCyr** [comment]
Don't we just want a small delay before marking the mail read (ie: the message must be open for at least <x> seconds for the read mark to be applied)?

**Comment by ChristophWurst** [comment]
> Don't we just want a small delay before marking the mail read (ie: the message must be open for at least seconds for the read mark to be applied)?

Sure :+1:
