### ISSUE TITLE
No translation in Transiflex available for 'remove account' dialogue

### ISSUE THREAD

**Issue by hartsberger** [nextcloud/mail#3729]
_I hope this is the right place to inform someone about this issue. Sorry if it is not._ 

### Expected behavior
In Transiflex / Mail should be a string available, that the people can translate. 
It is the text of the "remove account" dialoge: 

> The account for xxx and cached email data will be removed from Nextcloud, but not from your email provider.

### Actual behavior
That string does not exist in Transiflex. The message is displayed in English, although my language is set to German.

**Comment by ChristophWurst** [comment]
> I hope this is the right place to inform someone about this issue. Sorry if it is not.

it is! Thanks :)

**Comment by ChristophWurst** [comment]
https://github.com/nextcloud/mail/blob/e25d269f039d5a8e475c9ee1a621c7e46f2c930d/l10n/hu.js#L101 I think the string is translatable, tho. It might just be untranslated on https://www.transifex.com/nextcloud/. Mind checking there?

**Comment by hartsberger** [comment]
The button "remove account" is translated correctly. 
But the message that appears after clicking that button is not available on Transiflex. 

![Bildschirmfoto vom 2020-10-06 11-00-08](https://user-images.githubusercontent.com/60740965/95181852-1909f700-07c4-11eb-893c-3b7c683ecd91.png)

**Comment by ChristophWurst** [comment]
Got it. I think I know what the problem is.

**Comment by ChristophWurst** [comment]
https://github.com/nextcloud/mail/pull/3731 should fix the detection of the string. Once that is integrated we'll hopefully get the string on Transifex.

Thanks a lot
