### ISSUE TITLE
Option to show images by default [$10]

### ISSUE THREAD

**Issue by tenten8401** [nextcloud/mail#373]
Title pretty much says it all here, but can we have an option to show all images by default?

**Comment by ChristophWurst** [comment]
Implementation idea: add a new table `trusted_sender` with (id, user_id, email) that holds all addresses a user marked as trustworthy. If we can lookup the sender address for a message, we show the images by default.

FYI loading all images by default has a major impact on your privacy as we're not proxying/caching image in any way, hence all the nasty tracking stuff that is being done won't be blocked anymore.

**Comment by rainerzufall** [comment]
I just posted $10 on [Bountysource](https://www.bountysource.com/issues/45161113-option-to-show-images-by-default).

**Comment by jancborchardt** [comment]
I’d close this in favor of **Remember "Show images from sender" #505** because it’s a way better middle path. People don’t unwittingly give up their privacy, and it’s clear what you do.

**Comment by ChristophWurst** [comment]
There is a bounty on this ticket, though.

**Comment by jancborchardt** [comment]
@rainerzufall mind changing your bounty from this issue to #505? :)

**Comment by ChristophWurst** [comment]
That is not how it works. You have to send an email to Bountysource support.

**Comment by rainerzufall** [comment]
Don't worry about the bounty and let's not make it too complicated! Just have a beer/tea/coffee together after all the Corona thing is over :)

**Comment by ChristophWurst** [comment]
Yes but still you should get your money back to your account so you can put it onto a new ticket. It's now inaccessible.

:+1: for :beers: :grin:

**Comment by rainerzufall** [comment]
Ah I thought Jan got the money now, since he closed the ticket... So I thought I'd just sponsor you beer ;) Not because of this ticket, but I am a happy Nextcloud user, who appreciates your efforts... but if the money is now locked in I will put it onto a new ticket...
