### ISSUE TITLE
Allow to configure Sent and Drafts folder names

### ISSUE THREAD

**Issue by beccon4** [nextcloud/mail#3732]
### Feature Request

Allow user to configure name of IMAP.Sent and IMAP.Draft folder 

#### Summary

An IMAP account accessed with multiple clients tend to have localized names for Sent and Drafts - in my case it is INBOX.Gesendet and INBOX.Entwürfe (with the Umlaut)  

Mail doesn't recognise this and stores sent mails in INBOX.Sent.

**Comment by ChristophWurst** [comment]
There is an existing ticket for this.
