### ISSUE TITLE
Dashboard widget for unread mail

### ISSUE THREAD

**Issue by zerodogg** [nextcloud/mail#3742]
### Feature Request

A widget that displays the latest unread e-mails from subscribed inboxes

#### Summary

Provide an additional widget that just lists the latest unread e-mails. Useful to quickly get an overview of new mails, even those that the mail app hasn't decided is important.

**Comment by dumblob** [comment]
This feels like a must have.

I'd actually broaden this request to add support for any number of user-created "widgets" aggregating emails from all email accounts the user is using from all folders in those accounts and letting the user write her own **advanced filter** over all these emails (e.g. read/unread, check for a given custom header existence, check for substring in email body, etc.).

This is the only way (TM) :wink: to handle hundreds and thousands of emails per day (any other method involves manual email moving during email processing which is impossible with such amounts to do quickly and without mistakes).

Please don't confuse this with Sieve filtering as to mimic such "live view" behavior (the same email is part of several "live views" at the same time) with Sieve one would need to make copies of a message which is a no-go as any copying just messes things up (and even then one wouldn't be able to aggregate over multiple email addresses).

Thoughts?

**Comment by ChristophWurst** [comment]
> Btw. it could also be seen as "saved searches". It's all the same principle wink.

Makes sense, I guess.

**Comment by st3iny** [comment]
@dumblob Please open a new ticket for your feature request. A new dashboard widget for unread mails was added recently (#4124).

**Comment by zerodogg** [comment]
@st3iny Fantastic, looking forward to using this. Thanks!
