### ISSUE TITLE
Layout issue whith large To: field

### ISSUE THREAD

**Issue by StCyr** [nextcloud/mail#3743]
### Expected behavior
It's 2020 and people still use the To: or Cc: field to list a large amount of email addresses. Mail should protect itself from that

### Actual behavior
When displaying a message with large To: or Cc: field, this field overlaps other elements on the page:

![Untitled](https://user-images.githubusercontent.com/8179031/95305535-63ec4300-0886-11eb-9ad0-a96b2e341ed7.png)

### Mail app

**Mail app version:** master (1.5)

**Comment by ChristophWurst** [comment]
@jancborchardt @GretaD that is the theoretical issue we discussed about showing max one line with those avatars :)

**Comment by StCyr** [comment]
I've fixed locally with:

```
.avatar-header {
        max-height: 80px;
        overflow-y: auto;
}
```

**Comment by GretaD** [comment]
> I've fixed locally with:
> 
> ```
> .avatar-header {
>         max-height: 80px;
>         overflow-y: auto;
> }
> ```
Thank you, do you want to shot a PR? I should I do it?

**Comment by StCyr** [comment]
No problem. I’ll do it
