### ISSUE TITLE
Switching from one mailbox to another triggers two get requests to the /apps/mail/api/messages endpoint

### ISSUE THREAD

**Issue by IchbinkeinReh** [nextcloud/mail#3746]
### Expected behavior
When you switch from one mailbox to another, then only one get requests to the /apps/mail/api/messages endpoint is triggered

### Actual behavior
When you switch from one mailbox to another, then two get requests to the /apps/mail/api/messages endpoint are triggered

Mail app
Mail app version: v1.5.0

Mailserver or service: Strato

Server configuration
Operating system: Ubuntu 20.04

Web server: Apache

Database: MariaDB

PHP version: 7.4

Nextcloud Version: 20.0.0

Client configuration
Browser: Chrome 81

Operating system: Ubuntu 20.04

**Comment by StCyr** [comment]
Is it still the case. I can't reproduce this behaviour in v 1.9

And, when you say mailbox, you mean folder or completly different accounts?

**Comment by IchbinkeinReh** [comment]
I just tested it again with mail app version 1.9.1 and the issue is still there on my nextcloud instance.

- When switching from one folder to another of the same account then only one request is triggered
- When switching from inbox of account A to inbox of account B then two GET requests to the same url (/index.php/apps/mail/api/messages?mailboxId=53&limit=20) are triggered
- When switching from inbox of account A to "All inboxes" (i have 3 mail accounts) i see 6 GET requests of which 3 are unique. so also here every request is executed doubled.

**Comment by IchbinkeinReh** [comment]
Can we please reopen this issue. I just checked and the issue still exists on my nextcloud installation with mail app version 1.12.0-rc.1
