### ISSUE TITLE
Memory leak in mail app

### ISSUE THREAD

**Issue by maurerle** [nextcloud/mail#3747]
### Expected behavior
The following graph shows the memory usage of my docker-container:
![grafik](https://user-images.githubusercontent.com/25026204/95363263-85bde800-08cf-11eb-9126-ede8dd146448.png)

It always consumes more and more memory every day (seems independant from the usage). Since the 20th september, i deactivated the mail app, which stopped the memory leak.

I have multiple mailboxes configured and I also have 2 users with the same configured mailbox.
Everything is working quite well so far, but this should not happen anyways.

### Actual behavior
Memory usage rises continously until the next reboot. My peak is 1.6GB before I restarted the container

### Mail app

**Mail app version:** 1.4.1

**Mailserver or service:** Outlook, Gmail +4 others

### Server configuration

**Operating system**: Debian 10

**Web server:** Nginx reverse proxy

**Database:** PostgreSQL

**PHP version:** (e.g. 7.0)
docker-image: 19-fpm-alpine

**Nextcloud Version:** latest 19

**Comment by ChristophWurst** [comment]
How's that even possible? We don't manage any memory. Isn't that more of a php bug?

Btw this is about the server component and not what's happening in the front-end,right?

**Comment by maurerle** [comment]
Well I already tried moving from pm.dynamic to pm.static, 
tested the param
```
; The number of requests each child process should execute before respawning.
; This can be useful to work around memory leaks in 3rd party libraries. For
; endless request processing specify '0'. Equivalent to PHP_FCGI_MAX_REQUESTS.
; Default Value: 0
;pm.max_requests = 500
```
and played with the children numbers.

As it also occurs if I don't use the mail app for days, I think this has to do with the background sync/cron job?

And yes from my investiagtion I'd say this is backend/server issue.

**Comment by ChristophWurst** [comment]
Okay, but more like certain code that we use in Mail triggers this bug than we actively cause it, I think.

What version of php are you running right now?

**Comment by maurerle** [comment]
So its Nextcloud 19.0.3
PHP:
Version: 7.4.11
RAM-limit: 4 GB
max execution time: 3600
max upload size: 4 GB

i runs in docker nextcloud:19-alpine-fpm image

**Comment by ChristophWurst** [comment]
WHen mail is active, could you check the `oc_jobs` table for all mail sync jobs and see how long their last execution was?

alternatively you can trigger account syncs from the CLI with `occ mail:account:sync <id>` where id is taken from `oc_mail_accounts` and see if any of those is particularly slow.

**Comment by maurerle** [comment]
The oc prefix was removed a few releases ago right?

Thanks, thats cool.
I currently get for the `@outlook.com` mail address (synced with app password)

```
In ImapToDbSynchronizer.php line 213:
  Sync failed for 1:INBOX: IMAP error reported by server.
In Socket.php line 4602:
```
Considering, that each sync takes about 35MB, I could imagine that the failed syncs are not properly cleaned when run as cron?
The mails for this account are syncing though

Will try again in an hour or so and monitor the usage for the next days.
Does disable&removing the mail app also delete all mail accounts?

I think I will remove and configure the outlook.com account in a few days, to see if this helps

**Comment by maurerle** [comment]
I updated the password with a new app-password for it, and checked the settings again.
My outlook mail account is now syncing fine.

I am going to close this for now and will reopen  this issue if the error appears again.

**Comment by maurerle** [comment]
Yesterday morning at around 9:15 I had a RAM usage change from 267MB (9:14) to 409MB (9:16).

In the meantime there were two errors:
```
[mail] Error: OCA\Mail\Exception\ServiceException: Sync failed for 1:INBOX: IMAP error reported by server. at <<closure>>

0. /var/www/html/custom_apps/mail/lib/Service/Sync/ImapToDbSynchronizer.php line 114
   OCA\Mail\Service\Sync\ImapToDbSynchronizer->sync(OCA\Mail\Account {}, OCA\Mail\Db\Mailbox {id: 39}, 42, null, false)
1. /var/www/html/custom_apps/mail/lib/BackgroundJob/SyncJob.php line 92
   OCA\Mail\Service\Sync\ImapToDbSynchronizer->syncAccount(OCA\Mail\Account {})
2. /var/www/html/lib/public/BackgroundJob/Job.php line 80
   OCA\Mail\BackgroundJob\SyncJob->run({accountId: 1})
3. /var/www/html/lib/public/BackgroundJob/TimedJob.php line 61
   OCP\BackgroundJob\Job->execute(OC\BackgroundJob\JobList {}, OC\Log {})
4. /var/www/html/cron.php line 126
   OCP\BackgroundJob\TimedJob->execute(OC\BackgroundJob\JobList {}, OC\Log {})

at 2020-10-08T07:16:14+00:00
```
syncing with occ returns the same error message..

```
[mail] Error: Doctrine\DBAL\Exception\NotNullConstraintViolationException: An exception occurred while executing 'INSERT INTO "mail_classifiers" ("type", "training_set_size", "validation_set_size", "account_id", "duration", "app_version", "estimator", "active", "created_at") VALUES(?, ?, ?, ?, ?, ?, ?, ?, ?)' with params ["importance", 198, 22, 12, 0, "1.4.1", "Rubix\\ML\\Classifiers\\GaussianNB", false, 1602140720]:

SQLSTATE[23502]: Not null violation: 7 ERROR:  null value in column "recall_important" violates not-null constraint
DETAIL:  Failing row contains (4767, 12, importance, Rubix\ML\Classifiers\GaussianNB, 1.4.1, 198, 22, null, null, null, 0, f, 1602140720). at <<closure>>

 0. /var/www/html/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/DBALException.php line 169
    Doctrine\DBAL\Driver\AbstractPostgreSQLDriver->convertException("An exception oc ... .", Doctrine\DBAL\Dr ... ]})
 1. /var/www/html/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/DBALException.php line 145
    Doctrine\DBAL\DBALException::wrapException(Doctrine\DBAL\Driver\PDOPgSql\Driver {}, Doctrine\DBAL\Dr ... ]}, "An exception oc ... .")
 2. /var/www/html/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/Connection.php line 1063
    Doctrine\DBAL\DBALException::driverExceptionDuringQuery(Doctrine\DBAL\Driver\PDOPgSql\Driver {}, Doctrine\DBAL\Dr ... ]}, "INSERT INTO \"m ... )", {1: "importance" ... 0})
 3. /var/www/html/lib/private/DB/Connection.php line 214
    Doctrine\DBAL\Connection->executeUpdate("INSERT INTO \"m ... )", ["importance",19 ... 0], [2,1,1,1,1,2,2,5,1])
 4. /var/www/html/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/Query/QueryBuilder.php line 203
    OC\DB\Connection->executeUpdate("INSERT INTO \"m ... )", {dcValue1: "impo ... 0}, {dcValue1: 2,dcV ... 1})
 5. /var/www/html/lib/private/DB/QueryBuilder/QueryBuilder.php line 216
    Doctrine\DBAL\Query\QueryBuilder->execute()
 6. /var/www/html/lib/public/AppFramework/Db/QBMapper.php line 129
    OC\DB\QueryBuilder\QueryBuilder->execute()
 7. /var/www/html/custom_apps/mail/lib/Service/Classification/PersistenceService.php line 110
    OCP\AppFramework\Db\QBMapper->insert(OCA\Mail\Db\Classifier {id: null})
 8. /var/www/html/custom_apps/mail/lib/Service/Classification/ImportanceClassifier.php line 221
    OCA\Mail\Service\Classification\PersistenceService->persist(OCA\Mail\Db\Classifier {id: null}, Rubix\ML\Classifiers\GaussianNB {})
 9. /var/www/html/custom_apps/mail/lib/BackgroundJob/TrainImportanceClassifierJob.php line 80
    OCA\Mail\Service\Classification\ImportanceClassifier->train(OCA\Mail\Account {}, OC\AppFramework\Logger {})
10. /var/www/html/lib/public/BackgroundJob/Job.php line 80
    OCA\Mail\BackgroundJob\TrainImportanceClassifierJob->run({accountId: 12})
11. /var/www/html/lib/public/BackgroundJob/TimedJob.php line 61
    OCP\BackgroundJob\Job->execute(OC\BackgroundJob\JobList {}, OC\Log {})
12. /var/www/html/cron.php line 126
    OCP\BackgroundJob\TimedJob->execute(OC\BackgroundJob\JobList {}, OC\Log {})

at 2020-10-08T07:05:20+00:00
```
and a few "not enough messages to train a classifier" messages, which are unrelated.
My UFW logs leftovers from packages indicating a connection reset (RST)
`SRC=173.x.x.x DST=192.168.x.xLEN=40 TOS=0x00 PREC=0x00 TTL=123 ID=0 DF PROTO=TCP SPT=993 DPT=59534 WINDOW=0 RES=0x00 RST URGP=0` 
for each mail server.

I will try disabling ufw for tomorrow, as my server has only a few ports forwarded and is not an exposed host.

But in either way the nextcloud background service should kill the imap sync process if it fails?

**Comment by ChristophWurst** [comment]
> IMAP error reported by server

Something we'll need the horde_imap.log for. Enable debug mode, run the occ sync again and disable debug mode again. THen you'll find that file at `data/horde_imap.log`.



> null value in column "recall_important" violates not-null constraint

This I actually fixed just recently. But only for Mail v1.5 that is available for Nextcloud 20. Any plans for an upgrade?

> nd a few "not enough messages to train a classifier" messages, which are unrelated.

You can safely ignore those :)

**Comment by maurerle** [comment]
Hi again,

after the fetch the server stores the messages and 

```
S: 97 OK FETCH completed.
>> Command 97 took 52.369 seconds.
>> CACHE: Stored messages [INBOX; 1342,1360:1361,1365,1382...]
C: 98 UID SEARCH UID 18820,9187,18194,18196,18200...
S: 98 BAD Command Error. 10
>> Command 98 took 0.0343 seconds.
C: 99 LOGOUT
>> ERROR: Server closed the connection.
```

There is something which the outlook.com server does not like about the UID SEARCH UID command.
But this must be related to some kind of special mail in my account, as I seem to be the only one...

Any further ideas?

Otherwise I will check if I can reproduce this in a NC20 container too

**Comment by ChristophWurst** [comment]
It's indeed a MS Exchange specific error and not only this client has problems with it:

* https://github.com/mscdex/node-imap/issues/44
* https://github.com/soywod/iris.vim/issues/3
* https://github.com/soywod/iris.vim/issues/4
* https://github.com/mscdex/node-imap/issues/381

**Comment by maurerle** [comment]
This issue could not be reproduced on my test instance (NC20). I therefore uninstalled mail and dropped all mail related tables (as explained on the nextcloud forum) and let the mail app recreate them. 

Since then the memory leak is not happening anymore (on my NC19 instance).
The imap error persists when syncing with `occ mail:account:sync 2` but this doesnt bother the general experience.

I will close this as the memory leak no longer occurs.
Thank you for your efforts!
