### ISSUE TITLE
Where is the SERVER REQUIERE AUTHENTICATION ON SMTP

### ISSUE THREAD

**Issue by grohlperu** [nextcloud/mail#376]
I can't found the option for SMTP, requiere authentication

**Comment by ChristophWurst** [comment]
Could you please provide more detail about your question/problem?

**Comment by grohlperu** [comment]
Like Office Outlook there is not an option to select or activate the "SMTP requires authentication"

**Comment by ChristophWurst** [comment]
AFAIK it will always assume that authentication is required. Do you have issues with your SMTP setup?

**Comment by grohlperu** [comment]
When i put only email address and pass, i think the app test all types of possible config to setup the account, it takes his time and nothing happens. Then i put a manually setup first without SSL and then with SSL and nothing happens

**Comment by grohlperu** [comment]
Error when communicate with server only

**Comment by grohlperu** [comment]
I try with my gmail account and works, but when i try to my business account nothing happens

**Comment by ChristophWurst** [comment]
Please fill out the full [issue template](https://raw.githubusercontent.com/nextcloud/mail/master/.github/issue_template.md). Especially the SMTP log would be interesting. You'll find instructions on how to enable it in the readme.

**Comment by ChristophWurst** [comment]
I'm closing this ticket now due to the lack of feedback/activity.
