### ISSUE TITLE
"Register as application for mail links" feature does not work

### ISSUE THREAD

**Issue by IchbinkeinReh** [nextcloud/mail#3760]
### Expected behavior
After i clicked "Register as application for mail links" and then clicked on a website on a mailto link i get redirected to my nextcloud instance and see the compose new mail window with the to field and optional subject and body prefilled

### Actual behavior
After i clicked "Register as application for mail links" and then clicked on a website on a mailto link i get redirected to my nextcloud instance and see my email accounts

Mail app
Mail app version: v1.5.0

Mailserver or service: Strato

Server configuration
Operating system: Ubuntu 20.04

Web server: Apache

Database: MariaDB

PHP version: 7.4

Nextcloud Version: 20.0.0

Client configuration
Browser: Chrome 81

Operating system: Ubuntu 20.04

**Comment by ChristophWurst** [comment]
This might be a regression due to the routing change of https://github.com/nextcloud/mail/pull/3439 because at the generated redirect we still use the old hash routing: https://github.com/nextcloud/mail/blob/f8543ada0b781a8451fa930a62a38666df2e5114/lib/Controller/PageController.php#L221
