### ISSUE TITLE
BUG : Can not activate Mail app after  migration 19 to 20

### ISSUE THREAD

**Issue by daraelmin** [nextcloud/mail#3780]
Hi I can not activate Mail any more.
I've try to remove and reinstall and I've got this error: 
Une erreur est survenue durant la requête. Impossible de traiter la demande.✖
I use to see eigther, but not anymore now.

ERROR: Command errored out with exit status 1:      command: /usr/bin/python3 -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-yt6rb59l/pygame/setup.py'"'"'; __file__='"'"'/tmp/pip-install-yt6rb59l/pygame/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-install-yt6rb59l/pygame/pip-egg-info          cwd: /tmp/pip-install-yt6rb59l/pygame/     Complete output (18 lines):

**Comment by ChristophWurst** [comment]
I don't know if there is any relation to this actual app. Looks more like some system written in Python is causing trouble. So not Nextcloud.

Should this still be a bug in this very app then open a proper bug report using our template: https://github.com/nextcloud/mail/issues/new?assignees=&labels=bug%2C+0.+to+triage&template=bug.md&title=

:v:
