### ISSUE TITLE
Options to not auto mark as read when opening a message

### ISSUE THREAD

**Issue by junpet** [nextcloud/mail#3785]
### Feature Request

Currently if you open an unread message, it will be marked as read. It would be nice, if there would be an option in the Settings like `Opt out auto mark as read` or something like that. The default would be false/uncheck, like how currently things work.

#### Summary

Option to disable auto mark as read messages when opening them.

**Comment by ChristophWurst** [comment]
Duplicate of https://github.com/nextcloud/mail/issues/3723

**Comment by ChristophWurst** [comment]
Sure, you can open a feature request
