### ISSUE TITLE
CC name encoding

### ISSUE THREAD

**Issue by sheychen290** [nextcloud/mail#381]
### Steps to reproduce
1. receive mail with 'é' in CC name

### Expected behaviour
'clément'

### Actual behaviour
![capture](https://cloud.githubusercontent.com/assets/16181031/26722658/2a4b26ca-4791-11e7-83c3-e5a540a471b5.JPG)

### Mail app

**Mail app version:**  0.6.4

**Mailserver or service:** Gmail

**Transport security - IMAP:** STARTTLS ?

**Transport security - SMTP:** STARTTLS ?

**Number of accounts:** 4

### Server configuration

**Operating system**: Raspbian Lite (Debian)

**Web server:** Apache 2.4

**Database:** MariaDB

**PHP version:** 7.0.19

**Version:** 12.0.0

**Updated from an older version or fresh install:** 10

#### Client configuration
**Browser:** Firefox 53

**Operating system:** Windows 7

**Comment by ChristophWurst** [comment]
I'm closing this ticket because it hasn't received any updates in a long time. If this is still relevant, feel free to re-open or file a new ticket.

v0.12.0 of the app brought a new front-end.

Thank you.
