### ISSUE TITLE
Possibility

### ISSUE THREAD

**Issue by derritter88** [nextcloud/mail#3814]
### Feature Request

Althought Nextcloud is designed to work as a production hub for email, contacts and calendar it might be a useful feature if there would be the possiblity to have a syncronisation function with and Exchange server (Exchange Active Sync, EAS).

Currently Mail app is only able to add an IMAP server.
Contacts does not feature any external sources and Calendar only supports read-only.

#### Summary

Unified synchronisation to Exchange(-like) servers with EAS sync for Mail, Calendar & Contacts

**Comment by ChristophWurst** [comment]
We had a ticket for this but I can't find it right now. It's out of scope for us and we're rather reluctant imlementing this specific protocol when the standard protocol IMAP works with almost every provider, hence I'm closing the request.
