### ISSUE TITLE
Unending loading of mails

### ISSUE THREAD

**Issue by raspbeguy** [nextcloud/mail#3815]
### Expected behavior
Be able to view my mail.

Here is a [logfile excerpt](https://github.com/nextcloud/mail/files/5378491/nextcloud_mail.log)

### Actual behavior
The loading never ends.

### Mail app

**Mail app version:** 1.4.1

**Mailserver or service:** Own personal mail server.

### Server configuration

**Operating system**: Debian 10

**Web server:** Nging

**Database:** MariaDB

**PHP version:** 7.3

**Nextcloud Version:** 19.0.4

#### Client configuration
**Browser:** Firefox 81

**Operating system:** Arch Linux

**Comment by ChristophWurst** [comment]
> Incorrect string value: '\\xE9trov\\xE9...' for column `nextcloud`.`oc_mail_recipients`.`email` at row 1

Is your DB ready for https://docs.nextcloud.com/server/stable/admin_manual/configuration_database/mysql_4byte_support.html?

**Comment by raspbeguy** [comment]
Ok, I did the operations on the DB.
Now the good point is that small mailbox folders can ben viewed (I did not try before the database changes).
My main mailbox folder contains about 5000 messages, so I'm waiting a bit.

**Comment by ChristophWurst** [comment]
> My main mailbox folder contains about 5000 messages, so I'm waiting a bit.

Do that. But it should also not take too long, like more than a few mins max :)

**Comment by ChristophWurst** [comment]
> An exception occurred while executing 'INSERT INTO `oc_mail_recipients` (`message_id`, `type`, `label`, `email`) VALUES(?, ?, ?, ?)' with params [73345, 0, \"M\\u00e9trov\\u00e9lo\", \"\\x4d\\xe9\\x74\\x72\\x6f\\x76\\xe9\\x6c\\x6f\\x40\\x65\\x64\\x64\\x76\\x2d\\x6d\\x65\\x74\\x72\\x6f\\x76\\x65\\x6c\\x6f\\x2d\\x30\\x31\\x2e\\x65\\x6f\\x6c\\x61\\x73\\x2d\\x73\\x65\\x72\\x76\\x69\\x63\\x65\\x73\\x2e\\x63\\x6f\\x6d\"]:\n\nSQLSTATE[22007]: Invalid datetime format: 1366 Incorrect string value: '\\xE9trov\\xE9...' for column `nextcloud`.`oc_mail_recipients`.`email` at row 1"

very similar issue. could be the database. could be that that email has some non utf-8 encoded sender.

**Comment by ChristophWurst** [comment]
https://codebeautify.org/hex-string-converter/cbe22614 FYI that is the sender name. Is it spam?

**Comment by raspbeguy** [comment]
I don't think that is spam. But yeah there is a smap folder I managed to view.

**Comment by ChristophWurst** [comment]
how's that sender displayed in other clients? mind sharing a screenshot?

**Comment by raspbeguy** [comment]
![In Thunderbird](https://user-images.githubusercontent.com/1781287/96084268-1b084000-0ebf-11eb-8ad0-2a2a4a5fba57.png)

**Comment by ChristophWurst** [comment]
That looks just fine. Now I'm wondering there the encoding mismatch comes from.

**Comment by ChristophWurst** [comment]
yes?

**Comment by raspbeguy** [comment]
Sorry I accidentally closed it, so I reopened it. Sorry for the noise.

**Comment by ChristophWurst** [comment]
But I think this was actually fixed with https://github.com/nextcloud/mail/pull/3855

**Comment by ChristophWurst** [comment]
Please update to Nextcloud 20/Mail 1.6.1 and let us know :v:

**Comment by raspbeguy** [comment]
I just learnt that you could switch to beta to get new version and switch back to stable. I did that and everything seem to work. Thank you.
