### ISSUE TITLE
Mail Widget doesn't display the email

### ISSUE THREAD

**Issue by pkmkrishnakumar** [nextcloud/mail#3819]
### Steps to reproduce
1. After upgrading to NC20 or Fresh Install
2. Enabled Mail Widget in New Dashboard
3. Mail is not displayed

### Expected behaviour
To display the list of recent mail or important mail

### Actual behaviour
Did not display the list of recent mail or important mail

![image](https://user-images.githubusercontent.com/29704829/96069369-b5668480-0ebb-11eb-8cd2-8c00024f499c.png)

### Server configuration

**Operating system:** Ubuntu 18.04

**Web server:** Apache2

**Database:** MySQL

**PHP version:** Php 7.4

**Nextcloud version:**  20

**Updated from an older Nextcloud/ownCloud or fresh install:** Upgrade from 19 to 20

**Where did you install Nextcloud from:** Nextcloud Official Download

**Comment by ChristophWurst** [comment]
Check the browser log for logged errors and failing requests

**Comment by pkmkrishnakumar** [comment]
OCA\\Mail\\BackgroundJob\\TrainImportanceClassifierJob job with ID 4123","userAgent":"--","version":"20.0.0.9"}
{"reqId":"sH0TJrhFabRsXXlqU97z","level":1,"time":"2020-10-15T06:48:17+00:00","remoteAddr":"","user":"--","app":"mail","method":"","url":"--","message":"Ignoring cron training for provisioned account that has no password set yet","userAgent":"--","version":"20.0.0.9"}
{"reqId":"sH0TJrhFabRsXXlqU97z","level":0,"time":"2020-10-15T06:48:17+00:00","remoteAddr":"","user":"--","app":"cron","method":"","url":"--","message":"Finished OCA\\Mail\\BackgroundJob\\TrainImportanceClassifierJob job with ID 4123 in 0 seconds","userAgent":"--","version":"20.0.0.9"}

**Comment by ChristophWurst** [comment]
> Check the browser log for logged errors and failing requests

*browser* not server :wink:

**Comment by pkmkrishnakumar** [comment]
![image](https://user-images.githubusercontent.com/29704829/96118256-ddc8a000-0f08-11eb-804e-a0a1a978cb1f.png)
![image](https://user-images.githubusercontent.com/29704829/96118335-f933ab00-0f08-11eb-918a-03e6954edeba.png)

**Comment by ChristophWurst** [comment]
That is strange. I would have expected an error message logged for that *Internal Server Error*. Are you sure you didn't miss a line in the nextcloud.log?

**Comment by pkmkrishnakumar** [comment]
![image](https://user-images.githubusercontent.com/29704829/96158240-f2209300-0f30-11eb-838d-df4113e4355c.png)

![image](https://user-images.githubusercontent.com/29704829/96158311-04023600-0f31-11eb-8fed-4448faebd108.png)

**Comment by pkmkrishnakumar** [comment]
{"reqId":"omuGiTmqziZDLvlUF172","level":0,"time":"2020-10-15T06:48:26+00:00","remoteAddr":"","user":"--","app":"cron","method":"","url":"--","message":"Run OCA\\Mail\\BackgroundJob\\SyncJob job with ID 4136","userAgent":"--","version":"20.0.0.9"}
{"reqId":"omuGiTmqziZDLvlUF172","level":1,"time":"2020-10-15T06:48:26+00:00","remoteAddr":"","user":"--","app":"mail","method":"","url":"--","message":"Ignoring cron sync for provisioned account that has no password set yet","userAgent":"--","version":"20.0.0.9"}
{"reqId":"omuGiTmqziZDLvlUF172","level":0,"time":"2020-10-15T06:48:26+00:00","remoteAddr":"","user":"--","app":"cron","method":"","url":"--","message":"Finished OCA\\Mail\\BackgroundJob\\SyncJob job with ID 4136 in 0 seconds","userAgent":"--","version":"20.0.0.9"}
{"reqId":"QwqrYq9yvYeeUL73KKmj","level":0,"time":"2020-10-15T06:48:27+00:00","remoteAddr":"10.10.1.151","user":"jit0233","app":"admin_notifications","method":"POST","url":"/cloud/apps/text/session/sync","message":"/appinfo/app.php is deprecated, use \\OCP\\AppFramework\\Bootstrap\\IBootstrap on the application class instead.","userAgent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/86.0.4240.75 Safari/537.36","version":"20.0.0.9"}

**Comment by pkmkrishnakumar** [comment]
These are the errors seen in the Browser as well as in nextcloud.log

After upgrading to NC20, 

The following error is being filled in the nextcloud log  for most of the apps. It logs continuously and fills the log file with in couple of minutes to 100 MB .

{"reqId":"a9iXRRwrRXiQR4CEFy4C","level":0,"time":"2020-10-15T06:48:16+00:00","remoteAddr":"10.10.1.151","user":"jit0215","app":"contacts","method":"GET","url":"/cloud/ocs/v2.php/apps/notifications/api/v2/notifications","message":"/appinfo/app.php is deprecated, use \\OCP\\AppFramework\\Bootstrap\\IBootstrap on the application class instead.","userAgent":"Mozilla/5.0 (Windows NT 10.0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/86.0.4240.75 Safari/537.36","version":"20.0.0.9"}

**Comment by pkmkrishnakumar** [comment]
Is there any issue regarding NC running behind a proxy , causes such errors?

**Comment by anpattividana** [comment]
I have same the same issue. Because invalid duplicate E-mail account will be crated automatically in **_oc_mail_accounts_** table.
I don't know why this happened but the only difference is the 2 password strings and _**provisioned**_ fields
When I remove this invalid entry from the table, the widget will be working. But after few seconds, It will make another duplicate account and the mail widget will be not working again,

Other thing is its beater to show New email status on Dashboard rather than Important E-mails because they should be select manually.

**Comment by ChristophWurst** [comment]
> The following error is being filled in the nextcloud log for most of the apps. It logs continuously and fills the log file with in couple of minutes to 100 MB .

How many users are on that instance?

**Comment by pkmkrishnakumar** [comment]
80 active users as of now.

**Comment by ChristophWurst** [comment]
@pkmkrishnakumar the entries you posted from the logs are all DEBUG and INFO. So not really pointing to anything one could call an error.

**Comment by BernhardGehl** [comment]
@ChristophWurst: Keeping the nextcloud.log open in tail -f while reloading the dashboard, I get the following bunch of messages (I think I caught them all...):

{"file":"/var/www/html/custom_apps/mail/lib/IMAP/FolderMapper.php","line":60,"function":"listMailboxes","class":"Horde_Imap_Client_Base","type":"->","args":["*",5,{"delimiter":true,"attributes":true,"special_use":true}]},  
{"file":"/var/www/html/custom_apps/mail/lib/IMAP/MailboxSync.php","line":103,"function":"getFolders","class":"OCA\\Mail\\IMAP\\FolderMapper","type":"->","args":[{"__class__":"OCA\\Mail\\Account"},{"cacheFields":{"9":"HICenv","10":"HICflags","8":"HIChdrs","11":"HICdate","12":"HICsize","1":"HICstruct"},"changed":true,"statuscache":true,"__class__":"Horde_Imap_Client_Socket"}]},
{"file":"/var/www/html/custom_apps/mail/lib/Service/MailManager.php","line":127,"function":"sync","class":"OCA\\Mail\\IMAP\\MailboxSync","type":"->","args":[{"__class__":"OCA\\Mail\\Account"},{"__class__":"OC\\AppFramework\\ScopedPsrLogger"}]},
{"file":"/var/www/html/custom_apps/mail/lib/Controller/MailboxesController.php","line":92,"function":"getMailboxes","class":"OCA\\Mail\\Service\\MailManager","type":"->","args":[{"__class__":"OCA\\Mail\\Account"}]},
{"file":"/var/www/html/lib/private/AppFramework/Http/Dispatcher.php","line":169,"function":"index","class":"OCA\\Mail\\Controller\\MailboxesController","type":"->","args":[4]},
{"file":"/var/www/html/lib/private/AppFramework/Http/Dispatcher.php","line":100,"function":"executeController","class":"OC\\AppFramework\\Http\\Dispatcher","type":"->","args":[{"__class__":"OCA\\Mail\\Controller\\MailboxesController"},"index"]},
{"file":"/var/www/html/lib/private/AppFramework/App.php","line":152,"function":"dispatch","class":"OC\\AppFramework\\Http\\Dispatcher","type":"->","args":[{"__class__":"OCA\\Mail\\Controller\\MailboxesController"},"index"]},
{"file":"/var/www/html/lib/private/Route/Router.php","line":308,"function":"main","class":"OC\\AppFramework\\App","type":"::","args":["OCA\\Mail\\Controller\\MailboxesController","index",{"__class__":"OC\\AppFramework\\DependencyInjection\\DIContainer"},{"action":null,"_route":"mail.mailboxes.index"}]},
{"file":"/var/www/html/lib/base.php","line":1009,"function":"match","class":"OC\\Route\\Router","type":"->","args":["/apps/mail/api/mailboxes"]},
{"file":"/var/www/html/index.php","line":37,"function":"handleRequest","class":"OC","type":"::","args":[]}],"File":"/var/www/html/custom_apps/mail/vendor/pear-pear.horde.org/Horde_Imap_Client/Horde/Imap/Client/Socket.php","Line":5030},"CustomMessage":"IMAP error: Authentication failed."},"userAgent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/86.0.4240.183 Safari/537.36","version":"20.0.1.1"}

As with @pkmkrishnakumar, my browser shows Error Code 500 for something mailbox related - but in my case it's showing three of them (even though I only have one mailaccount set up for my user):
![image](https://user-images.githubusercontent.com/26908028/98864541-59672f80-246a-11eb-9178-238c222331b8.png)

* Fun observation: What happened to account Nr 2? ;-)
* Hopefully helpful observation: Previously I had three other mail-accounts on my Nextcloud of which one at some point malfunctioned - I can't really remember why. I then removed and re-configured it... could that be the source of the issue?

Is there a way to safely purge the mail app's config?

**Comment by ChristophWurst** [comment]
@BernhardGehl did you truncate the log line? I don't see the `message`.

**Comment by ChristophWurst** [comment]
> Hopefully helpful observation: Previously I had three other mail-accounts on my Nextcloud of which one at some point malfunctioned - I can't really remember why. I then removed and re-configured it... could that be the source of the issue?

That is where you lost ID 2. The database auto increment will always only increment. Gaps won't be filled.

**Comment by BernhardGehl** [comment]
> @BernhardGehl did you truncate the log line? I don't see the `message`.

Sorry - my bad: Messed it up between copy from log and paste to Github.
--> repeated and pasted (this time via VSCode)

[mail_dashbord_500s.log](https://github.com/nextcloud/mail/files/5529206/mail_dashbord_500s.log)

Better now? (The message seems to be an IMAP auth fail.)

**Comment by BernhardGehl** [comment]
> > Hopefully helpful observation: Previously I had three other mail-accounts on my Nextcloud of which one at some point malfunctioned - I can't really remember why. I then removed and re-configured it... could that be the source of the issue?
> 
> That is where you lost ID 2. The database auto increment will always only increment. Gaps won't be filled.

Understood. It's just that right now, I only have 1 account for my user in the app. I'd completely understand if the messages were talking about account #4 only - but the references to 1 and 3 look suspicious to me.

Side Note: The other users on the server don't have the issue. For them, the widget is working fine.

**Comment by ChristophWurst** [comment]
> Better now? (The message seems to be an IMAP auth fail.)

Yes: ``"Exception":"Horde_Imap_Client_Exception","Message":"Authentication failed."``.

Does that account actually work when you open the Mail app?

> I only have 1 account for my user in the app

Double-check the `oc_mail_accounts` table for the rows with your `user_id`.

**Comment by BernhardGehl** [comment]
> Does that account actually work when you open the Mail app?
> [...]
> Double-check the `oc_mail_accounts` table for the rows with your `user_id`.

Okay, typically I'm a bit reluctant to mess with the Nextcloud db tables, to avoid me accidentally breaking things. But `SELECT * FROM oc_mail_accounts WHERE user_id='<myuserid>';'` gave me four accounts:
* Accounts id 1, 3 and 4 refer to a gmail account. They are not visible in the mail app. I was using the account on the mail app some time ago but switched to my "own" server since. Noticing the obvious: These are the accounts, I get the error messages from.
* Account 11 looks like my regular mail account. This is where I don't get an error message.

If I may guess, the widget stumbles across these orphaned accounts in the mail app. The question is:
* How did they happen?  (I don't know)
* Should the mail widget be able to handle this exception? (I'd not insist...)
* How can I safely remove the orphan accounts from my config? (Please!)

If the issue is not restricted to my config (could someone else affected by the issue please check?), could someone maybe put a cleanup into the 'occ' command - either as a component for maintenance:repair or something mail:*-specific ?

**Comment by BernhardGehl** [comment]
Ha! #3135 comes pretty close to describing what happened: The three gmail accounts could very well be leftovers from my early configurations testing the mail app with adding/removing user accounts and/or the whole app - before the fix in v1.3.5.. 
--> Probable root cause found

Now I just need the safe cleanup procedure...

**Comment by BernhardGehl** [comment]
@ChristophWurst Is it safe to just delete the orphaned accounts using something like `DELETE FORM oc_mail_accounts WHERE id=1`? Should I look into other tables as well? Is there documentation so I can "rtfm"?

**Comment by ChristophWurst** [comment]
you can drop that row and the app will later automatically clean all related data

**Comment by BernhardGehl** [comment]
... aaaaand the mail widget is showing the mails from the remaining account!

@ChristophWurst Thank you! :-)

**Comment by ChristophWurst** [comment]
I guess we could have some code that checks for remnants, but it's expensive an needs to load each user from the user back-end. Mind opening a feature request for this? Thanks :v:
