### ISSUE TITLE
Failed connecting self hosted mail server by Roundcube webmail 

### ISSUE THREAD

**Issue by kamalaesh-uk** [nextcloud/mail#3821]
### Expected behavior
Manually connect/Sync an existing E-Mail account

### Actual behavior
'Fatal: Creating account failed: Error connecting to SMTP server'
Same error appears for all SMTP-Security options
We used the same E-mail server settings as thunderbird
### Mail app
**Mail app version:** (see apps admin page, e.g. 0.5.3)
1.4.1

**Mailserver or service:** (e.g. Outlook, Yahoo, Gmail, Exchange,...)
self hosted by Roundcube webmail
SMTP Server- Postfix
IMAP/POP3 Server- Dovecot

### Server configuration
**Operating system**: (e.g. Debian 8)
Linux 3.10.0-042stab141.3 x86_64
CentOS Linux 7.8.2003

**Web server:** (e.g. Apache, Nginx,...)
Plesk Obsidian Version 18.0.30
nginx

**Database:** (e.g. MariaDB, SQLite or PostgreSQL)
MariaDB 10.2.34

**PHP version:** (e.g. 7.0)
7.4.11 FPM

**Nextcloud Version:** (see admin page, e.g. 13.0.2)
19.0.4

#### Client configuration
**Browser:** (e.g. Firefox 48)
Chrome and edge

**Operating system:** (e.g. Arch Linux)
Windows 10

**Comment by ChristophWurst** [comment]
> self hosted by Roundcube webmail

With a valid TLS vertificate or not? See also https://github.com/nextcloud/mail/blob/master/doc/admin.md#disable-tls-verification-for-imapsmtp

**Comment by kamalaesh-uk** [comment]
We used 'Let's Encrypt' certificate and we also used 'app.mail.verify-tls-peer' => false' in config.php file

**Comment by ChristophWurst** [comment]
And then? Does it still not work?

**Comment by kamalaesh-uk** [comment]
No, it did not still work. An the same error appears aslo in the basic settings of nextcloud. It works with encryption 'none' and port '25' but not with encryption and port '465'

A problem occurred while sending the email. Please revise your settings. (Error: Connection could not be established with host <Domain> :stream_socket_client(): SSL operation failed with code 1. OpenSSL Error messages: error:14090086:SSL routines:ssl3_get_server_certificate:certificate verify failed)

**Comment by ChristophWurst** [comment]
> A problem occurred while sending the email. Please revise your settings. (Error: Connection could not be established with host :stream_socket_client(): SSL operation failed with code 1. OpenSSL Error messages: error:14090086:SSL routines:ssl3_get_server_certificate:certificate verify failed)

But that sounds like a problem with your SSL setup?

Do you use TLSv1.3?

**Comment by kamalaesh-uk** [comment]
We used 'Let's Encrypt' via Plesk integration with the following settings as attched
[Let's encrypt settings.txt](https://github.com/nextcloud/mail/files/5386012/Let.s.encrypt.settings.txt)

**Comment by ChristophWurst** [comment]
I'm not an expert with that but

> "tls_versions": ["TLSv1.3"],

sounds like it might require v1.3 and is a problem righ tnow: https://github.com/horde/Socket_Client/pull/4

**Comment by kamalaesh-uk** [comment]
We tested the SSl protocol with 'SSl check' and it shows that TLS 1.2 is offered and TLS 1.3 is 'offered with final'
