### ISSUE TITLE
"Reply All" is case sensitive

### ISSUE THREAD

**Issue by StCyr** [nextcloud/mail#3822]
### Expected behavior
When "Reply All" function is used, it should remove my e-mail address from the list of email addresses to reply to, regardless of the email address' case.

### Actual behavior
"Reply All" function doesn't remove my e-mail address when case is not the same (ie: "Cyrille[at]bollu.be" is regarded not the same as "cyrille[at]bollu.be)

### Mail app

**Mail app version:** master

**Comment by StCyr** [comment]
Yes yes email addresses are case insensitive

**Comment by StCyr** [comment]
Damned the local part of an email address is case sensitive 😲 !

This is the end of a 15 years belief for me 😞

**Comment by ChristophWurst** [comment]
so … close? :)

**Comment by StCyr** [comment]
Yes, I guess.
