### ISSUE TITLE
Can't add aliases API replies with status code 302

### ISSUE THREAD

**Issue by ntimo** [nextcloud/mail#3823]
### Expected behavior
It should be possible to add an alias.

### Actual behavior
When adding alias for an account the alias is is not added and the web api (https://nextcloudserver.com/apps/mail/api/aliases) returns a 302 with a redirect to the dashboard. 

### Mail app

**Mail app version:** 1.5.0

**Mailserver or service:** mailcow

### Server configuration

**Operating system**: docker image nextcloud:20.0.0-apache

**Web server:** Apache

**Database:** mariadb

**Nextcloud Version:** 20.0.0

#### Client configuration
**Browser:** Chrome 86.0.4240.75 (Official Build) (x86_64)

**Operating system:** macOS

**Comment by ChristophWurst** [comment]
Fixed by https://github.com/nextcloud/mail/pull/3761
