### ISSUE TITLE
Message body not properly formatted when forwarding emails

### ISSUE THREAD

**Issue by StCyr** [nextcloud/mail#3824]
### Expected behavior
When forwarding an email, the body of the message should contain the original message separated from the new message (yet to be  written) by a line, usualy in the form "On <data>, <original sender> wrote:".

### Actual behavior
When forwarding emails, the body of the message is just a plain copy of the original message. 

### Mail app

**Mail app version:** master (1.5)

**Comment by ChristophWurst** [comment]
As explained before this is a limitation of the editor. It will discard anything it can't deal with. Hence the simplified formatting. As soon as the editor can cope with more complex HTML, the forwarded message will come closer to the original.

**Comment by StCyr** [comment]
> As explained before this is a limitation of the editor. It will discard anything it can't deal with. Hence the simplified formatting. As soon as the editor can cope with more complex HTML, the forwarded message will come closer to the original.

No, no, that discussion is not related to this issue.

The issue here is that this line isn't called when I forward a message:

https://github.com/nextcloud/mail/blob/b8867af8217da5c95a002c500150b1b39c126a6a/src/components/Composer.vue#L473

**Comment by ChristophWurst** [comment]
I'm very sorry that I misunderstood the issue.
