### ISSUE TITLE
Regular user can get list of all users in Nextcloud in dropdown field "To"

### ISSUE THREAD

**Issue by krakazyabra** [nextcloud/mail#3826]
### Expected behavior
Regular user should see only members of his Nextcloud's group or his contact list

### Actual behavior
When starts to type first characters of receiver, appears the list will users, which are not in user's group or contact list. Try to type `.com` (or .de, .ru, .cz, your preferred domain) in field "To" and you will get ALL users of Nextcloud. This is _HUGE_ security hole.

 
### Mail app

**Mail app version:** (see apps admin page, e.g. 0.5.3)
1.4.1
**Mailserver or service:** (e.g. Outlook, Yahoo, Gmail, Exchange,...)
doesn't matter

### Server configuration

**Operating system**: (e.g. Debian 8)
Debian 10
**Web server:** (e.g. Apache, Nginx,...)
nginx+php-fpm
**Database:** (e.g. MariaDB, SQLite or PostgreSQL)
Percona
**PHP version:** (e.g. 7.0)
7.4.10
**Nextcloud Version:** (see admin page, e.g. 13.0.2)
19.0.1

**Comment by ChristophWurst** [comment]
> This is _HUGE_ security hole.

First of all congrats on reporting this publicly.

On a more serious note you can disable sharing user enumeration. This should fix it.

**Comment by krakazyabra** [comment]
>First of all congrats on reporting this publicly.

I followed the instruction :)

![image](https://user-images.githubusercontent.com/26598203/96260136-e24f9000-0fbe-11eb-97b8-f9de63d4ccd7.png)


>disable sharing user enumeration

Did you mean this?  
![image](https://user-images.githubusercontent.com/26598203/96260377-3d818280-0fbf-11eb-9c41-74a2b31af639.png)

**Comment by krakazyabra** [comment]
>you can disable sharing user enumeration

If you mean to disable it globally - we can't do it. Yes, it will solve the issue, but will disable one of the main features - enumeration inside group.

**Comment by ChristophWurst** [comment]
A security issue is not a bug, though.

In any case. This is the only way to fix this right now. The groups enumeration is not supported at the moment.

**Comment by krakazyabra** [comment]
>A security issue is not a bug, though.

Sorry, I don't know where report this problem. You can delete the issue, if you want. 

>The groups enumeration is not supported at the moment

That's sad. But nothing else to do.

**Comment by ChristophWurst** [comment]
> If you have discovered a security issue with Nextcloud, please read our responsible disclosure guidelines and contact us at hackerone.com/nextcloud
