### ISSUE TITLE
Signature in Mail not saved - no errors/warnings

### ISSUE THREAD

**Issue by Nick-Git2** [nextcloud/mail#3829]
### Expected behavior
After entering a signature and pressing "Save Signature" it should be stored and used for newly composed e-mails.

### Actual behavior
pressing "Save signature" does not result in storage of the signature in the database:
| signature | last_mailbox_sync | editor_mode
| | 1602850502 | plaintext |

"Save signature" button remains "pressed" until any further user action is carried out
![Bildschirmfoto zu 2020-10-16 14-12-46](https://user-images.githubusercontent.com/65270786/96303601-f5805100-0ffa-11eb-8972-d1ecf0a41a27.png)

no error or warnings are given
XHRPUThttps://XXXXX/nextcloud/index.php/apps/mail/api/accounts/2/signature
[HTTP/2 200 OK 94ms]
XHRPOSThttps://XXXXX/nextcloud/index.php/apps/mail/api/mailboxes/13/sync
[HTTP/2 200 OK 665ms]

### Mail app

**Mail app version:** (see apps admin page, e.g. 0.5.3)
1.5.0

**Mailserver or service:** (e.g. Outlook, Yahoo, Gmail, Exchange,...)
mail.sprit.org

### Server configuration

**Operating system**: (e.g. Debian 8)
Linux debian 4.19.0-11-amd64 #1 SMP Debian 4.19.146-1 (2020-09-17) x86_64 GNU/Linux

**Web server:** (e.g. Apache, Nginx,...)
Apache/2.4.38 (Debian)

**Database:** (e.g. MariaDB, SQLite or PostgreSQL)
10.3.23-MariaDB-0+deb10u1 Debian 10

**PHP version:** (e.g. 7.0)
7.3.19-1~deb10u1

**Nextcloud Version:** (see admin page, e.g. 13.0.2)
20.0.0

#### Client configuration
**Browser:** (e.g. Firefox 48)
FireFox 81 (64bit)

**Operating system:** (e.g. Arch Linux)
Ubuntu Linux odroid 4.9.236-97 #1 SMP PREEMPT Tue Sep 15 15:01:17 UTC 2020 aarch64 aarch64 aarch64 GNU/Linux

**Comment by BelmontCloud** [comment]
this identical signature issue still exists in v1.5.1. 
I noticed that its resolution has been relocated to future release v1.5.2.

**Comment by ChristophWurst** [comment]
That is correct.

**Comment by dumblob** [comment]
Just raising my hand here to show we're also interested in working signatures. Any temporary workarounds (e.g. manual DB changes...)?

**Comment by ChristophWurst** [comment]
Are you a developer?

**Comment by dumblob** [comment]
I'm an administrator of NC server for me and few friends. I'm unfortunately no developer, but I know some bits of SQL.
