### ISSUE TITLE
Error when selecting a file from computer as attachment

### ISSUE THREAD

**Issue by nickvergessen** [nextcloud/mail#3841]
### Expected behavior
Email sends with attachment

### Actual behavior
"Error 500"

`{"reqId":"KF7Jg5CVWZWQoCEE6MYB","level":3,"time":"2020-10-18T20:17:13+02:00","remoteAddr":"92.xxx","user":"xxx","app":"PHP","method":"POST","url":"/index.php/apps/mail/api/accounts/1/send","message":{"Exception":"Error","Message":"Trying to access array offset on value of type int at /var/www/nextcloud/lib/private/Files/Node/Node.php#328","Code":0,"Trace":[{"file":"/var/www/nextcloud/lib/private/Files/Node/Node.php","line":328,"function":"onError","class":"OC\\Log\\ErrorHandler","type":"::"},{"file":"/var/www/nextcloud/lib/private/Files/Node/Folder.php","line":62,"function":"isValidPath","class":"OC\\Files\\Node\\Node","type":"->"},{"file":"/var/www/nextcloud/lib/private/Files/Node/Folder.php","line":140,"function":"getFullPath","class":"OC\\Files\\Node\\Folder","type":"->"},{"file":"/var/www/nextcloud/lib/private/Files/SimpleFS/SimpleFolder.php","line":76,"function":"get","class":"OC\\Files\\Node\\Folder","type":"->"},{"file":"/var/www/nextcloud/apps_custom/mail/lib/Service/Attachment/AttachmentStorage.php","line":105,"function":"getFile","class":"OC\\Files\\SimpleFS\\SimpleFolder","type":"->"},{"file":"/var/www/nextcloud/apps_custom/mail/lib/Service/Attachment/AttachmentService.php","line":83,"function":"retrieve","class":"OCA\\Mail\\Service\\Attachment\\AttachmentStorage","type":"->"},{"file":"/var/www/nextcloud/apps_custom/mail/lib/Service/MailTransmission.php","line":301,"function":"getAttachment","class":"OCA\\Mail\\Service\\Attachment\\AttachmentService","type":"->"},{"file":"/var/www/nextcloud/apps_custom/mail/lib/Service/MailTransmission.php","line":278,"function":"handleLocalAttachment","class":"OCA\\Mail\\Service\\MailTransmission","type":"->"},{"file":"/var/www/nextcloud/apps_custom/mail/lib/Service/MailTransmission.php","line":126,"function":"handleAttachments","class":"OCA\\Mail\\Service\\MailTransmission","type":"->"},{"file":"/var/www/nextcloud/apps_custom/mail/lib/Controller/AccountsController.php","line":397,"function":"sendMessage","class":"OCA\\Mail\\Service\\MailTransmission","type":"->"},{"file":"/var/www/nextcloud/lib/private/AppFramework/Http/Dispatcher.php","line":169,"function":"send","class":"OCA\\Mail\\Controller\\AccountsController","type":"->"},{"file":"/var/www/nextcloud/lib/private/AppFramework/Http/Dispatcher.php","line":100,"function":"executeController","class":"OC\\AppFramework\\Http\\Dispatcher","type":"->"},{"file":"/var/www/nextcloud/lib/private/AppFramework/App.php","line":152,"function":"dispatch","class":"OC\\AppFramework\\Http\\Dispatcher","type":"->"},{"file":"/var/www/nextcloud/lib/private/Route/Router.php","line":308,"function":"main","class":"OC\\AppFramework\\App","type":"::"},{"file":"/var/www/nextcloud/lib/base.php","line":1009,"function":"match","class":"OC\\Route\\Router","type":"->"},{"file":"/var/www/nextcloud/index.php","line":37,"function":"handleRequest","class":"OC","type":"::"}],"File":"/var/www/nextcloud/lib/private/Log/ErrorHandler.php","Line":91,"CustomMessage":"--"},"userAgent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:82.0) Gecko/20100101 Firefox/82.0","version":"20.0.0.9","id":"5f8c885f7afc2"}`

### Mail app

**Mail app version:** 1.5.0

### Server configuration

**Operating system**: Ubuntu 18.04

**Web server:** Apache 2.4.x

**Database:** MySQL 8.0.x

**PHP version:** 7.4

**Nextcloud Version:** 20.0.0

**Comment by StCyr** [comment]
Can you reproduce this issue?

**Comment by nickvergessen** [comment]
Sorry for missing the reply. Seems it works now, but also performed a couple of updates (19 > 20, etc) in the meantime.

**Comment by StCyr** [comment]
re-closing the issue as user confirmed it is solved
