### ISSUE TITLE
no mailbox sync

### ISSUE THREAD

**Issue by JensKillermann** [nextcloud/mail#3847]
I have a problem with the version 1.5.0. The mail app doesn't sync mailaccount in background. An interaction as user (reload page) is needed. In the previews version this wasn't this way. I had an sync in background.

In the database there is a column last_mailbox_snc. The time isn't updated, so I think there is no background update job working.

Is there a flag or paramter to update the background sync a and/or interval?

I use mail app 1.5.0
NC 20.0.0.9

**Comment by ChristophWurst** [comment]
> Please ask your question in the community forum at https://help.nextcloud.com/c/apps/mail
> The Github issue tracker shall only be used for actual bugs

Forgot your :coffee:? :wink: 

Let's put this on https://help.nextcloud.com/ :v:
