### ISSUE TITLE
Cannot save several attachments to File

### ISSUE THREAD

**Issue by StCyr** [nextcloud/mail#3859]
### Expected behavior
When you have an email with several attachments, there's a button "Save all to File". Clicking on this button should save all attachments to the selected location.

### Actual behavior
Attachments are not saved.

### Mail app

**Mail app version:** master (1.5)

### Server configuration

**Nextcloud Version:** 20.0.0

#### Client configuration
**Browser:** FF latest

**Comment by ChristophWurst** [comment]
check the network log and nextcloud.log. any errors?
