### ISSUE TITLE
CSS is shown as txt reply

### ISSUE THREAD

**Issue by tamburra** [nextcloud/mail#3863]
### Expected behavior
When clicking reply to a message, css is then imported into the reply as text on screen.  This shouldn't be.  You do not see any of this when forwarding the message.

### Actual behavior
When clicking reply to a message, css is then imported into the reply as text on screen.

### Mail app
**Mail app version:1.5.0

### Server configuration
**Operating system: Debain 10
**Web server: Nginx
**Database: Mariadb
**PHP version: 7.0
**Nextcloud Version: 20.0.0

<img width="742" alt="Screen Shot 2020-10-21 at 1 25 58 PM" src="https://user-images.githubusercontent.com/16267805/96756397-0be32f80-13a2-11eb-9af4-72481bba19ca.png">

**Comment by ChristophWurst** [comment]
It's because the app tries to convert the HTML message into text. But it doesn't do a very good job …

**Comment by tamburra** [comment]
Thanks for the reply.  Happy to see this app getting developed.
