### ISSUE TITLE
Cronjob exhausts memory because of apps/mail/lib/IMAP/Threading/Container.php 

### ISSUE THREAD

**Issue by vasyugan** [nextcloud/mail#3869]
### Expected behavior
cron should finish without error. The memory_limit in /etc/php/7.4/cli/php.ini is 4096m, so this should be plenty.

### Actual behavior
Two times per day, the cronjob gets killed because of exhausting memory. Before I set a memory_limit, I just saw that php was getting killed by the kernel and that nextcloud was down for several minutes. Then, I did set a memory limit and so I started getting the following message twice a day:
```
PHP Fatal error:  Allowed memory size of 4294967296 bytes exhausted (tried to allocate 262144 bytes) in /var/www/****/cloud.****/apps/mail/lib/IMAP/Threading/Container.php on line 111
PHP Fatal error:  Allowed memory size of 4294967296 bytes exhausted (tried to allocate 262144 bytes) in Unknown on line 0

```

### Mail app

**Mail app version:** 1.5.0

**Mailserver or service:** self-hosted dovecot

### Server configuration

**Operating system**: Ubuntu 20.04

**Web server:** Nginx

**Database:** MariaDB

**PHP version:** 7.4

**Nextcloud Version:** 20.0.0

#### Client configuration

(doesn't apply here)
**Operating system:** (e.g. Arch Linux)

**Comment by ChristophWurst** [comment]
Please run ``occ mail:account:diagnose <accountId>`` for the account ID of that cron job.

**Comment by ChristophWurst** [comment]
And because it's related to threading you could export the account's threading data with ``occ mail:account:export-threads --redact <accountId>`` if you want to share that. All the info is redacted. You would only leak your number of emails and how those are related on an abstract level without any real IDs or anything.

**Comment by vasyugan** [comment]
https://gist.github.com/vasyugan/5b2200d8d9cd554d8f787814ba72a061

**Comment by vasyugan** [comment]
> Please run `occ mail:account:diagnose <accountId>` for the account ID of that cron job.
```

IMAP capabilities:
- AUTH
- ENABLE
- ID
- IDLE
- IMAP4REV1
- LITERAL+
- LOGIN-REFERRALS
- SASL-IR

Horde error occurred: IMAP error reported by server.. See nextcloud.log for more details.

```

**Comment by ChristophWurst** [comment]
> https://gist.github.com/vasyugan/5b2200d8d9cd554d8f787814ba72a061

I can build the threads just fine with only 24MB

```
php occ mail:thread /tmp/mailid.log 
6944 threads built from 8076 messages
24MB of memory used
```

can you reproduce this?

**Comment by ChristophWurst** [comment]
https://github.com/nextcloud/mail/pull/3871 is required, otherwise that command will fill the log with LOTS of errors.

**Comment by vasyugan** [comment]
> php occ mail:thread /tmp/mailid.log
Yes, same output, only that  it doesn't reveal the amount of memory used, but it finishes without error.

**Comment by ChristophWurst** [comment]
Okay … so it's not the threading. But just that at the point of threading the mem is used by something else.

> Horde error occurred: IMAP error reported by server.. See nextcloud.log for more details.

That was because of one of the other bugs you reported, right?

**Comment by ChristophWurst** [comment]
You can also try just the sync (which includes threading) with ``occ mail:account:sync <accountId>`` in the hope that the problematic mailbox or message is not marked for background sync and thus the process hopefully works.

**Comment by vasyugan** [comment]
> Okay … so it's not the threading. But just that at the point of threading the mem is used by something else.
> 
> > Horde error occurred: IMAP error reported by server.. See nextcloud.log for more details.
> 
> That was because of one of the other bugs you reported, right?

Don't think so.  Because re the other bugs, I have moved the offending message to another place, so that the bug no longer occurs, but the gist is that it can't get the account stats from dovecot, and that's probably because I haven't enabled the stats module in dovecot. I guess this is immaterial to the issue at hand.

**Comment by vasyugan** [comment]
> You can also try just the sync (which includes threading) with `occ mail:account:sync <accountId>` in the hope that the problematic mailbox or message is not marked for background sync and thus the process hopefully works.

Well, that's how I identified the offending mail account, because this threw an error. But weirdly, this time it finished without error. Which, I guess, makes tracing the cause of this bug more difficult. Let's see if I get more error mails  from cron...

**Comment by ChristophWurst** [comment]
I see. Running out of memory is hard to trace but maybe you can find a pattern.

There is also the chance that another job runs before that Mail background sync and consumes most of the memory, then Mail does its job and reaches the limit.

**Comment by vasyugan** [comment]
> I see. Running out of memory is hard to trace but maybe you can find a pattern.
> 
> There is also the chance that another job runs before that Mail background sync and consumes most of the memory, then Mail does its job and reaches the limit.
The first time I ran sync for the account manually, it actually did run out of the memory that I had given it (4 gigs!!) and it did so quickly. So this script had caused the memory exhaustion running standalone.

**Comment by ChristophWurst** [comment]
Good to know!

Could you maybe try running the sync in a loop a few times to see if it eventually shows up again?

Are you using the latest version of php? Just in case there's a bug on that level.

**Comment by vasyugan** [comment]
> Good to know!
> 
> Could you maybe try running the sync in a loop a few times to see if it eventually shows up again?
> 
> Are you using the latest version of php? Just in case there's a bug on that level.

PHP 7.4 FPM on Ubuntu 20.04

**Comment by vasyugan** [comment]
So this time, I have been able to reproduce the memory exhaustion with a different account (a GMail account). The trick is apparently  to append -f after sync in order to reproduce what happens during those cron jobs:

```
[debug] Account 50 has 64010 messages for threading
PHP Fatal error:  Allowed memory size of 4294967296 bytes exhausted (tried to allocate 262144 bytes) in /var/www/htdocs/cloud.****/apps/mail/lib/IMAP/Threading/Container.php on line 111

```

**Comment by ChristophWurst** [comment]
Thanks. I can't reproduce the mem exhaustion because the provided threading data triggers an infinite recursion for me

```
php occ mail:thread ~/Downloads/mail-threads.log 
An unhandled exception has been thrown:
Error: Maximum function nesting level of '256' reached, aborting! in /home/christoph/workspace/nextcloud/apps/mail/lib/IMAP/Threading/Container.php:106
```

**Comment by vasyugan** [comment]
> Thanks. I can't reproduce the mem exhaustion because the provided threading data triggers an infinite recursion for me
> 
> ```
> php occ mail:thread ~/Downloads/mail-threads.log 
> An unhandled exception has been thrown:
> Error: Maximum function nesting level of '256' reached, aborting! in /home/christoph/workspace/nextcloud/apps/mail/lib/IMAP/Threading/Container.php:106
> ```

To get to a memory exhaustion, you first have to set a memory limit. The default memory limit for the php cli on Debian and Ubuntu is -1, that is, there is no limit, see /etc/php/7.?/cli/php.ini

**Comment by ChristophWurst** [comment]
I attached a debugger and it peaks at 110MB memory used

**Comment by eleith** [comment]
i am seeing this error when running `occ mail:account:sync <accound_id>` i have 140k messages.

**Comment by ChristophWurst** [comment]
@eleith I've only tried with accounts of ~80k messages. So please see https://github.com/nextcloud/mail/blob/master/doc/admin.md#export-threading-data and if you provide us with this redacted data we can see if this is reproducible. Please also tell us at how many bytes the memory was exhausted.

**Comment by eleith** [comment]
`occ mail:account:sync <account-id>`

ends with the following error

```
PHP Fatal error:  Allowed memory size of 536870912 bytes exhausted 
(tried to allocate 262144 bytes) 
in /var/www/html/apps/mail/lib/IMAP/Threading/Container.php 
on line 111
```

and 

`occ mail:account:export-threads --redact <account-id>`

produces a 50+ Mb file using 

however, it's too large to upload to github, but i can upload it elsewhere or provide you a link privately. let me know your preference, if you still want the file.

**Comment by ChristophWurst** [comment]
> `occ mail:account:sync <account-id>`
> 
> ends with the following error

What's the rest of the output? E.g. it should show how many emails are there for threading. Please post that output here, it shouldn't contain any sensitive data except number of emails.

> produces a 50+ Mb file
> 
> however, it's too large to upload to github, but i can upload it elsewhere or provide you a link privately. let me know your preference, if you still want the file.

Yes please put it into a compressed archive and send me a link to the email you can find in [license headers](https://github.com/nextcloud/mail/blob/master/lib/Command/CleanUp.php).

**Comment by eleith** [comment]
```
./occ mail:account:sync <account-id>
[debug] account is up to date, skipping mailbox sync
[debug] Skipping mailbox sync for Archive
[debug] Skipping mailbox sync for Drafts
[debug] partial sync <account-id>:INBOX - get all known UIDs took 1s
[debug] partial sync <account-id>:INBOX - get new messages via Horde took 1s
[debug] partial sync <account-id>:INBOX - persist new messages took 0s
[debug] partial sync <account-id>:INBOX - get changed messages via Horde took 0s
[debug] partial sync <account-id>:INBOX - persist changed messages took 0s
[debug] partial sync <account-id>:INBOX - get vanished messages via Horde took 0s
[debug] partial sync <account-id>:INBOX - persist new messages took 0s
[debug] partial sync <account-id>:INBOX took 2s
[debug] Skipping mailbox sync for Junk
[debug] Skipping mailbox sync for Sent
[debug] Skipping mailbox sync for Trash
[debug] Account <account-id> has 142578 messages for threading
PHP Fatal error:  Allowed memory size of 536870912 bytes exhausted (tried to allocate 262144 bytes) in /var/www/html/apps/mail/lib/IMAP/Threading/Container.php on line 111
```

**Comment by ChristophWurst** [comment]
Thanks a lot. While I don't run out of memory (~280MB used with xdebug enabled) I get an infinite recursion.

What raises my suspicious is that your exported data contains ~140k messages. Does that seem right? Could you also run `occ mail:account:diagnose` for that account?

**Comment by eleith** [comment]
```
./occ mail:account:diagnose 4
IMAP capabilities:
- AUTH
- IMAP4
- IMAP4REV1
- UIDPLUS

Account has 155026 messages in 7 mailboxes
```

**Comment by ChristophWurst** [comment]
Ah right that is also what you put into your other reply. Then the data seems right.

Do you also run into out of memory issues when you thread the exported data? E.g. with `occ  mail:thread export.json`?

**Comment by eleith** [comment]
@ChristophWurst i do run out of memory, here is the output

```
php occ mail:thread email.json 
PHP Fatal error:  Allowed memory size of 536870912 bytes exhausted (tried to allocate 262144 bytes) in /var/www/html/apps/mail/lib/IMAP/Threading/Container.php on line 111
PHP Fatal error:  Allowed memory size of 536870912 bytes exhausted (tried to allocate 262144 bytes) in Unknown on line 0
```

**Comment by nkinkade** [comment]
I'm seeing something similar to @eleith. I'm running NC 20.0.2 and Mail 1.7.1 on an updated Debian 10 VM running dovecot 2.3.4.1. 

```
# php occ mail:account:diagnose -- 1
IMAP capabilities:
- AUTH
- ENABLE
- ID
- IDLE
- IMAP4REV1
- LITERAL+
- LOGIN-REFERRALS
- SASL-IR

Account has 170155 messages in 26 mailboxes
```

If I try to run `./occ mail:account:sync --force -- 1`, within seconds the OS invokes the oom-killer and kills apache2. This was with me setting the php-cli memory limit to `-1` to see what would happen. When not set to `-1`, you get the same PHP fatal errors that have been posted about "Allowed memory size exhausted".

**Comment by ksteinb** [comment]
Same problem on some (not all) of the cron  runs. Too bad the error message did not tell me with which account it will happen.

Environment:

NC 20.02 on Scientific Linux 7.9 (same as CentOS 7.9)
rh-php72-php-7.2.24

Mailserver : Dovecot 2.3.11
around 5000 Users, 5.7 TByte of Mailstorage

**Comment by jens-maus** [comment]
Since update to NC 20 (20.0.4) I do have the same issue with my nextcloud cronjob regularly returning `Allowed memory size exhausted` error messages. I use the Mail Addon version 1.7.2 here. After some investigation, I identified one account for which nextcloud seem to try to allocate more than the 4GB maximum it was assigned for php-cli. See:

```
# sudo -u nginx php ./occ mail:account:sync -- 1
[...]
[debug] Account 1 has 42129 messages for threading
PHP Fatal error:  Allowed memory size of 4294967296 bytes exhausted (tried to allocate 262144 bytes) in /var/www/localhost/htdocs/owncloud/apps/mail/lib/IMAP/Threading/Container.php on line 111
```

Another account just finishes fine without any issues. So has there been any progress in investigating this issue and identifying a solution or workaround for that issue? With older NC19 I didn't have such issues, btw.

**Comment by alexhass** [comment]
I have the same issue with v20.0.4 and Mailapp 1.7.2. 

`
PHP Fatal error:  Allowed memory size of 536870912 bytes exhausted (tried to allocate 262144 bytes) in html/apps/mail/lib/IMAP/Threading/Container.php on line 111
`

Largest mailbox may be 1,5GB. I'm can reproduce this easily when clicking some folders in the mail app.

**Comment by ChristophWurst** [comment]
I have to see if there is an easy way to get the memory footprint down.

**Comment by alexhass** [comment]
Now it uses ALL available memory. 14GB via cron.

mmap() failed: [12] Cannot allocate memory

mmap() failed: [12] Cannot allocate memory
PHP Fatal error:  Out of memory (allocated 14805893120) (tried to allocate 262144 bytes) in /apps/mail/lib/IMAP/Threading/Container.php on line 111

somethings need to be really really wrong!

**Comment by danusch** [comment]
I'm also facing the same issue with one of the mail accounts:
`php occ mail:account:diagnose 10`
```
IMAP capabilities:
- AUTH
- ENABLE
- ID
- IMAP4REV1
- LITERAL+
- SASL-IR

Account has 8648 messages in 17 mailboxes
```

I tried exporting the threads of that account:
`occ mail:account:export-threads  10 > /tmp/mailid.log!
The resulting file is only 2.1 MB.
And when I then do `php occ mail:thread /tmp/mailid.log` I get

> PHP Fatal error:  Allowed memory size of 536870912 bytes exhausted (tried to allocate 262144 bytes) in /opt/nextcloud/apps/mail/lib/IMAP/Threading/Container.php on line 111

I've attached the redacted version of the thread output file.
[mailidR.log](https://github.com/nextcloud/mail/files/5761508/mailidR.log)

Thanks for any help! Ps. I'm running Nextcloud 20.0.4

**Comment by vasyugan** [comment]
So, I see this phenomenon once again. And when I set the memory limit to -1, the process just never finishes. Another redacted thread file is attached
[threads.log](https://github.com/nextcloud/mail/files/5797335/threads.log)

**Comment by ChristophWurst** [comment]
I strongly believe the problem isn't actually about memory consumption but that the threading data builds some infinitely large data structure due to some recursion. I'll try to reproduce soonish with one of your data sets. The smaller ones are ideal as it will hopefully allow my to manually shrink the file to a bare minimum where the problem is still reproducible. If anyone wants to help or is just curious: try to remove as many entries from the json array. At some point we should have a low number of messages that cause this problem.

**Comment by vasyugan** [comment]
> I strongly believe the problem isn't actually about memory consumption but that the threading data builds some infinitely large data structure due to some recursion. I'll try to reproduce soonish with one of your data sets. The smaller ones are ideal as it will hopefully allow my to manually shrink the file to a bare minimum where the problem is still reproducible. If anyone wants to help or is just curious: try to remove as many entries from the json array. At some point we should have a low number of messages that cause this problem.

Isn't there some debug log that allows to see in real time what is going on?

BTW, since the trouble started only today, I assume that the culprit must be some message that arrived today. Before that, the account was just fine.

**Comment by ChristophWurst** [comment]
> Isn't there some debug log that allows to see in real time what is going on?

Well, we already have lots of debug info from the previous reports. My guess is that the code dies in `\OCA\Mail\IMAP\Threading\ThreadBuilder::buildIdTable`. That is where we take the list of raw message data and transform that into a tree structure based on references between messages.

> BTW, since the trouble started only today, I assume that the culprit must be some message that arrived today. Before that, the account was just fine.

That's a very good point. It might be very well the case. A completely wild guess is to check if there is any message the references itself, as in, `message-id` is found in `in-reply-to` or `references`. That would be a valid message at all, but someone could send it to trigger this bug.

**Comment by acsfer** [comment]
We monitor our PHP to trace slow requests, and all of them as of today come from mail app.
This leads to issues like server full swapping (8Gb of RAM, 2Gb of Swap) when mail is performing background tasks.

When it's not, RAM usage is less than 2Gb and SWAP not used at all.

- NC 20.0.7
- Mail 1.8.1 (2 IMAP boxes only)
- Apache 2.4
- PHP 7.4
- MySQL8
- Redis 6

Nextcloud logs thousands like :

> Allowed memory size of 536870912 bytes exhausted (tried to allocate 262144 bytes) at /nextcloud/public/apps/mail/lib/IMAP/Threading/Container.php#111

PHP log contains thousands of lines like these.

```
[pool nextcloud] pid 3335878
script_filename = /nextcloud/public/index.php
[0x00007f4010014060] execute() /nextcloud/public/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOStatement.php:127
[0x00007f4010013fe0] execute() /nextcloud/public/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/Connection.php:1062
[0x00007f4010013ef0] executeUpdate() /nextcloud/public/lib/private/DB/Connection.php:222
[0x00007f4010013e60] executeUpdate() /nextcloud/public/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/Query/QueryBuilder.php:209
[0x00007f4010013df0] execute() /nextcloud/public/lib/private/DB/QueryBuilder/QueryBuilder.php:217
[0x00007f4010013d30] execute() /nextcloud/public/apps/mail/lib/Db/MessageMapper.php:286
[0x00007f4010013bc0] insertBulk() /nextcloud/public/apps/mail/lib/Service/Sync/ImapToDbSynchronizer.php:293
[0x00007f4010013a50] runInitialSync() /nextcloud/public/apps/mail/lib/Service/Sync/ImapToDbSynchronizer.php:218
[0x00007f4010013930] sync() /nextcloud/public/apps/mail/lib/Service/Sync/SyncService.php:121
[0x00007f4010013850] syncMailbox() /nextcloud/public/apps/mail/lib/Controller/AccountsController.php:464
[0x00007f4010013650] draft() /nextcloud/public/lib/private/AppFramework/Http/Dispatcher.php:169
[0x00007f4010013520] executeController() /nextcloud/public/lib/private/AppFramework/Http/Dispatcher.php:100
[0x00007f4010013450] dispatch() /nextcloud/public/lib/private/AppFramework/App.php:152
[0x00007f4010013260] main() /nextcloud/public/lib/private/Route/Router.php:309
[0x00007f40100131b0] match() /nextcloud/public/lib/base.php:1008
[0x00007f40100130b0] handleRequest() /nextcloud/public/index.php:37

[pool nextcloud] pid 3335628
script_filename = /nextcloud/public/index.php
[0x00007f4010014830] __construct() /nextcloud/public/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php:27
[0x00007f4010014780] __construct() /nextcloud/public/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOMySql/Driver.php:22
[0x00007f40100146b0] connect() /nextcloud/public/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/Connection.php:362
[0x00007f4010014600] connect() /nextcloud/public/lib/private/DB/ReconnectWrapper.php:46
[0x00007f4010014570] connect() /nextcloud/public/lib/private/DB/Connection.php:69
[0x00007f40100144e0] connect() /nextcloud/public/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/Connection.php:1449
[0x00007f4010014480] getWrappedConnection() /nextcloud/public/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/Connection.php:892
[0x00007f4010014390] executeQuery() /nextcloud/public/lib/private/DB/Connection.php:202
[0x00007f40100142f0] executeQuery() /nextcloud/public/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/Query/QueryBuilder.php:206
[0x00007f4010014280] execute() /nextcloud/public/lib/private/DB/QueryBuilder/QueryBuilder.php:217
[0x00007f40100141c0] execute() /nextcloud/public/lib/private/AppConfig.php:345
[0x00007f40100140d0] loadConfigValues() /nextcloud/public/lib/private/AppConfig.php:110
[0x00007f4010014070] getApps() /nextcloud/public/lib/private/AppConfig.php:301
[0x00007f4010013fa0] getValues() /nextcloud/public/lib/private/legacy/OC_App.php:949
[0x00007f4010013f20] getAppVersions() /nextcloud/public/lib/private/Server.php:668
[0x00007f4010013e30] OC\{closure}() /nextcloud/public/lib/private/AppFramework/Utility/SimpleContainer.php:155
[0x00007f4010013db0] OC\AppFramework\Utility\{closure}() /nextcloud/public/3rdparty/pimple/pimple/src/Pimple/Container.php:118
[0x00007f4010013d00] offsetGet() unknown:0
[0x00007ffc74a4a2b0] ???() /nextcloud/public/lib/private/AppFramework/Utility/SimpleContainer.php:122
[0x00007f4010013c50] query() /nextcloud/public/lib/private/ServerContainer.php:156

[pool nextcloud] pid 3353560
script_filename = /nextcloud/public/index.php
[0x00007f3ec6c2bfa0] hasAncestor() /nextcloud/public/apps/mail/lib/IMAP/Threading/Container.php:111
[0x00007f3ec6c2bf20] hasAncestor() /nextcloud/public/apps/mail/lib/IMAP/Threading/Container.php:111
[0x00007f3ec6c2bea0] hasAncestor() /nextcloud/public/apps/mail/lib/IMAP/Threading/Container.php:111
[0x00007f3ec6c2be20] hasAncestor() /nextcloud/public/apps/mail/lib/IMAP/Threading/Container.php:111
[0x00007f3ec6c2bda0] hasAncestor() /nextcloud/public/apps/mail/lib/IMAP/Threading/Container.php:111
[0x00007f3ec6c2bd20] hasAncestor() /nextcloud/public/apps/mail/lib/IMAP/Threading/Container.php:111
[0x00007f3ec6c2bca0] hasAncestor() /nextcloud/public/apps/mail/lib/IMAP/Threading/Container.php:111
[0x00007f3ec6c2bc20] hasAncestor() /nextcloud/public/apps/mail/lib/IMAP/Threading/Container.php:111
[0x00007f3ec6c2bba0] hasAncestor() /nextcloud/public/apps/mail/lib/IMAP/Threading/Container.php:111
[0x00007f3ec6c2bb20] hasAncestor() /nextcloud/public/apps/mail/lib/IMAP/Threading/Container.php:111
[0x00007f3ec6c2baa0] hasAncestor() /nextcloud/public/apps/mail/lib/IMAP/Threading/Container.php:111
[0x00007f3ec6c2ba20] hasAncestor() /nextcloud/public/apps/mail/lib/IMAP/Threading/Container.php:111
[0x00007f3ec6c2b9a0] hasAncestor() /nextcloud/public/apps/mail/lib/IMAP/Threading/Container.php:111
[0x00007f3ec6c2b920] hasAncestor() /nextcloud/public/apps/mail/lib/IMAP/Threading/Container.php:111
[0x00007f3ec6c2b8a0] hasAncestor() /nextcloud/public/apps/mail/lib/IMAP/Threading/Container.php:111
[0x00007f3ec6c2b820] hasAncestor() /nextcloud/public/apps/mail/lib/IMAP/Threading/Container.php:111
[0x00007f3ec6c2b7a0] hasAncestor() /nextcloud/public/apps/mail/lib/IMAP/Threading/Container.php:111
[0x00007f3ec6c2b720] hasAncestor() /nextcloud/public/apps/mail/lib/IMAP/Threading/Container.php:111
[0x00007f3ec6c2b6a0] hasAncestor() /nextcloud/public/apps/mail/lib/IMAP/Threading/Container.php:111
[0x00007f3ec6c2b620] hasAncestor() /nextcloud/public/apps/mail/lib/IMAP/Threading/Container.php:111
```

**Comment by ChristophWurst** [comment]
@acsfer sounds like your Mail app now also has an account like the ones described by the others where the threading data has a loop or something similar that then builds an endless data structure until all memory is used up.

**Comment by acsfer** [comment]
@ChristophWurst is there anything i can do to help debug this?

**Comment by ChristophWurst** [comment]
I've created a debugging patch for you: https://github.com/nextcloud/mail/pull/4625. You can download it as https://patch-diff.githubusercontent.com/raw/nextcloud/mail/pull/4625.patch and it should apply on v1.8.x just fine. Once applied run the CLI sync again. The output will be very verbose but the few last lines should show where the process ends.

**Comment by acsfer** [comment]
@ChristophWurst here is the output on my side.

[debug.txt](https://github.com/nextcloud/mail/files/6061035/debug.txt)

**Comment by ChristophWurst** [comment]
Thanks a lot for that log. I *think* I know where it happens, I just don't know why. I'm also unable to trigger the same error with test data.

Could you get me `SELECT references, in_reply_to FROM oc_mail_messages WHERE message_id='<20210212175038.Horde.utMgQ8mHTFVZBMbfjDgTx7A@sdc65.fr>'`?

And then revert the previous patch, download the new version, apply again and test.

**Comment by acsfer** [comment]
SQL syntax error?

**Comment by ChristophWurst** [comment]
```SELECT `references`, in_reply_to FROM oc_mail_messages WHERE message_id='<20210212175038.Horde.utMgQ8mHTFVZBMbfjDgTx7A@sdc65.fr>'```

**Comment by acsfer** [comment]
```
+---------------------------------------------------------------------------+-----------------------------------------------------------------------+
| references                                                                | in_reply_to                                                           |
+---------------------------------------------------------------------------+-----------------------------------------------------------------------+
| ["<1612790998.SMTPs-dolibarr-pro23255@8286f1d7268ce9c329edf4946f53e85f>"] | <1612790998.SMTPs-dolibarr-pro23255@8286f1d7268ce9c329edf4946f53e85f> |
+---------------------------------------------------------------------------+-----------------------------------------------------------------------+
1 row in set (0.031 sec)
```

**Comment by acsfer** [comment]
Applied latest patch.

```
[debug] Processing reference <1612790998.SMTPs-dolibarr-pro23255@8286f1d7268ce9c329edf4946f53e85f> of message <20210212175038.Horde.utMgQ8mHTFVZBMbfjDgTx7A@sdc65.fr>
[debug] Processing reference <1612790998.SMTPs-dolibarr-pro23255@8286f1d7268ce9c329edf4946f53e85f> of message <20210212175038.Horde.utMgQ8mHTFVZBMbfjDgTx7A@sdc65.fr>
[debug] Step 1.B done
PHP Fatal error:  Allowed memory size of 536870912 bytes exhausted (tried to allocate 262144 bytes) in /apps/mail/lib/IMAP/Threading/Container.php on line 111
```

**Comment by ChristophWurst** [comment]
Thanks a lot. Unfortunately that doesn't give me the full picture of how your messages are connected.

Could you export the data for me as described in https://github.com/nextcloud/mail/issues/3869 and share via private email? If possible please don't redact as that would make it impossible for me to track the message back to the earlier debug logs.

**Comment by acsfer** [comment]
Mail sent to w**.chr***@gmail.com

**Comment by ChristophWurst** [comment]
I can reproduce the OOM error with the `occ mail:thread` command and your data :rocket:

**Comment by ChristophWurst** [comment]
```json
[
    {
        "subject": "ddc7b17d92b4bf13db951a880e830cc1@redacted",
        "id": "2e0890ddafefe7cf2470d450417db446@redacted",
        "references": [
            "2e0890ddafefe7cf2470d450417db446@redacted"
        ],
        "databaseId": 31884
    },
    {
        "subject": "41dd015a04a202d3c9d73b97f83418ba@redacted",
        "id": "894d2a6d49d1c830a886f708aa7af773@redacted",
        "references": [
            "2e0890ddafefe7cf2470d450417db446@redacted",
            "03772d55a8d179944bfce1c6c57083cf@redacted",
            "5a00f9760808fe565dcddf67bb822fd1@redacted",
            "5a00f9760808fe565dcddf67bb822fd1@redacted"
        ],
        "databaseId": 35208
    }
]
```

^ that is all it takes to let the sync engine explode :boom:

**Comment by szaimen** [comment]
Looks pretty normal to me. 
Why does it explode?

**Comment by ChristophWurst** [comment]
I'm debugging now.

**Comment by ChristophWurst** [comment]
Fix is at https://github.com/nextcloud/mail/pull/4628. Anyone who ran into this please give it a good test :)

Big thanks to @acsfer for the testing data :rocket:

**Comment by acsfer** [comment]
Confirm OK. 👍 

```
php occ mail:account:sync 8
...
[debug] Threading 11630 messages - build ID table took 2s
[debug] Threading 11630 messages - build root container took 0s
[debug] Threading 11630 messages - free ID table took 0s
[debug] Threading 11630 messages - prune containers took 0s
[debug] Threading 11630 messages - group by subject took 0s
[debug] Threading 11630 messages took 2s
[debug] Account 8 has 6036 threads
[debug] Account 8 has 0 messages with a new thread IDs
49MB of memory used
```
