### ISSUE TITLE
l10n: Extract the space character

### ISSUE THREAD

**Issue by Valdnet** [nextcloud/mail#3873]
**1.** I propose to extract the space character from text strings:

- Mark
- Unfavorite
- Favorite
- Unselect
- Move
- Delete
- unread
- read

in the file: src/components/EnvelopeList.vue.

This will improve the correctness of translations by translators in Transifex. Not all translators have spaces turned on in their settings, which causes them to skip the space at the end of sentences.

**2.** These words are also missing from Transifex:
- unread
- read

https://github.com/nextcloud/mail/blob/83d68085075dd250f62a58733be5b91641f0f54a/src/components/EnvelopeList.vue#L8-L9

In my opinion, the text strings need to be rebuilt for the Transifex bot to interpret them correctly.

Help: https://github.com/nextcloud/server/blob/a2a3b87c19662f06cfb804b9fead7e939b1c3e6c/core/src/globals.js#L130-L137

**Comment by ChristophWurst** [comment]
oh, yeah, that is not how we should translations.

@GretaD could you change this to a placeholder l10n string like `'Mark {number} unread'`?

**Comment by ChristophWurst** [comment]
actually @StCyr this is about the multiselect and not the mailbox in the navigation :)

**Comment by Valdnet** [comment]
@ChristophWurst Also remember this:

> 1. I propose to extract the space character from text strings:
> 
>     Mark
>     Unfavorite
>     Favorite
>     Unselect
>     Move
>     Delete
>     unread
>     read

**Comment by StCyr** [comment]
> 
> 
> actually @StCyr this is about the multiselect and not the mailbox in the navigation :)

I don't understand you. Shall I do something?

**Comment by ChristophWurst** [comment]
Your commit https://github.com/nextcloud/mail/commit/01b01891d7d9d98b0f9d76c5f5b1ba7c2c372722#diff-1c20844366f71c98b5cd4e19236e96619f374094d45de413131c8a63ef6e5c26R8-R22 chopped up l10n strings with a variable. You can't concatenate the string like this, you should use placeholders instead, like we do in https://github.com/nextcloud/mail/blob/9a5c24631e93bbb998292f82691e418df04e389e/src/components/NavigationMailbox.vue#L234-L243. Does it make sense now?

**Comment by StCyr** [comment]
Oh, yes, that I'd understood: I was not understanding if you were expecting something from me, since you'd asked Greta to do the change...

I can do it obviously

**Comment by ChristophWurst** [comment]
Nono I don't want to dictate who does what. It was more a question if one of you wants to pick this up. I first asked Greta becaues I thought it was related to a feature in the navigation that she worked on :)

**Comment by StCyr** [comment]
I'll do it. no problem
