### ISSUE TITLE
Can not access mail account in nextcloud after password change on imap server

### ISSUE THREAD

**Issue by RainerEmrich** [nextcloud/mail#3880]
### Expected behavior
There should be an option to set the new password.

### Actual behavior
Mail account is not shown anymore in nextcloud. The cronjob gives "OCA\Mail\Exception\ServiceException: IMAP errorMail server denied authentication." Can not access the mail account, so I even can not delete it.

### Mail app

**Mail app version:**  1.4.1

**Mailserver or service:** imap.1und1.de

### Server configuration

**Operating system**: Ubuntu 18.04

**Web server:** Apache 2.4.46

**Database:** MariaDB 10.4.15

**PHP version:** 7.3.23

**Nextcloud Version:** 19.0.4

#### Client configuration
**Browser:** Firefox 82.0

**Comment by RainerEmrich** [comment]
By the way, is there a known procedure to get rid of this dangling mail account. I tried "occ mail:clean-up", but this didn't work.

**Comment by ChristophWurst** [comment]
https://github.com/nextcloud/mail/pull/4419 fixes  this
