### ISSUE TITLE
Activating account provisioning is leading to a much longer loading time

### ISSUE THREAD

**Issue by jakobroehrl** [nextcloud/mail#3894]
If I activate account provisioning in the groupware settings the loading of the mail app is much more longer than without account provisioning. 

When I deactivate it, it's fast again.

**Comment by ChristophWurst** [comment]
Please use the [forum for community support](https://help.nextcloud.com/c/features-apps/mail/35) or open a new ticket in the support system if you're a customer, thanks

**Comment by ChristophWurst** [comment]
my guess is that the configured account doesn't actually work. check your logs.

**Comment by jakobroehrl** [comment]
Sorry, I didn't know that for mail errors I have to use the forum.
I tested the feature and want to report it, on all other repos I do it here on github.

**Comment by ChristophWurst** [comment]
Well it sounds like a typical troubleshooting ticket and the bug report template was completely ignored

let's first find out if it's really a bug, then we can create a proper report
