### ISSUE TITLE
[Request] Default Account

### ISSUE THREAD

**Issue by fsedarkalex** [nextcloud/mail#391]
Hi!

I realy like this app but am missing one point for professional use:

I would love to see some config options to be able to pre-fill the Server-Data with values I specify as well as an option to automatically add an account with following options:

Serverdata = from config
User = NextCloud-Login + Domain specified in config (probably add a field in config and some variables like %UserLogin%, %UserFirstName% and so on)
PAssword = NextCloud-Password

Or if this is not possible at least a feature to prefill also the user field :)

**Comment by lcalaresu** [comment]
Hello @fsedarkalex! Maybe the PR #28 is what you need?

**Comment by fsedarkalex** [comment]
Err... Looks like... didn't notice this :blush:

**Comment by ChristophWurst** [comment]
Yeah, we just finished this feature 🚀
