### ISSUE TITLE
many problems

### ISSUE THREAD

**Issue by asholino** [nextcloud/mail#3911]
Hi all 
i just set nexcloud mail . 
in th begining i was unable to configure but after i modified config.php seems working 
but when i triedto rspond to and email there was not and editor so i was du to instll anther app 
afeter i tried to send an email .. the buttun send is disabled and in draft i find the same message in drafts (arround 100 copy9 and my server crashed 
restarted server send buttun is active but i have Error 
![posta_nextcloud](https://user-images.githubusercontent.com/46514145/97612691-0a57de00-1a18-11eb-87ae-d234647730d0.png)

Error: Request failed with status code 500 
any ne one with this problem ?

**Comment by ChristophWurst** [comment]
help.nextcloud.com is the community forum. This is the bug tracker
