### ISSUE TITLE
oc_mail_accounts - Data too long for inbound_password

### ISSUE THREAD

**Issue by ma-ver-ick** [nextcloud/mail#393]
### Steps to reproduce
1. Create a new mail account

### Expected behaviour
New mail account should be created.

### Actual behaviour
Error message is shown, no account is created.

### Mail app

**Mail app version:** 0.6.4

**Mailserver or service:** tvial-mailserver

### Server configuration
nextcloud official docker image with, imap example.

##### Server log (data/nextcloud.log)
<details>
Creating account failed: An exception occurred while executing 'INSERT INTO `oc_mail_accounts`(`name`,`email`,`inbound_host`,`inbound_port`,`inbound_ssl_mode`,`inbound_user`,`inbound_password`,`outbound_host`,`outbound_port`,`outbound_ssl_mode`,`outbound_user`,`outbound_password`,`user_id`) VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?)' with params [omitted]: SQLSTATE[22001]: String data, right truncated: 1406 Data too long for column 'inbound_password' at row 1
</details>

The inbound_password is 276 characters long in the row the system is trying to persist (same with outbound_password).

**Comment by ChristophWurst** [comment]
Dup of https://github.com/nextcloud/mail/issues/340 and fixed in #375 :)
