### ISSUE TITLE
When selecting messages, and the message is read, the label should say "Mark unread"

### ISSUE THREAD

**Issue by GretaD** [nextcloud/mail#3956]
### Expected behavior
1. When i select a read message the label should say "Mark unread" and when i click the button should be turned into unread
2. Also, when on PI the *Other* category doest show the checkbox. ( I selected the first message)
![checkboxselect](https://user-images.githubusercontent.com/12728974/97982064-844ee500-1dd3-11eb-8f09-f9db5c6eedb8.png)

### Actual behavior
1. See gif here: https://github.com/nextcloud/mail/pull/3954#issue-514648423
2. The checkbox to select is shown

### Mail app

**Mail app version:** 1.5.1

**Comment by GretaD** [comment]
@StCyr please, as discussed, can you have a look whenever you can? Let me know if you need more testing

**Comment by StCyr** [comment]
I've fixed the "Label" issue but I can't reproduce the 2nd issue here with latest master:

![image](https://user-images.githubusercontent.com/8179031/98018039-5f249b80-1e00-11eb-8e03-da0ad35ea139.png)

**Comment by GretaD** [comment]
> I've fixed the "Label" issue but I can't reproduce the 2nd issue here with latest master:

All looks good now that  #3966 is merged. Thanks a lot :)
