### ISSUE TITLE
Unknown / undefined behaviour after creating / deleting mail accounts

### ISSUE THREAD

**Issue by ratermir** [nextcloud/mail#3997]
I gave a try to nextcloud e-mail client (it is a good idea, but the realization ... ??? - it is questionable to create mail client from scratch when there is a lot of good ones out there). Nevertheless, 

- I registered account at Google into the application, then deleted it, 
- then I added another account (from my private SMTP/IMAP server) which I deleted again. 

Both accounts worked somehow (even is the experience is far far to perfect; Google seems to be an enemy of this type of usage - but this is different story :) ). However after these tasks I am in the state when
- I dont see any account in the mail app now
- I am not able to add my private accoun that I deleted again (I see only message "Unexpected error during account creation")
- when I open the mail application, it tries to access Google account (Google informs me that someone accesses "insecure way" my account at tthe moment I opening the app)

Nextcloud 20.0.0 docker PHP FPM, Mail app 1.6.0 (also 1.5.6 did the same),

**Comment by ChristophWurst** [comment]
Please use the forum for community support questions: https://help.nextcloud.com/c/features-apps/mail/35

**Comment by ratermir** [comment]
Ok, thank you. I don't plan to use this app so I don't need support, but I was thinking that information about this (very strange) behavior could be useful for you.

**Comment by ChristophWurst** [comment]
Well it could if there was details. We'd need logs and reproduction steps.

**Comment by ratermir** [comment]
I looked into log, there were no more information than message posted above (of course with a lot of sauce around). 
Also the steps how I reproduced it are described above. Since I canř remove the original google account (since I don'tz see it), i don't know how to reproduce the whole proccess.

But OK later on (when I have more time) I will try to add the second account again and post the log here.

**Comment by ChristophWurst** [comment]
Cool, thanks. You can delete the account from `oc_mail_accounts` directly, I guess.

I've also just written down more troubleshooting instructions, those will certainly help shed more light onto your issues: https://github.com/nextcloud/mail/pull/4001
