### ISSUE TITLE
Mails with same sent_at value wont display (only one of them)

### ISSUE THREAD

**Issue by stavros-k** [nextcloud/mail#4000]
### Expected behavior
Display all mails

### Actual behavior
Diplays only one mail if more than 1 mail with same sent_at value exists

### Mail app

**Mail app version:** 1.6.0 (see apps admin page, e.g. 0.5.3)

**Mailserver or service:** Outlook (e.g. Outlook, Yahoo, Gmail, Exchange,...)

### Server configuration

**Operating system**: Unraid 6.8.3 (e.g. Debian 8)

**Web server:** Nginx (e.g. Apache, Nginx,...)

**Database:** PostgreSQL (e.g. MariaDB, SQLite or PostgreSQL)

**PHP version:** 7.3.24 (e.g. 7.0)

**Nextcloud Version:** 20.0.1 (see admin page, e.g. 13.0.2)

#### Client configuration
**Browser:** Chrome 86.0.4240.111(e.g. Firefox 48)

**Operating system:** Windows 10 (e.g. Arch Linux)

I have a folder with notifications from sites that items are back in stock again. Noticed some of them wasn't displaying. 
Checked db from pgAdmin and noticed all those had the same sent_at value, changed one of them and it displayed.

**Comment by ChristophWurst** [comment]
Interesting observation. Where I can imagine this to be a problem is the pagination, because the `sentAt` is used as the cursor. Does the overlap appear at the last element of a page?

**Comment by stavros-k** [comment]
I marked with yellow the 2 mails that appear on the webUI. 

It looks like it selects a random mail from the group of same sent_at values. Neither the 1st or the last.
If i manually change the sent_at value to a different one they appear normally.

![2](https://user-images.githubusercontent.com/47820033/98248348-7937b880-1f7d-11eb-997c-10912c9157f2.PNG)
![1](https://user-images.githubusercontent.com/47820033/98248352-7a68e580-1f7d-11eb-90ce-cdd30ad776b2.PNG)

**Comment by ChristophWurst** [comment]
This is a mailbox with just two messages? Once you changed the sent_at in the DB, the UI will always show both messages, even after reload?

**Comment by stavros-k** [comment]
This mailbox contains the selected rows on the db (8mails) 
Changed the sent_at on db, refreshed webui and all mails appeared, restarted docker, run "occ mail:account:sync 3 -f" and they still appear correctly. So it persists reboots.
Only way to make it get the original sent_at value is to remove mails and the mailbox from db and refetch

![4](https://user-images.githubusercontent.com/47820033/98252261-62e02b80-1f82-11eb-844a-006da930d3c4.PNG)
![3](https://user-images.githubusercontent.com/47820033/98252274-64a9ef00-1f82-11eb-8492-3e5e7925e62b.PNG)

**Comment by ChristophWurst** [comment]
Could you also try to have a mailbox with more than 20 (e.g. 25) messages to see if there is any missing messages within the first 19 items?

I'm not sure if this only happens for the last messages of the list

**Comment by stavros-k** [comment]
I don't have any mailbox with more than 20messages that happen to have same sent_at.
want me to manually set the same sent_at on a mailbox >20messages and see what is displayed?

**Comment by ChristophWurst** [comment]
Could you use another email client to *copy* more emails into a test mailbox. Like a mix of the messages from above and some arbitrary other messages?

**Comment by stavros-k** [comment]
Ok let me create another folder and copy some messages

**Comment by stavros-k** [comment]
So i put those 8 messages from above plus 22 from another mailbox. The above messages behave the same.
Also on the new mails i had 2 with same sent_at value. Only one of them appeared.
When i change the sent_at value to a different one, all mails appear correctly

In this case it also happened before the end of the list. One of the Epic Games message which had the same sent_at with another was missing, and after them there was the Cableworks messages

![6](https://user-images.githubusercontent.com/47820033/98253922-50ff8800-1f84-11eb-80d3-fa42eda94e2b.PNG)
![5](https://user-images.githubusercontent.com/47820033/98253927-5230b500-1f84-11eb-8c7a-c57d54831339.PNG)

**Comment by ChristophWurst** [comment]
I can reproduce!

**Comment by ChristophWurst** [comment]
Fix is at https://github.com/nextcloud/mail/pull/4015
