### ISSUE TITLE
Subject not visible on small screen

### ISSUE THREAD

**Issue by GretaD** [nextcloud/mail#4008]
### Expected behavior
The subject/header is visible

### Actual behavior
![subject](https://user-images.githubusercontent.com/12728974/98275482-f589c600-1f94-11eb-9b23-6ccca6532a25.png)

### Mail app

**Mail app version:** 1.6

**Comment by ChristophWurst** [comment]
is it because of the many participants of the thread?

**Comment by GretaD** [comment]
> is it because of the many participants of the thread?

yes, it happens when you have at least 2 rows of participants

**Comment by StCyr** [comment]
https://github.com/nextcloud/mail/pull/3745 will solve this issue

**Comment by ChristophWurst** [comment]
> yes, it happens when you have at least 2 rows of participants

Duplicate of https://github.com/nextcloud/mail/issues/3743 thus
