### ISSUE TITLE
[BUG] nextcloud not using AUTH command even when "Authentication required" checked

### ISSUE THREAD

**Issue by zen0x90** [nextcloud/mail#401]
### Steps to reproduce
1. Install and configure your own mail server (ex: postfix)
2. Enable secure SMTP by activating submission (port 587) (authentication required)
3. Execute a test email with nextcloud (in settings)

### Expected behaviour

Receive the test email.

### Actual behaviour

Jun 24 00:59:35 mail postfix/submission/smtpd[20965]: NOQUEUE: reject: RCPT from some.domain.org[1.2.3.4]: 554 5.7.1 <some.domain.org[1.2.3.4]>: Client host rejected: Access denied; from=<cloud@somewhere.com> to=<admin@somewhere.com> proto=ESMTP helo=<something.net>

It means nextcloud did a RCPT command before AUTH. In nextcloud settings you can configure your SMTP settings with "Authentication required" (checkbox). I did it but the error persist. I didn't check into the source code but it seems its a nextcloud bug.

### Mail app

**Mail app version:** N/A

**Mailserver or service:** Postfix/Dovecot with Submission

**Transport security - IMAP:** SSL/TLS

**Transport security - SMTP:** STARTTLS

**Number of accounts:** 3

**Mail app version build date:** (only if you are using a Nightly Build)

### Server configuration
**Operating system**: Linux itx 4.4.14 #2 SMP Fri Jun 24 13:38:27 CDT 2016 x86_64

**Web server:** nginx/1.10.2 (fpm-fcgi)

**Database:** sqlite3 3.13.0

**PHP version:** 5.6.30
Modules loaded: Core, date, ereg, libxml, pcre, fileinfo, filter, hash, SPL, json, mcrypt, pcntl, session, bz2, posix, Reflection, standard, SimpleXML, sockets, imap, sysvmsg, sysvsem, sysvshm, xml, xmlwriter, mysqlnd, cgi-fcgi, bcmath, openssl, calendar, ctype, curl, dba, dom, enchant, mbstring, ftp, gd, gettext, gmp, iconv, intl, ldap, exif, mysql, mysqli, odbc, zlib, PDO, pdo_mysql, pdo_sqlite, PDO_ODBC, pspell, shmop, snmp, soap, sqlite3, tokenizer, wddx, xmlreader, xsl, zip, Phar, redis, Zend OPcache

**Nextcloud version:** 11.0.3 (stable) - 11.0.3.2

**Updated from an older Nextcloud/ownCloud or fresh install:**

**Where did you install Nextcloud from:** 

**List of activated apps:**
<details>
	<summary>App list</summary>

Enabled:
 - activity: 2.4.1
 - admin_notifications: 1.0.0
 - apporder: 0.3.3
 - calendar: 1.5.3
 - checksum: 0.3.4
 - comments: 1.1.0
 - contacts: 1.5.3
 - dav: 1.1.1
 - direct_menu: 0.10.2
 - drawio: 0.8.8
 - encryption: 1.4.1
 - federatedfilesharing: 1.1.1
 - federation: 1.1.1
 - files: 1.6.1
 - files_downloadactivity: 1.0.1
 - files_pdfviewer: 1.0.1
 - files_sharing: 1.1.1
 - files_texteditor: 2.2
 - files_trashbin: 1.1.0
 - files_versions: 1.4.0
 - files_videoplayer: 1.0.0
 - firstrunwizard: 2.0
 - gallery: 16.0.0
 - issuetemplate: 0.2.1
 - logreader: 2.0.0
 - lookup_server_connector: 1.0.0
 - news: 10.2.0
 - nextcloud_announcements: 1.0
 - notes: 2.2.0
 - notifications: 1.0.1
 - ocr: 2.3.0
 - ocsms: 1.12.0
 - password_policy: 1.1.0
 - provisioning_api: 1.1.0
 - registration: 0.2.3
 - serverinfo: 1.1.1
 - sharebymail: 1.0.1
 - spreed: 1.2.0
 - survey_client: 0.1.5
 - systemtags: 1.1.3
 - tasks: 0.9.5
 - theming: 1.1.1
 - twofactor_backupcodes: 1.0.0
 - updatenotification: 1.1.1
 - workflowengine: 1.1.1

Disabled:
 - admin_audit
 - external
 - files_accesscontrol
 - files_automatedtagging
 - files_external
 - files_retention
 - rainloop
 - templateeditor
 - user_external
 - user_ldap
 - user_saml

</details>

**The content of config/config.php:**
<details>
	<summary>Config report</summary>

```
{
    "instanceid": "xxx",
    "passwordsalt": "***REMOVED SENSITIVE VALUE***",
    "secret": "***REMOVED SENSITIVE VALUE***",
    "trusted_domains": [
        "xxx"
    ],
    "datadirectory": "\/var\/www\/nextcloud\/data",
    "overwrite.cli.url": "https:\/\/xxx\/nextcloud",
    "dbtype": "sqlite3",
    "version": "11.0.3.2",
    "logtimezone": "UTC",
    "installed": true,
    "loglevel": 2,
    "maintenance": false,
    "memcache.local": "\\OC\\Memcache\\Redis",
    "redis": {
        "host": "\/var\/run\/redis\/redis.sock",
        "port": 0,
        "dbindex": 0,
        "timeout": 1.5
    },
    "mail_smtpmode": "smtp",
    "mail_smtpsecure": "tls",
    "mail_from_address": "cloud",
    "mail_domain": "xxx",
    "mail_smtphost": "xxx",
    "mail_smtpport": "587",
    "mail_smtpauthtype": "PLAIN",
    "mail_smtpauth": 1
}

**Comment by ChristophWurst** [comment]
Hi @zen0x90,

Nextcloud mail settings are handled by the Nextcloud server component, so please file an issue at https://github.com/nextcloud/server/issues/new

Thanks!
