### ISSUE TITLE
Support email templates (for branding, for special signature, etc.)

### ISSUE THREAD

**Issue by dumblob** [nextcloud/mail#4019]
#### Summary

As majority of other MUAs seem to do, I'd like to use arbitrary email as a template for new email. Usually in an arbitrary list of emails one can right click an email and in the menu there is something like **Edit as new message** (Thunderbird, ...) or open an arbitrary email and in menu of this opened email select **Edit as new** (Roundcube, ...).

This can be later extended with an option to set a currently edited/opened/selected message as default template for the chosen email account after clicking "New message" button.

I see this as low-hanging fruit implementation-wise but with enormous potential:

1. This solves the issue with sharing an email design (e.g. branded template or newsletter template or product list template etc.) with others (which users typically try to share using copy&paste which has many drawbacks a basically never leads to the intended result).

1. It can be used as an efficient & user-friendly workaround for signatures not working with pictures (which is a lot of work - search this issue tracker).

    A marketing team or an external company would create an example email with full-featured signature for every coworker (e.g. in Thunderbird or tool-generated/hand-written with `multipart/related` references) and this email will be simply sent to all users in an organization and since then the user will instead of **New message** click on the proper template email and select **Edit as new**.

    Of course, it still doesn't solve the "reply" scenario, but if the **set as default template for the given email account after clicking *New message* button** functionality (as mentioned above) gets implemented, the "reply" scenario will get automatically covered (the email the user replies to will be simply concatenated to the end of the template content before the closing sequence of `multipart/mixed` if any and it "shall" work).

    It won't automatically solve "automated stripping of signatures" but if the message editor can cope well with rich text, then this can be done easily and quickly by hand.

1. It shall be relatively straightforward to implement e.g. compared to the whole signatures functionality.If I'm not mistaken, it should be just a dumb copy of all the email contents without touching it in any way except for the insertion in the "reply" scenario (because touching it might destroy the `multipart/related` parts and thus links to images etc.).

This seems like a low-hanging

Note, currently (Mail 1.6.0) attachments (including `multipart/related`) are **not** preserved when forwarding an email - so forwarding is unfortunately not an option for the use cases the templates should cover.

Thoughts?

----

Whily writing the above proposal, I had to ask myself why is actually the content of a forwarded email quoted in NextCloud Mail?

From my experience MUAs treat *forwarding* differently from *replying*. In case of *forwarding* they do not do any quoting and just copy paste it all content (including attachments) and prepend some header meta information. Only in case of *reply* MUAs usually try to quote the content (often without attachments).

Why is NextCloud Mail different and quotes the content also in case of forwarding? And why does it even remove all attachments?

**Comment by ChristophWurst** [comment]
Use the issue search. Edit as new was just merged and will be shipped with 1.7, forward as attachment is a planned feature.

**Comment by ChristophWurst** [comment]
Also it's *Nextcloud* with a lower c

**Comment by dumblob** [comment]
>Edit as new was just merged and will be shipped with 1.7

Cool, I'll try it out.

>Use the issue search.

Sure thing. I did yesterday. Just try the search yourself and you'll find out there is not even a word about templates (except for this issue, of course :wink:).

>forward as attachment is a planned feature.

Sorry for not being clear - I meant really copy&paste of the email content **as is**, not wrapping it in another `multipart/mixed`. I'm not interested in forwarding as attachment, but **as is** - i.e. as exact copy without any wrapping, without any quoting, just **as is** (including attachments **as is**).
