### ISSUE TITLE
Unified search leads to poor UX in Mail when searching for emails

### ISSUE THREAD

**Issue by severin-lemaignan** [nextcloud/mail#4037]
Searching for email in nextcloud 20+ is done through the Unified search box.

However, the resulting user experience is not great: when you are in the mail app and you are search for an email, your search results are 'polluted' by results from others nextcloud apps that are irrelevant in the context or searching an email, and the email search result do not always show at the top:

![Screenshot from 2020-11-07 13-03-20](https://user-images.githubusercontent.com/385379/98442063-67c7eb00-20fa-11eb-8ec3-1dea6cb7f318.png)

Worst, in many cases, these other apps are faster to return a result, which means that the first visible results are not even related to the task ('searching for an email').

Power-users might be aware of `in:mail` in order to limit the search results to emails, but you should not need to be a power user to search in your emails.

=> It seems to me that, while nice on the paper, the 'unified search' approach has some real downsides in practice.

Possible ways forward:
- when in the mail app, the unified search bar only returns results from emails by default (with the option to extend to the other apps via eg clicking a buttom)
- have a dedicate search bar for the emails
- ...?

**Comment by StCyr** [comment]
>     * when in the mail app, the unified search bar only returns results from emails by default (with the option to extend to the other apps via eg clicking a buttom)

I agree with this solution, though it could be also the other way round (have an option to limit the search to only mails)

**Comment by ChristophWurst** [comment]
Found the issue.
