### ISSUE TITLE
Scroll past content

### ISSUE THREAD

**Issue by st3iny** [nextcloud/mail#4038]
### Expected behavior
Scrolling envelopes should stop at the bottom of the thread and not scroll the whole app layout.

### Actual behavior
Upon reaching the bottom of the thread the whole app layout is scrolled. If at least one envelope in the thread contains an attachment the bug is gone.

![scroll-bug](https://user-images.githubusercontent.com/1479486/98443307-c6956080-210a-11eb-8ab5-0d1adf1aafb6.gif)

### Mail app

**Mail app version:** master (also present in 1.6.0)

#### Client configuration
**Browser:** Chromium

**Comment by ChristophWurst** [comment]
regression of #3904 perhaps?

**Comment by st3iny** [comment]
Could be. I noticed that the bottom margin from the message bodies is missing as well.
