### ISSUE TITLE
The Full-Text search in NC 20.0.1 fails after updating to latest 1.6.0 version

### ISSUE THREAD

**Issue by frankbootmaker** [nextcloud/mail#4039]
### Expected behavior
Tell us what should happen

Full-Text search indexing with Elasticsearch shall run without any issue 

### Actual behavior
Tell us what happens instead

After updating to latest 1.6.0 version the indexing fails and I get the following error:

An unhandled exception has been thrown:
TypeError: Return value of "OCA\FullTextSearch\Command\Test::execute()" must be of the type int, "null" returned. in /var/www/html/custom_apps/mail/vendor/symfony/console/Command/Command.php:261
Stack trace:
#0 /var/www/html/core/Command/Base.php(169): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#1 /var/www/html/custom_apps/mail/vendor/symfony/console/Application.php(920): OC\Core\Command\Base->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#2 /var/www/html/custom_apps/mail/vendor/symfony/console/Application.php(266): Symfony\Component\Console\Application->doRunCommand(Object(OCA\FullTextSearch\Command\Test), Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#3 /var/www/html/custom_apps/mail/vendor/symfony/console/Application.php(142): Symfony\Component\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#4 /var/www/html/lib/private/Console/Application.php(215): Symfony\Component\Console\Application->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#5 /var/www/html/console.php(100): OC\Console\Application->run()
#6 /var/www/html/occ(11): require_once('/var/www/html/c...')

Disabling the Mail app the indexing works as expected.

### Mail app

Mail 1.6.0

Mailserver is a dovecot via IMAP

### Server configuration

**Operating system**: Debian 10 (NC Docker version)

**Web server:** : Apache

**Database:** MariaDB

**PHP version:** 7.4.11

**Nextcloud Version:** : 20.0.1

#### Client configuration
**Browser:** Firefox

**Operating system:** Windows 10

**Comment by ChristophWurst** [comment]
did you install both apps via the app store?

**Comment by ChristophWurst** [comment]
> TypeError: Return value of "OCA\FullTextSearch\Command\Test::execute()" must be of the type int, "null" returned. in /var/www/html/custom_apps/mail/vendor/symfony/console/Command/Command.php:261

This was a change from Nextcloud 19 on. FTS commands have to be fixed to always return an int: https://docs.nextcloud.com/server/latest/developer_manual/app_publishing_maintenance/upgrade-guide.html#symfony-update.

**Comment by ChristophWurst** [comment]
specifically there should be a `return 0;` after https://github.com/nextcloud/fulltextsearch/blob/045efda15b057efdf50402a267a2f30bf93845f5/lib/Command/Test.php#L188, but please report the issue to the FTS repo. Thanks :v:

**Comment by frankbootmaker** [comment]
Yeah, that additional line fixed it! 😊

I will report it as you suggested!

Many thanks for your help!

**Comment by frankbootmaker** [comment]
Hi,

I opened a ticket at them.
I realised that the below addition did fix the error for the /Test command, however the problem remained the same for the index, reset, … commands.

Do you have an idea what to do to get the reset and index commands to work at least?

**Comment by ChristophWurst** [comment]
It's the same issue for every command. They have to return a status code.
