### ISSUE TITLE
Sub Folder is not Expanding

### ISSUE THREAD

**Issue by pkmkrishnakumar** [nextcloud/mail#404]
Hi  I am an Mechanical Engineer with No knowledge of Computer Programming.
& I am new to Nextcloud & mail app as first.

Inbox shows the mail properly, but

When [Google Mail] in the left column is clicked,

loading [Google Mail] is shown up for 10 seconds later it results as,

**Could not load [Google Mail] :'-(**

I read few  #Issues 385 & #396. Tried to modify .css no improvement

Need help in simple terms

Thanks 

Krishnakumar Masimalai

### Steps to reproduce
1. Installed Mail from Apps in Nextcloud

### Expected behaviour
G mail sub folders to display

### Actual behaviour: 
Could not load [Google Mail] :'-(

Tell us what happens instead
Could not load [Google Mail] :'-(

### Mail app

**Mail app version:** 0.6.4

**Mailserver or service:** Gmail

**Transport security - IMAP:** IMAP

**Transport security - SMTP:** SMTP

**Number of accounts:** 01

### Server configuration

**Operating system**: Ubuntu 16.04

**Web server:** Apache2

**Database:** MySQL

**PHP version:** PHP 7.0

**Version:**  Next Cloud 12.0.0

**Updated from an older version or fresh install:** Fresh Install

**List of activated apps:**
Default Apps + Mail + Notes + Task + Calendar

![2017-06-26_16-00-48](https://user-images.githubusercontent.com/29704829/27535491-b31b8896-5a88-11e7-8eb4-52538f730d30.jpg)

**Comment by GnaXi** [comment]
I have the same issue with the latest version.

**Comment by lcalaresu** [comment]
What you described seems exactly what the PR #402 is fixing.
It has been approved already, it will be merged very soon ;)

**Comment by ChristophWurst** [comment]
Aaaaand merged 🚀
