### ISSUE TITLE
ActionRouter and ActionLink font size

### ISSUE THREAD

**Issue by st3iny** [nextcloud/mail#4040]
### Expected behavior
The envelope context menu action `Edit as new message` should have the same font size like the other context menu actions.

### Actual behavior
The font size of `Edit as new message` is slightly larger. This could be an issue in the ActionRouter component from nextcloud/nextcloud-vue.

![2020-11-08-143957_279x472_scrot](https://user-images.githubusercontent.com/1479486/98466564-94e6cd00-21d0-11eb-8878-63e522caa96e.png)

### Mail app
**Mail app version:** master

#### Client configuration
**Browser:** Chromium

**Comment by ChristophWurst** [comment]
Same for the action link actually
![Bildschirmfoto von 2020-11-09 09-02-47](https://user-images.githubusercontent.com/1374172/98514850-69b0bc00-226a-11eb-938b-be4f87f08f36.png)

**Comment by ChristophWurst** [comment]
(tested with the latest and greatest nc/vue@3.1.2 btw)

**Comment by ChristophWurst** [comment]
It is because of https://github.com/nextcloud/server/blob/05d332666476bec488989d39ef87e593eea02872/core/css/inputs.scss#L53. The other actions use buttons. Those two don't, hence they don't get the specific `13px` but remain at `100%`.

**Comment by ChristophWurst** [comment]
I opened a ticket upstream

**Comment by ChristophWurst** [comment]
Fixed by @GretaD in https://github.com/nextcloud/nextcloud-vue/pull/1543
