### ISSUE TITLE
Adding Mail-App as an application for mailto links [$5]

### ISSUE THREAD

**Issue by jansch2015** [nextcloud/mail#405]
### Steps to reproduce
1. Open Mail App
2. Dismiss "Add Nextcloud Mail as an application for mailto links"
3. Close Mail App
4. Open Mail App again

### Expected behaviour
The message should not appear again. Can this dismissal be saved?

### Actual behaviour
Dismissal-message appears every time I open the app.
![capture](https://user-images.githubusercontent.com/13114913/27677551-6f077666-5cb2-11e7-99e6-d12698387abe.JPG)

### Mail app

**Mail app version:** 0.6.4

**Mailserver or service:** Own IMAP-Server

**Transport security - IMAP:** SSL

**Transport security - SMTP:** SSL

**Number of accounts:** 1

#### Client configuration
**Browser:** Mozilla Firefox 54.0

**Operating system:** W10 Enterprise

**Comment by jancborchardt** [comment]
Isn’t this an issue on the browser side? Does this still happen for you @jansch2015 @alexanderdd – I was never able to reproduce it.

**Comment by alexanderdd** [comment]
I did not see this problem again in the last months (nc18.0.2 and corresponding mail app)

**Comment by ChristophWurst** [comment]
It's now only asked when the user clicks a button. So this should indeed not be an issue. @GretaD fixed this with https://github.com/nextcloud/mail/pull/2539. Please claim the bounty :)
