### ISSUE TITLE
remove the Folder "Vorrangiger Posteingang"

### ISSUE THREAD

**Issue by Neuroplant** [nextcloud/mail#4056]
### Feature Request

Hello,

is there a way, to remove the Folder "Vorrangiger Posteingang"?
Or at least make it optional to be the start folder to be opened, when opening Mail? (so It can be ignored)

Gruß
Neuroplant

**Comment by ChristophWurst** [comment]
I already linked it for you.

Open tickets in English please.

**Comment by robertlq** [comment]
I'm sorry, I still could not find any solution for the request to 'remove folder "Vorrangiger Posteingang" '. 
Please could anybody help? Thanks a lot...

**Comment by robertlq** [comment]
Just found the label in the English version: "Priority Inbox". 
But still could not find a solution to remove it. I would prefer to make my own priority and to see all inbox elements on the first place.
Thank you!

**Comment by Neuroplant** [comment]
Hello, unfortunately this "Feature" won't be removed.
But I used the app "External sites" to create a link to https://[your Server] /index.php/apps/mail/unified and replaced the "priority inbox" link with it

Gruß
Neuroplant

**Comment by robertlq** [comment]
Hi Neuroplant,
thanks a lot for your message. 
Unfortunately I can only install this app, but I'm not allowed to use it as I'm no admin on the hosted NC system.
It seems I have to live with the "feature" until more users request an option to make it invisible.
Best regards
Robert

**Comment by okow** [comment]
Hi,

i also would prefer to have just the chronological inbox, i.e. be able to disable the sidebar entry "Vorrangiger Posteingang"/"priority inbox".

Regards
Olaf
