### ISSUE TITLE
Background-fetching and showing some kind of notification icon [$15]

### ISSUE THREAD

**Issue by fsedarkalex** [nextcloud/mail#406]
This is a feature request.

I would love to see a feature (should be configurable by the user (configurable default in config.php) or at least through config.php) that adds a small red dot or similar visible indicator that makes a user notice that there are new mails in his inbox even when mail app is not running.
This indicator should show up when new mail is received until the user opens the mail app once, not every time when there are unread mails. It is about new items in Mailapp not unread mails.

If an indicator is not possible in that way what about a notification? I guess notifications can also be canceled when user enters mail app?

I hope you know what I am talking about... :laughing: 

Oh! The notification could look like this:
**You got X new E-Mails**
_Subject of E-Mail 1_
_Subject of E-Mail 2_
_Subject of E-Mail 3_

Email 1 is the latest email, 2 the second latest and so on... Only showing E-Mails that have not been noticed yet (noticed means seen - not read)

**Comment by ChristophWurst** [comment]
Actually we had this functionality once, but now that I'm thinking about it, I've not seen the red dot icon for a long time. IIRC it's a bit of a fragile feature as we're overwriting the icon that is set by the Nextcloud server component. @jancborchardt @juliushaertl or @nickvergessen could know more about it, I think we theme the icon now.

In any case, the background sync which provides the basis for a notification icon is kinda broken right now. I'll work on it as soon as #326 has been merged.

**Comment by juliushaertl** [comment]
@ChristophWurst Yes, the favicon will be generated depending on the app and theming color.

But there are some js libraries around to modify favicons on the fly. Those might be helpful for that:
- http://lab.ejci.net/favico.js/
- http://blog.tommoor.com/tinycon/
