### ISSUE TITLE
Contacts saved in folder "last contacted"

### ISSUE THREAD

**Issue by cracksilver** [nextcloud/mail#4060]
When I send a mail to several e-mail addresses, all contacts are saved in a system folder called "last contacted".

This is actually very helpful. However, these contacts can neither be deleted nor changed. They cannot be assigned to groups either.

Mail app version: 1.7.0
Contacts app version: 3.4.1
Mailserver or service: hoststar.ch

Server configuration
Operating system: Debian 10
Web server: Apache
Database: MariaDB
PHP version: 7.3.19
Nextcloud Version: 20.01

Client configuration
Browser: Firefox
Operating system: MacOS / Linux Debian

![screenshot](https://user-images.githubusercontent.com/74346108/98910589-af1bf600-24c3-11eb-9c6f-fcbc0f55555a.jpg)
![scrrenshot 2](https://user-images.githubusercontent.com/74346108/98910794-ef7b7400-24c3-11eb-9059-89cca306c624.jpg)

**Comment by ChristophWurst** [comment]
This is a Nextcloud server feature: https://github.com/nextcloud/server/pull/19075. The address book is indeed read-only. As far as I know there should be an option in Contacts to create a "real" contact from an interaction. @skjnldsv could you link the PR?

Mail is just one of the applications that emits data for this.

**Comment by skjnldsv** [comment]
Yes, they are read-only.
You can clone them on the top right menu
![image](https://user-images.githubusercontent.com/14975046/98911328-b8599280-24c4-11eb-8307-032e8bb05f03.png)

**Comment by ChristophWurst** [comment]
Also @cracksilver note that the recently contacted persons will also disappear after a while if you don't contact them again :)

**Comment by cracksilver** [comment]
hi there

The problem is that it doesn't work to duplicate the address.
![Bildschirmfoto 2020-11-12 um 16 33 31](https://user-images.githubusercontent.com/74346108/98961212-9cc2ac00-2505-11eb-8177-cd32ee1df6cd.jpg)

**Comment by ChristophWurst** [comment]
Please open a bug report at https://github.com/nextcloud/contacts and include the browser console log. Sounds like this is an error that should be shown there. Checking nextcloud.log as well would be good.

**Comment by ChristophWurst** [comment]
On an unrelated note I think you're running Nextcloud for a school and we'd love to hear more about this https://twitter.com/Nextclouders/status/1326939065963450373 :)

**Comment by cracksilver** [comment]
> 
> 
> On an unrelated note I think you're running Nextcloud for a school and we'd love to hear more about this https://twitter.com/Nextclouders/status/1326939065963450373 :)
;-) no, i am in no way affiliated with a school. i'm only on the parents' council. That's why I have the class addresses in there ...
