### ISSUE TITLE
ConsoleLogger: Lots of debug messages, Could not sync envelopes, heatbeat check "CSRF check failed"

### ISSUE THREAD

**Issue by stevleibelt** [nextcloud/mail#4062]
### Expected behavior
The Firefox console logger is polluted with lots of messages.
Unexpected are messages from the category `debug` and `info .

Furthermore, the upgrade to `nextcloud 20.0.1` resulted into many errors in the log.
I did two things last week. Migrate from CentOS 6 (Uberspace 6) to CentOS 7 (Uberspace 7) and migrated from `19.0.4.2` to `20.0.1`.

![image](https://user-images.githubusercontent.com/2287220/98997157-5a649380-2534-11eb-9e65-6dd0c6e4425f.png)

### Actual behavior
No debug or info messages in the javascript console logger (or maybe enable/disable via configuration setting).

### Mail app

**Mail app version:** (see apps admin page, e.g. 1.7.0)

**Mailserver or service:** (gmx.de, web.de.)

### Server configuration

**Uberspace**: 7

**Operating system**: CentOS 7

**Web server:** Apache 2

**Database:** MariaDB 10.3.26

**PHP version:** 7.4.12

**Nextcloud Version:** 20.0.1

#### Client configuration
**Browser:** Firefox 82.0.2 64 Bit

**Operating system:** Arch Linux 5.4.75-1-lts

**Comment by ChristophWurst** [comment]
So the "errors" are when the app tries to load an avatar for a sender where no avatar exists. We use semantic HTTP codes, 404 reflects a non existing avatar.

And the other ones we leave in because that is the only sane way for people to file good bug reports. Is there any issue with seeing debug/info logs in the console?

**Comment by stevleibelt** [comment]
@ChristophWurst, thanks for your quick reply.

For the 404-Errors, indeed it makes sense from the HTTP Status Codes point of view.
From the point of possible debugging issues, this error codes simple clutters the console log. For the case someone has a real error, this high amount of unimportant error messages increases the chance to slip over the real error.

This leads me to the second question if debug/info logs are an issues. It would be great if this could be configured.
For first error report, this very verbose logging is way to much. As you see for this current reported issue, it can lead to "false positive" issues.
So yes, from my point of view, having this logs as default in my console logs is an issue. Do you get my point?

**Comment by ChristophWurst** [comment]
> From the point of possible debugging issues, this error codes simple clutters the console log. For the case someone has a real error, this high amount of unimportant error messages increases the chance to slip over the real error.
> 
> This leads me to the second question if debug/info logs are an issues. It would be great if this could be configured.
> For first error report, this very verbose logging is way to much. As you see for this current reported issue, it can lead to "false positive" issues.
> So yes, from my point of view, having this logs as default in my console logs is an issue. Do you get my point?

Makes sense, I guess. So I've opened a new ticket for the logger lib: https://github.com/nextcloud/nextcloud-logger/issues/141
