### ISSUE TITLE
Inbox does not sync - getEmail() must be of the type string or null, bool returned

### ISSUE THREAD

**Issue by sutidor** [nextcloud/mail#4064]
### Expected behavior
Tell us what should happen
`occ mail:account:sync 1`
should sync my inbox

### Actual behavior

console output
```
[debug] account is up to date, skipping mailbox sync
[debug] Initial sync 1:INBOX - fetch all messages from IMAP took 1s

In ImapToDbSynchronizer.php line 235:

  Sync failed for 1:INBOX: Return value of OCA\Mail\Address::getEmail() must be of the type string or null, bool returned


In Address.php line 82:

  Return value of OCA\Mail\Address::getEmail() must be of the type string or null, bool returned
```

### Mail app

**Mail app version:** (see apps admin page, e.g. 0.5.3)
1.7.0

**Mailserver or service:** (e.g. Outlook, Yahoo, Gmail, Exchange,...)
postfix / dovecot self hosted. Works flawlessly with webmail and thunderbird

### Server configuration

**Operating system**: (e.g. Debian 8)
docker on debian 10, image from linuxserver.io

**Web server:** (e.g. Apache, Nginx,...)
1.18.0

**Database:** (e.g. MariaDB, SQLite or PostgreSQL)
MariaDB

**PHP version:** (e.g. 7.0)
v7.3.22

**Nextcloud Version:** (see admin page, e.g. 13.0.2)
20.0.1

#### Client configuration
**Browser:** (e.g. Firefox 48)
Firefox 82.0.3

**Operating system:** (e.g. Arch Linux)
Windows 10

**Comment by ChristophWurst** [comment]
do you have mod iconv installed for your php?

**Comment by ChristophWurst** [comment]
this was also reported at https://github.com/nextcloud/mail/issues/3999#issuecomment-722365928

**Comment by sutidor** [comment]
Thanks for the reference which I had'nt found. I found the issue addressed over in the linuxserver.io repos.
