### ISSUE TITLE
error message can't add email account - error connecting to SMTP server

### ISSUE THREAD

**Issue by Gerhardjz** [nextcloud/mail#407]
I installed a new nextcould version 12.0.0 with the mail app on a web hosted space. PHP 7 and MySql 5.5.
Mail 0.6.4
The service provider is 1&1.

I wanted to add a mail address that is hosted by 1&1. Enabled SSL on both IMAP and SMTP. Also tried to change the port to TLS. Tried the TLSSTART. Always the same result.
Triple checked the username and password. Server address. Connecting with Smartphone and OSX Mail do work without problems using IMAP.

Any hint what could be wrong.

Thanks for any advice and help,
Gerhard.

**Comment by lcalaresu** [comment]
Hello Gerhard,
Have you tried to turn on imap logging? (cf. README).
Maybe there will be interesting information in the log file you can share :)

**Comment by Gerhardjz** [comment]
I tried to do that.
added the line mentioned in the documentation.

--------------------------- config.php -------------------------------
<?php
$CONFIG = array (
  'instanceid' => 'oe',
  'passwordsalt' => '',
  'secret' => '',
  'trusted_domains' => 
  array (
    0 => 'cloud.diebessermacher.com',
  ),
  'datadirectory' => '/homepages/37/d.../htdocs/cloud/data',
  'overwrite.cli.url' => 'http://cloud.diebessermacher.com',
  'dbtype' => 'mysql',
  'version' => '12.0.0.29',
  'dbname' => 'db....',
  'dbhost' => 'db......db.1and1.com',
  'dbport' => '',
  'dbtableprefix' => 'oc_',
  'dbuser' => 'dbo...........',
  'dbpassword' => '......',
  'logtimezone' => 'UTC',
  'installed' => true,
  'maintenance' => false,
  'theme' => '',
  'loglevel' => 2,
);
'app.mail.transport' => 'php-mail'
'app.mail.imaplog.enabled' => true;
'app.mail.smtplog.enabled' => true;
------------- end config.php ----------------------------------

going to my login results in a php error.

Fatal error: Uncaught Error: Call to a member function getLogger() on null in /homepages/37/d666439592/htdocs/cloud/index.php:61 Stack trace: #0 {main} thrown in /homepages/37/d666439592/htdocs/cloud/index.php on line 61

I just found a entrance for 1&1 email, that I also added.

Thanks for responding on a Sunday afternoon :-)
Best regards,
Gerhard.

**Comment by Gerhardjz** [comment]
As it simes the copy paste corrupts the LF, I uploaded the config.php as PDF.
[config.php.pdf](https://github.com/nextcloud/mail/files/1117852/config.php.pdf)

**Comment by Gerhardjz** [comment]
OK. Now I found my mistake :-) Adding to the config in the array works. Can receive and send email.
Sometimes it's not wise to work on sunday's, even it rains.
  'theme' => '',
   'loglevel' => 2,
   'app.mail.imaplog.enabled' => true,
  'app.mail.smtplog.enabled' => true,
  'app.mail.transport' => 'php-mail' 
);

**Comment by lcalaresu** [comment]
@Gerhardjz 
I think it works thanks to the `'app.mail.transport' => 'php-mail'`.
If everything is fine to you, do not forget to remove the logging `'app.mail.xxxlog.enabled' => true,` as it might alter your performances...

**Comment by Gerhardjz** [comment]
Thanks for the advice. I already did and it still works 👍
