### ISSUE TITLE
Mail Reply ignore Reply-To

### ISSUE THREAD

**Issue by daebak74** [nextcloud/mail#4075]
### Expected behavior
When I click Reply button in an email the "To" field should use the "Reply-to" if different than "From"

### Actual behavior
When I click Reply button in an email the "To" field is populated with the From sender

### Mail app

**Mail app version:** (see apps admin page, e.g. 0.5.3)
1.6.0

**Mailserver or service:** (e.g. Outlook, Yahoo, Gmail, Exchange,...)
Generic IMAP provider

### Server configuration

**Operating system**: (e.g. Debian 8)
Ubuntu 18.04

**Web server:** (e.g. Apache, Nginx,...)

**Database:** (e.g. MariaDB, SQLite or PostgreSQL)
PostgreSQL

**PHP version:** (e.g. 7.0)
7.3.17

**Nextcloud Version:** (see admin page, e.g. 13.0.2)
20.0.1

#### Client configuration
**Browser:** (e.g. Firefox 48)
Chrome 86.0.4240.193

**Operating system:** (e.g. Arch Linux)

**Comment by KrLx1994roller** [comment]
This has been around for quite some time and I consider it critical enough to fix asap... Also it seems like a very easy fix. Could you please include in next patch? Thanks!

**Comment by ChristophWurst** [comment]
> Also it seems like a very easy fix

It sounds like you are quite familiar with the code. Could you send us a pull request with the critical changes?

**Comment by ChristophWurst** [comment]
Thanks for the feedback @sk757a

**Comment by vermeeren** [comment]
@ChristophWurst I created a patch to implement Reply-To header support on replying to a mail (both all and single) using Horde implementation for the address handling of the Reply-To mechanism. Could you (and perhaps others interested) check #8880 and share thoughts?

Thanks!
