### ISSUE TITLE
Microsoft Exchange Support?

### ISSUE THREAD

**Issue by MarcelRobitaille** [nextcloud/mail#4084]
### Feature Request

Microsoft exchange support

#### Summary
I would love support for the microsoft exchange api. My university exchange email server doesn't support IMAP.

Maybe this helps to implement? https://github.com/GNOME/evolution-ews

**Comment by ChristophWurst** [comment]
I thought there was an existing ticket but I can't find it right now. But no, we're focusing on IMAP for now as our only supported email protocol.

**Comment by BloodyIron** [comment]
> > Hi @ChristophWurst hope you're doing well. Quick question for you. A lot of Org use Microsoft Active Sync. Is there any plans on supporting this platform ?
> 
> about your question from ActiveSync: [nextcloud/calendar#2320 (comment)](https://github.com/nextcloud/calendar/issues/2320#issuecomment-640409530)

Still really worth adding Exchange ActiveSync, I pointed out a good bit of reasons why it should be added in that thread...
