### ISSUE TITLE
Inbox content not visible, stuck at loading messages

### ISSUE THREAD

**Issue by patzm** [nextcloud/mail#4095]
### Expected behavior
The inbox loads the list of emails in at most a few seconds.

### Actual behavior
The spinning "Loading messages" dialog does not go away.
![Peek 2020-11-18 10-35](https://user-images.githubusercontent.com/5219726/99512492-cf4b2980-2989-11eb-91f8-f1fe25c3889d.gif)

### Mail app

**Mail app version:** v1.7
**Mailserver or service:** one.com
I have multiple folders. The main inbox for instance has ~2k emails. Is that already too much?

### Server configuration
Everything is running inside a docker :whale: container. The base is [crazy-max/docker-nextcloud](https://github.com/crazy-max/docker-nextcloud), and this is [my configuration](https://github.com/patzm/dockerfiles/tree/master/nextcloud).
**Operating system**: Alpine s6:3.12
**Web server:** Nginx?
**Database:** MariaDB 10.2
**PHP version:** (e.g. 7.0)
**Nextcloud Version:** 20.0.1

#### Client configuration
**Browser:** Firefox 83
**Operating system:** Manjaro Linux, 5.8.18-1 kernel

**Comment by ChristophWurst** [comment]
> I have multiple folders. The main inbox for instance has ~2k emails. Is that already too much?

Nope that should work fine.

I think it's related to https://github.com/nextcloud/mail/issues/3999.

Anything in your nextcloud.log?

**Comment by patzm** [comment]
```
{"reqId":"Nvkp45virIf2ThxSxdW4","level":0,"time":"2020-11-18 13:53:51","remoteAddr":"172.29.0.3","user":"martin","app":"mail","method":"GET","url":"/apps/mail/api/messages?mailboxId=29&limit=20","message":"loading messages of folder <29>","userAgent":"Mozilla/5.0 (X11; Linux x86_64; rv:83.0) Gecko/20100101 Firefox/83.0
","version":"20.0.1.1"}
```
This is the only relevant line that metnionds the `"app":"mail"`.

You are right, the issue you linked looks very similar.

This is my email account diagnosis
```
occ $ mail:account:diagnose 2
IMAP capabilities:
- AUTH
- ENABLE
- ID
- IDLE
- IMAP4REV1
- LITERAL+
- LOGIN-REFERRALS
- SASL-IR
Account has 17246 messages in 19 mailboxes
```

I then tried to sync:
```
occ $ mail:account:sync 2
[debug] account is up to date, skipping mailbox sync
[debug] Initial sync 2:INBOX - fetch all messages from IMAP took 1s
In ImapToDbSynchronizer.php line 235:
                                                                               
  Sync failed for 2:INBOX: Return value of OCA\Mail\Address::getEmail() must   
  be of the type string or null, bool returned                                 
                                                                               
In Address.php line 82:
                                                                               
  Return value of OCA\Mail\Address::getEmail() must be of the type string or   
  null, bool returned
```
Running it again yielded:
```
occ $ mail:account:sync 2
[debug] account is up to date, skipping mailbox sync
In MailboxLockedException.php line 33:

  29 is already being synced
```

**Comment by ChristophWurst** [comment]
> Running it again yielded:
> 
> ```
> 
> ```

Could you apply https://github.com/nextcloud/mail/pull/4100 as patch https://patch-diff.githubusercontent.com/raw/nextcloud/mail/pull/4100.patch on your system and try again? In the meantime the mailbox should have unlocked. So try twice until you see the `MailboxLockedException` again.

**Comment by patzm** [comment]
Ok, I did the following
```bash
docker exec -it nextcloud /bin/bash  # enter the container <nextcloud>
apk add git  # wasn't installed
cd /var/www/userapps/mail
wget https://patch-diff.githubusercontent.com/raw/nextcloud/mail/pull/4100.patch
git apply --stat 4100.patch
 lib/Service/Sync/ImapToDbSynchronizer.php |    6 ++++++
 1 file changed, 6 insertions(+)
bash-5.0# git apply --check 4100.patch  # just checks if the patch can be applied
bash-5.0# git apply 4100.patch  # apply the patch
bash-5.0# git apply --check 4100.patch  # yes, it has been applied, because it is failing
error: patch failed: lib/Service/Sync/ImapToDbSynchronizer.php:198
error: lib/Service/Sync/ImapToDbSynchronizer.php: patch does not apply
```
Then I ran `occ mail:account:sync 2` again, twice, with exactly the same output.

**Comment by patzm** [comment]
I also tried:
```bash
docker-compose restart nextcloud  # restart the container
docker exec -it nextcloud /bin/bash  # enter the container <nextcloud>
cd /var/www/userapps/mail
# verify that the 4100.patch file is still there -> OK
git apply --check 4100.patch  # OK, changes still are applied
error: patch failed: lib/Service/Sync/ImapToDbSynchronizer.php:198
error: lib/Service/Sync/ImapToDbSynchronizer.php: patch does not apply
```
However, still stuck with the loading animation.

**Comment by ChristophWurst** [comment]
Run `update oc_mail_mailboxes set sync_new_lock=null, sync_changed_lock=null, sync_vanished_lock where id=29` to unlock the mailbox. Then you should be able to once trigger the iconv issue. And I'm curious to hear what's happening the second time.

**Comment by ChristophWurst** [comment]
Just to be clear: this isn't supposed to fix the problem. But it will hopefully tell me why your mailbox stays locked after the error. In theory the code should always unlock the mailbox, even if the synchronization causes an error.

**Comment by patzm** [comment]
how do I run the command? I tried pasting it into the occweb plugin (which is essentially prefixing `occ`), didn't work.
Also: I am not sure if I have _debug_ logging verbosity turned on. I need to make sure I have, right?

**Comment by ChristophWurst** [comment]
in the database. it's sql. forgot to mention that.

the debug logs will show on the CLI regardless of the log level. You don't have to change anything :)

**Comment by ChristophWurst** [comment]
`update oc_mail_mailboxes set sync_new_lock=null, sync_changed_lock=null, sync_vanished_lock=null where id=29` is the query. I made a an error above. this will unlock mailbox 29.

**Comment by patzm** [comment]
sorry for more stupid questions :laughing:. I have a MariaDB running as a separate container. How do I literally run this query?

**Comment by ChristophWurst** [comment]
https://dev.mysql.com/doc/mysql-linuxunix-excerpt/5.6/en/docker-mysql-getting-started.html#docker-connecting-within-container

**Comment by patzm** [comment]
got it. for reproduction:
```bash
$ docker exec -it nextcloud_db_1 mysql -uroot -p
Enter password: *** # done
```
then
```sql
> show tables;
...
mysql
nextcloud
...
> use nextcloud;
> show tables;
...
mail_accounts
mail_mailboxes
...
update mail_mailboxes set sync_new_lock=null, sync_changed_lock=null, sync_vanished_lock=null where id=29;
```
Looking at the `nextcloud.log`, I see 
```
{"reqId":"q4760LgGcP3jH9FJldc3","level":0,"time":"2020-11-18 18:57:56","remoteAddr":"172.29.0.3","user":"martin","app":"mail","method":"POST","url":"/apps/mail/api/mailboxes/29/sync","message":"Locking mailbox 29 for new messages sync","userAgent":"Mozilla/5.0 (X11; Linux x86_64; rv:83.0) Gecko/20100101 Firefox/83.0","version":"20.0.1.1"}
```
popping up every second.

Then I run the `update ...` SQL command again. This triggered a small message below the `Loading messages`:
![image](https://user-images.githubusercontent.com/5219726/99569018-689d2e80-29d0-11eb-990d-242e37c20287.png)
Still, nothing comes up. Also, CPU usages doesn't show any load right thereafter.

**Comment by ChristophWurst** [comment]
> popping up every second.

You should close the web browser. That output is expected. What I'm curious about is the full output of `occ $ mail:account:sync 2` after closing the browser and giving the requests a few seconds to finish.

**Comment by patzm** [comment]
So I did
1. closed all browser _tabs_ that were accessing the nextcloud.
1. in the MariaDB docker container
    ```sql
      update mail_mailboxes set sync_new_lock=null, sync_changed_lock=null, sync_vanished_lock=null where id=29;
   ```
1. wait for ~2 seconds
1. in the nextcloud docker container
    ```bash
     $ occ mail:account:sync 2
     ```
    ![image](https://user-images.githubusercontent.com/5219726/99571729-fdedf200-29d3-11eb-97a8-ffd2e64459b8.png)

**Comment by ChristophWurst** [comment]
that's good. the mailbox should be unlocked. could you try running the command two or three times in a series? with your original report it sounded like the error would leave the mailbox locked, so I'm just checking if that is even the case.

**Comment by patzm** [comment]
Yes, seems like it. Second and third command fail, finding a locked mailbox. Running the sql command obviously lifts that again (tested separately).
![image](https://user-images.githubusercontent.com/5219726/99577070-18779980-29db-11eb-96dd-fe9e160d1095.png)

**Comment by ChristophWurst** [comment]
Thanks a lot for this. I still don't get what's keeping the mailbox locked. So please do the following

* Clear the lock with the provided SQL
* Run the mail:account:sync but just *once*
* Run the SQL `select id, sync_new_lock, sync_changed_lock, sync_vanished_lock from oc_mail_mailboxes where id=29` and post the output here

**Comment by patzm** [comment]
![image](https://user-images.githubusercontent.com/5219726/99647044-88286b80-2a51-11eb-9f3e-dbd319d236c1.png)

**Comment by ChristophWurst** [comment]
This is unexpected but it explains why you see the locking error. The cleanup code claims to release the locks, but it doesn't actually do that. Would you have the means to enable *query logging* on your mysql and then try again? This info would hopefully shed more light on what's happening (or not). Those locking errors should really not pop up often.

**Comment by patzm** [comment]
I am not a DB expert and mostly use these docker images out of the box. If you send me the commands to do that, then sure, I can enable that. The DB load and disk usage still have resources to spend :slightly_smiling_face:, so extensive logging won't hurt for now.

**Comment by ChristophWurst** [comment]
Cool. https://stackoverflow.com/a/54404114/2239067 sounds like that could work with your setup. Could you check? :v:

**Comment by patzm** [comment]
Ok I have two logs now:
1. from accessing the mail app in the browser in nextcloud (`variant1.log`)
1. from doing the round-trip (`variant2.log`)
    1. clear the lock with the SQL statement
    1. trigger a mailbox sync
    1. trigger a mailbox sync again, see the failure
    1. clear the lock again with the SQL statement

I will send you the logs separately via email.

**Comment by ChristophWurst** [comment]
Thanks a lot!

```
		59478 Query	UPDATE `mail_mailboxes` SET `sync_new_lock` = 1605898223, `sync_changed_lock` = 1605898223, `sync_vanished_lock` = NULL WHERE `id` = 29
		59478 Query	UPDATE `mail_mailboxes` SET `sync_new_lock` = 1605898223, `sync_changed_lock` = NULL, `sync_vanished_lock` = NULL WHERE `id` = 29
		59478 Query	UPDATE `mail_mailboxes` SET `sync_new_lock` = NULL, `sync_changed_lock` = NULL, `sync_vanished_lock` = NULL WHERE `id` = 29
```
-> everything is unlocked as expected. I don't see how the database row could still have any locks on it when they are set to NULL here … :thinking: :thinking: :thinking:

**Comment by patzm** [comment]
Maybe because the default view tries to open multiple mailboxes?
* Important
* Favorites
* Other

Could it be that all try to access the same mailbox and end up in a deadlock?
![image](https://user-images.githubusercontent.com/5219726/99957265-b1b20180-2d87-11eb-95f9-ff638b9d5c63.png)

**Comment by ChristophWurst** [comment]
But you had the web UI closed while producing the requested logs, right?

**Comment by patzm** [comment]
yes, it was closed. True.
Do you think it could be something related to my environment? I.e. how to best debug it?

**Comment by patzm** [comment]
And any ideas how to take it from here?

**Comment by mgriego** [comment]
I'm not yet sure why the locks aren't being cleared, but I can say that, in my instance, one thing I'm running into is that an unhandled exception is being thrown in my Inbox, resulting in a 500 and a stale lock being left behind:

```
Sync failed for 1:INBOX: An exception occurred while executing 'INSERT INTO `oc_mail_messages` (`uid`, `message_id`, `references`, `in_reply_to`, `thread_root_id`, `mailbox_id`, `subject`, `sent_at`, `flag_answered`, `flag_deleted`, `flag_draft`, `flag_flagged`, `flag_seen`, `flag_forwarded`, `flag_junk`, `flag_notjunk`, `flag_important`) VALUES(?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)' with params [254880, "REDACTED", "[]", null, "REDACTED", 58, "REDACTED", 1609722005, false, false, false, false, false, false, false, false, false]:

SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry '254880-58' for key 'mail_msg_mb_uid_idx'
```
I'm thinking what may have happened is that a sync failed before it was able to update the sync token for the account.  But, before it failed, it was able to sync down some messages.  Therefore the sync is trying to re-sync messages that were actually already synced, due to the old uidvalidity, resulting in the duplicate key failures.

**Comment by Peronia** [comment]
I had the same issue, NC 20.0.5 and Mail 1.7.2.
I nulled all locks in DB (3 rows) and now all works fine.

I found many 404s for contactpictures and one deprecating warning, only as info.
![19-01-_2021_12-18-32](https://user-images.githubusercontent.com/25049991/105028121-e9b88680-5a50-11eb-8769-d83e50827efc.png)

**Comment by patzm** [comment]
> I nulled all locks in DB (3 rows) and now all works fine.

How did you do that?

**Comment by Peronia** [comment]
> `update oc_mail_mailboxes set sync_new_lock=null, sync_changed_lock=null, sync_vanished_lock=null where id=29` is the query. I made a an error above. this will unlock mailbox 29.

I used phpmyadmin and go into the table oc_mail_mailboxes and set all values @sync_changed_lock, sync_vanished_lock and sync_new_lock to null.

**Comment by miaulalala** [comment]
Could everyone test this again with the newest version from master? There was a change to an underlying query which seems to have improved this issue as well.

**Comment by the-lay** [comment]
@miaulalala now it works for me, thanks!

**Comment by patzm** [comment]
Nice :rocket: solved it for me too!

**Comment by wliwan** [comment]
![image](https://user-images.githubusercontent.com/33739491/197748177-f995da6b-96f5-4318-a025-4f6b1922a759.png)
@miaulalala I modified it as [Peronia](https://github.com/Peronia) described, but it didn't work, there are about 7K emails in the mailbox. when I nulled them and reload that site, they will be locked again.
