### ISSUE TITLE
Mail overwrites Symfony/Command globally

### ISSUE THREAD

**Issue by waffshappen** [nextcloud/mail#4102]
### Expected behavior
Mail should not globally override Symfony/Command

This breaks some commands' output/handling (see:  https://github.com/nextcloud/news/pull/952#issuecomment-730264295 )

### Actual behavior
Mail overrides Symfony/Command globally

### Mail app

1.7.0

**Mailserver or service:** Irrelevant

### Server configuration

**Operating system**: Fedora 33

**Web server:** Httpd

**Database:** Postgres

**PHP version:** 7.4

**Nextcloud Version:** 20.0.1

#### Client configuration
**Browser:** FF 82

**Operating system:** Fedora 33

**Comment by SMillerDev** [comment]
Related to https://github.com/nextcloud/ldap_contacts_backend/pull/13 and https://github.com/coenjacobs/mozart/issues/79

**Comment by ChristophWurst** [comment]
Let's see if we can possibly use https://github.com/bamarni/composer-bin-plugin for Mozart.

**Comment by ChristophWurst** [comment]
And if Mozart continues to be troublesome we can also give https://github.com/humbug/php-scoper another go.

**Comment by ChristophWurst** [comment]
I have a promising fix at #4633
