### ISSUE TITLE
when Reply an email it's saved as Drafts and duplicated

### ISSUE THREAD

**Issue by ramikilany** [nextcloud/mail#4119]
### Expected behavior
When trying to reply to an email, the email must be moved to sent folder

### Actual behavior
after sending the reply, the same reply message is shown in the drafts folder and duplicated. each time trying to delete the emails still show lot of the same draft email.

### Mail app

**Mail app version:** 1.7.0

**Mailserver or service:** Bluehost

### Server configuration

**Operating system**: Ubuntu 20.04

**Web server:** Apache

**Database:** MariaDB

**PHP version:** 7.4.3

**Nextcloud Version:** 20.0.2

#### Client configuration
**Browser:** Firefox 83

**Operating system:** Pop!_OS

**Comment by ChristophWurst** [comment]
Dup of #3984
