### ISSUE TITLE
regression: navigation in ckeditor sometimes stops working

### ISSUE THREAD

**Issue by StCyr** [nextcloud/mail#4122]
### Expected behavior
I should be able to navigate in the ckeditor 

### Actual behavior
Sometime, backspace and return key don't work and the following kind of log lines shows up in the console

`Uncaught CKEditorError: model-nodelist-offset-out-of-bounds Read more: https://ckeditor.com/docs/ckeditor5/latest/framework/guides/…t/error-codes.html#error-model-nodelist-offset-out-of-bounds
 {"offset":99,"nodeList":[{"data":"Oui, tu as raison...`

### Mail app

**Mail app version:** 1,7

### Server configuration

**Nextcloud Version:** 20,0,01

#### Client configuration
**Browser:** FF latest
**Operating system:** Windows 10

**Comment by ChristophWurst** [comment]
Dup of #4104?

**Comment by StCyr** [comment]
yes. sorry
