### ISSUE TITLE
Add Cache API support

### ISSUE THREAD

**Issue by StCyr** [nextcloud/mail#4125]
### Feature Request

https://developer.mozilla.org/en-US/docs/Web/API/Cache

https://caniuse.com/mdn-api_cache

#### Summary

Do you think it could be possible to add support for this API to Mail? 

This could be great to avoid further requests for messages' body for example (no further requests if we re-open a message that we've already opened)

**Comment by ChristophWurst** [comment]
We already use HTTP caching where applicable. 



> This could be great to avoid further requests for messages' body for example (no further requests if we re-open a message that we've already opened)

Here we use 1h of caching already: https://github.com/nextcloud/mail/blob/b4afd1347a14559848b52ac44425b382f2e05742/lib/Controller/MessagesController.php#L337-L338

**Comment by StCyr** [comment]
Why not in https://github.com/nextcloud/mail/blob/b4afd1347a14559848b52ac44425b382f2e05742/lib/Controller/MessagesController.php#L220

tho?

**Comment by ChristophWurst** [comment]
Guess we can add it there as well :)

**Comment by StCyr** [comment]
Ok, I've opened a PR for this.

But I still have one request that's slowing down the display of messages: getThread

However, I guess it's a bit harder to implement caching here, is it?

**Comment by ChristophWurst** [comment]
Yep. Caching is only ever easy for things that are immutable. The threads can change any time, hence caching isn't really appropriate.

**Comment by StCyr** [comment]
> Yep. Caching is only ever easy for things that are immutable. The threads can change any time, hence caching isn't really appropriate.

Though, getThread is really expensive (takes about 2 secs here to get the result). What would you think about implementing some caching at the application level here?

Like: Maintain a timestamp of when a thread was last computed on the backend and, in the frontend, only call getThread when the timestamp has changed

**Comment by StCyr** [comment]
> Like: Maintain a timestamp of when a thread was last computed on the backend and, in the frontend, only call getThread when the timestamp has changed

Argh. This is not possible: Thread information isn't persisted. 

What about persisting it?

**Comment by ChristophWurst** [comment]
How would you persist it?

**Comment by ChristophWurst** [comment]
Closing because https://github.com/nextcloud/mail/pull/4159 was done and I think the rest is already handled well.
