### ISSUE TITLE
unable to load some mails: "not found"

### ISSUE THREAD

**Issue by Benance** [nextcloud/mail#4127]
### Expected behavior
when I click on the mail, it should open

### Actual behavior
When I click on the mail, I have an error "not found" "unable to load message"

### Mail app

**Mail app version:** 1.4.1

**Mailserver or service:** Postfix + Dovecot

### Server configuration

**Operating system**: Raspbian 10

**Web server:** Nginx

**Database:** MariaDB

**PHP version:** 7.3

**Nextcloud Version:** 19.0.3

#### Client configuration
**Browser:** Firefox 78.5 ESR

**Operating system:** Windows 10 1909

When I want to open some mails, I have an error "not found". Note that it happens only with certain mails (not all, fortunately). I can open these problematic mails without problem from thunderbird on another pc or from fairemail on my phone.
I have attached the logfile from the nextcloud admin panel. Thanks for your help.
[log nextcloud mail.txt](https://github.com/nextcloud/mail/files/5602355/log.nextcloud.mail.txt)

**Comment by ChristophWurst** [comment]
Log indicates a possible problem on an IMAP level. Please provide us with the horde logs for that specific request.

The Nextcloud mail app offers an extensive logging system to make it easier identifying and tracking down bugs. Please enable [debug mode](https://docs.nextcloud.com/server/stable/developer_manual/general/devenv.html#enabling-debug-mode) and set the log [level to debug](https://docs.nextcloud.com/server/stable/admin_manual/configuration_server/logging_configuration.html) in your admin settings. Then, try to reproduce your issue and take another look at `data/horde_imap.log`.

**Comment by Benance** [comment]
Sorry but I haven't got any "debug" line in my config.php file... Just a "loglevel" line...

**Comment by ChristophWurst** [comment]
Add it ;)

**Comment by Benance** [comment]
all right. I've added the line
Here is the horde_imap.log file
[horde_imap.log](https://github.com/nextcloud/mail/files/5602820/horde_imap.log)

**Comment by ChristophWurst** [comment]
There actually is. UID 15955 of INBOX is causing the issue, and this is the IMAP communication that confirms the message can't be fetched

```
C: 4 UID FETCH 15955 (BODY.PEEK[1.1.1] BINARY.SIZE[1.1.1] BODY.PEEK[1.1.1.MIME])
S: * 107 FETCH (UID 15955 BODY[1.1.1] {2457}
S: [LITERAL DATA: 2457 bytes]
S: )
S: 4 NO [PARSE] Invalid data in MIME part (0.114 + 0.000 + 0.113 secs).
>> Command 4 took 0.116 seconds.
```

**Comment by ChristophWurst** [comment]
If I understand this correctly then that message can't be parsed by the server.

**Comment by Benance** [comment]
ok but I can open this mail on my phone and from a mail client...
I have forgetten to mention that this mail contains a pdf attachment.
Thanks for the diag.

**Comment by ChristophWurst** [comment]
I think it's the way we look into the body of the message. Possibly relevant ticket of another email client is https://github.com/roundcube/roundcubemail/issues/6383.

I don't have the time to look into this right now as it seems to be a rather specific issue. We should fix it, but there is more important work for me right now. If you are a developer please let us know and we can tell you how to debug this further.

**Comment by ChristophWurst** [comment]
If the email that can't be parsed doesn't contain any sensitive information you may try to export it with another email client, share it here and others can the import and try to reproduce with their email servers. Without access to an account that allows reproduction it's really hard to fix such problems.

**Comment by Benance** [comment]
the mail contains a link to a google form about scolar rhythms in my childrens' school... I prefer not to share it.

**Comment by ChristophWurst** [comment]
Sure, no worries.

**Comment by Aveyron-RetD** [comment]
well i am on 28 and this issue seems not solved

**Comment by alexhell** [comment]
having the same issue. 
All other clients (even snappymail on NC) can show the text. 
And even sometimes the mail app shows a "preview" but if you click on the email, it disappear.

**Comment by joopdo** [comment]
I'm having the same issue with one particular e-mail. (from my bank, so not sharing, I'll share full redacted source if I get it with a less important email) 

`"method":"GET","url":"/apps/mail/api/messages/100983/body","message":"mb_convert_encoding(): Argument #3 ($from_encoding) contains invalid encoding \"text/plain\" in file '/var/www/owncloud/apps/mail/lib/IMAP/ImapMessageFetcher.php' line 477","userAgent":"Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:126.0) Gecko/20100101 Firefox/126.0","version":"28.0.4.1","exception":{"Exception":"Exception","Message":"mb_convert_encoding(): Argument #3 ($from_encoding) contains invalid encoding \"text/plain\" in file '/var/www/owncloud/apps/mail/lib/IMAP/ImapMessageFetcher.php' line 477","Code":0,"Trace":[{"file":"/var/www/owncloud/lib/private/AppFramework/App.php","line":184,"function":"dispatch","class":"OC\\AppFramework\\Http\\Dispatcher","type":"->","args":[["OCA\\Mail\\Controller\\MessagesController"],"getBody"]},{"file":"/var/www/owncloud/lib/private/Route/Router.php","line":315,"function":"main","class":"OC\\AppFramework\\App","type":"::","args":["OCA\\Mail\\Controller\\MessagesController","getBody",["OC\\AppFramework\\DependencyInjection\\DIContainer"],["100983","mail.messages.getBody"]]},{"file":"/var/www/owncloud/lib/base.php","line":1069,"function":"match","class":"OC\\Route\\Router","type":"->","args":["/apps/mail/api/messages/100983/body"]},{"file":"/var/www/owncloud/index.php","line":39,"function":"handleRequest","class":"OC","type":"::","args":[]}],"File":"/var/www/owncloud/lib/private/AppFramework/Http/Dispatcher.php","Line":169,"Previous":{"Exception":"ValueError","Message":"mb_convert_encoding(): Argument #3 ($from_encoding) contains invalid encoding \"text/plain\"","Code":0,"Trace":[{"file":"/var/www/owncloud/apps/mail/lib/IMAP/ImapMessageFetcher.php","line":477,"function":"mb_convert_encoding","args":`
