### ISSUE TITLE
1366x768: Make Columns Adjustable

### ISSUE THREAD

**Issue by kaffeeringe** [nextcloud/mail#4132]
My former Chromebook has a 1366x768 screen. The middle column with the list of mails is too narrow. I can't read anything there. I don't even have to blur my screenshot:
![Screenshot_2020-11-27 E-Mail - Steffen's Cloud](https://user-images.githubusercontent.com/367592/100423187-e2e24880-308b-11eb-9a51-16ef5c9468c5.png)

Suggestions:
- Make columns adjustable
- disable the icon when the column gets too narrow
- Remove the age info when the column is too narrow
- Replace the age info with a colored dot that is bright red when the mail is brand new and turns grey the older the mail. The actual age could be revealed in a mouse over of the dot.

**Comment by ChristophWurst** [comment]
Thanks for the feedback and suggestions.

This seems to be a duplicate of https://github.com/nextcloud/mail/issues/3940. Could you add your points there? THanks :v:
