### ISSUE TITLE
Porblems with sending, show folders and deleting when using a domainfactory managed mail account

### ISSUE THREAD

**Issue by CordlessWool** [nextcloud/mail#414]
### Actual behaviour
I have connected the app to two accounts. One is my University account, currently there are no problems with this account. But there a problems with the second account: The server is an managed server from [domainfactory](https://www.df.eu/de/e-mail-hosting/). I also call mail from the domainfactory server via android (Lineage default mail client) and Evolution (Linux Mail client), also sort E-Mails with imapfilter... Domainfactory offers also a [horde](https://webmail.df.eu/horde/login.php) web interface. Everywhere without nextcloud mail it is not problem to see folders, send or delete mails.

But in Nextcloud Mail I get an error message if I am sending messages (sends the message anyway but shows "server error"), could not see created folder (Instead all mails shown in Inbox) and it is also not be able to delete mails (showing message: "error while deleting message") 

### Mail app

**Mail app version:** (see apps admin page)
0.6.4

**Mailserver or service:** (e.g. Outlook, Yahoo, Gmail, Exchange,...)
Domainfactory Managed Mail
Link to config instruction: [https://www.df.eu/blog/sslin-df-eu-sslout-df-eu/](https://www.df.eu/blog/sslin-df-eu-sslout-df-eu/)

**Transport security - IMAP:** (None, SSL, TLS, STARTTLS) 
ssl

**Transport security - SMTP:** (None, SSL, TLS, STARTTLS)
ssl

**Number of accounts:**
2 but ony one affected 

### Server configuration

**Operating system**:
Official Docker  Container

**Web server:**
php-fpm

**Database:**
mysql

**PHP version:**
7.1-fpm

**Version:** (see admin page)
nextcloud version 12

[horde_imap_ while_opening.txt](https://github.com/nextcloud/mail/files/1148821/horde_imap_.while_opening.txt)
[nextcloud_log_part.txt](https://github.com/nextcloud/mail/files/1148822/nextcloud_log_part.txt)
[server_log_parts.txt](https://github.com/nextcloud/mail/files/1148824/server_log_parts.txt)

**Comment by ChristophWurst** [comment]
Hi,

may I ask you to fill out the full issue template and provide us relevant information from your log files (nextcloud.log, horde_imap.log, horde_smtp.log) https://raw.githubusercontent.com/nextcloud/mail/master/.github/issue_template.md ?
Thanks.

**Comment by CordlessWool** [comment]
I added some parts from the log files. Hope it will help you. If you need more information please request.

**Comment by ChristophWurst** [comment]
@CordlessWool thanks a lot. I think I've found the issue:

> C: 5 UID MOVE 236 Trash
> S: 5 NO Client tried to access nonexistent namespace. (Mailbox name should probably be prefixed with: INBOX.) (0.000 + 0.000 secs).

**Comment by CordlessWool** [comment]
I talk to my provider and maybe it could be also a problem that sent and draft are sub folders of inbox? So there have to be an option to set the path to sent and draft!?

**Comment by ChristophWurst** [comment]
> I talk to my provider and maybe it could be also a problem that sent and draft are sub folders of inbox?

Yup, I think that can be an issue. See https://github.com/nextcloud/mail#dovecot-imap.

> So there have to be an option to set the path to sent and draft!?

Yes, the mail app currently tries to guess those folders. Obviously there are cases where it guesses wrongly.

**Comment by CordlessWool** [comment]
Want to update this issue to new Nextcloud Mail Version 7.3
- Folders are shown now, but only as INBOX.folder.folder, but that is ok. But if open a folder firstly the complete inbox is shown, after some secound it switched to the mails in the folder if it is not empty or has no subfolders, otherwise it keep showing the complete Inbox
... after clicken a while from folder to folder it shows sometime first the mails in the folder and then the mails from complete inbox and stay at this view
- Deleteing is still not be possible
- Sending mails is happen without error message
- University account seems to be working fine

thanks developing this app, it get better from time to time :+1:

**Comment by CordlessWool** [comment]
A new Update to new Nextcloud Mail Version 7.5
- I do not test everything now but sending mail from my university account is not possible yet, but working before. I am not sure if it stops with 7.4, 7.3 or some time before (not using it that often). Sending from the other address works.

**Comment by CordlessWool** [comment]
A new Update to Nextcloud Mail Version 8.1
- Moving, deleting and writing messages are working now - Thank you
- One Problem with deleting messages was, that I did not activate trash folder. I think there is a flag to mark deletion without moving it to a trash folder, that was active before. With active trash folder everything is ok.
