### ISSUE TITLE
»CSRF check failed« when writing new email on tab which was open for longer

### ISSUE THREAD

**Issue by jancborchardt** [nextcloud/mail#417]
Encountered this on our cloud.nc installation with the Mail app:

I had a tab open since yesterday. Just opened from suspend and started to write a new mail in the old tab I had open with the Mail app. On sending, I got a showNotification with »CSRF check failed« and the following console log:

```
POST 
XHR 
https://cloud.[…].com/apps/mail/accounts/22/draft [HTTP/1.1 412 Precondition failed 200ms]
[message] "send" Array [ Object, Object, Object ] mail.min.js:148:14867
[ui] "document:click" Array [ Object ] mail.min.js:148:14867
[ui] "document:click" Array [ Object ] mail.min.js:148:14867
```

We should make sure that even if you keep tabs open (what people tend to do, especially when they use the app a lot), the app silently reconnects after wake from suspend.
(Related to similar issue in the notes app https://github.com/nextcloud/notes/issues/122)

@nextcloud/mail @nextcloud/javascript

**Comment by ChristophWurst** [comment]
Dup of https://github.com/nextcloud/mail/issues/258
