### ISSUE TITLE
Add the undo option for the "Remember images for this sender"

### ISSUE THREAD

**Issue by GretaD** [nextcloud/mail#4176]
### Feature Request

Right now, we have the option to remember a sender as trusted and all the messages coming from them and have images, the images will be shown. We should be able to undo this option when we dont want to see the images anymore.

#### Summary

Ref: #4103

**Comment by jancborchardt** [comment]
Design-wise, ref what @ChristophWurst wrote in https://github.com/nextcloud/mail/pull/4103#issuecomment-733620772

> https://support.google.com/mail/thread/12526769
> ![Bildschirmfoto von 2020-11-25 11-31-38](https://user-images.githubusercontent.com/1374172/100215854-d6d27b80-2f11-11eb-8a6b-819eab726e27.png)

It would be a section in the account settings called "Remote content" or "Trusted senders" with a short settings-hint of: `Senders accepted via "Show images from this sender" will show up here`. Wording needs adjustment
