### ISSUE TITLE
Installation of mail app with occ command fails

### ISSUE THREAD

**Issue by Joachim1305** [nextcloud/mail#4178]
### Expected behavior
Tell us what should happen
Successful (fresh) installation

### Actual behavior
Tell us what happens instead
root@xxx:/var/www/nextcloud# sudo -u www-data php occ app:install --keep-disabled mail
Error: An exception occurred while executing 'SELECT COUNT(*) FROM `oc_mail_coll_addresses`':

SQLSTATE[42S02]: Base table or view not found: 1146 Table 'nextcloud.oc_mail_coll_addresses' doesn't exist

### Mail app

**Mail app version:** (see apps admin page, e.g. 0.5.3)
1.7.1
**Mailserver or service:** (e.g. Outlook, Yahoo, Gmail, Exchange,...)

### Server configuration

**Operating system**: (e.g. Debian 8)
Ubuntu 20.04
**Web server:** (e.g. Apache, Nginx,...)
Apache2.4
**Database:** (e.g. MariaDB, SQLite or PostgreSQL)
MariaDB 10.5
**PHP version:** (e.g. 7.0)
7.4
**Nextcloud Version:** (see admin page, e.g. 13.0.2)
20.0.2
#### Client configuration
**Browser:** (e.g. Firefox 48)
Firefox 83.0
**Operating system:** (e.g. Arch Linux)

**Comment by Joachim1305** [comment]
Hint:
App was installed before. I had issues receiving emails.
To ensure clean re-installation I dropped all oc_mail_* tables in DB.

**Comment by ChristophWurst** [comment]
so?

**Comment by ChristophWurst** [comment]
First you do this

> To ensure clean re-installation I dropped all oc_mail_* tables in DB.

Then you encounter this

> SQLSTATE[42S02]: Base table or view not found: 1146 Table 'nextcloud.oc_mail_coll_addresses' doesn't exist

… that is expected, right?

**Comment by Joachim1305** [comment]
Well, I expected that during installation with

"  sudo -u www-data php occ app:install --keep-disabled mail  "

all necessary tables will be created again.

**Comment by ChristophWurst** [comment]
nope, that is not the case. We use migrations and no database diffs. If you mangle with the db schema the app won't "repair" itself.

**Comment by Joachim1305** [comment]
Do you see any remedy ?

**Comment by ChristophWurst** [comment]
Not for production instances. That process isn't supported. We have some docs for developers but this means anything that goes wrong from here is basically not our fault. But check https://github.com/nextcloud/mail/blob/master/doc/developer.md#resetting-the-app.

**Comment by Morelcia** [comment]
I had same issue because I wanted to reset mail app to defaults.
```
DELETE FROM oc_migrations WHERE app='mail';
DELETE FROM oc_preferences WHERE appid='mail';
DROP TABLE IF EXISTS oc_mail_accounts,oc_mail_aliases,oc_mail_attachments,oc_mail_classifiers,oc_mail_coll_addresses,oc_mail_mailboxes,oc_mail_messages,oc_mail_messages,oc_mail_recipients,oc_mail_trusted_senders;
```
After that Mail app should install again
