### ISSUE TITLE
Attachments should show inline below the message with more suitable icon

### ISSUE THREAD

**Issue by benks-io** [nextcloud/mail#4181]
When reading a mail in the current version of the mail app, the only clue that there is a file attached is the chain icon below the message.
This easily slips away from the attention, as it has no context or label.

First - I'd argue that the Icon is not the best choice, as in the rest of Nextcloud's GUI it is used to indicate a folder being shared (Files App - File List), or stands for the URL behind a share (Share Sidebar). The well known Icon for an Attachment is the Paper-Clip. I'd propose to change to that.
An Icon could also be useful at the Avatar Circle of the mail in the content frame and maybe even attached to the avatar in the Mail List.

In addition to that the Filename should be visible directly below the Message with a proper Icon and a possibility to save the file to files app or HDD. Images should have a preview.

This was also discussed during last contributor week in Mail design review.

**Comment by ChristophWurst** [comment]
Yep yep. This was done partly for some technical difficulties with the message height (of iframes) that we couldn't quite control at that time. But @st3iny fixed that and now we could show them inline again. We actually had that in the past.

also :eyes: @violoncelloCH who did the floating icon :)

**Comment by brueckner** [comment]
Do you have screenshots of what it used to look like, or should be come up with a (layout) suggestion for @jancborchardt to look at? _Get well soon @jancborchardt, btw!_

**Comment by ChristophWurst** [comment]
Phew I don't find any screenshot but I'm sure there should be some somewhere …

**Comment by GretaD** [comment]
@jancborchardt  @nimisha-vijay can you please send me a mockup of the final design of this ticket?

**Comment by nimisha-vijay** [comment]
This is the design we had made:

![image](https://user-images.githubusercontent.com/52440189/133067716-4a1e9125-ac53-47c1-a424-4941a9d53375.png)

- The thumbnail would be a preview of the attachment if available, otherwise a filetype icon
- That action menu would open on clicking the 3 dot menu 

cc @jancborchardt also

**Comment by ChristophWurst** [comment]
> The thumbnail would be a preview of the attachment if available, otherwise a filetype icon

Let's make that a follow-up, we don't have an endpoint for previews yet and loading the originals (for images) is a lot of bandwidth

**Comment by benks-io** [comment]
Thanks @GretaD :)
