### ISSUE TITLE
Link styles not visible because links are overwritten to be black in Nextcloud

### ISSUE THREAD

**Issue by benks-io** [nextcloud/mail#4182]
### Expected behavior
A URL or Link in a Mail that is clickable should be visually distinguishable from normal Text, probably blue or underlined.

### Actual behavior
URLs and Links are just black.

### Mail app

**Mail app version:** 1.7.1

**Comment by StCyr** [comment]
really? Never noticed that... Mind sharing a screenshot?

**Comment by benks-io** [comment]
@StCyr Seems to be fixed by now.

**Comment by ChristophWurst** [comment]
fixed by https://github.com/nextcloud/mail/pull/4235
