### ISSUE TITLE
Unable to activate on nextcloud-20/php-7.2 - PHP 7.3 or higher is required

### ISSUE THREAD

**Issue by uli-heller** [nextcloud/mail#4183]
### Expected behavior

The changelog of version 1.7.1 reads: "Fixed ... Php7.2 compatibility issues"

After updating mail to version 1.7.1, I'm expecting to be able to activate it

### Actual behavior

I cannot activate mail. There is a message like this: 

```
Diese App kann nicht installiert werden, weil die folgenden Abhängigkeiten nicht erfüllt sind:
PHP 7.3 or higher is required.
```

### Mail app

**Mail app version:** 1.7.1

### Nextcloud

- 20.0.2 on ubuntu-18.04.5 using php-7.2

**Comment by ChristophWurst** [comment]
Yeah, this is kind of a problem. Nextcloud 20s are not supposed to use 1.6+, but the updater doesn't check for php compatibility. I'm fixing this at https://github.com/nextcloud/server/pull/24416.

So yeah, the 1.7.1 fixed some 7.2 syntax errors for those incorrect installations. But the app formally still dropped the 7.2 support. Hence I'm even a bit surprised that your instance magically does the php compatibility check. I wanted to add this as https://github.com/nextcloud/server/pull/24398.

Did you update the app manually or via the app store?

**Comment by uli-heller** [comment]
Good Morning @ChristophWurst ,

sorry, I thought 1.7.1 fixes all 7.2 issues. I guess I better upgrade to ubuntu-20.04 and don't care about php-7.2 any more.

I installed 1.7.0 and 1.7.1 manually, meaning: unpack the tar.gz within the apps folder and activate the app.

Somehow, I managed to activate mail in previous versions. That's how I stumbled over #4063 for example. Later, the actvate button suddenly was grayed out and the compatibiliry warning shows up:

![image](https://user-images.githubusercontent.com/1677414/101136384-8a6ff580-360d-11eb-9201-a64acdf7afb6.png)

> Did you update the app manually or via the app store?

Manually

**Comment by ChristophWurst** [comment]
> sorry, I thought 1.7.1 fixes all 7.2 issues. I guess I better upgrade to ubuntu-20.04 and don't care about php-7.2 any more.

yep. we dropped 7.2 for good reason: https://www.php.net/supported-versions.php. I just didn't know about the implications with how Nextcloud handles app store updates.

**Comment by ChristophWurst** [comment]
> Somehow, I managed to activate mail in previous versions. That's how I stumbled over #4063 for example. Later, the actvate button suddenly was grayed out and the compatibiliry warning shows up:

That warning is actually good :)

I think with my two linked PRs the situation should be a lot better

1) Users won't get an (auto) update to an incompatible version
2) Manual upgrades to an incompatible version will be impossible -> admins can revert to an older release before anything bad happens

**Comment by uli-heller** [comment]
So you're fixing this as well? https://apps.nextcloud.com/apps/mail

![image](https://user-images.githubusercontent.com/1677414/101140738-a7a7c280-3613-11eb-9d5a-3cae3dab6561.png)

**Comment by ChristophWurst** [comment]
What exactly? The app store only groups by Nextcloud version. 1.5.x runs on NC20, php7.2+, 1.6.x+ runs on NC20, php7.3+

**Comment by ChristophWurst** [comment]
So no, I'm not fixing the app store. But feel free to raise a ticket there to include the php restrictions in the overview. I highly doubt anyone would add this, though, as it brings a lot of complexity.

**Comment by uli-heller** [comment]
So I cannot go to the app store, look at the mail app, go to the downloads and try to download the mail app version that shows up next to my nextcloud version? I mean: For "Nextcloud 19", I wouldn't probably even try in install anything newer than 1.4.1. Currently, for "Nextcloud 20" I would expect the versiobn 1.7.1 to work. Isn't there a "flag" within the mail app declaring the compatibility to a certain nextcloud version which is used to display the correct version within the app store?

In case you cannot see the screenshot, here table:

|Nextcloud version|Mail version| ... |
|-------------|----|----|
| Nextcloud 20 | 1.7.1 | ... |
| Nextcloud 19 | 1.4.1 | ... |
| Nextcloud 18 | 1.4.1 | ... |

**Comment by uli-heller** [comment]
Sorry, I didn't read your response carefully enough. No, I don't like the PHP version to show up. I just want to be able to install the version that's mentioned in the list to be "compatible". So when Nextcloud 20 supports PHP 7.2, all apps compatible with nextcloud 20 should support PHP 7.2. But that's just my personal opinion. In the end I don't care too much
