### ISSUE TITLE
Upodateproblem 1.9.0 up to 1.9.1

### ISSUE THREAD

**Issue by ThorstenUm** [nextcloud/mail#4184]
On Nextcloud 20.0.2 i can't update from 1.9.0 up to 1.9.1.

In Logging i find:
`GuzzleHttp\Exception\ConnectException: cURL error 28: Operation timed out after 300000 milliseconds with 3507577 out of 15797746 bytes received (see https://curl.haxx.se/libcurl/c/libcurl-errors.html)`

and

`Error: InvalidArgumentException: Dataset must contain samples with exactly 4 dimensions, 3 given. at <<closure>>

 0. /var/www/html/nextcloud/apps/mail/vendor/rubix/ml/src/Classifiers/GaussianNB.php line 298
    Rubix\ML\Specifications\DatasetHasDimensionality->check()`

Can you help me?

**Comment by ChristophWurst** [comment]
> GuzzleHttp\Exception\ConnectException: cURL error 28: Operation timed out after 300000 milliseconds with 3507577 out of 15797746 bytes received (see https://curl.haxx.se/libcurl/c/libcurl-errors.html)

Unrelated to Mail.

> `Error: InvalidArgumentException: Dataset must contain samples with exactly 4 dimensions, 3 given. at <>
> 
>     1. /var/www/html/nextcloud/apps/mail/vendor/rubix/ml/src/Classifiers/GaussianNB.php line 298
>        Rubix\ML\Specifications\DatasetHasDimensionality->check()`

I'm preparing a fix for that at the moment. But this code is certainly not run durnig the update. This is unrelated.

For the update problem please consult https://help.nextcloud.com/c/support/7
