### ISSUE TITLE
New emails showing sender and subject from deleted emails

### ISSUE THREAD

**Issue by northorsouth** [nextcloud/mail#4198]
### Expected behavior
Tell us what should happen
A new email is received, the sender, icon and subject appears in the inbox list. The full email body is displayed when clicked.

### Actual behavior
Tell us what happens instead
A new email is received, the sender, icon and subject that appears is from an email that was previously deleted. When clicked, the full view shows the same incorrect sender, subject and icon, however, the correct body from the new email is displayed. The emails are displayed correctly only when the account is removed and re-added. The emails are also displayed correctly if I access the same IMAP server through mutt.

### Mail app

**Mail app version:** (see apps admin page, e.g. 0.5.3)
1.7.1

**Mailserver or service:** (e.g. Outlook, Yahoo, Gmail, Exchange,...)
Protonmail, accessed through hydroxide: https://github.com/emersion/hydroxide

### Server configuration

**Operating system**: (e.g. Debian 8)
Debian 10

**Web server:** (e.g. Apache, Nginx,...)
Apache, behind an Nginx reverse proxy

**Database:** (e.g. MariaDB, SQLite or PostgreSQL)
MariaDB, hosted in a docker

**PHP version:** (e.g. 7.0)
7.3.19

**Nextcloud Version:** (see admin page, e.g. 13.0.2)
20.0.2

#### Client configuration
**Browser:** (e.g. Firefox 48)
Firefox 83

**Operating system:** (e.g. Arch Linux)
Windows 10

**Comment by northorsouth** [comment]
I also can't load my Trash folder, if that's related at all. It just loads forever and says it's indexing. And this message appears in the logs: `Can not get messages from mailbox Trash: Error when communicating with the mail server.`

**Comment by jim-perkins** [comment]
I have similar behaviour except I could empty my trash.  Whenever an email is in the inbox it has the wrong sender listed.  the body of the message is correct as is the source.  my nextcloud installation is up 2 date along with all apps

**Comment by jim-perkins** [comment]
I repaired my installation by running this on my database and re configuring the app  .  I peeked at oc_mail_accounts before I dropped it to refresh my memory of the account configuration.  

DROP TABLE oc_mail_accounts;
DROP TABLE oc_mail_aliases;
DROP TABLE oc_mail_coll_addresses;
DROP TABLE oc_mail_attachments;
DROP TABLE oc_mail_mailboxes;
DROP TABLE oc_mail_messages;
DROP TABLE oc_mail_recipients;

https://github.com/nextcloud/mail/blob/master/doc/developer.md#resetting-the-app

**Comment by northorsouth** [comment]
I switched to Rainloop since posting this, and I'm actually seeing similar behavior. So I'm now assuming this is Hydroxide, rather than Nextcloud Mail.

**Comment by jim-perkins** [comment]
yea IDK about rainloop and hyrdroxide. My setup is Ubuntu_server_20.04/postfix/dovecot/roundcube.  within Roundcube the messages looks fine.  In nextcloud_mail the sender was wrong .  It was a github notification address that kept showing as 'from'.  If the issue comes back I will ask for info on how to troubleshoot which is impossible now as I blew away all the related tables.  thanks

**Comment by jim-perkins** [comment]
Let me know how this should be troubleshot . I am guessing the special character in the subject has something to do with it but I am probably mistaken.  thanks

Attached are 3 screenshots.  

  1.  Email that is getting mixed up into nextcloud_mail.  I noticed the subject has some extended characters "Subject: Renewal by Andersen â€“ Window Consultation" .  Also notice spamassassin tagged this email.
  2. The way the above listed message effected nextcloud_mail
  3.   the way the effected email should have been shown.



![mail_where_wrong_sender_came_from](https://user-images.githubusercontent.com/6559269/103677549-11cfc200-4f48-11eb-9807-52ce47565590.png)
![nextcloud_mail_wrong_sender](https://user-images.githubusercontent.com/6559269/103677551-12685880-4f48-11eb-9e4f-aa2fec851cb6.png)
![what_email_should_have_shown](https://user-images.githubusercontent.com/6559269/103677553-12685880-4f48-11eb-9772-e7b6940b701f.png)

**Comment by jim-perkins** [comment]
https://scan.nextcloud.com/
Rating  A+
https://nextcloud.redacted.com
**Running Nextcloud 20.0.4.0**
 Latest patch level
 Major version still supported
Scanned at 2021-01-05 17:42:37

Running Mail app version
**Mail	1.7.2**

PHP
Version: 7.4.13
Memory Limit: 512 MB
Max Execution Time: 3600
Upload max size: 2 MB

Mysql
Type: mysql
Version: 5.7.32
Size: 108.1 MB

Ubuntu 18.04.5 LTS ( in a KVM/libvirt VM )
Operating System:	Linux 5.4.0-59-generic x86_64
CPU:	Westmere E56xx/L56xx/X56xx (IBRS update) (4 cores)
Memory:	7.77 GB

**Comment by ChristophWurst** [comment]
is this the same problem as https://github.com/nextcloud/mail/issues/4412?
