### ISSUE TITLE
Several keys unresponsive after using Backspace (using Firefox)

### ISSUE THREAD

**Issue by joober** [nextcloud/mail#4208]
### Expected behavior
When I press Backspace, the character I just typed should be deleted. Nothing further should happen.

### Actual behavior
When I press Backspace, the character I just typed is deleted but after that, Backspace ceases to work. Also, the Enter and Delete key input gets ignored by the editor.
This is similar to [https://github.com/nextcloud/mail/issues/4104]

### Mail app

**Mail app version:** 1.4.2

**Mailserver or service:** Local MTA (Postfix + Dovecot) on Nextcloud server

### Server configuration

**Operating system**: Ubuntu 16.04.7 LTS

**Web server:** Apache/2.4.18 (Ubuntu)

**Database:** MariaDB (5.7.32-0ubuntu0.16.04.1)

**PHP version:** 7.3.24-3+ubuntu16.04.1+deb.sury.org+1

**Nextcloud Version:** 19.0.5

#### Client configuration
**Browser:** Firefox 83.0 (64-bit)

**Operating system:** Ubuntu 20.04 LTS

#### Error in Firefox Web Console:
Uncaught CKEditorError: a is undefined
    <anonymous> VueJS
    value range.js:348
    value deletecommand.js:107
    value model.js:805
    value model.js:231
    value deletecommand.js:76
    decorate observablemixin.js:255
    fire emittermixin.js:209
    e observablemixin.js:259
    value commandcollection.js:68
    value editor.js:288
    value delete.js:55
    fire emittermixin.js:209
    c deleteobserver.js:87
    u deleteobserver.js:50
    fire emittermixin.js:209
    value domeventobserver.js:96
    value keyobserver.js:28
    value domeventobserver.js:79
    fire emittermixin.js:209
    r emittermixin.js:235
    attach emittermixin.js:193
    listenTo emittermixin.js:59
    value domeventobserver.js:77
    value domeventobserver.js:76
    value view.js:286
    value ballooneditorui.js:86
    value ballooneditor.js:217
    promise callback*value/< ballooneditor.js:216
    value ballooneditor.js:201
    mounted ckeditor.js:64
    VueJS 18
    init vue-router.esm.js:2795
    init vue-router.esm.js:2794
    updateRoute vue-router.esm.js:2223
    transitionTo vue-router.esm.js:2086
    confirmTransition vue-router.esm.js:2208
    r vue-router.esm.js:1892
    ge vue-router.esm.js:1903
    confirmTransition vue-router.esm.js:2311
    r vue-router.esm.js:1892
    r vue-router.esm.js:1896
    p vue-router.esm.js:2188
    ve vue-router.esm.js:1970
    p vue-router.esm.js:2169
    r vue-router.esm.js:1895
    r vue-router.esm.js:1899
    ge vue-router.esm.js:1903
    confirmTransition vue-router.esm.js:2196
    transitionTo vue-router.esm.js:2083
    push vue-router.esm.js:2508
    push vue-router.esm.js:2826
    push vue-router.esm.js:2825
    onNewMessage Navigation.vue:137
    VueJS 4
    click AppNavigationNew.js:1
    VueJS 3
mail.js:1:64080

**Comment by ChristophWurst** [comment]
Ref https://github.com/nextcloud/mail/pull/4166#issuecomment-740100845

**Comment by alexanderdd** [comment]
@ChristophWurst remove label "to triage" and add "to develop"? Add "backport to NC19" in title?

looks like 20% of servers still run NC19 (https://ncpw.mdns.eu/ ), and it is officially supported until 2021-06 (https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) so it would be nice to get this fix =)

**Comment by ChristophWurst** [comment]
Feel free to patch this on your instance. You have full access to the source, the fixes and everything else you need

**Comment by alexanderdd** [comment]
@ChristophWurst thank you.
Does that mean you won't backport it to 19? In that case, you could close this issue as "wontfix"

**Comment by StCyr** [comment]
ping @ChristophWurst

**Comment by ChristophWurst** [comment]
wontfix is when we decide against a feature or fix, but that isn't the case. we simply don't have the resources to do it. so this remains open until someone jumps in and helps.
