### ISSUE TITLE
Can't upload attachment

### ISSUE THREAD

**Issue by st3iny** [nextcloud/mail#4217]
### Expected behavior
Uploading attachments should add them to the mail.

### Actual behavior
The attachments are not added and an error is shown in the console.

### Steps to reproduce
1. Compose a new mail.
2. Add recipient, subject and some text.
3. Upload attachment from local file system.

#### Console Log
```
xhr.js:177 POST http://localhost/index.php/apps/mail/api/attachments 400 (Bad request)
dispatchXhrRequest @ xhr.js:177
xhrAdapter @ xhr.js:13
dispatchRequest @ dispatchRequest.js:52
Promise.then (async)
request @ Axios.js:61
Axios.<computed> @ Axios.js:87
wrap @ bind.js:9
uploadLocalAttachment @ AttachmentService.js:67
(anonymous) @ ComposerAttachments.vue?674f:124
(anonymous) @ _baseConvert.js:34
(anonymous) @ _baseMap.js:17
(anonymous) @ _createBaseEach.js:24
baseMap @ _baseMap.js:16
map @ map.js:50
wrapper @ _createHybrid.js:87
(anonymous) @ _baseConvert.js:455
wrapper @ _createHybrid.js:87
onLocalAttachmentSelected @ ComposerAttachments.vue?674f:132
invokeWithErrorHandling @ vue.runtime.esm.js:1854
invoker @ vue.runtime.esm.js:2179
original._wrapper @ vue.runtime.esm.js:6917

ConsoleLogger.js:54 [ERROR] mail: could not upload all attachments {app: "mail", uid: "admin", error: Error: Request failed with status code 400
    at createError (http://localhost/dev_apps/mail/js/ma…}
log @ ConsoleLogger.js:54
error @ ConsoleLogger.js:80
(anonymous) @ ComposerAttachments.vue?674f:134
Promise.catch (async)
onLocalAttachmentSelected @ ComposerAttachments.vue?674f:133
invokeWithErrorHandling @ vue.runtime.esm.js:1854
invoker @ vue.runtime.esm.js:2179
original._wrapper @ vue.runtime.esm.js:6917

ConsoleLogger.js:42 [DEBUG] mail: attachments uploaded {app: "mail", uid: "admin"}
```

#### Response from the server:
```json
{
  "status": "fail",
  "data": {
    "message": "no file attached",
    "type": "OCA\\Mail\\Exception\\ClientException"
  }
}
```

### Mail app

**Mail app version:** master

**Mailserver or service:** antespi/docker-imap-devel

### Server configuration

**Web server:** Apache

**Database:** MariaDB

**PHP version:** 7.4

**Nextcloud Version:** master

**Comment by st3iny** [comment]
The error is also thrown when testing #3950 but not in #3998.

**Comment by StCyr** [comment]
works good here 😕

**Comment by st3iny** [comment]
I just updated all of the php dependencies via composer v1 and uploading attachments is working again. I haven't updated those in a long time due to the dropped pear repository support in composer v2 (and I was too lazy to manually install composer v1).

**Comment by ChristophWurst** [comment]
ah so it was only locally due to missing dependencies?

**Comment by st3iny** [comment]
Yes. I only encountered this error on my local dev instance and now it's gone.
