### ISSUE TITLE
POP3 Support

### ISSUE THREAD

**Issue by triforce** [nextcloud/mail#422]
Are there any plans for POP3 support?

**Comment by ChristophWurst** [comment]
No, sorry. We do plan to support the POP protocol in this app.

**Comment by MuhammadShaban** [comment]
is there a release date for this?

**Comment by ChristophWurst** [comment]
> No, sorry. We do plan to support the POP protocol in this app.

Typo: we do *not* plan to support it.

**Comment by MuhammadShaban** [comment]
@ChristophWurst
oh, i'm very sad to hear that
thanks at all
