### ISSUE TITLE
Attachments will not download or save to files.

### ISSUE THREAD

**Issue by ericvandamme** [nextcloud/mail#4223]
### Expected behavior
Email attachments should allow download or save to files as expected.

This behaviour was working as expected before the latest update.

### Actual behavior
When trying to download, a simple JSON is returned
`{"status":"error","message":"Server error","data":[],"code":0}`

Recorded on the Nextcloud Log:
```json
{
  "reqId": "X9Lmr96eZMLxZtBb-WZNhwAATQM",
  "level": 3,
  "time": "2020-12-11T03:25:36+00:00",
  "remoteAddr": "192.168.1.166",
  "user": "USERNAME",
  "app": "mail",
  "method": "GET",
  "url": "/apps/mail/api/accounts/2/folders/SU5CT1g=/messages/90879/attachment/2",
  "message": {
    "Exception": "Horde_Imap_Client_Exception_ServerResponse",
    "Message": "IMAP error reported by server.",
    "Code": 0,
    "Trace": [
      {
        "file": "/var/www/html/apps/mail/vendor/pear-pear.horde.org/Horde_Imap_Client/Horde/Imap/Client/Socket.php",
        "line": 4314,
        "function": "_getLine",
        "class": "Horde_Imap_Client_Socket",
        "type": "->",
        "args": [
          {
            "data": {
              "modseqs": [],
              "modseqs_nouid": []
            },
            "fetch": {
              "__class__": "Horde_Imap_Client_Fetch_Results"
            },
            "__class__": "Horde_Imap_Client_Interaction_Pipeline"
          }
        ]
      },
      {
        "file": "/var/www/html/apps/mail/vendor/pear-pear.horde.org/Horde_Imap_Client/Horde/Imap/Client/Socket.php",
        "line": 4242,
        "function": "_sendCmdChunk",
        "class": "Horde_Imap_Client_Socket",
        "type": "->",
        "args": [
          {
            "data": {
              "modseqs": [],
              "modseqs_nouid": []
            },
            "fetch": {
              "__class__": "Horde_Imap_Client_Fetch_Results"
            },
            "__class__": "Horde_Imap_Client_Interaction_Pipeline"
          },
          [
            {
              "debug": [],
              "literalplus": true,
              "literal8": false,
              "on_error": null,
              "on_success": null,
              "pipeline": {
                "data": {
                  "modseqs": [],
                  "modseqs_nouid": []
                },
                "fetch": {
                  "__class__": "Horde_Imap_Client_Fetch_Results"
                },
                "__class__": "Horde_Imap_Client_Interaction_Pipeline"
              },
              "response": {
                "tag": "5",
                "responseCode": null,
                "status": 1,
                "token": {
                  "__class__": "Horde_Imap_Client_Tokenize"
                },
                "__class__": "Horde_Imap_Client_Interaction_Server_Tagged"
              },
              "tag": "5",
              "__class__": "Horde_Imap_Client_Interaction_Command"
            }
          ]
        ]
      },
      {
        "file": "/var/www/html/apps/mail/vendor/pear-pear.horde.org/Horde_Imap_Client/Horde/Imap/Client/Socket.php",
        "line": 1234,
        "function": "_sendCmd",
        "class": "Horde_Imap_Client_Socket",
        "type": "->",
        "args": [
          {
            "data": {
              "modseqs": [],
              "modseqs_nouid": []
            },
            "fetch": {
              "__class__": "Horde_Imap_Client_Fetch_Results"
            },
            "__class__": "Horde_Imap_Client_Interaction_Pipeline"
          }
        ]
      },
      {
        "file": "/var/www/html/apps/mail/vendor/pear-pear.horde.org/Horde_Imap_Client/Horde/Imap/Client/Base.php",
        "line": 1051,
        "function": "_openMailbox",
        "class": "Horde_Imap_Client_Socket",
        "type": "->",
        "args": [
          {
            "__class__": "Horde_Imap_Client_Mailbox"
          },
          1
        ]
      },
      {
        "file": "/var/www/html/apps/mail/vendor/pear-pear.horde.org/Horde_Imap_Client/Horde/Imap/Client/Base.php",
        "line": 2511,
        "function": "openMailbox",
        "class": "Horde_Imap_Client_Base",
        "type": "->",
        "args": [
          {
            "__class__": "Horde_Imap_Client_Mailbox"
          },
          1
        ]
      },
      {
        "file": "/var/www/html/apps/mail/vendor/pear-pear.horde.org/Horde_Imap_Client/Horde/Imap/Client/Base.php",
        "line": 2478,
        "function": "_fetchWrapper",
        "class": "Horde_Imap_Client_Base",
        "type": "->",
        "args": [
          {
            "__class__": "Horde_Imap_Client_Mailbox"
          },
          {
            "__class__": "Horde_Imap_Client_Fetch_Query"
          },
          {
            "ids": {
              "duplicates": false,
              "__class__": "Horde_Imap_Client_Ids"
            }
          }
        ]
      },
      {
        "file": "/var/www/html/apps/mail/lib/Attachment.php",
        "line": 71,
        "function": "fetch",
        "class": "Horde_Imap_Client_Base",
        "type": "->",
        "args": [
          {
            "__class__": "Horde_Imap_Client_Mailbox"
          },
          {
            "__class__": "Horde_Imap_Client_Fetch_Query"
          },
          {
            "ids": {
              "duplicates": false,
              "__class__": "Horde_Imap_Client_Ids"
            }
          }
        ]
      },
      {
        "file": "/var/www/html/apps/mail/lib/Attachment.php",
        "line": 44,
        "function": "load",
        "class": "OCA\\Mail\\Attachment",
        "type": "->",
        "args": []
      },
      {
        "file": "/var/www/html/apps/mail/lib/Mailbox.php",
        "line": 303,
        "function": "__construct",
        "class": "OCA\\Mail\\Attachment",
        "type": "->",
        "args": [
          {
            "cacheFields": {
              "1": "HICstruct",
              "8": "HIChdrs",
              "9": "HICenv",
              "10": "HICflags",
              "11": "HICdate",
              "12": "HICsize"
            },
            "changed": true,
            "statuscache": true,
            "__class__": "Horde_Imap_Client_Socket"
          },
          {
            "__class__": "Horde_Imap_Client_Mailbox"
          },
          90879,
          "2"
        ]
      },
      {
        "file": "/var/www/html/apps/mail/lib/Controller/MessagesController.php",
        "line": 367,
        "function": "getAttachment",
        "class": "OCA\\Mail\\Mailbox",
        "type": "->",
        "args": [
          90879,
          "2"
        ]
      },
      {
        "file": "/var/www/html/lib/private/AppFramework/Http/Dispatcher.php",
        "line": 170,
        "function": "downloadAttachment",
        "class": "OCA\\Mail\\Controller\\MessagesController",
        "type": "->",
        "args": [
          2,
          "SU5CT1g=",
          90879,
          "2"
        ]
      },
      {
        "file": "/var/www/html/lib/private/AppFramework/Http/Dispatcher.php",
        "line": 100,
        "function": "executeController",
        "class": "OC\\AppFramework\\Http\\Dispatcher",
        "type": "->",
        "args": [
          {
            "__class__": "OCA\\Mail\\Controller\\MessagesController"
          },
          "downloadAttachment"
        ]
      },
      {
        "file": "/var/www/html/lib/private/AppFramework/App.php",
        "line": 137,
        "function": "dispatch",
        "class": "OC\\AppFramework\\Http\\Dispatcher",
        "type": "->",
        "args": [
          {
            "__class__": "OCA\\Mail\\Controller\\MessagesController"
          },
          "downloadAttachment"
        ]
      },
      {
        "file": "/var/www/html/lib/private/AppFramework/Routing/RouteActionHandler.php",
        "line": 47,
        "function": "main",
        "class": "OC\\AppFramework\\App",
        "type": "::",
        "args": [
          "OCA\\Mail\\Controller\\MessagesController",
          "downloadAttachment",
          {
            "__class__": "OC\\AppFramework\\DependencyInjection\\DIContainer"
          },
          {
            "accountId": "2",
            "folderId": "SU5CT1g=",
            "messageId": "90879",
            "attachmentId": "2",
            "_route": "mail.messages.downloadAttachment"
          }
        ]
      },
      {
        "function": "__invoke",
        "class": "OC\\AppFramework\\Routing\\RouteActionHandler",
        "type": "->",
        "args": [
          {
            "accountId": "2",
            "folderId": "SU5CT1g=",
            "messageId": "90879",
            "attachmentId": "2",
            "_route": "mail.messages.downloadAttachment"
          }
        ]
      },
      {
        "file": "/var/www/html/lib/private/Route/Router.php",
        "line": 297,
        "function": "call_user_func",
        "args": [
          {
            "__class__": "OC\\AppFramework\\Routing\\RouteActionHandler"
          },
          {
            "accountId": "2",
            "folderId": "SU5CT1g=",
            "messageId": "90879",
            "attachmentId": "2",
            "_route": "mail.messages.downloadAttachment"
          }
        ]
      },
      {
        "file": "/var/www/html/lib/base.php",
        "line": 1010,
        "function": "match",
        "class": "OC\\Route\\Router",
        "type": "->",
        "args": [
          "/apps/mail/api/accounts/2/folders/SU5CT1g=/messages/90879/attachment/2"
        ]
      },
      {
        "file": "/var/www/html/index.php",
        "line": 37,
        "function": "handleRequest",
        "class": "OC",
        "type": "::",
        "args": []
      }
    ],
    "File": "/var/www/html/apps/mail/vendor/pear-pear.horde.org/Horde_Imap_Client/Horde/Imap/Client/Socket.php",
    "Line": 4602,
    "CustomMessage": "--"
  },
  "userAgent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:83.0) Gecko/20100101 Firefox/83.0",
  "version": "19.0.6.2",
  "id": "5fd2e7b696d34"
}
```

Dovecot doesn't record anything unusual:
```
Dec 10 22:33:03 SERVERNAME dovecot: imap-login: Login: user=<EMAILADDRESS>, method=PLAIN, rip=192.168.1.46, lip=192.168.1.45, mpid=100126, TLS, session=<SESSION>
Dec 10 22:33:03 SERVERNAME dovecot: imap(EMAILADDRESS)<100126><SESSION>: Logged out in=26 out=508 deleted=0 expunged=0 trashed=0 hdr_count=0 hdr_bytes=0 body_count=0 body_bytes=0
Dec 10 22:33:03 SERVERNAME dovecot: imap-login: Login: user=<EMAILADDRESS>, method=PLAIN, rip=192.168.1.46, lip=192.168.1.45, mpid=100128, TLS, session=<SESSION>
Dec 10 22:33:03 SERVERNAME dovecot: imap(EMAILADDRESS)<100128><SESSION>: Logged out in=48 out=533 deleted=0 expunged=0 trashed=0 hdr_count=0 hdr_bytes=0 body_count=0 body_bytes=0
```

### Mail app

**Mail app version:** 1.4.2

**Mailserver or service:** Local Dovecot IMAP Service

### Server configuration

**Operating system**: Debian 10 Buster

**Web server:** Apache

**Database:** Different instances are running either MySQL or PostgreSQL 12.5

**PHP version:** 7.3.19

**Nextcloud Version:** 19.0.6 and 19.0.5

#### Client configuration
**Browser:** Firefox 83.0 and Chrome 87.0.4280.88

**Operating system:** Windows 10

**Comment by ericvandamme** [comment]
Probably also worth noting, if "Viewing Source" within Nextcloud, the attachment data can be viewed without any issue. An unusually ambitious user could copy the BASE64 encoded attachment and convert it to a binary file to open the attachment.

**Comment by H0ST4L3X** [comment]
+1
Same here.
Though we are using a third-party mail exchange, where logs are not available (for now).
Viewing and downloading attachments used to work until recently.

**Mail app**
Mail app version: 1.4.2
Mailserver or service: 3rd party

**Server configuration**
Operating system: Ubuntu 20.04.1 LTS
Web server: nginx
Database: mariadb-server-10.5
PHP version: PHP 7.4.3
Nextcloud Version: 19.0.4

**Client configuration**
Browser: Firefox 83.0
Operating system: Linux & Windows 10

**Comment by ChristophWurst** [comment]
> ```json
> "2"
> ```

@ericvandamme that is the mime part ID used. When inspecting the message, can you confirm that the message is the second part?

Otherwise it would definitely help to know the IMAP logs.

The Nextcloud mail app offers an extensive logging system to make it easier identifying and tracking down bugs. Please enable [debug mode](https://docs.nextcloud.com/server/stable/developer_manual/general/devenv.html#enabling-debug-mode) and set the log [level to debug](https://docs.nextcloud.com/server/stable/admin_manual/configuration_server/logging_configuration.html) in your admin settings. Then, try to reproduce your issue and take another look at `data/nextcloud.log` and `data/horde_imap.log`.

**Comment by ericvandamme** [comment]
Assuming it starts counting from 0, it does appear to be attachment 2.

I included the Nextcloud and Horde logs; as well as the response in the browser, and the email source of the message in question. 

[nextcloud.log](https://github.com/nextcloud/mail/files/5689118/nextcloud.log)
[server-response.log](https://github.com/nextcloud/mail/files/5689119/server-response.log)
[horde.log](https://github.com/nextcloud/mail/files/5689120/horde.log)
[email_source.txt](https://github.com/nextcloud/mail/files/5689121/email_source.txt)

**Comment by laurentiu2** [comment]
Can confirm, it appeared a few days before 19.0.6 and the update did not solve it.
ubuntu 18.0.4/apache2.4.29/php 7.4.13/NC19.0.6/firefox83.0

[mail] Error: Horde_Imap_Client_Exception_ServerResponse: IMAP error reported by server. at <<closure>>

 0. /var/www/nextcloud/apps/mail/vendor/pear-pear.horde.org/Horde_Imap_Client/Horde/Imap/Client/Socket.php line 4314
    Horde_Imap_Client_Socket->_getLine(Horde_Imap_Clien ... }})
 1. /var/www/nextcloud/apps/mail/vendor/pear-pear.horde.org/Horde_Imap_Client/Horde/Imap/Client/Socket.php line 4242
    Horde_Imap_Client_Socket->_sendCmdChunk(Horde_Imap_Clien ... }}, [Horde_Imap_Clie ... }])
 2. /var/www/nextcloud/apps/mail/vendor/pear-pear.horde.org/Horde_Imap_Client/Horde/Imap/Client/Socket.php line 1234
    Horde_Imap_Client_Socket->_sendCmd(Horde_Imap_Clien ... }})
 3. /var/www/nextcloud/apps/mail/vendor/pear-pear.horde.org/Horde_Imap_Client/Horde/Imap/Client/Base.php line 1051
    Horde_Imap_Client_Socket->_openMailbox(Horde_Imap_Client_Mailbox {}, 1)
 4. /var/www/nextcloud/apps/mail/vendor/pear-pear.horde.org/Horde_Imap_Client/Horde/Imap/Client/Base.php line 2511
    Horde_Imap_Client_Base->openMailbox(Horde_Imap_Client_Mailbox {}, 1)
 5. /var/www/nextcloud/apps/mail/vendor/pear-pear.horde.org/Horde_Imap_Client/Horde/Imap/Client/Base.php line 2478
    Horde_Imap_Client_Base->_fetchWrapper(Horde_Imap_Client_Mailbox {}, Horde_Imap_Client_Fetch_Query {}, {ids: Horde_Imap ... }})
 6. /var/www/nextcloud/apps/mail/lib/Attachment.php line 71
    Horde_Imap_Client_Base->fetch(Horde_Imap_Client_Mailbox {}, Horde_Imap_Client_Fetch_Query {}, {ids: Horde_Imap ... }})
 7. /var/www/nextcloud/apps/mail/lib/Attachment.php line 44
    OCA\Mail\Attachment->load()
 8. /var/www/nextcloud/apps/mail/lib/Mailbox.php line 303
    OCA\Mail\Attachment->__construct(Horde_Imap_Clien ... e}, Horde_Imap_Client_Mailbox {}, 10778, "1.3")
 9. /var/www/nextcloud/apps/mail/lib/Controller/MessagesController.php line 367
    OCA\Mail\Mailbox->getAttachment(10778, "1.3")
10. /var/www/nextcloud/lib/private/AppFramework/Http/Dispatcher.php line 170
    OCA\Mail\Controller\MessagesController->downloadAttachment(1, "SU5CT1g=", 10778, "1.3")
11. /var/www/nextcloud/lib/private/AppFramework/Http/Dispatcher.php line 100
    OC\AppFramework\Http\Dispatcher->executeController(OCA\Mail\Controller\MessagesController {}, "downloadAttachment")
12. /var/www/nextcloud/lib/private/AppFramework/App.php line 137
    OC\AppFramework\Http\Dispatcher->dispatch(OCA\Mail\Controller\MessagesController {}, "downloadAttachment")
13. /var/www/nextcloud/lib/private/AppFramework/Routing/RouteActionHandler.php line 47
    OC\AppFramework\App::main("OCA\\Mail\\Cont ... r", "downloadAttachment", OC\AppFramework\ ... {}, {accountId: "1", ... "})
14. <<closure>>
    OC\AppFramework\Routing\RouteActionHandler->__invoke({accountId: "1", ... "})
15. /var/www/nextcloud/lib/private/Route/Router.php line 297
    call_user_func(OC\AppFramework\ ... {}, {accountId: "1", ... "})
16. /var/www/nextcloud/lib/base.php line 1010
    OC\Route\Router->match("/apps/mail/api/ ... 3")
17. /var/www/nextcloud/index.php line 37
    OC::handleRequest()

GET /index.php/apps/mail/api/accounts/1/folders/SU5CT1g=/messages/10778/attachment/1.3

**Comment by Benance** [comment]
Hello
Same problem for me since I upgraded the app in V1.4.2 a few days ago. I'm unable to open attachments.
OS: debian 10
Nextcloud: 19.0.3
php: 7.3.19

**Comment by ChristophWurst** [comment]
@Benance something is fishy with your server

> C: 4 AUTHENTICATE PLAIN [INITIAL CLIENT RESPONSE (username: eric.vandamme@example.org)]
> S: 4 OK [CAPABILITY IMAP4rev1 SASL-IR LOGIN-REFERRALS ID ENABLE IDLE SORT SORT=DISPLAY THREAD=REFERENCES THREAD=REFS THREAD=ORDEREDSUBJECT MULTIAPPEND URL-PARTIAL CATENATE UNSELECT CHILDREN NAMESPACE UIDPLUS LIST-EXTENDED I18NLEVEL=1 CONDSTORE QRESYNC ESEARCH ESORT SEARCHRES WITHIN CONTEXT=SEARCH LIST-STATUS BINARY MOVE SNIPPET=FUZZY LITERAL+ NOTIFY SPECIAL-USE ACL RIGHTS=texk] Logged in
> >> Command 4 took 0.0299 seconds.
> C: 5 EXAMINE INBOX (QRESYNC (73233 1599))
> S: 5 BAD Error in IMAP command EXAMINE: QRESYNC not enabled (0.001 + 0.000 secs).

it specifies the QRESYNC capability but when that is used, the server rejects.

**Comment by ericvandamme** [comment]
What I noticed was it logged in twice. The first login, the IMAP client enabled QRESYNC. The second login, it did not.

I logged in using Telnet, entered the commands in the log without the logout that occurs in the middle, and the command executed just fine.

**Comment by ericvandamme** [comment]
Want to mention I recently updated to Nextcloud 20.0.4 and Mail 1.7.2 and the issue has went away.
