### ISSUE TITLE
cant create account when using Nexcloud Docker image

### ISSUE THREAD

**Issue by sch0etti** [nextcloud/mail#4236]
Good evening everybody,

in a local test installation of Nextcloud in a Lampp stack the mail app works without any problems.
However, in my productive Docker container (official, latest version) I have the following problem:
I can't set up a mail account with my own mail server.
I use Starttls for IMAP and SMTP. 
The following appears in the Nextcloud log:

{"reqId":"T2ch9b1ys9Dnd6LTarsw","level":3,"time":"2020-12-13T21:25:08+00:00","remoteAddr":"172.x.x.x","user":"myuser","app":"mail","method":"POST","url":"/apps/mail/api/accounts","message":"Creating account failed: Could not connect to IMAP host mail.mydomain.net:143: Could not open secure TLS connection to the IMAP server.","userAgent":"Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/86.0.4240.185 Safari/537.36","version":"20.0.3.2","id":"5fd68792c14d3"}

The horde_imap.log looks like the following: 
------------------------------
>> Sun, 13 Dec 2020 21:35:12 +0000
>> Connection to: imap://mail.mydomain.net/
>> Server connection took 0.0497 seconds.
S: * OK [CAPABILITY IMAP4rev1 LITERAL+ SASL-IR LOGIN-REFERRALS ID ENABLE IDLE STARTTLS LOGINDISABLED] Dovecot ready.
C: 1 STARTTLS
S: 1 OK Begin TLS negotiation now.
>> Command 1 took 0.0147 seconds.

This setting in my nexctloud config did not help:
 'app.mail.verify-tls-peer' => false,

Does anyone have any idea what I am doing wrong? Am I perhaps missing a php plugin?
OpenSSH is active according to phpinfo.

**Comment by ChristophWurst** [comment]
> Creating account failed: Could not connect to IMAP host mail.mydomain.net:143: Could not open secure TLS connection to the IMAP server.

So yes, indeed a TLS issues but hard to tell what exactly.

**Comment by LostinSpacetime** [comment]
I get the same error on a local installation of Nextcloud 20.0.4 on Ubuntu 18.04

**Comment by LostinSpacetime** [comment]
Adding 'app.mail.verify-tls-peer' => false to config file fixed it.
