### ISSUE TITLE
Can't enable Mail on 20.0.3

### ISSUE THREAD

**Issue by danvilar** [nextcloud/mail#4247]
### Expected behavior
Enabling the mail app.

### Actual behavior
![image](https://user-images.githubusercontent.com/11343743/102218854-8f1e8e80-3ed6-11eb-8ba0-f45b33bd9057.png)

### Mail app

**Mail app version:** 1.7.2

**Mailserver or service:** n.a.

### Server configuration

**Operating system**: Arch Linux running Docker

**Web server:** Apache

**Database:** MariaDB

**PHP version:** 7.4.13

**Nextcloud Version:** 20.0.3

#### Client configuration
**Browser:** not relevant

**Operating system:** not relevant

------

When I click enable, it just says An error occurred during the request. Unable to proceed.
This only happened after updating to 20.0.3, it was working fine before. Inspecting the page shows there is a problem with the POST request.

![image](https://user-images.githubusercontent.com/11343743/102219389-4e734500-3ed7-11eb-9743-428a99c0a310.png)

I checked the logs and this is what came up: https://gist.github.com/danvilar/dac58818966fc7abcdee26b18aae3f60

Does anyone have any idea?

**Comment by ChristophWurst** [comment]
> I checked the logs and this is what came up: https://gist.github.com/danvilar/dac58818966fc7abcdee26b18aae3f60

Class 'Horde_Mail_Rfc822_Address' not found -> dup of https://github.com/nextcloud/mail/issues/3784

**Comment by danvilar** [comment]
Do you know why this happens after an update?

**Comment by ChristophWurst** [comment]
https://github.com/nextcloud/mail/issues/3784#issuecomment-708260666
