### ISSUE TITLE
Identities for default account

### ISSUE THREAD

**Issue by fsedarkalex** [nextcloud/mail#425]
Hi another request...
I use the default account feature and it is great. One point I am missing is the ability to add identities to this default account.

This should be done by the user manually not by config.

Also mail signatures (per identity) would be great

**Comment by andreas-p** [comment]
Missing for me too.

**Comment by ChristophWurst** [comment]
> Missing for me too.

please use reactions like :+1: instead of comments

**Comment by andreas-p** [comment]
I'm a little surprised that this issue isn't more popular, I'm seeing multiple identities everywhere around. Thumbs-upping probably won't help.

**Comment by ChristophWurst** [comment]
> Thumbs-upping probably won't help.

how would the comment help?

> I'm a little surprised that this issue isn't more popular

it is always hard to guess what people need the most. Are you interested in helping?

**Comment by andreas-p** [comment]
> > Thumbs-upping probably won't help.
> 
> how would the comment help?
Marking my me-too as spam isn't too friendly either...

I can live with the problem at the moment, but priority will probably get upped next year, depending on customer's requirements. I might look into that then (haven't worked with horde so far, nor do I know about its integration into NC).

**Comment by ChristophWurst** [comment]
> depending on customer's requirements

Just let us know when you need help. [We're here to help](https://nextcloud.com/enterprise/)

**Comment by mat-m** [comment]
@ChristophWurst Is it not a duplicate of #1722 ? Or, since this one is older, it should have been closed a while ago ?

**Comment by ChristophWurst** [comment]
Yeah, actually in the past it wouldn't have been possible. But since https://github.com/nextcloud/mail/pull/2259 we can treat aliases of a provisioned account just like for any other account.

Closing as duplicate of #1722  thus.
