### ISSUE TITLE
Bad layout when reading mail with long address list

### ISSUE THREAD

**Issue by kernie** [nextcloud/mail#4252]
### Expected behavior
Message should be readable.

### Actual behavior
The address list lays over buttons and message body, you can't do anything.
<img width="1191" alt="Bildschirmfoto 2020-12-17 um 18 36 14" src="https://user-images.githubusercontent.com/23321751/102523072-5ed21e00-4097-11eb-8e91-979758ab152e.png">

### Mail app

**Mail app version:** (see apps admin page, e.g. 0.5.3)
1.7.2
**Mailserver or service:** (e.g. Outlook, Yahoo, Gmail, Exchange,...)
Strato
### Server configuration

**Operating system**: (e.g. Debian 8)
Ubuntu 18.04
**Web server:** (e.g. Apache, Nginx,...)
Nginx 
**Database:** (e.g. MariaDB, SQLite or PostgreSQL)

**PHP version:** (e.g. 7.0)
7.4
**Nextcloud Version:** (see admin page, e.g. 13.0.2)
20.0.4
#### Client configuration
**Browser:** (e.g. Firefox 48)
Firefox 82
**Operating system:** (e.g. Arch Linux)
Mac Big Sur

**Comment by ChristophWurst** [comment]
@StCyr :eyes:

**Comment by StCyr** [comment]
That is strange: This should have been fixed since v1.7.1

Cache issue? Did you update Mail recently by any chances?

**Comment by kernie** [comment]
Yes, I updated mail yesterday. I cleared my browser cache, but that didn't help. 

Where should I clear the cache on top?

**Comment by StCyr** [comment]
Oops sorry my bad.

The fix has not made it to versions 1.7.x. It will only be available in 1.8 (due next week)

**Comment by StCyr** [comment]
This is definitively fixed in recent versions of Mail
