### ISSUE TITLE
https://nextcloud.example.com/apps/mail/setup "Manual Setup" triggers 404

### ISSUE THREAD

**Issue by gohrner** [nextcloud/mail#4276]
### Expected behavior
I just upgraded Nextcloud to 20.0.4 and tried to setup the Mail extension for the first time.

This lead me to https://nextcloud.example.com/apps/mail/setup where I switched to "manual setup", entered all data, and pressed the "Verbinden" ("Connect") button.

I expect that this either continues the setup process, or opens the Nextcloud Mail extension to display my mails.

### Actual behavior

It just leads to an error message:

![image](https://user-images.githubusercontent.com/26199042/102697493-63810880-4236-11eb-90c0-59a8ab428420.png)

![image](https://user-images.githubusercontent.com/26199042/102697489-5a903700-4236-11eb-96fa-b0440e4b7849.png)

### Mail app

**Mail app version:** 1.7.2

**Mailserver or service:** Dovecot IMAP

### Server configuration

**Operating system**: Debian 10 Buster

**Web server:** Apache 2.4.38 with PHP-FPM (Debian Package)

**Database:** MariaDB 10.3.27 (Debian Package)

**PHP version:** 7.3.19 (Debian Package, PHP-FPM)

**Nextcloud Version:** 20.0.4

#### Client configuration
**Browser:** Chromium Version 87.0.4280.88 (Offizieller Build) snap (64-Bit)

**Operating system:** Ubuntu 20.04 (KDE neon)

**Comment by Marcool04** [comment]
Hi all,
Same issue here.
Mail server is verified to be working. Also getting this same, very terse 404 error. The account is actually created, but the server IMAP and SMTP settings aren't populated.
````
httpd[14962]: ACCLOG RESP:404 FROM:176.141.189.183 REQ:"GET /index.php/apps/mail/api/mailboxes?accountId=1 HTTP/2.0" ON:HTTP/2.0 TO:nextcloud.archraspberrypi.tk:443 USER:-/- (SIZE:27 I:64 O:84) REF:"-" REDIR_TO:"-" U-A:"Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:83.0) Gecko/20100101 Firefox/83.0" LOGID:-
````
Operating system is Arch Linux ARM (on a Raspberry Pi 4), latest Nextcloud, latest Mail app.

**Comment by ChristophWurst** [comment]
Hm. Strange that the route to get the list of mailboxes would return a 404. Does the nextcloud.log have anything to say when this happens?

**Comment by Marcool04** [comment]
Putting Nextcloud into loglevel 0, also with Apache ACCLOG, dovecot and Postfix messages included I have this:

````
Dec 21 18:24:38 HOSTNAME Nextcloud[764]: {"reqId":"X@DaVpiT8mnJ3zpe8GUpogAA0Bg","level":1,"time":"2020-12-21T17:24:38+00:00","remoteAddr":"CLIENT-IP","user":"USERNAME","app":"mail","method":"POST","url":"/index.php/apps/mail/api/accounts","message":"Setting up manually configured account","userAgent":"Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:83.0) Gecko/20100101 Firefox/83.0","version":"20.0.0.9"}
Dec 21 18:24:38 HOSTNAME Nextcloud[764]: {"reqId":"X@DaVpiT8mnJ3zpe8GUpogAA0Bg","level":0,"time":"2020-12-21T17:24:38+00:00","remoteAddr":"CLIENT-IP","user":"USERNAME","app":"mail","method":"POST","url":"/index.php/apps/mail/api/accounts","message":"Connecting to account USERNAME@mail.HOSTNAME","userAgent":"Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:83.0) Gecko/20100101 Firefox/83.0","version":"20.0.0.9"}
Dec 21 18:24:39 HOSTNAME dovecot[31918]: imap-login: Login: user=<USERNAME>, method=PLAIN, rip=127.0.0.1, lip=127.0.0.1, mpid=32685, TLS, session=<fAiau/y2sL5/AAAB>
Dec 21 18:24:39 HOSTNAME postfix/submission/smtpd[32686]: connect from localhost[127.0.0.1]
Dec 21 18:24:39 HOSTNAME postfix/submission/smtpd[32686]: Anonymous TLS connection established from localhost[127.0.0.1]: TLSv1.2 with cipher ECDHE-RSA-AES128-GCM-SHA256 (128/128 bits)
Dec 21 18:24:39 HOSTNAME Nextcloud[764]: {"reqId":"X@DaVpiT8mnJ3zpe8GUpogAA0Bg","level":0,"time":"2020-12-21T17:24:39+00:00","remoteAddr":"CLIENT-IP","user":"USERNAME","app":"mail","method":"POST","url":"/index.php/apps/mail/api/accounts","message":"account created 5","userAgent":"Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:83.0) Gecko/20100101 Firefox/83.0","version":"20.0.0.9"}
Dec 21 18:24:39 HOSTNAME dovecot[31918]: imap(USERNAME)<32685><fAiau/y2sL5/AAAB>: Logged out in=26 out=527 deleted=0 expunged=0 trashed=0 hdr_count=0 hdr_bytes=0 body_count=0 body_bytes=0
Dec 21 18:24:39 HOSTNAME postfix/submission/smtpd[32686]: disconnect from localhost[127.0.0.1] ehlo=2 starttls=1 auth=1 quit=1 commands=5
Dec 21 18:24:39 HOSTNAME httpd[31944]: ACCLOG RESP:201 FROM:CLIENT-IP REQ:"POST /index.php/apps/mail/api/accounts HTTP/2.0" ON:HTTP/2.0 TO:nextcloud.HOSTNAME:443 USER:-/- (SIZE:446 I:407 O:513) REF:"-" REDIR_TO:"-" U-A:"Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:83.0) Gecko/20100101 Firefox/83.0" LOGID:X@DaVpiT8mnJ3zpe8GUpogAA0Bg
Dec 21 18:24:39 HOSTNAME dovecot[31918]: imap-login: Login: user=<USERNAME>, method=PLAIN, rip=127.0.0.1, lip=127.0.0.1, mpid=32690, TLS, session=<uQWju/y2tL5/AAAB>
Dec 21 18:24:39 HOSTNAME dovecot[31918]: imap(USERNAME)<32690><uQWju/y2tL5/AAAB>: Logged out in=183 out=1149 deleted=0 expunged=0 trashed=0 hdr_count=0 hdr_bytes=0 body_count=0 body_bytes=0
Dec 21 18:24:39 HOSTNAME httpd[31944]: ACCLOG RESP:404 FROM:CLIENT-IP REQ:"GET /index.php/apps/mail/api/mailboxes?accountId=5 HTTP/2.0" ON:HTTP/2.0 TO:nextcloud.HOSTNAME:443 USER:-/- (SIZE:27 I:65 O:27) REF:"-" REDIR_TO:"-" U-A:"Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:83.0) Gecko/20100101 Firefox/83.0" LOGID:X@DaV5iT8mnJ3zpe8GUpowAA0hg
````

Honestly, I see no reason for the 404 either… Everything looks good in fact.
Let me know if I can do anything else to help.

**Comment by gohrner** [comment]
Is there any known workaround to get the Mail application to work at all, or is it currently completely defunct for new accounts?

**Comment by ChristophWurst** [comment]
Believe it or not but it works for me, so there is something that causes those issues on *some* setups, but not all. I haven't had time to dig into it, any debugging help is highly appreciated :v:

**Comment by Yuri6037** [comment]
Exact same problem here: no matter what I can do when running Nextcloud behind apache2 trying to connect to a IMAP/SMTP server combination even with SSL/TLS, STARTTLS and valid SSL certificate NextCloud mail client just throws "Request failed with status code 404" and nothing more. The logs for Nextcloud do not show anything at all.

The logs from Postfix/Dovecot however do work and shows that the server attempted to connect to itself and succeeded both from Dovecot IMAP and Postfix SMTP.
