### ISSUE TITLE
File picker does not work when crafting subsequent mails

### ISSUE THREAD

**Issue by blizzz** [nextcloud/mail#4278]
### Expected behavior

- When writing a second mail, the file picker for "Add attachment link from files" should offer files to pick

### Actual behavior

- it shows a loading spinner

### Mail app

**Mail app version:** 1.7.2

#### Client configuration
**Browser:** Firefox 84

**Operating system:** Arch Linux

**Comment by ChristophWurst** [comment]
do you get any js error?

**Comment by blizzz** [comment]
I do:

```
Uncaught (in promise) TypeError: this.$filePicker is null
    _fillSlug dialogs.js:1235
    _fillFilePicker dialogs.js:1157
    jQuery 4
    getFolderContents client.js:512
    promise callback*getFolderContents client.js:505
    _fillFilePicker dialogs.js:1117
    filepicker dialogs.js:434
    jQuery 3
    filepicker dialogs.js:417
    jQuery 8
    filepicker dialogs.js:254
    pick index.es.js:1424
    pick index.es.js:1423
    onAddCloudAttachmentLink ComposerAttachments.vue:148
    VueJS 2
    onAddCloudAttachmentLink Composer.vue:582
    VueJS 4
    onClick ActionButton.js:43
    VueJS 49
    openMenu Actions.js:66
    VueJS 4
    show v-tooltip.esm.js:3600
    r v-tooltip.esm.js:3846
dialogs.js:1235:13
    _fillSlug dialogs.js:1235
    _fillFilePicker dialogs.js:1157
    jQuery 4
    getFolderContents client.js:512
    (Async: promise callback)
    getFolderContents client.js:505
    _fillFilePicker dialogs.js:1117
    filepicker dialogs.js:434
    jQuery 3
    filepicker dialogs.js:417
    jQuery 8
    filepicker dialogs.js:254
    pick index.es.js:1424
    pick index.es.js:1423
    onAddCloudAttachmentLink ComposerAttachments.vue:148
    onAddCloudAttachmentLink self-hosted:1161
    VueJS 2
    onAddCloudAttachmentLink Composer.vue:582
    onAddCloudAttachmentLink self-hosted:1161
    VueJS 4
    onClick ActionButton.js:43
    onClick self-hosted:1161
    VueJS 49
    openMenu Actions.js:66
    openMenu self-hosted:1161
    VueJS 4
    show v-tooltip.esm.js:3600
    show self-hosted:1161
    r v-tooltip.esm.js:3846
```

**Comment by blizzz** [comment]
The loading  spinner goes away, meanwhile, and you can select a file. But the attachment is still not being added in subsequent mails.

**Comment by GretaD** [comment]
this is a very weird behavior. Actually on the second time the link it is added, it just takes a long time to show, or you need to click on the editor, select all, and it is shown.

BUT, on the composer modal, this error doesnt exist. I will keep this ticket open till we release the composer modal and test again, to make sure its not something on my local dev env.

**Comment by ChristophWurst** [comment]
> I will keep this ticket open till we release the composer modal and test again

you can test now, right?

**Comment by blizzz** [comment]
> > I will keep this ticket open till we release the composer modal and test again
> 
> you can test now, right?

Works! Thx :)
