### ISSUE TITLE
Doesn't work with 20.0.4!

### ISSUE THREAD

**Issue by rougerouter** [nextcloud/mail#4287]
### Expected behavior
Tell us what should happen

### Actual behavior
Tell us what happens instead
Won't install! If you're going to make an app which everyone depends on even when they do updates you should keep it revised. I won't use it anymore, because it's not dependable. 

### Mail app

**Mail app version:** (see apps admin page, e.g. 0.5.3)

**Mailserver or service:** (e.g. Outlook, Yahoo, Gmail, Exchange,...)

### Server configuration

**Operating system**: (e.g. Debian 8)

**Web server:** (e.g. Apache, Nginx,...)

**Database:** (e.g. MariaDB, SQLite or PostgreSQL)

**PHP version:** (e.g. 7.0)

**Nextcloud Version:** (see admin page, e.g. 13.0.2)

#### Client configuration
**Browser:** (e.g. Firefox 48)

**Operating system:** (e.g. Arch Linux)

**Comment by ChristophWurst** [comment]
https://nextcloud.com/contribute/code-of-conduct/
