### ISSUE TITLE
can't reinstall

### ISSUE THREAD

**Issue by zsbolyoczki** [nextcloud/mail#4303]
### Expected behavior

Reinstall without problems.

### Actual behavior

* mail was installed
* then it was removed
* then I have tried to install again
* installation failed because of the lefotver tables in the database
* I have renamed the tables
* install still fail because 
```
An exception occurred while executing 'UPDATE `oc_mail_accounts` SET `last_mailbox_sync` = ?' with params [0]: SQLSTATE[42S02]: Base table or view not found: 1146 Table 'mydbname.oc_mail_accounts' doesn't exist
```

### Mail app

**Mail app version:** 

v1.7.2 (offered by Nextcloud)

**Mailserver or service:** (e.g. Outlook, Yahoo, Gmail, Exchange,...)

Nextcloud v20.0.4

**Comment by ChristophWurst** [comment]
> then it was removed

what exactly did you do? what was the previous version?

**Comment by iexclus1ve** [comment]
Hello All! I have some trouble to reinstall mail app:

**Comment by ChristophWurst** [comment]
https://github.com/nextcloud/mail/issues/4041
