### ISSUE TITLE
Subfolders of different mail accounts are always shown under the first mail account

### ISSUE THREAD

**Issue by tarator** [nextcloud/mail#4305]
I have two mail accounts each having one or more subfolder(s) beneath INBOX. 

### Expected behavior
The subfolders of each account should appear beneath the corresponding mail account.

### Actual behavior
All subfolders are shown under the first mail-account

### Mail app

**Mail app version:** 1.7.2

**Mailserver or service:** irrelevant

### Server configuration

**Operating system**: Ubuntu 20.04

**Web server:** Apache

**Database:** MariaDB

**PHP version:** 7.4.3

**Nextcloud Version:** 20.0.4 - 20.0.4.0

#### Client configuration
**Browser:** Firefox 84.0 / Chromium 87.0.4280.88

**Operating system:** Ubuntu

**Comment by StCyr** [comment]
Mind sharing a screenshot?

**Comment by tarator** [comment]
Hi, here a screenshot. The two marked subfolders don't belong to the E-Mail-Account "geor....@...". They belong to the E-Mail-Account "g.abe...@trade..."

![nextcloud mail subfolder problem ](https://user-images.githubusercontent.com/414814/104029053-c75d7800-51c9-11eb-8118-9c6d8aa61176.jpg)

**Comment by nilskamm** [comment]
We have the same problem, what makes the whole app kinda unuseable.

**Comment by tarator** [comment]
One thing, that might be of interest: Although both E-Mail-Adressen end with a different domain, they have the same imap and smtp server address.

**Comment by nilskamm** [comment]
For me it is the same address ending for all tested accounts.
