### ISSUE TITLE
Display big number of recipients addresses in a non-overflowing way

### ISSUE THREAD

**Issue by myrho** [nextcloud/mail#4311]
### Expected behavior
When viewing an email with many recipients, the addresses must not interfere with the UI. For instance, only the first N should be shown and a "+" sign to indicate more to be shown. User may expand the display of the addresses to view all of them optionally.

### Actual behavior
When viewing an email with many recipients, the addresses overflow into the rest of the UI so one cannot even click the "answer"  button or read the mail text.

![Untitled](https://user-images.githubusercontent.com/1172181/103486323-5b5fc600-4dfd-11eb-9226-61630f4411c5.jpg)

### Mail app

**Mail app version:** 1.7.2

### Server configuration

Using the official docker image of nextcloud.
 
#### Client configuration
**Browser:** Firefox 84, Chromium 87

**Comment by StCyr** [comment]
This will be fixed in version 1.8

**Comment by st3iny** [comment]
Fixed by #3745
