### ISSUE TITLE
Update Issue from 1.4.2 to 1.7.2 (Nextcloud 20)

### ISSUE THREAD

**Issue by wernerasln** [nextcloud/mail#4313]
### Question
How can I solve this problem? 
nothing happens when I click update. There is no error message but also no update, only that the button can be clicked again after about 2 minutes.
![image](https://user-images.githubusercontent.com/76956565/103546061-ba2b4b00-4ea2-11eb-9842-279abdb9fe14.png)
![image](https://user-images.githubusercontent.com/76956565/103546101-c57e7680-4ea2-11eb-9c74-0d0c810155d3.png)
it is the same as the other apps. Mail social and talk.

can someone help me with this, please?

**Comment by ChristophWurst** [comment]
Please use the forum for support https://help.nextcloud.com/c/apps/mail/35
