### ISSUE TITLE
ktinerary binary adapter does not work with selinux

### ISSUE THREAD

**Issue by Wotisrv** [nextcloud/mail#4321]
### Expected behavior
No warning

### Actual behavior
Warning appears: KItinerary binary adapter is not available, can't extract information

### Mail app

**Mail app version:** 1.7.3

**Mailserver or service:** Gmail

### Server configuration

**Operating system**: Fedora 33 Server-Edition

**Web server:** Apache 2.4.46

**Database:** MariaDB 10.4.7

**PHP version:** 7.4.13

**Nextcloud Version:** 20.0.4

#### Client configuration
**Browser:** irrelevant

**Operating system:** irrelevant

I installed the Nextcloud mail app 1.7.3 and signed in to my Google account. 
When I open emails the following warning appears in the Nextcloud log: 
```
KItinerary binary adapter is not available, can't extract information.
```

Following command shows the right permissions, if I am not wrong:
```
stat -c '%A %a %U %G %n' *
-rwxr--r-- 744 apache apache kitinerary-extractor
```
I got some SELinux access control errors: 
```
SELinux prevents kitinerary-extr from reading the file /memfd:JSVMStack:/var/www/html/nextcloud/apps/mail/vendor/christophwurst/kitinerary-bin/src/../bin/kitinerary-extractor ( deleted). To view the complete SELinux notification, run the following command: sealert -l 7aa82033-c4c7-47b4-8b18-a9a9885b6dbb

SELinux prevents kitinerary-extr from accessing file memfd: JSVMStack: /var/www/html/nextcloud/apps/mail/vendor/christophwurst/kitinerary-bin/src/../bin/kitinerary-extractor with write access. To view the complete SELinux notification, run the following command: sealert -l 3e21a9bd-e3f3-43f1-b884-d69a43b0666d
```
I got that fixed by issuing the following command:
```
setsebool -P httpd_execmem 1
ausearch -c ‘kitinerary-extr’ --raw | audit2allow -M my-kitineraryextr
semodule -i my-kitineraryextr.pp
```
Anyway, the warning in the Nextcloud log does not disappear.

**Comment by ChristophWurst** [comment]
Thanks for the report.

I'm not that familiar with selinux, hence it's hard to judge why this still shows the warning in the logs.

The logic for this is found at https://github.com/ChristophWurst/kitinerary-bin/blob/eaafa040b404651cb4ab75a2d7a53c71b55d2395/src/BinaryAdapter.php#L67-L94 in case anyone sees the issue from looking at the code.

**Comment by Wotisrv** [comment]
As this is written for 2 months ago,  I'll just inform I am on the latest app version and NC 20.0.8 version but SELINUX issue still proceeds.

**Comment by ChristophWurst** [comment]
sure, I never claimed that this would be fixed

This needs help form a developer that knows php and selinux.

**Comment by MastaG** [comment]
I think you can do something like:
```
setsebool -P httpd_execmem 1
semanage fcontext -a -t httpd_sys_script_exec_t '/var/www/html/nextcloud/apps/mail/vendor/christophwurst/kitinerary-bin/bin(/.*)?'
restorecon -vFR /var/www/html/nextcloud/apps/mail/vendor/christophwurst/kitinerary-bin
```

Still I wonder why the mail app requires external binaries though...

**Comment by Wotisrv** [comment]
I can give that a try...

**Comment by ChristophWurst** [comment]
> Still I wonder why the mail app requires external binaries though...

It's not external but shipped. If you have suggestions for how to better integrate this I'm all ears.
