### ISSUE TITLE
Can't access huge imap folder with kopano as mailserver

### ISSUE THREAD

**Issue by nachfuellbar** [nextcloud/mail#4322]
### Expected behavior
Mail folder should be accessable - about 3000 mails in the folder

### Actual behavior
I get the Message "Loading messages" in Web UI - in Log i get the following error and after some retries in ui i get "Could not open Mailbox" in the ui
Argument 3 passed to OCA\Mail\Model\IMAPMessage::__construct() must be of the type int, null given, called in /var/www/nextcloud/apps/mail/lib/IMAP/MessageMapper.php on line 229
Same error occurs when using using occ mail:account:sync 1

I tried the same with dovecot and there i get no error (synced inbox via imapsync)

### Mail app

**Mail app version:** 1.7.2

**Mailserver or service:** Kopano

### Server configuration

**Operating system**: CentOS 7

**Web server:** Nginx

**Database:**Postgres

**PHP version:** 7.3.20

**Nextcloud Version:** 20.0.4

#### Client configuration
**Browser:** Chromium 87

**Operating system:** Arch Linux

**Comment by ChristophWurst** [comment]
> IMAPMessage::__construct() must be of the type int, null given

That could only happen if one of the messages does not have an integer `UID`, which technically is impossible. Weird.

Do you have the full error trace?

**Comment by nachfuellbar** [comment]
I just setup this account again (removed it previously)
The full log is way to huge - added the account and after some minutes there were about 40 MiB Logs
Hopefully i got everything you wanted in this gist

https://gist.github.com/nachfuellbar/44d65b9dc640c05d0d6624363cb99b75

**Comment by ChristophWurst** [comment]
Thanks a lot. Only the last entry is actually an error.

As I understand this happens through the initial sync of the mailbox. First we try to get a list of UIDs to fetch, then we fetch those. And somehow there is at least one UID that we find on IMAP but where we can't fetch the message header.

> I tried the same with dovecot and there i get no error (synced inbox via imapsync)

What do you mean by that?

**Comment by nachfuellbar** [comment]
Literally what i wrote ;)
I synced the whole mailbox with imapsync to a newly setup dovecot and there it worked like a charm
