### ISSUE TITLE
Persistent PHP errors in the Nextcloud journal HEADER.FIELDS (CONTENT-TYPE X-PRIORITY LIST-POST IMPORTANCE)

### ISSUE THREAD

**Issue by sosed213** [nextcloud/mail#433]
My details: (Crome browser, Nextcloud 12.1, Nginx 1.11.8 (cache purge), PHP 7.1.8).
The Mail application works, but there are always errors in the log.

Error PHP Undefined index: HEADER.FIELDS (CONTENT-TYPE X-PRIORITY LIST-POST IMPORTANCE) at /var/www/cloud12/apps/mail/vendor/pear-pear.horde.org/Horde_Imap_Client/Horde/Imap/Client/ Socket.php # 3208

### Steps to reproduce
1. Add an account IMAP Yandex
2. Check email
3. Make sure there are errors in the log

### Expected behaviour
Errors in the log should not be

### Actual behaviour
The Mail application works, but there are errors in the log.

### Mail app

**Mail app version:** (see apps admin page)
Mail	0.6.4

**Mailserver or service:** (e.g. Outlook, Yahoo, Gmail, Exchange,...)
Yandex

**Transport security - IMAP:** (None, SSL, TLS, STARTTLS) 
SSL(993) and/or None (143)

**Transport security - SMTP:** (None, SSL, TLS, STARTTLS)
SSL (465) and/or None (587 port)

**Number of accounts:**
1

### Server configuration

**Operating system**:
Ubuntu Server 16.04
Linux media 4.4.0-67-generic #88-Ubuntu SMP Wed Mar 8 16:34:45 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux

**Web server:**
nginx/1.11.8

**Database:**
mysql  Ver 15.1 Distrib 10.1.15-MariaDB, for debian-linux-gnu (x86_64) using readline 5.2 

**PHP version:**
PHP 7.1.8-2+ubuntu16.04.1+deb.sury.org+4 (cli) (built: Aug  4 2017 13:04:12) ( NTS ) 

**Version:** (see admin page)
Nextcloud 12.0.1

**Updated from an older version or fresh install:**
Nextcloud 12

**List of activated apps:**

Enabled:
  - activity: 2.5.2
  - apporder: 0.4.0
  - bookmarks: 0.10.1
  - bruteforcesettings: 1.0.2
  - calendar: 1.5.3
  - comments: 1.2.0
  - contacts: 1.5.3
  - dav: 1.3.0
  - deck: 0.2.1
  - drawio: 0.8.8
  - federatedfilesharing: 1.2.0
  - federation: 1.2.0
  - files: 1.7.2
  - files_downloadactivity: 1.1.1
  - files_external: 1.3.0
  - files_pdfviewer: 1.1.1
  - files_sharing: 1.4.0
  - files_texteditor: 2.4.1
  - files_trashbin: 1.2.0
  - files_versions: 1.5.0
  - files_videoplayer: 1.1.0
  - firstrunwizard: 2.1
  - gallery: 17.0.0
  - logreader: 2.0.0
  - lookup_server_connector: 1.0.0
  - mail: 0.6.4
  - nextcloud_announcements: 1.1
  - notes: 2.3.1
  - notifications: 2.0.0
  - oauth2: 1.0.5
  - onlyoffice: 1.1.3
  - password_policy: 1.2.2
  - previewgenerator: 1.0.6
  - provisioning_api: 1.2.0
  - serverinfo: 1.2.0
  - sharebymail: 1.2.0
  - survey_client: 1.0.0
  - systemtags: 1.2.0
  - theming: 1.3.0
  - twofactor_backupcodes: 1.1.1
  - updatenotification: 1.2.0
  - workflowengine: 1.2.0
Disabled:
  - admin_audit
  - encryption
  - radio
  - user_external
  - user_ldap

**The content of config/config.php:**
<details>
{
    "system": {
        "instanceid": "xxxxxx",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "cloud12.xxx.ru"
        ],
        "datadirectory": "\/var\/www\/cloud12\/data",
        "overwrite.cli.url": "https:\/\/cloud12.xxx.ru",
        "overwriteprotocol": "https",
        "dbtype": "mysql",
        "version": "12.0.1.5",
        "dbname": "nextcloud12",
        "dbhost": "localhost",
        "dbport": "",
        "dbtableprefix": "oc_",
        "mysql.utf8mb4": true,
        "htaccess.RewriteBase": "\/",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "installed": true,
        "loglevel": 2,
        "logtimezone": "Asia\/Omsk",
        "logfile": "\/var\/log\/nextcloud12.log",
        "log_rotate_size": 104857600,
        "cron_log": true,
        "filesystem_check_changes": true,
        "quota_include_external_storage": false,
        "knowledgebaseenabled": false,
        "memcache.local": "\\OC\\Memcache\\APCu",
        "filelocking.enabled": "true",
        "memcache.locking": "\\OC\\Memcache\\Redis",
        "redis": {
            "host": "\/var\/run\/redis\/redis.sock",
            "port": 0,
            "timeout": 0
        },
        "maintenance": false,
        "theme": "",
        "enable_previews": true,
        "mail_smtpmode": "smtp",
        "mail_smtpsecure": "ssl",
        "mail_from_address": "cloud",
        "mail_domain": "xxxx.ru",
        "mail_smtpauth": 1,
        "mail_smtpauthtype": "LOGIN",
        "mail_smtphost": "smtp.yandex.ru",
        "mail_smtpport": "465",
        "mail_smtpname": "***REMOVED SENSITIVE VALUE***",
        "mail_smtppassword": "***REMOVED SENSITIVE VALUE***",
        "updater.secret": "***REMOVED SENSITIVE VALUE***"
    },
    "apps": {
        "activity": {
            "enabled": "yes",
            "installed_version": "2.5.2",
            "types": "filesystem"
        },
        "apporder": {
            "enabled": "yes",
            "installed_version": "0.4.0",
            "order": "[\"\/apps\/files\/\",\"\/apps\/gallery\/\",\"\/apps\/notes\/\",\"\/apps\/mail\/\",\"\/apps\/contacts\/\",\"\/apps\/activity\/\",\"\/apps\/bookmarks\/\",\"\/apps\/calendar\/\",\"\/apps\/deck\/\",\"\/apps\/radio\"]",
            "types": ""
        },
        "audioplayer": {
            "enabled": "no",
            "installed_version": "2.0.2",
            "types": ""
        },
        "backgroundjob": {
            "lastjob": "164"
        },
        "bookmarks": {
            "enabled": "yes",
            "installed_version": "0.10.1",
            "types": ""
        },
        "bruteForce": {
            "whitelist_1": "192.168.1.0\/24"
        },
        "bruteforcesettings": {
            "enabled": "yes",
            "installed_version": "1.0.2",
            "types": ""
        },
        "calendar": {
            "enabled": "yes",
            "installed_version": "1.5.3",
            "types": ""
        },
        "comments": {
            "enabled": "yes",
            "installed_version": "1.2.0",
            "types": "logging"
        },
        "contacts": {
            "enabled": "yes",
            "installed_version": "1.5.3",
            "types": ""
        },
        "core": {
            "backgroundjobs_mode": "cron",
            "installed.bundles": "[\"CoreBundle\"]",
            "installedat": "1502077136.9863",
            "lastcron": "1502179202",
            "lastupdateResult": "[]",
            "lastupdatedat": "1502178324",
            "moveavatarsdone": "yes",
            "oc.integritycheck.checker": "[]",
            "previewsCleanedUp": "1",
            "public_files": "files_sharing\/public.php",
            "public_webdav": "dav\/appinfo\/v1\/publicwebdav.php",
            "scss.variables": "31dd1757f0f9de146d3c5f038132277d",
            "shareapi_default_expire_date": "yes",
            "shareapi_expire_after_n_days": "3",
            "umgmt_send_email": "true",
            "umgmt_show_backend": "false",
            "umgmt_show_email": "true",
            "umgmt_show_last_login": "true",
            "umgmt_show_storage_location": "true",
            "updater.secret.created": "1502163429",
            "vendor": "nextcloud"
        },
        "dav": {
            "enabled": "yes",
            "installed_version": "1.3.0",
            "types": "filesystem"
        },
        "deck": {
            "enabled": "yes",
            "installed_version": "0.2.1",
            "types": ""
        },
        "drawio": {
            "enabled": "yes",
            "installed_version": "0.8.8",
            "types": "filesystem"
        },
        "federatedfilesharing": {
            "enabled": "yes",
            "installed_version": "1.2.0",
            "types": ""
        },
        "federation": {
            "enabled": "yes",
            "installed_version": "1.2.0",
            "types": "authentication"
        },
        "files": {
            "cronjob_scan_files": "500",
            "default_quota": "100 GB",
            "enabled": "yes",
            "installed_version": "1.7.2",
            "types": "filesystem"
        },
        "files_downloadactivity": {
            "enabled": "yes",
            "installed_version": "1.1.1",
            "types": "filesystem"
        },
        "files_external": {
            "enabled": "yes",
            "installed_version": "1.3.0",
            "types": "filesystem"
        },
        "files_pdfviewer": {
            "enabled": "yes",
            "installed_version": "1.1.1",
            "ocsid": "166049",
            "types": ""
        },
        "files_sharing": {
            "enabled": "yes",
            "installed_version": "1.4.0",
            "types": "filesystem"
        },
        "files_texteditor": {
            "enabled": "yes",
            "installed_version": "2.4.1",
            "ocsid": "166051",
            "types": ""
        },
        "files_trashbin": {
            "enabled": "yes",
            "installed_version": "1.2.0",
            "types": "filesystem"
        },
        "files_versions": {
            "enabled": "yes",
            "installed_version": "1.5.0",
            "types": "filesystem"
        },
        "files_videoplayer": {
            "enabled": "yes",
            "installed_version": "1.1.0",
            "types": ""
        },
        "firstrunwizard": {
            "enabled": "yes",
            "installed_version": "2.1",
            "types": "logging"
        },
        "gallery": {
            "enabled": "yes",
            "installed_version": "17.0.0",
            "types": ""
        },
        "logreader": {
            "enabled": "yes",
            "installed_version": "2.0.0",
            "ocsid": "170871",
            "relativedates": "1",
            "types": ""
        },
        "lookup_server_connector": {
            "enabled": "yes",
            "installed_version": "1.0.0",
            "types": "authentication"
        },
        "mail": {
            "enabled": "yes",
            "installed_version": "0.6.4",
            "types": ""
        },
        "metadata": {
            "enabled": "no",
            "installed_version": "0.3.0",
            "types": ""
        },
        "music": {
            "enabled": "no",
            "installed_version": "0.4.3",
            "types": "filesystem"
        },
        "nextcloud_announcements": {
            "enabled": "yes",
            "installed_version": "1.1",
            "pub_date": "Sat, 10 Dec 2016 00:00:00 +0100",
            "types": "logging"
        },
        "notes": {
            "enabled": "yes",
            "installed_version": "2.3.1",
            "types": ""
        },
        "notifications": {
            "enabled": "yes",
            "installed_version": "2.0.0",
            "types": "logging"
        },
        "oauth2": {
            "enabled": "yes",
            "installed_version": "1.0.5",
            "types": "authentication"
        },
        "onlyoffice": {
            "DocumentServerInternalUrl": "https:\/\/office.xxxxx.ru\/",
            "DocumentServerSecret": "",
            "DocumentServerUrl": "https:\/\/office.xxxxxx.ru\/",
            "StorageUrl": "",
            "defFormats": "{\"docx\":\"true\",\"xlsx\":\"true\",\"pptx\":\"true\",\"ppsx\":\"true\",\"txt\":\"false\",\"csv\":\"false\"}",
            "enabled": "yes",
            "installed_version": "1.1.3",
            "sameTab": "true",
            "skey": "1502081545015",
            "types": "filesystem"
        },
        "password_policy": {
            "enabled": "yes",
            "enforceNumericCharacters": "1",
            "enforceUpperLowerCase": "0",
            "installed_version": "1.2.2",
            "types": ""
        },
        "previewgenerator": {
            "enabled": "yes",
            "installed_version": "1.0.6",
            "types": "filesystem"
        },
        "provisioning_api": {
            "enabled": "yes",
            "installed_version": "1.2.0",
            "types": "prevent_group_restriction"
        },
        "radio": {
            "enabled": "no",
            "installed_version": "0.5.0",
            "types": ""
        },
        "serverinfo": {
            "enabled": "yes",
            "installed_version": "1.2.0",
            "types": ""
        },
        "sharebymail": {
            "enabled": "yes",
            "installed_version": "1.2.0",
            "types": "filesystem"
        },
        "survey_client": {
            "enabled": "yes",
            "installed_version": "1.0.0",
            "types": ""
        },
        "systemtags": {
            "enabled": "yes",
            "installed_version": "1.2.0",
            "types": "logging"
        },
        "theming": {
            "enabled": "yes",
            "installed_version": "1.3.0",
            "types": "logging"
        },
        "twofactor_backupcodes": {
            "enabled": "yes",
            "installed_version": "1.1.1",
            "types": ""
        },
        "updatenotification": {
            "enabled": "yes",
            "installed_version": "1.2.0",
            "types": "",
            "update_check_errors": "0"
        },
        "workflowengine": {
            "enabled": "yes",
            "installed_version": "1.2.0",
            "types": "filesystem"
        }
    }
}

</details>

#### Client configuration
**Browser:**
Google Chrome
**Operating system:**
Windows 7 x64
##### Web server error log
```
Insert your webserver log here
```

##### Server log (data/nextcloud.log)
<details>
{"reqId":"ljie9RuIZdZEMtd7ucoR","level":3,"time":"2017-08-07T12:29:37+06:00","remoteAddr":"xxx.xxx.xxx.xxx","user":"xxx","app":"PHP","method":"GET","url":"\/apps\/mail\/accounts\/1\/folders\/SU5CT1g%3D\/messages?filter=","message":"Undefined index: HEADER.FIELDS (CONTENT-TYPE X-PRIORITY LIST-POST IMPORTANCE) at \/var\/www\/cloud12\/apps\/mail\/vendor\/pear-pear.horde.org\/Horde_Imap_Client\/Horde\/Imap\/Client\/Socket.php#3208","userAgent":"Mozilla\/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit\/537.36 (KHTML, like Gecko) Chrome\/59.0.3071.115 Safari\/537.36","version":"12.0.0.29"}
</details>

##### Horde IMAP log (data/horde_imap.log)
<details>
```
Insert your horde IMAP log here, see https://github.com/nextcloud/mail#debug-mode
```
</details>

##### Horde SMTP log (data/horde_smtp.log)
<details>
```
Insert your horde SMTP log here, see https://github.com/nextcloud/mail#debug-mode
```
</details>

##### Browser log
<details>
```
Insert your browser log here, this could for example include:

a) The javascript console log
b) The network log 
c) ...
```
</details>

**Comment by sosed213** [comment]
Any ideas about the problem?

**Comment by ChristophWurst** [comment]
> Any ideas about the problem?

Not yet. Maybe an update of the horde libs will fix it.

**Comment by ChristophWurst** [comment]
@sosed213 could you please retry with v0.7.3? We've updated some of the horde libs. Thanks

**Comment by sosed213** [comment]
![12-09-2017 210932](https://user-images.githubusercontent.com/16791649/30333960-06678a40-9800-11e7-8fbb-75564f20e3ff.png)
Unfortunately, the application update did not help. After the upgrade, I cleaned the cache. And he went into the cloud.

And one more problem, some letters do not open, in particular your :)

![12-09-2017 210907](https://user-images.githubusercontent.com/16791649/30333954-039cfcd2-9800-11e7-8ae7-a26812cfa64e.png)

**Comment by HelferP** [comment]
with v 0.7.4 I get the same error

Undefined index: HEADER.FIELDS (CONTENT-TYPE X-PRIORITY LIST-POST IMPORTANCE) at /var/www/nextcloud/apps/mail/vendor/pear-pear.horde.org/Horde_Imap_Client/Horde/Imap/Client/Socket.php#3208

**Comment by sosed213** [comment]
I confirm. At me as this error continues to be present.

**Comment by sosed213** [comment]
Some emails are not yet loaded, most likely because of special characters in the Subject field or the reverse sender. For example:


`Received: from mxfront12g.mail.yandex.net ([127.0.0.1])
	by mxfront12g.mail.yandex.net with LMTP id BbLNg72e
	for <sosed213@yandex.ru>; Sun, 29 Oct 2017 23:10:18 +0300
Received: from github-smtp2-ext6.iad.github.net (github-smtp2-ext6.iad.github.net [192.30.252.197])
	by mxfront12g.mail.yandex.net (nwsmtp/Yandex) with ESMTPS id waxSYCIKNB-AHZ4SUgf;
	Sun, 29 Oct 2017 23:10:17 +0300
	(using TLSv1.2 with cipher ECDHE-RSA-AES128-GCM-SHA256 (128/128 bits))
	(Client certificate not present)
Return-Path: noreply@github.com
X-Yandex-Front: mxfront12g.mail.yandex.net
X-Yandex-TimeMark: 1509307817
Authentication-Results: mxfront12g.mail.yandex.net; spf=pass (mxfront12g.mail.yandex.net: domain of github.com designates 192.30.252.197 as permitted sender, rule=[ip4:192.30.252.0/22]) smtp.mail=noreply@github.com; dkim=pass header.i=@github.com
X-Yandex-Spam: 1
Date: Sun, 29 Oct 2017 13:10:16 -0700
DKIM-Signature: v=1; a=rsa-sha256; c=relaxed/relaxed; d=github.com;
	s=pf2014; t=1509307816;
	bh=wPz01JgkGTiXVATrGg2xDvgUtkEQHZWlqXZSYBnl3lg=;
	h=From:Reply-To:To:Cc:In-Reply-To:References:Subject:List-ID:
	 List-Archive:List-Post:List-Unsubscribe:From;
	b=BtfasTzXFbBUuQIgzSq7cmCSs1tgFxbjVk0VGzSZbkgFlFmr5r4RhQf9uBI5SLKk6
	 7CJy79KgCtflBIY2yfi1QZQhxqsL8A1Y17FfMwqz22WB2TIlOHyiVPNA/dZ/Nj+MH/
	 QvshpYr3FN1i0X3FY/kWmPSsOeg6jz/NW2jCjJMg=

**Comment by vit1-irk** [comment]
Can confirm, all the same. And Github notification letters are not readable through the Mail app as @sosed213 stated

**Comment by rEnr3n** [comment]
I have this error when adding yandex account too. Gmail and riseup accounts are fine.

**Comment by Temtaime** [comment]
And me i cannot connect a google account using latest nextcloud 12.0.5 and latest mail app
