### ISSUE TITLE
Warning	mail	KItinerary binary adapter is not available, can't extract information

### ISSUE THREAD

**Issue by gueniewie** [nextcloud/mail#4339]
### Expected behavior
Tell us what should happen

I have this message in my logs

Warning | mail | KItinerary binary adapter is not available, can't extract information

### Actual behavior
Tell us what happens instead
I make a
sudo -u apache php /var/www/html/nextcloud/occ maintenance:repair
but the Warning exists

### Mail app

**Mail app version:** (see apps admin page, e.g. 0.5.3)

latest from Nextcloud APP

**Mailserver or service:** (e.g. Outlook, Yahoo, Gmail, Exchange,...)
postfix dovecot

### Server configuration

**Operating system**: (e.g. Debian 8)
oracle 8.3

**Web server:** (e.g. Apache, Nginx,...)
apache

**Database:** (e.g. MariaDB, SQLite or PostgreSQL)
MariaDB
**PHP version:** (e.g. 7.0)
7.14

**Nextcloud Version:** (see admin page, e.g. 13.0.2)
20.0.4

#### Client configuration
**Browser:** (e.g. Firefox 48)
Firefox
**Operating system:** (e.g. Arch Linux)

**Comment by gueniewie** [comment]
This is a bad Problem with selinux I found ?
Have you any Info to create a correct selinux polici

**Comment by ChristophWurst** [comment]
> Have you any Info to create a correct selinux polici

I don't have any. But mind asking about this on the forum https://help.nextcloud.com/?

**Comment by doc75** [comment]
#5999 will decrease the logging level to info (and reduce amount of logging message)
