### ISSUE TITLE
TypeError: 'open' called on an object that does not implement interface XMLHttpRequest.

### ISSUE THREAD

**Issue by Gomez** [nextcloud/mail#434]
### Steps to reproduce
1. Install current master (make all)
2. Answer to a mail and add a local attachment
3. Console error is shown: TypeError: 'open' called on an object that does not implement interface XMLHttpRequest. 

### Expected behaviour
No console error

### Actual behaviour
Console error. The mail and attachment still get send correctly.
Happens only without debug mode. In debug mode no error.

### Mail app
0.7.0

**Comment by ChristophWurst** [comment]
Is that still an issue?

**Comment by ChristophWurst** [comment]
> Is that still an issue?

I assume not -> closing :)
