### ISSUE TITLE
sending a message through mail throws a 500 Internal Server Error

### ISSUE THREAD

**Issue by eBug** [nextcloud/mail#4340]
### Expected behavior
Email should be sent

### Actual behavior
When I reply to an email from INBOX, the mail is sent OK.
If I write a new mail to the same address , mail throws a: Error: Request failed with status code 500

### Mail app
**Mail app version:** (see apps admin page, e.g. 0.5.3)
1.7.2
**Mailserver or service:** (e.g. Outlook, Yahoo, Gmail, Exchange,...)
This is a corporate mailserver running postfix 3.4.14 with dovecot 2.3.4.1

### Server configuration
**Operating system**: (e.g. Debian 8)
Debian 10

**Web server:** (e.g. Apache, Nginx,...)
Apache 2.4.38

**Database:** (e.g. MariaDB, SQLite or PostgreSQL)
MariaDB 10.3.27
**PHP version:** (e.g. 7.0)
7.3.19
**Nextcloud Version:** (see admin page, e.g. 13.0.2)
20.0.4
#### Client configuration
**Browser:** (e.g. Firefox 48)
Firefox 78.6.0
**Operating system:** (e.g. Arch Linux)
Debian 10

Log says:
[mail] Error: OCA\Mail\Exception\ServiceException: Sync failed for 3:INBOX: Error connecting to mail server. at <<closure>>

0. /var/www/nextcloud/apps/mail/lib/Service/Sync/SyncService.php line 121
   OCA\Mail\Service\Sync\ImapToDbSynchronizer->sync(OCA\Mail\Account {}, OCA\Mail\Db\Mailbox {id: 22}, OC\AppFramework\ScopedPsrLogger {}, 42, [1,5,10,11], false)
1. /var/www/nextcloud/apps/mail/lib/Controller/MailboxesController.php line 161
   OCA\Mail\Service\Sync\SyncService->syncMailbox(OCA\Mail\Account {}, OCA\Mail\Db\Mailbox {id: 22}, 42, [794,772,767,763], true, null)
2. /var/www/nextcloud/lib/private/AppFramework/Http/Dispatcher.php line 169
   OCA\Mail\Controller\MailboxesController->sync(22, [794,772,767,763], false, null)
3. /var/www/nextcloud/lib/private/AppFramework/Http/Dispatcher.php line 100
   OC\AppFramework\Http\Dispatcher->executeController(OCA\Mail\Control ... {}, "sync")
4. /var/www/nextcloud/lib/private/AppFramework/App.php line 152
   OC\AppFramework\Http\Dispatcher->dispatch(OCA\Mail\Control ... {}, "sync")
5. /var/www/nextcloud/lib/private/Route/Router.php line 308
   OC\AppFramework\App::main("OCA\\Mail\\Cont ... r", "sync", OC\AppFramework\ ... {}, {action: null,id ... "})
6. /var/www/nextcloud/lib/base.php line 1008
   OC\Route\Router->match("/apps/mail/api/mailboxes/22/sync")
7. /var/www/nextcloud/index.php line 37
   OC::handleRequest()

POST /index.php/apps/mail/api/mailboxes/22/sync
from 79.145.131.140 by juaco at 2021-01-10T18:30:06+00:00

**Comment by ChristophWurst** [comment]
> Error connecting to mail server

If there isn't any obvious reason for this failing connection you can enable debug mode and check the horde logs at `data/horde_imap.log`.

**Comment by HannesJo0139** [comment]
I also encountered this error message when sending via yahoo. The mails has been sent anyway.

**Comment by ChristophWurst** [comment]
@HannesJo0139 please check your logs for the exception trace

**Comment by HannesJo0139** [comment]
> @HannesJo0139 please check your logs for the exception trace

Oh sometimes I am so dumb :D .. I thought this is a Yahoo server error since it only happens when sending via Yahoo :confused: 

However, this error happens when saving the draft:
```
[mail] Error: OCA\Mail\Exception\ServiceException: Could not save draft message at <<closure>>

0. /config/www/nextcloud/apps/mail/lib/Controller/AccountsController.php line 456
   OCA\Mail\Service\MailTransmission->saveDraft(OCA\Mail\Model\NewMessageData {}, null)
1. /config/www/nextcloud/lib/private/AppFramework/Http/Dispatcher.php line 169
   OCA\Mail\Controller\AccountsController->draft(6, "test", "this is a test mail", "", "", "", false, null)
2. /config/www/nextcloud/lib/private/AppFramework/Http/Dispatcher.php line 100
   OC\AppFramework\Http\Dispatcher->executeController(OCA\Mail\Controller\AccountsController {}, "draft")
3. /config/www/nextcloud/lib/private/AppFramework/App.php line 152
   OC\AppFramework\Http\Dispatcher->dispatch(OCA\Mail\Controller\AccountsController {}, "draft")
4. /config/www/nextcloud/lib/private/Route/Router.php line 308
   OC\AppFramework\App::main("OCA\\Mail\\Cont ... r", "draft", OC\AppFramework\ ... {}, {action: null,id ... "})
5. /config/www/nextcloud/lib/base.php line 1008
   OC\Route\Router->match("/apps/mail/api/accounts/6/draft")
6. /config/www/nextcloud/index.php line 37
   OC::handleRequest()

POST /apps/mail/api/accounts/6/draft
from _myIP_ by johannes at 2021-01-15T15:49:13+01:00
```


And that one when trying to send:
```
[mail] Error: OCA\Mail\Exception\ServiceException: Could not save sent message on IMAP at <<closure>>

 0. /config/www/nextcloud/lib/private/EventDispatcher/ServiceEventListener.php line 76
    OCA\Mail\Listener\SaveSentMessageListener->handle(OCA\Mail\Events\MessageSentEvent {})
 1. /config/www/nextcloud/3rdparty/symfony/event-dispatcher/EventDispatcher.php line 251
    OC\EventDispatcher\ServiceEventListener->__invoke(OCA\Mail\Events\MessageSentEvent {}, "OCA\\Mail\\Events\\MessageSentEvent", Symfony\Componen ... {})
 2. /config/www/nextcloud/3rdparty/symfony/event-dispatcher/EventDispatcher.php line 73
    Symfony\Component\EventDispatcher\EventDispatcher->callListeners([Closure {},Clos ... }], "OCA\\Mail\\Events\\MessageSentEvent", OCA\Mail\Events\MessageSentEvent {})
 3. /config/www/nextcloud/lib/private/EventDispatcher/EventDispatcher.php line 86
    Symfony\Component\EventDispatcher\EventDispatcher->dispatch(OCA\Mail\Events\MessageSentEvent {}, "OCA\\Mail\\Events\\MessageSentEvent")
 4. /config/www/nextcloud/apps/mail/lib/Service/MailTransmission.php line 178
    OC\EventDispatcher\EventDispatcher->dispatch("OCA\\Mail\\Events\\MessageSentEvent", OCA\Mail\Events\MessageSentEvent {})
 5. /config/www/nextcloud/apps/mail/lib/Controller/AccountsController.php line 405
    OCA\Mail\Service\MailTransmission->sendMessage(OCA\Mail\Model\NewMessageData {}, null, null, null)
 6. /config/www/nextcloud/lib/private/AppFramework/Http/Dispatcher.php line 169
    OCA\Mail\Controller\AccountsController->send(6, "test", "this is a test mail", "_myAdress_", "", "", false, null, null, [], null)
 7. /config/www/nextcloud/lib/private/AppFramework/Http/Dispatcher.php line 100
    OC\AppFramework\Http\Dispatcher->executeController(OCA\Mail\Controller\AccountsController {}, "send")
 8. /config/www/nextcloud/lib/private/AppFramework/App.php line 152
    OC\AppFramework\Http\Dispatcher->dispatch(OCA\Mail\Controller\AccountsController {}, "send")
 9. /config/www/nextcloud/lib/private/Route/Router.php line 308
    OC\AppFramework\App::main("OCA\\Mail\\Cont ... r", "send", OC\AppFramework\ ... {}, {action: null,id ... "})
10. /config/www/nextcloud/lib/base.php line 1008
    OC\Route\Router->match("/apps/mail/api/accounts/6/send")
11. /config/www/nextcloud/index.php line 37
    OC::handleRequest()

POST /apps/mail/api/accounts/6/send
from _myIP_ by johannes at 2021-01-15T15:51:40+01:00
```


Errors found in Horde-LOG:
```
------------------------------
>> Fri, 15 Jan 2021 15:04:43 +0000
>> Connection to: imap://imap.mail.yahoo.com:993/
>> Server connection took 0.1867 seconds.
S: * OK [CAPABILITY IMAP4rev1 SASL-IR AUTH=PLAIN AUTH=XOAUTH2 AUTH=OAUTHBEARER ID MOVE NAMESPACE XYMHIGHESTMODSEQ UIDPLUS LITERAL+ CHILDREN X-MSG-EXT OBJE$
C: 1 AUTHENTICATE PLAIN [INITIAL CLIENT RESPONSE (username: _myAdress_)]
S: 1 OK AUTHENTICATE completed
>> Command 1 took 0.1303 seconds.
C: 2 CAPABILITY
S: * CAPABILITY IMAP4rev1 ID MOVE NAMESPACE XYMHIGHESTMODSEQ UIDPLUS LITERAL+ CHILDREN X-MSG-EXT UNSELECT OBJECTID
S: 2 OK CAPABILITY completed
>> Command 2 took 0.2391 seconds.
>> CACHE: Using the OCA\Mail\Cache\Cache storage driver.
C: 3 APPEND Sent (\seen) {315+}
C: [LITERAL DATA: 315 bytes]
C: 
S: 3 BAD [CLIENTBUG] Additional arguments found after last expected argument
>> Command 3 took 0.0852 seconds.
>> ERROR: mail server explicitly reporting an error.
C: 4 LOGOUT
S: * BAD [CLIENTBUG] Command has no tag set
>> ERROR: mail server explicitly reporting an error.
S: * BYE IMAP4rev1 Server logging out
S: 4 OK LOGOUT completed
>> Command 4 took 0.2848 seconds.
------------------------------
```

**Comment by ChristophWurst** [comment]
> 3 BAD [CLIENTBUG] Additional arguments found after last expected argument

:open_mouth:

**Comment by HannesJo0139** [comment]
Best feature of all times to close issues due to inactivity lol. Loving Nextcloud but NC Mail is dead.

**Comment by HannesJo0139** [comment]
> @HannesJo0139 if you have nothing nice to say, how about you say nothing at all.

1. There is something nice: "Loving Nextcloud".
2. This page is about issues and not about kissing your ass.
3. Criticism is not a bad thing. My comment was not about hitting on anyone but criticizing the bad state of NC Mail and the automatic closing of unsolved issues.

**Comment by miaulalala** [comment]
> > @HannesJo0139 if you have nothing nice to say, how about you say nothing at all.
> 
> 1. There is something nice: "Loving Nextcloud".

Good, I'm glad.

> 2. This page is about issues and not about kissing your ass.

No asskissing needed, but a simple "This is still an issue" would have sufficed.

> 3. Criticism is not a bad thing. My comment was not about hitting on anyone but criticizing the bad state of NC Mail and the automatic closing of unsolved issues.

Closing issues that haven't had any interaction after a while is standard for a lot of repos. I'm sure I don't need to explain the logic behind it.

If you have any *constructive* feedback, feel free to post it. But "Mail is dead" is neither criticism nor is it constructive. As such, see my first comment.

**Comment by ChristophWurst** [comment]
Closing as stale.
