### ISSUE TITLE
Use Nextcloud's Symfony console

### ISSUE THREAD

**Issue by jernst** [nextcloud/mail#4342]
According to https://github.com/nextcloud/server/issues/25042#issuecomment-757676301, mail ships its own Symfony console, which may be picked up instead of Nextcloud's own, as it happened in https://github.com/nextcloud/server/issues/25042.

It appears mail should use Nextcloud's.

**Comment by ChristophWurst** [comment]
Blocked by https://github.com/coenjacobs/mozart/issues/79

**Comment by ChristophWurst** [comment]
I have a promising fix at https://github.com/nextcloud/mail/pull/4633
