### ISSUE TITLE
Maintain local copy of the emails

### ISSUE THREAD

**Issue by dhrunia** [nextcloud/mail#4344]
### Feature Request
Sync emails to a local database (in a /Mails folder maybe?) similar to what some email clients (thunderbird for example) do

#### Summary
Quite often either due to network issues or if mail server is down the mail app fails to load old emails, one has to wait for the issues to be fixed to gain access to old emails. It would be great if the mail app can sync emails to a local database similar to what some desktop email clients like thunderbird/evolution do. I am willing to work on this if someone can guide.

**Comment by ChristophWurst** [comment]
it's already being cached. downloading the full message is not planned right now.

thanks for the feedback :)

btw loading threads got a lot faster this week: #4583
