### ISSUE TITLE
backspace not working anymore 

### ISSUE THREAD

**Issue by StCyr** [nextcloud/mail#4355]
### Expected behavior
How to resimulate:

0. Using an account with "Rich Text" editing enabled;
1. Open a message;
2. Click on "Reply";
3. Remove some blank lines in the original message;
4. Type some text in your reply and try to delete it => it doesn't work

### Actual behavior
You should be able to delete the text you type

### Mail app

**Mail app version:** 1.7.1

#### Client configuration
**Browser:** Firefow latest (84.0.2 64bits)

**Operating system:** Windows 10

**Comment by ChristophWurst** [comment]
is there any error in the console?

**Comment by ChristophWurst** [comment]
I can't reproduce with 1.7.1

**Comment by StCyr** [comment]
When I delete the line from the original message, I get:

18:51:37.620 Uncaught CKEditorError: n is undefined
Read more: https://ckeditor.com/docs/ckeditor5/latest/framework/guides/support/error-codes.html#error-n is undefined
    value model.js:565
    m deletecontent.js:216
    default deletecontent.js:100
    value model.js:178
    default deletecontent.js:74
    value model.js:471
    decorate observablemixin.js:255
    fire emittermixin.js:209
    e observablemixin.js:259
    value deletecommand.js:113

Then after, when I type backspace, I get:

Uncaught CKEditorError: t is null
Read more: https://ckeditor.com/docs/ckeditor5/latest/framework/guides/support/error-codes.html#error-t is null
    e rect.js:63
    u scroll.js:186
    s scroll.js:43
    value view.js:392
    value delete.js:59
    fire emittermixin.js:209
    l deleteobserver.js:87
    c deleteobserver.js:50
    fire emittermixin.js:209
    value domeventobserver.js:96
    value keyobserver.js:28
    value domeventobserver.js:79
    fire emittermixin.js:209
    r emittermixin.js:247
    attach emittermixin.js:202
    listenTo emittermixin.js:61
    value domeventobserver.js:77
    value domeventobserver.js:76

**Comment by StCyr** [comment]
Here's a small clip showing the issue:

https://user-images.githubusercontent.com/8179031/104705315-0afc3880-571a-11eb-9cba-bce4fe1b1d8d.mp4
