### ISSUE TITLE
Cannot install the app, as the Mail app is not listed as an available app

### ISSUE THREAD

**Issue by v0d** [nextcloud/mail#4371]
### Expected behavior
The install instructions [here](https://github.com/nextcloud/mail/blob/master/doc/admin.md) mention:
 "simply navigate to »Apps«, choose the category »Social & Communication«, find the Mail app and enable it.

### Actual behavior
The "Mail" app is not listed under `hostname/settings/apps/social`

### Server configuration

**Operating system**: Ubuntu 20.04.1 LTS
**Web server:** Apache2.4.41
**Database:**  Ver 15.1 Distrib 10.3.25-MariaDB, for debian-linux-gnu (x86_64) using readline 5.2
**PHP version:**  PHP 7.4.3-4ubuntu2.4
**Nextcloud Version:** 20.0.5

Where can I find more information why the app is not available?

**Comment by v0d** [comment]
Well, the App appeared, once I've resolved all Security & setup warnings.

**Comment by GabrieleV** [comment]
Not here: no warnings, but mail app is missing...

**Comment by ntn888** [comment]
Same here: no warnings, but mail app is missing...
