### ISSUE TITLE
Could not load message.

### ISSUE THREAD

**Issue by vishdrck** [nextcloud/mail#4374]
## Steps to reproduce
1. Login to mail account in nextcloud
2. Emails won't  loading

## Expected behaviour
All emails should be appeared in the Inbox 

## Actual behaviour
Loading error

## Error
```
OCA\Mail\Exception\ServiceException: Could not load message
  at OCA\Mail\Service\MailManager::getMessage
     /usr/local/lib/owncloud/apps/mail/lib/Controller/MessagesController.php, line 218
  at OCA\Mail\Controller\MessagesController::getBody
     /usr/local/lib/owncloud/lib/private/AppFramework/Http/Dispatcher.php, line 170
  at OC\AppFramework\Http\Dispatcher::executeController
     /usr/local/lib/owncloud/lib/private/AppFramework/Http/Dispatcher.php, line 99
  at OC\AppFramework\Http\Dispatcher::dispatch
     /usr/local/lib/owncloud/lib/private/AppFramework/App.php, line 126
  at OC\AppFramework\App::main
     /usr/local/lib/owncloud/lib/private/AppFramework/Routing/RouteActionHandler.php, line 47
  at OC\AppFramework\Routing\RouteActionHandler::__invoke
  at call_user_func
     /usr/local/lib/owncloud/lib/private/Route/Router.php, line 297
  at OC\Route\Router::match
     /usr/local/lib/owncloud/lib/base.php, line 997
  at OC::handleRequest
     /usr/local/lib/owncloud/index.php, line 42

```

**Comment by ChristophWurst** [comment]
The Nextcloud mail app offers an extensive logging system to make it easier identifying and tracking down bugs. Please enable [debug mode](https://docs.nextcloud.com/server/stable/developer_manual/general/devenv.html#enabling-debug-mode) and set the log [level to debug](https://docs.nextcloud.com/server/stable/admin_manual/configuration_server/logging_configuration.html) in your admin settings. Then, try to reproduce your issue and take another look at `data/nextcloud.log`, `data/horde_imap.log` and `data/horde_smtp.log`. Make sure you don't post any sensitive information.
