### ISSUE TITLE
Mail sending failed with 500 when replying

### ISSUE THREAD

**Issue by abbasharoon** [nextcloud/mail#4375]
### Expected behavior
Mail should be sent

### Actual behavior
Clicking the send button returns error saying "Request Failed wtih status code 500"

### Mail app

**Mail app version:** 1.7.2
**Mailserver or service:** Custom Server based on VirtualMin

### Server configuration

**Operating system**: e.g. Ubuntu 18 LTS

**Web server:** Nginx

**Database:** MariaDB

**PHP version:**  7.2

**Nextcloud Version:** 20.0.4

#### Client configuration
**Browser:** Firefox 84.0.2

**Operating system:** Windows

#### Error Log
[mail] Error: OCA\Mail\Exception\ServiceException: Could not send message: mail() returned failure. at <<closure>>

0. /var/snap/nextcloud/25647/nextcloud/extra-apps/mail/lib/Controller/AccountsController.php line 405
   OCA\Mail\Service\MailTransmission->sendMessage(OCA\Mail\Model\NewMessageData {}, null, null, OCA\Mail\Db\Message {id: 104399})
1. /snap/nextcloud/25647/htdocs/lib/private/AppFramework/Http/Dispatcher.php line 169
   OCA\Mail\Controller\AccountsController->send(1, "RE: I ordered m ... ]", "<p style=\"marg ... >", "reciepient-email@redacted", "", "", true, 104399, null, [], null)
2. /snap/nextcloud/25647/htdocs/lib/private/AppFramework/Http/Dispatcher.php line 100
   OC\AppFramework\Http\Dispatcher->executeController(OCA\Mail\Controller\AccountsController {}, "send")
3. /snap/nextcloud/25647/htdocs/lib/private/AppFramework/App.php line 152
   OC\AppFramework\Http\Dispatcher->dispatch(OCA\Mail\Controller\AccountsController {}, "send")
4. /snap/nextcloud/25647/htdocs/lib/private/Route/Router.php line 308
   OC\AppFramework\App::main("OCA\\Mail\\Cont ... r", "send", OC\AppFramework\ ... {}, {action: null,id ... "})
5. /snap/nextcloud/25647/htdocs/lib/base.php line 1008
   OC\Route\Router->match("/apps/mail/api/accounts/1/send")
6. /snap/nextcloud/25647/htdocs/index.php line 37
   OC::handleRequest()

POST /index.php/apps/mail/api/accounts/1/send
from 127.0.0.1 by username-redacted at 2021-01-18T16:57:26+00:00

**Comment by ChristophWurst** [comment]
The Nextcloud mail app offers an extensive logging system to make it easier identifying and tracking down bugs. Please enable [debug mode](https://docs.nextcloud.com/server/stable/developer_manual/general/devenv.html#enabling-debug-mode) and set the log [level to debug](https://docs.nextcloud.com/server/stable/admin_manual/configuration_server/logging_configuration.html) in your admin settings. Then, try to reproduce your issue and take another look at `data/nextcloud.log`, `data/horde_imap.log` and `data/horde_smtp.log`. Please make sure that your logs do not contain any sensitive data.

**Comment by abbasharoon** [comment]
Thanks @ChristophWurst, 

The debug mode link you shared is broken. I manually changed the log level to 0 but nothing else is logged except the following when I try to send an email:

```
  | OCA\Mail\Exception\ServiceException: Could not send message: mail() returned failure./var/snap/nextcloud/25647/nextcloud/extra-apps/mail/lib/Controller/AccountsController.php - line 407: OCA\Mail\Service\MailTransmission->sendMessage(OCA\Mail\Mod ... {}, null, null, OCA\Mail\Db\Message { id: 37})/snap/nextcloud/25647/htdocs/lib/private/AppFramework/Http/Dispatcher.php - line 169: OCA\Mail\Controller\AccountsController->send(1, "Is the mail forwarded to you?", "Seems like  ... l", "receipent@email-reducted", "", "", false, false, 37, null, [], null)/snap/nextcloud/25647/htdocs/lib/private/AppFramework/Http/Dispatcher.php - line 100: OC\AppFramework\Http\Dispatcher->executeController(OCA\Mail\Con ... {}, "send")/snap/nextcloud/25647/htdocs/lib/private/AppFramework/App.php - line 152: OC\AppFramework\Http\Dispatcher->dispatch(OCA\Mail\Con ... {}, "send")/snap/nextcloud/25647/htdocs/lib/private/Route/Router.php - line 308: OC\AppFramework\App::main("OCA\\Mail\\ ... r", "send", OC\AppFramew ... {}, { action: nu ... "})/snap/nextcloud/25647/htdocs/lib/base.php - line 1008: OC\Route\Router->match("/apps/mail/ ... d")/snap/nextcloud/25647/htdocs/index.php - line 37: OC::handleRequest()Caused by Horde_Mime_Exception: mail() returned failure./var/snap/nextcloud/25647/nextcloud/extra-apps/mail/vendor/pear-pear.horde.org/Horde_Mime/Horde/Mime/Mail.php - line 479: Horde_Mime_Part->send("reciepent@email-redacted", Horde_Mime_Headers {}, Horde_Mail_T ... "})/var/snap/nextcloud/25647/nextcloud/extra-apps/mail/lib/Service/MailTransmission.php - line 186: Horde_Mime_Mail->send(Horde_Mail_T ... "}, false, false)/var/snap/nextcloud/25647/nextcloud/extra-apps/mail/lib/Controller/AccountsController.php - line 407: OCA\Mail\Service\MailTransmission->sendMessage(OCA\Mail\Mod ... {}, null, null, OCA\Mail\Db\Message { id: 37})/snap/nextcloud/25647/htdocs/lib/private/AppFramework/Http/Dispatcher.php - line 169: OCA\Mail\Controller\AccountsController->send(1, "Is the mail forwarded to you?", "Seems like  ... l", "receipent@email-redacted", "", "", false, false, 37, null, [], null)/snap/nextcloud/25647/htdocs/lib/private/AppFramework/Http/Dispatcher.php - line 100: OC\AppFramework\Http\Dispatcher->executeController(OCA\Mail\Con ... {}, "send")/snap/nextcloud/25647/htdocs/lib/private/AppFramework/App.php - line 152: OC\AppFramework\Http\Dispatcher->dispatch(OCA\Mail\Con ... {}, "send")/snap/nextcloud/25647/htdocs/lib/private/Route/Router.php - line 308: OC\AppFramework\App::main("OCA\\Mail\\ ... r", "send", OC\AppFramew ... {}, { action: nu ... "})/snap/nextcloud/25647/htdocs/lib/base.php - line 1008: OC\Route\Router->match("/apps/mail/ ... d")/snap/nextcloud/25647/htdocs/index.php - line 37: OC::handleRequest()Caused by Horde_Mail_Exception: mail() returned failure./var/snap/nextcloud/25647/nextcloud/extra-apps/mail/vendor/pear-pear.horde.org/Horde_Mime/Horde/Mime/Part.php - line 1620: Horde_Mail_Transport_Mail->send("receipent@email-redacted", { From: "Abb ... "}, "Seems like  ... l")/var/snap/nextcloud/25647/nextcloud/extra-apps/mail/vendor/pear-pear.horde.org/Horde_Mime/Horde/Mime/Mail.php - line 479: Horde_Mime_Part->send("receipent@email-redacted", Horde_Mime_Headers {}, Horde_Mail_T ... "})/var/snap/nextcloud/25647/nextcloud/extra-apps/mail/lib/Service/MailTransmission.php - line 186: Horde_Mime_Mail->send(Horde_Mail_T ... "}, false, false)/var/snap/nextcloud/25647/nextcloud/extra-apps/mail/lib/Controller/AccountsController.php - line 407: OCA\Mail\Service\MailTransmission->sendMessage(OCA\Mail\Mod ... {}, null, null, OCA\Mail\Db\Message { id: 37})/snap/nextcloud/25647/htdocs/lib/private/AppFramework/Http/Dispatcher.php - line 169: OCA\Mail\Controller\AccountsController->send(1, "Is the mail forwarded to you?", "Seems like  ... l", "receipent@email-redacted", "", "", false, false, 37, null, [], null)/snap/nextcloud/25647/htdocs/lib/private/AppFramework/Http/Dispatcher.php - line 100: OC\AppFramework\Http\Dispatcher->executeController(OCA\Mail\Con ... {}, "send")/snap/nextcloud/25647/htdocs/lib/private/AppFramework/App.php - line 152: OC\AppFramework\Http\Dispatcher->dispatch(OCA\Mail\Con ... {}, "send")/snap/nextcloud/25647/htdocs/lib/private/Route/Router.php - line 308: OC\AppFramework\App::main("OCA\\Mail\\ ... r", "send", OC\AppFramew ... {}, { action: nu ... "})/snap/nextcloud/25647/htdocs/lib/base.php - line 1008: OC\Route\Router->match("/apps/mail/ ... d")/snap/nextcloud/25647/htdocs/index.php - line 37: OC::handleRequest()
-- | --
```

There are no data/horde_imap.log & data/horde_smtp.log in data folder ( I am using NC Snap). I also updated the mail app to version 18 with no luck. 

The smtp server is working fine on Android Gmail app, Mozilla Thunderbird & Outlook on desktop. I checked the credentials a dozen time and they are correct. I suspect the line where it says `Caused by Horde_Mime_Exception: mail() returned failure.` 
but TBH the issue is a bit frustrating as there is no proper clue on what's causing the error when everything else seems to be entered correctly.

**Comment by ChristophWurst** [comment]
> mail() returned failure

Did you enable https://github.com/nextcloud/mail/blob/master/doc/admin.md#use-php-mail-for-sending-mail?

**Comment by abbasharoon** [comment]
Yes, without it the IMAP doesn't work at all. With PHP-mail enabled, the server is able to fetch the emails but not send it

![image](https://user-images.githubusercontent.com/6374851/105517569-07a81480-5cf9-11eb-8db3-2f65b43f5add.png)

**Comment by ChristophWurst** [comment]
Ok but the php-mail is for very specific setups only, you're most likely using it wrong.

Like you couldn't first set up your account because the SMTP settings are incorrect. After switching to php-mail the setup succeds because SMTP is off. Now you want to send a mail and php-mail is actually not working. Duh.

Figure out the right SMTP settings and disable php-mail, then your account will work.
