### ISSUE TITLE
CAN NOT DOWNLOAD 

### ISSUE THREAD

**Issue by informaticavera** [nextcloud/mail#4378]
### Question
I USED THE LAST VERSION NEXTCLOUD BUT CAN NOT DOWNLOAD AND INSTALL APP

root@nextcloud:/var/www/nextcloud # sudo -u www-data php occ app:install mail
Error: Could not download app mail

**Comment by Jojo-Burger** [comment]
Personally I cannot download it from the WEB interface, I also use the last versin.

**Comment by ChristophWurst** [comment]
> Please ask your question in the community forum at https://help.nextcloud.com/c/apps/mail
