### ISSUE TITLE
No error message shown when no PGP key available for recipient (Mailvelope)

### ISSUE THREAD

**Issue by cnmicha** [nextcloud/mail#4379]
### Expected behavior
When trying to send an encrypted email (using Mailvelope) to a recipent we don't know the key from, show an error message to the user.

### Actual behavior
No error message is shown.

Browser console:
> Error: No valid encryption key for recipient address
>     at mapError (mailvelope-client-api.js:813)
>     at eventListener (mailvelope-client-api.js:783)

### Mail app

**Mail app version:** 1.7.2

**Mailserver or service:** Custom IMAP/SMTP

### Server configuration

**Operating system**: Debian 10

**Web server:** Nginx

**Database:** MariaDB

**PHP version:** 7.4.14

**Nextcloud Version:** 20.0.5

#### Client configuration
**Browser:** Chrome

**Operating system:** Ubuntu

**Comment by ChristophWurst** [comment]
thanks for the report, @cnmicha. I think that trace is actually from Mailvelope, not the Mail app, correct?

**Comment by cnmicha** [comment]
I cannot reproduce the issue anymore and I don't know what changed. Now, Mailvelope shows an error message if there is no key for the recipient. Thanks.
