### ISSUE TITLE
Installation/Update/Activation of mail app 1.8.0 not possible

### ISSUE THREAD

**Issue by klassikmann** [nextcloud/mail#4380]
### Expected behavior
Update mail app from 1.7.2 to 1.8.0 runs smoothly. 

### Actual behavior
On update or new installation I get:
An exception occurred while executing 'CREATE TABLE oc_mail_trusted_senders (id INT AUTO_INCREMENT NOT NULL, email VARCHAR(255) NOT NULL, user_id VARCHAR(64) NOT NULL, UNIQUE INDEX mail_trusted_sender_uniq (email, user_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_bin` ENGINE = InnoDB ROW_FORMAT = compressed': SQLSTATE[42000]: Syntax error or access violation: 1071 Specified key was too long; max key length is 767 bytes

### Mail app

**Mail app version:** (see apps admin page, e.g. 0.5.3)
1.8.0
**Mailserver or service:** (e.g. Outlook, Yahoo, Gmail, Exchange,...)
Not yet configured

### Server configuration

**Operating system**: (e.g. Debian 8)
Armbian 20.11.6 Buster with Linux 5.9.14-mvebu
**Web server:** (e.g. Apache, Nginx,...)
nginx
**Database:** (e.g. MariaDB, SQLite or PostgreSQL)
mariaDB
**PHP version:** (e.g. 7.0)
7.4.14
**Nextcloud Version:** (see admin page, e.g. 13.0.2)
20.0.5
#### Client configuration
**Browser:** (e.g. Firefox 48)
Firefox 84.0.2 (but problem is not client related)
**Operating system:** (e.g. Arch Linux)
Windows 10 (but problem is not client related)

**Comment by ChristophWurst** [comment]
Please see https://github.com/nextcloud/twofactor_totp/issues/1051 and let us know if that issue could be related

**Comment by ChristophWurst** [comment]
is your database configured according to https://docs.nextcloud.com/server/stable/admin_manual/configuration_database/mysql_4byte_support.html?

**Comment by klassikmann** [comment]
> 
> 
> is your database configured according to https://docs.nextcloud.com/server/stable/admin_manual/configuration_database/mysql_4byte_support.html?

I did it successfully in the past. But now innodb_file_format fell back to "Antelope". I tried to set "Barracuda" but after a restart of the mariadb container I'm back at "Antilope".

**Comment by ChristophWurst** [comment]
Hm.. Well that would at least explain why this migration fails, the table is created with the wrong storage format. Could you check the db manual or any other online resources for this? You might also have some luck on https://help.nextcloud.com/

**Comment by klassikmann** [comment]
Mea culpa! (I did too many things in parallel.)
I'm using MariaDB 10.1.47 and I forgot the commands in the section "MariaDB 10.2 or earlier" in the document "Enabling MySQL 4-byte support". 
Activation of the mail app 1.8.0 was possible now.
