### ISSUE TITLE
Mail app not available for installation

### ISSUE THREAD

**Issue by GabrieleV** [nextcloud/mail#4383]
### Expected behavior
The mail app must show up in available apps from the Nextcloud web interface

### Actual behavior
The app is not liste

### Mail app

NA

### Server configuration

**Operating system**: Debian 10

**Web server:** Apache

**Database:** MariaDB

**PHP version:** 7.3.19-1

**Nextcloud Version:** 20.0.5

#### Client configuration
**Browser:** Firefox 84.0.2 (64-bit)

**Operating system:** Ubuntu 20.10

Nextcloud Report attached
[2021-01-22.txt](https://github.com/nextcloud/mail/files/5855266/2021-01-22.txt)

**Comment by ChristophWurst** [comment]
Sounds like https://github.com/nextcloud/server/issues/25137

**Comment by reekol** [comment]
Up. Same here - Nextcloud  20.0.5.

**Comment by snejball** [comment]
Looks like I am affected as well, also on Nextcloud 20.0.5 fresh installation

**Comment by ChristophWurst** [comment]
@reekol @snejball read https://github.com/nextcloud/mail/issues/4383#issuecomment-765322133

**Comment by snejball** [comment]
> @reekol @snejball read [#4383 (comment)](https://github.com/nextcloud/mail/issues/4383#issuecomment-765322133)

Thank you for suggesting this, I applied the fix mentioned, but it seems to have no effect, unfortunately

**Comment by ChristophWurst** [comment]
> **PHP version:** 7.3.19-1

Do all of you use a php version like that, e.g. with the hyphen at the end?

**Comment by GabrieleV** [comment]
<pre>
# php -version
PHP 7.3.19-1~deb10u1 (cli) (built: Jul  5 2020 06:46:45) ( NTS )
Copyright (c) 1997-2018 The PHP Group
Zend Engine v3.3.19, Copyright (c) 1998-2018 Zend Technologies
    with Zend OPcache v7.3.19-1~deb10u1, Copyright (c) 1999-2018, by Zend Technologies
</pre>

**Comment by reekol** [comment]
PHP 7.4.14 (cli) (built: Jan 13 2021 08:04:06) ( NTS )
Copyright (c) The PHP Group
Zend Engine v3.4.0, Copyright (c) Zend Technologies
    with Zend OPcache v7.4.14, Copyright (c), by Zend Technologies

**Comment by reekol** [comment]
Something interesting. After fresh install it does not appear. Few days later it's on the store. Changes i have made since then ( installation ) are to enable opcache and redis ( may not be relevant ).

**Comment by GabrieleV** [comment]
Fresh installed 9 days ago, mail app never appeared.
I've enabled opcache too, not redis.

**Comment by GabrieleV** [comment]
Just upgraded to 20.0.6 and now the mail app is listed ...

**Comment by ChristophWurst** [comment]
Looking at https://github.com/nextcloud/server/commit/bedd9acf7874b836bef224989c2ce7f5e3b0a2fa I think we now do version comparisons wrong. PHP's `version_compare` will return `false` for `version_compare('7.4.14', '7.4', '<=')`. But if the app says it's compatible with 7.4 then 7.4.14 is totally fine. 7.4 shouldn't be expanded to 7.4.0. I'll see how we can fix this.

**Comment by ChristophWurst** [comment]
Patch is at https://github.com/nextcloud/server/pull/25335. Please let me know if that helps.

**Comment by GuillaumeAmat** [comment]
@ChristophWurst  It doesn't seem to do the job for me :/

**Comment by ChristophWurst** [comment]
@GuillaumeAmat any more info? Are you sure your server didn't just use a cached version of the filtered response? Check again now if my patch is still applied.

**Comment by GuillaumeAmat** [comment]
Oh you're right it's working now 👌 Thanks for the cache tip

**Comment by schmichri** [comment]
@ChristophWurst  Sorry. But for the stupids like me. Mail App is still not listed on my 20.0.6 installation. What cache do I have to reset?

**Comment by ChristophWurst** [comment]
did you apply the patch? if so, just wait an hour or so, I don't recall the cache TTL.

**Comment by schmichri** [comment]
have I applied the patch correctly?

```
                                                        $minPhpFulfilled = $minPhpVersion === '' || version_compare(
                                                                        PHP_VERSION,
                                                                        $minPhpVersion,
                                                                        '>='
                                                                );
                                                        $maxPhpFulfilled = $maxPhpVersion === '' || version_compare(
                                                                        PHP_VERSION,
                                                                        $maxPhpVersion,
                                                                        '<='
                                                                );
```

**Comment by ChristophWurst** [comment]
Instructions are at https://github.com/nextcloud/server/pull/25335#issuecomment-769316364

**Comment by schmichri** [comment]
thanks a lot! I just understood a `patch` command. Love it!

**Comment by Javihache** [comment]
how do we patch for docker installations?

**Comment by schmichri** [comment]
I've done it inside the running container something like this: 

```
docker exec -it -u www-data nextcloud_app_1   wget https://patch-diff.githubusercontent.com/raw/nextcloud/server/pull/25335.patch
docker exec -it -u www-data nextcloud_app_1  patch -p1 < 25335.patch
```
