### ISSUE TITLE
Mail app does not work after 1.8.0 upgrade

### ISSUE THREAD

**Issue by Tachi107** [nextcloud/mail#4385]
### Expected behavior
Nothing should break after an upgrade

### Actual behavior
The mail app is completely broken, it does not load.
![image](https://user-images.githubusercontent.com/34214253/105523951-50eb6a80-5cdf-11eb-9681-dd6afc3cf736.png)

### Mail app

**Mail app version:** 1.8.0

**Mailserver or service:** Self-hosted on the same server, Postfix + Dovecot

### Server configuration

**Operating system**: Debian 10

**Web server:** Nginx

**Database:** PostgreSQL

**PHP version:** 7.3

**Nextcloud Version:** 20.0.4

**Nextcloud, web server and client logs**: Nothing relevant

#### Client configuration
**Browser:** Chromium 87

**Operating system:** Debian Testing

**Comment by ChristophWurst** [comment]
What does the browser console say? Smells like a js error

**Comment by Tachi107** [comment]
JQuery deprecation stuff and this:
![image](https://user-images.githubusercontent.com/34214253/105528932-e558cb80-5ce5-11eb-9565-eb2b21e819d3.png)

Full log
``` log
index.js:46 No OC found
t.getLanguage @ index.js:46
jquery-migrate.min.js:2 JQMIGRATE: Migrate is installed, version 1.4.1
globals.js:60 jQuery is deprecated: The global jQuery is deprecated. It will be updated to v3.x in Nextcloud 21. In later versions of Nextcloud it might be removed completely. Please ship your own.
ie @ globals.js:60
globals.js:60 $ is deprecated: The global jQuery is deprecated. It will be updated to v3.x in Nextcloud 21. In later versions of Nextcloud it might be removed completely. Please ship your own.
ie @ globals.js:60
globals.js:60 jQuery is deprecated: The global jQuery is deprecated. It will be updated to v3.x in Nextcloud 21. In later versions of Nextcloud it might be removed completely. Please ship your own.
ie @ globals.js:60
globals.js:60 jQuery is deprecated: The global jQuery is deprecated. It will be updated to v3.x in Nextcloud 21. In later versions of Nextcloud it might be removed completely. Please ship your own.
ie @ globals.js:60
base64.mjs:203 Uncaught TypeError: Cannot read property 'replace' of undefined
    at P (base64.mjs:203)
    at Object.$ (base64.mjs:209)
    at Module.<anonymous> (main.js:80)
    at i (bootstrap:77)
    at bootstrap:242
    at mail.js?v=c4f44bee-0:1
session-heartbeat.js:97 session heartbeat polling started
```

**Comment by Tachi107** [comment]
The issue went away after upgrading to Nextcloud 20.0.6
