### ISSUE TITLE
Mail body for this mail(12345) could not be loaded

### ISSUE THREAD

**Issue by Joachim1305** [nextcloud/mail#4400]
### Expected behavior
Select a message for viewing the body.

### Actual behavior
Infinite spinning circle

### Mail app

**Mail app version:** 1.8

**Mailserver or service:** Protonmail Bridge (no problems with Thunderbird as IMAP-client !)

### Server configuration

**Operating system**: Linux

**Web server:** Apache

**Database:** MariaDB

**PHP version:** 7.4

**Nextcloud Version:** 20.0.5

#### Client configuration
**Browser:** Firefox 84.0.2

**Operating system:** Ubuntu 20.04

------------------------------
nextcloud.log:
---
OCA\Mail\Exception\ServiceException: Could not load message

    /var/www/nextcloud/apps/mail/lib/Controller/MessagesController.php - line 249:

    OCA\Mail\Service\MailManager->getImapMessage()

    /var/www/nextcloud/lib/private/AppFramework/Http/Dispatcher.php - line 169:

    OCA\Mail\Controller\MessagesController->getBody()

    /var/www/nextcloud/lib/private/AppFramework/Http/Dispatcher.php - line 100:

    OC\AppFramework\Http\Dispatcher->executeController()

    /var/www/nextcloud/lib/private/AppFramework/App.php - line 152:

    OC\AppFramework\Http\Dispatcher->dispatch()

    /var/www/nextcloud/lib/private/Route/Router.php - line 309:

    OC\AppFramework\App::main()

    /var/www/nextcloud/lib/base.php - line 1008:

    OC\Route\Router->match()

    /var/www/nextcloud/index.php - line 37:

    OC::handleRequest()

Verursacht durchOCP\AppFramework\Db\DoesNotExistException: Mail body for this mail(449) could not be loaded

    /var/www/nextcloud/apps/mail/lib/Model/IMAPMessage.php - line 535:

    OCA\Mail\Model\IMAPMessage->loadBodyData()

    /var/www/nextcloud/apps/mail/lib/Model/IMAPMessage.php - line 413:

    OCA\Mail\Model\IMAPMessage->handleTextMessage()

    /var/www/nextcloud/apps/mail/lib/Model/IMAPMessage.php - line 373:

    OCA\Mail\Model\IMAPMessage->getPart()

    /var/www/nextcloud/apps/mail/lib/Model/IMAPMessage.php - line 94:

    OCA\Mail\Model\IMAPMessage->loadMessageBodies()

    /var/www/nextcloud/apps/mail/lib/IMAP/MessageMapper.php - line 222:

    OCA\Mail\Model\IMAPMessage->__construct()

    <<closure>>

    OCA\Mail\IMAP\MessageMapper->OCA\Mail\IMAP\{closure}("*** sensiti ... *")

    /var/www/nextcloud/apps/mail/lib/IMAP/MessageMapper.php - line 236:

    array_map()

    /var/www/nextcloud/apps/mail/lib/IMAP/MessageMapper.php - line 64:

    OCA\Mail\IMAP\MessageMapper->findByIds()

    /var/www/nextcloud/apps/mail/lib/Service/MailManager.php - line 182:

    OCA\Mail\IMAP\MessageMapper->find()

    /var/www/nextcloud/apps/mail/lib/Controller/MessagesController.php - line 249:

    OCA\Mail\Service\MailManager->getImapMessage()

    /var/www/nextcloud/lib/private/AppFramework/Http/Dispatcher.php - line 169:

    OCA\Mail\Controller\MessagesController->getBody()

    /var/www/nextcloud/lib/private/AppFramework/Http/Dispatcher.php - line 100:

    OC\AppFramework\Http\Dispatcher->executeController()

    /var/www/nextcloud/lib/private/AppFramework/App.php - line 152:

    OC\AppFramework\Http\Dispatcher->dispatch()

    /var/www/nextcloud/lib/private/Route/Router.php - line 309:

    OC\AppFramework\App::main()

    /var/www/nextcloud/lib/base.php - line 1008:

    OC\Route\Router->match()

    /var/www/nextcloud/index.php - line 37:

    OC::handleRequest()

	

-----------------------------
horde_imap.log:
---
>> Sun, 24 Jan 2021 10:56:34 +0000
>> Connection to: imap://127.0.0.1:1143/
>> Server connection took 0.0001 seconds.
S: * OK [CAPABILITY IMAP4rev1 LITERAL+ SASL-IR CHILDREN STARTTLS AUTH=PLAIN AUTH=LOGIN ID APPENDLIMIT] IMAP4rev1 Service Ready
C: 1 AUTHENTICATE PLAIN [INITIAL CLIENT RESPONSE (username: yyy@pm.me)]
S: 1 OK [CAPABILITY IMAP4rev1 LITERAL+ SASL-IR CHILDREN IDLE MOVE ID QUOTA APPENDLIMIT=26214400 UNSELECT UIDPLUS] AUTHENTICATE completed
>> Command 1 took 0.0003 seconds.
>> CACHE: Using the OCA\Mail\Cache\Cache storage driver.
C: 2 EXAMINE INBOX
S: * FLAGS (\Seen \SEEN \Flagged \FLAGGED \Deleted \DELETED \Draft \DRAFT $junk junk nonjunk)
S: * OK [PERMANENTFLAGS (\Seen \SEEN \Flagged \FLAGGED \Deleted \DELETED \Draft \DRAFT $junk junk nonjunk)] Flags permitted.
S: * OK [UNSEEN 1] Message 1 is first unseen
S: * 0 RECENT
S: * OK [UIDNEXT 450] Predicted next UID
S: * OK [UIDVALIDITY 4] UIDs valid
S: * 1 EXISTS
S: 2 OK [READ-ONLY] EXAMINE completed
>> Command 2 took 0.0005 seconds.
C: 3 UID FETCH 449 (BODYSTRUCTURE)
------------------------------
>> Sun, 24 Jan 2021 10:56:34 +0000
>> Connection to: imap://127.0.0.1:1143/
>> Server connection took 0.0001 seconds.
S: * OK [CAPABILITY IMAP4rev1 LITERAL+ SASL-IR CHILDREN STARTTLS AUTH=PLAIN AUTH=LOGIN ID APPENDLIMIT] IMAP4rev1 Service Ready
C: 1 AUTHENTICATE PLAIN [INITIAL CLIENT RESPONSE (username: yyy@pm.me)]
S: 1 OK [CAPABILITY IMAP4rev1 LITERAL+ SASL-IR CHILDREN IDLE MOVE ID QUOTA APPENDLIMIT=26214400 UNSELECT UIDPLUS] AUTHENTICATE completed
>> Command 1 took 0.0003 seconds.
>> CACHE: Using the OCA\Mail\Cache\Cache storage driver.
C: 2 STATUS INBOX (MESSAGES UIDNEXT UIDVALIDITY)
S: * STATUS INBOX (MESSAGES 1 UIDNEXT 450 UIDVALIDITY 4)
S: 2 OK STATUS completed
>> Command 2 took 0.0003 seconds.
C: 3 STATUS INBOX (MESSAGES UIDNEXT UIDVALIDITY)
S: * STATUS INBOX (MESSAGES 1 UIDNEXT 450 UIDVALIDITY 4)
S: 3 OK STATUS completed
>> Command 3 took 0.0002 seconds.
C: 4 STATUS INBOX (MESSAGES UIDNEXT UIDVALIDITY)
S: * STATUS INBOX (MESSAGES 1 UIDNEXT 450 UIDVALIDITY 4)
S: 4 OK STATUS completed
>> Command 4 took 0.0002 seconds.
C: 5 LOGOUT
S: * BYE Closing connection
S: 5 OK LOGOUT completed
>> Command 5 took 0.0002 seconds.
------------------------------
>> Sun, 24 Jan 2021 10:56:34 +0000
>> Connection to: imap://127.0.0.1:1143/
>> Server connection took 0.0001 seconds.
S: * OK [CAPABILITY IMAP4rev1 LITERAL+ SASL-IR CHILDREN STARTTLS AUTH=PLAIN AUTH=LOGIN ID APPENDLIMIT] IMAP4rev1 Service Ready
C: 1 AUTHENTICATE PLAIN [INITIAL CLIENT RESPONSE (username: yyy@pm.me)]
S: 1 OK [CAPABILITY IMAP4rev1 LITERAL+ SASL-IR CHILDREN IDLE MOVE ID QUOTA APPENDLIMIT=26214400 UNSELECT UIDPLUS] AUTHENTICATE completed
>> Command 1 took 0.0003 seconds.
>> CACHE: Using the OCA\Mail\Cache\Cache storage driver.
C: 2 STATUS INBOX (MESSAGES UIDNEXT UIDVALIDITY)
S: * STATUS INBOX (MESSAGES 1 UIDNEXT 450 UIDVALIDITY 4)
S: 2 OK STATUS completed
>> Command 2 took 0.0003 seconds.
C: 3 STATUS INBOX (MESSAGES UIDNEXT UIDVALIDITY)
S: * STATUS INBOX (UIDVALIDITY 4 MESSAGES 1 UIDNEXT 450)
S: 3 OK STATUS completed
>> Command 3 took 0.0002 seconds.
C: 4 STATUS INBOX (MESSAGES UIDNEXT UIDVALIDITY)
S: * STATUS INBOX (MESSAGES 1 UIDNEXT 450 UIDVALIDITY 4)
S: 4 OK STATUS completed
>> Command 4 took 0.0002 seconds.
S: * 1 FETCH (BODYSTRUCTURE ("text" "plain" ("charset" "utf-8") NIL NIL "quoted-printable" 12 36 NIL ("inline" ()) NIL NIL) UID 449)
S: 3 OK UID FETCH completed
>> Command 3 took 0.2437 seconds.
>> CACHE: Stored messages [INBOX; 449]
C: 4 LOGOUT
S: * BYE Closing connection
S: 4 OK LOGOUT completed
>> Command 4 took 0.0021 seconds.
C: 5 LOGOUT
S: * BYE Closing connection
S: 5 OK LOGOUT completed
>> Command 5 took 0.0002 seconds.
------------------------------
>> Sun, 24 Jan 2021 10:56:34 +0000
>> Connection to: imap://127.0.0.1:1143/
>> Server connection took 0.0001 seconds.
S: * OK [CAPABILITY IMAP4rev1 LITERAL+ SASL-IR CHILDREN STARTTLS AUTH=PLAIN AUTH=LOGIN ID APPENDLIMIT] IMAP4rev1 Service Ready
C: 1 AUTHENTICATE PLAIN [INITIAL CLIENT RESPONSE (username: yyy@pm.me)]
S: 1 OK [CAPABILITY IMAP4rev1 LITERAL+ SASL-IR CHILDREN IDLE MOVE ID QUOTA APPENDLIMIT=26214400 UNSELECT UIDPLUS] AUTHENTICATE completed
>> Command 1 took 0.0004 seconds.
>> CACHE: Using the OCA\Mail\Cache\Cache storage driver.
C: 2 STATUS INBOX (MESSAGES UIDNEXT UIDVALIDITY)
S: * STATUS INBOX (MESSAGES 1 UIDNEXT 450 UIDVALIDITY 4)
S: 2 OK STATUS completed
>> Command 2 took 0.0003 seconds.
C: 3 STATUS INBOX (MESSAGES UIDNEXT UIDVALIDITY)
S: * STATUS INBOX (MESSAGES 1 UIDNEXT 450 UIDVALIDITY 4)
S: 3 OK STATUS completed
>> Command 3 took 0.0003 seconds.
C: 4 STATUS INBOX (MESSAGES UIDNEXT UIDVALIDITY)
S: * STATUS INBOX (UIDNEXT 450 UIDVALIDITY 4 MESSAGES 1)
S: 4 OK STATUS completed
>> Command 4 took 0.0003 seconds.
C: 5 EXAMINE INBOX
S: * FLAGS (\Seen \SEEN \Flagged \FLAGGED \Deleted \DELETED \Draft \DRAFT $junk junk nonjunk)
S: * OK [PERMANENTFLAGS (\Seen \SEEN \Flagged \FLAGGED \Deleted \DELETED \Draft \DRAFT $junk junk nonjunk)] Flags permitted.
S: * OK [UNSEEN 1] Message 1 is first unseen
S: * OK [UIDNEXT 450] Predicted next UID
S: * OK [UIDVALIDITY 4] UIDs valid
S: * 1 EXISTS
S: * 0 RECENT
S: 5 OK [READ-ONLY] EXAMINE completed
>> Command 5 took 0.0005 seconds.
>> CACHE: Retrieved messages (HICenv,HIChdrs,HICdate,HICdg [INBOX; 449])
C: 6 UID FETCH 449 (ENVELOPE FLAGS INTERNALDATE BODY.PEEK[HEADER.FIELDS (REFERENCES)])
S: * 1 FETCH (ENVELOPE ("Sun, 24 Jan 2021 11:53:35 +0100" "Testmail" (("xxx" NIL "xxx" "t-online.de")) (("xxx" NIL "xxx "t-online.de")) NIL ((NIL NIL "yyy" "pm.me")) NIL NIL NIL "<zzz.t-online.de>") FLAGS (nonjunk) INTERNALDATE "24-Jan-2021 11:53:35 +0100" BODY[HEADER.FIELDS (REFERENCES)] {126}
S: [LITERAL DATA: 126 bytes]
S:  UID 449)
S: 6 OK UID FETCH completed
>> Command 6 took 0.0118 seconds.
>> CACHE: Stored messages [INBOX; 449]
C: 7 UID SEARCH UID 449
S: * SEARCH 449
S: 7 OK UID SEARCH completed
>> Command 7 took 0.0006 seconds.
C: 8 LOGOUT
S: * BYE Closing connection
S: 8 OK LOGOUT completed
>> Command 8 took 0.005 seconds.
------------------------------
>> Sun, 24 Jan 2021 10:56:34 +0000
>> Connection to: imap://127.0.0.1:1143/
>> Server connection took 0.0001 seconds.
S: * OK [CAPABILITY IMAP4rev1 LITERAL+ SASL-IR CHILDREN STARTTLS AUTH=LOGIN AUTH=PLAIN ID APPENDLIMIT] IMAP4rev1 Service Ready
C: 1 LOGIN yyy@pm.me [PASSWORD]
S: 1 OK [CAPABILITY IMAP4rev1 LITERAL+ SASL-IR CHILDREN IDLE MOVE ID QUOTA APPENDLIMIT=26214400 UNSELECT UIDPLUS] LOGIN completed
>> Command 1 took 0.0003 seconds.
>> CACHE: Using the OCA\Mail\Cache\Cache storage driver.
C: 2 EXAMINE INBOX
S: * FLAGS (\Seen \SEEN \Flagged \FLAGGED \Deleted \DELETED \Draft \DRAFT $junk junk nonjunk)
S: * OK [PERMANENTFLAGS (\Seen \SEEN \Flagged \FLAGGED \Deleted \DELETED \Draft \DRAFT $junk junk nonjunk)] Flags permitted.
S: * OK [UNSEEN 1] Message 1 is first unseen
S: * OK [UIDVALIDITY 4] UIDs valid
S: * 1 EXISTS
S: * 0 RECENT
S: * OK [UIDNEXT 450] Predicted next UID
S: 2 OK [READ-ONLY] EXAMINE completed
>> Command 2 took 0.0004 seconds.
>> CACHE: Retrieved messages (HICenv,HIChdrs,HICdate,HICdg [INBOX; 449])
C: 3 UID FETCH 449 (FLAGS)
S: * 1 FETCH (FLAGS (nonjunk) UID 449)
S: 3 OK UID FETCH completed
>> Command 3 took 0.0106 seconds.
>> CACHE: Retrieved messages (HICenv,HIChdrs,HICdate,HICsize,HICstruct,HICdg [INBOX; 449])
C: 4 UID FETCH 449 (FLAGS RFC822.SIZE BODY.PEEK[HEADER.FIELDS (DISPOSITION-NOTIFICATION-TO)])
S: * 1 FETCH (FLAGS (nonjunk) RFC822.SIZE 3293 BODY[HEADER.FIELDS (DISPOSITION-NOTIFICATION-TO)] {0}
S:  UID 449)
S: 4 OK UID FETCH completed
>> Command 4 took 0.0106 seconds.
>> CACHE: Stored messages [INBOX; 449]
C: 5 UID FETCH 449 (BODY.PEEK[1] BODY.PEEK[1.MIME])
S: 5 NO list message build: wrong section 1
>> Command 5 took 0.0105 seconds.
C: 6 LOGOUT
S: * BYE Closing connection
S: 6 OK LOGOUT completed
>> Command 6 took 0.005 seconds.

**Comment by ChristophWurst** [comment]
try another time with this patch

```patch
diff --git a/lib/Model/IMAPMessage.php b/lib/Model/IMAPMessage.php
index 46f00da08..cf96e546c 100644
--- a/lib/Model/IMAPMessage.php
+++ b/lib/Model/IMAPMessage.php
@@ -48,6 +48,8 @@ use OCA\Mail\Service\Html;
 use OCP\AppFramework\Db\DoesNotExistException;
 use OCP\Files\File;
 use OCP\Files\SimpleFS\ISimpleFile;
+use function array_keys;
+use function implode;
 use function in_array;
 use function mb_convert_encoding;
 
@@ -583,7 +585,7 @@ class IMAPMessage implements IMessage, JsonSerializable {
                /* @var $fetch Horde_Imap_Client_Data_Fetch */
                $fetch = $headers[$this->messageId];
                if (is_null($fetch)) {
-                       throw new DoesNotExistException("Mail body for this mail($this->messageId) could not be loaded");
+                       throw new DoesNotExistException("Mail body for this mail($this->messageId) could not be loaded. Available UIDs are " . implode(', ', array_keys($headers)));
                }
 
                $mimeHeaders = $fetch->getMimeHeader($partNo, Horde_Imap_Client_Data_Fetch::HEADER_PARSE);
```

**Comment by Joachim1305** [comment]
Hi Christoph,
I applied the patch on a fresh mail 1.8.3 installation. Mail body still not loadable.
Please see corresponding logfiles:
[horde_imap.log](https://github.com/nextcloud/mail/files/6030649/horde_imap.log)
[nextcloud.log](https://github.com/nextcloud/mail/files/6030650/nextcloud.log)
Best regards
Joachim

**Comment by ChristophWurst** [comment]
ai, I made a little mistake. try

```patch
diff --git a/lib/Model/IMAPMessage.php b/lib/Model/IMAPMessage.php
index 46f00da08..ee09d87a0 100644
--- a/lib/Model/IMAPMessage.php
+++ b/lib/Model/IMAPMessage.php
@@ -356,7 +356,7 @@ class IMAPMessage implements IMessage, JsonSerializable {
                /** @var Horde_Imap_Client_Data_Fetch $fetch */
                $fetch = $headers[$this->messageId];
                if (is_null($fetch)) {
-                       throw new DoesNotExistException("This email ($this->messageId) can't be found. Probably it was deleted from the server recently. Please reload.");
+                       throw new DoesNotExistException("Mail body for this mail($this->messageId) could not be loaded. Available UIDs are " . implode(', ', array_keys($headers->ids())));
                }
 
                // set $this->fetch to get to, from ...
```

**Comment by Joachim1305** [comment]
I added 2nd patch to the first one. Hope this is ok.

Sent message "Test2" to myself. Same behavior.

[horde_imap.log](https://github.com/nextcloud/mail/files/6039142/horde_imap.log)
[nextcloud.log](https://github.com/nextcloud/mail/files/6039143/nextcloud.log)

**Comment by Joachim1305** [comment]
One more interesting observation:
Mail body is loaded, when message contains an attachment !
Attachment is loaded correctly as well.
[horde_imap.log](https://github.com/nextcloud/mail/files/6042058/horde_imap.log)

**Comment by ChristophWurst** [comment]
please also attach the nextcloud.log as that is where the patch will add the logging

**Comment by Joachim1305** [comment]
Ok. Please see
[horde_imap.log](https://github.com/nextcloud/mail/files/6044054/horde_imap.log)
[nextcloud.log](https://github.com/nextcloud/mail/files/6044055/nextcloud.log)
But  I am not sure, whether the patch works correctly.

**Comment by Joachim1305** [comment]
Please see another trial with V1.9 and patch for debugging purposes: 
[horde_imap.log](https://github.com/nextcloud/mail/files/6075310/horde_imap.log)
[nextcloud.log](https://github.com/nextcloud/mail/files/6075311/nextcloud.log)

**Comment by ChristophWurst** [comment]
> please also attach the nextcloud.log as that is where the patch will add the logging

use the data from the log file or copy the lines as *raw* from the web UI. The info you copied is lacking the full trace.

**Comment by Joachim1305** [comment]
Ok. Here you are :

[horde_imap.log](https://github.com/nextcloud/mail/files/6075984/horde_imap.log)
[nextcloud_raw.log](https://github.com/nextcloud/mail/files/6075985/nextcloud_raw.log)

As I mentioned earlier: Do you have any explanation, why the body is loaded, when there is an attachment ?

**Comment by ChristophWurst** [comment]
No UIDs are actually returned. This could be an issue with Horde. I don't have any more insights at the moment.
