### ISSUE TITLE
Subscribe/Unsubscribe on email folders broken.

### ISSUE THREAD

**Issue by yward** [nextcloud/mail#4402]
### Expected behavior
When managing an account by clicking the "..." button
Checking "Show Only Subscribed" should only show subscribed folder and the option should remain checked after initially activating it.
Shown here:
https://i.imgur.com/eOQkjcT.png
When you uncheck "Subscribed" box the folder should stay unsubscribed. As shown here:
https://i.imgur.com/R2mJqxf.png

### Actual behavior
The "Subscribed" check mark returns upon refreshing the mail App after you, same thing with the "Show Only Subscribed" option.

### Mail app

**Mail app version:** 1.8.0

**Mailserver or service:**  EXIM/Dovecot

### Server configuration

**Operating system**: Ubuntu 18.04

**Web server:** Apache

**Database:** MySQL 10.3.22

**PHP version:** 7.4.7

**Nextcloud Version:** 20.0.5

#### Client configuration
**Browser:** Firefox 84.0.2

**Operating system:** Windows 10

**Comment by GretaD** [comment]
Hello @yward,
I am trying to reproduce this error but all is good on my side. But can you please check your IMAP server in case the server toggles the subscription flag back?

**Comment by ChristophWurst** [comment]
yep, especially since it's about the INBOX I think the IMAP server could have a strong opinion about whether that should be subscribed :wink:

**Comment by yward** [comment]
So I added a gmail account to test it out and I believe I'm able to narrow down the issue a bit more.
@ChristophWurst note about the inbox folder is a tad bit accurate but it's not just the inbox, ANY folder that is native, i.e. with a black icon in the following image, cannot be toggled, however, custom created folders by users, i.e. the blue ones in the following image CAN be toggled.
I'm not sure if that is the intended behaviour, if so, this can be disregarded.

https://i.imgur.com/mznQgj5.png

**Comment by ChristophWurst** [comment]
> I'm not sure if that is the intended behaviour, if so, this can be disregarded.

The intention was to let the user change this server state.

The Nextcloud mail app offers an extensive logging system to make it easier identifying and tracking down bugs. Please enable [debug mode](https://docs.nextcloud.com/server/stable/developer_manual/getting_started/devenv.html#enabling-debug-mode). Then try to reproduce your issue and take a look at `data/horde_imap.log`. This will contain the IMAP communication and hopefully show us is the correct mailbox subscription is updated.

**Comment by ChristophWurst** [comment]
> i.e. the blue ones in the following image CAN be toggled

This could be an important detail btw. The blue ones are the ones without a special role.

**Comment by yward** [comment]
I did a test with two folders. "Test Folder" which is a  user created folder and "Sent" which is a system folder.

The log results look very similar, however the "Sent" folder almost instantly retoggle the subscription (regardless of logs), doesn't matter if it's gmail or my exim/dovecot setup, the following log is for the exim one though, not gmail.
https://pastebin.com/85ffympm

**Comment by ChristophWurst** [comment]
![Bildschirmfoto von 2021-01-25 14-50-40](https://user-images.githubusercontent.com/1374172/105714509-bb3d1e80-5f1c-11eb-9c57-7907963ab760.png)

(first and last highlighted rows are relevant)

Bingo. The server lets you unsubscribe but then the mailbox is said to be subscribed a moment later.

**Comment by yward** [comment]
> 
> 
> ![Bildschirmfoto von 2021-01-25 14-50-40](https://user-images.githubusercontent.com/1374172/105714509-bb3d1e80-5f1c-11eb-9c57-7907963ab760.png)
> 
> (first and last highlighted rows are relevant)
> 
> Bingo. The server lets you unsubscribe but then the mailbox is said to be subscribed a moment later.

As per my understaniding from what you explained and my intrepertation of the log, the mail sever is accepting the unsubscription, but horde's client is forcing it to revert to be subscribed with a tag called "special-use".

If so I think I need to take a look at horde's files to see if the behaviour can be edited, otherwise if I understood your explanation incorrectly and this is indeed the mail server's doing, then the issue is safe to close.

**Comment by ChristophWurst** [comment]
I'm sorry, I wasn't clear.

Horde instructs the IMAP server to unsubscribe. The server accepts. Then Horde asks for a listing of mailboxes and suddenly the mailbox is subscribed again.

Horde doesn't flip the switch, I think it's the IMAP server. And my guess is that the special-use \Send is responsible for the IMAP server behavior. 

From https://tools.ietf.org/html/rfc3501#section-6.3.7

> This command returns a tagged OK response only if the unsubscription is successful.

… which means your server is behaving off-standard.

**Comment by yward** [comment]
I'll reconduct this trial with gmail and outlook, however I did try gmail earlier and gmail acted identically to my EXIM server (didn't check the logs then but the front end behaviour was identical) @ChristophWurst 
Here's the gmail trial:
> 
> 
> So I added a gmail account to test it out and I believe I'm able to narrow down the issue a bit more.
> @ChristophWurst note about the inbox folder is a tad bit accurate but it's not just the inbox, ANY folder that is native, i.e. with a black icon in the following image, cannot be toggled, however, custom created folders by users, i.e. the blue ones in the following image CAN be toggled.
> I'm not sure if that is the intended behaviour, if so, this can be disregarded.
> 
> https://i.imgur.com/mznQgj5.png

**Comment by yward** [comment]
This can be closed, it was tested with roundcube and others and the behaviour is identical in other webmail clients, apologies for confusion.
