### ISSUE TITLE
Wrong attachment is sent when adding an attachment from Files

### ISSUE THREAD

**Issue by StCyr** [nextcloud/mail#4403]
### Expected behavior
Proper attachment sould be sent

### Actual behavior
Another attachment is sent (not random: if you send 3 times an email with fileA as attachment, it will consistenly be fileB which will be sent, not once fileB, then another one fileC,...)

The "send" request sent to the server contains the info about fileA. So, it seems the problem occurs after that point.

### Mail app

**Mail app version:** 1.8

**Comment by ChristophWurst** [comment]
> f you send 3 times an email with fileA as attachment, it will consistenly be fileB which will be sent

if you only ever picked file a, where does file b come from?

**Comment by ChristophWurst** [comment]
@davidpr78 @st3iny could anyone test the v1.8.1? is this fixed? we got a new and similar report with https://github.com/nextcloud/mail/issues/4464 but I can't reproduce
