### ISSUE TITLE
cannot update from 1.7.2 to 1.8

### ISSUE THREAD

**Issue by laurentiu2** [nextcloud/mail#4409]
### Expected behavior
received notification that Mail 1.8 is available, clicked on it and in Apps the Mail should have displayed the Update button.

### Actual behavior
The Update button is missing
(see screenshot
![Screenshot 2021-01-26 at 11 56 32](https://user-images.githubusercontent.com/29857699/105830114-c8feac80-5fcd-11eb-9d9f-073853595f38.png)
Cannot update from command line either (sudo -u www-data php occ app:update mail)

Error in Logging:
[no app in context] Info: Deprecated event type for {"[object] (OCP\SabrePluginEvent)":{"*statusCode":200,"*message":"","*server":{"[object] (OCA\DAV\Connector\Sabre\Server)":{"tree":"[object] (OCA\DAV\Connector\Sabre\ObjectTree)","*baseUri":"/remote.php/webdav/","httpResponse":"[object] (Sabre\HTTP\Response)","httpRequest":"[object] (Sabre\HTTP\Request)","sapi":"[object] (Sabre\HTTP\Sapi)","*plugins":[],"transactionType":null,"protectedProperties":{"...":"Over 20 items, aborting normalization"},"debugExceptions":false,"resourceTypeMapping":[],"enablePropfindDepthInfinity":true,"xml":"[object] (Sabre\DAV\Xml\Service)","*listeners":{"...":"Over 20 items, aborting normalization"},"*wildcardListeners":[],"*listenerIndex":[],"*logger":null}},"Symfony\Contracts\EventDispatcher\EventpropagationStopped":false}}: null

### Mail app

**Mail app version:** 1.7.2

**Mailserver or service:** Hetzner

### Server configuration

**Operating system**: Ubuntu 20

**Web server:** Apache

**Database:** MariaDB

**PHP version:** 7.4.3

**Nextcloud Version:** 20.0.5 / 20.0.6

#### Client configuration
**Browser:** Firefox 84.0.2

**Operating system:** Mac OS Catalina

**Comment by laurentiu2** [comment]
Tried to disable and then enable the Mail app:

Exception: Class 'Horde_Mail_Rfc822_Address' not found

    /var/www/nextcloud/lib/private/AppFramework/App.php - line 152:

    OC\AppFramework\Http\Dispatcher->dispatch()

    /var/www/nextcloud/lib/private/Route/Router.php - line 309:

    OC\AppFramework\App::main()

    /var/www/nextcloud/lib/base.php - line 1008:

    OC\Route\Router->match()

    /var/www/nextcloud/index.php - line 37:

    OC::handleRequest()

Caused by Error: Class 'Horde_Mail_Rfc822_Address' not found

    /var/www/nextcloud/apps/mail/lib/Migration/FixCollectedAddresses.php - line 56:

    OCA\Mail\Migration\FixCollectedAddresses->fixAddress()

    /var/www/nextcloud/lib/private/Repair.php - line 111:

    OCA\Mail\Migration\FixCollectedAddresses->run()

    /var/www/nextcloud/lib/private/legacy/OC_App.php - line 1042:

    OC\Repair->run()

    /var/www/nextcloud/lib/private/Installer.php - line 160:

    OC_App::executeRepairSteps()

    /var/www/nextcloud/apps/settings/lib/Controller/AppSettingsController.php - line 448:

    OC\Installer->installApp()

    /var/www/nextcloud/lib/private/AppFramework/Http/Dispatcher.php - line 169:

    OCA\Settings\Controller\AppSettingsController->enableApps()

    /var/www/nextcloud/lib/private/AppFramework/Http/Dispatcher.php - line 100:

    OC\AppFramework\Http\Dispatcher->executeController()

    /var/www/nextcloud/lib/private/AppFramework/App.php - line 152:

    OC\AppFramework\Http\Dispatcher->dispatch()

    /var/www/nextcloud/lib/private/Route/Router.php - line 309:

    OC\AppFramework\App::main()

    /var/www/nextcloud/lib/base.php - line 1008:

    OC\Route\Router->match()

    /var/www/nextcloud/index.php - line 37:

    OC::handleRequest()

Now it is completely unusable.

**Comment by ChristophWurst** [comment]
Could you check https://github.com/nextcloud/mail/issues/4383? I think this is the same issue. But maybe also https://github.com/nextcloud/mail/issues?q=is%3Aissue+Horde_Mail_Rfc822_Address+

**Comment by laurentiu2** [comment]
I used a backup from yesterday to rebuild my server, and after 4-5 attempts the update succeeded.
No explanation for me..
