### ISSUE TITLE
Complete inbox fails to load

### ISSUE THREAD

**Issue by freekvh** [nextcloud/mail#441]
### Steps to reproduce
1. receive a specific message
2. Inbox folder fails to load
3. Other folders do load

### Expected behaviour
It should show my inbox, in fact it does when I remove the message using another mail client

### Actual behaviour
Inbox not shown

### Mail app

**Mail app version:** 0.6.4

**Mailserver or service:** TransIP (imap)

**Transport security - IMAP:** SSL/TLS 

**Transport security - SMTP:** SSL/TLS

**Number of accounts:** 1

**Mail app version build date:** (only if you are using a Nightly Build)

### Server configuration

**Operating system**: Ubuntu 16.04

**Web server:** Nginx

**Database:** MariaDB

**PHP version:** 7

**Version:** (see admin page)

**Updated from an older version or fresh install:** Updated through several versions

**List of activated apps:** Many

#### Client configuration
**Browser:** Firefox 55

**Operating system:** Windows 10/Linux and osX

The special condition is that this mail contains an encoded images, the source looks like this:

```
--001a11c155589e8bfd0556db1226
Content-Type: multipart/alternative; boundary="001a11c155589e8bfb0556db1225"

--001a11c155589e8bfb0556db1225
Content-Type: text/plain; charset="UTF-8"

[image: Inline afbeelding 1]

--001a11c155589e8bfb0556db1225
Content-Type: text/html; charset="UTF-8"

<div dir="ltr"><img src="cid:ii_15dea40c3571f1fa" alt="Inline afbeelding 1" width="267" height="377"><br></div>

--001a11c155589e8bfb0556db1225--
--001a11c155589e8bfd0556db1226
Content-Type: image/png; name="image.png"
Content-Disposition: inline; filename="image.png"
Content-Transfer-Encoding: base64
Content-ID: <ii_15dea40c3571f1fa>
X-Attachment-Id: ii_15dea40c3571f1fa

iVBORw0KGgoAAAANSUhEUgAAAQsAAAF5CAYAAACIvw+YAAAgAElEQVR4Aey9abNk13Wmt3O8U82o
wlAACvNEgABIUaJISpQEmhRbcodDdnREK6J/gX+Svzo6wg67wz3IpESZ7BYpiiLAASQAAiRQhakm
1DzcOfNm+nneledWkVb3p/7gjuC5lZXn7LP3mtfaaw/nZO/mlYvzfr/fPPb29tpsNmvz+TzXlnf3
LPfo9Xr7ZV7/Zv3ufgfD+11b61vux7LpdLr/bdnScNTGfHrgFc4MevYW9PT7vTboD3Kv9QDE9Zzv
nn/UvRu25x3twpWvrsy6Xf2ONr+t1/fTk75UT72ubkpoO59xE3T90Sj1bOfHw7ri7drcXd7d9/vu
Nl53R2ju9ZvQ5vNZ6J5Opm0yneTcdnKqfJZGQ3Ap/5KlOAeDYRsOB4FvOUWpC1dFM7A7Gjucd3//
Jr3es+xu/f1TvFnm526+unYdTL+7eh3Ou2XVlXW4uvpd++5+V+713ecdbL/vPrpy63awuzrdt+V+
OniWe975g9fSOhgM7gad866uFx0Ov+8+FtYR3UUpi7qBK72BD05qxLy4FtfdsDv6ZtiFTaSkz4l1
PLpvzzv8Hb+Wdcdv3uuuQ8s/Ybvy7eH94e3b6zGw4XC4L5wOcFfpbkK6ezIjIgXaIeyU3yGwrvck
Whh+TzD+YrgU0glBeBMEMZns2Cho/L9T/Xy6uMi9XhvhrAs5BXaHsxNQx3wA8V9Ho9d382N5d89w
aDCoMutV3a7+bA8HnhW/g90pBlTUde2FLXm262TRtbWO537urt+V2RZz1FwSJJFa0YEJ9YE5JzJO
kfWEADuHhrayxDWBZHc3ch2Oxm1leYV7S/s4pGWO4GYEwO4Q32/S5r3i+dfr/WbZPwXjN+vcff2b

....


3ORtHZlreZ+Xz+aNwPDT+ZJ1+pbx678U3RYU1BmBVa8FKZQTbj9SXqapV9KddDy/65+KTEuAEW9a
3K/eppJap7e2b1BgQmw+9eZr+6E3L1CHtVQt4rdJnbn4lj8TPL3l0ptfaxVv1CUtC4mM9NaXdXxH
PdvPvVnGB//cQ9aUPnv9Ox+wj2/gavuxv7jfb2lh+wE1muMfSP+C+if11idru46VrwnO3tpWVQQS
PLh/S5lJf99atnZxG+DU+OafSbnQI5cnz6dVKvb+BI+Tsm+Wqfet7c+Xqdfy1z/f8bKsdU3e33Fz
+8db2/iL7qfTVSrW22/gVFjESLUMvPkX12UZcVI/xdFkDN7aF4W00yV9Ryp2+TWKeLuw4zrDdMSj
F+dz1mldMOj1/wapAPPr6bw6CQAAAABJRU5ErkJggg==
--001a11c155589e8bfd0556db1226--
```

**Comment by ChristophWurst** [comment]
Hi,

thanks a lot for reporting this. Could you please provide the relevant nextcloud.log entries to see where it fails specifically? Possibly there's a stacktrace being logged whenever the error occurs. Thanks

**Comment by freekvh** [comment]
Hi, no problem, glad to help improve my primary way of emailing ;)

I believe this to be the relevant error, it returns when I put the message in question back:


    Error | index | TypeError: Argument  1 passed to OCA\Mail\Model\IMAPMessage::hordeToAssoc() must be an  instance of Horde_Mail_Rfc822_Address, instance of  Horde_Mail_Rfc822_Group given, called in  /data/1/public_html/cloud.hmrt.nl/apps/mail/lib/Model/ConvertAddresses.php  on line 74 | 2017-08-17T21:40:40+0200
-- | -- | -- | --

**Comment by ChristophWurst** [comment]
> I believe this to be the relevant error, it returns when I put the message in question back in my inbox:

Interesting, this has been fixed already in #339 and will be included in 0.7 which I hope to release soon. Meanwhile you could try a nightly build to verify it's been fixed. Thanks!

**Comment by freekvh** [comment]
Ok, thanx, I can't play with nightlies as I rely to much on Nextclouds stable operation but I'm looking forward to the update in the future.

**Comment by ChristophWurst** [comment]
Great :)
