### ISSUE TITLE
Mail App Disappeared after NC Upgrade 20.0.6

### ISSUE THREAD

**Issue by KvoiceOxford** [nextcloud/mail#4410]
### Expected behaviour
Tell us what should happen

The Mail App should still be present after NC upgrade to 20.0.6.

### Actual behaviour
Tell us what happens instead

An angel - silent and dark as midnight - has removed the entire Mail App from my NC system including my emails and also she taken with her the Mail App installer which has also disappeared. I was not expecting that one!  'Where has it all gone,' I cry.  I'm too shocked to write any more about this right now. I'll just close my eyes and hope it all comes back.

**Comment by ChristophWurst** [comment]
Dup of https://github.com/nextcloud/mail/issues/4383?
