### ISSUE TITLE
Shared mailboxes are not shown: "skipping mailbox sync for shared/"

### ISSUE THREAD

**Issue by vasyugan** [nextcloud/mail#4421]
### Expected behavior
All subscribed mailboxes should be shown just as in Thunderbird or other IMAP clients

### Actual behavior
Shared mailboxes are not shown.

I wonder if this is the same as #3848, although the observation seems to be different. When I run occ mail:accounts:sync, it tells me for all the shared mailboxes:
`
[debug] Skipping mailbox sync for shared/user@domain/[mailbox name]`

When I run occ mail:account:diagnose for the account I get the following output:

```
IMAP capabilities:
- AUTH
- ENABLE
- ID
- IDLE
- IMAP4REV1
- LITERAL+
- LOGIN-REFERRALS
- SASL-IR

Horde error occurred: IMAP error reported by server.. See nextcloud.log for more details.

The error seems to be this: `
""CustomMessage":"Could not get account statistics: Horde_Imap_Client_Exception_ServerResponse: IMAP error reported by server."`

from the below logfile

```
in Nextcloud.log I find the following:

`{"reqId":"lNeGVlzdwdQ2lajUL5dr","level":3,"time":"2021-01-29T12:28:50+00:00","remoteAddr":"","user":"--","app":"mail","method":"","url":"--","message":{"Exception":"Horde_Imap_Client_Exception_ServerResponse","Message":"IMAP error reported by server.","Code":0,"Trace":[{"file":"/var/www/chrooted/someOrganisationweb/htdocs/cloud.someOrganisation.org/apps/mail/vendor/pear-pear.horde.org/Horde_Imap_Client/Horde/Imap/Client/Socket.php","line":4314,"function":"_getLine","class":"Horde_Imap_Client_Socket","type":"->"},{"file":"/var/www/chrooted/someOrganisationweb/htdocs/cloud.someOrganisation.org/apps/mail/vendor/pear-pear.horde.org/Horde_Imap_Client/Horde/Imap/Client/Socket.php","line":4242,"function":"_sendCmdChunk","class":"Horde_Imap_Client_Socket","type":"->"},{"file":"/var/www/chrooted/someOrganisationweb/htdocs/cloud.someOrganisation.org/apps/mail/vendor/pear-pear.horde.org/Horde_Imap_Client/Horde/Imap/Client/Socket.php","line":1751,"function":"_sendCmd","class":"Horde_Imap_Client_Socket","type":"->"},{"file":"/var/www/chrooted/someOrganisationweb/htdocs/cloud.someOrganisation.org/apps/mail/vendor/pear-pear.horde.org/Horde_Imap_Client/Horde/Imap/Client/Base.php","line":1733,"function":"_status","class":"Horde_Imap_Client_Socket","type":"->"},{"file":"/var/www/chrooted/someOrganisationweb/htdocs/cloud.someOrganisation.org/apps/mail/lib/Command/DiagnoseAccount.php","line":136,"function":"status","class":"Horde_Imap_Client_Base","type":"->"},{"function":"OCA\\Mail\\Command\\{closure}","class":"OCA\\Mail\\Command\\DiagnoseAccount","type":"->","args":["*** sensitive parameters replaced ***"]},{"file":"/var/www/chrooted/someOrganisationweb/htdocs/cloud.someOrganisation.org/apps/mail/lib/Command/DiagnoseAccount.php","line":138,"function":"array_reduce"},{"file":"/var/www/chrooted/someOrganisationweb/htdocs/cloud.someOrganisation.org/apps/mail/lib/Command/DiagnoseAccount.php","line":90,"function":"printMailboxesMessagesStats","class":"OCA\\Mail\\Command\\DiagnoseAccount","type":"->"},{"file":"/var/www/chrooted/someOrganisationweb/htdocs/cloud.someOrganisation.org/apps/mail/vendor/symfony/console/Command/Command.php","line":255,"function":"execute","class":"OCA\\Mail\\Command\\DiagnoseAccount","type":"->"},{"file":"/var/www/chrooted/someOrganisationweb/htdocs/cloud.someOrganisation.org/apps/mail/vendor/symfony/console/Application.php","line":971,"function":"run","class":"Symfony\\Component\\Console\\Command\\Command","type":"->"},{"file":"/var/www/chrooted/someOrganisationweb/htdocs/cloud.someOrganisation.org/apps/mail/vendor/symfony/console/Application.php","line":290,"function":"doRunCommand","class":"Symfony\\Component\\Console\\Application","type":"->"},{"file":"/var/www/chrooted/someOrganisationweb/htdocs/cloud.someOrganisation.org/apps/mail/vendor/symfony/console/Application.php","line":166,"function":"doRun","class":"Symfony\\Component\\Console\\Application","type":"->"},{"file":"/var/www/chrooted/someOrganisationweb/htdocs/cloud.someOrganisation.org/lib/private/Console/Application.php","line":215,"function":"run","class":"Symfony\\Component\\Console\\Application","type":"->"},{"file":"/var/www/chrooted/someOrganisationweb/htdocs/cloud.someOrganisation.org/console.php","line":100,"function":"run","class":"OC\\Console\\Application","type":"->"},{"file":"/var/www/chrooted/someOrganisationweb/htdocs/cloud.someOrganisation.org/occ","line":11,"args":["/var/www/chrooted/someOrganisationweb/htdocs/cloud.someOrganisation.org/console.php"],"function":"require_once"}],"File":"/var/www/chrooted/someOrganisationweb/htdocs/cloud.someOrganisation.org/apps/mail/vendor/pear-pear.horde.org/Horde_Imap_Client/Horde/Imap/Client/Socket.php","Line":4602,**"CustomMessage":"Could not get account statistics: Horde_Imap_Client_Exception_ServerResponse: IMAP error reported by server.** in /var/www/chrooted/someOrganisationweb/htdocs/cloud.someOrganisation.org/apps/mail/vendor/pear-pear.horde.org/Horde_Imap_Client/Horde/Imap/Client/Socket.php:4602\nStack trace:\n#0 /var/www/chrooted/someOrganisationweb/htdocs/cloud.someOrganisation.org/apps/mail/vendor/pear-pear.horde.org/Horde_Imap_Client/Horde/Imap/Client/Socket.php(4314): Horde_Imap_Client_Socket->_getLine()\n#1 /var/www/chrooted/someOrganisationweb/htdocs/cloud.someOrganisation.org/apps/mail/vendor/pear-pear.horde.org/Horde_Imap_Client/Horde/Imap/Client/Socket.php(4242): Horde_Imap_Client_Socket->_sendCmdChunk()\n#2 /var/www/chrooted/someOrganisationweb/htdocs/cloud.someOrganisation.org/apps/mail/vendor/pear-pear.horde.org/Horde_Imap_Client/Horde/Imap/Client/Socket.php(1751): Horde_Imap_Client_Socket->_sendCmd()\n#3 /var/www/chrooted/someOrganisationweb/htdocs/cloud.someOrganisation.org/apps/mail/vendor/pear-pear.horde.org/Horde_Imap_Client/Horde/Imap/Client/Base.php(1733): Horde_Imap_Client_Socket->_status()\n#4 /var/www/chrooted/someOrganisationweb/htdocs/cloud.someOrganisation.org/apps/mail/lib/Command/DiagnoseAccount.php(136): Horde_Imap_Client_Base->status()\n#5 [internal function]: OCA\\Mail\\Command\\DiagnoseAccount->OCA\\Mail\\Command\\{closure}()\n#6 /var/www/chrooted/someOrganisationweb/htdocs/cloud.someOrganisation.org/apps/mail/lib/Command/DiagnoseAccount.php(138): array_reduce()\n#7 /var/www/chrooted/someOrganisationweb/htdocs/cloud.someOrganisation.org/apps/mail/lib/Command/DiagnoseAccount.php(90): OCA\\Mail\\Command\\DiagnoseAccount->printMailboxesMessagesStats()\n#8 /var/www/chrooted/someOrganisationweb/htdocs/cloud.someOrganisation.org/apps/mail/vendor/symfony/console/Command/Command.php(255): OCA\\Mail\\Command\\DiagnoseAccount->execute()\n#9 /var/www/chrooted/someOrganisationweb/htdocs/cloud.someOrganisation.org/apps/mail/vendor/symfony/console/Application.php(971): Symfony\\Component\\Console\\Command\\Command->run()\n#10 /var/www/chrooted/someOrganisationweb/htdocs/cloud.someOrganisation.org/apps/mail/vendor/symfony/console/Application.php(290): Symfony\\Component\\Console\\Application->doRunCommand()\n#11 /var/www/chrooted/someOrganisationweb/htdocs/cloud.someOrganisation.org/apps/mail/vendor/symfony/console/Application.php(166): Symfony\\Component\\Console\\Application->doRun()\n#12 /var/www/chrooted/someOrganisationweb/htdocs/cloud.someOrganisation.org/lib/private/Console/Application.php(215): Symfony\\Component\\Console\\Application->run()\n#13 /var/www/chrooted/someOrganisationweb/htdocs/cloud.someOrganisation.org/console.php(100): OC\\Console\\Application->run()\n#14 /var/www/chrooted/someOrganisationweb/htdocs/cloud.someOrganisation.org/occ(11): require_once('/var/www/chroot...')\n#15 {main}"},"userAgent":"--","version":"20.0.6.1"}
`

### Mail app

**Mail app version:** 1.8.0

**Mailserver or service:** Dovecot  2.3.7.2 / Postfix 3.4.13 on same server

### Server configuration

**Operating system**: Ubuntu 2.04

**Web server:** Nginx

**Database:** Mariadb

**PHP version:** 7.4

**Nextcloud Version:** 20.0.6

#### Client configuration
**Browser:** Firefox 84

**Operating system:** Debian GNU/Linux Bullseye

**Comment by ChristophWurst** [comment]
mailboxes that do not have the `sync_in_background` set to `true` will be skipped in the background sync. you can toggle this setting as a user from the mailbox' actions menu

**Comment by ChristophWurst** [comment]
so that means the background sync *does* have your mailboxes but the front-end doesn't show them?!

please confirm by inspecting oc_mail_mailboxes with the matching account_id of your account.

**Comment by vasyugan** [comment]
Right nown they have shown up. Maybe this was a temporary glitch.

**Comment by ChristophWurst** [comment]
FYI we cache mailboxes for 2h and only after that we get a new listing from IMAP. maybe that plays a role
