### ISSUE TITLE
Move emails to folders

### ISSUE THREAD

**Issue by prilly** [nextcloud/mail#443]
Not possible to move emails to folders

**Comment by ChristophWurst** [comment]
This feature was added by #90. You can now drag and drop email inside a single account.

**Comment by 1337sup3rh4x0r** [comment]
I see that it has long been merged and marked for the 0.6.1 milestone.

However I am on 0.6.4 and cannot drag and drop mails to another folder. If i try, it simply highlights the text in the mail, just like clicking, holding and dragging the cursor on any text on any website does.

**Comment by Egahras** [comment]
I got this issue, too.
I can't drag'n Drop, its just highlighting the Text.

I am on 0.6.4
I just found this [https://github.com/nextcloud/mail/issues/370](https://github.com/nextcloud/mail/issues/370), so we have to wait for 0.6.5!?

**Comment by ChristophWurst** [comment]
> I just found this #370, so we have to wait for 0.6.5!?

You do know that 0.7.3 is the latest version, right? 😉 🙈 

Please open new tickets if you have found any bug.
