### ISSUE TITLE
Send the wrong file as attachment

### ISSUE THREAD

**Issue by beccon4** [nextcloud/mail#4454]
### Expected behavior
When I attach a file from the Nextcloud file app to a mail and the file appears in the outgoing mail, then I expect that very file to arrive at the destination.

### Actual behavior
Another file gets attached and sent. (which could be embarrassing the best and downright dangerous in a business context) The sender cannot verify this as the correct file name and path appears in the mail, It is btw. always the same (pdf) file that gets attached.

### Mail app
**Mail app version:** (see apps admin page, e.g. 0.5.3)
- Mail App 1.8.0

**Mailserver or service:** (e.g. Outlook, Yahoo, Gmail, Exchange,...)
own Mailserver, qmail

### Server configuration
debian 8

**Operating system**: (e.g. Debian 8)

**Web server:** (e.g. Apache, Nginx,...)
Apache

**Database:** (e.g. MariaDB, SQLite or PostgreSQL)
MySQL

**PHP version:** (e.g. 7.0)
7.3

**Nextcloud Version:** (see admin page, e.g. 13.0.2)
20.0.6

#### Client configuration
**Browser:** (e.g. Firefox 48)
Firefox

**Operating system:** (e.g. Arch Linux)
Ubuntu 20.04

**Comment by bendilobi** [comment]
I can replicate this. It occurs only when attaching a file from Nextcoud files. Uploading an attachment from the desktop works fine. If I attach any file from Nextcloud files, no error message, everything looks fine but the receiver gets some other file that I attached to some other mail by uploading from the desktop several months ago. Regardless of the file chosen from Nextcould files, always the same "wrong" file is sent to the mail receiver. 

This is a serious issue. Please consider adding regression tests for this.

**Comment by ChristophWurst** [comment]
> This is a serious issue. Please consider adding regression tests for this.

Sounds good! This could be added to https://github.com/nextcloud/mail/tree/master/tests/Integration. Do you need help with a dev setup?

**Comment by ChristophWurst** [comment]
fixed in https://github.com/nextcloud/mail/pull/4447 btw

**Comment by ChristophWurst** [comment]
v1.8.1 is out: https://github.com/nextcloud/mail/releases/tag/v1.8.1

sorry for any inconveniences caused

if anyone would like to join the Mail testing team please let me know :v:

**Comment by bendilobi** [comment]
Thank you for fixing this so quickly :-) 

I know this sounds stale, but: at the moment, I absolutely don't have the time to help with testing. Might be interested in half a year or so...
