### ISSUE TITLE
Add a manual update/refresh button

### ISSUE THREAD

**Issue by ChristophWurst** [nextcloud/mail#4456]
### Feature Request

As a user I want to have an option force a refresh of the current mailbox.

#### Summary

Like the `r` shortcut, but via a button.

**Comment by GretaD** [comment]
@jancborchardt Sup? Can you please suggest where we can add this button, so i can start working on it?

**Comment by jancborchardt** [comment]
Yep, this requires the design change as specified at https://github.com/nextcloud/server/issues/16934#issuecomment-542201187 (for both Mail and Contacts ideally, in the component, while we are at it)

Then a refresh icon can be shown on the same row of the "New message" button, aligned to the right.

**Comment by ChristophWurst** [comment]
I raised my personal concerns with this design for Mail before because IMO there is semantic/logic to a *+ Add contact* button in Contacts where you actually add a new item to that very list but in Mail you don't. You don't add a message to that *list* (inbox).

Another issues is that we are already fighting to get more information displayed for priority inbox because there we have the three section titles that take up some vertical space and therefore fewer actual messages are shown. If we have that big button on top we'll hide at least one more message from the list.

So I'm not feeling very confident with this change.

Also looking at other sophisticated solutions I don't know any that has the *New message* button there, like neither Geary nor Gmail.

**Comment by ya-d** [comment]
Thank you for taking the time to consider and discuss these changes. I don't think either of this is an issue:
- Right now, the "+ New Message" button sits above the list of your mailboxes. Semantically it would even be an improvement to have it on top of your list of conversations (even though they are incoming).
- You have to place the hamburger icon somewhere which currently overlaps content. So the vertical space is already lost to that. There is also die "i" button which right now wildly floats around with content. (I don't think vertical space is the most urgent problem of the current design but rather [#16934](https://github.com/nextcloud/server/issues/16934#issuecomment-542201187) and #3940 / #4123.)
- It might be an option to move the create new / refresh buttons to the top right of the message view but that won't get rid of the hamburger icon.

Regarding the topic in this issue: **pull to refresh** is a rather common metaphor these days and might be an option .

Thank you so much for pushing Nextcloud forward. Keep it up!

<img width="279" alt="image" src="https://user-images.githubusercontent.com/30781876/107774761-ba3f2600-6d3f-11eb-951c-2220fa79f912.png">

**Comment by ChristophWurst** [comment]
> **pull to refresh** is a rather common metaphor these days and might be an option

We had this. Well, kind of. It was *scroll to refresh*, so when you scrolled up all the way it caused a refresh. But I personally never liked it because on desktop that it's not a common gesture at all and on mobile it never felt good because browsers are typically not as responsive as native apps.
