### ISSUE TITLE
Translation missing/error log lines after Mail enabled

### ISSUE THREAD

**Issue by simmarn** [nextcloud/mail#446]
### Steps to reproduce
1. Set Language to "Svenska" (Swedish) (Personal -> Personal Info -> Language)
2. Activate Mail app 

### Expected behaviour
No errors in Nextcloud log
In Mail app text on button "+ New Message" shall be translated to Swedish

### Actual behaviour
The following errors in Nextcloud log
```
Method OC_L10N_String::__toString() must return a string value at /var/www/nextcloud/lib/private/L10N/L10N.php#85
vsprintf(): Too few arguments at /var/www/nextcloud/lib/private/legacy/l10n/string.php#72
```

"+ New Message" button text is no translated
The rest of the app content is translated correctly.

Same problem as the following? [https://github.com/nextcloud/passman/issues/238](url)

### Mail app

**Mail app version:** (see apps admin page)
0.6.4

**Mailserver or service:** dovecot

**Transport security - IMAP:** None

**Transport security - SMTP:** None

**Number of accounts:** 1

### Server configuration

**Operating system**: Linux nextcloud 3.16.0-4-amd64 #1 SMP Debian 3.16.43-2+deb8u1 (2017-06-18) x86_64

**Web server:** Apache (apache2handler)

**Database:** mysql 10.1.24

**PHP version:** 5.6.30-0+deb8u1

**Version:** (see admin page)
12.0.2

**Updated from an older version or fresh install:**
Updated from 12.0.1

**Comment by ChristophWurst** [comment]
Hey @simmarn,

could you please re-try with a recent version of this app? Thanks!

**Comment by simmarn** [comment]
Hi Christoph,

I upgraded mail app to 0.7.3. Now it works. "New Message" button is translated and no errors in log.

Thanks!
/Martin

**Comment by ChristophWurst** [comment]
Great, thanks! :)
