### ISSUE TITLE
Argument 7 passed to OCA\Mail\Controller\MessagesController::__construct() must be of the type string, null given

### ISSUE THREAD

**Issue by timreeves** [nextcloud/mail#4462]
### Expected behavior
No error

### Actual behavior
```
TypeError: Argument 7 passed to OCA\Mail\Controller\MessagesController::__construct() must be of the type string, null given

<<closure>>

OCA\Mail\Controller\MessagesController->__construct()

/var/www/vhosts/sat-chit-ananda.org/owncloud.sat-chit-ananda.org/lib/private/AppFramework/Utility/SimpleContainer.php - line 101:

ReflectionClass->newInstanceArgs()

/var/www/vhosts/sat-chit-ananda.org/owncloud.sat-chit-ananda.org/lib/private/AppFramework/Utility/SimpleContainer.php - line 109:

OC\AppFramework\Utility\SimpleContainer->buildClass()

/var/www/vhosts/sat-chit-ananda.org/owncloud.sat-chit-ananda.org/lib/private/AppFramework/Utility/SimpleContainer.php - line 126:

OC\AppFramework\Utility\SimpleContainer->resolve()

/var/www/vhosts/sat-chit-ananda.org/owncloud.sat-chit-ananda.org/lib/private/AppFramework/DependencyInjection/DIContainer.php - line 455:

OC\AppFramework\Utility\SimpleContainer->query()

/var/www/vhosts/sat-chit-ananda.org/owncloud.sat-chit-ananda.org/lib/private/AppFramework/DependencyInjection/DIContainer.php - line 427:

OC\AppFramework\DependencyInjection\DIContainer->queryNoFallback()

/var/www/vhosts/sat-chit-ananda.org/owncloud.sat-chit-ananda.org/lib/private/AppFramework/App.php - line 139:

OC\AppFramework\DependencyInjection\DIContainer->query()

/var/www/vhosts/sat-chit-ananda.org/owncloud.sat-chit-ananda.org/lib/private/Route/Router.php - line 309:

OC\AppFramework\App::main()

/var/www/vhosts/sat-chit-ananda.org/owncloud.sat-chit-ananda.org/lib/base.php - line 1008:

OC\Route\Router->match()

/var/www/vhosts/sat-chit-ananda.org/owncloud.sat-chit-ananda.org/index.php - line 37:

OC::handleRequest()

```

### Mail app

**Mail app version:** 1.8.0

**Mailserver or service:** Self-Hosted (Plesk, Dovecot, Postfix)

### Server configuration

**Operating system**: Debian 10

**Web server:** Nginx

**Database:** MariaDB

**PHP version:** 7.4

**Nextcloud Version:** 20.0.6

#### Client configuration
**Browser:** (e.g. Firefox 48)

**Operating system:** (e.g. Arch Linux)

**Comment by ChristophWurst** [comment]
was that an unauthorized request maybe? see https://github.com/nextcloud/mail/issues/2917#issuecomment-614656730 for older reports of the same error

**Comment by timreeves** [comment]
It could be - I have a particular email account which 3 users could connect to successfully, but a fourth user could not, he can use IMAP but not send via SMTP. Really strange, as I checked the entered data several times, even removed the email account from the user account and reconnected it. But the server still seemed to know about its connection specifics - is anything being cached or not deleted, just marked as deleted?
Apart from that: Can't you check for a null parameter and handle the situation somehow gracefully?

**Comment by timreeves** [comment]
After lunch :)
Well maybe no users were active at lunch time, so I tried to send from the account mentioned above where sendning does not work. After that I see an expected error in the Nextcloud log, that sending failed - but not the "Argument 7 Null" message, so that seems to be a different problem. What I do see:
OCA\Mail\Exception\ServiceException: Could not send message: Server requires authentication.

    /var/www/vhosts/sat-chit-ananda.org/owncloud.sat-chit-ananda.org/apps/mail/lib/Controller/AccountsController.php - line 407:

    OCA\Mail\Service\MailTransmission->sendMessage()

    /var/www/vhosts/sat-chit-ananda.org/owncloud.sat-chit-ananda.org/lib/private/AppFramework/Http/Dispatcher.php - line 169:

    OCA\Mail\Controller\AccountsController->send()

    /var/www/vhosts/sat-chit-ananda.org/owncloud.sat-chit-ananda.org/lib/private/AppFramework/Http/Dispatcher.php - line 100:

    OC\AppFramework\Http\Dispatcher->executeController()

    /var/www/vhosts/sat-chit-ananda.org/owncloud.sat-chit-ananda.org/lib/private/AppFramework/App.php - line 152:

    OC\AppFramework\Http\Dispatcher->dispatch()

    /var/www/vhosts/sat-chit-ananda.org/owncloud.sat-chit-ananda.org/lib/private/Route/Router.php - line 309:

    OC\AppFramework\App::main()

    /var/www/vhosts/sat-chit-ananda.org/owncloud.sat-chit-ananda.org/lib/base.php - line 1008:

    OC\Route\Router->match()

    /var/www/vhosts/sat-chit-ananda.org/owncloud.sat-chit-ananda.org/index.php - line 37:

    OC::handleRequest()

Verursacht durchHorde_Mime_Exception: Server requires authentication.

    /var/www/vhosts/sat-chit-ananda.org/owncloud.sat-chit-ananda.org/apps/mail/vendor/pear-pear.horde.org/Horde_Mime/Horde/Mime/Mail.php - line 479:

    Horde_Mime_Part->send()

    /var/www/vhosts/sat-chit-ananda.org/owncloud.sat-chit-ananda.org/apps/mail/lib/Service/MailTransmission.php - line 186:

    Horde_Mime_Mail->send()

    /var/www/vhosts/sat-chit-ananda.org/owncloud.sat-chit-ananda.org/apps/mail/lib/Controller/AccountsController.php - line 407:

    OCA\Mail\Service\MailTransmission->sendMessage()

    /var/www/vhosts/sat-chit-ananda.org/owncloud.sat-chit-ananda.org/lib/private/AppFramework/Http/Dispatcher.php - line 169:

    OCA\Mail\Controller\AccountsController->send()

    /var/www/vhosts/sat-chit-ananda.org/owncloud.sat-chit-ananda.org/lib/private/AppFramework/Http/Dispatcher.php - line 100:

    OC\AppFramework\Http\Dispatcher->executeController()

    /var/www/vhosts/sat-chit-ananda.org/owncloud.sat-chit-ananda.org/lib/private/AppFramework/App.php - line 152:

    OC\AppFramework\Http\Dispatcher->dispatch()

    /var/www/vhosts/sat-chit-ananda.org/owncloud.sat-chit-ananda.org/lib/private/Route/Router.php - line 309:

    OC\AppFramework\App::main()

    /var/www/vhosts/sat-chit-ananda.org/owncloud.sat-chit-ananda.org/lib/base.php - line 1008:

    OC\Route\Router->match()

    /var/www/vhosts/sat-chit-ananda.org/owncloud.sat-chit-ananda.org/index.php - line 37:

    OC::handleRequest()

Verursacht durchHorde_Mail_Exception: Server requires authentication.

    /var/www/vhosts/sat-chit-ananda.org/owncloud.sat-chit-ananda.org/apps/mail/vendor/pear-pear.horde.org/Horde_Mime/Horde/Mime/Part.php - line 1620:

    Horde_Mail_Transport_Smtphorde->send()

    /var/www/vhosts/sat-chit-ananda.org/owncloud.sat-chit-ananda.org/apps/mail/vendor/pear-pear.horde.org/Horde_Mime/Horde/Mime/Mail.php - line 479:

    Horde_Mime_Part->send()

    /var/www/vhosts/sat-chit-ananda.org/owncloud.sat-chit-ananda.org/apps/mail/lib/Service/MailTransmission.php - line 186:

    Horde_Mime_Mail->send()

    /var/www/vhosts/sat-chit-ananda.org/owncloud.sat-chit-ananda.org/apps/mail/lib/Controller/AccountsController.php - line 407:

    OCA\Mail\Service\MailTransmission->sendMessage()

    /var/www/vhosts/sat-chit-ananda.org/owncloud.sat-chit-ananda.org/lib/private/AppFramework/Http/Dispatcher.php - line 169:

    OCA\Mail\Controller\AccountsController->send()

    /var/www/vhosts/sat-chit-ananda.org/owncloud.sat-chit-ananda.org/lib/private/AppFramework/Http/Dispatcher.php - line 100:

    OC\AppFramework\Http\Dispatcher->executeController()

    /var/www/vhosts/sat-chit-ananda.org/owncloud.sat-chit-ananda.org/lib/private/AppFramework/App.php - line 152:

    OC\AppFramework\Http\Dispatcher->dispatch()

    /var/www/vhosts/sat-chit-ananda.org/owncloud.sat-chit-ananda.org/lib/private/Route/Router.php - line 309:

    OC\AppFramework\App::main()

    /var/www/vhosts/sat-chit-ananda.org/owncloud.sat-chit-ananda.org/lib/base.php - line 1008:

    OC\Route\Router->match()

    /var/www/vhosts/sat-chit-ananda.org/owncloud.sat-chit-ananda.org/index.php - line 37:

    OC::handleRequest()

Verursacht durchHorde_Smtp_Exception: Server requires authentication.

    /var/www/vhosts/sat-chit-ananda.org/owncloud.sat-chit-ananda.org/apps/mail/vendor/pear-pear.horde.org/Horde_Smtp/Horde/Smtp.php - line 755:

    Horde_Smtp->_getResponse()

    /var/www/vhosts/sat-chit-ananda.org/owncloud.sat-chit-ananda.org/apps/mail/vendor/pear-pear.horde.org/Horde_Smtp/Horde/Smtp.php - line 666:

    Horde_Smtp->resetCmd()

    /var/www/vhosts/sat-chit-ananda.org/owncloud.sat-chit-ananda.org/apps/mail/vendor/pear-pear.horde.org/Horde_Mail/Horde/Mail/Transport/Smtphorde.php - line 143:

    Horde_Smtp->send()

    /var/www/vhosts/sat-chit-ananda.org/owncloud.sat-chit-ananda.org/apps/mail/vendor/pear-pear.horde.org/Horde_Mime/Horde/Mime/Part.php - line 1620:

    Horde_Mail_Transport_Smtphorde->send()

    /var/www/vhosts/sat-chit-ananda.org/owncloud.sat-chit-ananda.org/apps/mail/vendor/pear-pear.horde.org/Horde_Mime/Horde/Mime/Mail.php - line 479:

    Horde_Mime_Part->send()

    /var/www/vhosts/sat-chit-ananda.org/owncloud.sat-chit-ananda.org/apps/mail/lib/Service/MailTransmission.php - line 186:

    Horde_Mime_Mail->send()

    /var/www/vhosts/sat-chit-ananda.org/owncloud.sat-chit-ananda.org/apps/mail/lib/Controller/AccountsController.php - line 407:

    OCA\Mail\Service\MailTransmission->sendMessage()

    /var/www/vhosts/sat-chit-ananda.org/owncloud.sat-chit-ananda.org/lib/private/AppFramework/Http/Dispatcher.php - line 169:

    OCA\Mail\Controller\AccountsController->send()

    /var/www/vhosts/sat-chit-ananda.org/owncloud.sat-chit-ananda.org/lib/private/AppFramework/Http/Dispatcher.php - line 100:

    OC\AppFramework\Http\Dispatcher->executeController()

    /var/www/vhosts/sat-chit-ananda.org/owncloud.sat-chit-ananda.org/lib/private/AppFramework/App.php - line 152:

    OC\AppFramework\Http\Dispatcher->dispatch()

    /var/www/vhosts/sat-chit-ananda.org/owncloud.sat-chit-ananda.org/lib/private/Route/Router.php - line 309:

    OC\AppFramework\App::main()

    /var/www/vhosts/sat-chit-ananda.org/owncloud.sat-chit-ananda.org/lib/base.php - line 1008:

    OC\Route\Router->match()

    /var/www/vhosts/sat-chit-ananda.org/owncloud.sat-chit-ananda.org/index.php - line 37:

    OC::handleRequest()

**Comment by timreeves** [comment]
To be a bit more precise: The email account where SMTP is failing is on the local server. But that applies to the 3 other users who have no problem sending... I'm at a complete loss. Sadly, the one account where sending does not work is that of my direct client - the boss, so to speak )-: If I remove the email account, can I check in any DB tables if anything of its data have remained?
