### ISSUE TITLE
MSTeams meatings request attachement are not shown

### ISSUE THREAD

**Issue by chrisaga** [nextcloud/mail#4463]
### Expected behavior
When a mail is meeting request issued by Microsoft Teams, the request should be visible as an attachment so we could add it in our calendar.

### Actual behavior
The HTML text of the meeting request is visible as the mail body with no attachment.

The mail itself is a multipart MIME with 2 base64 encoded parts : 

* Message in text format (ignored by Mail app)
```
Content-Type: text/plain; charset="utf-8"
Content-Transfer-Encoding: base64
```
* Same message in HTML format (the one Mail app displays)
```
Content-Type: text/html; charset="utf-8"
Content-Transfer-Encoding: base64
```
* The calendar invitation which should be processed as an attachement (ignored by Mail app)
```
Content-Type: text/calendar; charset="utf-8"; method=REQUEST
Content-Transfer-Encoding: base64
```

### Mail app

**Mail app version:** 1.8.1

**Mailserver or service:** MS Teams (+ MS Exchange ?)

### Server configuration

**Operating system**: Debian 9

**Web server:** Apache

**Database:** MariaDB

**PHP version:** 7.3

**Nextcloud Version:** 20.0.7

#### Client configuration
**Browser:** Firefox 85

**Operating system:** Ubuntu

**Comment by ChristophWurst** [comment]
Works with Nextcloud Talk :wink: 

If you share the original message as .eml or similar we can try to import and debug

**Comment by chrisaga** [comment]
> Works with Nextcloud Talk wink
> 
> If you share the original message as .eml or similar we can try to import and debug
Here is a copy of the source of the message.
Hope it can help
[teams.zip](https://github.com/nextcloud/mail/files/5920843/teams.zip)

**Comment by ChristophWurst** [comment]
Thanks. We'll try to have a look when time allows.

**Comment by ChristophWurst** [comment]
For some reason Horde is not able to read the part as attachment file filename in `\OCA\Mail\Model\IMAPMessage::getPart`. The $filename is always `null`.

**Comment by chrisaga** [comment]
Could it be me storing the message in the zip file ?
Would you like me to send you a Teams meeting request ?

BTW. I managed to filter and decode manually the message with sed and base64 to create an .ics file and import it in nextcloud calendar app.

**Comment by ChristophWurst** [comment]
no, it's fine. I think the format that microsoft uses is somewhat special and therefore needs special handling.

**Comment by StCyr** [comment]
Well, I can see the following in `\OCA\Mail\Model\IMAPMessage::getPart`

		// TEXT
		if ($p->getType() === 'text/calendar') {
			// TODO: skip inline ics for now
			return;
		}

https://github.com/nextcloud/mail/blob/e685a541957d333aadee0a6a87e22012ae98f01c/lib/Model/IMAPMessage.php#L427

Doesn't it explain this issue?

**Comment by prismopensource** [comment]
Same issue here, would be a very nice if this could work in the year of 2021.

**Comment by ChristophWurst** [comment]
Yeah it's time someone finally fixes this.

**Comment by StCyr** [comment]
Hello,

If possible, please test https://github.com/nextcloud/mail/pull/5080
