### ISSUE TITLE
Wrong attachement when inserting multiple files from Nextcloud Files

### ISSUE THREAD

**Issue by chrisaga** [nextcloud/mail#4464]
### Expected behavior
1) Create a new mail
2) Attach 2 files from Files (files are already on NC server, not uploaded, attached to the mail, not NC links)
3) Send mail
4) Recipient receives mail with 2 attachments

### Actual behavior
Mail app wrongly attach twice the same file (which can be verified displaying the source of the sent mail).
Recipient receives only 1 attachment (duplicate seems to be filtered somewhere).

### Mail app

**Mail app version:** 1.8.1

**Mailserver or service:** Not relevent

### Server configuration

**Operating system**: Debian 9

**Web server:** Apache

**Database:** MariaDB

**PHP version:** 7.3

**Nextcloud Version:** 20.0.7

#### Client configuration
**Browser:** Firefox 85

**Operating system:** Ubuntu

**Comment by ChristophWurst** [comment]
> **Mail app version:** 1.8.1

https://github.com/nextcloud/mail/pull/4407 is supposed to fix this

**Comment by ChristophWurst** [comment]
I still can't reproduce this

 I found a regression with local uploads and an issue with the webdav library on latest master. but v1.8.1 should work as expected … am I missing somehting?

**Comment by davidpr78** [comment]
I couldn't reproduce this, too. It works now with v1.8.1

**Comment by st3iny** [comment]
Just tested with multiple combinations of files and I can't reproduce this bug on v1.8.1.

**Comment by ChristophWurst** [comment]
Thanks for checking :pray: 

I can sleep well again

**Comment by ChristophWurst** [comment]
> I'll pay attention in the next few days and if nothing happens I'll close the issue. Sorry for the inconvenience.

No worries, I appreciate the time you took to report this!

**Comment by StCyr** [comment]
At least, it made us discover another bug 😄

**Comment by chrisaga** [comment]
Hello ! The issue didn't happen since then, so I guess I can close it.
Thanks to have looked into it and sorry for the false alarm. I definitively had several issues with attachments that day and I'll never know why.

**Comment by ChristophWurst** [comment]
thanks for the info @chrisaga. seeing a notification for this ticket just before the weekend gave me a little heart attack tho :wink:
