### ISSUE TITLE
unable to connect to live.com account

### ISSUE THREAD

**Issue by Goddard** [nextcloud/mail#447]
imap-mail.outlook.com
smtp-mail.outlook.com

using connection details from live.com which can't be shown, but they are the same as on this page.
https://www.firetrust.com/products/mailwasher-pro/support/Hotmail_Outlook_POP3_IMAP_SMTP_Settings

Any help appreciated.

Thanks

**Comment by ChristophWurst** [comment]
Hi,

may I ask you to fill out the issue template as asked when you created this ticket? Would be interesting to see where the app fails to connect (error message, server log, imap log and smtp log).

**Comment by ChristophWurst** [comment]
Closing due to lack of feedback.
