### ISSUE TITLE
Not compatble with Nexcloud 20.0.7

### ISSUE THREAD

**Issue by poltrian** [nextcloud/mail#4471]
i would like update from 20.0.6 to 20.0.7. But the upater shows. These apps are not compatible, Mail, Music, TOTP.

Whats going wrong?

**Comment by ChristophWurst** [comment]
> Whats going wrong?

Mistakes were made and 20.0.6 contain faulty compatibility check. You can update, at least Mail and TOTP will be there.

**Comment by poltrian** [comment]
Could be a problem in 20.0.6. I can confirm, update to 20.0.7 without any problems
