### ISSUE TITLE
Sending mails to groups fails

### ISSUE THREAD

**Issue by erichrueger** [nextcloud/mail#4476]
### Expected behavior
When I choose a group as recipient for a mail and send it, the mail is being sent to every member of that group.

### Actual behavior
The mail app returns: Error: Request failed with status code 500

### Mail app

**Mail app version:** 1.8.1

**Mailserver or service:** All-Inkl

### Server configuration

**Operating system**: Ubuntu 18.04

**Web server:** Nginx

**Database:** MariaDB

**PHP version:** 7.4.14 (cli)

**Nextcloud Version:** 20.0.5

#### Client configuration
**Browser:** Chrome 88

**Operating system:** (e.g. Arch Linux)

**Comment by ChristophWurst** [comment]
anything in your nextcloud.log?

**Comment by erichrueger** [comment]
Hello,

there is nothing in the logs I can work with.
Here are two lines in connection to the mail-app. (I just removed the mail
address.)


{"reqId":"qwEwlcRGmFQs8m9ShFVj","level":3,"time":"2021-02-04T21:42:57+00:00","remoteAddr":"172.180.0.1","user":"
mail@example.com","app":"mail","method":"POST","url":"/apps/mail/api/accounts/1027/send","message":"Sending
mail failed: Could not send message: Mailbox
unavailable.","userAgent":"Mozilla/5.0 (Macintosh; Intel Mac OS X 11_1_0)
AppleWebKit/537.36 (KHTML, like Gecko) Chrome/88.0.4324.96
Safari/537.36","version":"20.0.5.2"}

{"reqId":"PW0I7krm4QwGtvnPYuua","level":3,"time":"2021-02-04T21:44:01+00:00","remoteAddr":"172.180.0.1","user":"
mail@example.com","app":"mail","method":"POST","url":"/apps/mail/api/accounts/721/draft","message":{"Exception":"Exception","Message":"Argument
1 passed to OCA\\Mail\\Address::fromRaw() must be of the type string, null
given, called in /var/www/html/apps/mail/lib/Service/MailTransmission.php
on line
221","Code":0,"Trace":[{"file":"/var/www/html/lib/private/AppFramework/App.php","line":152,"function":"dispatch","class":"OC\\AppFramework\\Http\\Dispatcher","type":"->"},{"file":"/var/www/html/lib/private/Route/Router.php","line":309,"function":"main","class":"OC\\AppFramework\\App","type":"::"},{"file":"/var/www/html/lib/base.php","line":1008,"function":"match","class":"OC\\Route\\Router","type":"->"},{"file":"/var/www/html/index.php","line":37,"function":"handleRequest","class":"OC","type":"::"}],"File":"/var/www/html/lib/private/AppFramework/Http/Dispatcher.php","Line":110,"Previous":{"Exception":"TypeError","Message":"Argument
1 passed to OCA\\Mail\\Address::fromRaw() must be of the type string, null
given, called in /var/www/html/apps/mail/lib/Service/MailTransmission.php
on line
221","Code":0,"Trace":[{"file":"/var/www/html/apps/mail/lib/Service/MailTransmission.php","line":221,"function":"fromRaw","class":"OCA\\Mail\\Address","type":"::"},{"file":"/var/www/html/apps/mail/lib/Controller/AccountsController.php","line":458,"function":"saveDraft","class":"OCA\\Mail\\Service\\MailTransmission","type":"->"},{"file":"/var/www/html/lib/private/AppFramework/Http/Dispatcher.php","line":169,"function":"draft","class":"OCA\\Mail\\Controller\\AccountsController","type":"->"},{"file":"/var/www/html/lib/private/AppFramework/Http/Dispatcher.php","line":100,"function":"executeController","class":"OC\\AppFramework\\Http\\Dispatcher","type":"->"},{"file":"/var/www/html/lib/private/AppFramework/App.php","line":152,"function":"dispatch","class":"OC\\AppFramework\\Http\\Dispatcher","type":"->"},{"file":"/var/www/html/lib/private/Route/Router.php","line":309,"function":"main","class":"OC\\AppFramework\\App","type":"::"},{"file":"/var/www/html/lib/base.php","line":1008,"function":"match","class":"OC\\Route\\Router","type":"->"},{"file":"/var/www/html/index.php","line":37,"function":"handleRequest","class":"OC","type":"::"}],"File":"/var/www/html/apps/mail/lib/Address.php","Line":52},"CustomMessage":"Argument
1 passed to OCA\\Mail\\Address::fromRaw() must be of the type string, null
given, called in /var/www/html/apps/mail/lib/Service/MailTransmission.php
on line 221"},"userAgent":"Mozilla/5.0 (Macintosh; Intel Mac OS X 11_1_0)
AppleWebKit/537.36 (KHTML, like Gecko) Chrome/88.0.4324.96
Safari/537.36","version":"20.0.5.2"}

Sending mails to individual users works by the way.
Thank you for time and help!
Best regards.

Erich Rüger

Am Fr., 5. Feb. 2021 um 08:23 Uhr schrieb Christoph Wurst <
notifications@github.com>:

**Comment by erichrueger** [comment]
Hello,

there is nothing in the logs I can work with.
Here are two lines in connection to the mail-app. (I just removed the mail
address.)


{"reqId":"qwEwlcRGmFQs8m9ShFVj","level":3,"time":"2021-02-04T21:42:57+00:00","remoteAddr":"172.180.0.1","user":"
mail@example.com","app":"mail","method":"POST","url":"/apps/mail/api/accounts/1027/send","message":"Sending
mail failed: Could not send message: Mailbox
unavailable.","userAgent":"Mozilla/5.0 (Macintosh; Intel Mac OS X 11_1_0)
AppleWebKit/537.36 (KHTML, like Gecko) Chrome/88.0.4324.96
Safari/537.36","version":"20.0.5.2"}

{"reqId":"PW0I7krm4QwGtvnPYuua","level":3,"time":"2021-02-04T21:44:01+00:00","remoteAddr":"172.180.0.1","user":"
mail@example.com","app":"mail","method":"POST","url":"/apps/mail/api/accounts/721/draft","message":{"Exception":"Exception","Message":"Argument
1 passed to OCA\\Mail\\Address::fromRaw() must be of the type string, null
given, called in /var/www/html/apps/mail/lib/Service/MailTransmission.php
on line
221","Code":0,"Trace":[{"file":"/var/www/html/lib/private/AppFramework/App.php","line":152,"function":"dispatch","class":"OC\\AppFramework\\Http\\Dispatcher","type":"->"},{"file":"/var/www/html/lib/private/Route/Router.php","line":309,"function":"main","class":"OC\\AppFramework\\App","type":"::"},{"file":"/var/www/html/lib/base.php","line":1008,"function":"match","class":"OC\\Route\\Router","type":"->"},{"file":"/var/www/html/index.php","line":37,"function":"handleRequest","class":"OC","type":"::"}],"File":"/var/www/html/lib/private/AppFramework/Http/Dispatcher.php","Line":110,"Previous":{"Exception":"TypeError","Message":"Argument
1 passed to OCA\\Mail\\Address::fromRaw() must be of the type string, null
given, called in /var/www/html/apps/mail/lib/Service/MailTransmission.php
on line
221","Code":0,"Trace":[{"file":"/var/www/html/apps/mail/lib/Service/MailTransmission.php","line":221,"function":"fromRaw","class":"OCA\\Mail\\Address","type":"::"},{"file":"/var/www/html/apps/mail/lib/Controller/AccountsController.php","line":458,"function":"saveDraft","class":"OCA\\Mail\\Service\\MailTransmission","type":"->"},{"file":"/var/www/html/lib/private/AppFramework/Http/Dispatcher.php","line":169,"function":"draft","class":"OCA\\Mail\\Controller\\AccountsController","type":"->"},{"file":"/var/www/html/lib/private/AppFramework/Http/Dispatcher.php","line":100,"function":"executeController","class":"OC\\AppFramework\\Http\\Dispatcher","type":"->"},{"file":"/var/www/html/lib/private/AppFramework/App.php","line":152,"function":"dispatch","class":"OC\\AppFramework\\Http\\Dispatcher","type":"->"},{"file":"/var/www/html/lib/private/Route/Router.php","line":309,"function":"main","class":"OC\\AppFramework\\App","type":"::"},{"file":"/var/www/html/lib/base.php","line":1008,"function":"match","class":"OC\\Route\\Router","type":"->"},{"file":"/var/www/html/index.php","line":37,"function":"handleRequest","class":"OC","type":"::"}],"File":"/var/www/html/apps/mail/lib/Address.php","Line":52},"CustomMessage":"Argument
1 passed to OCA\\Mail\\Address::fromRaw() must be of the type string, null
given, called in /var/www/html/apps/mail/lib/Service/MailTransmission.php
on line 221"},"userAgent":"Mozilla/5.0 (Macintosh; Intel Mac OS X 11_1_0)
AppleWebKit/537.36 (KHTML, like Gecko) Chrome/88.0.4324.96
Safari/537.36","version":"20.0.5.2"}

Sending mails to individual users works by the way.
Thank you for time and help!

**Comment by ChristophWurst** [comment]
> Argument
> 1 passed to OCA\Mail\Address::fromRaw() must be of the type string, null
> given

does your Mail account have an email set? check `oc_mail_accounts.email`.

**Comment by erichrueger** [comment]
> > Argument
> > 1 passed to OCA\Mail\Address::fromRaw() must be of the type string, null
> > given
> 
> does your Mail account have an email set? check `oc_mail_accounts.email`.

Thank you for your help. I could resolve the issue. It was related to the database.  For some reason there were users without mail accounts in oc_mail_accounts.email. Removing them was part of the solution. After that a new error emerged. Looking at horde_smtp.log we figured out that nextcloud did not remove all deleted users from oc_group_user. The mailserver denied sending any mails to groups, as long as there were inactive mail-adresses involved. Cleaning up in oc_group_user made sending mails to groups possible again.
