### ISSUE TITLE
Changing the default colour for links

### ISSUE THREAD

**Issue by GretaD** [nextcloud/mail#4478]
We use the CK default blue for links. On dark theme, the links are unreadable. I propose to be changed into #07d the default that some other clients use like google.

### Expected behavior
![link_blue](https://user-images.githubusercontent.com/12728974/107029054-b5fa9200-67ae-11eb-95c3-8f6cafd4357e.png)

### Actual behavior

![link_badblue](https://user-images.githubusercontent.com/12728974/107028952-89df1100-67ae-11eb-96b2-9df6cf07fdf9.png)

@jancborchardt what do you think?

**Comment by jancborchardt** [comment]
> I propose to be changed into #07d the default that some other clients use like google.

Great suggestion @GretaD, let’s do that! :)
