### ISSUE TITLE
Could not send message: Server requires authentication.

### ISSUE THREAD

**Issue by timreeves** [nextcloud/mail#4480]
### Expected behavior
New message (Email) should be sent, SMTP data is provided and correct. This is, admittedly, a special case: I do not manage the server where the mail account is, and sadly, Postfix is not configured to accept encoded passwords. Furthermore, there is a '#' character (i.e. possibly interpreted as comment somewhere) in the password. Even so, it would be nice if it would work reliably.

### Actual behavior
Could not send message: Server requires authentication. This is in the error log:

`Error	mail	OCA\Mail\Exception\ServiceException: Could not send message: Server requires authentication.

    /var/www/vhosts/sat-chit-ananda.org/owncloud.sat-chit-ananda.org/apps/mail/lib/Controller/AccountsController.php - line 407:

    OCA\Mail\Service\MailTransmission->sendMessage()

    /var/www/vhosts/sat-chit-ananda.org/owncloud.sat-chit-ananda.org/lib/private/AppFramework/Http/Dispatcher.php - line 169:

    OCA\Mail\Controller\AccountsController->send()

    /var/www/vhosts/sat-chit-ananda.org/owncloud.sat-chit-ananda.org/lib/private/AppFramework/Http/Dispatcher.php - line 100:

    OC\AppFramework\Http\Dispatcher->executeController()

    /var/www/vhosts/sat-chit-ananda.org/owncloud.sat-chit-ananda.org/lib/private/AppFramework/App.php - line 152:

    OC\AppFramework\Http\Dispatcher->dispatch()

    /var/www/vhosts/sat-chit-ananda.org/owncloud.sat-chit-ananda.org/lib/private/Route/Router.php - line 309:

    OC\AppFramework\App::main()

    /var/www/vhosts/sat-chit-ananda.org/owncloud.sat-chit-ananda.org/lib/base.php - line 1008:

    OC\Route\Router->match()

    /var/www/vhosts/sat-chit-ananda.org/owncloud.sat-chit-ananda.org/index.php - line 37:

    OC::handleRequest()

Verursacht durchHorde_Mime_Exception: Server requires authentication.

    /var/www/vhosts/sat-chit-ananda.org/owncloud.sat-chit-ananda.org/apps/mail/vendor/pear-pear.horde.org/Horde_Mime/Horde/Mime/Mail.php - line 479:

    Horde_Mime_Part->send()

    /var/www/vhosts/sat-chit-ananda.org/owncloud.sat-chit-ananda.org/apps/mail/lib/Service/MailTransmission.php - line 186:

    Horde_Mime_Mail->send()

    /var/www/vhosts/sat-chit-ananda.org/owncloud.sat-chit-ananda.org/apps/mail/lib/Controller/AccountsController.php - line 407:

    OCA\Mail\Service\MailTransmission->sendMessage()

    /var/www/vhosts/sat-chit-ananda.org/owncloud.sat-chit-ananda.org/lib/private/AppFramework/Http/Dispatcher.php - line 169:

    OCA\Mail\Controller\AccountsController->send()

    /var/www/vhosts/sat-chit-ananda.org/owncloud.sat-chit-ananda.org/lib/private/AppFramework/Http/Dispatcher.php - line 100:

    OC\AppFramework\Http\Dispatcher->executeController()

    /var/www/vhosts/sat-chit-ananda.org/owncloud.sat-chit-ananda.org/lib/private/AppFramework/App.php - line 152:

    OC\AppFramework\Http\Dispatcher->dispatch()

    /var/www/vhosts/sat-chit-ananda.org/owncloud.sat-chit-ananda.org/lib/private/Route/Router.php - line 309:

    OC\AppFramework\App::main()

    /var/www/vhosts/sat-chit-ananda.org/owncloud.sat-chit-ananda.org/lib/base.php - line 1008:

    OC\Route\Router->match()

    /var/www/vhosts/sat-chit-ananda.org/owncloud.sat-chit-ananda.org/index.php - line 37:

    OC::handleRequest()`

### Mail app

**Mail app version:** 1.8.1

**Mailserver or service:** Selfhosted, on Debian 9, Postfix, not optimally configured

### Server configuration (Nextcloud Server, not SMTP server)

**Operating system**: Debian 10

**Web server:** Nginx

**Database:** MariaDB 10.3

**PHP version:** 7.4

**Nextcloud Version:** 20.0.7

**Comment by kesselb** [comment]
> Server requires authentication

I don't see a mail issue here. Your server responds with 530 to our requests. Most likely the configuration is wrong.

**Comment by ChristophWurst** [comment]
in doubt you can also enable debug mode and inspect the SMTP communication
