### ISSUE TITLE
Need ability to copy recipient email address to clipboard

### ISSUE THREAD

**Issue by timreeves** [nextcloud/mail#4481]
### Feature Request

When you put the focus on a specific mail, the participant addresses of the email thread appear in the large right field at the top, just below the subject. By mouse-over the plain text name you can see the address visually, but you can't copy it to the clipboard. There is a (very inconvenient) detour: In the subject field of every single email there are the iconic three dots on the far right, behind them a context menu, one menu item of which is "View source". In a popup the whole source of the email is displayed, i.e. the whole SMTP headers and further down the body of the email. In the headers - From, CC, BCC ... - are the email addresses and can be marked and copied. As stated inconvenient, not possible to tell normal users to do that.

#### Summary

I won't assume to know this interface better than the authors. And I really don't mind exactly how it's done, the main thing, there is an easy way for the user to get the email address into the clipboard, a way in direct association with the boxed recipient name which he's looking at. Currently I'm saying "bring the mouse over, then write the address on a piece of paper"...

### While we're here

Two further observations on the UI:

1. After successfully sending an Email, the button "New message" at top left is inactive. One must click on the button "Compose another message" (or similar text) in the main area. I did not notice that button, and would not have expected it there. Please make the "usual" button work as well.

2. When selecting / typing a new email address (while composing a new message) the dropdown entry of that name has a tick at its left. A click on the name does not change the tick (hover effect). To know if the address is selected or not? Currently I can only see whether the "Send" button is active or not - assuming only 1 recipient... Please find a unique way of indicating that an address is selected, rather than re-using the hover effect.

At this point: Yes I sure do understand how much "heart blood" goes into an App like Mail, and we are all really really grateful for it - don't want to come across niggly here. It's just that I'm getting some flak from users, and I sadly have to agree with them that some features are not yet "round".

**Comment by StCyr** [comment]
Hello @ChristophWurst 

I would like to implement this feature (copy email address to clipboard). Any recommandations?

I was thinking about using the clipboardy package (https://www.npmjs.com/package/clipboardy) for this purpose.

**Comment by miaulalala** [comment]
@StCyr there's aready some copy/paste options in Nextcloud. Calendar has it in the left bottom Settings menu for example (`$copyText`).

Maybe @st3iny can weight in as well.

**Comment by StCyr** [comment]
Ha, apparently they use vue-clipboard2 (https://www.npmjs.com/package/vue-clipboard2) in calendar
