### ISSUE TITLE
Cannot update to 1.8.1

### ISSUE THREAD

**Issue by StCyr** [nextcloud/mail#4482]
### Expected behavior
Mail 1.8.1 has been released a few days ago and I should be offered the update

### Actual behavior
No update is proposed on my index.php/settings/apps page

Running occ app:update mail doesn't seem to do anything. Though Memcache related messages appears in the log:

`[[Feb  5 15:37:14 vps612142 Nextcloud[1469]: {"reqId":"7UzPOCI6lmnj1Uu6lZ2e","level":1,"time":"2021-02-05T14:37:14+00:00","remoteAddr":"","user":"--","app":"cli","method":"","url":"--","message":"Memcache \\OC\\Memcache\\APCu not available for local cache","userAgent":"--","version":"20.0.6.1"}´`
`Feb  5 15:37:14 vps612142 Nextcloud[1469]:{"reqId":"7UzPOCI6lmnj1Uu6lZ2e","level":1,"time":"2021-02-05T14:37:14+00:00","remoteAddr":"","user":"--","app":"cli","method":"","url":"--","message":"Memcache \\OC\\Memcache\\APCu not available for distributed cache","userAgent":"--","version":"20.0.6.1"}`

### Mail app

**Mail app version:** 1.8.0

### Server configuration

**Operating system**: Debian buster

**Web server:** Apache

**Database:** MariaDB

**PHP version:** (e.g. 7.0)

**Nextcloud Version:** 20.0.6

**Comment by ChristophWurst** [comment]
20.0.6 is buggy, you need 20.0.7
