### ISSUE TITLE
make build-js won't work

### ISSUE THREAD

**Issue by StCyr** [nextcloud/mail#4485]
### Expected behavior
make build-js compiles properly

### Actual behavior
Lot of such errors:

`
ERROR in ./node_modules/@nextcloud/dialogs/styles/toast.scss (./node_modules/css-loader/dist/cjs.js!./node_modules/sass-loader/dist/cjs.js!./node_modules/@nextcloud/dialogs/styles/toast.scss)
Module Error (from ./node_modules/sass-loader/dist/cjs.js):
ENOENT: no such file or directory, scandir '/var/www/nextcloud/apps/mail/node_modules/node-sass/vendor'
`

and 

`ERROR in ./src/components/MailboxThread.vue?vue&type=style&index=0&id=350610de&lang=scss&scoped=true& (./node_modules/css-loader/dist/cjs.js!./node_modules/vue-loader/lib/loaders/stylePostLoader.js!./node_modules/sass-loader/dist/cjs.js!./node_modules/vue-loader/lib??vue-loader-options!./src/components/MailboxThread.vue?vue&type=style&index=0&id=350610de&lang=scss&scoped=true&)
Module build failed (from ./node_modules/vue-loader/lib/loaders/stylePostLoader.js):
Error: PostCSS received undefined instead of CSS string
`
### Mail app

**Mail app version:** master (1.8.1)

**Comment by StCyr** [comment]
Damned, this fixes the issues:

```
cyrille@vm-cyrille-debian:/var/www/nextcloud/apps/mail$ git diff package.json
diff --git a/package.json b/package.json
index 48a83e6a3..c3728c91c 100644
--- a/package.json
+++ b/package.json
@@ -104,6 +104,7 @@
     "mocha": "^8.2.1",
     "mochapack": "^2.0.6",
     "node-sass": "^5.0.0",
+    "sass": "^1.32.6",
     "sass-loader": "^10.1.1",
     "sinon": "^9.2.4",
     "sinon-chai": "^3.4.0",
```

**Comment by ChristophWurst** [comment]
oh I think I had that in one of my side projects as well. good find! Mind sending a PR? :)
