### ISSUE TITLE
Can't connect. 

### ISSUE THREAD

**Issue by srednax** [nextcloud/mail#4504]
I can't connect to my imap account, nextcloud mail says an error happened, the log says:
Creating account failed: Could not connect to IMAP host mail.alweb.dk:143: Could not open secure TLS connection to the IMAP server.

I can connect using kmail, the service webmail, the various mail apps on my phone, thunderbird, you name it.
In kmail settings, I can see that authentification is set to "cleartext", but nextcloud mail does not offer that setting - that may be the problem?

**Comment by kesselb** [comment]
Thank you for taking the time to report a problem :+1: 

As this seems to be a setup issue I would like to ask you to raise your question at https://help.nextcloud.com the next time.


```
$ openssl s_client -connect mail.alweb.dk:143 -starttls imap
CONNECTED(00000003)
depth=2 O = Digital Signature Trust Co., CN = DST Root CA X3
verify return:1
depth=1 C = US, O = Let's Encrypt, CN = R3
verify return:1
depth=0 CN = c29694.sgvps.net
verify return:1
---
Certificate chain
 0 s:CN = c29694.sgvps.net
   i:C = US, O = Let's Encrypt, CN = R3
 1 s:C = US, O = Let's Encrypt, CN = R3
   i:O = Digital Signature Trust Co., CN = DST Root CA X3
```

Output shows that your server sends a certificate valid for c29694.sgvps.net. You are using mail.alweb.dk to connect. As the certificate is not valid for mail.alweb.dk the connection is refused. It should work if c29694.sgvps.net is used to connect or replace the certificate with a valid one for mail.alweb.dk.
