### ISSUE TITLE
Title of attachment not visible

### ISSUE THREAD

**Issue by davidpr78** [nextcloud/mail#4507]
### Expected behavior
When I add an attachtment from the local harddrive, the title of the file is visible.

### Actual behavior
The title/name of the attached file from the local harddrive is not visible in the mail, only the trashcan.

### Mail app

**Mail app version: 1.8.1

**Mailserver or service:** 
WebhostOne

### Server configuration
Edudocs.org

#### Client configuration
**Browser:** Chrome

**Operating system:** 
Windows 10

**Comment by ChristophWurst** [comment]
Fixed with https://github.com/nextcloud/mail/pull/4474 :)
