### ISSUE TITLE
New Message button after sending a message does not work

### ISSUE THREAD

**Issue by davidpr78** [nextcloud/mail#4522]
### Expected behavior
After sending a message you can click on the + new message button to send another mail.

### Actual behavior
After sending a mail the + new message button does not react.

### Mail app

**Mail app version:** 1.8.1

**Mailserver or service:** WebhostOne

### Server configuration

Edudocs.org

#### Client configuration Chrome 88

**Operating system:** Windows 10

**Comment by davidpr78** [comment]
I forgot to say: It only happens, when I wrote a mail to more than one recipients.

**Comment by StCyr** [comment]
Here, it does that wathever the number of recipients

**Comment by ChristophWurst** [comment]
Fix is at #4535 :rocket:
