### ISSUE TITLE
"Error sending your message" when sending a draft but message is sent

### ISSUE THREAD

**Issue by LukasReschke** [nextcloud/mail#4523]
I just had this on c.nc.c when trying to send a draft:

![image](https://user-images.githubusercontent.com/878997/107944394-52cae580-6f8e-11eb-8edc-8191612dbea1.png)

The HTTP response to /apps/mail/api/accounts/{ACCOUNT_ID}/send was:

```
{"status":"error","message":"Server error","data":[],"code":0}
```

But the mail was actually send on each press to "send" in the draft.

**Comment by ChristophWurst** [comment]
looks like a dup of https://github.com/nextcloud/mail/issues/4153
