### ISSUE TITLE
updating account details fails (request to malformed address)

### ISSUE THREAD

**Issue by fallingcats** [nextcloud/mail#4529]
### Expected behavior
Tell us what should happen
Mail app should write changes to account settings into the database

### Actual behavior
Nothing happens, there is no error.

## Observation
I have seen my browser make a request to `https://FQDN/apps/mail/api/accounts/%7Bid%7D` which makes me believe there is an error somewhere in the JS code because `%7Bid%7D` unescaped would be `{id}` which probably should have been subsituted by some actual id.
The strange thing is that the server responds with http 200 (no error) which probably fools the mail client into not showing an error.

### Mail app

**Mail app version:** (see apps admin page, e.g. 0.5.3)
1.8.1

**Mailserver or service:** (e.g. Outlook, Yahoo, Gmail, Exchange,...)
other (a1.net)

### Server configuration
**Operating system:**
Ubuntu 20.04.2 LTS

**Web server:**
nginx 1.18.0-0ubuntu1

**Database:**
mariadb-server-10.3

**PHP version:**
7.4.3-4ubuntu2.4

**Nextcloud version:** (see Nextcloud admin page)
Nextcloud 20.0.7

#### Client configuration
**Browser:** (e.g. Firefox 48)
Firefox 85.0.2, Chromium 88.0.4324.150

**Operating system:** (e.g. Arch Linux)
Arch Linux

**Comment by kesselb** [comment]
![image](https://user-images.githubusercontent.com/3902676/108225961-be52b580-713c-11eb-8e77-f259022161be.png)

Looks like the account id is not set.
