### ISSUE TITLE
Error message trying to install plugin

### ISSUE THREAD

**Issue by guymass** [nextcloud/mail#4530]
I was trying to install the plugin on my nextcloud site and I get this error:

personalNamespace is not a valid attribute
![Screen Shot 5781-06-05 at 1 40 12](https://user-images.githubusercontent.com/58882903/108135629-1946c700-70c1-11eb-958e-6b7737e53ec0.jpg)

Site is fully updated.

**Comment by ChristophWurst** [comment]
mind checking the logs and first opening this ticket on the forums? this doesn't look like an issue with the app itself but some problem with the app download or extraction
