### ISSUE TITLE
Blank message with php8

### ISSUE THREAD

**Issue by ChristophWurst** [nextcloud/mail#4532]
### Expected behavior

The app works with php8.

### Actual behavior

Any newly added messages are "blank" with php8 because Horde gives us null values for all the header fields we request due to an error on IMAP.

### Mail app

**Mail app version:**

v1.8.x or later

cc @miaulalala 

Upstream bug https://bugs.horde.org/ticket/15050

**Comment by miaulalala** [comment]
Current workaround is to replace line 2932 in `Horde_Imap_Client_Socket` with `$cmd = ( is_string( $key ) === true && ( $key == 0 ) === false  )`. This will allow commands to be built with

**Comment by ChristophWurst** [comment]
Fixed with #4534
