### ISSUE TITLE
Unvisible Text in Darkmode

### ISSUE THREAD

**Issue by chrmah** [nextcloud/mail#4545]
Hello !

On current NC version i can read the emails only on marking the hole text.

The Background of mails are in "light-grey", the same color of the defined font-color. Better could be the "dark-grey" color as background - like the same in Darkmode of NC.

![Screenshot_2021-02-18 Mail NC](https://user-images.githubusercontent.com/75425360/108319788-344d3000-71c2-11eb-9c69-7f9366e1e3f7.png)

**Comment by ChristophWurst** [comment]
update to v1.8.2
