### ISSUE TITLE
Duplicate table: relation already exists

### ISSUE THREAD

**Issue by almereyda** [nextcloud/mail#4564]
### Expected behavior

- The Maps app is installable via the Nextcloud web interface also on the slower `aarch64` platform.

### Actual behavior

- Go to Apps Overview and search for Mail
- Click the *Download and Install* button
- Wait for it to finish as a grey button, only for it to return to its green state.
- Click the button again.
- Watch this error appear:

```
An exception occurred while executing 'CREATE TABLE oc_mail_messages (id SERIAL NOT NULL, uid INT NOT NULL, message_id VARCHAR(255) DEFAULT NULL, mailbox_id VARCHAR(4) NOT NULL, subject VARCHAR(255) DEFAULT '' NOT NULL, sent_at INT NOT NULL, flag_answered BOOLEAN DEFAULT 'false' NOT NULL, flag_deleted BOOLEAN DEFAULT 'false' NOT NULL, flag_draft BOOLEAN DEFAULT 'false' NOT NULL, flag_flagged BOOLEAN DEFAULT 'false' NOT NULL, flag_seen BOOLEAN DEFAULT 'false' NOT NULL, flag_forwarded BOOLEAN DEFAULT 'false' NOT NULL, flag_junk BOOLEAN DEFAULT 'false' NOT NULL, flag_notjunk BOOLEAN DEFAULT 'false' NOT NULL, updated_at INT DEFAULT NULL, PRIMARY KEY(id))': SQLSTATE[42P07]: Duplicate table: 7 ERROR: relation "oc_mail_messages" already exists
```

![Bildschirmfoto von 2021-02-19 16-53-18](https://user-images.githubusercontent.com/1645308/108528278-88940500-72d3-11eb-8a6f-4bacadf6cb6f.png)

### Mail app

**Mail app version:** 1.8.3

**Mailserver or service:** not yet applicable

### Server configuration

**Operating system**: Ubuntu 20.04.1

**Web server:** Boringproxy > Caddy > Nginx > php-fpm

**Database:** PostgreSQL

**PHP version:** a lot! (up to date from Docker containers)

**Nextcloud Version:** 20.0.7

#### Client configuration
**Browser:** Firefox latest

**Operating system:** Fedora 33

**Comment by ChristophWurst** [comment]
Well, this isn't ideal but also nothing the app can improve. Have you tried improving the performance of your Nextcloud with some tweaks like a faster db or caching? It looks like your php process ran into a timeout (increase that value maybe?) and the process died after creating the table but before writing that the migration had been run …

**Comment by almereyda** [comment]
Thanks for the details. I wanted to leave a note here, in case some other
search engine user comes up with a similar error, and might find additional
information here. As you provided, thanks.

This is a Raspberry Pi, there's not much I can do to increase the available
speed of the system.
