### ISSUE TITLE
Mail + DavMail: Sending an e-mail ends with "Error: Request failed with status code 503"

### ISSUE THREAD

**Issue by leArthurDent** [nextcloud/mail#4572]
### Expected behavior
Sending an e-mail using mail app configured to work with DavMail (exchange to imap/smtp gateway) finishes without an error message.

### Actual behavior
The e-mail is actually send and is received, but mail app displays the following error:
"Error: Request failed with status code 503"

Judging from the logs, mail app tries to save a copy of the e-mail in the sent folder which is (as far as I know) handled by exchange on the server side and thus cannot be confirmed by DavMail. Maybe a solution for this to work would be an option for the mail app to not try to save a copy in a specific folder.

### Log output

`OCA\Mail\Exception\ServiceException: Could not save sent message on IMAP
/var/www/html/nextcloud/lib/private/EventDispatcher/ServiceEventListener.php - line 76:
OCA\Mail\Listener\SaveSentMessageListener->handle(OCA\Mail\Eve ... {})
/var/www/html/nextcloud/3rdparty/symfony/event-dispatcher/EventDispatcher.php - line 251:
OC\EventDispatcher\ServiceEventListener->__invoke(OCA\Mail\Eve ... {}, "OCA\\Mail\\ ... t", Symfony\Comp ... {})
/var/www/html/nextcloud/3rdparty/symfony/event-dispatcher/EventDispatcher.php - line 73:
Symfony\Component\EventDispatcher\EventDispatcher->callListeners([ Closure {} ... }], "OCA\\Mail\\ ... t", OCA\Mail\Eve ... {})
/var/www/html/nextcloud/lib/private/EventDispatcher/EventDispatcher.php - line 86:
Symfony\Component\EventDispatcher\EventDispatcher->dispatch(OCA\Mail\Eve ... {}, "OCA\\Mail\\ ... t")
/var/www/html/nextcloud/apps/mail/lib/Service/MailTransmission.php - line 198:
OC\EventDispatcher\EventDispatcher->dispatch("OCA\\Mail\\ ... t", OCA\Mail\Eve ... {})
/var/www/html/nextcloud/apps/mail/lib/Controller/AccountsController.php - line 414:
OCA\Mail\Service\MailTransmission->sendMessage(OCA\Mail\Mod ... {}, null, null, OCA\Mail\Db\Message { id: 8142})
/var/www/html/nextcloud/lib/private/AppFramework/Http/Dispatcher.php - line 169:
OCA\Mail\Controller\AccountsController->send(3, "www", "--\n\nDr. S ... .", "username@domain.de", "", "", false, false, 8142, null, [], null)
/var/www/html/nextcloud/lib/private/AppFramework/Http/Dispatcher.php - line 100:
OC\AppFramework\Http\Dispatcher->executeController(OCA\Mail\Con ... {}, "send")
/var/www/html/nextcloud/lib/private/AppFramework/App.php - line 152:
OC\AppFramework\Http\Dispatcher->dispatch(OCA\Mail\Con ... {}, "send")
/var/www/html/nextcloud/lib/private/Route/Router.php - line 309:
OC\AppFramework\App::main("OCA\\Mail\\ ... r", "send", OC\AppFramew ... {}, { id: "3",_r ... "})
/var/www/html/nextcloud/lib/base.php - line 1008:
OC\Route\Router->match("/apps/mail/ ... d")
/var/www/html/nextcloud/index.php - line 37:
OC::handleRequest()`

`Verursacht durch Horde_Imap_Client_Exception: Error when communicating with the mail server.
/var/www/html/nextcloud/apps/mail/vendor/pear-pear.horde.org/Horde_Imap_Client/Horde/Imap/Client/Socket.php - line 4542:
Horde_Imap_Client_Socket_Connection_Socket->read()
/var/www/html/nextcloud/apps/mail/vendor/pear-pear.horde.org/Horde_Imap_Client/Horde/Imap/Client/Socket.php - line 4466:
Horde_Imap_Client_Socket->_getLine(Horde_Imap_C ... }})
/var/www/html/nextcloud/apps/mail/vendor/pear-pear.horde.org/Horde_Imap_Client/Horde/Imap/Client/Socket.php - line 4427:
Horde_Imap_Client_Socket->_processCmdContinuation(Horde_Imap_C ... }})
/var/www/html/nextcloud/apps/mail/vendor/pear-pear.horde.org/Horde_Imap_Client/Horde/Imap/Client/Socket.php - line 4295:
Horde_Imap_Client_Socket->_processCmd(Horde_Imap_C ... }}, Horde_Imap_C ... "}, Horde_Imap_C ... "})
/var/www/html/nextcloud/apps/mail/vendor/pear-pear.horde.org/Horde_Imap_Client/Horde/Imap/Client/Socket.php - line 4235:
Horde_Imap_Client_Socket->_sendCmdChunk(Horde_Imap_C ... }}, [ Horde_Imap ... }])
/var/www/html/nextcloud/apps/mail/vendor/pear-pear.horde.org/Horde_Imap_Client/Horde/Imap/Client/Socket.php - line 1941:
Horde_Imap_Client_Socket->_sendCmd(Horde_Imap_C ... "})
/var/www/html/nextcloud/apps/mail/vendor/pear-pear.horde.org/Horde_Imap_Client/Horde/Imap/Client/Base.php - line 1846:
Horde_Imap_Client_Socket->_append(Horde_Imap_Client_Mailbox {}, [ { data: nu ... }], [])
/var/www/html/nextcloud/apps/mail/lib/IMAP/MessageMapper.php - line 317:
Horde_Imap_Client_Base->append(Horde_Imap_Client_Mailbox {}, [ { data: nu ... }])
/var/www/html/nextcloud/apps/mail/lib/Listener/SaveSentMessageListener.php - line 90:
OCA\Mail\IMAP\MessageMapper->save(Horde_Imap_C ... e}, OCA\Mail\Db\Mailbox { id: 21}, Horde_Mime_Mail {})
/var/www/html/nextcloud/lib/private/EventDispatcher/ServiceEventListener.php - line 76:
OCA\Mail\Listener\SaveSentMessageListener->handle(OCA\Mail\Eve ... {})
/var/www/html/nextcloud/3rdparty/symfony/event-dispatcher/EventDispatcher.php - line 251:
OC\EventDispatcher\ServiceEventListener->__invoke(OCA\Mail\Eve ... {}, "OCA\\Mail\\ ... t", Symfony\Comp ... {})
/var/www/html/nextcloud/3rdparty/symfony/event-dispatcher/EventDispatcher.php - line 73:
Symfony\Component\EventDispatcher\EventDispatcher->callListeners([ Closure {} ... }], "OCA\\Mail\\ ... t", OCA\Mail\Eve ... {})
/var/www/html/nextcloud/lib/private/EventDispatcher/EventDispatcher.php - line 86:
Symfony\Component\EventDispatcher\EventDispatcher->dispatch(OCA\Mail\Eve ... {}, "OCA\\Mail\\ ... t")
/var/www/html/nextcloud/apps/mail/lib/Service/MailTransmission.php - line 198:
OC\EventDispatcher\EventDispatcher->dispatch("OCA\\Mail\\ ... t", OCA\Mail\Eve ... {})
/var/www/html/nextcloud/apps/mail/lib/Controller/AccountsController.php - line 414:
OCA\Mail\Service\MailTransmission->sendMessage(OCA\Mail\Mod ... {}, null, null, OCA\Mail\Db\Message { id: 8142})
/var/www/html/nextcloud/lib/private/AppFramework/Http/Dispatcher.php - line 169:
OCA\Mail\Controller\AccountsController->send(3, "www", "--\n\nDr. S ... .", "username@domain.de", "", "", false, false, 8142, null, [], null)
/var/www/html/nextcloud/lib/private/AppFramework/Http/Dispatcher.php - line 100:
OC\AppFramework\Http\Dispatcher->executeController(OCA\Mail\Con ... {}, "send")
/var/www/html/nextcloud/lib/private/AppFramework/App.php - line 152:
OC\AppFramework\Http\Dispatcher->dispatch(OCA\Mail\Con ... {}, "send")
/var/www/html/nextcloud/lib/private/Route/Router.php - line 309:
OC\AppFramework\App::main("OCA\\Mail\\ ... r", "send", OC\AppFramew ... {}, { id: "3",_r ... "})
/var/www/html/nextcloud/lib/base.php - line 1008:
OC\Route\Router->match("/apps/mail/ ... d")
/var/www/html/nextcloud/index.php - line 37:
OC::handleRequest()`

### Mail app

**Mail app version:** 1.8.3

**Mailserver or service:** Exchange vial DavMail 5.1.0

### Server configuration

**Operating system**: Raspbian GNU/Linux 10 (buster)

**Web server:** Apache

**Database:** MariaDB

**PHP version:** 7.3

**Nextcloud Version:** 20.0.7

#### Client configuration
**Browser:** Epiphany 3.34.2

**Operating system:** openSUSE 15.2

EDIT: Removed some private details from logs.

**Comment by ChristophWurst** [comment]
> Error when communicating with the mail server

The Nextcloud mail app offers an extensive logging system to make it easier identifying and tracking down bugs. Please enable [debug mode](https://docs.nextcloud.com/server/stable/developer_manual/general/devenv.html#enabling-debug-mode) and set the log [level to debug](https://docs.nextcloud.com/server/stable/admin_manual/configuration_server/logging_configuration.html) in your admin settings. Then, try to reproduce your issue and take another look at `data/nextcloud.log` and `data/horde_imap.log`. Make sure not to post any personal information.

**Comment by leArthurDent** [comment]
Hi, thanks for hinting to the debug mode. Your link to the explanation on how to enable debug mode is broken, I acted as suggested [here](https://docs.nextcloud.com/server/latest/developer_manual/getting_started/debugging.html?highlight=debug%20mode).

I started with fresh log files, started debug mode, sent one message as described above, and disabled debug mode again. You'll find the requested output in the files below. Please note that I cropped nextcloud.log only keeping entries with "app":"mail" and removed any sensitive content from any log. However, if you still come across sensitive content in those log files, please let me know.

[nextcloud_cropped.log](https://github.com/nextcloud/mail/files/6035859/nextcloud_cropped.log)
[horde_smtp_censored.log](https://github.com/nextcloud/mail/files/6035883/horde_smtp_censored.log)
[horde_imap_censored.log](https://github.com/nextcloud/mail/files/6035973/horde_imap_censored.log)


What caught my attention were the last two lines of horde_imap_censored.log

`C: 6 APPEND Sent (\seen) {995}` 
`>> ERROR: Server closed the connection.`

Please let me know, if you need anything else.

**Comment by ChristophWurst** [comment]
> C: 7 EXAMINE &ABQ-nonexist&ABQ-
> S: 7 BAD unable to handle request: Fehler bei der Schemaüberprüfung der Anforderung: Es wurde das Token """ erwartet

that is the issue. that mailbox has a problematic name apparently.

**Comment by leArthurDent** [comment]
I just dug a bit deeper and realised that the message is wrongfully translated from imap to exchange by davmail. It's the attribute *FieldURIOrConstant* that is set wrongly (see below in bold) containing some funny character.

><soap:Envelope
	xmlns:soap="http://schemas.xmlsoap.org/soap/envelope/"
	xmlns:t="http://schemas.microsoft.com/exchange/services/2006/types"
	xmlns:m="http://schemas.microsoft.com/exchange/services/2006/messages">
	<soap:Header>
		<t:RequestServerVersion Version="Exchange2013_SP1"/>
	</soap:Header>
	<soap:Body>
		<m:FindFolder Traversal="Shallow">
			<m:FolderShape>
				<t:BaseShape>IdOnly</t:BaseShape>
				<t:AdditionalProperties>
					<t:ExtendedFieldURI PropertyTag="0x3008" PropertyType="SystemTime"/>
					<t:ExtendedFieldURI PropertyTag="0x3613" PropertyType="String"/>
					<t:ExtendedFieldURI PropertyTag="0x360a" PropertyType="Boolean"/>
					<t:ExtendedFieldURI PropertyTag="0x670a" PropertyType="SystemTime"/>
					<t:ExtendedFieldURI PropertyTag="0x6751" PropertyType="Integer"/>
					<t:FieldURI FieldURI="folder:DisplayName"/>
					<t:ExtendedFieldURI PropertyTag="0x3603" PropertyType="Integer"/>
					<t:ExtendedFieldURI PropertyTag="0x10f3" PropertyType="String"/>
					<t:ExtendedFieldURI PropertyTag="0x3602" PropertyType="Integer"/>
					<t:ExtendedFieldURI PropertyTag="0x6752" PropertyType="Integer"/>
				</t:AdditionalProperties>
			</m:FolderShape>
			<m:IndexedPageFolderView MaxEntriesReturned="1" Offset="0" BasePoint="Beginning"/>
			<m:Restriction>
				<t:IsEqualTo>
					<t:FieldURI FieldURI="folder:DisplayName"/>
					<t:FieldURIOrConstant>
						<t:Constant Value=**"^Tnonexist^T"**/>
					</t:FieldURIOrConstant>
				</t:IsEqualTo>
			</m:Restriction>
			<m:ParentFolderIds>
				<t:DistinguishedFolderId Id="msgfolderroot"/>
			</m:ParentFolderIds>
		</m:FindFolder>
	</soap:Body>
</soap:Envelope>

I setup a virtual machine with openSUSE 15.3 (currently alpha), nextcloud and davmail and found out that it works fine using that setup. 
Since openSUSE has a more up to date version of davmail I installed a the same version on my raspberry pi and it still didn't work (even after copying the settings file from openSUSE to the raspberry pi).
So finally, I kinda guess that it might be a bug in the java runtime or anything else. But I think we can rule out that this is a bug in mail.

**Comment by ChristophWurst** [comment]
you can inspect the `oc_mail_mailboxes` table for the mailbox names. are they correct there? if so I second the suspicious that it's a bug elsewhere.

**Comment by leArthurDent** [comment]
I did so and didn't find anything unusual.

>MariaDB [xxxxx]> select name from oc_mail_mailboxes;
+-----------------+
| name            |
+-----------------+
| Drafts          |
| INBOX           |
| Junk            |
| Sent            |
| Trash           |
| Unsent Messages |
+-----------------+

I even purged the mail app from the instance and all corresponding tables from the database and started over freshly but that didn't change anything at all.

**Comment by ChristophWurst** [comment]
That looks just fine. You can inspect the IMAP logs but it seems more and more an issue of the IMAP server.

**Comment by leArthurDent** [comment]
I'll close the issue, since I works in several instances and it doesn't seem to be related to mail app.
