### ISSUE TITLE
wrong avatars on the widget "Wichtige E-Mail"

### ISSUE THREAD

**Issue by kinimodmeyer** [nextcloud/mail#4580]
### Expected behavior

the displayed avatar on the email in the widget should be correct.

### Actual behavior
on the widget "Wichtige E-Mail" i see wrong avatars which are not related to the email/thread.
when i inspect the html i  can see the following in the src of the img: "https://../remote.php/dav/addressbooks/system/system/system/Database:XYZ.vcf?photo"
(XYZ is not part on this e-mail)

pressing F5 on the dashboard also shows different not related avatars on the same email.
seams like a random display behavior.

### Mail app

**Mail app version:** 1.8.3

**Comment by ChristophWurst** [comment]
Dup of https://github.com/nextcloud/mail/issues/4412?

**Comment by kinimodmeyer** [comment]
hm i don´t saw this wrong avatar handling on the email lists or inside a email.

**Comment by ChristophWurst** [comment]
The other technical reason I could think of is that Vue tries to reuse unrelated avatars. But in theory we have a key on all of our envelopes … :thinking:

**Comment by AutomCoding** [comment]
I have the same issue (favicon and text censored):
![screenshot_nextcloud](https://user-images.githubusercontent.com/40275136/152966282-fe2112e7-f49d-410d-bfa5-07d08333cbfb.png)

Messages 4, 5 and 7 (T. S.) are from the same person, but number 5 uses the favicon of number 6 (M. R.). Number 6 then uses the default avatar from their initials.

My gut feeling says it likely has something to do with consecutive duplicates. I can confirm that it behaves as intended in the Mail app itself.
