### ISSUE TITLE
Keep recipients when pressing backspace in an empty recipients field 

### ISSUE THREAD

**Issue by myrho** [nextcloud/mail#4581]
### Expected behavior
Users may press backspace more often than there are characters in recipients fields without removing already selected recipients.

### Actual behavior
1. User enters characters in an recipients field
2. Autocompletion suggests recipients
3. User selects one.
4. User deletes characters to free the field for a new search
5. Cursor may move too slow due to autocompletion being triggered at each keystroke, so that user hits backspace more often than there are characters.
6. Pressing backspace on an empty recepients field causes removal of the last selected recipient from the list. This may be missed by the user especially in the case of many recepients selected.

### Mail app

**Mail app version:** 1.8.3

#### Client configuration
**Browser:** Firefox 85

**Comment by ChristophWurst** [comment]
I think this can be seen as part of https://github.com/nextcloud/mail/issues/2769. FYI @GretaD is currently working on a rework of the component.
