### ISSUE TITLE
Mail won't connect to email server

### ISSUE THREAD

**Issue by wadeandree** [nextcloud/mail#4592]
### Expected behavior
When creating new email account it should have logged in using the provided user and email settings

### Actual behavior
[mail] Error: Creating account failed: Could not connect to IMAP host mail.andreefamily.com:993: Error connecting to mail server.

POST /index.php/apps/mail/api/accounts

### Mail app

**Mail app version:** 1.8.3

**Mailserver or service:** Personally hosted postfix email server.  The mail server is running using a Let's Encrypt certificate.  Nextcloud and the email server are on the same machine.  Login info is correct.  Server settings are correct.

### Server configuration

**Operating system**: Unbuntu

**Web server:** Apache

**Database:** Mysql

**PHP version:** 7.4

**Nextcloud Version:** 20.0.8

#### Client configuration
**Browser:** Safari

**Operating system:** Mac OS

**Comment by ChristophWurst** [comment]
> Could not connect to IMAP host mail.andreefamily.com:993: Error connecting to mail server

do you have a fast connection between your Nextcloud installation and the mail server?

The Nextcloud mail app offers an extensive logging system to make it easier identifying and tracking down bugs. Please enable [debug mode](https://docs.nextcloud.com/server/stable/developer_manual/getting_started/devenv.html#enabling-debug-mode) and set the log [level to debug](https://docs.nextcloud.com/server/stable/admin_manual/configuration_server/logging_configuration.html) in your admin settings. Then, try to reproduce your issue and take another look at `data/nextcloud.log` and `data/horde_imap.log`. Make sure to remove any sensitive data before posting. Reset log levels and debug mode to the previous values afterwards.

**Comment by arghyadeep-k** [comment]
@wadeandree Can you please explain how you fixed the issue?

**Comment by wadeandree** [comment]
I didn't.  I haven't been able to locate the log entry or a more detail reason for it not to connectSent via the Samsung Galaxy S8 Active, an AT&T 5G Evolution capable smartphone
-------- Original message --------From: Arghyadeep ***@***.***> Date: 4/6/21  19:22  (GMT-05:00) To: nextcloud/mail ***@***.***> Cc: wadeandree ***@***.***>, Mention ***@***.***> Subject: Re: [nextcloud/mail] Mail won't connect to email server (#4592) 
@wadeandree Can you please explain how you fixed the issue?
