### ISSUE TITLE
Show favorite mails on top in the inbox

### ISSUE THREAD

**Issue by jancborchardt** [nextcloud/mail#460]
Just like we do in Files with favorite folders, we should show favorited mails on top of the respective views so they are directly visible. That way favorites are more nicely integrated.

**Comment by ChristophWurst** [comment]
As discussed, I'm against this. It might be my very personal work flow, but usually I have too many flagged messages in my inbox so that new emails would never be visible. We already have the special folder for flagged messages. We can improve that one (e.g. show a reliable messages counter) or something similar, but I wouldn't change the sorting order/priority for flagged messages in the normal inbox.

**Comment by ChristophWurst** [comment]
cc @nextcloud/mail for more opinions

**Comment by jancborchardt** [comment]
We don't need to show them all, maybe just the first 3 and below a "Show all" to switch to Favorites. See Google Inbox for reference.

**Comment by ChristophWurst** [comment]
Let's close this as I don't see that coming in the next few months.

**Comment by jancborchardt** [comment]
Even though it’s not coming in the next few months, we shouldn’t close it. It’s still an active request and something that would greatly improve the utility of favorites.

**Comment by jancborchardt** [comment]
@violoncelloCH @StCyr @Gomez @kevgathuku what do you think? :)

**Comment by kevgathuku** [comment]
Sorry, I accidentally closed the issue 😅

I would also go for flagging/starring 🌟 . I also make heavy use of this feature, and have lots of flagged messages. It would be distracting always having these at the top of the inbox and having to scroll some pages to see my recent emails.

If they are in a separate folder, I can use the inbox to keep track of new messages and have a Favorites folder, where I can access the starred messages.

**Comment by jancborchardt** [comment]
Hmm, as said above there’s other platforms which designed for that even when you have lots of favorites:

> We don't need to show them all, maybe just the first 3 and below a "Show all" to switch to Favorites. See Google Inbox for reference.

So it’s not either all or nothing, but we can have stuff inbetween. :) Much like the "Recommendations" section in Files essentially.

**Comment by StCyr** [comment]
@nextcloud/mail shows me only 13 envelopes on my 1080p screen, so I don't think I would like losing 3 entries for showing favorites. 

I think 1 entry would be the maximum I would be willing to spend for showing favorites. But, in this case, why not just adding a "Unified Favorites" entry in the Navigation pane?

**Comment by jancborchardt** [comment]
This is part of "Priority inbox", pull request at https://github.com/nextcloud/mail/pull/2648 :)

**Comment by alexanderdd** [comment]
Close because it's implemented?

**Comment by ChristophWurst** [comment]
Yes :)

Thanks for cleaning up the tickets a bit @alexanderdd :)
