### ISSUE TITLE
Allow/block certain mail providers

### ISSUE THREAD

**Issue by diemelone** [nextcloud/mail#4601]
Admins should be able to set certain mail providers on a blocklist/allowlist

eg if you use nc for a certain club/company/etc. you wouldn't want any private emails taking up space, therefore I'd like to only allow accounts ending with @example.com, @example.org, ...

**Comment by ChristophWurst** [comment]
sounds like an enterprise feature

**Comment by ChristophWurst** [comment]
duplicate of https://github.com/nextcloud/mail/issues/4317

**Comment by diemelone** [comment]
Almost, #4317 was just a whitelist, I'm suggesting a whitelist aswell.
> 
> 
> duplicate of #4317
