### ISSUE TITLE
Release 1.8.3 not compatible with PHP 8

### ISSUE THREAD

**Issue by rio-** [nextcloud/mail#4603]
The `info.xml` of v1.8.3 contains

	<dependencies>
		<php min-version="7.3" max-version="7.4" />
		<nextcloud min-version="20" max-version="21" />
	</dependencies>

Hence, it won't install on a system running PHP 8, despite the changelog listing fixes for PHP 8 compatibility already.

**Comment by ChristophWurst** [comment]
Whoops, then the changelog is wrong. https://github.com/nextcloud/mail/pull/4319 was never intended for v1.8 but only v1.9

**Comment by rio-** [comment]
Well then when are we getting a release of v1.9? Nextcloud 21 has been released on February 22 and is compatible with PHP 8. This app is the only missing piece in my Nextcloud installation.

**Comment by ChristophWurst** [comment]
When it's ready. We are working on it.

**Comment by ChristophWurst** [comment]
You may test a prerelease that I just packaged for you: https://github.com/nextcloud/mail/releases/tag/v1.9.0-alpha2

**Comment by ChristophWurst** [comment]
@rio- we are awaiting some testing feedback before the release.

**Comment by rio-** [comment]
I successfully installed the alpha release and it seems to work fine.

**Comment by ChristophWurst** [comment]
thanks a lot for testing!
