### ISSUE TITLE
Focused inbox [$22]

### ISSUE THREAD

**Issue by jancborchardt** [nextcloud/mail#461]
This would be a better inbox, kind of similar to Google’s priority Inbox or the iOS Mail »VIP« feature. It would show:

- Mails where you are the only person in the _to_ field
- Favorited mails
- Mails from favorite contacts

It would **not** show mails:
- where you are just in cc
- where you are in the _to_ field among other people
- which are notifications from platforms like Twitter, Github, Facebook, Meetup etc
- which are newsletters
- from mailing lists or forums
- …

Probably it’s easier to filter by the whitelist rules because those are much less rules.

What do you think @Gomez @ChristophWurst @nextcloud/mail

**Comment by ChristophWurst** [comment]
Sounds like https://www.hanselman.com/blog/OneEmailRuleHaveASeparateInboxAndAnInboxCCToReduceEmailStressGuaranteed.aspx :wink:

**Comment by jancborchardt** [comment]
See, others think it makes sense too. ;) So that's a simple one-rule way to create an MVP of focused inbox.

**Comment by ChristophWurst** [comment]
Fixed via https://github.com/nextcloud/mail/projects/7

hey @johanlives the ticket at https://www.bountysource.com/issues/48604504-focused-inbox does not close. can you help?

**Comment by johanlives** [comment]
send a ticket to support@bountysource.com
