### ISSUE TITLE
Self hosted email server 

### ISSUE THREAD

**Issue by bitfanatic** [nextcloud/mail#4617]
### Feature Request

A feature to host my own mail server would be awesome

I realise this a not something that is easy otherwise you might already have done it

But a few weeks ago i came across a project called Mailpile 
https://github.com/mailpile/Mailpile

I looks like and awesome project / feature that many people would like to use 

But i would like to use this with nextcloud to self host my mail

The ability the self host mail would be God like, the holy grail of self hosting
And something that all people should have the ability to do

#### Summary

A way to self host mail even for the non tech savvy people

And With encryption utilising mailpile

**Comment by dehnhardt** [comment]
I'm sorry, but mailpile is just as much an email client as this mail program. What you are looking for is an email server.

**Comment by bitfanatic** [comment]
> I'm sorry, but mailpile is just as much an email client as this mail program. What you are looking for is an email server.

Ok i must admit i am not that technical but the mailpile website does claim that its self hosted

But they do it a different way.
You keep your normal mail adresse provider but you download all your emails and store them on my own hardware
While deleting on mail client

Any incoming mail sent to your mail addresse provider will be downloaded and stored on my hardware 
And deleted on mail provider

Does the nextcloud mail app work like this aswell?

**Comment by dehnhardt** [comment]
> I keep my normal email account provider mymail@gmail.com but you download all my emails and store them on my own hardware
> While deleting on my email account mymail@gmail.com

This is what used to be called a POP account. The problem with POP accounts was that you couldn't access your email from multiple locations because it was stored on a single computer in a single mail client. If they were really claiming to do that, I would consider that an April Fool's joke - just a month early.

**Comment by bitfanatic** [comment]
Hmm ok well there goes my excitement too bad

Do you know what would be the best way to self hosted mail server 
For a noobie

**Comment by bitfanatic** [comment]
> > I keep my normal email account provider [mymail@gmail.com](mailto:mymail@gmail.com) but you download all my emails and store them on my own hardware
> > While deleting on my email account [mymail@gmail.com](mailto:mymail@gmail.com)
> 
> This is what used to be called a POP account. The problem with POP accounts was that you couldn't access your email from multiple locations because it was stored on a single computer in a single mail client. If they were really claiming to do that, I would consider that an April Fool's joke - just a month early.

Thank you for taking the time to answer 👍🙂

**Comment by miaulalala** [comment]
Hi @bitfanatic , thank you for your suggestion! As @dehnhardt has kindly explained already, what you need is a mail server.
