### ISSUE TITLE
Further avatar sources [$50]

### ISSUE THREAD

**Issue by jancborchardt** [nextcloud/mail#463]
Most often my inbox looks like this:
![screenshot from 2017-08-24 18-11-46](https://user-images.githubusercontent.com/925062/29676231-c3792fca-88f7-11e7-9738-1b4a2b425226.png)![screenshot from 2017-08-24 18-11-32](https://user-images.githubusercontent.com/925062/29676233-c399381a-88f7-11e7-9d3e-81f99871a997.png)![screenshot from 2017-08-24 18-11-19](https://user-images.githubusercontent.com/925062/29676234-c39b373c-88f7-11e7-8a53-dee13a4ab1db.png)
And so on, you get the point.

Our flow looks like this:
1. Check for avatars from the Contacts app (if installed and if a picture is present for the contact)
2. Show a placeholder

The problem is that many of the emails we get are not necessarily from people in our contacts. We should improve it like this:
1. Check for avatars from the Contacts app (if installed and if a picture is present for the contact)
2. Check for avatars from federated Nextcloud servers
3. Check https://en.gravatar.com (yes this might be a privacy concern, but we could offer a setting to deactivate this)
4. Check the domain for a favicon we can use, which is good especially for notifications from Twitter, Github, Facebook, Meetup etc. (this could also have a setting to deactivate since it pings other services)
5. Show a placeholder

Any other ideas?

**Comment by jakobsack** [comment]
Current offline WIP:

- [x] Contacts app
- [ ] Federated servers
- [x] Gravatar
- [ ] Favicon

**Comment by jancborchardt** [comment]
@jakobsack aaaawesome! :)

**Comment by ChristophWurst** [comment]
Fixed by #469

**Comment by jancborchardt** [comment]
Everyday usage looks soooo much better now! Thanks @jakobsack! :)
