### ISSUE TITLE
Using Circles in the Mail-App

### ISSUE THREAD

**Issue by configonfi** [nextcloud/mail#4630]
### Feature Request

Using NC-groups as a recipient-list is the killer-feature for me and many other in my organisation. 
It would be pretty nice to be able to use circles too. Actually it does not work, that's very sad.      

NC 20.0.4
Circles 0.20.7

Thanks for your Work!

**Comment by ya-d** [comment]
Duplikate of #1850 I guess. But promoting Circles to a core feature of NC probably gives some weight to this issue.
