### ISSUE TITLE
Cant add imap account

### ISSUE THREAD

**Issue by small1** [nextcloud/mail#4635]
### Expected behavior
Adding an imap ccount should work out of the box

### Actual behavior
I get an error 500 saing something went wrong.  The account says broken and i cant access it. 

### Mail app

**Mail app version:** 1.8.3

**Mailserver or service:** imap at a webhosting company of unknown veriosn. Just says imap4rev1 ready

### Server configuration

**Operating system**: debian 10

**Web server:** nginx)

**Database:** mariadb 10.3

**PHP version:** 7.4

**Nextcloud Version:** 20.0.8

#### Client configuration
**Browser:** Chrome and firefox and edge tested

**Operating system:** uibuntu 20.04 and windows 10 tested

From nextcloud.log:

`{"reqId":"g3yEalW2NYlgBUtKgDdy","level":3,"time":"2021-03-02T13:59:02+00:00","remoteAddr":"2.65.92.7","user":"admin","app":"mail","method":"GET","url":"/apps/mail/box/priority","message":{"Exception":"OCA\\Mail\\Exception\\ServiceException","Message":"IMAP error: IMAP error reported by server.","Code":0,"Trace":[{"file":"/var/www/nextcloud/apps/mail/lib/Service/MailManager.php","line":128,"function":"sync","class":"OCA\\Mail\\IMAP\\MailboxSync","type":"->","args":[{"__class__":"OCA\\Mail\\Account"},{"__class__":"OC\\AppFramework\\ScopedPsrLogger"}]},{"file":"/var/www/nextcloud/apps/mail/lib/Controller/PageController.php","line":119,"function":"getMailboxes","class":"OCA\\Mail\\Service\\MailManager","type":"->","args":[{"__class__":"OCA\\Mail\\Account"}]},{"file":"/var/www/nextcloud/apps/mail/lib/Controller/PageController.php","line":179,"function":"index","class":"OCA\\Mail\\Controller\\PageController","type":"->","args":[]},{"file":"/var/www/nextcloud/lib/private/AppFramework/Http/Dispatcher.php","line":169,"function":"mailbox","class":"OCA\\Mail\\Controller\\PageController","type":"->","args":[0]},{"file":"/var/www/nextcloud/lib/private/AppFramework/Http/Dispatcher.php","line":100,"function":"executeController","class":"OC\\AppFramework\\Http\\Dispatcher","type":"->","args":[{"__class__":"OCA\\Mail\\Controller\\PageController"},"mailbox"]},{"file":"/var/www/nextcloud/lib/private/AppFramework/App.php","line":152,"function":"dispatch","class":"OC\\AppFramework\\Http\\Dispatcher","type":"->","args":[{"__class__":"OCA\\Mail\\Controller\\PageController"},"mailbox"]},{"file":"/var/www/nextcloud/lib/private/Route/Router.php","line":309,"function":"main","class":"OC\\AppFramework\\App","type":"::","args":["OCA\\Mail\\Controller\\PageController","mailbox",{"__class__":"OC\\AppFramework\\DependencyInjection\\DIContainer"},{"id":"priority","_route":"mail.page.mailbox"}]},{"file":"/var/www/nextcloud/lib/base.php","line":1008,"function":"match","class":"OC\\Route\\Router","type":"->","args":["/apps/mail/box/priority"]},{"file":"/var/www/nextcloud/index.php","line":37,"function":"handleRequest","class":"OC","type":"::","args":[]}],"File":"/var/www/nextcloud/apps/mail/lib/IMAP/MailboxSync.php","Line":106,"Previous":{"Exception":"Horde_Imap_Client_Exception_ServerResponse","Message":"IMAP error reported by server.","Code":0,"Trace":[{"file":"/var/www/nextcloud/apps/mail/vendor/pear-pear.horde.org/Horde_Imap_Client/Horde/Imap/Client/Socket.php","line":4314,"function":"_getLine","class":"Horde_Imap_Client_Socket","type":"->","args":[{"data":{"modseqs":[],"modseqs_nouid":[]},"fetch":{"__class__":"Horde_Imap_Client_Fetch_Results"},"__class__":"Horde_Imap_Client_Interaction_Pipeline"}]},{"file":"/var/www/nextcloud/apps/mail/vendor/pear-pear.horde.org/Horde_Imap_Client/Horde/Imap/Client/Socket.php","line":4242,"function":"_sendCmdChunk","class":"Horde_Imap_Client_Socket","type":"->","args":[{"data":{"modseqs":[],"modseqs_nouid":[]},"fetch":{"__class__":"Horde_Imap_Client_Fetch_Results"},"__class__":"Horde_Imap_Client_Interaction_Pipeline"},[{"debug":[],"literalplus":true,"literal8":false,"on_error":null,"on_success":null,"pipeline":{"data":{"modseqs":[],"modseqs_nouid":[]},"fetch":{"__class__":"Horde_Imap_Client_Fetch_Results"},"__class__":"Horde_Imap_Client_Interaction_Pipeline"},"response":{"tag":"9","responseCode":null,"status":4,"token":{"__class__":"Horde_Imap_Client_Tokenize"},"__class__":"Horde_Imap_Client_Interaction_Server_Tagged"},"tag":"9","__class__":"Horde_Imap_Client_Interaction_Command"},{"debug":[],"literalplus":true,"literal8":false,"on_error":null,"on_success":null,"pipeline":{"data":{"modseqs":[],"modseqs_nouid":[]},"fetch":{"__class__":"Horde_Imap_Client_Fetch_Results"},"__class__":"Horde_Imap_Client_Interaction_Pipeline"},"response":{"tag":"10","responseCode":null,"status":4,"token":{"__class__":"Horde_Imap_Client_Tokenize"},"__class__":"Horde_Imap_Client_Interaction_Server_Tagged"},"tag":"10","__class__":"Horde_Imap_Client_Interaction_Command"},{"debug":[],"literalplus":true,"literal8":false,"on_error":null,"on_success":null,"pipeline":{"data":{"modseqs":[],"modseqs_nouid":[]},"fetch":{"__class__":"Horde_Imap_Client_Fetch_Results"},"__class__":"Horde_Imap_Client_Interaction_Pipeline"},"response":{"tag":"11","responseCode":null,"status":4,"token":{"__class__":"Horde_Imap_Client_Tokenize"},"__class__":"Horde_Imap_Client_Interaction_Server_Tagged"},"tag":"11","__class__":"Horde_Imap_Client_Interaction_Command"},{"debug":[],"literalplus":true,"literal8":false,"on_error":null,"on_success":null,"pipeline":{"data":{"modseqs":[],"modseqs_nouid":[]},"fetch":{"__class__":"Horde_Imap_Client_Fetch_Results"},"__class__":"Horde_Imap_Client_Interaction_Pipeline"},"response":{"tag":"12","responseCode":null,"status":4,"token":{"__class__":"Horde_Imap_Client_Tokenize"},"__class__":"Horde_Imap_Client_Interaction_Server_Tagged"},"tag":"12","__class__":"Horde_Imap_Client_Interaction_Command"},{"debug":[],"literalplus":true,"literal8":false,"on_error":null,"on_success":null,"pipeline":{"data":{"modseqs":[],"modseqs_nouid":[]},"fetch":{"__class__":"Horde_Imap_Client_Fetch_Results"},"__class__":"Horde_Imap_Client_Interaction_Pipeline"},"response":{"tag":"13","responseCode":null,"status":4,"token":{"__class__":"Horde_Imap_Client_Tokenize"},"__class__":"Horde_Imap_Client_Interaction_Server_Tagged"},"tag":"13","__class__":"Horde_Imap_Client_Interaction_Command"},"And 35 more entries, set log level to debug to see all entries"]]},{"file":"/var/www/nextcloud/apps/mail/vendor/pear-pear.horde.org/Horde_Imap_Client/Horde/Imap/Client/Socket.php","line":1751,"function":"_sendCmd","class":"Horde_Imap_Client_Socket","type":"->","args":[{"data":{"modseqs":[],"modseqs_nouid":[]},"fetch":{"__class__":"Horde_Imap_Client_Fetch_Results"},"__class__":"Horde_Imap_Client_Interaction_Pipeline"}]},{"file":"/var/www/nextcloud/apps/mail/vendor/pear-pear.horde.org/Horde_Imap_Client/Horde/Imap/Client/Base.php","line":1733,"function":"_status","class":"Horde_Imap_Client_Socket","type":"->","args":[[{"__class__":"Horde_Imap_Client_Mailbox"},{"__class__":"Horde_Imap_Client_Mailbox"},{"__class__":"Horde_Imap_Client_Mailbox"},{"__class__":"Horde_Imap_Client_Mailbox"},{"__class__":"Horde_Imap_Client_Mailbox"},"And 35 more entries, set log level to debug to see all entries"],63]},{"file":"/var/www/nextcloud/apps/mail/lib/IMAP/FolderMapper.php","line":115,"function":"status","class":"Horde_Imap_Client_Base","type":"->","args":[{"Deleted Items":"Deleted Items","Drafts":"Drafts","INBOX":"INBOX","INBOX/2010":"INBOX/2010","INBOX/2010/Anst\u00e4llda":"INBOX/2010/Anst\u00e4llda","0":"And 35 more entries, set log level to debug to see all entries"}]},{"file":"/var/www/nextcloud/apps/mail/lib/IMAP/MailboxSync.php","line":104,"function":"getFoldersStatus","class":"OCA\\Mail\\IMAP\\FolderMapper","type":"->","args":[{"Deleted Items":{"__class__":"OCA\\Mail\\Folder"},"Drafts":{"__class__":"OCA\\Mail\\Folder"},"INBOX":{"__class__":"OCA\\Mail\\Folder"},"INBOX/2010":{"__class__":"OCA\\Mail\\Folder"},"INBOX/2010/Anst\u00e4llda":{"__class__":"OCA\\Mail\\Folder"},"0":"And 35 more entries, set log level to debug to see all entries"},{"cacheFields":["HICenv","HICflags","HIChdrs","HICdate","HICsize","And 1 more entries, set log level to debug to see all entries"],"changed":true,"statuscache":true,"__class__":"Horde_Imap_Client_Socket"}]},{"file":"/var/www/nextcloud/apps/mail/lib/Service/MailManager.php","line":128,"function":"sync","class":"OCA\\Mail\\IMAP\\MailboxSync","type":"->","args":[{"__class__":"OCA\\Mail\\Account"},{"__class__":"OC\\AppFramework\\ScopedPsrLogger"}]},{"file":"/var/www/nextcloud/apps/mail/lib/Controller/PageController.php","line":119,"function":"getMailboxes","class":"OCA\\Mail\\Service\\MailManager","type":"->","args":[{"__class__":"OCA\\Mail\\Account"}]},{"file":"/var/www/nextcloud/apps/mail/lib/Controller/PageController.php","line":179,"function":"index","class":"OCA\\Mail\\Controller\\PageController","type":"->","args":[]},{"file":"/var/www/nextcloud/lib/private/AppFramework/Http/Dispatcher.php","line":169,"function":"mailbox","class":"OCA\\Mail\\Controller\\PageController","type":"->","args":[0]},{"file":"/var/www/nextcloud/lib/private/AppFramework/Http/Dispatcher.php","line":100,"function":"executeController","class":"OC\\AppFramework\\Http\\Dispatcher","type":"->","args":[{"__class__":"OCA\\Mail\\Controller\\PageController"},"mailbox"]},{"file":"/var/www/nextcloud/lib/private/AppFramework/App.php","line":152,"function":"dispatch","class":"OC\\AppFramework\\Http\\Dispatcher","type":"->","args":[{"__class__":"OCA\\Mail\\Controller\\PageController"},"mailbox"]},{"file":"/var/www/nextcloud/lib/private/Route/Router.php","line":309,"function":"main","class":"OC\\AppFramework\\App","type":"::","args":["OCA\\Mail\\Controller\\PageController","mailbox",{"__class__":"OC\\AppFramework\\DependencyInjection\\DIContainer"},{"id":"priority","_route":"mail.page.mailbox"}]},{"file":"/var/www/nextcloud/lib/base.php","line":1008,"function":"match","class":"OC\\Route\\Router","type":"->","args":["/apps/mail/box/priority"]},{"file":"/var/www/nextcloud/index.php","line":37,"function":"handleRequest","class":"OC","type":"::","args":[]}],"File":"/var/www/nextcloud/apps/mail/vendor/pear-pear.horde.org/Horde_Imap_Client/Horde/Imap/Client/Socket.php","Line":4602},"CustomMessage":"Could not load account mailboxes: IMAP error: IMAP error reported by server."},"userAgent":"Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/88.0.4324.182 Safari/537.36","version":"20.0.8.1"}`

Horde.log says no errors. But i can prvide it if needed.

**Comment by ChristophWurst** [comment]
>  IMAP error reported by server.

This …

> Horde.log says no errors

… does not match :wink: 

do you have any `S: NO …` where the server denies a command?

**Comment by small1** [comment]
Not a single one.  This happens when it tries to scan the mailboxes it seems.

**Comment by small1** [comment]
Changing on that i found a NO STATUS failed, no such mailbox

**Comment by small1** [comment]
C: 48 STATUS Public (MESSAGES RECENT UIDNEXT UIDVALIDITY UNSEEN)
S: 48 NO STATUS failed, no such mailbox.
>> Command 48 took 0.5454 seconds.

**Comment by small1** [comment]
And from what i can see the clients never see that Public folder. So i dont know what it does. Probably some kind of special folder

**Comment by small1** [comment]
Mail server is Mailenable ....  Seems like that might have a bases for Public shared folders. Even if the user has no shared folder in the account

**Comment by small1** [comment]
Instead of killing the connection if a status on a mailbox occurs can it be filtered in some way as a solution?

**Comment by ChristophWurst** [comment]
That sounds suspiciously related to https://github.com/nextcloud/mail/pull/4318. We didn't backport that one, so you can either try a prerelease of v1.9 or wait until we push it out officially

**Comment by small1** [comment]
Yepp like that one.

I'll try that fix and see.

/Johan

**Comment by small1** [comment]
The fix in #4318 solves my problems!  Awesome! Ill close this issue
