### ISSUE TITLE
Message source not scrollable in Safari

### ISSUE THREAD

**Issue by LukasReschke** [nextcloud/mail#4645]
### Expected behavior

Being able to scroll the message source.

### Actual behavior

Can't scroll the message source. It's impossible to scroll and view more.

### Mail app

c.nc.c

#### Client configuration
**Browser:** Safari

**Operating system:** 14.0.3

**Comment by bendilobi** [comment]
Same issue on Chromium 88.0.4324.182 (ubuntu snap)

**Comment by ChristophWurst** [comment]
we had that before: https://github.com/nextcloud/mail/issues/3532

@StCyr wanna have a look? :)
