### ISSUE TITLE
Draft mail shows up in inbox folder but not in draft folder

### ISSUE THREAD

**Issue by Nick-Git2** [nextcloud/mail#4653]
### Expected behavior
Draft mail should show up and should be saved in draft folder. 

### Actual behavior
A newly composed mail (draft) is not saved in the draft folder but in the inbox folder

### Mail app

**Mail app version:** (see apps admin page, e.g. 0.5.3)
1.9.1

**Mailserver or service:** (e.g. Outlook, Yahoo, Gmail, Exchange,...)

### Server configuration

**Operating system**: (e.g. Debian 8)
Ubuntu 20.04 LTS

**Web server:** (e.g. Apache, Nginx,...)
Apache

**Database:** (e.g. MariaDB, SQLite or PostgreSQL)
MariaDB

**PHP version:** (e.g. 7.0)
7.4
**Nextcloud Version:** (see admin page, e.g. 13.0.2)
20.0.8
#### Client configuration
**Browser:** (e.g. Firefox 48)
FireFox 86
**Operating system:** (e.g. Arch Linux)
Windows 10

**Comment by ChristophWurst** [comment]
which mailbox did you select for drafts in your account settings?

**Comment by Nick-Git2** [comment]
Inbox was selected and I didn't know that. Apologies for the false alarm! :-|
