### ISSUE TITLE
Additional signature is appended to the mail each time draft is accessed

### ISSUE THREAD

**Issue by Nick-Git2** [nextcloud/mail#4654]
### Expected behavior
Signature should be added to the mail only once which is when the e-mail is created

### Actual behavior
each time the draft mail is accessed the signature is added to the mail again

### Mail app

**Mail app version:** (see apps admin page, e.g. 0.5.3)
1.9.1
**Mailserver or service:** (e.g. Outlook, Yahoo, Gmail, Exchange,...)

### Server configuration

**Operating system**: (e.g. Debian 8)
Ubuntu 20.04 LTS
**Web server:** (e.g. Apache, Nginx,...)
Apache
**Database:** (e.g. MariaDB, SQLite or PostgreSQL)
MariaDB
**PHP version:** (e.g. 7.0)
7.4
**Nextcloud Version:** (see admin page, e.g. 13.0.2)
20.0.8
#### Client configuration
**Browser:** (e.g. Firefox 48)
Firefox 86
**Operating system:** (e.g. Arch Linux)
Windows 10

**Comment by ChristophWurst** [comment]
thanks for the report @Nick-Git2.

This isn't quite the same but yet similar to https://github.com/nextcloud/mail/issues/1660. @kesselb maybe you can keep this ticket in mind while you fix the signature switching during composition and then we can possibly solve this bug in a follow-up change.
