### ISSUE TITLE
Error 500 when forwarding message with image inside

### ISSUE THREAD

**Issue by grubshka** [nextcloud/mail#4656]
Hello,

If I try to forward a message containing an image.
I send me a message in a mail client, inserting an image from my computer in the body.
The image is sent as an attachment.
In Nextcloud mail app, I try to forward the message.

### Expected behavior
Message should be sent

### Actual behavior
Error 500.

Here's the log from the nextcloud log file : 

`{"reqId":"9WlJrxIOIowS2XSfYS42","level":3,"time":"2021-03-03T22:07:41+01:00","remoteAddr":"82.249.70.72","user":"xxxx@yyyy.com","app":"mail","method":"POST","url":"/apps/mail/api/accounts/6/send","message":{"Exception":"Exception","Message":"Argument 2 passed to OCA\\Mail\\Model\\Message::addRawAttachment() must be of the type string, null given, called in /usr/local/share/nextcloud/current/apps/mail/lib/Service/MailTransmission.php on line 399","Code":0,"Trace":[{"file":"/usr/local/share/nextcloud/current/lib/private/AppFramework/App.php","line":152,"function":"dispatch","class":"OC\\AppFramework\\Http\\Dispatcher","type":"->","args":[{"class":"OCA\\Mail\\Controller\\AccountsController"},"send"]},{"file":"/usr/local/share/nextcloud/current/lib/private/Route/Router.php","line":308,"function":"main","class":"OC\\AppFramework\\App","type":"::","args":["OCA\\Mail\\Controller\\AccountsController","send",{"class":"OC\\AppFramework\\DependencyInjection\\DIContainer"},{"action":null,"id":"6","_route":"mail.accounts.send"}]},{"file":"/usr/local/share/nextcloud/current/lib/base.php","line":1008,"function":"match","class":"OC\\Route\\Router","type":"->","args":["/apps/mail/api/accounts/6/send"]},{"file":"/usr/local/share/nextcloud/current/index.php","line":37,"function":"handleRequest","class":"OC","type":"::","args":[]}],"File":"/usr/local/share/nextcloud/current/lib/private/AppFramework/Http/Dispatcher.php","Line":110,"Previous":{"Exception":"TypeError","Message":"Argument 2 passed to OCA\\Mail\\Model\\Message::addRawAttachment() must be of the type string, null given, called in /usr/local/share/nextcloud/current/apps/mail/lib/Service/MailTransmission.php on line 399","Code":0,"Trace":[{"file":"/usr/local/share/nextcloud/current/apps/mail/lib/Service/MailTransmission.php","line":399,"function":"addRawAttachment","class":"OCA\\Mail\\Model\\Message","type":"->","args":["image logo signature.PNG",null]},{"file":"/usr/local/share/nextcloud/current/apps/mail/lib/Service/MailTransmission.php","line":319,"function":"handleForwardedAttachment","class":"OCA\\Mail\\Service\\MailTransmission","type":"->","args":[{"class":"OCA\\Mail\\Account"},{"fileName":"image logo signature.PNG","displayName":"image logo signature.PNG","id":"2.2","messageId":37661,"type":"message-attachment"},{"class":"OCA\\Mail\\Model\\Message"}]},{"file":"/usr/local/share/nextcloud/current/apps/mail/lib/Service/MailTransmission.php","line":151,"function":"handleAttachments","class":"OCA\\Mail\\Service\\MailTransmission","type":"->","args":[{"class":"OCA\\Mail\\Account"},{"class":"OCA\\Mail\\Model\\NewMessageData"},{"class":"OCA\\Mail\\Model\\Message"}]},{"file":"/usr/local/share/nextcloud/current/apps/mail/lib/Controller/AccountsController.php","line":414,"function":"sendMessage","class":"OCA\\Mail\\Service\\MailTransmission","type":"->","args":[{"class":"OCA\\Mail\\Model\\NewMessageData"},null,null,{"id":37756,"class":"OCA\\Mail\\Db\\Message"}]},{"file":"/usr/local/share/nextcloud/current/lib/private/AppFramework/Http/Dispatcher.php","line":169,"function":"send","class":"OCA\\Mail\\Controller\\AccountsController","type":"->","args":[6,"Fwd: YYYYY","coumoi!\n> -------- Message transf\u00e9r\u00e9 -------- Sujet : ZZZZZZZZZ","<xxxx@yyyy.com>","","",false,false,37756,null,[{"fileName":"image logo signature.PNG","displayName":"image logo signature.PNG","id":"2.2","messageId":37661,"type":"message-attachment"}],null]},{"file":"/usr/local/share/nextcloud/current/lib/private/AppFramework/Http/Dispatcher.php","line":100,"function":"executeController","class":"OC\\AppFramework\\Http\\Dispatcher","type":"->","args":[{"class":"OCA\\Mail\\Controller\\AccountsController"},"send"]},{"file":"/usr/local/share/nextcloud/current/lib/private/AppFramework/App.php","line":152,"function":"dispatch","class":"OC\\AppFramework\\Http\\Dispatcher","type":"->","args":[{"class":"OCA\\Mail\\Controller\\AccountsController"},"send"]},{"file":"/usr/local/share/nextcloud/current/lib/private/Route/Router.php","line":308,"function":"main","class":"OC\\AppFramework\\App","type":"::","args":["OCA\\Mail\\Controller\\AccountsController","send",{"class":"OC\\AppFramework\\DependencyInjection\\DIContainer"},{"action":null,"id":"6","_route":"mail.accounts.send"}]},{"file":"/usr/local/share/nextcloud/current/lib/base.php","line":1008,"function":"match","class":"OC\\Route\\Router","type":"->","args":["/apps/mail/api/accounts/6/send"]},{"file":"/usr/local/share/nextcloud/current/index.php","line":37,"function":"handleRequest","class":"OC","type":"::","args":[]}],"File":"/usr/local/share/nextcloud/current/apps/mail/lib/Model/Message.php","Line":220},"CustomMessage":"Argument 2 passed to OCA\\Mail\\Model\\Message::addRawAttachment() must be of the type string, null given, called in /usr/local/share/nextcloud/current/apps/mail/lib/Service/MailTransmission.php on line 399"},"userAgent":"Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:83.0) Gecko/20100101 Firefox/83.0","version":"20.0.4.0"}`

### Mail app

**Mail app version:** 1.9.1
**Mailserver or service:** Postfix + Dovecot

### Server configuration

**Operating system**: Debian 10

**Web server:** Nginx 1.14.2

**Database:** MariaDB 10.3.27

**PHP version:** 7.3

**Nextcloud Version:** 20.0.4

#### Client configuration

**Browser:** Firefox 86

**Operating system:** Debian  Bullseye

**Comment by StCyr** [comment]
I can reproduce the error here. I'll have a look
