### ISSUE TITLE
Cant accept or decline appointments

### ISSUE THREAD

**Issue by Kenarso** [nextcloud/mail#4684]
### Expected behavior
Hello all,
Ubuntu Server 20.04 
via snap nextcloud in version 20.0.7 installed.
mail app in version 1.8.3
Calendar App in version 2.1.3.

Nextcloud is a smtp server deposited to send password resets, etc (admin account, so to speak).

Furthermore, my user account has a mail address.

In the mail app I have created five different mail accounts

The calendar has a calendar

Now to my problems with it:

If I receive an appointment invitation from someone outside the cloud, these situations arise:

Invitation via google calendar -> Appointment is displayed in the mail app as html page, I have the links "Yes", "Maybe" and "No" displayed, as well as an invite.ics (see nc_google_invite)

Invitation via Outlook calendar -> appointment is displayed in the mail app with an empty body (see nc_outlook_invite)

Invitation via OX Calendar -> Appointment is displayed in the mail app with info, but without interactive elements (links, buttons, etc), but contains an invite.ics (see nc_ox_invite)

I can then always import the invite.ics into the calendar, but without any "customization".

From my point of view it is not possible to work productively this way, because I never know from where (system) I get an appointment invitation.

### Mail app

**Mail app version: 1.9.1

**Mailserver or service:** Outlook, open Xchange, Group Office

### Server configuration

**Operating system**: Ubuntu Server 20.04

**Nextcloud Version: 20.07
**apache 2.4
**php 7.3
**My SQL 5,7
** Redis 5.0

#### Client configuration
**Browser:** Firefox, Chromium

**Operating system:** xubuntu 20.04, ChromeOS Version 89.0.4389.76 (Offizieller Build) beta (64-Bit), Windows 10 built ???

**Web server:** apache
![nc_google_invite](https://user-images.githubusercontent.com/9461091/110204502-a769ce00-7e73-11eb-9e22-ba8b62f1038b.png)
![nc_outlook_invite](https://user-images.githubusercontent.com/9461091/110204507-ac2e8200-7e73-11eb-9b67-75e195592d83.png)
![nc_ox_invite](https://user-images.githubusercontent.com/9461091/110204509-b05a9f80-7e73-11eb-8549-4d872ed33a53.png)

**Comment by ChristophWurst** [comment]
This is not a bug but a missing feature. https://github.com/nextcloud/mail/issues/160 seems to describe what you are missing in this application.
