### ISSUE TITLE
Auto allocation mail access

### ISSUE THREAD

**Issue by christophe195** [nextcloud/mail#4687]
### Feature Request

Let admin user's add default settings for groups.

#### Summary

if we add a new staff to our nextcloud system we need to set up ther mail settings for multiple inboxes. It woud be nice if we can add default mail accounts for groups, so when we add a user to the group "sales" they get access to "sales1@domain.com", "sales2@domain.com" and if we add them to group "b&b" they get access to "b&b@domain.com".

Greathings

**Comment by ChristophWurst** [comment]
Isn't that typicall done on an IMAP level? Like in a way that messages are distributed automatically to that group? Alternatively they could use a shared mailbox.

**Comment by christophe195** [comment]
It was a example, we are a youth movement with 30 leaders and have no access to the IMAP settings. 

Can we add a (or multiple) shared mailboxes in nextcloud mail?

**Comment by ChristophWurst** [comment]
the mailboxes are shared on the IMAP *server*, not in the IMAP client

**Comment by christophe195** [comment]
I have change some DB code to get one global mail client, it does what we want. Sadley we will not take every update for now.
