### ISSUE TITLE
Mail App not working after DB reset

### ISSUE THREAD

**Issue by nick83972** [nextcloud/mail#4691]
### Expected behavior

I have reset the Mail App(DB) with the Info from [Developer Documentation](https://github.com/nextcloud/mail/blob/master/doc/developer.md) (after I had to use a backup for Nextcloud which didn't include Mail App, but DB had still Mail Tables etc.) and reinstalled it via the App Store. So everything should work fine again.

### Actual behavior

The Mail Account Creation works and I can see the List of Mails on the Left. But if I click on one of the Mails the Text isn't loaded.
It is stuck with te loading circle.

This is in the Logs: 

Doctrine\DBAL\Exception\TableNotFoundException: An exception occurred while executing a query: SQLSTATE[42S02]: Base table or view not found: 1146 Table 'nextcloud.oc_mail_trusted_senders' doesn't exist

It seems that the App isn't creating all the tables needed at installation.
### Mail app

**Mail app version:** (see apps admin page, e.g. 0.5.3)
Mail App Version: 1.9.1
**Mailserver or service:** (e.g. Outlook, Yahoo, Gmail, Exchange,...)
Mailbox.org

### Server configuration

**Operating system**: (e.g. Debian 8)
Docker
**Web server:** (e.g. Apache, Nginx,...)
Apache
**Database:** (e.g. MariaDB, SQLite or PostgreSQL)
MariaDB
**PHP version:** (e.g. 7.0)
7.4.16
**Nextcloud Version:** (see admin page, e.g. 13.0.2)
21.0.0
#### Client configuration
**Browser:** (e.g. Firefox 48)
Firefox 86.0
**Operating system:** (e.g. Arch Linux)
Linux Mint

**Comment by miaulalala** [comment]
HI @nick83972 , what happens when you run occ upgrade in the command line? Looks like the migrations haven't run properly.

**Comment by nick83972** [comment]
Hi @miaulalala , If I just use the occ upgrade command I get „Nextcloud is already latest Version“ back. 
But it doesn’t change anything.

**Comment by ChristophWurst** [comment]
could you inspect the oc_migrations table with all mail related entries?

**Comment by nick83972** [comment]
Yes, it has 29 entries with app = "mail" in it do you need a screenshot ?

**Comment by ChristophWurst** [comment]
yes please

**Comment by nick83972** [comment]
![Screenshot from 2021-03-08 11-57-59](https://user-images.githubusercontent.com/40697080/110312646-a4064c00-8005-11eb-807e-280a86e9b24e.png)

**Comment by miaulalala** [comment]
The migration that creates the oc_mail_trusted_senders table is the entry: 1080Date20201119084820, which seems to have run.

What happens when you reset the app again? Do you run into the same issue?

**Comment by ChristophWurst** [comment]
did you have any error during the previous installation? did you resume the installation after such an error perhaps?

**Comment by nick83972** [comment]
Yes I had one error after I installed the App (after the Reset) was also a DB related error. But i was able to install by reloading and trying to install again. I will reset the app (DB) again later when I have time and report how it was going and what the issue says if it comes up again.

Should i first remove the app and then the tables in the db or the other way around ?

**Comment by ChristophWurst** [comment]
> Yes I had one error after I installed the App (after the Reset) was also a DB related error. But i was able to install by reloading and trying to install again.

Good to know :)

Then this might be related to https://github.com/nextcloud/server/pull/25924.

It's not unlikely that you run into the same DB error again. Please capture logs and output this time and share it with us.

**Comment by nick83972** [comment]
Hi I have reset the DB again. And tried to install the Mail APP afterwards via "APP's".
Here is the screenshot with the error that comes up:
![Screenshot from 2021-03-10 22-37-31](https://user-images.githubusercontent.com/40697080/110701388-66fead00-81f1-11eb-8b7a-24cdc3d308ee.png)

Those are the Errors I can see in the Nextcloud Log:

![Screenshot from 2021-03-10 22-41-11](https://user-images.githubusercontent.com/40697080/110701664-c361cc80-81f1-11eb-93c3-39092b287e8c.png)

Also, this seems related :

![Screenshot from 2021-03-10 22-42-56](https://user-images.githubusercontent.com/40697080/110701915-176cb100-81f2-11eb-8667-363dca0d2b5d.png)

I can also send you the nextcloud.log but only in a private (not sure if usernames etc. could be exposed) way, if needed.

**Comment by ChristophWurst** [comment]
did you actually clean up the oc_mail_classifiers table before the installation?

**Comment by nick83972** [comment]
Yes I have  removed all tables that are listed on the dev site.

But if I want to remove this table it wasn’t even created with the installation so there is nothing to remove.

**Comment by miaulalala** [comment]
Could be a possible issue with the way tables are handled. Are you using InnoDB? If you're using innodb_file_per_table, check the data directory to make sure you have both an .frm file and .ibd file for the table in question. If it's MYISAM, there should be a .frm, .MYI and a .MYD file.
