### ISSUE TITLE
All new emails are presented with "me" as sender

### ISSUE THREAD

**Issue by BelIblis31** [nextcloud/mail#4694]
### Expected behavior
Sender listed for every email should be the mail sender.

### Actual behavior
Since the last updated 1.9.1 only new emails are presented as sent by me.
Which means all new emails received has one expeditor which is myself.
This is not an email issue because if I look at them from mobile app or another web app all is normal.

Issue seems only related to the way to display emails. If I try to answer an email all is ok: I'm the sender of the answer and the original sender is the recipient.

### Mail app

**Mail app version:** 1.9.1

**Mailserver or service:** IMAP with OVH servers

### Server configuration

**Operating system**: ADM 3.5.4.RE11 (Asustor NAS)

**Web server:** I guess it is Apache

**Database:** MariaDB

**PHP version:** 7.0

**Nextcloud Version:** 20.0.0.8

#### Client configuration
**Browser:** Firefox 86

**Operating system:** Windows 10

**Comment by ChristophWurst** [comment]
> Issue seems only related to the way to display emails. If I try to answer an email all is ok: I'm the sender of the answer and the original sender is the recipient.

Another thing to please check: if one of those wrong emails is open in the browser, you should see the numeric ID in the URL, something like */thread/12345*. Try to look up sender/recipients of that message with `SELECT * FROM oc_mail_recpipients where message_id=12345` in the DB and share the (redacted) output with us. I'm curious if the data is already inserted wrongly or this is just displayed wrong on the front-end.

**Comment by BelIblis31** [comment]
Well this is surprising.
I used the last email received id (799) #here:

`localhost/MariaDB/oc_mail_recipients/		https://www.xxx/phpmyadmin/db_sql.php?db=MariaDB
 Affichage des lignes 0 -  5 (total de 6, traitement en 0.0017 seconde(s).)

SELECT * FROM oc_mail_recipients where message_id=799


id	message_id	type	label	email	
1603	799	0	Vincent XXXX ww@ww.com	
1604	799	1	ASUSTOR	esupport@asustor.com	
1767	799	0	Christoph Wurst	notifications@github.com	
1768	799	1	nextcloud/mail	mail@noreply.github.com	
1769	799	2	BelIblis31	w@ww.com	
1770	799	2	Author	author@noreply.github.com	
`

**Comment by ChristophWurst** [comment]
The meaning of the `type` is defined at https://github.com/nextcloud/mail/blob/a8c974a0910948b04c4dc3639bb67840e4478ffb/lib/Address.php#L36-L39.

So that looks fine, right? How's this displayed in the UI?

**Comment by BelIblis31** [comment]
Here is what I see.
Basically starting last updated 3 days ago all emails are now flagged from me.

![image](https://user-images.githubusercontent.com/80246132/110300534-43701280-7ff7-11eb-8dae-05c0e05452c0.png)

**Comment by ChristophWurst** [comment]
This is possibly related to https://github.com/nextcloud/mail/issues/4412 as I see that your Mariadb is also not the latest.

**Comment by BelIblis31** [comment]
Yes it looks similar.
As I use the the official Nextcloud implementation from Asustor and MariaDB I need to wait for the update to be released by them.
I will send them an email.

**Comment by BelIblis31** [comment]
Asustor is aware of the issue and is working on MariaDB update.
I will confirm if it is solved once they publish the update.

**Comment by miaulalala** [comment]
@BelIblis31 any updates?

**Comment by BelIblis31** [comment]
Well, I am now on Nextcloud 22.2 and MariaDB 10.5.8.r51 and the problem is solved.
I am not sure which update solved it as I was using an external email client since the issue.

**Comment by GretaD** [comment]
Thank you @BelIblis31. Im closing this ticket and see if somebody else will face it again.
