### ISSUE TITLE
More formatting options

### ISSUE THREAD

**Issue by zipwerk** [nextcloud/mail#4707]
**More formatting options**

The possibility to add a color and a background color to the text, to set ship sizes in px, to set links and maybe even to choose different fonts are certainly great options that should not be missing in any modern mail program.

**Comment by ChristophWurst** [comment]
Are you familier with js development? This change is mostly about turning on CKEditor features or adding more of its plugins.

**Comment by zipwerk** [comment]
Okay, I see. Unfortunately I haven't had that much experience with Javascript yet - only with HTML/CSS.

**Comment by ChristophWurst** [comment]
No problem.

**Comment by edosmedia** [comment]
which is the file that controls the signature for email so try to put CKEDITOR in some way

**Comment by ChristophWurst** [comment]
https://github.com/nextcloud/mail/blob/master/src/components/TextEditor.vue
