### ISSUE TITLE
Parts of html formated mails disappear

### ISSUE THREAD

**Issue by ghost** [nextcloud/mail#471]
### Steps to reproduce
1. select/open an html formated mail
2. scroll / navigate to the top of the mail
3. compare the mail: thunderbird vs. mail app

### Expected behaviour
Navigation section should appear at the top of the mail
![grafik](https://user-images.githubusercontent.com/20593693/29740646-a7f4d0f0-8a5b-11e7-9416-7eeb07db6f52.png)

### Actual behaviour
The navigation panel disappear in the mail app in both: in the right panel as well in a new tab/window:
![grafik](https://user-images.githubusercontent.com/20593693/29740657-e4e96886-8a5b-11e7-97d1-9afa877aad4b.png)
![grafik](https://user-images.githubusercontent.com/20593693/29740664-0639d6b0-8a5c-11e7-943f-c252cc3afde1.png)

### Mail app

**Mail app version:** 0.7.0

**Mailserver or service:** all-inklö.com || kasserver.com

**Transport security - IMAP:** STARTTLS

**Transport security - SMTP:** STARTTLS

**Number of accounts:** 1

### Server configuration

root@nc:-# sudo -u www-data php /var/www/nextcloud/occ app:list
Enabled:

    admin_audit: 1.2.0
    bruteforcesettings: 1.0.2
    calendar: 1.5.3
    contacts: 1.5.3
    dav: 1.3.0
    federatedfilesharing: 1.2.0
    files: 1.7.2
    files_clipboard: 0.6.4
    files_downloadactivity: 1.1.1
    files_pdfviewer: 1.1.1
    files_sharing: 1.4.0
    files_texteditor: 2.4.1
    files_trashbin: 1.2.0
    files_videoplayer: 1.1.0
    gallery: 17.0.0
    keeweb: 0.4.0
    logreader: 2.0.0
    lookup_server_connector: 1.0.0
    mail: 0.7.0
    nextcloud_announcements: 1.1
    notes: 2.3.1
    notifications: 2.0.0
    oauth2: 1.0.5
    password_policy: 1.2.2
    provisioning_api: 1.2.0
    rainloop: 5.0.1
    sharebymail: 1.2.0
    theming: 1.3.0
    twofactor_backupcodes: 1.1.1
    updatenotification: 1.2.0
    workflowengine: 1.2.0
    Disabled:
    activity
    comments
    encryption
    federation
    files_external
    files_versions
    firstrunwizard
    serverinfo
    survey_client
    systemtags
    twofactor_totp
    user_external
    user_ldap

The content of config/config.php:
root@nc:-# sudo -u www-data php /var/www/nextcloud/occ config:list system
{
"system": {
"instanceid": "oc84hxlnpsu0",
"passwordsalt": "REMOVED SENSITIVE VALUE",
"secret": "REMOVED SENSITIVE VALUE",
"trusted_domains": [
"xyz.c-rieger.de",
"192.168.2.117"
],
"datadirectory": "/ncdata",
"overwrite.cli.url": "https://xyz.c-rieger.de",
"dbtype": "mysql",
"version": "12.0.2.0",
"dbname": "nextcloud",
"dbhost": "localhost",
"dbport": "",
"dbtableprefix": "xyz_",
"mysql.utf8mb4": true,
"dbuser": "REMOVED SENSITIVE VALUE",
"dbpassword": "REMOVED SENSITIVE VALUE",
"installed": true,
"htaccess.RewriteBase": "/",
"overwriteprotocol": "https",
"loglevel": 2,
"logtimezone": "Europe/Berlin",
"logfile": "/var/nc_data/nextcloud.log",
"log_rotate_size": 104857600,
"cron_log": true,
"filesystem_check_changes": 1,
"quota_include_external_storage": false,
"knowledgebaseenabled": false,
"memcache.local": "\OC\Memcache\APCu",
"filelocking.enabled": "true",
"memcache.locking": "\OC\Memcache\Redis",
"redis": {
"host": "/var/run/redis/redis.sock",
"port": 0,
"timeout": 0
},
"maintenance": false,
"theme": "",
"enable_previews": true,
"enabledPreviewProviders": [
"OC\Preview\PNG",
"OC\Preview\JPEG",
"OC\Preview\GIF",
"OC\Preview\BMP",
"OC\Preview\XBitmap",
"OC\Preview\Movie",
"OC\Preview\PDF",
"OC\Preview\MP3",
"OC\Preview\TXT",
"OC\Preview\MarkDown"
],
"mail_from_address": "xyz",
"mail_smtpmode": "smtp",
"mail_smtpauthtype": "LOGIN",
"mail_domain": "c-rieger.de",
"mail_smtpsecure": "tls",
"mail_smtpauth": 1,
"mail_smtphost": "xyz.kasserver.com",
"mail_smtpport": "587",
"mail_smtpname": "REMOVED SENSITIVE VALUE",
"mail_smtppassword": "REMOVED SENSITIVE VALUE"
}
}
Client configuration

Browser: Firefox 55.03 x64 / Microsoft Edge

Operating system:
W10 Prof / Ubuntu 16.04.3 LTS XENIAL x64

**Comment by Gomez** [comment]
Was it working in version 0.6?

**Comment by riegercloud** [comment]
I just installed 0.6.4 on NC12.0.2 and the behaviour is the same:
![grafik](https://user-images.githubusercontent.com/20593693/29782051-6f5a2346-8c1b-11e7-92f3-83cedd2a0d51.png)

**Comment by alexanderdd** [comment]
The worst about this issue is that emails sent from nextcloud itself, e.g. information about password change, are formatted weirdly too.

=(

**Comment by ChristophWurst** [comment]
I'm closing this ticket because it hasn't received any updates in a long time. If this is still relevant, feel free to re-open or file a new ticket.

Thank you.
