### ISSUE TITLE
l10n: Correction of text strings

### ISSUE THREAD

**Issue by Valdnet** [nextcloud/mail#4720]
In my opinion, the text strings in the app settings need to be rebuilt:

![obraz](https://user-images.githubusercontent.com/47037905/110604597-8ca39c00-8188-11eb-8ad1-f193d7bd268e.png)

https://github.com/nextcloud/mail/blob/b8b1830ffe840c07b4ca031e383288b9d9134468/src/components/AppSettingsMenu.vue#L79
https://github.com/nextcloud/mail/blob/b8b1830ffe840c07b4ca031e383288b9d9134468/src/components/AppSettingsMenu.vue#L82

In the first text string, you must break it apart. Remove the period after "Allow the app to collect data about your interactions", then add the rest as the function description.
In the text string "Put my text to the bottom of a reply instead of on top of it." you must remove the dot at the end of the sentence as this is the name of the setting.

 In my opinion, they should be as follows:

- Allow the app to collect data about your interactions
  Based on this data, the app will adapt to your preferences. The data will only be stored locally.

- Use Gravatar and favicon avatars

- Put my text to the bottom of a reply instead of on top of it

### Mail app

**Mail app version:** (see apps admin page, e.g. 0.5.3)
1.9.1

**Comment by ChristophWurst** [comment]
This has been split

![image](https://github.com/nextcloud/mail/assets/1374172/52f65724-7dca-48df-98fa-4378e0835976)
