### ISSUE TITLE
server error

### ISSUE THREAD

**Issue by stanelie** [nextcloud/mail#474]
### Steps to reproduce
1. create an email and push SEND
2.
3.

### Expected behaviour

Message should be sent without issues
### Actual behaviour
The Nextcloud web interface produces a "server error" notification at the top of the page for a few seconds. Also, the log shows "Sending mail failed: Error when communicating with the server.". However, the email is still sent out.
### Mail app

**Mail app version:** (see apps admin page)
0.7.0
**Mailserver or service:** (e.g. Outlook, Yahoo, Gmail, Exchange,...)
Exchange 2010
**Transport security - IMAP:** (None, SSL, TLS, STARTTLS) 
startls
**Transport security - SMTP:** (None, SSL, TLS, STARTTLS)
startls
**Number of accounts:**
1
**Mail app version build date:** (only if you are using a Nightly Build)

### General server configuration

**Operating system:** Linux cloud 4.4.0-89-generic #112-Ubuntu SMP Mon Jul 31 19:38:41 UTC 2017 x86_64

**Web server:** Apache (apache2handler)

**Database:** mysql 5.7.19

**PHP version:** 7.0.22-0ubuntu0.16.04.1
<details>
        <summary>PHP-modules loaded</summary>

```
 - Core
 - date
 - libxml
 - openssl
 - pcre
 - zlib
 - filter
 - hash
 - Reflection
 - SPL
 - session
 - standard
 - apache2handler
 - mysqlnd
 - PDO
 - xml
 - bz2
 - calendar
 - ctype
 - curl
 - dom
 - mbstring
 - fileinfo
 - ftp
 - gd
 - gettext
 - iconv
 - igbinary
 - imagick
 - intl
 - json
 - ldap
 - exif
 - mcrypt
 - mysqli
 - pdo_mysql
 - Phar
 - posix
 - readline
 - redis
 - shmop
 - SimpleXML
 - smbclient
 - sockets
 - sysvmsg
 - sysvsem
 - sysvshm
 - tokenizer
 - wddx
 - xmlreader
 - xmlwriter
 - xsl
 - zip
 - libsmbclient
 - Zend OPcache
```
</details>

### Nextcloud configuration

**Nextcloud version:** 12.0.2 - 12.0.2.0

**Updated from an older Nextcloud/ownCloud or fresh install:** Yup

**Where did you install Nextcloud from:**  nextcloud web site

**Are you using external storage, if yes which one:** Array
(
\OC\Files\Storage\Local
\OCA\Files_External\Lib\Storage\SMB
)

**Are you using encryption:** no

**Are you using an external user-backend, if yes which one:** yes
 (LDAP)

<details>
        <summary>Signing status</summary>

```
[]
```
</details>

<details>
        <summary>Enabled apps</summary>

```
 - activity: 2.5.2
 - audioplayer: 2.0.2
 - bruteforcesettings: 1.0.2
 - calendar: 1.5.3
 - comments: 1.2.0
 - contacts: 1.5.3
 - dav: 1.3.0
 - federatedfilesharing: 1.2.0
 - federation: 1.2.0
 - files: 1.7.2
 - files_downloadactivity: 1.1.1
 - files_external: 1.3.0
 - files_pdfviewer: 1.1.1
 - files_reader: 1.0.4
 - files_retention: 1.1.2
 - files_sharing: 1.4.0
 - files_texteditor: 2.4.1
 - files_trashbin: 1.2.0
 - files_versions: 1.5.0
 - files_videoplayer: 1.1.0
 - firstrunwizard: 2.1
 - gallery: 17.0.0
 - issuetemplate: 0.2.2
 - logreader: 2.0.0
 - lookup_server_connector: 1.0.0
 - mail: 0.7.0
 - nextcloud_announcements: 1.1
 - notes: 2.3.1
 - notifications: 2.0.0
 - oauth2: 1.0.5
 - ojsxc: 3.3.0
 - password_policy: 1.2.2
 - provisioning_api: 1.2.0
 - quota_warning: 1.0.1
 - radio: 0.6.0
 - richdocuments: 1.12.34
 - serverinfo: 1.2.0
 - sharebymail: 1.2.0
 - socialsharing_email: 1.0.1
 - spreed: 2.0.1
 - survey_client: 1.0.0
 - systemtags: 1.2.0
 - tasks: 0.9.5
 - twofactor_backupcodes: 1.1.1
 - updatenotification: 1.2.0
 - user_ldap: 1.2.1
 - workflowengine: 1.2.0
```
</details>

<details>
        <summary>Disabled apps</summary>

```
 - admin_audit
 - apporder
 - encryption
 - theming
 - user_external
```
</details>

<details>
        <summary>Content of config/config.php</summary>

```
{
    "instanceid": "oc7ckidgggwo",
    "passwordsalt": "***REMOVED SENSITIVE VALUE***",
    "secret": "***REMOVED SENSITIVE VALUE***",
    "trusted_domains": [
        "192.168.0.5",
        "***REMOVED SENSITIVE VALUE***",
        "***REMOVED SENSITIVE VALUE***",
        "***REMOVED SENSITIVE VALUE***"
    ],
    "datadirectory": "\/var\/www\/nextcloud\/data",
    "overwrite.cli.url": "https:\/\/***REMOVED SENSITIVE VALUE***",
    "dbtype": "mysql",
    "version": "12.0.2.0",
    "dbname": "nextcloud",
    "dbhost": "localhost",
    "dbport": "",
    "dbtableprefix": "oc_",
    "dbuser": "***REMOVED SENSITIVE VALUE***",
    "dbpassword": "***REMOVED SENSITIVE VALUE***",
    "logtimezone": "America\/New_York",
    "installed": true,
    "overwriteprotocol": "https",
    "mail_smtpmode": "smtp",
    "mail_smtphost": "relais.videotron.ca",
    "mail_from_address": "nextcloud",
    "mail_domain": "***REMOVED SENSITIVE VALUE***",
    "theme": "exm",
    "trashbin_retention_obligation": "7,14",
    "memcache.local": "\\OC\\Memcache\\Redis",
    "filelocking.enabled": true,
    "memcache.locking": "\\OC\\Memcache\\Redis",
    "redis": {
        "host": "\/var\/run\/redis\/redis.sock",
        "port": 0,
        "timeout": 0
    },
    "ldapIgnoreNamingRules": false,
    "default_language": "fr",
    "ldapProviderFactory": "\\OCA\\User_LDAP\\LDAPProviderFactory",
    "trusted_proxies": [
        "192.168.0.2"
    ],
    "mail_smtpport": "25",
    "maintenance": false,
    "loglevel": 1
}
```
</details>

<details>
        <summary>LDAP config</summary>

```
With access to your command line run e.g.:
sudo -u www-data php occ ldap:show-config
from within your Nextcloud installation folder

Without access to your command line download the data/owncloud.db to your local
computer or access your SQL server remotely and run the select query:
SELECT * FROM `oc_appconfig` WHERE `appid` = 'user_ldap';

Eventually replace sensitive data as the name/IP-address of your LDAP server or groups.
```
</details>

### Client configuration

**Browser:** Firefox 0.0 

**Operating system:** any

### Logs

<details>
        <summary>Web server error log</summary>

```
Insert your webserver log here
```
</details>

<details>
        <summary>Nextcloud log (data/nextcloud.log)</summary>

```
Insert your Nextcloud log here
```
</details>

<details>
        <summary>Browser log</summary>

```
Insert your browser log here, this could for example include:

a) The javascript console log
b) The network log
c) ...
```
</details>

**Comment by ChristophWurst** [comment]
> Also, the log shows "Sending mail failed: Error when communicating with the server.". However, the email is still sent out.

Wild guess: the app fails to access/create the 'Sent' folder.

**Comment by stanelie** [comment]
If I clic on the "sent" folder, it pulls up my sent emails from the IMAP server. So, I guess it is correctly configured. I could be wrong...

**Comment by methuselah-0** [comment]
Same issue here when I use ldap but not when I use regular users. I had to fix the timeout settings though or else I got the server error message. This is what I configured:
#'app.mail.imaplog.enabled' => true,                                                                                                                                                           
#'app.mail.smtplog.enabled' => true,                                                                                                                                                           
#'app.mail.imap.timeout' => 30,                                                                                                                                                                
#'app.mail.smtp.timeout' => 10,                                                                                                                                                                
#'app.mail.transport' => 'smtp-mail'

**Comment by Scriptkiddi** [comment]
Hey guys I had this issue a while ago, is it possible you are using exim where the mail server returns a message ID on the last command like:
OK --- <message-id>?

**Comment by stanelie** [comment]
My back end is an Exchange 2010 server, using IMAP, so, no exim...

**Comment by stanelie** [comment]
I get this : 
`250 2.6.0 <5ba1c6ea-9c3e-4b0d-bfb3-ad3d506ecc43@hidden.domain> [InternalId=3094] Queued mail for delivery`

**Comment by Scriptkiddi** [comment]
I was running 0.7.6

**Comment by FreeMinded** [comment]
I'm having this issue only when mailing attachments which have some size. It works as expected with small attachements but fails on larger ones. Tested with 55KB (OK) and 650KB/2.2MB (fails)
Mail App Version: 0.7.9

**Comment by Scriptkiddi** [comment]
Hey could it be that your mail server replies something different than normal?
Can you test it over the command line using swaks (http://www.jetmore.org/john/code/swaks/)

**Comment by FreeMinded** [comment]
I did this
./swaks.pl --to receipiant@domain.ch --from sender@otherdomain.ch --server asmtp.mail.mailprovider.ch:587 --auth PLAIN --auth-user sender@otherdomain.ch --attach file.pdf --attach-type application/pdf

I get this 
.... 
-> ------=_MIME_BOUNDARY_000_10399--
 -> 
 -> 
 -> .
<-  250 OK id=1eqfCz-000Npr-4t
 -> QUIT
<-  221 asmtp012.mail.mailprovider.ch closing connection
=== Connection closed with remote host.

Mail is sent and delivered successfully. What I noticed is that it takes 12 seconds between 
-> .
<-  250 OK id=1eqfCz-000Npr-4t

Might that be too, long for Nextcloud?
@Scriptkiddi ist that different to normal?

**Comment by ChristophWurst** [comment]
> Might that be too, long for Nextcloud?

Good point. See https://github.com/nextcloud/mail/blob/master/doc/admin.md#imap-timeout. Maybe setting a higher timeout value helps.

**Comment by FreeMinded** [comment]
> Good point. See https://github.com/nextcloud/mail/blob/master/doc/admin.md#imap-timeout. Maybe setting a higher timeout value helps.
Thanks @ChristophWurst I'll try that and see if it helps. I'm pretty sure it will.

**Comment by dnel** [comment]
I have also seen this issue, increasing the SMTP timeout to 10 seconds resolved the problem for me.
