### ISSUE TITLE
Internal Server Error while accessing mail app

### ISSUE THREAD

**Issue by oljask** [nextcloud/mail#4745]
Mail app never worked for me on this installation. But since it is working nice and fast on other near identical installation, I want to find the cause of the problem.

I have dropped mail tables as it is described in DEV docs. Reinstalled and enabled mail app. Then I filled up required configuration fields. But when when I click mail app I get Internal Server Error.

> {"reqId":"LjOwxHGMujmKHPeNTB6j","level":3,"time":"2021-03-11T21:01:27+00:00","remoteAddr":"192.168.2.22","user":"oljas","app":"index","method":"GET","url":"/apps/mail/","message":{"Exception":"Exception","Message":"substr() expects parameter 1 to be string, bool given","Code":0,"Trace":[{"file":"/usr/local/www/nextcloud/lib/private/AppFramework/App.php","line":157,"function":"dispatch","class":"OC\\AppFramework\\Http\\Dispatcher","type":"->"},{"file":"/usr/local/www/nextcloud/lib/private/Route/Router.php","line":302,"function":"main","class":"OC\\AppFramework\\App","type":"::"},{"file":"/usr/local/www/nextcloud/lib/base.php","line":993,"function":"match","class":"OC\\Route\\Router","type":"->"},{"file":"/usr/local/www/nextcloud/index.php","line":37,"function":"handleRequest","class":"OC","type":"::"}],"File":"/usr/local/www/nextcloud/lib/private/AppFramework/Http/Dispatcher.php","Line":159,"Previous":{"Exception":"TypeError","Message":"substr() expects parameter 1 to be string, bool given","Code":0,"Trace":[{"file":"/usr/local/www/nextcloud/lib/private/Security/Crypto.php","line":95,"function":"substr"},{"file":"/usr/local/www/nextcloud/apps-pkg/mail/lib/Service/Provisioning/Manager.php","line":192,"function":"encrypt","class":"OC\\Security\\Crypto","type":"->","args":["*** sensitive parameters replaced ***"]},{"file":"/usr/local/www/nextcloud/apps-pkg/mail/lib/Http/Middleware/ProvisioningMiddleware.php","line":75,"function":"updatePassword","class":"OCA\\Mail\\Service\\Provisioning\\Manager","type":"->","args":["*** sensitive parameters replaced ***"]},{"file":"/usr/local/www/nextcloud/lib/private/AppFramework/Middleware/MiddlewareDispatcher.php","line":98,"function":"beforeController","class":"OCA\\Mail\\Http\\Middleware\\ProvisioningMiddleware","type":"->"},{"file":"/usr/local/www/nextcloud/lib/private/AppFramework/Http/Dispatcher.php","line":119,"function":"beforeController","class":"OC\\AppFramework\\Middleware\\MiddlewareDispatcher","type":"->"},{"file":"/usr/local/www/nextcloud/lib/private/AppFramework/App.php","line":157,"function":"dispatch","class":"OC\\AppFramework\\Http\\Dispatcher","type":"->"},{"file":"/usr/local/www/nextcloud/lib/private/Route/Router.php","line":302,"function":"main","class":"OC\\AppFramework\\App","type":"::"},{"file":"/usr/local/www/nextcloud/lib/base.php","line":993,"function":"match","class":"OC\\Route\\Router","type":"->"},{"file":"/usr/local/www/nextcloud/index.php","line":37,"function":"handleRequest","class":"OC","type":"::"}],"File":"/usr/local/www/nextcloud/lib/private/Security/Crypto.php","Line":95},"CustomMessage":"--"},"userAgent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:86.0) Gecko/20100101 Firefox/86.0","version":"21.0.0.18","id":"604a85430c059"}

Other odd behavior is that a cannot modify app settings anymore. They just stay the same as in first time setup.

> {"reqId":"DCmR8GdckN7sPfKppNLz","level":3,"time":"2021-03-11T21:01:51+00:00","remoteAddr":"192.168.2.22","user":"oljas","app":"PHP","method":"DELETE","url":"/apps/mail/api/settings/provisioning","message":{"Exception":"Error","Message":"hash_hkdf(): Input keying material cannot be empty at /usr/local/www/nextcloud/lib/private/Security/Crypto.php#94","Code":0,"Trace":[{"function":"onError","class":"OC\\Log\\ErrorHandler","type":"::"},{"file":"/usr/local/www/nextcloud/lib/private/Security/Crypto.php","line":94,"function":"hash_hkdf"},{"file":"/usr/local/www/nextcloud/apps-pkg/mail/lib/Service/Provisioning/Manager.php","line":192,"function":"encrypt","class":"OC\\Security\\Crypto","type":"->","args":["*** sensitive parameters replaced ***"]},{"file":"/usr/local/www/nextcloud/apps-pkg/mail/lib/Http/Middleware/ProvisioningMiddleware.php","line":75,"function":"updatePassword","class":"OCA\\Mail\\Service\\Provisioning\\Manager","type":"->","args":["*** sensitive parameters replaced ***"]},{"file":"/usr/local/www/nextcloud/lib/private/AppFramework/Middleware/MiddlewareDispatcher.php","line":98,"function":"beforeController","class":"OCA\\Mail\\Http\\Middleware\\ProvisioningMiddleware","type":"->"},{"file":"/usr/local/www/nextcloud/lib/private/AppFramework/Http/Dispatcher.php","line":119,"function":"beforeController","class":"OC\\AppFramework\\Middleware\\MiddlewareDispatcher","type":"->"},{"file":"/usr/local/www/nextcloud/lib/private/AppFramework/App.php","line":157,"function":"dispatch","class":"OC\\AppFramework\\Http\\Dispatcher","type":"->"},{"file":"/usr/local/www/nextcloud/lib/private/Route/Router.php","line":302,"function":"main","class":"OC\\AppFramework\\App","type":"::"},{"file":"/usr/local/www/nextcloud/lib/base.php","line":993,"function":"match","class":"OC\\Route\\Router","type":"->"},{"file":"/usr/local/www/nextcloud/index.php","line":37,"function":"handleRequest","class":"OC","type":"::"}],"File":"/usr/local/www/nextcloud/lib/private/Log/ErrorHandler.php","Line":92,"CustomMessage":"--"},"userAgent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:86.0) Gecko/20100101 Firefox/86.0","version":"21.0.0.18","id":"604a85430c018"}

### Expected behavior
Mail app should provision accounts and show INBOX

### Actual behavior
Internal Server Error

### Mail app

**Mail app version:** 1.9.1

**Mailserver or service:** Dovecot

### Server configuration

**Operating system:** FreeBSD 12.2

**Web server:**  Nginx

**Database:** MariaDB

**PHP version:** 7.4

**Nextcloud Version:** 21.0.0

#### Client configuration
**Browser:**  Firefox 86

**Operating system:** Windows 10

**Comment by miaulalala** [comment]
Hi olijask, 

can you have a look at your `config/config.php` to see if the value for `secret` is defined?

> Then I filled up required configuration fields.

Does that mean you are trying to create an email account or setting up Nextcloud Server?

**Comment by oljask** [comment]
>  `secret` is defined?

No, secret undefined.
If that is the case, should I generate it somehow?

> Does that mean you are trying to create an email account or setting up Nextcloud Server?

I am trying to create email accounts for all users in "Groupware Settings". I can fill settings one first time only, after that no modifications apply.

**Comment by ChristophWurst** [comment]
Whoopsie. There should be a secret, yes.

It's by default a 48 byte random string. Use https://duckduckgo.com/?t=ffab&q=random+password+48&ia=answer or similar to generate yours. I think that should fix the problem.

If you had a secret before and it was lost I would highly suggest to check your backups for the old value. Changing the secret isn't actually supported and can therefore cause other trouble.

**Comment by TtuxX** [comment]
Also just had this issue on my NC instance.

My instance is pretty old (installed around ownCloud 4 and upgraded through years). I searched few backups for `secret` variable in `config.php` file and have not found any, which seems pretty strange to me, and I also never saw any warning from the Nextcloud admin self-ckecks page regarding this variable that seems critical.

I added a `secret` variable to my `config.php` file as per Christoph's instructions and it is working so far but:
- All users have to login again from their NC-connected applications,
- As `secret` variable is used to encrypt data, Nextcloud Passwords app no longer works and needs that:
  - You remove the newly-added `secret` entry to be able to access your passwords,
  - Once you can access them, you export them (database backup from the app Backup/Restore section),
  - You delete everything from inside the Danger zone section of the Passwords app,
  - You restore the new `secret` entry again and login again on your instance,
  - You restore the backup, and you're done. :)
  
  Be careful not to blindly add this variable if you have files encryption enabled.

**Comment by oljask** [comment]
@TtuxX 
Thank you! My installation grows from owncloud 7 or maybe 6. And I also don't recall deleting 'secret'. I`ve tried to just define it as suggested by @ChristophWurst . But after that I got Internal Server Error on login. Glad it worked out for you. Passwords and file encryption is not enabled on this setup. If it worked for you, I hope it will work for me. I will try again with disabling other apps.

**Comment by oljask** [comment]
@ChristophWurst @TtuxX 
Added 'secret', truncated table oc_storage_credentials.
Now Mail app works flawlessly.
Thank you!

**Comment by alioneuquechilo** [comment]
Hi @TtuxX, @oljask.. I have the secret parameter configured since always but I also get the error of internal error server. any suggestion?

**Comment by TtuxX** [comment]
Hi @alioneuquechilo ! Could you please share your error log message?

**Comment by koehn** [comment]
I reset the blank secret parameter (also an old owncloud-> nextcloud server) and it appears to blow up TOTP as well. I needed to disable it by updating `oc_twofactor_providers`.

It might make sense to detect this in Settings -> Administration -> Overview and recommend that admins fix it.
