### ISSUE TITLE
Unable to connect to imap/s, no meaningful error message

### ISSUE THREAD

**Issue by lemmy04** [nextcloud/mail#4769]
I'm trying to set up a mail account which uses imaps and smtps with a "private" certificate, i.e. issued by my own CA and not signed by any "public" CA.

### Expected behavior
It should either work, or give me a meaningful warning (something like "SSL certificate issued by an unknown authority"), and preferrably should give me the option to look at details, and then decide to trust or not.

### Actual behavior
"Unexpected error connecting to mail server", no further information.
And in the log files:
{"reqId":"aSo4fBjUT99VBddRK2r7","level":3,"time":"2021-03-16T07:23:38+00:00","remoteAddr":"2003:cf:9f3c:5e2e:6a05:caff:fe1b:695f","user":"mathias","app":"mail","method":"POST","url":"/index.php/apps/mail/api/accounts","message":"Creating account failed: Connection to IMAP at eregion.kicks-ass.net:993 failed. Error connecting to mail server.","userAgent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:86.0) Gecko/20100101 Firefox/86.0","version":"21.0.0.18"}

which also didn't help.

As soon as I used the **internal** address which is also open for imap and smtp without SSL/TLS it worked... So it's most likely my untrusted certificate.

### Mail app
1.9.3

**Mailserver or service:** (e.g. Outlook, Yahoo, Gmail, Exchange,...)
cyrus imap 2.4.19 on openSUSE 15.2

### Server configuration

**Operating system**: openSUSE 15.2

**Web server:** apache 2.4.43

**Database:** mariadb 10.4.17

**PHP version:** (e.g. 7.0)

**Nextcloud Version:** nextcloud 21.0.0

#### Client configuration
**Browser:** Firefox 86.0

**Operating system:** Windows 10

**Comment by ChristophWurst** [comment]
Dup of https://github.com/nextcloud/mail/issues/3006 and https://github.com/nextcloud/mail/issues/2785
