### ISSUE TITLE
Issues with ransomware protection

### ISSUE THREAD

**Issue by derritter88** [nextcloud/mail#4774]
### Expected behavior
Everything should work

### Actual behavior
I get log entries in my Nextcloud log (see below)

### Mail app

**Mail app version:** 1.9.3

**Mailserver or service:** N/A

### Server configuration

**Operating system**: Ubuntu 20.04

**Web server:** Apache

**Database:** PostgreSQL

**PHP version:** 7.4-FPM

**Nextcloud Version:** 21.0.0

#### Client configuration
**Browser:** 86.0.1

**Operating system:** Windows 10 20H2

**Comment by derritter88** [comment]
Log entry:
Error: include(): Failed opening 'ransomware_protection/personal.php' for inclusion (include_path='/var/www/cloud/apps/news/vendor/pear/net_url2:/var/www/cloud/apps/mail/vendor/pear-pear.horde.org/Horde_Crypt_Blowfish:/var/www/cloud/apps/mail/vendor/pear-pear.horde.org/Horde_Date:/var/www/cloud/apps/mail/vendor/pear-pear.horde.org/Horde_Exception:/var/www/cloud/apps/mail/vendor/pear-pear.horde.org/Horde_Idna:/var/www/cloud/apps/mail/vendor/pear-pear.horde.org/Horde_Imap_Client:/var/www/cloud/apps/mail/vendor/pear-pear.horde.org/Horde_ListHeaders:/var/www/cloud/apps/mail/vendor/pear-pear.horde.org/Horde_Mail:/var/www/cloud/apps/mail/vendor/pear-pear.horde.org/Horde_ManageSieve:/var/www/cloud/apps/mail/vendor/pear-pear.horde.org/Horde_Mime:/var/www/cloud/apps/mail/vendor/pear-pear.horde.org/Horde_Nls:/var/www/cloud/apps/mail/vendor/pear-pear.horde.org/Horde_Secret:/var/www/cloud/apps/mail/vendor/pear-pear.horde.org/Horde_Smtp:/var/www/cloud/apps/mail/vendor/pear-pear.horde.org/Horde_Socket_Client:/var/www/cloud/apps/mail/vendor/pear-pear.horde.org/Horde_Stream:/var/www/cloud/apps/mail/vendor/pear-pear.horde.org/Horde_Stream_Filter:/var/www/cloud/apps/mail/vendor/pear-pear.horde.org/Horde_Stream_Wrapper:/var/www/cloud/apps/mail/vendor/pear-pear.horde.org/Horde_Stringprep:/var/www/cloud/apps/mail/vendor/pear-pear.horde.org/Horde_Support:/var/www/cloud/apps/mail/vendor/pear-pear.horde.org/Horde_Text_Filter:/var/www/cloud/apps/mail/vendor/pear-pear.horde.org/Horde_Text_Flowed:/var/www/cloud/apps/mail/vendor/pear-pear.horde.org/Horde_Translation:/var/www/cloud/apps/mail/vendor/pear-pear.horde.org/Horde_Util:/var/www/cloud/3rdparty/pear/archive_tar:/var/www/cloud/3rdparty/pear/console_getopt:/var/www/cloud/3rdparty/pear/pear-core-minimal/src:/var/www/cloud/3rdparty/pear/pear_exception:/var/www/cloud/apps') at /var/www/cloud/lib/private/legacy/OC_App.php#660

**Comment by ChristophWurst** [comment]
what's the relation to Mail?

**Comment by derritter88** [comment]
It appears to be related to Mail app due to log entry


....nclude_path='/var/www/cloud/apps/news/vendor/pear/net_url2:/var/www/cloud/apps/mail/vendor/pear-pear.horde.org/Horde_Crypt_Blowfish:/var/www/cloud/apps/mail/vendor/pear-pear.horde.org/Horde_Date:/var/www/cloud/apps/mail/vendor/pear-pear.ho
.....


That's why I think it's related to Mail

**Comment by ChristophWurst** [comment]
> Failed opening 'ransomware_protection/personal.php'

Problem of the ransomware_protection app

you also find traces of News in the include path.
