### ISSUE TITLE
Doctrine\DBAL\Query\QueryException: More than 1000 expressions in a list are not allowed on Oracle.

### ISSUE THREAD

**Issue by schnulli22** [nextcloud/mail#4782]
Was ist zu tun bei großen Postfächern? Löschen von Nachrichten kann doch nicht die Lösung sein, oder??

**Comment by miaulalala** [comment]
Hi schnulli22, where exactly did you run into this exception?

**Comment by schnulli22** [comment]
After installation Mail-App and installation and configuration of a mail account with many messages (4000)

**Comment by ChristophWurst** [comment]
dup of https://github.com/nextcloud/mail/issues/4584
