### ISSUE TITLE
"Default folders" can't be set

### ISSUE THREAD

**Issue by TheFrenchGhosty** [nextcloud/mail#4787]
### Expected behavior

When setting up the "Default folders" of an accounts, they are indeed setup and work correctly.

### Actual behavior

After setting them up, and saving, they aren't set to anything, even refreshing after setting up the page doesn't work.

This is a massive issues, because of examples, emails can't be deleted since "No trash mailbox configured" is displayed.

### Mail app

**Mail app version:** 1.9.3

**Mailserver or service:** Posteo.de

### Server configuration

**Operating system**: Private

**Web server:** `nextcloud:20-apache` docker image, reverse proxied by NginX on metal

**Database:** MariaDB

**PHP version:** 7.4.16

**Nextcloud Version:** 20.0.8

#### Client configuration
**Browser:** Firefox 86

**Operating system:** Private

**Comment by ChristophWurst** [comment]
thanks for the report. could you inspect the `oc_mail_accounts` table to see if the `???_mailbox_id` column gets updated?
