### ISSUE TITLE
Allow to display images once

### ISSUE THREAD

**Issue by mat-m** [nextcloud/mail#4797]
### Feature Request

Allow to display images only once in an email

#### Summary

Following #505, which is nice, I also have the opposite use case.

When first receiving an HTML email from a third-party, I want to check if images are of interest or too much intrusive. Since those emails don't always have a browser-url  coutnerpart, the only solution is to see pictures in the mail client.
Abnother use case is: I don't want to allow images from a third-party emails, but I need to on a specific email (embedded link, unreadable email because of layout change, ...)

Suggestion; Add a 3rd option: _Display images this time_

**Comment by miaulalala** [comment]
Is this what you're looking for?

![image](https://user-images.githubusercontent.com/7427347/111974914-46dbc180-8b00-11eb-90d4-5bb6ce331b12.png)


You do have the option to only temporarily show images which is the same thing.

**Comment by ChristophWurst** [comment]
This was added with https://github.com/nextcloud/mail/pull/4743 and that hasn't been released yet.
