### ISSUE TITLE
Mailbox account color not updated on scrolling a long unified list

### ISSUE THREAD

**Issue by mat-m** [nextcloud/mail#4799]
### Expected behavior
Tell us what should happen

In the message list, the color on the left should always match the one of the account it comes from.

### Actual behavior
Tell us what happens instead

First set of 20 messages have the right color (By category in the Priority inbox, Whole list in Unified inbox).
Then other messages have all the color of the last account in the account panel, until you select them, where the color is fixed.

Before selection:

![image](https://user-images.githubusercontent.com/1039753/111889060-549b2500-89e2-11eb-9f07-24cb6098a834.png)

After selection move (mouse or keyboard):

![image](https://user-images.githubusercontent.com/1039753/111889077-798f9800-89e2-11eb-914a-5113fa67e960.png)

FWIW, I have 7 registered accounts in the Mail App. (Which means I am very grateful of the Mail App being there and so coool now, thanks for the great work!)

### Mail app

**Mail app version:** (see apps admin page, e.g. 0.5.3)

**Mailserver or service:** (e.g. Outlook, Yahoo, Gmail, Exchange,...) unified inbox

### Server configuration

**Operating system**: (e.g. Debian 8) Debian 10 (Raspbian, actually)

**Web server:** (e.g. Apache, Nginx,...) nginx

**Database:** (e.g. MariaDB, SQLite or PostgreSQL) Mariadb

**PHP version:** (e.g. 7.0) 7.3

**Nextcloud Version:** (see admin page, e.g. 13.0.2) 20.0.7

#### Client configuration
**Browser:** (e.g. Firefox 48) Opera 75

**Operating system:** (e.g. Arch Linux) Linux Mint 20.1

**Comment by GretaD** [comment]
Hey, can you please let us know what version of mail are you using? This was a problem on 1.7, but we solved it since then.

**Comment by mat-m** [comment]
@GretaD : I can confirm it is still there in Mail 1.9.5, on Nextcloud 20.0.10.

**Comment by mat-m** [comment]
@GretaD : Can't reproduce with NC 21.0.3 and Mail 1.9.5

**Comment by mat-m** [comment]
@GretaD : Reproduced in Priority Inbox after 20 mails in "Other" with Mail 1.10.0

**Comment by ChristophWurst** [comment]
I can finally reproduce. The messages `accountId` is `undefined`. I will have a look.
