### ISSUE TITLE
Show receiver mail address that is not real

### ISSUE THREAD

**Issue by SilvainLouis** [nextcloud/mail#4801]
### Expected behavior
Show only correct receiver mail address

### Actual behavior
Show only correct receiver mail address and a another mail address of a another mail

### Mail app

**Mail app version:** (see apps admin page, e.g. 0.5.3)
 1.9.3

**Mailserver or service:** (e.g. Outlook, Yahoo, Gmail, Exchange,...)
Imap

### Server configuration

**Operating system**: (e.g. Debian 8)
Web cloud OVH

**Web server:** (e.g. Apache, Nginx,...)

**Database:** (e.g. MariaDB, SQLite or PostgreSQL)

**PHP version:** (e.g. 7.0)
7.3 CGI

**Nextcloud Version:** (see admin page, e.g. 13.0.2)
20.0.7

#### Client configuration
**Browser:** (e.g. Firefox 48)
Firefox

**Operating system:** (e.g. Arch Linux)

**Comment by ChristophWurst** [comment]
dup of https://github.com/nextcloud/mail/issues/4412? do you use mysql 5.7?
