### ISSUE TITLE
Tag management UI

### ISSUE THREAD

**Issue by ChristophWurst** [nextcloud/mail#4806]
This is a more detailed ticket about the UI parts of https://github.com/nextcloud/mail/issues/25 for users to set up their tags.

## User story

As a user I want to be able to add, edit and possibly delete the tags that are used in my email accounts. The system will create five default tags for me, just like Thunderbird does. I want to be able to change their color as well as their *display name*.

![Bildschirmfoto von 2021-03-23 10-21-31](https://user-images.githubusercontent.com/1374172/112123528-a1892200-8bc1-11eb-876c-730e333eff2f.png)

## Technical background

We don't store tags on IMAP directly because of encoding and length limitations. Hence we use *keywords* aka placeholders that are sent to IMAP and mapped in the application. For example *important* is saved as *$label1* on IMAP.

Every tag has a
* keyword for imap
* display name for the UI
* color

Just like in Thunderbird I would only allow the users to influence display name and color, the keyword should be assigned by the system (e.g. incrementing `$labelXYZ`).

![Bildschirmfoto von 2021-03-23 10-22-15](https://user-images.githubusercontent.com/1374172/112123683-c41b3b00-8bc1-11eb-8ea0-d995f47d8841.png)

As of #4665 we have the back-end support to manage tags inside Nextcloud. For the most part we need an UI, but possibly a few controller methods to create and modify user tags.

As opposed to many other settings tags are not to be configured per email account but per Nextcloud account. Hence they should probably not show in the account settings modal but in a more generic settings modal. The *trusted senders* are actually similar to this, we could move those two into a new settings modal.

- [x] Requires a restructured Vuex store for central tag mutations https://github.com/nextcloud/mail/issues/4871

cc @nimisha-vijay for design input :)

**Comment by sutidor** [comment]
Cool feature. How can I remove or edit (color, name) a tag?

**Comment by ChristophWurst** [comment]
> Cool feature. How can I remove or edit (color, name) a tag?

https://help.nextcloud.com/c/apps/mail/35 is the place for questions :v:
