### ISSUE TITLE
Priority inbox does not show unread email

### ISSUE THREAD

**Issue by thstyl2000** [nextcloud/mail#4810]
### Expected behavior
By "Important and unread" I understand that this list contains important emails and unread emails.

### Actual behavior
This section contains only the emails that have been recognized by the ML code and are also unread.

I am not sure if this is classified as a bug (in the wording of the list) or as an enhancement....I would anyway be happy for a list containing only the unread messages.

### Mail app

**Mail app version:** 1.9.3

**Mailserver or service:** any

### Server configuration

**Operating system**: freebsd 12

**Web server:** Apache behind Nginx reverse proxy

**Database:** MariaDB

**PHP version:** 7.4

**Nextcloud Version:** 20.0.8

#### Client configuration
**Browser:** any

**Operating system:** Kubuntu

**Comment by ChristophWurst** [comment]
this is not a bug. it's literally important **and** unread. that is the condition. anything that isn't important but unread will show in *Other*

**Comment by thstyl2000** [comment]
Well then, what about making the heading a bit more descriptive, sth like "Importand unread emails". I understand this probably does not make so much sense since, unless I am mistaken, the whole tagging framework will shortly become standard. So, If this is indeed the case, I would just close the issue.....
