### ISSUE TITLE
calendar invitation from exchange or gmail 

### ISSUE THREAD

**Issue by lucdurb** [nextcloud/mail#4813]
### Expected behavior
when i recieve a calendar invitation from exchange, the email is blank. when i recieve a calendar invitation from gmail i see the message but the .ics don't write on the calendar

i have tried with chrome, edge chromium. 
i'm using nextcloud 20 or 21

**Comment by ChristophWurst** [comment]
duplicate of https://github.com/nextcloud/mail/issues/4463 or https://github.com/nextcloud/mail/issues/4758 or https://github.com/nextcloud/mail/issues/4423

**Comment by ChristophWurst** [comment]
please fill out the actual issue template next time you report a bug. thanks.
