### ISSUE TITLE
Delete all message_tags entries if a user deletes the associated tag

### ISSUE THREAD

**Issue by miaulalala** [nextcloud/mail#4825]
### Feature Request

Currently, we leave rows orphaned in `message_tags` if a tag is deleted. Rows that have invalid entries should be cleaned up two ways - remove all associated entries at the time of deleting a tag, and also add a deleteOrphans() to the Cleanup Job.

**Comment by ChristophWurst** [comment]
Ref #4806 because as long as we don't have user defined tags there is nothing to delete or clean up :)

**Comment by miaulalala** [comment]
> Ref #4806 because as long as we don't have user defined tags there is nothing to delete or clean up :)

Not quite true, some tags might be set/unset by users in another mail client and still show up in our app :)
