### ISSUE TITLE
1071 Specified key was too long; max key length is 3072 bytes

### ISSUE THREAD

**Issue by StCyr** [nextcloud/mail#4827]
### Expected behavior
After pulling the latest changes on master (7bc1cb1f64294236dcab0f24d4757399539c7524), I should be able to build, update, and run Mail

### Actual behavior
The update step fails with the following log:

`Mar 25 11:14:59 vm-cyrille-debian Nextcloud[327994]: {"reqId":"tyMI74CgO6yyu9LKwKPA","level":3,"time":"2021-03-25T10:14:59+00:00","remoteAddr":"192.168.0.9","user":"--","app":"core","method":"GET","url":"/core/ajax/update.php?requesttoken=1ItfP2tk2LNpPOPHrejLjHeW9J9szFndd2O%2BPqG8QFQ%3D%3AvuU3ai8w7vIBWrWQnNy%2B9hTMo%2Fk%2FixOHNQLOdvHRODo%3D","message":"{\"Exception\":\"Exception\",\"Message\":\"Database error when running migration latest for app mail\",\"Code\":0,\"Trace\":[{\"file\":\"/var/www/nextcloud/lib/private/legacy/OC_App.php\",\"line\":993,\"function\":\"migrate\",\"class\":\"OC\\\\DB\\\\MigrationService\",\"type\":\"->\"},{\"file\":\"/var/www/nextcloud/lib/private/Updater.php\",\"line\":340,\"function\":\"updateApp\",\"class\":\"OC_App\",\"type\":\"::\",\"args\":[\"*** sensitive parameters replaced ***\"]},{\"file\":\"/var/www/nextcloud/lib/private/Updater.php\",\"line\":260,\"function\":\"doAppUpgrade\",\"class\":\"OC\\\\Updater\",\"type\":\"->\"},{\"file\":\"/var/www/nextcloud/lib/private/Updater.php\",\"line\":132,\"function\":\"doUpgrade\",\"class\":\"OC\\\\Updater\",\"type\":\"->\"},{\"file\":\"/var/www/nextcloud/core/ajax/update.php\",\"line\":214,\"function\":\"upgrade\",\"class\":\"OC\\\\Updater\",\"type\":\"->\"}],\"File\":\"/var/www/nextcloud/lib/private/DB/MigrationService.php\",\"Line\":430,\"Previous\":{\"Exception\":\"Doctrine\\\\DBAL\\\\Exception\\\\DriverException\",\"Message\":\"An exception occurred while executing a query: SQLSTATE[42000]: Syntax error or access violation: 1071 Specified key was too long; max key length is 3072 bytes\",\"Code\":1071,\"Trace\":[{\"file\":\"/var/www/nextcloud/3rdparty/doctrine/dbal/src/Connection.php\",\"line\":1728,\"function\":\"convert\",\"class\":\"Doctrine\\\\DBAL\\\\Driver\\\\API\\\\MySQL\\\\ExceptionConverter\",\"type\":\"->\"},{\"file\":\"/var/www/nextcloud/3rdparty/doctrine/dbal/src/Connection.php\",\"line\":1667,\"function\":\"handleDriverException\",\"class\":\"Doctrine\\\\DBAL\\\\Connection\",\"type\":\"->\"},{\"file\":\"/var/www/nextcloud/3rdparty/doctrine/dbal/src/Connection.php\",\"line\":1040,\"function\":\"convertExceptionDuringQuery\",\"class\":\"Doctrine\\\\DBAL\\\\Connection\",\"type\":\"->\"},{\"file\":\"/var/www/nextcloud/lib/private/DB/Connection.php\",\"line\":226,\"function\":\"executeQuery\",\"class\":\"Doctrine\\\\DBAL\\\\Connection\",\"type\":\"->\"},{\"file\":\"/var/www/nextcloud/3rdparty/doctrine/dbal/src/Connection.php\",\"line\":1757,\"function\":\"executeQuery\",\"class\":\"OC\\\\DB\\\\Connection\",\"type\":\"->\"},{\"file\":\"/var/www/nextcloud/lib/private/DB/Migrator.php\",\"line\":256,\"function\":\"query\",\"class\":\"Doctrine\\\\DBAL\\\\Connection\",\"type\":\"->\"},{\"file\":\"/var/www/nextcloud/lib/private/DB/Migrator.php\",\"line\":90,\"function\":\"applySchema\",\"class\":\"OC\\\\DB\\\\Migrator\",\"type\":\"->\"},{\"file\":\"/var/www/nextcloud/lib/private/DB/Connection.php\",\"line\":524,\"function\":\"migrate\",\"class\":\"OC\\\\DB\\\\Migrator\",\"type\":\"->\"},{\"file\":\"/var/www/nextcloud/lib/private/DB/MigrationService.php\",\"line\":539,\"function\":\"migrateToSchema\",\"class\":\"OC\\\\DB\\\\Connection\",\"type\":\"->\"},{\"file\":\"/var/www/nextcloud/lib/private/DB/MigrationService.php\",\"line\":426,\"function\":\"executeStep\",\"class\":\"OC\\\\DB\\\\MigrationService\",\"type\":\"->\"},{\"file\":\"/var/www/nextcloud/lib/private/legacy/OC_App.php\",\"line\":993,\"function\":\"migrate\",\"class\":\"OC\\\\DB\\\\MigrationService\",\"type\":\"->\"},{\"file\":\"/var/www/nextcloud/lib/private/Updater.php\",\"line\":340,\"function\":\"updateApp\",\"class\":\"OC_App\",\"type\":\"::\",\"args\":[\"*** sensitive parameters replaced ***\"]},{\"file\":\"/var/www/nextcloud/lib/private/Updater.php\",\"line\":260,\"function\":\"doAppUpgrade\",\"class\":\"OC\\\\Updater\",\"type\":\"->\"},{\"file\":\"/var/www/nextcloud/lib/private/Updater.php\",\"line\":132,\"function\":\"doUpgrade\",\"class\":\"OC\\\\Updater\",\"type\":\"->\"},{\"file\":\"/var/www/nextcloud/core/ajax/update.php\",\"line\":214,\"function\":\"upgrade\",\"class\":\"OC\\\\Updater\",\"type\":\"->\"}],\"File\":\"/var/www/nextcloud/3rdparty/doctrine/dbal/src/Driver/API/MySQL/ExceptionConverter.php\",\"Line\":114,\"Previous\":{\"Exception\":\"Doctrine\\\\DBAL\\\\Driver\\\\PDO\\\\Exception\",\"Message\":\"SQLSTATE[42000]: Syntax error or access violation: 1071 Specified key was too long; max key length is 3072 bytes\",\"Code\":1071,\"Trace\":[{\"file\":\"/var/www/nextcloud/3rdparty/doctrine/dbal/src/Driver/PDO/Connection.php\",\"line\":87,\"function\":\"new\",\"class\":\"Doctrine\\\\DBAL\\\\Driver\\\\PDO\\\\Exception\",\"type\":\"::\"},{\"file\":\"/var/www/nextcloud/3rdparty/doctrine/dbal/src/Connection.php\",\"line\":1035,\"function\":\"query\",\"class\":\"Doctrine\\\\DBAL\\\\Driver\\\\PDO\\\\Connection\",\"type\":\"->\"},{\"file\":\"/var/www/nextcloud/lib/private/DB/Connection.php\",\"line\":226,\"function\":\"executeQuery\",\"class\":\"Doctrine\\\\DBAL\\\\Connection\",\"type\":\"->\"},{\"file\":\"/var/www/nextcloud/3rdparty/doctrine/dbal/src/Connection.php\",\"line\":1757,\"function\":\"executeQuery\",\"class\":\"OC\\\\DB\\\\Connection\",\"type\":\"->\"},{\"file\":\"/var/www/nextcloud/lib/private/DB/Migrator.php\",\"line\":256,\"function\":\"query\",\"class\":\"Doctrine\\\\DBAL\\\\Connection\",\"type\":\"->\"},{\"file\":\"/var/www/nextcloud/lib/private/DB/Migrator.php\",\"line\":90,\"function\":\"applySchema\",\"class\":\"OC\\\\DB\\\\Migrator\",\"type\":\"->\"},{\"file\":\"/var/www/nextcloud/lib/private/DB/Connection.php\",\"line\":524,\"function\":\"migrate\",\"class\":\"OC\\\\DB\\\\Migrator\",\"type\":\"->\"},{\"file\":\"/var/www/nextcloud/lib/private/DB/MigrationService.php\",\"line\":539,\"function\":\"migrateToSchema\",\"class\":\"OC\\\\DB\\\\Connection\",\"type\":\"->\"},{\"file\":\"/var/www/nextcloud/lib/private/DB/MigrationService.php\",\"line\":426,\"function\":\"executeStep\",\"class\":\"OC\\\\DB\\\\MigrationService\",\"type\":\"->\"},{\"file\":\"/var/www/nextcloud/lib/private/legacy/OC_App.php\",\"line\":993,\"function\":\"migrate\",\"class\":\"OC\\\\DB\\\\MigrationService\",\"type\":\"->\"},{\"file\":\"/var/www/nextcloud/lib/private/Updater.php\",\"line\":340,\"function\":\"updateApp\",\"class\":\"OC_App\",\"type\":\"::\",\"args\":[\"*** sensitive parameters replaced ***\"]},{\"file\":\"/var/www/nextcloud/lib/private/Updater.php\",\"line\":260,\"function\":\"doAppUpgrade\",\"class\":\"OC\\\\Updater\",\"type\":\"->\"},{\"file\":\"/var/www/nextcloud/lib/private/Updater.php\",\"line\":132,\"function\":\"doUpgrade\",\"class\":\"OC\\\\Updater\",\"type\":\"->\"},{\"file\":\"/var/www/nextcloud/core/ajax/update.php\",\"line\":214,\"function\":\"upgrade\",\"class\":\"OC\\\\Updater\",\"type\":\"->\"}],\"File\":\"/var/www/nextcloud/3rdparty/doctrine/dbal/src/Driver/PDO/Exception.php\",\"Line\":26,\"Previous\":{\"Exception\":\"PDOException\",\"Message\":\"SQLSTATE[42000]: Syntax error or access violation: 1071 Specified key was too long; max key length is 3072 bytes\",\"Code\":\"42000\",\"Trace\":[{\"file\":\"/var/www/nextcloud/3rdparty/doctrine/dbal/src/Driver/PDO/Connection.php\",\"line\":82,\"function\":\"query\",\"class\":\"PDO\",\"type\":\"->\"},{\"file\":\"/var/www/nextcloud/3rdparty/doctrine/dbal/src/Connection.php\",\"line\":1035,\"function\":\"query\",\"class\":\"Doctrine\\\\DBAL\\\\Driver\\\\PDO\\\\Connection\",\"type\":\"->\"},{\"file\":\"/var/www/nextcloud/lib/private/DB/Connection.php\",\"line\":226,\"function\":\"executeQuery\",\"class\":\"Doctrine\\\\DBAL\\\\Connection\",\"type\":\"->\"},{\"file\":\"/var/www/nextcloud/3rdparty/doctrine/dbal/src/Connection.php\",\"line\":1757,\"function\":\"executeQuery\",\"class\":\"OC\\\\DB\\\\Connection\",\"type\":\"->\"},{\"file\":\"/var/www/nextcloud/lib/private/DB/Migrator.php\",\"line\":256,\"function\":\"query\",\"class\":\"Doctrine\\\\DBAL\\\\Connection\",\"type\":\"->\"},{\"file\":\"/var/www/nextcloud/lib/private/DB/Migrator.php\",\"line\":90,\"function\":\"applySchema\",\"class\":\"OC\\\\DB\\\\Migrator\",\"type\":\"->\"},{\"file\":\"/var/www/`

### Mail app

**Mail app version:** master branch

### Server configuration

**Operating system**: Debian 10

**Web server:** Apache

**Database:** MariaDB 10.5.9

**PHP version:** 7.3

**Nextcloud Version:**  stable21 branch

**Comment by ChristophWurst** [comment]
We might be able to use a shortened index like in https://github.com/nextcloud/server/pull/26070

**Comment by miaulalala** [comment]
Removing the unique index will fix this: #4833

**Comment by StCyr** [comment]
> 
> 
> Removing the unique index will fix this: #4833

Yes, #4840 fixes this issue
