### ISSUE TITLE
Rework message_tags to use a hash of the imap_message_id

### ISSUE THREAD

**Issue by miaulalala** [nextcloud/mail#4828]
### Feature Request

Due to constraints on different types of databases, the unique index for a long value such as an IMAP message id won't always work and fail with a `Specified key was too long` error like in #4827 

#### Summary

Use the appropriate hashing mechanism for the message_tags_table to hash the imap_message_id and write it into a separate column.

**Comment by ChristophWurst** [comment]
Alternatively we do just shorten the index: https://github.com/nextcloud/mail/issues/4827#issuecomment-807968328

**Comment by ChristophWurst** [comment]
> Use the appropriate hashing mechanism for the message_tags_table to shorten the current VARCHAR(1023) field considerably.

As discussed I'd say if we use hashes than they should be an *additional column* so we can still compare the original message IDs

**Comment by miaulalala** [comment]
See #4833
