### ISSUE TITLE
Opening mail first shows accurate emails but after a few socnds only mail from 2 months ago are shown

### ISSUE THREAD

**Issue by small1** [nextcloud/mail#4835]
### Expected behavior
Open mail. Click on the accounts inbox. See all mail, latest first

### Actual behavior
Open mail new mails are seen first but after a few seconds when the spinner dissapears only mail from 2 months ago are seen

### Mail app

**Mail app version:** 1.9.4

**Mailserver or service:** Mailenable as mail server

### Server configuration

**Operating system**: Debian 10

**Web server:** Nginx

**Database:** MariaDB

**PHP version:** 7.4

**Nextcloud Version:** 20.0.8

#### Client configuration
**Browser:** Latest Chrome and Firefox tested
**Operating system:** Ubuntu 20.04

**Comment by SteveC00ps** [comment]
Similar for me with MailEnable as the server. I briefly see all the current mail as expected, then it refreshes and I see just a few mails from days ago. Each refresh or change of folder I see just older and older mail.
Nextcloud 21.0, Mail App 1.9.5, Mailenable 10.32

Cheers,
Steve

**Comment by ChristophWurst** [comment]
I'm pretty sure this is a duplicate of https://github.com/nextcloud/mail/issues/4762.
