### ISSUE TITLE
[request] Select all option and clear trash option

### ISSUE THREAD

**Issue by PortStone** [nextcloud/mail#485]
Hey,

could you add a feature like in gmail to select all E-Mails from Inbox? So you could just delete 10 E-Mails from your Inbox with two clicks.

Another cool feature would be if you could delete the whole trash bin with one click.

**Comment by zyphlar** [comment]
Speaking of this, how is the mail trash even supposed to work? Does it just sit there and accumulate indefinitely unless manually cleared? I was hunting for automatic trash emptying settings and came up empty.

**Comment by ChristophWurst** [comment]
> Does it just sit there and accumulate indefinitely unless manually cleared?

Yep

**Comment by StCyr** [comment]
Couldn't we consider this issue as closed? cc @ChristophWurst and @jancborchardt
