### ISSUE TITLE
Draftfolder doesn't load from time to time

### ISSUE THREAD

**Issue by LukasReschke** [nextcloud/mail#4853]
### Expected behavior

Draft folder loads fast.

### Actual behavior

Draft folder doesn't load from time to time and I need to wait a few minutes.

<img width="617" alt="Screenshot 2021-03-29 at 11 22 47" src="https://user-images.githubusercontent.com/878997/112815988-3045e500-9081-11eb-9597-3b16de54f22d.png">

I see a request to `/apps/mail/api/messages?mailboxId=6365&limit=20` that fails with a 409:

```json
{
    "status": "fail",
    "data": {
        "message": "6365 is already being synced",
        "type": "OCA\\Mail\\Exception\\MailboxLockedException"
    }
}
```

Reopening that folder a few minutes later usually works.

### Mail app

c.nc.c

**Comment by ChristophWurst** [comment]
> Sync failed for 33:Drafts: An exception occurred while executing a query: SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry '18942-6365' for key 'mail_msg_mb_uid_idx'

that's the error that leads to the locked mailbox. I'll investigate.

**Comment by ChristophWurst** [comment]
This sounds like a possible side effect of https://github.com/nextcloud/mail/pull/4760, though I can't tell why this only is a problem "from time to time".

**Comment by ChristophWurst** [comment]
Hmm

```
        {
          "file": "/var/www/html/apps/mail/lib/Service/Sync/ImapToDbSynchronizer.php",
          "line": 218,
          "function": "runInitialSync",
          "class": "OCA\\Mail\\Service\\Sync\\ImapToDbSynchronizer",
          "type": "->"
        },
        {
          "file": "/var/www/html/apps/mail/lib/Service/Sync/SyncService.php",
          "line": 121,
          "function": "sync",
          "class": "OCA\\Mail\\Service\\Sync\\ImapToDbSynchronizer",
          "type": "->"
        },
        {
          "file": "/var/www/html/apps/mail/lib/Controller/AccountsController.php",
          "line": 471,
          "function": "syncMailbox",
          "class": "OCA\\Mail\\Service\\Sync\\SyncService",
          "type": "->"
        },
```

so this actually happens because an *initial sync* is triggered and as long as we don't have #4765 the mailbox might not be fully locked and if then more than one process tries to add new messages they will run into a conflict.

@LukasReschke did you have the app open in more than one tab by any chance?

**Comment by LukasReschke** [comment]
> @LukasReschke did you have the app open in more than one tab by any chance?

I think so... I do have around 10 Nc.com tabs open 🙈

**Comment by ChristophWurst** [comment]
just nc.com or really Mail?

**Comment by LukasReschke** [comment]
Well. At least 4 mail tabs. Sending mails takes a long time, so I have several tabs open and also sometimes I need to reference mails :S

**Comment by ChristophWurst** [comment]
You'll definitely love our planned feature https://github.com/nextcloud/mail/issues/2831

**Comment by ChristophWurst** [comment]
let's wait until this is really resolved

**Comment by LukasReschke** [comment]
😢
