### ISSUE TITLE
Add "close without save" / "continue editing later" options in new message editor

### ISSUE THREAD

**Issue by thstyl2000** [nextcloud/mail#4855]
### Feature Request

As title says....

#### Summary

It happens often that one starts writing an email and then sth happens and the email does not need to be sent after all. However it is already saved in drafts. It would be practical to be able to simultaneously close the editor and delete all related drafts. Moreover, sometimes one needs to check/copy sth, possibly from another email, and then return to editing. With current configuration, (although the msec scale was insane..!) one has to wait 10sec for autosave to kick in. A manual "save" button would be very practical.

**Comment by ChristophWurst** [comment]
dup of https://github.com/nextcloud/mail/issues/2492
