### ISSUE TITLE
Total unread count on tob bar icon

### ISSUE THREAD

**Issue by thstyl2000** [nextcloud/mail#4862]
### Feature Request
Show the total number of unread messages (overlayed) in the top bar menu entry for the mail app.

#### Summary
It is currently a bit unclear, especially if one uses folders & server filters, to keep up with the number of unread messages (one has to click on the three-dotted menu of each folder to see the number). Would it be possible to have a total unread count on the mail app icon at the nextcloud top-bar?

**Comment by ChristophWurst** [comment]
Dup of https://github.com/nextcloud/mail/issues/1400
