### ISSUE TITLE
Subfolders in Mailboxes created in other mail applications don't sync

### ISSUE THREAD

**Issue by miaulalala** [nextcloud/mail#4873]
When testing #4869 I stumbled upon this. A subfolder created in Thunderbird in the Inbox shows up on my mail hosting web client, but not in NC Mail.

Thunderbird:
![image](https://user-images.githubusercontent.com/7427347/113281233-916df280-92e5-11eb-91eb-ad742b372ca7.png)

GMX:
![image](https://user-images.githubusercontent.com/7427347/113281067-684d6200-92e5-11eb-94fb-dd0af47de3f5.png)

NC:
![image](https://user-images.githubusercontent.com/7427347/113281122-769b7e00-92e5-11eb-8983-6f421cdfe0bd.png)

The Database does reflect the changes but the UI doesn't.

![image](https://user-images.githubusercontent.com/7427347/113303616-8c1ea100-9301-11eb-873f-7216ae5efc73.png)

@kesselb has confirmed this is an issue

**Comment by miaulalala** [comment]
Nvm, it just takes some time

**Comment by ChristophWurst** [comment]
> Nvm, it just takes some time

2h because that is our cache TTL for mailboxes :)

**Comment by duelli** [comment]
I am experiencing this as well.

A newly created folder on the root level, took some time but finally appeared in Nvm.

However, a subfolder of my INBOX which was created at the same time is still not shown.

Is there a way to enforce an update?

**Comment by ChristophWurst** [comment]
I created a feature request for this: https://github.com/nextcloud/mail/issues/4999
