### ISSUE TITLE
Email Signature

### ISSUE THREAD

**Issue by slideup-benni** [nextcloud/mail#490]
Is there a way to add a signature under each emails?

**Comment by ChristophWurst** [comment]
> Is there a way to add a signature under each emails?

No, not yet. But we do have a ticket for this feature request: https://github.com/nextcloud/mail/issues/190

Btw, please try to search for existig tickets before opening new ones. This one was easy to find: https://github.com/nextcloud/mail/issues?q=is%3Aissue%20signature 😉
