### ISSUE TITLE
Dark mailbox icon with dark theme

### ISSUE THREAD

**Issue by ChristophWurst** [nextcloud/mail#4908]
### Expected behavior
I can see my mailbox icons

### Actual behavior
![Bildschirmfoto von 2021-04-08 09-02-06](https://user-images.githubusercontent.com/1374172/113983913-cd0b3e00-984a-11eb-807b-5c976a75a7b5.png)

### Mail app

**Mail app version:** v1.9.4

### Server configuration

**Nextcloud Version:** 21

#### Client configuration
**Browser:** FF

cc @GretaD

**Comment by GretaD** [comment]
Closing as all is good after a hard refresh :)
