### ISSUE TITLE
Update or reinstall: App for id mail has a wrong app ID in info.xml: 

### ISSUE THREAD

**Issue by fzahn** [nextcloud/mail#492]
### Steps to reproduce
1. Running version 0.70 without problems
2. trying to update to 0.71 gives error message: App for id mail has a wrong app ID in info.xml: 
3. removing and reinstalling: App for id mail has a wrong app ID in info.xml: 

### Expected behaviour
Update from 0.7.0 to 0.7.1 should work via the Web-GUI as expected

### Actual behaviour
When updating the mail app I get the error message "App for id mail has a wrong app ID in info.xml: ".
Then i tried to remove and reinstall the app, but without success, same error message....

### Mail app

**Mail app version: 0.71 (currently none)

**Mailserver or service:** (e.g. Outlook, Yahoo, Gmail, Exchange,...) own IMAP-server on localhost

**Transport security - IMAP: IMAP TLS

**Transport security - SMTP: SMTP TLS

**Number of accounts: 1

**Mail app version build date:** (only if you are using a Nightly Build)

**Comment by ChristophWurst** [comment]
Hi,

which version of the Nextcloud server are you using?

**Comment by gameoftwo** [comment]
Hi,  I have this problem I'm using nextcloud only say this when I want active the app.

**Comment by AndreFG01** [comment]
I found a solution that worked for me...
I've just copyed all files from "/var/www/nextcloud/apps/mail/" from another installation of nextcloud to the new one, creating the missing directories an then clicking "enable app"
I belive that you can just copy all files from this repository, instead of making a separated nextcloud install to copy the files from...
Probably not the best solution though, but since it worked, maybe it helps someone else...

**Comment by Arnauec** [comment]
I'm also having this issue? Any fix that is not copying from another installation? Thank you!

**Comment by ChristophWurst** [comment]
> Hi,
> 
> which version of the Nextcloud server are you using?

Still waiting for an answer ;)

**Comment by Arnauec** [comment]
I'm using Nextcloud version 12.

**Comment by fzahn** [comment]
I am using the Nextcloud version 12 beta release...
Sorry for late reply

**Comment by ChristophWurst** [comment]
This sounds very similar to https://github.com/nextcloud/twofactor_u2f/issues/52. Could you please check your `nextcloud.log` and webserver error log for logged error messages?

**Comment by ChristophWurst** [comment]
Also https://github.com/nextcloud/dashboard/issues/16. This makes me think that it's an issue with the Nextcloud server and not this specific app. Could someone please file a ticket at the server repo? Thanks!

**Comment by Jokepp** [comment]
I run into the same problem when trying tu update (and later re-install) the mail plugin. I'm also running NC 12. I wanted to update mail from 7.0 to 7.2. These three messages are in my logs several times:

Error | core | App for id mail has a wrong app ID in info.xml: | 2017-09-11T14:20:38+0200
Error | PHP | Trying to get property of non-object at /data/web/e68116/html/org/nextcloud/lib/private/Installer.php#311 | 2017-09-11T14:20:38+0200
Error | PHP | Trying to get property of non-object at /data/web/e68116/html/org/nextcloud/lib/private/Installer.php#306 | 2017-09-11T14:20:38+0200

**Comment by heldzz** [comment]
the same problem on my server. any suggestions?

**Comment by ChristophWurst** [comment]
> the same problem on my server. any suggestions?

See https://github.com/nextcloud/mail/issues/492#issuecomment-328446874 :)

**Comment by heldzz** [comment]
Phew, I don't know what this means. I can submit logs, but it's exactly the same as Jokepp posted (that's why I said "the same problem on my server") and my apache error.log is saying nothing. I'm no developer, just a dumb nextcloud user searching for a possibility to use the mail app again ;-)

**Comment by crooked-rook** [comment]
For what it's worth, I'm running into the same issue.  Fresh nextcloud 12.0.2 install, trying to add Mail app for the first time:
"App for id mail has a wrong app ID in info.xml"

**Comment by canaaerus** [comment]
I am running MailApp 0.6.4 and just got the notification that an update to 0.7.3 is available. But when I press the update button, the update is not completed and I get the following error message in my logs:

    {
        "reqId":"RtGhqBZxiqSgGRQfgNgk",
        "level":3,
        "time":"2017-09-13T17:55:01+00:00",
        "remoteAddr":"xxx.xxx.xxx.xxx",
        "user":"admin",
        "app":"core",
        "method":"POST",
        "url":"\/index.php\/settings\/ajax\/updateapp.php",
        "message":"App for id mail has a wrong app ID in info.xml: ",
        "userAgent":"Mozilla\/5.0 (X11; Linux x86_64; rv:52.0) Gecko\/20100101 Firefox\/52.0",
        "version":"12.0.2.0"
    }

**Comment by ChristophWurst** [comment]
Just a wild guess, but it could be the case that the temp directory is full or not writable for Nextcloud and thus the app archive cannot be extracted. Could anyone please try to adjust `tempdirectory` in confi.php? See https://docs.nextcloud.com/server/12/admin_manual/configuration_server/config_sample_php_parameters.html#all-other-configuration-options for more info.

**Comment by ntrinh** [comment]
@ChristophWurst I am not sure it is related to a full temp directory.
I can install other apps but I have this issue only with the mail app.

Note : fresh install of Nextcloud 12.0.2 on Debian 8.9

**Comment by ChristophWurst** [comment]
According to @LukasReschke this problem most likely is caused by an buggy/outdated ssl lib that doesn't handle redirects and such well and thus fails to download the app archive from the github releases page. So I'd be curious about what Linux distributions, which versions of it and what version of php you're using.

IMO there's little we can do about this, other than failing more gracefully https://github.com/nextcloud/server/pull/6586.

**Comment by heldzz** [comment]
Error is still valid on my installation.
Is use Debian 9.1, OpenSSL 1.1.0f, and PHP Version 7.1.8_20170905140316.

**Comment by ntrinh** [comment]
I have this error in my log file and the tmp directory permissions are correct.
This error appears just before the wrong APP ID error

`{"reqId":"eRica500hmUW2T8QpPVK","level":3,"time":"2017-09-22T20:54:51+00:00","remoteAddr":"81.249.198.54","user":"xxx","app":"PHP","method":"POST","url":"\/index.php\/settings\/ajax\/enableapp.php","message":"simplexml_load_file(): I\/O warning : failed to load external entity \"\/var\/www\/virtual\/mywebsite\/cloud\/00_private\/oc_tmp_CDQqHk-folder\/\/mail\/appinfo\/info.xml\" at \/var\/www\/virtual\/mywebsite\/cloud\/htdocs\/lib\/private\/Installer.php#304","userAgent":"Mozilla\/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit\/537.36 (KHTML, like Gecko) Chrome\/60.0.3112.113 Safari\/537.36","version":"12.0.3.3"}`

Directory permissions:
```
3803623 drwxr-x---  6 vu2013 vu2013 4096 Sep 22 22:36 .
3413375 drwxr-x--- 10 vu2013 vu2013 4096 Sep 17 15:54 ..
4067563 drwxr-x---  2 vu2013 vu2013 4096 Sep 22 22:54 00_private
3935766 drwxr-x---  2 vu2013 vu2013 4096 Sep 17 15:54 cgi-bin
4197335 drwxr-x--- 15 vu2013 vu2013 4096 Sep 22 22:05 htdocs
4197305 drwxrwxrwx  2 vu2013 vu2013 4096 Sep 22 22:41 phptmp
```

**Comment by simonspa** [comment]
For me I think it might have been the `temp` storage space issue suggested by @ChristophWurst - I noticed only few minutes after having this upgrade issue that my server ran out of storage space on `/`. Cleaning up old apt cache files resoled this and Mail works as expected.

**Comment by canaaerus** [comment]
For me there is definitely enough space on `/`.
I am on ```Ubuntu 16.04.3 LTS / Linux 4.4.0-96-generic #119-Ubuntu SMP Tue Sep 12 14:59:54 UTC 2017 GNU/Linux``` with `PHP 7.0.22-0ubuntu0.16.04.1` and `openssl-1.0.2g-1ubuntu4.6`

**Comment by ChristophWurst** [comment]
Has anybody tried patch https://github.com/nextcloud/server/pull/6586?

**Comment by ChristophWurst** [comment]
> Has anybody tried patch nextcloud/server#6586?

FYI you can download the patch file from https://patch-diff.githubusercontent.com/raw/nextcloud/server/pull/6586.patch

**Comment by fzahn** [comment]
I tried it. Now i get the error message: Could not extract app mail

**Comment by ChristophWurst** [comment]
Perfect. Thanks!

**Comment by kevquirk** [comment]
Benn trying to work around this issue, but I still can't get it working correctly. I downloaded 0.72 from Github and uploaded it manually. This allowed me to enable the app, but when I try to upgrade to 0.73, it fails.

If I download from 0.73 from Github, the FTP it to my server, I can't enable it. It says "Cannot enable app as it makes server unstable" when I try.

Mail is the main reason I wanted to use Nextcloud, I hope this can be resolved...

**Comment by ChristophWurst** [comment]
> If I download from 0.73 from Github, the FTP it to my server, I can't enable it. It says "Cannot enable app as it makes server unstable" when I try.

Please file a new ticket for that issue. I'm sure there's more info in your nextcloud.log.
