### ISSUE TITLE
Configure Mail Forward

### ISSUE THREAD

**Issue by wedge47** [nextcloud/mail#4927]
Currently we are using an old Horde Groupware solution and think about switching to nextcloud to have all in one place for the users. Although we have a lot of users, not everyone is using the email address we are providing. 

One important use case is therefore  that users are able to configure an **email forward** if they do not use "our" mail address regularly. I did not find a way do to this as a user with the current mail app. Have I missed it or is it just not implemented? If not are there plans to do so?

Thank you

**Comment by ChristophWurst** [comment]
we don't have this but isn't the forward email something to configure on the *mail server*?

**Comment by wedge47** [comment]
yes it is configured on the mail server via Sieve Script. Same goes for out-of-office notifications. But the user does not have access to this on the mail server. In Horde the user is able to set the forward via filter options

![mail-redirect](https://user-images.githubusercontent.com/45931845/114160779-948d6200-9927-11eb-862f-ef556732a11a.gif)

**Comment by ChristophWurst** [comment]
we have Sieve support in Mail since v1.9: https://github.com/nextcloud/mail/pull/4472

the rest is just a matter of whether there is an UI to create the forward filter of if the user enters it as textual rule. The UI parts are covered by https://github.com/nextcloud/mail/issues/44.
