### ISSUE TITLE
Mail App Breaks nextcloud on every update since 20.0.8

### ISSUE THREAD

**Issue by Routhinator** [nextcloud/mail#4934]
### Expected behavior
Mail app updates without breaking nextcloud

### Actual behavior
Nextcloud breaks after mail app updates with error:

```
[Fri Apr 09 20:50:18.269563 2021] [php7:error] [pid 43] [client 172.16.1.183:34536] PHP Fatal error:  require(): Failed opening required '/var/www/html/custom_apps/mail/vendor/composer/../rubix/tensor/src/constants.php' (include_path='/var/www/html/custom_apps/mail/vendor/pear-pear.horde.org/Horde_Crypt_Blowfish:/var/www/html/custom_apps/mail/vendor/pear-pear.horde.org/Horde_Date:/var/www/html/custom_apps/mail/vendor/pear-pear.horde.org/Horde_Exception:/var/www/html/custom_apps/mail/vendor/pear-pear.horde.org/Horde_Idna:/var/www/html/custom_apps/mail/vendor/pear-pear.horde.org/Horde_Imap_Client:/var/www/html/custom_apps/mail/vendor/pear-pear.horde.org/Horde_ListHeaders:/var/www/html/custom_apps/mail/vendor/pear-pear.horde.org/Horde_Mail:/var/www/html/custom_apps/mail/vendor/pear-pear.horde.org/Horde_ManageSieve:/var/www/html/custom_apps/mail/vendor/pear-pear.horde.org/Horde_Mime:/var/www/html/custom_apps/mail/vendor/pear-pear.horde.org/Horde_Nls:/var/www/html/custom_apps/mail/vendor/pear-pear.horde.org/Horde_Secret:/var/www/html/custom_apps/mail/vendor/pear-pear.horde.org/Horde_Smtp:/var/www/html/custom_apps/ in /var/www/html/custom_apps/mail/vendor/composer/autoload_real.php on line 73
```
It is also impossible to run any OCC commands as this failure fundamentally breaks everything in Nextcloud.

Recovering from this requires the following steps:
- Exec into docker container/server and delete the `custom_apps/mail` folder
- Disable maintenance mode, which the update starts but never exits due to the 500 errors.
- Go back to UI and reload, it Nextcloud will be operational.
- Go to apps; the Mail app will be messed up and say version 0,  click disable on mail.
- Click Download and Enable on mail, and the latest version will be installed and enabled.

### Mail app

**Mail app version:** Currently 1.9.5, however this happened when updating from 1.9.3 and 1.9.4

**Mailserver or service:** Custom dovecot.

### Server configuration

**Operating system**: nextcloud:20.0.8-apache

**Web server:** nextcloud:20.0.8-apache

**Database:** Postgresql

**PHP version:** nextcloud:20.0.8-apache
**Nextcloud Version:** nextcloud:20.0.8-apache

#### Client configuration
Not relevant to this issue

**Comment by ChristophWurst** [comment]
Dup of https://github.com/nextcloud/mail/issues/4832. I'll reopen the other one.
