### ISSUE TITLE
How to add Email Account in Mail app Manually through APIs.

### ISSUE THREAD

**Issue by dharmikvyas** [nextcloud/mail#4937]
### Question

I have implemented Keycloak(SSO) With Nextcloud. Now when I logged in to Nextcloud through KeyCloak(SSO), I am unable to view mail account in mail app. If I do login directly it works. But as per requirement, I have too use KeyCloak(SSO). I also can add Mail account with Manual Add. But it is not possible to add all accounts Manually, Because there are thousands of users who needs to access Nextcloud so can't add manual account to each and everyone. Is there a way To add Mail Account through API? When I create user in keycloak and Nextcloud using APIs, I also would like to mail account in Nextcloud through API. So When user login he/she can find out his working Mail App.

**Comment by ChristophWurst** [comment]
> Please ask your question in the community forum at https://help.nextcloud.com/c/apps/mail
> Please ask your question in the community forum at https://help.nextcloud.com/c/apps/mail

you successfully ignored the issue template

there is no such api. you can use the occ command, but that's it. enterprise setups usually use the account provisioning feature via the admin settings.
