### ISSUE TITLE
Quoted text breaks lines in plaintext emails

### ISSUE THREAD

**Issue by aaronjangel** [nextcloud/mail#4938]
I receive plaintext daily reports from a FreeBSD system that includes network statistics. Some of them appear in the following form:

nfe0   1500 <Link#1>      xx:xx:xx:xx:xx:xx   697862     0     0   638443     0     0     0

Instead of displaying the line as is, the mail app decides part of this is quoted text and displays it as below:

nfe0   1500 <Link#1
▼Quoted text
*>      xx:xx:xx:xx:xx:xx   697862     0     0   638443     0     0     0*

This is not how quoted text works; > must begin the line.

Side note: In addition to fixing this, it would be really nice to have the option to disable this feature.

**Comment by ChristophWurst** [comment]
mind submitting a proper bug report following our template with like expected and actual behavior?

Please also send us a snippet of the original message and make sure to quote it to prevent github markdown formatting obfuscate the original text.

**Comment by aaronjangel** [comment]
Hello Christoph,

Yes, I would be glad to. I was not able to find a template in the documentation. Do you have a link?

Thanks,
Aaron

-------- Original Message --------

**Comment by ChristophWurst** [comment]
https://github.com/nextcloud/mail/issues/new?assignees=&labels=bug%2C+0.+to+triage&template=bug.md&title= :)
