### ISSUE TITLE
Error logged by cron job

### ISSUE THREAD

**Issue by marcogaio** [nextcloud/mail#4942]
NC 21.0.0, on debian buster (PHP 7.3.27-1~deb10u1); latest stable email app.

I have my NC installation binded to an LDAP server, and configured on 'groupware' config page the respective email account, globally for all users.
I have also at least one administrative account, non binded to LDAP, that could be the source of this error.

Anyway, i get at every cron job run:
```
Apr 12 00:15:13 nextcloud Nextcloud[16710]: {"reqId":"fzngdMxTdh8kKSAquFsb","level":3,"time":"2021-04-11T22:15:13+00:00","remoteAddr":"","user":"--","app":"mail","method":"","url":"--","message":"{\"Exception\":\"OCA\\\\Mail\\\\Exception\\\\ServiceException\",\"Message\":\"IMAP error: Mail server denied authentication.\",\"Code\":102,\"Trace\":[{\"file\":\"/var/www/nextcloud/apps/mail/lib/BackgroundJob/SyncJob.php\",\"line\":91,\"function\":\"sync\",\"class\":\"OCA\\\\Mail\\\\IMAP\\\\MailboxSync\",\"type\":\"->\",\"args\":[{\"__class__\":\"OCA\\\\Mail\\\\Account\"},{\"__class__\":\"OC\\\\AppFramework\\\\ScopedPsrLogger\"},true]},{\"file\":\"/var/www/nextcloud/lib/public/BackgroundJob/Job.php\",\"line\":80,\"function\":\"run\",\"class\":\"OCA\\\\Mail\\\\BackgroundJob\\\\SyncJob\",\"type\":\"->\",\"args\":[{\"accountId\":4}]},{\"file\":\"/var/www/nextcloud/lib/public/BackgroundJob/TimedJob.php\",\"line\":61,\"function\":\"execute\",\"class\":\"OCP\\\\BackgroundJob\\\\Job\",\"type\":\"->\",\"args\":[{\"__class__\":\"OC\\\\BackgroundJob\\\\JobList\"},{\"__class__\":\"OC\\\\Log\"}]},{\"file\":\"/var/www/nextcloud/cron.php\",\"line\":128,\"function\":\"execute\",\"class\":\"OCP\\\\BackgroundJob\\\\TimedJob\",\"type\":\"->\",\"args\":[{\"__class__\":\"OC\\\\BackgroundJob\\\\JobList\"},{\"__class__\":\"OC\\\\Log\"}]}],\"File\":\"/var/www/nextcloud/apps/mail/lib/IMAP/MailboxSync.php\",\"Line\":106,\"Previous\":{\"Exception\":\"Horde_Imap_Client_Exception\",\"Message\":\"Mail server denied authentication.\",\"Code\":102,\"Trace\":[{\"file\":\"/var/www/nextcloud/apps/mail/vendor/pear-pear.horde.org/Horde_Imap_Client/Horde/Imap/Client/Base.php\",\"line\":838,\"function\":\"_login\",\"class\":\"Horde_Imap_Client_Socket\",\"type\":\"->\",\"args\":[\"*** sensitive parameters replaced ***\"]},{\"file\":\"/var/www/nextcloud/apps/mail/vendor/pear-pear.horde.org/Horde_Imap_Client/Horde/Imap/Client/Base.php\",\"line\":1389,\"function\":\"login\",\"class\":\"Horde_Imap_Client_Base\",\"type\":\"->\",\"args\":[\"*** sensitive parameters replaced ***\"]},{\"file\":\"/var/www/nextcloud/apps/mail/lib/IMAP/FolderMapper.php\",\"line\":60,\"function\":\"listMailboxes\",\"class\":\"Horde_Imap_Client_Base\",\"type\":\"->\",\"args\":[\"*\",5,{\"delimiter\":true,\"attributes\":true,\"special_use\":true}]},{\"file\":\"/var/www/nextcloud/apps/mail/lib/IMAP/MailboxSync.php\",\"line\":103,\"function\":\"getFolders\",\"class\":\"OCA\\\\Mail\\\\IMAP\\\\FolderMapper\",\"type\":\"->\",\"args\":[{\"__class__\":\"OCA\\\\Mail\\\\Account\"},{\"cacheFields\":[\"HICenv\",\"HICflags\",\"HIChdrs\",\"HICdate\",\"HICsize\",\"And 1 more entries, set log level to debug to see all entries\"],\"changed\":true,\"statuscache\":true,\"__class__\":\"Horde_Imap_Client_Socket\"}]},{\"file\":\"/var/www/nextcloud/apps/mail/lib/BackgroundJob/SyncJob.php\",\"line\":91,\"function\":\"sync\",\"class\":\"OCA\\\\Mail\\\\IMAP\\\\MailboxSync\",\"type\":\"->\",\"args\":[{\"__class__\":\"OCA\\\\Mail\\\\Account\"},{\"__class__\":\"OC\\\\AppFramework\\\\ScopedPsrLogger\"},true]},{\"file\":\"/var/www/nextcloud/lib/public/BackgroundJob/Job.php\",\"line\":80,\"function\":\"run\",\"class\":\"OCA\\\\Mail\\\\BackgroundJob\\\\SyncJob\",\"type\":\"->\",\"args\":[{\"accountId\":4}]},{\"file\":\"/var/www/nextcloud/lib/public/BackgroundJob/TimedJob.php\",\"line\":61,\"function\":\"execute\",\"class\":\"OCP\\\\BackgroundJob\\\\Job\",\"type\":\"->\",\"args\":[{\"__class__\":\"OC\\\\BackgroundJob\\\\JobList\"},{\"__class__\":\"OC\\\\Log\"}]},{\"file\":\"/var/www/nextcloud/cron.php\",\"line\":128,\"function\":\"execute\",\"class\":\"OCP\\\\BackgroundJob\\\\TimedJob\",\"type\":\"->\",\"args\":[{\"__class__\":\"OC\\\\BackgroundJob\\\\JobList\"},{\"__class__\":\"OC\\\\Log\"}]}],\"File\":\"/var/www/nextcloud/apps/mail/vendor/pear-pear.horde.org/Horde_Imap_Client/Horde/Imap/Client/Socket.php\",\"Line\":572},\"CustomMessage\":\"Cron mail sync failed: IMAP error: Mail server denied authentication.\"}","userAgent":"--","version":"21.0.0.18"}
```

There's some way to 'filter' account for which the job are run, or disable email cron job?

Thanks.

**Comment by ChristophWurst** [comment]
> Mail server denied authentication

one of the accounts has a wrong password or the mail server denied because or a rate limit or something simliar.

> 'filter' account for which the job are run, or disable email cron job?

No, they are run for all accounts. I don't see a valid reason to not run the background job when other logic relies on it.

**Comment by marcogaio** [comment]
Probably this is not really a bug, better a 'feature request'; sorry for taking the wrong path...

> No, they are run for all accounts. I don't see a valid reason to not run the background job when other logic relies on it.
I totally disagree for that; it is best practice NOT to delete users in domains (LDAP; AD), but simply disable it. So it is totally normal to have disabled users in a domain; and it is totally normal that disable users fail authentication.
Disabled users can be normally _queried_ in domain (or, clearly, you can query enabled users).
So, consider an options to query for account also the account status (enabled, disabled but also locked).

If needed, i can provide example query at least for AD and LDAP/Samba3.

Thanks.

**Comment by ChristophWurst** [comment]
Are you Mail accounts created via the provisioning?

If Nextcloud know that a user is disabled we could skip the synchronization. But that needs some modifications in the provisioning logic.

**Comment by marcogaio** [comment]
> Are you Mail accounts created via the provisioning?

Ahem, meaning what?! My users are defined in LDAP, and MTA (and IMAP server, indeed) know users (and email) because are defined in LDAP.

> If Nextcloud know that a user is disabled we could skip the synchronization. But that needs some modifications in the provisioning logic.

Indeed. But probably this is not a specific _mail app question_, but a generic NC one... NC have in user management an _disabled user_ info/flag? NC can inherit from external account source this info?

**Comment by ChristophWurst** [comment]
Please open a topic at https://help.nextcloud.com/c/apps/mail/35 so we can move this off the bug tracker. Thanks.

**Comment by marcogaio** [comment]
Done.

https://help.nextcloud.com/t/mail-ldap-ad-provisioned-account-and-disabled-ones/114234
