### ISSUE TITLE
KItinerary binary adapter is not available, can't extract information

### ISSUE THREAD

**Issue by mateumann** [nextcloud/mail#4948]
### Expected behavior
KItinerary binary would work

### Actual behavior
Warning log appers as stated

### Mail app

**Mail app version:**  1.9.5

**Mailserver or service:** private IMAP server

### Server configuration

**Operating system**: Debian GNU/Linux 10 on Raspberry Pi 4

**Web server:** Apache/2.4.38 (Debian)

**Database:** MariaDB 10.5.9

**PHP version:** 7.4.16

**Nextcloud Version:** 20.0.9

#### Client configuration
**Browser:** N/A

**Operating system:** N/A

----

The problem described is caused by the fact that `custom_apps/mail/vendor/christophwurst/kitinerary-bin/bin/kitinerary-extractor` installed from "App Store" (?) is a `x86-64` executable which of course won't work on an `aarch64` system.

```
# uname -a
Linux kube-worker-3 5.10.11-v8+ #1399 SMP PREEMPT Thu Jan 28 12:14:03 GMT 2021 aarch64 GNU/Linux

# file custom_apps/mail/vendor/christophwurst/kitinerary-bin/bin/kitinerary-extractor 
custom_apps/mail/vendor/christophwurst/kitinerary-bin/bin/kitinerary-extractor: ELF 64-bit LSB executable, x86-64, version 1 (GNU/Linux), dynamically linked, interpreter /lib64/ld-linux-x86-64.so.2, for GNU/Linux 3.0.0, BuildID[sha1]=a84dd8e4cafd7bc302582e8ea6f161a474aaa36a, stripped
```

**Comment by ChristophWurst** [comment]
yep https://github.com/nextcloud/mail/issues?q=is%3Aissue+%22KItinerary+binary+adapter+is+not+available%22

**Comment by mateumann** [comment]
I know there are "a few" issues concerning KItinerary already reported.  I didn't find any of them related to mixed architectures though.

**Comment by ChristophWurst** [comment]
No problem.

There are different reasons for why the binary can't be run. The effect is always the same and there is nothing really to do about it. As soon as there are app provided setup checks we can move this from a runtime log statement to something only the admin sees once.

**Comment by doc75** [comment]
#5999 will decrease the logging level to info (and reduce amount of logging message)
