### ISSUE TITLE
nonjunk and forwarded should not show as tags

### ISSUE THREAD

**Issue by GretaD** [nextcloud/mail#4951]
### Expected behavior
It is shown as flag and not tag

### Actual behavior
![database](https://user-images.githubusercontent.com/12728974/114716579-7a42f200-9d34-11eb-9e33-5a073b57646f.png)

### Mail app

**Mail app version:** master

cc @miaulalala

**Comment by ChristophWurst** [comment]
The standardized IMAP flags are `$junk` and `$notjunk`. `nonjunk`is added by Thunderbird: https://help.zoho.com/portal/ja/community/topic/all-new-incoming-mail-being-marked-with-nonjunk-tag

Maybe we can find how other web clients handle this? Do they filter out nonjunk?

**Comment by ChristophWurst** [comment]
`$forwarded` (`\Horde_Imap_Client::FLAG_FORWARDED`) is a standardized one. We should filter that out from tags.

**Comment by miaulalala** [comment]
Ok, so filter out the nojunk one and add the $forwarded to `$allowed`?

**Comment by ChristophWurst** [comment]
Yep, $forwarded is certainly missing from the list. With *nonjunk* we have to be a bit flexible. This is not the recommended flag according to the RFC, but it seems not all clients are strict: https://stackoverflow.com/a/47924882/2239067. That said, we might want to consider *junk* and *nonjunk* as special *flag* and ignore them for our tags.
