### ISSUE TITLE
Not all mails are showing up in the Inbox

### ISSUE THREAD

**Issue by feutl** [nextcloud/mail#4973]
### Expected behavior
Actually, seeing all mails of the Inbox instead of just "some"

### Actual behavior
I do only see 4 emails out of 16.
Other tools like rainloop or thunderbird see all of them. Even NC Mail says there are 16 mails, but not showing them in the view.

![image](https://user-images.githubusercontent.com/8522012/115698116-906c3600-a364-11eb-9dc6-52cf0d313a58.png)

### Mail app

**Mail app version:** 1.9.5

**Mailserver or service:** GMAIL

### Server configuration

**Operating system**: Debian 10

**Web server:** Apache

**Database:** MariaDB

**PHP version:** 7.3.27

**Nextcloud Version:** 20.0.1

#### Client configuration
**Browser:** Firefox 87, Edge 90

**Operating system:** Windows

**Comment by miaulalala** [comment]
Hi Herbert,

can you have a look at your browser's dev console to see if there are any JS errors?

Thanks,
Anna

**Comment by feutl** [comment]
Hi @miaulalala 
This are the "errors" I see, which one should I expand ?
![image](https://user-images.githubusercontent.com/8522012/116058573-447d0200-a680-11eb-9e89-d831e2589c7a.png)

![image](https://user-images.githubusercontent.com/8522012/116058746-6d9d9280-a680-11eb-8faa-56af6512a409.png)

What I did was opening Mail, and from there moving from the unified inbox to the "gmail" inbox.

**Comment by ChristophWurst** [comment]
> **Mailserver or service:** GMAIL

I have the same issue with gmail, and only with gmail. There were also reports before. I think this could be related to https://github.com/nextcloud/mail/issues/4762, so that our app deletes some messages from the cache before they actually vanished.

**Comment by feutl** [comment]
@ChristophWurst could be, looks similar :)
But I wonder where this "clear cache" button comes from which @zimmersi is using, so I could test this too.

**Comment by ChristophWurst** [comment]
> But I wonder where this "clear cache" button comes from which @zimmersi is using, so I could test this too.

Only shows when your instance is in debug mode :)

**Comment by joernu76** [comment]
I have the same(?) problem. Running current "stable" nextcloud on Rasbian. One(!) mail shown from 115. Accessing strato.de via IMAP.
The problem occurs since at least 20.x.

**Comment by ChristophWurst** [comment]
See https://github.com/nextcloud/mail/issues/4762

**Comment by joernu76** [comment]
I manually applied the fix from #4762 and restarted apache, but it has no effect on my inbox in nextcloud.

**Comment by ChristophWurst** [comment]
> I manually applied the fix from #4762 and restarted apache, but it has no effect on my inbox in nextcloud.

If you run into the bug described there then your cache won't fix itself. Messages that are reported to have vanished are deleted. There is no logic to retrieve them again. See https://tools.ietf.org/html/rfc3501 for details on how the synchronization works.

**Comment by joernu76** [comment]
So to properly test the fix I need to delete my mail-account on nextcloud and create it anew?

**Comment by ChristophWurst** [comment]
> Cool, that looks much better! I hope that this finally fixes the issue.

Whohoo. So you implicitly confirm that the patch linked works? :P

I'll try to send a friendly reminder to the Horde folks to get that patch in soonish.

**Comment by joernu76** [comment]
I cannot *prove* that it works, it sometimes worked before as well, but not for very long. 
But I played around now with two different nextcloud accounts and separate (both Strato based) mai accounts, sending mails, deleting, etc. and it seems very stable!
Nice.

**Comment by ChristophWurst** [comment]
Then let's close this one and continue in #4762.
