### ISSUE TITLE
Tag emails Replied / Forwarded

### ISSUE THREAD

**Issue by thstyl2000** [nextcloud/mail#4996]
### Feature Request

Having a way to quickly check if an email has been forwarded or replied would be great.

#### Summary

It could be done eg by having "undo/redo" arrows appearing next to the sender name, or in the bottom half of the avatar. I do not think hat this should be part of the manual tagging system, since it is more fundamental imo.

**Comment by ChristophWurst** [comment]
We have an indicator for *replied* but the svg icon somehow broke. You'll see the subject slightly indented.

The *forwarded* flag is in our current data structures but we don't show it. This is a rather easy change to have an icon for that as well.

**Comment by thstyl2000** [comment]
Cool, thanks!

**Comment by thstyl2000** [comment]
So I found it, namely special characters should not be escaped in `url(" ")` (with quotes) so that the background image in the _replied_ icon style should look like `url("<svg xmlns="http://www.w3.org/2000/svg"><path d="M15 15s-.4-7.8-7-10V1L1 8l7 7v-4c5.1 0 7 4 7 4z"></path></svg>")`.
But you already solved it by just using a real svg, so that I suppose that only the forwarded case is not implemented, right?

**Comment by ChristophWurst** [comment]
As far as I remember this broke when we changed/upgraded the svg loader or a similar webpack plugin
