### ISSUE TITLE
The application freezes and does not respond.

### ISSUE THREAD

**Issue by parus7** [nextcloud/mail#5000]
My manager likes to send emails without 
content, there is only a subject line and an attachment.
But in one of the letters the attachment to the letter is not visible, but in other email clients everything works well.  
Also, this email cannot be replied or forwarded.
The application freezes and does not respond. There are no errors in the log files. 
Other letters have not this problem. I can look and open attachment.

### Mail app

**Mail app version:** (see apps admin page, e.g. 0.5.3)

**Mailserver or service:** (e.g. Outlook, Yahoo, Gmail, Exchange,...)

### Server configuration

**Operating system**: 
kernel Linux 5.4.78-2-pve x86_64
$ cat /etc/os-release 
NAME="Ubuntu"
VERSION="20.04.1 LTS (Focal Fossa)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 20.04.1 LTS"
VERSION_ID="20.04"
UBUNTU_CODENAME=focal

**Web server:** (e.g. Apache, Nginx,...)
apache2 -v
Server version: Apache/2.4.41 (Ubuntu)
Server built:   2020-08-12T19:46:17

**Database:** (e.g. MariaDB, SQLite or PostgreSQL)
MariaDB  10.3.25

**PHP version:** (e.g. 7.0)
php -v
PHP 7.4.3 (cli) (built: Oct  6 2020 15:47:56) ( NTS )
Copyright (c) The PHP Group
Zend Engine v3.4.0, Copyright (c) Zend Technologies
with Zend OPcache v7.4.3, Copyright (c), by Zend Technologies

**Nextcloud Version:** (see admin page, e.g. 13.0.2)
Nextcloud 20.0.9
mail app version - 1.9.5
#### Client configuration
**Browser:** (e.g. Firefox 48)
Chromium 90.0.4430.85  Chrome 90.0.4430.93
 Firefox 87.0 Safary 14.0.1

[problem_mail.txt](https://github.com/nextcloud/mail/files/6397291/problem_mail.txt)
[console_messages.txt](https://github.com/nextcloud/mail/files/6397302/console_messages.txt)

Best regards

**Comment by miaulalala** [comment]
Hi @parus7 , unfortunately I can't reproduce this error. Do you have a way to access your nextcloud.log?

**Comment by parus7** [comment]
this issue is very similar to issue 4758. Similarly, it is not possible to see the attachment. There are no messages in the log files.
I later saw ChristophWurst merged commit 8d72028 on 26 Mar, but couldn't use it for myself. Maybe I can do it later.
