### ISSUE TITLE
Segmentation fault when syncing mail

### ISSUE THREAD

**Issue by Ta180m** [nextcloud/mail#5007]
### Expected behavior
`occ mail:account:sync 2` completes without an error.

### Actual behavior
A few days ago, the mail app stopped loading emails and instead just displayed "messages loading". I tried reinstalling the app, cleaning the database, but the problem still persists. However, I think the problem is when syncing, because when I try to do a manual sync with `occ mail:account:sync 2`, I get a segmentation fault.

In the Nextcloud log, the following error messages show up when trying to do a sync:
```
Error: Required parameter $pipeline follows optional parameter $msg at /var/lib/nextcloud/apps/mail/vendor/pear-pear.horde.org/Horde_Imap_Client/Horde/Imap/Client/Exception/ServerResponse.php#0
Error: Required parameter $server follows optional parameter $msg at /var/lib/nextcloud/apps/mail/vendor/pear-pear.horde.org/Horde_Imap_Client/Horde/Imap/Client/Exception/ServerResponse.php#52
```

Here is the output of `occ mail:account:sync 2`:
```
[debug] account is up to date, skipping mailbox sync
[debug] Skipping mailbox sync for [Gmail]
[debug] Skipping mailbox sync for [Gmail]/Drafts
[debug] Skipping mailbox sync for [Gmail]/Important
[debug] Skipping mailbox sync for [Gmail]/Sent Mail
[debug] Skipping mailbox sync for [Gmail]/Spam
[debug] Skipping mailbox sync for [Gmail]/Starred
[debug] Locking mailbox 10 for new messages sync
[debug] Locking mailbox 10 for changed messages sync
[debug] Locking mailbox 10 for vanished messages sync
[debug] partial sync 2:INBOX - get all known UIDs took 0s
[debug] partial sync 2:INBOX - get new messages via Horde took 1s
[debug] partial sync 2:INBOX - persist new messages took 0s
[debug] partial sync 2:INBOX - get changed messages via Horde took 1s
[debug] partial sync 2:INBOX - persist changed messages took 0s
[debug] partial sync 2:INBOX - get vanished messages via Horde took 0s
[debug] partial sync 2:INBOX - persist new messages took 0s
[debug] partial sync 2:INBOX took 2s
[debug] Unlocking mailbox 10 from vanished messages sync
/usr/bin/occ: line 45: 530826 Segmentation fault      sudo --preserve-env="${preserved_environment_vars}" -u "$user" "$php_command" -c "${config}" /usr/share/webapps/nextcloud/occ "$@"
```

### Mail app

**Mail app version:** 1.9.5

**Mailserver or service:** Gmail

### Server configuration

**Operating system**: Arch Linux

**Web server:** nginx

**Database:** PostgreSQL

**PHP version:** 8.0.5

**Nextcloud Version:** 21.0.1

#### Client configuration
**Browser:** Firefox 88

**Operating system:** Arch Linux

**Comment by ChristophWurst** [comment]
Did you update your php perhaps? Segmentation faults are rarely caused by php code but more commonly but bugs in the php runtime. What precise version of php do you run right now?

**Comment by Ta180m** [comment]
Thanks! I updated `php` to 8.0.6 and now sync completes without an error.
