### ISSUE TITLE
Mails fetched in background don’t get account color set (red instead)

### ISSUE THREAD

**Issue by jancborchardt** [nextcloud/mail#501]
See this – the newest 3 mails came in after the last full page refresh:
![screenshot from 2017-09-05 12-48-09](https://user-images.githubusercontent.com/925062/30057872-de05d63c-9238-11e7-92d9-d0820dc296b4.png)

**Comment by ChristophWurst** [comment]
Yeah, right. That's definitely a 🐛

**Comment by ChristophWurst** [comment]
Aaaaand fixed
