### ISSUE TITLE
Email Signature how append tags like <table>, <div> and inline styles (no replace by CKEDITOR)

### ISSUE THREAD

**Issue by kofston** [nextcloud/mail#5024]
#### Summary

Its a bug?
I can't add email signature correctly, all <table> , inline styles etc are replace with <p></p> tags.... 

Can i turn off it? (Maybe its a  CKEDITOR setting ? )

**Comment by ChristophWurst** [comment]
https://github.com/nextcloud/mail/issues/2263#issuecomment-581297850
