### ISSUE TITLE
Mail Viewer iFrame "iFrameResizer1" always 150px in height; Hardcoded HTTP htmlresponse.js

### ISSUE THREAD

**Issue by Routhinator** [nextcloud/mail#5032]
### Expected behavior
Mail content should be viewable.

### Actual behavior
Mail Viewer iFrame "iFrameResizer1" always 150px in height, likely because of a hardcoded HTTP url causing mixed content block on http://nextcloud.example.org/custom_apps/mail/js/htmlresponse.js

Newer versions of Firefox do not allow mixed content.

### Mail app

**Mail app version:** 0.9.5 (and all previous versions dating back to sometime in late 2020, I don't use the app much as I use clients. I basically ignored it for a long time thinking it would be fixed.)

**Mailserver or service:** Dovecot, using the ISP Caramel setup.

### Server configuration

**Operating system**: Nextcloud Helm Chart

**Web server:** Nextcloud Helm uses Official Apache Docker 20.0.9 image from Nextcloud, fronted by nginx-ingress.

**Database:** PostgreSQL

**PHP version:** Nextcloud Docker Apache version 20.0.9

**Nextcloud Version:** Nextcloud Docker Apache version 20.0.9

#### Client configuration
**Browser:** Firefox 88.0.1 (And all versions back to late 2020 as per above.)

**Operating system:** Ubuntu Linux

![Screenshot from 2021-05-15 13-07-58](https://user-images.githubusercontent.com/727535/118377249-fec9a000-b580-11eb-8aa0-c169933eb33d.png)

**Comment by miaulalala** [comment]
Might be ralted to #5008

**Comment by ChristophWurst** [comment]
:eyes: @st3iny

**Comment by st3iny** [comment]
This could be an issue with the configuration of your nextcloud instance. The url for the injected htmlresponse.js script is not hardcoded but generated by your instance on demand. If ssl termination is handled by another server (e.g. nginx revese proxy), your instance won't be able to correctly identify that https is used and generate a downgraded http url.

Please examine your nextcloud server configuration (`config/config.php`) and make sure that https is used for all generated urls:
```php
  'overwriteprotocol' => 'https',
```

More on that topic: https://docs.nextcloud.com/server/19/admin_manual/configuration_server/config_sample_php_parameters.html#proxy-configurations

I just spawned a new server using the official helm chart, configured nginx as a ssl reverse proxy and can confirm that the injected script will be loaded from `http://`. Regardless of this, my browser (Firefox v89.0b13) executes the script and renders the iframe correctly.

Let me know if this fixes the issue.

**Comment by Routhinator** [comment]
That setting worked. No idea why everything seems to have worked but this.. but it's fixed now!

**Comment by Nasjoe** [comment]
Hi. This settings not working for me.
I'm with a Nextcloud 22. Up with Docker. Behing a Traefik Proxy.
