### ISSUE TITLE
Adding additional modules to CK Editor 5 (Table, Images etc)

### ISSUE THREAD

**Issue by kofston** [nextcloud/mail#5033]
#### Summary

Hello!
I want ask you can i add new plugins (from node modules or somethink) to ckeditor? I want add table and images plugin for CK editor, because i want add HTML footer for my emails (signature).

Where i can find package.json or somethink? Can i add additional modules or somethink?

**Comment by ChristophWurst** [comment]
Duplicate of https://github.com/nextcloud/mail/issues/4707
