### ISSUE TITLE
ctrl+v paste images

### ISSUE THREAD

**Issue by Martin-Eckleben** [nextcloud/mail#5034]
Hi and thank you for your hard work!

A feature I miss is ctrl+v pasting images into a mail.
I’d totally be ready to try to implement it (I’m a pretty solid fullstack dev).
I’d try and post a PR on Github.

Is this a feature the maintainers would like and merge if done correctly?

**Comment by ChristophWurst** [comment]
See https://github.com/nextcloud/mail/issues/2052 and https://github.com/nextcloud/mail/issues/2733, especially https://github.com/nextcloud/mail/issues/2733#issuecomment-720989398

It's technically possible, but not easy. We can't use base64, we have to write a custom uploader for ckeditor, then serve the image from a custom endpoint as the user composes the message and before the message is sent we have to rewrite the HTML to switch from the temporary endpoint to references of the attached images.
