### ISSUE TITLE
Remember »Show images from this sender«

### ISSUE THREAD

**Issue by jancborchardt** [nextcloud/mail#505]
Clicking the button »Show images from this sender« should only be necessary once per sender. We should remember that you want to see images from this sender, which is the point of this button. ;)

cc @nextcloud/mail

**Comment by NESC1US** [comment]
it would be also nice to show the images after the button disappears, I see some octet streams, but those are never actually shown on the page.

**Comment by ChristophWurst** [comment]
> its been 3 years for this bug, maybe the feature is too big to be implemented, how about removing it completely?

Just needs someone to implement it :) Are you a developer or know someone who is?
