### ISSUE TITLE
Option to show/hide unread/total count

### ISSUE THREAD

**Issue by thstyl2000** [nextcloud/mail#5056]
### Feature Request

It would be great to have an option to show or hide the unread and total mail counter  (#4969)  in each folder.

#### Summary

Trying to work with a zero inbox, one has to file messages to different folders according to type/priority. Having a total message counter helps keeping track, and the ability to toggle the counter on/off could be useful for other workflows.

**Comment by ChristophWurst** [comment]
we try to keep the number of settings to a reasonable minimum. I'd say a toggle for this counter is quite an overkill. Is there any downside to seeing the number by default?

**Comment by ChristophWurst** [comment]
Do you mean when the counter is at zero? We could hide it in that case.

**Comment by thstyl2000** [comment]
Nope, a "zero inbox" approach is a system in which each email is either directly replied, or deleted, or refiled, or archived, so that the inbox remains empty (like the real letterbox). Here is a very nice exposition.

https://blog.hubspot.com/service/inbox-zero

(sorry, cannot add links with chrome on android?!)

**Comment by ChristophWurst** [comment]
I'm familiar with inbox zero.

Nevertheless I don't see a strong need for a setting just to hide the counter for this purpose.
