### ISSUE TITLE
New mail exists in inbox but is not shown in the list

### ISSUE THREAD

**Issue by thstyl2000** [nextcloud/mail#5058]
### Expected behavior
One should see new emails.

### Actual behavior
Message does not appear, instead "No messages in this mailbox" is shown (see attached screenshot). `occ mail:account:sync` does not throw any errors.
![Screenshot_20210520_130235](https://user-images.githubusercontent.com/18458458/118969355-40858c80-b96d-11eb-8567-3d6c8bec043b.png)

### Mail app

**Mail app version:** 1.9.5
**Mailserver or service:** IMAP

### Server configuration

**Operating system**: FreeBSD 12.2 Jail

**Web server:** Apache

**Database:** MariaDB

**PHP version:** 8.0

**Nextcloud Version:** 21.0.1

#### Client configuration
**Browser:** Chrome

**Operating system:** Ubuntu

**Comment by ChristophWurst** [comment]
> **Mailserver or service:** IMAP

We only support IMAP. What provider is that? Is this gmail by any chance?

See https://github.com/nextcloud/mail/issues/4762 for a likely related bug.

**Comment by thstyl2000** [comment]
Nope, it is a dovecot behind an apache. (Yes, IMAP is a stupid answer....)

**Comment by thstyl2000** [comment]
To be more precise, it is a specific message that does not appear. Newer messages display fine.

**Comment by thstyl2000** [comment]
So after moving the message around it a bit it reappeared. Closing.
