### ISSUE TITLE
Locked Mailbox didn't unlock automatically

### ISSUE THREAD

**Issue by Bubu** [nextcloud/mail#5061]
### Expected behavior
Mail accounts loads (eventually).

### Actual behavior
After some recent update my mailbox didn't load anymore (since 2 weeks or so, I had no time to investigate inbetween). The logs perpetually showed the 409 "Mailbox is locked error". (yes, it didn't unlock for weeks, apparently?)

I ended up in https://github.com/nextcloud/mail/issues/3159 and tried the troubleshooting steps there:

```
IMAP capabilities:
- AUTH
- ENABLE
- ID
- IDLE
- IMAP4REV1
- LITERAL+
- LOGIN-REFERRALS
- SASL-IR

Account has 85951 messages in 14 mailboxes
```

Trying `sync` it told me:
```
In MailboxLockedException.php line 33:
                              
  47 is already being synced  
```

it wasn't syncing in the background though, no new mails were being added.

I tried the `--force` option. That completed within a few seconds. Everything seems to be working now. I still wanted to report the issue.

### Mail app

**Mail app version:** 1.9.5
**Mailserver or service:** dovecot 2.3.14

### Server configuration

**Operating system**: Archlinux

**Web server:** Nginx

**Database:**Postgres

**PHP version:** 8.0.6

**Nextcloud Version:** 21.0.1

#### Client configuration
**Browser:** FF 88.0.1

**Operating system:** Archlinux

**Comment by miaulalala** [comment]
Hi Bubu, thanks for your report! We are aware of this and it will be fixed in the next release!

**Comment by Bubu** [comment]
Hi @miaulalala thanks for looking at this, could you link to the commit that fixed this?

**Comment by miaulalala** [comment]
#4812 is the main ticket we're working with and #4819 is the PR.
