### ISSUE TITLE
Curser doesn't move in plain text editor

### ISSUE THREAD

**Issue by davidpr78** [nextcloud/mail#5068]
### Expected behavior
You can type words. 

### Actual behavior
You can't type words because the curser always moves back to the left. 

### Mail app

**Mail app version:** (see apps admin page, e.g. 0.5.3)
1.9.5

**Mailserver or service:** (e.g. Outlook, Yahoo, Gmail, Exchange,...)
WebhostOne

### Server configuration

edudocs.de 

**Operating system**: (e.g. Debian 8)

**Web server:** (e.g. Apache, Nginx,...)

**Database:** (e.g. MariaDB, SQLite or PostgreSQL)

**PHP version:** (e.g. 7.0)

**Nextcloud Version:** (see admin page, e.g. 13.0.2)
20

#### Client configuration
**Browser:** (e.g. Firefox 48)
Safari

**Operating system:** (e.g. Arch Linux)
iOS 14.5.1

**Comment by ChristophWurst** [comment]
> iOS 14.5.1

in https://github.com/nextcloud/mail/issues/5057 we found other issues with ios. Could you check if the editor works for you?

**Comment by davidpr78** [comment]
It does. I can also paste text.
