### ISSUE TITLE
Missing visual message drop target

### ISSUE THREAD

**Issue by kesselb** [nextcloud/mail#5071]
https://user-images.githubusercontent.com/3902676/119572138-99608500-bdb2-11eb-96aa-d70fe942a981.mp4

**How to reproduce**

- Open a thread
- Drag a message from conversation view to another mailbox

**Mail app version** master

**Comment by GretaD** [comment]
The scope of this Issue should change, the drag and drop now works, the problem is that you cannot visually see which mailbox is selected.

[Screencast from 23.09.2022 15:03:46.webm](https://user-images.githubusercontent.com/12728974/191966647-fcb12c43-cee0-44dc-91ce-d8137d7d4493.webm)
