### ISSUE TITLE
Manual refresh needed on browser restart

### ISSUE THREAD

**Issue by jancborchardt** [nextcloud/mail#508]
### Steps to reproduce
1. Have Nextcloud Mail as a pinned tab in Firefox for example
2. Restart your computer
3. Open the browser

### Expected behaviour
The Mail app should load directly.

### Actual behaviour
Instead it’s stuck at a GET request, showing only two spinners, and you need to manually refresh.

@nextcloud/mail

**Comment by skjnldsv** [comment]
It's the same on the contact app :)

**Comment by ChristophWurst** [comment]
Dup of https://github.com/nextcloud/mail/issues/322, fix at https://github.com/nextcloud/server/pull/6360 ;-)

**Comment by jancborchardt** [comment]
@ChristophWurst haha great timing :) thanks!
