### ISSUE TITLE
Edit tag display name

### ISSUE THREAD

**Issue by kesselb** [nextcloud/mail#5085]
### Feature Request

As user I would like to change the display name of a tag.

**Comment by ChristophWurst** [comment]
@nextcloud/designers may I ask for you input on this one? Our current status is that as a user you can see five default tags that every users has. There is an action on every envelope that open a modal where you can add and remove those tags. Additionally there is an input at the bottom to add a new tag on the fly.

Now, as a user I would occasionally like to rename one of those tags that I added, for example when I made a typo.

Where would you expect to find a dialog that allows you to do this? A bit of technical detail: we store tags per user, not per account. If you have two accounts and in account 1 you tag a message with "nextcloud" then you will see this tag for selection next time you tag in account 2. Therefore I have the feeling that we can't just put the tag management into the account settings, as there is no relation to that account. Each account would show the same tags. I find that idea a bit confusing.

Alternatively there could be a "global" settings modal for any Mail related settings of the user. They could manage their tags there. This is also what Thunderbird does. You can tag a message with the existing tags that are configured, but if you change the tags then you will be taken to the global settings.

What do you think?

**Comment by jancborchardt** [comment]
@ChristophWurst first expectation I had was also the account settings, also cause I would expect tags to be account-specific, as in tied to a server (like Gmail labels are).

When the settings which are currently in the bottom left and not in a modal yet (like shortcuts, adding a new account etc) move into a modal, the tag management could move in there too though.
