### ISSUE TITLE
IMAP inbox - keeps loading messages - folders OK

### ISSUE THREAD

**Issue by tobefrank1** [nextcloud/mail#5103]
### Expected behavior
Show the Inbox mails.

### Actual behaviour

I am able to log into my IMAP post-box, but the Inbox folder does not show any messages, but keeps on loading messages.
The strange thing is that the folders are accessible and mails in the folders are shown. 
Tried to purge mail as in admin docs, reinstalled several times, tried to unlock and everything I could find on the internet, Nothing works. 
The account works fine with Outlook or Thunderbird etc. no issues. 

Also strange is, that a different account form a different provider runs well.   

For any clue I would be thankful. 

### Mail app

**Mail app version:** 
1.9.5
**Mailserver or service:** 
IMAP  

### Server configuration

**Operating system**:  Ubuntu Server 20.01

**Web server:** Nginx 

**Database:**  MariaDB,

**PHP version:**  8.0

**Nextcloud Version:** 21.0.2)

#### Client configuration
**Browser:** (e.g. Firefox, Chrome)

**Operating system:** (e.g. Arch Linux)
Win 10

**Comment by ChristophWurst** [comment]
You've already discovered our admin docs. Please see the section on logging. It would be very insightful to know if either the nextcloud.log or the horde_imap.log show indications of an error during the synchronization.

**Comment by tobefrank1** [comment]
Hello Chirstoph,

thank you for your quick response and help. 

As I am not familiar with debugging, finding and creating logs, I still hope the following information might help.


1. I tried  occ mail:account:sync  1 - because it could  be a syncing problem: 

[debug] account is up to date, skipping mailbox sync
[debug] Skipping mailbox sync for Drafts
[debug] Skipping mailbox sync for Trash
[debug] Skipping mailbox sync for INBOX.Gesendete Elemente
[debug] Skipping mailbox sync for INBOX.Folders
[debug] Skipping mailbox sync for INBOX.Folders.PK Oven 7
[debug] Skipping mailbox sync for INBOX.Folders.Privat
[debug] Skipping mailbox sync for INBOX.Folders.Privat.IMDS
[debug] Skipping mailbox sync for INBOX.Folders.IMDS
[debug] Skipping mailbox sync for INBOX.Folders.ISO
[debug] Skipping mailbox sync for INBOX.Gelöschte Elemente
[debug] Skipping mailbox sync for INBOX.Entwürfe
[debug] Skipping mailbox sync for INBOX.Junk-E-Mail
[debug] Skipping mailbox sync for Junk
[debug] Skipping mailbox sync for Sent
[debug] Locking mailbox 15 for new messages sync
[debug] Locking mailbox 15 for changed messages sync
[debug] Locking mailbox 15 for vanished messages sync
[debug] Initial sync 1:INBOX - fetch all messages from IMAP took 1s
[debug] Unlocking mailbox 15 from vanished messages sync
[debug] Unlocking mailbox 15 from changed messages sync
[debug] Unlocking mailbox 15 from new messages sync
In ImapToDbSynchronizer.php line 238:
  Sync failed for 1:INBOX: An exception occurred while executing a query: SQLSTATE[22003]: Numeric value out of range: 1264 Out of range value for column 'uid' at row 1
In ExceptionConverter.php line 114:
  An exception occurred while executing a query: SQLSTATE[22003]: Numeric value out of range: 1264 Out of range value for column 'uid' at row 1
In Exception.php line 26:
  SQLSTATE[22003]: Numeric value out of range: 1264 Out of range value for column 'uid' at row 1
In Statement.php line 82:
  SQLSTATE[22003]: Numeric value out of range: 1264 Out of range value for column 'uid' at row 1

mail:account:sync [-f|--force] [--] <account-id>

2. I tried to get some information out of the Nextcloud logfile: 

{"reqId":"xxxxxxx","level":0,"time":"June 02, 2021 08:37:36","remoteAddr":"xxxxxxxx","user":"xxxxxx","app":"files_external","method":"GET","url":"/apps/mail/api/messages?mailboxId=15&limit=20","message":"/appinfo/app.php is deprecated, use \\OCP\\App>{"reqId":"xxxx","level":0,"time":"June 02, 2021 08:37:36","remoteAddr":"xxxxxxxxx","user":"xxxxxx","app":"files_sharing","method":"GET","url":"/apps/mail/api/messages?mailboxId=15&limit=20","message":"/appinfo/app.php is deprecated, use \\OCP\\AppF>{"reqId":"xxxxx","level":0,"time":"June 02, 2021 08:37:36","remoteAddr":"xXXXXXXXX","user":"XXXXX","app":"mail","method":"GET","url":"/apps/mail/api/messages?mailboxId=15&limit=20","message":"loading messages of folder <15>","userAgent":"Mozilla/5.>

**Comment by ChristophWurst** [comment]
> Out of range value for column 'uid'

Could you inspect your database to find out the current column type and size of oc_mail_messages.uid? It looks like the UID of one of your messages has a value too large for the column.

**Comment by tobefrank1** [comment]
I have no idea how to to this. Could you give me some advice?

**Comment by tobefrank1** [comment]
I have copied all my INBOX mails to an Inbox copy folder, pured mail and reinstalled. With no mail in the inbox it looked fine, but as soon as I send a test mail and try to see it in the inbox folder, the error came back "loading messages" . 
I can see my mails in the Inbox copy folder with no problems. 

mail:account:sync  did not show any thing usefull. 


mail:account:sync  1
[debug] account is up to date, skipping mailbox sync
[debug] Skipping mailbox sync for Drafts
[debug] Skipping mailbox sync for Trash
[debug] Skipping mailbox sync for INBOX.Gesendete Elemente
[debug] Skipping mailbox sync for INBOX.Folders
[debug] Skipping mailbox sync for INBOX.Folders.PK Oven 7
[debug] Skipping mailbox sync for INBOX.Folders.INBOXCOPY
[debug] Skipping mailbox sync for INBOX.Folders.Privat
[debug] Skipping mailbox sync for INBOX.Folders.Privat.IMDS
[debug] Skipping mailbox sync for INBOX.Folders.IMDS
[debug] Skipping mailbox sync for INBOX.Folders.ISO
[debug] Skipping mailbox sync for INBOX.Gelöschte Elemente
[debug] Skipping mailbox sync for INBOX.Entwürfe
[debug] Skipping mailbox sync for INBOX.Junk-E-Mail
[debug] Skipping mailbox sync for Junk
[debug] Skipping mailbox sync for Sent
[debug] Locking mailbox 16 for new messages sync

In MailboxLockedException.php line 33:

  16 is already being synced

**Comment by ChristophWurst** [comment]
> I have no idea how to to this. Could you give me some advice?

https://stackoverflow.com/a/31830486

**Comment by tobefrank1** [comment]
Dear all,

As other IMAP-Mail server did work with no issues. I solved this strange issue by changing the postbox within my provider.
Therefore it may not be a Nextcloud-Mail problem.  
Thank you.
