### ISSUE TITLE
Migrate from composer v1 to composer v2

### ISSUE THREAD

**Issue by LukasReschke** [nextcloud/mail#5136]
On current master (e7b92945281eaeab9d9d9d1e60a19d1fda359183):

```
lukasreschke@Lukass-Air mail % make dev-setup
composer install -o

                                                          
  [RuntimeException]                                      
  The PEAR repository has been removed from Composer 2.0  
                                                          

make: *** [install-composer-deps-dev] Error 1
```
---

Migrate Mail from composer v1 to composer v2, because v1 has been deprecated and will stop working soon.

- [ ] Help migrate the Horde packages from PEAR to packagist upstream
- [ ] Check if any other packages require migration

**Comment by ChristophWurst** [comment]
yeah … you need composer v1. There are some attempts at the Horde project to bring their packages over but I think those stalled. There is nothing we can do here at the moment :/

**Comment by szaimen** [comment]
I have the same problem

**Comment by ChristophWurst** [comment]
tracked in https://github.com/orgs/nextcloud/projects/45#card-67313209 and will be taken in consideration for the next planning

**Comment by HLFH** [comment]
Link to composer v1: https://getcomposer.org/download/1.10.22/composer.phar

**Comment by ChristophWurst** [comment]
Ref https://github.com/composer/composer/issues/8778#issuecomment-717050280

**Comment by szaimen** [comment]
🎉
