### ISSUE TITLE
unread messages count missing in tab title when red dot appears

### ISSUE THREAD

**Issue by fsedarkalex** [nextcloud/mail#514]
> Probably. I think we don't synchronize the number of unread messages when we sync new/changed/vanished messages in background. Please file an issue and I'll take a look at this.

Did so. :+1: 

There is no number of unread messages in tab title when red dot appears.
followup to PR 499

**Comment by ChristophWurst** [comment]
Thanks

**Comment by ChristophWurst** [comment]
we don't have that dot indicator anymore, so this bug is outdated
