### ISSUE TITLE
Revised draft is not saved properly

### ISSUE THREAD

**Issue by rollanders** [nextcloud/mail#5148]
### Expected behavior
I write a draft and get an indication that it is saved. I do some other stuff. I return to the draft and add new things. I get an indication that the (revised) draft is saved. When returning to the draft a third time I expect that the revision should be included.   

### Actual behavior
The revisions are not included. I only get the first draft.  

### Mail app

**Mail app version:** (see apps admin page, e.g. 0.5.3)
1.4.2

**Mailserver or service:** (e.g. Outlook, Yahoo, Gmail, Exchange,...)
Other - coupled with IMAP and SMTP

### Server configuration
**Operating system**: (e.g. Debian 8)
I think it is Ubuntu 18.0.4 but the system say
Linux 4.15.0-70-generic x86_64

**Web server:** (e.g. Apache, Nginx,...)
Nginx
**Database:** (e.g. MariaDB, SQLite or PostgreSQL)
MariaDB
**PHP version:** (e.g. 7.0)
7.3.22
**Nextcloud Version:** (see admin page, e.g. 13.0.2)
19.0.8

#### Client configuration
**Browser:** (e.g. Firefox 48)
Chrome
**Operating system:** (e.g. Arch Linux)
Windows 10

**Comment by rollanders** [comment]
Same behaviour with Mail 1.9.5 in NC 21.0.2, Ubuntu 20.0.4 PHP 8.0.

In the log an error related to Mail
[mail] Warning: KItinerary binary adapter is not available, can't extract information

The saving of the draft is now very much delayed. When the saving of the draft happens the last draft is sometimes removed from the column with all drafts (the first draft in the column disappeares and the remaining are moved upwards one position) when the delayed saving of the draft happens.

**Comment by ChristophWurst** [comment]
Drafts are a bit of an issue, we are aware of that. We've had a few discussions around the feature and possible alternative solutions but as of now there is no concept that could work better. Due to the fact that IMAP messages are immutable we have to create a new message for every new version and delete the previous one. In combination with auto save there is a lot of concurrency going on. It seems we are not handling that very well.

**Comment by rollanders** [comment]
Sometimes the last added draft (on top in the column) disappears and then reappers after a few seconds.

**Comment by ChristophWurst** [comment]
This could have to do with the asynchronous synchronization of the mailbox. If you open the browser's dev tools you might see a sync request when that happens.

**Comment by rollanders** [comment]
OK. So draft is not usable? With the current long delay the first draft risk not to be saved, and repeated revisions are not saved. 
One of our customers complains that each time she make a revision there is another draft created. I cannot confirm that behaviour though.

**Comment by ChristophWurst** [comment]
> One of our customers complains that each time she make a revision there is another draft created. I cannot confirm that behaviour though.

Yes, as explained

> Due to the fact that IMAP messages are immutable we have to create a new message for every new version and delete the previous one.

> So draft is not usable?

That would be quite an exaggeration. There are problems, but they not unusable.

**Comment by ChristophWurst** [comment]
this can be closed as duplicate of https://github.com/nextcloud/mail/issues/4768
