### ISSUE TITLE
Gnome Evolution compatibility

### ISSUE THREAD

**Issue by ChristophWurst** [nextcloud/mail#5150]
If you tag a message as important we assign `$label1`. So does Thunderbird. Gnome Evolution shows the message as important. BUT if you first flag as important in Evolution, then `$labelimportant` will be used and our app creates a new tag with display name `labelimportant`.

### Expected behavior

We have five hard coded rules to treat the Evolution labels like the one from Thunderbird, the app must not create new tags.

### Actual behavior

![Bildschirmfoto von 2021-06-09 17-41-28](https://user-images.githubusercontent.com/1374172/121386575-6689c580-c94a-11eb-912a-00d6967dbe29.png)

![Bildschirmfoto von 2021-06-09 17-45-59](https://user-images.githubusercontent.com/1374172/121386969-9507a080-c94a-11eb-98ee-96b69307efef.png)

### Mail app

**Mail app version:** master

**Comment by miaulalala** [comment]
I'd love to add an `also_known_as` column to the DB but I fear this will just grow into a monster. Thoughts?

**Comment by ChristophWurst** [comment]
The list won't be static and identical for every user's `$label1`. So any time we find another alias that we want to map we have to update all existing rows of this imap label for every user. Additionally DBs aren't really meant for multi value colums, so we'd need our own serialization and deserialization when a single column can hold n values.

The complexity is indeed not worth it. Let's just map this in application code, where we can unit test and add new mapping dynamically.
