### ISSUE TITLE
Fit the app-navigation to css guidelines [$20]

### ISSUE THREAD

**Issue by skjnldsv** [nextcloud/mail#516]
Refs: https://docs.nextcloud.com/server/12/developer_manual/app/css.html

**Comment by skjnldsv** [comment]
Blocked by #528

**Comment by ChristophWurst** [comment]
@nextcloud/mail FYI if we don't come up with a solution for this issue (the app looks totally crappy at the moment) I will tag this app as incompatible with NC13 and also upload a patch release to the app store to make sure people don't install a non-compatible app.

Unfortunately, this shouldn't even have happened but I've made the mistake (again, happened with the TOTP app too already) of uploading a release to the app store that was compatible with the upcoming Nextcloud server. As things are likely to break (we're not as stable as I wish we were) we should never ever release any app as compatible with anything newer than the latest stable release of the Nextcloud server.

**Comment by skjnldsv** [comment]
Can we close this then? :)

**Comment by ChristophWurst** [comment]
Sure. @skjnldsv don't forget to claim your bounty at https://www.bountysource.com/issues/49232072-fit-the-app-navigation-to-css-guidelines 😉
