### ISSUE TITLE
Folder sync issue

### ISSUE THREAD

**Issue by mchobbel** [nextcloud/mail#5164]
### Expected behavior

After I created a new IMAP-folder in Thunderbird this folder should appear in Nextcloud.

### Actual behavior
The new IMAP-folder does not show in Nextcloud.

The only way for me to get the new folder in Nextcloud is by removing the IMAP-account from nextcloud and then adding it again.

### Mail app

**Mail app version: ** 1.9.5 

**Mailserver or service: ** Dovecot

### Server configuration

**Operating system De**: Debian 10

**Web server:** Apache

**Database:** MariaDB

**PHP version:** 7.4.6

**Nextcloud Version:** 21.0.2

#### Client configuration
**Browser:** : Firefox 88

**Operating system:** Linux

**Comment by miaulalala** [comment]
Hi! Do you have anything in you horde_imap.log file when you search for the newly created folder name?

**Comment by mchobbel** [comment]
No errors in the horder_imap.log. But what is interesting: after toggling the Show only subscribed checkbox on and off I can see the client requesting the folder list :

` C: 2 LIST () "" (*) RETURN (SUBSCRIBED SPECIAL-USE) `

and in the server-response I can see the new folder-name is present. But still it doesn't appear in the UI.

Nb. I also used the Mutt Imap client to verify that the server is working correct.

**Comment by miaulalala** [comment]
Can you check your `oc_mail_mailboxes` table for the entry that belongs to this folder and tell me what it says?

**Comment by mchobbel** [comment]
The new folder is not present in oc_mail_mailboxes

**Comment by miaulalala** [comment]
Can you check your Dovecot namespaces and check what is set for the `auto` option and `special_use` option? Are you subscribed to the folder?

**Comment by mchobbel** [comment]
Yes, I am subscribed to the folder. Let me add IMAP response to the LIST command:

```C: 2 LIST () "" (*) RETURN (SUBSCRIBED SPECIAL-USE)
S: * LIST (\Subscribed \UnMarked) "/" subfolder2
S: * LIST (\Subscribed \UnMarked) "/" sub1
S: * LIST (\Subscribed \UnMarked \Trash) "/" Trash
S: * LIST (\Subscribed \UnMarked \Sent) "/" Sent
S: * LIST (\Subscribed \UnMarked) "/" Verzonden
S: * LIST (\Subscribed \UnMarked) "/" ost_done
S: * LIST (\Subscribed \UnMarked) "/" INBOX/test1
S: * LIST (\Subscribed) "/" gdw_nl
S: * LIST (\Subscribed) "/" gdw_nl2
S: * LIST (\Subscribed \UnMarked) "/" gdw_nl2/stest3
S: * LIST (\UnMarked) "/" gdw_nl2/test3
S: * LIST (\Subscribed \UnMarked) "/" gdw_nl2/test2
S: * LIST (\NonExistent) "/" gdw_nl3
S: * LIST (\Subscribed \UnMarked) "/" gdw_nl3/done1
S: * LIST () "/" test1_nc_qf
S: * LIST (\UnMarked) "/" test1_nc_qf/done2
S: * LIST (\UnMarked) "/" test1_nc_qf/done
S: * LIST (\NonExistent) "/" Egroupware_tot_okt_2020
S: * LIST (\Subscribed) "/" INBOX
S: 2 OK List completed (0.005 + 0.000 + 0.004 secs).
>> Command 2 took 0.005 seconds.
C: 3 STATUS subfolder2 (MESSAGES RECENT UIDNEXT UIDVALIDITY UNSEEN)
S: * STATUS subfolder2 (MESSAGES 1 RECENT 0 UIDNEXT 2 UIDVALIDITY 1610536818 UNSEEN 0)
S: 3 OK Status completed (0.001 + 0.000 secs).
>> Command 3 took 0.0041 seconds.
```

Here you can see that `subfolder2` (yes, this is the one) has the Subscribed flag and has no special use flags. ( interesting to see that the client does a status-request for `subfolfder2` i.e. this folder is not completely ignored by Nextcloud.)

As for the auto setting. I have no auto settings configured in my dovecot config. The auto related stuff in `conf.d/15-mailboxes.conf`  is commented out

**Comment by miaulalala** [comment]
Thanks, that will help a lot! I'll debug some more and get back to you.

**Comment by miaulalala** [comment]
Hi, has the folder appeared now? I've found out that there is a two hour delay between folder syncs at the moment, but we're working on creating a force sync button so this process can be triggered manually.

**Comment by mchobbel** [comment]
Yep. It's there now alright! Thanks for working on this. It would be a nice improvement indeed.
