### ISSUE TITLE
Sharing a webpage via email leads to exception

### ISSUE THREAD

**Issue by thstyl2000** [nextcloud/mail#5169]
### Expected behavior
Nextcloud Mail is set as default email app. Clicking on a "share this webpage" link on some webpage should open the mail app composer with some predefined message containing a link.

### Actual behavior
It  throws an internal server error with the following log:

```
{
  "reqId": "3DzPmdpPFqwd8hWwEezl",
  "level": 3,
  "time": "2021-06-11T14:26:55+00:00",
  "remoteAddr": "xxx.xxx.xxx.xxx",
  "user": "xxxxxxxxxxx",
  "app": "index",
  "method": "GET",
  "url": "/apps/mail/compose?uri=mailto%3A%3Fsubject%3DMaths%2520Teachers%2520Day%2520%25E2%2580%25A2%2520University%2520of%2520Passau%26body%3Dhttps%253A%252F%252Fwww.uni-passau.de%252Fen%252Fdmv-oemg-jahrestagung-2021%252Fmaths-teachers-day%252F",
  "message": {
    "Exception": "Exception",
    "Message": "OCA\\Mail\\Controller\\PageController::compose(): Argument #1 ($uri) must be of type string, null given, called in /usr/local/www/nextcloud/lib/private/AppFramework/Http/Dispatcher.php on line 218",
    "Code": 0,
    "Trace": [
      {
        "file": "/usr/local/www/nextcloud/lib/private/AppFramework/App.php",
        "line": 157,
        "function": "dispatch",
        "class": "OC\\AppFramework\\Http\\Dispatcher",
        "type": "->"
      },
      {
        "file": "/usr/local/www/nextcloud/lib/private/Route/Router.php",
        "line": 302,
        "function": "main",
        "class": "OC\\AppFramework\\App",
        "type": "::"
      },
      {
        "file": "/usr/local/www/nextcloud/lib/base.php",
        "line": 993,
        "function": "match",
        "class": "OC\\Route\\Router",
        "type": "->"
      },
      {
        "file": "/usr/local/www/nextcloud/index.php",
        "line": 37,
        "function": "handleRequest",
        "class": "OC",
        "type": "::"
      }
    ],
    "File": "/usr/local/www/nextcloud/lib/private/AppFramework/Http/Dispatcher.php",
    "Line": 159,
    "Previous": {
      "Exception": "TypeError",
      "Message": "OCA\\Mail\\Controller\\PageController::compose(): Argument #1 ($uri) must be of type string, null given, called in /usr/local/www/nextcloud/lib/private/AppFramework/Http/Dispatcher.php on line 218",
      "Code": 0,
      "Trace": [
        {
          "file": "/usr/local/www/nextcloud/lib/private/AppFramework/Http/Dispatcher.php",
          "line": 218,
          "function": "compose",
          "class": "OCA\\Mail\\Controller\\PageController",
          "type": "->"
        },
        {
          "file": "/usr/local/www/nextcloud/lib/private/AppFramework/Http/Dispatcher.php",
          "line": 127,
          "function": "executeController",
          "class": "OC\\AppFramework\\Http\\Dispatcher",
          "type": "->"
        },
        {
          "file": "/usr/local/www/nextcloud/lib/private/AppFramework/App.php",
          "line": 157,
          "function": "dispatch",
          "class": "OC\\AppFramework\\Http\\Dispatcher",
          "type": "->"
        },
        {
          "file": "/usr/local/www/nextcloud/lib/private/Route/Router.php",
          "line": 302,
          "function": "main",
          "class": "OC\\AppFramework\\App",
          "type": "::"
        },
        {
          "file": "/usr/local/www/nextcloud/lib/base.php",
          "line": 993,
          "function": "match",
          "class": "OC\\Route\\Router",
          "type": "->"
        },
        {
          "file": "/usr/local/www/nextcloud/index.php",
          "line": 37,
          "function": "handleRequest",
          "class": "OC",
          "type": "::"
        }
      ],
      "File": "/usr/local/www/nextcloud/apps/mail/lib/Controller/PageController.php",
      "Line": 211
    },
    "CustomMessage": "--"
  },
  "userAgent": "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.77 Safari/537.36",
  "version": "21.0.2.1",
  "id": "60c375321a201"
}
```

### Mail app

**Mail app version:** 1.9.5

**Mailserver or service:** dovecot imap

### Server configuration

**Operating system**: freebsd 12

**Web server:** apache

**Database:** MariaDB

**PHP version:** 8.0

**Nextcloud Version:** 21.0.2

#### Client configuration
**Browser:** Chrome Version 91.0.4472.101 (Official Build) (64-bit)

**Operating system:** Ubuntu 20.04

**Comment by ChristophWurst** [comment]
You already shared the link - kind of :wink: - mind copying the raw `mailto:....` link and pasting it us here for us so we can test with the same?

**Comment by thstyl2000** [comment]
Thanks for the response! There it is:

```
<a href="mailto:?subject=&amp;body=:%20" target="_blank" title="Send email" onclick="window.open('mailto:?subject=' + encodeURIComponent(document.title) + '&amp;body=' + encodeURIComponent(document.URL)); return false;"><svg class="svg-inline--fa fa-envelope-square fa-w-14 fa-fw" aria-hidden="true" data-prefix="fas" data-icon="envelope-square" role="img" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 448 512" data-fa-i2svg=""><path fill="currentColor" d="M400 32H48C21.49 32 0 53.49 0 80v352c0 26.51 21.49 48 48 48h352c26.51 0 48-21.49 48-48V80c0-26.51-21.49-48-48-48zM178.117 262.104C87.429 196.287 88.353 196.121 64 177.167V152c0-13.255 10.745-24 24-24h272c13.255 0 24 10.745 24 24v25.167c-24.371 18.969-23.434 19.124-114.117 84.938-10.5 7.655-31.392 26.12-45.883 25.894-14.503.218-35.367-18.227-45.883-25.895zM384 217.775V360c0 13.255-10.745 24-24 24H88c-13.255 0-24-10.745-24-24V217.775c13.958 10.794 33.329 25.236 95.303 70.214 14.162 10.341 37.975 32.145 64.694 32.01 26.887.134 51.037-22.041 64.72-32.025 61.958-44.965 81.325-59.406 95.283-70.199z"></path></svg><!-- <i class="fas fa-fw fa-envelope-square"></i> --><span class="sr-only">Per E-Mail senden</span></a>
```

In case this does not work, [here is the webpage](https://www.uni-passau.de/dmv-oemg-2021/lehrerinnentag/). The share button is at the bottom.

**Comment by thstyl2000** [comment]
I don't know if this is related, but the following mailto link is not working (leads to 502 error):

`<a href="mailto:admin@waves.kit.edu?subject=%5Bsummer21%5D%20Registration&amp;body=Dear%20organizers%20of%20this%20year's%20CRC%201173%20Summer%20School%20%C2%BBWave%20Phenomena%3A%20Analysis%20and%20Numerics%C2%AB%2C%0D%0A%0D%0Aplease%20register%20me%20with%20the%20following%20details%20to%20your%20summer%20school.%0D%0A%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%0D%0AForename%3A%0D%0ASurename%3A%0D%0AEmail%3A%0D%0AInstitution%3A%0D%0APosition%3A%20(student%2C%20Ph.D.%20student%2C%20postdoc)%0D%0A---------------------------------------------------------------------%0D%0AFor%20master%20students.%0D%0A(Preliminary)%20topic%20Master%20thesis%3A%0D%0AAdvisor%20of%20thesis%3A%0D%0A---------------------------------------------------------------------%0D%0AFor%20Ph.D.%20students.%0D%0AStart%20of%20Ph.D.%20on%3A%20(mm%2Fyy)%0D%0A(Preliminary)%20topic%20of%20Ph.D.%20thesis%3A%0D%0AAdvisor%20of%20thesis%3A%0D%0A%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%0D%0A%0D%0A*Remarks*%3A%0D%0AThe%20summer%20school%20starts%20on%20Monday%2C%20September%2027th%20at%209%3A00%20and%20ends%20on%0D%0AThursday%2C%20September%2030th%20at%2018%3A00.%0D%0A---------------------------------------------------------------------%0D%0A(Approx.)%20Day%20of%20my%20arrival%3A%0D%0A(Approx.)%20Day%20of%20my%20departure%3A%0D%0A%0D%0AI%20do%20need%20a%20visa%3A%20(yes%2Fno)%0D%0A---------------------------------------------------------------------%0D%0A%0D%0A*Remark*%3A%0D%0AAccommodation%20will%20be%20provided%20in%20a%20hotel%20in%20the%20city%20of%20Karlsruhe%0D%0Abetween%2027th%20and%2030th%20September.%20If%20you%20want%20to%20look%20for%20different%0D%0Aaccommodation%20you%20may%20contact%20us%20for%20information.%0D%0A---------------------------------------------------------------------%0D%0APlease%20book%20an%20accommodation%20for%20me%3A%20(yes%2Fno)%0D%0A%0D%0AI%20apply%20for%20free%20accommodation%3A%20(yes%2Fno)%0D%0A%0D%0AIf%20yes%3A%0D%0APlease%20attach%20a%20letter%20of%20motivation%20(at%20most%20a%20page%2C%20single%20PDF%20file)%0D%0Aand%20a%20(short)%20letter%20of%20recommendation%20from%20your%20advisor.%0D%0A---------------------------------------------------------------------%0D%0A%0D%0A*Remark*%3A%0D%0AWe%20plan%20a%20poster%20session.%20When%20this%20event%20will%20be%20on-site%20or%20at%20least%0D%0Ahybrid%20we%20offer%20you%20that%20we%20will%20print%20your%20poster%20for%20you.%20Details%0D%0Awill%20follow.%0D%0A---------------------------------------------------------------------%0D%0AI%20would%20like%20to%20present%20a%20poster%3A%20(yes%2Fno)%0D%0A%0D%0AI%20wish%20the%20print%20service%3A%20(yes%2Fno)%0D%0A---------------------------------------------------------------------%0D%0A%0D%0AKind%20regards%2C%0D%0A%0D%0A">completing this email form</a>`

**Comment by thstyl2000** [comment]
(it is the registration email form from here: `https://www.waves.kit.edu/summerschool2021.php`)
