### ISSUE TITLE
Tagging Modal is showing the wrong tags / duplicate tags

### ISSUE THREAD

**Issue by miaulalala** [nextcloud/mail#5197]
### Expected behavior

Tags are correctly categorised and shown

### Actual behavior

TagModal:

![image](https://user-images.githubusercontent.com/7427347/122220653-d0592080-ceb0-11eb-8f5a-5130df3d5126.png)

Database:

![image](https://user-images.githubusercontent.com/7427347/122220693-de0ea600-ceb0-11eb-9c13-c23f8eea005b.png)

**Comment by ChristophWurst** [comment]
:eyes: @GretaD

**Comment by miaulalala** [comment]
So the conclusion to a debugging session with @GretaD and @kesselb was that there are multiple issues at play.

Firstly, there was a bug in the way we create Tags from the modal.

Secondly, there is an issue with the mail provider I'm using (GMX, which is IONOS). They cast their labels to Uppercase, and Horde does the opposite, they cast all labels to lowercase. So untagging a message will not work, and due to the incoming label without the `$` attached, it created a new tag.

(Quick side note, is the `$` on our labels going to leave us vulnerable re: PHP? Since it's a special char?)
