### ISSUE TITLE
Unable to untag Messages on GMX and possibly others

### ISSUE THREAD

**Issue by miaulalala** [nextcloud/mail#5207]
Follow up to #5197 

### Expected behavior
When I untag a message, the tag disappears.

### Actual behavior
The tags reappears on the next sync from IMAP.

This happens because the GMX IMAP implementation casts every keyword to uppercase - but the Horde Library casts all keywords to lowercase, so we never actually receive any of the uppercase tags.

Both of these behaviours are technically correct:

> Except as noted otherwise, all alphabetic characters are case-
   insensitive.  The use of upper or lower case characters to define
   token strings is for editorial clarity only.  Implementations MUST
   accept these strings in a case-insensitive fashion.

https://marc.info/?l=imap&m=96057337517863&w=2

It's just unfortunate that these behaviours are diametrically opposed.  

Also GMX is not respecting it's own uppercase casting on a SEARCH query for IMAP. They do not treat `$label1` and `$LABEL1` as the same string.

**Comment by ChristophWurst** [comment]
> Also GMX is not respecting it's own uppercase casting on a SEARCH query for IMAP. They do not treat `$label1` and `$LABEL1` as the same string.

But this then sounds like a violation of the insensitive convention, right?

**Comment by miaulalala** [comment]
Yes indeed, it's not implemented properly apparently.

**Comment by ChristophWurst** [comment]
I'm undecided what we can really do about this here. Maybe this is just that one provider and they have to fix it, but it could be more than that.

Would it help to send a patch upstream to Horde to have the automatic lowering removed? Then we could always write (set/unset) the tags both lowercase and uppercase. This is an ugly hack, but if it doesn't come with any other side effects then I wouldn't be too opposed this.

**Comment by miaulalala** [comment]
We could then send two requests to untag - `$label1` and `$LABEL1`. I'm not sure if this would already work? The Horde `_store` command does not seem to perform any lowercasing as far as I can tell.

**Comment by ChristophWurst** [comment]
Let's try?

**Comment by miaulalala** [comment]
Well looks like something changed - I can add and remove the labels without problems and the list of permflags contains all labels in their original case.

**Comment by ChristophWurst** [comment]
Dear anonymous GMX engineer who watches our repo, thanks for fixing this :pray:
