### ISSUE TITLE
www-data as envelope sender

### ISSUE THREAD

**Issue by wadeandree** [nextcloud/mail#5213]
### Expected behavior
Should send mail without appending www-data as envelop sender

### Actual behavior
Whenever I send mail to gmail from the app my mail is bounced, and the following message is in the mail log:

o=<wadeandree@gmail.com>, relay=gmail-smtp-in.l.google.com[74.125.21.26]:25, delay=0.24, delays=0/0/0.22/0.02, dsn=5.1.7, status=bounced (host gmail-smtp-in.l.google.com[74.125.21.26] said: 553 5.1.7 The sender address <www-data> is not a valid RFC-5321 address. y2si5915922ybh.202 - gsmtp (in reply to MAIL FROM command))

### Mail app

1.9.5

postfix

### Server configuration

**Operating system**: Ubuntu 20

**Web server:** Apache

**Database:** My sql

**PHP version:** 7.4

**Nextcloud Version:**21.0.2

#### Client configuration
Safari

**Operating system:** BigSur 11.4

**Comment by ChristophWurst** [comment]
Do you use php-mail for transport https://github.com/nextcloud/mail/blob/master/doc/admin.md#use-php-mail-for-sending-mail?

**Comment by wadeandree** [comment]
No.  Where does that go?  In config.php?

**Comment by ChristophWurst** [comment]
Don't use it unless you know what you are doing. 

Where exactly do you see www-data as sender?

**Comment by wadeandree** [comment]
It’s in the mail.log as a bounce message from gmail whenever I send a message via the mail app.

**Comment by ChristophWurst** [comment]
Could you please share that log with us?

> o=[wadeandree@gmail.com](mailto:wadeandree@gmail.com), relay=gmail-smtp-in.l.google.com[74.125.21.26]:25, delay=0.24, delays=0/0/0.22/0.02, dsn=5.1.7, status=bounced (host gmail-smtp-in.l.google.com[74.125.21.26] said: 553 5.1.7 The sender address is not a valid RFC-5321 address. y2si5915922ybh.202 - gsmtp (in reply to MAIL FROM command))

I don't see any traces of www-data in here.

**Comment by wadeandree** [comment]
I’ve attached the full log.  Below is the section that I’m referring to.

 

Jun 18 21:37:00 Eagle postfix/pickup[7721]: 9AC1D2C0678: uid=33 from=<www-data>

Jun 18 21:37:00 Eagle postfix/cleanup[7797]: 9AC1D2C0678: ***@***.***>

Jun 18 21:37:00 Eagle postfix/qmgr[12595]: 9AC1D2C0678: from=<www-data>, size=2496, nrcpt=1 (queue active)

Jun 18 21:37:01 Eagle postfix/smtp[7800]: 9AC1D2C0678: ***@***.***>, relay=gmail-smtp-in.l.google.com[74.125.21.26]:25, delay=0.37, delays=0.02/0.01/0.32/0.02, dsn=5.1.7, status=bounced (host gmail-smtp-in.l.google.com[74.125.21.26] said: 553 5.1.7 The sender address <www-data> is not a valid RFC-5321 address. e6si4103874ybj.173 - gsmtp (in reply to MAIL FROM command))

 

From: Christoph Wurst ***@***.***>
Reply-To: nextcloud/mail ***@***.***>
Date: Monday, June 21, 2021 at 9:59 AM
To: nextcloud/mail ***@***.***>
Cc: wadeandree ***@***.***>, Author ***@***.***>
Subject: Re: [nextcloud/mail] www-data as envelope sender (#5213)

 

Could you please share that log with us?

***@***.***, relay=gmail-smtp-in.l.google.com[74.125.21.26]:25, delay=0.24, delays=0/0/0.22/0.02, dsn=5.1.7, status=bounced (host gmail-smtp-in.l.google.com[74.125.21.26] said: 553 5.1.7 The sender address is not a valid RFC-5321 address. y2si5915922ybh.202 - gsmtp (in reply to MAIL FROM command))

I don't see any traces of www-data in here.
