### ISSUE TITLE
after second click on same folder shows wrong mails

### ISSUE THREAD

**Issue by pamapa** [nextcloud/mail#522]
### Steps to reproduce
1. click e.g. on "Sent" or any other sub folder (not inbox itself)
2. click again on same folder
3. click again on same folder

### Expected behaviour
I would expect that i always only see mails from that particular folder. e.g "Sent" 

### Actual behaviour
It shows the first time only mails from the e.g. "Sent" which is good. But after the second click
on the same folder it shows the mails from the inbox. When using JavaScript breakpoints i can see
always, that it properly loads first the "Sent" mails, but when i keep it running it somehow over loads those again with the one from the inbox.

### Mail app

**Mail app version: 0.7.3

**Mailserver or service: IMAP server on webhoster, i dont know which product.

**Transport security - IMAP: TLS

**Transport security - SMTP: TLS

**Number of accounts: 1

#### Client configuration
**Browser: Firefox and Chrome

**Operating system: Linux and Windows

##### Browser log
<details>
Content Security Policy: Directive ‘frame-src’ has been deprecated. Please use directive ‘child-src’ instead.  (unknown)
JQMIGRATE: Migrate is installed, version 1.4.0  core.js:7:542
Starting Mail …  build.js:11195:3
initializing cache…  build.js:8583:3
</details>

**Comment by pamapa** [comment]
does no longer happen with v0.7.5

**Comment by ChristophWurst** [comment]
Great to hear that! Thanks for your feedback!
