### ISSUE TITLE
Blank page on Safari mobile

### ISSUE THREAD

**Issue by ChristophWurst** [nextcloud/mail#5236]
### Expected behavior

Happy @LukasReschke

### Actual behavior

@LukasReschke sends me a screenshot from his iphone showing the mail app just renders an empty page

### Mail app

**Mail app version:** v1.10.0 RC1

**Comment by StCyr** [comment]
works very good here

**Comment by szaimen** [comment]
the same happens on Chromium and Firefox for Android mobile on c.nc.c in my testing
see 
![image](https://user-images.githubusercontent.com/42591237/123415057-fff4e080-d5b4-11eb-88c7-db57539bd924.png)

**Comment by ChristophWurst** [comment]
Indeed. As I understand you now see the right column by default. There was logic to hide it until you open a message. This is likely a regression of https://github.com/nextcloud/mail/pull/5201 cc @GretaD @brueckner

**Comment by miaulalala** [comment]
![image](https://user-images.githubusercontent.com/7427347/123426761-15bdd200-d5c4-11eb-8817-788ef7431279.png)
Can reproduce on chrome dev console
