### ISSUE TITLE
Turn of link-redirection

### ISSUE THREAD

**Issue by revpriest** [nextcloud/mail#5248]
Email-links are pretty dangerous things to click on in general, so I really really often want to right-click and then say "open in private window", avoid their cookies and whatnot.

But of course the links are all re-written to go through nextcloud for some reason, which means "open in private tab" shows me the nextcloud login screen.

I'd like to be able to turn off this link-redirection entirely really. I don't really grok what it's for, but I don't like it, it feels creepy even when it's my own server rewriting the links.

Is there an "off" button? Can there be?

**Comment by ChristophWurst** [comment]
Links are rewritten for security reasons, e.g. to stip the referrer of the iframe.

There are no plans right now to make this configurable, but I'll leave the ticket open so we can see if anyone else is actually interested in this feature.

**Comment by revpriest** [comment]
Humm, shame. Means I can't copy/paste a link from an email either.

Would a pull-request be added if I built one?

**Comment by ChristophWurst** [comment]
I'm afraid it won't be accepted to have a PR for this if this adds a configuration flag.

Maybe we can find a solution that allows you to copy the link to open in a private window but also redirect if users just click them?

**Comment by revpriest** [comment]
Could maybe rewrite the redirect link with an onclick? So that if copied or right-clicked it still stayed as the original link but when clicked directly it'd rewrite to the redirect link? 

Or could the redirect page just have "nocsrfrequred" so that it'd work in a non-logged-in private window? The redirect is slow but if it worked when not logged in it'd at least not fail to even open the link. Though that'd still would leave no way to copy the link without opening it.

**Comment by ChristophWurst** [comment]
We can look into that when time allows. The iframe only allows certain js for security reasons, but I guess it should be possible to have a click handler in there that rewrites the link on click.

**Comment by revpriest** [comment]
Okay, I'll just run a simple patch for now then.

In case anyone else is wondering, if you edit apps/mail/lib/Service/Html.php and comment out the following line by adding the two slashes at the start, around like 139:

//		$uri->addFilter(new TransformURLScheme($messageParameters, $mapCidToAttachmentId, $this->urlGenerator, $this->request), $config);

Then the URL-redirection is turned off.

Warning: Sounds like this might make it easier to track you but, you know, you're clicking a link in an email. Chances are it's got some link-tracking anyway. Maybe that private-window is a better choice.
