### ISSUE TITLE
README.md - information about the debug log location need to be corrected

### ISSUE THREAD

**Issue by j-ed** [nextcloud/mail#525]
In the README.md file the paragraph "**Debug mode**" it is written that IMAP/SMTP log files will appear **in the same directory as your nextcloud.log**. This information is not correct because they are stored in the `datadirectory`of the Nextcloud installation and not the logfile path.
The easiest way to fix this discrepancy would be to correct the information in the README.md file instead of changing the path in the program code.

**Comment by ChristophWurst** [comment]
Agreed. We shouldn't change the directory but fix the description. I've never thought about this scenario, but of course it makes sense since people can tweak the logfile location to their needs and then the current description doesn't make sense. Good catch!

**Comment by j-ed** [comment]
[x] Done, see https://github.com/nextcloud/mail/pull/526

**Comment by ChristophWurst** [comment]
Thanks!
