### ISSUE TITLE
Allow to disable automatic classification

### ISSUE THREAD

**Issue by nickvergessen** [nextcloud/mail#5260]
### Expected behavior
You have a usable inbox in thunderbird

### Actual behavior
100 emails per week are marked as "Important"

The "problem" is that 2 features work together quite nicely:
* Tags/labels are synced and appear in thunderbird
* Priority inbox labels email as `$label1`

My account is automatically deployed, so I can't remove it (I think). The priority inbox automatically scans and adds labels althought I wouldn't use the web mail at all.

There should at least be an option to opt-out from the auto-labeling

### Mail app

**Mail app version:** company instance

**Mailserver or service:** company instance

**Comment by ChristophWurst** [comment]
So the disable option can either

1) Disable classification at all
2) Switch over to another custom but hidden tag that won't do any harm on Thunderbird

**Comment by ChristophWurst** [comment]
:eyes: @miaulalala

**Comment by ChristophWurst** [comment]
Let's do option 2 for v1.10, but not #3265 yet.

* Add a checkbox in the bottom left
  + Checked by default
  + If unchecked, the classification listener exits early and doesn't classify, tag nor flag anything

**Comment by hostingnuggets** [comment]
Is it possible to disable mail classification system-wide for example by setting a parameter in Nextcloud's config.php file?

**Comment by ChristophWurst** [comment]
no, that's not possible right now.

**Comment by hostingnuggets** [comment]
Thanks for the fast answer. 

That would be a great feature I think. For example my appdata_*/mail/classifiers directory gets filled with over 300k of small files for nothing, which makes the things slow as having many files in one directory is not optimal.

**Comment by ChristophWurst** [comment]
> As far as I know there is not even a cron job or occ command to cleanup that classifiers directory.

Right, that is another issue. Mind opening a ticket for this? Thanks!

**Comment by hostingnuggets** [comment]
> Right, that is another issue. Mind opening a ticket for this? Thanks!

Sure, I now opened https://github.com/nextcloud/mail/issues/5288

**Comment by BtbN** [comment]
It does not seem like that PR(#5270) fixed the issue.
I toggled off the option it added ("Automatically classify importance of new emails"), but most of the new E-Mails in my inbox in Thunderbird still show up red, because Nextcloud Mail tagged them as Important.

**Comment by ChristophWurst** [comment]
It doesn't change the tag of existing messages. This setting only influences what happens to new messages that will arrive now.

**Comment by BtbN** [comment]
Yes, it is still tagging new mail that's coming in.
I'm not looking at old mail.

**Comment by ChristophWurst** [comment]
Got it. Please open a new ticket. This is a bug then.

**Comment by hbogner** [comment]
Can confirm it is happening here too.
Tested on multiple users.

**Comment by tobox** [comment]
> Is it possible to disable mail classification system-wide for example by setting a parameter in Nextcloud's config.php file?

Is this still not possible? I had to disable the mail app when the tagging issues came up, and I would love to enable it again. But I have many users and none of them was happy with the new feature. 

Will there be an option to set this globally, or is there a command line hack to disable it iteratively for each user?

**Comment by ChristophWurst** [comment]
There is no global setting yet but I'll accept a PR for a configurable default value if you do the coding.

**Comment by ttmooney** [comment]
Hi @ChristophWurst --

This is a problem for multiple users in multiple domains that I'm running Nextcloud mail with. It's totally random, and creates a customer (all our users are considered customers) perception that something is wrong, and that the system doesn't work properly.

This should be a show-stopper bug and we need a global setting to disable the classifier across all users.

We are still on NC Mail 1.12 (installed on UCS 4, so on their release train with NC 21.0.7 -- is this resolved in a future release?

Kind regards,

travis

**Comment by BtbN** [comment]
I feel like you're interpreting those reactions in the opposite way they were meant.
I'm carrying a custom patch that turns off the entire classification thing for a while now, since it just wastes a massive amount of CPU time on the Server, and nobody is using it anyway.

Would definitely appreciate a way to just server-side configure the whole thing out.

**Comment by ChristophWurst** [comment]
Got it :v:
