### ISSUE TITLE
Diable automaticly sending mail read receipt

### ISSUE THREAD

**Issue by rockpham** [nextcloud/mail#5262]
### Question

Is there a way to disable automatic sending of read confirmation to sender?

**Comment by ChristophWurst** [comment]
I don't think we do that. at least intentionally. are you sure this happens through Nextcloud Mail?

**Comment by rockpham** [comment]
Thank you for your time. I have received another email with notification request and Nextcloud Mail does not automatically send read confirmation. It shows a big button "Notify the sender". I must have inadvertently clicked that button in the other email, I apologize.
Is it possible to disable that button? I do not want to send notification ever, and maybe there are some other people who feel the same way?

**Comment by ChristophWurst** [comment]
> Is it possible to disable that button?

There is no configuration option for it. I guess you could work around it by writing a Sieve rule that automatically set thes $mdnsent flag for all new messages. Then our application and likely others won't ask you to send the receipt. They will only (wrongly) show that it had already been sent (but it hasn't).
