### ISSUE TITLE
make use of subcribed mailbox folder list to speed-up the app performance

### ISSUE THREAD

**Issue by j-ed** [nextcloud/mail#527]
## Expected behavior
The mail app should show and load all subscribed folders of an IMAP account instead of scanning the whole IMAP tree on-and-on. Similar to e.g. Mozilla Thunderbird a subscribe/unsubscribe function should be added to select the mail folders to process.

## Current behavior
If you open the mail app, it scans the whole IMAP account for available mail folders instead of relying on the list of subscribed folders only. This slows down the app and can make it unusable if there are many mail folders available in a IMAP tree.

I tried this out by setting-up a new email account to which I've added more and more mail folders. First I recognized, that the .mailboxlist file doesn't exist and wasn't created by the app, which usually contains the list of subscribed mail folders. I then created such a file to find out if it effects the behavior of the app, but it doesn't. To substantiate my assumption I added a folder which increased the total number
of folders to 1000 which make the mail app unusable.

### Steps to reproduce
1. Open the Mail app.
2. Set-up an email account which contains e.g. 1000 mail folders.
3. wait, wait, drink coffee, wait, wait, ...

#### Server Configuration
OS: Linux 3.16.46
Web server: Apache2 2.4.26
Database: MariaDB 10.0.32
PHP version: 5.6.29
Nextcloud version: 12.0.2
Nextcloud Mail app version: 0.7.3
IMAP mail daemon: Panda IMAP

#### Client Configuration
Browser: Mozilla Firefox 55.0.3
Operating system: Windows 7

**Comment by ChristophWurst** [comment]
I think https://github.com/nextcloud/mail/pull/1956 should eliminate this slowness mostly. In combination with https://github.com/nextcloud/mail/pull/2064 the mailboxes will be sync'ed in background once an hour, so whenever you open the web interface, the app has to just fetch the cached list from the database. This should not take very long. https://github.com/nextcloud/mail/pull/3116 will finally only show subscribed folders.

I conclude that we handle this well by now :)
