### ISSUE TITLE
Unread counter on Trash is unnecessarily distracting

### ISSUE THREAD

**Issue by jancborchardt** [nextcloud/mail#5272]
There is an unread counter for every folder, which does make sense everywhere – except Trash. If you trashed a message unread, then you don’t want to be bothered by it.

The solution for that would be to not show the unread counter on the Trash folder. Gmail does it like that as well:

Nextcloud Mail with unread trash counter | Gmail without unread trash counter
-|-
![mail navigation](https://user-images.githubusercontent.com/925062/124281267-d7875c00-db49-11eb-9247-9a57a136dbbe.png)|![image](https://user-images.githubusercontent.com/925062/124281252-d3f3d500-db49-11eb-9396-08471aff4144.png)

**Comment by thstyl2000** [comment]
Also maybe for the spam folder? I suppose that some might like to show/hide the counter on other folders too. Sorry for the bump, but what about adding a folder option to show/hide the unread/total message counter?

**Comment by ChristophWurst** [comment]
> Also maybe for the spam folder?

Dunno. I would say that depends. People might keep their junk folder empty-ish and then it's useful when you see that something popped up in there nevertheless where the server moved a message for you.

> Sorry for the bump, but what about adding a folder option to show/hide the unread/total message counter?

This is too specific IMO. We try to have good defaults that replace an overcomplicated UI with too many options.

**Comment by thstyl2000** [comment]
True, nowadays at least I am getting ca 20 spams per day (both in my work and private email, so ca 40/day) so I do not really periodically check them, unless I am made aware of some message not coming through.

About customizability, I totally agree with you. Would it be possible to show/hide these counters with custom css?
