### ISSUE TITLE
Check attachments for virus(es) on upload

### ISSUE THREAD

**Issue by dienteperro** [nextcloud/mail#5280]
#### Summary

It would be nice if the Mail app is installed along the Antivirus for files (https://apps.nextcloud.com/apps/files_antivirus) in the same Nextcloud server to have it check the attachments as the Antivirus for files does to uploads to prevent viruses to spread through mail.

**Comment by ChristophWurst** [comment]
this would require a new API in Nextcloud where apps can ask for a scan on a given file. Such an API doesn't exist at the moment.

**Comment by dienteperro** [comment]
Shame on me for not being able to write it! Best regards!

**Comment by ChristophWurst** [comment]
No worries :)

We also have other ways of contributing if you are interested https://nextcloud.com/contribute/ :)
