### ISSUE TITLE
Attachments not shown in email (need to click "View Source")

### ISSUE THREAD

**Issue by LukasReschke** [nextcloud/mail#5282]
### Expected behavior
I see the text/x-patch attachments attached to an email sent to me.

### Actual behavior
I do not see said attachments.  I had to press "View Source", to view the email source and then manually look at the attachments there.I can provide the whole EML privately on request. (it contains sensitive information)

### Mail app
c.nc.c - Thread is 1984129

**Comment by ChristophWurst** [comment]
@LukasReschke see https://github.com/nextcloud/mail/pull/5339. Can you confirm that your email was also a plain text one with inline attachments?

**Comment by LukasReschke** [comment]
@ChristophWurst I have no clue how to figure that out. That said, I gave @kesselb my EML and naively assume that the PR was that this way :-)

**Comment by ChristophWurst** [comment]
Got it. Didn't know we had the original EML!

**Comment by ChristophWurst** [comment]
@onny @GuillaumeAmat you reacted with a :+1:, is your affected email also one with plain text and inline attachments? Could you please check? :)

**Comment by onny** [comment]
I don't see attachments like sending a photo from my iPhone to my mail. They don't appear in Nextcloud Mail

**Comment by ChristophWurst** [comment]
could you please recreate with some non-sensitive data and share the .eml with us?

**Comment by onny** [comment]
> could you please recreate with some non-sensitive data and share the .eml with us?

sorry I have an old version installed (1.9.5) so maybe this is already fixed. Unfortunately I cannot test the new version yet.

**Comment by GuillaumeAmat** [comment]
Sorry @ChristophWurst, I can't find the problematic emails... I guess we can close the issue and reopen it if the problem pops up again.

**Comment by ChristophWurst** [comment]
No worries. https://github.com/nextcloud/mail/pull/5339 makes sense and it fixes one of the ten million possible ways to write an email :wink:
