### ISSUE TITLE
1.10.0: Message is not shown after hitting the 

### ISSUE THREAD

**Issue by jakobroehrl** [nextcloud/mail#5284]
### Expected behavior
Tell us what should happen

### Actual behavior
Tell us what happens instead

### Mail app

**Mail app version:** (see apps admin page, e.g. 0.5.3)

**Mailserver or service:** (e.g. Outlook, Yahoo, Gmail, Exchange,...)

### Server configuration

**Operating system**: (e.g. Debian 8)

**Web server:** (e.g. Apache, Nginx,...)

**Database:** (e.g. MariaDB, SQLite or PostgreSQL)

**PHP version:** (e.g. 7.0)

**Nextcloud Version:** (see admin page, e.g. 13.0.2)

#### Client configuration
**Browser:** (e.g. Firefox 48)

**Operating system:** (e.g. Arch Linux)

**Comment by ChristophWurst** [comment]
the … what :see_no_evil:

**Comment by jakobroehrl** [comment]
sorry, my fault, created a complete issue now.
