### ISSUE TITLE
1.10.0: Next Message is not shown up after hitting the DEL Button on the 1st message

### ISSUE THREAD

**Issue by jakobroehrl** [nextcloud/mail#5285]
If I hit DEL on a message the message above is shown. 
On message 2-n everthing is working good.

If I delete the 1st message the 2nd should shown

**Comment by ChristophWurst** [comment]
possibly related to https://github.com/nextcloud/mail/pull/5106 cc @kesselb

**Comment by GuillaumeAmat** [comment]
It's still an issue

**Comment by ChristophWurst** [comment]
let's continue in https://github.com/nextcloud/mail/issues/6042.
