### ISSUE TITLE
Unable to update Mail app to 1.10 in NC 20.0.11

### ISSUE THREAD

**Issue by facorazza** [nextcloud/mail#5286]
Please refer to: https://help.nextcloud.com/t/cant-update-polls-and-mail-in-20-0-11/119663

**Comment by ChristophWurst** [comment]
Hmmmm this is yet another of those upgrade bugs where the app isn't doing anything wrong but Nextcloud loads the old app code first and then in the post migration change the new app code is expected. ``\OCA\Mail\Db\MailboxMapper::findAllIds`` only exists for v1.10, hence the error this time.

So this is the same type of issue as in https://github.com/nextcloud/mail/issues/4746

@miaulalala I think we didn't want this to be a repair step as the jobs are a one-time thing. A repair step would insert the async jobs over and over every time it's run.

**Comment by ChristophWurst** [comment]
Here's what we can do. We check for the method existence. If it's there then we insert the jobs right away. Otherwise we log a warning for the admins that the upgrade is incomplete. Then we offer a new simple occ command that can insert those jobs at any given time. Admins won't run the command usually, but only when this output tells them. Does that sound sane?

cc @nickvergessen as expert for upgrade issues :)

**Comment by miaulalala** [comment]
Yep, sounds like a sensible idea.

**Comment by ChristophWurst** [comment]
The changes in the migrations will be identical to https://github.com/nextcloud/mail/pull/4747

**Comment by miaulalala** [comment]
Just saw that I do't check on the mailboxs properties. Should I see if this mailbox is even active any more? I have ~400 new entries for my local entries.

**Comment by ChristophWurst** [comment]
How do you know if a mailbox is *active*?

**Comment by miaulalala** [comment]
if the accounts exists?

**Comment by ChristophWurst** [comment]
https://github.com/nextcloud/mail/blob/master/lib/Service/CleanupService.php takes care of this. In production systems there shouldn't be much leftover data

**Comment by facorazza** [comment]
I see the 1.10.1 milestone is getting an increasing number of issues added. would it be possible to move them to a 1.10.2 version and release the 1.10.1 with this fix so that at least we can use the app in the meantime?

**Comment by ChristophWurst** [comment]
> increased

Yeah we are awaiting a few fixes, then this will go out. The impatient are welcome to take the patch and apply it locally.

**Comment by facorazza** [comment]
> > increased
> 
> Yeah we are awaiting a few fixes, then this will go out. The impatient are welcome to take the patch and apply it locally.

Then along with these fixes please include some testing so that you stop shipping broken software

**Comment by miaulalala** [comment]
@facorazza feel free to test and contribute. This is open source after all. If you need help with your first PR, here's a handy guide: https://github.com/sleepypioneer/ContributingToNextcloudIntroductoryWorkshop

**Comment by facorazza** [comment]
> @facorazza feel free to test and contribute. This is open source after all. If you need help with your first PR, here's a handy guide: https://github.com/sleepypioneer/ContributingToNextcloudIntroductoryWorkshop

Clearly I'm already a tester as it seems no one here cares to test stuff before releasing it

**Comment by miaulalala** [comment]
@facorazza  We are grateful for you help in testing the application, but that does not entitle you to treat us rudely.

https://nextcloud.com/contribute/code-of-conduct/

**Comment by facorazza** [comment]
> @facorazza We are grateful for you help in testing the application, but that does not entitle you to treat us rudely.
> 
> https://nextcloud.com/contribute/code-of-conduct/

Then would you care to elaborate why you need to wait for other fixes when you could just release this one? I'd do it myself if could.

I wouldn't insist as much if it was an ordinary issue, but I can't even use the app as of now. I'm not asking for a perfect, bug-free, full-featured app, I'm just asking for a working version. It's not like you still have to work this out. It's done. It's ready. The least you could do is to explain the decision behind it.
