### ISSUE TITLE
mailto composer: Possible to open in new tab?

### ISSUE THREAD

**Issue by jancborchardt** [nextcloud/mail#529]
Currently when you click on a mailto link on a website, you get switched to Nextcloud. This is a bit annoying cause the previous site is gone. Is it possible to do some `target="_blank"` stuff? I’m guessing not, but maybe someone has an idea?

**Comment by ChristophWurst** [comment]
> I’m guessing not

Correct. AFAIK it's the browser that handles this, not the website that was registered for the event. Thus I'm afraid there's nothing we can do about this.

**Comment by jancborchardt** [comment]
Yeah, I guess the website which puts the mailto link up needs to define the target="_blank" in the a.
