### ISSUE TITLE
Mails are getting automatically classified even if classification is disabled

### ISSUE THREAD

**Issue by BtbN** [nextcloud/mail#5290]
### Expected behavior
After #5270 was merged, I was expecting that deselecting that new setting would stop Nextcloud from making virtually all new Mails show up as Important in Thunderbird.

### Actual behavior
Most new mails are still getting Tagged as important, despite the setting being disabled.

### Mail app

**Mail app version:** 1.10.0

**Mailserver or service:** Dovecot

### Server configuration

**Operating system**: Gentoo

**Web server:** Apache

**Database:** PostgreSQL

**PHP version:** 7.4

**Nextcloud Version:** 22.0.0

#### Client configuration
**Browser:** Edge 91

**Operating system:** Windows

**Comment by miaulalala** [comment]
Related to #5260

**Comment by ChristophWurst** [comment]
The bug only happens in cron, hence we couldn't reproduce. @miaulalala is working on a fix :v:

**Comment by jpschewe** [comment]
I just installed version 1.10.2 of the mail app yesterday and this morning woke to find that it is still marking emails as important despite "Automatically classify importance of new email" not being checked in my settings.

**Comment by nhathaway** [comment]
Same here. Mails are still be marked red even though both checkboxes are off ("Allow the app to collect..." and "Automatically classify...")

Nextcloud: 22.0.0
Mail app: 1.10.2

**Comment by BtbN** [comment]
The fix is not in any release yet, so that's not all that surprising.

**Comment by ChristophWurst** [comment]
Backport was missing. It's at https://github.com/nextcloud/mail/pull/5426.

**Comment by damnms** [comment]
i installed latest nextcloud 2 weeks ago for testing purposes and suddenly i noticed some emails that are tagged as important. i thought "wtf". now by accident i found this bug. i am very sure nextcloud does this on my machine now too. i was running latest stable (27.1.5) but killed it because ... thats a real killer. i assume its somehow because of that cron.php. 
anyone an idea how to figure out wth is going on?

**Comment by gohrner** [comment]
@damnms: So you have disabled the "Important" tagging in the NC Mail app, but it still classifies mails as "Important"?

**Comment by damnms** [comment]
i did not configure anything with tagging, so i would not expect that emails are tagged as important automatically. i did not configure the mail app further, only basic setup for testing nextcloud.

**Comment by gohrner** [comment]
@damnms: The NC devs explicitly decided to let this option's default be "enabled". It can be disabled in the user's mail app settings in the mail app's lower left corner.

There's a feature request somewhere here to make the default configurable for the instance, but it wasn't implemented so far.

However, if you didn't disable it, the behaviour you observe does not appear to be a bug, but "works as designed". (One could argue about that design, but here's probably not the right place to do so, and as said, there's already at least a feature request for making it configurable - it "just" needs to be implemented now...)

**Comment by kaidrumm** [comment]
This happened to me after an upgrade this week and it also appears as a bug for me. It is marking repetitive bot emails as important.

**Comment by ChristophWurst** [comment]
@kaidrumm file a new report with your version etc. This is an old ticket. Thanks!
