### ISSUE TITLE
mailto composer: Goes to log in screen even if you are already logged in

### ISSUE THREAD

**Issue by jancborchardt** [nextcloud/mail#530]
Every time you click a mailto link, the log in screen is shown. Even when you are already logged in, or have »stay logged in« marked.

**Comment by ChristophWurst** [comment]
Tried it. Works for me. Please be more precise about reproduction steps 😉

**Comment by jancborchardt** [comment]
I can’t be more precise. :D 

1. Be logged in to your Nextcloud (local dev instance in my case)
2. Have it set as default mailto handler
3. Go to [mailto:someone@example.com?Subject=Hello%20again](mailto:someone@example.com?Subject=Hello%20again)
4. See the log in screen again

**Comment by ChristophWurst** [comment]
> Go to mailto:someone@example.com?Subject=Hello%20again

Which URL are is opened? To which one does it redirect you?

**Comment by jancborchardt** [comment]
http://localhost/nextcloud/index.php/login?redirect_url=/nextcloud/index.php/apps/mail/compose%3Furi%3Dmailto%253Asomeone%2540example.com

**Comment by ChristophWurst** [comment]
> Which URL are is opened?

So

**Comment by jancborchardt** [comment]
Ah sorry, the url it goes to then is:
http://localhost/nextcloud/index.php/apps/mail/#mailto?to=test%40example.com

**Comment by ChristophWurst** [comment]
@LukasReschke volunteered for fixing this bug 😉

**Comment by LukasReschke** [comment]
@ChristophWurst volunteered to bring me some more Kürbiskerne

**Comment by ChristophWurst** [comment]
> @ChristophWurst volunteered to bring me some more Kürbiskerne

Done

**Comment by jancborchardt** [comment]
Ok so probably some issue on my side. Closing this, maybe @Gomez or @lcalaresu can reproduce?
