### ISSUE TITLE
Attachments / Send buttons "hidden" at the end of a long message

### ISSUE THREAD

**Issue by thstyl2000** [nextcloud/mail#5320]
### Expected behavior
The "send" button and the existence of attachments are always there, at the bottom end of the frame.

### Actual behavior
If a mail body is long, one has to scroll down all the way to click on "send", or to find out if there are any attachments. The second is more of a problem, since some people have long signatures, so in order to realize there is an attachment, one needs to "read" the full signaure.

### Mail app

**Mail app version:** 1.10.0

**Mailserver or service:** (irrelevant)

### Server configuration

**Operating system**: FreeBSD

**Web server:** Apache, Nginx rev.proxy

**Database:** MariaDB

**PHP version:** 8.0

**Nextcloud Version:** 21.0.3

#### Client configuration
**Browser:** Firefox / Nativifier

**Operating system:** Kubuntu

**Comment by ChristophWurst** [comment]
would it be possible to get a screenshot for this bug?

**Comment by thstyl2000** [comment]
There you go! Thanks for looking into it!
![Screenshot_20210715_130934](https://user-images.githubusercontent.com/18458458/125780665-7aaf0792-f6fc-4f35-8143-a3a182fae1b9.png)
![Screenshot_20210715_131411](https://user-images.githubusercontent.com/18458458/125780668-aaa41882-0483-4de3-8f16-397f6e1409c5.png)
![Screenshot_20210715_131717](https://user-images.githubusercontent.com/18458458/125780671-864ca534-857d-447e-b8ea-2e6ef5c086eb.png)
![Screenshot_20210715_131959](https://user-images.githubusercontent.com/18458458/125780674-292537c6-c51e-42c8-aab5-42033fb2e7e4.png)

**Comment by thstyl2000** [comment]
Tracked in #4181. Closing.
