### ISSUE TITLE
Design review v1.x

### ISSUE THREAD

**Issue by ChristophWurst** [nextcloud/mail#5321]
In the next few weeks we want to do a design review of this app. Let's collect some thoughts and ideas in here so we have some points to work on when we get to this task.

Older design feedback to triage or work on
* [x] #5481
* [x] #5482
* [x] https://github.com/nextcloud/mail/issues/4181
* [x] #5483
* [x] https://github.com/nextcloud/mail/issues/5144
* [x] https://github.com/nextcloud/mail/issues/5145
* [x] https://github.com/nextcloud/mail/issues/5272
* [x] https://github.com/nextcloud/mail/issues/5271
* [x]  #5528
* [x] #5484

cc @nextcloud/designers @GretaD

**Comment by nimisha-vijay** [comment]
- One thing that we can improve is the "compose message section", maybe we can use a modal like in the new iCloud mail, or a popup thingy in the bottom of the screen like in Gmail.

- We can also think about changing the message list, by showing a smaller time format (1h instead of 1 hour ago), and maybe some commonly used actions such as favourite and mark as read/unread when the list is wide enough. We can also maybe hide the avatars if the list is too narrow.

**Comment by ChristophWurst** [comment]
> popup thingy in the bottom of the screen like in Gmail

https://github.com/nextcloud/mail/issues/2831

**Comment by ChristophWurst** [comment]
One thing that is often a bit much is that we show the full messages as bold when it's unread. Could we maybe scope this to only the subject? Then sender name and time aren't taking up as much space and you can still tell when something is unread. Just an idea.

**Comment by thstyl2000** [comment]
Maybe even use a larger font size to make unread messages stand out in the list? The way it is now (bold, sender & subject) is somehow a bit visually confusing for me.

**Comment by thstyl2000** [comment]
Concerning #3402, what about something like #4816 ?

**Comment by cptMikky** [comment]
There's also #3940. The discussion basically distilled the issue to "resizable columns" but there's more there (visual separation of messages in message list, better read/unread distinction, etc.)

**Comment by miaulalala** [comment]
A community suggestion I really like: #5395

**Comment by dodedodo** [comment]
Just wanted to refer to a [comment](https://github.com/nextcloud/mail/issues/65#issuecomment-874213122) I made some time ago.

**Comment by nimisha-vijay** [comment]
How about something like this for the email content?

![image](https://user-images.githubusercontent.com/52440189/129175039-0cc7077d-7653-4e5d-8681-0c5fad95065e.png)

- A stacked card looking layout for threads (for single messages it could just be one card) and it hopefully addresses [#3941](#3941) and the [comment](https://github.com/nextcloud/mail/issues/65#issuecomment-874213122) on [#65](#65)
- Attachments are clearer and can have the "Download" and "Save to files" option in the 3 dot menu, addresses [#4181](#4181)
- We can also remove the "Re:" and "Fwd:" on threads to show the subject more? Gmail does something similar. To indicate that it is a thread in the list we can show multiple people's names in the sender

And something like this for writing a new message 

![image](https://user-images.githubusercontent.com/52440189/129175901-97f91bda-1ad2-451e-b681-d84c0d799769.png)
- Like mentioned in #2831
- would also take care of #3453
- "From" field can be automatically filled 

What do you think? 
cc @jancborchardt who worked on the mockups as well

**Comment by GretaD** [comment]
I will start working on this one, but help is also appreciated if some community members want to help

**Comment by ChristophWurst** [comment]
I would like to define which items we now want to do and which ones are optional so that this task can be considered done at some point. @jancborchardt would you be available for a short call to discuss this?

**Comment by GretaD** [comment]
all done, yuhuuu
