### ISSUE TITLE
Move spam messages to spam mailbox

### ISSUE THREAD

**Issue by miaulalala** [nextcloud/mail#5326]
### Feature Request

We currently don't do anything on makring a message as spam/junk. Add a setting that will automatically move a message to the spam / junk folder on marking it as such.

**Comment by ChristophWurst** [comment]
I would argue this could be the default. But let's check the RFCs as I'm sure there are guidelines for how email clients should handle this

**Comment by miaulalala** [comment]
This will also mean adding a default folder for junk I assume?

**Comment by ChristophWurst** [comment]
Yes, we need a setting for the preferred junk mailbox like we have for draft, sent and trash.

**Comment by ChristophWurst** [comment]
Dup of https://github.com/nextcloud/mail/issues/4101
