### ISSUE TITLE
i can not install the app

### ISSUE THREAD

**Issue by Nobissoft** [nextcloud/mail#533]
i can not install the app. i become a mistake like this
"App for id mail has a wrong app ID in info.xml:"
what can i do? thx for help

**Comment by ChristophWurst** [comment]
> what can i do?

Hello.

First, I'd suggest *not* to ignore the issue template when you file a ticket as that would actually help us identify the bug easier. But you're lucky, there's already a duplicate ticket for this: #492. So please take a loot at it and we'll continue the discussion there.

Thanks and have a nice weekend.
