### ISSUE TITLE
Cant connect to IMAP Account

### ISSUE THREAD

**Issue by Taste-IT** [nextcloud/mail#535]
1.filled out the connection settings with TLS/SSL and the IMAP Account didnt connected, I got an runing circle all the time. Same if i use StartTLS for testing. Connecting from another Webmailer like Roundcube works.
Server Debian Jessie, latest stable MariaDB, latest NC.

**Error in Log**

Error while creating the account: Kontoerstellung fehlgeschlagen:Authentication failed.

Horde_Imap_Client_Exception_ServerResponse: IMAP error reported by server.
/var/www/clients/client12/web31/web/apps/mail/vendor/pear-pear.horde.org/Horde_Imap_Client/Horde/Imap/Client/Socket.php - line 4302: Horde_Imap_Client_Socket->_getLine(Object(Horde_Imap_Client_Interaction_Pipeline))
/var/www/clients/client12/web31/web/apps/mail/vendor/pear-pear.horde.org/Horde_Imap_Client/Horde/Imap/Client/Socket.php - line 4230: Horde_Imap_Client_Socket->_sendCmdChunk(Object(Horde_Imap_Client_Interaction_Pipeline), Array)
/var/www/clients/client12/web31/web/apps/mail/vendor/pear-pear.horde.org/Horde_Imap_Client/Horde/Imap/Client/Socket.php - line 1751: Horde_Imap_Client_Socket->_sendCmd(Object(Horde_Imap_Client_Interaction_Pipeline))
/var/www/clients/client12/web31/web/apps/mail/vendor/pear-pear.horde.org/Horde_Imap_Client/Horde/Imap/Client/Base.php - line 1728: Horde_Imap_Client_Socket->_status(Array, 8717)
/var/www/clients/client12/web31/web/apps/mail/vendor/pear-pear.horde.org/Horde_Imap_Client/Horde/Imap/Client/Base.php - line 4033: Horde_Imap_Client_Base->status(Array, 8717)
/var/www/clients/client12/web31/web/apps/mail/vendor/pear-pear.horde.org/Horde_Imap_Client/Horde/Imap/Client/Base.php - line 3585: Horde_Imap_Client_Base->_syncStatus('dovecot.sieve')
/var/www/clients/client12/web31/web/apps/mail/lib/Service/FolderMapper.php - line 51: Horde_Imap_Client_Base->getSyncToken('dovecot.sieve')
/var/www/clients/client12/web31/web/apps/mail/lib/Service/MailManager.php - line 70: OCA\Mail\Service\FolderMapper->getFolders(Object(OCA\Mail\Account), Object(Horde_Imap_Client_Socket))
/var/www/clients/client12/web31/web/apps/mail/lib/Controller/FoldersController.php - line 72: OCA\Mail\Service\MailManager->getFolders(Object(OCA\Mail\Account))
[internal function] OCA\Mail\Controller\FoldersController->index(6)
/var/www/clients/client12/web31/web/lib/private/AppFramework/Http/Dispatcher.php - line 160: call_user_func_array(Array, Array)
/var/www/clients/client12/web31/web/lib/private/AppFramework/Http/Dispatcher.php - line 90: OC\AppFramework\Http\Dispatcher->executeController(Object(OCA\Mail\Controller\FoldersController), 'index')
/var/www/clients/client12/web31/web/lib/private/AppFramework/App.php - line 114: OC\AppFramework\Http\Dispatcher->dispatch(Object(OCA\Mail\Controller\FoldersController), 'index')
/var/www/clients/client12/web31/web/lib/private/AppFramework/Routing/RouteActionHandler.php - line 47: OC\AppFramework\App main('OCA\\Mail\\Contro...', 'index', Object(OC\AppFramework\DependencyInjection\DIContainer), Array)
[internal function] OC\AppFramework\Routing\RouteActionHandler->__invoke(Array)
/var/www/clients/client12/web31/web/lib/private/Route/Router.php - line 299: call_user_func(Object(OC\AppFramework\Routing\RouteActionHandler), Array)
/var/www/clients/client12/web31/web/lib/base.php - line 1004: OC\Route\Router->match('/apps/mail/acco...')
/var/www/clients/client12/web31/web/index.php - line 48: OC handleRequest()
{main}

**Comment by ChristophWurst** [comment]
> Authentication failed.

Wrong password, maybe? If not, please file a proper bug report and fill out the issue template as you've been asked at https://github.com/nextcloud/mail/issues/new 😉

**Comment by ChristophWurst** [comment]
> dovecot.sieve

Actually, this has been fixed in https://github.com/nextcloud/mail/pull/520. Just wait for the next release and it should work again.

**Comment by ChristophWurst** [comment]
Duplicate of https://github.com/nextcloud/mail/issues/475
