### ISSUE TITLE
Creating account failure

### ISSUE THREAD

**Issue by schmackz** [nextcloud/mail#5350]
I have searched. No solutions I have not found a solution that corrected my issue.

### Expected behavior
Add account

### Actual behavior
[mail] Error: Creating account failed: Connection to IMAP at _________ :993 failed. Authentication failed.

POST /files/index.php/apps/mail/api/accounts

### Mail app

**Mail app version: 

**Mailserver or service: Godaddy

### Server configuration
Apache Version | 2.4.46
PHP Version | 7.0.33
MySQL Version | 5.7.33-cll-lve
Architecture | x86_64
Operating System | linux
Nextcloud Version: 22.0

#### Client configuration
**Browser:** Chrome
**Operating system:**  windows10

FYI Its not a password issue

**Comment by GretaD** [comment]
From the error you have posted looks like a problem with your imap/smtp connection.
Can you try to reproduce and send us the log from nextcloud.log?

**Comment by schmackz** [comment]
> From the error you have posted looks like a problem with your imap/smtp connection.
> Can you try to reproduce and send us the log from nextcloud.log?

{"reqId":"YPXjOfZUWQzXHLgHQx1FBwAA4iU","level":3,"time":"2021-07-19T20:40:39+00:00","remoteAddr":"96.241.162.132","user":"tjohnson","app":"mail","method":"POST","url":"/files/index.php/apps/mail/api/accounts","message":"Creating account failed: Connection to IMAP at mail.najessentials.com:993 failed. Authentication failed.","userAgent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.124 Safari/537.36","version":"22.0.0.11"}
{"reqId":"YPXkSvZUWQzXHLgHQx1HZQAA4iU","level":3,"time":"2021-07-19T20:45:00+00:00","remoteAddr":"96.241.162.132","user":"tjohnson","app":"mail","method":"POST","url":"/files/index.php/apps/mail/api/accounts","message":"Creating account failed: Connection to IMAP at imap.secureserver.net:993 failed. Authentication failed.","userAgent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.124 Safari/537.36","version":"22.0.0.11"}
{"reqId":"YPXkY-ZUWQzXHLgHQx1HhwAA4iU","level":3,"time":"2021-07-19T20:45:25+00:00","remoteAddr":"96.241.162.132","user":"tjohnson","app":"mail","method":"POST","url":"/files/index.php/apps/mail/api/accounts","message":"Creating account failed: Connection to IMAP at imap.secureserver.net:993 failed. Authentication failed.","userAgent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.124 Safari/537.36","version":"22.0.0.11"}
{"reqId":"YPXkcPZUWQzXHLgHQx1HlQAA4iU","level":3,"time":"2021-07-19T20:45:50+00:00","remoteAddr":"96.241.162.132","user":"tjohnson","app":"mail","method":"POST","url":"/files/index.php/apps/mail/api/accounts","message":"Creating account failed: Connection to IMAP at mail.najessentials.com:993 failed. Authentication failed.","userAgent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.124 Safari/537.36","version":"22.0.0.11"}
{"reqId":"YPXwaxOtQ6qzJEnavm45SwAAJQQ","level":3,"time":"2021-07-19T21:38:04+00:00","remoteAddr":"96.241.162.132","user":"tjohnson","app":"mail","method":"POST","url":"/files/index.php/apps/mail/api/accounts","message":"Creating account failed: Connection to IMAP at mail.najessentials.com:993 failed. Mail server denied authentication.","userAgent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.124 Safari/537.36","version":"22.0.0.11"}
{"reqId":"YPX3FhufEY5yAaMYRsuinQAAzgo","level":3,"time":"2021-07-19T22:07:04+00:00","remoteAddr":"96.241.162.132","user":"tjohnson","app":"mail","method":"POST","url":"/files/index.php/apps/mail/api/accounts","message":"Creating account failed: Connection to IMAP at mail.najessentials.com:993 failed. Mail server denied authentication.","userAgent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.124 Safari/537.36","version":"22.0.0.11"}
{"reqId":"YPX4chufEY5yAaMYRsukqwAAzhM","level":3,"time":"2021-07-19T22:11:21+00:00","remoteAddr":"96.241.162.132","user":"tjohnson","app":"mail","method":"POST","url":"/files/index.php/apps/mail/api/accounts","message":"Creating account failed: Connection to IMAP at mail.najessentials.com:993 failed. Mail server denied authentication.","userAgent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.124 Safari/537.36","version":"22.0.0.11"}
{"reqId":"YPYCMRufEY5yAaMYRsu2QgAAzgM","level":3,"time":"2021-07-19T22:52:47+00:00","remoteAddr":"96.241.162.132","user":"tjohnson","app":"mail","method":"POST","url":"/files/index.php/apps/mail/api/accounts","message":"Creating account failed: Connection to IMAP at mail.najessentials.com:993 failed. Authentication failed.","userAgent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.124 Safari/537.36","version":"22.0.0.11"}
{"reqId":"YPYCyRufEY5yAaMYRsu3LQAAzgY","level":3,"time":"2021-07-19T22:55:19+00:00","remoteAddr":"96.241.162.132","user":"tjohnson","app":"mail","method":"POST","url":"/files/index.php/apps/mail/api/accounts","message":"Creating account failed: Connection to IMAP at webmail.najessentials.com:993 failed. Authentication failed.","userAgent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.124 Safari/537.36","version":"22.0.0.11"}
{"reqId":"YPYC4RufEY5yAaMYRsu3VAAAzgY","level":3,"time":"2021-07-19T22:55:39+00:00","remoteAddr":"96.241.162.132","user":"tjohnson","app":"mail","method":"POST","url":"/files/index.php/apps/mail/api/accounts","message":"Creating account failed: Connection to IMAP at najessentials.com:993 failed. Authentication failed.","userAgent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.124 Safari/537.36","version":"22.0.0.11"}
{"reqId":"YPYDY0lVo3pwME5xvKDfkQABIBg","level":3,"time":"2021-07-19T22:57:39+00:00","remoteAddr":"96.241.162.132","user":"tjohnson","app":"mail","method":"POST","url":"/files/index.php/apps/mail/api/accounts","message":"Creating account failed: Connection to IMAP at imap.najessentials.com:993 failed. Error connecting to mail server.","userAgent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.124 Safari/537.36","version":"22.0.0.11"}
{"reqId":"YPYDdklVo3pwME5xvKDfvAABIBg","level":3,"time":"2021-07-19T22:58:12+00:00","remoteAddr":"96.241.162.132","user":"tjohnson","app":"mail","method":"POST","url":"/files/index.php/apps/mail/api/accounts","message":"Creating account failed: Connection to IMAP at mail.najessentials.com:993 failed. Authentication failed.","userAgent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.124 Safari/537.36","version":"22.0.0.11"}
{"reqId":"YPYMGxrjKza59YqSQqKylgAAkww","level":3,"time":"2021-07-19T23:36:21+00:00","remoteAddr":"96.241.162.132","user":"tjohnson","app":"mail","method":"POST","url":"/files/index.php/apps/mail/api/accounts","message":"Creating account failed: Connection to IMAP at mail.najessentials.com:993 failed. Mail server denied authentication.","userAgent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.124 Safari/537.36","version":"22.0.0.11"}
{"reqId":"YPYNlhrjKza59YqSQqK1OwAAkwQ","level":3,"time":"2021-07-19T23:42:21+00:00","remoteAddr":"96.241.162.132","user":"tjohnson","app":"mail","method":"POST","url":"/files/index.php/apps/mail/api/accounts","message":"Creating account failed: Connection to IMAP at mail.najessentials.com:993 failed. Mail server denied authentication.","userAgent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.124 Safari/537.36","version":"22.0.0.11"}
{"reqId":"YPYPchV7jDcDtBWDKCIpvgAA6ws","level":3,"time":"2021-07-19T23:50:25+00:00","remoteAddr":"96.241.162.132","user":"tjohnson","app":"mail","method":"POST","url":"/files/index.php/apps/mail/api/accounts","message":"Creating account failed: Connection to IMAP at mail.najessentials.com:993 failed. Mail server denied authentication.","userAgent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.124 Safari/537.36","version":"22.0.0.11"}
{"reqId":"YPYQPhrjKza59YqSQqK5twAAggg","level":3,"time":"2021-07-19T23:52:44+00:00","remoteAddr":"96.241.162.132","user":"tjohnson","app":"mail","method":"POST","url":"/files/index.php/apps/mail/api/accounts","message":"Creating account failed: Connection to IMAP at mail.najessentials.com:143 failed. Authentication failed.","userAgent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.124 Safari/537.36","version":"22.0.0.11"}

**Comment by miaulalala** [comment]
@schmackz Have you verified your account and password have been entered correctly?

**Comment by schmackz** [comment]
> @schmackz Have you verified your account and password have been entered correctly?

As previously stated above it is not a username/password issue.

**Comment by ChristophWurst** [comment]
> Authentication failed

It is.

**Comment by schmackz** [comment]
> > Authentication failed
> 
> It is.

It isn't.. I can let you log in, create a brand new email account choosing your own password, and try to login and it won't work. You know how i know? Because I did that 20 times already..

**Comment by ChristophWurst** [comment]
Is it possible that you just used the wrong username or email? Have you tried both?

**Comment by schmackz** [comment]
> Is it possible that you just used the wrong username or email? Have you tried both?

I kinda feel like you are trolling. I’ve said 3 times now that it’s neither the username or password.

**Comment by miaulalala** [comment]
Is your IMAP server URL and port correct? In your logs you seem to be trying different domains.

**Comment by schmackz** [comment]
> Is your IMAP server URL and port correct? In your logs you seem to be trying different domains.

The error log shows me attempting to get any mail address on any of my domains to work..

Ports and hostnames are correct. The email username is correct. The password is correct. Creating account fails.

Last line in the log:
{"reqId":"YP6t6fIrocpJ7yn7tRGcYQAAwAU","level":3,"time":"2021-07-26T12:43:27+00:00","remoteAddr":"96.241.162.132","user":"tjohnson","app":"mail","method":"POST","url":"/cloud/index.php/apps/mail/api/accounts","message":"Creating account failed: Connection to IMAP at mail.tajcoessentials.com:143 failed. Mail server denied authentication.","userAgent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.164 Safari/537.36","version":"22.0.0.11"}

**Comment by ChristophWurst** [comment]
> I kinda feel like you are trolling. I’ve said 3 times now that it’s neither the username or password.

I'm trying to help. The IMAP lib reports that authentication failed.

*Sometimes* IMAP servers also give you a failed auth when a single IP opens too many connections. Could that be the case somehow?

**Comment by schmackz** [comment]
> > I kinda feel like you are trolling. I’ve said 3 times now that it’s neither the username or password.
> 
> I'm trying to help. The IMAP lib reports that authentication failed.
> 
> _Sometimes_ IMAP servers also give you a failed auth when a single IP opens too many connections. Could that be the case somehow?

I don't think so, because I'm able to add the account to Thunderbird from the same machine and send/receive email. But possibly..

**Comment by schmackz** [comment]
When adjusting the email settings in basic settings I encountered this error: A problem occurred while sending the email. Please revise your settings. (Error: Connection could not be established with host mail.tajcoessentials.com :stream_socket_client(): Peer certificate CN=`*.prod.phx3.secureserver.net' did not match expected CN=`mail.tajcoessentials.com')

So im gonna assume my issues are with my SSL certificate. Godaddy is really annoying.
