### ISSUE TITLE
Unable to add event to Calendar

### ISSUE THREAD

**Issue by nick-stocks** [nextcloud/mail#5355]
### Expected behavior
Tell us what should happen
When clicking Add to Calendar, it should add to calendar

### Actual behavior
Tell us what happens instead
The spinny circle spins forever

![Screenshot 2021-07-21 at 11 44 29](https://user-images.githubusercontent.com/22432139/126476910-d4b10a26-2a32-4569-bcdd-bc9bb5cb38c8.png)

### Mail app

**Mail app version:** (see apps admin page, e.g. 0.5.3)
1.10.1

**Mailserver or service:** (e.g. Outlook, Yahoo, Gmail, Exchange,...)
Dovecot IMAP, localhost

### Server configuration

**Operating system**: (e.g. Debian 8)
Ubuntu 20.2.2

**Web server:** (e.g. Apache, Nginx,...)
Nginx

**Database:** (e.g. MariaDB, SQLite or PostgreSQL)
MariaDB

**PHP version:** (e.g. 7.0)
7.4

**Nextcloud Version:** (see admin page, e.g. 13.0.2)
22.0.0

#### Client configuration
**Browser:** (e.g. Firefox 48)
Safari 15.0

**Operating system:** (e.g. Arch Linux)
MacOS Monterey

**Comment by NeCeN** [comment]
I have the same trouble on Chrome 91 but not with Firefox 89.

**Comment by miaulalala** [comment]
Hi @nick-stocks , thanks for your report. Could you please open your dev console and see what kind of errors you get? That would be very helpful!

**Comment by nick-stocks** [comment]
Hi @miaulalala. See below. 

![Screenshot 2021-07-22 at 11 41 19](https://user-images.githubusercontent.com/22432139/126629129-df56b241-e828-470c-872b-da49e16ce2e5.png)

Links through to this block of code

```
	for (const acl of acls) {
		if (acl.grant?.privilege?.write !== undefined) {
			return true
		}
	}
```

**Comment by miaulalala** [comment]
@kesselb wasn't that what you debugged earlier this weeK?

**Comment by kesselb** [comment]
Yes ;)

**Comment by ChristophWurst** [comment]
https://github.com/nextcloud/mail/blob/888a47c48b5a0afb35cca8f69485d58932bacac1/src/service/DAVService.js#L35-L38 I noticed this as well. If there is only one ACL then it's not an array.

**Comment by ChristophWurst** [comment]
We can extract this change and backport the fix in the meantime. That snippet is from https://github.com/nextcloud/mail/pull/5178

**Comment by nick-stocks** [comment]
Any idea when this fix will be released to apply to NextCloud? Or is there an easy way I could patch my env?

**Comment by GretaD** [comment]
> Any idea when this fix will be released to apply to NextCloud? Or is there an easy way I could patch my env?

We will try to do a release this week
