### ISSUE TITLE
Configure mail app for IMAP authenticated users

### ISSUE THREAD

**Issue by rayfun** [nextcloud/mail#536]
### Steps to reproduce
1. Login to Nextcloud through IMAP auth backend
2. Go to mail app

### Expected behaviour
Mail app should be setup with auth credentials from IMAP authentication and a set of preconfigured values for host, port etc

### Actual behaviour
IMAP authentication backend works properly but mail app needs to be configured manually.

### Mail app

**Mail app version:** (see apps admin page)
0.7.3

**Mailserver or service:** (e.g. Outlook, Yahoo, Gmail, Exchange,...)
Postfix 3.1.0-3/Dovecot 2.2.22-1ubuntu2.4

**Transport security - IMAP:** (None, SSL, TLS, STARTTLS) 

**Transport security - SMTP:** (None, SSL, TLS, STARTTLS)

**Number of accounts:**

**Mail app version build date:** (only if you are using a Nightly Build)

### Server configuration

**Operating system**:
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=16.04
DISTRIB_CODENAME=xenial
DISTRIB_DESCRIPTION="Ubuntu 16.04.3 LTS"

**Web server:**
2.4.18-2ubuntu3.4
**Database:**

**PHP version:**

**Version:** (see admin page)

**Updated from an older version or fresh install:**

**List of activated apps:**

```
If you have access to your command line run e.g.:
sudo -u www-data php occ app:list
from within your server installation folder
```

**The content of config/config.php:**

<details>
```
If you have access to your command line run e.g.:
sudo -u www-data php occ config:list system
from within your Nextcloud installation folder

or

Insert your config.php content here
Make sure to remove all sensitive content such as passwords. (e.g. database password, passwordsalt, secret, smtp password, …)
```
</details>

#### Client configuration
**Browser:**

**Operating system:**

##### Web server error log
```
Insert your webserver log here
```

##### Server log (data/nextcloud.log)
<details>
```
Insert your server log here
```
</details>

##### Horde IMAP log (data/horde_imap.log)
<details>
```
Insert your horde IMAP log here, see https://github.com/nextcloud/mail#debug-mode
```
</details>

##### Horde SMTP log (data/horde_smtp.log)
<details>
```
Insert your horde SMTP log here, see https://github.com/nextcloud/mail#debug-mode
```
</details>

##### Browser log
<details>
```
Insert your browser log here, this could for example include:

a) The javascript console log
b) The network log 
c) ...
```
</details>

**Comment by ChristophWurst** [comment]
This feature was implemented in https://github.com/nextcloud/mail/pull/28. You can find a sample configuration at https://github.com/nextcloud/mail/pull/28#issuecomment-307884360. Unfortunately, we don't have any better documentation *yet*, but feel free to contribute such as soon as you managed to set it up for yourself to help others :)
