### ISSUE TITLE
.ics (iCal) file sent as mail attachment is not imported into calendar

### ISSUE THREAD

**Issue by raider-com** [nextcloud/mail#5364]
### Expected behavior
When selecting 'Import into calendar' from ics link, mail app should import the meeting into the calendar app after asking which calendar to import to.

### Actual behavior
Selecting 'Import into calendar' results in a spinner spinning, but never does anything.
Additionally, in the browser console, this message is displayed: 'Uncaught (in promise) TypeError: e is not iterable'
No non-2xx error message is recorded in the network tab, just the above error in the console.

### Mail app
**Mail app version:** (see apps admin page, e.g. 0.5.3)
1.10.1

**Mailserver or service:** 
Gmail

Nextcloud v22 docker install
Calendar 2.3.1

Mail app linked with an email account receives an invite to a meeting (from gmail).  Clicking on the attachment link at the bottom offers 2 options to import into calendar (calendar.ics and invite.ics). 
Wasn't sure whether or not to reopen https://github.com/nextcloud/mail/issues/2134 or not, and I can reproduce the issue.
I'm new to using nextcloud, but eager to use it more, the more I'm seeing of the product.

### Server configuration

**Operating system**: (e.g. Debian 8)
Ubuntu 20.04 Server install

**Web server:** (e.g. Apache, Nginx,...)
Nginx reverse proxy to the nextcloud app container

**Database:** (e.g. MariaDB, SQLite or PostgreSQL)
SQLite

**PHP version:** (e.g. 7.0)
7.4.21

**Nextcloud Version:** (see admin page, e.g. 13.0.2)
22.0

#### Client configuration
**Browser:** (e.g. Firefox 48)
Chrome Version 92.0.4515.107 (Official Build) (64-bit)
Firefox 90.0 (64-bit)

**Operating system:** (e.g. Arch Linux)
Ubuntu 20.04 Desktop

**Comment by kesselb** [comment]
Thanks for reporting :+1: 

Closing in favor of https://github.com/nextcloud/mail/issues/5355.
