### ISSUE TITLE
Mailbox does not connect - spinner spins forever

### ISSUE THREAD

**Issue by beccon4** [nextcloud/mail#5373]
### Expected behavior
When I open the Mail application, it should display the mailbox' content within reasonable time

### Actual behavior
Bit nothing happens - it shows the circling wait indicator for ages (>12h) Reconfiguring the mailbox has no effect, neither does have reinstalling the Mail app nor occ commands. Changing the ssl methods doesn't do anything either.

What I can read though is the number of unread messages and sometimes the subfolders of INBOX as well. Sometimes - when I try to open a subfolder I'm displayed the content.

I have Rainloop installed on the same Nextcloud and I have a couple of clients too - all work perfectly with the same mailbox. I closed them all for the test to avoid interference.

Mail app Version is  1.10.2 and I have the latest 21 Nextcloud.
My Mailserver is Qmail on own server with Plesk 

Very strange recurring NC log entries while the App tries to retrieve (please keep in mind: Rainloop is installed on this server but here we use the Mail App.

`21.0.1.1"}
{"reqId":"cvMwAopE3VIdpgA7X9q6","level":1,"time":"2021-07-30T09:42:49+00:00","remoteAddr":"89.16.xx.yy","user":"beccon","app":"no app in context","method":"PROPFIND","url":"/remote.php/webdav/Dokumente/Projekte/Technik/zertifikate/Mail/","message":"Deprecated event type for {\"[object] (OCP\\SabrePluginEvent)\":{\"*statusCode\":200,\"*message\":\"\",\"*server\":{\"[object] (OCA\\DAV\\Connector\\Sabre\\Server)\":{\"tree\":\"[object] (OCA\\DAV\\Connector\\Sabre\\ObjectTree)\",\"*baseUri\":\"/remote.php/webdav/\",\"httpResponse\":\"[object] (Sabre\\HTTP\\Response)\",\"httpRequest\":\"[object] (Sabre\\HTTP\\Request)\",\"sapi\":\"[object] (Sabre\\HTTP\\Sapi)\",\"*plugins\":[],\"transactionType\":null,\"protectedProperties\":{\"...\":\"Over 20 items, aborting normalization\"},\"debugExceptions\":false,\"resourceTypeMapping\":[],\"enablePropfindDepthInfinity\":true,\"xml\":\"[object] (Sabre\\DAV\\Xml\\Service)\",\"*logger\":null,\"*listeners\":{\"...\":\"Over 20 items, aborting normalization\"},\"*wildcardListeners\":[],\"*listenerIndex\":[]}},\"Symfony\\Contracts\\EventDispatcher\\EventpropagationStopped\":false}}: null","userAgent":"Mozilla/5.0 (Android) Nextcloud-android/3.16.1","version":"21.0.1.1"}
{"reqId":"sTwwIinVDG1R8RCY8FGp","level":0,"time":"2021-07-30T09:42:50+00:00","remoteAddr":"89.16.xx.yy","user":"beccon","app":"contacts","method":"PROPFIND","url":"/remote.php/webdav/Dokumente/Projekte/Technik/zertifikate/Mail/Conrad%20Beckert%20conrad_b%40myserver.xx-(0x571AD8E62D5CE9D6)-gesamt.asc","message":"/appinfo/app.php is deprecated, use \\OCP\\AppFramework\\Bootstrap\\IBootstrap on the application class instead.","userAgent":"Mozilla/5.0 (Android) Nextcloud-android/3.16.1","version":"21.0.1.1"}
{"reqId":"sTwwIinVDG1R8RCY8FGp","level":0,"time":"2021-07-30T09:42:50+00:00","remoteAddr":"89.16.xx.yy","user":"beccon","app":"drawio","method":"PROPFIND","url":"/remote.php/webdav/Dokumente/Projekte/Technik/zertifikate/Mail/Conrad%20Beckert%20conrad_b%40myserver.xx-(0x571AD8E62D5CE9D6)-gesamt.asc","message":"/appinfo/app.php is deprecated, use \\OCP\\AppFramework\\Bootstrap\\IBootstrap on the application class instead.","userAgent":"Mozilla/5.0 (Android) Nextcloud-android/3.16.1","version":"21.0.1.1"}
{"reqId":"sTwwIinVDG1R8RCY8FGp","level":0,"time":"2021-07-30T09:42:50+00:00","remoteAddr":"89.16.xx.yy","user":"beccon","app":"files_external","method":"PROPFIND","url":"/remote.php/webdav/Dokumente/Projekte/Technik/zertifikate/Mail/Conrad%20Beckert%20conrad_b%40myserver.xx-(0x571AD8E62D5CE9D6)-gesamt.asc","message":"/appinfo/app.php is deprecated, use \\OCP\\AppFramework\\Bootstrap\\IBootstrap on the application class instead.","userAgent":"Mozilla/5.0 (Android) Nextcloud-android/3.16.1","version":"21.0.1.1"}
{"reqId":"sTwwIinVDG1R8RCY8FGp","level":0,"time":"2021-07-30T09:42:50+00:00","remoteAddr":"89.16.xx.yy","user":"beccon","app":"files_sharing","method":"PROPFIND","url":"/remote.php/webdav/Dokumente/Projekte/Technik/zertifikate/Mail/Conrad%20Beckert%20conrad_b%40myserver.xx-(0x571AD8E62D5CE9D6)-gesamt.asc","message":"/appinfo/app.php is deprecated, use \\OCP\\AppFramework\\Bootstrap\\IBootstrap on the application class instead.","userAgent":"Mozilla/5.0 (Android) Nextcloud-android/3.16.1","version":"21.0.1.1"}
{"reqId":"sTwwIinVDG1R8RCY8FGp","level":0,"time":"2021-07-30T09:42:50+00:00","remoteAddr":"89.16.xx.yy","user":"beccon","app":"maps","method":"PROPFIND","url":"/remote.php/webdav/Dokumente/Projekte/Technik/zertifikate/Mail/Conrad%20Beckert%20conrad_b%40myserver.xx-(0x571AD8E62D5CE9D6)-gesamt.asc","message":"/appinfo/app.php is deprecated, use \\OCP\\AppFramework\\Bootstrap\\IBootstrap on the application class instead.","userAgent":"Mozilla/5.0 (Android) Nextcloud-android/3.16.1","version":"21.0.1.1"}
{"reqId":"sTwwIinVDG1R8RCY8FGp","level":1,"time":"2021-07-30T09:42:50+00:00","remoteAddr":"89.16.xx.yy","user":"beccon","app":"no app in context","method":"PROPFIND","url":"/remote.php/webdav/Dokumente/Projekte/Technik/zertifikate/Mail/Conrad%20Beckert%20conrad_b%40myserver.xx-(0x571AD8E62D5CE9D6)-gesamt.asc","message":"Deprecated event type for {\"[object] (OCP\\SabrePluginEvent)\":{\"*statusCode\":200,\"*message\":\"\",\"*server\":{\"[object] (OCA\\DAV\\Connector\\Sabre\\Server)\":{\"tree\":\"[object] (OCA\\DAV\\Connector\\Sabre\\ObjectTree)\",\"*baseUri\":\"/remote.php/webdav/\",\"httpResponse\":\"[object] (Sabre\\HTTP\\Response)\",\"httpRequest\":\"[object] (Sabre\\HTTP\\Request)\",\"sapi\":\"[object] (Sabre\\HTTP\\Sapi)\",\"*plugins\":[],\"transactionType\":null,\"protectedProperties\":{\"...\":\"Over 20 items, aborting normalization\"},\"debugExceptions\":false,\"resourceTypeMapping\":[],\"enablePropfindDepthInfinity\":true,\"xml\":\"[object] (Sabre\\DAV\\Xml\\Service)\",\"*logger\":null,\"*listeners\":{\"...\":\"Over 20 items, aborting normalization\"},\"*wildcardListeners\":[],\"*listenerIndex\":[]}},\"Symfony\\Contracts\\EventDispatcher\\EventpropagationStopped\":false}}: null","userAgent":"Mozilla/5.0 (Android) Nextcloud-android/3.16.1","version":"21.0.1.1"}
{"reqId":"GMIoc6eoS2yBZT9PGlk5","level":0,"time":"2021-07-30T09:42:55+00:00","remoteAddr":"89.16.xx.yy","user":"beccon","app":"apporder","method":"GET","url":"/index.php/apps/mail/api/messages?mailboxId=123&filter=is:pi-important&limit=20","message":"/appinfo/app.php is deprecated, use \\OCP\\AppFramework\\Bootstrap\\IBootstrap on the application class instead.","userAgent":"Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:90.0) Gecko/20100101 Firefox/90.0","version":"21.0.1.1"}
{"reqId":"GMIoc6eoS2yBZT9PGlk5","level":0,"time":"2021-07-30T09:42:55+00:00","remoteAddr":"89.16.xx.yy","user":"beccon","app":"contacts","method":"GET","url":"/index.php/apps/mail/api/messages?mailboxId=123&filter=is:pi-important&limit=20","message":"/appinfo/app.php is deprecated, use \\OCP\\AppFramework\\Bootstrap\\IBootstrap on the application class instead.","userAgent":"Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:90.0) Gecko/20100101 Firefox/90.0","version":"21.0.1.1"}
{"reqId":"GMIoc6eoS2yBZT9PGlk5","level":0,"time":"2021-07-30T09:42:55+00:00","remoteAddr":"89.16.xx.yy","user":"beccon","app":"drawio","method":"GET","url":"/index.php/apps/mail/api/messages?mailboxId=123&filter=is:pi-important&limit=20","message":"/appinfo/app.php is deprecated, use \\OCP\\AppFramework\\Bootstrap\\IBootstrap on the application class instead.","userAgent":"Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:90.0) Gecko/20100101 Firefox/90.0","version":"21.0.1.1"}
{"reqId":"GMIoc6eoS2yBZT9PGlk5","level":0,"time":"2021-07-30T09:42:55+00:00","remoteAddr":"89.16.xx.yy","user":"beccon","app":"files_external","method":"GET","url":"/index.php/apps/mail/api/messages?mailboxId=123&filter=is:pi-important&limit=20","message":"/appinfo/app.php is deprecated, use \\OCP\\AppFramework\\Bootstrap\\IBootstrap on the application class instead.","userAgent":"Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:90.0) Gecko/20100101 Firefox/90.0","version":"21.0.1.1"}
{"reqId":"GMIoc6eoS2yBZT9PGlk5","level":0,"time":"2021-07-30T09:42:55+00:00","remoteAddr":"89.16.xx.yy","user":"beccon","app":"files_mindmap","method":"GET","url":"/index.php/apps/mail/api/messages?mailboxId=123&filter=is:pi-important&limit=20","message":"/appinfo/app.php is deprecated, use \\OCP\\AppFramework\\Bootstrap\\IBootstrap on the application class instead.","userAgent":"Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:90.0) Gecko/20100101 Firefox/90.0","version":"21.0.1.1"}
{"reqId":"GMIoc6eoS2yBZT9PGlk5","level":0,"time":"2021-07-30T09:42:55+00:00","remoteAddr":"89.16.xx.yy","user":"beccon","app":"files_sharing","method":"GET","url":"/index.php/apps/mail/api/messages?mailboxId=123&filter=is:pi-important&limit=20","message":"/appinfo/app.php is deprecated, use \\OCP\\AppFramework\\Bootstrap\\IBootstrap on the application class instead.","userAgent":"Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:90.0) Gecko/20100101 Firefox/90.0","version":"21.0.1.1"}
{"reqId":"GMIoc6eoS2yBZT9PGlk5","level":0,"time":"2021-07-30T09:42:55+00:00","remoteAddr":"89.16.xx.yy","user":"beccon","app":"maps","method":"GET","url":"/index.php/apps/mail/api/messages?mailboxId=123&filter=is:pi-important&limit=20","message":"/appinfo/app.php is deprecated, use \\OCP\\AppFramework\\Bootstrap\\IBootstrap on the application class instead.","userAgent":"Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:90.0) Gecko/20100101 Firefox/90.0","version":"21.0.1.1"}`

**Comment by miaulalala** [comment]
Hi @beccon4, thanks for your report. Can you have a look at your console while having a mailbox in this loading state? What does it report?
