### ISSUE TITLE
How to disable tagging

### ISSUE THREAD

**Issue by doc75** [nextcloud/mail#5375]
### Question

I wonder how I can remove the automatic tagging. Indeed, I am not using it and when accessing my mail account with thunderbird I have the **Important** tag put on some of the mail and I have to remove it manually all the time.

In the settings, I have unchecked both options:
- Automatically classify importance of new email
- Allow app to collect data about your interactions...

But it still classify some email as important.

Thanks for your help.

**Comment by miaulalala** [comment]
Hi @doc75 , this is due to a bug in the tagging logic. The fix is not yet released, see #5290
