### ISSUE TITLE
occ mail:account:sync returns sql error: "Did expect one result but found none"

### ISSUE THREAD

**Issue by D3V1LC0D3R** [nextcloud/mail#5405]
### Expected behavior
no error

### Actual behavior
when executing "occ mail:account:sync [ACCOUNT ID]" the occ command returns:
```Did expect one result but found none when executing: query SELECT * FROM `*PREFIX*mail_accounts` WHERE `id` = :dc  
  Value1";```

### Mail app

**Mail app version:** 1.10.2

**Mailserver or service:** imap&smtp over SSL 1 account

### Server configuration

**Operating system**: ubuntu

**Web server:** nginx + php-fpm

**Database:** MariaDB

**PHP version:** 7.4

**Nextcloud Version:** 21.0.3

#### Client configuration
**Browser:** any (chromium, firefox or brave)

**Operating system:** any

**other things that may be related**
when opening the mail app on the web i only get a blank page

**Comment by ChristophWurst** [comment]
>  "occ mail:account:sync "

Did you really run it like that without any argument? There is one required argument, the account ID. You can't omit it.

**Comment by D3V1LC0D3R** [comment]
no otherwise it would hav given me a different error

**Comment by ChristophWurst** [comment]
I'm not sure if you confirmed that you didn't run it with an argument. How exactly did you call it and what is the *different* error?

**Comment by D3V1LC0D3R** [comment]
occ mail:account:sync:                                                 
  Not enough arguments (missing: "account-id").  
  mail:account:sync [-f|--force] [--] <account-id>

occ mail:account:sync <Account ID>
  Did expect one result but found none when executing: query "SELECT * FROM `*PREFIX*mail_accounts` WHERE `id` = :dc  
  Value1";

**Comment by D3V1LC0D3R** [comment]
i found out why it seemed that i didnt supply any arguments. If you write < then some string then > github hides it

**Comment by ChristophWurst** [comment]
Fix is at https://github.com/nextcloud/mail/pull/5407

**Comment by D3V1LC0D3R** [comment]
if im not misunderstanding: this error means that the account doesnt exist?

**Comment by ChristophWurst** [comment]
yes.

**Comment by D3V1LC0D3R** [comment]
ohh thats not good. I recently moved servers and this user definitely exists (or occ user:list is wrong)

**Comment by D3V1LC0D3R** [comment]
also when creating a fresh temp account with "occ user:add tmp" and then do: "occ mail:account:sync tmp" i get the exact same error

**Comment by ChristophWurst** [comment]
yeah because the account is identified by an ID, not the username.

**Comment by D3V1LC0D3R** [comment]
another strange thing: when i log into this temp account and go to mails i get a blank screen

**Comment by ChristophWurst** [comment]
okay this is turning into a support session. Please use https://help.nextcloud.com/ for user support.

The command works as is if you give it a correct ID. See https://github.com/nextcloud/mail/blob/master/doc/admin.md for our admin docs.

**Comment by D3V1LC0D3R** [comment]
yeah, im sorry
