### ISSUE TITLE
Undo sending an email

### ISSUE THREAD

**Issue by nimishavijay** [nextcloud/mail#5438]
## Feature Request

Many emails are sent because you accidentally hit the "Send" button prematurely. In Gmail, Apple mail, Outlook and Mailbird there is an option to undo sending an email for that's available for a few seconds after you hit "send". We can have something like that in Mail as well.

Here's how Gmail does it (pretty much everyone else does it the same way too).
After clicking on send, there's a little pop up in the bottom left corner of the screen which says "Sending..." which turns into this popup once the message has been sent. Here you can either undo the sending, which turns it back into a draft and opens the message composer, or view the message, or dismiss the popup.
![image](https://user-images.githubusercontent.com/52440189/129203871-c6b15713-9a8e-470f-9e64-f906e3b00a32.png)

The duration for showing this popup is configurable in the settings, but even just having this option with a set duration of 15 seconds or so would be super useful.

## Implementation

* [x] #5884
* [x] Utilize the outbox
  + Push the message to the outbox when fake sending it
  + Send me message after x seconds
  + Drop the message off the outbox if sending is undone

---

cc @jancborchardt and @karlitschek

**Comment by karlitschek** [comment]
very cool!!! 👍

**Comment by GretaD** [comment]
Steps how this will work:\
1. I click send
2. This  feedback will  be shown and look more or less like this: 
![undo](https://user-images.githubusercontent.com/12728974/160658273-b71487ed-d697-42a9-bee7-b2a096c78f99.png)
3. After i click the undo button it will take me to the modal message in an editing state of the message i am sending i order to do the changes i need before sending again

@jancborchardt @nimishavijay

**Comment by ChristophWurst** [comment]
The alternative would have been to stay in the existing composer modal and where we already say *Message sent* there could be an *Undo* button underneath that goes back to the editor. That would avoid the closing and re-opening of the modal.

@jancborchardt @nimishavijay your call.

**Comment by nimishavijay** [comment]
> The alternative would have been to stay in the existing composer modal and where we already say

This sounds good. We could have an empty content component with "Message sent" as the text and a button that says "Undo". The modal could disappear automatically after 5 seconds or 7 seconds, or dismissed using a close button on the top right corner.

**Comment by nimishavijay** [comment]
Yep, an undo button below the "Message sent". And we should automatically close the modal after a few seconds (however long the undo action is available -- around 5 seconds would work)

**Comment by GretaD** [comment]
the second proposal will look like this

![undomodal](https://user-images.githubusercontent.com/12728974/160862801-5152e05e-d346-4bd6-aad8-3989a2b11ff8.png)

**Comment by jancborchardt** [comment]
@GretaD sorry, to clarify, I meant the flow you mentioned with the approach of notification, not modal.

Reason being: Having to undo a mail is an exception, not the rule, so it shouldn’t be shown for several seconds seemingly blocking further interaction. Feedback about message being sent is enough via notification.

**Comment by jancborchardt** [comment]
@nimishavijay yup, exactly. :) Notification is enough for this 1 sentence feedback + button because you want to focus on other things. Modal is only needed when the composer is there because that’s what the focus is on then.
