### ISSUE TITLE
Getting a confirmation page when clicking on e-mail links

### ISSUE THREAD

**Issue by leandro-lucarella-sociomantic** [nextcloud/mail#547]
This looks like #250.

### Steps to reproduce
1. Open an e-mail with an external link

### Expected behaviour
I should get to the link I just clicked

### Actual behaviour
I get to a redirect page where I have to confirm I want to continue to that link.

### General server configuration

**Operating system:** Linux omicron 4.10.0-36-generic #40-Ubuntu SMP Tue Sep 19 12:15:43 UTC 2017 x86_64

**Web server:** Apache/2.4.25 (Ubuntu) (apache2handler)

**Database:** mysql 5.7.19

**PHP version:** 7.0.22-0ubuntu0.17.04.1
<details>
        <summary>PHP-modules loaded</summary>

```
 - Core
 - date
 - libxml
 - openssl
 - pcre
 - zlib
 - filter
 - hash
 - Reflection
 - SPL
 - session
 - standard
 - apache2handler
 - mysqlnd
 - PDO
 - xml
 - apcu
 - calendar
 - ctype
 - curl
 - dom
 - mbstring
 - fileinfo
 - ftp
 - gd
 - gettext
 - iconv
 - json
 - exif
 - mcrypt
 - mysqli
 - pdo_mysql
 - Phar
 - posix
 - readline
 - shmop
 - SimpleXML
 - sockets
 - sysvmsg
 - sysvsem
 - sysvshm
 - tokenizer
 - wddx
 - xmlreader
 - xmlwriter
 - xsl
 - zip
 - Zend OPcache
```
</details>

### Nextcloud configuration

**Nextcloud version:** 12.0.3 - 12.0.3.3

**Updated from an older Nextcloud/ownCloud or fresh install:** YOUR ANSWER HERE

**Where did you install Nextcloud from:**  YOUR ANSWER HERE

**Are you using external storage, if yes which one:** Array
(
    [0] => \OC\Files\Storage\Local
    [1] => \OCA\Files_External\Lib\Storage\FTP
    [2] => \OC\Files\Storage\DAV
    [3] => \OCA\Files_External\Lib\Storage\OwnCloud
    [4] => \OCA\Files_External\Lib\Storage\SFTP
    [5] => \OCA\Files_External\Lib\Storage\AmazonS3
    [6] => \OCA\Files_External\Lib\Storage\Dropbox
    [7] => \OCA\Files_External\Lib\Storage\Google
    [8] => \OCA\Files_External\Lib\Storage\Swift
    [9] => \OCA\Files_External\Lib\Storage\SFTP
    [10] => \OCA\Files_External\Lib\Storage\SMB
    [11] => \OCA\Files_External\Lib\Storage\SMB
)

**Are you using encryption:** no

**Are you using an external user-backend, if yes which one:** YOUR ANSWER HERE (LDAP/ActiveDirectory/Webdav/...)

<details>
        <summary>Signing status</summary>

```
[]
```
</details>

<details>
        <summary>Enabled apps</summary>

```
 - activity: 2.5.2
 - admin_audit: 1.2.0
 - audioplayer: 2.1.0
 - bruteforcesettings: 1.0.2
 - calendar: 1.5.5
 - checksum: 0.3.5
 - comments: 1.2.0
 - contacts: 1.5.3
 - dav: 1.3.0
 - external: 2.0.3
 - federatedfilesharing: 1.2.0
 - federation: 1.2.0
 - files: 1.7.2
 - files_automatedtagging: 1.2.2
 - files_external: 1.3.0
 - files_pdfviewer: 1.1.1
 - files_reader: 1.0.4
 - files_sharing: 1.4.0
 - files_texteditor: 2.4.1
 - files_trashbin: 1.2.0
 - files_versions: 1.5.0
 - files_videoplayer: 1.1.0
 - firstrunwizard: 2.1
 - gallery: 17.0.0
 - issuetemplate: 0.2.2
 - keeweb: 0.4.0
 - logreader: 2.0.0
 - lookup_server_connector: 1.0.0
 - mail: 0.7.3
 - nextant: 1.0.8
 - nextcloud_announcements: 1.1
 - notes: 2.3.1
 - notifications: 2.0.0
 - oauth2: 1.0.5
 - password_policy: 1.2.2
 - provisioning_api: 1.2.0
 - serverinfo: 1.2.0
 - sharebymail: 1.2.0
 - socialsharing_email: 1.0.1
 - survey_client: 1.0.0
 - systemtags: 1.2.0
 - tasks: 0.9.5
 - theming: 1.3.0
 - twofactor_backupcodes: 1.1.1
 - twofactor_totp: 1.3.1
 - updatenotification: 1.2.0
 - workflowengine: 1.2.0
```
</details>

<details>
        <summary>Disabled apps</summary>

```
 - encryption
 - user_external
 - user_ldap
```
</details>

<details>
        <summary>Content of config/config.php</summary>

```
{
    "defaultapp": "mail",
    "instanceid": "***REMOVED SENSITIVE VALUE***",
    "passwordsalt": "***REMOVED SENSITIVE VALUE***",
    "datadirectory": "***REMOVED SENSITIVE VALUE***",
    "dbtype": "mysql",
    "version": "12.0.3.3",
    "appstoreenabled": true,
    "apps_paths": [
        {
            "path": "***REMOVED SENSITIVE VALUE***",
            "url": "\/apps",
            "writable": true
        }
    ],
    "dbname": "owncloud",
    "dbhost": "localhost",
    "dbtableprefix": "oc_",
    "dbuser": "***REMOVED SENSITIVE VALUE***",
    "dbpassword": "***REMOVED SENSITIVE VALUE***",
    "installed": true,
    "forcessl": true,
    "theme": "",
    "maintenance": false,
    "trusted_domains": [
        "***REMOVED SENSITIVE VALUE***"
    ],
    "mail_from_address": "***REMOVED SENSITIVE VALUE***",
    "mail_smtpmode": "php",
    "mail_smtpname": "***REMOVED SENSITIVE VALUE***",
    "mail_smtppassword": "***REMOVED SENSITIVE VALUE***",
    "mail_domain": "***REMOVED SENSITIVE VALUE***",
    "secret": "***REMOVED SENSITIVE VALUE***",
    "remember_login_cookie_lifetime": 1296000,
    "session_lifetime": 259200,
    "session_keepalive": true,
    "preview_max_scale_factor": 1,
    "enabledPreviewProviders": [
        "OC\\Preview\\Image",
        "OC\\Preview\\Illustrator",
        "OC\\Preview\\Postscript",
        "OC\\Preview\\Photoshop",
        "OC\\Preview\\TIFF"
    ],
    "forceSSLforSubdomains": true,
    "memcache.local": "\\OC\\Memcache\\APCu",
    "appstore.experimental.enabled": true,
    "log_type": "owncloud",
    "logfile": "***REMOVED SENSITIVE VALUE***",
    "loglevel": 2,
    "trashbin_retention_obligation": "auto",
    "updatechecker": false,
    "asset-pipeline.enabled": true,
    "updater.release.channel": "stable",
    "overwrite.cli.url": "***REMOVED SENSITIVE VALUE***"
}
```
</details>

### Client configuration

**Browser:** Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:56.0) Gecko/20100101 Firefox/56.0

**Operating system:** Ubuntu Xenial

### Logs

<details>
        <summary>Web server error log</summary>

```
Insert your webserver log here
```
</details>

<details>
        <summary>Nextcloud log (data/nextcloud.log)</summary>

```
Insert your Nextcloud log here
```
</details>

<details>
        <summary>Browser log</summary>

```
Insert your browser log here, this could for example include:

a) The javascript console log
b) The network log
c) ...
```
</details>

**Comment by ChristophWurst** [comment]
Do you, by chance, know whether that is an HTML or a text email?

**Comment by ChristophWurst** [comment]
@jancborchardt I think you told me about a similar problem last week.

**Comment by jancborchardt** [comment]
Yep, still have the same issue. Definitely with HTML mails, need to test if with others too.

**Comment by leandro-lucarella-sociomantic** [comment]
HTML.

**Comment by leandro-lucarella-sociomantic** [comment]
I can check if it happens too for plain text mails.

**Comment by leandro-lucarella-sociomantic** [comment]
Getting it for plain text e-mails too.

**Comment by leandro-lucarella-sociomantic** [comment]
No, wait, it seems like it was an HTML e-mail in disguise. It seems to work as expected for plain text messages. Is there any way to tell for sure from the e-mail app? Any way to get the e-mail source or something? I had to check with another e-mail client to make sure the e-mail I was testing was really plain text.

**Comment by ChristophWurst** [comment]
> No, wait, it seems like it was an HTML e-mail in disguise. It seems to work as expected for plain text messages. Is there any way to tell for sure from the e-mail app? Any way to get the e-mail source or something? I had to check with another e-mail client to make sure the e-mail I was testing was really plain text.

Not yet, unfortunately.

**Comment by ChristophWurst** [comment]
Could someone please check whether the `Referer` HTTP header is set for the redirect page/URL? You should be able to inspect that with your browser's developer tools in the network tab.

**Comment by leandro-lucarella-sociomantic** [comment]
I don't see any `Referer` header for the `/index.php/apps/mail/redirect?src=...` request.

**Comment by jancborchardt** [comment]
Doesn’t look like it, no:
![screenshot from 2017-09-28 11-47-29](https://user-images.githubusercontent.com/925062/30960277-d604884a-a442-11e7-8734-eaa7f32cbe69.png)

**Comment by jancborchardt** [comment]
And I can confirm the issue is just there for HTML mails. Links in plaintext mails get opened directly, even without redirect page.

**Comment by ChristophWurst** [comment]
Good, then I know why the automated redirect doesn't work. We only do if it a correct `Redirect` header is set. Does the anchor element for the external link in your email have a `noreferrer` attribute or similar?

**Comment by jancborchardt** [comment]
> Does the anchor element for the external link in your email have a noreferrer attribute or similar?

Yup! And if I edit that out manually, it works. :) So I guess we should strip noreferrer automatically from anchor elements?

**Comment by ChristophWurst** [comment]
> Yup! And if I edit that out manually, it works. :) So I guess we should strip noreferrer automatically from anchor elements?

https://github.com/nextcloud/mail/pull/409 🤔

**Comment by jancborchardt** [comment]
@ChristophWurst right – however I’m on master (also on any branch which has that fix) and it doesn’t seem to work properly. Get a bunch of HTML mails sent to you, like from newsletters or company emails or Github notifications, and test it out. :)

**Comment by ChristophWurst** [comment]
Maybe the attribute already exists on the original anchor element. I have to check. So far I have not seen this problem on my instance, using the latest released version.

**Comment by jancborchardt** [comment]
Yes, this also happens for me again with latest master (both server and Mail app).

**Comment by mat-m** [comment]
Confirmed with Nextcloud 15.0.0 and Mail 0.11.0. 

Very annoying because you can't open such links in a private window without authenticating again on Nextcloud to get the redirect ...

**Comment by mat-m** [comment]
@ChristophWurst do you reproduce with NC 15 ?

**Comment by ChristophWurst** [comment]
Yes

**Comment by jancborchardt** [comment]
Just tested with latest version, this is not an issue anymore for neither plaintext nor HTML mails.
