### ISSUE TITLE
Mail gap analysis issues

### ISSUE THREAD

**Issue by AndyScherzinger** [nextcloud/mail#5478]
- [ ] https://github.com/nextcloud/mail/issues/3996
- [ ] https://github.com/nextcloud/mail/issues/2048
- [ ] https://github.com/nextcloud/mail/issues/5437
- [ ] https://github.com/nextcloud/mail/issues/5438
- [ ] https://github.com/nextcloud/mail/issues/5441
- [ ] https://github.com/nextcloud/mail/issues/1626

**Comment by jancborchardt** [comment]
Closing this then. :)
