### ISSUE TITLE
Missing text "No messages in this folder" in transifex?

### ISSUE THREAD

**Issue by 1ucay** [nextcloud/mail#548]
In l10n folders there is no text "No messages in this folder" for translate. Also in transifex missing. Thanks

EDIT: Also missing in textarea placeholder "Message ...".

**Comment by ChristophWurst** [comment]
Strange. It's in the template and using the `t` function, hence it should show up on transifex https://github.com/nextcloud/mail/blob/master/js/templates/empty-folder.html

**Comment by ChristophWurst** [comment]
Fix is in https://github.com/nextcloud/mail/pull/550

**Comment by ChristophWurst** [comment]
Thanks a lot for reporting, @1ucay 😉

**Comment by 1ucay** [comment]
Thanks 👍
