### ISSUE TITLE
An exception occurred while executing a query: SQLSTATE[HY000]: General error: 1813 Tablespace for table ‘nextcloud.oc_mail_trusted_senders’ exists. Please DISCARD the tablespace before IMPORT

### ISSUE THREAD

**Issue by hjaltioj** [nextcloud/mail#5488]
Hi
i get this error:
An exception occurred while executing a query: SQLSTATE[HY000]: General error: 1813 Tablespace for table ‘nextcloud.oc_mail_trusted_senders’ exists. Please DISCARD the tablespace before IMPORT
But i cant se oc_mail_trusted_senders anywhere in the databae??? do you know what i can do to fix this?

i have run these commands in mariadb
DELETE FROM `oc_migrations` WHERE app='mail';
DELETE FROM `oc_preferences` WHERE appid='mail';
drop table oc_mail_accounts;
drop table oc_mail_attachments;
drop table oc_mail_aliases;
drop table oc_mail_coll_addresses;
drop table oc_mail_mailboxes;
drop table oc_mail_classifiers;
drop table oc_mail_messages;
drop table oc_mail_recipients;
drop table oc_mail_trusted_senders;

but it still wont install?

**Comment by ChristophWurst** [comment]
This is outside our scope. It sounds like you uninstalled the app manually, as per our development instructions, right?

See https://stackoverflow.com/questions/15694168/error-tablespace-for-table-xxx-exists-please-discard-the-tablespace-before-imp and similar Duckduckgo search hits.

**Comment by ChristophWurst** [comment]
> Please ask your question in the community forum at https://help.nextcloud.com/c/apps/mail 

:wink:
