### ISSUE TITLE
Sent folder incomplete

### ISSUE THREAD

**Issue by acnp77** [nextcloud/mail#549]
### Steps to reproduce
1. Add GMail Account
2. Check Sent-Folder (1)
3. Show all Folders
4. Goto Sent-Folder (2) under [GMail]
5. compare the contents

### Expected behaviour
Content should be the same

### Actual behaviour
The Sent-Folder (1) has only items older than a year. All recently sent items only show in Sent-Folder (2) under [GMail].

### Mail app
Mail
**Mail app version:** (see apps admin page)
0.7.2
**Mailserver or service:** (e.g. Outlook, Yahoo, Gmail, Exchange,...)
Gmail
**Transport security - IMAP:** (None, SSL, TLS, STARTTLS) 
SSL
**Transport security - SMTP:** (None, SSL, TLS, STARTTLS)
STARTTLS
**Number of accounts:**
2
**Mail app version build date:** (only if you are using a Nightly Build)

### Server configuration

**Operating system**:
Debian 8.8
**Web server:**
Apache
**Database:**
MySQL/MariaDB
**PHP version:**
7
**Version:** (see admin page)

**Updated from an older version or fresh install:**
fresh install
**List of activated apps:**
Mail, Calendar, Contacts, Tasks
```
If you have access to your command line run e.g.:
sudo -u www-data php occ app:list
from within your server installation folder
```

**The content of config/config.php:**

<details>
```
If you have access to your command line run e.g.:
sudo -u www-data php occ config:list system
from within your Nextcloud installation folder

or

Insert your config.php content here
Make sure to remove all sensitive content such as passwords. (e.g. database password, passwordsalt, secret, smtp password, …)
```
</details>

#### Client configuration
**Browser:**
Firefox, IE11
**Operating system:**
Windows 7 / 10
##### Web server error log
```
Insert your webserver log here
```

##### Server log (data/nextcloud.log)
<details>
```
Insert your server log here
```
</details>

##### Horde IMAP log (data/horde_imap.log)
<details>
```
Insert your horde IMAP log here, see https://github.com/nextcloud/mail#debug-mode
```
</details>

##### Horde SMTP log (data/horde_smtp.log)
<details>
```
Insert your horde SMTP log here, see https://github.com/nextcloud/mail#debug-mode
```
</details>

##### Browser log
<details>
```
Insert your browser log here, this could for example include:

a) The javascript console log
b) The network log 
c) ...
```
</details>

**Comment by acnp77** [comment]
I am sorry, I found that the "sent" folder is in fact complete. So this is not the issue.
GMail has two IMAP folders for sent mail. "[Google Mail]/Sent Mail" and "[IMAP]/Sent".
Mail sent over Webmail (Gmail-interface or Nextcloud mail app) are stored in "[Google Mail]/Sent Mail" only. And mails sent with a local client are stored in "[Google Mail]/Sent Mail" and "[IMAP]/Sent".

The inconvenience with Nextcloud mail app is that although the sent mails are only stored in "[Google Mail]/Sent Mail" this folder needs to be expanded everytime you load the app. And the mostly empty "IMAP]/Sent" is easily accessible.

Cheers

**Comment by alexanderdd** [comment]
Hi @acnp77
So the issue as described above is solved, right? Can you close it then please?

If you believe that something can be done *in the nextcloud mail app* about the issue you describe in your comment, you can file a new issue.
