### ISSUE TITLE
Forwarded Mail

### ISSUE THREAD

**Issue by davidpr78** [nextcloud/mail#5493]
### Expected behavior
A forwarded mail even with no added text by the sender is vissible and can be deleted. 

### Actual behavior
I can't open or delete a forwarded mail without added text by the sender. 

### Mail app

**Mail app version:** (see apps admin page, e.g. 0.5.3)
1.10.3

**Mailserver or service:** (e.g. Outlook, Yahoo, Gmail, Exchange,...)
WebhostOne

### Server configuration
Edudocs 

**Operating system**: (e.g. Debian 8)
Linux 4.15.0-153-generic

**Web server:** (e.g. Apache, Nginx,...)
Apache/2.4.48 (Ubuntu) 

**Database:** (e.g. MariaDB, SQLite or PostgreSQL)
mysql 5.7.35

**PHP version:** (e.g. 7.0)
7.3.29

**Nextcloud Version:** (see admin page, e.g. 13.0.2)
21.0.3.1

#### Client configuration
**Browser:** (e.g. Firefox 48)
Chrome and Safari 

**Operating system:** (e.g. Arch Linux)
iOS/Windows 10

**Comment by ChristophWurst** [comment]
there is a ticket somewhere. basically this app doesn't support embedded messages yet. if the forwarded message is cited then it will work, but not when attached as embedded message.

**Comment by davidpr78** [comment]
Ok, thanks! But why is it not possible to delete it in the inbox?

**Comment by ChristophWurst** [comment]
that I don't know. deletion *should* be possible

**Comment by davidpr78** [comment]
When I try I get: message can't be deleted and the empty mail remains in my inbox.

**Comment by miaulalala** [comment]
Could you have a look at your nextcloud.log to see if there are any errors regarding the deletion?
