### ISSUE TITLE
Remember selected inbox (save UI state)

### ISSUE THREAD

**Issue by ya-d** [nextcloud/mail#5515]
### Feature Request

Would be great if Mail could remember the last active inbox and open the same inbox when returning to the app. Task for example remembers which list you worked in.

Would also help bypass priority inbox or give users choice between a single or shared inbox without additional settings. (See #3265)

Thanks for considering and all the great work ❤️

**Comment by ChristophWurst** [comment]
Duplicate of https://github.com/nextcloud/mail/issues/1665
