### ISSUE TITLE
Clicking through 3 or more messages in your draft folder, overwrites messages in some situations

### ISSUE THREAD

**Issue by LostinSpacetime** [nextcloud/mail#5518]
### Expected behavior
Clicking through my messages in draft folder, should show me the messages I clicked on and save the draft when I change something.

### Actual behavior
I have 3 messages in my draft folder. While clicking through my messages, I don't see always the message I clicked on and at some point, one message gets overwritten with another. See video:

[https://cloud.schloss-schule.wien/index.php/s/xrqiJnNdN3aCYdz](url)

### Mail app

App-Version: 1.10.3
Mailserver or service: IMAP

### Server configuration

Operating system: Ubuntu 18.04 (Plesk 18.0.37)

Web server: Apache

Database: MariaDB

PHP version: 7.4.23

Nextcloud Version: 21.0.4

#### Client configuration
Browser: Chromium based and Firefox

Operating system: Ubuntu Linux, Windows 10

**Comment by ChristophWurst** [comment]
We will have to rework drafts handling, it's far from ideal right now: https://github.com/nextcloud/mail/issues/4768#issuecomment-915527078

**Comment by LostinSpacetime** [comment]
I've found another error which is probably related. When the draft folder is open, a message selected and one chooses to write a new message, the message from the draft folder remains marked, but it shows the content of the new empty message. The new message gets never saved to the draft folder. Should I file a new report @ChristophWurst ?

**Comment by ChristophWurst** [comment]
> Should I file a new report @ChristophWurst ?

https://github.com/nextcloud/mail/issues?q=is%3Aissue+is%3Aopen+drafts possibly already tracked somewhere

**Comment by LostinSpacetime** [comment]
This is still present and makes the usage of the draft folder basically impossible.
Nextcloud 23.0.3
Mail 1.11.7

**Comment by ChristophWurst** [comment]
Drafts now open in the composer modal. This should no longer be possible.
