### ISSUE TITLE
Download all attachments of an email

### ISSUE THREAD

**Issue by jancborchardt** [nextcloud/mail#552]
When there are more attachments, we have a button for »Save all to Files«. What would be awesome is another button for »Download all«.

**Comment by ChristophWurst** [comment]
We should use zip archives as they are supported well on most platforms.

**Comment by jancborchardt** [comment]
Yep, this is also what we do for the Files app.

**Comment by jakobsack** [comment]
The files app uses the private API (`OC_FILES` => `\OC\Streamer`).
Implementing the zip feature seems to be straight forward but we'd have to implement a streamer class/interface in the `OCP` namespace first.

**Comment by ChristophWurst** [comment]
PR is at https://github.com/nextcloud/mail/pull/4536 :rocket:
