### ISSUE TITLE
HTML message is clipped

### ISSUE THREAD

**Issue by mat-m** [nextcloud/mail#5527]
### Expected behavior

The sender is in the white list to display images.

The mail should be in a taller box, with a scrollbar if needed

### Actual behavior

![image](https://user-images.githubusercontent.com/1039753/132762318-98063a79-01ba-45c4-8096-8650f81a8348.png)

Mail can't be read.

### Mail app

**Mail app version:** 	1.10.3

**Mailserver or service:** (e.g. Outlook, Yahoo, Gmail, Exchange,...): gmx.com

### Server configuration

**Operating system**: (e.g. Debian 8)  Raspbian (base Debian 10)

**Web server:** nginx

**Database:** Mariadb

**PHP version:** 7.3

**Nextcloud Version:** 21.0.4

#### Client configuration
**Browser:** (e.g. Firefox 48) Firefox 92, Opera 79

**Operating system:** (e.g. Arch Linux) Linux Mint 20.2

**Comment by mat-m** [comment]
Some HTML mails are ok. 
OK and truncated are sent as `Content-Type: multipart/alternative;`

I don't know what to search to explain the blocking

**Comment by ChristophWurst** [comment]
This might be a regression of https://github.com/nextcloud/mail/pull/5473
