### ISSUE TITLE
Closing file chooser of »Save all to Files« leaves button inactive and loading

### ISSUE THREAD

**Issue by jancborchardt** [nextcloud/mail#553]
### Steps to reproduce
1. Go to an email with multiple attachments
2. Click on »Save all to Files«
3. Close the file chooser popup

### Expected behaviour
The button is active again.

### Actual behaviour
The »Save all to Files« button is inactive and loading:
![screenshot from 2017-09-28 12-23-16](https://user-images.githubusercontent.com/925062/30961910-18a1372a-a448-11e7-84a4-2b1d94c2828c.png)

**Comment by ChristophWurst** [comment]
Fixed by #559
