### ISSUE TITLE
office 365 email accounts stay loading forever

### ISSUE THREAD

**Issue by igorneumann** [nextcloud/mail#5540]
### Expected behavior
Click at the "Mail" tab and see my emaiils

### Actual behavior
1st time after configuring the email It works fine... afterwards it stays loading forever, mail from OTHER providers works just fine.

![image](https://user-images.githubusercontent.com/45451191/133767261-bdaccda1-6fe1-4980-8240-072b11f87190.png)

CHANGES I DID:
- At 1st you couldnt add the email aty all as it failed SMTP authentication, so II added THIS to the config file:

  'app.mail.transport' => 'php-mail',
  
  This allowed to the SMTP connection to work fine and the emails even appeared in my mail app, until I tried to load it again.
  
  ONLY WAY to make it appear is to remove the account and add it again, every time I enter.

### Mail app

**Mail app version:** 1.10.4 (AT LEAST A COUPLE OF VERSIIIONS PRIOR TO IT ALSO HAD THIS PROBLEM)
**Mailserver or service:** OFFICEC365

### Server configuration

**Operating system**: Ubuntu 20

**Web server:** Apache AND NGINX managed by Plesk

**Database:** MariaDB 10

**PHP version:** Tried with 7.3, 7.4 and 8.0

**Nextcloud Version:** (22.1.1=

#### Client configuration
**Browser:** Chrome 93

**Operating system:** Windows 10

**Comment by ChristophWurst** [comment]
>     * At 1st you couldnt add the email aty all as it failed SMTP authentication, so II added THIS to the config file:
>       'app.mail.transport' => 'php-mail',

Are you aware of what this setting actually does?

Please provide us with some logs so we can narrow down where the problem occurs. Do you see errors in the browser console? Do you see any in nextcloud.log? https://github.com/nextcloud/mail/blob/master/doc/admin.md#logging will help you find out more.

**Comment by igorneumann** [comment]
> > ```
> > * At 1st you couldnt add the email aty all as it failed SMTP authentication, so II added THIS to the config file:
> >   'app.mail.transport' => 'php-mail',
> > ```
> 
> Are you aware of what this setting actually does?
> 
> Please provide us with some logs so we can narrow down where the problem occurs. Do you see errors in the browser console? Do you see any in nextcloud.log? https://github.com/nextcloud/mail/blob/master/doc/admin.md#logging will help you find out more.

I assume it changed the mail transport handler to php mail, using the PHP mail() function... But NO, Im not fully aware of all its imiplications.

Anyways, without that change, I cant authenticate on Office 365 email server at all.

I cleaned the LOGS earlier today so its not HUGE: https://cloud.bezares.com/index.php/s/HBzNDz9kRsr4Qj7

But anyways I wanted to make things easier for you, so I renamed the log, removed my email address, added it again and opened in a new tab to reproduce the problem and have a CLEAN(ish) log for you: https://cloud.bezares.com/index.php/s/a9LcnZZiATb6KZ6

And there is the embarassing part, the issue went away! :-(

Had tried to do the same things many times in the past, including today... 
I did uninstalled THIS plugin today  (the only change I did today): https://apps.nextcloud.com/apps/auto_mail_accounts 

But I had removed and added back the email AFTER this, MAYBE there was still something at the cache.

Anyways, MY issue is fixed, as long as Ii use php-mail, please let me know if you want me to remove it from config to get a log of the problem it has with the built in mail system, otherwise, just close this thread.

**Comment by ChristophWurst** [comment]
> And there is the embarassing part, the issue went away! :-(

Maybe your internet connection just caused some timeouts and retrying gave you more luck :)

> Anyways, MY issue is fixed, as long as Ii use php-mail

If you know what php mail is and how to set up it's fine :+1:

**Comment by igorneumann** [comment]
Actually no... It worked for 2 days and Im back with it not working.

All other providers works fine.

**Comment by ChristophWurst** [comment]
> Mail server denied authentication

is the error that stands out. I think your login credentials are just not right. That also explains why SMTP didn't work.

**Comment by igorneumann** [comment]
It worked fine for 2 days, including email sending (SMTP just works wgen
using php-mail) I do have a HUGE inbox but it worked fine when I was using
mail from Arsys.

It gives no error, it just stay loading forever.
