### ISSUE TITLE
Unprovisioned config does not delete account

### ISSUE THREAD

**Issue by jroussay** [nextcloud/mail#5549]
### Expected behavior
Delete provisioning account

### Actual behavior
Admin web: No more config displayed
Web: Error 500 we I go on the mail tab when no mail account is configured
CLI: This is a provisioned account which can not be deleted from CLI. Use the Provisioning UI instead.

Log :
`
{"reqId":"q6vgagGpyzxkO3r316Fn","level":3,"time":"2021-09-18T13:47:01+00:00","remoteAddr":"78.207.28.216","user":"a_gelman","app":"index","method":"GET","url":"/apps/mail/","message":"Argument 1 passed to OC\\Security\\Crypto::decrypt() must be of the type string, null given, called in /data/nextcloud/apps/mail/lib/IMAP/IMAPClientFactory.php on line 66","userAgent":"Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:91.0) Gecko/20100101 Firefox/91.0","version":"22.1.1.2","exception":{"Exception":"Exception","Message":"Argument 1 passed to OC\\Security\\Crypto::decrypt() must be of the type string, null given, called in /data/nextcloud/apps/mail/lib/IMAP/IMAPClientFactory.php on line 66","Code":0,"Trace":[{"file":"/data/nextcloud/lib/private/AppFramework/App.php","line":156,"function":"dispatch","class":"OC\\AppFramework\\Http\\Dispatcher","type":"->","args":[{"__class__":"OCA\\Mail\\Controller\\PageController"},"index"]},{"file":"/data/nextcloud/lib/private/Route/Router.php","line":301,"function":"main","class":"OC\\AppFramework\\App","type":"::","args":["OCA\\Mail\\Controller\\PageController","index",{"__class__":"OC\\AppFramework\\DependencyInjection\\DIContainer"},{"_route":"mail.page.index"}]},{"file":"/data/nextcloud/lib/base.php","line":1000,"function":"match","class":"OC\\Route\\Router","type":"->","args":["/apps/mail/"]},{"file":"/data/nextcloud/index.php","line":36,"function":"handleRequest","class":"OC","type":"::","args":[]}],"File":"/data/nextcloud/lib/private/AppFramework/Http/Dispatcher.php","Line":158,"Previous":{"Exception":"TypeError","Message":"Argument 1 passed to OC\\Security\\Crypto::decrypt() must be of the type string, null given, called in /data/nextcloud/apps/mail/lib/IMAP/IMAPClientFactory.php on line 66","Code":0,"Trace":[{"file":"/data/nextcloud/apps/mail/lib/IMAP/IMAPClientFactory.php","line":66,"function":"decrypt","class":"OC\\Security\\Crypto","type":"->","args":["*** sensitive parameters replaced ***"]},{"file":"/data/nextcloud/apps/mail/lib/IMAP/MailboxSync.php","line":91,"function":"getClient","class":"OCA\\Mail\\IMAP\\IMAPClientFactory","type":"->","args":[{"__class__":"OCA\\Mail\\Account"}]},{"file":"/data/nextcloud/apps/mail/lib/Service/MailManager.php","line":139,"function":"sync","class":"OCA\\Mail\\IMAP\\MailboxSync","type":"->","args":[{"__class__":"OCA\\Mail\\Account"},{"__class__":"OC\\AppFramework\\ScopedPsrLogger"}]},{"file":"/data/nextcloud/apps/mail/lib/Controller/PageController.php","line":129,"function":"getMailboxes","class":"OCA\\Mail\\Service\\MailManager","type":"->","args":[{"__class__":"OCA\\Mail\\Account"}]},{"file":"/data/nextcloud/lib/private/AppFramework/Http/Dispatcher.php","line":217,"function":"index","class":"OCA\\Mail\\Controller\\PageController","type":"->","args":[]},{"file":"/data/nextcloud/lib/private/AppFramework/Http/Dispatcher.php","line":126,"function":"executeController","class":"OC\\AppFramework\\Http\\Dispatcher","type":"->","args":[{"__class__":"OCA\\Mail\\Controller\\PageController"},"index"]},{"file":"/data/nextcloud/lib/private/AppFramework/App.php","line":156,"function":"dispatch","class":"OC\\AppFramework\\Http\\Dispatcher","type":"->","args":[{"__class__":"OCA\\Mail\\Controller\\PageController"},"index"]},{"file":"/data/nextcloud/lib/private/Route/Router.php","line":301,"function":"main","class":"OC\\AppFramework\\App","type":"::","args":["OCA\\Mail\\Controller\\PageController","index",{"__class__":"OC\\AppFramework\\DependencyInjection\\DIContainer"},{"_route":"mail.page.index"}]},{"file":"/data/nextcloud/lib/base.php","line":1000,"function":"match","class":"OC\\Route\\Router","type":"->","args":["/apps/mail/"]},{"file":"/data/nextcloud/index.php","line":36,"function":"handleRequest","class":"OC","type":"::","args":[]}],"File":"/data/nextcloud/lib/private/Security/Crypto.php","Line":114},"CustomMessage":"--"},"id":"6145f198da3d6"}
`
### Mail app

**Mail app version:** (see apps admin page, e.g. 0.5.3)
1.10.4	
**Mailserver or service:** (e.g. Outlook, Yahoo, Gmail, Exchange,...)
IMAP

### Server configuration

**Operating system**: (e.g. Debian 8)
Debian 10
**Web server:** (e.g. Apache, Nginx,...)
Apache
**Database:** (e.g. MariaDB, SQLite or PostgreSQL)
MaraiDB
**PHP version:** (e.g. 7.0)
7.3
**Nextcloud Version:** (see admin page, e.g. 13.0.2)
22.1.1
#### Client configuration
**Browser:** (e.g. Firefox 48)
All
**Operating system:** (e.g. Arch Linux)
All

**Comment by kesselb** [comment]
Hey, did you delete a provisioned account or a provisioning configuration?

**Comment by jroussay** [comment]
Hi,
I deleted a provisioning configuration. The first thing is that accounts were not unprovisioned, then I got the 500 from the Mail App.
Thanks!

**Comment by ChristophWurst** [comment]
> then I got the 500 from the Mail App.

It's a bug that the whole page doesn't load anymore because of this problem. This should be improved with https://github.com/nextcloud/mail/pull/5553.

> The first thing is that accounts were not unprovisioned,

This needs investigation and is indeed the root of the problem.
