### ISSUE TITLE
Mixed case "Inbox" and all caps "INBOX", the union of the two contains all inbox messages

### ISSUE THREAD

**Issue by RobT2012** [nextcloud/mail#555]
I noticed my Inbox folder was missing a lot of messages. See below ...

### Steps to reproduce

NOTE: This ONLY occurs on some IMAP email accounts!

1. Add IMAP email account
2. Look at the Inbox. some messages are missing
3. Click "show all folders", there's an additional all caps INBOX folder with the remaining messages, INBOX excludes the messages found inside the mixed case Inbox folder. The union of the two inbox's create a complete list of inbox messages.

### Expected behaviour
I should see only one Inbox folder with all the messages in it.

### Actual behaviour
I should not see a mixed case Inbox  folder and an all caps INBOX folder, each with a partial list of messages.

### Mail app

**Mail app version:** (see apps admin page)
0.7.3

**Operating system:** Linux 4.9.0-2-amd64 #1 SMP Debian 4.9.18-1 (2017-03-30) x86_64

**Web server:** Apache/2.4.25 (Debian) (apache2handler)

**Database:** mysql 10.1.22

**PHP version:** 7.0.16-3

If more details are needed, pls ask.

**Comment by ChristophWurst** [comment]
Any observations on which messages are missing? Anything special about them?

**Comment by RobT2012** [comment]
To be clear, there are no missing messages, they are distributed inside two separate inbox folders, one is mixed case "Inbox" the other is all caps "INBOX", combining both Inbox and INBOX together will result in a complete list of inbox emails. 

So the only problem I have is that the inboxes are being split into two rather than being combined into one. I do not have this split Inbox/INBOX problem when using any other email clients. I figure there's a folder matching issue in the code somewhere, it should match case insensitive but isn't. I can see that the php code is attempting to match folders by converting them to all lower case, but so far I've not yet found where it's getting confabulated.

**Comment by RobT2012** [comment]
I looked more carefully at the problem this morning and I realise I misunderstood the problem and therefore described it incorrectly. 

I do have an all caps INBOX, but it actually does contain all the inbox messages. It is the other "inbox" which is missing emails, this folder is not named "Inbox", it is named as my email address and appears first in the list, it is missing a lot of the files that are in the INBOX folder. 

So it means that messages from INBOX are being listed in the main inbox list, but there must be something different with the missing emails causing them to be left out.

I discovered that only emails marked with a "star" appear in the main inbox list, while all other emails are left out. When I unstar the email, it will vanish from the main inbox list, star it again, and it will reappear. I have another email account that does not display this behaviour, all inbox emails show up in the main inbox list and it does not matter if they are starred or not.

There's a folder named "favorites" which contains only the stared emails. The main inbox list is identical to the favorites folder.

**Comment by ChristophWurst** [comment]
I think I understood your problem now, but I'm not sure. May I ask you to take a screenshots of the inboxes in question?

Note that the `Favourites` folder is a special folder added by this app. It only shows inbox folders that are flagged (as you correctly observed) - the folder does not exists on IMAP.

**Comment by RobT2012** [comment]
Here's a screen shot. I've edited out my email address for privacy reasons. 

![screenshot_ncmail_2017-10-03_22-34-29](https://user-images.githubusercontent.com/3242265/31161589-dd348bbc-a88c-11e7-8069-d655a616c02a.png)

At the very top of the list is the main folder (the blue dot), it is named as my email address (blanked out).com, for some reason it contains only starred emails from my inbox, which is exactly that same as what is listed in the Favorites folder. 

For another email account that is on a different service provider, I do not have the same issue. The main folder contains all inbox emails, including starred and not starred emails, this is what I would expect to see. The Favorites folder contains only starred emails which I assume is also correct.

Since I get two different behaviors depending on the service provider, there's something different between them. Both are IMAP. One has all caps "INBOX", the other (that works) has mixed-case "Inbox". There are a few other differences, you can see the Archives/2016 and Archives/2017 folders,  the other account (that works) has a no Archives folders, but has "Contacts" and "Emailed Contacts" folders. So far these are the only differences that I can see, other than obviously different email accounts on different services.

**Comment by ChristophWurst** [comment]
> At the very top of the list is the main folder (the blue dot), it is named as my email address (blanked out).com, for some reason it contains only starred emails from my inbox

I see. So clicking the email address is just a hidden shortcut to open the first folder in the list. That's why it's identical to what you see when clicking on favorites 😉 

> For another email account that is on a different service provider, I do not have the same issue. The main folder contains all inbox emails, including starred and not starred emails, this is what I would expect to see. The Favorites folder contains only starred emails which I assume is also correct.

So as far as I can see, it looks like the folder role detection fails here. It should use `INBOX` as the account's inbox and also show it as first entry.

**Comment by RobT2012** [comment]
> clicking the email address is just a hidden shortcut to open the first folder in the list.

That explains what I'm seeing for all my email accounts.

> It should use INBOX as the account's inbox and also show it as first entry.

Yes, that would make a whole lot more sense.

**Comment by RobT2012** [comment]
The "All inboxes" features also does not work, it looks like a directly related problem, it only combines emails from the account with the mixed case "Inbox" folder, it is leaving out all the uppercase INBOX folders (these accounts have the Favorites problem), but in this case it is not taking emails from Favorites.
