### ISSUE TITLE
Mails from puri.sm are not correctly displayed

### ISSUE THREAD

**Issue by Quix0r** [nextcloud/mail#5562]
### Expected behavior
The HTML mail from the said provider should display as any other HTML mail (e.g. from twitch.tv) does.

### Actual behavior
The HTML code is shown as "Quoted text".

Screenshot is [here](https://cloud.mxchange.org/index.php/s/public?path=%2FNextcloud%2F202109), Github showed error message when I tried to upload it here.

### Mail app

**Mail app version:** 1.10.4

**Mailserver or service:** Courier

### Server configuration

**Operating system**: Devuan with 5.10 kernel

**Web server:** Apache 2.4

**Database:** MariaDB 10.3.27 (soon 29)

**PHP version:** 7.3.29:
````
PHP 7.3.29-1~deb10u1 (cli) (built: Jul  2 2021 04:04:33) ( NTS )
Copyright (c) 1997-2018 The PHP Group
Zend Engine v3.3.29, Copyright (c) 1998-2018 Zend Technologies
    with Zend OPcache v7.3.29-1~deb10u1, Copyright (c) 1999-2018, by Zend Technologies
    with Xdebug v2.7.0RC2, Copyright (c) 2002-2019, by Derick Rethans
````

**Nextcloud Version:** 21.0.3

### Client configuration
**Browser:** Firefox 78.12.0esr (64-bit)

**Operating system:** Debian Linux 11

**Comment by Quix0r** [comment]
Still up-to-date.

**Comment by ChristophWurst** [comment]
For some reason the email content type is seen as text when it's HTML.

Does it still happen? If so, please post the headers of the mail.
