### ISSUE TITLE
Mails of immobilienscout24 will not be displayed completely

### ISSUE THREAD

**Issue by zian92** [nextcloud/mail#5563]
### Expected behavior
The message of any immobilienscout24 filter email is cut off after some lines. -> https://ibb.co/wdH9Hmz

### Actual behavior
The mail should be displayed completely.

### Mail app

**Mail app version:** (1.10.4
**Mailserver or service:** my own postfix/dovecot

### Server configuration

**Operating system**: Cent OS 7
**Web server:** Apache

**Database:** MariaDB

**PHP version:** 7. something

**Nextcloud Version:** 21.0.2

#### Client configuration
**Browser:** Chrome and Firefox

**Operating system:** Fedora

**Comment by ChristophWurst** [comment]
would it be possible to get this email as .eml or similar so that we can import and inspect in our dev envs?

**Comment by ChristophWurst** [comment]
this is very likely a duplicate of https://github.com/nextcloud/mail/issues/5527

**Comment by zian92** [comment]
Yes, it looks the same. I'll see that I hand over that mail.

**Comment by zian92** [comment]
[immoscout.txt](https://github.com/nextcloud/mail/files/7231440/immoscout.txt)

**Comment by ChristophWurst** [comment]
Thanks a lot! This should be fixed with https://github.com/nextcloud/mail/pull/5567 and the next v1.10.x release :v:

**Comment by zian92** [comment]
It was fixed! :) Thanks a lot!
