### ISSUE TITLE
Uncaught TypeError: Cannot read properties of undefined (reading 'replace')

### ISSUE THREAD

**Issue by HLFH** [nextcloud/mail#5565]
### Expected behavior
Nextcloud Mail should launch and should not have an empty window.

### Actual behavior
Nextcloud Mail does not launch correctly and have an empty window.
JS error in Chrome console:

> Uncaught TypeError: Cannot read properties of undefined (reading 'replace')

### Mail app

**Mail app version:** 
1.10.4

**Mailserver or service:**
Postfix 3.6.2 + Dovecot 2.3.16

### Server configuration

**Operating system**: 
ArchLinux with kernel 5.10.11-arch1-1

**Web server:** 
nginx version: nginx/1.20.1
built with OpenSSL 1.1.1k  25 Mar 2021 (running with OpenSSL 1.1.1l  24 Aug 2021)
TLS SNI support enabled
configure arguments: --prefix=/etc/nginx --conf-path=/etc/nginx/nginx.conf --sbin-path=/usr/bin/nginx --pid-path=/run/nginx.pid --lock-path=/run/lock/nginx.lock --user=http --group=http --http-log-path=/var/log/nginx/access.log --error-log-path=stderr --http-client-body-temp-path=/var/lib/nginx/client-body --http-proxy-temp-path=/var/lib/nginx/proxy --http-fastcgi-temp-path=/var/lib/nginx/fastcgi --http-scgi-temp-path=/var/lib/nginx/scgi --http-uwsgi-temp-path=/var/lib/nginx/uwsgi --with-cc-opt='-march=x86-64 -mtune=generic -O2 -pipe -fno-plt -D_FORTIFY_SOURCE=2' --with-ld-opt=-Wl,-O1,--sort-common,--as-needed,-z,relro,-z,now --with-compat --with-debug --with-file-aio --with-http_addition_module --with-http_auth_request_module --with-http_dav_module --with-http_degradation_module --with-http_flv_module --with-http_geoip_module --with-http_gunzip_module --with-http_gzip_static_module --with-http_mp4_module --with-http_realip_module --with-http_secure_link_module --with-http_slice_module --with-http_ssl_module --with-http_stub_status_module --with-http_sub_module --with-http_v2_module --with-mail --with-mail_ssl_module --with-pcre-jit --with-stream --with-stream_geoip_module --with-stream_realip_module --with-stream_ssl_module --with-stream_ssl_preread_module --with-threads

**Database:**
mariadb  Ver 15.1 Distrib 10.6.4-MariaDB, for Linux (x86_64) using readline 5.1

**PHP version:** 
PHP 8.0.10 (cli) (built: Aug 26 2021 10:26:33) ( NTS )
Copyright (c) The PHP Group
Zend Engine v4.0.10, Copyright (c) Zend Technologies
    with Zend OPcache v8.0.10, Copyright (c), by Zend Technologies

**Nextcloud Version:** 
Nextcloud 22.1.1

#### Client configuration
**Browser:** 
Chrome Version 94.0.4606.54 (Official Build) (x86_64)

**Operating system:**
macOS Monterey 12.0 Beta (21A5506j)

**Comment by ChristophWurst** [comment]
How do I reproduce this? Does that happen with no accounts? 1? 2? What route/URL do you see? Any clicks or input necessary to trigger this? Could you post a trace of the error?

**Comment by HLFH** [comment]
@ChristophWurst 

I had several mail accounts on the Mail app.
It is when I click on the Mail app link apps/mail in the Nextcloud menu. 

I fixed it. Might be linked to this Nextcloud error:

>  SSL operation failed with code 1. OpenSSL Error messages:\nerror:1416F086:SSL routines:tls_process_server_certificate:certificate verify failed

My mail server TLS certificate had expired, and I had to renew it (and fix certbot).
I suppose it was related to that.

Shall I close the issue?
