### ISSUE TITLE
Use Backbone push state routing

### ISSUE THREAD

**Issue by ChristophWurst** [nextcloud/mail#557]
We have some decent routing in place, based on Backbone.Router. It's working fairly well, but currently has some limitations as we're using the hash-based (#) routing. That works fine unless you have to deal with any server-side routing, like the login redirection in case your session timed out. The problem is that the server-side doesn't know about hash routing and thus this part of the URL is lost on redirection.

Luckily, Backbone has a modern mechanism for that, which updates the pages URL dynamically, without using an anchor (hash). This mode is called `push state`: http://backbonejs.org/#Router.

I've used this push state in another project and it seems to work well, so I'd like to enable it here too. The only potentially critical parts are conflicting routes, e.g. `/apps/mail/accounts` is already taken by the REST API. Moreover I'm not sure how to handle pretty/non-pretty URLs, where the index.php part might be present/needed or not.

To circumvent the first problem I suggest we change our routes to a `/api` sub-route with 0.7.4. With the next release 0.7.5 or 0.8 we can then do the jump to push state. This shall give us a nice migration path.

**Comment by ChristophWurst** [comment]
@rullzer can I have multiple routes mapped to a single controller method? I want to have `/`, `/accounts/…`, `/setup` and `/shortcuts` view the index page. The client will do the actual routing.

I tried
```
		[
			'name' => 'page#index',
			'url' => '/',
			'verb' => 'GET'
		],
		[
			'name' => 'page#index',
			'url' => '/accounts/{path}',
			'defaults' => array('path' => ''),
			'verb' => 'GET'
		],
		[
			'name' => 'page#setup',
			'url' => '/setup',
			'verb' => 'GET'
		],
		[
			'name' => 'page#shortcuts',
			'url' => '/shortcuts',
			'verb' => 'GET'
		],
```
But then only the very last entry actually is routed. The previous ones are ignored. I'm assuming that we map it to a key and thus they are just overwritten.

**Comment by ChristophWurst** [comment]
Note to myself:
```
Backbone.history.start({
				pushState: true,
				root: OC.generateUrl('/apps/mail')
			});
```
seems to do the base url routing.

**Comment by rullzer** [comment]
I guess we can't right now. But it should be possible to hack that in (just another check if the route is already there and if so just append or something) because when matching rotues we do not depend on this index.

**Comment by ChristophWurst** [comment]
lol no :)
