### ISSUE TITLE
Error when UTF8 special chars in IMAP mail subject

### ISSUE THREAD

**Issue by julien-garand** [nextcloud/mail#5582]
OCA\Mail\Exception\ServiceException: Sync failed for 32:INBOX: An exception occurred while executing a query: SQLSTATE[HY000]: General error: 1366 Incorrect string value: '\xF0\x9F\x8E\x92 A...' for column 'subject' at row 1

IMAP sync is not working when there is a special UTF8 char in email subject. 

Thanks for all,

**Comment by ChristophWurst** [comment]
https://docs.nextcloud.com/server/stable/admin_manual/configuration_database/mysql_4byte_support.html
