### ISSUE TITLE
mb_convert_encoding does not support windows-1256 / Arabic

### ISSUE THREAD

**Issue by HLFH** [nextcloud/mail#5583]
### Expected behavior
The app should be able to read popular encodings.

### Actual behavior
Some encodings (windows-1256 specifically ; Arabic) cause warnings/errors. Apparently that's not supported by the build-in function: https://secure.php.net/manual/de/mbstring.supported-encodings.php. However, some clients such as Outlook use this encoding.

### Mail app
Mail app version:
1.10.4

### Server configuration
PHP version:
PHP 8.0.11 (cli) (built: Sep 25 2021 07:52:29) ( NTS )
Copyright (c) The PHP Group
Zend Engine v4.0.11, Copyright (c) Zend Technologies
    with Zend OPcache v8.0.11, Copyright (c), by Zend Technologies

Nextcloud Version:
Nextcloud 22.1.1

**Comment by ChristophWurst** [comment]
https://github.com/nextcloud/mail/search?q=mb_convert_encoding shows our usages of this php function.

**Comment by HLFH** [comment]
Related to https://github.com/nextcloud/mail/issues/1037 that is for windows-1250 character encoding support.

**Comment by ChristophWurst** [comment]
> Related to #1037 that is for windows-1250 code page support.

Oh, I forgot about that ticket. I would say this is a duplicate. I'm updating the description there. Thanks :v:

**Comment by HLFH** [comment]
Ok you can update the other ticket description ;)
