### ISSUE TITLE
InvalidArgumentException: Only strings, Literals and Parameters are allowed

### ISSUE THREAD

**Issue by walidbbq** [nextcloud/mail#5586]
When I set up my e-mail at Mail app, no message could be opened then I went to the log file and I found this error message in Logging 
![tempsnip](https://user-images.githubusercontent.com/45328993/135052040-6f2f74d2-2163-4283-a0ce-414344a18016.png)

**Comment by ChristophWurst** [comment]
could you please copy the raw log line? it's hidden in the ... menu

**Comment by walidbbq** [comment]
I do not know exactly what you mean I've actually inserted the whole error message here. Is that what you mean?

{"reqId":"YVMewzRgcjlqDyPJkw9XdgAAAgA","level":3,"time":"2021-09-28T13:55:21+00:00","remoteAddr":"192.168.1.106","user":"walid","app":"mail","method":"POST","url":"/index.php/apps/mail/api/mailboxes/21/sync","message":{"Exception":"InvalidArgumentException","Message":"Only strings, Literals and Parameters are allowed","Code":0,"Trace":[{"file":"/var/www/nextcloud/lib/private/DB/QueryBuilder/QueryBuilder.php","line":439,"function":"quoteColumnName","class":"OC\\DB\\QueryBuilder\\QuoteHelper","type":"->","args":[["t.*","mt.imap_message_id"]]},{"file":"/var/www/nextcloud/apps/mail/lib/Db/TagMapper.php","line":135,"function":"selectDistinct","class":"OC\\DB\\QueryBuilder\\QueryBuilder","type":"->","args":[["t.*","mt.imap_message_id"]]},{"file":"/var/www/nextcloud/apps/mail/lib/Db/MessageMapper.php","line":1012,"function":"getAllTagsForMessages","class":"OCA\\Mail\\Db\\TagMapper","type":"->","args":[[{"id":96175,"__class__":"OCA\\Mail\\Db\\Message"},{"id":95694,"__class__":"OCA\\Mail\\Db\\Message"},{"id":92522,"__class__":"OCA\\Mail\\Db\\Message"},{"id":89791,"__class__":"OCA\\Mail\\Db\\Message"},{"id":89737,"__class__":"OCA\\Mail\\Db\\Message"},{"id":89707,"__class__":"OCA\\Mail\\Db\\Message"},{"id":89579,"__class__":"OCA\\Mail\\Db\\Message"},{"id":89442,"__class__":"OCA\\Mail\\Db\\Message"},{"id":89415,"__class__":"OCA\\Mail\\Db\\Message"},{"id":89298,"__class__":"OCA\\Mail\\Db\\Message"},{"id":88506,"__class__":"OCA\\Mail\\Db\\Message"},{"id":81904,"__class__":"OCA\\Mail\\Db\\Message"},{"id":79591,"__class__":"OCA\\Mail\\Db\\Message"},{"id":75173,"__class__":"OCA\\Mail\\Db\\Message"},{"id":73455,"__class__":"OCA\\Mail\\Db\\Message"},{"id":65265,"__class__":"OCA\\Mail\\Db\\Message"},{"id":65002,"__class__":"OCA\\Mail\\Db\\Message"},{"id":64645,"__class__":"OCA\\Mail\\Db\\Message"},{"id":64589,"__class__":"OCA\\Mail\\Db\\Message"},{"id":62842,"__class__":"OCA\\Mail\\Db\\Message"},{"id":62002,"__class__":"OCA\\Mail\\Db\\Message"}],"walid"]},{"file":"/var/www/nextcloud/apps/mail/lib/Db/MessageMapper.php","line":951,"function":"findRelatedData","class":"OCA\\Mail\\Db\\MessageMapper","type":"->","args":[[{"id":96175,"__class__":"OCA\\Mail\\Db\\Message"},{"id":95694,"__class__":"OCA\\Mail\\Db\\Message"},{"id":92522,"__class__":"OCA\\Mail\\Db\\Message"},{"id":89791,"__class__":"OCA\\Mail\\Db\\Message"},{"id":89737,"__class__":"OCA\\Mail\\Db\\Message"},{"id":89707,"__class__":"OCA\\Mail\\Db\\Message"},{"id":89579,"__class__":"OCA\\Mail\\Db\\Message"},{"id":89442,"__class__":"OCA\\Mail\\Db\\Message"},{"id":89415,"__class__":"OCA\\Mail\\Db\\Message"},{"id":89298,"__class__":"OCA\\Mail\\Db\\Message"},{"id":88506,"__class__":"OCA\\Mail\\Db\\Message"},{"id":81904,"__class__":"OCA\\Mail\\Db\\Message"},{"id":79591,"__class__":"OCA\\Mail\\Db\\Message"},{"id":75173,"__class__":"OCA\\Mail\\Db\\Message"},{"id":73455,"__class__":"OCA\\Mail\\Db\\Message"},{"id":65265,"__class__":"OCA\\Mail\\Db\\Message"},{"id":65002,"__class__":"OCA\\Mail\\Db\\Message"},{"id":64645,"__class__":"OCA\\Mail\\Db\\Message"},{"id":64589,"__class__":"OCA\\Mail\\Db\\Message"},{"id":62842,"__class__":"OCA\\Mail\\Db\\Message"},{"id":62002,"__class__":"OCA\\Mail\\Db\\Message"}],"walid"]},{"file":"/var/www/nextcloud/apps/mail/lib/Service/Sync/SyncService.php","line":166,"function":"findByIds","class":"OCA\\Mail\\Db\\MessageMapper","type":"->","args":["walid",[62842,62002,65265,65002,64645,64589,75173,73455,79591,81904,89298,88506,89791,89737,89707,89579,89442,89415,92522,96175,95694]]},{"file":"/var/www/nextcloud/apps/mail/lib/Service/Sync/SyncService.php","line":134,"function":"getDatabaseSyncChanges","class":"OCA\\Mail\\Service\\Sync\\SyncService","type":"->","args":[{"__class__":"OCA\\Mail\\Account"},{"id":21,"__class__":"OCA\\Mail\\Db\\Mailbox"},[],{"__class__":"OCA\\Mail\\Service\\Search\\SearchQuery"}]},{"file":"/var/www/nextcloud/apps/mail/lib/Controller/MailboxesController.php","line":161,"function":"syncMailbox","class":"OCA\\Mail\\Service\\Sync\\SyncService","type":"->","args":[{"__class__":"OCA\\Mail\\Account"},{"id":21,"__class__":"OCA\\Mail\\Db\\Mailbox"},42,[],true,"is:pi-starred"]},{"file":"/var/www/nextcloud/lib/private/AppFramework/Http/Dispatcher.php","line":169,"function":"sync","class":"OCA\\Mail\\Controller\\MailboxesController","type":"->","args":[21,[],false,"is:pi-starred"]},{"file":"/var/www/nextcloud/lib/private/AppFramework/Http/Dispatcher.php","line":100,"function":"executeController","class":"OC\\AppFramework\\Http\\Dispatcher","type":"->","args":[{"__class__":"OCA\\Mail\\Controller\\MailboxesController"},"sync"]},{"file":"/var/www/nextcloud/lib/private/AppFramework/App.php","line":152,"function":"dispatch","class":"OC\\AppFramework\\Http\\Dispatcher","type":"->","args":[{"__class__":"OCA\\Mail\\Controller\\MailboxesController"},"sync"]},{"file":"/var/www/nextcloud/lib/private/Route/Router.php","line":308,"function":"main","class":"OC\\AppFramework\\App","type":"::","args":["OCA\\Mail\\Controller\\MailboxesController","sync",{"__class__":"OC\\AppFramework\\DependencyInjection\\DIContainer"},{"action":null,"id":"21","_route":"mail.mailboxes.sync"}]},{"file":"/var/www/nextcloud/lib/base.php","line":1008,"function":"match","class":"OC\\Route\\Router","type":"->","args":["/apps/mail/api/mailboxes/21/sync"]},{"file":"/var/www/nextcloud/index.php","line":37,"function":"handleRequest","class":"OC","type":"::","args":[]}],"File":"/var/www/nextcloud/lib/private/DB/QueryBuilder/QuoteHelper.php","Line":62,"CustomMessage":"Only strings, Literals and Parameters are allowed"},"userAgent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:92.0) Gecko/20100101 Firefox/92.0","version":"20.0.2.2","id":"61531ed08d4eb"}

**Comment by kesselb** [comment]
> 20.0.2.2

You really need to update nextcloud. At least to 20.0.12.

**Comment by ChristophWurst** [comment]
Yep this is not an issue in up to date version of Nextcloud.

**Comment by walidbbq** [comment]
Thank you very much i updated it and it worked !
