### ISSUE TITLE
Replace loading-view with error-view if the content can not be loaded

### ISSUE THREAD

**Issue by ChristophWurst** [nextcloud/mail#56]
Currently we show an ugly yellow notification on the top of the page whenever an error occurs while loading a view's content, e.g. loading the list of messages or the message body.

Instead, I'd like to try using something similar to the "No search result" or "No messages in this folder" view: replacing the loading view with an "An error occured while xxx" or "Could not load xxx" view and get rid of the yellow notifications.

We could even go one step further and put a "Retry" button on that view, where the user can re-trigger loading the content. I think that would be nice UI and UX-wise.

@nextcloud/designers @nextcloud/mail @jancborchardt @MariusBluem let me know what you think :-)

**Comment by ChristophWurst** [comment]
Another argument for it: notifications vanish after 7 seconds, while the error-view would stay in place until the user explicitly acts again (e.g. clicking on another folder)

**Comment by te-online** [comment]
Also, in the same strike, I would love to see the auto-reload when an error happened redesigned. Maybe it should try to fetch the page in the background or do some other testing of the connection. And if that's not possible it should display a retry button. With the current solution, we auto-remove the precious loaded content from the screen when the user is offline for longer than 5 seconds.

**Comment by ChristophWurst** [comment]
@te-online good catch. That annoys me too, but AFAIK that is triggered by the server or the notifications app. There's an issue somewhere…

**Comment by ChristophWurst** [comment]
here it is: https://github.com/nextcloud/server/issues/992

**Comment by te-online** [comment]
Yeah, sorry, that is a system wide behaviour I guess...
