### ISSUE TITLE
"Send" button is disabled when writing new message

### ISSUE THREAD

**Issue by mstaudinger** [nextcloud/mail#5616]
### Expected behavior
When clicking on "New Message" and filling in a recipient, subject, and message body, the blue "Send" button should be dark blue and clickable.  Inspector HTML output when sending is enabled:

`<input data-v-ee7216e4="" type="submit" class="submit-message send primary icon-confirm-white" value="Send">`

### Actual behavior
When writing a new message, the "Send" button is light blue, and disabled / not clickable.  This applies only to writing a new message.   If I reply to an existing email in my inbox, the "Send" button is working as expected. And I know from this that my SMTP settings are correct.  Inspector HTML output observed:
`<input data-v-ee7216e4="" type="submit" disabled="disabled" class="submit-message send primary icon-confirm-white" value="Send">`

### Mail app

**Mail app version:** 1.10.5

**Mailserver or service:** Local / Postfix 3.6.2

### Server configuration

**Operating system**: FreeBSD 12.2

**Web server:** Apache 2.4.x

**Database:** MySQL 8.0.26

**PHP version:** PHP 7.4.23

**Nextcloud Version:** 22.2.0 - but also observed in 21.0.2

#### Client configuration
**Browser:** Observed in both Safari 12.1.2 and Brave 1.29.77 / Chromium: 93.0.4577.63

**Operating system:** MacOS Mojave 10.14.6

**Comment by mstaudinger** [comment]
Upon further investigation this is arguably not a bug, but user error.... however, there's definitely something lacking here in the UX.

After taking out the "disabled" CSS attribute I tried to send the mail and got something useful from my mail log - namely, "4 4.5.1 Error: no valid recipients".

I added the recipient to my contact list and selected it that way, and lo, I was able to send. My mistake was assuming that entering an email address, and pressing 'tab' or clicking on to another section of the message would be sufficient to indicate intent to add that address as a recipient.  In fact, pressing "enter" or selecting it from the contact list seems to be the only way to proceed here.

**Comment by elBoberido** [comment]
From https://github.com/nextcloud/mail/issues/2769#issuecomment-2004385999

Ideally Send should never be grayed out and a missing recipient or subject or any other reason the mail cannot be sent should display a warning with the exact reason when the send button is pressed.

**Comment by mtissington** [comment]
Is there any update/fix for this yet?
