### ISSUE TITLE
Emails are invisible with opcache enabled

### ISSUE THREAD

**Issue by lowtower** [nextcloud/mail#562]
### Steps to reproduce
1. disable opcache in php.ini: ```opcache.enable = 0```
2. the list of emails is shown in Inbox
3. enable opcache in php.ini: ```opcache.enable = 1```
4. no emails are shown: 

> Posteingang konnte nicht geladen werden :-(

### Expected behaviour
I expect, that my emails are shown whether opcache is enabled or not

### Actual behaviour
The emails are only shown with opcache DISabled

### Mail app

**Mail app version:** (see apps admin page)
0.7.3
**Mailserver or service:** (e.g. Outlook, Yahoo, Gmail, Exchange,...)

**Transport security - IMAP:** (None, SSL, TLS, STARTTLS) 
SSL
**Transport security - SMTP:** (None, SSL, TLS, STARTTLS)
SSL
**Number of accounts:**
2
**Mail app version build date:** (only if you are using a Nightly Build)

### Server configuration

**Operating system**:
Linux 3.2.0-4-amd64 SMP Debian 3.2.89.2 x86_64 GNU/Linux
**Web server:**
Apache/2.2.22 (Debian) DAV/2 SVN/1.6.17 mod_ssl/2.2.22 OpenSSL/1.0.1t
**Database:**
5.5.31-MariaDB - MariaDB Server
**PHP version:**
PHP Version 7.1.2
**Version:** (see admin page)
Nextcloud 12.0.3
**Updated from an older version or fresh install:**
fresh
**List of activated apps:**
<details>

- Auditing / Logging
- Deleted files
- File sharing
- Log Reader
- Monitoring
- Nextcloud announcements
- Notifications
- Password policy
- PDF viewer
- Share by mail
- Text editor
- Theming
- Update notification
- Usage survey
- Versions
- Audio Player
- Brute-force settings
- Calendar
- Contacts
- Mail
- Ransomware protection
- Tasks
</details>

**The content of config/config.php:**
<details>

```php
<?php
$CONFIG = array (
  'instanceid' => 'oc123456',
  'passwordsalt' => '123456',
  'trusted_domains' => 
  array (
    0 => 'www.xxx.yyy.net',
    1 => 'xxx.yyy.net',
  ),
  'datadirectory' => '/home/www/1_applications/nextcloud_data',
  'dbtype' => 'mysql',
  'version' => '12.0.3.3',
  'dbname' => 'webXXX_db1',
  'dbhost' => '127.0.0.1:3307',
  'dbtableprefix' => 'oc_',
  'dbuser' => 'webXXX',
  'dbpassword' => 'passwd',
  'installed' => true,
  'mail_smtpmode' => 'smtp',
  'mail_from_address' => 'timo',
  'mail_domain' => 'yyy.net',
  'mail_smtpauthtype' => 'PLAIN',
  'mail_smtpauth' => 1,
  'loglevel' => 1,
  'mail_smtphost' => 'serverXX.yyy.com',
  'mail_smtpport' => '465',
  'mail_smtpsecure' => 'ssl',
  'mail_smtpname' => 'webXXXp1',
  'mail_smtppassword' => 'passwd',
  'forcessl' => true,
  'xframe_restriction' => false,
  'theme' => '',
  'maintenance' => false,
  'secret' => 'xxxYYYxxxYYY',
  'trashbin_retention_obligation' => 'auto',
  'appstore.experimental.enabled' => false,
  'htaccess.RewriteBase' => '/',
  'updater.release.channel' => 'stable',
  'default_language' => 'de',
  'asset-pipeline.enabled' => true,
  'overwrite.cli.url' => 'https://www.xxx.yyy.com',
);
```
</details>

#### Client configuration
**Browser:**
Firefox 52.3.0
**Operating system:**
Linux  2.6.32-696.1.1.el6.x86_64 #1 SMP Tue Mar 21 12:19:18 EDT 2017 x86_64 x86_64 x86_64 GNU/Linux
##### Web server error log
```
[Thu Oct 05 15:33:05 2017] [notice] child pid 3264 exit signal Segmentation fault (11)
```

##### Server log (data/nextcloud.log)
_file is empty_

##### Horde IMAP log (data/horde_imap.log)
_file doesn't exist_

##### Horde SMTP log (data/horde_smtp.log)
_file doesn't exist_

##### Browser log
<details>
The network log:

```
502 GET messages?filter=
```

HEADERS:
```
Host: www.xxx.yyy.net
User-Agent: Mozilla/5.0 (X11; Linux x86_64; rv:52.0) Gecko/20100101 Firefox/52.0
Accept: */*
Accept-Language: de-DE,en;q=0.7,en-US;q=0.3
Accept-Encoding: gzip, deflate, br
requesttoken: qWbfVTTgJrQ94OMpkgGUIjsr79MNYIrRSZ56IUY=
OCS-APIREQUEST: true
X-Requested-With: XMLHttpRequest
Cookie: cb6e8025ad35af5e16cf6c4befe4; oc_sessionPassphrase=2FdFkr%2BcwMuwwq%2BA0e5C%2Fb87dLnx1C2sn%2FuZwYKl2y%2BvSeaWAupaSKIxGqsmEeu5; __Host-nc_sameSiteCookielax=true; __Host-nc_sameSiteCookiestrict=true
DNT: 1
Proxy-Authorization: Basic pwb2xkaTIzNg==
Connection: keep-alive
```
RESPONSE
```html
<html>
<head><title>502 Bad Gateway</title></head>
<body bgcolor="white">
<center><h1>502 Bad Gateway</h1></center>
<hr><center>nginx</center>
</body>
</html>
```
</details>

**Comment by lowtower** [comment]
added Error message

**Comment by ChristophWurst** [comment]
> child pid 3264 exit signal Segmentation fault (11)

Hard to tell what might have caused that. The only segfaults I've experienced were caused by php itself, hence an update/downgrade usually helped.

**Comment by lowtower** [comment]
Thanks for Your reply.
What should Include update?
Nextcloud and PHP are (quite) current versions.
It's a shared host, so I cannot upgrade PHP.

**Comment by lowtower** [comment]
Okay,

I have downgraded PHP to version 7.0.16 and the emails are shown again - everything is fine.
So, the problem lies in the combination of PHP_v7.1 and opcache.
Could be a server configuration thing.
Any suggestions what I could check?
I have the possibility to change/add entries in the httpd.conf and php.ini.

Thanks in advance.

**Comment by ChristophWurst** [comment]
I don't know for sure, but to me it looks like a php bug. Hopefully the next php update will work again.
