### ISSUE TITLE
[Feature Request] Add mail app section to the Nextcloud admin page

### ISSUE THREAD

**Issue by scroom** [nextcloud/mail#563]
### Expected behaviour
It would be great if there was a section for the mail app on the admin page, where the admin can set up a mail account for all users (eg, for all users, set up a mail account if the logon data is the same as the mail server).

If that is not possible it would be great if the admin could set up accounts over the config.php.

**Comment by ChristophWurst** [comment]
> If that is not possible it would be great if the admin could set up accounts over the config.php.

I'm working on that already https://github.com/nextcloud/mail/pull/544 😉 

> It would be great if there was a section for the mail app on the admin page, where the admin can set up a mail account for all users (eg, for all users, set up a mail account if the logon data is the same as the mail server).

That's not on the roadmap yet, as the config.php option is sufficient IMO. But as always, if you'd like to have that feel free to implement it or find someone who does it for you.

Thus I'm closing this ticket now. Thanks for your input :)
