### ISSUE TITLE
Wrong email deleted if one arrives between opening the menu and selecting the option

### ISSUE THREAD

**Issue by revpriest** [nextcloud/mail#5635]
I opened the menu to delete an email, but while the menu was open another email arrived.

When I actually pressed the "delete thread" button, it deleted the newly arrived one instead of the one I pressed to open the menu.

### Expected behavior
It should delete the email whose "..." menu I clicked.

### Actual behavior
It deleted the newly arrived email instead, before I could even read it.

### Mail app

**Mail app version:** (see apps admin page, e.g. 0.5.3)
1.10.2

**Mailserver or service:** (e.g. Outlook, Yahoo, Gmail, Exchange,...)
mailbox.org but I doubt that's important.

### Server configuration

**Operating system**: (e.g. Debian 8)
Debian GNU/Linux 10 (buster)

**Web server:** (e.g. Apache, Nginx,...)
Apache

**Database:** (e.g. MariaDB, SQLite or PostgreSQL)
Mysql

**PHP version:** (e.g. 7.0)
7.3.29

**Nextcloud Version:** (see admin page, e.g. 13.0.2)
21.0.3

#### Client configuration
**Browser:** (e.g. Firefox 48)
Firefox, latest

**Operating system:** (e.g. Arch Linux)
Debian Buster on the desktop as well as on the server.

**Comment by st3iny** [comment]
I just tested to reproduce this and wasn't able to. This most likely was fixed by our refactors on the selection logic.
