### ISSUE TITLE
No mail shows up for one account  (same issue closed  #130)

### ISSUE THREAD

**Issue by bmabma** [nextcloud/mail#564]
### Steps to reproduce
1.my account free.fr IMAP provider 
2.this account works with sogo, zimbra, thunderbird
3. I have other mail accounts

### Expected behaviour
Want to see the messages

### Actual behaviour
I don't see any message, but the number of messages il displayed

### Mail app

**Mail app version:** 0.7.3

**Mailserver or service:**  imap.free.fr

**Transport security - IMAP:** (SSL, TLS, STARTTLS) 

**Transport security - SMTP:** ( SSL, TLS, STARTTLS)

### Server configuration

**Operating system**: Debian Jessie uptodate

**Web server:** apache

**Database:** mysql

**PHP version:** libapache2-mod-php5:amd64/jessie 5.6.30+dfsg-0+deb8u1 

**Version:** (see admin page)

**Updated from an older version or fresh install:**

**List of activated apps:**
mail contacts agenda
```

```

**The content of config/config.php:**

<details>
<?php
$CONFIG = array (
  'instanceid' => 'oc45x5skfu9o',
  'passwordsalt' => 'xxxxx',
  'secret' => 'yyyyyyyyyy',
  'trusted_domains' =>
  array (
    0 => 'nextcloud.civam.fr',
  ),
  'datadirectory' => '/var/www/nextcloud/nextcloud/data',
  'overwrite.cli.url' => 'http://nextcloud.xxxxx.fr',
  'dbtype' => 'mysql',
  'version' => '12.0.3.3',
  'dbname' => 'nextcloud',
  'dbhost' => 'localhost:3306',
  'dbport' => '',
  'dbtableprefix' => 'oc_',
  'dbuser' => 'nextcloud',
  'dbpassword' => 'xxxxxxxxxxxxxx',
  'installed' => true,
  'default_language' => 'fr',
  'mail_smtpmode' => 'smtp',
  'mail_smtpauthtype' => 'LOGIN',
  'mail_from_address' => 'webmaster',
  'mail_domain' => 'xxxxx.fr',
  'mail_smtpsecure' => 'ssl',
  'mail_smtpauth' => 1,
  'mail_smtphost' => 'yyyyyyy,
  'mail_smtpport' => '465',
  'mail_smtpname' => 'yyyyyr@hhhh.fr',
  'mail_smtppassword' => 'yyyyyyy',

'memcache.local' => '\OC\Memcache\APCu',

);
</details>

#### Client configuration
**Browser:** firefox or chromium

**Operating system:** Debian GNU/Linux

##### Web server error log

Nothing in logs

**Comment by ChristophWurst** [comment]
> I don't see any message, but the number of messages il displayed

Could you take a screenshot of that and share it with us? Thanks

**Comment by bmabma** [comment]
![free](https://user-images.githubusercontent.com/6573784/31342141-1ed5e236-ad0c-11e7-8638-6831b7a20222.png)

here is a screenshot

**Comment by ChristophWurst** [comment]
> but the number of messages il displayed

Ah, that was a typo 🙈 I thought you mean there's a list of `li` HTML elements 😉

**Comment by bmabma** [comment]
Eh ! your message is displayed, but only your message :-(


![free1](https://user-images.githubusercontent.com/6573784/31342421-08a5ae82-ad0d-11e7-8b4d-710e4b67f5b0.png)

**Comment by ChristophWurst** [comment]
Interesting, probably because it's been fetched in the background. So the initial loading doesn't work, but sync does. Hmm …
Can you confirm that you cannot see the message if you reload the page?

**Comment by bmabma** [comment]
I confirm I  cannot see the messages if I reload the page

**Comment by dusscloud** [comment]
Exactly the same issue on my side (same email provider, same effect on background/reload).
Using Nextcloud 12.0.3 and Mail app 0.7.4

**Comment by MelvinHadasht** [comment]
I had the same issue with free.fr, and it looks like it is related to IMAP server return ESORT while Horde_Imap_Client was expecting ESEARCH. Result, is that the list of messages is not parsed. AFAIU, free.fr server is not standard compliant.

If you have access to mail/vendor/pear-pear.horde.org/Horde_Imap_Client/Horde/Imap/Client/Socket.php in your installation, try to add "case 'ESORT':" above "case 'ESEARCH':" in function _serverResponse
That fixed it for me.

Unfortunately, I did not find how to file a support request to Horde_Imap_Client.

**Comment by bmabma** [comment]
Ok thank's; That fixed it for me too.

**Comment by ChristophWurst** [comment]
@MelvinHadasht great findings! Would you mind reporting this to the [horde team](https://www.horde.org/) to get feedback on whether this is actually a bug or there is some kind of configuration possible in their library?
