### ISSUE TITLE
Uses TLSv1.2 when TLSv1.3 is available

### ISSUE THREAD

**Issue by jas4711** [nextcloud/mail#5643]
### Expected behavior
Connections to the IMAP server should be secured using TLS version 1.3.  All my other mail clients that I use (Evolution, iOS Mail, Gnus, etc) all uses TLSv1.3 these days.

### Actual behavior
Right now it connects with TLSv1.2

### Mail app
**Mail app version:** 1.10.3
**Mailserver or service:** Dovecot IMAP from Debian bullseye

### Server configuration
**Operating system**: Debian 11 Bullseye
**Web server:** Apache
**Database:** MariaDB
**PHP version:** 7.4
**Nextcloud Version:** 22.2.0

#### Client configuration
**Browser:** Firefox 78esr
**Operating system:** Debian 11 Bullseye

**Comment by ChristophWurst** [comment]
This should be working now
