### ISSUE TITLE
Messages with lots of replies are indented a lot

### ISSUE THREAD

**Issue by StCyr** [nextcloud/mail#5645]
### Expected behavior

Mail should use the largest possible width available to display a message content.

### Actual behavior

In case of a messages with lots of replies, due to the indentation of replies, Mail uses very little space to display the content.

Here's a screenshot (lots of text redacted to preserve privacy), the width used to display the text is about 130px large :(

![image](https://user-images.githubusercontent.com/8179031/137684205-c7b7a7a6-059b-4ade-a52a-b5b9467e5f3f.png)

### Mail app

**Mail app version:** 1.10.5

**Mailserver or service:** Self-hosted

### Server configuration

**Operating system**: Debian 11

**Web server:** Apache

**Database:** MariaDB

**PHP version:** 7.3

**Nextcloud Version:** 22.1.0

#### Client configuration

**Browser:** Firefox latest

**Operating system:** Windows 10 20H2

**Comment by ChristophWurst** [comment]
![image](https://github.com/user-attachments/assets/e36cbf14-7c14-422c-9017-5fcd4ea368a7)

This seems OK now
