### ISSUE TITLE
"Forward as attachment" is hard to discover

### ISSUE THREAD

**Issue by ChristophWurst** [nextcloud/mail#5655]
### Expected behavior

As a user I occasionally want to forward a message as attachment as opposed to the default quoted forward. The app supports this feature. Yet it's only shown in the multiselect actions menu, not the simple envelope or message actions. This leads to confusion.

### Actual behavior

The app supports this feature. Yet it's only shown in the multiselect actions menu, not the simple envelope or message actions. This leads to confusion.

This action wasn't only done for multiselect by accident, there was some reasoning behind: https://github.com/nextcloud/mail/pull/4251#issuecomment-747436011 and following comments.

### Proposed solution

Once the nc/vue components allow something like sub actions we could have *Forward as attachment* as sub item of *Forward*. Then it's directly accessible and discoverable.

### Mail app

**Mail app version:** v1.8.0-1.10.0

---

cc @nextcloud/designers

**Comment by GretaD** [comment]
@marcoambrosini can you please write here briefly what we discussed during hackeweek and why you proposed not to add it as a sub-action?

**Comment by marcoambrosini** [comment]
Yes I would basically not complicate how actions work by introducing yet another new pattern. 
I think that this "Forward as attachment" feature can just be buried down 1 level deeper into the "More actions" entry

**Comment by nimishavijay** [comment]
We can have more actions easily accessible in the main content when a mail is open. Next to the reply button there could be commonly used actions like forward, favourite, reply to only sender. But agreed that forward as attachment which is a niche feature doesn't need to be out in the front.

**Comment by GretaD** [comment]
@nimishavijay @jancborchardt can you please send a mockup on how you think this should look, or should i move on with Marco suggestion and add it into the "More actions" also. I think it should not be removed from where it is now action menu - Select - Forward as attachment, because it should be as part of select too.

**Comment by jancborchardt** [comment]
Yes, agree with Marco that this action should go into "More actions".
