### ISSUE TITLE
No public/shared Imap Folders 

### ISSUE THREAD

**Issue by andreas-wolf** [nextcloud/mail#566]
### Steps to reproduce
1. Create public/shared imap folder and give access to user

### Expected behaviour
The folders the user has access to show up in the folder list.

### Actual behaviour
Folders are not shown.

### Mail app
**Mail app version:** (see apps admin page)
0.7.3

**Mailserver or service:** (e.g. Outlook, Yahoo, Gmail, Exchange,...)
Cyrus Imap 2.4.19

Further information:

An IMAP NAMESPACE command returns
NAMESPACE (("INBOX." ".")) (("user." ".")) (("" "."))

An IMAP LIST "*" "*"  returns:
* LIST (\HasChildren) "." INBOX
* LIST (\HasChildren) "." INBOX.Archiv
[...]
* LIST (\HasChildren) "." pub.shared

As you can see the shared folders live under pub.shared.
They are not shown in the folder list at all. The folders under INBOX are also not show as folders like in "Subfolders and Dovecot #386" already mentioned.

**Comment by ChristophWurst** [comment]
As there is no feedback since a while I will close this ticket. If this is still happening please make sure to upgrade to the latest version after that, feel free to reopen.
