### ISSUE TITLE
Print email

### ISSUE THREAD

**Issue by dermitdemdino** [nextcloud/mail#5667]
### Feature Request

Unfortunately, the printouts are terrible.

#### Summary

When printing an e-mail (CTRL-P) the result is almost always unusable. Text is cut off, formatting is not really present.
So I wish me in the 3-point menu the entry "print", which then provides a usable result.

**Comment by dermitdemdino** [comment]
I was sick and could not answer sooner. Everything is fine on the screen. With most e-mail, the printout looks anything but nice. There is a similar discussion in the forum: [](https://help.nextcloud.com/t/featur
![print](https://user-images.githubusercontent.com/6813869/139651271-bec41b8f-8719-43fd-a634-f296e2ed5f60.jpg)
![screenshot](https://user-images.githubusercontent.com/6813869/139651274-3a25e5d6-acee-4bc3-bca6-db4002060fec.jpg)
e-request-print-view-for-emails/27823)

**Comment by ChristophWurst** [comment]
I don't see where this looks "terrible". Is this the print view or what the email looks like when you just read it?

Please provide a screenshot of the *print preview*. Also provide one of the same message but a different email client where you think it doesn't look terrible so we can see the difference. Thanks.

**Comment by Discostu36** [comment]
I can reproduce the problem. Here an example of a newsletter how it looks in the browser:

**Comment by ChristophWurst** [comment]
Thanks a lot!

**Comment by Discostu36** [comment]
For comparison here the print version from FairMail app on my Android:

![Screenshot_20211109_142721.jpg](https://user-images.githubusercontent.com/30999326/140932503-16554098-f98e-4aa4-b106-a16f613eb19c.jpg)

**Comment by GretaD** [comment]
actually its resolved here:  #5744
