### ISSUE TITLE
Long IMap Folder Name is unreadable

### ISSUE THREAD

**Issue by andreas-wolf** [nextcloud/mail#567]
### Steps to reproduce
1. create long imap folder name

### Expected behaviour
Name should be fully readable or at least the folder column should be resizeable/horizonal scrollable

### Actual behaviour
Name is cut off.
All I can see are folder names like 
INBOX.Archiv.Orders.Outgoing.A...
INBOX.Archiv.Orders.Outgoing.A...
INBOX.Archiv.Orders.Outgoing.A...

### Mail app
**Mail app version:** (see apps admin page)
0.7.3

**Comment by ChristophWurst** [comment]
Do you see the full folder name if you hover it?

**Comment by andreas-wolf** [comment]
In the left colum there is no hover text at all. Neither at e.g. the Sent folder nor at the other folders.

```Html
   <li class="ui-droppable"><a class="folder
	
	" href="/index.php/apps/mail/#accounts/1/folders/I_REMOVED_THE_ID%3D%3D">
	INBOX.Archiv.xxxxx.xxxxx.xxxxxxxxxx
</a>
<div class="folders"><ul></ul></div></li>
```
In the A-tag there are two tabs after class="folder
I've tested with Firefox 56.0.1 and Chrome Version 61.0.3163.100

Furthermore I see that the folders are not in alphabetical order:

INBOX.Archiv.Orders.R...
INBOX.Archiv
INBOX.Archiv.Orders.A..

**Comment by ftoledo** [comment]
I have same behavior on 0.7.4 over Firefox 57
![recibidos ragnarok docksud com ar mail bbs cloud](https://user-images.githubusercontent.com/95441/32997555-7912f48a-cd70-11e7-8a06-f2cbc94467b8.png)

**Comment by ChristophWurst** [comment]
this should be better with recent versions of Mail
