### ISSUE TITLE
Can not empty trash

### ISSUE THREAD

**Issue by edobrizio** [nextcloud/mail#5672]
### Expected behavior
The item empty trash is missing!

### Actual behavior
Tell us what happens instead
**The item empty trash is missing!**

### Mail app

**Mail app version:** (see apps admin page, e.g. 0.5.3)

**Mailserver or service:** (e.g. Outlook, Yahoo, Gmail, Exchange,...)

### Server configuration

**Operating system**: (e.g. Debian 8)
Linux
![Schermata del 2021-10-27 09-52-25](https://user-images.githubusercontent.com/45711036/139023551-f1f4d467-04c5-4544-ab10-9147c76dafae.png)

**Web server:** (e.g. Apache, Nginx,...)
Apache
**Database:** (e.g. MariaDB, SQLite or PostgreSQL)
MariaDB
**PHP version:** (e.g. 7.0)
8.0
**Nextcloud Version:** (see admin page, e.g. 13.0.2)
22
#### Client configuration
**Browser:** (e.g. Firefox 48)
Firefox 93
**Operating system:** (e.g. Arch Linux)
Ubuntu 20.0.4.03 LTS

**Comment by jancborchardt** [comment]
I have the same issue, on 2 different accounts (one being our nextcloud mail address). Even though the app seemingly recognizes it in both as per settings:
![image](https://user-images.githubusercontent.com/925062/154950199-7308511f-808e-4af7-a718-b6872e17791d.png)

**Comment by liqueurdetoile** [comment]
I've installed 1.14.1 (Nextcloud 24.0.6) and still no luck to empty any mailboxes though it is announced in release features : https://apps.nextcloud.com/apps/mail/releases?platform=24#24

Any clue to deal with this ?

**Comment by ChristophWurst** [comment]
Even announced features can have bugs :)

**Comment by JohannesGGE** [comment]
Tested and couldn't reproduce. Seems to be fixed already by:
https://github.com/nextcloud/mail/pull/6286
https://github.com/nextcloud/mail/pull/6800

Another Issue related: https://github.com/nextcloud/mail/issues/6060
