### ISSUE TITLE
Links in drafts are marked up via HTML even though it’s plain-text

### ISSUE THREAD

**Issue by jancborchardt** [nextcloud/mail#568]
If I write a draft with a link, for example `https://twitter.com/hashtag/opensourcedesign` 

Then close the window and want to continue the draft later, it will have changed the link to this:
` <a href="https://twitter.com/hashtag/opensourcedesign" rel="noreferrer noopener" target="_blank">twitter.com/hashtag/opensourcedesign</a> `

That’s a bit odd considering it’s a plain-text mail. The link should probably stay the same.

**Comment by sagorika1996** [comment]
Similar to #632, I think this one can be closed.

**Comment by ChristophWurst** [comment]
@jancborchardt please verify.

**Comment by jancborchardt** [comment]
The issue still persists, same for the one mentioned in #632.

You can easily test it:

1. Compose a new message with `> https://wikimedia.de`
2. Navigate somewhere else to have the draft saved
3. Open the draft and see `&gt; <a href="https://wikimedia.de" rel="noreferrer noopener" target="_blank">wikimedia.de</a>`

**Comment by jancborchardt** [comment]
This is not an issue anymore → closing :)
