### ISSUE TITLE
Current master crashes browser at »Loading accounts …« step

### ISSUE THREAD

**Issue by jancborchardt** [nextcloud/mail#570]
Current master seems to be unusable in both Chrome and Firefox, crashing both whole browsers:
![screenshot from 2017-10-16 13-33-57](https://user-images.githubusercontent.com/925062/31610464-70d82848-b278-11e7-8ca4-b4f743955a79.png)

![screenshot from 2017-10-16 13-34-16](https://user-images.githubusercontent.com/925062/31610463-70b3db5a-b278-11e7-9d46-7de1cdb9aab0.png)

Any idea @nextcloud/mail? Can you reproduce? I can’t seem to get any relevant log entries.

**Comment by ChristophWurst** [comment]
I have had that too this morning. A new webpack build solved it somehow.

**Comment by foxbow** [comment]
Is it possible that this is a node.js 6 vs node.js 8 issue? With my node.js 6 I'm seeing the same error. And the webpack was installed today...

**Comment by ChristophWurst** [comment]
@jancborchardt please let us know which version of Node you're using by running `node -v` and copy-pasting the output here.

**Comment by jancborchardt** [comment]
I was also not able to reproduce it after a new build, but I was on some standard Node package from Debian I think, 3.x or 4.x maybe?

**Comment by ChristophWurst** [comment]
Removing the priority label as I cannot reproduce this locally and packages are built with a more recent version of Node.
