### ISSUE TITLE
Recurrent cron report: PHP Deprecated:  Required parameter $server follows optional parameter $msg

### ISSUE THREAD

**Issue by aauzi** [nextcloud/mail#5707]
### Expected behavior
cron should execute without _recurrent_ PHP Deprecated messages.

Ideally, it should only report it once...

### Actual behavior
On each cron execution I get the following message in my mailbox:

PHP Deprecated:  Required parameter $server follows optional parameter $msg in /var/lib/nextcloud/apps/mail/vendor/pear-pear.horde.org/Horde_Imap_Client/Horde/Imap/Client/Exception/ServerResponse.php on line 52

### Mail app

**Mail app version:** (see apps admin page, e.g. 0.5.3)

1.10.5

**Mailserver or service:** (e.g. Outlook, Yahoo, Gmail, Exchange,...)

self-hosted Dovecot-2.3.16

### Server configuration

**Operating system**: (e.g. Debian 8)

Fedora Linux 35: 5.14.15-300.fc35.x86_64

**Web server:** (e.g. Apache, Nginx,...)

apache-2.4.51

**Database:** (e.g. MariaDB, SQLite or PostgreSQL)

postgresql-13.4

**PHP version:** (e.g. 7.0)

**php-8.0.12**

**Nextcloud Version:** (see admin page, e.g. 13.0.2)

22.2.0

#### Client configuration
**Browser:** (e.g. Firefox 48)

Firefox-94.0

**Operating system:** (e.g. Arch Linux)

Fedora Linux 35: 5.14.15-300.fc35.x86_64

**FWIW:** 

Please find here after the patch I've done to mute this nuisance

```diff
diff --git a/ServerResponse.php.ori b/ServerResponse.php
index 7d15494..38a280f 100644
--- a/ServerResponse.php.ori
+++ b/ServerResponse.php
@@ -50,8 +50,16 @@ class Horde_Imap_Client_Exception_ServerResponse extends Horde_Imap_Client_Excep
      * @param Horde_Imap_Client_Interaction_Pipeline $pipeline  Pipeline ob.
      */
     public function __construct(
+       /* PATCH AAU: PHP Deprecated:  Required parameter $server follows optional parameter $msg
+        * in apps/mail/vendor/pear-pear.horde.org/Horde_Imap_Client/Horde/Imap/Client/Exception/ServerResponse.php
+        * on line 52
+      
         $msg = null,
         $code = 0,
+	*/
+      
+        string $msg,
+        int $code,
         Horde_Imap_Client_Interaction_Server $server,
         Horde_Imap_Client_Interaction_Pipeline $pipeline
     )
```

**Final words:**

Thanks for the great work you're doing.

André

**Comment by miaulalala** [comment]
Hi aauzi, thanks for your report. Unfortunately, this is in a vendor library so we can't push any updates for it.

I'm glad you found a solution for this issue!

If you want to, you could open a PR at Horde https://github.com/horde/Imap_Client

**Comment by ChristophWurst** [comment]
This will be fixed once https://github.com/horde/Imap_Client/pull/13 got reviewed, merged and released by the Horde project.
