### ISSUE TITLE
Weird mix of language in mail app

### ISSUE THREAD

**Issue by CarlSchwan** [nextcloud/mail#5712]
### Expected behavior

Only french appears on the UI elements since it the language I choose in nextcloud to use :)

### Actual behavior

A mix between French and German. See screenshot

![image](https://user-images.githubusercontent.com/23653902/140764881-7ac3f446-79d9-446d-b43c-1d2a203a31d7.png)

### Mail app

Nextcloud 22 (company instance)

#### Client configuration
**Browser:** Firefox 93 configured to get english version of pages
**Operating system:** openSUSE tumbleweed

**Comment by ChristophWurst** [comment]
locale vs language? ref https://github.com/nextcloud/server/pull/14784 and its friends

**Comment by CarlSchwan** [comment]
Yes this is that bug.
