### ISSUE TITLE
INBOX prefix from OVH is displayed

### ISSUE THREAD

**Issue by martin-damien** [nextcloud/mail#573]
Hi,

Actually OVH seems to prefix folder with `INBOX.`.
As far as I understand in https://github.com/nextcloud/mail/blob/master/doc/admin.md#dovecot-imap, this behaviour can be configured on OVH server. But as it is shared hosting, they'll do nothing for that.

Can't we have an option to hide those prefixes from UI (I don't really mind if it keeps the prefixe in background) ?

### Steps to reproduce

1. Create a mailbox on ovh.com
2. Add folders through Roundcube (mail.ovh.net)
3. Register account inside nextcloud's mail app
4. Look at folders

### Expected behaviour

![capture d ecran 2017-10-19 a 09 03 58](https://user-images.githubusercontent.com/295478/31758526-19fe411e-b4ae-11e7-89a6-87683abe1bd9.png)

### Actual behaviour

![capture d ecran 2017-10-19 a 09 03 46](https://user-images.githubusercontent.com/295478/31758528-1d69e4de-b4ae-11e7-914d-3559316311be.png)

### Mail app

**Mail app version:** 0.7.3

**Mailserver or service:** OVH

**Transport security - IMAP:** SSL

**Transport security - SMTP:** SSL

**Number of accounts:** 1

**Mail app version build date:** (only if you are using a Nightly Build)

### Server configuration
**Operating system:** Linux sol3 4.9.23-std-1 #1 SMP Mon Apr 24 13:18:14 UTC 2017 aarch64

**Web server:** nginx/1.10.3 (fpm-fcgi)

**Database:** mysql 10.1.25

**PHP version:** 7.1.10-1+ubuntu17.04.1+deb.sury.org+1
<details>
        <summary>PHP-modules loaded</summary>

```
 - Core
 - date
 - libxml
 - openssl
 - pcre
 - zlib
 - filter
 - hash
 - Reflection
 - SPL
 - session
 - standard
 - cgi-fcgi
 - mysqlnd
 - PDO
 - xml
 - apcu
 - apc
 - bcmath
 - calendar
 - ctype
 - curl
 - dom
 - mbstring
 - fileinfo
 - ftp
 - gd
 - gettext
 - iconv
 - igbinary
 - json
 - exif
 - msgpack
 - mysqli
 - pdo_mysql
 - pdo_sqlite
 - Phar
 - posix
 - readline
 - shmop
 - SimpleXML
 - sockets
 - sqlite3
 - sysvmsg
 - sysvsem
 - sysvshm
 - tokenizer
 - wddx
 - xmlreader
 - xmlwriter
 - xsl
 - zip
 - memcached
 - Zend OPcache
```
</details>

**Version:** 12.0.3

**Updated from an older version or fresh install:** Updated from an older version

**List of activated apps:**

Enabled:
  - activity: 2.5.2
  - bookmarks: 0.10.1
  - bruteforcesettings: 1.0.2
  - calendar: 1.5.6
  - comments: 1.2.0
  - contacts: 2.0.1
  - dav: 1.3.0
  - deck: 0.2.4
  - documents: 0.16.0
  - encryption: 1.6.0
  - external: 2.0.3
  - federatedfilesharing: 1.2.0
  - federation: 1.2.0
  - files: 1.7.2
  - files_automatedtagging: 1.2.2
  - files_external: 1.3.0
  - files_markdown: 2.0.1
  - files_pdfviewer: 1.1.1
  - files_reader: 1.0.4
  - files_sharing: 1.4.0
  - files_texteditor: 2.4.1
  - files_trashbin: 1.2.0
  - files_versions: 1.5.0
  - files_videoplayer: 1.1.0
  - firstrunwizard: 2.1
  - gallery: 17.0.0
  - issuetemplate: 0.2.2
  - logreader: 2.0.0
  - lookup_server_connector: 1.0.0
  - mail: 0.7.3
  - metadata: 0.5.0
  - music: 0.5.3
  - news: 11.0.5
  - nextcloud_announcements: 1.1
  - notes: 2.3.1
  - notifications: 2.0.0
  - oauth2: 1.0.5
  - ocsms: 1.12.1
  - passman: 2.1.4
  - password_policy: 1.2.2
  - provisioning_api: 1.2.0
  - qownnotesapi: 17.5.0
  - quota_warning: 1.1.1
  - ransomware_protection: 1.0.4
  - serverinfo: 1.2.0
  - sharebymail: 1.2.0
  - survey_client: 1.0.0
  - systemtags: 1.2.0
  - tasks: 0.9.5
  - theming: 1.3.0
  - theming_customcss: 1.0.0
  - twofactor_backupcodes: 1.1.1
  - twofactor_totp: 1.3.1
  - updatenotification: 1.2.0
  - weather: 1.5.0
  - workflowengine: 1.2.0
Disabled:
  - admin_audit
  - user_external
  - user_ldap

**The content of config/config.php:**

{
    "system": {
        "instanceid": "ocyo0tqpg3c2",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "cloud.martin-damien.fr"
        ],
        "datadirectory": "\/var\/www\/nextcloud\/data",
        "overwrite.cli.url": "http:\/\/cloud.martin-damien.fr",
        "dbtype": "mysql",
        "version": "12.0.3.3",
        "dbname": "nextcloud",
        "dbhost": "127.0.0.1",
        "dbport": "",
        "dbtableprefix": "oc_",
        "installed": true,
        "maintenance": false,
        "theme": "",
        "loglevel": 2,
        "mail_from_address": "sol3",
        "mail_smtpmode": "php",
        "mail_smtpauthtype": "LOGIN",
        "mail_domain": "cloud.martin-damien.fr",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "mysql.utf8mb4": true
    }
}

#### Client configuration
**Browser:** Firefox 56

**Operating system:** Mac OS X 10.13

**Comment by ChristophWurst** [comment]
Please check the existing issues, IIRC we already have one for this issue. Thanks

**Comment by ChristophWurst** [comment]
Dup of https://github.com/nextcloud/mail/issues/386#issuecomment-313681624
