### ISSUE TITLE
1.11.0 RC1: Log messages: KItinerary binary adapter is not available, can't extract information

### ISSUE THREAD

**Issue by jakobroehrl** [nextcloud/mail#5732]
![image](https://user-images.githubusercontent.com/24530680/142418704-bd469d94-5efc-49e3-ba61-176fb3b380ba.png)

**Comment by ChristophWurst** [comment]
did you not see this before? This code wasn't touched. If you see this now you would also have seen this with v1.10 and earlier

**Comment by jakobroehrl** [comment]
You are right, this message was already there before the update to 1.11.0, sorry.

**Comment by ChristophWurst** [comment]
no worries

**Comment by jakobroehrl** [comment]
With NC23 + Mail 1.11.0 this is shown a lot. 
Maybe it's possible to classify it as Info?
![image](https://user-images.githubusercontent.com/24530680/143249317-4ef7bb83-c474-4e5c-877e-4f5285efc477.png)

**Comment by ChristophWurst** [comment]
Feel free to improve this in `lib/Integration/KItinerary/ItineraryExtractor.php`.

**Comment by doc75** [comment]
#5999 will decrease the logging level to info (and reduce amount of logging message)
