### ISSUE TITLE
Subdirectories not working

### ISSUE THREAD

**Issue by flonowa** [nextcloud/mail#574]
Steps to reproduce

    Open mail app
    Click on an (IMAP) folder that contains subdirectories
    The folder will not expand/shot its subdirectories

Expected behaviour

When clicking on the "triangle" icon the folder should be expanded to shot its subdirectories.
Actual behaviour

Nothing happens. Only the contents of the parent folder are shown (mails but not the subdirectories).
Mail app

Mail app version: 0.7.3

Transport security - IMAP: SSL/TLS

Transport security - SMTP: SSL/TLS

Number of accounts: 1

Client configuration

Browser: Tested in recent versions of FireFox and Chrome.

**Comment by flonowa** [comment]
solved

**Comment by slowhand93** [comment]
solved - by what???
