### ISSUE TITLE
Cannot update from v20.0.7.1

### ISSUE THREAD

**Issue by pseudoua** [nextcloud/mail#5741]
```
Updating \<mail\> ...
An unhandled exception has been thrown:
ArgumentCountError: Too few arguments to function OCA\Mail\Migration\ProvisionAccounts::__construct(), 0 passed in /srv/nextcloud/lib/private/Repair.php on line 127 and exactly 1 expected in /srv/nextcloud/apps/mail/lib/Migration/ProvisionAccounts.php:37
Stack trace:
#0 /srv/nextcloud/lib/private/Repair.php(127): OCA\Mail\Migration\ProvisionAccounts->__construct()
nextcloud/server#1 /srv/nextcloud/lib/private/legacy/OC_App.php(1035): OC\Repair->addStep()
nextcloud/server#2 /srv/nextcloud/lib/private/legacy/OC_App.php(979): OC_App::executeRepairSteps()
nextcloud/server#3 /srv/nextcloud/lib/private/Updater.php(379): OC_App::updateApp()
nextcloud/server#4 /srv/nextcloud/lib/private/Updater.php(258): OC\Updater->doAppUpgrade()
nextcloud/server#5 /srv/nextcloud/lib/private/Updater.php(130): OC\Updater->doUpgrade()
nextcloud/server#6 /srv/nextcloud/core/Command/Upgrade.php(255): OC\Updater->upgrade()
nextcloud/server#7 /srv/nextcloud/3rdparty/symfony/console/Command/Command.php(255): OC\Core\Command\Upgrade->execute()
nextcloud/server#8 /srv/nextcloud/3rdparty/symfony/console/Application.php(1000): Symfony\Component\Console\Command\Command->run()
nextcloud/server#9 /srv/nextcloud/3rdparty/symfony/console/Application.php(271): Symfony\Component\Console\Application->doRunCommand()
nextcloud/server#10 /srv/nextcloud/3rdparty/symfony/console/Application.php(147): Symfony\Component\Console\Application->doRun()
nextcloud/server#11 /srv/nextcloud/lib/private/Console/Application.php(215): Symfony\Component\Console\Application->run()
nextcloud/server#12 /srv/nextcloud/console.php(100): OC\Console\Application->run()
nextcloud/server#13 /srv/nextcloud/occ(11): require_once('/srv/nextcloud/...')
nextcloud/server#14 {main}
```

**Comment by pseudoua** [comment]
[](url
[next.pdf](https://github.com/nextcloud/mail/files/7576324/next.pdf)
)

**Comment by pseudoua** [comment]
![image](https://user-images.githubusercontent.com/68471179/142763697-7f6b1658-6db1-4a65-b62c-dae7fe3136d4.png)
Any user who is not even registered can click the refresh button

**Comment by ChristophWurst** [comment]
> /srv/nextcloud/lib/private/Repair.php on line 127

What version of Nextcloud is that?

**Comment by C-Magic** [comment]
![image](https://user-images.githubusercontent.com/59870706/142849033-3e29a39d-b06a-45d1-a023-3bb8eda2846c.png)

**Comment by ChristophWurst** [comment]
This doesn't make sense. Your error said the exception was thrown on L127 but there is no such code there https://github.com/nextcloud/server/blob/68fecc1d9f6810e815c6a6ba80d4c13a0bde98b8/lib/private/Repair.php#L127

I would expect it to throw here instead https://github.com/nextcloud/server/blob/68fecc1d9f6810e815c6a6ba80d4c13a0bde98b8/lib/private/Repair.php#L143

**Comment by miaulalala** [comment]
@C-Magic can you compare your file to stable20 please? https://github.com/nextcloud/server/blob/stable20/lib/private/Repair.php#L129

**Comment by C-Magic** [comment]
--- /home/pseudo/project/NextCloud/git
+++ /home/pseudo/project/NextCloud/Repair.php
@@ -42,7 +42,6 @@
 use OC\Repair\ClearGeneratedAvatarCache;
 use OC\Repair\Collation;
 use OC\Repair\MoveUpdaterStepFile;
-use OC\Repair\NC22\LookupServerSendCheck;
 use OC\Repair\Owncloud\CleanPreviews;
 use OC\Repair\NC11\FixMountStorages;
 use OC\Repair\Owncloud\MoveAvatars;
@@ -61,7 +60,6 @@
 use OC\Repair\Owncloud\DropAccountTermsTable;
 use OC\Repair\Owncloud\SaveAccountsTableData;
 use OC\Repair\RemoveLinkShares;
-use OC\Repair\RepairDavShares;
 use OC\Repair\RepairInvalidShares;
 use OC\Repair\RepairMimeTypes;
 use OC\Repair\SqliteAutoincrement;
@@ -184,8 +182,6 @@
 			\OC::$server->query(EncryptionLegacyCipher::class),
 			\OC::$server->query(EncryptionMigration::class),
 			\OC::$server->get(ShippedDashboardEnable::class),
-			\OC::$server->get(RepairDavShares::class),
-			\OC::$server->get(LookupServerSendCheck::class),
 		];
 	}
 
@@ -214,7 +210,7 @@
 			new Collation(\OC::$server->getConfig(), \OC::$server->getLogger(), $connection, true),
 			new SqliteAutoincrement($connection),
 			new SaveAccountsTableData($connection, $config),
-			new DropAccountTermsTable($connection),
+			new DropAccountTermsTable($connection)
 		];
 
 		return $steps;

**Comment by C-Magic** [comment]
![image](https://user-images.githubusercontent.com/59870706/142894257-a9fa367c-fe94-4576-a13a-c290045d7b59.png)

**Comment by miaulalala** [comment]
How did you get your version? Did you pull it from Github?

**Comment by pseudoua** [comment]
I do not remember. I remember trying to run it on docker, but there were a lot of problems in the finished solution, in particular, they were connected with ssl and Collabora, which were frozen, I launched it on LXC. Well, there were so many experiments that I can't even remember where I got the code from. **But several times everything was updated normally through the console.** **This time I decided that once the product is a stable update via the web interface. And that's all. Everything is broken! Was it just lucky?**

**Comment by pseudoua** [comment]
If I just change this file, will it be correct?

**Comment by ChristophWurst** [comment]
Replacing single files will likely cause more damage. Could you download an official package from https://download.nextcloud.com/server/releases/? E.g. the latest stable 20 and then replace your copy with that? As always: make backups before so you can restore the previous state.

**Comment by C-Magic** [comment]
Found a snapshot of the previous update:
NextCloud 20.0.6 → 20.0.7 RC1
Collabora 3.7.11 → 3.7.14
Code 6.4.303 → 6.4.403
Polls 1.6.3 → 1.7.5
First version be latest-19.zip

Now I'll try to change it to latest-20.zip

**Comment by C-Magic** [comment]
![image](https://user-images.githubusercontent.com/59870706/142990078-c82ffd39-84af-4af6-adbf-009668077425.png)
![image](https://user-images.githubusercontent.com/59870706/142990112-a6773bad-1b4a-450e-98a6-9315c3fc208b.png)

**Comment by ChristophWurst** [comment]
you need to provide the relevant section(s) of your nextcloud.log

But may I ask you to put the upgrade issues to https://help.nextcloud.com/c/support/7? Github is not a support forum and so far we don't see a clear indication of a bug in Mail. Please use the forums to get your instance to a working version of nextcloud. Once that is done you can try to reproduce the Mail migration error when you enable the app. Leave the app disabled until then.

**Comment by C-Magic** [comment]
Sorry! Forgot to roll back the database. Here is the real post. The previous one was after a second restoration without restoring the database
![image](https://user-images.githubusercontent.com/59870706/142992238-3019a2ba-105d-4208-b758-851ccd901e82.png)
![image](https://user-images.githubusercontent.com/59870706/142992316-97954d21-4211-4d64-aa3d-9d1342c4db2b.png)

**Comment by C-Magic** [comment]
![image](https://user-images.githubusercontent.com/59870706/143012534-3d751030-3861-4b3c-944c-ee04184c7a1d.png)
I rolled back to version 20.0.6, which had previously been successfully upgraded to 20.0.7 RC1.
And tried again to update from it to fresh. Error too!
![image](https://user-images.githubusercontent.com/59870706/143014016-0e356f27-c773-47f2-a893-75d6201164f8.png)

**Comment by m4rduc** [comment]
I have a very similar problem docker container on unraid

root@7dbf3a08b34e:/# sudo -u abc php /config/www/nextcloud/occ maintenance:mode --off
Nextcloud or one of the apps require upgrade - only a limited number of commands are available
You may use your browser or the occ upgrade command to do the upgrade
Maintenance mode disabled
root@7dbf3a08b34e:/# sudo -u abc php /config/www/nextcloud/occ upgrade
Nextcloud or one of the apps require upgrade - only a limited number of commands are available
You may use your browser or the occ upgrade command to do the upgrade
Setting log level to debug
Turned on maintenance mode
Updating database schema
Updated database
Updating <mail> ...
An unhandled exception has been thrown:
ArgumentCountError: Too few arguments to function OCA\Mail\Migration\ProvisionAccounts::__construct(), 0 passed in /config/www/nextcloud/lib/private/Repair.php on line 122 and exactly 1 expected in /config/www/nextcloud/apps/mail/lib/Migration/ProvisionAccounts.php:37
Stack trace:
#0 /config/www/nextcloud/lib/private/Repair.php(122): OCA\Mail\Migration\ProvisionAccounts->__construct()
#1 /config/www/nextcloud/lib/private/legacy/OC_App.php(1035): OC\Repair->addStep()
#2 /config/www/nextcloud/lib/private/legacy/OC_App.php(979): OC_App::executeRepairSteps()
#3 /config/www/nextcloud/lib/private/Updater.php(375): OC_App::updateApp()
#4 /config/www/nextcloud/lib/private/Updater.php(254): OC\Updater->doAppUpgrade()
#5 /config/www/nextcloud/lib/private/Updater.php(130): OC\Updater->doUpgrade()
#6 /config/www/nextcloud/core/Command/Upgrade.php(255): OC\Updater->upgrade()
#7 /config/www/nextcloud/3rdparty/symfony/console/Command/Command.php(255): OC\Core\Command\Upgrade->execute()
#8 /config/www/nextcloud/3rdparty/symfony/console/Application.php(1000): Symfony\Component\Console\Command\Command->run()
#9 /config/www/nextcloud/3rdparty/symfony/console/Application.php(271): Symfony\Component\Console\Application->doRunCommand()
#10 /config/www/nextcloud/3rdparty/symfony/console/Application.php(147): Symfony\Component\Console\Application->doRun()
#11 /config/www/nextcloud/lib/private/Console/Application.php(215): Symfony\Component\Console\Application->run()
#12 /config/www/nextcloud/console.php(100): OC\Console\Application->run()
#13 /config/www/nextcloud/occ(11): require_once('/config/www/nex...')
#14 {main}root@7dbf3a08b34e:/#

**Comment by samtuke** [comment]
I have the same error. Installed NC originally from official release tarball. CLI logs:

```
sudo -u apache php occ upgrade
Nextcloud or one of the apps require upgrade - only a limited number of commands are available
You may use your browser or the occ upgrade command to do the upgrade
Setting log level to debug
Turned on maintenance mode
Updating database schema
Updated database
Updating <mail> ...
An unhandled exception has been thrown:
ArgumentCountError: Too few arguments to function OCA\Mail\Migration\ProvisionAccounts::__construct(), 0 passed in /var/www/website.com/html/lib/private/Repair.php on line 129 and exactly 1 expected in /var/www/website.com/html/apps/mail/lib/Migration/ProvisionAccounts.php:37
Stack trace:
#0 /var/www/website.com/html/lib/private/Repair.php(129): OCA\Mail\Migration\ProvisionAccounts->__construct()
#1 /var/www/website.com/html/lib/private/legacy/OC_App.php(1053): OC\Repair->addStep('OCA\\Mail\\Migrat...')
#2 /var/www/website.com/html/lib/private/legacy/OC_App.php(997): OC_App::executeRepairSteps('mail', Array)
#3 /var/www/website.com/html/lib/private/Updater.php(386): OC_App::updateApp('mail')
#4 /var/www/website.com/html/lib/private/Updater.php(260): OC\Updater->doAppUpgrade()
#5 /var/www/website.com/html/lib/private/Updater.php(132): OC\Updater->doUpgrade('20.0.14.2', '20.0.12.1')
#6 /var/www/website.com/html/core/Command/Upgrade.php(255): OC\Updater->upgrade()
#7 /var/www/website.com/html/3rdparty/symfony/console/Command/Command.php(255): OC\Core\Command\Upgrade->execute(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#8 /var/www/website.com/html/3rdparty/symfony/console/Application.php(1000): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#9 /var/www/website.com/html/3rdparty/symfony/console/Application.php(271): Symfony\Component\Console\Application->doRunCommand(Object(OC\Core\Command\Upgrade), Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#10 /var/www/website.com/html/3rdparty/symfony/console/Application.php(147): Symfony\Component\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#11 /var/www/website.com/html/lib/private/Console/Application.php(215): Symfony\Component\Console\Application->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#12 /var/www/website.com/html/console.php(100): OC\Console\Application->run()
#13 /var/www/website.com/html/occ(11): require_once('/var/www/nextcl...')
#14 {main}
```

**Comment by samtuke** [comment]
If you need an urgent workaround to get your NC install up and running again (as I did), then follow the instructions here to disable the mail app from CLI, then your NC should finish the upgrade and work correctly: https://help.nextcloud.com/t/how-to-remove-apps-from-the-terminal/63569

**Comment by Rello** [comment]
exact same issue here

`An unhandled exception has been thrown:
ArgumentCountError: Too few arguments to function OCA\Mail\Migration\ProvisionAccounts::__construct(), 0 passed in /homepages/34/d849701472/htdocs/nextcloud/lib/private/Repair.php on line 129 and exactly 1 expected in /homepages/34/d849701472/htdocs/nextcloud/apps/mail/lib/Migration/ProvisionAccounts.php:37
Stack trace:
#0 /homepages/34/d849701472/htdocs/nextcloud/lib/private/Repair.php(129): OCA\Mail\Migration\ProvisionAccounts->__construct()
#1 /homepages/34/d849701472/htdocs/nextcloud/lib/private/legacy/OC_App.php(1053): OC\Repair->addStep('OCA\\Mail\\Migrat...')
#2 /homepages/34/d849701472/htdocs/nextcloud/lib/private/legacy/OC_App.php(997): OC_App::executeRepairSteps('mail', Array)
#3 /homepages/34/d849701472/htdocs/nextcloud/lib/private/Updater.php(386): OC_App::updateApp('mail')
#4 /homepages/34/d849701472/htdocs/nextcloud/lib/private/Updater.php(260): OC\Updater->doAppUpgrade()
#5 /homepages/34/d849701472/htdocs/nextcloud/lib/private/Updater.php(132): OC\Updater->doUpgrade('20.0.14.2', '20.0.11.1')
#6 /homepages/34/d849701472/htdocs/nextcloud/core/Command/Upgrade.php(255): OC\Updater->upgrade()
`

**Comment by ChristophWurst** [comment]
@Rello you can still reproduce after the upgrade? This is great. You can help us 🤗 

Do you remember the trick to track down a injected service that can't be loaded by the DI container? It must be something like that here. Could you comment out some of the constructor args of ProvisionAccounts or nested classes?

**Comment by ChristophWurst** [comment]
https://github.com/nextcloud/server/commit/40507ca54347a0fd9deee2d9c0286433f9fdb925 was only added for 21. Therefore your installations also do :boom: when `ILDAPProviderFactory` can't be found.

**Comment by ChristophWurst** [comment]
The fix can be found at https://github.com/nextcloud/mail/pull/5783.

https://patch-diff.githubusercontent.com/raw/nextcloud/mail/pull/5783.patch is the patch. https://docs.nextcloud.com/server/latest/admin_manual/issues/applying_patch.html will guide you through the patching process.

I would appreciate if two of you could test and verify the patch. Once I got your confirmation I'll merge, backport and release.

:v:

**Comment by C-Magic** [comment]
Weird!
Updated!
The service has started.
Proposed to upgrade to 21.0.7
Updating in progress

**Comment by ChristophWurst** [comment]
Well welcome to Nextcloud 21.

I need test results for 20. 21 won't be affected. You won't see the error.

**Comment by C-Magic** [comment]
Well my problem is solved, I was able to update from 20.07.
Thanks!
![image](https://user-images.githubusercontent.com/59870706/144825009-6e5681b6-b902-4acd-bdaa-65414113b9ab.png)
**There is no mistake anymore**

**Comment by C-Magic** [comment]
If necessary, I can roll back to 20.0.6 and update again

**Comment by Rello** [comment]
Hi,
also confirmed to be working on 20.0.14
thank you!

**Comment by C-Magic** [comment]
20.0.6 (mail 1.4.2  to 1.11.0) - OK (post patch)!
20.0.7 (mail 1.8.0 to 1.11.0) - OK (post patch)!

**Comment by ChristophWurst** [comment]
Thanks for the quick testing feedback @Rello @C-Magic! :v:

**Comment by C-Magic** [comment]
pseudoua is also me (from home)
