### ISSUE TITLE
[Feature Request] Ignore JUNK / SPAM Folder for important mails

### ISSUE THREAD

**Issue by Gunnar-GO** [nextcloud/mail#5754]
If i open mail i get the priority mailbox, thats fine and a usefull idea. 

My mailboxes are sorted, partly filtered and synced via IMAP. an eMail in Junk / Spam (Newsletter are discussable) shouldn't be listed in prioritised mailbox.

Maybe there is an option to set folders to ignore i missed?

**Comment by miaulalala** [comment]
Can you possibly share a screenshot? It's highly unusual that a mail from junk shows up in the prio inbox.

**Comment by ChristophWurst** [comment]
For clarification: are we talking about messages from junk/spam *mailboxes* or messages in the inbox tagged as spam/junk? Only the latter is possible for the PI. The classification currently doesn't take any flags into consideration.
