### ISSUE TITLE
Disable adding of own accounts

### ISSUE THREAD

**Issue by kroerig** [nextcloud/mail#5759]
### Feature Request

From https://help.nextcloud.com/t/disable-setting-add-new-mail-account/106160

Users can add their own accounts. It should be possible to disable this function globally.

#### Summary

Adding external accounts could break data protecion rules.

**Comment by the-djmaze** [comment]
Disable autoconfig and manual login screen should be the best option.
But it als requires error messages (not allowed) and domain settings management.

I came here due to discussion
https://github.com/the-djmaze/snappymail/discussions/1738#discussioncomment-10669358

**Comment by ChristophWurst** [comment]
Delivered via https://github.com/nextcloud/mail/pull/7358
