### ISSUE TITLE
BadFunctionCallException: ldapAliasesProvisioning is not a valid attribute

### ISSUE THREAD

**Issue by dervishe-** [nextcloud/mail#5760]
### Expected behavior
When we go to the Mail app in Nextcloud, it shoud show the mail interface. Before the new app version, it was working well.

### Actual behavior
It show an error message on blue screen:

Erreur interne du serveur
Le serveur est incapable d'exécuter votre requête.
Si cela se reproduit, veuillez envoyer les détails techniques ci-dessous à l'administrateur du serveur.
Le fichier journal du serveur peut fournir plus de renseignements.
Renseignements techniques
    Adresse distante : my.ip.address
    ID de la demande : myRequestId

The log trace:

```
[index] Error: ldapAliasesProvisioning is not a valid attribute

GET /apps/mail/
from XX.XX.XX.XX by admin at 2021-11-30T17:56:31+01:00

```

`{"reqId":"ml17puWC94kFlUWI4WWI","level":3,"time":"2021-11-30T17:56:31+01:00","remoteAddr":"XX.XX.XX.XX","user":"admin","app":"index","method":"GET","url":"/apps/mail/","message":"ldapAliasesProvisioning is not a valid attribute","userAgent":"Mozilla/5.0 (X11; Linux x86_64; rv:78.0) Gecko/20100101 Firefox/78.0","version":"22.2.3.0","exception":{"Exception":"BadFunctionCallException","Message":"ldapAliasesProvisioning is not a valid attribute","Code":0,"Trace":[{"file":"/usr/local/www/nextcloud/lib/public/AppFramework/Db/Entity.php","line":158,"function":"setter","class":"OCP\\AppFramework\\Db\\Entity","type":"->"},{"file":"/usr/local/www/nextcloud/lib/public/AppFramework/Db/Entity.php","line":73,"function":"__call","class":"OCP\\AppFramework\\Db\\Entity","type":"->"},{"file":"/usr/local/www/nextcloud/lib/public/AppFramework/Db/QBMapper.php","line":320,"function":"fromRow","class":"OCP\\AppFramework\\Db\\Entity","type":"::"},{"file":"/usr/local/www/nextcloud/lib/public/AppFramework/Db/QBMapper.php","line":339,"function":"mapRowToEntity","class":"OCP\\AppFramework\\Db\\QBMapper","type":"->"},{"file":"/usr/local/www/nextcloud/apps/mail/lib/Db/ProvisioningMapper.php","line":60,"function":"findEntities","class":"OCP\\AppFramework\\Db\\QBMapper","type":"->"},{"file":"/usr/local/www/nextcloud/apps/mail/lib/Service/Provisioning/Manager.php","line":79,"function":"getAll","class":"OCA\\Mail\\Db\\ProvisioningMapper","type":"->"},{"file":"/usr/local/www/nextcloud/apps/mail/lib/Http/Middleware/ProvisioningMiddleware.php","line":67,"function":"getConfigs","class":"OCA\\Mail\\Service\\Provisioning\\Manager","type":"->"},{"file":"/usr/local/www/nextcloud/lib/private/AppFramework/Middleware/MiddlewareDispatcher.php","line":97,"function":"beforeController","class":"OCA\\Mail\\Http\\Middleware\\ProvisioningMiddleware","type":"->"},{"file":"/usr/local/www/nextcloud/lib/private/AppFramework/Http/Dispatcher.php","line":118,"function":"beforeController","class":"OC\\AppFramework\\Middleware\\MiddlewareDispatcher","type":"->"},{"file":"/usr/local/www/nextcloud/lib/private/AppFramework/App.php","line":156,"function":"dispatch","class":"OC\\AppFramework\\Http\\Dispatcher","type":"->"},{"file":"/usr/local/www/nextcloud/lib/private/Route/Router.php","line":302,"function":"main","class":"OC\\AppFramework\\App","type":"::"},{"file":"/usr/local/www/nextcloud/lib/base.php","line":1006,"function":"match","class":"OC\\Route\\Router","type":"->"},{"file":"/usr/local/www/nextcloud/index.php","line":36,"function":"handleRequest","class":"OC","type":"::"}],"File":"/usr/local/www/nextcloud/lib/public/AppFramework/Db/Entity.php","Line":129,"CustomMessage":"--"},"id":"61a657c262af3"}
`

### Mail app

**Mail app version:** 1.11.0

**Mailserver or service:** postfix/dovecot

### Server configuration

**Operating system**: freeBSD

**Web server:** nginx

**Database:** mariadb / openldap

**PHP version:** 8.0.12

**Nextcloud Version:** 22.2.3

#### Client configuration
**Browser:** Firefox78.15.0esr (64 bits)

**Operating system:** gentoo

**Comment by kesselb** [comment]
Hi, on your instance a database migration, to add the column ldap aliases provisioning, did not run.

https://github.com/nextcloud/mail/blob/master/lib/Migration/Version1101Date20210616141806.php is the related migration.

**Comment by dervishe-** [comment]
Using occ maintenance:repair did the job. Thanks !

**Comment by aiso-net** [comment]
Im having the same issue and the occ maintenance:repair did not fix it for me.
