### ISSUE TITLE
Invalid Message-ID header

### ISSUE THREAD

**Issue by sim6** [nextcloud/mail#5764]
### Expected behavior
Create valid Message-ID header.
From syntax rules of https://datatracker.ietf.org/doc/html/rfc822
```
optional-field =
                 /  "Message-ID"        ":"   msg-id

msg-id      =  "<" addr-spec ">"            ; Unique message id

addr-spec   =  local-part "@" domain        ; global address
```
I undestand that should be something like the following example:
```
Message-ID: <20211201100841.Horde.vJATlrnmG0ZJXLLjr-iX2-Z@example.com>
```

### Actual behavior
Current Message-ID doesn't content the domain, it is like the following example: 
```
Message-ID: <20211201100841.Horde.vJATlrnmG0ZJXLLjr-iX2-Z@>
```

### Mail app

**Mail app version:** 1.11.0

**Mailserver or service:** mailu.io

### Server configuration

**Operating system**: Alpine (docker image nextcloud:21.0.2-fpm-alpine)

**Web server:** Nginx

**Database:** PostgreSQL

**PHP version:** PHP 7.4.20 (cli) (built: Jun  3 2021 22:19:26) ( NTS )

**Nextcloud Version:** 21.0.2

**Comment by ChristophWurst** [comment]
If I'm not mistaken this happens at https://github.com/nextcloud/mail/blob/7e14ad8fe990ca27347d06edf4f35c6f7c6f377d/lib/Service/MailTransmission.php#L275. It's horde's logic to build the identifier.

**Comment by ChristophWurst** [comment]
It uses `$_SERVER['SERVER_NAME']`. An empty string in that superglobal could lead to the empty part after `@`.

> Message-ID: <20211201100841.Horde.vJATlrnmG0ZJXLLjr-iX2-Z@>

**Comment by sim6** [comment]
Thanks, I see that it spuld fallback to `localhost`.

https://github.com/horde/Support/blob/d9ad61f15c07d76f2bd68a0d64cd8db60081ac8b/lib/Horde/Support/Guid.php#L60

I will take a look if we have al empty string value in `$_SERVER['SERVER_NAME'].

**Comment by ChristophWurst** [comment]
Thanks for checking. If that's the case then we should send a patch upstream to switch from `isset` to `empty`.

**Comment by sim6** [comment]
Yes, it is empty. I will investigate why is empty.

**Comment by sim6** [comment]
Our fault: https://gitlab.com/isard/isard-apps/-/merge_requests/28
I'm sorry for the noise.
Thanks you very much.

**Comment by ChristophWurst** [comment]
No worries :)
