### ISSUE TITLE
Unexpected behaviour in Mail Rendering

### ISSUE THREAD

**Issue by feutl** [nextcloud/mail#5774]
### Expected behavior
This is how the mail looks like in Rainloop (inside Nextcloud) and Fairemail on my Android Phone
![image](https://user-images.githubusercontent.com/8522012/144555864-7fea8e28-cf90-48d1-81ed-19051c467afd.png)
![image](https://user-images.githubusercontent.com/8522012/144556034-c94831f8-51fd-43bc-9e9c-b7a337a57bb0.png)

### Actual behavior
This is the mail in NC Mail with the "Termin buchen" Link not visible, but if you know where it is, you can click it at least 🗡️ 
![image](https://user-images.githubusercontent.com/8522012/144556102-ffc43e75-fa61-405a-92ea-0b90a01696a5.png)

### Mail app
**Mail app version:** 1.11
**Mailserver or service:** IMAP

### Server configuration
**Operating system**: Debian 10
**Web server:** Apache
**Database:** MariaDB
**PHP version:** 7.3
**Nextcloud Version:** 22.2.2
#### Client configuration
**Browser:** FF 94 & Edge 96.0
**Operating system:** Windows 10

HTML Code of the Mail can be shared if requested.

**Comment by GretaD** [comment]
hello @feutl, does any error popup on web console when you open this specific message? 
Can you please send us your nextcloud log(or how ever you call your instance)

I will try to reproduce it myself too.

**Comment by feutl** [comment]
@GretaD I have sent you an email, hopefully this helps.

**Comment by GretaD** [comment]
Hello @feutl,

I have discussed this with one of my colleagues and we cannot find a reason why this happens, we tried even to hack a solution and it doesn work. Somehow the background color is filtered out. We will discuss it with another colleague too.

**Comment by feutl** [comment]
@GretaD 
Thanks, but it is not that unusual having issues with mail rendering.
For example, mails from aliexpress cannot be opened at all wie NC Mail, whereas Rainloop on NC or Fairemail on Android handles that without problems.
Whereas with the mails from aliexpress I get at least a console error, but have no clue why and the mail stays "white"
```
Status
500
Internal Server Error
VersionHTTP/2
Transferred879 B (62 B size)
Referrer Policyno-referrer
```

**Comment by GretaD** [comment]
> @GretaD Thanks, but it is not that unusual having issues with mail rendering. For example, mails from aliexpress cannot be opened at all wie NC Mail, whereas Rainloop on NC or Fairemail on Android handles that without problems. Whereas with the mails from aliexpress I get at least a console error, but have no clue why and the mail stays "white"

How do you mean "stays white". If you inspect that mail, can you read the content?

**Comment by miaulalala** [comment]
Could this be the html parser?

**Comment by ChristophWurst** [comment]
> 500
> Internal Server Error

Check nextcloud.log

**Comment by feutl** [comment]
> > 500
> > Internal Server Error
> 
> Check nextcloud.log

This is what I see opening the aliexpress mail
```
<html><body>
<!--StartFragment-->

  | Exception: Argument  2 passed to OCA\Mail\Service\MailManager::getThread() must be of the  type string, null given, called in  /var/www/nextcloud/apps/mail/lib/Controller/MessagesController.php on  line 310/var/www/nextcloud/lib/private/AppFramework/App.php - line 156: OC\AppFramework\Http\Dispatcher->dispatch(OCA\Mail\Con ... {}, "getThread")/var/www/nextcloud/lib/private/Route/Router.php - line 302: OC\AppFramework\App::main("OCA\\Mail\\ ... r", "getThread", OC\AppFramew ... {}, { id: "54639 ... "})/var/www/nextcloud/lib/base.php - line 1006: OC\Route\Router->match("/apps/mail/ ... d")/var/www/nextcloud/index.php - line 36: OC::handleRequest()Verursacht durch TypeError: Argument  2 passed to OCA\Mail\Service\MailManager::getThread() must be of the  type string, null given, called in  /var/www/nextcloud/apps/mail/lib/Controller/MessagesController.php on  line 310/var/www/nextcloud/apps/mail/lib/Controller/MessagesController.php - line 310: OCA\Mail\Service\MailManager->getThread(OCA\Mail\Account {}, null)/var/www/nextcloud/lib/private/AppFramework/Http/Dispatcher.php - line 217: OCA\Mail\Controller\MessagesController->getThread(54639)/var/www/nextcloud/lib/private/AppFramework/Http/Dispatcher.php - line 126: OC\AppFramework\Http\Dispatcher->executeController(OCA\Mail\Con ... {}, "getThread")/var/www/nextcloud/lib/private/AppFramework/App.php - line 156: OC\AppFramework\Http\Dispatcher->dispatch(OCA\Mail\Con ... {}, "getThread")/var/www/nextcloud/lib/private/Route/Router.php - line 302: OC\AppFramework\App::main("OCA\\Mail\\ ... r", "getThread", OC\AppFramew ... {}, { id: "54639 ... "})/var/www/nextcloud/lib/base.php - line 1006: OC\Route\Router->match("/apps/mail/ ... d")/var/www/nextcloud/index.php - line 36: OC::handleRequest()
-- | --


<!--EndFragment-->
</body>
</html>
```

for the other mail (oesterreich-testet), where @GretaD is already working on, I do not see and error in the nextcloud log

**Comment by feutl** [comment]
I found another mail having the same issue or actually even worse. It does not render at all.
![image](https://user-images.githubusercontent.com/8522012/149472050-b6c7ae1b-e1b0-4994-8be5-d0e3c601201b.png)

Mail App Version: 1.11.5

**Comment by miaulalala** [comment]
@feutl can you forward me the email if at all possible? anna@nextcloud.com :)

**Comment by feutl** [comment]
> @feutl can you forward me the email if at all possible? [anna@nextcloud.com](mailto:anna@nextcloud.com) :)

on its way :)

**Comment by feutl** [comment]
I got another message these days having the same issue with the latest NC mail app on my instance.

![image](https://user-images.githubusercontent.com/8522012/161544755-8b6f6239-b8c5-4604-bd4a-7addd1209ff3.png)

And this is what Thunderbird makes out of it
![image](https://user-images.githubusercontent.com/8522012/161544995-0ecff397-35e4-416b-bd23-560d165ed953.png)
