### ISSUE TITLE
Cannot connect G Suite email to NextCloud Mail

### ISSUE THREAD

**Issue by rebeccaformfx** [nextcloud/mail#578]
### Steps to reproduce
1.  Create one-time password for G Suite Gmail account 
2.  Enter in email and one-time password
3.  Receive error connecting

I did this successfully with my @gmail.com account, but with my business email which is a Bluehost email server being serviced through G Suite, this is failing every time.  I have 2-step verification on and am using an App password to connect to NextCloud.  Access to "less secure apps" is Enabled so that shouldn't be a problem.
 
Any pointers?

### Expected behaviour
Tell us what should happen

### Actual behaviour
Tell us what happens instead

### Mail app

**Mail app version:** (see apps admin page)

**Mailserver or service:** (e.g. Outlook, Yahoo, Gmail, Exchange,...)

**Transport security - IMAP:** (None, SSL, TLS, STARTTLS) 

**Transport security - SMTP:** (None, SSL, TLS, STARTTLS)

**Number of accounts:**

**Mail app version build date:** (only if you are using a Nightly Build)

### Server configuration

**Operating system**:

**Web server:**

**Database:**

**PHP version:**

**Version:** (see admin page)

**Updated from an older version or fresh install:**

**List of activated apps:**

```
If you have access to your command line run e.g.:
sudo -u www-data php occ app:list
from within your server installation folder
```

**The content of config/config.php:**

<details>
```
If you have access to your command line run e.g.:
sudo -u www-data php occ config:list system
from within your Nextcloud installation folder

or

Insert your config.php content here
Make sure to remove all sensitive content such as passwords. (e.g. database password, passwordsalt, secret, smtp password, …)
```
</details>

#### Client configuration
**Browser:**

**Operating system:**

##### Web server error log
```
Insert your webserver log here
```

##### Server log (data/nextcloud.log)
<details>
```
Insert your server log here
```
</details>

##### Horde IMAP log (data/horde_imap.log)
<details>
```
Insert your horde IMAP log here, see https://github.com/nextcloud/mail#debug-mode
```
</details>

##### Horde SMTP log (data/horde_smtp.log)
<details>
```
Insert your horde SMTP log here, see https://github.com/nextcloud/mail#debug-mode
```
</details>

##### Browser log
<details>
```
Insert your browser log here, this could for example include:

a) The javascript console log
b) The network log 
c) ...
```
</details>

**Comment by ChristophWurst** [comment]
> Receive error connecting

Hi,

if you fill out the full issue template, I might be able to tell you what failed and thus how it could be fixed. With this sparse information it's hard to tell.

Please provide the log entries as asked by the issue template. Thanks.

**Comment by ChristophWurst** [comment]
No info provided -> closing
