### ISSUE TITLE
Upgrading to 1.11.0 Error Message "General error: 2006 MySQL server has gone away"

### ISSUE THREAD

**Issue by jlaba** [nextcloud/mail#5781]
### Expected behavior
Upgrade from 1.10 to 1.11. should run without any problems

### Actual behavior
Upgrade stops with the error "General error: 2006 MySQL server has gone away"

### Mail app

**Mail app version:** 1.11.0

**Mailserver or service:** Postfix and Dovedot on same host

### Server configuration

**Operating system**: Debian 10 Buster

**Web server:** Apache

**Database:** MariaDB

**PHP version:** 7.3

**Nextcloud Version:** 22.2.3

#### Client configuration
**Browser:** Firefox 91.3

**Operating system:** OpenSUSE Leap 15.3

**Comment by ChristophWurst** [comment]
Your mysql server is down. Check its logs.

**Comment by jlaba** [comment]
Yep, you are right. It's crashing at the command

`ALTER TABLE oc_mail_provisionings ADD ldap_aliases_provisioning TINYINT(1) DEFAULT '0', ADD ldap_aliases_attribute VARCHAR(255) DEFAULT ''`

It's crashing because of the assertion failure InnoDB: Assertion failure in file /build/mariadb-10.3-Y84vY7/mariadb-10.3-10.3.31/storage/innobase/dict/dict0mem.cc line 143

So probably there is something wrong with my database. Nevertheless it is strange, that it is happening only at this line every time. All other services including nextcloud without the mail app are running fine.

**Comment by ChristophWurst** [comment]
Could you try again with MariaDB 10.3.32? That is the latest release of the 10.3 line.

To me it's a bit strange that the whole DB crashes because of a query. If there is anything wrong with it I would just expect an SQL error.

**Comment by jlaba** [comment]
Actually I do not want to install mariadb versions, not in the distribution repository. But now I have upgraded to debian bullseye and now it is running mariadb version 10.5.12. But it produces the same error as before.

**Comment by ChristophWurst** [comment]
Even on a second look I don't see anything wrong with the DDL we send. 

What happens if you run the same query manually?

If it goes through drop the two newly created columns again to get back to the previous schema.

**Comment by joni1993** [comment]
I expirience the same error with the Talk app - MariaDB(10.3.32) just crashes. I suspect this is not due to the apps but some problem with the SQL server.

**Comment by joni1993** [comment]
It seems some corruption happened here - doing an mysqldump and reimporting it again, the error disappears. Maybe this helps @jlaba

**Comment by jlaba** [comment]
I have dumped the database and loaded it at another server. I issued the ALTER TABLE command manually and it works without any problems.

Dropped the original database and imported it from the dump again to the original server. Afterwards everything runs as expected. I'm not sure, what has corrupted the database, but after the reimport is seems to be gone.
