### ISSUE TITLE
Incorrect position of navigation button

### ISSUE THREAD

**Issue by TeksuSiK** [nextcloud/mail#5785]
### Expected behavior
Navigation button shouldn't overlap other elements

### Actual behavior
![](https://i.imgur.com/JX4VkHh.png)

### Mail app
**Mail app version:** 1.11.0
**Mailserver or service:** N/A

### Server configuration
**Operating system**: Ubuntu 20.04
**Web server:** Nginx
**Database:** MySQL
**PHP version:** 7.4
**Nextcloud Version:** 23.0.0

### Client configuration
**Browser:** Edge 96.0.1054.43
**Operating system:** Windows 11 21H2

**Comment by ChristophWurst** [comment]
Known: https://github.com/nextcloud/groupware/issues/2
