### ISSUE TITLE
Reply button is a bit messed up

### ISSUE THREAD

**Issue by thstyl2000** [nextcloud/mail#5789]
### Expected behavior
Reply button should look good

### Actual behavior
Reply button looks like that:

![Screenshot_20211207_113207](https://user-images.githubusercontent.com/18458458/145013151-25675a54-a52c-4e88-8fc1-427a1144141e.png)

### Mail app

**Mail app version:** 1.11.0

**Mailserver or service:** IMAP

### Server configuration

**Operating system**: FreeBSD

**Web server:** Apache

**Database:** MariaDB

**PHP version:** 8.0

**Nextcloud Version:** 22.2.3

#### Client configuration
**Browser:** Chromium 96.0.4664.45
**Operating system:** Kubuntu

**Comment by GretaD** [comment]
this was already fixed and the release had the fixed version, i dont understand why you're seeing this. Let me try to reproduce with your setup.

**Comment by GretaD** [comment]
Oh i think i found the problem, you're still on NC 22 and the PR that fixes this: https://github.com/nextcloud/server/pull/30010

its not merged yet for 22.

**Comment by st3iny** [comment]
The fix is merged and will be included in all upcoming releases.
