### ISSUE TITLE
Print stylesheet [$65]

### ISSUE THREAD

**Issue by andrewborell** [nextcloud/mail#579]
Occasionally a user needs to print an email. CTRL+P will print the page, not the message. Adding a div to the messages-list-item template and some js tied to an action will not address CTRL+P but im not sure if everyone would want to override the browser shortcut anyway.  

There are some tricks in CSS To make the output in the mail-message-container cleaner ( reply attachment and forward buttons for example ) for printing but putting the print button in the message list item would at least prevent that particular control from being printed. 

Alternatively I suppose it would be even better in some cases to pull the message from the mail server again for printing purposes to avoid printing all the extraneous information mentioned above, and in the event someone entered text into the reply but had not sent it yet -- we might not want to print message text that has never been sent. 

Other considerations are whether we want the print preview dialog allowing the user to select a printer or to blindly print to whatever is default.   

Any thoughts on this?  I can probably contribute to this one if its not already in progress or part of NCMail13 but Id like to hear some input from others. 

thx
-d

**Comment by jancborchardt** [comment]
@andrewborell it would be great if you can contribute this! :) Am happy to help.

Generally how I would do it is in the print stylesheet simply hide everything except app-content-detail (the rightmost column) and of course the reply fields and actions. Then there's also special CSS with :after to display the contents of an href in parentheses behind the actual linked text so links are "readable" even when printed. Fonts and everything I'd keep the same.

**Comment by jancborchardt** [comment]
@andreasjacobsen93 any update on this? As said I would be happy to assist you with this. :)
