### ISSUE TITLE
Set working hours disappear for a second when refresh

### ISSUE THREAD

**Issue by GretaD** [nextcloud/mail#5791]
### Expected behavior
When i refresh the set working hours should show

### Actual behavior
for 1 second no working hours are shown

https://user-images.githubusercontent.com/12728974/145018578-3d17d267-1dc8-4ec9-b7bc-616e95e5c247.mp4

### Mail app

**Mail app version:** latest

**Comment by ChristophWurst** [comment]
Done via https://github.com/nextcloud/calendar-availability-vue/issues/13
