### ISSUE TITLE
Error in german translation of account deletion modal

### ISSUE THREAD

**Issue by st3iny** [nextcloud/mail#5795]
### Expected behavior
I open the modal to delete a mail account.
The placeholder for the email should be replaced correctly.

### Actual behavior
The placeholder (`{E-Mail}`) is not replaced because it seems like it was modified in the german translation. It should be left untouched and probably be `{email}`.

(The email address was redacted for privacy reasons.)
![mail-translation-bug](https://user-images.githubusercontent.com/1479486/145191549-8f3dbc81-ffc3-4690-95a6-b2764343b32e.PNG)

### Mail app

**Mail app version:** 1.11.0

**Mailserver or service:** Not relevant

### Server configuration

**Operating system**: Ubuntu LTS

**Web server:** Nginx

**Database:** MariaDB

**PHP version:** 7.4

**Nextcloud Version:** 22.2.3

**Comment by ChristophWurst** [comment]
@rakekniven could you take care of this? Thanks.

**Comment by rakekniven** [comment]
> @rakekniven could you take care of this? Thanks.

Yes.
