### ISSUE TITLE
Provision aliases based on "User Backend SQL Raw" plugin

### ISSUE THREAD

**Issue by Samonitari** [nextcloud/mail#5797]
### Feature Request

The [User Backend SQL Raw plugin](https://github.com/PanCakeConnaisseur/user_backend_sql_raw) is a simple plugin that makes it possible to use an existing SQL database as a user backend. Users of this plugin - at least the ones that I know of - connect a  mailserver's database this way as a backend to Nextcloud, which would contain mail aliases (if they exist).

Similarily to #5173 I'd like that the Mail app could extract the alias list for the provisioned account, using this backend instead of LDAP.
This has a preprequisite that the mentioned plugin does have (at least) a setting entry for alias querying. That seems fairly trivial.
Setting aliases through this backend from Mail app could be postponed as second step (does the LDAP backend support this), but the option to select an existing alias from the mailserver's database would be a great convenience already, as:
- provisioned, non-LDAP accounts prohibit alias additions, so you cannot even add the existing ones manually.
- mailserver database re-users would already have a way to add aliases.

Thanks for the answer!

**Comment by ChristophWurst** [comment]
Given the low traffic on this ticket I would close it as not planned for now

**Comment by ultinous-kszegi** [comment]
No problem, I've since moved away from "User Backend SQL Raw" to LDAP.
