### ISSUE TITLE
Performance improvements

### ISSUE THREAD

**Issue by ChristophWurst** [nextcloud/mail#5835]
### Feature Request

The app performance can be improved. This is an overview. Tickets are sorted from highest impact to lowest.

* [x] https://github.com/nextcloud/mail/issues/4466
* [x] https://github.com/nextcloud/mail/issues/6305
* [x] https://github.com/nextcloud/mail/issues/6307
* [x] https://github.com/nextcloud/mail/issues/4823
* [x] https://github.com/nextcloud/mail/issues/4983
* [x] https://github.com/nextcloud/mail/issues/6308
* [x] https://github.com/nextcloud/mail/issues/4664
* [x] https://github.com/nextcloud/mail/issues/5294

Removed from the short term plan
* https://github.com/nextcloud/mail/issues/5250

Related changes
* https://github.com/nextcloud/mail/issues/4735

Improvements that do not show any performance benefits right now
* https://github.com/nextcloud/mail/issues/4824

#### Summary

Make the app faster and more usable.

**Comment by brendan-pike** [comment]
Our small organisation has just starting using mail for its main communication and file sharing with clients. We have 4 employees sharing a single email account,  to achieve this we simply added the imap account for each user.  Loading an email can take 10 to 20 second to load a single email. We have a VPS with lots of resources 4 CPU/8GB low load and has been highly tuned as per nextcloud documentation.

Performance is our top issue right now.  So I see this ticket is very important.

**Comment by ChristophWurst** [comment]
You judged too early. The tags just tell us how quickly we need to pick something up. The linked tickets will be addressed shortly.

**Comment by brendan-pike** [comment]
Thanks for the feedback Christoph, that is encouraging to hear.

My team has had me install afterlogic and rainloop and have been testing 
them and while of course they are faster none of them properly integrate 
in the way that nextcloud mail does.  Nextlcoud mail will always be 
everyone's first choice, but as a tool used all day long the speed issue 
is significant.

Also, I'm new to this community but I've been a dedicated opensource 
user and advocate for decades. I would strongly encourage you to not 
hide comments that you find negative, unless they are offensive or a 
personal attack. Censorship quickly disengages a community where as an 
open response if respected even if it strongly disagrees with the first 
person.

Thank you for everything you and the Nextcloud team do!

Cheers
Brendan
