### ISSUE TITLE
Selecting messages is visualized as bold

### ISSUE THREAD

**Issue by GretaD** [nextcloud/mail#5836]
When I select a message or more, it turns into bold, making it confusing if its a read message or a select message.

https://user-images.githubusercontent.com/12728974/145803275-0ce1dcac-bae3-44ac-be38-1aba26dddfb2.mp4

**Comment by GretaD** [comment]
Actually, im not sure if its a bug or intended but i think its confusing. @nextcloud/designers any idea how it should be shown when i select messages?

**Comment by st3iny** [comment]
Isn't the checkbox and highlighted background enough? IMO, we could just remove the bold text when selecting envelopes so that bold always means unread.

**Comment by GretaD** [comment]
@nimishavijay @jancborchardt what do you think?

**Comment by nimishavijay** [comment]
Agreed, bold should just be for unread messages. The checkbox being filled is more than enough visual indication.
We can get rid of the bold when selecting.
