### ISSUE TITLE
Threading does not work as it should.

### ISSUE THREAD

**Issue by small1** [nextcloud/mail#5841]
### Expected behavior
Each email should have its own thread

### Actual behavior
Some emails gets threaded wrong. And if one doesnt notice this deleting a thread might delete other emails as well.

![Screenshot from 2021-12-13 15-28-34](https://user-images.githubusercontent.com/317830/145832597-f732d3ef-c152-43c9-9361-152f1ce64947.png)

### Mail app

**Mail app version:** 1.11.1

**Mailserver or service:**  dovecot 2.2.9

### Server configuration

**Operating system**: Debian 10

**Web server:** Nginx

**Database:** Mariadb

**PHP version:** 7.4

**Nextcloud Version:** 23.0.0

#### Client configuration
**Browser:** Chrome latest

**Operating system:** ubuntu 20.04

**Comment by ChristophWurst** [comment]
fixed by https://github.com/nextcloud/mail/pull/5828
