### ISSUE TITLE
Logic flaw with Array Chunking and Doctrines DBAL 

### ISSUE THREAD

**Issue by swdee** [nextcloud/mail#5844]
## Introduction

In my investigation with debugging #5716 I discovered the bug is due to a wide spread logic flaw in the code base where Array Chunking is used with Doctrines DBAL Query Builder.

Throughout the code base array chunking of queries has been implemented by first creating a new `QueryBuilder`  then proceeding with the `foreach` loop, eg:

https://github.com/nextcloud/mail/blob/71dca9e3e9bd375880b9ca8e2d8acbd6e18fc903/lib/Db/MessageMapper.php#L1130-L1136

In the above piece of code `$ids` has ~94000 elements when I ran into issue #5716.

## Code Logic Execution

The code logic that triggers the above bug executes as follows;

* A new instance of `QueryBuilder` is created on Line 1130.

* `foreach` loop is entered and the first 1000 ids are processed.

* In the query construction `createNamedParameter()` is called on Line 1134.

* Doctrines DBAL `createNamedParameter()` function returns a string, however it also stores in an array the parameter created in its `setParameter()` call.
https://github.com/doctrine/dbal/blob/7d0c93ad2725b6f6688f93956f105e67ca4cdc9d/src/Query/QueryBuilder.php#L1463-L1473

* Code of `setParameter()` showing the key and value is stored in `$this->params`.
https://github.com/doctrine/dbal/blob/7d0c93ad2725b6f6688f93956f105e67ca4cdc9d/src/Query/QueryBuilder.php#L417-L426

* Once query is built the `execute()` function is called and a number of checks/tests are performed.  One of these tests involves retrieving the parameters of the query using the `getParameters()` call.
https://github.com/nextcloud/server/blob/af98f52eacab4c8731063c5261f4b1267fb25cf9/lib/private/DB/QueryBuilder/QueryBuilder.php#L257-L265

* `getParameters()` returns the array `$this->params`.
https://github.com/doctrine/dbal/blob/decf34ad95334180dec6497f47b1557de02ea9b0/src/Query/QueryBuilder.php#L460-L463

## The Flaw

The code logic flaw occurs on the subsequent iterations of the `foreach` loop.  `$qb4` creates a new `QueryBuilder` above the loop, but each time the loop executes the parameters are being set in Doctrines `$this->params` without being cleared.  Therefore `$this->params` keeps growing until ~65 iterations of the loop have occurred which then triggers the check below erroring with `The number of parameters must not exceed 65535. Restriction by PostgreSQL.`.

https://github.com/nextcloud/server/blob/af98f52eacab4c8731063c5261f4b1267fb25cf9/lib/private/DB/QueryBuilder/QueryBuilder.php#L277-L285

You can see in Doctrines `execute()` function that parameters are never cleared.
https://github.com/doctrine/dbal/blob/decf34ad95334180dec6497f47b1557de02ea9b0/src/Query/QueryBuilder.php#L336
https://github.com/doctrine/dbal/blob/decf34ad95334180dec6497f47b1557de02ea9b0/src/Connection.php#L1117

## Solution

One solution to this problem would be a refactoring of the code bases use of array chunking to create a new `QueryBuilder` inside the `foreach` loop, eg:

```php
foreach (array_chunk($ids, 1000) as $chunk) {
     $qb4 = $this->db->getQueryBuilder();
     $recipientsQuery = $qb4
          ->delete('mail_recipients')
          ->where($qb4->expr()->in('id', $qb4->createNamedParameter($chunk, IQueryBuilder::PARAM_INT_ARRAY), IQueryBuilder::PARAM_INT_ARRAY));
     $recipientsQuery->execute();
}
```
As each iteration of the loop creates a new `QueryBuilder` the parameters array effectively is reset for each 1000 entries so reaching a parameter limit of 65535 would never be hit.

**Comment by ChristophWurst** [comment]
This matches with @miaulalala's findings from yesterday. Instead of creating a new instance of the query builder it's also possible to use a parameter to create the query outside the loop, then inside always just assign the new value and execute the query.

Awesome debugging @swdee :v:
