### ISSUE TITLE
Loading messages fails on some folders with mb_convert_encoding() error

### ISSUE THREAD

**Issue by victoraroyo** [nextcloud/mail#5845]
The setup is Nexcloud 23 beta, IMAP mailbox, centos 7 with postgres 12.8, php 8.0.3.

The specific error is:

mb_convert_encoding(): Argument #3 ($from_encoding) must specify at least one encoding

and in the logs the full stack says:

Caused by ValueError: mb_convert_encoding(): Argument #3 ($from_encoding) must specify at least one encoding
/var/www/html/nextcloud/apps/mail/vendor/pear-pear.horde.org/Horde_Util/Horde/String.php - line 160:

mb_convert_encoding(null, "utf-8", "")

Is there a setting I'm missing or something else I should do to my setup to fix it?

Edit: Forgot to clarify that this is due to php8 now throw a value error for incorrect encoding. It is fixable if in vendor/pear-pear.horde.org/Horde_Util/Horde/String.php from_encoding is changed to self::_mbstringCharset($from)?self::_mbstringCharset($from):null but is there a setting to specify a default encoding which I'm missing.

**Comment by miaulalala** [comment]
Related to #5834
