### ISSUE TITLE
Add "select all" / "unselect all" in mailboxes

### ISSUE THREAD

**Issue by MeiKatz** [nextcloud/mail#5859]
### Feature Request

Currently there is no option to select / unselect all items / messages in a mailbox. There could be an option after selecting at least one item in the now showing popup menu above the messages list.

**Comment by GretaD** [comment]
Hello,

We do have the selecting option. Click the action menu of one messages and its one of the options
![select](https://user-images.githubusercontent.com/12728974/146365143-82cbaa15-3537-4dbd-9298-9f2bc6ca455f.png)

**Comment by MeiKatz** [comment]
No, that's the option to mark all selected messages as read. But it's not an option to select all messages or unselect all messages. That's a totally different action.

**Comment by GretaD** [comment]
> No, that's the option to select a message so I can select some messages together. But it's not an option to select all messages or unselect all messages. That's a totally different action. The advantage would be, that I don't have to select each message on its own, but to click "select all" and all messages are selected at once.

Ah, sorry, I misread your request

**Comment by ChristophWurst** [comment]
so a dup of https://github.com/nextcloud/mail/issues/4285?

**Comment by MeiKatz** [comment]
> so a dup of #4285?

Yes, I think so. I could not find it while searching for it yesterday evening.
