### ISSUE TITLE
Reply arrows cannot be seen in night mode

### ISSUE THREAD

**Issue by StCyr** [nextcloud/mail#5861]
### Expected behavior
Reply arrows in EnvelopeList should be white on black background in night mode

### Actual behavior
Reply arrows are black on black background

![image](https://user-images.githubusercontent.com/8179031/146338310-37e2e64e-9c49-4472-966a-ed96142d44cf.png)

### Mail app

**Mail app version:** 1.11.1

**Mailserver or service:** not relevant

### Server configuration

**Operating system**: Debian 10

**Web server:** Apache

**Database:** MariaDB

**PHP version:** 7.3
**Nextcloud Version:** 22.2.3

#### Client configuration
**Browser:** Firefox 95.0 64bits

**Operating system:** Windows 10

**Comment by ChristophWurst** [comment]
The mailbox icons on the left should also switch to white.

**Comment by GretaD** [comment]
It is shown correctly for me

![darkicon](https://user-images.githubusercontent.com/12728974/146365630-71fcb917-e0b0-425e-a0e3-238b3df04816.png)

**Comment by ChristophWurst** [comment]
> 1.11.1

Could you try with .4?

**Comment by StCyr** [comment]
You're right: it's solved in 1.11.4.

Thanks Christoph
