### ISSUE TITLE
Email content iframe is not resizing properly due to script being mixed content

### ISSUE THREAD

**Issue by DerpgonCz** [nextcloud/mail#5863]
### Expected behavior
- The whole e-mail content is shown.
- The e-mail message content iFrame is contacted by a javascript script on the current page to determine it's inner size.
- Script URL in the iFrame is generated with `https` schema because it is forced on NextCloud via ENV variable `OVERWRITEPROTOCOL=https`.
- The e-mail renders correctly when opening the iFrame URL in a new standalone tab.

### Actual behavior

- ❌ The e-mail content window (an iFrame) is very small and the e-mail is barely readable.
- ❌ The javascript script tries to contact the script inside the iFrame but fails.
- ❌ The script in iFrame is loaded via `http`.
- ✅ The e-mail renders correctly when opened in a standalone tab. The script loads correctly over `https`.

### Mail app

**Mail app version:** 1.11.4

**Mailserver or service:** IMAP

### Server configuration

**Operating system**: Unknown (using Docker)

**Web server:** Apache (bundled with Docker image)

**Reverse proxy:** Traefik

**Database:** MySQL

**PHP version:** 7.4.16

**Nextcloud Version:** 21.0.1

#### Client configuration
**Browser:** Google Chrome 92.0.4515.159

**Operating system:** Manjaro (Arch Linux)

**Comment by GretaD** [comment]
Hello @DerpgonCz,
Can you please send a screenshot to have a better view what is wrong and how small is the content part. Can you also check if you have any error on your nextcloud log, or web console that you can share here?

**Comment by DerpgonCz** [comment]
Hello @GretaD 
Thanks for answering, it seems like when vising from a different computer entirely, the page now seems to work properly. It seems like it was a caused by cache - I am not sure how, when I tried restarting the server and clearing browser cache via devtools.

Sorry for wasting your time guys 👍
