### ISSUE TITLE
Open mail in right with but wrong height

### ISSUE THREAD

**Issue by Bajotaz** [nextcloud/mail#5868]
### Expected behavior
open mail in acceptable size

### Actual behavior
open mail with width ok but height only shows 6 rows of text 

### Mail app
Nextcloud mail app

**Mail app version:** (see apps admin page, e.g. 0.5.3)
1.11.4

**Mailserver or service:** (e.g. Outlook, Yahoo, Gmail, Exchange,...)
Gmail, Yahoo, Hotmail

### Server configuration

**Operating system**: (e.g. Debian 8)
Debian 11

**Web server:** (e.g. Apache, Nginx,...)
Apache2

**Database:** (e.g. MariaDB, SQLite or PostgreSQL)
MariaDB

**PHP version:** (e.g. 7.0)
7.4.25

**Nextcloud Version:** (see admin page, e.g. 13.0.2)
22.2.3

#### Client configuration
**Browser:** (e.g. Firefox 48)
Brave Version 1.33.106 Chromium: 96.0.4664.110 (Officiell version) (64 bitar)

**Operating system:** (e.g. Arch Linux)
Windows 10, fully updated -17th december 2021

Attached screenshot in dark mode and standard
![Skärmbild (1)](https://user-images.githubusercontent.com/51438474/146462831-0253873b-3c80-405b-bba5-29d7f14a8e05.png)
![Skärmbild (2)](https://user-images.githubusercontent.com/51438474/146462882-4c54511e-6cfe-47d5-ab02-dd25a8ac5440.png)

**Comment by GretaD** [comment]
I cannot reproduce this with any of the html messages i have. Can you please send this email to me at greta@nextcloud.com as .eml?
Thank you,

**Comment by Bajotaz** [comment]
> I cannot reproduce this with any of the html messages i have. Can you please send this email to me at [greta@nextcloud.com](mailto:greta@nextcloud.com) as .eml? Thank you,

mail sent now from bajotaz@gmail.com with this thread url as subject

**Comment by GretaD** [comment]
ok, its weird that you see that, because i tested with what you sent me and i cannot reproduce, the message is shown correctly.

I also see that the fixup for this problem is also backported on v22: https://github.com/nextcloud/mail/pull/5567
So you're not suppose to have this problem. Can you please make sure its not a cache problem? Also thanks for sending the mail :)

**Comment by Bajotaz** [comment]
After awesome help from GretaD (Thank you!) and some digging around i found that the fault is related to my Brave browser.
Clearing Braves caches and history has not resolved issue, will continue to investegate.
