### ISSUE TITLE
cannot download to NC after 0.7.4 update

### ISSUE THREAD

**Issue by laurentiu2** [nextcloud/mail#588]
### Steps to reproduce
1.update to latest version 0.7.4
2.open Mail, read messages, etc
3.try to download attachment directly to NC

### Expected behaviour
save attachment to Files

### Actual behaviour
got the message 'Attachment saved to Files'  but no download
no error in logs

### Mail app

**Mail app version:** 0.7.4

**Mailserver or service:** Hetzner - DE,  mail.your-server.de

**Transport security - IMAP:** TLS

**Transport security - SMTP:** TLS

**Number of accounts:** 1

**Mail app version build date:** (only if you are using a Nightly Build)

### Server configuration

**Operating system**: Ubuntu 1604 xenial

**Web server:** apache

**Database:** MariaDB

**PHP version:** 7.1

**Version:** 12.0.3

**Updated from an older version or fresh install:** fresh

**List of activated apps:**
<details>
```
Enabled:
  - activity: 2.5.2
  - bruteforcesettings: 1.0.2
  - calendar: 1.5.6
  - comments: 1.2.0
  - dav: 1.3.0
  - encryption: 1.6.0
  - external: 2.0.3
  - federatedfilesharing: 1.2.0
  - federation: 1.2.0
  - files: 1.7.2
  - files_clipboard: 0.6.4
  - files_pdfviewer: 1.1.1
  - files_sharing: 1.4.0
  - files_texteditor: 2.4.1
  - files_trashbin: 1.2.0
  - files_versions: 1.5.0
  - files_videoplayer: 1.1.0
  - firstrunwizard: 2.1
  - gallery: 17.0.0
  - logreader: 2.0.0
  - lookup_server_connector: 1.0.0
  - mail: 0.7.4
  - metadata: 0.6.0
  - nextcloud_announcements: 1.1
  - notifications: 2.0.0
  - oauth2: 1.0.5
  - passman: 2.1.4
  - password_policy: 1.2.2
  - provisioning_api: 1.2.0
  - quota_warning: 1.1.1
  - ransomware_protection: 1.0.5
  - serverinfo: 1.2.0
  - sharebymail: 1.2.0
  - survey_client: 1.0.0
  - systemtags: 1.2.0
  - tasks: 0.9.5
  - theming: 1.3.0
  - twofactor_backupcodes: 1.1.1
  - updatenotification: 1.2.0
  - workflowengine: 1.2.0

```

**The content of config/config.php:**

<details>
```
{
    "system": {
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "*"
        ],
        "datadirectory": "\/var\/lib\/nextcloud\/data",
        "overwrite.cli.url": "http:\/\/localhost",
        "dbtype": "mysql",
        "version": "12.0.3.3",
        "dbname": "nextcloud",
        "dbhost": "localhost",
        "dbport": "",
        "dbtableprefix": "oc_",
        "mysql.utf8mb4": true,
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "installed": true,
        "instanceid": "ocsLI9gDP9Cc",
        "memcache.local": "\\OC\\Memcache\\Redis",
        "redis": {
            "dbindex": "0",
            "host": "localhost",
            "port": "6379",
            "timeout": "1.5"
        },
        "maintenance": false,
        "theme": "",
        "loglevel": 0,
        "updater.release.channel": "stable",
        "mail_smtpmode": "smtp",
        "mail_smtpauthtype": "LOGIN",
        "mail_from_address": "info",
        "mail_domain": "iscan.pro",
        "mail_smtpauth": 1,
        "mail_smtphost": "mail.your-server.de",
        "mail_smtpport": "465",
        "mail_smtpname": "***REMOVED SENSITIVE VALUE***",
        "mail_smtppassword": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpsecure": "ssl"
    }
...

#### Client configuration
**Browser:** Firefox 56.0.2 

**Operating system:** MacOS High Sierra

#### Logs
##### Web server error log
```
[Wed Nov 01 06:25:04.132860 2017] [ssl:warn] [pid 1185] AH01909: 2a01:4f8:c0c:37df::2:443:0 server certificate does NOT include an ID which matches the server name
[Wed Nov 01 06:25:04.133634 2017] [mpm_prefork:notice] [pid 1185] AH00163: Apache/2.4.18 (Ubuntu) OpenSSL/1.0.2g configured -- resuming normal operations
[Wed Nov 01 06:25:04.133645 2017] [core:notice] [pid 1185] AH00094: Command line: '/usr/sbin/apache2'
```

##### Server log (data/nextcloud.log)
<details>
```
{"reqId":"J6pJJ7t22UYzzTGfX1Sd","level":0,"time":"2017-11-01T11:16:56+00:00","remoteAddr":"79.115.205.145","user":"offrc","app":"mail","method":"GET","url":"\/index.php\/apps\/mail\/api\/accounts\/3\/folders\/SU5CT1g%3D\/messages?filter=&cursor=1509116534","message":"loading messages of folder <SU5CT1g=>","userAgent":"Mozilla\/5.0 (Macintosh; Intel Mac OS X 10.13; rv:56.0) Gecko\/20100101 Firefox\/56.0","version":"12.0.3.3"}
{"reqId":"UstNxK0KkNJQ6xE6F1V1","level":0,"time":"2017-11-01T11:16:56+00:00","remoteAddr":"79.115.205.145","user":"offrc","app":"mail","method":"GET","url":"\/index.php\/apps\/mail\/api\/accounts\/3\/folders\/SU5CT1g%3D\/messages?filter=&cursor=1509116534","message":"loading messages of folder <SU5CT1g=>","userAgent":"Mozilla\/5.0 (Macintosh; Intel Mac OS X 10.13; rv:56.0) Gecko\/20100101 Firefox\/56.0","version":"12.0.3.3"}
{"reqId":"tA1p96WFwgMmJq6QTaoJ","level":0,"time":"2017-11-01T11:17:00+00:00","remoteAddr":"79.115.205.145","user":"offrc","app":"mail","method":"GET","url":"\/index.php\/apps\/mail\/api\/accounts\/3\/folders\/SU5CT1g%3D\/messages?filter=&cursor=1509116534","message":"loading messages of folder <SU5CT1g=>","userAgent":"Mozilla\/5.0 (Macintosh; Intel Mac OS X 10.13; rv:56.0) Gecko\/20100101 Firefox\/56.0","version":"12.0.3.3"}
{"reqId":"04MQVahfuja4V9sp2MKa","level":0,"time":"2017-11-01T11:17:01+00:00","remoteAddr":"79.115.205.145","user":"offrc","app":"mail","method":"GET","url":"\/index.php\/apps\/mail\/api\/accounts\/3\/folders\/SU5CT1g%3D\/messages?filter=&cursor=1509116534","message":"loading messages of folder <SU5CT1g=>","userAgent":"Mozilla\/5.0 (Macintosh; Intel Mac OS X 10.13; rv:56.0) Gecko\/20100101 Firefox\/56.0","version":"12.0.3.3"}
{"reqId":"PCVMyGDUAJ8AVh4xmL2r","level":3,"time":"2017-11-01T11:17:03+00:00","remoteAddr":"79.115.205.145","user":"offrc","app":"index","method":"GET","url":"\/index.php\/apps\/mail\/api\/accounts\/3\/folders\/SU5CT1g%3D\/messages\/17","message":"Exception: {\"Exception\":\"Horde_Imap_Client_Exception\",\"Message\":\"Mail server denied authentication.\",\"Code\":102,\"Trace\":\"#0 \\\/var\\\/www\\\/nextcloud\\\/apps\\\/mail\\\/vendor\\\/pear-pear.horde.org\\\/Horde_Imap_Client\\\/Horde\\\/Imap\\\/Client\\\/Base.php(833): Horde_Imap_Client_Socket->_login(*** sensitive parameters replaced ***)\\n#1 \\\/var\\\/www\\\/nextcloud\\\/apps\\\/mail\\\/lib\\\/Account.php(160): Horde_Imap_Client_Base->login(*** sensitive parameters replaced ***)\\n#2 \\\/var\\\/www\\\/nextcloud\\\/apps\\\/mail\\\/lib\\\/Account.php(320): OCA\\\\Mail\\\\Account->getImapConnection()\\n#3 \\\/var\\\/www\\\/nextcloud\\\/apps\\\/mail\\\/lib\\\/Controller\\\/MessagesController.php(168): OCA\\\\Mail\\\\Account->getMailbox('INBOX')\\n#4 \\\/var\\\/www\\\/nextcloud\\\/apps\\\/mail\\\/lib\\\/Controller\\\/MessagesController.php(201): OCA\\\\Mail\\\\Controller\\\\MessagesController->loadMessage(3, 'SU5CT1g=', '17')\\n#5 [internal function]: OCA\\\\Mail\\\\Controller\\\\MessagesController->show(3, 'SU5CT1g=', '17')\\n#6 \\\/var\\\/www\\\/nextcloud\\\/lib\\\/private\\\/AppFramework\\\/Http\\\/Dispatcher.php(160): call_user_func_array(Array, Array)\\n#7 \\\/var\\\/www\\\/nextcloud\\\/lib\\\/private\\\/AppFramework\\\/Http\\\/Dispatcher.php(90): OC\\\\AppFramework\\\\Http\\\\Dispatcher->executeController(Object(OCA\\\\Mail\\\\Controller\\\\MessagesController), 'show')\\n#8 \\\/var\\\/www\\\/nextcloud\\\/lib\\\/private\\\/AppFramework\\\/App.php(114): OC\\\\AppFramework\\\\Http\\\\Dispatcher->dispatch(Object(OCA\\\\Mail\\\\Controller\\\\MessagesController), 'show')\\n#9 \\\/var\\\/www\\\/nextcloud\\\/lib\\\/private\\\/AppFramework\\\/Routing\\\/RouteActionHandler.php(47): OC\\\\AppFramework\\\\App::main('OCA\\\\\\\\Mail\\\\\\\\Contro...', 'show', Object(OC\\\\AppFramework\\\\DependencyInjection\\\\DIContainer), Array)\\n#10 [internal function]: OC\\\\AppFramework\\\\Routing\\\\RouteActionHandler->__invoke(Array)\\n#11 \\\/var\\\/www\\\/nextcloud\\\/lib\\\/private\\\/Route\\\/Router.php(299): call_user_func(Object(OC\\\\AppFramework\\\\Routing\\\\RouteActionHandler), Array)\\n#12 \\\/var\\\/www\\\/nextcloud\\\/lib\\\/base.php(1004): OC\\\\Route\\\\Router->match('\\\/apps\\\/mail\\\/api\\\/...')\\n#13 \\\/var\\\/www\\\/nextcloud\\\/index.php(48): OC::handleRequest()\\n#14 {main}\",\"File\":\"\\\/var\\\/www\\\/nextcloud\\\/apps\\\/mail\\\/vendor\\\/pear-pear.horde.org\\\/Horde_Imap_Client\\\/Horde\\\/Imap\\\/Client\\\/Socket.php\",\"Line\":572}","userAgent":"Mozilla\/5.0 (Macintosh; Intel Mac OS X 10.13; rv:56.0) Gecko\/20100101 Firefox\/56.0","version":"12.0.3.3"}
{"reqId":"u5toU3mynCSzc392kwko","level":3,"time":"2017-11-01T11:17:06+00:00","remoteAddr":"79.115.205.145","user":"offrc","app":"index","method":"GET","url":"\/index.php\/apps\/mail\/api\/accounts\/3\/folders\/SU5CT1g%3D\/sync?syncToken=VTUyLFY1MDkxMDE4NjUsTTI0&uids%5B%5D=51&uids%5B%5D=47&uids%5B%5D=46&uids%5B%5D=45&uids%5B%5D=44&uids%5B%5D=43&uids%5B%5D=42&uids%5B%5D=41&uids%5B%5D=37&uids%5B%5D=36&uids%5B%5D=33&uids%5B%5D=31&uids%5B%5D=30&uids%5B%5D=25&uids%5B%5D=21&uids%5B%5D=19&uids%5B%5D=18&uids%5B%5D=17&uids%5B%5D=15&uids%5B%5D=14","message":"Exception: {\"Exception\":\"Horde_Imap_Client_Exception\",\"Message\":\"Mail server denied authentication.\",\"Code\":102,\"Trace\":\"#0 \\\/var\\\/www\\\/nextcloud\\\/apps\\\/mail\\\/vendor\\\/pear-pear.horde.org\\\/Horde_Imap_Client\\\/Horde\\\/Imap\\\/Client\\\/Base.php(833): Horde_Imap_Client_Socket->_login(*** sensitive parameters replaced ***)\\n#1 \\\/var\\\/www\\\/nextcloud\\\/apps\\\/mail\\\/vendor\\\/pear-pear.horde.org\\\/Horde_Imap_Client\\\/Horde\\\/Imap\\\/Client\\\/Base.php(1593): Horde_Imap_Client_Base->login(*** sensitive parameters replaced ***)\\n#2 \\\/var\\\/www\\\/nextcloud\\\/apps\\\/mail\\\/vendor\\\/pear-pear.horde.org\\\/Horde_Imap_Client\\\/Horde\\\/Imap\\\/Client\\\/Base.php(4033): Horde_Imap_Client_Base->status(Object(Horde_Imap_Client_Mailbox), 8713)\\n#3 \\\/var\\\/www\\\/nextcloud\\\/apps\\\/mail\\\/vendor\\\/pear-pear.horde.org\\\/Horde_Imap_Client\\\/Horde\\\/Imap\\\/Client\\\/Base.php(3627): Horde_Imap_Client_Base->_syncStatus(Object(Horde_Imap_Client_Mailbox))\\n#4 \\\/var\\\/www\\\/nextcloud\\\/apps\\\/mail\\\/lib\\\/IMAP\\\/Sync\\\/Synchronizer.php(57): Horde_Imap_Client_Base->sync(Object(Horde_Imap_Client_Mailbox), 'U52,V509101865,...', Array)\\n#5 \\\/var\\\/www\\\/nextcloud\\\/apps\\\/mail\\\/lib\\\/Service\\\/MailManager.php(86): OCA\\\\Mail\\\\IMAP\\\\Sync\\\\Synchronizer->sync(Object(Horde_Imap_Client_Socket), Object(OCA\\\\Mail\\\\IMAP\\\\Sync\\\\Request))\\n#6 \\\/var\\\/www\\\/nextcloud\\\/apps\\\/mail\\\/lib\\\/Controller\\\/FoldersController.php(95): OCA\\\\Mail\\\\Service\\\\MailManager->syncMessages(Object(OCA\\\\Mail\\\\Account), Object(OCA\\\\Mail\\\\IMAP\\\\Sync\\\\Request))\\n#7 [internal function]: OCA\\\\Mail\\\\Controller\\\\FoldersController->sync(3, 'SU5CT1g=', 'VTUyLFY1MDkxMDE...', Array)\\n#8 \\\/var\\\/www\\\/nextcloud\\\/lib\\\/private\\\/AppFramework\\\/Http\\\/Dispatcher.php(160): call_user_func_array(Array, Array)\\n#9 \\\/var\\\/www\\\/nextcloud\\\/lib\\\/private\\\/AppFramework\\\/Http\\\/Dispatcher.php(90): OC\\\\AppFramework\\\\Http\\\\Dispatcher->executeController(Object(OCA\\\\Mail\\\\Controller\\\\FoldersController), 'sync')\\n#10 \\\/var\\\/www\\\/nextcloud\\\/lib\\\/private\\\/AppFramework\\\/App.php(114): OC\\\\AppFramework\\\\Http\\\\Dispatcher->dispatch(Object(OCA\\\\Mail\\\\Controller\\\\FoldersController), 'sync')\\n#11 \\\/var\\\/www\\\/nextcloud\\\/lib\\\/private\\\/AppFramework\\\/Routing\\\/RouteActionHandler.php(47): OC\\\\AppFramework\\\\App::main('OCA\\\\\\\\Mail\\\\\\\\Contro...', 'sync', Object(OC\\\\AppFramework\\\\DependencyInjection\\\\DIContainer), Array)\\n#12 [internal function]: OC\\\\AppFramework\\\\Routing\\\\RouteActionHandler->__invoke(Array)\\n#13 \\\/var\\\/www\\\/nextcloud\\\/lib\\\/private\\\/Route\\\/Router.php(299): call_user_func(Object(OC\\\\AppFramework\\\\Routing\\\\RouteActionHandler), Array)\\n#14 \\\/var\\\/www\\\/nextcloud\\\/lib\\\/base.php(1004): OC\\\\Route\\\\Router->match('\\\/apps\\\/mail\\\/api\\\/...')\\n#15 \\\/var\\\/www\\\/nextcloud\\\/index.php(48): OC::handleRequest()\\n#16 {main}\",\"File\":\"\\\/var\\\/www\\\/nextcloud\\\/apps\\\/mail\\\/vendor\\\/pear-pear.horde.org\\\/Horde_Imap_Client\\\/Horde\\\/Imap\\\/Client\\\/Socket.php\",\"Line\":572}","userAgent":"Mozilla\/5.0 (Macintosh; Intel Mac OS X 10.13; rv:56.0) Gecko\/20100101 Firefox\/56.0","version":"12.0.3.3"}
{"reqId":"58rSVls9xlgCAgQfCtXa","level":0,"time":"2017-11-01T11:17:19+00:00","remoteAddr":"79.115.205.145","user":"offrc","app":"mail","method":"GET","url":"\/index.php\/apps\/mail\/api\/accounts\/3\/folders\/SU5CT1g%3D\/messages?filter=&cursor=1509116534","message":"loading messages of folder <SU5CT1g=>","userAgent":"Mozilla\/5.0 (Macintosh; Intel Mac OS X 10.13; rv:56.0) Gecko\/20100101 Firefox\/56.0","version":"12.0.3.3"}
{"reqId":"ejMA9gOFnRbTaLDsd4Ca","level":3,"time":"2017-11-01T11:17:22+00:00","remoteAddr":"79.115.205.145","user":"offrc","app":"PHP","method":"GET","url":"\/index.php\/apps\/mail\/api\/accounts\/3\/folders\/SU5CT1g=\/messages\/17\/html","message":"Attempted to retrieve non-existent variable CurrentAttr at \/var\/www\/nextcloud\/apps\/mail\/vendor\/ezyang\/htmlpurifier\/library\/HTMLPurifier\/Context.php#48","userAgent":"Mozilla\/5.0 (Macintosh; Intel Mac OS X 10.13; rv:56.0) Gecko\/20100101 Firefox\/56.0","version":"12.0.3.3"}
{"reqId":"ejMA9gOFnRbTaLDsd4Ca","level":3,"time":"2017-11-01T11:17:22+00:00","remoteAddr":"79.115.205.145","user":"offrc","app":"PHP","method":"GET","url":"\/index.php\/apps\/mail\/api\/accounts\/3\/folders\/SU5CT1g=\/messages\/17\/html","message":"Attempted to retrieve non-existent variable CurrentAttr at \/var\/www\/nextcloud\/apps\/mail\/vendor\/ezyang\/htmlpurifier\/library\/HTMLPurifier\/Context.php#48","userAgent":"Mozilla\/5.0 (Macintosh; Intel Mac OS X 10.13; rv:56.0) Gecko\/20100101 Firefox\/56.0","version":"12.0.3.3"}

```
</details>

##### Horde IMAP log (data/horde_imap.log)
<details>
```
Insert your horde IMAP log here, see https://github.com/nextcloud/mail#debug-mode
```
</details>

##### Horde SMTP log (data/horde_smtp.log)
<details>
```
Insert your horde SMTP log here, see https://github.com/nextcloud/mail#debug-mode
```
</details>

##### Browser log
<details>
```
Insert your browser log here, this could for example include:

a) The javascript console log
b) The network log 
c) ...
```
</details>

**Comment by CannyFoxx** [comment]
I confirm this issue. I just tried to upgrade to 0.7.4 through web interface and received next error:

    Doctrine\DBAL\Exception\InvalidFieldNameException: An exception occurred while executing 'SELECT min_value, increment_by FROM "oc_comments_id_seq"': SQLSTATE[42703]: Undefined column: 7 ERROR: column "min_value" does not exist LINE 1: SELECT min_value, increment_by FROM "oc_comments_id_seq"

**Comment by ppascher** [comment]
I can confirm this. Using the option "Save to Files" on an attachment brings up the directory chooser and clicking on "Choose" sends a POST request which gets a "302 - Found" return value.
No errors in web server logs, browser logs or nextcloud logs. But the file is nowhere to be found under "Files" App.
The "Download Attachment" link works fine.

### Mail app

**Mail app version:** 0.7.4

**Mailserver or service:** Postfix 3.2.3

**Transport security - IMAP:** TLS

**Transport security - SMTP:** TLS

**Number of accounts:** 1

### Server configuration

**Operating system**: CentOS7.4

**Web server:**nginx

**Database:**PostgreSQL 10

**PHP version:**7.1

**Version:** 12.0.3

**Updated from an older version or fresh install:** updated

**List of activated apps:**
<details>
<summary>App Details</summary>

```
Enabled:
  - activity: 2.5.2
  - bruteforcesettings: 1.0.2
  - calendar: 1.5.6
  - comments: 1.2.0
  - contacts: 2.0.1
  - dav: 1.3.0
  - federatedfilesharing: 1.2.0
  - files: 1.7.2
  - files_pdfviewer: 1.1.1
  - files_sharing: 1.4.0
  - files_texteditor: 2.4.1
  - files_trashbin: 1.2.0
  - files_versions: 1.5.0
  - files_videoplayer: 1.1.0
  - firstrunwizard: 2.1
  - gallery: 17.0.0
  - logreader: 2.0.0
  - lookup_server_connector: 1.0.0
  - mail: 0.7.4
  - nextcloud_announcements: 1.1
  - notifications: 2.0.0
  - oauth2: 1.0.5
  - passman: 2.1.4
  - password_policy: 1.2.2
  - provisioning_api: 1.2.0
  - serverinfo: 1.2.0
  - sharebymail: 1.2.0
  - survey_client: 1.0.0
  - systemtags: 1.2.0
  - theming: 1.3.0
  - twofactor_backupcodes: 1.1.1
  - twofactor_totp: 1.3.1
  - updatenotification: 1.2.0
  - user_ldap: 1.2.1
  - user_saml: 1.4.0
  - workflowengine: 1.2.0
Disabled:
  - admin_audit
  - encryption
  - federation
  - files_external
  - user_external
```
</details>

**The content of config/config.php:**
<details>
<summary>config.php</summary>

```
{
    "system": {
        "version": "12.0.3.3",
        "instanceid": "ochej9bt9h8e",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "nextcloud01.ipa.mydomain.com",
            "proxy01.ipa.mydomain.com",
            "next.mydomain.com",
            "mydomain.com"
        ],
        "knowledgebaseenabled": true,
        "datadirectory": "\/mnt\/freenas\/data\/nextcloud\/data",
        "overwriteprotocol": "https",
        "forcessl": true,
        "overwrite.cli.url": "https:\/\/nextcloud01.ipa.mydomain.com",
        "dbtype": "pgsql",
        "dbname": "nextcloud",
        "dbhost": "postgresql01.ipa.mydomain.com",
        "dbport": "",
        "dbtableprefix": "oc_",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "memcache.local": "\\OC\\Memcache\\APCu",
        "filelocking.enabled": "true",
        "memcache.locking": "\\OC\\Memcache\\Redis",
        "redis": {
            "host": "\/var\/run\/redis\/redis.sock",
            "port": 0,
            "timeout": 0
        },
        "installed": true,
        "auth.bruteforce.protection.enabled": true,
        "mail_smtpmode": "smtp",
        "mail_smtpsecure": "tls",
        "mail_from_address": "nextcloud",
        "mail_domain": "mydomain.com",
        "mail_smtpauthtype": "PLAIN",
        "mail_smtpauth": 1,
        "mail_smtphost": "mail.mydomain.com",
        "mail_smtpport": "587",
        "mail_smtptimeout": "30",
        "mail_smtpname": "***REMOVED SENSITIVE VALUE***",
        "mail_smtppassword": "***REMOVED SENSITIVE VALUE***",
        "cipher": "AES-256-CFB",
        "enable_avatars": true,
        "has_internet_connection": true,
        "check_for_working_webdav": true,
        "check_for_working_wellknown_setup": true,
        "check_for_working_htaccess": true,
        "ldapIgnoreNamingRules": false,
        "ldapUserCleanupInterval": 51,
        "ldapProviderFactory": "\\OCA\\User_LDAP\\LDAPProviderFactory",
        "enable_previews": true,
        "preview_max_x": 2048,
        "preview_max_y": 2048,
        "preview_max_scale_factor": 1,
        "preview_max_filesize_image": 50,
        "preview_libreoffice_path": "\/usr\/bin\/libreoffice",
        "preview_office_cl_parameters": " --headless --nologo --nofirststartwizard --invisible --norestore --convert-to pdf --outdir ",
        "enabledPreviewProviders": [
            "OC\\Preview\\PNG",
            "OC\\Preview\\JPEG",
            "OC\\Preview\\GIF",
            "OC\\Preview\\BMP",
            "OC\\Preview\\XBitmap",
            "OC\\Preview\\MP3",
            "OC\\Preview\\TXT"
        ],
        "hashingCost": 12,
        "blacklisted_files": [
            ".htaccess"
        ],
        "forwarded_for_headers": [
            "HTTP_X_FORWARDED",
            "HTTP_FORWARDED_FOR"
        ],
        "trusted_proxies": [
            "10.x.x.x",
            "fe80::xxxx:xxxx:xxxx:xxxx"
        ],
        "htaccess.RewriteBase": "\/",
        "appstoreenabled": true,
        "appcodechecker": true,
        "updatechecker": true,
        "updater.release.channel": "stable",
        "logfile": "\/var\/log\/nextcloud\/nextcloud.log",
        "logdateformat": "Y-m-d H:i:s",
        "logtimezone": "Europe\/Berlin",
        "log_query": false,
        "cron_log": true,
        "log_rotate_size": "10485760",
        "loglevel": 2,
        "filesystem_check_changes": 1,
        "cache_path": "\/srv\/www\/cache\/",
        "theme": "",
        "maintenance": false
    }
}
```
</details>

#### Client configuration
**Browser:**Firefox 58 (Nightly)

**Operating system:** (Arch)

#### Logs
##### Web server error log
```
1518 10.x.x.x - - [31/Oct/2017:23:09:03 +0100] "GET /apps/mail/api/accounts/1/folders/SU5CT1g%3D/messages?ids=6880%2C6846%2C6827%2C6826%2C6757%2C6756%2C6657 HTTP/1.1" 200 9592 "-" "Mozilla/5.0 (X11; Linux x86_64; rv:58.0) Gecko/201     00101 Firefox/58.0" "10.20.30.40"
1519 10.x.x.x - - [31/Oct/2017:23:09:05 +0100] "PROPFIND /remote.php/webdav/ HTTP/1.1" 207 1351 "-" "Mozilla/5.0 (X11; Linux x86_64; rv:58.0) Gecko/20100101 Firefox/58.0" "10.20.30.40"
1520 10.x.x.x - - [31/Oct/2017:23:09:07 +0100] "PROPFIND /remote.php/webdav/test HTTP/1.1" 207 771 "-" "Mozilla/5.0 (X11; Linux x86_64; rv:58.0) Gecko/20100101 Firefox/58.0" "10.20.30.40"
1521 10.x.x.x - - [31/Oct/2017:23:09:08 +0100] "POST /apps/mail/accounts/1/folders/SU5CT1g%3D/messages/6850/attachment/2 HTTP/1.1" 302 5 "-" "Mozilla/5.0 (X11; Linux x86_64; rv:58.0) Gecko/20100101 Firefox/58.0" "10.20.30.40"
```

**Comment by ChristophWurst** [comment]
> I can confirm this. Using the option "Save to Files" on an attachment brings up the directory chooser and clicking on "Choose" sends a POST request which gets a "302 - Found" return value.
> No errors in web server logs, browser logs or nextcloud logs. But the file is nowhere to be found under "Files" App.
> The "Download Attachment" link works fine.

Can you tell me the URL it's requesting? That would help, thanks.

**Comment by laurentiu2** [comment]
I have updated the post with missing info. Don't have horde_imap.log and horde_smtp.log.

**Comment by ppascher** [comment]
Hello Christoph,

nginx access log: 
POST /apps/mail/accounts/1/folders/SU5CT1g%3D/messages/6850/attachment/2

firefox network tab:
url: https://mydomain.com/apps/mail/accounts/1/folders/SU5CT1g=/messages/6850/attachment/2
params: targetPath:  /test

Also: there is a little popup saying "Attachment saved to files" at the top center.

**Comment by ChristophWurst** [comment]
This is a regression introduced by #558. https://github.com/nextcloud/mail/blob/e21e067761c79e29270482df26dd52e955af4673/js/service/attachmentservice.js#L47 lacking the `api/` prefix.

This is easy to fix and would make a great first contribution to this project. Anybody up to submitting a pull request? 😉

**Comment by ppascher** [comment]
I gave it a try.  😮

**Comment by laurentiu2** [comment]
Doesn't work for me. I manually modified the attachmentservice.js, restarted everything..
Should I do something else?

**Comment by ChristophWurst** [comment]
> Doesn't work for me. I manually modified the attachmentservice.js, restarted everything..
> Should I do something else?

The change won't have any effect unless webpack is run to generate a new `js/build/build.js`. See https://github.com/nextcloud/mail#development-setup for more info.

**Comment by ChristophWurst** [comment]
Fixed by https://github.com/nextcloud/mail/pull/592. Thanks @ppascher 😉
