### ISSUE TITLE
Create database structure and REST API for an outbox

### ISSUE THREAD

**Issue by ChristophWurst** [nextcloud/mail#5885]
1. `mail_local_mailbox`
  * `type`: int, allows us to distinguish between outboxes and local draft mailboxes
  * `account_id`: foreign key to `mail_accounts`
  * `send_at`: nullable timestamp
  * `text`: the email as RFC822 message (or separate columns for to, cc, bcc, subject, contents and attachments as another 1:n table)
2. QB mapper for the table(s)
3. A service for handles access the outbox
4. REST resource at `/apps/mail/api/outbox`
  * `POST /apps/mail/api/outbox` to enqueue a message
  * `GET /apps/mail/api/outbox` returns the outbox contents
  * `GET /apps/mail/api/outbox/{id}` returns the outbox message by id
  * `DELETE /apps/mail/api/outbox/{id}` deletes a specific message
  * `POST /apps/mail/api/outbox/{id}` sends a specific message
  * `PUT /apps/mail/api/outbox/{id}` updates the message

Whenever a Mail account is deleted, we'll have to wipe the outbox messages that are still to be sent. Otherwise the sending will run into a null account.

**Comment by miaulalala** [comment]
Should I also add a type here, as we've discussed in December re: Draft Handling?

**Comment by ChristophWurst** [comment]
Done via https://github.com/nextcloud/mail/pull/6052 and https://github.com/nextcloud/mail/pull/6030
