### ISSUE TITLE
Create frontend for an outbox

### ISSUE THREAD

**Issue by ChristophWurst** [nextcloud/mail#5887]
Create the frontend for the outbox mailbox that shows unsent emails
  + Show a mailbox entry right below *Priority inbox* and *All inboxes*
    + Show counter on the outbox
  + Make the outbox a routable page
    + List messages of the outbox
    + Actions
      + Offer to delete a message
      + Offer to send a message now
    + When clicked, open the message composer so the user can resume editing

**Comment by ChristophWurst** [comment]
@jancborchardt @nimishavijay the outbox will *look* similar to any regular mailbox, but internally they are quite different. Therefore we'll have to reimplement some of the logic that shows a message.

However, if I'm looking at other solutions with scheduled sending I see that they don't even "preview" the message but when you click it it is put back into the message editor, so that you can still change the message.

So I'm wondering if it's okay to omit the message preview and do the same. That means we'll have the middle column as outbox contents so all currently enqueued messages are listed. And the right pane would stay empty. When the user clicks one of the messages, the composer modal opens.

**Comment by jancborchardt** [comment]
@ChristophWurst that seems fine, yes.

Actually, if it's possible what might be even nicer is if there is no extra "Outbox" category but instead the mails which are about to be sent are just on top of "Sent", in color-text-maxcontrast. Cause at any point there's never really many mails (mostly none) in the outbox anyway, so it would be a bit useless.

**Comment by ChristophWurst** [comment]
Thank you for sharing your ideas. I'd say we should probably split this off into another ticket. Right now the dedicated outbox is the most straight forward solution from a technical perspective, and I've compared it with gmail, outlook and apple mail and they also handle it like this.
