### ISSUE TITLE
Empty message saved as draft

### ISSUE THREAD

**Issue by ChristophWurst** [nextcloud/mail#5908]
## How to reproduce

1) Set up an account
2) Open the composer

### Expected behavior

Nothing happens. Because I haven't put in any information. No recipient. No subject. No content. No attachments.

### Actual behavior

A draft is saved. Or at least so the UI tells me.

![Bildschirmfoto von 2021-12-27 11-20-21](https://user-images.githubusercontent.com/1374172/147462369-3987ad58-7baf-4963-8807-422c2572b903.png)

### Mail app

**Mail app version:** v1.12

**Comment by peppinoita** [comment]
Sorry if I Bump this issue, I am facing the same.

**Comment by ChristophWurst** [comment]
![Bildschirmfoto vom 2022-04-07 21-05-14](https://user-images.githubusercontent.com/1374172/162277964-0e9f004e-66a5-487b-8c31-2b9df2e7c5e3.png)

this still happens

**Comment by JuliaKirschenheuter** [comment]
Well, i have fixed a part of a bug and then saw, that "saving"-process of a Draft will not be triggered, if some **attachments** / **cc** / **bcc** / **to** will be somehow changed. It is a bit tricky to fix, will need a bit more time.
