### ISSUE TITLE
Feature Request Delete E-Mails Button

### ISSUE THREAD

**Issue by MrLoverLoverMMMM** [nextcloud/mail#5912]
Hello!
It would be very helpful if it would be possible to add a button to each mailbox (no matter if inbox, sent,..) to delete all emails at once.

Alternatively, a Button Clean Cache would also be useful ==> If I delete all emails from the server from all inboxes, they should also disappear in Nextcloud Mail (currently only happens with the inbox).

In addition, I would like to be able to select / deselect multiple emails at once and then delete the selected emails at once.

**Comment by ChristophWurst** [comment]
I'd appreciate if you could use the issue template from https://github.com/nextcloud/mail/issues/new?assignees=&labels=enhancement%2C+0.+to+triage&template=feature_request.md&title= and reformat your ticket.

**Comment by ChristophWurst** [comment]
And please use the search before opening tickets. This is a duplicate https://github.com/nextcloud/mail/issues/5858.

**Comment by MrLoverLoverMMMM** [comment]
OK, Thank you very much
