### ISSUE TITLE
Hasnoattachment on emails + HTML Signature

### ISSUE THREAD

**Issue by JordanDIG** [nextcloud/mail#5917]
Hello,

The mention "Hasnoattachment" appears on all my mails. I would like to hide it.

And second problem when I add my signature in HTML in the signature tab when sending an email the text is not converted to HTML which just returns the raw text of my signature.

**Comment by JordanDIG** [comment]
I would also like to disable the grouping of messages, i.e. not to form a kind of discussion with the old replies to my mails, but I cannot find the option

**Comment by ChristophWurst** [comment]
Assuming you went through https://github.com/nextcloud/mail/issues/new/choose when you created the ticket you should have seen our templates.

https://help.nextcloud.com/c/apps/mail/35 is for support and questions.
