### ISSUE TITLE
Default tags are not editable

### ISSUE THREAD

**Issue by miaulalala** [nextcloud/mail#5920]
Make the default tags editable so users can set their own descriptions and colours.

If you want to be super fancy, also offer a reset option to "Reset To Default".

**Comment by GretaD** [comment]
actually we did this on purpose when we added the edit option for the other tags. Why do you think this is helpful? They can always add a new tag.

I think we removed the edit option from default ones to make sure it will be the same in all mail clients.

**Comment by miaulalala** [comment]
Please see the first linked issue :)

**Comment by miaulalala** [comment]
Re: `$label1` (Important) - this plays more into the mail system than any other tag and is special. Priority Mailbox and classification runs into this. Gmail treats the label the same way, it's important used for a specific purpose. So the suggestion by @GretaD is not to edit it and I agree 100%.
