### ISSUE TITLE
Passwordless users cannot provision accounts

### ISSUE THREAD

**Issue by sevmonster** [nextcloud/mail#5933]
Attempting to provision accounts (either via first visit to `apps/mail` where the user gets a 500 error, or via mass provisioning) chokes when trying to set password [here](https://github.com/nextcloud/mail/blob/d9f3cc1de93d70368fed5fe6613a6ca0043e59cc/lib/Http/Middleware/ProvisioningMiddleware.php#L75).

`PUT /apps/mail/api/settings/provisioning/all`
```
TypeError: OCA\Mail\Service\Provisioning\Manager::updatePassword(): Argument #2 ($password) must be of type string, null given, called in /var/lib/nextcloud/apps/mail/lib/Http/Middleware/ProvisioningMiddleware.php on line 75  in file '/var/lib/nextcloud/apps/mail/lib/Service/Provisioning/Manager.php' line 300

/var/lib/nextcloud/apps/mail/lib/Http/Middleware/ProvisioningMiddleware.php - line 75:
OCA\Mail\Service\Provisioning\Manager->updatePassword("*** sensiti ... *")

/usr/share/webapps/nextcloud/lib/private/AppFramework/Middleware/MiddlewareDispatcher.php - line 97:
OCA\Mail\Http\Middleware\ProvisioningMiddleware->beforeController()

/usr/share/webapps/nextcloud/lib/private/AppFramework/Http/Dispatcher.php - line 118:
OC\AppFramework\Middleware\MiddlewareDispatcher->beforeController()

/usr/share/webapps/nextcloud/lib/private/AppFramework/App.php - line 157:
OC\AppFramework\Http\Dispatcher->dispatch()

/usr/share/webapps/nextcloud/lib/private/Route/Router.php - line 302:
OC\AppFramework\App::main()

/usr/share/webapps/nextcloud/lib/base.php - line 1006:
OC\Route\Router->match()

/usr/share/webapps/nextcloud/index.php - line 36:
OC::handleRequest()
```

- Nextcloud Hub 23.0.0
- Alpine Linux edge (5.15.13-0-lts)
- PHP 8.0.14 (built: Dec 17 2021 20:46:56) ( NTS )
- mail: 1.11.5

I do not know if an issue should be opened under `server` or `user_saml` for this, or if any other backends have this issue.

**Comment by sevmonster** [comment]
Yes, I apologize if I neglected to say that.

----------------------------------------

*From: *Anna Larch ***@***.***>
*To: *nextcloud/mail ***@***.***>
*CC: *sev ***@***.***>; Author ***@***.***>
*Date: *Jan 13, 2022 04:55:53
*Subject: *Re: [nextcloud/mail] SAML users cannot provision accounts 
(Issue #5933)

**Comment by miaulalala** [comment]
No worries.

Since you're using it, what would you suggest should happen for passwordless accounts? I am not aware that IMAP offers passwordless signing, but I could be mistaken. I would be grateful to get some input about a suggested workflow for provisioning such accounts :)

**Comment by sevmonster** [comment]
> Since you're using it, what would you suggest should happen for passwordless accounts?

Ideally the user is prompted for an IMAP password (redirect to first time setup page with error message about password? or a new page?) to complete the sign-in process. At the very least, don't cause an error if there is no password to assign which prevents the user from utilizing the app.

>I am not aware that IMAP offers passwordless signing, but I could be mistaken.

Some server implementations offer alternative sign on methods to passwords, such as OAuth2/OIDC support in Dovecot. In the case of cloud providers, many (such as Microsoft 365) are moving away completely from "legacy" plaintext password logins—PLAIN, LOGIN, etc... they recommend HTTP SSO redirects, which are recognized by really any modern mail client, or app passwords if the former is not possible.

In my environment, for example, I have both Nextcloud and Dovecot set up for SSO, and authorization is automatic, so being signed in via SSO will allow you immediate access to either.

I understand this would likely be a less thsn trivial implementation, but even OAuth2 support would open the gates for most autentication and authorization frameworks. I would just be happy if it didn't generate an error so I and my users could use it at all, though.

**Comment by miaulalala** [comment]
Thanks for an excellent analysis of the situation. I'll see what we can do about this!

**Comment by pelzvieh** [comment]
Actually around line 75 there is already logic to cope with unavailable credentials. Only that the exception raised here is not one of the expected ones. I suggest to explicitly test for getPassword returning null and return immediately in this case (as does the existing catch clause).

**Comment by MohammedNoureldin** [comment]
I am not sure what the current status of this is. I am trying to use a mailserver that uses OAuth2 for authentication, but I still see no connections coming at all after provisioning the mail or when trying to access the mail app.

Is NextCloud supposed to forward the tokens or try to connect at all with the mail server for users logged in using OIDC?

In my Nextcloud log I still see:

ServiceException
IMAP error synchronizing account 4: No password provided.
Could not load account mailboxes: IMAP error synchronizing account 4: No password provided.

Is there anything special to be done for this to work?

**Comment by sevmonster** [comment]
Rather than try to get some kind of credential passing between my mail server and Nextcloud Mail, I added a `static` `passdb` to my Dovecot configuration and switched to the recently implemented master password feature; there should be an issue about it somewhere. However, at the time I was messing with it, there was a bug where users without passwords (yes the same issue here) caused an error that prevented the master password from beibg used at all. I had to take out some of the code to get it to not error out and use the provided master password, but after that it did work.

However, this was some months ago if I recall, so I am not sure if more recent versions have fixed this issue and the master password feature is more stable. I've since switched to [SnappyMail(https://snappymail.eu), and am not doing much with Nextcloud these days, so unfortunately I can't give a more recent update.

**Comment by MohammedNoureldin** [comment]
Thank you for your reply. It does not feel good to use master password when we already have OAuth2 tokens which only need to be properly forwarded. An official statement about this would be good.

**Comment by ChristophWurst** [comment]
As far as I can say provisioning doesn't work with oauth at the moment.

**Comment by MohammedNoureldin** [comment]
Thank you for your reply, @ChristophWurst. Good to know, because I though something is misconfigured from my side.

**Comment by nowheretobefound** [comment]
@ChristophWurst Are you aware of any other github issue tracking the progress of forwarding the Oauth2 tokens (from user_oidc app) ?

**Comment by ChristophWurst** [comment]
Dear @nowheretobefound, thank you for your message. I am not aware of any. You could try to search the Nextcloud Github organization for matching tickets, for example with https://github.com/search?q=org%3Anextcloud+oauth+oidc&type=issues.
