### ISSUE TITLE
Hide duplicate message

### ISSUE THREAD

**Issue by MeiKatz** [nextcloud/mail#5940]
### Feature Request

I have the "problem", that I get messages on my personal e-mail address and also from the mailing list, where my personal e-mail address is in. Therefore if anybody sends an e-mail message to my personal e-mail address and the mailing list address, I get the message twice. And currently NextCloud Mail also shows both message even so they have the identical content. Maybe there is a way to squash them together and only show one of the messages.

I think the duplicate contents could be detected by the `Message-Id` header or by dropping the `X-Original-To` and `Delivered-To` headers and hash the whole contents. If the hashes are equal, it is the same message. Only problem would be how the `show source` option should be changed, so that both messages are visible.

**Comment by ChristophWurst** [comment]
Is this still relevant?
