### ISSUE TITLE
Read E-Mail is not marked as read

### ISSUE THREAD

**Issue by davidpr78** [nextcloud/mail#5942]
When I open a new Mail an read it, it is still bold in the list (like not read).

Chrome Browser 97
Mail App 1.11.5
Nextcloud 22

**Comment by GretaD** [comment]
Hello,

I can reproduce the error on 1.11.5 but not on latest one. Can you please update to the latest one and see if persists. Meanwhile i will try to see why this happens on 1.11.5

**Comment by davidpr78** [comment]
Ok, thanks. In my Nextcloud 1.11.5 is the latest version. I will wait.

Best regards
David

Greta ***@***.***> schrieb am Mi., 12. Jan. 2022, 16:37:

**Comment by ChristophWurst** [comment]
@GretaD could you reproduce?

**Comment by miaulalala** [comment]
> @GretaD could you reproduce?

Not Greta, but I do find that this sometimes happens on c.nc.com.

**Comment by GretaD** [comment]
> @GretaD could you reproduce?

yes i could, thats why i added the to.develop
