### ISSUE TITLE
Deal with the overcrowded envelope actions menu

### ISSUE THREAD

**Issue by marcoambrosini** [nextcloud/mail#5956]
Hello mail friends, I think there are too many actions for the envelope component. The popover in the screenshot spans for half the height of my screen.

<img width="229" alt="Screenshot 2022-01-17 at 14 22 39" src="https://user-images.githubusercontent.com/26852655/149777137-9937beef-dce3-4d6d-a8e9-b9a3fd817892.png">

2 possible solutions:
- Getting rid of some of those and having them only accessible within the content
- Having a "more actions" `ActionButton` that "routes" to a submenu within the popover like in Deck

https://user-images.githubusercontent.com/26852655/149777598-da31efad-e4aa-4d81-b39b-7342071b8e85.mov

cc @jancborchardt @nimishavijay

**Comment by ChristophWurst** [comment]
Related: https://github.com/nextcloud/mail/issues/5655

**Comment by jancborchardt** [comment]
More refined mockup:
Current | New menu | New menu more actions
-|-|-
![Mail menu current](https://user-images.githubusercontent.com/925062/154268038-de70f43a-73b3-45c3-898b-25b0566d975d.png)|![Mail action menu](https://user-images.githubusercontent.com/925062/154268036-3ff8a542-81fa-4b70-9413-048061400155.png)|![Mail action menu more](https://user-images.githubusercontent.com/925062/154268033-159c3dae-4cdc-4424-af05-0e427bcb4d27.png)


Live prototype ("More actions" and going back is clickable) at https://design.penpot.app/#/view/35e1b580-8f21-11ec-bd38-efdb6fa63305?page-id=35e1b581-8f21-11ec-bd38-efdb6fa63305&section=interactions&index=0&share-id=f9fe3b00-8f26-11ec-bd38-efdb6fa63305

**Comment by ChristophWurst** [comment]
looks good. we'll have to create a new component for this, the current actions do not appear suitable.

the middle and right menu is the same and a user has to click "More actions" to get from middle to right, right?

**Comment by JuliaKirschenheuter** [comment]
@jancborchardt should we have a "Primary Actions" (top of menu) also inside of "more actions menu"?

**Comment by marcoambrosini** [comment]
Looks nice but what's the font size of those buttons at the top? It seems pretty small to me. Also, I think that text will be ellipsized more often than not with translations. Not sure this is the best way to go, I'd suggest we use delayed tooltips instead of button text or just dump more actions in the 3 dot entry.

**Comment by nimishavijay** [comment]
> should we have a "Primary Actions" (top of menu) also inside of "more actions menu"?

@JuliaKirschenheuter I'd say it's not necessary, we could just replace the entire menu with the "More actions" menu since this enhancement is just to deal with the actions menu being too long.

> Looks nice but what's the font size of those buttons at the top? It seems pretty small to me.

@marcoambrosini On the mockup it is 14px, which is 2px smaller than the main text. I think this isn't too small, plus there are clear well known icons also.

> Also, I think that text will be ellipsized more often than not with translations

This I agree, might lead to 3 ellipsized words in the worst case.
Is it possible to resize this such that the width of each column is equal to the width of the longest text? Would that solve the issue? We could enforce a min and max width, but between those limits we could have a variable width depending on the text.

**Comment by jancborchardt** [comment]
Agree on all of @nimishavijay's points.

To expand a bit on what you asked @marcoambrosini – we can also just make the action menu a bit wider to alleviate the possible ellipsis issue. The 3-actions next to each other with text below is quite a common pattern on Android, and they should absolutely get text below to work both on mobile and for people who don't use Nextcloud every single day.

**Comment by marcoambrosini** [comment]
Wider menu sounds good and will solve the concern I've raised, although now that I take a look at it again, the submenu system with horizontal navigation seems like a better solution to me and doesn't require adding new components to the vue lib, which will take some time 🤔

**Comment by jancborchardt** [comment]
> the submenu system with horizontal navigation seems like a better solution to me and doesn't require adding new components to the vue lib, which will take some time thinking

The submenu system is one part of this. The other thing is the "3 top actions" part, which yes needs a new component. It does take some time, but with the growing menus, it is needed so we should have it?

**Comment by JuliaKirschenheuter** [comment]
Hi together,
the first working version is done. Please look inside ;)
We can discuss all improvements.
![image](https://user-images.githubusercontent.com/6078378/156021856-95dc73fa-a0ab-4928-9ce4-8ee46853111d.png)
![image](https://user-images.githubusercontent.com/6078378/156022079-135be611-3d1d-43fb-808a-7f9e22925f65.png)
