### ISSUE TITLE
email address lists

### ISSUE THREAD

**Issue by R7JANV1** [nextcloud/mail#5957]
Please add email address lists to copy in the recipient area.  As is the case in mail programs of all kinds.  So that a list of email addresses can be copied and pasted without entering each address individually

**Comment by ChristophWurst** [comment]
@R7JANV1 I think I've asked you before, but **please** use the issue templates.

**Comment by pierreozoux** [comment]
closing in favor of:
https://github.com/nextcloud/mail/issues/6013
