### ISSUE TITLE
Update to 1.11.5 fails

### ISSUE THREAD

**Issue by pierreozoux** [nextcloud/mail#5959]
### Expected behavior

I should be able to update.

### Actual behavior

It fails with the following message:
```
/usr/src/nextcloud $ php occ upgrade
Nextcloud or one of the apps require upgrade - only a limited number of commands are available
You may use your browser or the occ upgrade command to do the upgrade
Setting log level to debug
Turned on maintenance mode
Updating database schema
Updated database
Updating <mail> ...
Restore default tags that are missing

 Done
 1/1 [============================] 100%
Purify and migrate collected mail addresses
 Done
    0/0 [------->--------------------]   0%
Insert background jobs for all accounts
 Done
 1/1 [============================] 100%
Doctrine\DBAL\Exception\InvalidFieldNameException: An exception occurred while executing a query: SQLSTATE[42703]: Undefined column: 7 ERROR:  column "in_reply_to" does not exist
LINE 1: ...DATE "mail_messages" SET "in_reply_to" = $1 WHERE "in_reply_...
                                                             ^
Update failed
Maintenance mode is kept active
Resetting log level
```

I guess it is related to Postgres.

In the mean time, I did deactivate this app.

### Mail app

**Mail app version:** 	<version>1.11.5</version>

**Mailserver or service:** not applicable

### Server configuration

**Operating system**: kubernetes

**Web server:** Nginx

**Database:** PostgreSQL

**PHP version:** Docker

**Nextcloud Version:**  21.0.7

**Comment by miaulalala** [comment]
HI there, can you run `DESCRIBE oc_mail_messages;` please?

**Comment by pierreozoux** [comment]
Sorry, at the end, it was a beta env, I recycled it, and we didn't have the issue in prod.
(I guess a migration was missing in the beta :shrug: )
