### ISSUE TITLE
Draft counter doesn't update when you delete a draft

### ISSUE THREAD

**Issue by mathiasconradt** [nextcloud/mail#596]
Happens on NC 12.0.3 (on the Cloud of Nextcloud staff):

I had 4 drafts, I deleted 2 of them via the trashcan icon of the draft. The counter on the left doesn't update but stays at 4.

The counter only updates when I reload the page entirely.

![screenshot from 2017-11-05 11-28-39](https://user-images.githubusercontent.com/295122/32413991-1b073134-c21d-11e7-82ef-6ffdae406e98.png)

**Comment by kamsuri** [comment]
I would like to this issue as a good first bug for RGSOC'18.

**Comment by ChristophWurst** [comment]
Awesome! :)

**Comment by sagorika1996** [comment]
The counter (folders other than draft) doesn't get updated when we delete unread messages.

**Comment by ChristophWurst** [comment]
> The counter (folders other than draft) doesn't get updated when we delete unread messages.

Sounds like another bug. Are you able to localize and fix it?

**Comment by sagorika1996** [comment]
@ChristophWurst Actually I was having some issue with the development setup. Even after enabling the debug mode, only the build.js file is being loaded in the browser.

**Comment by ChristophWurst** [comment]
Sounds like you're referring to https://github.com/nextcloud/mail/tree/master/js#javascript-development? I totally forgot about that documentation, it's totally outdated. We now use webpack and always minify all JavaScript sources into a single file.

Ref https://github.com/nextcloud/mail/issues/815

**Comment by ChristophWurst** [comment]
FYI if you run `npm run dev` it will build a development bundle of js files and watch for changes to update the bundle incrementally, which is much faster than rebuilding the whole bundle after every change.

**Comment by sagorika1996** [comment]
Total is not getting updated here. Correcting this should fix this issue.
https://github.com/nextcloud/mail/blob/1e8adc04f13950256d57e8c3131222ad87e77d6f/js/controller/foldercontroller.js#L199
Unread message bug can handled by adding `Radio.message.trigger('flag', message, 'unseen', false);` after [line 200](https://github.com/nextcloud/mail/blob/master/js/controller/foldercontroller.js#L200).
