### ISSUE TITLE
500 Internal Server Error: Draft message cannot be loaded

### ISSUE THREAD

**Issue by mathiasconradt** [nextcloud/mail#597]
Happens on NC 12.0.3 (Cloud instance for Nextcloud staff):

I have two draft messages in my draft folder. When I click on them to load them, I get a 500 Internal Server Error and the message cannot be loaded:

![screenshot from 2017-11-05 11-29-06](https://user-images.githubusercontent.com/295122/32414014-df24d7ba-c21d-11e7-817d-8cfc2ccbbfad.png)

**Comment by clementhk** [comment]
500 means you need to post your php log.
