### ISSUE TITLE
Add a "reply" (as opposed to "reply all") action [$20]

### ISSUE THREAD

**Issue by mathiasconradt** [nextcloud/mail#598]
NC 12.0.3

I had posted about this in the help forum: https://help.nextcloud.com/t/mail-app-design-decisions-regarding-reply-reply-all-forward-actions/23128

There is currrently no way to simply **reply** to the sender (as opposed to **reply all**) in an easy way. As opposed to other mail clients, the primary action is already preset to "reply all" rather than giving the user the choice.

This leads to the problem that if the user wants to reply to only the sender, he would need to go into the recipients line and manually mark all recipients that he doesn't want to address (if there would be a small 'x' beside each recipient where the user could at least remove a recipient via one click, it would make things easier). 
I think this behaviour (having to mark recipients manually in order to remove them / in order to just reply to the sender) is not really good from a UX perspective and also not very common or what a user would expect from a mail client (at least I didn't see it in any other mail client so far).
Even though the "reply all" might be the most probably primary action a user would take, it should not be pre-selected but giving the user a choice.

Alternatively, there should at least be an action button "reply" similar to the "forward" button, that allows the user to do a simple reply. It's an alternative, but not the best solution.

IMHO the current design seems to be good for a group messaging app, but not for a mail app.

I noticed this when I started working with the mail client now on a regular basis.

**Comment by dcrobertson01** [comment]
Huh. I am trying to find out how I can reply all. All I can do is reply to sender. I need to use another mail programme to reply all. I can't even see the full list of recipients.

**Comment by mathiasconradt** [comment]
@dcrobertson01 Hm, that's weird. The button is labeled "reply" but it has the function of a "reply all" at the moment (see first screenshots in my form link mentioned above). 
Sure that your email actually has multiple recipients in it when you reply? Maybe you can post a screenshot, cause there should not be a simple reply function at the moment.

**Comment by dcrobertson01** [comment]
![2017-11-27-194621_1280x800_scrot](https://user-images.githubusercontent.com/283012/33254215-8672134e-d3ac-11e7-83db-11f3740c9b4b.png)

**Comment by ChristophWurst** [comment]
We've discovered a few bugs recently that effected which addresses were put into the reply to/cc fields. Maybe your installed version was effected too.

**Comment by freekvh** [comment]
I have the same behavior in 12.0.4. Just emailed over 100 people using just the reply button...

**Comment by brzd** [comment]
Hi all

Issue still persists: Nextcloud 13.0.2 and Mail 0.7.10 --> reply sends to everyone in original mail. Separate "reply" and "reply all" would be great.

Br, 
brzd

**Comment by StCyr** [comment]
Here's a proposal:

1. Do not display the `Composer` component as long as a "Reply" or "Reply all" button has not been clicked;
2. Once a "Reply" or "Reply all" button has been clicked, hide these buttons and show a "Send" button.

Issues:

1. The "Forward" button should also been dealt with;
2. All these buttons will start to clutter the screen, especially on mobile devices. It might be worth replacing them by a "hamburger" or "..." menu button.

What d'ya think?

**Comment by ChristophWurst** [comment]
I think putting them to the top right, inside the message's header would be fine. It could be a button group.

**Comment by StCyr** [comment]
yeah but

1. Do you agree with the idea to replace the "Send" button by the "Reply", "Reply all", and "Forward" buttons? And, do you agree to hide the `Composer` component as long as one of these buttons haven't been clicked?
2. I'd have to learn what a button group is :-)

**Comment by ChristophWurst** [comment]
1) I think so.
2) Just a series of `<button>` elements that look like they belong together ;-) Something like https://getbootstrap.com/docs/4.0/components/button-group/

**Comment by StCyr** [comment]
working on it here: https://github.com/nextcloud/mail/pull/1774

**Comment by ChristophWurst** [comment]
Fixed by #1774. @StCyr please don't forget to claim your bounty :)
