### ISSUE TITLE
Not possible to create submailbox in submailboxes

### ISSUE THREAD

**Issue by StCyr** [nextcloud/mail#5987]
### Feature Request

It's currently not possible to create a submailbox from within a submailbox; Creating a submailbox is only possible at the 1st mailbox level.

Is it normal?

* __From within a 1st level mailbox:__

![image](https://user-images.githubusercontent.com/8179031/151338979-5f05de04-a8bc-4725-967e-936e48232772.png)

 * __From within a submailbox:__

![image](https://user-images.githubusercontent.com/8179031/151339567-71345b49-bb74-4b78-a5f2-d9c7c9397fdc.png)

**Comment by GretaD** [comment]
this is intended, yes. Do you think we should have it more than one level? Design wise this is the better solution, because too many levels will star hiding on the right side.

**Comment by ChristophWurst** [comment]
I think that is a relict from the times when we didn't have a deep hierarchy in the app. I would say it's okay to allow deeper hierarchies now.

**Comment by JuliaKirschenheuter** [comment]
Please see 2 PullRequests:
https://github.com/nextcloud/nextcloud-vue/pull/2483
https://github.com/nextcloud/mail/pull/6022
