### ISSUE TITLE
Ability to directly view further attachments from email

### ISSUE THREAD

**Issue by Bibo-Joshi** [nextcloud/mail#5988]
### Feature Request

#5701 was marked as closed by #5898, but IISC that only adds previews for images and not other files (e.g. pdfs). the preview is also only renders a small thumb at the bottom of the mail and one can't view the picture in full-screen without downloading it to PC/NC. (Please correctly me, if I got anything wrong here!)

From #2225 I understand that it's not straight forward to display arbitrary files, also because interaction with other NC components is necessary. However, from the discussion in #5701 and #5898 it's not clear to me whether or not previewing other file types is completely dropped or not.
If it's too complicated to get on any road map, feel free to close. If there is a chance that this could be implemented at some point, I would ask to keep this open :)

#### Summary

Ideally, I would like a preview to use the default tool assigned for the file type (if there is one), e.g. the markdown editor for `.md` files, pdf viewer for pdfs, OnlyOffice for `.docx` & friends, …

TBH, right now I'd already be happy if I could print PDF-attachments without having to download them to my PC/NC first :D

**Comment by jancborchardt** [comment]
Agree on that – https://github.com/nextcloud/mail/issues/5701 called for the ability to directly open it in a Viewer, and that is still valid.

**Comment by ChristophWurst** [comment]
@jancborchardt please specify a list of MIME types that we *have to* support to remove another misunderstanding.

**Comment by jancborchardt** [comment]
@ChristophWurst sorry, misunderstood that https://github.com/nextcloud/mail/pull/5898 did do a viewer for images but is not deployed yet, which is already nice. :)

Then for further viewing it would be nice if Mail supports the same file types for viewing that the Files app also supports – not sure where that list is, but the essentials beyond images would probably indeed be the ones @Bibo-Joshi mentioned:
- pdf
- docx and other MS Office formats
- odf and other LibreOffice formats
- txt, md (that can be opened read-only in the Text app)

**Comment by jancborchardt** [comment]
(Also, is there a specific reason we use a modal and not the same Viewer as in the Files app?)

**Comment by GretaD** [comment]
> (Also, is there a specific reason we use a modal and not the same Viewer as in the Files app?)

yes, attachments are saved in user folder which means that we cannot use viewer because viewer doesnt support that.

**Comment by jancborchardt** [comment]
> > (Also, is there a specific reason we use a modal and not the same Viewer as in the Files app?)
> 
> yes, attachments are saved in user folder which means that we cannot use viewer because viewer doesnt support that.

Thanks for the explanation! Briefly talked with Christoph about that too, would of course be nice to make the Viewer compatible for this too, but I understand this is some work. cc @skjnldsv

**Comment by ChristophWurst** [comment]
There is more discussion at https://github.com/nextcloud/mail/issues/2225.

**Comment by Bibo-Joshi** [comment]
Just double checking, because the responses were mixed: Is the auto-close desired b/c this feature is too complicated or is it a false-positive?

**Comment by ChristophWurst** [comment]
Primary goal of this ticket is to open PDF tickets. The others (Viewer) will come in the next step.

**Comment by tflatka** [comment]
Hi guys,
is there any movement on this issue?
This is a major productivity killer and the biggest issue of the Nextcloud Mail App in a corporate environment.

We need to be able to click on any mail attachment and Nextcloud is supposed to open it (if it knows how to handle the extensiont).
If it is a jpg, a png, all the Collabora supported file types...
The current way:
Saving the attachment to a folder, then go to the folder, find the file and open it... Yes it is a workaround but you are getting stoned by your colleagues for this. This is not competitive and is not what other mail clients offer and it is really killing productivity.

I am wondering if the Nextcloud GmbH employees work with the Nextcloud Mail App as their sole Mailclient day by day, I doubt it!

I can see that you are working very hard to make NC Mail better and better, but having such a productivity killer in the code for more than 3 years, I can't believe it. My hope lies in the developer conference that there will be an effort made to find a solution to make it work.

Cheers
Thorsten

**Comment by ChristophWurst** [comment]
Thank you for your feedback

> If it is a jpg, a png

Those have been supported since https://github.com/nextcloud/mail/issues/6983. MIME image*, video/*, audio/* and application/pdf are handed to the Viewer, if enabled.

For text/* MIME it seems that the Viewer still can't handle files with a source. I temporarily lifted the MIME filter as suggested [https://github.com/nextcloud/text/pull/2832#issuecomment-1667619927](here), but the source is not fetched. Instead, Text tries to start a new session with the absolute URL of the attachment source.

To my best knowledge Collabora still requires the file to exist on the user's Nextcloud Files storage, which is not the case of attachments of Mail, so these files don't work out of the box unfortunately.
