### ISSUE TITLE
Activity notification mail from Nextcloud is not displayed [$15]

### ISSUE THREAD

**Issue by Bables55** [nextcloud/mail#599]
### Steps to reproduce
1. receive mail by nextcloud mail

### Expected behaviour
The content of the mail is normally displayed.

### Actual behaviour
Subject of mail, and FROM and TO. Only the custom logo and background color header of my Nextcloud site will be displayed.
And down there is a blank space with a gray background color with a height of 1000px or more. I'm designating a custom logo and background color as green.
And at the bottom is a block for mail reply.

In the mail application(Thunderbird, WEB mail of My ISP, outlook, Apple mail, iOS genie Mail.app) of the local computer, it is displayed without problems. There is a problem only with Activity Notification Mail of Nextcloud which is received with this nextcloud mail.

### Mail app

**Mail app version:** (see apps admin page)
0.7.4(This also occurred in the old version)
**Mailserver or service:** (e.g. Outlook, Yahoo, Gmail, Exchange,...)
My ISP mail server
**Transport security - IMAP:** (None, SSL, TLS, STARTTLS) 
SSL
**Transport security - SMTP:** (None, SSL, TLS, STARTTLS)
SSL

### Server configuration

**Operating system**:
CentOS 7.3
**Web server:**
nginx 1.11.13
**Database:**
MariaDB 5.5.56
**PHP version:**
7.1.11
**Version:** (see admin page)
12.0.3
**Updated from an older version or fresh install:**
0.7.1

**Comment by jancborchardt** [comment]
cc @Espina2 @MorrisJobke you worked on the Notification mails, right?

**Comment by Bables55** [comment]
Then I was able to restart the server. Then, the reply processing block was not displayed before, but now it scrolls the area outside the iframe and goes fairly downward, the body of the mail and the reply processing block are displayed.
It seems that this iFrame block has been set to a considerably high height for displaying the logo. I can not solve this problem by returning to the initial logo of Nextcloud(default).

A user with administrative authority is an activity item of settings, even if the notification timing is set to "every other day", it seems that it is reported "every hour".
I think that functions other than "problems of this time and above" are functioning normally.

**Comment by MorrisJobke** [comment]
cc @nickvergessen

**Comment by nickvergessen** [comment]
No need to mention ;)

The mail app does currently fail on all our templated emails, including share notifications, activity, etc. So this is a general problem in the mail app

**Comment by jancborchardt** [comment]
Although there is a very slight difference it seems:
- in Share notification mails, there is a big block of grey but the info is still visible below
- in Activity notification mails, the above issue occurs where the real content is not visible even at the bottom

**Comment by nickvergessen** [comment]
Well there is a second scroll bar for me, and with that one I can reach the real activity email content
> ![bildschirmfoto von 2017-11-13 11-23-38](https://user-images.githubusercontent.com/213943/32720946-406d4672-c865-11e7-874f-8c3a7eaa9e07.png)

The issue there is, that the activity email uses the list option which creates more HTML and therefor causes more space

**Comment by alexanderdd** [comment]
@jancborchardt  This issue was opened 2017. The Bug is still present in 2020, with most recent NC 18.0.2 mail 1.1.4

In my opinion this should be high priority because it destroys trust. People who use Nextcloud and install the mail app (which is an official app) will see broken notification mails, thinking "Well if Nextcloud cannot handle it's own notification mails, why should I trust it with anything else?"

- message should be displayed correctly (see screenshot above)
- there should be only one scrollbar (I think there is a separate issue for that somewhere, can someone post a link?)

If it is not possible to fix this soon, a quick fix would be to **not call it offical/featured app any more**. Opinions?

**Comment by Bables55** [comment]
I am NC18.0.3, but better than before. Previously, the height was 100% of the browser, but now it is displayed like an iframe with a height range of about 60%.
![image](https://user-images.githubusercontent.com/30524004/78616775-3101cc00-78b0-11ea-8052-aa3f044a825d.png)

The attached image above is a state where the remote image is not loaded. In my case, the gray area under the header bar is meaninglessly large. When I load a remote image, the site logo sometimes appears at 100% original size of the image.

**Comment by jancborchardt** [comment]
Pull request to fix this at https://github.com/nextcloud/server/pull/20380, please review :)

**Comment by alexanderdd** [comment]
Aweseome, merged! I am not able to test, will check it out once it reaches consumers.

@Bables55 maybe u can test? Or close this issue without testing, just believing the screenshots in the pull request above?

**Comment by Bables55** [comment]
![image](https://user-images.githubusercontent.com/30524004/81627716-c1947480-9439-11ea-81e1-1fab92d73a2b.png)
There is no change in this display.

**Comment by jancborchardt** [comment]
@Bables55 that is because the change is only in current master, which is set to be released as Nextcloud 19 end of this month. You can only test that with a development setup. :) See how to set that up at https://docs.nextcloud.com/server/latest/developer_manual/general/devenv.html#devenv

**Comment by jancborchardt** [comment]
The Bountysource link is somehow broken. Whoever put 15$ onto this issue can feel free to move it to another issue. :) As per our policy, Nextcloud employees never take the bounty, or if they take it, put it back onto other issues.
