### ISSUE TITLE
Black screen after  'htaccess.RewriteBase' => '/',

### ISSUE THREAD

**Issue by mrAceT** [nextcloud/mail#6001]
### Expected behavior
working mail ;)

### Actual behavior
navigation bar visible, completely white 'content screen' (no mail app)

### Mail app
**Mail app version:** 1.11.6
**Mailserver or service:** IMAP mail client (AlmaLinux/Postfix/sendmail)

### Server configuration
**Operating system**: AlmaLinux 8
**Web server:** Apache
**Database:** MySql
**PHP version:** 7.4
**Nextcloud Version:** 22.2.4

#### Client configuration
**Browser:** Google Chrome Version 97.0.4692.99 (Official Build) (64-bit)
**Operating system:** Windows 10

I disliked the 'index.php' in the URL and discovered that adding 'htaccess.RewriteBase' => '/', to the config solved that.
Offcourse followed by 'occ maintenance:update:htaccess'.
All worked well, until I discovered that the mail-app was simple gone, it disappeared!? The 'mail icon' was still there in the navigation bar, but after clicking that all below the navigation bar got white.. nothing happened! I saw that there was an update, do I dit that. But the wh8ite screen persisted! Then I realized that it might be the RewriteBase I recently configured.. I removed that and dit the htaccess update again.. and (thankfully) the mail app worked again ..

So there's something not compatible with that RewriteBase in the mail app?

**Comment by ChristophWurst** [comment]
I think this belongs on https://help.nextcloud.com/

**Comment by ChristophWurst** [comment]
if you think it's a bug in the app then please provide us with browser logs and we can reopen the ticket.
