### ISSUE TITLE
After syncing headers disappear

### ISSUE THREAD

**Issue by CobraPhil** [nextcloud/mail#6007]
After syncing with email account, the headers appear for a few seconds, then they disappear. 
Neither logging out or restarting NextCloud brings the headers back.
Removing and adding the email account again, same results. Headers appear for a few seconds, then disappear.
Running NextCloud 23, Mail 1.11.6.
![mail](https://user-images.githubusercontent.com/73192318/152104757-d39d7161-47b3-4c4b-981f-85954d1bba98.png)

**Comment by CobraPhil** [comment]
This is in the error log. 

Error | PHP | Error: Undefined offset: -1 at /var/www/nextcloud/apps/mail/lib/IMAP/MessageMapper.php#186

Happens with different NextCloud accounts.

**Comment by ChristophWurst** [comment]
Please follow the template and submit a complete report https://github.com/nextcloud/mail/issues/new?assignees=&labels=bug%2C+0.+to+triage&template=bug.md&title=
