### ISSUE TITLE
Unexpected tag "Loadremoteimages" showing up in tag list

### ISSUE THREAD

**Issue by jancborchardt** [nextcloud/mail#6020]
The tag "Loadremoteimages" shows up in the user-facing tag list even though it is just machine readable. Would be nicer if we prevent it from showing up there:

![image](https://user-images.githubusercontent.com/925062/153183931-4b80e025-e006-4acc-b1c6-f2bb481d4b07.png)

**Comment by miaulalala** [comment]
interesting, did this happen after you clicked on "show images" in NC or in a different client?

**Comment by jancborchardt** [comment]
There we go, it seems to be Geary (GNOME Mail): https://gitlab.gnome.org/search?search=loadremoteimages&group_id=8&project_id=1894&scope=&search_code=true&snippets=false&repository_ref=mainline&nav_source=navbar

Could not find anything in the K9-Mail code.

So how do we proceed there? Probably will have to visually filter that tag out both in the tag list and from displaying on messages in the in the envelope list?

**Comment by miaulalala** [comment]
Well it's a good question. I would be in favour of not doing anything special with tags that might come from other mail programmes, since the list could possibly be endless. On the other hand, we already have exceptions such as the $important label. Also a question on where we'd filter them - just frontend, or backend, too?

I'd display them anyway.

**Comment by ChristophWurst** [comment]
I agree. If we are going to hide some then we'll have to curate this list. Another tag that occasionally shows up for me is `hascal`. I think Thunderbird sets it for ics attachments.

**Comment by jancborchardt** [comment]
> If we are going to hide some then we'll have to curate this list.

Which we already do for the "Re: ", "Fwd: ", etc case, and this improves the experience of the app quite a lot.

> Another tag that occasionally shows up for me is hascal. I think Thunderbird sets it for ics attachments.

That would be another argument for such a list – certainly weird to have a technical tag like that show to people.

**Comment by mat-m** [comment]
Some more tags from laposte.net provider:

![image](https://user-images.githubusercontent.com/1039753/174460118-e87e0b7b-f4fb-46d4-bcc4-13f534bd06ed.png)

**Comment by ChristophWurst** [comment]
> where we'd filter them - just frontend, or backend, too?

Let's add a simple block list to the frontend that filters out those special tags.

**Comment by violoncelloCH** [comment]
@JuliaKirschenheuter are you already working on this ? If not I could take a look at it and open a PR :)

**Comment by JuliaKirschenheuter** [comment]
@violoncelloCH please take over
