### ISSUE TITLE
Tags can not be deleted

### ISSUE THREAD

**Issue by R7JANV1** [nextcloud/mail#6023]
### Expected behavior

When keywords are created they cannot be deleted.

### Actual behavior

Keywords should be able to be deleted.

### Steps to reproduce

1.Select email
2. create keywords
3. try to delete the keywords (does not work)

**Comment by miaulalala** [comment]
What do you mean with keywords? Can you post a screenshot?

**Comment by GretaD** [comment]
duplication #5146
