### ISSUE TITLE
Possible to create tags with same name while in the modal

### ISSUE THREAD

**Issue by jancborchardt** [nextcloud/mail#6024]
### Expected behavior

People shouldn’t be able to create tags with the exact same name.

### Actual behavior

Currently it’s possible to create tags with the exactly same name, which makes little sense. After a refresh, the duplicates are gone though, making it look like a bug that they are visible in the first place:
![image](https://user-images.githubusercontent.com/925062/153201844-5843369f-4d42-4a74-a8db-1f7d261505bc.png)

### Steps to reproduce

1. Edit tags of a mail
2. Create some tags with the same name
3. Then to confirm they are gone, refresh and check that the duplicate tags are gone again

**Comment by miaulalala** [comment]
Can confirm, seems to be Frontend only. Backend doesn't have duplicates in the DB.

**Comment by Zivangu9** [comment]
Hello, I am a beginner and I would like to contribute, I think I can solve this issue, so I’ll get started on it

**Comment by ChristophWurst** [comment]
Sounds good @Zivangu9! Are you familiar with Vue?

**Comment by Zivangu9** [comment]
Not really, but I have worked with JavaScript before, and I know the MVC.

**Comment by Zivangu9** [comment]
I was analyzing the code and I already thought of a solution, it would be a validation when creating a new label if the imap_label already exists in the list of labels
