### ISSUE TITLE
Tag modal allows creating "empty" tags

### ISSUE THREAD

**Issue by miaulalala** [nextcloud/mail#6025]
### Expected behavior

When I save an empty string or a string just consisting of whitespace, the tag modal alerts me to it and doesn't send the http request

### Actual behavior

The http request is sent, leading to an "empty" label in the db like this:

![image](https://user-images.githubusercontent.com/7427347/153217100-71f005ce-332a-4f5f-89dc-690d205ab34b.png)

### Steps to reproduce

1. Open modal
2. type something and delete it again or just enter a witespace character and save it
3. have a look at the DB entry

### Mail app version

master

### Mailserver or service

GMX

### Operating system

Ubuntu 20

### PHP engine version

PHP 8.0

### Web server

Apache (supported)

### Database

MySQL

**Comment by ChristophWurst** [comment]
Duplicate of https://github.com/nextcloud/mail/issues/9020 and fixed?

**Comment by ChristophWurst** [comment]
Fixed by https://github.com/nextcloud/mail/pull/9074
