### ISSUE TITLE
Deleting topmost message in a list does not move to open next message

### ISSUE THREAD

**Issue by jancborchardt** [nextcloud/mail#6042]
### Steps to reproduce

1. Open any folder, e.g. your inbox
2. Go to the topmost message
3. Delete it, either via the menu or the Delete key

### Expected behavior

Move to the next mail below and open it. It does work if you do it with any other mail in the list, moving to the next newest. Of course there needs to be 1 special case, which is to open the next older mail if there is no next newest mail. :)

(This used to work at some point in the past which is why it is a regression.)

### Actual behavior

The envelope view on the right turns blank and no message is selected.

### Mail app version

Current on cloud.nextcloud.com

**Comment by GretaD** [comment]
this only happens on INBOX, not PI.

I get this message when i delete the top message: 
```
vue-router.esm.js:2065 Uncaught (in promise) NavigationDuplicated: Avoided redundant navigation to current location: "/box/unified/thread/2327736".
    at Ft (https://cloud.nextcloud.com/apps/mail/js/mail.js?v=14a9ed25-72:495:26600)
```

**Comment by jancborchardt** [comment]
@GretaD I do have the same issue elsewhere as well, tested in Priority inbox, Sent, Archive, and Trash

All with that error message you pasted too.
