### ISSUE TITLE
Message loading experience is a multi-step process and feels slow and not solid as a result

### ISSUE THREAD

**Issue by jancborchardt** [nextcloud/mail#6045]
**This is how message loading looks right now:**
![HTML 4 step rendering](https://user-images.githubusercontent.com/925062/154257575-f5ffea34-3173-481a-b54b-c834aa8eab16.gif)

**The HTML message viewing experience is currently a 4-step process:**
1. The envelope view goes blank first
2. A small row/envelope appears, with a loading spinner cutting through the bottom, looking broken
3. It extends to a container which looks of a more proper height, still with spinner
4. The mail content loads fully and expands (or if very little text, retracts) to full height

**To improve this, could we do the following, or some of it?**
1. Completely cut step 1 with the blank view. We do have the avatar and sender data from the message list, the rest is generic controls, so it could all be shown directly?
2. Skip this step with the small row/envelope → can we directly go to step 3 where the envelope has a reasonable default height?
3. Several things possible here:
	- Instead of a simple spinner, we can use a skeleton view here – just like we do for Talk conversations, which makes the experience feel much quicker than a generic spinner.
	- The height in this step (new default height) could be reduced a tad to be the exact height it would be if the message had no content (e.g. if only a subject), or only 1 line of text.
	- Sometimes in this step the read/unread state of the mail toggles (see animation, unbolding and bolding of sender name) and goes back again, making it look a bit off.
4. Have a very quick expand animation (100ms quick or so) to the full height once the content is fully loaded so that it looks less jarring.

**Comment by ChristophWurst** [comment]
## Break down of current HTML loading order

### Thread loading
![vlcsnap-2022-11-09-11h46m54s353](https://user-images.githubusercontent.com/1374172/200810603-b23129b3-1e31-43dd-ac22-0621e1e38868.png)

### Message loading
![vlcsnap-2022-11-09-11h46m59s137](https://user-images.githubusercontent.com/1374172/200810653-7e33010c-bb1c-467a-925a-f8315cf80f6d.png)

### ???
![vlcsnap-2022-11-09-11h47m06s683](https://user-images.githubusercontent.com/1374172/200810710-f4fe8774-c11f-4353-a4d6-f134e31c5ab7.png)

### Finished loading
![vlcsnap-2022-11-09-11h47m12s550](https://user-images.githubusercontent.com/1374172/200810757-b8b1da03-eed6-41db-9c16-336b50ab9ce8.png)

**Comment by ChristophWurst** [comment]
Todo

- [ ] Fix the thread login screen
  - Center the icon (empty content component?)
  - Add a text
- [ ] Fix the message loading screen
  - Add minimum height to element so the spinner looks less broken. This should be less than an action message
  - After the loading finished, animate that the element grows to the actual message size (especially text messages)
- [ ] Fix the ifram loading screen
  - Either
    - Load the iframe with v-show=false and show a loading icon while the body loads
    - Remove the loading icon

**Comment by ChristophWurst** [comment]
> 4\. Remove the loading thread(emptycontent) as a first step and show the subject/recipient and envelope header directly instead

This is not always possible. If we have no info about the thread but its ID then we have to show some sort of general loading screen. If we have at least one message we can guess the thread subject. The former happen when you load a thread on page load. The latter happens when you open a thread from the loaded envelope list.

https://github.com/nextcloud/mail/pull/7607 improves those two code paths.

**Comment by ChristophWurst** [comment]
@GretaD close?

**Comment by GretaD** [comment]
yeesssss
