### ISSUE TITLE
ArgumentCountError: array_merge() expects at least 1 parameter, 0 given

### ISSUE THREAD

**Issue by tcitworld** [nextcloud/mail#6047]
### Steps to reproduce

1. Checkout logs
2. Notice the error

### Expected behavior

No error

### Actual behavior

The following error in logs

<pre>
<code>
{"reqId":"Rlegc5HWmaAbKD2W8h8t",
"level":3,
"time":"2022-02-17T09:10:12+01:00",
"remoteAddr":"",
"user":"--",
"app":"mail",
"method":"",
"url":"--",
"message":"Cron importance classifier training failed: array_merge() expects at least 1 parameter, 0 given"
,"userAgent":"--",
"version":"23.0.0.10",
"exception":{
"Exception":"ArgumentCountError","Message":"array_merge() expects at least 1 parameter, 0 given",
"Code":0,
"Trace":[
  {"file":"/var/www/clients/client1/web1/web/nextcloud/apps/mail/lib/Db/MessageMapper.php","line":983,"function":"array_merge","args":[]},
  {"file":"/var/www/clients/client1/web1/web/nextcloud/apps/mail/lib/Db/MessageMapper.php","line":1019,"function":"findRecipients","class":"OCA\\Mail\\Db\\MessageMapper","type":"->","args":[[]]},{"file":"/var/www/clients/client1/web1/web/nextcloud/apps/mail/lib/Db/MessageMapper.php","line":1105,"function":"findRelatedData","class":"OCA\\Mail\\Db\\MessageMapper","type":"->","args":[[],"c346a576-fa89-1032-9add-db265ef6f722"]},
  {"file":"/var/www/clients/client1/web1/web/nextcloud/apps/mail/lib/Service/Classification/ImportanceClassifier.php","line":167,"function":"findLatestMessages","class":"OCA\\Mail\\Db\\MessageMapper","type":"->","args":["c346a576-fa89-1032-9add-db265ef6f722",[],1000]},
  {"file":"/var/www/clients/client1/web1/web/nextcloud/apps/mail/lib/BackgroundJob/TrainImportanceClassifierJob.php","line":86,"function":"train","class":"OCA\\Mail\\Service\\Classification\\ImportanceClassifier","type":"->","args":[{"__class__":"OCA\\Mail\\Account"},{"__class__":"OC\\AppFramework\\ScopedPsrLogger"}]},
  {"file":"/var/www/clients/client1/web1/web/nextcloud/lib/public/BackgroundJob/Job.php","line":79,"function":"run","class":"OCA\\Mail\\BackgroundJob\\TrainImportanceClassifierJob","type":"->","args":[{"accountId":1}]},
  {"file":"/var/www/clients/client1/web1/web/nextcloud/lib/public/BackgroundJob/TimedJob.php","line":63,"function":"execute","class":"OCP\\BackgroundJob\\Job","type":"->","args":[{"__class__":"OC\\BackgroundJob\\JobList"},{"__class__":"OC\\Log"}]},
  {"file":"/var/www/clients/client1/web1/web/nextcloud/cron.php","line":128,"function":"execute","class":"OCP\\BackgroundJob\\TimedJob","type":"->","args":[{"__class__":"OC\\BackgroundJob\\JobList"},{"__class__":"OC\\Log"}]}
],
"File":"/var/www/clients/client1/web1/web/nextcloud/apps/mail/lib/Db/MessageMapper.php","Line":983,"CustomMessage":"Cron importance classifier training failed: array_merge() expects at least 1 parameter, 0 given"},"id":"620e0da41eca4"}
</code>
</pre>

### Mail app version

1.11.6

### Mailserver or service

IMAP (Bluemind)

### Operating system

Debian

### PHP engine version

PHP 7.3

### Web server

Nginx

### Additional info

`$recipientsResults` can stay equal to `[]` so the call to `array_merge` gives an error.

https://github.com/nextcloud/mail/blob/da7b2c1ebd3154fecca6930e1fb8181f4aa969b7/lib/Db/MessageMapper.php#L983

**Comment by FadeFx** [comment]
hi, i am not sure if i did something wrong, but i see this frequently in my logfiles still, mail version seems to be 1.11.7
my mail provider is gmail via imap and an app password (if this is important) or gmx via imap (i guess its that one as i see ncp in the error message paramater somewhere, which is the built in admin user for nextcloudpi)
`{"reqId":"8MZU4jsSeJjNObzv89cP","level":3,"time":"2022-04-17T16:00:02+00:00","remoteAddr":"","user":"--","app":"mail","method":"","url":"--","message":"Cron importance classifier training failed: array_merge() expects at least 1 parameter, 0 given","userAgent":"--","version":"23.0.2.1","exception":{"Exception":"ArgumentCountError","Message":"array_merge() expects at least 1 parameter, 0 given","Code":0,"Trace":[{"file":"/var/www/nextcloud/apps/mail/lib/Db/MessageMapper.php","line":983,"function":"array_merge","args":[]},{"file":"/var/www/nextcloud/apps/mail/lib/Db/MessageMapper.php","line":1019,"function":"findRecipients","class":"OCA\\Mail\\Db\\MessageMapper","type":"->","args":[[]]},{"file":"/var/www/nextcloud/apps/mail/lib/Db/MessageMapper.php","line":1105,"function":"findRelatedData","class":"OCA\\Mail\\Db\\MessageMapper","type":"->","args":[[],"ncp"]},{"file":"/var/www/nextcloud/apps/mail/lib/Service/Classification/ImportanceClassifier.php","line":167,"function":"findLatestMessages","class":"OCA\\Mail\\Db\\MessageMapper","type":"->","args":["ncp",{"3":25,"4":26},1000]},{"file":"/var/www/nextcloud/apps/mail/lib/BackgroundJob/TrainImportanceClassifierJob.php","line":86,"function":"train","class":"OCA\\Mail\\Service\\Classification\\ImportanceClassifier","type":"->","args":[{"__class__":"OCA\\Mail\\Account"},{"__class__":"OC\\AppFramework\\ScopedPsrLogger"}]},{"file":"/var/www/nextcloud/lib/public/BackgroundJob/Job.php","line":79,"function":"run","class":"OCA\\Mail\\BackgroundJob\\TrainImportanceClassifierJob","type":"->","args":[{"accountId":3}]},{"file":"/var/www/nextcloud/lib/public/BackgroundJob/TimedJob.php","line":63,"function":"execute","class":"OCP\\BackgroundJob\\Job","type":"->","args":[{"__class__":"OC\\BackgroundJob\\JobList"},{"__class__":"OC\\Log"}]},{"file":"/var/www/nextcloud/cron.php","line":128,"function":"execute","class":"OCP\\BackgroundJob\\TimedJob","type":"->","args":[{"__class__":"OC\\BackgroundJob\\JobList"},{"__class__":"OC\\Log"}]}],"File":"/var/www/nextcloud/apps/mail/lib/Db/MessageMapper.php","Line":983,"CustomMessage":"Cron importance classifier training failed: array_merge() expects at least 1 parameter, 0 given"}}`

**Comment by tcitworld** [comment]
This is in version 11.8.

**Comment by FadeFx** [comment]
ah, so its not out yet?

**Comment by tcitworld** [comment]
That's right.
