### ISSUE TITLE
Full message body not displayed

### ISSUE THREAD

**Issue by dustbro** [nextcloud/mail#6050]
### Steps to reproduce

Receiving email from Wordpress / wpforms fails to display entire message. 

### Expected behavior

message body should display entire form contents

### Actual behavior

Message body is getting cut off.

![Screenshot from 2022-02-18 09-41-35](https://user-images.githubusercontent.com/9417887/154705389-785abc9b-7412-4f6f-85c4-257689e064e6.png)

### Mail app version

1.11.6

### Mailserver or service

Zoho

### Operating system

Ubuntu 20.04

### PHP engine version

PHP 7.4

### Web server

Nginx

### Database

MariaDB

**Comment by GretaD** [comment]
hello dustbro, do you see any error on nextcloud.log or on your web console when you try to open this message?

**Comment by dustbro** [comment]
"app":"mail","method":"GET","url":"/index.php/apps/mail/api/messages/5/body","message":"KItinerary binary adapter is not available, can't extract information","userAgent":"Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:97.0) Gecko/20100101 Firefox/97.0","version":"23.0.2.1"}

**Comment by ChristophWurst** [comment]
to me it looks more like a styling issue, as if the height of the iframe is limited to x pixels. are you familiar with browser inspection? could you take a closer look and see if that could be the case?
