### ISSUE TITLE
Search bar for searching emails

### ISSUE THREAD

**Issue by JordanDIG** [nextcloud/mail#6058]
### Is your feature request related to a problem? Please describe.

I am frustrated that nextcloud mail does not offer a search bar to look for an email in a folder for example or via an address.

### Describe the solution you'd like

I would like to be able to search my e-mails by e-mail address, by date, by file, by subject or by content.

### Describe alternatives you've considered

I hardly use nextcloud mail because in the company or in the personal world we spend our time writing/searching mails etc..
The addition of this feature would allow me to let go of my usual SMTP client.

**Comment by ChristophWurst** [comment]
@jancborchardt @nimishavijay do we have any concepts for a more detailed search feature? The unified search works and has some hidden filter attributes, but this isn't quite discoverable for the non power users and the search results are also quite limited.

**Comment by JordanDIG** [comment]
We need something simple to use.

**Comment by nimishavijay** [comment]
There are plans to standardize having the "New message" button on the content list for many apps (like contacts, mail, etc). This would allow for a search bar in the navigation for searching through mails (or contacts, etc)
I think it could be a good idea to have app-specific search in the navigation.

cc @jancborchardt 👀

**Comment by JordanDIG** [comment]
Yes it could be useful and practical

**Comment by JordanDIG** [comment]
Do you have any idea when this would be implemented? @ChristophWurst

**Comment by ChristophWurst** [comment]
Not really

**Comment by JordanDIG** [comment]
Okay...

**Comment by Lionel-cl** [comment]
Hello,
For me, this function and powerful search are essential. Without this, the use of Mail will remain limited to occasional users.

@ChristophWurst Can you put here the hidden filter attributes and how to use them?
before: date format?

Also in my NC24 instances, unified search in Mail doesn't work, while it works in Files, Deck, ...
Thank you

**Comment by BiglifeMatt** [comment]
Not only would a dedicated search be more practical and useful but hopefully it would operate by return a select group of email so that, for example, you could Select All and Delete a returned group.  This alone is one reason we are still requiring Rainloop to be used.  There are other features of Rainloop that I prefer as well but the search is critical.

**Comment by Karamelmar** [comment]
Actually the state of the search filtering is whats keeping us from using the mail app as our daily driver.
If f.e. one of us wants to write an email to a member of another organizational unit, often the name of the person is forgotten, only the organizations name... so when we type in that name, the suspected outcome should be that i find all mails that came from the domain from that company...
The same goes for Names... if a partial name is typed, all mails where that contain it in any field should pop up.
For a daily use in a company or like in our case a university, this is a feature every single person needs multiple times a day.

Apart from that problem, we are very impressed how the mail app progressed, thanks!

**Comment by GretaD** [comment]
Hello,

a community member has already worked on a feature like that and its already released on 2.1. The pr: https://github.com/nextcloud/mail/pull/6546
So please update and give it a try.
