### ISSUE TITLE
Ability to empty spam/junk all at once

### ISSUE THREAD

**Issue by jancborchardt** [nextcloud/mail#6060]
### Is your feature request related to a problem? Please describe.

The usual way to deal with the spam/junk folder is to briefly look through it, confirm there’s really nothing of value in it, and then empty it. The emptying step is a bit cumbersome at the moment, as you have to use select → select all manually one by one → delete.

### Describe the solution you'd like

Just like "Empty trash" (which doesn’t work for me atm, ref https://github.com/nextcloud/mail/issues/5672 ) it would be nice to have the same for the spam/junk folder, as in an "Empty spam" action as the last entry of the spam folder actions menu.

### Describe alternatives you've considered

We could also have a button "Empty spam" in the header of the folder similar like Geary does. However, this might be too much and could also be confused with the "New message" button once we move it there.
![image](https://user-images.githubusercontent.com/925062/154950767-72e14215-7931-40ce-b13c-7bccc5479af0.png)
So let’s not do this, just noting it here for the sake of completion.

**Comment by GretaD** [comment]
Hello @jancborchardt ,
Clear mailbox work for me in every mailbox including Junk. 

[Screencast from 02.01.2023 13:02:32.webm](https://user-images.githubusercontent.com/12728974/210228952-ef10a1d6-d88e-4aa7-b245-9c55ce0ee5db.webm)

Can you please check again if that work for you?

**Comment by jancborchardt** [comment]
@GretaD ah nice, yep "Clear mailbox" works, thanks! :)

What do you think about the additional prompt as described above:

> We could also have a button "Empty spam" in the header of the folder similar like Geary does.

**Comment by GretaD** [comment]
> @GretaD ah nice, yep "Clear mailbox" works, thanks! :)
> 
> What do you think about the additional prompt as described above:
> 
> > We could also have a button "Empty spam" in the header of the folder similar like Geary does.

Sorry, im a bit confused, the description you would like, its the one we have now, so as the last item on the action menu.
While on the alternatives you've considered you say:
> However, this might be too much and could also be confused with the "New message" button once we move it there. So let’s not do this, just noting it here for the sake of completion.

which i agree.

**Comment by jancborchardt** [comment]
Ok cool, then let's close this.
