### ISSUE TITLE
Column "oc_mail_mailboxes"."selectable" is type Bool and also NotNull, so it can not store "false"

### ISSUE THREAD

**Issue by direc85** [nextcloud/mail#6065]
### Steps to reproduce

Try to install Mail either from command line or from GUI

### Expected behavior

The Mail extension should install.

### Actual behavior

Error message `Column "oc_mail_mailboxes"."selectable" is type Bool and also NotNull, so it can not store "false"` appears, both in GUI and with `occ`. The app doesn't install (and apparently rolls back changes, because table `oc_mail_mailboxes` isn't there for inspection anymore.

### Mail app version

1.11.7

### Mailserver or service

N/A

### Operating system

Debian 10 Buster (Kernel 5.10.68)

### PHP engine version

PHP 8.0

### Web server

Apache (supported)

### Database

MariaDB

### Additional info

I've been running for a few days Nextcloud 23.0.2, which originates as an _old_ OwnCloud installation (can't even remember how old), which I just now updated to Nextcloud. Also, I think I had the old Mail app installed at some point for testing during OwnCloud era, but I think those files are long gone - perhaps some lint remains in database? OC/NC folder has been fully replaced, save the config file, many times.

I tried to install the Mail app in GUI with admin account, no luck. From command line using `occ`, same error. So I started digging and eventually grepped my way to two migrations [0156](https://github.com/nextcloud/mail/blob/7f32cfe6570d112fb748c9a97590e2b9d6e8aafb/lib/Migration/Version0156Date20190828140357.php#L79) and [0161](https://github.com/nextcloud/mail/blob/7f32cfe6570d112fb748c9a97590e2b9d6e8aafb/lib/Migration/Version0161Date20190902103701.php#L87) which seemed interesting. I followed suit from some other boolean column operations and after I changed both migrations to like this, `occ app:enable mail` went through:

    $mailboxTable->addColumn('selectable', 'boolean', [
        'notnull' => false,
        'default' => true,
    ]);

Again, I'm not sure how I ran into this, but these are just my findings and what fixed it for me :)

Some further system details:

- Apache2 2.4.38-3+deb10u4
- MariaDB 10.3.31-MariaDB-0+deb10u1
- PHP 8.0.15 (cli) (built: Jan 29 2022 07:39:13)
- The server is a shared host with no root access for me

Thanks!

**Comment by chrissi55** [comment]
same here
NGinx 1.21
PostgreSQL 14.1 DB
PHP 8.0.15
ubuntu server 20.04.4

Need to change the values in 0156 and 0161 from "true" to "false" and enabled it via occ command.

**Comment by ChristophWurst** [comment]
> Need to change the values in 0156 and 0161 from "true" to "false" and enabled it via occ command.

so you now have the columns with *default false*?

**Comment by chrissi55** [comment]
I've  changed the values for 'notnull' => true to 'notnull' => false in both files (0156 and 0161)

The values for 'default' => true were unchanged.

liThe values for 'default' => true were unchanged.

like this

```
$mailboxTable->addColumn('selectable', 'boolean', [
			'notnull' => false,
			'length' => 1,
			'default' => true,
		]);
```

**Comment by Larx** [comment]
Has anybody found a workaround yet?

**Comment by jeekajoo** [comment]
Same here when trying to install Mail 1.12.1 on Nextcloud 24.0.1 :
`Database error when running migration 0156Date20190828140357 for app mail Column "oc_mail_mailboxes"."selectable" is type Bool and also NotNull, so it can not store "false". `

Debian 4.19.194-3
PHP 8.0.18
MySQL server 8.0.29

**Comment by ChristophWurst** [comment]
Fixed with https://github.com/nextcloud/mail/pull/6515. v1.12.2 will include this fix https://github.com/nextcloud/mail/pull/6607.
