### ISSUE TITLE
Subscribe and unsubscribe from a mailbox

### ISSUE THREAD

**Issue by ChristophWurst** [nextcloud/mail#6073]
### Is your feature request related to a problem? Please describe.

As a user I want to be able to change the subscription status of my mailboxes. After all Mail gives me the option to show only subscribed mailboxes.

### Describe the solution you'd like

Add an action button to subscribe/unsubscribe each mailbox to the actions menu of a mailbox.

### Describe alternatives you've considered

N/a

### Additional context

https://github.com/nextcloud/mail/pull/3116

**Comment by JuliaKirschenheuter** [comment]
> sorry, which feature?

**Comment by ChristophWurst** [comment]
https://github.com/nextcloud/mail/issues/6073#issue-1147820183

**Comment by JuliaKirschenheuter** [comment]
I would say yes. Besides this https://github.com/nextcloud/mail/pull/6411#issuecomment-1123806739 where it makes no sense to show "subscribed" checkbox, because this folders could be only "subscribed".
