### ISSUE TITLE
Move messages between accounts

### ISSUE THREAD

**Issue by cnmicha** [nextcloud/mail#6102]
### Is your feature request related to a problem? Please describe.

I use multiple email accounts and like to move email between them, e.g. moving an email from the inbox of account A to a directory of account B.

Currently, when dragging a message, all directories of other email accounts become greyed out so moving is not possible.

### Describe the solution you'd like

Directories of other email accounts should not become grayed out when dragging a message, so moving between accounts is possible.

### Additional context

All common email applications for desktop computers support this (e.g. Outlook, Thunderbird).

**Comment by ChristophWurst** [comment]
Dup of https://github.com/nextcloud/mail/issues/5596
