### ISSUE TITLE
Convert Email to Task

### ISSUE THREAD

**Issue by thstyl2000** [nextcloud/mail#6127]
Detailed feature request taken from https://github.com/nextcloud/mail/issues/6678.

## Is your feature request related to a problem? Please describe.

I love that we already have the ability to create an event from an e-mail, but what would be even more useful to me would be to be able to create tasks with an optional due date from an e-mail. I often create myself a todo list to manage incoming e-mails, so this feature could speed up that work.

## Describe the solution you'd like

The flow could be almost identical to creating events:

1. Click on the 3 dots menu on a specified e-mail and go into the "More actions" sub-menu. There you would find a new button below "Create event" such as "Create task"
![image](https://user-images.githubusercontent.com/36501744/172541295-5869f520-49a4-44ca-b60d-48f3e3d8f8f1.png)

2.  Click on "Create task". This would open a modal similar to the "Create event" one, with some or all of the following options:
    - Name (defaults to e-mail title)
    - Start date (defaults to now)
    - Due date (defaults to now + 1 hour for example)
    - "All day" checkbox (similar to events, turns the two previous datetime selections into date only selections)
    - Calendar selection (to which calendar should the task be attached)
    - Optional: Priority ?
    - Optional: Status ?
    - Optional: Tags ?
    - Optional: Notes (defaults to e-mail body)
Here is the "Create event" modal as a reference:
![image](https://user-images.githubusercontent.com/36501744/172542515-fe38c87f-c90c-4c05-b7da-3ab5d685dc27.png)

## Acceptance criteria

* Optional: put *Create task* into existing *Create event* action and modal
  * Use https://github.com/nextcloud/nextcloud-vue/pull/3945 to switch between event and task

## Work packages

- [ ] Main implementation that fulfill acceptance criteria
- [ ] https://github.com/nextcloud/documentation/issues/10016

**Comment by miaulalala** [comment]
Nice idea!

**Comment by ufgum** [comment]
Another benefit could be to "create a deck card" subject as card name, body as attachment or as description. Also to add to an existing card. With **task or deck**, it would be possible to  handle projects with the mail APP.

**Comment by olgru** [comment]
I'm looking for a way to document requests somehow. Most are reaching me by mail, most got respond by mail too. But I don't want my mail client to be the documentation system. Would be much nicer to have this here as other related team activities are also within NC. 
Si I support this request... ;-)

**Comment by cydnax** [comment]
Hi. Any update on this yet?
