### ISSUE TITLE
IMAP auto config not working (postfix & dovecot backend)

### ISSUE THREAD

**Issue by CrazyFluffyPony** [nextcloud/mail#6130]
### Steps to reproduce

1. Setup nextcloud
2. Setup a postfix and dovecot (imap and stmp) for https
3. Try to connect via nextcloud mail app form (v 1.11.7)
4. Fails

(Trying with SMTP and without SMTP settings leads to the same result)

I can try to provide further postfix/dovecot logs, although i wont call myself an expert on mail administration, i'm earning my money with web dev.

As mentioned below, the settings work fine with both Thunderbird and FairMail (Android App) and i copy pasted their configurations over to the nextcloud mail form (tried 1 year ago, half a year ago and today).

The only result of my issue research was this: #5763

A big thanks to all of you working on this project, it is amazing ❤️ !
Cheers, Pony

### Expected behavior

Working, just like my Android App (FairMail) and Thunderbird

### Actual behavior

Fails to connect via website, dovecot does not even recognize a login attempt.
Nextcloud error log

```
Fehler	PHP	Error: simplexml_load_string(): ^ at /var/www/nextcloud/apps/mail/lib/Service/AutoConfig/IspDb.php#73	
2022-03-15T11:31:52+0100
Fehler	PHP	Error: simplexml_load_string(): &lt;/html&gt; at /var/www/nextcloud/apps/mail/lib/Service/AutoConfig/IspDb.php#73	
2022-03-15T11:31:52+0100
Fehler	PHP	Error: simplexml_load_string(): Entity: line 17: parser error : EndTag: '&lt;/' not found at /var/www/nextcloud/apps/mail/lib/Service/AutoConfig/IspDb.php#73	
2022-03-15T11:31:52+0100
Fehler	PHP	Error: simplexml_load_string(): ^ at /var/www/nextcloud/apps/mail/lib/Service/AutoConfig/IspDb.php#73	
2022-03-15T11:31:52+0100
Fehler	PHP	Error: simplexml_load_string(): &lt;/html&gt; at /var/www/nextcloud/apps/mail/lib/Service/AutoConfig/IspDb.php#73	
2022-03-15T11:31:52+0100
Fehler	PHP	Error: simplexml_load_string(): Entity: line 17: parser error : Opening and ending tag mismatch: body line 4 and html at /var/www/nextcloud/apps/mail/lib/Service/AutoConfig/IspDb.php#73	
2022-03-15T11:31:52+0100
Fehler	PHP	Error: simplexml_load_string(): ^ at /var/www/nextcloud/apps/mail/lib/Service/AutoConfig/IspDb.php#73	
2022-03-15T11:31:52+0100
Fehler	PHP	Error: simplexml_load_string(): &lt;/body&gt; at /var/www/nextcloud/apps/mail/lib/Service/AutoConfig/IspDb.php#73	
2022-03-15T11:31:52+0100
Fehler	PHP	Error: simplexml_load_string(): Entity: line 16: parser error : Opening and ending tag mismatch: img line 4 and body at /var/www/nextcloud/apps/mail/lib/Service/AutoConfig/IspDb.php#73	
2022-03-15T11:31:52+0100
Fehler	PHP	Error: simplexml_load_string(): ^ at /var/www/nextcloud/apps/mail/lib/Service/AutoConfig/IspDb.php#73	
2022-03-15T11:31:52+0100
Fehler	PHP	Error: simplexml_load_string(): &lt;/head&gt; at /var/www/nextcloud/apps/mail/lib/Service/AutoConfig/IspDb.php#73	
2022-03-15T11:31:52+0100
Fehler	PHP	Error: simplexml_load_string(): Entity: line 6: parser error : Opening and ending tag mismatch: meta line 4 and head at /var/www/nextcloud/apps/mail/lib/Service/AutoConfig/IspDb.php#73	
2022-03-15T11:31:52+0100
Fehler	PHP	Error: simplexml_load_string(): ^ at /var/www/nextcloud/apps/mail/lib/Service/AutoConfig/IspDb.php#73	
2022-03-15T11:31:52+0100
Fehler	PHP	Error: simplexml_load_string(): &lt;/html&gt; at /var/www/nextcloud/apps/mail/lib/Service/AutoConfig/IspDb.php#73	
2022-03-15T11:31:52+0100
Fehler	PHP	Error: simplexml_load_string(): Entity: line 17: parser error : EndTag: '&lt;/' not found at /var/www/nextcloud/apps/mail/lib/Service/AutoConfig/IspDb.php#73
```

This log continues (same problem type, but slightly different HTML Entities).

### Mail app version

1.11.7

### Mailserver or service

postfix & dovecot

### Operating system

Ubuntu 20.04.4 LTS

### PHP engine version

PHP 7.4

### Web server

Apache (supported)

### Database

PostgreSQL

**Comment by miaulalala** [comment]
Hey, I worked on the other ticket. I remember it well. Seems like the xml that is loaded for the auto configuration is either malformed. You could patch the line here
https://github.com/nextcloud/mail/blob/main/lib/Service/AutoConfig/IspDb.php#L74

log the XML or your could step through it with a debugger to see  what the get request is getting back from your mail endpoint.

**Comment by miaulalala** [comment]
Ok, so increasing the timeout time is one thing you could try. I would also recheck if your port is open / check your firewall configuration.

**Comment by CrazyFluffyPony** [comment]
Did not help, unfortunately.
I will close this issue for now. Thx for the help!
