### ISSUE TITLE
Can't save mail attachmentsto folder 

### ISSUE THREAD

**Issue by Olgsi** [nextcloud/mail#614]
### Steps to reproduce
1. open mail with attachment
2. save to folder
3. file is not in the folder (also after log out and in)

### Expected behaviour
The file should be displayed in the destination folder

### Actual behaviour
nextcloud told me "file is saved in folder" but i can't see anything in browser or iOS app

### Mail app

**Mail app version:** 0.7.4

**Mailserver or service:** own mail

**Transport security - IMAP:** imap SSL

**Transport security - SMTP:** smtp SSL

**Number of accounts:** one

### General server configuration

**Operating system:** Linux ha01s021 3.16.0-4-amd64 #1 SMP Debian 3.16.43-2+deb8u2 (2017-06-26) x86_64

**Web server:** Apache/2.4.10 (Debian) (cgi-fcgi)

**Database:** mysql 5.6.37

**PHP version:** 5.6.32
<details>
        <summary>PHP-modules loaded</summary>

### Client configuration

**Browser:** Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/62.0.3202.94 Safari/537.36

**Operating system:** YOUR ANSWER HERE

### Logs

<details>
        <summary>Web server error log</summary>

```
Insert your webserver log here
```
</details>

<details>
        <summary>Nextcloud log (data/nextcloud.log)</summary>

```
Insert your Nextcloud log here
```
</details>

<details>
        <summary>Browser log</summary>

```
Insert your browser log here, this could for example include:

a) The javascript console log
b) The network log
c) ...
```
</details>

**Operating system**:

**Web server:**

**Database:**

**PHP version:**

**Version:** (see admin page)

**Updated from an older version or fresh install:**

**List of activated apps:**

**Comment by alahwany** [comment]
same issue with me

**Comment by ChristophWurst** [comment]
Dup of https://github.com/nextcloud/mail/issues/588
