### ISSUE TITLE
Improve look of priority inbox

### ISSUE THREAD

**Issue by nimishavijay** [nextcloud/mail#6142]
### Is your feature request related to a problem? Please describe.

The priority inbox is the first thing we see when we open the Mail app, some design improvements could go a long way to make the Mail app more polished.

### Describe the solution you'd like

@jancborchardt and I worked on making some design changes that (hopefully) make the experience better.

| New priority inbox | Skeleton screen | No important mails |
| --- | --- | --- |
| ![image](https://user-images.githubusercontent.com/52440189/159458613-98761ab7-0b63-4e8e-ac6f-0c101a4399e5.png) | ![image](https://user-images.githubusercontent.com/52440189/159458957-889ddf51-23fc-4c5f-8727-1224d72526f9.png) | ![image](https://user-images.githubusercontent.com/52440189/159459103-719d3139-1750-43d9-9ca6-5f9d4a6850b6.png) |

Major changes:

- [x] Remove the "Favorite" section as it can be accessed from the navigation
- [x] Move the "New message" and "Refresh" button from top of navigation to top of the mail list #6774 
- [x] Instead of "Important and unread" show only all important mails (read and unread) as you can't access the important mails from anywhere -- what do you think? Many email clients allow different configurations of the inbox so it's not clear which is the most common one. 
- [x] Show more emails in the Important section --> if possible we could calculate the maximum number of mails that can be shown from the height of the viewport? 
- [x] Show skeleton screen while loading instead of the loading spinner
- [x] Hide *Important* section when it's empty
- [x] Show skeleton for the thread details. There shall be placeholders for the title, sender etc of a typical thread and *one message*

Minor changes:

- [x] - Change refresh icon to MDI `refresh`
- [x] - Left align the message shown when a section is empty
- [x] - Also change the text so that it is more helpful when there are no important mails 
- [x] "No messages" --> "Messages marked as important will show up here"
- [x] - Add icon and change alignment of "Load more"

What do you think?
cc @jancborchardt and @karlitschek 

### Additional context

(edit: decided with Jan that the collapsing of the important section is not necessary after all, and changed the screenshots to reflect that)

**Comment by thstyl2000** [comment]
You're doing a great work, but I've got to be honest: I haven't yet found a way to include 'Important' messages to my workflow....
I am personally using a tagging/folder system for my work account and a favorites/folder system for my personal email.

From this point of view, how about having no 'Imprtant' list, but only favorites, but the important emails get sorted on top?

**Comment by karlitschek** [comment]
Question: Why do we show the whole 'Important (i), Messages marked as important will show up here. Other:' block when there are no 'Important' messages. It would look a lot cleaner to hide this block if there is nothing to show anyways.

**Comment by ChristophWurst** [comment]
@karlitschek makes sense to hide the section indeed!

The (i) was added to explain why some messages show up in that section and not *Others*. But if nothing is in the section there is no good reason to show it. The user can't do anything with it.

**Comment by jancborchardt** [comment]
@karlitschek @ChristophWurst The intention is to showcase the feature. As a new user of Nextcloud Mail, you will not have any mails marked as priority, and thus "Priority inbox" would be 100% the same as "All inboxes". This note aims to make people aware that Mail has this capability and how to use it. Just to keep that in mind.

As mentioned in the past, it would be better if the empty state of priority inbox is not empty and if we just have some heuristics to support the manual setting of "Priority" (like mails sent _only_ to you), so it’s not a fully manual endeavor.

**Comment by ChristophWurst** [comment]
> As a new user of Nextcloud Mail, you will not have any mails marked as priority

You would.

We do have manual filtering for the so called *cold start*. That is, when there is too little data for the ML classifier to learn any user patterns. That means incoming emails get classified in every case.

Previously we showed *important and unread* in the first section. So it was very well possible that a user of the priority inbox would have no important **and** unread messages there at a time.

However, now that we want to show *all* important messages in the first section it would rarely be empty, unless a user marks all messages as not important or they turned off automatic classification.

**Comment by jancborchardt** [comment]
Ok, fine with hiding it then for the case it doesn't have content. :)

**Comment by ChristophWurst** [comment]
We have to revert https://github.com/nextcloud/mail/pull/7302

**Comment by ChristophWurst** [comment]
@GretaD all items are done, I think. Please double check.

**Comment by GretaD** [comment]
all items are done
