### ISSUE TITLE
Some icons are not changing to grey when in light theme

### ISSUE THREAD

**Issue by thstyl2000** [nextcloud/mail#6147]
### Steps to reproduce

1. Choose #FFFFFF as color in Admin settings -> Theme (Yes, it is extreme, but its looking/working great on devices with eink screens)
2. Go to mail app (obviously...)
3. Look at the "reply" and the "send" buttons.

### Expected behavior

Something like that:
![Screenshot_20220323_082056](https://user-images.githubusercontent.com/18458458/159644959-d7264195-f4ca-42da-bbd7-01d0d657b179.png)
Have letters in black but icons in grey (maybe...?)

### Actual behavior

The buttons look like that:

![Screenshot_20220323_081457](https://user-images.githubusercontent.com/18458458/159644609-360b92b3-cc54-431e-b98b-ecb79bafe0a9.png)
![Screenshot_20220323_081041](https://user-images.githubusercontent.com/18458458/159644729-e136452e-1c52-4168-ba9b-7501a735bddc.png)
(that's before adding a recipient)
![Screenshot_20220323_081007](https://user-images.githubusercontent.com/18458458/159644668-51d93f46-6167-4525-baa6-488058b416ad.png)
(and after adding one)

### Mail app version

1.11.7

### Operating system

freebsd

### PHP engine version

PHP 8.0

### Web server

Apache (supported)

### Database

MySQL

**Comment by ChristophWurst** [comment]
Tested and this seems to work well now
