### ISSUE TITLE
Mail App ignores autocomplete settings 

### ISSUE THREAD

**Issue by Honigbrot** [nextcloud/mail#6148]
### Steps to reproduce

1. Set "Allow sharing with groups" + "Restrict users to only share with users in their groups"
2. Set "Allow username autocompletion in share dialog" + "Allow username autocompletion to users within the same group"
3. Mail app autocompletes users from other groups and other groups
<img width="1061" alt="image" src="https://user-images.githubusercontent.com/34781745/159757384-d40f17a6-c1da-4266-aaa9-2e015986df00.png">
<img width="805" alt="image" src="https://user-images.githubusercontent.com/34781745/159759109-37b10c59-ec0d-415b-90dc-e9bcd05f01fc.png">

### Expected behavior

Isolate groups from others for privacy reasons. Still allow sharing and autocompletion within group

### Actual behavior

Mail app autocompletes other groups on the same instance and users from other groups, despite the admin sharing settings

### Mail app version

1.11.7

### PHP engine version

PHP 8.0

### Web server

Apache (supported)

### Database

MySQL

**Comment by ChristophWurst** [comment]
> ... in share dialog

:thinking:

**Comment by Honigbrot** [comment]
> > ... in share dialog
> 
> 🤔

I understand your confusion. But when enabling this option in the admin / Sharing Settings the Mail app autocompletes the individual users from other groups.

I can't seem to find separate settings for file sharing and mail.

**Comment by kesselb** [comment]
Hey @Honigbrot, thanks for your report.

We have a similar report over here: https://github.com/nextcloud/mail/issues/6017

Can you share some details how to reproduce it? 

> Mail app autocompletes other groups on the same instance and users from other groups, despite the admin sharing settings

I'd say when you enable sharing with groups it's expected to get auto completion for groups. Why would you expect something different?
