### ISSUE TITLE
Connecting a Microsoft 365 account throws PHP errors (pastebin)

### ISSUE THREAD

**Issue by JoeyEamigh** [nextcloud/mail#6149]
### Steps to reproduce

1. Create a new NextCloud instance (I am using UnRaid plugin with SQLite DB
2. Try to log into an O365 account under the connect your mail account page
3. See errors

### Expected behavior

The account to be connected to

### Actual behavior

[https://pastebin.com/RX5d1sEk](https://pastebin.com/RX5d1sEk) - This is the log of what happens when you attempt to log in.

I also have tried the manual set up with the settings my Exchange Admin Portal suggests, and I get a simple error about the authentication being denied, even though the password is correct.

### Mail app version

1.11.7

### Mailserver or service

Exchange

### Operating system

UnRaidOS 6.10.0-rc2 (kernel 5.14.15-Unraid) (https://github.com/linuxserver/docker-nextcloud/pkgs/container/nextcloud)

### PHP engine version

PHP 7.4

### Web server

Nginx

### Database

SQLite

### Additional info

Happy to provide more info! I just have no idea what could be useful in this situation. Thanks!

**Comment by joshtrichards** [comment]
Hi @JoeyEamigh - Are you still able to reproduce this today? There have been quite a few changes since your report. There's also some additional error reporting for xml that will help if you are still seeing the issue. Let us know.

Possibly related:  #5763, #5766, #6130
