### ISSUE TITLE
Can't download app from store, can't enable manually downloaded app

### ISSUE THREAD

**Issue by sdfg2** [nextcloud/mail#6168]
### Steps to reproduce

1. Doesn't show up in app list to install from store.
2. Download app and install manually
3. App shows up on list, can't enable

### Expected behavior

The app is installed

### Actual behavior

The app doesn't install or enable

### Mail app version

1.11.7

### Mailserver or service

n/a

### Operating system

Not installed, but it's goint to be arch

### PHP engine version

PHP 8.1

### Web server

Nginx

### Database

PostgreSQL

### Additional info

Nextcloud 23 installed via arch for php 8.1 support.  Yes I know it's not official but I was just wondering if there are any hidden php module requirements that I might not have enabled, I can't find any information about it.

**Comment by ChristophWurst** [comment]
It's likely because the app specifically says it doesn't work with php newer than 8.0. If you feel risky you can modify the appinfo/info.xml yourself. Otherwise you'll have to wait for https://github.com/nextcloud/mail/pull/6131.

**Comment by sdfg2** [comment]
I am so sorry, I thought I had searched everywhere for requirements, but I see it now.  My bad!
