### ISSUE TITLE
better tree view of folders

### ISSUE THREAD

**Issue by ftoledo** [nextcloud/mail#618]
### Steps to reproduce
1. Open mail app
2. View folders

### Expected behaviour
The folders must show as tree view
INBOX
    -- Archives
            ---- 2015
            ---- 2016
            ---- 2017

### Actual behaviour
Some folders do not show as treeview (see attach image)
INBOX.Archives.2015
INBOX.Archives.2016
INBOX.Archives.2017

### Mail app

**Mail app version:** 0.7.4

**Mailserver or service:** dovecot

**Transport security - IMAP:** SSL

**Transport security - SMTP:** TLS

**Number of accounts:** 2

### Server configuration

Running nextcloud 12.0.3 on Debian GNU/Linux Stretch with nginx

**Database:** Mysql

**PHP version:** PHP 5.6.30-0+deb8u1 (cli) (built: Feb  8 2017 08:50:21) 

**Version:** Nextcloud 12.0.3

**Updated from an older version or fresh install:** Upgrade from previous version

**List of activated apps:**
Enabled:
  - activity: 2.5.2
  - admin_notifications: 1.0.0
  - audioplayer: 2.2.1
  - calendar: 1.5.6
  - comments: 1.2.0
  - contacts: 2.0.1
  - dashboard: 4.0.5
  - dav: 1.3.0
  - deck: 0.2.7
  - federatedfilesharing: 1.2.0
  - federation: 1.2.0
  - files: 1.7.2
  - files_external: 1.3.0
  - files_markdown: 2.0.1
  - files_pdfviewer: 1.1.1
  - files_sharing: 1.4.0
  - files_texteditor: 2.4.1
  - files_trashbin: 1.2.0
  - files_versions: 1.5.0
  - files_videoplayer: 1.1.0
  - firstrunwizard: 2.1
  - gallery: 17.0.0
  - groupfolders: 1.1.0
  - logreader: 2.0.0
  - lookup_server_connector: 1.0.0
  - mail: 0.7.4
  - metadata: 0.6.0
  - music: 0.5.4
  - nextcloud_announcements: 1.1
  - notes: 2.3.1
  - notifications: 2.0.0
  - oauth2: 1.0.5
  - ojsxc: 3.3.1
  - password_policy: 1.2.2
  - provisioning_api: 1.2.0
  - serverinfo: 1.2.0
  - sharebymail: 1.2.0
  - spreed: 2.0.1
  - survey_client: 1.0.0
  - systemtags: 1.2.0
  - tasks: 0.9.5
  - theming: 1.3.0
  - twofactor_backupcodes: 1.1.1
  - updatenotification: 1.2.0
  - user_external: 0.4
  - workflowengine: 1.2.0
Disabled:
  - admin_audit
  - bruteforcesettings
  - encryption
  - telephoneprovider
  - user_ldap

#### Client configuration
**Browser:** Firefox 57

**Operating system:** Debian GNU/Linux

![recibidos ragnarok docksud com ar mail bbs cloud](https://user-images.githubusercontent.com/95441/32997464-364fa89c-cd6f-11e7-915f-a23439c5bf42.png)

**Comment by ChristophWurst** [comment]
We deliberately show only one level of subfolders.
cc @jancborchardt @skjnldsv

**Comment by jancborchardt** [comment]
Yeah, but this is no sublevel at all, as it looks like on the screenshot.

There should be an "Archive" entry with subfolders for the years. But might also be a mailserver issue cause it's a subfolder of Inbox?

**Comment by ftoledo** [comment]
Also, i use thunderbird and rainloop for same account and both render as expected (more screenshots)

If you need, i can provide detailed server setup to help to improve it. Anyway, it's a typical courier/postfix/mysql recipe on debian gnu/linux.

Thunderbird:
![pantallazo-2017-11-22 10-03-21](https://user-images.githubusercontent.com/95441/33129010-504b2db6-cf6d-11e7-9816-0ef682853de3.png)

Rainloop:
![19 ftoledo pressenter com ar buzon pressenter webmail](https://user-images.githubusercontent.com/95441/33129017-55107838-cf6d-11e7-9bb9-fac317106cb5.png)

Thanks!

**Comment by Hoeze** [comment]
Is there some update on this?
I just tried out the mail app and found the missing tree view.
This is a game stopper for me, since I organize everything with IMAP folders...
