### ISSUE TITLE
Automatic Signature below 

### ISSUE THREAD

**Issue by gerardoml** [nextcloud/mail#6188]
### Is your feature request related to a problem? Please describe.

I would like to have an automatic signature at the bottom of the text. 

### Describe the solution you'd like

**Something like this**
Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.

**"Thank you in advance." 
John Doe
+01 123456679**

### Describe alternatives you've considered

I haven´t considered any other solution

**Comment by max65482** [comment]
You should be able to do this in the account settings.
