### ISSUE TITLE
Account color indicator shows in priority inbox even if only 1 account is configured

### ISSUE THREAD

**Issue by jancborchardt** [nextcloud/mail#6191]
### Steps to reproduce

1. Have only 1 account in Mail
2. Check the Priority inbox
3. Notice a color line on the left (and the color line also shows for the "load more" action entry which seems off)

### Expected behavior

No color line on the left since it’s only 1 account.

### Actual behavior

This color line is shown on the left:
![image](https://user-images.githubusercontent.com/925062/162163916-a5ed636e-97c0-4ef8-85f6-c0cd5a60f363.png)

cc @ChristophWurst @karlitschek as we saw in the call. :)

### Mail app version

Current on cloud.nc.com

**Comment by ChristophWurst** [comment]
@JuliaKirschenheuter could have a look?
