### ISSUE TITLE
Disallow scheduled sending for instances using AjaxCron

### ISSUE THREAD

**Issue by miaulalala** [nextcloud/mail#6195]
### Is your feature request related to a problem? Please describe.

AjaxCron cannot reliably send outbox messages that are scheduled to be sent later.

Imagine a scenario of an office where nobody works on Saturday and Sunday but a message is to be sent on Sunday morning. The background job would not be triggered because there is no interaction with Nextcloud on Sunday.

Thus we should disable scheduled sending for instances that use AjaxCron.

### Describe the solution you'd like

1) scheduled sending is not shown as an option in the mail app
2) the admin backend shows the information on why the scheduled sending is disabled somewhere (possibly near the cron settings as we do for other stuff).

**Comment by st3iny** [comment]
I think adding a setup check would be a nice way to inform the admins. However, we missed the feature freeze for 24 as this needs to be implement in the server repo AFAIK.
