### ISSUE TITLE
Primary actions design issues

### ISSUE THREAD

**Issue by ChristophWurst** [nextcloud/mail#6201]
### Steps to reproduce

1. Open the actions menu of a message/thread

### Expected behavior

The three primary actions have the same width.

### Actual behavior

![Bildschirmfoto vom 2022-04-07 20-50-29](https://user-images.githubusercontent.com/1374172/162276423-6b36f8bd-e856-4090-a4c7-38b067d7d060.png)
![Bildschirmfoto vom 2022-04-07 20-50-21](https://user-images.githubusercontent.com/1374172/162276427-31e89e23-35f3-4532-8ab0-084ca44ed2ba.png)
![Bildschirmfoto vom 2022-04-07 20-50-18](https://user-images.githubusercontent.com/1374172/162276428-f1156918-2180-4404-86b1-bf8e05caa916.png)

### Mail app version

1.x

### Additional info

Ref https://github.com/nextcloud/mail/pull/6098

**Comment by JuliaKirschenheuter** [comment]
@ChristophWurst i have discussed this issue with @jancborchardt, as i've implemented it. To have a same width for primary actions i have to do a some fix width for them. And it is not always helpful for different languages (because the title will be either cut or have a second line).

@jancborchardt told that is is ok, how it is looks like. Is there some new info?
@ChristophWurst, @jancborchardt please reply

**Comment by ChristophWurst** [comment]
If this is intended then I'm okay with it. I'm not a designer. It's just that something makes this UI look unpolished. Maybe @nimishavijay can share a secondary opinion? :)

**Comment by nimishavijay** [comment]
Yes, we had discussed this. We thought we could calculate the width of the button with the longest text, and use that length for all the buttons, but turns out it's too difficult, so we decided to keep it this way :) 

If it is possible to adjust the width of the buttons considering all languages and lengths of text without any fancy javascript stuff then I think we should totally do it like that :)

**Comment by ChristophWurst** [comment]
![Bildschirmfoto vom 2022-05-16 08-18-39](https://user-images.githubusercontent.com/1374172/168539716-e70bf572-d538-41dc-bf95-022cde45540c.png)

I can't help it but something feels off with this new menu. Do we need larger icons? Some breathing space somewhere? A rounded background like in https://github.com/nextcloud/mail/issues/6200#issuecomment-1108416443?

**Comment by JuliaKirschenheuter** [comment]
>  A rounded background like in [#6200 (comment)](https://github.com/nextcloud/mail/issues/6200#issuecomment-1108416443)?

I'm not sure, that rounded background would help (it looks nice, but we should rethink a way of positioning). My suggestion: leave only icons, without text, text put into ```<aria-label>```. And change icons depends on the state (read - unread)

**Comment by jancborchardt** [comment]
It's also possible that now that actions can't have the whole width, we need to make sure translations cut their wording down too, like we did from "Mark as read" to "Read" etc.

Going icon-only is not really user-friendly, especially the "Important" icon is not common. Before we end up going that route, I'd say going back to putting the top 3 normally in the list is better. (But not before we tried the text cutting in translations.)

**Comment by JuliaKirschenheuter** [comment]
> It's also possible that now that actions can't have the whole width, we need to make sure translations cut their wording down too, like we did from "Mark as read" to "Read" etc.

Hm, how could we influence translations in this special case?

> Going icon-only is not really user-friendly, especially the "Important" icon is not common. 

Ok

**Comment by ChristophWurst** [comment]
We have to adjust the English text and hope that the translations are also short.

We will likely run into strangely translated strings for some languages, though. Like the English *Read* will likely be translated to *Lesen* or *Gelesen* for German.

https://cdn.vox-cdn.com/uploads/chorus_asset/file/20032761/Hey_image_2.png they do something similar and it looks "designed".

**Comment by ChristophWurst** [comment]
I'm experiment with more modern, consistent icon design. I think this looks a bit more "designed" than what we currently have:


| Before | After |
|--------|-------|
| ![Bildschirmfoto vom 2022-05-17 15-07-09](https://user-images.githubusercontent.com/1374172/168818058-b278adb0-065d-4e9b-86c8-b9034938b450.png) | ![Bildschirmfoto vom 2022-05-17 15-05-29](https://user-images.githubusercontent.com/1374172/168818105-3bd36087-19fc-42f2-9fab-13f32fed0a37.png) |

Please ignore the other missing icons. This problem is tracked in https://github.com/nextcloud/mail/issues/6478.

**Comment by jancborchardt** [comment]
@ChristophWurst nice, good stuff on using Material Design icons. Rounded corners also look good, but should then be done consistently in the menu entries below, as well as on the menu itself → @nimishavijay you mocked that up somewhere but I can’t find it, could you link it? :)

**Comment by ChristophWurst** [comment]
https://github.com/nextcloud/mail/issues/6200#issuecomment-1108416443.

I know those things are not tightly related, hence the two screenshots. But I'd push to get there soon.

**Comment by ChristophWurst** [comment]
Things are round now and look a lot better.
