### ISSUE TITLE
Floating mailbox/outbox loading animation

### ISSUE THREAD

**Issue by ChristophWurst** [nextcloud/mail#6205]
### Steps to reproduce

1. Open the outbox

### Expected behavior

A loading spinner in the center of the center column.

### Actual behavior

![Bildschirmfoto vom 2022-04-07 21-28-36](https://user-images.githubusercontent.com/1374172/162281583-fd32cd42-252a-47b2-b5ce-5641b4169444.png)

### Mail app version

1.x

**Comment by st3iny** [comment]
This also applies to every other mailbox.
