### ISSUE TITLE
Single letter avatars are not centered

### ISSUE THREAD

**Issue by ChristophWurst** [nextcloud/mail#6206]
### Steps to reproduce

1. Write a message to "c" (invalid recipient)
2. See the message fail, but ignore this
3. Go to the outbox

### Expected behavior

The "C" is centered.

### Actual behavior

![Bildschirmfoto vom 2022-04-07 21-33-31](https://user-images.githubusercontent.com/1374172/162282353-9f63fc80-0b69-4dab-afee-775b5b3f4053.png)

### Mail app version

1.12

**Comment by JuliaKirschenheuter** [comment]
@ChristophWurst i have checked it, and can not reproduce it. In my opinion there are centered (tested in Chrome + Firefox) 

![image](https://user-images.githubusercontent.com/6078378/165064326-9901871d-67c0-4a2b-9397-2abaa9e63573.png)
![image](https://user-images.githubusercontent.com/6078378/165064463-453d8287-84c9-4bc3-ab5b-f44b5c4910dd.png)
![image](https://user-images.githubusercontent.com/6078378/165064621-54ff1af0-f997-4839-bbdc-4a3db271960c.png)
![image](https://user-images.githubusercontent.com/6078378/165064718-2b57c0c4-218c-4c0e-ba86-c7422486413d.png)

**Comment by miaulalala** [comment]
i also can't reproduce (brave, chrome, ff)

**Comment by ChristophWurst** [comment]
![Bildschirmfoto vom 2022-04-29 11-20-56](https://user-images.githubusercontent.com/1374172/165917977-350f1f37-a466-4732-8682-451e2421f0d5.png)

looks good indeed
