### ISSUE TITLE
Account creation dialogue succeeds but redirect to /apps/mail/box fails as accountId is 0

### ISSUE THREAD

**Issue by miaulalala** [nextcloud/mail#6212]
### Steps to reproduce

1. add new account from setup dialogue
2. observe success response:
``` JSON
{
    "status": "success",
    "data": {
        "id": 3206,
        "accountId": 3206,
        "name": "admin",
        "order": null,
        "emailAddress": "--------@@gmx.net",
        "imapHost": "imap.gmx.net",
        "imapPort": 993,
        "imapUser": "--------@gmx.net",
        "imapSslMode": "ssl",
        "signature": null,
        "editorMode": null,
        "provisioningId": null,
        "showSubscribedOnly": false,
        "personalNamespace": null,
        "draftsMailboxId": null,
        "sentMailboxId": null,
        "trashMailboxId": null,
        "sieveEnabled": false,
        "signatureAboveQuote": false,
        "smtpHost": "mail.gmx.net",
        "smtpPort": 465,
        "smtpUser": "--------@@gmx.net",
        "smtpSslMode": "ssl"
    }
}
```
3. Observe redirect to `http://nextcloud.local/index.php/apps/mail/api/mailboxes?accountId=%7BaccountId%7D` which will present an error like the account creation failed (will show an error below the account from). Looks like the query string parameters are not resolved properly: `accountId: {accountId}`
4. try to reaload the mail app
5. the account was indeed created

### Expected behavior

If the account creation is successful I am redirected to my new mailbox

### Actual behavior

The redirect fails and it looks like the account creation didn't succeed.

### Mail app version

1.12.0-alpha.4

### Mailserver or service

GMX

### Operating system

Ubuntu 20

### PHP engine version

PHP 8.0

### Web server

Apache (supported)

### Database

MySQL

**Comment by ChristophWurst** [comment]
This only happens with manual setup.
