### ISSUE TITLE
Mail awfully slow when editing very long messages

### ISSUE THREAD

**Issue by StCyr** [nextcloud/mail#6222]
### Steps to reproduce

1. Have a message with a lot of text (like 1000+ lines or 10.000+ characters);
2. Edit it (forward or reply to it);
3. Write some text

### Expected behavior

Editing the mail should be swift

### Actual behavior

Mail becomes slow to death

### Mail app version

1.11.7

### Mailserver or service

Self-hosted postfix/dovecot

### Operating system

Debian 11

### PHP engine version

PHP 7.4

### Web server

Apache (supported)

### Database

MariaDB

**Comment by StCyr** [comment]
Maybe caused by CKEditor => https://github.com/ckeditor/ckeditor5-vue/issues/42

**Comment by StCyr** [comment]
2 observations from the https://github.com/ckeditor/ckeditor5-vue/issues/42 issue:

1. The issue seems correlated with the number of top-level elements (see See also https://github.com/ckeditor/ckeditor5-vue/issues/42#issuecomment-773005455). With Mail inserting lots of &nbsp when replying/forwarding a message, this could worsen the situation.

Excerpt of a message replied from Mail showing a single paragraph and the number of &nbsp elements inserted:

```
<p style="margin:0cm">&nbsp;<o:p></o:p></p>
<p style="margin:0cm">&nbsp;<o:p></o:p></p>
<p style="margin:0cm">&nbsp;<o:p></o:p></p>
<p style="margin:0cm">&nbsp;<o:p></o:p></p>
<p style="margin:0cm">&nbsp;<o:p></o:p></p>
<p style="margin:0cm">&nbsp;<o:p></o:p></p>
<p style="margin:0cm">&nbsp;<o:p></o:p></p>
<p style="margin:0cm">Some additional questions:<o:p></o:p></p>
<p style="margin:0cm">&nbsp;<o:p></o:p></p>
<p style="margin:0cm">&nbsp;<o:p></o:p></p>
<p style="margin:0cm">&nbsp;<o:p></o:p></p>
```

2. It seems the issue could be limited by adding some debouncing. See also https://github.com/ckeditor/ckeditor5-vue/issues/42#issuecomment-773005455

**Comment by GretaD** [comment]
i tried this with different scenarios and its not happening anymore. We can open it again if its reported again. But for now i would close it.
