### ISSUE TITLE
Missing close or choose button in file picker dialog since 0.7.5

### ISSUE THREAD

**Issue by onny** [nextcloud/mail#626]
Hey,
the file picker dialog is missing a close or save button:
![2017-11-22-125411_swaygrab](https://user-images.githubusercontent.com/757752/33126343-747aa31c-cf84-11e7-94ac-efb245416502.png)
But maybe this is related to core?
I'm using Nextcloud Beta 13 and the latest mail app (from git).

Best regards,
Jonas

**Comment by ChristophWurst** [comment]
> But maybe this is related to core?

Yup, that is part of the Nextcloud server. Could you please file a ticket in the server repo? We should fix that for the nc13 release.

Thanks for reporting.

**Comment by ChristophWurst** [comment]
As discovered in https://github.com/nextcloud/server/issues/7282, these bugs seem only to occur in this app.

@skjnldsv @jancborchardt any idea what's wrong? Could one of you have a look? Thanks.

![bildschirmfoto von 2017-11-27 08-35-19](https://user-images.githubusercontent.com/1374172/33255573-9ebf825a-d34e-11e7-8639-218faff554ea.png)

**Comment by laurentiu2** [comment]
Same here, NC 12.0.3
![screen shot 2017-11-27 at 8 25 27 pm](https://user-images.githubusercontent.com/29857699/33282394-31a7967c-d3b1-11e7-9615-2825ca05ff78.png)

**Comment by pixelipo** [comment]
Updated the title since this affects both NC12 and NC13

**Comment by buttle** [comment]
What a pity the app can 'break' in such a way.

**Comment by ChristophWurst** [comment]
> What a pity the app can 'break' in such a way.

But hey, it's open source and I encourage anybody interested in taking a look at the source code and trying to fix it so that we have a working filepicker again 😉 

Do you know js?

I already gave it a shot but couldn't figure out what's been broken. Hence this will remain unfixed until someone jumps in and has a closer look.

**Comment by buttle** [comment]
I know a little js. But I don't have much time on my hands, unfortunately.

**Comment by pixelipo** [comment]
@ChristophWurst I can't test since I'm unable to set up Mail locally, but I see this issue popping up in console:
`TypeError: this._setOptionDisabled is not a function build.js:20:4462`

Since `_setOption` in **core/js/jquery.ocdialog.js** is responsible for painting missing DOM elements, it seems probable that there is some conflict there... Maybe one of the vendor JS is overriding this?

**Comment by ChristophWurst** [comment]
> @ChristophWurst I can't test since I'm unable to set up Mail locally, but I see this issue popping up in console:

Let me know where you've got stuck. How did you set it up?

> Since _setOption in core/js/jquery.ocdialog.js is responsible for painting missing DOM elements, it seems probable that there is some conflict there... Maybe one of the vendor JS is overriding this?

Good hint. We're shipping jquery ui with this app too, maybe that's the problem.

**Comment by ChristophWurst** [comment]
> Since _setOption in core/js/jquery.ocdialog.js is responsible for painting missing DOM elements, it seems probable that there is some conflict there... Maybe one of the vendor JS is overriding this?

Bingo! `$.ui.version` returns `0.10.0` when I browse the files app, but `0.12.1` when browsing the mail app's page. So jquery-ui registers itself on the global jquery somehow. Awesome, right? ☹️

**Comment by buttle** [comment]
Can you just do away with the jquery you ship?

**Comment by pixelipo** [comment]
If You're talking about jQuery library, then ye, of course.
If you're referring to the code that applies SVG filters in IE, then no - we definitely need to write some. It doesn't have to be written with jQuery, but it will probably be easiest way.

**Comment by pixelipo** [comment]
Sorry, ignore me - wrong thread...

**Comment by ChristophWurst** [comment]
One possible solution would be to not use the [global jQuery](https://github.com/nextcloud/mail/blob/master/js/jquery.js) but or own. We'd have to set up the ajax core to use the nc request token but other than that it should work and prevent overriding jquery-ui in the global namespace.

**Comment by buttle** [comment]
Without knowing the code, it seems to make more sense to use the global library as it is already there, globally. (my 2 cents)

**Comment by ChristophWurst** [comment]
With knowing the code, it's necessary for apps to ship certain deps as the ones in the global namespace are pretty much outdated.

**Comment by ChristophWurst** [comment]
@buttle to give you a bit more context: the main problem here is that if you write a front-end app for Nextcloud you either rely on the libraries already available in the Nextcloud server or ship your own. The former seems easy, but the dependency of your code on those libraries become unclear. Can you expect the libs to keep a stable API, as in they don't break on upgrades? What if I pull in an additional library, that depends on one of those already available ones - how do I know those versions are compatible? Based on that, it's also really hard to update the server libraries as it might break apps. And thus, historically, those libs weren't really touched unless it was really necessary.
If you take the second approach of shipping your own libs, you're *completely* independent. You know which version you've got and nobody can change that. They are the exact same, no matter where you deploy the app and no matter which other apps are loading arbitrary script on a Nextcloud page. While it sounds like a bit of overhead using multiple version of the same lib, tools like webpack are really good at compressing js code and thus the app's js bundle is relatively small.

I hope that sheds some light on the situation and why I'm not blindly removing jquery-ui from this app.

**Comment by pixelipo** [comment]
I really hope we can ditch jquery-ui soon...

**Comment by ChristophWurst** [comment]
Not fully fixed yet.

**Comment by schmitzerwien** [comment]
Ok thanks :-)

**Comment by ChristophWurst** [comment]
On my local setup this was somehow resolved. Please let me know if it's also fixed for you with the latest mail release. Thanks.

**Comment by pixelipo** [comment]
Wasn't working in 0.7.7, fixed in 0.7.8 :+1:
