### ISSUE TITLE
Defect PDF Attachment

### ISSUE THREAD

**Issue by seorasC** [nextcloud/mail#627]
I got an email with pdf-attachment. I can‘t open it in Nextcloud Mail. I can open it in Thunderbird. When I save the attachment in Thunderbird and in Nextcloud Mail the saved files are not the same. There is a difference already in the size of the pdf-file. The file saved with Thunderbird get opened, the other not. The same in Rainloop.

Nextcloud 12.0.3
Mail 0.7.4
Rainloop 5.0.3
PHP 7.0.19
Debian Stretch

**Comment by ChristophWurst** [comment]
Anything in your logs? Can you share the file?

**Comment by seorasC** [comment]
The file I send:
1.) Export with Thunderbird
[Nextcloud Mail Admin Documentation-Thunderbird Export.pdf](https://github.com/nextcloud/mail/files/1499078/Nextcloud.Mail.Admin.Documentation-Thunderbird.Export.pdf)
2.) Export with Nextcloud/Mail (The original name was only "2", I added ".pdf")
[2.pdf](https://github.com/nextcloud/mail/files/1499092/2.pdf)
 The log File:

Log-File -> begin
{"reqId":"CykYmebWLoCvr7zN2PCk","level":3,"time":"2017-11-23T12:45:07+00:00","remoteAddr":"<IP>","user":"<username>","app":"PHP","method":"GET","url":"\/index.php\/apps\/mail\/api\/accounts\/1\/folders\/SU5CT1g=\/messages\/29532\/attachment\/1.2","message":"Invalid argument supplied for foreach() at \/var\/www\/nextcloud\/apps\/mail\/lib\/Attachment.php#113","userAgent":"Mozilla\/5.0 (X11; Linux x86_64; rv:52.0) Gecko\/20100101 Firefox\/52.0","version":"12.0.3.3"}
{"reqId":"WuiNvgoeDFSnDbbhWkKD","level":3,"time":"2017-11-23T12:46:24+00:00","remoteAddr":"<IP>","user":"<username>","app":"PHP","method":"GET","url":"\/index.php\/apps\/mail\/api\/accounts\/1\/folders\/SU5CT1g=\/messages\/29518\/attachment\/2","message":"Invalid argument supplied for foreach() at \/var\/www\/nextcloud\/apps\/mail\/lib\/Attachment.php#113","userAgent":"Mozilla\/5.0 (X11; Linux x86_64; rv:52.0) Gecko\/20100101 Firefox\/52.0","version":"12.0.3.3"}
<- Log-File end

**Comment by ChristophWurst** [comment]
> Invalid argument supplied for foreach() at /var/www/nextcloud/apps/mail/lib/Attachment.php#113

Voilà: https://github.com/nextcloud/mail/blob/d25e0a56f760b5ce37f503367335c531afb5ad68/lib/Attachment.php#L113

That's where it fails. Not sure why though.

**Comment by seorasC** [comment]
Sorry, I'm not a software developer, I'm only a user! What does it mean? What happend next?

**Comment by ChristophWurst** [comment]
I don't know yet. May I ask you to fill out the full issue template you've been asked to fill out when you created this ticket? You can find it [here](https://raw.githubusercontent.com/nextcloud/mail/master/.github/issue_template.md). Thanks.

Next time please fill it out right away 😉

**Comment by ChristophWurst** [comment]
No info provided -> closing
