### ISSUE TITLE
Add Outbox Description in rightmost column

### ISSUE THREAD

**Issue by miaulalala** [nextcloud/mail#6270]
### Steps to reproduce

1. Open a outbox folder.
2. See that the content (third column) is empty. 

### Expected behavior

The content should include a message "Pending or not sent messages will show up here".

### Actual behavior

Content is empty.
![image](https://user-images.githubusercontent.com/6078378/166928036-cb155749-9d87-40fc-ab93-e1383d830136.png)

### Mail app version

1.12.0

### Mailserver or service

Not relevant

### Operating system

Not relevant

### PHP engine version

Not relevant

### Web server

Not relevant

### Database

Not relevant

### Additional info

Not relevant

**Comment by GretaD** [comment]
@miaulalala this ticket is about showing a default text, right?

**Comment by ChristophWurst** [comment]
It's about the third column. It's always empty right now.

**Comment by GretaD** [comment]
> It's about the third column. It's always empty right now.

yes i know, but it should show the default text that anna has written on the description, or that the pending message itself should be shown there, like other normal messages?

**Comment by ChristophWurst** [comment]
It should show the text. Messages are opened in the modal.
