### ISSUE TITLE
Unsubscribe option for "Favourites" folder should be hidden

### ISSUE THREAD

**Issue by miaulalala** [nextcloud/mail#6296]
### Steps to reproduce

1. Try unsubscribing from mailbox "Favourites"
2. Frontend gets confused and throws an error

### Expected behavior

No unsubscribe option is offered as it's not a real mailbox.

### Actual behavior

The unsubscribe option is offered and errors out.

### Mail app version

1.11.6

### Mailserver or service

no info

### Web server

Apache (supported)

### Database

MariaDB

**Comment by ChristophWurst** [comment]
We don't have https://github.com/nextcloud/mail/issues/6073 yet so I suppose this is about the *Sync in background* checkbox, right?
