### ISSUE TITLE
Cannot Create any new email or use the mailServer with NEXTCLOUD

### ISSUE THREAD

**Issue by JoyX2** [nextcloud/mail#6303]
### Steps to reproduce

I have NextCloud 23.0.0.3 with a Mailserver using PostFix and Dovecut  and SSL (certbot.eff).

 I followed this guide [>>thisGuide<<](https://www.server-world.info/en/note?os=Ubuntu_20.04&p=nextcloud&f=7) in the installation process.

I followed it step by step but the issue appeared on the last step while I'm trying to create a new email to the server

config.php

> <?php
> $CONFIG = array (
>   'debug' => true,
>   'instanceid' => '***************************',
>   'passwordsalt' => '**************************************',
>   'secret' => '***********************************************************',
>   'trusted_domains' => 
>   array (
>     0 => '<SERVER_IP_ADDRESS>',
>     1 => '<DOMAIN>',
>   ),
>   'datadirectory' => '/var/www/nextcloud/data',
>   'dbtype' => 'mysql',
>   'version' => '23.0.3.2',
>   'overwrite.cli.url' => 'http://<SERVER_IP_ADDRESS>',
>   'dbname' => '**********',
>   'dbhost' => 'localhost',
>   'dbport' => '',
>   'dbtableprefix' => '**_',
>   'mysql.utf8mb4' => true,
>   'dbuser' => '***********',
>   'dbpassword' => '************',
>   'installed' => true,
>   'memcache.local' => '\\OC\\Memcache\\APCu',
>   'default_phone_region' => 'US',
>   'mail_from_address' => 'noreply',
>   'mail_smtpmode' => 'smtp',
>   'mail_sendmailmode' => 'smtp',
>   'mail_domain' => '<DOMAIN>',
>   'mail_smtphost' => 'smpt.<SERVER_IP_ADDRESS>',
>   'app_install_overwrite' => 
>   array (
>     0 => 'mindmap_app',
>   ),
>   'mail_smtpport' => '25',
>   'mail_smtpsecure' => 'ssl',
> );
details i add to the new email 
https://ibb.co/xFbtgK5

I've also tried different names and simpler passwords and more complex once, they all endup the same way
I checked all the required ports  I cant find any issue and as for now`ufw` is not active.

### Expected behavior

Email being created

### Actual behavior

> reating account failed:Connection to IMAP at <DOMAIN>:993 failed. Authentication failed.

on horde_imap.log 
>> Connection to: imap://<DOMAIN>:993/
>> Server connection took 0.0132 seconds.
S: * OK [CAPABILITY IMAP4rev1 SASL-IR LOGIN-REFERRALS ID ENABLE IDLE LITERAL+ AUTH=PLAIN AUTH=LOGIN] Dovecot (Ubuntu) ready.
C: 1 AUTHENTICATE PLAIN [INITIAL CLIENT RESPONSE (username: noreply@<DOMAIN>)]
S: 1 NO [AUTHENTICATIONFAILED] Authentication failed.
>> Command 1 took 3.1667 seconds.
C: 2 LOGIN noreply@<DOMAIN> [PASSWORD]
>> Slow Command: 5.005 seconds
>> ERROR: read/timeout error.
S: 2 NO [AUTHENTICATIONFAILED] Authentication failed.
>> Command 2 took 7.7852 seconds.

and the NextCloud.log

> {"reqId":"*************","level":3,"time":"2022-04-26T00:34:45+00:00","remoteAddr":"**************","user":"**********","app":"mail","method":"POST","url":"/index.php/apps/mail/api/accounts","message":"Creating account failed: Connection to IMAP at <DOMAIN>:993 failed. Authentication failed.","userAgent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/100.0.4896.127 Safari/537.36","version":"23.0.3.2"}

### Mail app version

Latest, I've downloaded it today

### Mailserver or service

my own mailserver using postfix

### Operating system

ubuntu 20.04

### PHP engine version

PHP 7.4

### Web server

Apache (supported)

### Database

MariaDB

**Comment by ChristophWurst** [comment]
the login operation timed out

try increasing https://github.com/nextcloud/mail/blob/main/doc/admin.md#imap-timeout to 10

**Comment by JoyX2** [comment]
> the login operation timed out
> 
> try increasing https://github.com/nextcloud/mail/blob/main/doc/admin.md#imap-timeout to 10

already did that, i made it 30 just to be sure
`'app.mail.imap.timeout' => 30`

i have also removed TLS just for testing.
`'app.mail.verify-tls-peer' => false`

Horde's log
------------------------------
```
>> Tue, 26 Apr 2022 01:50:47 +0000
>> Connection to: imap://xxxxx.xxx:993/
>> Server connection took 0.0139 seconds.
S: * OK [CAPABILITY IMAP4rev1 SASL-IR LOGIN-REFERRALS ID ENABLE IDLE LITERAL+ AUTH=PLAIN AUTH=LOGIN] Dovecot (Ubuntu) ready.
C: 1 AUTHENTICATE PLAIN [INITIAL CLIENT RESPONSE (username: noreply@xxxxxx.xxx)]
S: 1 NO [AUTHENTICATIONFAILED] Authentication failed.
>> Command 1 took 3.9005 seconds.
C: 2 LOGIN noreply@xxxxxx.xxxx [PASSWORD]
>> Slow Command: 7.826 seconds
S: 2 NO [AUTHENTICATIONFAILED] Authentication failed.
>> Command 2 took 7.8264 seconds.
```
NextCloud's log

```
{"reqId":"xxxxxxxxxxxxxxxxx","level":3,"time":"2022-04-26T01:50:59+00:00","remoteAddr":"xxxx.xxxxx.xxxxx.xxxx","user":"xxxxxxx","app":"mail","method":"POST","url":"/index.php/apps/mail/api/accounts","message":"Creating account failed: Connection to IMAP at xxxxxxx.xxxx:993 failed. Authentication failed.","userAgent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/100.0.4896.127 Safari/537.36","version":"23.0.3.2"}
```

**Comment by JoyX2** [comment]
I have noticed that if I go to my domain www.example.com  it fails to load everything even though my apache settings were suppose to redirect all traffic to ssl ( certbot)

![image](https://user-images.githubusercontent.com/101886922/165257644-204fa0e5-de8e-4530-b827-a3db393e21d9.png)


here is my current apache conf 

```
<IfModule mod_ssl.c>
<VirtualHost *:80> 
  ServerName example.com
  ServerAlias www.example.com

  Redirect permanent / https://example.com/
</VirtualHost>

<VirtualHost *:443>
    DocumentRoot "/var/www/nc"
    ServerName localhost

    Protocols h2 http/1.1

    <Directory "/var/www/nc">
        Options MultiViews FollowSymLinks
        AllowOverride All
        Order allow,deny
        Allow from all
    </Directory>


    TransferLog /var/log/apache2/apacheLog.log
    ErrorLog /var/log/apache2/apacheErrorLog.log
Header always set Strict-Transport-Security "max-age=15552000;includeSubDomains"

RewriteEngine on
RewriteCond %{SERVER_NAME} =localhost [OR]
RewriteCond %{SERVER_NAME} =example.com
RewriteRule ^ https://%{SERVER_NAME}%{REQUEST_URI} [END,NE,R=permanent]

SSLCertificateFile /etc/letsencrypt/live/example.com/fullchain.pem
SSLCertificateKeyFile /etc/letsencrypt/live/example.com/privkey.pem
Include /etc/letsencrypt/options-ssl-apache.conf

</VirtualHost>
</IfModule>
```

**Comment by ChristophWurst** [comment]
> S: 1 NO [AUTHENTICATIONFAILED] Authentication failed.

Check your IMAP username and password.

**Comment by JoyX2** [comment]
> > S: 1 NO [AUTHENTICATIONFAILED] Authentication failed.
> 
> Check your IMAP username and password.

how to check them ? I'm creating a new email account ??
also I have tried to create different Emails and with a different password combination
```
aaaa@example.com  - TestTest@123123 - TestTest@123123TestTest@123123
noreply@example.com -TestTest123123  - TestTest123123TestTest123123 
test2@example.com - testtest123123 - testtest123123testtest123123
```
it always fails

**Comment by ChristophWurst** [comment]
you need an existing IMAP account on your server. you do *not* create a new one here. you *connect* an existing one.

**Comment by JoyX2** [comment]
> you need an existing IMAP account on your server. you do _not_ create a new one here. you _connect_ an existing one.

well, I have just created the server, I don't think I have any existing one from the that domain.
do you mean, I can connect an email that I already have from a different provider (ex: gmail) here ?

**Comment by ChristophWurst** [comment]
yes.

If you have any other questions please open a topic at https://help.nextcloud.com/c/support/7. The Github tracker is for bugs :)
