### ISSUE TITLE
Draft encoding issues (make drafts unusable)

### ISSUE THREAD

**Issue by jancborchardt** [nextcloud/mail#632]
### Steps to reproduce
1. Write a draft
2. Do something else
3. Open the draft again

### Expected behaviour
The existing characters should be saved in plain text and things shouldn’t be mangled.

### Actual behaviour

Say this is the original text in the reply:
```
> http://wikimedia.de
> 
```

Opening the draft looks like this:
```
&gt; <a href="http://wikimedia.de" rel="noreferrer noopener" target="_blank">wikimedia.de</a>
&gt; 
```

And it gets worse every time you open it again:
```
&amp;gt; &lt;a href="<a href="http://wikimedia.de" rel="noreferrer noopener" target="_blank">wikimedia.de</a>" rel="noreferrer noopener" target="_blank"&gt;<a href="http://wikimedia.de" rel="noreferrer noopener" target="_blank">wikimedia.de</a>&lt;/a&gt;
&amp;gt; 
```

### Mail app

**Mail app version:** latest

Let me know if any of the other things are relevant, but it doesn’t seem like it.

**Comment by alexanderdd** [comment]
Can confirm. I just stumbled over this, too.

**Comment by ChristophWurst** [comment]
I'm closing this ticket because it hasn't received any updates in a long time. If this is still relevant, feel free to re-open or file a new ticket.

Thank you.
