### ISSUE TITLE
Emails appear as High Priority randomly in Thunderbird now

### ISSUE THREAD

**Issue by MenooMeow** [nextcloud/mail#6320]
### Steps to reproduce

1.  Configure Nextcloud Mail to use IMAP account.
2.  Use connected account normally.
3.  Observe a totally separate Thunderbird installation now display some messages in Red (High Importance).

### Expected behavior

Nextcloud Mail should not be tagging email as high priority on its own (assuming that is the case).

### Actual behavior

In thunderbird, some emails appear as high priority across different accounts.  I am using 10 different IMAP accounts.  They all started exhibiting this behavior after using Nextcloud Mail with these IMAP accounts.

### Mail app version

1.11.7

### Mailserver or service

private IMAP

### Operating system

Nextcloud via Linux VM

### PHP engine version

PHP 7.4

### Web server

Apache (supported)

### Database

MySQL

**Comment by pierre-alain-b** [comment]
I guess you can inactivate the classification by unchecking this checkbox: 

![image](https://user-images.githubusercontent.com/386857/198930445-9c0ee491-e1d3-4b29-a8ca-43cd475241a3.png)

**Comment by ChristophWurst** [comment]
Yes, that is the solution @pierre-alain-b. The classification uses the IMAP message label `$label1` that other clients also use to mark *important* messages. So the interoperability means that messages tagged as important by Mail (automatically) means they will also show as important in other clients like Thunderbird and Apple Mail.
