### ISSUE TITLE
No way to view email list on iPad horizontal orientation

### ISSUE THREAD

**Issue by MenooMeow** [nextcloud/mail#6321]
### Steps to reproduce

1.  Use Nextcloud mail normally
2.  Back button that appears on top left does not appear.
3.

### Expected behavior

In portrait mode, the browser displays a back icon in the message which allows you to see the listing of emails.  

This interface needs to be thought out a bit more.  When you click on the Inbox folder of a mail account, you should always see a list of emails, not a specific email.  On iPads, this is what currently happens.  On desktop clients, it shows the list of mailboxes, a list of emails, and a specific email.  This is more conventional to Thunderbird and Outlook.  But an iOS browser render skips the listing of emails altogether, making navigation impossible.

### Actual behavior

Button to access list of emails in that mailbox does not appear in landscape mode.  

### Mail app version

1.11.7

### Mailserver or service

personal IMAP

### Operating system

Linux Nextcloud VM (Hansson?)

### Web server

Apache (supported)

### Database

MySQL

**Comment by ChristophWurst** [comment]
This should be fixed with the new layout modes of the app.
