### ISSUE TITLE
All Inboxes view completely fails

### ISSUE THREAD

**Issue by MenooMeow** [nextcloud/mail#6322]
### Steps to reproduce

1.  Add 10 IMAP accounts.
2.  Click/tap on All Inboxes
3.  Endlessly says "loading messages"

### Expected behavior

Instantly displays a merged readout of all unread emails across all mapped IMAP mailboxes.

### Actual behavior

Generally shows "Loading messages" forever.

### Mail app version

1.11.7

### Mailserver or service

personal IMAP

### Operating system

Linux Nextcloud VM (Hansson?)

### PHP engine version

PHP 7.4

### Web server

Apache (supported)

### Database

MySQL

### Additional info

Individual mailbox Inbox folders do work.

**Comment by ChristophWurst** [comment]
Closing as stale.

If it happens again please make sure to capture the browser console.log and the nextcloud.log.
