### ISSUE TITLE
Outbox message edits are not automatically saved

### ISSUE THREAD

**Issue by GretaD** [nextcloud/mail#6330]
### Steps to reproduce

1. Open an existing outbox message
2. Type something else on the body or change to/cc
3. Close the modal
4. Open again and see if you see what you typed last

### Expected behavior

My new changes are shown

### Actual behavior

No changes are shown

### Mail app version

latest

**Comment by JuliaKirschenheuter** [comment]
Thanks for opening this bug. As i fixed this bug: #5908 i have already recognized that problem, which you have described here. #5908 cannot be closed with a problem "The outbox changes are not automatically saved", and i suggest to fix all saving problems in existing one #5908. What do you think?

**Comment by ChristophWurst** [comment]
I would tackle those two separately

**Comment by GretaD** [comment]
> . #5908 cannot be closed with a problem "The outbox changes are not automatically saved", and i suggest to fix all saving problems in existing one #5908.

The 2 problems are not directly related so lets split them, but i dont understand what do you mean with the sentences above? Also, do you already have a pr for #5908?

**Comment by JuliaKirschenheuter** [comment]
> The 2 problems are not directly related so lets split them, but i dont understand what do you mean with the sentences above? Also, do you already have a pr for https://github.com/nextcloud/mail/issues/5908?

As i saw a problem with "saving"-process, i thought it could be fixed all together, because it is technically one problem. Let me make a PR for #5908, and then i can start fix fix this bug.
