### ISSUE TITLE
Sent emails sometimes remain in draft box

### ISSUE THREAD

**Issue by eibex** [nextcloud/mail#6348]
### Steps to reproduce

Can't always reproduced but:
1. Write an email
2. Auto-draft saving
3. Send email
4. Email is sent but a draft version remains in the draft box

### Expected behavior

Emails sent do not remain in draft box

### Actual behavior

Emails sent sometimes remain in draft box

### Mail app version

1.11.7

### Operating system

Ubuntu 20.04

### PHP engine version

PHP 7.4

### Web server

Apache (supported)

### Database

PostgreSQL

### Additional info

No errors were logged

**Comment by ChristophWurst** [comment]
This is very likely covered with https://github.com/nextcloud/mail/issues/4768. It is certainly planned to take up this task soon. Sorry for any inconveniences caused :v:
