### ISSUE TITLE
Attachment does not upload

### ISSUE THREAD

**Issue by davidpr78** [nextcloud/mail#6354]
### Steps to reproduce

I can't upload attachments anymore

### Expected behavior

It is possible to upload an attachment.

### Actual behavior

Uploaded attachments are not being saved. I can't send them.

Logfile: OCA\Mail\Exception\UploadException: could not read uploaded file

### Mail app version

1.11.7

### Mailserver or service

WebhostOne

### Operating system

Edudocs

**Comment by ChristophWurst** [comment]
> Logfile: OCA\Mail\Exception\UploadException: could not read uploaded file

could you share the raw log?

**Comment by davidpr78** [comment]
I‘m not allowed to publish it. Sorry

**Comment by ChristophWurst** [comment]
Understandable. Then we need to wait for someone else who runs into this.

**Comment by davidpr78** [comment]
Problem solved. Was a php update error.
