### ISSUE TITLE
Can‘t write e-mails on an iPad

### ISSUE THREAD

**Issue by davidpr78** [nextcloud/mail#6357]
### Steps to reproduce

1. Open New Mail

### Expected behavior

You can type intro a text-field

### Actual behavior

You can‘t type intro a text field on an iPad.

### Mail app version

1.12.0

### Mailserver or service

WebhostOne

### Operating system

Edudocs

**Comment by ChristophWurst** [comment]
why does it not work? screenshot?

**Comment by davidpr78** [comment]
Can‘t test it now. Set back to an earlier Version.
