### ISSUE TITLE
Missing \\answered flag on replied messages

### ISSUE THREAD

**Issue by davidpr78** [nextcloud/mail#6358]
### Steps to reproduce

1. view the e-mail list
2.
3.

### Expected behavior

When replying to an e-mail, there is a back arrow in the mail list.

### Actual behavior

There appears no back arrow anymore after replying an e-mail.

### Mail app version

1.12.0

### Mailserver or service

WebhostOne

### Operating system

Edudocs

**Comment by ChristophWurst** [comment]
@davidpr78 please be a bit more elaborative with your reports. It takes a lot of guessing to figure out where you are stuck. For any visual bugs like this, please add a screenshot. It goes a long way towards understanding :)

**Comment by davidpr78** [comment]
It is a productive enviroment with user data. I'm not allowed to publish screen shots.

**Comment by ChristophWurst** [comment]
then try to describe it in words

**Comment by davidpr78** [comment]
![ScreenShot Tool -20220504113552](https://user-images.githubusercontent.com/60741877/166657202-60324a9f-4158-4e36-ab76-bca4ec6d6354.png)

**Comment by davidpr78** [comment]
The mail app used to attach an arrow to answered mails in the list. After the update to 1.12.0 it does not appear anymore in new answered mails.

**Comment by ChristophWurst** [comment]
Likely because of https://github.com/nextcloud/mail/blob/66a326e18afa61b76b0c64a35f4160e9cc9a4601/src/components/NewMessageModal.vue#L109

**Comment by ChristophWurst** [comment]
Fix is at https://github.com/nextcloud/mail/pull/6371
