### ISSUE TITLE
Draft subjects are removed (again)

### ISSUE THREAD

**Issue by jancborchardt** [nextcloud/mail#637]
As the title says, any draft saved by Nextcloud Mail gets the subject removed again. This does not happen if you directly reply (thankfully).

**Comment by ChristophWurst** [comment]
Steps to reproduce would be great.

**Comment by jancborchardt** [comment]
1. Write a mail
2. Do something else
3. Check your drafts folder


This happens with any and every draft, so no real specific steps. You can’t reproduce @ChristophWurst? cc @Gomez

**Comment by ChristophWurst** [comment]
Cannot reproduce. I stepped through the code using a debugger and the subject is successfully transferred to the IMAP server and also loaded in the list of drafts.

**Comment by jancborchardt** [comment]
Still have the same issue with the latest master. Can anyone from @nextcloud/mail reproduce?

**Comment by shaahid1** [comment]
I'm experiencing the same issue. I also have multiple drafts being created for the same email.

**Comment by ChristophWurst** [comment]
> I'm experiencing the same issue. I also have multiple drafts being created for the same email.

https://github.com/nextcloud/mail/issues/637#issuecomment-347434173
https://github.com/nextcloud/mail/issues/637#issuecomment-348905378

:wink:
