### ISSUE TITLE
Composer modal has a scroll bar by default

### ISSUE THREAD

**Issue by st3iny** [nextcloud/mail#6379]
### Is your feature request related to a problem? Please describe.

An (almost) empty composer has an unecessary scroll bar by default on small screens.

![image](https://user-images.githubusercontent.com/1479486/167162780-7e17acb1-a1f1-496d-8e0c-2746ed16cdf0.png)

### Describe the solution you'd like

The composer should not have a scroll bar if it's mostly empty. However, the problem is that this minimum height was added deliberately to make the compose look nicer. Maybe basing it around e.g. `50vh` works better on all screen sizes.

### Additional context

This was a part of #6242 initially but got lost somehow.

**Comment by jancborchardt** [comment]
Already tracked in https://github.com/nextcloud/mail/issues/6271 :)
