### ISSUE TITLE
Sending mails to groups fails (again!)

### ISSUE THREAD

**Issue by escribana** [nextcloud/mail#6382]
### Steps to reproduce

1. Create new message for group
2. Send
3.  Message lands in outbox without being sent

### Expected behavior

Message is sent to all users of the group

### Actual behavior

Message stays in outbox and cannot be sent

### Mail app version

1.12.0

### Mailserver or service

bluewin.ch & gmx.net

### Operating system

Ubuntu 20.0.4

### PHP engine version

PHP 7.4

### Web server

Apache (supported)

### Database

MariaDB

### Additional info

Log for bluewin.ch -------------------------------------------------------------------------------------------------

OCA\Mail\Exception\ServiceException: Could not send message: need RCPT before DATA
/var/www/html/nextcloud/apps/mail/lib/Service/MailTransmission.php - line 271:
OCA\Mail\Service\MailTransmission->sendMessage()
/var/www/html/nextcloud/apps/mail/lib/Service/OutboxService.php - line 129:
OCA\Mail\Service\MailTransmission->sendLocalMessage()
/var/www/html/nextcloud/apps/mail/lib/Controller/OutboxController.php - line 191:
OCA\Mail\Service\OutboxService->sendMessage()
/var/www/html/nextcloud/lib/private/AppFramework/Http/Dispatcher.php - line 217:
OCA\Mail\Controller\OutboxController->send()
/var/www/html/nextcloud/lib/private/AppFramework/Http/Dispatcher.php - line 126:
OC\AppFramework\Http\Dispatcher->executeController()
/var/www/html/nextcloud/lib/private/AppFramework/App.php - line 157:
OC\AppFramework\Http\Dispatcher->dispatch()
/var/www/html/nextcloud/lib/private/Route/Router.php - line 302:
OC\AppFramework\App::main()
/var/www/html/nextcloud/lib/base.php - line 1008:
OC\Route\Router->match()
/var/www/html/nextcloud/index.php - line 36:
OC::handleRequest()

Caused by Horde_Mime_Exception: need RCPT before DATA
/var/www/html/nextcloud/apps/mail/vendor/pear-pear.horde.org/Horde_Mime/Horde/Mime/Mail.php - line 479:
Horde_Mime_Part->send()
/var/www/html/nextcloud/apps/mail/lib/Service/MailTransmission.php - line 208:
Horde_Mime_Mail->send()
/var/www/html/nextcloud/apps/mail/lib/Service/MailTransmission.php - line 271:
OCA\Mail\Service\MailTransmission->sendMessage()
/var/www/html/nextcloud/apps/mail/lib/Service/OutboxService.php - line 129:
OCA\Mail\Service\MailTransmission->sendLocalMessage()
/var/www/html/nextcloud/apps/mail/lib/Controller/OutboxController.php - line 191:
OCA\Mail\Service\OutboxService->sendMessage()
/var/www/html/nextcloud/lib/private/AppFramework/Http/Dispatcher.php - line 217:
OCA\Mail\Controller\OutboxController->send()
/var/www/html/nextcloud/lib/private/AppFramework/Http/Dispatcher.php - line 126:
OC\AppFramework\Http\Dispatcher->executeController()
/var/www/html/nextcloud/lib/private/AppFramework/App.php - line 157:
OC\AppFramework\Http\Dispatcher->dispatch()
/var/www/html/nextcloud/lib/private/Route/Router.php - line 302:
OC\AppFramework\App::main()
/var/www/html/nextcloud/lib/base.php - line 1008:
OC\Route\Router->match()
/var/www/html/nextcloud/index.php - line 36:
OC::handleRequest()

Caused by Horde_Mail_Exception: need RCPT before DATA
/var/www/html/nextcloud/apps/mail/vendor/pear-pear.horde.org/Horde_Mime/Horde/Mime/Part.php - line 1620:
Horde_Mail_Transport_Smtphorde->send()
/var/www/html/nextcloud/apps/mail/vendor/pear-pear.horde.org/Horde_Mime/Horde/Mime/Mail.php - line 479:
Horde_Mime_Part->send()
/var/www/html/nextcloud/apps/mail/lib/Service/MailTransmission.php - line 208:
Horde_Mime_Mail->send()
/var/www/html/nextcloud/apps/mail/lib/Service/MailTransmission.php - line 271:
OCA\Mail\Service\MailTransmission->sendMessage()
/var/www/html/nextcloud/apps/mail/lib/Service/OutboxService.php - line 129:
OCA\Mail\Service\MailTransmission->sendLocalMessage()
/var/www/html/nextcloud/apps/mail/lib/Controller/OutboxController.php - line 191:
OCA\Mail\Service\OutboxService->sendMessage()
/var/www/html/nextcloud/lib/private/AppFramework/Http/Dispatcher.php - line 217:
OCA\Mail\Controller\OutboxController->send()
/var/www/html/nextcloud/lib/private/AppFramework/Http/Dispatcher.php - line 126:
OC\AppFramework\Http\Dispatcher->executeController()
/var/www/html/nextcloud/lib/private/AppFramework/App.php - line 157:
OC\AppFramework\Http\Dispatcher->dispatch()
/var/www/html/nextcloud/lib/private/Route/Router.php - line 302:
OC\AppFramework\App::main()
/var/www/html/nextcloud/lib/base.php - line 1008:
OC\Route\Router->match()
/var/www/html/nextcloud/index.php - line 36:
OC::handleRequest()

Caused by Horde_Smtp_Exception: need RCPT before DATA
/var/www/html/nextcloud/apps/mail/vendor/pear-pear.horde.org/Horde_Smtp/Horde/Smtp.php - line 712:
Horde_Smtp->_getResponse()
/var/www/html/nextcloud/apps/mail/vendor/pear-pear.horde.org/Horde_Mail/Horde/Mail/Transport/Smtphorde.php - line 143:
Horde_Smtp->send()
/var/www/html/nextcloud/apps/mail/vendor/pear-pear.horde.org/Horde_Mime/Horde/Mime/Part.php - line 1620:
Horde_Mail_Transport_Smtphorde->send()
/var/www/html/nextcloud/apps/mail/vendor/pear-pear.horde.org/Horde_Mime/Horde/Mime/Mail.php - line 479:
Horde_Mime_Part->send()
/var/www/html/nextcloud/apps/mail/lib/Service/MailTransmission.php - line 208:
Horde_Mime_Mail->send()
/var/www/html/nextcloud/apps/mail/lib/Service/MailTransmission.php - line 271:
OCA\Mail\Service\MailTransmission->sendMessage()
/var/www/html/nextcloud/apps/mail/lib/Service/OutboxService.php - line 129:
OCA\Mail\Service\MailTransmission->sendLocalMessage()
/var/www/html/nextcloud/apps/mail/lib/Controller/OutboxController.php - line 191:
OCA\Mail\Service\OutboxService->sendMessage()
/var/www/html/nextcloud/lib/private/AppFramework/Http/Dispatcher.php - line 217:
OCA\Mail\Controller\OutboxController->send()
/var/www/html/nextcloud/lib/private/AppFramework/Http/Dispatcher.php - line 126:
OC\AppFramework\Http\Dispatcher->executeController()
/var/www/html/nextcloud/lib/private/AppFramework/App.php - line 157:
OC\AppFramework\Http\Dispatcher->dispatch()
/var/www/html/nextcloud/lib/private/Route/Router.php - line 302:
OC\AppFramework\App::main()
/var/www/html/nextcloud/lib/base.php - line 1008:
OC\Route\Router->match()
/var/www/html/nextcloud/index.php - line 36:
OC::handleRequest()

Log for gmx.net ---------------------------------------------------------------------------------------------------------------------------

Error	mail	OCA\Mail\Exception\ServiceException: Could not send message: Bad sequence of commands

/var/www/html/nextcloud/apps/mail/lib/Service/MailTransmission.php - line 271:
OCA\Mail\Service\MailTransmission->sendMessage()
/var/www/html/nextcloud/apps/mail/lib/Service/OutboxService.php - line 129:
OCA\Mail\Service\MailTransmission->sendLocalMessage()
/var/www/html/nextcloud/apps/mail/lib/Controller/OutboxController.php - line 191:
OCA\Mail\Service\OutboxService->sendMessage()
/var/www/html/nextcloud/lib/private/AppFramework/Http/Dispatcher.php - line 217:
OCA\Mail\Controller\OutboxController->send()
/var/www/html/nextcloud/lib/private/AppFramework/Http/Dispatcher.php - line 126:
OC\AppFramework\Http\Dispatcher->executeController()
/var/www/html/nextcloud/lib/private/AppFramework/App.php - line 157:
OC\AppFramework\Http\Dispatcher->dispatch()
/var/www/html/nextcloud/lib/private/Route/Router.php - line 302:
OC\AppFramework\App::main()
/var/www/html/nextcloud/lib/base.php - line 1008:
OC\Route\Router->match()
/var/www/html/nextcloud/index.php - line 36:
OC::handleRequest()

Caused by Horde_Mime_Exception: Bad sequence of commands

/var/www/html/nextcloud/apps/mail/vendor/pear-pear.horde.org/Horde_Mime/Horde/Mime/Mail.php - line 479:
Horde_Mime_Part->send()
/var/www/html/nextcloud/apps/mail/lib/Service/MailTransmission.php - line 208:
Horde_Mime_Mail->send()
/var/www/html/nextcloud/apps/mail/lib/Service/MailTransmission.php - line 271:
OCA\Mail\Service\MailTransmission->sendMessage()
/var/www/html/nextcloud/apps/mail/lib/Service/OutboxService.php - line 129:
OCA\Mail\Service\MailTransmission->sendLocalMessage()
/var/www/html/nextcloud/apps/mail/lib/Controller/OutboxController.php - line 191:
OCA\Mail\Service\OutboxService->sendMessage()
/var/www/html/nextcloud/lib/private/AppFramework/Http/Dispatcher.php - line 217:
OCA\Mail\Controller\OutboxController->send()
/var/www/html/nextcloud/lib/private/AppFramework/Http/Dispatcher.php - line 126:
OC\AppFramework\Http\Dispatcher->executeController()
/var/www/html/nextcloud/lib/private/AppFramework/App.php - line 157:
OC\AppFramework\Http\Dispatcher->dispatch()
/var/www/html/nextcloud/lib/private/Route/Router.php - line 302:
OC\AppFramework\App::main()
/var/www/html/nextcloud/lib/base.php - line 1008:
OC\Route\Router->match()
/var/www/html/nextcloud/index.php - line 36:
OC::handleRequest()

Caused by Horde_Mail_Exception: Bad sequence of commands

/var/www/html/nextcloud/apps/mail/vendor/pear-pear.horde.org/Horde_Mime/Horde/Mime/Part.php - line 1620:
Horde_Mail_Transport_Smtphorde->send()
/var/www/html/nextcloud/apps/mail/vendor/pear-pear.horde.org/Horde_Mime/Horde/Mime/Mail.php - line 479:
Horde_Mime_Part->send()
/var/www/html/nextcloud/apps/mail/lib/Service/MailTransmission.php - line 208:
Horde_Mime_Mail->send()
/var/www/html/nextcloud/apps/mail/lib/Service/MailTransmission.php - line 271:
OCA\Mail\Service\MailTransmission->sendMessage()
/var/www/html/nextcloud/apps/mail/lib/Service/OutboxService.php - line 129:
OCA\Mail\Service\MailTransmission->sendLocalMessage()
/var/www/html/nextcloud/apps/mail/lib/Controller/OutboxController.php - line 191:
OCA\Mail\Service\OutboxService->sendMessage()
/var/www/html/nextcloud/lib/private/AppFramework/Http/Dispatcher.php - line 217:
OCA\Mail\Controller\OutboxController->send()
/var/www/html/nextcloud/lib/private/AppFramework/Http/Dispatcher.php - line 126:
OC\AppFramework\Http\Dispatcher->executeController()
/var/www/html/nextcloud/lib/private/AppFramework/App.php - line 157:
OC\AppFramework\Http\Dispatcher->dispatch()
/var/www/html/nextcloud/lib/private/Route/Router.php - line 302:
OC\AppFramework\App::main()
/var/www/html/nextcloud/lib/base.php - line 1008:
OC\Route\Router->match()
/var/www/html/nextcloud/index.php - line 36:
OC::handleRequest()

Caused by Horde_Smtp_Exception: Bad sequence of commands

/var/www/html/nextcloud/apps/mail/vendor/pear-pear.horde.org/Horde_Smtp/Horde/Smtp.php - line 712:
Horde_Smtp->_getResponse()
/var/www/html/nextcloud/apps/mail/vendor/pear-pear.horde.org/Horde_Mail/Horde/Mail/Transport/Smtphorde.php - line 143:
Horde_Smtp->send()
/var/www/html/nextcloud/apps/mail/vendor/pear-pear.horde.org/Horde_Mime/Horde/Mime/Part.php - line 1620:
Horde_Mail_Transport_Smtphorde->send()
/var/www/html/nextcloud/apps/mail/vendor/pear-pear.horde.org/Horde_Mime/Horde/Mime/Mail.php - line 479:
Horde_Mime_Part->send()
/var/www/html/nextcloud/apps/mail/lib/Service/MailTransmission.php - line 208:
Horde_Mime_Mail->send()
/var/www/html/nextcloud/apps/mail/lib/Service/MailTransmission.php - line 271:
OCA\Mail\Service\MailTransmission->sendMessage()
/var/www/html/nextcloud/apps/mail/lib/Service/OutboxService.php - line 129:
OCA\Mail\Service\MailTransmission->sendLocalMessage()
/var/www/html/nextcloud/apps/mail/lib/Controller/OutboxController.php - line 191:
OCA\Mail\Service\OutboxService->sendMessage()
/var/www/html/nextcloud/lib/private/AppFramework/Http/Dispatcher.php - line 217:
OCA\Mail\Controller\OutboxController->send()
/var/www/html/nextcloud/lib/private/AppFramework/Http/Dispatcher.php - line 126:
OC\AppFramework\Http\Dispatcher->executeController()
/var/www/html/nextcloud/lib/private/AppFramework/App.php - line 157:
OC\AppFramework\Http\Dispatcher->dispatch()
/var/www/html/nextcloud/lib/private/Route/Router.php - line 302:
OC\AppFramework\App::main()
/var/www/html/nextcloud/lib/base.php - line 1008:
OC\Route\Router->match()
/var/www/html/nextcloud/index.php - line 36:
OC::handleRequest()

**Comment by escribana** [comment]
Seems like [this bug](https://github.com/nextcloud/mail/issues/2066) resurrected its ugly head?

**Comment by damixem** [comment]
I have the same problem !
When I send a mail with 5 or more recipient, I have the error 500

**Comment by escribana** [comment]
I have some more information about this fatal error.
As you can see in the the following screenshot of the browser debugger a contactgroup (here "test") gets **not** resolved!!  Sending the message to "contacts:test" results in HTTP error 500 of course.

![ResolveGroupError](https://user-images.githubusercontent.com/28783957/168034301-81c53c8e-963e-4634-aff0-9d9c6a20ec27.png)

**Comment by LostinSpacetime** [comment]
I believe I have the same problem with a slight difference in the error log:

OCA\Mail\Exception\ServiceException: Could not send message: RCPT first

/var/www/vhosts/schloss-schule.wien/cloud.schloss-schule.wien/apps/mail/lib/Service/MailTransmission.php - line 271:
OCA\Mail\Service\MailTransmission->sendMessage()
/var/www/vhosts/schloss-schule.wien/cloud.schloss-schule.wien/apps/mail/lib/Service/OutboxService.php - line 129:
OCA\Mail\Service\MailTransmission->sendLocalMessage()
/var/www/vhosts/schloss-schule.wien/cloud.schloss-schule.wien/apps/mail/lib/Controller/OutboxController.php - line 191:
OCA\Mail\Service\OutboxService->sendMessage()
/var/www/vhosts/schloss-schule.wien/cloud.schloss-schule.wien/lib/private/AppFramework/Http/Dispatcher.php - line 217:
OCA\Mail\Controller\OutboxController->send()
/var/www/vhosts/schloss-schule.wien/cloud.schloss-schule.wien/lib/private/AppFramework/Http/Dispatcher.php - line 126:
OC\AppFramework\Http\Dispatcher->executeController()
/var/www/vhosts/schloss-schule.wien/cloud.schloss-schule.wien/lib/private/AppFramework/App.php - line 157:
OC\AppFramework\Http\Dispatcher->dispatch()
/var/www/vhosts/schloss-schule.wien/cloud.schloss-schule.wien/lib/private/Route/Router.php - line 302:
OC\AppFramework\App::main()
/var/www/vhosts/schloss-schule.wien/cloud.schloss-schule.wien/lib/base.php - line 1008:
OC\Route\Router->match()
/var/www/vhosts/schloss-schule.wien/cloud.schloss-schule.wien/index.php - line 36:
OC::handleRequest()

Verursacht durch Horde_Mime_Exception: RCPT first

/var/www/vhosts/schloss-schule.wien/cloud.schloss-schule.wien/apps/mail/vendor/pear-pear.horde.org/Horde_Mime/Horde/Mime/Mail.php - line 479:
Horde_Mime_Part->send()
/var/www/vhosts/schloss-schule.wien/cloud.schloss-schule.wien/apps/mail/lib/Service/MailTransmission.php - line 208:
Horde_Mime_Mail->send()
/var/www/vhosts/schloss-schule.wien/cloud.schloss-schule.wien/apps/mail/lib/Service/MailTransmission.php - line 271:
OCA\Mail\Service\MailTransmission->sendMessage()
/var/www/vhosts/schloss-schule.wien/cloud.schloss-schule.wien/apps/mail/lib/Service/OutboxService.php - line 129:
OCA\Mail\Service\MailTransmission->sendLocalMessage()
/var/www/vhosts/schloss-schule.wien/cloud.schloss-schule.wien/apps/mail/lib/Controller/OutboxController.php - line 191:
OCA\Mail\Service\OutboxService->sendMessage()
/var/www/vhosts/schloss-schule.wien/cloud.schloss-schule.wien/lib/private/AppFramework/Http/Dispatcher.php - line 217:
OCA\Mail\Controller\OutboxController->send()
/var/www/vhosts/schloss-schule.wien/cloud.schloss-schule.wien/lib/private/AppFramework/Http/Dispatcher.php - line 126:
OC\AppFramework\Http\Dispatcher->executeController()
/var/www/vhosts/schloss-schule.wien/cloud.schloss-schule.wien/lib/private/AppFramework/App.php - line 157:
OC\AppFramework\Http\Dispatcher->dispatch()
/var/www/vhosts/schloss-schule.wien/cloud.schloss-schule.wien/lib/private/Route/Router.php - line 302:
OC\AppFramework\App::main()
/var/www/vhosts/schloss-schule.wien/cloud.schloss-schule.wien/lib/base.php - line 1008:
OC\Route\Router->match()
/var/www/vhosts/schloss-schule.wien/cloud.schloss-schule.wien/index.php - line 36:
OC::handleRequest()

Verursacht durch Horde_Mail_Exception: RCPT first

/var/www/vhosts/schloss-schule.wien/cloud.schloss-schule.wien/apps/mail/vendor/pear-pear.horde.org/Horde_Mime/Horde/Mime/Part.php - line 1620:
Horde_Mail_Transport_Smtphorde->send()
/var/www/vhosts/schloss-schule.wien/cloud.schloss-schule.wien/apps/mail/vendor/pear-pear.horde.org/Horde_Mime/Horde/Mime/Mail.php - line 479:
Horde_Mime_Part->send()
/var/www/vhosts/schloss-schule.wien/cloud.schloss-schule.wien/apps/mail/lib/Service/MailTransmission.php - line 208:
Horde_Mime_Mail->send()
/var/www/vhosts/schloss-schule.wien/cloud.schloss-schule.wien/apps/mail/lib/Service/MailTransmission.php - line 271:
OCA\Mail\Service\MailTransmission->sendMessage()
/var/www/vhosts/schloss-schule.wien/cloud.schloss-schule.wien/apps/mail/lib/Service/OutboxService.php - line 129:
OCA\Mail\Service\MailTransmission->sendLocalMessage()
/var/www/vhosts/schloss-schule.wien/cloud.schloss-schule.wien/apps/mail/lib/Controller/OutboxController.php - line 191:
OCA\Mail\Service\OutboxService->sendMessage()
/var/www/vhosts/schloss-schule.wien/cloud.schloss-schule.wien/lib/private/AppFramework/Http/Dispatcher.php - line 217:
OCA\Mail\Controller\OutboxController->send()
/var/www/vhosts/schloss-schule.wien/cloud.schloss-schule.wien/lib/private/AppFramework/Http/Dispatcher.php - line 126:
OC\AppFramework\Http\Dispatcher->executeController()
/var/www/vhosts/schloss-schule.wien/cloud.schloss-schule.wien/lib/private/AppFramework/App.php - line 157:
OC\AppFramework\Http\Dispatcher->dispatch()
/var/www/vhosts/schloss-schule.wien/cloud.schloss-schule.wien/lib/private/Route/Router.php - line 302:
OC\AppFramework\App::main()
/var/www/vhosts/schloss-schule.wien/cloud.schloss-schule.wien/lib/base.php - line 1008:
OC\Route\Router->match()
/var/www/vhosts/schloss-schule.wien/cloud.schloss-schule.wien/index.php - line 36:
OC::handleRequest()

Verursacht durch Horde_Smtp_Exception: RCPT first

/var/www/vhosts/schloss-schule.wien/cloud.schloss-schule.wien/apps/mail/vendor/pear-pear.horde.org/Horde_Smtp/Horde/Smtp.php - line 712:
Horde_Smtp->_getResponse()
/var/www/vhosts/schloss-schule.wien/cloud.schloss-schule.wien/apps/mail/vendor/pear-pear.horde.org/Horde_Mail/Horde/Mail/Transport/Smtphorde.php - line 143:
Horde_Smtp->send()
/var/www/vhosts/schloss-schule.wien/cloud.schloss-schule.wien/apps/mail/vendor/pear-pear.horde.org/Horde_Mime/Horde/Mime/Part.php - line 1620:
Horde_Mail_Transport_Smtphorde->send()
/var/www/vhosts/schloss-schule.wien/cloud.schloss-schule.wien/apps/mail/vendor/pear-pear.horde.org/Horde_Mime/Horde/Mime/Mail.php - line 479:
Horde_Mime_Part->send()
/var/www/vhosts/schloss-schule.wien/cloud.schloss-schule.wien/apps/mail/lib/Service/MailTransmission.php - line 208:
Horde_Mime_Mail->send()
/var/www/vhosts/schloss-schule.wien/cloud.schloss-schule.wien/apps/mail/lib/Service/MailTransmission.php - line 271:
OCA\Mail\Service\MailTransmission->sendMessage()
/var/www/vhosts/schloss-schule.wien/cloud.schloss-schule.wien/apps/mail/lib/Service/OutboxService.php - line 129:
OCA\Mail\Service\MailTransmission->sendLocalMessage()
/var/www/vhosts/schloss-schule.wien/cloud.schloss-schule.wien/apps/mail/lib/Controller/OutboxController.php - line 191:
OCA\Mail\Service\OutboxService->sendMessage()
/var/www/vhosts/schloss-schule.wien/cloud.schloss-schule.wien/lib/private/AppFramework/Http/Dispatcher.php - line 217:
OCA\Mail\Controller\OutboxController->send()
/var/www/vhosts/schloss-schule.wien/cloud.schloss-schule.wien/lib/private/AppFramework/Http/Dispatcher.php - line 126:
OC\AppFramework\Http\Dispatcher->executeController()
/var/www/vhosts/schloss-schule.wien/cloud.schloss-schule.wien/lib/private/AppFramework/App.php - line 157:
OC\AppFramework\Http\Dispatcher->dispatch()
/var/www/vhosts/schloss-schule.wien/cloud.schloss-schule.wien/lib/private/Route/Router.php - line 302:
OC\AppFramework\App::main()
/var/www/vhosts/schloss-schule.wien/cloud.schloss-schule.wien/lib/base.php - line 1008:
OC\Route\Router->match()
/var/www/vhosts/schloss-schule.wien/cloud.schloss-schule.wien/index.php - line 36:
OC::handleRequest()

**Comment by ChristophWurst** [comment]
Expanding group recipients to memeber recipients is missing in the outbox implementation.

**Comment by escribana** [comment]
@ChristophWurst: Many, many thanks for the fast reaction: I will do some more tests, but group mails are working again so far!

**Comment by LostinSpacetime** [comment]
@escribana What did you do to apply the patch? We are using the mail app in our school and, as it is, teachers can't write to the parents groups right now. So, it's quite urgent to fix this, and I don't have any experience with GitHub. Can you please help?

**Comment by escribana** [comment]
@LostinSpacetime: Be warned, that the following procedure can produce troubles depending of the version of Nextcloud. (I tried with version 23.0.4 and it worked so far.) 
If you don't want to use git, you can download the the raw php-files by hand and copy them to the corresponding place in your installation directory of Nextcloud. Be sure to put a copy of the original files in a save place, so you can go back if something goes wrong!!

1. Go to [https://github.com/nextcloud/mail/pull/6460/commits/1a3a3893e4b6899345a9e56938d826bdfd8024f6](url)

**Comment by escribana** [comment]
@LostinSpacetime: Be warned, that the following procedure can produce troubles depending of the version of Nextcloud. (I tried with version 23.0.4 and it worked so far.) 
If you don't want to use git, you can download the the raw php-files by hand and copy them to the corresponding place in your installation directory of Nextcloud. Be sure to put a copy of the original files in a save place, so you can go back if something goes wrong!!

1. Go to [https://github.com/nextcloud/mail/pull/6460/commits/1a3a3893e4b6899345a9e56938d826bdfd8024f6](url)
