### ISSUE TITLE
Multi-selecting drafts open modal editor

### ISSUE THREAD

**Issue by Chartman123** [nextcloud/mail#6389]
### Steps to reproduce

1. Go to Drafts folder
2. Click on three dots for selecting the first message
3. Click on checkbox to select further messages
4. See how modal editor window opens

### Expected behavior

Selecting a message with the checkbox selects the message

### Actual behavior

Selecting a message with the checkbox selects the message and opens it in the modal editor

### Mail app version

1.12.0

### Operating system

Docker image

### PHP engine version

PHP 8.0

### Web server

Apache (supported)

### Database

PostgreSQL

**Comment by Chartman123** [comment]
It doesn't only happen in the drafts folder but with drafts in general, e. g. when you multi-select a deleted draft mail in the trash folder.

**Comment by GretaD** [comment]
I can reproduce this one and i am having a look

**Comment by Chartman123** [comment]
@ChristophWurst @GretaD it looks like this issue came back now... I'm on the latest mail app on NC29

**Comment by Chartman123** [comment]
@GretaD oh, I forgot that selecting multiple messages with CTRL + Click arrived later... Since this is available I always use CTRL + left click for selecting the messages.

**Comment by GretaD** [comment]
> @GretaD oh, I forgot that selecting multiple messages with CTRL + Click arrived later... Since this is available I always use CTRL + left click for selecting the messages.

yes, i can reproduce it with the shortcut. This needs a new ticket. Will check it out soon
