### ISSUE TITLE
New message button does nothing

### ISSUE THREAD

**Issue by jancborchardt** [nextcloud/mail#64]
In the console there’s only
```
[ui] "document:click" [n.Event]
```

Nothing at all happens. Nothing in the log otherwise.

Chrome, latest master

**Comment by ChristophWurst** [comment]
Noticed that too while working on a recent PR and fixed it: https://github.com/nextcloud/mail/pull/48/files#diff-ed795e5e29b548a79bfc8633dbafb234R32

Let me extract that fix to a separate PR…
