### ISSUE TITLE
Mailvelope misformed encrypted message. Nextcloud Mail 1.12.0

### ISSUE THREAD

**Issue by robviauc** [nextcloud/mail#6402]
### Steps to reproduce

1. Set up Mailvelope. Authorize NextCloud domain using API. Set up a key pair associated with the Nextcloud Email address (previously set up using IMAP)
2. Send an encrypted message through NextCloud Mail to a second email address (I tried a Gmail address)
3. Attempt to decrypt the message using Mailvelope Gmail API.

### Expected behavior

The encrypted email should be readable by the Mailvelope Extension. 

### Actual behavior

The encrypted cannot be read. According to debug info: "Mandatory blank line missing between armor headers and armor data"

### Mail app version

1.12.0

### Mailserver or service

Dovencot/IMAP

### Operating system

Amazon Linux

### PHP engine version

PHP 8.1

### Web server

Apache (supported)

### Database

MariaDB

### Additional info

Browser: Firefox 100
Notice there should be a \<CR> after the dashes on "BEGIN PGP MESSAGE", then a \<CR> after the Mailvelope version, another \<CR> after the "Comment: https://www.mailvelope.com", a blank line + \<CR>, and then begin the e encrypted ASCII. 
At the end, there should be a \<CR> between the 2 "=" signs, and a \<CR> before the dashes that precede the "END PGP MESSAGE" statement.

Sent message:

-----BEGIN PGP MESSAGE----- Version: Mailvelope v4.5.2 Comment: https://www.mailvelope.com wcFMA6pwc/ewRsrzARAAk095GqI8IGpN28shP1RQGOx2eghRXSlU78gTcFF6 7nCDWtK0HlQ7Dl0Xh+ugRA77wk1bsvcf8C+t3pAyHkjCc4/Y0419B5jUK185 fDb/gZuUVKdvPYrCL1mKfJcvTR455ZDqjLIJAcjXkOU9sZcobfHVgX/LqDwz IGRpz1oSu++N10LVqIvm3zbM2B76KemcllCNbCJo7StyiTjHyUQj3x1henHo rl1CGHSyzhcPKjqcd3ib229BS1HmVs9q2Mlm3VEDen6iEoBSd9IymbzTnlgM uC6j1sMHZuAu2d6cWiWySveME1SSSKoXXJWytTqXOPiMXAAokZYgag43mWLB yFgzriCVLsJWxpXcCOKXKYdXdEHoQplb2IB42TV70SV0CV7p9gsT6/Q955wF ZdeSlCCo2eXGK4NeDb1GJ//8jub8NSzT+ptu2XI2vm0xQ7UvK4fxJHpanOb+ goM3PhMtzusw6VFm7hD0k1+bQzxIA4k2tyUNE0pzOQXj0MFM+fGwNl5tFDnH qLzwJDZWMmOi0d4Oh4JVQycBIhJ7EiRsLPOtXswh3WJCZPbOzK79K1Iek45n 4QOYgfMZcvRlrPe0wQtIB7CbmKojK1RvKQQ/MnBbo1UvjEvn4UIc+jdhnaUv KaMMwDVaRFxUrZQVGgCUTZwEuOIiSnnaTV9AlhwUE1nBwUwDKq1753o0AlkB D/0V2l+yGepAjT7HwwG2F7c/WhhE2lr8ZjuqVPloaiusi9acyXVUFrfeIQec HfZdVywcWUaHXXsaXahVOR1U8q5jwt5eENjxhcJGmLj/5mCsbmxW9lu1+44j Khe4AK7lq2toni4czMDso5pFlpxzJAnmlxcRhnH7PLZjJJstFGk+j4xFA9Y7 +uem2C9t37SHD9hhVHCVlOFnrJ7o41mvNfZKxEPKL+tmUHUsUV9X0l/M8LzG xc1uMuc0veOmE8++zCbeCCaD/bYiGNyY5MwVRYjV87FceFsO8cZEaupuByD3 A4zNLO/bZQzi3suuFsJqdQ0cxM4cTOL6oR1G9IykSLL0H+zSEQ2gYsHsFHYZ /CQjMrxz9r5ZWRaa0npM5owL6HN3pXkLpn2lzXdcvyouLY03PuVKLl46V4ff NizJZ2adhcWSENC7MR9I8A1O3pbSzR/N+VOXbWbFK3PONXALSQZRs5aWZ7l1 IenC1szGtZVW6bFx6VDNwP1ZI+DZ6QalEgsj1iBTMEgc/VCj7gYFgiIkjFS2 l2Jw/D20a4rucieXYXnfqFCbEZzbHwQNu8lCS3oxYwI+f1j9VjcnU4BnNAPn S0akwJ+468lK5PnW8xJorVuIovdVqdEmKErHWLzUxMbhSqF/R0lJ142iZZtn vIsbpjWHTaUKnfdQIP13wJmdYNLDcAEIxZCFsvPOuIlnAal1r3k4pqyRuNWz 6T38L2ZaYiRA3+ZhtZkYfSc/xXwdi7K8Tlvgj+MmT20m55q+RVfLo79HQ9OW dh4QoDc7dVINRG1q+JMKBLwc0OS6v+jBA1Dx9d7qCsssIBq9twurLQiPvdTe qf8DJTkEUexjASQ8IycrrxiNryUrLwubG8W3RROWrotJcG9uYjtOLBtHS1Eo bzNy0yf3LiRZHchjImU6NC9K0s7unTwnSwL3bB7X6cDdk/DzivVKM/DDb4jR BlUbWn7Bf312SQBUKlQJ27jhzwKkgx3b7jSHf8YqyTSfwvcjw+IYShbSeMI1 NtJv+LMdXwSyPn0tvFb+yUUWWzh8G1ApvBfyoUkTcpcOQCe6fQeo6dMzPYjE cWhr1BCti80NQ/ENb37vVmD+Sqqs7N9/vbCJV+Is0rZIYKUQaaa7ZXzBx9V2 M/Ehu0UK/C2eadlGVoMkTOTxgqPdaZfuoLv8rFEydlkHCJh5eTxM7+wk+YPn 7xJSgttvr+msp98mbp+5R/J3EAWcOnsn0IUVqo5MCazRxmgzxOWl2FneodSY LM3UECstudWyW2s7sQdcXcAh0caZOKuuHYdzS8u9ExfdkmanXEWTxMPnEnPJ pF5uVGeUWOu7zzcJmfLpxmAmW0btVLiag/3dqZ8nymkBMnvUClv2Mkcpbfuk oMh7wCoXuZkX4YQxy/vnOesscYP8I3JWlKeyXm9TaYwFIk5DeiXMn33gqI8f K+r9wFEJfrlj2ShnJSXdvRkMw+3ETsLM7Z+tTe7aNsGYvHWn0VGnI+UyYbD/ 5MxQCLI7T7wmG0+UMCALfnaezfho/b3xRzwQnniqWdPa2YeSjmHLtNrz4NkA AJZbI+j882D4tLNPsTthYWvQ6/LDjUEmqh8pFq1b3iC3SLrf+0UdjMCg5GEb 7Njk9NFU4g/cPnT23tz7gebQ+5ulbPDzOVDOXNEjxBvHOHmojlWuj80qcxOX rQ4vVcNCXquvUojUa5DTg/SC9xO1QbA9n4YBCxzPyTxAmm8wu/Y+4ep6+8P1 52XcmFbvhvIGHDLWJOnYDlOw4Nwj4AeC2DIrTHMUp4IjtbUuX1XzlYeb+O5e NG2qRbKWU2U8dNeNcbW3s9+fP92sRm461CZ962cOj1oZpctXHf11MPdMf8Hq pFy5j52cBZs5PssrHyjMcodbLkxwkON9EYiRIHav3+hPLSq43fRrtUVnGlJS 3GvtS1ZxxnqGHquZ7hn3tQyMjZjqJKYQkWiM3aIwAilOEb1X/Ueazby6NxTq 2rvOrpg3LheVnyXtXA3MxFLjdOOK/YDsYU61ruEZLrHz0lX2fJ6+K5cGqGRv 8QVmjXddc64O9xfAaGU+IU9/k9fytvMlW/tJON/nKxJY/CkytvZUBbBc2G0M +FP9LAsUZwfjXcUPAyA= =yK8X -----END PGP MESSAGE-----

**Comment by ChristophWurst** [comment]
This is resolved. The CRs are inserted and clients correctly recognize the format.
