### ISSUE TITLE
Mails with attachment are not being sent: localMessageId is not a valid attribute

### ISSUE THREAD

**Issue by davidpr78** [nextcloud/mail#6406]
### Steps to reproduce

Add an attachment to an e-mail.

### Expected behavior

You can send an e-mail with attachment.

### Actual behavior

Mails with attachment are not being send (Error 500)

### Mail app version

1.12.0

### Mailserver or service

WebhostONe

### Operating system

Edudocs

### Additional info

I'm not allowed to send log. But TLS/SSL error comes often

**Comment by davidpr78** [comment]
I can send attachments from nc but not from local. After sending I have to delete the browser cache otherwise it doesn't work.

**Comment by GretaD** [comment]
Hello,

please send us the error log on my work email greta@nextcloud.com, remove the sensitive info, so we can see a bit better what is happening

**Comment by ChristophWurst** [comment]
If the logs aren't sensitive please post them here. Ideally you copy the log line(s) of nextcloud.log of the request that caused HTTP500.

**Comment by davidpr78** [comment]
[mail] Fehler: localMessageId is not a valid attribute

POST /xxx/apps/mail/api/accounts/15/send
from 80.xxx5 by xxx at 2022-05-11T07:46:39+00:00


[PHP] Fehler: get_headers(): SSL operation failed with code 1. OpenSSL Error messages:
error:1416F086:SSL routines:tls_process_server_certificate:certificate verify failed at /zfsinst/ed_instances/xxx/apps/mail/lib/Vendor/Favicon/DataAccess.php#21

GET /xxx/apps/mail/api/avatars/url/xxx.org
from 109.xxx by xxx at 2022-05-11T07:33:12+00:00

**Comment by miaulalala** [comment]
Do you have your loglevel set to 0 (debug)? If you can reproduce with that loglevel and post that log message pls :pray:

**Comment by davidpr78** [comment]
there is no debug log message. Sorry

**Comment by miaulalala** [comment]
Can you please try setting your log level to debug in the config and try to reproduce this error if possible?

Here is how you can change your loglevel for Nextcloud:

https://docs.nextcloud.com/server/latest/admin_manual/configuration_server/logging_configuration.html

**Comment by davidpr78** [comment]
[scss_cacher] Fehlersuche: SCSSCacher::isCached 4039-2cc7-mobile.css isCachedCache is expired or unset

GET /xxx/apps/mail/
from 80.xxx by xxx at 2022-05-11T09:35:09+00:00


[mail] Fehlersuche: loading messages of folder <19>

GET /xxx/apps/mail/api/messages?mailboxId=19&filter=is:pi-other&limit=20
from 80.xxx by xxx at 2022-05-11T09:35:10+00:00


[mail] Fehlersuche: findByIds in INBOX got 0 UIDs but found none

POST /xxx/apps/mail/api/mailboxes/19/sync
from 80.xxx by xxx at 2022-05-11T09:35:11+00:00



[files_readmemd] Fehlersuche: /appinfo/app.php is deprecated, use \OCP\AppFramework\Bootstrap\IBootstrap on the application class instead.

GET /xxx/apps/logreader/get?offset=0&count=50&levels=10000
from 80.xxx by xxx at 2022-05-11T09:35:36+00:00

**Comment by ChristophWurst** [comment]
Could you please copy the *raw* logs?

**Comment by davidpr78** [comment]
{"reqId":"tAMb1t8fNuq7wjOlLUal","level":0,"time":"2022-05-11T09:35:34+00:00","remoteAddr":"80.xxx","user":"xxx","app":"scss_cacher","method":"GET","url":"/xxx/settings/admin/logging","message":"SCSSCacher::isCached 35c3-2cc7-settings.css isCachedCache is expired or unset","userAgent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/101.0.4951.54 Safari/537.36","version":"23.0.4.1","id":"627b839201541"}

**Comment by davidpr78** [comment]
{"reqId":"XwZwc8HWpBPHtmgrTMkg","level":0,"time":"2022-05-11T09:35:32+00:00","remoteAddr":"80.xxx","user":"xxx","app":"files_readmemd","method":"POST","url":"/xxx/apps/mail/api/accounts/1/draft","message":"/appinfo/app.php is deprecated, use \\OCP\\AppFramework\\Bootstrap\\IBootstrap on the application class instead.","userAgent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/101.0.4951.54 Safari/537.36","version":"23.0.4.1","id":"627b8396e8cc5"}

**Comment by davidpr78** [comment]
{"reqId":"PIDXSWruG87bvNFZs3Wf","level":0,"time":"2022-05-11T09:35:13+00:00","remoteAddr":"80.xxx","user":"xxx","app":"mail","method":"POST","url":"/xxx/apps/mail/api/mailboxes/19/sync","message":"findByIds in INBOX got 0 UIDs but found none","userAgent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/101.0.4951.54 Safari/537.36","version":"23.0.4.1","id":"627b839825794"}

**Comment by davidpr78** [comment]
{"reqId":"bxCP4EDCiI77vuy2sxD5","level":3,"time":"2022-05-11T09:51:55+00:00","remoteAddr":"80.xxx","user":"xxx","app":"mail","method":"POST","url":"/xxx/apps/mail/api/accounts/1/send","message":"localMessageId is not a valid attribute","userAgent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/101.0.4951.54 Safari/537.36","version":"23.0.4.1","exception":{"Exception":"BadFunctionCallException","Message":"localMessageId is not a valid attribute","Code":0,"Trace":[{"file":"/zfsinst/ed_instances/xxx/lib/public/AppFramework/Db/Entity.php","line":158,"function":"setter","class":"OCP\\AppFramework\\Db\\Entity","type":"->"},{"file":"/zfsinst/ed_instances/xxx/lib/public/AppFramework/Db/Entity.php","line":73,"function":"__call","class":"OCP\\AppFramework\\Db\\Entity","type":"->"},{"file":"/zfsinst/ed_instances/dbs-telgte/lib/public/AppFramework/Db/QBMapper.php","line":320,"function":"fromRow","class":"OCP\\AppFramework\\Db\\Entity","type":"::"},{"file":"/zfsinst/ed_instances/dbs-telgte/lib/public/AppFramework/Db/QBMapper.php","line":361,"function":"mapRowToEntity","class":"OCP\\AppFramework\\Db\\QBMapper","type":"->"},{"file":"/zfsinst/ed_instances/dbs-telgte/apps/mail/lib/Db/LocalAttachmentMapper.php","line":56,"function":"findEntity","class":"OCP\\AppFramework\\Db\\QBMapper","type":"->"},{"file":"/zfsinst/ed_instances/dbs-telgte/apps/mail/lib/Service/Attachment/AttachmentService.php","line":82,"function":"find","class":"OCA\\Mail\\Db\\LocalAttachmentMapper","type":"->"},{"file":"/zfsinst/ed_instances/dbs-telgte/apps/mail/lib/Service/MailTransmission.php","line":380,"function":"getAttachment","class":"OCA\\Mail\\Service\\Attachment\\AttachmentService","type":"->"},{"file":"/zfsinst/ed_instances/dbs-telgte/apps/mail/lib/Service/MailTransmission.php","line":347,"function":"handleLocalAttachment","class":"OCA\\Mail\\Service\\MailTransmission","type":"->"},{"file":"/zfsinst/ed_instances/dbs-telgte/apps/mail/lib/Service/MailTransmission.php","line":158,"function":"handleAttachments","class":"OCA\\Mail\\Service\\MailTransmission","type":"->"},{"file":"/zfsinst/ed_instances/dbs-telgte/apps/mail/lib/Controller/AccountsController.php","line":433,"function":"sendMessage","class":"OCA\\Mail\\Service\\MailTransmission","type":"->"},{"file":"/zfsinst/ed_instances/dbs-telgte/lib/private/AppFramework/Http/Dispatcher.php","line":217,"function":"send","class":"OCA\\Mail\\Controller\\AccountsController","type":"->"},{"file":"/zfsinst/ed_instances/dbs-telgte/lib/private/AppFramework/Http/Dispatcher.php","line":126,"function":"executeController","class":"OC\\AppFramework\\Http\\Dispatcher","type":"->"},{"file":"/zfsinst/ed_instances/dbs-telgte/lib/private/AppFramework/App.php","line":157,"function":"dispatch","class":"OC\\AppFramework\\Http\\Dispatcher","type":"->"},{"file":"/zfsinst/ed_instances/xxx/lib/private/Route/Router.php","line":302,"function":"main","class":"OC\\AppFramework\\App","type":"::"},{"file":"/zfsinst/ed_instances/xxx/lib/base.php","line":1008,"function":"match","class":"OC\\Route\\Router","type":"->"},{"file":"/zfsinst/ed_instances/xxx/index.php","line":36,"function":"handleRequest","class":"OC","type":"::"}],"File":"/zfsinst/ed_instances/xxx/lib/public/AppFramework/Db/Entity.php","Line":129,"CustomMessage":"localMessageId is not a valid attribute"},"id":"627b87af2bb38"}

**Comment by ChristophWurst** [comment]
> localMessageId is not a valid attribute

bingo!

**Comment by ChristophWurst** [comment]
* https://github.com/nextcloud/mail/blob/v1.12.0/lib/Migration/Version1120Date20220223094709.php#L98-L101 added the column to the database
* https://github.com/nextcloud/mail/blob/v1.12.0/lib/Db/LocalMessageMapper.php#L113 loads the row
* https://github.com/nextcloud/mail/blob/v1.12.0/lib/Db/LocalAttachment.php#L57 has the entity attribute

I can't explain why the mapping form row to entity fails with `localMessageId`.

**Comment by miaulalala** [comment]
@davidpr78 do you have access to the source code on your server? If so, can you look at the files Christoph mentioned above to see if you can spot a difference? The most important one would be `lib/Db/LocalAttachment.php` - in line 57 it should say `protected $localMessageId`.

And also check your database table `oc_mail_attachments` to see if it has the column `local_message_id`?

:pray:

**Comment by davidpr78** [comment]
> @davidpr78 do you have access to the source code on your server? If so, can you look at the files Christoph mentioned above to see if you can spot a difference? The most important one would be `lib/Db/LocalAttachment.php` - in line 57 it should say `protected $localMessageId`.
> 
> And also check your database table `oc_mail_attachments` to see if it has the column `local_message_id`?


My organisation uses Edudocs.org 
I don't have access to the source code on the server. Sorry!

**Comment by ChristophWurst** [comment]
Let's see if anyone else runs into this.

**Comment by ChristophWurst** [comment]
Maybe you can ask edudocs support to check in with us in this ticket.

**Comment by t-markmann** [comment]
The line in the file lib/Db/LocalAttachment.php was missing.
I removed the mail app and reinstalled it. Now it is there.

The column in the database is there as well.

Try again David :-)
Thanks for the support Christoph.

**Comment by davidpr78** [comment]
It works. Thank you!!

**Comment by wriver4** [comment]
Code is missing in 11.7 release tag in github
...
class LocalAttachment extends Entity implements JsonSerializable {

public function jsonSerialize() {
	/** @var string */
	protected $userId;

	/** @var string */
	protected $fileName;

	/** @var string */
	protected $mimeType;

	/** @var mixed */
	protected $createdAt;

       public function jsonSerialize() {
		return [
			'id' => $this->id,
			'fileName' => $this->fileName,
		];
	}
}

12.1
...
class LocalAttachment extends Entity implements JsonSerializable {

	/** @var string */
	protected $userId;

	/** @var string */
	protected $fileName;

	/** @var string */
	protected $mimeType;

	/** @var int|null */
	protected $createdAt;

	/** @var int|null */
	protected $localMessageId;

	public function jsonSerialize() {
		return [
			'id' => $this->id,
			'type' => 'local',
			'fileName' => $this->fileName,
			'mimeType' => $this->mimeType,
			'createdAt' => $this->createdAt,
			'localMessageId' => $this->localMessageId
		];
	}
}

**Comment by ChristophWurst** [comment]
That code was only added for v1.12
