### ISSUE TITLE
Avoid having two nested vertical scroll bars at the same time

### ISSUE THREAD

**Issue by mathiasconradt** [nextcloud/mail#641]
In general I think having two nested vertical scrollbars at the same time in web applications is not a good design and should be avoided. It makes scrolling hard (depending where your mouse position is at the moment, when you have a swipe mouse) and is often a bit annoying.

![screen shot 2017-11-28 at 06 54 29](https://user-images.githubusercontent.com/295122/33304549-d914a5d2-d409-11e7-8d40-aac02e9502de.png)

I would split original content/message and reply section into two separately scrollable divs for example. Split screen vertically with resizable handle bar in between.

**Comment by Xananax** [comment]
I have three, and I'm not understanding where they come from. If someone is willing to guide me as to what is creating those bars, I'm willing to write the relevant CSS, test in multiple browsers, and submit a PR

**Comment by jancborchardt** [comment]
This issue is fixed ever since original message and reply composer are separated. :)
