### ISSUE TITLE
Lack of Mail App

### ISSUE THREAD

**Issue by amurdock37** [nextcloud/mail#6414]
### Steps To Reproduce

Installation of script

### Expected Result

Successful installation

### Actual Result

Installed Nextcloud

### Additional Context

I do not see a mail app in the new verison of Nextcloud. Do you still have a script for Nextcloud 23?

### Build Version

24

### Environment

By using the scripts

**Comment by enoch85** [comment]
PHP 8.1
Ubuntu 22.04
PostgreSQL 14

cc @ChristophWurst

**Comment by ChristophWurst** [comment]
https://github.com/nextcloud/mail/pull/6131
