### ISSUE TITLE
No way to move an email or email folder between 2 accounts

### ISSUE THREAD

**Issue by Goldmaster** [nextcloud/mail#6415]
### Steps to reproduce

1. Add 2 email accounts to nextcloud
2. Try and drag an email or folder from 1 email account to another
3. You will find that you can only move an email between folders and not from 1 account to another account.

### Expected behavior

In thunderbird, it is possible to drag and drop an email or folder from 1 account to another or move an email or folder the same way. Why hasn't nextcloud mail added this feature yet?

### Actual behavior

Whe dragging an email, the other account inbox and folders grey out as if there is no way to move an email from account to another.

### Mail app version

latest version

### Mailserver or service

gmail

### Operating system

unraid

**Comment by ChristophWurst** [comment]
Dup of https://github.com/nextcloud/mail/issues/5596
