### ISSUE TITLE
Aliases disappeared after update to latest version

### ISSUE THREAD

**Issue by Chartman123** [nextcloud/mail#6430]
### Steps to reproduce

1. Create aliases in previous version
2. Update mail app
3. See that alias is missing

### Expected behavior

Aliases shouldn't get lost

### Actual behavior

Aliases are lost

### Mail app version

1.12.0

### Operating system

Docker image

### PHP engine version

PHP 8.0

### Web server

Apache (supported)

### Database

PostgreSQL

**Comment by Chartman123** [comment]
Aliases also get lost again after you re-enter them in the settings.

**Comment by crdxfire** [comment]
I can confirm this as well. Aliases are not being saved anymore.

**Comment by ChristophWurst** [comment]
The alias *is* saved. It is stored to `oc_mail_aliases`. But it doesn't show on the UI. I'll investigate.
