### ISSUE TITLE
Provide opt-out setting for the new avatar feature

### ISSUE THREAD

**Issue by jancborchardt** [nextcloud/mail#644]
In the bottom left settings area we should have a »Get avatars from online sources« checkbox which is enabled by default. So that people can disable the checking on Gravatar and external domains.

(And yes, it should be enabled by default as it improves the experience by miles.)

**Comment by fti7** [comment]
Please also provide an Option to do this on a Global-Level (Administrator Settings)

**Comment by jancborchardt** [comment]
@fti7 please test the pull request at https://github.com/nextcloud/mail/pull/653 and comment there accordingly. :)
