### ISSUE TITLE
Alias name ignored

### ISSUE THREAD

**Issue by dugite-code** [nextcloud/mail#645]
### Steps to reproduce
1. Create alias with separate name/email address from sign in address
2. Compose new message
3. Send the email

### Expected behaviour
Address name is used shoud be `Dugite Code <dugite-code@example.tld>`. Verified to work using the same server settings using the android app K9 mail for android

### Actual behaviour
Sign in address name is used i.e. `John Doe <dugite-code@example.tld>`

### Mail app

**Mail app version:**  0.7.5

**Mailserver or service:** Modoboa (Postfix, Dovecote PostgreSQL)

**Transport security - IMAP:** None - Using IMAPProxy on localhost

**Transport security - SMTP:** STARTTLS

**Number of accounts:** 1

### Server configuration
<details>

**Operating system**: Debian 9

**Web server:** Nginx

**Database:** MariaDB

**PHP version:** PHP 7.0

**Version:** 12.0.3

**Updated from an older version or fresh install:** fresh install
</details>

**List of activated apps:**

<details>

| Enabled: | Disabled: |
|-----------|-----------|
|  - activity: 2.5.2 |   - admin_audit |
|  - apporder: 0.4.0 |  - user_ldap |
|  - bookmarks: 0.10.1 | |
|  - bruteforcesettings: 1.0.2 | |
|  - calendar: 1.5.6 | |
|  - checksum: 0.3.5 | |
|  - comments: 1.2.0 | |
|  - contacts: 2.0.1 | |
|  - dav: 1.3.0 | |
|  - deck: 0.2.8 | |
|  - encryption: 1.6.0 | |
|  - federatedfilesharing: 1.2.0 | |
|  - federation: 1.2.0 | |
|  - files: 1.7.2 | |
|  - files_clipboard: 0.6.4 | |
|  - files_external: 1.3.0 | |
|  - files_markdown: 2.0.1 | |
|  - files_pdfviewer: 1.1.1 | |
|  - files_sharing: 1.4.0 | |
|  - files_texteditor: 2.4.1 | |
|  - files_trashbin: 1.2.0 | |
|  - files_versions: 1.5.0 | |
|  - files_videoplayer: 1.1.0 | |
|  - firstrunwizard: 2.1 | |
|  - gallery: 17.0.0 | |
|  - groupfolders: 1.1.0 | |
|  - keeweb: 0.4.0 | |
|  - logreader: 2.0.0 | |
|  - lookup_server_connector: 1.0.0 | |
|  - mail: 0.7.5 | |
|  - metadata: 0.6.0 | |
|  - news: 11.0.5 | |
|  - nextcloud_announcements: 1.1 | |
|  - notifications: 2.0.0 | |
|  - oauth2: 1.0.5 | |
|  - passman: 2.1.4 | |
|  - password_policy: 1.2.2 | |
|  - previewgenerator: 1.0.7 | |
|  - provisioning_api: 1.2.0 | |
|  - quota_warning: 1.1.1 | |
|  - sensorlogger: 0.0.5 | |
|  - serverinfo: 1.2.0 | |
|  - sharebymail: 1.2.0 | |
|  - socialsharing_email: 1.0.1 | |
|  - survey_client: 1.0.0 | |
|  - systemtags: 1.2.0 | |
|  - tasks: 0.9.5 | |
|  - theming: 1.3.0 | |
|  - theming_customcss: 1.0.0 | |
|  - twofactor_backupcodes: 1.1.1 | |
|  - twofactor_totp: 1.3.1 | |
|  - updatenotification: 1.2.0 | |
|  - user_external: 0.4 | |
|  - workflowengine: 1.2.0| | |

</details>

**The content of config/config.php:**

<details>

```
<?php
$CONFIG = array (
  'loglevel' => '3',
  'instanceid' => '*******************************',
  'passwordsalt' => '*******************************',
  'secret' => '*******************************',
  'trusted_domains' =>
  array (
    0 => 'example.tld',
  ),
  'datadirectory' => '/var/www/nextcloud/data',
  'overwrite.cli.url' => 'https://example.tld',
  'dbtype' => 'mysql',
  'version' => '12.0.3.3',
  'dbname' => 'nextcloud',
  'dbhost' => '127.0.0.1',
  'dbport' => '',
  'dbtableprefix' => 'oc_',
  'dbuser' => 'nextcloud',
  'dbpassword' => '*******************************',
  'installed' => true,
  'memcache.local' => '\\OC\\Memcache\\APCu',
  'memcache.locking' => '\\OC\\Memcache\\Redis',
  'filelocking.enabled' => 'true',
  'redis' =>
  array (
    'host' => '/var/run/redis/redis.sock',
    'port' => 0,
    'timeout' => 0.0,
  ),
  'user_backends' =>
  array (
    0 =>
    array (
      'class' => 'OC_User_IMAP',
      'arguments' =>
      array (
        0 => '{mail.example.tld:993/ssl/imap/readonly}',
        1 => 'example.tld',
      ),
    ),
  ),
  'defaultapp' => 'mail',
  'app.mail.imap.timeout' => 30,
  'app.mail.smtp.timeout' => 15,
  'mail_smtptimeout' => 30,
  'mail_smtpmode' => 'smtp',
  'mail_smtpauthtype' => 'PLAIN',
  'mail_from_address' => 'server',
  'mail_domain' => 'example.tld',
  'mail_smtpauth' => 1,
  'mail_smtpname' => 'postmaster@example.tld',
  'mail_smtppassword' => '*******************************',
  'mail_smtphost' => 'mail.example.tld',
  'mail_smtpport' => '587',
  'mail_smtpsecure' => 'tls',
  'mysql.utf8mb4' => true,
  'auth.bruteforce.protection.enabled' => true,
  'maintenance' => false,
  'theme' => '',
);
```
</details>

#### Client configuration
**Browser:** Firefox

**Operating system:** Windows 10

**Comment by jancborchardt** [comment]
This seems to be fixed now, closing hence.
