### ISSUE TITLE
Can not close outbox modal of a scheduled message

### ISSUE THREAD

**Issue by ChristophWurst** [nextcloud/mail#6457]
### Steps to reproduce

1. Compose a message
2. Schedule it for later
3. Reload the page
4. Open the same message
5. Click outside the modal

### Expected behavior

The modal closes.

### Actual behavior

The modal closes but the background overlay stays

![Bildschirmfoto vom 2022-05-16 11-25-17](https://user-images.githubusercontent.com/1374172/168561849-51d3f81d-96e3-4be3-b64b-7db64dff6a66.png)

```
XHRPUThttps://localhost/apps/mail/api/outbox/225
[HTTP/2 500 Internal Server Error 116ms]

OCA\Mail\Controller\OutboxController::update(): Argument #4 ($body) must be of type string, array given
``` 

This is sent to the server
![Bildschirmfoto vom 2022-05-16 11-32-05](https://user-images.githubusercontent.com/1374172/168563126-37f218e5-cda0-425c-854c-ad1a5c33b241.png)

### Additional info

As far as I can tell this is a regression of https://github.com/nextcloud/mail/pull/6350

**Comment by GretaD** [comment]
i think this is a regression of https://github.com/nextcloud/mail/commit/a4b7ca3feec30ff0302fdbf1f6fcbdd3708f1954#diff-7f345453ff2ebcb0438364dc0c2bcdc5f1737b31e70168b49c95b4f54d2e4d8bR5

**Comment by ChristophWurst** [comment]
Because it seems to be of relevance: my account is set to use *plain text* editing and not HTML.
