### ISSUE TITLE
Wrong initial value (NaN) for prop "checked" for scheduled sending radio button

### ISSUE THREAD

**Issue by JuliaKirschenheuter** [nextcloud/mail#6459]
### Steps to reproduce

1. Click to "New message"
2. Choose "Send later"
3. See the wrong initial value for radio button

### Expected behavior

No error, Boolean should be given to scheduled sending radio button

### Actual behavior

Invalid prop: type check failed for prop "checked". Expected Boolean, got Number with value NaN.

### Mail app version

1.12.0

### Mailserver or service

not relevant 

### Operating system

not relevant

**Comment by ChristophWurst** [comment]
This still pops up when I click *Send later*. Could you please have a look?
