### ISSUE TITLE
Long migration time on update to 1.13.0-beta1

### ISSUE THREAD

**Issue by blizzz** [nextcloud/mail#6468]
### Steps to reproduce

1. have an instance with a significant number of mail messages (and users)
1. run server upgrade via cli
2. See Update app mail from App Store

### Expected behavior

1. quick upgrade, or some sort of busy indicator

### Actual behavior

1. Nothing happens, and I wonder about my Internet connection, state of nextcloud etc, 
2. Tables are being emptied via DELETE FROM. This removes rows one by one (MariaDB here). TRUNCATE (respectively the platform-dependent query) should be used instead.

### Mail app version

1.13.0-beta1

### Database

MariaDB

**Comment by ChristophWurst** [comment]
The database abstraction doesn't offer truncate and for the oc_mail_messages table we need a `WHERE` so only cached IMAP messages are deleted and no local outbox messages.

**Comment by ChristophWurst** [comment]
@miaulalala please double check :)

**Comment by blizzz** [comment]
> The database abstraction doesn't offer truncate and for the oc_mail_messages table we need a WHERE so only cached IMAP messages are deleted and no local outbox messages.

I spotted several places in the migration code where there was no WHERE clause. Would not claim it is everywhere the case, but some speed ups could still help.

You can get the query via DatabasePlatform, and it's necessary to have the table prefix placeholder in place.

https://github.com/nextcloud/server/blob/master/apps/user_ldap/lib/Migration/Version1130Date20211102154716.php#L70
