### ISSUE TITLE
Lost update when resuming a scheduled message

### ISSUE THREAD

**Issue by ChristophWurst** [nextcloud/mail#6470]
### Steps to reproduce

1. Compose a new message
2. Schedule it
3. "Send" (save) it
4. Open the message again
5. Change it
6. Click outside the composer modal

### Expected behavior

My latest changes are saved and the message is rescheduled.

### Actual behavior

My latest changes are dropped but the message is rescheduled.

### Mail app version

v1.13.0 Beta 1

### Additional info

Ref https://github.com/nextcloud/mail/pull/6350#discussion_r873935072

**Comment by st3iny** [comment]
This behavior is intended. But I can see that it might be confusing for our users.

**Comment by ChristophWurst** [comment]
How is it intended?

**Comment by st3iny** [comment]
Intended as in I deliberately programmed it this way. I assumed that changes should only be saved through an explicit click on the send button.

**Comment by ChristophWurst** [comment]
There can be at least three scenarios
1) Modal is opened, no modifications are done and the user clicks outside -> nothing to save
2) Modal is opened, modifications are made and user awaits the automatic draft before they click outside -> currently rescheduling restores the values before the draft update
3) Modal is opened, modifications are made and user clicks aware before the automatic drafts -> rescheduling restores the previous version.

In any case we have to assume that users will also accidentally close the modal. It happened to me twice while selecting a recipient. A few pixels away from the multiselect and the modal goes away.

Ideally we would always make sure the latest state is saved as a draft. Then we reschedule or even do it in one step.

**Comment by ChristophWurst** [comment]
Label dropped because it was a duplicate of the attribute at https://github.com/orgs/nextcloud/projects/61. The priority does **not** change.
