### ISSUE TITLE
Unnecessary scrolling in message composer modal / ghost attachments

### ISSUE THREAD

**Issue by ChristophWurst** [nextcloud/mail#6474]
### Steps to reproduce

1. Compose a new message
2. Add an attachment (from Nextcloud files)

### Expected behavior

I see that there is a file attached to the message I'm currently composing

### Actual behavior

The attachment is invisible because the editor has lots of scrolling area even when empty. The attachments are only visible once I scroll down.

### Before scrolling
![Bildschirmfoto vom 2022-05-17 10-43-42](https://user-images.githubusercontent.com/1374172/168769653-cfdbf1fe-edc1-4152-9eb6-a9ccfbef3dbb.png)

### After scrolling
![Bildschirmfoto vom 2022-05-17 10-43-47](https://user-images.githubusercontent.com/1374172/168769742-66c08229-2140-43b3-92dd-8bd21b03abd4.png)

### Mail app version

v1.13.0

**Comment by GretaD** [comment]
what is causing this is min-heigh for body, from a quick look on webconsole, looking into if its actually that :dragon:
