### ISSUE TITLE
Icons vanished

### ISSUE THREAD

**Issue by ChristophWurst** [nextcloud/mail#6478]
### Steps to reproduce

1. Run latest Nextcloud master branch
2. Open the app

### Expected behavior

Icons where we placed them.

### Actual behavior

![Bildschirmfoto vom 2022-05-17 11-47-01](https://user-images.githubusercontent.com/1374172/168782785-00d8cf6b-932d-442d-839b-25f8345adc1e.png)
![Bildschirmfoto vom 2022-05-17 11-47-09](https://user-images.githubusercontent.com/1374172/168782803-45442920-c2ea-47f1-a8a3-686c550b9ca2.png)

### Mail app version

v1.13.0

### Additional info

Possibly related to https://github.com/nextcloud/server/issues/32072

**Comment by GretaD** [comment]
You still have the old icons there, maybe you're not on latest mail? I cannot reproduce

**Comment by ChristophWurst** [comment]
Dup of https://github.com/nextcloud/groupware/issues/38?

**Comment by GretaD** [comment]
> Dup of [nextcloud/groupware#38](https://github.com/nextcloud/groupware/issues/38)?

yes, i thought you just opened this ticket, but you actually just assigned me :roll_eyes:
