### ISSUE TITLE
Migrate to @nextcloud/vue buttons

### ISSUE THREAD

**Issue by ChristophWurst** [nextcloud/mail#6479]
### Is your feature request related to a problem? Please describe.

Since https://github.com/nextcloud/nextcloud-vue/pull/1808 `@nextcloud/vue` has shiny new buttons. This app still doesn't use them.

### Describe the solution you'd like

Use Vue buttons instead of HTML buttons to give the UI a more refreshed and consistent look.

### Additional context

Buttons require Nextcloud 23 to work if I remember correctly. Setting as blocked for now.

**Comment by GretaD** [comment]
done and released since v1.14
