### ISSUE TITLE
Implement autocrypt [$5]

### ISSUE THREAD

**Issue by stefan-niedermann** [nextcloud/mail#648]
This is a feature request to implement [autocrypt](https://autocrypt.org/en/latest/).

Long story short:

- E-Mails get encrypted as good as possible without **any** user interaction needed (no user wants to challenge pgp/gpg nor read anything about keys)
- Many clients support it (K-9, Enigmail-Thunderbird Add-On, DeltaChat and others)

**Comment by nsrosenqvist** [comment]
Is there a timeframe for this?

**Comment by ChristophWurst** [comment]
No

**Comment by cmonagle** [comment]
It looks like Mailvelope has support for Autocrypt coming in the pipeline:
https://github.com/mailvelope/mailvelope/pull/669

**Comment by jancborchardt** [comment]
Seems like the pull request to integrate Autocrypt into Mailvelope was merged meanwhile mailvelope/mailvelope#669 (thanks @cmonagle for bringing it up!) → We can close this. :)

**Comment by stefan-niedermann** [comment]
Mailvelope is a 3rd-party browser extension as far as i understand. How does this affect the direct support for autocrypt in Nextcloud Mail?

**Comment by BuZZ-dEE** [comment]
@jancborchardt Mailvelope is a third party extension. It would be great if this is directly supported by Nextcloud mail. Could you please open this issue again?

**Comment by ChristophWurst** [comment]
Would you have the resources to deliver the implementation?
