### ISSUE TITLE
Missing save attachment/close button

### ISSUE THREAD

**Issue by ddecaro94** [nextcloud/mail#649]
Good evening,
I want to submit to your interest the issue i've experienced lately.
I have a fresh install of nextcloud 12 on a private server on ubuntu 17.10.

Your app is great and working perfectly, nevertheless very useful, though i couldn't upload attachments to nextcloud: i couldn't find the save button to commit the operation once selected the folder. Also i had no way to go back from uploading except for reloading the page.

Thanks in advance for your interest!

### Steps to reproduce
1. Open a mail containing an attachment
2. Click on save to files
3. Navigation modal appears - no button to select folder or close

### Mail app

**Mail app version:** (see apps admin page)
0.7.5
**Mailserver or service:** (e.g. Outlook, Yahoo, Gmail, Exchange,...)
Gmail
**Transport security - IMAP:** (None, SSL, TLS, STARTTLS) 

**Transport security - SMTP:** (None, SSL, TLS, STARTTLS)

**Number of accounts:**
1
**Mail app version build date:** (only if you are using a Nightly Build)

### Server configuration

**Operating system**:
Ubuntu 17.10
**Web server:**
Apache
**Database:**
MySQL
**PHP version:**
7.1
**Version:** (see admin page)
12.0.3
**Updated from an older version or fresh install:**
Fresh

#### Client configuration
**Browser:**
Chrome 62 - Opera - Firefox
**Operating system:**
Windows - Ubuntu 16.10

##### Browser log
<details>
```
[1512320991131.log](https://github.com/nextcloud/mail/files/1524979/1512320991131.log)

```
</details>

**Comment by ChristophWurst** [comment]
Thanks a lot for reporting. I saw this too and it's pretty annoying.

**Comment by ChristophWurst** [comment]
This seems to be related to #626. Strangely enough, the file picker seems to work depending on which app is active. It *does* work for files and activity. In the mail app, the clos icon is missing. In the contacts app, I get `Error: cannot call methods on ocdialog prior to initialization; attempted to call method 'close'`. I don't get the connection.

Steps to reproduce: run `OC.dialogs.filepicker(t('mail', 'Choose a folder to store the attachment in'))` in your browser's console.

@icewind1991 @MorrisJobke any ideas?

**Comment by ChristophWurst** [comment]
> the file picker seems to work depending on which app is active.

The generated HTML is also different. The close button is already missing in the HTML structure. First, it thought it would be hidden/invisible but that turned out to be wrong.

**Comment by MorrisJobke** [comment]
> @icewind1991 @MorrisJobke any ideas?

Maybe some needed CSS is not properly loaded :/

**Comment by ChristophWurst** [comment]
I'd say this is a dup of https://github.com/nextcloud/mail/issues/626.
