### ISSUE TITLE
Sending emails to GMX (also web.de) email addresses in BCC fails due to policy restrictions

### ISSUE THREAD

**Issue by LostinSpacetime** [nextcloud/mail#6497]
### Steps to reproduce

1. Create new message
2. Add an existing recipient address  xxxxxxxx@gmx.at to BCC
3. Send email

### Expected behavior

Email should be accepted by the GMX server

### Actual behavior

Email is rejected with the following error:

212.227.15.9 failed after I sent the message.
Remote host said: 554-Transaction failed
554-Reject due to policy restrictions.
554 For explanation visit https://www.gmx.net/mail/senderguidelines?ip=85.158.181.12&c=hi

### Mail app version

1.12.0

### Operating system

Ubuntu 18.04

### PHP engine version

PHP 8.0

### Web server

Apache (supported)

### Database

MariaDB

### Additional info

--- Below this line is a copy of the message.

```
Return-Path: [<name@someschool.at>](mailto:name@someschool.at)
Received: (qmail 22419 invoked from network); 18 May 2022 15:37:06 +0200
X-Fcrdns: Yes
Received: from static.22.135.202.116.clients.your-server.de (HELO nextcloud.wien) (116.202.135.22)
  (smtp-auth username [name@someschool.at](mailto:name@someschool.at), mechanism plain)
  by cloud9-vm114.de-nserver.de (qpsmtpd/0.92) with (TLS_AES_256_GCM_SHA384 encrypted) ESMTPSA; Wed, 18 May 2022 15:37:06 +0200
X-GeoIP-Country: DE
From: Some Name [<name@someschool.at>](mailto:name@someschool.at)
To: 
Cc: 
Subject: test5
Message-ID: [<20220518133704.Horde.v-cbH6nQu64HNJc8FdEh5eV@nextcloud.wien>](mailto:20220518133704.Horde.v-cbH6nQu64HNJc8FdEh5eV@cloud.schloss-schule.wien)
User-Agent: Horde Application Framework 5
Date: Wed, 18 May 2022 13:37:04 +0000
Content-Type: multipart/alternative; boundary="=_7Zet-MgdtjmARJWzO5R3AO9"
MIME-Version: 1.0
Content-Transfer-Encoding: 8bit
X-User-Auth: Auth by [name@someschool.at(mailto:name@someschool.at) through 116.202.135.22

This message is in MIME format.

--=_7Zet-MgdtjmARJWzO5R3AO9
Content-Type: text/plain; charset=utf-8
Content-Description: Plaintext Version of Message
Content-Transfer-Encoding: 8bit

 
test
--=_7Zet-MgdtjmARJWzO5R3AO9
Content-Type: text/html; charset=utf-8
Content-Description: HTML Version of Message

<p style="margin:0;">&nbsp;</p><p style="margin:0;">test</p>
--=_7Zet-MgdtjmARJWzO5R3AO9--
```

**Comment by LostinSpacetime** [comment]
This problem appeared after updating to 1.12.0.

**Comment by Chartman123** [comment]
Are you sure? I know of this behaviour for a longer time... GMX (and others) accepts mails only if there is at least one "to" recipient and not only BCCs.

**Comment by LostinSpacetime** [comment]
> Are you sure? I know of this behaviour for a longer time... GMX (and others) accepts mails only if there is at least one "to" recipient and not only BCCs.

You are right.
