### ISSUE TITLE
Update app logo design

### ISSUE THREAD

**Issue by ChristophWurst** [nextcloud/mail#6498]
### Is your feature request related to a problem? Please describe.

After all these years with the same unmodified icon I wonder if it's time to refresh it a bit.

### Describe the solution you'd like

Like with the rest of our icons, move towards the design language of material icons.

Examples

* https://materialdesignicons.com/icon/email
* https://materialdesignicons.com/icon/email-outline

### Additional context

cc @jancborchardt @nimishavijay

**Comment by jancborchardt** [comment]
Probably makes sense to put that in line. Just a note though, materialdesignicons.com is a community site – we need to always check the official Material Design icons at https://material.io/icons before. :) (Also we use rounded filled icons, not outline.)

In this case it’s of course simple as it’s just an email icon, so it would be this: https://fonts.google.com/icons?selected=Material%20Icons%3Aemail%3A

**Comment by jancborchardt** [comment]
Also cc @cartierbresson @karlitschek regarding marketing and branding – this probably makes sense since we switch everything else to Material Design icons, so it doesn’t look out of place.

**Comment by jancborchardt** [comment]
> Does anyone know if/how we need to attribute the icon source if we make a copy for our app icon?

Material Design Icons are licensed under Apache License 2.0, these are the (human readable) conditions: https://en.wikipedia.org/wiki/Apache_License#Licensing_conditions

**Comment by ChristophWurst** [comment]
> In every licensed file, original copyright, patent, trademark, and attribution notices must be preserved

The file at https://fonts.gstatic.com/s/i/materialicons/email/v18/24px.svg does *not* contain license information.

I suppose we can do it like Calendar and https://github.com/nextcloud/calendar/blob/main/img/LICENSES.md

**Comment by ChristophWurst** [comment]
Curiosity preview

![Bildschirmfoto vom 2022-06-30 13-55-27](https://user-images.githubusercontent.com/1374172/176671266-e0d1dcbb-d0e3-4bf1-8269-459653d25fed.png)

**Comment by GretaD** [comment]
> > In every licensed file, original copyright, patent, trademark, and attribution notices must be preserved
> 
> The file at https://fonts.gstatic.com/s/i/materialicons/email/v18/24px.svg does _not_ contain license information.
> 
> I suppose we can do it like Calendar and https://github.com/nextcloud/calendar/blob/main/img/LICENSES.md

i will do it like this then
