### ISSUE TITLE
TypeError for accoutId

### ISSUE THREAD

**Issue by moraus** [nextcloud/mail#650]
### Steps to reproduce
1. Clear cache
2. Reload nextcloud and mail app

### Expected behaviour
Mail app loaded as expected

See details on the attached screenshots under "details" below

### Actual behaviour
Mail app hanging with "spinning wheel", and displaying "Error: Failed to load account"
Browser error 500

![screenshot from 2017-12-04 08-57-03](https://user-images.githubusercontent.com/4199965/33542503-9a2b6d5a-d8d3-11e7-9472-90b3dff73ffb.png)
![screenshot from 2017-12-04 08-55-18](https://user-images.githubusercontent.com/4199965/33542502-9a129f50-d8d3-11e7-9061-7dbae971f1c9.png)

### Mail app

**Mail app version:**
0.7.5

**Mailserver or service:** 
Exim4 (4.86.2)

**Transport security - IMAP:** (None, SSL, TLS, STARTTLS) 
TLS

**Transport security - SMTP:** (None, SSL, TLS, STARTTLS)
TLS

**Number of accounts:**
1

**Mail app version build date:** (only if you are using a Nightly Build)
Stable

### Server configuration

**Operating system**:
Linux

**Web server:**
apache2.4

**Database:**
Mysql

**PHP version:**
7

**Version:** (see admin page)
12.0.3

**Updated from an older version or fresh install:**
Update

**List of activated apps:**
Enabled:
  - activity: 2.3.2
  - apporder: 0.3.2
  - bookmarks: 0.9.0
  - calendar: 1.4.1
  - comments: 0.3.0
  - configreport: 0.1.1
  - contacts: 1.5.1
  - dav: 0.2.7
  - external: 1.2
  - federatedfilesharing: 0.3.0
  - federation: 0.1.0
  - files: 1.5.1
  - files_external: 0.6.0
  - files_mv: true
  - files_pdfviewer: 0.8.1
  - files_sharing: 0.10.0
  - files_texteditor: 2.1
  - files_trashbin: 0.9.0
  - files_versions: 1.3.0
  - files_videoplayer: 0.9.8
  - firstrunwizard: 1.1
  - gallery: 15.0.0
  - mail: 0.6.0
  - notifications: 0.3.0
  - passman: 1.3.38
  - provisioning_api: 0.5.0
  - systemtags: 0.3.0
  - tasks: 0.9.4
  - templateeditor: 0.1
  - updatenotification: 0.2.1
  - user_external: 0.4
Disabled:
  - encryption
  - example-theme
  - files_antivirus
  - market

**The content of config/config.php:**

<details>

</details>

#### Client configuration
**Browser:**
Chrome 62

**Operating system:**
Linux

##### Web server error log
Failed to load resource: the server responded with a status of 500 (Internal Server Error)

##### Server log (data/nextcloud.log)
<details>
Nothing to log
</details>

##### Horde IMAP log (data/horde_imap.log)
<details>
Nothing to log
</details>

##### Horde SMTP log (data/horde_smtp.log)
<details>
Nothing to log
</details>

##### Browser log
<details>
See screenshots above
</details>

**Comment by ChristophWurst** [comment]
> Browser error 500

*server error 😉 

Please complete the issue template and provide your log files. Otherwise we won't be able to help because the error happened on the server-side.

**Comment by moraus** [comment]
I'm sorry.
This error was caused by the app Gallery, which had created a ".nomedia" file inside the Maildir.
Closing this bug as "user error"
`Horde_Imap_Client_Exception_ServerResponse: IMAP error reported by server.
/var/www/nextcloud/apps/mail/vendor/pear-pear.horde.org/Horde_Imap_Client/Horde/Imap/Client/Socket.php - line 4302: Horde_Imap_Client_Socket->_getLine(Object(Horde_Imap_Client_Interaction_Pipeline))
/var/www/nextcloud/apps/mail/vendor/pear-pear.horde.org/Horde_Imap_Client/Horde/Imap/Client/Socket.php - line 4230: Horde_Imap_Client_Socket->_sendCmdChunk(Object(Horde_Imap_Client_Interaction_Pipeline), Array)
/var/www/nextcloud/apps/mail/vendor/pear-pear.horde.org/Horde_Imap_Client/Horde/Imap/Client/Socket.php - line 1751: Horde_Imap_Client_Socket->_sendCmd(Object(Horde_Imap_Client_Interaction_Pipeline))
/var/www/nextcloud/apps/mail/vendor/pear-pear.horde.org/Horde_Imap_Client/Horde/Imap/Client/Base.php - line 1728: Horde_Imap_Client_Socket->_status(Array, 8205)
/var/www/nextcloud/apps/mail/vendor/pear-pear.horde.org/Horde_Imap_Client/Horde/Imap/Client/Base.php - line 4033: Horde_Imap_Client_Base->status(Array, 8205)
/var/www/nextcloud/apps/mail/vendor/pear-pear.horde.org/Horde_Imap_Client/Horde/Imap/Client/Base.php - line 3585: Horde_Imap_Client_Base->_syncStatus('INBOX.nomedia')
/var/www/nextcloud/apps/mail/lib/Service/FolderMapper.php - line 56: Horde_Imap_Client_Base->getSyncToken('INBOX.nomedia')
/var/www/nextcloud/apps/mail/lib/Service/MailManager.php - line 70: OCA\Mail\Service\FolderMapper->getFolders(Object(OCA\Mail\Account), Object(Horde_Imap_Client_Socket))
/var/www/nextcloud/apps/mail/lib/Controller/FoldersController.php - line 71: OCA\Mail\Service\MailManager->getFolders(Object(OCA\Mail\Account))
[internal function] OCA\Mail\Controller\FoldersController->index(4)
/var/www/nextcloud/lib/private/AppFramework/Http/Dispatcher.php - line 160: call_user_func_array(Array, Array)
/var/www/nextcloud/lib/private/AppFramework/Http/Dispatcher.php - line 90: OC\AppFramework\Http\Dispatcher->executeController(Object(OCA\Mail\Controller\FoldersController), 'index')
/var/www/nextcloud/lib/private/AppFramework/App.php - line 114: OC\AppFramework\Http\Dispatcher->dispatch(Object(OCA\Mail\Controller\FoldersController), 'index')
/var/www/nextcloud/lib/private/AppFramework/Routing/RouteActionHandler.php - line 47: OC\AppFramework\App main('OCA\\Mail\\Contro...', 'index', Object(OC\AppFramework\DependencyInjection\DIContainer), Array)
[internal function] OC\AppFramework\Routing\RouteActionHandler->__invoke(Array)
/var/www/nextcloud/lib/private/Route/Router.php - line 299: call_user_func(Object(OC\AppFramework\Routing\RouteActionHandler), Array)
/var/www/nextcloud/lib/base.php - line 1004: OC\Route\Router->match('/apps/mail/api/...')
/var/www/nextcloud/index.php - line 48: OC handleRequest()
{main}`
