### ISSUE TITLE
Revert Procedure from v12.0 to to 11.7

### ISSUE THREAD

**Issue by wriver4** [nextcloud/mail#6506]
### Steps to reproduce

1. Try to send to 11 or more people in any combination, and it hangs in outbox and none are sent
2. Missing Signature.
3.

### Expected behavior

working correctly

### Actual behavior

steps to reproduce

### Mail app version

12.0

### Mailserver or service

bluehost

### Operating system

Ubuntu 20.04

### PHP engine version

PHP 7.4

### Web server

Apache (supported)

### Database

MySQL

### Additional info

I know you are working on a resolution and v13. User complaints are killing me, so thought I would inquire.

**Comment by ChristophWurst** [comment]
There is no downgrade support for Nextcloud apps.

Restore a snapshot from before the upgrade or wait for v1.12.1. It will come in a few days.
