### ISSUE TITLE
Can't write e-mail on an iPad

### ISSUE THREAD

**Issue by davidpr78** [nextcloud/mail#6507]
### Steps to reproduce

Write new mail in safari browser on an iPad. 

https://user-images.githubusercontent.com/60741877/169364308-cda31372-f305-4ffb-8ae3-be19d431b76d.mp4

### Expected behavior

You can write an e-mail in safari on an iPad

### Actual behavior

You can't type into the mail text area.

### Mail app version

1.12.0

### Mailserver or service

WebhostOne

### Operating system

Edudocs

**Comment by ChristophWurst** [comment]
so when you click into the editor, it doesn't focus?

**Comment by davidpr78** [comment]
Nothing happens

**Comment by davidpr78** [comment]
It doesn't work on a Mac with Safari either. Please fix this.

**Comment by davidpr78** [comment]
There are a bunch of experimental features for Safari on iPad. Maybe there is sth that would help? (Java Skript is on)
![IMG_0525](https://user-images.githubusercontent.com/60741877/169845153-b6a11b2f-bf72-4df3-a4cf-9cc2ed88d8d7.PNG)
![IMG_0526](https://user-images.githubusercontent.com/60741877/169845171-15df2215-8819-4f39-ba6f-35053df0b034.PNG)
![IMG_0527](https://user-images.githubusercontent.com/60741877/169845177-ea25fd47-4c34-49e1-8b4b-8401d2371b17.PNG)
![IMG_0528](https://user-images.githubusercontent.com/60741877/169845185-6595d80d-a7c6-4935-8551-5ac13d81abfe.PNG)
![IMG_0529](https://user-images.githubusercontent.com/60741877/169845188-519175e9-2d13-4542-911d-29ca8d0ffb58.PNG)
![IMG_0530](https://user-images.githubusercontent.com/60741877/169845190-bd6edd51-0c22-4277-9321-5f49e2f5abd1.PNG)
![IMG_0531](https://user-images.githubusercontent.com/60741877/169845193-10cc31bc-bddd-4ac3-83b8-fda45afa8ce0.PNG)

**Comment by mellow2012** [comment]
Same hear on iphone and ipad
any update for that problem?

**Comment by davidpr78** [comment]
Its fixed in 1.13.5!
