### ISSUE TITLE
Unbalanced focus border for composer subject

### ISSUE THREAD

**Issue by ChristophWurst** [nextcloud/mail#6510]
### Steps to reproduce

1. Click *New message*
2. Focus the subject input

### Expected behavior

Same border on top and bottom.

### Actual behavior

![Bildschirmfoto vom 2022-05-20 08-53-13](https://user-images.githubusercontent.com/1374172/169471032-aafb19e6-c87a-40f1-be42-432f55e72736.png)

### Mail app version

v1.13.0

### Additional info

Using Nextcloud server master.

**Comment by Zivangu9** [comment]
I test in my Development setup and I don't see the error you mention, actually the border doesn't highlight on focus. Maybe because I have version 1.13.0-beta.2

**Comment by ChristophWurst** [comment]
What version of Nextcloud did you test with?

**Comment by Zivangu9** [comment]
Use the latest version, (24.0.1)

**Comment by ChristophWurst** [comment]
It doesn't appear there. It only shows with Nextcloud 25/development version

**Comment by ChristophWurst** [comment]
Not the case anymore
