### ISSUE TITLE
Ability to access a shared mailbox within Microsoft 365

### ISSUE THREAD

**Issue by crdxfire** [nextcloud/mail#6524]
### Is your feature request related to a problem? Please describe.

No

### Describe the solution you'd like

In order to access a shared mailbox within Microsoft 365 via IMAP, you have to use username@domain.tld\sharedmailboxname@domain.tld as username.

### Describe alternatives you've considered

Use a different Mail program...

### Additional context

Even if I try to use username@domain.tld\alias oder username@domain.tld\sharedmailbox@domain.tld I get the error username or password wrong. Double-checked functionality with other Email client and it works.

**Comment by ChristophWurst** [comment]
I have the feeling this could be due to the special meaning of a backslash.

Could you try with one or two forward slashes instead of the backslash?

Ref https://social.technet.microsoft.com/Forums/en-US/336e02ee-6767-4810-90a0-1352bd7cc9e9/office-365-how-to-access-a-shared-mailbox-using-imap-client?forum=onlineservicesexchange

**Comment by crdxfire** [comment]
Hey Christoph, I've double-checked it right now with one and two forward slashes, unfortunately without success. The link from technet you are referring to is exactly the one I've read and was referring to. If there would be a way to get this working, would be great, as we would require it for ourselves and another customer.

I don't know how difficult it would be to implement this, but for me it looks like a common use-case, as both - Microsoft 365 and shared mailboxes - are widely in use today.

**Comment by stavros-k** [comment]
Some desktop clients I've used for shared mailbox, they are worked fine with `/` (forward slash).
You could give it a shot. But no guarantees!

**Comment by ChristophWurst** [comment]
This should be supported now. The app can process ACLs set via IMAP. See also https://github.com/nextcloud/mail/issues/7057.
