### ISSUE TITLE
The width of the list of e-mail messages should be possible to configure.

### ISSUE THREAD

**Issue by RokeJulianLockhart** [nextcloud/mail#6525]
### Is your feature request related to a problem? Please describe.

"http://github.com/nextcloud/mail/issues/3940" explains that the current list of messages is unnecessarily large.

### Describe the solution you'd like

I propose that whether avatars are presented be possible to disable, and that the size of the font be reduced to that of normal text.

### Additional context

“http://github.com/nextcloud/mail/issues/3940#issuecomment-913830020”.

**Comment by GretaD** [comment]
We now have at least 2 features that resolve this issue. We have resizable columns and now we can change the mail layout to list layout or horizontal layout that shows the envelope list in full width :)
