### ISSUE TITLE
Duplicate Emails sent

### ISSUE THREAD

**Issue by yankees5963** [nextcloud/mail#6535]
### Steps to reproduce

1. Reply to email
2. Open Outlook and view two messages sent
3. Duplicate messages should be shown in any future reply from the recipient. 

### Expected behavior

One email sent to recipient

### Actual behavior

Two emails sent to recipient with duplicate messages at the same timestamp. Send button was only clicked once, and did not display any errors.

### Mail app version

1.13.0-beta1

### Mailserver or service

Outlook

### Operating system

Docker Install on Ubuntu 22.04 LTS

### PHP engine version

PHP 8.1

### Web server

Nginx

### Database

MariaDB

### Additional info

Appears to be only with Outlook emails. On fresh install with newest beta, I was able to see a reply was sent and the second was stuck on the outbox. I was able to delete the one stuck in outbox before it sent a duplicate. Not sure why two email replies are created for outlook emails only.

**Comment by ChristophWurst** [comment]
This should be fixed. This was a bug in the outbox logic.
