### ISSUE TITLE
Send button hidden behind the XMPP Chat panel

### ISSUE THREAD

**Issue by DiGGeR2** [nextcloud/mail#654]
### Steps to reproduce
1. Open Mail application
2. Click on new message
3. The "Send" button is behid the XMPP Chat panel

### Expected behaviour
When I open or close the chat panel, all is well resized except the "Send" button.

**Comment by ChristophWurst** [comment]
Hi,

I'd say that's a bug/issue of the XMPP app since also other apps are potentially effected if it overlays the app content view.

**Comment by DiGGeR2** [comment]
All other apps react well on open and close the XMPP panel... the Mail app too, except the "Send" button...

**Comment by ChristophWurst** [comment]
So you're saying that e.g. the calendar app would adjust it's calendar view if the chat view overlaps an event?

Neither do I know how this app is supposed to detect this case, nor do I see why it's responsible for that.
cc @jancborchardt for cross-app input. I don't use the chat app.

**Comment by ChristophWurst** [comment]
Wait a minute. I think now I get what you're talking about. It's a *sidebar*, not some chat overlay on the bottom, right? Would be great to see a screenshot and a link to which chat app you're actually referring. To my knowledge there are at least two.

**Comment by DiGGeR2** [comment]
![visualproblem](https://user-images.githubusercontent.com/1783500/33573723-fc17a4b2-d936-11e7-8512-674d82f2ff94.png)

**Comment by ToeJet** [comment]
I am encountering the same issue.   Firefox 58.  Nextcloud 13.  Integrated chat function.   Same issue was occuring before upgrading to 13.   There a work around other than shrinking chat?
