### ISSUE TITLE
Could not send message: The recipient address <firstname.lastname> is not a valid RFC-5321 address.

### ISSUE THREAD

**Issue by feutl** [nextcloud/mail#6545]
### Steps to reproduce

Actually I assume that this is the reason for the problem I have.
One of my users sees
![image](https://user-images.githubusercontent.com/8522012/170200739-49260b2a-d0bc-4bac-a95e-fd9c0e292611.png)
for days now and has no chance to delete nor overcome that situation.

I looked into the logs and found that `Could not send message: The recipient address <xxx> is not a valid RFC-5321 address.` shows up every 10 minutes in the logs, and the mail address (just firstname.lastname no domain) belongs to the users address book.

The user sent a mail using a contact group as the recipient including a not fully compliant mail address. This is what we assume triggered this situation.
The mail server contacted is gmail.

I have no clue how to get rid of this message which fills the logs, and annoys the user from having and non-empty outbox.

### Expected behavior

Get the error message into the "inbox" of the user and the outbox gets emptied and sending is not retried over and over again.

### Actual behavior

Mail is stuck in outbox of NC Mail and seems to get resend and rejected over and over again.

### Mail app version

1.12.0

### Mailserver or service

gmail

### Operating system

debian

### PHP engine version

PHP 7.4

### Web server

Apache (supported)

### Database

MariaDB

**Comment by ChristophWurst** [comment]
The resend is intended for any temporary SMTP server issues but here it shouldn't retry actually. This is related to https://github.com/nextcloud/mail/issues/6540.

The user should be able to see and delete the message from the outbox with v1.12.1.

**Comment by ChristophWurst** [comment]
The release automation failed. I've retriggered the release of v1.12.1.

**Comment by feutl** [comment]
Was able to see and delete the message with 1.12.1 👍
