### ISSUE TITLE
Can't send newly composed mail (send button is bright), but I can send "replay to".

### ISSUE THREAD

**Issue by ratermir** [nextcloud/mail#6550]
### Steps to reproduce

Can't send newly composed e-mails since the "Send" button is bright and does'nt allow to be clicked. There is no explanation why I can't click it.

### Expected behavior

To allow always clicking to the "Send" button (regardless the mail composition status). All necessary checks perform after clicking and - in case of any issue - show proper message (ideally with navigation to the mistaken part)

### Actual behavior

When compose new mail I fill all necessary data (target e-mail, topic and body) but the "send" button is still "bright" and I can't send the mail. 
When I compose new mail with the "reply to" (to the same address as I composed previous mail for), everything works and the mail is sent (and delivered) to target address. 

### Mail app version

1.12.1

### Mailserver or service

Private mail server (the "mailu"), works wekk with another e-mail clients

### Operating system

OPenSuSE Linux, Kubernetes / Docker

### PHP engine version

PHP 8.1

### Web server

Nginx

### Database

PostgreSQL

### Additional info

Nextcloud 23.0.3, 
![image](https://user-images.githubusercontent.com/52619304/170250370-31ee8cf7-d4f5-47f1-9ab7-b63a58e78b71.png)

**Comment by ChristophWurst** [comment]
The recipient isn't selected. Press enter or click on the email address.

For further questions please use https://help.nextcloud.com/c/apps/mail/35

**Comment by ratermir** [comment]
Wow ... thank you for super-fast response. But ... it is not too intuitive if I see the whole (and correct) target address but it does not work

**Comment by GretaD** [comment]
> Wow ... thank you for super-fast response. But ... it is not too intuitive if I see the whole (and correct) target address but it does not work

Yes, we are aware of this problem and we will try to improve the multiselect component as soon as possible.
