### ISSUE TITLE
The attach file from Nextcloud has no "attach button" to select (and close windows)

### ISSUE THREAD

**Issue by DiGGeR2** [nextcloud/mail#656]
### Steps to reproduce
1. Click on New Message
2. Try to attach a File from Nextcloud
3. There is no "Attach button"

### Mail app

**Mail app version: 0.7.5

This bug is only in 0.7.5, the button is present in 0.7.4 (In 0.7.4 this box have a Title, not in the 0.7.5 .

Tested with Latest Firefox and Chrom web browser.

**Comment by ChristophWurst** [comment]
Dup of https://github.com/nextcloud/mail/issues/649
