### ISSUE TITLE
IMAP standart and ghostly labels with NC tags

### ISSUE THREAD

**Issue by sazanof** [nextcloud/mail#6561]
### Is your feature request related to a problem? Please describe.

**One day**, after connecting a Yandex Mail account, I noticed a strange thing - I had additional tags in the list of tags. Among them were the tags "encrypted", "system hamon", "redmine forgotten", "delivery confirmation". The paradox is that I did not create these labels and did not assign these labels to emails. If I can still associate the last two with services, then the first two are not. Especially "encrypted". I thought it was some kind of system tag and in a puff I sent a PR https://github.com/nextcloud/mail/pull/6551  

![image](https://user-images.githubusercontent.com/3595562/170439191-895a9e1d-bc9d-4fcd-8439-05145e54dee4.png)

The fact is that "I'm always frustrated when" I see a tag in the list of letters, which not only came from nowhere, but it also spoils the list of letters ... =(

![image](https://user-images.githubusercontent.com/3595562/170439334-2ab6ee4a-7906-4b51-89d8-3e9cd156d9b6.png)

Thanks!

### Describe the solution you'd like

It may be worth defining a list of standard tags, or weeding out obscure tags (since their display only confuses), or writing them into the design with certain symbols (or highlights). Is it also possible to add functionality to the labels to change the color.

### Describe alternatives you've considered

https://github.com/nextcloud/mail/pull/6551

### Additional context

This strange tags below
![image](https://user-images.githubusercontent.com/3595562/170438793-caab4cfc-9c35-4d3b-a25d-d252f5fc466c.png)

This list whith strange tags (strange tags are first & I cant see this tag, because it has no color)
![image](https://user-images.githubusercontent.com/3595562/170438991-b15eac36-ba1e-4167-8751-dc807b2f0d62.png)

**Comment by jancborchardt** [comment]
Yep, so just like the ones reported in https://github.com/nextcloud/mail/issues/6020, we can just add those additional tags to the list? They definitely should be filtered out and not shown.
