### ISSUE TITLE
Random background sync error

### ISSUE THREAD

**Issue by jet438** [nextcloud/mail#6563]
### Steps to reproduce

Not sure

### Expected behavior

No error

### Actual behavior

Random errors

### Mail app version

1.12.1

### Mailserver or service

Gmail

### Operating system

Ubuntu 22.04

### PHP engine version

PHP 8.1

### Web server

Nginx

### Database

MariaDB

### Additional info

[mail] Error: OCA\Mail\Exception\MailboxLockedException: 6 is already being synced at <<closure>>

0. /var/www/nextcloud/apps/mail/lib/Db/MailboxMapper.php line 168
   OCA\Mail\Exception\MailboxLockedException::from()
1. /var/www/nextcloud/apps/mail/lib/Db/MailboxMapper.php line 192
   OCA\Mail\Db\MailboxMapper->lockForSync()
2. /var/www/nextcloud/apps/mail/lib/Service/Sync/ImapToDbSynchronizer.php line 209
   OCA\Mail\Db\MailboxMapper->lockForNewSync()
3. /var/www/nextcloud/apps/mail/lib/Service/Sync/ImapToDbSynchronizer.php line 135
   OCA\Mail\Service\Sync\ImapToDbSynchronizer->sync()
4. /var/www/nextcloud/apps/mail/lib/BackgroundJob/SyncJob.php line 122
   OCA\Mail\Service\Sync\ImapToDbSynchronizer->syncAccount()
5. /var/www/nextcloud/lib/public/BackgroundJob/Job.php line 79
   OCA\Mail\BackgroundJob\SyncJob->run()
6. /var/www/nextcloud/lib/public/BackgroundJob/TimedJob.php line 95
   OCP\BackgroundJob\Job->execute()
7. /var/www/nextcloud/cron.php line 151
   OCP\BackgroundJob\TimedJob->execute()

at 2022-05-25T18:10:08+00:00

{"reqId":"Uvqgn0AjKxr1ieV7vUmu","level":3,"time":"2022-05-25T11:12:25+00:00","remoteAddr":"24.103.1.10","user":"kc","app":"mail","method":"POST","url":"/apps/mail/api/mailboxes/6/sync","message":"Could not fetch stats of mailbox 6. IMAP error: Mail server denied authentication.","userAgent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/101.0.4951.67 Safari/537.36","version":"24.0.1.1","exception":{"Exception":"OCA\\Mail\\Exception\\ServiceException","Message":"Could not fetch stats of mailbox 6. IMAP error: Mail server denied authentication.","Code":102,"Trace":[{"file":"/var/www/nextcloud/apps/mail/lib/Service/Sync/SyncService.php","line":130,"function":"syncStats","class":"OCA\\Mail\\IMAP\\MailboxSync","type":"->"},{"file":"/var/www/nextcloud/apps/mail/lib/Controller/MailboxesController.php","line":161,"function":"syncMailbox","class":"OCA\\Mail\\Service\\Sync\\SyncService","type":"->"},{"file":"/var/www/nextcloud/lib/private/AppFramework/Http/Dispatcher.php","line":225,"function":"sync","class":"OCA\\Mail\\Controller\\MailboxesController","type":"->"},{"file":"/var/www/nextcloud/lib/private/AppFramework/Http/Dispatcher.php","line":133,"function":"executeController","class":"OC\\AppFramework\\Http\\Dispatcher","type":"->"},{"file":"/var/www/nextcloud/lib/private/AppFramework/App.php","line":172,"function":"dispatch","class":"OC\\AppFramework\\Http\\Dispatcher","type":"->"},{"file":"/var/www/nextcloud/lib/private/Route/Router.php","line":298,"function":"main","class":"OC\\AppFramework\\App","type":"::"},{"file":"/var/www/nextcloud/lib/base.php","line":1023,"function":"match","class":"OC\\Route\\Router","type":"->"},{"file":"/var/www/nextcloud/index.php","line":36,"function":"handleRequest","class":"OC","type":"::"}],"File":"/var/www/nextcloud/apps/mail/lib/IMAP/MailboxSync.php","Line":148,"Previous":{"Exception":"Horde_Imap_Client_Exception","Message":"Mail server denied authentication.","Code":102,"Trace":[{"file":"/var/www/nextcloud/apps/mail/vendor/pear-pear.horde.org/Horde_Imap_Client/Horde/Imap/Client/Base.php","line":838,"function":"_login","class":"Horde_Imap_Client_Socket","type":"->","args":["*** sensitive parameters replaced ***"]},{"file":"/var/www/nextcloud/apps/mail/vendor/pear-pear.horde.org/Horde_Imap_Client/Horde/Imap/Client/Base.php","line":1598,"function":"login","class":"Horde_Imap_Client_Base","type":"->","args":["*** sensitive parameters replaced ***"]},{"file":"/var/www/nextcloud/apps/mail/lib/IMAP/FolderMapper.php","line":146,"function":"status","class":"Horde_Imap_Client_Base","type":"->"},{"file":"/var/www/nextcloud/apps/mail/lib/IMAP/MailboxSync.php","line":145,"function":"getFoldersStatusAsObject","class":"OCA\\Mail\\IMAP\\FolderMapper","type":"->"},{"file":"/var/www/nextcloud/apps/mail/lib/Service/Sync/SyncService.php","line":130,"function":"syncStats","class":"OCA\\Mail\\IMAP\\MailboxSync","type":"->"},{"file":"/var/www/nextcloud/apps/mail/lib/Controller/MailboxesController.php","line":161,"function":"syncMailbox","class":"OCA\\Mail\\Service\\Sync\\SyncService","type":"->"},{"file":"/var/www/nextcloud/lib/private/AppFramework/Http/Dispatcher.php","line":225,"function":"sync","class":"OCA\\Mail\\Controller\\MailboxesController","type":"->"},{"file":"/var/www/nextcloud/lib/private/AppFramework/Http/Dispatcher.php","line":133,"function":"executeController","class":"OC\\AppFramework\\Http\\Dispatcher","type":"->"},{"file":"/var/www/nextcloud/lib/private/AppFramework/App.php","line":172,"function":"dispatch","class":"OC\\AppFramework\\Http\\Dispatcher","type":"->"},{"file":"/var/www/nextcloud/lib/private/Route/Router.php","line":298,"function":"main","class":"OC\\AppFramework\\App","type":"::"},{"file":"/var/www/nextcloud/lib/base.php","line":1023,"function":"match","class":"OC\\Route\\Router","type":"->"},{"file":"/var/www/nextcloud/index.php","line":36,"function":"handleRequest","class":"OC","type":"::"}],"File":"/var/www/nextcloud/apps/mail/vendor/pear-pear.horde.org/Horde_Imap_Client/Horde/Imap/Client/Socket.php","Line":572},"CustomMessage":"Could not fetch stats of mailbox 6. IMAP error: Mail server denied authentication."},"id":"628f6eb7f0fbe"}

**Comment by ChristophWurst** [comment]
> Could not fetch stats of mailbox 6. IMAP error: Mail server denied authentication.

The IMAP server possibly rejected because of too many open connections. Was the app also open in the browser?

**Comment by jet438** [comment]
I don't think so. I gave up using the browser once I had Nextcloud
up...maybe my phone though.
