### ISSUE TITLE
Is there a way to connect to email provider by using their SSO athentication?

### ISSUE THREAD

**Issue by dd88w** [nextcloud/mail#6585]
### Is your feature request related to a problem? Please describe.

Hi developer:
I was trying to use mail app to connect to my gmail or mailgun, but I failed becouse the NC mail app only support smtp/pop3 or imap way, and which those ways I don't use anymore, and during the mail config setup there was no way to ignore the imap section, the app always check if the imap config is correct or not, and this makes me unable to add any customize mail address. Generally speaking ,using password itself makes it a risk in nowadays, and using email provider's OAuth would makes the setup process far more easier then using password.

### Describe the solution you'd like

so my feature request is :
1.support to use mail provider's SSO authentication to setup a mail account.
2.support to ignore imap config during the manual config process， and that would makes the NC mail app support more email providers like mailgun.

**Comment by dd88w** [comment]
And mostly , thanks for your great work on these app!

**Comment by ChristophWurst** [comment]
This request is possibly covered by https://github.com/nextcloud/mail/issues/3146.

**Comment by LasseRosenow** [comment]
What about a custom oauth server like keycloak?

**Comment by ChristophWurst** [comment]
Custom OAuth is not supported yet. This app can only work with Gmail and Microsoft Online OAuth.

Does this answer all your questions @dd88w?

**Comment by nextcloud-command** [comment]
Hi there! It looks like this issue hasn’t seen much activity for a while and might need a bit more information to move forward. If we don’t hear back soon, we may close it to keep things organized. Thanks again for your contributions – we really appreciate it!
