### ISSUE TITLE
Outbox saves no body message

### ISSUE THREAD

**Issue by JuliaKirschenheuter** [nextcloud/mail#6588]
### Steps to reproduce

**First scenario:** 

1. Click to new message
2. Write something in to, subject and body
3. Send the message
4. Make undo message
5. **Message body will not be shown to user. But is still in payload request.**
6. Make no changes, send the message again
7. Make undo message
8. **Message body will not be shown to user. Body in a payload request is empty.**

**Second scenario:** 
1. Open existing message in outbox
2. Make some changes in body
3. Wait until message will be saved
4. **Message body will not be shown to user. But is still in payload request.**
5. Click outside
6. Open the same message in outbox
7. **Message body will not be shown to user. Body in a payload request is empty.**

### Expected behavior

Message body is saved

### Actual behavior

Message body is not saved

### Mail app version

v1.13.0

### Mailserver or service

not relevant 

### Operating system

not relevant

**Comment by ChristophWurst** [comment]
> ### Mail app version
> 
> 1.12.1

Is that so? I can _not_ reproduce it with 1.12.1, only with today's `main`.

**Comment by ChristophWurst** [comment]
https://github.com/nextcloud/mail/pull/6565 one of the latest editor changes

**Comment by ChristophWurst** [comment]
I'm bisecting.

**Comment by ChristophWurst** [comment]
3d77d9bf74e3056f9820e5fa357f8f46f247462c is the bad one.

**Comment by ChristophWurst** [comment]
It was important to run `npm ci && npm run watch` with each step because the regression is not coming from our code change but a dependency. Going back a few days without `npm ci` did _not_ show the bug.
