### ISSUE TITLE
Mail Envelope Icon remains after drag and drop to folder. Ends up in wrong subfolder

### ISSUE THREAD

**Issue by dugite-code** [nextcloud/mail#659]
### Steps to reproduce
1. Drag email from mail-message-list to expanded folder list with subfolders
2. release

### Expected behaviour
Mail is moved to correct folder and envelope icon disappears

### Actual behaviour
Mail is moved to wrong folder and envelope icon remains floating

![image](https://user-images.githubusercontent.com/12742064/33754797-f8d8e8fc-dc28-11e7-8aa4-394bac4b49ac.png)

This appears to be a bug with the collapsed subfolders, as the emails end up in the folder that would have been in the drop area when expanded. For example below the email dragged to `Receipts` ends up in `Documentation.Government`

| Colapsed | Expanded |
|----  |----  |
| ![image](https://user-images.githubusercontent.com/12742064/33756123-f35bf846-dc2e-11e7-912b-84973fb4be86.png) | ![image](https://user-images.githubusercontent.com/12742064/33756136-04031a76-dc2f-11e7-9b0b-e8c25af6e3c4.png) |

Expanding all the subfolders fixes this issue.

### Mail app

**Mail app version:**  0.7.5

**Mailserver or service:** Modoboa (Postfix, Dovecote PostgreSQL)

**Transport security - IMAP:** None - Using IMAPProxy on localhost

**Transport security - SMTP:** STARTTLS

**Number of accounts:** 1

### Server configuration
<details>

**Operating system**: Debian 9

**Web server:** Nginx

**Database:** MariaDB

**PHP version:** PHP 7.0

**Version:** 12.0.3

**Updated from an older version or fresh install:** fresh install
</details>

**List of activated apps:**

<details>

| Enabled: | Disabled: |
|-----------|-----------|
|  - activity: 2.5.2 |   - admin_audit |
|  - apporder: 0.4.0 |  - user_ldap |
|  - bookmarks: 0.10.1 | |
|  - bruteforcesettings: 1.0.2 | |
|  - calendar: 1.5.6 | |
|  - checksum: 0.3.5 | |
|  - comments: 1.2.0 | |
|  - contacts: 2.0.1 | |
|  - dav: 1.3.0 | |
|  - deck: 0.2.8 | |
|  - encryption: 1.6.0 | |
|  - federatedfilesharing: 1.2.0 | |
|  - federation: 1.2.0 | |
|  - files: 1.7.2 | |
|  - files_clipboard: 0.6.4 | |
|  - files_external: 1.3.0 | |
|  - files_markdown: 2.0.1 | |
|  - files_pdfviewer: 1.1.1 | |
|  - files_sharing: 1.4.0 | |
|  - files_texteditor: 2.4.1 | |
|  - files_trashbin: 1.2.0 | |
|  - files_versions: 1.5.0 | |
|  - files_videoplayer: 1.1.0 | |
|  - firstrunwizard: 2.1 | |
|  - gallery: 17.0.0 | |
|  - groupfolders: 1.1.0 | |
|  - keeweb: 0.4.0 | |
|  - logreader: 2.0.0 | |
|  - lookup_server_connector: 1.0.0 | |
|  - mail: 0.7.5 | |
|  - metadata: 0.6.0 | |
|  - news: 11.0.5 | |
|  - nextcloud_announcements: 1.1 | |
|  - notifications: 2.0.0 | |
|  - oauth2: 1.0.5 | |
|  - passman: 2.1.4 | |
|  - password_policy: 1.2.2 | |
|  - previewgenerator: 1.0.7 | |
|  - provisioning_api: 1.2.0 | |
|  - quota_warning: 1.1.1 | |
|  - sensorlogger: 0.0.5 | |
|  - serverinfo: 1.2.0 | |
|  - sharebymail: 1.2.0 | |
|  - socialsharing_email: 1.0.1 | |
|  - survey_client: 1.0.0 | |
|  - systemtags: 1.2.0 | |
|  - tasks: 0.9.5 | |
|  - theming: 1.3.0 | |
|  - theming_customcss: 1.0.0 | |
|  - twofactor_backupcodes: 1.1.1 | |
|  - twofactor_totp: 1.3.1 | |
|  - updatenotification: 1.2.0 | |
|  - user_external: 0.4 | |
|  - workflowengine: 1.2.0| | |

</details>

**The content of config/config.php:**

<details>

```
<?php
$CONFIG = array (
  'loglevel' => '3',
  'instanceid' => '*******************************',
  'passwordsalt' => '*******************************',
  'secret' => '*******************************',
  'trusted_domains' =>
  array (
    0 => 'example.tld',
  ),
  'datadirectory' => '/var/www/nextcloud/data',
  'overwrite.cli.url' => 'https://example.tld',
  'dbtype' => 'mysql',
  'version' => '12.0.3.3',
  'dbname' => 'nextcloud',
  'dbhost' => '127.0.0.1',
  'dbport' => '',
  'dbtableprefix' => 'oc_',
  'dbuser' => 'nextcloud',
  'dbpassword' => '*******************************',
  'installed' => true,
  'memcache.local' => '\\OC\\Memcache\\APCu',
  'memcache.locking' => '\\OC\\Memcache\\Redis',
  'filelocking.enabled' => 'true',
  'redis' =>
  array (
    'host' => '/var/run/redis/redis.sock',
    'port' => 0,
    'timeout' => 0.0,
  ),
  'user_backends' =>
  array (
    0 =>
    array (
      'class' => 'OC_User_IMAP',
      'arguments' =>
      array (
        0 => '{mail.example.tld:993/ssl/imap/readonly}',
        1 => 'example.tld',
      ),
    ),
  ),
  'defaultapp' => 'mail',
  'app.mail.imap.timeout' => 30,
  'app.mail.smtp.timeout' => 15,
  'mail_smtptimeout' => 30,
  'mail_smtpmode' => 'smtp',
  'mail_smtpauthtype' => 'PLAIN',
  'mail_from_address' => 'server',
  'mail_domain' => 'example.tld',
  'mail_smtpauth' => 1,
  'mail_smtpname' => 'postmaster@example.tld',
  'mail_smtppassword' => '*******************************',
  'mail_smtphost' => 'mail.example.tld',
  'mail_smtpport' => '587',
  'mail_smtpsecure' => 'tls',
  'mysql.utf8mb4' => true,
  'auth.bruteforce.protection.enabled' => true,
  'maintenance' => false,
  'theme' => '',
);
```
</details>

#### Client configuration
**Browser:** Firefox

**Operating system:** Windows 10

##### Browser log

<details>

```
TypeError: t is undefined[Learn More] build.js:43:17864
	addMessage https://example.tld/apps/mail/js/build/build.js:43:17864
	a https://example.tld/apps/mail/js/build/build.js:20:10779
	y https://example.tld/apps/mail/js/build/build.js:12:54246
	v https://example.tld/apps/mail/js/build/build.js:12:53874
	d https://example.tld/apps/mail/js/build/build.js:12:51826
	c.trigger https://example.tld/apps/mail/js/build/build.js:12:53767
	onRender/<.drop< https://example.tld/apps/mail/js/build/build.js:75:12003
	<anonymous> self-hosted:954:17
	_trigger https://example.tld/core/vendor/core.js:13:10073
	_drop https://example.tld/core/vendor/core.js:13:40404
	e.widget/</a[t]</< https://example.tld/core/vendor/core.js:13:5075
	drop/< https://example.tld/core/vendor/core.js:13:42309
	each https://example.tld/core/vendor/core.js:2:2880
	drop https://example.tld/core/vendor/core.js:13:42132
	_mouseStop https://example.tld/apps/mail/js/build/build.js:51:3644
	t.widget/</a[e]</< https://example.tld/apps/mail/js/build/build.js:20:1103
	_mouseUp https://example.tld/apps/mail/js/build/build.js:59:2734
	t.widget/</a[e]</< https://example.tld/apps/mail/js/build/build.js:20:1103
	_mouseUp https://example.tld/apps/mail/js/build/build.js:51:4239
	t.widget/</a[e]</< https://example.tld/apps/mail/js/build/build.js:20:1103
	_mouseDown/this._mouseUpDelegate https://example.tld/apps/mail/js/build/build.js:59:1634
	dispatch https://example.tld/core/vendor/core.js:3:6414
	add/r.handle https://example.tld/core/vendor/core.js:3:3224
```
</details>

**Comment by dugite-code** [comment]
Any additional details required to debug this? I'm still encountering this issue

**Comment by ChristophWurst** [comment]
Feel free to dig into the code. I think it's an issue with jquery-ui's draggable/droppable. IIRC there is a config option to have the icon return to its original position or similar.

**Comment by dugite-code** [comment]
@ChristophWurst I had a look into the code but it looks like the jquery-ui's config is correct? I couldn't figure out the problem myself. The icon will go back to it's original position as expected but only if there are no collapsed folders "underneath" the target folder.

**Comment by ashgoodman** [comment]
It happens to me even if there are no other collapsed folders under the target folder but if the target folder is in the expanded view of a parent folder

**Comment by st3iny** [comment]
See #4048 for the new drag and drop feature.
