### ISSUE TITLE
Loading icon and text are too close

### ISSUE THREAD

**Issue by ChristophWurst** [nextcloud/mail#6616]
### Steps to reproduce

1. Configure an account
2. Open the app another time

### Expected behavior

:sunglasses: 

### Actual behavior

![Bildschirmfoto vom 2022-05-31 19-46-22](https://user-images.githubusercontent.com/1374172/171251787-550e7fc1-0a22-4d0c-9658-37a24b31b594.png)

While messages are indexed/fetched.

![Bildschirmfoto vom 2022-06-01 10-08-36](https://user-images.githubusercontent.com/1374172/171358125-6813f820-93aa-4d3a-ba3f-cc8afae3ceb1.png)

When I send a message.

### Mail app version

v1.13

**Comment by Sam-Takahashi** [comment]
I can look into this.

**Comment by ChristophWurst** [comment]
Awesome! Let me know if you need any guidance.

**Comment by Sam-Takahashi** [comment]
I've gotten a little busy with other projects, but I will definitely look into this. please be patient.

**Comment by ChristophWurst** [comment]
Sure sure, take your time :)

**Comment by GretaD** [comment]
i have replaced all the loading icons in this pr with material design icons: https://github.com/nextcloud/mail/pull/6995 and the the loading icon now looks like this:
![loadingsending](https://user-images.githubusercontent.com/12728974/186898168-96a503a3-eafd-489c-946e-2b1c14efc055.png)

**Comment by Sam-Takahashi** [comment]
Is this concluded then? or is the icon still too close?

**Comment by PeterJGDe** [comment]
I can't reproduce it anymore. It seems to be fixed.
