### ISSUE TITLE
Replies and forwards not quoted anymore

### ISSUE THREAD

**Issue by ChristophWurst** [nextcloud/mail#6622]
### Steps to reproduce

1. Open a message
2. Reply/forward

### Expected behavior

The original body is quoted

### Actual behavior

The original body is not quoted

### Mail app version

1.14

### Additional info

I can _not_ trigger this with v1.13.0 RC1

**Comment by ChristophWurst** [comment]
@GretaD could you have a look please as you also debugged https://github.com/nextcloud/mail/issues/6564?

**Comment by GretaD** [comment]
I cannot reproduce it on latest anymore. Any special condition on your local env?

**Comment by ChristophWurst** [comment]
I can trigger it for replies on plain text and HTML message, with plain or HTML editing mode as default.

**Comment by ChristophWurst** [comment]
I can reproduce with HTML and plain text emails on v1.13.0

**Comment by ChristophWurst** [comment]
So this must have been introduced somewhere between RC1 and .0. Ref https://github.com/nextcloud/mail/commits/stable1.13

**Comment by ChristophWurst** [comment]
Replying to an email with formatting also drops the formatting.

**Comment by kenpyfin** [comment]
Any follow-up on this issue. We have to stop using the mail app because of this issue. It's major enough that it makes the mail app not usable.

**Comment by ChristophWurst** [comment]
Fix is at https://github.com/nextcloud/mail/pull/6663.

**Comment by kenpyfin** [comment]
Thank you for the quick fix!! Appreciate everyone's effort.
