### ISSUE TITLE
Yellow star on white background is hard to see

### ISSUE THREAD

**Issue by ChristophWurst** [nextcloud/mail#6626]
### Steps to reproduce

1. Configure an account
2. Star a message
3. Open the message action menu

### Expected behavior

Visually easy to process UI.

### Actual behavior

![Bildschirmfoto vom 2022-06-01 15-50-31](https://user-images.githubusercontent.com/1374172/171420947-a8652e64-d64a-486a-8416-60475cd2dd3d.png)

Maybe I have a bug with my eyes and yellow/white is trickier for me than other people, but this doesn't look good. A black, filled star would be much easier to recognize.

### Mail app version

v1.12

### Additional info

cc @nimishavijay @jancborchardt 

cc @JuliaKirschenheuter because this potentially touches on accessibility as well

**Comment by jancborchardt** [comment]
Yep, totally agree. Let's instead use:
- unfavorited: star outline/border https://fonts.google.com/icons?selected=Material%20Icons%3Astar_border%3A
- favorited: filled star https://fonts.google.com/icons?selected=Material%20Icons%3Astar%3A

This will fix it by distinguishing it via form instead, and get rid of a color which is difficult to see.

Is it possible to do this as a component or so, that it's also fixed in other apps like Files and Talk? cc @skjnldsv @marcoambrosini

**Comment by marcoambrosini** [comment]
I think this will require separate fixes I think

**Comment by JuliaKirschenheuter** [comment]
> This will fix it by distinguishing it via form instead, and get rid of a color which is difficult to see.

you mean if we use unfavorited / favorited and completely remove a color? 

> cc @JuliaKirschenheuter because this potentially touches on accessibility as well

yes, especially if there is some other background (not white), it could be problematically

**Comment by jancborchardt** [comment]
> you mean if we use unfavorited / favorited and completely remove a color?

Yes – or we move towards a more orange color for the star which would make it a bit darker. We could see if our existing color-warning works better?

But even then we should use the outline/border version of the icon for "unfavorited", so we don't only distinguish by color.

**Comment by JuliaKirschenheuter** [comment]
> But even then we should use the outline/border version of the icon for "unfavorited", so we don't only distinguish by color.

Do we have this issue? Should i create one?

**Comment by ChristophWurst** [comment]
That is the case already. We use fille/outline for the distinction.
