### ISSUE TITLE
Pasting image in editor

### ISSUE THREAD

**Issue by J-C-P** [nextcloud/mail#6629]
### Is your feature request related to a problem? Please describe.

Hello,

I'm sure this has been discussed before (but I can't find the topic) but this is THE ONLY REASON why I don't use the mail app in NextCloud.
I have no development skills at all, my question is first degree, without any trace of sarcasm. 
Is it so difficult to implement ? I'm obviously missing something here. Can I help in any way ?

### Describe the solution you'd like

Being able to past an image from the clipboard to the editor (a print screen, for instance).

### Describe alternatives you've considered

Using another mail client :-/

### Additional context

I know that, if it is so easy, it would have been done already.
Thanks to the dev team ! Having no dev skills, I'm always impressed by those impressive peace of software :-)

**Comment by ChristophWurst** [comment]
Dup of https://github.com/nextcloud/mail/issues/2733

**Comment by ChristophWurst** [comment]
We will work on this soon. It is indeed a lot harder than it seems.

**Comment by J-C-P** [comment]
Thanks for your feedback :-)

Have a great day !
