### ISSUE TITLE
After the new update, 'Reply' acts funny as it won't quote the email body but direct edit it

### ISSUE THREAD

**Issue by kenpyfin** [nextcloud/mail#6636]
### Steps to reproduce

Just hit the reply button from an email.

### Expected behavior

There's should be a quote line.

### Actual behavior

Direct edit the email body being replied.

**Comment by ChristophWurst** [comment]
Dup of https://github.com/nextcloud/mail/issues/6622?

**Comment by Chartman123** [comment]
> Dup of #6622?

Probably, yes :)
