### ISSUE TITLE
Create a task from a mail

### ISSUE THREAD

**Issue by snyssen** [nextcloud/mail#6678]
### Is your feature request related to a problem? Please describe.

I love that we already have the ability to create an event from an e-mail, but what would be even more useful to me would be to be able to create tasks with an optional due date from an e-mail. I often create myself a todo list to manage incoming e-mails, so this feature could speed up that work.

### Describe the solution you'd like

The flow could be almost identical to creating events:

1. Click on the 3 dots menu on a specified e-mail and go into the "More actions" sub-menu. There you would find a new button below "Create event" such as "Create task"
![image](https://user-images.githubusercontent.com/36501744/172541295-5869f520-49a4-44ca-b60d-48f3e3d8f8f1.png)

2.  Click on "Create task". This would open a modal similar to the "Create event" one, with some or all of the following options:
    - Name (defaults to e-mail title)
    - Start date (defaults to now)
    - Due date (defaults to now + 1 hour for example)
    - "All day" checkbox (similar to events, turns the two previous datetime selections into date only selections)
    - Calendar selection (to which calendar should the task be attached)
    - Priority ?
    - Status ?
    - Tags ?
    - Notes (defaults to e-mail body)
Here is the "Create event" modal as a reference:
![image](https://user-images.githubusercontent.com/36501744/172542515-fe38c87f-c90c-4c05-b7da-3ab5d685dc27.png)

**Comment by ChristophWurst** [comment]
Dup of https://github.com/nextcloud/mail/issues/6127

Thanks for the thorough report. I've copied your details into the other request :)
