### ISSUE TITLE
Readme says »Dependencies out of date«

### ISSUE THREAD

**Issue by jancborchardt** [nextcloud/mail#67]
![capture du 2016-09-15 13-14-38](https://cloud.githubusercontent.com/assets/925062/18547948/66c00110-7b46-11e6-8ddd-a12eadd6ddb6.png)
Why are there two of them and how can we fix it?

**Comment by ChristophWurst** [comment]
not our projekt that is shown, should be removed https://github.com/nextcloud/mail/pull/63

**Comment by jancborchardt** [comment]
Aah ok, thx!
