### ISSUE TITLE
Oftentimes when clicking a message, the drag&drop mail icon shows

### ISSUE THREAD

**Issue by jancborchardt** [nextcloud/mail#670]
When you are not 100% still in your click, but move the mouse a little (perfectly normal when you go through a list) this happens:
![peek 2017-12-12 11-59](https://user-images.githubusercontent.com/925062/33881248-7efc72c4-df34-11e7-9896-6d0ef18edc66.gif)

I guess that could be fixed by upping a threshold which is used for initiating the drag&drop?

**Comment by awetails** [comment]
If no is working on this, I would like to dip my toe in the water and take it as my first issue.

**Comment by ChristophWurst** [comment]
Hey @awetails,

great to hear you'd be interested in working on this. Do you need any pointers to get started? Are you familiar with Nextcloud development?

**Comment by ChristophWurst** [comment]
> yes I would love that. I've never contributed to any such project so I am a little lost (and my work uses SVN so not that familiar with Git either).

No worries. You'll get into that. GitHub and other pages have very good guides on how to get started. I'd suggest to just art with cloning the repository and then look up whatever you want to do with git :)

> (I am a software developer so no help needed there,
> and I have read (or more of perused) the ownCloud (before transferring to nextcloud) developer documentation so I am not all lost on the technicalities)

Perfect. At this point the development setup/tools are quite similar.

**Comment by ChristophWurst** [comment]
Btw, @awetails, you're very welcome to also join us at our [conference](https://eventyay.com/e/77d26f89/) :raised_hands:

**Comment by awetails** [comment]
Just to leave additional information in a proper place.
According to jQuery UI docs:

https://jqueryui.com/upgrade-guide/1.12/#deprecated-distance-and-delay-options

> 
> Deprecated  distance and delay options
> (#10615) Interactions should be instantaneous. These settings are typically used to prevent accidental drags, but a proper fix for that is to improve the user experience, e.g., using handles to avoid accidental drags.
> 

Options which would be typically used for the fix. The possible solutions seem to be:

- ignore it and use them anyway
The docs state that the functionality won't be removed until a rewrite is available, therefore this fix can still be used

- implement code around the jQuery UI components, that would provide the appropriate functionality

- redesign the message item to include said handles and bypass the problem of accidental drag&drop

**Comment by awetails** [comment]
I am but a simple outsider here, but I would venture to guess that should standardization be concerned @skjnldsv would be the ideal developer to consult. :)

**Comment by skjnldsv** [comment]
Yes, but we're all here to discuss anyway ;)
When you talk about handles, you mean like adding a specific spot to only enable the drag-dro pfrom? Like the 6 grey dots when sorting items? (like so)

- [ ] test
- [ ] test2
- [ ] test2

**Comment by awetails** [comment]
Typical solution would look like
![revert_false](https://user-images.githubusercontent.com/16638967/43898091-7cd35fc8-9bde-11e8-82d6-4c2bc7032cb7.gif)

**Comment by jancborchardt** [comment]
Doesn’t happen anymore → closing.
