### ISSUE TITLE
FR: Mark multiple Mails and apply action on them

### ISSUE THREAD

**Issue by PhilipMay** [nextcloud/mail#6704]
### Is your feature request related to a problem? Please describe.

If I have multiple mails and want to delete them (for example) -> I have delete them mail by mail.

### Describe the solution you'd like

I want to be able to mark multiple mails in an Folder (Inbox or what ever folder).
When they are marked I want to apply actions on all of them.
These actions are: 

1. Move to Archive
2. Move to other folder
3. delete
4. mark as read / mark as unread
6. mark as important / mark as notimportant
7. add tag / remove tag

**Comment by ChristophWurst** [comment]
![Bildschirmfoto vom 2022-06-09 13-56-53](https://user-images.githubusercontent.com/1374172/172841243-3102a1ff-f90b-4b27-b54c-bf7c787056bd.png)

we have multi select

**Comment by PhilipMay** [comment]
>we have multi select

Is it already released? I do not have those checkboxes in version 1.13.3...
