### ISSUE TITLE
FR: Search (filter) messages and apply action on them

### ISSUE THREAD

**Issue by PhilipMay** [nextcloud/mail#6706]
### Is your feature request related to a problem? Please describe.

Currently if I do a search in my mails I can only select one of the mails.
But I want to select multiple of them. This is connected to #6704.

### Describe the solution you'd like

I want to filter and search messages.
All messages from someone or all messages with something in the topic.
Then I want to use #6704 and apply a "mass action" on all of them.
That would also imply a "mark all" button.

**Comment by ChristophWurst** [comment]
https://github.com/nextcloud/mail/issues/6704 exists so this is now possible
