### ISSUE TITLE
FR: Change "starting folder"

### ISSUE THREAD

**Issue by PhilipMay** [nextcloud/mail#6707]
### Is your feature request related to a problem? Please describe.

If I click the "mail icon" in Nextcloud the mail app opens the "priority inbox".
But I do not like the "priority inbox". I prefer just the normal "inbox".

### Describe the solution you'd like

I want to change the default folder that is opened when I click the nextcloud mail icon so that the "Inbox" is opened and not the "priority inbox".

**Comment by ChristophWurst** [comment]
Dup of https://github.com/nextcloud/mail/issues/1665
