### ISSUE TITLE
Account settings modal window doesn't have a first focus in itself

### ISSUE THREAD

**Issue by JuliaKirschenheuter** [nextcloud/mail#6716]
### Steps to reproduce

Accessibility issue.

1. Connect an email account
2. Click to (...) button
3. Click to "Account settings"
4. Modal window will be opened

### Expected behavior

Focus goes to the first control element inside of modal window (or first navbar element in a modal sidebar) **needs to be clarified**

### Actual behavior

Tab navigation goes through the left navigation below the email account and will never do inside of the modal window.

### Mail app version

1.13

**Comment by GretaD** [comment]
if i understood this issue right, now the focus is inside the settings modal and if i click tab again it will move on the next element inside the modal.

![Screenshot from 2022-09-23 14-33-49](https://user-images.githubusercontent.com/12728974/191961187-ea5aff5f-b4c5-4fd6-ac35-c0161ac36eed.png)

**Comment by GretaD** [comment]
> if i understood this issue right, now the focus is inside the settings modal and if i click tab again it will move on the next element inside the modal. So i am assuming this is fixed. @JuliaKirschenheuter please check if i got it right and close the ticket, or hide my comment if this is not what you want to be fixed here.
> 
> ![Screenshot from 2022-09-23 14-33-49](https://user-images.githubusercontent.com/12728974/191961187-ea5aff5f-b4c5-4fd6-ac35-c0161ac36eed.png)

**Comment by ChristophWurst** [comment]
Can't reproduce either.
