### ISSUE TITLE
Add attachment from files is missing a add/done/close button

### ISSUE THREAD

**Issue by MG2R** [nextcloud/mail#674]
### Steps to reproduce
1. Start writing mail
2. Click "Add attachments from files"

### Expected behaviour
I should be able to select some attachments to add and press a button to do so.

### Actual behaviour
There is no button, the modal which pops up is there to stay forever -- or until I reload.
Issue has been there for as long as I can remember.

### Mail app

**Mail app version:** 0.7.6

**Mailserver or service:** Postfix + Dovecot

**Transport security - IMAP:** STARTTLS

**Transport security - SMTP:** STARTTLS

**Number of accounts:** 2

**Mail app version build date:** N/A (stable)

## Server configuration detail

**Operating system:** Linux 4.13.3-1-ARCH #1 SMP PREEMPT Thu Sep 21 20:33:16 CEST 2017 x86_64

**Webserver:** Apache (fpm-fcgi)

**Database:** mysql 10.1.24

**PHP version:** 7.1.10
Modules loaded: Core, date, libxml, openssl, pcre, zlib, ctype, dom, fileinfo, filter, hash, json, mbstring, pcntl, SPL, PDO, bz2, posix, readline, Reflection, session, SimpleXML, standard, tokenizer, xml, xmlreader, xmlwriter, mysqlnd, cgi-fcgi, curl, zip, apcu, Phar, exif, gd, iconv, imap, mcrypt, mysqli, pdo_mysql, redis, Zend OPcache

**Nextcloud version:** 12.0.4 - 12.0.4.3

**Updated from an older Nextcloud/ownCloud or fresh install:** updated from 12.0.4

**Where did you install Nextcloud from:** unknown

<details><summary>Signing status</summary>

Array
</details>

<details><summary>List of activated apps</summary>

```
Enabled:
 - activity: 2.5.2
 - apporder: 0.4.1
 - audioplayer: 2.2.1
 - bruteforcesettings: 1.0.2
 - calendar: 1.5.7
 - cms_pico: 0.9.6
 - comments: 1.2.0
 - contacts: 2.0.1
 - dav: 1.3.0
 - federatedfilesharing: 1.2.0
 - federation: 1.2.0
 - files: 1.7.2
 - files_clipboard: 0.6.4
 - files_markdown: 2.0.1
 - files_pdfviewer: 1.1.1
 - files_reader: 1.0.4
 - files_sharing: 1.4.0
 - files_texteditor: 2.4.1
 - files_trashbin: 1.2.0
 - files_versions: 1.5.0
 - files_videoplayer: 1.1.0
 - firstrunwizard: 2.1
 - gallery: 17.0.0
 - gpxedit: 0.0.7
 - issuetemplate: 0.3.0
 - keeweb: 0.4.0
 - logreader: 2.0.0
 - lookup_server_connector: 1.0.0
 - mail: 0.7.6
 - news: 11.0.5
 - nextcloud_announcements: 1.1
 - notifications: 2.0.0
 - oauth2: 1.0.5
 - passman: 2.1.4
 - password_policy: 1.2.2
 - previewgenerator: 1.0.7
 - provisioning_api: 1.2.0
 - quota_warning: 1.1.1
 - ransomware_protection: 1.0.5
 - richdocuments: 1.12.39
 - serverinfo: 1.2.0
 - sharebymail: 1.2.0
 - systemtags: 1.2.0
 - tasks: 0.9.5
 - theming: 1.3.0
 - twofactor_backupcodes: 1.1.1
 - twofactor_totp: 1.3.1
 - updatenotification: 1.2.0
 - workflowengine: 1.2.0
Disabled:
 - admin_audit
 - encryption
 - files_external
 - spreed
 - survey_client
 - twofactor_u2f
 - user_external
 - user_ldap

```
</details>

<details><summary>Configuration (config/config.php)</summary>

```
{
    "instanceid": "ocori1ilcw8b",
    "passwordsalt": "***REMOVED SENSITIVE VALUE***",
    "secret": "***REMOVED SENSITIVE VALUE***",
    "trusted_domains": [
        "<MYDOMAIN>",
        "www.<MYDOMAIN>"
    ],
    "datadirectory": "\/srv\/nextcloud",
    "overwrite.cli.url": "https:\/\/<MYDOMAIN>",
    "dbtype": "mysql",
    "version": "12.0.4.3",
    "dbname": "<DBNAME>",
    "dbhost": "<MYDB>",
    "dbport": "",
    "dbtableprefix": "oc_",
    "dbuser": "***REMOVED SENSITIVE VALUE***",
    "dbpassword": "***REMOVED SENSITIVE VALUE***",
    "logtimezone": "UTC",
    "installed": true,
    "mail_smtpmode": "smtp",
    "mail_from_address": "nextcloud",
    "mail_domain": "<SERVERFQDN>",
    "mail_smtphost": "localhost",
    "mail_smtpport": "25",
    "maintenance": false,
    "theme": "",
    "loglevel": 0,
    "memcache.locking": "\\OC\\Memcache\\Redis",
    "memcache.local": "\\OC\\Memcache\\APCu",
    "redis": {
        "host": "localhost",
        "port": 6379
    },
    "mysql.utf8mb4": true,
    "updater.secret": "***REMOVED SENSITIVE VALUE***"
}
```
</details>

**Are you using external storage, if yes which one:** l no

**Are you using encryption:** no

**Are you using an external user-backend, if yes which one:** no

## Client configuration

**Browser:** Mozilla/5.0 (X11; Linux x86_64; rv:57.0) Gecko/20100101 Firefox/57.0

**Browser:** Chromium 63

**Operating system:** Arch Linux

##### Web server error log
No Apache/PHP errors during reproduction of issue.

##### Server log (data/nextcloud.log)
<details>
```
{"reqId":"f0t8ldnG3cvr20eHxFwR","level":0,"time":"2017-12-13T13:19:52+00:00","remoteAddr":"<MYIP>","user":"<ME>","app":"mail","method":"GET","url":"\/index.php\/apps\/mail\/","message":"no default config found","userAgent":"Mozilla\/5.0 (X11; Linux x86_64; rv:57.0) Gecko\/20100101 Firefox\/57.0","version":"12.0.4.3"}
{"reqId":"72BygkHUT1bizHdBpMPV","level":0,"time":"2017-12-13T13:19:55+00:00","remoteAddr":"<MYIP>","user":"<ME>","app":"mail","method":"GET","url":"\/index.php\/apps\/mail\/api\/accounts\/3\/folders\/SU5CT1g%3D\/messages?filter=","message":"loading messages of folder <SU5CT1g=>","userAgent":"Mozilla\/5.0 (X11; Linux x86_64; rv:57.0) Gecko\/20100101 Firefox\/57.0","version":"12.0.4.3"}
{"reqId":"Hhoo2hPEL1r3VVIPQ5wF","level":0,"time":"2017-12-13T13:19:55+00:00","remoteAddr":"<MYIP>","user":"<ME>","app":"mail","method":"GET","url":"\/index.php\/apps\/mail\/api\/accounts\/4\/folders\/SU5CT1g%3D\/messages?filter=","message":"loading messages of folder <SU5CT1g=>","userAgent":"Mozilla\/5.0 (X11; Linux x86_64; rv:57.0) Gecko\/20100101 Firefox\/57.0","version":"12.0.4.3"}
```
</details>

##### Browser log
<details>
```
Starting Mail … -> build.js:20:35993
initializing cache… -> build.js:12:74177
TypeError: this._setOptionDisabled is not a function -> build.js:20:4462
```
</details>

**Comment by ChristophWurst** [comment]
Dup of https://github.com/nextcloud/mail/issues/626

**Comment by MG2R** [comment]
Whoops, did not find that previous issue, sorry.

**Comment by ChristophWurst** [comment]
No worries 😉
