### ISSUE TITLE
Edit as new message -> Body is missing

### ISSUE THREAD

**Issue by kesselb** [nextcloud/mail#6742]
### Steps to reproduce

1. Open Sent folder
2. Pick a message and click edit as new message

### Expected behavior

Body of original message is there

### Actual behavior

Body is not there

### Mail app version

main

**Comment by ChristophWurst** [comment]
Wait this is expected, right? Why should the message be quoted? It's not a reply

**Comment by kesselb** [comment]
Thunderbird and Roundcube keep the original message body ;)

**Comment by kesselb** [comment]
I updated the issue description. "quoted" was the wrong wording. The body is missing.

**Comment by LostinSpacetime** [comment]
Maybe this is related to #6780

**Comment by ChristophWurst** [comment]
I can not reproduce. *Edit as new* does load the editor with the original message's body.
