### ISSUE TITLE
Editor mode depends on first account but not sender email address

### ISSUE THREAD

**Issue by kesselb** [nextcloud/mail#6745]
### Steps to reproduce

1. Have two email accounts
2. Set the first one to plain text
3. Set the second one to rich text 
4. Compose a new message
5. Switch to email address from second account
6. Try to use the rich text toolbar 

### Expected behavior

I have the rich text toolbar

### Actual behavior

I don't have the rich text toolbar

### Mail app version

main

### Additional info

https://user-images.githubusercontent.com/3902676/173589561-9b012af8-1bd8-4656-8c60-eb66c6b8cbeb.mp4

**Comment by miaulalala** [comment]
:(

**Comment by st3iny** [comment]
Could this be related to my recent "fix" at #6375?

**Comment by ChristophWurst** [comment]
> Could this be related to my recent "fix" at #6375?

@kesselb mind retesting? :pray:

**Comment by GretaD** [comment]
I tested it and the issue is fixed ✌
