### ISSUE TITLE
Error sending your message AxiosError: Request failed with status code 500

### ISSUE THREAD

**Issue by prismopensource** [nextcloud/mail#6759]
### Steps to reproduce

Can't reliably reproduce, problem started after the upgrade to version 1.13.4, bug wasn't present in earlier versions of mail. Users with Firefox are complaining the most about this bug, those same users don't experience the bug in Edge, Safari or Chrome.

### Expected behavior

After composing an email and clicking the Send button you'd expect the compose window to go away and in the top right an "Message sent" notification. 

### Actual behavior

After composing an email and clicking the Send button some users are getting this error message:

Error sending your message 
AxiosError: Request failed with status code 500

And the email is never actually send.

### Mail app version

1.13.4

### Mailserver or service

Exim

### Operating system

Debian

### PHP engine version

PHP 8.0

### Web server

Apache (supported)

### Database

MariaDB

### Additional info

[mail] Error: Exception: OCA\Mail\Controller\OutboxController::create(): Argument #4 ($editorBody) must be of type string, null given, called in /home/username/domains/domain.com/cloud_public_html/lib/private/AppFramework/Http/Dispatcher.php on line 225 in file '/home/username/domains/domain.com/cloud_public_html/apps/mail/lib/Controller/OutboxController.php' line 101 at <<closure>>

0. /home/username/domains/domain.com/cloud_public_html/lib/private/AppFramework/App.php line 172
   OC\AppFramework\Http\Dispatcher->dispatch()
1. /home/username/domains/domain.com/cloud_public_html/lib/private/Route/Router.php line 298
   OC\AppFramework\App::main()
2. /home/username/domains/domain.com/cloud_public_html/lib/base.php line 1023
   OC\Route\Router->match()
3. /home/username/domains/domain.com/cloud_public_html/index.php line 36
   OC::handleRequest()

POST /index.php/apps/mail/api/outbox
from 105.186.193.134 by gbakker at 2022-06-17T09:28:21+00:00

Caused by TypeError: OCA\Mail\Controller\OutboxController::create(): Argument #4 ($editorBody) must be of type string, null given, called in /home/username/domains/domain.com/cloud_public_html/lib/private/AppFramework/Http/Dispatcher.php on line 225
1. /home/username/domains/domain.com/cloud_public_html/lib/private/AppFramework/Http/Dispatcher.php - line 225:  OCA\Mail\Controller\OutboxController->create()
2. /home/username/domains/domain.com/cloud_public_html/lib/private/AppFramework/Http/Dispatcher.php - line 133:  OC\AppFramework\Http\Dispatcher->executeController()
3. /home/username/domains/domain.com/cloud_public_html/lib/private/AppFramework/App.php - line 172:  OC\AppFramework\Http\Dispatcher->dispatch()
4. /home/username/domains/domain.com/cloud_public_html/lib/private/Route/Router.php - line 298:  OC\AppFramework\App::main()
5. /home/username/domains/domain.com/cloud_public_html/lib/base.php - line 1023:  OC\Route\Router->match()
6. /home/username/domains/domain.com/cloud_public_html/index.php - line 36:  OC::handleRequest()

**Comment by GretaD** [comment]
we're having a look, thanks for the report

**Comment by ChristophWurst** [comment]
I'm assuming this is no longer relevant
