### ISSUE TITLE
($from_encoding) contains invalid encoding "unicode-1-1-utf-7"

### ISSUE THREAD

**Issue by WarpinWolf** [nextcloud/mail#6796]
### Steps to reproduce

Nextcloud 24.0.2 - PHP Version: 8.0.20 - Debian 10.12

Getting error when trying to use mail.

Issue is same as described here - https://github.com/nextcloud/mail/issues/6405

Applied "fix" described above to apps/mail/vendor/bytestream/horde-util/lib/Horde/String.php

Now it is working - no error anymore.

Error in log is here:
{"reqId":"xHmQph0aX8g0StFVWPre","level":3,"time":"2022-06-26T13:30:07+00:00","remoteAddr":"","user":"--","app":"mail","method":"","url":"--","message":"Cron mail sync failed for account 4","userAgent":"--","version":"24.0.2.1","exception":{"Exception":"OCA\\Mail\\Exception\\ServiceException","Message":"Sync failed for 4:INBOX: mb_convert_encoding(): Argument #3 ($from_encoding) contains invalid encoding \"unicode-1-1-utf-7\"","Code":0,"Trace":[{"file":"/var/www/nextcloud.mydomain.org/apps/mail/lib/Service/Sync/ImapToDbSynchronizer.php","line":137,"function":"sync","class":"OCA\\Mail\\Service\\Sync\\ImapToDbSynchronizer","type":"->"},{"file":"/var/www/nextcloud.mydomain.org/apps/mail/lib/BackgroundJob/SyncJob.php","line":122,"function":"syncAccount","class":"OCA\\Mail\\Service\\Sync\\ImapToDbSynchronizer","type":"->"},{"file":"/var/www/nextcloud.mydomain.org/lib/public/BackgroundJob/Job.php","line":79,"function":"run","class":"OCA\\Mail\\BackgroundJob\\SyncJob","type":"->"},{"file":"/var/www/nextcloud.mydomain.org/lib/public/BackgroundJob/TimedJob.php","line":95,"function":"execute","class":"OCP\\BackgroundJob\\Job","type":"->"},{"file":"/var/www/nextcloud.mydomain.org/cron.php","line":151,"function":"execute","class":"OCP\\BackgroundJob\\TimedJob","type":"->"}],"File":"/var/www/nextcloud.mydomain.org/apps/mail/lib/Service/Sync/ImapToDbSynchronizer.php","Line":255,"Previous":{"Exception":"ValueError","Message":"mb_convert_encoding(): Argument #3 ($from_encoding) contains invalid encoding \"unicode-1-1-utf-7\"","Code":0,"Trace":[{"file":"/var/www/nextcloud.mydomain.org/apps/mail/vendor/bytestream/horde-util/lib/Horde/String.php","line":160,"function":"mb_convert_encoding"},{"file":"/var/www/nextcloud.mydomain.org/apps/mail/vendor/bytestream/horde-util/lib/Horde/String.php","line":96,"function":"_convertCharset","class":"Horde_String","type":"::"},{"file":"/var/www/nextcloud.mydomain.org/apps/mail/vendor/bytestream/horde-mime/lib/Horde/Mime.php","line":259,"function":"convertCharset","class":"Horde_String","type":"::"},{"file":"/var/www/nextcloud.mydomain.org/apps/mail/vendor/bytestream/horde-mime/lib/Horde/Mime/Headers/Element/Single.php","line":62,"function":"decode","class":"Horde_Mime","type":"::"},{"file":"/var/www/nextcloud.mydomain.org/apps/mail/vendor/bytestream/horde-mime/lib/Horde/Mime/Headers/Element.php","line":79,"function":"_setValue","class":"Horde_Mime_Headers_Element_Single","type":"->"},{"file":"/var/www/nextcloud.mydomain.org/apps/mail/vendor/bytestream/horde-mime/lib/Horde/Mime/Headers/Element.php","line":56,"function":"setValue","class":"Horde_Mime_Headers_Element","type":"->"},{"file":"/var/www/nextcloud.mydomain.org/apps/mail/vendor/bytestream/horde-mime/lib/Horde/Mime/Headers/Subject.php","line":31,"function":"__construct","class":"Horde_Mime_Headers_Element","type":"->"},{"file":"/var/www/nextcloud.mydomain.org/apps/mail/vendor/bytestream/horde-mime/lib/Horde/Mime/Headers.php","line":201,"function":"__construct","class":"Horde_Mime_Headers_Subject","type":"->"},{"file":"/var/www/nextcloud.mydomain.org/apps/mail/vendor/bytestream/horde-imap-client/lib/Horde/Imap/Client/Data/Envelope.php","line":160,"function":"addHeader","class":"Horde_Mime_Headers","type":"->"},{"file":"/var/www/nextcloud.mydomain.org/apps/mail/vendor/bytestream/horde-imap-client/lib/Horde/Imap/Client/Socket.php","line":3517,"function":"__set","class":"Horde_Imap_Client_Data_Envelope","type":"->"},{"file":"/var/www/nextcloud.mydomain.org/apps/mail/vendor/bytestream/horde-imap-client/lib/Horde/Imap/Client/Socket.php","line":3167,"function":"_parseEnvelope","class":"Horde_Imap_Client_Socket","type":"->"},{"file":"/var/www/nextcloud.mydomain.org/apps/mail/vendor/bytestream/horde-imap-client/lib/Horde/Imap/Client/Socket.php","line":4777,"function":"_parseFetch","class":"Horde_Imap_Client_Socket","type":"->"},{"file":"/var/www/nextcloud.mydomain.org/apps/mail/vendor/bytestream/horde-imap-client/lib/Horde/Imap/Client/Socket.php","line":4574,"function":"_serverResponse","class":"Horde_Imap_Client_Socket","type":"->"},{"file":"/var/www/nextcloud.mydomain.org/apps/mail/vendor/bytestream/horde-imap-client/lib/Horde/Imap/Client/Socket.php","line":4313,"function":"_getLine","class":"Horde_Imap_Client_Socket","type":"->"},{"file":"/var/www/nextcloud.mydomain.org/apps/mail/vendor/bytestream/horde-imap-client/lib/Horde/Imap/Client/Socket.php","line":4241,"function":"_sendCmdChunk","class":"Horde_Imap_Client_Socket","type":"->"},{"file":"/var/www/nextcloud.mydomain.org/apps/mail/vendor/bytestream/horde-imap-client/lib/Horde/Imap/Client/Socket.php","line":2837,"function":"_sendCmd","class":"Horde_Imap_Client_Socket","type":"->"},{"file":"/var/www/nextcloud.mydomain.org/apps/mail/vendor/bytestream/horde-imap-client/lib/Horde/Imap/Client/Base.php","line":2584,"function":"_fetch","class":"Horde_Imap_Client_Socket","type":"->"},{"file":"/var/www/nextcloud.mydomain.org/apps/mail/vendor/bytestream/horde-imap-client/lib/Horde/Imap/Client/Base.php","line":2478,"function":"_fetchWrapper","class":"Horde_Imap_Client_Base","type":"->"},{"file":"/var/www/nextcloud.mydomain.org/apps/mail/lib/IMAP/MessageMapper.php","line":246,"function":"fetch","class":"Horde_Imap_Client_Base","type":"->"},{"file":"/var/www/nextcloud.mydomain.org/apps/mail/lib/IMAP/MessageMapper.php","line":214,"function":"findByIds","class":"OCA\\Mail\\IMAP\\MessageMapper","type":"->"},{"file":"/var/www/nextcloud.mydomain.org/apps/mail/lib/Service/Sync/ImapToDbSynchronizer.php","line":301,"function":"findAll","class":"OCA\\Mail\\IMAP\\MessageMapper","type":"->"},{"file":"/var/www/nextcloud.mydomain.org/apps/mail/lib/Service/Sync/ImapToDbSynchronizer.php","line":231,"function":"runInitialSync","class":"OCA\\Mail\\Service\\Sync\\ImapToDbSynchronizer","type":"->"},{"file":"/var/www/nextcloud.mydomain.org/apps/mail/lib/Service/Sync/ImapToDbSynchronizer.php","line":137,"function":"sync","class":"OCA\\Mail\\Service\\Sync\\ImapToDbSynchronizer","type":"->"},{"file":"/var/www/nextcloud.mydomain.org/apps/mail/lib/BackgroundJob/SyncJob.php","line":122,"function":"syncAccount","class":"OCA\\Mail\\Service\\Sync\\ImapToDbSynchronizer","type":"->"},{"file":"/var/www/nextcloud.mydomain.org/lib/public/BackgroundJob/Job.php","line":79,"function":"run","class":"OCA\\Mail\\BackgroundJob\\SyncJob","type":"->"},{"file":"/var/www/nextcloud.mydomain.org/lib/public/BackgroundJob/TimedJob.php","line":95,"function":"execute","class":"OCP\\BackgroundJob\\Job","type":"->"},{"file":"/var/www/nextcloud.mydomain.org/cron.php","line":151,"function":"execute","class":"OCP\\BackgroundJob\\TimedJob","type":"->"}],"File":"/var/www/nextcloud.mydomain.org/apps/mail/vendor/bytestream/horde-util/lib/Horde/String.php","Line":160},"CustomMessage":"Cron mail sync failed for account 4"},"id":"62b8762ade6c7"}

### Expected behavior

Should not happen.

### Actual behavior

I fixed it and now I can use maill app again.

### Mail app version

1.13.5

### Mailserver or service

Exim/Dovecot

### Operating system

Debian

### PHP engine version

PHP 8.0

### Database

PostgreSQL

**Comment by kesselb** [comment]
Hey, closing in favor of https://github.com/nextcloud/mail/issues/6562.
