### ISSUE TITLE
Allow replying with an iMIP message to email invitations

### ISSUE THREAD

**Issue by miaulalala** [nextcloud/mail#6803]
### Is your feature request related to a problem? Please describe.

See #160 

### Describe the solution you'd like

Backend:
~~- -[ ]create api endpoint that creates an iMIP compatible email that is sent when clicking Accept, Decline, etc (REPLY). Should allow passing of params PARTSTAT, guests, comments, etc. See RFC for more details on what exactly is needed.~~

This is not neccesary as CalDAV already sends such an email.

Frontent:
- [ ] trigger request to api write the VCARD to the calendar of the user's choice. This should pass on the updated PARTSTAT and possibly more options (guests, comment) as described in the RFC. This will then trigger an email form scheduling.

~~There might be a Reply-To email address in the invitation. This has to be respected as the new `to:` email address.~~ 

thi is not relevant for replies

**Comment by ChristophWurst** [comment]
> See #160

Isn't this effectively a duplicate? Let's merge the tickets

**Comment by miaulalala** [comment]
No? This is part of what we discussed and only contains a specific part of what is neccessary to make iMIP work?

**Comment by ChristophWurst** [comment]
Alright, then I misunderstood. #160 is listed as problem description, so I (wrongly) figured it's about the same thing.

**Comment by ChristophWurst** [comment]
Am I understanding correctly that #160 is purely about rendering the invitation (without actions) and this ticket will build on top and add the actions that send the reply?

**Comment by miaulalala** [comment]
Yeah I would take 160 as the ticket for the first part of the implementation, displaying the iMIP messages. Are you ok with that?

**Comment by miaulalala** [comment]
Is there any way we can parse the PARTSTAT for an attendee and display that instead of the generic "this event has been updated"?

![image](https://user-images.githubusercontent.com/7427347/180758933-b1ae5939-7839-4c87-adee-95d64de6552c.png)

**Comment by gcolpart** [comment]
> For me the bug is still present : external organizers (for example with Google Calendar users) are never notified when you accept/decline an external invitation in "Nextcloud Mail", and same problem if you accept/decline in "Nextcloud Calendar".
> 
> Nextcloud should send an iMIP message (with iCal attachment reflecting the response).
> 
> This is a significant bug because an external organizer never know if I have accepted or I have declined the invitation… or I didn't respond to the invitation!

It's now fixed for Calendar in Nextcloud 29.04 and 28.08, and in Mail 3.7.8.
