### ISSUE TITLE
Signup Dialogue is visually broken

### ISSUE THREAD

**Issue by miaulalala** [nextcloud/mail#6810]
### Steps to reproduce

1. Have no mail account
2. open Mail
3. see that the signup dialogue isn't pretty:

![image](https://user-images.githubusercontent.com/7427347/176655137-f958769e-a994-4d54-965a-ddf1f507a44e.png)

### Expected behavior

Signup dialogue looking fresh

### Actual behavior

Signup dialogue not looking fresh

### Mail app version

main

### Mailserver or service

GMX

### Operating system

Ubuntu 20

### PHP engine version

PHP 8.0

### Web server

Apache (supported)

### Database

MySQL

**Comment by ChristophWurst** [comment]
Changing to high priority because this is important for the first use experience
