### ISSUE TITLE
Thread message loading spinner shown on top of other message

### ISSUE THREAD

**Issue by ChristophWurst** [nextcloud/mail#6811]
### Steps to reproduce

1. Open a thread with 5+ messages (last message should be open, the others collapsed)
2. Click on the second message
3. See a loading spinner

### Expected behavior

The spinner shows on the clicked message or some kind of placeholder space underneath

### Actual behavior

The spinner hovers the next message

![Bildschirmfoto vom 2022-06-30 13-25-38](https://user-images.githubusercontent.com/1374172/176666564-7829e8af-12f3-4c27-a49c-dbdae2027b1d.png)

### Mail app version

1.13

**Comment by GVodyanov** [comment]
Fixed by https://github.com/nextcloud/mail/pull/7472, seeing as the spinner does not exist any more
