### ISSUE TITLE
Loading spinner is on top of text when indexing messages

### ISSUE THREAD

**Issue by miaulalala** [nextcloud/mail#6813]
![image](https://user-images.githubusercontent.com/7427347/176676336-e10746e9-9ace-4a16-beeb-ab98bdd4b489.png)

### Expected behavior

The spinner is above the text

### Actual behavior

The spinner is in the text

### Mail app version

master

### Mailserver or service

GMX

### Operating system

Ubuntu 20

### PHP engine version

PHP 8.0

### Web server

Apache (supported)

### Database

MySQL

**Comment by ChristophWurst** [comment]
This is https://github.com/nextcloud/mail/issues/6205 's friend

**Comment by ChristophWurst** [comment]
This does not happen anymore
