### ISSUE TITLE
Entwurf wird nicht korrekt gespeichert, keine Adressen, kein Inhalt!

### ISSUE THREAD

**Issue by Andi220769** [nextcloud/mail#6815]
### Steps to reproduce

1. Beim Schreiben einer normalen Mail an mehrere Empfänger wird automatisch ein Entwurf gespeichert.
2. Ruft man jedoch einen dieser Entwürfe auf, erscheint lediglich eine leere Mail. Nur der Betreff wird gespeichert.
3. So ist die Entwurfsspeicherung unbrauchbar.

### Expected behavior

Ein Entwurf sollte zum Speicherzeitpunkt die komplette bis dahin gemachten Änderungen einer Mail speichern.

### Mail app version

1.13.5

### Mailserver or service

own server at hetzner.der

### Operating system

Nextcloud Server at Heztner cloud

### PHP engine version

PHP 8.1

### Web server

Apache (supported)

### Database

MySQL

**Comment by ChristophWurst** [comment]
Update to v1.13.6.

Ref https://github.com/nextcloud/mail/pull/6798

Please write your future reports in English.
