### ISSUE TITLE
Give starred message icon a white outline too

### ISSUE THREAD

**Issue by ChristophWurst** [nextcloud/mail#6818]
### Is your feature request related to a problem? Please describe.

The *important* icon looks quite nice on the sender avatar, the star not so much.

![Bildschirmfoto vom 2022-07-01 11-02-43](https://user-images.githubusercontent.com/1374172/176862976-dd5582c1-192d-406d-8dc1-15e9deaa8044.png)

### Describe the solution you'd like

Add an outline to the star. That would also make it look consistent with the other icon.

### Additional context

@GretaD possible task for you

cc @nimishavijay @jancborchardt for additional input

**Comment by nimishavijay** [comment]
Great idea 👍🏽 The vertical alignment of the important and star is also off by 1-2 pixels, we should fix that if possible (or it might get fixed once the outline is added)
