### ISSUE TITLE
Request: allow unprivileged User to auto-save attachments to Files

### ISSUE THREAD

**Issue by sunjam** [nextcloud/mail#682]
[files_frommail devs are encouraging me to create this issue with the Mail App devs directly.  Hello!](https://github.com/nextcloud/files_frommail/issues/3)  
    
Problem is saving attachments to files currently requires administrative rights, but I'd like for standard users (such as those at a school) to  be able to email files directly into their account w/out admin rights -- See open [Issue #3 I posted to files_frommail github page.](https://github.com/nextcloud/files_frommail/issues/3)

Closed Issue #249 allows for only admins to save attachments as files, but not users
Open Issue #675 is a similar request, but I'm specifically interested in allowing attachments to be saved by users without admin privileges.

**Comment by ChristophWurst** [comment]
Hello,

thank you for reporting this here. I still don't think such a feature would be used by the majority of your users and thus it has very little priority. Though I do not plan to integrate a feature like this here, I'm okay with leaving the ticket open. If someone wants to pick it up, please keep in mind that I will only integrate it if it is fully functional (including UI, unit and integration tests) and someone dedicates their time on maintaining the feature in the future (testing before releases, updating dependencies, triaging GitHub issues and so on).

**Comment by ChristophWurst** [comment]
> sunjam referenced this issue in pierre-alain-b/rainloop-nextcloud on 15 Feb
> Closed
> Request: allow Rainloop user to auto-save attachments to Files #50

Looks like you're using another mail app anyway and this feature is more or less implemented by https://apps.nextcloud.com/apps/files_frommail, so I'm closing this ticket.
