### ISSUE TITLE
Gateway Time-out mail server shut down

### ISSUE THREAD

**Issue by Tealk** [nextcloud/mail#6829]
### Steps to reproduce

when opening the mail app

### Expected behavior

the mail app should open and the entry should be deletable

### Actual behavior

I get a white page with 504 Gateway Time-out

### Mail app version

1.13.5

### Mailserver or service

mailcow

### Operating system

debian

### PHP engine version

PHP 8.1

### Web server

Nginx

### Database

MariaDB

### Additional info

i had a web account connected where the mailserver is now offline
now i can no longer access the mail app

**Comment by Tealk** [comment]
Maybe it would be a good option if you would add a delete button in the settings, so that you can reset mail settings?

**Comment by ChristophWurst** [comment]
You can delete a defunct mail account now
