### ISSUE TITLE
1.13.6 not released yet

### ISSUE THREAD

**Issue by LostinSpacetime** [nextcloud/mail#6832]
### Steps to reproduce

Version 1.13.6 is marked as complete, but is not released yet.

### Expected behavior

Being able to update to 1.13.6

### Actual behavior

Not being able to update to 1.13.6

### Mail app version

1.13.5

**Comment by ChristophWurst** [comment]
https://github.com/nextcloud-releases/mail/releases

**Comment by GretaD** [comment]
i would bet a lot of money that i did all the steps of the release right :face_exhaling: 

https://github.com/nextcloud-releases/mail/actions/workflows/appstore-build-publish.yml
