### ISSUE TITLE
Phone only displays one page of emails.

### ISSUE THREAD

**Issue by wriver4** [nextcloud/mail#6836]
### Steps to reproduce

1. In the phone's browser, ios or android go to your Nextcloud installation.
2. Login to Nextcloud and tap Mail
3. Try to an old email.

### Expected behavior

You should be able to scroll down or have pagination arrows to see more than one page of email.

### Actual behavior

On the phone, it only shows one page and just bounces when you try and scroll.
In any browser on Mac, Win, or Linux it works as expected. 

### Mail app version

1.11.7

### Mailserver or service

Control Web Panel - CWP/Centos Web Panel - Postfix

### Operating system

IOS or Android

### PHP engine version

PHP 7.4

### Web server

Apache (supported)

### Database

MySQL

**Comment by ChristophWurst** [comment]
Dup of https://github.com/nextcloud/mail/issues/1619. The fix will be released soon.
