### ISSUE TITLE
some message are not rendered correctly

### ISSUE THREAD

**Issue by joergmschulz** [nextcloud/mail#6838]
### Steps to reproduce

1. click on message 

### Expected behavior

message content should be visible. But only the subject is visible. This happens for /some/ message, but not for all.

### Actual behavior

<img width="1031" alt="image" src="https://user-images.githubusercontent.com/6523646/177486131-da6bf6ae-caa2-4a62-b9a2-4369f8be1301.png">

### Mail app version

1.13.5, 1.13.6

### Operating system

Debian

### PHP engine version

PHP 8.0

### Web server

Nginx

### Database

PostgreSQL

### Additional info

Nginx --> Traefik.
Browsers: Firefox (with some script blockers), Safari (unblocked) on osx , Edge on Windows

**Comment by st3iny** [comment]
Is this also happening when you disable all script blockers etc.? 

Could you share this email with me for debugging? I can provide a private email address if you don't want to share it publicly.

**Comment by joergmschulz** [comment]
<img width="1141" alt="image" src="https://user-images.githubusercontent.com/6523646/177970962-44e0baad-0a66-45b9-ac41-ca94138675f1.png">
will follow up soon - it seems this happens for messages that have been DELETED by other imap MUAs. Possibly, the nc mail app indexer keeps some data?
