### ISSUE TITLE
Cannot attach files to email

### ISSUE THREAD

**Issue by pieter-groeneweg** [nextcloud/mail#685]
### Steps to reproduce
1. click "New Message"
2. click "Add attachment from Files
3. browser and select a file

### Expected behaviour
Expect to have the file attached to the email by either click or have a button to click

### Actual behaviour
Nothing happens and I am locked in the file explorer modal, can only get out refreshing the page

### Mail app

version 0.7.6

postfix

**Transport security - IMAP:

**Transport security - SMTP:

**Number of accounts:**

**Mail app version build date:** (only if you are using a Nightly Build)

## Server configuration detail

**Operating system:** Linux 4.9.0-4-amd64 #1 SMP Debian 4.9.51-1 (2017-09-28) x86_64

**Webserver:** Apache/2.4.25 (cgi-fcgi)

**Database:** mysql 10.1.26

**PHP version:** 7.0.19-1
Modules loaded: Core, date, libxml, openssl, pcre, zlib, filter, hash, pcntl, Reflection, SPL, session, standard, cgi-fcgi, mysqlnd, PDO, xml, apcu, apc, bcmath, bz2, calendar, ctype, curl, dom, mbstring, fileinfo, ftp, gd, gettext, iconv, intl, json, exif, mcrypt, mysqli, pdo_mysql, Phar, posix, readline, shmop, SimpleXML, smbclient, sockets, sysvmsg, sysvsem, sysvshm, tokenizer, wddx, xmlreader, xmlwriter, xsl, zip, libsmbclient, Zend OPcache

**Nextcloud version:** 12.0.4 - 12.0.4.3

Enabled:
 - activity: 2.5.2
 - apporder: 0.4.1
 - audioplayer: 2.2.1
 - bruteforcesettings: 1.0.3
 - calendar: 1.5.7
 - comments: 1.2.0
 - contacts: 2.0.1
 - dav: 1.3.0
 - deck: 0.2.8
 - federatedfilesharing: 1.2.0
 - federation: 1.2.0
 - files: 1.7.2
 - files_accesscontrol: 1.2.5
 - files_clipboard: 0.6.4
 - files_downloadactivity: 1.1.1
 - files_external: 1.3.0
 - files_pdfviewer: 1.1.1
 - files_sharing: 1.4.0
 - files_texteditor: 2.4.1
 - files_trashbin: 1.2.0
 - files_versions: 1.5.0
 - files_videoplayer: 1.1.0
 - firstrunwizard: 2.1
 - gallery: 17.0.0
 - groupfolders: 1.1.0
 - impersonate: 1.0.2
 - issuetemplate: 0.3.0
 - logreader: 2.0.0
 - lookup_server_connector: 1.0.0
 - mail: 0.7.6
 - metadata: 0.6.0
 - nextcloud_announcements: 1.1
 - notes: 2.3.2
 - notifications: 2.0.0
 - oauth2: 1.0.5
 - password_policy: 1.2.2
 - previewgenerator: 1.0.7
 - provisioning_api: 1.2.0
 - richdocuments: 1.12.39
 - serverinfo: 1.2.0
 - sharebymail: 1.2.0
 - spreedme: 0.3.11
 - survey_client: 1.0.0
 - systemtags: 1.2.0
 - tasks: 0.9.5
 - theming: 1.3.0
 - twofactor_backupcodes: 1.1.1
 - updatenotification: 1.2.0
 - workflowengine: 1.2.0
Disabled:
 - admin_audit
 - encryption
 - music
 - spreed
 - user_external
 - user_ldap

**Comment by ChristophWurst** [comment]
Dup of #626
