### ISSUE TITLE
Subfolders shown repeatedly with full path (dovecot IMAP server)

### ISSUE THREAD

**Issue by archont00** [nextcloud/mail#689]
### Steps to reproduce
1. Open mail app in Nexctloud.
2. Show all folders in left pane.
3. Click on "expansion" triangle for a parent folder.
3. Subfolders appear as a flat list of full paths to subfolders (Parent/Subfolder1, Parent/Subfolder2, ...).

### Expected behaviour
A classical hierarchy tree would be expected. Sufolders should be listed alphabetically, too.
````
- Archive
     2003
     2004
     2005
     2006
     ... cut on purpose ...
     2017
````

### Actual behaviour
Flat list of subfolder full path is shown - see the screenshot.
![subfolders list bug](https://user-images.githubusercontent.com/937861/34378102-a285fbd6-eaf4-11e7-9fcc-89f1589375b4.png)
(In this case the parent level is called "Archive" while the childern are listed as Archives/... The "Archive" and "Archives" is technically the same mail folder, which is just shown as "Archive" virtual folder on top level.
The bug exhibits also for user created folder (Other/School, Other/Work, Other/Mailing Lists/Whatever).

### Mail app

**Mail app version:** 0.7.6

**Mailserver or service:** dovecot 2.2.33.2
````
/etc/dovecot/conf.d/10-mail.conf
... cut on purpose ...
#     Maildir:LAYOUT=fs:DIRNAME=Grr
#     'fs' layout allows to use file system hierarchy as an actual folder structure.
#     DIRNAME helps to remove problem w/ use of reserved keywords {new,cur,tmp}
#     and it should be some word unlikely to be used by a user as folder name:
#        Maildir/SomeFolder/DIRNAME/{cur,new,tmp}
mail_location = maildir:~/Maildir:LAYOUT=fs:DIRNAME=0_mAIL
... cut on purpose ...
````
**Transport security - IMAP:** imap over SSL (imaps, port 993)

**Number of accounts:** 2

## Server configuration detail

**Operating system:** Linux 4.9.60-1-lts #1 SMP Thu Nov 2 16:48:25 CET 2017 x86_64

**Webserver:** nginx/1.13.7 (fpm-fcgi)

**Database:** mysql 10.2.11

**PHP version:** 7.1.11
Modules loaded: Core, date, libxml, openssl, pcre, sqlite3, zlib, ctype, curl, dom, fileinfo, filter, gd, hash, iconv, json, mbstring, SPL, PDO, pdo_sqlite, bz2, posix, readline, Reflection, session, SimpleXML, standard, tokenizer, xml, xmlreader, xmlwriter, mysqlnd, cgi-fcgi, apcu, Phar, exif, ftp, gmp, imap, intl, ldap, mcrypt, mysqli, pcntl, pdo_mysql, pdo_pgsql, pgsql, zip, redis, smbclient, libsmbclient, Zend OPcache

**Nextcloud version:** 12.0.4 - 12.0.4.3

**Updated from an older Nextcloud/ownCloud or fresh install:** Cca a half year ago upgraded from ownCloud to Nextcloud, but never used Mail app before. Mail app was activated in Nextcloud 12.0.x for the first time.

**Where did you install Nextcloud from:** docker repository hoellen/nextcloud:12.0

<details><summary>Signing status</summary>

Array
</details>

<details><summary>List of activated apps</summary>

```
Enabled:
 - activity: 2.5.2
 - calendar: 1.5.7
 - contacts: 2.0.1
 - dav: 1.3.0
 - federatedfilesharing: 1.2.0
 - files: 1.7.2
 - files_accesscontrol: 1.2.5
 - files_downloadactivity: 1.1.1
 - files_external: 1.3.0
 - files_pdfviewer: 1.1.1
 - files_sharing: 1.4.0
 - files_texteditor: 2.4.1
 - files_trashbin: 1.2.0
 - files_versions: 1.5.0
 - files_videoplayer: 1.1.0
 - firstrunwizard: 2.1
 - gallery: 17.0.0
 - impersonate: 1.0.2
 - issuetemplate: 0.3.0
 - keeweb: 0.4.0
 - lookup_server_connector: 1.0.0
 - mail: 0.7.6
 - metadata: 0.6.0
 - nextant: 1.0.8
 - nextcloud_announcements: 1.1
 - oauth2: 1.0.5
 - password_policy: 1.2.2
 - previewgenerator: 1.0.8
 - provisioning_api: 1.2.0
 - richdocuments: 1.12.39
 - sharebymail: 1.2.0
 - systemtags: 1.2.0
 - twofactor_backupcodes: 1.1.1
 - updatenotification: 1.2.0
 - workflowengine: 1.2.0
Disabled:
 - admin_audit
 - bruteforcesettings
 - comments
 - encryption
 - external
 - federation
 - logreader
 - notifications
 - ocsms
 - serverinfo
 - survey_client
 - theming
 - user_external
 - user_ldap

```
</details>

<details><summary>Configuration (config/config.php)</summary>

```
{
    "datadirectory": "\/data",
    "apps_paths": [
        {
            "path": "\/nextcloud\/apps",
            "url": "\/apps",
            "writable": false
        },
        {
            "path": "\/apps2",
            "url": "\/apps2",
            "writable": true
        }
    ],
    "memcache.local": "\\OC\\Memcache\\APCu",
    "instanceid": "ocwgkowh3q4h",
    "mail_from_address": "webmaster",
    "logtimezone": "Europe\/Berlin",
    "logdateformat": "Y-m-d H:i:s",
    "passwordsalt": "***REMOVED SENSITIVE VALUE***",
    "secret": "***REMOVED SENSITIVE VALUE***",
    "trusted_domains": [
        "cloud.REMOVED.net"
    ],
    "overwrite.cli.url": "https:\/\/cloud.REMOVED.net",
    "dbtype": "mysql",
    "version": "12.0.4.3",
    "dbname": "nextcloud",
    "dbhost": "db",
    "dbport": "",
    "dbtableprefix": "",
    "mysql.utf8mb4": true,
    "dbuser": "***REMOVED SENSITIVE VALUE***",
    "dbpassword": "***REMOVED SENSITIVE VALUE***",
    "installed": true,
    "loglevel": 2,
    "maintenance": false,
    "mail_domain": "REMOVED.net",
    "mail_smtpmode": "smtp",
    "mail_smtpauthtype": "PLAIN",
    "mail_smtphost": "smtp.REMOVED.net",
    "mail_smtpport": "25",
    "auth.bruteforce.protection.enabled": false,
    "preview_max_x": 512,
    "preview_max_y": 512,
    "preview_max_scale_factor": 1
}
```
</details>

## Client configuration

**Browser:** Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/63.0.3239.108 Safari/537.36

**Comment by myzinsky** [comment]
Sane Problem here with Nextcloud 12.0.5 and Mail 0.7.9:

![capture](https://user-images.githubusercontent.com/1970554/35580884-944a59d4-05ea-11e8-97e4-1bf1620f1828.PNG)

**Comment by joe-speedboat** [comment]
Same Problem here, seems to be defective for ages.
To sad, would be great app. I love the attachment handling.
but since I use many folders, I moved to rainloop
NextCloud:
CentOS 7 Server
Nextcloud 13.01 stable
Mail  0.7.10
eMail:
CentOS 7
dovecot-2.2.10-8.el7.x86_64
Folder config: `mail_location = mbox:~/mail:LAYOUT=maildir++:INDEX=~/mail/index:CONTROL=~/mail/control`

Works as expected with thunderbird and rainloop.

Thanks
Chris

![mail_20180407-130849](https://user-images.githubusercontent.com/14975048/38454304-edb0d562-3a64-11e8-8dd7-c2dae0cfecef.png)

**Comment by milankni** [comment]
However stale, it is still valid.

**Comment by doc75** [comment]
I confim that this bug is still persent (NC 17 and mail v1.3.3).

Moreover the content of the folder is seen as empty while it contains mail on the server.
This is making sub-folder unusable in mail application.

**Comment by RafalLukawiecki** [comment]
Same problem in NC 19.0.0, cannot use subfolders with NC mail, even though they work in other apps/systems.
