### ISSUE TITLE
App settings should be a modal

### ISSUE THREAD

**Issue by ya-d** [nextcloud/mail#6896]
### Is your feature request related to a problem? Please describe.

Currently app settings are located in the lower left corner. This makes the view very cramped and off sight, and requires lots of scrolling on a tiny space. It also makes the settings button move up and melt with the list of inboxes and folder, without any visual separation.

<img width="150" alt="image" src="https://user-images.githubusercontent.com/30781876/179344997-2654b698-c6c9-4799-a249-5be99491c32c.png">

### Describe the solution you'd like

Like Talk, settings should be displayed in a modal view.

**Comment by ChristophWurst** [comment]
Let's do this and also move the global *Trusted senders* from account settings modals to the app settings modal.
