### ISSUE TITLE
Some messages won't open

### ISSUE THREAD

**Issue by AMajor-C** [nextcloud/mail#6913]
### Steps to reproduce

I dont know why but app just not load and show some messages. It seems independent on incoming mail address or mail account...

### Expected behavior

All messages available to load and view

### Actual behavior

Some messages won't open

### Mail app version

1.13.6

### Mailserver or service

yandex

### Operating system

Centos 8

### PHP engine version

Other

### Web server

Apache (supported)

### Database

MySQL

### Additional info

```
OCA\Mail\Exception\ServiceException: Could not load message

/var/www/ncloud.ainet.us/html/apps/mail/lib/Controller/MessagesController.php - line 248:

OCA\Mail\Service\MailManager->getImapMessage(OCA\Mail\Account {}, OCA\Mail\Db\Mailbox { id: 19}, 1721, true)

/var/www/ncloud.ainet.us/html/lib/private/AppFramework/Http/Dispatcher.php - line 225:

OCA\Mail\Controller\MessagesController->getBody(130)

/var/www/ncloud.ainet.us/html/lib/private/AppFramework/Http/Dispatcher.php - line 133:

OC\AppFramework\Http\Dispatcher->executeController(OCA\Mail\Con ... {}, "getBody")

/var/www/ncloud.ainet.us/html/lib/private/AppFramework/App.php - line 172:

OC\AppFramework\Http\Dispatcher->dispatch(OCA\Mail\Con ... {}, "getBody")

/var/www/ncloud.ainet.us/html/lib/private/Route/Router.php - line 298:

OC\AppFramework\App::main("OCA\\Mail\\ ... r", "getBody", OC\AppFramew ... {}, [ "130","mai ... "])

/var/www/ncloud.ainet.us/html/lib/base.php - line 1023:

OC\Route\Router->match("/apps/mail/ ... y")

/var/www/ncloud.ainet.us/html/index.php - line 36:

OC::handleRequest()

Caused by OCP\AppFramework\Db\DoesNotExistException: Mail body for this mail(1721) could not be loaded

/var/www/ncloud.ainet.us/html/apps/mail/lib/Model/IMAPMessage.php - line 583:

OCA\Mail\Model\IMAPMessage->loadBodyData(Horde_Mime_Part { parent: null}, 1)

/var/www/ncloud.ainet.us/html/apps/mail/lib/Model/IMAPMessage.php - line 459:

OCA\Mail\Model\IMAPMessage->handleHtmlMessage(Horde_Mime_Part { parent: null}, 1)

/var/www/ncloud.ainet.us/html/apps/mail/lib/Model/IMAPMessage.php - line 381:

OCA\Mail\Model\IMAPMessage->getPart(Horde_Mime_Part { parent: null}, 1)

/var/www/ncloud.ainet.us/html/apps/mail/lib/Model/IMAPMessage.php - line 102:

OCA\Mail\Model\IMAPMessage->loadMessageBodies()

/var/www/ncloud.ainet.us/html/apps/mail/lib/IMAP/MessageMapper.php - line 261:

OCA\Mail\Model\IMAPMessage->__construct(Horde_Imap_C ... e}, "INBOX", 1721, null, true)



OCA\Mail\IMAP\MessageMapper->OCA\Mail\IMAP\{closure}("*** sensiti ... *")

/var/www/ncloud.ainet.us/html/apps/mail/lib/IMAP/MessageMapper.php - line 275:

array_map(Closure {}, [ "*** sensi ... "])

/var/www/ncloud.ainet.us/html/apps/mail/lib/IMAP/MessageMapper.php - line 71:

OCA\Mail\IMAP\MessageMapper->findByIds(Horde_Imap_C ... e}, "INBOX", Horde_Imap_C ... e}, true)

/var/www/ncloud.ainet.us/html/apps/mail/lib/Service/MailManager.php - line 181:

OCA\Mail\IMAP\MessageMapper->find(Horde_Imap_C ... e}, "INBOX", 1721, true)

/var/www/ncloud.ainet.us/html/apps/mail/lib/Controller/MessagesController.php - line 248:

OCA\Mail\Service\MailManager->getImapMessage(OCA\Mail\Account {}, OCA\Mail\Db\Mailbox { id: 19}, 1721, true)

/var/www/ncloud.ainet.us/html/lib/private/AppFramework/Http/Dispatcher.php - line 225:

OCA\Mail\Controller\MessagesController->getBody(130)

/var/www/ncloud.ainet.us/html/lib/private/AppFramework/Http/Dispatcher.php - line 133:

OC\AppFramework\Http\Dispatcher->executeController(OCA\Mail\Con ... {}, "getBody")

/var/www/ncloud.ainet.us/html/lib/private/AppFramework/App.php - line 172:

OC\AppFramework\Http\Dispatcher->dispatch(OCA\Mail\Con ... {}, "getBody")

/var/www/ncloud.ainet.us/html/lib/private/Route/Router.php - line 298:

OC\AppFramework\App::main("OCA\\Mail\\ ... r", "getBody", OC\AppFramew ... {}, [ "130","mai ... "])

/var/www/ncloud.ainet.us/html/lib/base.php - line 1023:

OC\Route\Router->match("/apps/mail/ ... y")

/var/www/ncloud.ainet.us/html/index.php - line 36:

OC::handleRequest()

```

**Comment by miaulalala** [comment]
Please have a look at your nextcloud.log at ./data/nextcloud.log

**Comment by AMajor-C** [comment]
> Please have a look at your nextcloud.log at ./data/nextcloud.log in your root directory

`OCA\Mail\Exception\ServiceException: Could not load message

    /var/www/ncloud.ainet.us/html/apps/mail/lib/Controller/MessagesController.php - line 248:

    OCA\Mail\Service\MailManager->getImapMessage(OCA\Mail\Account {}, OCA\Mail\Db\Mailbox { id: 19}, 1721, true)

    /var/www/ncloud.ainet.us/html/lib/private/AppFramework/Http/Dispatcher.php - line 225:

    OCA\Mail\Controller\MessagesController->getBody(130)

    /var/www/ncloud.ainet.us/html/lib/private/AppFramework/Http/Dispatcher.php - line 133:

    OC\AppFramework\Http\Dispatcher->executeController(OCA\Mail\Con ... {}, "getBody")

    /var/www/ncloud.ainet.us/html/lib/private/AppFramework/App.php - line 172:

    OC\AppFramework\Http\Dispatcher->dispatch(OCA\Mail\Con ... {}, "getBody")

    /var/www/ncloud.ainet.us/html/lib/private/Route/Router.php - line 298:

    OC\AppFramework\App::main("OCA\\Mail\\ ... r", "getBody", OC\AppFramew ... {}, [ "130","mai ... "])

    /var/www/ncloud.ainet.us/html/lib/base.php - line 1023:

    OC\Route\Router->match("/apps/mail/ ... y")

    /var/www/ncloud.ainet.us/html/index.php - line 36:

    OC::handleRequest()

Caused by OCP\AppFramework\Db\DoesNotExistException: Mail body for this mail(1721) could not be loaded

    /var/www/ncloud.ainet.us/html/apps/mail/lib/Model/IMAPMessage.php - line 583:

    OCA\Mail\Model\IMAPMessage->loadBodyData(Horde_Mime_Part { parent: null}, 1)

    /var/www/ncloud.ainet.us/html/apps/mail/lib/Model/IMAPMessage.php - line 459:

    OCA\Mail\Model\IMAPMessage->handleHtmlMessage(Horde_Mime_Part { parent: null}, 1)

    /var/www/ncloud.ainet.us/html/apps/mail/lib/Model/IMAPMessage.php - line 381:

    OCA\Mail\Model\IMAPMessage->getPart(Horde_Mime_Part { parent: null}, 1)

    /var/www/ncloud.ainet.us/html/apps/mail/lib/Model/IMAPMessage.php - line 102:

    OCA\Mail\Model\IMAPMessage->loadMessageBodies()

    /var/www/ncloud.ainet.us/html/apps/mail/lib/IMAP/MessageMapper.php - line 261:

    OCA\Mail\Model\IMAPMessage->__construct(Horde_Imap_C ... e}, "INBOX", 1721, null, true)

    <<closure>>

    OCA\Mail\IMAP\MessageMapper->OCA\Mail\IMAP\{closure}("*** sensiti ... *")

    /var/www/ncloud.ainet.us/html/apps/mail/lib/IMAP/MessageMapper.php - line 275:

    array_map(Closure {}, [ "*** sensi ... "])

    /var/www/ncloud.ainet.us/html/apps/mail/lib/IMAP/MessageMapper.php - line 71:

    OCA\Mail\IMAP\MessageMapper->findByIds(Horde_Imap_C ... e}, "INBOX", Horde_Imap_C ... e}, true)

    /var/www/ncloud.ainet.us/html/apps/mail/lib/Service/MailManager.php - line 181:

    OCA\Mail\IMAP\MessageMapper->find(Horde_Imap_C ... e}, "INBOX", 1721, true)

    /var/www/ncloud.ainet.us/html/apps/mail/lib/Controller/MessagesController.php - line 248:

    OCA\Mail\Service\MailManager->getImapMessage(OCA\Mail\Account {}, OCA\Mail\Db\Mailbox { id: 19}, 1721, true)

    /var/www/ncloud.ainet.us/html/lib/private/AppFramework/Http/Dispatcher.php - line 225:

    OCA\Mail\Controller\MessagesController->getBody(130)

    /var/www/ncloud.ainet.us/html/lib/private/AppFramework/Http/Dispatcher.php - line 133:

    OC\AppFramework\Http\Dispatcher->executeController(OCA\Mail\Con ... {}, "getBody")

    /var/www/ncloud.ainet.us/html/lib/private/AppFramework/App.php - line 172:

    OC\AppFramework\Http\Dispatcher->dispatch(OCA\Mail\Con ... {}, "getBody")

    /var/www/ncloud.ainet.us/html/lib/private/Route/Router.php - line 298:

    OC\AppFramework\App::main("OCA\\Mail\\ ... r", "getBody", OC\AppFramew ... {}, [ "130","mai ... "])

    /var/www/ncloud.ainet.us/html/lib/base.php - line 1023:

    OC\Route\Router->match("/apps/mail/ ... y")

    /var/www/ncloud.ainet.us/html/index.php - line 36:

    OC::handleRequest()`

**Comment by miaulalala** [comment]
Can you please enable debug logging?

https://docs.nextcloud.com/server/latest/admin_manual/configuration_server/logging_configuration.html

I think this might be connected to the encoding issues we're seeing sometimes.

**Comment by AMajor-C** [comment]
> Can you please enable debug logging?
> 
> https://docs.nextcloud.com/server/latest/admin_manual/configuration_server/logging_configuration.html
> 
> I think this might be connected to the encoding issues we're seeing sometimes.

`OCA\Mail\Exception\ServiceException: Could not load message

    /var/www/ncloud.ainet.us/html/apps/mail/lib/Controller/MessagesController.php - line 248:

    OCA\Mail\Service\MailManager->getImapMessage(OCA\Mail\Account {}, OCA\Mail\Db\Mailbox { id: 19}, 1727, true)

    /var/www/ncloud.ainet.us/html/lib/private/AppFramework/Http/Dispatcher.php - line 225:

    OCA\Mail\Controller\MessagesController->getBody(131)

    /var/www/ncloud.ainet.us/html/lib/private/AppFramework/Http/Dispatcher.php - line 133:

    OC\AppFramework\Http\Dispatcher->executeController(OCA\Mail\Con ... {}, "getBody")

    /var/www/ncloud.ainet.us/html/lib/private/AppFramework/App.php - line 172:

    OC\AppFramework\Http\Dispatcher->dispatch(OCA\Mail\Con ... {}, "getBody")

    /var/www/ncloud.ainet.us/html/lib/private/Route/Router.php - line 298:

    OC\AppFramework\App::main("OCA\\Mail\\ ... r", "getBody", OC\AppFramew ... {}, [ "131","mai ... "])

    /var/www/ncloud.ainet.us/html/lib/base.php - line 1023:

    OC\Route\Router->match("/apps/mail/ ... y")

    /var/www/ncloud.ainet.us/html/index.php - line 36:

    OC::handleRequest()

Caused by OCP\AppFramework\Db\DoesNotExistException: Mail body for this mail(1727) could not be loaded

    /var/www/ncloud.ainet.us/html/apps/mail/lib/Model/IMAPMessage.php - line 583:

    OCA\Mail\Model\IMAPMessage->loadBodyData(Horde_Mime_Part { parent: null}, 1)

    /var/www/ncloud.ainet.us/html/apps/mail/lib/Model/IMAPMessage.php - line 459:

    OCA\Mail\Model\IMAPMessage->handleHtmlMessage(Horde_Mime_Part { parent: null}, 1)

    /var/www/ncloud.ainet.us/html/apps/mail/lib/Model/IMAPMessage.php - line 381:

    OCA\Mail\Model\IMAPMessage->getPart(Horde_Mime_Part { parent: null}, 1)

    /var/www/ncloud.ainet.us/html/apps/mail/lib/Model/IMAPMessage.php - line 102:

    OCA\Mail\Model\IMAPMessage->loadMessageBodies()

    /var/www/ncloud.ainet.us/html/apps/mail/lib/IMAP/MessageMapper.php - line 261:

    OCA\Mail\Model\IMAPMessage->__construct(Horde_Imap_C ... e}, "INBOX", 1727, null, true)

    <<closure>>

    OCA\Mail\IMAP\MessageMapper->OCA\Mail\IMAP\{closure}("*** sensiti ... *")

    /var/www/ncloud.ainet.us/html/apps/mail/lib/IMAP/MessageMapper.php - line 275:

    array_map(Closure {}, [ "*** sensi ... "])

    /var/www/ncloud.ainet.us/html/apps/mail/lib/IMAP/MessageMapper.php - line 71:

    OCA\Mail\IMAP\MessageMapper->findByIds(Horde_Imap_C ... e}, "INBOX", Horde_Imap_C ... e}, true)

    /var/www/ncloud.ainet.us/html/apps/mail/lib/Service/MailManager.php - line 181:

    OCA\Mail\IMAP\MessageMapper->find(Horde_Imap_C ... e}, "INBOX", 1727, true)

    /var/www/ncloud.ainet.us/html/apps/mail/lib/Controller/MessagesController.php - line 248:

    OCA\Mail\Service\MailManager->getImapMessage(OCA\Mail\Account {}, OCA\Mail\Db\Mailbox { id: 19}, 1727, true)

    /var/www/ncloud.ainet.us/html/lib/private/AppFramework/Http/Dispatcher.php - line 225:

    OCA\Mail\Controller\MessagesController->getBody(131)

    /var/www/ncloud.ainet.us/html/lib/private/AppFramework/Http/Dispatcher.php - line 133:

    OC\AppFramework\Http\Dispatcher->executeController(OCA\Mail\Con ... {}, "getBody")

    /var/www/ncloud.ainet.us/html/lib/private/AppFramework/App.php - line 172:

    OC\AppFramework\Http\Dispatcher->dispatch(OCA\Mail\Con ... {}, "getBody")

    /var/www/ncloud.ainet.us/html/lib/private/Route/Router.php - line 298:

    OC\AppFramework\App::main("OCA\\Mail\\ ... r", "getBody", OC\AppFramew ... {}, [ "131","mai ... "])

    /var/www/ncloud.ainet.us/html/lib/base.php - line 1023:

    OC\Route\Router->match("/apps/mail/ ... y")

    /var/www/ncloud.ainet.us/html/index.php - line 36:

    OC::handleRequest()`

**Comment by miaulalala** [comment]
Can you maybe send me the full (not truncated) logs at anna.larch@nextcloud.com if you don't want to post them here?

**Comment by AMajor-C** [comment]
> Can you maybe send me the full (not truncated) logs at [anna.larch@nextcloud.com](mailto:anna.larch@nextcloud.com) if you don't want to post them here?

Done

**Comment by ChristophWurst** [comment]
Can this be closed?

**Comment by ChristophWurst** [comment]
It's most likely https://github.com/nextcloud/mail/issues/9168
