### ISSUE TITLE
Show all folders if only one is behind the „Show all folders“-button [$15]

### ISSUE THREAD

**Issue by MariusBluem** [nextcloud/mail#692]
![4f427aa6-4e2f-4d79-a09f-466884425ff4](https://user-images.githubusercontent.com/19711361/34499173-0022f860-f005-11e7-8829-e8fcdb7a653b.gif)

@ChristophWurst ... any clue why this is flickering when clicking on „Show all folders“ 🤭

**Comment by ChristophWurst** [comment]
> @ChristophWurst ... any clue why this is flickering when clicking on „Show all folders“ 🤭

It's a subtle hint that you shall not use that ugly proprietary phone & browser. Doesn't occur on FF 😛 

My guess would be that it's shown due to the re-rending of the account view.

**Comment by nickvergessen** [comment]
Would it also make sense to allow to have the list expanded all the time? I only have one account configured, thanks to Sieve rules the Inbox is always empty and the folders where my Emails are sorted into is always one click further away than necessary.

**Comment by ChristophWurst** [comment]
Sure, would make sense to somehow save the UI state, even if it's just saved locally in the browser.
