### ISSUE TITLE
 1.14.0-alpha.4 Reply form is empty

### ISSUE THREAD

**Issue by jakobroehrl** [nextcloud/mail#6925]
### Steps to reproduce

1. Open a email
2. Click Reply
3. The reply form is empty

![grafik](https://user-images.githubusercontent.com/24530680/180438011-04b0b8f0-c8c2-4862-a881-d1d01177b85a.png)
![grafik](https://user-images.githubusercontent.com/24530680/180438047-b596819b-66d7-4355-a2a0-cc6c844d915b.png)

### Expected behavior

show mail content

### Actual behavior

no content, tested wit Firefox and Brave

**Comment by kesselb** [comment]
Hey, 

I guess that's a regression of https://github.com/nextcloud/mail/pull/6654.
