### ISSUE TITLE
Add mail account causes nothing

### ISSUE THREAD

**Issue by JuliaKirschenheuter** [nextcloud/mail#6937]
### Steps to reproduce

1. Go to mail settings on a left sidebar
2. Click to "+ Add mail account"
3. Nothing happens

### Expected behavior

Add new account view will be shown

### Actual behavior

Nothing happens. No error messages

### Mail app version

1.13.7

**Comment by ChristophWurst** [comment]
Possibly related

```
[Vue warn]: Property or method "onAccountUpdated" is not defined on the instance but referenced during render. Make sure that this property is reactive, either in the data option, or for class-based components, by initializing the property. See: https://vuejs.org/v2/guide/reactivity.html#Declaring-Reactive-Properties.

found in

---> <AccountSettings> at src/components/AccountSettings.vue
       <RouterLink>
         <AppNavigationItem>
           <NavigationAccount> at src/components/NavigationAccount.vue
             <AppNavigation>
               <Navigation> at src/components/Navigation.vue
                 <Content>
                   <Home> at src/views/Home.vue
                     <App> at src/App.vue
                       <Root>
```

**Comment by ChristophWurst** [comment]
I can not reproduce

**Comment by GretaD** [comment]
this is caused by this: https://github.com/nextcloud/mail/commit/799ee0028d553d46af475bc0499cb1db44864e61

**Comment by JuliaKirschenheuter** [comment]
works but this warning should be fixed 

_Property or method "onAccountUpdated" is not defined on the instance but referenced during render. Make sure that this property is reactive, either in the data option, or for class-based components, by initializing the property._

_found in
---> <AccountSettings> at src/components/AccountSettings.vue_

**Comment by GretaD** [comment]
> works but this warning should be fixed
> 
> _Property or method "onAccountUpdated" is not defined on the instance but referenced during render. Make sure that this property is reactive, either in the data option, or for class-based components, by initializing the property._
> 
> _found in ---> at src/components/AccountSettings.vue_

when i was debbuging it, i replaced the onSave with onAccountUpdate and i didnt see the warning anymore(ithink). Thats what you did too?

**Comment by GretaD** [comment]
fixed here: https://github.com/nextcloud/mail/pull/6998

because i cannot use account settings anymore and i need that for another pr
