### ISSUE TITLE
Support for adding Office365 email accounts using Outlook Web Access

### ISSUE THREAD

**Issue by Fuseteam** [nextcloud/mail#6939]
### Is your feature request related to a problem? Please describe.

I have a office 365 email account that also utilizes 2 factor authentication

this means that it  fails when attempting to add the account to nextcloud mail

### Describe the solution you'd like

appearently in order to add an office 365 account with 2FA to an email client is via outlook web access

### Describe alternatives you've considered

i'm currently running a windows vm with outlook installed

**Comment by ChristophWurst** [comment]
Tracked in https://github.com/nextcloud/mail/issues/6591
