### ISSUE TITLE
Composer font size is too small 

### ISSUE THREAD

**Issue by marcoambrosini** [nextcloud/mail#6940]
### Is your feature request related to a problem? Please describe.

Font size is 13. Not very readable

### Describe the solution you'd like

Bring it up to 15 or 16

**Comment by auroraanna** [comment]
Do you mean 13px? Or are you referring to other units?

With my browser's devtools, if I hover over the text I wrote in the composer, it displays, that it's the font size is 15px. So, if you are referring to pixels then this issue has already been fixed, try updating.
