### ISSUE TITLE
IMAP folders not refreshed - restart needed

### ISSUE THREAD

**Issue by PhilipMay** [nextcloud/mail#6949]
### Steps to reproduce

1. connect NC mail with IMAP mail server
2. connect "2nd client" with the same IMAP server
3. use "2nd client" to create a new folder in the IMAP server
4. see if it is visible in NC mail
5. see that it is not visible in NC mail
6. restart the nextcloud server
7. it is visible in NC mail

### Expected behavior

NC mail should sync the folders

### Actual behavior

NC mail does not see that there is a new server - only after restart

It seems like NC mail only check at start time...

### Mail app version

1.13.7

### Mailserver or service

hetzner

### Operating system

Linux NC docker image

### Database

MariaDB

**Comment by miaulalala** [comment]
Hello!

Unfortunately, refreshing folders isn't instant. The background sync runs every hour.

**Comment by PhilipMay** [comment]
> Hello!
> 
> Unfortunately, refreshing folders isn't instant. The background sync runs every hour.

I will check that and report back.

**Comment by PhilipMay** [comment]
The test folder appeared after some time.
Closing this again. Thanks @miaulalala
