### ISSUE TITLE
Clicking email addresses from mails (linkified to mailto addresses) just refresh the app

### ISSUE THREAD

**Issue by jancborchardt** [nextcloud/mail#696]
### Steps to reproduce
1. Open a reply to an email, or look at a signature
2. See a linkified email address like person@example.com
3. Click it

### Expected behaviour
Without refresh, the new mail composer is opened with the »to« field filled out with that email address and the subject line focused.

### Actual behaviour
A url is loaded: http://localhost/nextcloud/index.php/apps/mail/#mailto?to=person%40example.com
And the app is refreshed. No composer is opened.

Happens on latest master.

**Comment by ChristophWurst** [comment]
Not a regression. This never worked.

**Comment by jancborchardt** [comment]
Ah ok, I assumed this would have been the same as when you click the "from" link in an email.

**Comment by jancborchardt** [comment]
While it still refreshes the page, now it works as expected and a composer is opened with the mail address in the "To" field. :)
