### ISSUE TITLE
Move more message actions out of the actions menu

### ISSUE THREAD

**Issue by ChristophWurst** [nextcloud/mail#6976]
### Is your feature request related to a problem? Please describe.

![Bildschirmfoto vom 2022-08-11 12-51-22](https://user-images.githubusercontent.com/1374172/184117946-4621e28e-69ba-4aca-84ab-b232a8a4725e.png)

### Describe the solution you'd like

Move expanded message actions out of menu: Reply, Fav, Mark unread, Delete – as icon-only buttons

![Bildschirmfoto vom 2022-08-11 12-51-50](https://user-images.githubusercontent.com/1374172/184118027-b0efe69e-b7e4-458e-8975-c5313341b89a.png)

**Comment by jancborchardt** [comment]
Just for info, in the bottom mockup/screenshot the Delete button is missing, but it would be shown between the "Mark read/unread" and the "More actions" icon.
