### ISSUE TITLE
Colored navigation unread counter

### ISSUE THREAD

**Issue by ChristophWurst** [nextcloud/mail#6980]
### Describe the solution you'd like

Navigation unread pills should have primary light as bg and primary as text instead of bland grey.

### Additional context

- [x] Requires https://github.com/nextcloud/nextcloud-vue/issues/3054

**Comment by meichthys** [comment]
Just as a cross-reference, the Tasks app uses the 'bland grey'. Perhaps we'd want to update it there as well, or leave them as is to standardize? (IMO, i don't mind the bland grey at all)

**Comment by ChristophWurst** [comment]
This will be done in the shared components https://github.com/nextcloud/nextcloud-vue/issues/3054
