### ISSUE TITLE
»name@missing domain« in draft »to« field if you didn’t finish typing

### ISSUE THREAD

**Issue by jancborchardt** [nextcloud/mail#699]
### Steps to reproduce
1. Compose an email
2. Type in to whom you want to send it
3. Don’t finish, or don’t have them in your contacts

### Expected behaviour
Only the part you typed is saved, like »Clara«

### Actual behaviour
The »to« field has »Clara@missing_domain« as value, which looks like a very technical error.

Happens with latest master, and before too.

**Comment by ChristophWurst** [comment]
I'm assuming this is a requirement of the IMAP server. But possibly it's just the horde libs trying to fix the invalid address.

**Comment by StCyr** [comment]
In `AccountsController.php`, function draft() calls ` NewMessageData::fromRequest($account, $to, $cc, $bcc, $subject, $body, []);`

which in turns calls `AddressList::parse()` for each of the $to, $ccList, and $bccList arguments

This function is the following:

```
        public static function parse($str) {
                $hordeList = new Horde_Mail_Rfc822_List($str);
                return self::fromHorde($hordeList);
        }
```

The function `fromHorde()` seems to highlight the problem:

```
        public static function fromHorde(Horde_Mail_Rfc822_List $hordeList) {
                $addresses = array_map(function(Horde_Mail_Rfc822_Address $addr) {
                        return new Address($addr->personal, $addr->bare_address);
                }, array_filter(iterator_to_array($hordeList), function(Horde_Mail_Rfc822_Object $obj) {
                                // TODO: how to handle non-addresses? This doesn't seem right …
                                return $obj instanceof Horde_Mail_Rfc822_Address;
                        }));
                return new AddressList($addresses);
        }
```

**Comment by jancborchardt** [comment]
@StCyr good find! Do you want to submit a pull request with the fix? You can ask here if you need any help. :)

**Comment by StCyr** [comment]
It turns out the draft is saved properly on the remove IMAP server (ie: If I save the draft and then use my email provider's webmail to look at the draft, I can see its "To" field without the "@missing_domain" part added yet).

So, the problem must occurs later, somewhere when the email is retrieved from the IMAP server.

I'm trying to debug the issue but for some reason the logger doesn't seem to be working in MessageController here (I can't see any logs from this class, though I've sucessfully added some logs  in the mailTransmission service)....

**Comment by jancborchardt** [comment]
@nextcloud/mail can someone help @StCyr here? :)

**Comment by StCyr** [comment]
All I need for now is to be able to see the logs from the MessageController class.

Can someone at least confirm that the logger doesn't work for him also in this class?

**Comment by ChristophWurst** [comment]
Please be more precise on "does not work". Does it throw an error? Does it do just nothing? In general the logger should work everywhere. When you don't get any output the code is either never run or your log level is set too high.

In most cases it's worth spending an hour on setting up xdebug. The quality of debugging is a lot higher once it's up and running and you'll more easily find and identify bugs :wink:

**Comment by StCyr** [comment]
thanks for the answer @ChristophWurst 

As I said earlier, I can't see any logs from the MessageController class, though my loglevel is set to 1 and I can see logs from mailTransmission.

Here's an example of the logs I've since I set loglevel=1 yesterday:

```
Jun 11 16:53:27 vps612142 Nextcloud[5036]: {mail} MailTransmission->saveDraft(): imapMessage->getTo()
Jun 11 16:53:27 vps612142 Nextcloud[5036]: {mail} Array
Jun 11 16:53:27 vps612142 Nextcloud[5036]: (
Jun 11 16:53:27 vps612142 Nextcloud[5036]:     [0] => Array
Jun 11 16:53:27 vps612142 Nextcloud[5036]:         (
Jun 11 16:53:27 vps612142 Nextcloud[5036]:             [label] => cyrtest
Jun 11 16:53:27 vps612142 Nextcloud[5036]:             [email] => cyrtest
Jun 11 16:53:27 vps612142 Nextcloud[5036]:         )
Jun 11 16:53:27 vps612142 Nextcloud[5036]:
Jun 11 16:53:27 vps612142 Nextcloud[5036]: )
Jun 11 16:53:27 vps612142 Nextcloud[5036]:
Jun 11 17:08:44 vps612142 Nextcloud[5326]: {mail} Updating draft <759> in account <1>
Jun 11 17:08:44 vps612142 Nextcloud[5326]: {mail} messageData->to:
Jun 11 17:08:44 vps612142 Nextcloud[5326]: {mail} Array
Jun 11 17:08:44 vps612142 Nextcloud[5326]: (
Jun 11 17:08:44 vps612142 Nextcloud[5326]:     [0] => Array
Jun 11 17:08:44 vps612142 Nextcloud[5326]:         (
Jun 11 17:08:44 vps612142 Nextcloud[5326]:             [label] => testme@missing_domain
Jun 11 17:08:44 vps612142 Nextcloud[5326]:             [email] => testme@missing_domain
Jun 11 17:08:44 vps612142 Nextcloud[5326]:         )
Jun 11 17:08:44 vps612142 Nextcloud[5326]:
Jun 11 17:08:44 vps612142 Nextcloud[5326]: )
Jun 11 17:08:44 vps612142 Nextcloud[5326]:
Jun 11 17:08:44 vps612142 Nextcloud[5326]: {mail} MailTransmission->saveDraft(): imapMessage->getTo()
Jun 11 17:08:44 vps612142 Nextcloud[5326]: {mail} Array
Jun 11 17:08:44 vps612142 Nextcloud[5326]: (
Jun 11 17:08:44 vps612142 Nextcloud[5326]:     [0] => Array
Jun 11 17:08:44 vps612142 Nextcloud[5326]:         (
Jun 11 17:08:44 vps612142 Nextcloud[5326]:             [label] => testme@missing_domain
Jun 11 17:08:44 vps612142 Nextcloud[5326]:             [email] => testme@missing_domain
Jun 11 17:08:44 vps612142 Nextcloud[5326]:         )
Jun 11 17:08:44 vps612142 Nextcloud[5326]:
Jun 11 17:08:44 vps612142 Nextcloud[5326]: )
Jun 11 17:08:44 vps612142 Nextcloud[5326]:
Jun 11 20:30:50 vps612142 Nextcloud[8536]: {cli} Memcache \OC\Memcache\APCu not available for local cache
Jun 11 20:30:50 vps612142 Nextcloud[8536]: {cli} Memcache \OC\Memcache\APCu not available for distributed cache
Jun 11 20:31:49 vps612142 Nextcloud[8565]: {cli} Memcache \OC\Memcache\APCu not available for local cache
Jun 11 20:31:49 vps612142 Nextcloud[8565]: {cli} Memcache \OC\Memcache\APCu not available for distributed cache
Jun 11 22:00:22 vps612142 Nextcloud[5851]: {core} Trusted domain error. "107.170.197.38" tried to access using "a.b.c.d" as host.
Jun 12 03:57:33 vps612142 Nextcloud[5851]: {core} Trusted domain error. "184.105.247.252" tried to access using "a.b.c.d" as host.
Jun 12 07:00:16 vps612142 Nextcloud[7922]: {core} Trusted domain error. "71.6.232.7" tried to access using "a.b.c.d" as host.
Jun 12 09:02:29 vps612142 Nextcloud[5851]: {mail} Message moved to trash: 1936 from mailbox INBOX
Jun 12 09:02:34 vps612142 Nextcloud[7922]: {mail} Message moved to trash: 1937 from mailbox INBOX
Jun 12 09:27:27 vps612142 Nextcloud[6041]: {core} Trusted domain error. "138.246.253.5" tried to access using "acme.org" as host.
```

Not much uh?

I must say that I'm using syslog for logging so these may get lost somewhere. I must investigate this.

WRT xdebug, I'm not sure I'm willing to install it on my production server...

Cyrille

**Comment by StCyr** [comment]
Ok, sorry for the noise: loglevel=1 was just not enough :-(

**Comment by StCyr** [comment]
After further analysis, I don't think the addition of the "@missing_domain" part is a real problem.

Indeed, once an input (a tag in vue-multiselect langage) has been selected it cannot be edited further. It therefore doesn't make much difference that this tag is in the form "foobar" or "foobar@missing_domain"; In both cases sending the email to this recipient will fail.

What I think would be good to do would be to implement some pre-send validation: When the user press the "Send" button, mail validates all recipients before actually sending the email. 

Idealy this validation would highlight any invalid recipients.

What do you think?

**Comment by ChristophWurst** [comment]
Yeah, that wouldn't hurt in general

**Comment by jancborchardt** [comment]
This seems to not be an issue anymore with the new select2? At least I can’t reproduce, closing hence.
