### ISSUE TITLE
Delete draft(s) after message has been sent.

### ISSUE THREAD

**Issue by thstyl2000** [nextcloud/mail#7008]
### Is your feature request related to a problem? Please describe.

Filled Drafts folder with many unused messages.

### Describe the solution you'd like

At least a couple of clients I am using (one of them AquaMail on android) do that. The drafts folder is then not cluttered.

### Describe alternatives you've considered

Manually deleting drafts....

**Comment by st3iny** [comment]
That should work but there seems to be a bug somewhere.

**Comment by ChristophWurst** [comment]
I'm sure this is already covered by https://github.com/nextcloud/mail/issues/4768

**Comment by thstyl2000** [comment]
Ok, closing as duplicate then...?
