### ISSUE TITLE
Uploading attachments is broken

### ISSUE THREAD

**Issue by st3iny** [nextcloud/mail#7009]
### Steps to reproduce

1. Compose a new message.
2. Try to add an attachment via ... -> "Upload attachment"

### Expected behavior

A file picker shows.

### Actual behavior

Nothing happens.

### Mail app version

main

**Comment by df911** [comment]
Hello,
Same problem and no log are generated.

**Comment by ChristophWurst** [comment]
@df911 version?

**Comment by ChristophWurst** [comment]
This missing file picker was fixed with https://github.com/nextcloud/mail/commit/970bcc409e60f4abc6d0bf628cd5d60cd8995011.
