### ISSUE TITLE
ThreadEnvelope buttons overflow horizontally

### ISSUE THREAD

**Issue by st3iny** [nextcloud/mail#7010]
### Steps to reproduce

1. Have a reasonably small horizontal resolution (e.g. portrait mode).
2. Open a thread.
3. Observe the header of an envelope.

### Expected behavior

The header should be truncated or collapsed.

### Actual behavior

The buttons on the right overflow the container of the envelope. Have a look at the three dot menu.

![Screenshot 2022-08-16 at 15-45-44 Mail - Nextcloud](https://user-images.githubusercontent.com/1479486/184895736-409dbd45-41a9-409c-ae8f-c9517ad6ae91.png)

### Mail app version

main

**Comment by ChristophWurst** [comment]
The alignment of sender, date and buttons is also not great

**Comment by GretaD** [comment]
this happens because as you can see there is no space so when the timestamp reached max-width of send, pushes everything else. As a quick fix im thinking changing timestamp whitespace into prewrap and it will be shown smth like this: 
![Screenshot from 2022-08-16 16-25-55](https://user-images.githubusercontent.com/12728974/184904585-5fbed88f-68b3-4baf-8bb6-ac15995d14f3.png)

**Comment by jancborchardt** [comment]
If the space is getting low, we can:
- Put the icons back in the overflow actions menu (either one by one or all except "reply all" at a specific breakpoint)
- Use the short date format like we do in the AppContentList (also at a breakpoint)

Breaking the text doesn't look good, so let's not do that.

**Comment by GretaD** [comment]
> If the space is getting low, we can:
> 
> * Put the icons back in the overflow actions menu (either one by one or all except "reply all" at a specific breakpoint)
> * Use the short date format like we do in the AppContentList (also at a breakpoint)
> 
> Breaking the text doesn't look good, so let's not do that.

i went with your second proposal :)
