### ISSUE TITLE
Add shortcut to archive email

### ISSUE THREAD

**Issue by meichthys** [nextcloud/mail#7027]
### Is your feature request related to a problem? Please describe.

Archiving an email is not easy.

### Describe the solution you'd like

Currently the only way to archive an email is to use the `...` context menu and then choose move message, then choose the Archive folder.

Ideally we should have a one click archive button or a keyboard shortcut. Thunderbird for example uses the `a` key to archive.

### Describe alternatives you've considered

Drag and dropping emails to the archive folder works on desktop but doesn't work great on mobile or touch-based devices.

**Comment by ChristophWurst** [comment]
Duplicate of https://github.com/nextcloud/mail/issues/22
