### ISSUE TITLE
Handle appointment invitations

### ISSUE THREAD

**Issue by 8sd** [nextcloud/mail#703]
### Steps to reproduce
1. send invitation to nextloud
2. the app recognizes that the mail is an invitation (shows details of appointment in special form)

### Expected behavior
There should be three buttons **accept**, **tentative**, and  **no -accept** (I don't no the correct name)
After pressing **accept** or **tentative** the appointment should be shown in the designated calendar

### Actual behavior
you cannot interact with the invitation

## Server configuration detail

**Operating system:** Linux 3.16.0-4-amd64 #1 SMP Debian 3.16.43-2 (2017-04-30) x86_64

**Webserver:** nginx/1.13.8 (fpm-fcgi)

**Database:** mysql 10.2.12

**PHP version:** 7.0.27-0+deb9u1
Modules loaded: Core, date, libxml, openssl, pcre, zlib, filter, hash, Reflection, SPL, session, standard, cgi-fcgi, mysqlnd, PDO, xml, calendar, ctype, curl, dom, mbstring, fileinfo, ftp, gd, gettext, iconv, intl, json, exif, mcrypt, mysqli, pdo_mysql, Phar, posix, readline, shmop, SimpleXML, sockets, sysvmsg, sysvsem, sysvshm, tokenizer, wddx, xmlreader, xmlwriter, xsl, zip, Zend OPcache

**Nextcloud version:** 12.0.0 - 12.0.0.29

**Updated from an older Nextcloud/ownCloud or fresh install:** 

**Where did you install Nextcloud from:** unknown

<details><summary>Signing status</summary>

Array
</details>

<details><summary>List of activated apps</summary>

```
Enabled:
 - activity: 2.5.2
 - bruteforcesettings: 1.0.3
 - calendar: 1.5.7
 - checksum: 0.3.5
 - comments: 1.2.0
 - contacts: 2.0.1
 - dav: 1.3.0
 - deck: 0.3.0
 - drawio: 0.8.8
 - federatedfilesharing: 1.2.0
 - federation: 1.2.0
 - files: 1.7.2
 - files_markdown: 2.0.1
 - files_pdfviewer: 1.1.1
 - files_sharing: 1.4.0
 - files_texteditor: 2.4.1
 - files_trashbin: 1.2.0
 - files_versions: 1.5.0
 - files_videoplayer: 1.1.0
 - firstrunwizard: 2.1
 - gallery: 17.0.0
 - issuetemplate: 0.3.0
 - logreader: 2.0.0
 - lookup_server_connector: 1.0.0
 - mail: 0.7.7
 - nextcloud_announcements: 1.1
 - notifications: 2.0.0
 - oauth2: 1.0.5
 - ownpad: 0.5.10
 - password_policy: 1.2.2
 - polls: 0.8.0
 - provisioning_api: 1.2.0
 - richdocuments: 1.12.40
 - serverinfo: 1.2.0
 - sharebymail: 1.2.0
 - survey_client: 1.0.0
 - systemtags: 1.2.0
 - theming: 1.3.0
 - twofactor_backupcodes: 1.1.1
 - unsplash: 1.0.5
 - updatenotification: 1.2.0
 - workflowengine: 1.2.0
Disabled:
 - admin_audit
 - encryption
 - files_external
 - user_external
 - user_ldap

```
</details>

<details><summary>Configuration (config/config.php)</summary>

```
{
    "instanceid": "ocz1zntnete4",
    "passwordsalt": "***REMOVED SENSITIVE VALUE***",
    "secret": "***REMOVED SENSITIVE VALUE***",
    "trusted_domains": [
        "…",
        "…"
    ],
    "datadirectory": "…",
    "overwrite.cli.url": "…",
    "dbtype": "mysql",
    "version": "12.0.0.29",
    "dbname": "nextcloud",
    "dbhost": "localhost",
    "dbport": "",
    "dbtableprefix": "oc_",
    "mysql.utf8mb4": true,
    "dbuser": "***REMOVED SENSITIVE VALUE***",
    "dbpassword": "***REMOVED SENSITIVE VALUE***",
    "installed": true,
    "maintenance": false,
    "mail_smtpmode": "smtp",
    "mail_smtpauthtype": "LOGIN",
    "mail_smtpsecure": "ssl",
    "mail_from_address": "nexcloud",
    "mail_smtpauth": 1,
    "mail_domain": "…",
    "mail_smtphost": "smtp.mailbox.org",
    "mail_smtpport": "465",
    "mail_smtpname": "***REMOVED SENSITIVE VALUE***",
    "mail_smtppassword": "***REMOVED SENSITIVE VALUE***"
}
```
</details>

**Are you using external storage, if yes which one:** local/smb/sftp/...

**Are you using encryption:** no

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...

## Client configuration

**Browser:** Mozilla/5.0 (X11; Linux x86_64; rv:57.0) Gecko/20100101 Firefox/57.0

**Comment by dudasfau** [comment]
This is no duplicate, the mail is displayed properly.
I want to add the invitation to my cal.

The issue #160 only mentions the portrayal of inivations from outlook.

**Comment by ChristophWurst** [comment]
Sorry, didn't read the full detail. Re-opening.

**Comment by ChristophWurst** [comment]
> It could be very cool to have a way to add ics to Calendar app from Mail app.

That is already supported but there seem to be cases where the mime of the ics is not detected correctly. If you have a file to reproduce the issue, please create a new ticket and share the ics with us. Thanks.

**Comment by 8sd** [comment]
So I just made an invitation.

It's displayed this way:

![untitled](https://user-images.githubusercontent.com/32878822/40162878-8782b27c-59b5-11e8-894d-5d0a5bb9bb24.png)

Here is the invite (I anonymized it)
[invite.tar.gz](https://github.com/nextcloud/mail/files/2012088/invite.tar.gz)

It looks like the file was recognized but I cannot add it to a calendar…

**Comment by SpamReceiver** [comment]
+1 from me!

**Comment by litec-gole** [comment]
> > It could be very cool to have a way to add ics to Calendar app from Mail app.
> 
> That is already supported but there seem to be cases where the mime of the ics is not detected correctly. If you have a file to reproduce the issue, please create a new ticket and share the ics with us. Thanks.

Hi, 

i thought this feature is not implemented because I never got any accept or decline buttons when I received an invitation. After i read this entry I tried to send me invites from gmail, office365 and nextcloud. But never I saw the accept button, just the attachment.  Is there anything I do wrong?

**Comment by ChristophWurst** [comment]
you're right. nobody implemented this feature :man_shrugging:

**Comment by ToeJet** [comment]
Is it being planned as a new feature?

**Comment by ChristophWurst** [comment]
planned in a sense that we want to have this but not that it's on any roadmap or that I could give an ETA

**Comment by ToeJet** [comment]
Thanks for the quick reply.    Depending on the invite,  it is usually listed as an attachment such as .ics.  Is there a quick way that the Nextcloud Mail could use the association to launch the associated handler which would process adding it.  Similar to the way file manager can open a doc with Collabra-Office.   I am assuming the link just launches with the associated nextcloud app but does not have to actually understand the link.   Possibly a white list for allow extensions to launch associations?

**Comment by ChristophWurst** [comment]
That would be a possibility, yes, but we don't have this mechanism right know I'm afraid.

**Comment by litec-gole** [comment]
Hi, thanks for the reply! I am sorry to hear, that this is not on any roadmap. Otherwise I could finally dump all those workarounds.  How does a feature like this get on a roadmap?

**Comment by ChristophWurst** [comment]
> How does a feature like this get on a roadmap?

Usually if someone contributes the necessary code or [by customer demand](https://nextcloud.com/enterprise/)

**Comment by litec-gole** [comment]
Okey, thanks. Lets hope the German government has the demand ;)! Unfortunately my own programming skills won't do any good here.

**Comment by Luncheon3462** [comment]
@ChristophWurst @miaulalala @st3iny, please help get this fixed.  When Office 365 sends calendar invitations, the snappymail nextcloud app by @the-djmaze handles them perfectly.   They appear in the email message and can be added to a nextcloud calendar with one-click.   Maybe this code that @the-djmaze mentioned will work?  https://github.com/the-djmaze/snappymail/blob/fffc04499875531bd3dd626d01baaf7a86452cd3/plugins/nextcloud/js/message.js#L111-L179

**Comment by ChristophWurst** [comment]
@Luncheon3462 sounds good. Feel free to bring the code over to this app :+1:

**Comment by Luncheon3462** [comment]
@ChristophWurst I'm sure your comment isn't meant to be snark.  I don't code, but am willing to support financially.  Please tell me your preferred method for bug bounty and a suggested price.

**Comment by ChristophWurst** [comment]
I can't take any bounties. If someone wants to code this we can give pointers.

If you run a business and this is important to you: https://nextcloud.com/enterprise/

**Comment by miaulalala** [comment]
We added this with https://github.com/nextcloud/mail/pull/6956

**Comment by Luncheon3462** [comment]
@miaulalala does this mean that when someone uses Microsoft Office 365 to send a calendar invite to an individual using nextcloud mail, that the nextcloud user will be able to interact with that invite directly and add it to their calendar with one click?

**Comment by keunes** [comment]
Thanks @ChristophWurst @miaulalala! Which Mail app version do we need to have minimally to benefit from this? I couldn't really identify the version number from the PR, and would like to be sure so that I'm on the right version before testing (and potentially creating invalid bug reports).

**Comment by miaulalala** [comment]
> Thanks @ChristophWurst @miaulalala, great to hear this is now implemented! Which Mail app version do we need to have minimally to benefit from this? I couldn't really identify the version number from the PR, and would like to be sure so that I'm on the right version before testing (and potentially creating invalid bug reports).

Try it with with 3.5.x or if you're up for prereleases, 3.6.0.

**Comment by miaulalala** [comment]
> @miaulalala does this mean that when someone uses Microsoft Office 365 to send a calendar invite to an individual using nextcloud mail, that the nextcloud user will be able to interact with that invite directly and add it to their calendar with one click?

Already thumbed up your previous comment. Please stop spamming.

**Comment by Luncheon3462** [comment]
I'm not trying to spam.  please be patient with me.    Does a thumbs up emoji mean that the answer to my question is 'yes'?

**Comment by Haui1112** [comment]
I have the same issue, even on Mail 3.7.2 and Snappymail 2.36.4. I'm testing Apple <> Nextcloud and Outlook <> Nextcloud calendar invites per email. Apple works oob, both ways but NC Mail an Snappymail wont let me accept invites from Outlook. 

Should I open another issue or am I doing something wrong?

## Screenshots
![Screenshot_20240711_105355](https://github.com/nextcloud/mail/assets/109665179/31e8c9c1-2261-430b-ab66-9d32ebc5467f)
![Screenshot_20240711_105304](https://github.com/nextcloud/mail/assets/109665179/785e1b65-eca2-40d2-8ac9-bc127a300b4b)

## Message body
```
Delivered-To: ***

Received: by 2002:a59:ca2d:0:b0:483:957b:2685 with SMTP id u13csp762421vqt;

        Wed, 10 Jul 2024 21:49:41 -0700 (PDT)

X-***-Smtp-Source: AGHT+IFo+5LQ6Mwa3JOvOE8kZLAeFyUtAe1tJVSvCLpsKLRCuOs+U/osTwRl6aAhzDBMubIg28Vv

X-Received: by 2002:a7b:c38f:0:b0:426:62df:bdf0 with SMTP id 5b1f17b1804b1-426707d8a07mr51732485e9.10.1720673381335;

        Wed, 10 Jul 2024 21:49:41 -0700 (PDT)

ARC-Seal: i=1; a=rsa-sha256; t=1720673381; cv=none;

        d=***.com; s=arc-20160816;

        b=GS22OtHYeFlWpaxeiGZLFC3Yc3Wu53ev9sIzvnk9gHwitB2NyNVM9+8rqX2vclD/+m

         GikSrM9aCv21lCtbJikV8v9MMb3aNS/QKl2bsvH4jDMcP1bO/QWVWaaubCPzMp7JLBNG

         UZs6cUqCvW5ZcieiF1GXyx/o8xq8ML++2c9NX8K/2TCDsJZThp6iSBnwuW0MJDgVx2Bb

         2HzWZuY0ArvDjebz3/fzk3+ioCgBQIfl4//SdQ3XpUc8lRa+plEE8F/hHyi2GmZJbg4D

         sKkLgYSspOJoZCG3W7R0JvaYycvvsAHKxudC4Srd031LfuK8qDw6RNh9/HyhAOC0ZqNe

         xeFw==

ARC-Message-Signature: i=1; a=rsa-sha256; c=relaxed/relaxed; d=***.com; s=arc-20160816;

        h=ui-outboundreport:content-language:thread-index

         :content-transfer-encoding:mime-version:message-id:date:subject:to

         :from:dkim-signature;

        bh=hbKIVf7/5xSmTZ7Ak9ohDJQ4lznod6WEFoYdxjQktk0=;

        fh=xkPyWO5G5yo56aYoZ5VFoSj5+7geIPrbU+aXAtPjZLU=;

        b=CEkssZZEYyoD57PgEJvsTqcxJ0jY+euYNJRTZ4eP444lzZWDKnxyMK0Xis5HvB7kvq

         E17rtB1n3fBuowgAO/mjM9eftzievXA/8x7gSgeQC4odB5LWWurYAZobJgNs2WEQDcFQ

         hvj5vFA+Uvc0gOW2hyODjJI6/RwwnzaH6fnrDWTlwp5i+xzIG8BzwYGLgq+0RlUOQiNe

         ljKVTrmxieMuqD9Myx/CB8gcnxYMgoC0cenZUVAd0zXTewSyA0ODi7ZBLZdOgLK/TUlP

         KiEqY+SHo3ReybrXQSs9MFG2mPV2OkLnwrfoHESFjagYBG8/RQ9gFk5JtrmXUzYZl0PO

         jJdA==;

        dara=***.com

ARC-Authentication-Results: i=1; mx.***.com;

       dkim=pass header.i=@*** header.s=s1-ionos header.b=Icjj46C1;

       spf=pass (***.com: domain of *** designates *** as permitted sender) smtp.mailfrom=***

Return-Path: <***>

Received: from mout.***.de (mout.***.de. [***])

        by mx.***.com with ESMTPS id 5b1f17b1804b1-4266cad792fsi42447745e***.***

        for <***>

        (version=TLS1_3 cipher=TLS_AES_256_GCM_SHA384 bits=256/256);

        Wed, 10 Jul 2024 21:49:41 -0700 (PDT)

Received-SPF: pass (***.com: domain of *** designates *** as permitted sender) client-ip=***;

Authentication-Results: mx.***.com;

       dkim=pass header.i=@*** header.s=s1-ionos header.b=Icjj46C1;

       spf=pass (***.com: domain of *** designates *** as permitted sender) smtp.mailfrom=***

DKIM-Signature: v=1; a=rsa-sha256; c=relaxed/relaxed; d=***;

	s=s1-ionos; t=1720673380; x=1721278180; i=***;

	bh=hbKIVf7/5xSmTZ7Ak9ohDJQ4lznod6WEFoYdxjQktk0=;

	h=X-UI-Sender-Class:From:To:Subject:Date:Message-ID:MIME-Version:

	 Content-Type:Content-Transfer-Encoding:cc:

	 content-transfer-encoding:content-type:date:from:message-id:

	 mime-version:reply-to:subject:to;

	b=Icjj46C1MQxMO8eQAQF3pmGA4j4ViIP571T5GACa1hg3Zsfpa6LDa3OTd/PXho1W

	 G1xT9b9M+1SrlR/0ev0I1w1d59GBq4CXTdM0wQFUnUXCDJX7LBs5ZMC9nC1EXu3bI

	 gjAL6ySpZu7CEEokpFk5YEzsjXq7Nr/7o6caHT/1Z/pvzfk2jnIvKcw2+YwDxB96T

	 EKQaTxdoqiZHZ5PVW1rbDH5/OC/X1VRufXAcO2SyyWIE1kqZAvdAyJwWV1JxxFNhw

	 QBUWPgn8/iuOj0VJ6Ql8QrarNJAlazVHmcLxnLGnwwAkxQtEPLgdMfO5XZZ9VY7mB

	 vOzWzoFlf0qyOyfs6w==

X-UI-Sender-Class: 55c96926-9e95-11ee-ae09-1f7a4046a0f6

Received: from *** ([***]) by mrelayeu.***.de

 (mreue109 [***]) with ESMTPSA (Nemesis) id

 1N49Yt-1sIjLB2X1l-00zkml for <***>; Thu, 11 Jul 2024

 06:49:40 +0200

From: <***>

To: <***>

Subject: =?UTF-8?Q?Kompatibilit=C3=A4tstest_:=29?=

Date: Thu, 11 Jul 2024 06:49:40 +0200

Message-ID: <001101dad34d$bd80ac40$388204c0$@***>

MIME-Version: 1.0

Content-Type: text/calendar; method=REQUEST;

	charset="UTF-8"

Content-Transfer-Encoding: quoted-printable

X-Mailer: Microsoft Outlook 16.0

Thread-Index: AdrTTbWbN6xQMlGEQoi7p2SIoHI9mAAAAdyw

Content-Language: de

X-Provags-ID: V03:K1:jfXyWg17UicZcqLW5+PaP+XQGblZE5AuqUigfWSOyYK+NBcCc5m

 AEJkQInbjmzltmiOi3+i0X9fOzt9POzf54qbCCpxnwAhu3s95rf15trxGN8P6jGck+5JhFu

 Y30pNlqP5qhjIHmilr27hBTSw1GyvyiskD0iNaL8M9wAw7U48IJ17lXvkW/5sIApR04pDZa

 RbvmxCOvTAE1jjQ815f/Q==

X-Spam-Flag: NO

UI-OutboundReport: notjunk:1;M01:P0:Ps1Nl7LUPIk=;+PLcg58GCwGd2WSPJfYLgOxofs6

 bBD44wdzqAHxLS5Ktu82tTIW1h8uVQRLDIjAp9j0rw8Ngt/OrwGbTn+xjV+LIfyA5ocIDx3mu

 LdHDS3eKiFohLCU7/J5WEf978nGdbGawTYUgWUAvwVmjW9ipoWhVOo85LNHVJl3WVwGgf3wTg

 fX6C91wk7ab2aNycOKmLfM7VSwkGw1nqaDeb4IFkyzSDh4Rm40bNHNBXyHncMriIuyBBsaDux

 kQx1cgEKznZVQSPWbu097oCxABHgSapfJaDqFM/IF+5QnlZUnLrIJ+hhil6/Wvp3vgKeqMvv/

 tk5eqpe6m8hTQ8RhzTetSQ8ZrqL143szhTOpN5IXgqA7sR+M973upYuciYKsAIzuEGi7ZiwjF

 Z/mPODjiskASMRkcMo5OcJtJy7S9q8XIq3SHZKLRyo0z1eR3cbYtkHgEPo4fEiRWG7lva5m1Z

 C3iLC90/i6E1MiDOgVBZ5d8efTn1MWFGuAy4jXptgOYW1HD+pVt8Y4II9ypyVFNGBpWWo8TmH

 yvTA+8UaY+NvkPYXouhsEBH+ca/PGXP9mEkqgsSSA4NjTgDxTkAkkEn3yWUDAlS8pKc5p/tf5

 G3bPh+p3cAc0jJFcE1N3UBzCoxYU5Ti6URRYhbhCplCbbzIFSWRIA/EehGrZkFCU+M6wXGzJU

 FI5505yxzA2KjcCEfOeL+5vVDda56jc/NESlm0aZR0vPmkYGS2TWkCKLYFwJu7YKJzvZwgi2o

 sBkBy+/ol4luBVckDUSE3gwnKHB8qyouXat+bngTgksqzwtdksploSYkatAueE9sSICRovOnQ

 HYiTEX1spGepmY/QXKIxaGStEt59jrYmrYk5NdICn/qyc=



BEGIN:VCALENDAR

PRODID:-//Microsoft Corporation//Outlook 16.0 MIMEDIR//EN

VERSION:2.0

METHOD:REQUEST

X-MS-OLK-FORCEINSPECTOROPEN:TRUE

BEGIN:VTIMEZONE

TZID:W. Europe Standard Time

BEGIN:STANDARD

DTSTART:16011028T030000

RRULE:FREQ=3DYEARLY;BYDAY=3D-1SU;BYMONTH=3D10

TZOFFSETFROM:+0200

TZOFFSETTO:+0100

END:STANDARD

BEGIN:DAYLIGHT

DTSTART:16010325T020000

RRULE:FREQ=3DYEARLY;BYDAY=3D-1SU;BYMONTH=3D3

TZOFFSETFROM:+0100

TZOFFSETTO:+0200

END:DAYLIGHT

END:VTIMEZONE

BEGIN:VEVENT

ATTENDEE;CN=3D***;RSVP=3DTRUE:mailto:***@g=

mail.

	com

CLASS:PUBLIC

CREATED:20240711T044939Z

DESCRIPTION: \n\n

DTEND;TZID=3D"W. Europe Standard Time":20240712T113000

DTSTAMP:20240711T044939Z

DTSTART;TZID=3D"W. Europe Standard Time":20240712T110000

LAST-MODIFIED:20240711T044939Z

ORGANIZER;CN=3D***:mailto:***

PRIORITY:5

SEQUENCE:0

SUMMARY;LANGUAGE=3Dde:Kompatibilit=C3=A4tstest :)

TRANSP:OPAQUE

UID:040000008200E00074C5B7101A82E00800000000E0D295805ED3DA0100000000000000=

0

	010000000801B2BC5185A6046B5368309E7BDC80F

X-ALT-DESC;FMTTYPE=3Dtext/html:<html xmlns:v=3D"urn:schemas-microsoft-com:=

vml"

	xmlns:o=3D"urn:schemas-microsoft-com:office:office" xmlns:w=3D"urn:schema=

s-mic

	rosoft-com:office:word" xmlns:m=3D"http://schemas.microsoft.com/office/20=

04/

	12/omml" xmlns=3D"http://www.w3.org/TR/REC-html40"><head><meta http-equiv=

=3DCo

	ntent-Type content=3D"text/html\; charset=3Diso-8859-1"><meta name=3DGene=

rator c

	ontent=3D"Microsoft Word 15 (filtered medium)"><style><!--\n/* Font Defin=

iti

	ons */\n@font-face\n	{font-family:"Cambria Math"\;\n	panose-1:2 4 5 3 5 4

	6 3 2 4\;}\n@font-face\n	{font-family:Calibri\;\n	panose-1:2 15 5 2 2 2 4

	3 2 4\;}\n/* Style Definitions */\np.MsoNormal\, li.MsoNormal\, div.MsoNo=

r

	mal\n	{margin:0cm\;\n	margin-bottom:.0001pt\;\n	font-size:11.0pt\;\n	font=

-

	family:"Calibri"\,sans-serif\;\n	mso-fareast-language:EN-US\;}\na:link\, =

s

	pan.MsoHyperlink\n	{mso-style-priority:99\;\n	color:#0563C1\;\n	text-deco=

r

	ation:underline\;}\na:visited\, span.MsoHyperlinkFollowed\n	{mso-style-pr=

i

	ority:99\;\n	color:#954F72\;\n	text-decoration:underline\;}\np.msonormal0=

\

	, li.msonormal0\, div.msonormal0\n	{mso-style-name:msonormal\;\n	mso-marg=

i

	n-top-alt:auto\;\n	margin-right:0cm\;\n	mso-margin-bottom-alt:auto\;\n	ma=

r

	gin-left:0cm\;\n	font-size:11.0pt\;\n	font-family:"Calibri"\,sans-serif\;=

}

	\nspan.E-MailFormatvorlage18\n	{mso-style-type:personal\;\n	font-family:"=

C

	alibri"\,sans-serif\;\n	color:windowtext\;}\nspan.E-MailFormatvorlage19\n

	{mso-style-type:personal-compose\;}\n.MsoChpDefault\n	{mso-style-type:exp=

o

	rt-only\;\n	font-size:10.0pt\;}\n@page WordSection1\n	{size:612.0pt 792.0=

p

	t\;\n	margin:70.85pt 70.85pt 2.0cm 70.85pt\;}\ndiv.WordSection1\n	{page:W=

o

	rdSection1\;}\n--></style><!--[if gte mso 9]><xml>\n<o:shapedefaults v:ex=

t

	=3D"edit" spidmax=3D"1026" />\n</xml><![endif]--><!--[if gte mso 9]><xml>=

\n<o:

	shapelayout v:ext=3D"edit">\n<o:idmap v:ext=3D"edit" data=3D"1" />\n</o:s=

hapelay

	out></xml><![endif]--></head><body lang=3DDE link=3D"#0563C1" vlink=3D"#9=

54F72">

	<div class=3DWordSection1><p class=3DMsoNormal><o:p>&nbsp\;</o:p></p></di=

v></b

	ody></html>

X-MICROSOFT-CDO-BUSYSTATUS:TENTATIVE

X-MICROSOFT-CDO-IMPORTANCE:1

X-MICROSOFT-CDO-INTENDEDSTATUS:BUSY

X-MICROSOFT-DISALLOW-COUNTER:FALSE

X-MS-OLK-AUTOSTARTCHECK:FALSE

X-MS-OLK-CONFTYPE:0

BEGIN:VALARM

TRIGGER:-PT15M

ACTION:DISPLAY

DESCRIPTION:Reminder

END:VALARM

END:VEVENT

END:VCALENDAR
```

**Comment by Luncheon3462** [comment]
Still not addressed.   This is a huge barrier to nextcloud adoption by business.  Microsoft is largest email and calendar provider in world, yet Nextcloud can’t handle invites from it.
