### ISSUE TITLE
Move Account Settings close icon (X) to modal.

### ISSUE THREAD

**Issue by meichthys** [nextcloud/mail#7068]
### Is your feature request related to a problem? Please describe.

Currently when using nextcloud in full screen mode (or on wide screens), the close icon is at the top right of the screen (by the user profile icon). This is not close to the account settings modal when the screen is wide:
![image](https://user-images.githubusercontent.com/10717998/186155010-7b538628-f147-4ff8-ba46-dd55233c7e1a.png)

### Describe the solution you'd like

The close icon would probably be better suited if it was inside the modal. Something like:
![image](https://user-images.githubusercontent.com/10717998/186154815-b7128626-8ee1-41c6-94b1-65447d8cc029.png)

### Additional context

This isn't really an issue on small screens, but for desktop browsers the close icon can get lost being so far away from the modal it is supposed to be closing.

**Comment by ChristophWurst** [comment]
Done
