### ISSUE TITLE
Account settings close button does not work

### ISSUE THREAD

**Issue by kesselb** [nextcloud/mail#7074]
### Steps to reproduce

1. Open account settings
2. Click close button
3. ...

### Expected behavior

Account settings are closed

### Actual behavior

Nothing :disappointed: 

### Mail app version

6938b489823629ec0fefc05b23031969a0162b5a

**Comment by raimund-schluessler** [comment]
Maybe it was fixed with https://github.com/nextcloud/nextcloud-vue/pull/3066. An update to nextcloud/vue-6.0.0-beta.4 might solve it.

**Comment by ChristophWurst** [comment]
If it is the same bug as https://github.com/nextcloud/mail/pull/7071#issuecomment-1224472707 then no, unfortunately this is still a bug in beta4.

**Comment by GretaD** [comment]
> If it is the same bug as [#7071 (comment)](https://github.com/nextcloud/mail/pull/7071#issuecomment-1224472707) then no, unfortunately this is still a bug in beta4.

i can confirm its because of the update to nc/vuebeta4

**Comment by ChristophWurst** [comment]
It works now
