### ISSUE TITLE
Shortcut buttons have different lengths and look ugly 

### ISSUE THREAD

**Issue by marcoambrosini** [nextcloud/mail#7075]
### Steps to reproduce

1. Click envelope's 3 dot menu

### Expected behavior

The menu looks balanced and graceful 

### Actual behavior

The buttons have different lengths, and it can get much worse depending on the language selected

https://user-images.githubusercontent.com/26852655/186348555-3e6175dd-f124-4a66-ae1c-ac81d3a39319.mov

**Possible solutions:**
- Remove labels and delayed tooltips
- Use regular ActionButtons, maybe with a separator to make them stand out

**Comment by ChristophWurst** [comment]
Dup of https://github.com/nextcloud/mail/issues/6201?
