### ISSUE TITLE
Rework Draft Handling - Backend Part

### ISSUE THREAD

**Issue by miaulalala** [nextcloud/mail#7076]
Backend part of https://github.com/nextcloud/mail/issues/4768

**Comment by miaulalala** [comment]
Note: the Outbox Backend already handles drafts via an OutboxCreatedEvent that triggers the DeleteDraftListerner. Adjust this class to delete local and IMAP drafts.

**Comment by miaulalala** [comment]
Note: We do need a GET for the contents of a draft (unless we load all messages with their content?) something for the fontenders to tell me :)

**Comment by ChristophWurst** [comment]
> Note: We do need a GET for the contents of a draft (unless we load all messages with their content?) something for the fontenders to tell me :)

https://github.com/nextcloud/mail/issues/4768#issuecomment-1224352762. `MessageService.js::fetchMessage`.

**Comment by ChristophWurst** [comment]
## Leftovers

* [ ] T6

**Comment by ChristophWurst** [comment]
UC3 doesn't work apparently. Local drafts stay local draft forever, the background job does not move idle items to IMAP.
