### ISSUE TITLE
Rework Draft Handling - Frontend Part

### ISSUE THREAD

**Issue by miaulalala** [nextcloud/mail#7077]
Front-end part of https://github.com/nextcloud/mail/issues/4768

- [x] Requires https://github.com/nextcloud/mail/issues/7076

**Comment by ChristophWurst** [comment]
That was a misunderstanding. Local drafts are not visible to the user.

**Comment by ChristophWurst** [comment]
The todo above is only draft, we haven't discussed it yet. I'll spec out the feature when the backend is done.

**Comment by neeraj-nandan** [comment]
By when can we expect this issue to be resolved?

Please provide a date. It would be highly regarded.
