### ISSUE TITLE
New message modal close button overlapped by identify picker

### ISSUE THREAD

**Issue by jakobroehrl** [nextcloud/mail#7079]
### Steps to reproduce

New Mail has a circle

![image](https://user-images.githubusercontent.com/24530680/186584614-13af22c1-feba-4ba6-a0fd-b8f78bbcf9fd.png)

### Expected behavior

.

### Actual behavior

.

**Comment by GretaD** [comment]
related to your first point, yes we are aware and its already fixed, we will release it soon.

I cannot reproduce the second one, but i am having a look

**Comment by ChristophWurst** [comment]
The second one could be related to https://github.com/nextcloud/mail/pull/6715

**Comment by meichthys** [comment]
I'm using firefox as well but don't see number 2 either 🤷‍♂️

**Comment by jakobroehrl** [comment]
> I'm using firefox as well but don't see number 2 either 🤷‍♂️

It's a breeze dark problem, sorry.

**Comment by meichthys** [comment]
I'm not seeing this issue in 1.14.0-beta1

**Comment by ChristophWurst** [comment]
AFAIK this only happens with Nextcloud 25 and/or `@nextcloud/vue@7`. The v1.14 line uses nc/vue@6 and only works with Nextcloud 24 and lower.

**Comment by meichthys** [comment]
Hmm I'm still not seeing this after updating to NC 25 (beta4) and Mail  v2.0.0-beta.3
I do however see a white background around the compose button, but I think that's different.
![image](https://user-images.githubusercontent.com/10717998/188956836-7e4b025e-a043-4bc2-ad27-246bc4c1a1a8.png)
