### ISSUE TITLE
Tags imported from IMAP account have black text (Not easily visible in dark mode)

### ISSUE THREAD

**Issue by meichthys** [nextcloud/mail#7083]
### Steps to reproduce

1. Setup imap account
2. Wait for emails to be imported 
3. Tags will be imported from emails

### Expected behavior

Tags in "edit tags" dialog should be visible in dark mode.

### Actual behavior

Tags in "edit tags" dialog are hardly visible in dark mode:
Note:  Newly created tags in the dialog are fine, and tags displayed on the emails themselves are fine even if they are hard to see on the dialog

In Dialog:
![image](https://user-images.githubusercontent.com/10717998/186676754-4ad9c2cf-1688-4cae-91e5-e7632e354d6a.png)

On Email:
![image](https://user-images.githubusercontent.com/10717998/186676850-cff74615-17db-4cb9-80cf-a4ecc8667aa9.png)

### Mail app version

1.13.8

### Mailserver or service

Zoho (IMAP)

### Operating system

Nextcloud VM (Ubuntu?)

### PHP engine version

PHP 7.4

**Comment by ChristophWurst** [comment]
Pretty much a duplicate of https://github.com/nextcloud/mail/issues/5149, but with the dark theme :)

**Comment by meichthys** [comment]
Missed that one. Yes, probably the same issue. Closing this one for now.
