### ISSUE TITLE
New account form is not showing on main

### ISSUE THREAD

**Issue by nickvergessen** [nextcloud/mail#7086]
### Steps to reproduce

I guess it's due to some changes in NcEmptyContent

### Expected behavior

The following patch makes the form appear:
```diff
diff --git a/src/views/Setup.vue b/src/views/Setup.vue
index 042a2f25e..7d0baa0f1 100644
--- a/src/views/Setup.vue
+++ b/src/views/Setup.vue
@@ -8,10 +8,12 @@
                                </template>
                                <h2>{{ t('mail', 'Connect your mail account') }}</h2>
                                <template #desc>
+                                       a
                                        <AccountForm :display-name="displayName"
                                                :email="email"
                                                :error.sync="error"
                                                @account-created="onAccountCreated" />
+                                       b
                                </template>
                        </EmptyContent>
                </div>
```

### Actual behavior

Only the title is shown

**Comment by ChristophWurst** [comment]
Reported in https://github.com/nextcloud/mail/pull/6995#pullrequestreview-1074133525 as well.

**Comment by GretaD** [comment]
> Reported in [#6995 (review)](https://github.com/nextcloud/mail/pull/6995#pullrequestreview-1074133525) as well.

i can confirm that it is fixed there

**Comment by ChristophWurst** [comment]
![Bildschirmfoto vom 2022-09-05 21-40-22](https://user-images.githubusercontent.com/1374172/188506148-dabb06b1-910b-4a14-8bf4-ff8cf6827def.png)

Works (again)
