### ISSUE TITLE
Navigation expand icon moved to the right

### ISSUE THREAD

**Issue by ChristophWurst** [nextcloud/mail#7095]
### Steps to reproduce

1. Open the app
2. Configure an account
3. Create a hierarchy of mailboxes
4. Hover the parent mailbox

### Expected behavior

Expand icon shows on the left, instead of the mailbox icon.

### Actual behavior

Expand icon shows on the right.

![Bildschirmfoto vom 2022-08-23 19-40-13](https://user-images.githubusercontent.com/1374172/186227576-9a5b7738-e335-4272-9533-d1738fc11b5a.png)

### Mail app version

v1.4 46c445b3fa227376734303c92248aaae605a2bf5

**Comment by ChristophWurst** [comment]
I think this is a regression of https://github.com/nextcloud/nextcloud-vue/pull/2704.

**Comment by GretaD** [comment]
fixed on nc/vue 7.2.0

**Comment by ChristophWurst** [comment]
link?

**Comment by GretaD** [comment]
there is no specific fix for this problem, but on nc/vue 7.2.0 the problem doesnt exist anymore. I can have a look to see what exactly fixed this one too.

**Comment by GretaD** [comment]
> fixed on nc/vue 7.2.0

well, looks like on 7.3.0 it broken again

**Comment by ChristophWurst** [comment]
It looks fixed with v3 :sunglasses:
