### ISSUE TITLE
Account setup button stays active during submit

### ISSUE THREAD

**Issue by ChristophWurst** [nextcloud/mail#7096]
### Steps to reproduce

1. Open the account
2. Open the setup page and fill in some data (doesn't have to be correct)
3. Click *Connect*

### Expected behavior

*Connect* button turns disabled.

### Actual behavior

Button stays enabled.

### Additional info

Likely a regression of https://github.com/nextcloud/mail/commit/fd055f33fcf180c0b8309410526903c9341d871b.

**Comment by GretaD** [comment]
this is not a regression, the button was always active, fix #7100
