### ISSUE TITLE
Attachments scroll horizontally

### ISSUE THREAD

**Issue by ChristophWurst** [nextcloud/mail#7120]
### Steps to reproduce

1. Open a message with many attachments

### Expected behavior

See a grid of attachments

### Actual behavior

See a long vertical list that scrolls

![Bildschirmfoto vom 2022-08-31 15-18-39](https://user-images.githubusercontent.com/1374172/187689032-95a8bd02-88e8-4785-b6e7-66471de62048.png)

### Mail app version

1.4

### Additional info

@jancborchardt @nimishavijay is this intentional? Then we can close the ticket.

**Comment by jancborchardt** [comment]
No that's not intentional, especially not horizontal scroll.

@sazanof are you aware of this? :)
Also, it's a bit strange that with different sized images, the text is all in different places. The layout should be more constant like in the files grid view.

**Comment by ChristophWurst** [comment]
> **not**

Explains why I couldn't find your PR in the list of closed PRs :see_no_evil:

**Comment by ChristophWurst** [comment]
If your PR obsoletes a fix then we can prioritize that. I'll have a look.
