### ISSUE TITLE
Action close-after-click no longer works

### ISSUE THREAD

**Issue by ChristophWurst** [nextcloud/mail#7124]
### Steps to reproduce

1. Open the app
2. Configure an account
3. Open a mailbox
4. Open the actions menu of an envelope
5. Click an action

### Expected behavior

1) Menu is closed
2) Action is performed

### Actual behavior

1) Action is performed

### Mail app version

1.4

### Additional info

This could be an upstream issue with `@nextcloud/vue`.

**Comment by raimund-schluessler** [comment]
Try with a production build and clean install via npm. I noticed this in Tasks as well, it never works using a dev build.

**Comment by ChristophWurst** [comment]
Indeed!
