### ISSUE TITLE
Opening composer does not focus the "To" field anymore

### ISSUE THREAD

**Issue by jancborchardt** [nextcloud/mail#7125]
### Steps to reproduce

1. Open the composer via "New message"

### Expected behavior

The "To" field is focused, like it used to be and like it is in other mail apps as well.

### Actual behavior

The focus remains on the "New message" button, which at this stage is behind the modal view.

### Mail app version

Current on cloud.nc.com

### Additional info

Also cc @tobiasKaminsky who noted this.

**Comment by ChristophWurst** [comment]
https://github.com/nextcloud/mail/blob/88b7366404548b8ed4c4a4b9d4048d8e8204b59b/src/components/Composer.vue#L791-L793 the code i still there. Either Vue Multiselect change or the focus trap steals focus once again.

**Comment by GretaD** [comment]
right now the focus is on the _From_ field and the multiselect list of your account/s is open by default
![Screenshot from 2022-09-23 14-42-41](https://user-images.githubusercontent.com/12728974/191963628-29d1a0d3-da42-424a-aab6-7c9b4c5ea054.png)

**Comment by ChristophWurst** [comment]
Do you know why the focus is put there? Can we disable that?

**Comment by ChristophWurst** [comment]
@GretaD is that a no?
