### ISSUE TITLE
Mail account connection screen does not have background or scrollbar with new design

### ISSUE THREAD

**Issue by jancborchardt** [nextcloud/mail#7134]
### Steps to reproduce

Try out Mail with Nextcloud server master.

### Expected behavior

The mail account connection screen could use a background (full width sans the 8px padding is good) and should be scrollable.

### Actual behavior

The mail account connection screen has no background nor a scrollbar.
![image](https://user-images.githubusercontent.com/925062/188037309-8ca2874d-c8b4-46cf-accf-4b7fc5a8e854.png)

### Mail app version

1.14.0-beta1

**Comment by ChristophWurst** [comment]
![Bildschirmfoto vom 2022-09-07 11-26-23](https://user-images.githubusercontent.com/1374172/188843316-a5c3e8fd-7180-471a-b010-90e287b990e1.png)

Can't reproduce.

That must have been a combination of Nextcloud 25 and the old UI.
