### ISSUE TITLE
When Inbox is open, both its entry and account heading is highlighted

### ISSUE THREAD

**Issue by jancborchardt** [nextcloud/mail#7135]
### Steps to reproduce

1. Open the inbox of an account

### Expected behavior

Only the inbox should be highlighted.

Yes it’s fine for a click on the account heading to also open the inbox, however still only the inbox entry should be highlighted.

### Actual behavior

Both entries are highlighted, looking strange:
![image](https://user-images.githubusercontent.com/925062/188038032-2fbec357-90c6-4e3d-a76a-5b32187a775f.png)

### Mail app version

1.14.0-beta1

**Comment by ChristophWurst** [comment]
I guess that is because the account email is a nav element that points to the first mailbox (typically the inbox) and when that inbox is open, the Vue router adds the active state to both elements.

**Comment by ChristophWurst** [comment]
I can't reproduce at the moment. If I click on the account email it stays *active* but that's because the element is still focused after click.

**Comment by JohannesGGE** [comment]
> I can't reproduce at the moment. If I click on the account email it stays _active_ but that's because the element is still focused after click.

I can confirm this behavior. As soon as there is a click somewhere else the focused is removed.
