### ISSUE TITLE
app-content-details not centered anymore

### ISSUE THREAD

**Issue by kesselb** [nextcloud/mail#7144]
### Steps to reproduce

[Screencast from 02.09.2022 22:29:14.webm](https://user-images.githubusercontent.com/3902676/188231116-9ad4c7d8-fcde-4191-94ba-ab2e58bd8b33.webm)

### Expected behavior

A proper width for the envelope container

### Actual behavior

Weird width ;)

### Mail app version

2.0

**Comment by jancborchardt** [comment]
The width seems fine according to recommendations for legibility, however it’s not centered. :)

**Comment by ChristophWurst** [comment]
Moreover the content list can't resized. It's like some CSS rules are fighting each other.

**Comment by ChristophWurst** [comment]
This seems fixed with the latest nc/vue bump.
