### ISSUE TITLE
Top pill-style nav item doesn't align with frame radius

### ISSUE THREAD

**Issue by ChristophWurst** [nextcloud/mail#7151]
### Steps to reproduce

1. Open the app
2. Configure an account
3. Look at the top left

### Expected behavior

Pleasing design

### Actual behavior

![Bildschirmfoto vom 2022-09-05 16-29-39](https://user-images.githubusercontent.com/1374172/188472057-9cac3c08-bbc3-4e05-9218-4b67e135419f.png)

### Mail app version

2.0.0 beta 1

**Comment by GretaD** [comment]
fixed here #7158
