### ISSUE TITLE
Settings menu doesn't look nice with the new content frame

### ISSUE THREAD

**Issue by ChristophWurst** [nextcloud/mail#7152]
### Steps to reproduce

1. Open the app
2. Configure an account
3. Look at the bottom left

### Expected behavior

Pleasing design 

### Actual behavior

![Bildschirmfoto vom 2022-09-05 16-29-47](https://user-images.githubusercontent.com/1374172/188472237-5335ff8e-6472-4c4f-b63a-d6a89f41d595.png)

### Mail app version

2.0.0 beta 1

**Comment by GretaD** [comment]
fixed here https://github.com/nextcloud/mail/pull/7158
