### ISSUE TITLE
Settings menu has white background

### ISSUE THREAD

**Issue by ChristophWurst** [nextcloud/mail#7153]
### Steps to reproduce

1. Open the app
2. Configure an account
3. Open the settings menu bottom left

### Expected behavior

Pleasing design

### Actual behavior

![Bildschirmfoto vom 2022-09-05 16-29-56](https://user-images.githubusercontent.com/1374172/188472397-0bf2d488-cd9b-4c33-a611-8cc26b05074f.png)

### Mail app version

2.0.0 beta 1

**Comment by GretaD** [comment]
fixed here https://github.com/nextcloud/mail/pull/7158
