### ISSUE TITLE
Recipient multiselect jumps with focus

### ISSUE THREAD

**Issue by ChristophWurst** [nextcloud/mail#7165]
### Steps to reproduce

1. Open the app
2. Configure an account
3. Click *New message*
4. Click into *To*

### Expected behavior

Focus change but text stays where it was

### Actual behavior

| Blur | Focus |
|---|---|
| ![Bildschirmfoto vom 2022-09-05 22-30-46](https://user-images.githubusercontent.com/1374172/188510052-91164a27-ae6f-4c95-8c34-1d4f3a656cc0.png) | ![Bildschirmfoto vom 2022-09-05 22-30-50](https://user-images.githubusercontent.com/1374172/188510050-d4bb053b-1000-473c-a1b4-834577655700.png) |

### Mail app version

2.0.0 beta 1

**Comment by JuliaKirschenheuter** [comment]
After searching for this odd behavior i can't reproduce this bug anymore. If this will happens again, i'll reopen this issue.
