### ISSUE TITLE
Composer subject has focus border and element border 

### ISSUE THREAD

**Issue by ChristophWurst** [nextcloud/mail#7166]
### Steps to reproduce

1. Open the app
2. Configure an account
3. Click *New message*

### Expected behavior

Modal looks nice

### Actual behavior

Double border

![Bildschirmfoto vom 2022-09-05 22-33-34](https://user-images.githubusercontent.com/1374172/188510282-fd437ed5-c133-4d3d-8bdf-a6f76e20fb33.png)

### Mail app version

2.0.0 beta 1

**Comment by ChristophWurst** [comment]
## Current

![Bildschirmfoto vom 2022-09-08 12-34-30](https://user-images.githubusercontent.com/1374172/189101349-eee79506-e4cf-48b1-b6ef-14a649e36c48.png)

## Solution 1 - no input border

![Bildschirmfoto vom 2022-09-08 12-34-50](https://user-images.githubusercontent.com/1374172/189101390-856f5f07-5108-4b35-ad89-ec4a93e67dc6.png)

## Solution 2 - no wrapper border

![Bildschirmfoto vom 2022-09-08 12-35-12](https://user-images.githubusercontent.com/1374172/189101432-c4a83834-7c80-48b8-8dbb-86c2b5359a3d.png)

**Comment by ChristophWurst** [comment]
I'm really on the fence here. S1 brings us close to the previous design, S2 brings us closer to the new design of inputs in Nextcloud.

**Comment by jancborchardt** [comment]
Yes, as said solution 1 absolutely. Otherwise we end up with way too many borders.
