### ISSUE TITLE
Can not copy contact email to clipboard

### ISSUE THREAD

**Issue by ChristophWurst** [nextcloud/mail#7169]
### Steps to reproduce

1. Open the app
2. Configure an account
3. Open a message
4. Click on the sender or recipient bubbles below the thread subject
5. Click *Copy to clipboard*

![Bildschirmfoto vom 2022-09-06 09-13-42](https://user-images.githubusercontent.com/1374172/188570599-85627e5c-ddee-4c9b-87ad-6b75e6c5916e.png)

### Expected behavior

Sender/recipient is copied to clipboard

### Actual behavior

Nothing

### Mail app version

2.0.0 beta 1

**Comment by derekakelly** [comment]
I can confirm this on NC25, and Mail 2.1.0-rc.1

**Comment by meichthys** [comment]
Also seeing this in v2.1.0
