### ISSUE TITLE
Account email ellipsized too late

### ISSUE THREAD

**Issue by ChristophWurst** [nextcloud/mail#7171]
### Steps to reproduce

1. Open the app
2. Create an account
3. Look at the navigation

### Expected behavior

Good design

### Actual behavior

![Bildschirmfoto vom 2022-09-06 09-51-15](https://user-images.githubusercontent.com/1374172/188578078-3f92be8c-a86d-40a5-b53f-f78ca50ec5b6.png)

### Mail app version

2.0.0 beta 1

### Additional info

Likely a regression of `@nextcloud/vue`

**Comment by GVodyanov** [comment]
@ChristophWurst This has somewhat been forgotten about but I just looked into it again and we now have the exact opposite issue 

![image](https://github.com/user-attachments/assets/52fb97f8-06d8-4ad9-8c73-dc0386dbb6e4)

**Comment by ChristophWurst** [comment]
Ouch
