### ISSUE TITLE
mail.css and mobile.css missing

### ISSUE THREAD

**Issue by kesselb** [nextcloud/mail#7172]
### Steps to reproduce

1. Open mail app
2. Open network inspector
3. Reload page
4. See a 302 request for mail.css and mobile.css
5. See the files are missing

### Expected behavior

Don't request mail.css and mobile.css ;)

### Actual behavior

A request for mail.css and mobile.css

### Mail app version

2ef0f2b63f32af0bdf9de0b6fb5eff3c1f5bb799

**Comment by ChristophWurst** [comment]
That is because of the scss drop in server. It is no longer compiled.
