### ISSUE TITLE
Loginviapost addin - execute without a form - feature request

### ISSUE THREAD

**Issue by dansmithpm** [nextcloud/mail#718]
The loginviapost app is great so long as you login via a form, which I guess is what it’s designed to do.

In my scenario I already have a login screen which logs my users into our portal and also to the mail server though want this to log them into NC also. I’m also using the user_sql app to I can authenticate my users from my one database which also works.

I’m trying to the following but it never works, if i put a regular form it logs in perfectly though I want to login users behind the scenes so their NC drive is available via one of the links in our portal.
The example form is purely to execute the standard nextcloud login and bypasses external origin etc.

so in essence: the form below when posted works perfectly and logs the user in

```
<form method="post" action="https://domain.co.uk/index.php/apps/loginviapost/login">
	<input type="text" name="username" />
	<input type="text" name="password"  />
	<input type="submit" value="Submit" />
</form>
```
whereas executing via code as below does nothing and if I subsequently go the files page I just get the log in page.

```
$data = array(
	'username' => 'username',
	'password' => 'password'
);

$postvars = http_build_query($data) . "\n";

$ch = curl_init();
curl_setopt($ch, CURLOPT_URL, 'https://domain.co.uk/index.php/apps/loginviapost/login');
curl_setopt($ch, CURLOPT_POST, 1);
curl_setopt($ch, CURLOPT_POSTFIELDS, $postvars);
curl_setopt($ch, CURLOPT_RETURNTRANSFER, true);
$server_output = curl_exec ($ch);
curl_close ($ch);
```
Can anyone please provide a code sample which will work and allow me via regular PHP code (given a username and password) to login to nextcloud without going through the UI login process?

**Comment by ChristophWurst** [comment]
What are you trying to achieve? I don't see any connection to this app.

> Can anyone please provide a code sample which will work and allow me via regular PHP code (given a username and password) to login to nextcloud without going through the UI login process?

That's not supported AFAIK.

**Comment by dansmithpm** [comment]
I'm using nextcloud as part of a wider platform solution for my client which provides a custom CRM system with nextcloud integrating in as a google drive type replacement together with collabora as well as afterlogic webmail pro.
So I have a single login (not a onelogin etc) which gets the user onto the platform. I have webmail linked in and integrated and the final piece is to have the user also logged onto nextcloud at the same time. I'm using the external sql app to allow credentials from my database so that's fine though in order to have a single login form I need to be able to have this code working.
Without this they get the files tab in the portal but it purely shows the login screen which I'm trying to bypass.
It may well not be possible though I'm exploring every avenue before calling it a day!

**Comment by ChristophWurst** [comment]
Okay, thanks for the additional info. So you're looking for technical support. Please see https://nextcloud.com/support/ and https://nextcloud.com/enterprise/.

Since this is the bug tracker of Nextcloud's mail app, I'm closing this ticket.

**Comment by dansmithpm** [comment]
ok, so I posted in the wrong app - where is it appropriate to post it as
it's time sensitive, and the only place to put a bounty was via github

- sorry wasn't sure how to contact you without going through this channel?

**Comment by ChristophWurst** [comment]
Please see [our website](https://nextcloud.com/contact). Thanks.
