### ISSUE TITLE
Dark mailbox counter with dark system theme

### ISSUE THREAD

**Issue by ChristophWurst** [nextcloud/mail#7182]
### Steps to reproduce

1. Set your system/browser to use the dark theme
2. Open the app
3. Configure an account
4. Look at the navigation

### Expected behavior

My eyes don't hurt

### Actual behavior

| Light (looks good) | Dark (looks strange) |
|--|--|
| ![Bildschirmfoto vom 2022-09-06 15-17-35](https://user-images.githubusercontent.com/1374172/188645945-d98fd0ce-f773-486a-8ae9-962679a03f9c.png) | ![Bildschirmfoto vom 2022-09-06 15-19-15](https://user-images.githubusercontent.com/1374172/188645940-84366800-7ae4-4e8d-bfbd-821c1abc0430.png) |

### Mail app version

2.0.0 beta 1

**Comment by ChristophWurst** [comment]
> seems to be an issue with --color-primary-element-lighter

Jan-C. Borchard, 2022

**Comment by ChristophWurst** [comment]
@GretaD could you have a look? This feature was added with https://github.com/nextcloud/nextcloud-vue/pull/3070. `--color-primary-element-light` looks better than `--color-primary-element-lighter` but I'm sure there is a reason why we use the light*er* variant.

**Comment by GretaD** [comment]
dark version should look like this, which version of NC do you have in the testing?
![Screenshot from 2022-09-07 13-23-18](https://user-images.githubusercontent.com/12728974/188866746-cd2c98fd-bfd3-46da-a16a-c599b0299d78.png)

**Comment by ChristophWurst** [comment]
> dark version should look like this, which version of NC do you have in the testing?

You have to switch Nextcloud to the bright theme but your *browser* to dark theme.

**Comment by GretaD** [comment]
> > dark version should look like this, which version of NC do you have in the testing?
> 
> You have to switch Nextcloud to the bright theme but your _browser_ to dark theme.

same result as my screenshot

**Comment by ChristophWurst** [comment]
Try Firefox?

**Comment by ChristophWurst** [comment]
![Bildschirmfoto vom 2022-09-07 15-40-39](https://user-images.githubusercontent.com/1374172/188893023-e2c65f57-abcb-4b64-8a09-4edba7778a1e.png)

![Bildschirmfoto vom 2022-09-07 15-40-11](https://user-images.githubusercontent.com/1374172/188893050-4e990f70-16ea-4e5c-b500-88837c46a14f.png)

**Comment by GretaD** [comment]
yes, i had the default one, now i can reproduce

**Comment by ChristophWurst** [comment]
It's like the Nextcloud theme doesn't detect the browser's dark theme except for the counter. Look at the theming app. I suspect it's somewhere in the logic that defines the css vars.

**Comment by GretaD** [comment]
fixed on server: https://github.com/nextcloud/server/pull/33946

**Comment by ChristophWurst** [comment]
https://github.com/nextcloud/server/pull/33946#issuecomment-1240381322 let's do that as well
