### ISSUE TITLE
In mobile view, vertical scrolling is not possible

### ISSUE THREAD

**Issue by jancborchardt** [nextcloud/mail#7192]
### Steps to reproduce

1. Open the app
2. Make the screen narrow, or zoom in until the breakpoint at which on the top left the "back" button is shown.

### Expected behavior

You can scroll

### Actual behavior

Vertical scrolling is not possible at all.

### Mail app version

2.0.0-beta.2

**Comment by ChristophWurst** [comment]
Every time you open a ticket without the issue template god punctures a bike.

**Comment by ChristophWurst** [comment]
Probably needs a retest after https://github.com/nextcloud/mail/pull/7202.

**Comment by GretaD** [comment]
fixed #7346
![Screenshot from 2022-10-10 12-41-17](https://user-images.githubusercontent.com/12728974/194848344-6c4aebd3-f530-40d8-be90-1e6635f1a7ca.png)
