### ISSUE TITLE
Message thread width does not reduce according to viewport width

### ISSUE THREAD

**Issue by jancborchardt** [nextcloud/mail#7193]
With 2.0.0-beta.2 on tech-preview

When you make the window narrower or go into mobile mode, the threads and mail texts are cropped off on the right side because they do not reduce in width.

**Comment by kesselb** [comment]
Thanks @jancborchardt :+1: 

Hope you don't mind when I add some of my findings to this issue as they look related.

**Issue 1: Width 1440. Message component is wider than viewport**

[Screencast from 06.09.2022 16:55:01.webm](https://user-images.githubusercontent.com/3902676/188667975-6dd6b746-6aa5-41a3-893d-8beabb4958f8.webm)

**Issue 2: Width 1024. Envelope list is not visibile**

![image](https://user-images.githubusercontent.com/3902676/188668448-d2887614-f7ce-4647-a73f-be004475851f.png)

Please let me know if we need a dedicated issue for those.

**Comment by jancborchardt** [comment]
Perfect, thank you @kesselb! :) Those are exactly my issues too, just didn’t have a test account to take screenshots with.

**Comment by ChristophWurst** [comment]
It appears to happen for a very small range of window widths now. Yet I can not figure our where this is coming from.

**Comment by ChristophWurst** [comment]
Did the nc-vue breakpoints change with the new padded body container?

**Comment by ChristophWurst** [comment]
Bingo. Setting the breakpoint to 1008px (1024-2*8) resolves this issue.

**Comment by szaimen** [comment]
I think this is solved with https://github.com/nextcloud/nextcloud-vue/pull/3329

**Comment by st3iny** [comment]
This needs a backport to stable1.14. We can probably hard code the changes from nextcloud-vue into the stable1.14 branch because a bump is not feasible.

Ref https://github.com/nextcloud/mail/issues/7424#issuecomment-1279107539

**Comment by st3iny** [comment]
Fixed by #7419
