### ISSUE TITLE
Big margin if big message thread

### ISSUE THREAD

**Issue by sazanof** [nextcloud/mail#7196]
### Steps to reproduce

1. Open app with account
2. Open a big message thread
3. Look at this

### Expected behavior

No marging, if big thread

### Actual behavior

![image](https://user-images.githubusercontent.com/3595562/188682760-923f24be-b887-42cb-a0d2-d489e73c9bc0.png)

### Mail app version

2.0.0-beta.3

### Mailserver or service

Dovecot

### Operating system

Ubuntu 20.04

### PHP engine version

PHP 8.0

### Web server

Apache (supported)

### Database

MySQL

**Comment by ChristophWurst** [comment]
Good catch!

**Comment by JuliaKirschenheuter** [comment]
I can't reproduce it with current main branch. Could you?

**Comment by JuliaKirschenheuter** [comment]
@sazanof and me could not reproduce it anymore. Closing issue.
