### ISSUE TITLE
"Show images" button design issue

### ISSUE THREAD

**Issue by jancborchardt** [nextcloud/mail#7197]
The "Show images" button looks strange again on tech-preview with Mail v 2.0.0-beta.2

![image](https://user-images.githubusercontent.com/925062/188690750-2699884c-47d9-4622-a55a-6829984de7c1.png)

Expected would be as per mockup, which also was like that before (can not show a screenshot cause on cloud.nc I can not open a lot of mailboxes currently):
![image](https://user-images.githubusercontent.com/925062/188691219-bfd5778c-c07c-49bf-bc69-6103f4fafa7a.png)

The wording is fine as is. :) cc @GretaD

**Comment by ChristophWurst** [comment]
Fixed with beta 3
