### ISSUE TITLE
no default config found since update 0.7.8

### ISSUE THREAD

**Issue by Babene03** [nextcloud/mail#721]
### Steps to reproduce
Since the update from 0.7.7 to 0.7.8, I can no longer retrieve e-mails. When I retrieve, I get the following message: "Error loading accounts." In the log I always get the message: "no default configuration found". Before the update, everything worked. The configuration was not changed. I have tried several times to reenter the account data. But always come to the same mistake.

Must I reset the config?

**Mail app version:** 0.7.8

**Operating system**: Ubuntu 17.10

**Web server:** nginx/1.13.6

**Database:** MariaDB 10.1.30

**PHP version:** 7.1.13

**Version:** 12.0.4.3

**Comment by ChristophWurst** [comment]
That's a debug log statement. Nothing to worry about https://github.com/nextcloud/mail/blob/78cea6455aa38fd5ed274cdf38d50db976879d61/lib/Service/DefaultAccount/Manager.php#L73

Please fill out the full issue template for the other issue. Thanks.

**Comment by Babene03** [comment]
I have now reinstalled the server, but the same problem.

What I have now discovered about the domain, I can not access the emails. However, when I go over IP on the local network, he calls the accounts.

But only since the update

**Comment by Babene03** [comment]
Closed, with the new Update is this fixed.
