### ISSUE TITLE
Cyrillic not working

### ISSUE THREAD

**Issue by deviceh** [nextcloud/mail#7222]
### Steps to reproduce

1. Install Nexcloud 25
2. Install Mail 2.0
3. All Cyrillic texts are sent and displayed, for example, on gmail: "ÐÐÐÐ¢Ð Ð ÐÐÐÐÐÐÐ"

### Expected behavior

In nextcloud 24 it worked perfectly, the Cyrillic text looked like this for example: "привет мир!"

### Actual behavior

All Cyrillic texts are sent and displayed, for example, on gmail: "ÐÐÐÐ¢Ð Ð ÐÐÐÐÐÐÐ"

### Mail app version

2.0

### Mailserver or service

Gmail, Dovecot

### Operating system

Debian

### PHP engine version

PHP 7.4

### Web server

Apache (supported)

### Database

MySQL

### Additional info

Fix this pls :(

**Comment by deviceh** [comment]
Perhaps there is a quick sample code that will solve this problem, I will be very grateful

**Comment by ChristophWurst** [comment]
@sazanof that is the error you ran into as well, right?

**Comment by sazanof** [comment]
@ChristophWurst exactly

![image](https://user-images.githubusercontent.com/3595562/189049377-fbdf8b0b-6c7b-44e4-9c6d-d33db72f3c08.png)

**Comment by ChristophWurst** [comment]
Could one of you export such message as .eml or .mbox from Thunderbird or similar and attach it here as .txt? I'll see if this is reproducible on my dev instance. Encoding don't always show an all systems ...

**Comment by sazanof** [comment]
[Test with attachments 2.txt](https://github.com/nextcloud/mail/files/9524379/Test.with.attachments.2.txt)
[WSUS: сводка по состоянию обновлений от WSUS.txt](https://github.com/nextcloud/mail/files/9524361/WSUS.WSUS.txt)
will that do?

there is another nuance - in the branch, the preview line of the message body may be in the wrong encoding, while if you open the message, everything will be correct

And there may also be an error with encoding in two places (in the branch and in the preview)

**Comment by ChristophWurst** [comment]
Thanks a lot. I'll have a look.

**Comment by ChristophWurst** [comment]
Does this still happen?

**Comment by auroraanna** [comment]
> Does this still happen?

![image](https://github.com/nextcloud/mail/assets/81317317/153b22db-4f4a-4095-87cf-462d429a4d2d)

I can't reproduce it.

**Comment by bjoernv** [comment]
The issue does not occur with UTF-8. Try a Cyrillic 8bit code like ISO-8859-5.
This is an example email: [cyrillic-ISO-8859-5.txt](https://github.com/nextcloud/mail/files/12441116/cyrillic-ISO-8859-5.txt)

![image](https://github.com/nextcloud/mail/assets/6728426/5a6e5846-b871-4f6d-8b08-bda5c6b9fd9a)
