### ISSUE TITLE
Drafts don't save attachments

### ISSUE THREAD

**Issue by mat-m** [nextcloud/mail#7224]
### Steps to reproduce

1. Create a Draft with an attachment
2. Wait for the AutoSave
3. Go in the _Drafts_ folder

### Expected behavior

4.The draft is here, *with* its  attachments

### Actual behavior

4.The draft is here, but without attachments

### Mail app version

1.13.8

### Mailserver or service

gandi

### Operating system

Linux mint 21

### PHP engine version

PHP 7.4

**Comment by ChristophWurst** [comment]
Dup of https://github.com/nextcloud/mail/issues/458
