### ISSUE TITLE
Clickable area to expand/collapse mail is too small, leading to misclicks

### ISSUE THREAD

**Issue by jancborchardt** [nextcloud/mail#7238]
### Steps to reproduce

1. Open the mail app
2. Open a thread
3. Try to open a closed message of the thread

### Expected behavior

A click on any part of this area should toggle open/close, of course excluding the entire height of the actions part on the right if the message is open:
![image](https://user-images.githubusercontent.com/925062/189224837-271bb334-aaed-4acc-873e-8b2ef1e59aee.png)

### Actual behavior

Currently only the text is clickable, which is especially finicky (and violates our 44px min clickable area guideline) when there is no preview subline:
![image](https://user-images.githubusercontent.com/925062/189223513-cfc8efe2-1422-4dcd-a781-61fac160ada8.png)

### Mail app version

2.0.0-beta.4

**Comment by ChristophWurst** [comment]
I can no longer reproduce.

**Comment by GretaD** [comment]
I fixed this while working on another thread issue, long time ago. Also, i cannot reproduce :)
