### ISSUE TITLE
Removing/Adding a user on to/cc/bcc composer doesnt work properly

### ISSUE THREAD

**Issue by GretaD** [nextcloud/mail#7260]
### Steps to reproduce

1. Open composer
2. Try to add a recipient on _to_
3. See that you cannot see the recipient you just added
4. Click on the body to see the recipient and try to remove the recipient you added
5. You cannot

### Expected behavior

Adding a user and removing a user works properly, so i can remove them when i click X

### Actual behavior

I cannot remove a user after adding and cannot see the user after adding, the editing state is always open

### Mail app version

latest

### Additional info

https://user-images.githubusercontent.com/12728974/189370676-750eb217-23a2-4c24-8023-3cb502597a93.mp4

**Comment by ChristophWurst** [comment]
https://github.com/nextcloud/mail/pull/7240 could help

**Comment by GretaD** [comment]
fixed here https://github.com/nextcloud/mail/pull/7240
