### ISSUE TITLE
Resolve php7.2 deprecation warning in Horde Stream lib

### ISSUE THREAD

**Issue by ChristophWurst** [nextcloud/mail#731]
Since we include php72 in our build matrix, the php7.2 job keeps failing due to a deprecation warning:
![bildschirmfoto von 2018-01-23 14-58-16](https://user-images.githubusercontent.com/1374172/35279669-fe835032-004d-11e8-9e86-0645a5b3d6ca.png)

The specific error is
```
1) OCA\Mail\Tests\Integration\FolderSynchronizationTest::testSyncNewMessage
The each() function is deprecated. This message will be suppressed on further calls
/home/travis/build/nextcloud/core/apps/mail/vendor/pear-pear.horde.org/Horde_Stream_Wrapper/Horde/Stream/Wrapper/Combine.php:129
/home/travis/build/nextcloud/core/apps/mail/vendor/pear-pear.horde.org/Horde_Stream_Wrapper/Horde/Stream/Wrapper/Combine.php:100
/home/travis/build/nextcloud/core/apps/mail/vendor/pear-pear.horde.org/Horde_Mime/Horde/Mime/Mail.php:502
/home/travis/build/nextcloud/core/apps/mail/tests/Integration/Framework/ImapTest.php:138
/home/travis/build/nextcloud/core/apps/mail/tests/Integration/FolderSynchronizationTest.php:72
```

I've looked into it twice and this deprecation has actually been addressed already in https://github.com/horde/Stream_Wrapper/commit/6018b26b20a78654c113da04ad9e816b1ac0c5e9 by @yunosh.

However, the distributed version on https://pear.horde.org/ is outdated.

Contacting the horde devs via their #horde channel on freenode failed twice, I never got any response.

@yunosh: (sorry for shamelessly mentioning you here) Can you tell me whether you plan to release a new version of the stream wrapper lib soon? If there's anything I can do to help you move this forward, just let me know. I'd be happy to help! 😉

**Comment by ChristophWurst** [comment]
In the case of being totally unable to get any response/help from the horde devs I see no other option than distributing those packages myself via composer. It's a lot of unnecessary work, but we're kinda stuck here.

**Comment by yunosh** [comment]
No problem, we'll cut a release soon.

**Comment by ChristophWurst** [comment]
Thanks a lot, @yunosh!

**Comment by yunosh** [comment]
2.1.4 has been released.

**Comment by ChristophWurst** [comment]
> 2.1.4 has been released.

Thank you very much! 🚀
