### ISSUE TITLE
CKEditor doesn't respect dark theme

### ISSUE THREAD

**Issue by szaimen** [nextcloud/mail#7324]
### Steps to reproduce

Install latest RC for NC25

### Expected behavior

it should look great

### Actual behavior

it doesnt

see 
![image](https://user-images.githubusercontent.com/42591237/192359762-f1ffa8c9-044f-4608-863d-d8bf735aea4c.png)
![image](https://user-images.githubusercontent.com/42591237/192359786-0cb608a4-ba39-44db-affd-4effeec975f2.png)

### Mail app version

latest RC for NC25

**Comment by ChristophWurst** [comment]
Multiselects look :clown_face: across the ecosystem. That has to be adddressed in \@nextcloud/vue.

**Comment by ChristophWurst** [comment]
Dup of https://github.com/nextcloud/mail/issues/6378
