### ISSUE TITLE
Mail Header mailformed

### ISSUE THREAD

**Issue by florian140807** [nextcloud/mail#7328]
### Steps to reproduce

1. Create a new mail with the sender address as "To" recipient and another address as "Bcc"
2. Send it with nextcloud mail
3. check the source code of the sent message

### Expected behavior

"To" and "Bcc" fields should be filled accordingly in the source code of the sent message

When the same is done by the hosting (all-inkl) Webmailer, the header fields are as expected (see below)
![grafik](https://user-images.githubusercontent.com/37881373/192615335-349c6c69-ca39-4ec7-abfe-c5cccafd3bf1.png)

### Actual behavior

"To" field is empty, "Bcc" field is not visible at all

![grafik](https://user-images.githubusercontent.com/37881373/192614593-bbbb10d8-e56b-4ed7-aa5b-c701984651f0.png)

### Mail app version

1.11.7

**Comment by kesselb** [comment]
Hey,

1.11.7 is kinda old. Would you mind to try a newer version?

**Comment by florian140807** [comment]
Hi,
thanks for that feedback. The NC update is currently ongoing but the update procedure will not work as expected. I need to investigate there. As soon as there are news, I'll report back

**Comment by florian140807** [comment]
Update to NC 24.0.5 (mail: 1.13.8) done, but the behavior did not change. The source code of the sent message looks still the same as with 1.11.7.

**Comment by GretaD** [comment]
it looks like on stable4.0 works as expected. @florian140807 do you mind testing it again?

**Comment by nextcloud-command** [comment]
Hi there! It looks like this issue hasn’t seen much activity for a while and might need a bit more information to move forward. If we don’t hear back soon, we may close it to keep things organized. Thanks again for your contributions – we really appreciate it!
