### ISSUE TITLE
Nextcloud Mail App Not Working With Mailvelope

### ISSUE THREAD

**Issue by zohaib09** [nextcloud/mail#7344]
### Steps to reproduce

1. Install mailvelop in chrome
2. Add NC domain to authorized domain
3. Create new email with mailvelop Email body and try to encrypt
4. When Enable API in authorized domain for our NC domain then Mailvelope option disappeared during compose of new emails

### Expected behavior

Emails Should be encrypted as other webmail services.

### Actual behavior

Email does not encryptes

### Mail app version

1.13.8

### Mailserver or service

Zimbra

### Operating system

Debian 11

**Comment by zohaib09** [comment]
@ChristophWurst  plesse advice

**Comment by miaulalala** [comment]
Do you have any error messages in your logs or in the browser console?

**Comment by ChristophWurst** [comment]
Tested and the email *is* encrypted. Please provide screenshots.

**Comment by zohaib09** [comment]
Hi

Mailvelope installed

![image](https://user-images.githubusercontent.com/47688270/193426665-6a5bf37c-15df-4b3a-b8e7-c1306bcd9626.png)

Domain is authorized without API enabled (Default settings) then went to NC mail app, click New Message

![image](https://user-images.githubusercontent.com/47688270/193426783-06f86023-7269-4e94-9d44-fef11bc64c66.png)

Then clicked on mailvelooped icon, composed email in Mailvelope-Editor 

![image](https://user-images.githubusercontent.com/47688270/193426911-8e608e06-0d73-4692-afb1-23fd92408271.png)

Then click on encrypt

Then prompted password to sign email (entered the password, clicked ok)

![image](https://user-images.githubusercontent.com/47688270/193427031-cf669b0b-f9f2-4b76-8295-ad3ec7e99b14.png)

Then this empty mail app editor appears

![image](https://user-images.githubusercontent.com/47688270/193427125-d5a7c980-3803-43d4-a82c-34d946d88e68.png)


This is perfectly working for webmail client of zimbra, gmail etc. but not for mail app.

**Comment by zohaib09** [comment]
@ChristophWurst  Hi, please suggest a solution for this. What may be the cause.

**Comment by ChristophWurst** [comment]
You forgot to enable *API mode* for the domain.

**Comment by zohaib09** [comment]
Another thing, in mail app of nextcloud , decryption is perfectly working. Only encryption have issue

![image](https://user-images.githubusercontent.com/47688270/193663457-093a4b01-09e8-4a50-bbac-d34fe1ff0dd4.png)

**Comment by zohaib09** [comment]
> You forgot to enable _API mode_ for the domain.

When I enable API, it disappears mailvelope icon from new compose message

![image](https://user-images.githubusercontent.com/47688270/193664105-23b7672e-5951-4cbc-90c2-3a2d43a06d8b.png)


![image](https://user-images.githubusercontent.com/47688270/193664291-c6977d30-053d-4d6e-8d9e-6d36c87f1a4a.png)


Also decryption does not work once apti enabled

**Comment by zohaib09** [comment]
@ChristophWurst please suggest, if any other info is required let me know please

**Comment by ChristophWurst** [comment]
Decryption doesn't work due to the formatting of the message. I think we need to fix that.

**Comment by zohaib09** [comment]
@ChristophWurst , will you update the code for this? Or anything I can do at my NC or mail app? Please suggest

**Comment by zohaib09** [comment]
@ChristophWurst any updates on it please?

**Comment by zohaib09** [comment]
Okay thank you @ChristophWurst . Yes yes you are right. Take your time.

**Comment by dolphinscorp** [comment]
Hi @ChristophWurst 

Hope you are doing good. Just want to ask if some progress regarding this issue. I know team working on this application is quite busy at the moment. Just want to ask if there is any update.

Thanks in advance.

**Comment by ChristophWurst** [comment]
> Decryption doesn't work due to the formatting of the message. I think we need to fix that.

This is still the case.

**Comment by SephGER** [comment]
Is there any data you need to analyze this issue? For me it just shows a file named "encrypted.asc" when reading a mail. Writing encrypted mails works with API-Mode.

**Comment by ChristophWurst** [comment]
No, thanks, I think we have all info/data we need for an engineer to reproduce and fix the issue.

**Comment by ChristophWurst** [comment]
I can no longer reproduce any issues with the Mailvelope integration. I can send and receive encrypted messages:

![Bildschirmfoto vom 2022-11-07 10-32-27](https://user-images.githubusercontent.com/1374172/200276342-02f9b3fb-487c-492d-8972-9faa7e6f8b7f.png)

**Comment by zohaib09** [comment]
Thank you @ChristophWurst 

I will check and update here.

**Comment by zohaib09** [comment]
Hi @ChristophWurst 

First of thank you for your all efforts to resolve this issue.

Unfortunately i have still same problem. My Mail App version is 1.14.2 & Nextcloud is 24.0.7

I can see there is a release of Mail app v2.1.0.  does this issue resolve in this release? 

In my nextcloud it doesn't show V2.1 of mail aap. Latest release in Nextcloud 24.0.7 app store available is 1.14.2 which is already installed.

Please suggest

**Comment by miaulalala** [comment]
Hi @zohaib09 , version 2 of the mail app is only available for NC25 and up.

**Comment by dolphinscorp** [comment]
Hi @ChristophWurst 
 
I am also still facing the same issue :(

**Comment by ChristophWurst** [comment]
What same issue @dolphinscorp? Could you be a bit more clear about the problem you face?

**Comment by ChristophWurst** [comment]
I confirm *reading* GPG messages with v1.14 doesn't work. Writing does work.

**Comment by ChristophWurst** [comment]
The issue is the writing mode. If text formatting is enabled prior to switching on encryption, the PGP ciphertext is sent as HTML message. I'll have a look.

**Comment by ChristophWurst** [comment]
Fix is at https://github.com/nextcloud/mail/pull/7558.

**Comment by dolphinscorp** [comment]
Hi I confirmed Mail app is working fine by selecting Rich Text (from account settings) and uncheck "Enable Formatting"

Thank you ! 

@ChristophWurst

**Comment by SephGER** [comment]
I have still problems reading encrypted mails. I can read them in Thunderbird with the same key but with Nextcloud+Mailvelope I only see a "encrypted.asc" file when viewing the mail.

**Comment by ChristophWurst** [comment]
You are probably looking at a pgp/mime mail. Mailvelope only works with inline pgp/inline. See https://github.com/mailvelope/mailvelope/issues/41.

**Comment by dolphinscorp** [comment]
Hi

Today I sent email from thunderbird with same mailvelope key using openpgp (not smime) to my gmail and nextcloud mail app. both using same mailvelope keys. Gmail received email and decrypt the email automatically but on other hand mail app received email and but could not decrypt email and shows attache .asc file.

Mail app

![image](https://user-images.githubusercontent.com/115947558/202912457-039e446e-09bf-4ae2-86b0-3dc1092d51d2.png)


Thunderbird Settings: (Only using openpgp standard)

![image](https://user-images.githubusercontent.com/115947558/202912515-bfe01ee7-8f3e-435e-8f53-ae1ded98ca33.png)


Gmail can easily decrypt this email same email from thunderbird


Decryption with gmail and mailvelope

![image](https://user-images.githubusercontent.com/115947558/202912583-68b9b45b-37f8-4042-bd36-0894a8afa210.png)

**Comment by ChristophWurst** [comment]
![Bildschirmfoto vom 2022-11-21 10-08-58](https://user-images.githubusercontent.com/1374172/203010287-a5f82687-f754-40dc-a2ce-1c42debeea94.png)

They keyword is `multipart/encrypted`. I'm able to reproduce with encrypted messages from Gnome Evolution.

**Comment by ChristophWurst** [comment]
That brings us back to https://github.com/nextcloud/mail/issues/3833. Let's continue there.
