### ISSUE TITLE
Shared folders break signup process

### ISSUE THREAD

**Issue by miaulalala** [nextcloud/mail#7369]
### Steps to reproduce

1. Try signing up to mail with an account that has shared folder
2. Signup process errors out with permissions error on \OCA\Mail\IMAP\FolderMapper::getFoldersStatus in the MailSync

### Expected behavior

The sync handles shared folders gracefully even if they are not supported.

### Actual behavior

The sync fails.

### Mail app version

2.0

### Mailserver or service

MailCow

**Comment by ChristophWurst** [comment]
This should be fine now
