### ISSUE TITLE
Account Setup failure still adds account to the database (if the error is not directly detected in the setup)

### ISSUE THREAD

**Issue by miaulalala** [nextcloud/mail#7370]
### Steps to reproduce

1. Have an account setup that has shared folders (I have test login data for this)
2. Try to add account to Mail 
3. Fail with error "No permissions" (see #7369)
4. Reload page - design breaks completely and mail account is added anyway:

![1024-650](https://user-images.githubusercontent.com/7427347/193459586-3d3e391e-0b0a-4f1e-95af-cc8b4b3b53ab.png)

### Expected behavior

The design is stable

### Actual behavior

The design falls apart

### Mail app version

2.0

**Comment by GretaD** [comment]
the initial issue is solved with the shared folder, so this is not reproducible anymore
