### ISSUE TITLE
Request: provide an option to "keep a copy of emails which are deleted on mail server"

### ISSUE THREAD

**Issue by saeedsepehr** [nextcloud/mail#738]
Hi and thanks for your great job.

I wanted to use my cloud server as an email storage, too. 
So I need to **keep all emails, even while they've been deleted in mail server** (origin). It would be nice if you _provide an option in setting to check and do this_ as exceptional cases like mine.

Kind regards

**Comment by ChristophWurst** [comment]
Sounds like a very specific use case to me, hence I suggest to simply use an existing software solution like [imapsync](http://imapsync.lamiral.info/) here. I don't think the majority of our users would use that and thus it's unlikely to be worked on nor being integrated into this app.

**Comment by ChristophWurst** [comment]
cc @nextcloud/mail

**Comment by jancborchardt** [comment]
Yeah, I also don't see how we can do this since we are just an IMAP client. Mails are not duplicated or saved to Nextcloud.
