### ISSUE TITLE
Mail stuck in a loop at initial setup 

### ISSUE THREAD

**Issue by AngryWarrior** [nextcloud/mail#7380]
### Steps to reproduce

1. Install nextcloud/ the mail app
2. Configure email account
3. Mail never finish indexing/ completing the setup.

### Expected behavior

That the setup is finished successfully after completing the initial indexing... 

### Actual behavior

Never finishing it but is stuck.
As described in the next cloud forum thread here: 
https://help.nextcloud.com/t/mail-setup-stalling-stuck-in-a-loop/146696

### Mail app version

1.13.8

### Mailserver or service

Mailenable / private server 

### Operating system

Centos server

### PHP engine version

PHP 7.4

### Web server

Apache (supported)

### Database

MariaDB

### Additional info

Screen recording/ gif image of the issue:
[](https://help.nextcloud.com/uploads/default/original/3X/1/b/1b8f89be7dd185aa84660a13d8223760df207783.gif)

**Comment by croulibri** [comment]
Exact same issue 😞 

**Steps to reproduce**

Install nextcloud/ the mail app
Configure email account
Mail never finish indexing/ completing the setup.

**Expected behavior**

That the setup is finished successfully after completing the initial indexing...
Actual behavior

Never finishing it but is stuck.
As described in the next cloud forum thread here:
https://help.nextcloud.com/t/mail-setup-stalling-stuck-in-a-loop/146696

**Mail app version**

1.13.8 on Nextcloud 24.0.5 (through Yunohost (https://github.com/YunoHost-Apps/nextcloud_ynh) )

**Mailserver or service**

Zimbra on yulpa.io

**Operating system**

Debian 10 with Yunohost (https://yunohost.org/whatsyunohost)

**PHP engine version**

PHP 8.0.24

**Web server**

Nginx

**Database**

MariaDB 10.5.15

**Comment by ChristophWurst** [comment]
I would appreciate some logs. Could you remove the account again, enable logging https://github.com/nextcloud/mail/blob/main/doc/admin.md#troubleshooting and reproduce another time?

Things to look out for: any errors in the horde_imap.log, errors in nextcloud.log.

**Comment by AngryWarrior** [comment]
@ChristophWurst 
I'll will enable the debug on this new installation and share some logs once I have it.

**Comment by AngryWarrior** [comment]
Hi @ChristophWurst 
I've sent you a email privately .

**Comment by ChristophWurst** [comment]
Please post the logs publicly next time so anyone can help solve this issue. Cheers.

**Comment by AngryWarrior** [comment]
Hi @ChristophWurst 
_Please post the logs publicly next time so anyone can help solve this issue. Cheers._
Right, I'll do that next time then. Thanks.
I just thought it would be easier/better if you could see the full raw logs.

Kind regards

**Comment by AngryWarrior** [comment]
**Memory Limit:**
I don't understand the memory limit though you mentioned. Because we had it on the suggested 512M. We have increased it to 1024M now. 

**The Mail app:**
As for the mailapp it self; the solution is to do the mySQL/MariaDB teaks then as described in your shared link: 
https://docs.nextcloud.com/server/stable/admin_manual/configuration_database/mysql_4byte_support.html ?

**Comment by ChristophWurst** [comment]
> Allowed memory size of 33554432 bytes exhausted

I guess you edited the php.ini for CLI, not for Apache.



> mySQL/MariaDB teaks

Yes. You received an email beginning with "📣 D" as per `Invalid datetime format: 1366 Incorrect string value: '\\xF0\\x9F\\x93\\xA3 D...' for column `nextcloud`.`oc_mail_messages`.`subject` `

**Comment by AngryWarrior** [comment]
Thanks for the reply.
Yes, php.ini was the one. For most web apps it is usally sufficent to give them the memory they need. 

> Yes. You received an email beginning with "📣 D" as per Invalid datetime format: 1366 Incorrect string value: '\\xF0\\x9F\\x93\\xA3 D...' for column `nextcloud`.`oc_mail_messages`.`subject`
We will look into upgrading/tweaking the database then. Hopefully it will solve the issue then.

Thanks Christof.

**Comment by AngryWarrior** [comment]
Ok, so the memory issue seemed to be fixed, but we are still getting errors from MariaDB. Sharing the log file this time as mentioned before.
https://pastebin.com/LS5rL95J

**Comment by ChristophWurst** [comment]
``\\xF0\\x9F\\x93\\xA3 D...`` is a valid UTF8 sequence. Did you follow https://docs.nextcloud.com/server/stable/admin_manual/configuration_database/mysql_4byte_support.html?

**Comment by AngryWarrior** [comment]
Well our VPS server is managed (so we do not have root access) and we asked the staff to do this but they are sort of confused over what is needed to be done with the database and yes I have given them your link.. 
So I guess I'm stuck in a catch 22.

**Comment by ChristophWurst** [comment]
That is unfortunate but if the database doesn't understand utf8 there is nothing nextcloud can do to work around it.

**Comment by AngryWarrior** [comment]
So it is all about configuring the database to understand and read utf8?
