### ISSUE TITLE
Deleting a folder / mailbox clears the entire right content area including background

### ISSUE THREAD

**Issue by jancborchardt** [nextcloud/mail#7406]
### Steps to reproduce

1. Delete a mailbox / folder via the left navigation
2. Observe the interface break

### Expected behavior

When deleting a folder / deleting a mailbox, Mail could automatically jump to open the Inbox of the same account? That would be similar to how we do it for deleting mails.

### Actual behavior

The content area gets wiped including background container:
![image](https://user-images.githubusercontent.com/925062/195051087-7312936b-0bb3-4539-bc63-7a0435cf4527.png)

### Mail app version

Current on cloud.nc.com

**Comment by jancborchardt** [comment]
@GretaD could be good to fix it for 25 because pre-25 this was not visible as we had a full white background, so from the visual perspective it looks like a regression even.

**Comment by ChristophWurst** [comment]
Label dropped because it was a duplicate of the attribute at https://github.com/orgs/nextcloud/projects/61. The priority does **not** change.
