### ISSUE TITLE
Context menu on folder shown below messages list.

### ISSUE THREAD

**Issue by roliverio** [nextcloud/mail#7409]
### Steps to reproduce

1. Open Mail app
2. Click on the "..." icon next to a folder

### Expected behavior

Pop-up / Context menu shown _above_ message list pane

### Actual behavior

Pop-up / Context menu shown _below_ message list pane

### Mail app version

1.14.0

### Mailserver or service

Dovecot

### Operating system

Debian 11.0

### PHP engine version

PHP 7.4

### Web server

Apache (supported)

### Database

MariaDB

### Additional info

Pop-up / Context menu is shown _below_ message list pane, at first i was suspicious of a browser issue but i've tested it on the latest versions of Firefox and Chrome. My guess is that is a simple css issue.

Screenshot attached.

![popup_menu_nextcloud_mail](https://user-images.githubusercontent.com/390821/195102125-4113b270-726a-4db3-a206-4b8e8b04382a.png)

**Comment by Mer0me** [comment]
Same behavior here, Windows 10 / Firefox 91.8.0 ESR

![image](https://user-images.githubusercontent.com/6248852/195852307-6bdca02c-5c76-4c4d-955a-f1c08212ca05.png)

**Comment by ChristophWurst** [comment]
Are you both on 1.14.0 or 1.14.1? In .1 we updated the component library that renders the menu.

**Comment by roliverio** [comment]
I can confirm that with the 1.14.1 update the issue went away.
