### ISSUE TITLE
made message-iframe height auto to use the remaining space (return of issue #3696)

### ISSUE THREAD

**Issue by valerebron** [nextcloud/mail#7424]
### Steps to reproduce

1. got to mail app
2. load an email

### Expected behavior

message-frame should be full-height, and message should be scrollable.

### Actual behavior

message-frame height is not in full height and not scrollable

### Mail app version

1.14.0

### Additional info

The bug appear on nextcloud 24.0.2 & both firefox & chromium.
![Screenshot from 2022-10-13 17-28-55](https://user-images.githubusercontent.com/1766587/195640245-c019b993-3e20-4549-baab-e627b2111209.png)

**Comment by st3iny** [comment]
Hey, I wasn't able to reproduce your issue. 

Could you please share the .eml file of this newsletter? That would certainly help with debugging the problem. Some emails have special formatting that break our resizing logic.

You can export the whole source in Nextcloud Mail using the `three dot menu on the top right` -> `More actions` -> `Download message`.

**Comment by valerebron** [comment]
Hi st3iny,
I paste the .eml file here : https://pastebin.com/J7P9VDip

It seems to occure for each html email. I'm still investigate.

**Comment by ChristophWurst** [comment]
Thanks a lot @valerebron! We'll have a look.

**Comment by elhananjair** [comment]
@ChristophWurst just to add to this, I am having this problem, the content of some emails won't wrap instead they are trimmed. 
![image](https://user-images.githubusercontent.com/69236638/195875196-c9532f56-d39b-4464-a692-b4f8f028e687.png)

**Comment by ChristophWurst** [comment]
> the content of some emails won't wrap instead they are trimmed

Sounds like https://github.com/nextcloud/mail/issues/7193.

**Comment by st3iny** [comment]
@valerebron I set up a Nextcloud 24 instance with Mail v1.14.0, imported your mail and wasn't able to reproduce your issue. Are you using a reverse proxy or change any CSPs? The iframe resizer has to communicate through frame boundaries and I imagine this might break if stricter CSPs are applied manually.

**Comment by valerebron** [comment]
what's CSPs ?
Indeed, I use a reverse-proxy (https://github.com/nginx-proxy/nginx-proxy).
All my configuration files are stored here : https://github.com/valerebron/pegaz/tree/master/services/nextcloud
I stil have Security & setup warnings I can't fix right now ...

**Comment by ChristophWurst** [comment]
https://developer.mozilla.org/en-US/docs/Web/HTTP/CSP

**Comment by valerebron** [comment]
Thanks for CSP definition link @ChristophWurst .
I fix the email height problem with adding
`OVERWRITEPROTOCOL: "https"`
![Screenshot from 2022-10-27 15-29-23](https://user-images.githubusercontent.com/1766587/198298514-b9a2a268-8e0c-4e53-99b1-6d443ff0038d.png)
Thanks for the help !

**Comment by ChristophWurst** [comment]
have a look at https://docs.nextcloud.com/server/stable/admin_manual/configuration_server/reverse_proxy_configuration.html
