### ISSUE TITLE
SMTP to Yahoo Small Business Email (currently Turbify.com)

### ISSUE THREAD

**Issue by jmfieza** [nextcloud/mail#7425]
### Steps to reproduce

The SMTP is working fine on NextCloud general settings > Email Server because it has a "Authentication required before sending emails" option. This same option is absent on Mail settings.
I need to use port 465 on SSL, but every request needs to be authenticated

I see you are updating very frequently, so found it interesting to share this concern. As it is actually working on Nextcloud, just not on Mail, I think it be rather practical to fix this.

Thanks.

### Expected behavior

Send Yahoo Small Business emails via SMTP port 465 as it is on NextCloud notifications.

### Actual behavior

It saves on imap server as DRAFTS and won't send in Mail App.
Nexlcloud is sending notifications normally.
![tela](https://user-images.githubusercontent.com/48530195/195655549-19d7f27c-0db1-44d1-b53f-60f1eed82355.png)

### Mail app version

1.14.1

### Mailserver or service

Yahoo Small Business (currently Turbify)

### Operating system

Linux 5.15.0-25-generic x86_64

### PHP engine version

PHP 8.1

### Web server

Nginx

### Database

MySQL

**Comment by ChristophWurst** [comment]
Please create a report at https://github.com/nextcloud/server/issues. This repo is for the *Mail app*, the IMAP client. Your issue is about the Nextcloud system emails.

**Comment by jmfieza** [comment]
No! I'm sorry if didn't write it very clear. It's about the Mail App.

I need the Mail App to do the same thing as the nextcloud system. I attached an image of the specific item.

I need the Mail App to have the "authentication required" in SMTP config, using port 465.

@ChristophWurst

**Comment by ChristophWurst** [comment]
I believe every SMTP connection will be authenticated if the server requests it. In doubt follow https://github.com/nextcloud/mail/blob/main/doc/admin.md#logging to get insights into the SMTP communication logs.

**Comment by jmfieza** [comment]
This is the only visible difference between Mail App and the System Email Server. As I said, the notifications are being normally sent by system. 

I will take a look at the link.

**Comment by jmfieza** [comment]
Here it is. I had to ask to my web hoster.
Another relevant information: the RainLoop app for nextcloud has an awful interface, but it has this checkbox for "authorization needed" and I could also send emails normally. So, the system and the RainLoop app can send emails, Just the Mail App cannot. I am pretty sure this checkbox is the only thing stopping smtp to work.

[nextcloud.log](https://github.com/nextcloud/mail/files/9823162/nextcloud.log)

**Comment by jmfieza** [comment]
forgot to mention @ChristophWurst

**Comment by ChristophWurst** [comment]
You don't have to mention me. Github notifies anyone who has been active in a ticket.

**Comment by jmfieza** [comment]
I'm afraid I coudn't hold the team anymore... We're migrating to Microsoft 365.
But hopefully this will help somebody in a near future.

**Comment by ChristophWurst** [comment]
Ok. If someone provides the SMTP logs as described at https://github.com/nextcloud/mail/blob/main/doc/admin.md#logging we can have another look.

**Comment by jmfieza** [comment]
Isn't it right over here?

Jorge Fieza 📲

Em qua., 9 de nov. de 2022 04:32, Christoph Wurst ***@***.***>
escreveu:

**Comment by jmfieza** [comment]
> Here it is. I had to ask to my web hoster. Another relevant information: the RainLoop app for nextcloud has an awful interface, but it has this checkbox for "authorization needed" and I could also send emails normally. So, the system and the RainLoop app can send emails, Just the Mail App cannot. I am pretty sure this checkbox is the only thing stopping smtp to work.
> 
> [nextcloud.log](https://github.com/nextcloud/mail/files/9823162/nextcloud.log)

Isn't it right here? On the link.

**Comment by miaulalala** [comment]
> > Here it is. I had to ask to my web hoster. Another relevant information: the RainLoop app for nextcloud has an awful interface, but it has this checkbox for "authorization needed" and I could also send emails normally. So, the system and the RainLoop app can send emails, Just the Mail App cannot. I am pretty sure this checkbox is the only thing stopping smtp to work.
> > [nextcloud.log](https://github.com/nextcloud/mail/files/9823162/nextcloud.log)
> 
> Isn't it right here? On the link.

`data/horde_smtp.log` :)
