### ISSUE TITLE
usability experience stuff I saw

### ISSUE THREAD

**Issue by kylepwarren** [nextcloud/mail#744]
- reply / send button weirdness - seems like it often says the wrong thing and is in the wrong transparent/disable visual state. Not exactly sure how to recreate, try this. open a draft.

- delete: works ok I guess, though no confirmation. feel pretty sure a checkbox system, like for files in nextcloud would be good improvement.
    *also, would be nice to have folder actions, like mark as read, or delete all. may be able to achieve (possible with drag drop to folder) things like this, but I didn't see it in places I looked[where they usually are in email clients]

**Comment by ChristophWurst** [comment]
Thank you for your feedback.

> reply / send button weirdness - seems like it often says the wrong thing and is in the wrong transparent/disable visual state. Not exactly sure how to recreate, try this. open a draft.

Please provide some steps to reproduce.



> delete: works ok I guess, though no confirmation. feel pretty sure a checkbox system, like for files in nextcloud would be good improvement.
> *also, would be nice to have folder actions, like mark as read, or delete all. may be able to achieve (possible with drag drop to folder) things like this, but I didn't see it in places I looked[where they usually are in email clients]

Please file a separate ticket for the multi selection.

Thanks.

**Comment by ChristophWurst** [comment]
No info provided -> closing

Thank you for your report.
