### ISSUE TITLE
Mail app: importing *.ics files no longer works

### ISSUE THREAD

**Issue by maxi322** [nextcloud/mail#7444]
### Steps to reproduce

1. get E-Mail sent with an *.ics File attached
2. click on "Import into calendar"
3. nothing happens, no further menue opens

### Expected behavior

after clicking on "Import into calendar" a select option should appear in wich calender the event shoud be added.

### Actual behavior

The select option for the wanted caldendar never appears

### Mail app version

1.14.1

### Operating system

Debian

### PHP engine version

PHP 8.1

### Web server

Apache (supported)

### Database

MySQL

### Additional info

I tested this behaiviour on my test cloud where version 1.13.9 was still installed of the mail app. It did work there, after updating to 1.14.1 the problem also appeared on my test cloud

**Comment by miaulalala** [comment]
I can reproduce. The PROPFIND for the Calendars works but the modal doesn't appear.

**Comment by PaperTowels207** [comment]
I can also confirm this. HTTP access logs show `"PROPFIND /remote.php/dav/calendars/username/ HTTP/1.1"` -- but nothing resolves after this. Nothing in Nextcloud or HORDE logs. 

Unsure if related but html buttons in calendar invites from outside Nextcloud users also no longer showing as html.

**Comment by PaperTowels207** [comment]
I attempted the mail update to 1.14.3 as well as Nextcloud update to 24.0.7, as the changelogs showed some cal/DAV changes I thought would help, but am still experiencing the same issue. Has anyone else had success in remedying this?

**Comment by PaperTowels207** [comment]
Updated again today, Mail 1.14.5 and NC 24.0.8. Still same issue. I did find this support thread from a year ago:

https://help.nextcloud.com/t/default-calendar-for-appointments-via-email/129361/4 

I can confirm that `SELECT * FROM oc_preferences WHERE appid='dav' AND configkey='defaultCalendar'` does not return any values. I checked the `oc_preferances` table and no users have it set. I also verified that the URI of the calendar for users does read as `personal` Additionally, the function to create a calendar of that URI if one is not present is working as intended. Deleting the Calendar works, but the next time a `PROPFIND` is called, the calendar is re-made.

I am guessing if manually setting the default calendar was possible, it would resolve the .ics import.  However, the `configkey='defaultCalendar'` is not something I have been able to locate.

**Comment by etique57** [comment]
I confirm, same issue here on NC 25.0.2 and Mail 2.2.1

**Comment by maxi322** [comment]
Today I updated to NC 25.0.3, Mail 2.2.3 and Calendar 4.2.3, the issue is still present.
Although the menu now pops up, but when you want to select a calendar to add the event to nothing happens.

**Comment by max65482** [comment]
I found out why this happens:
This part (the calendar selection)
https://github.com/nextcloud/mail/blob/b1b1f50d2d94fb1b8649dd9a89504f3a0a13696f/src/components/MessageAttachment.vue#L66-L75
was moved inside `<Actions>`. There it won't be rendered.
Anyway, I couldn't figure out how to fix this nicely.

**Comment by ChristophWurst** [comment]
@GretaD can you help with ^?

**Comment by GretaD** [comment]
Sorry, i missed this ping, will check it out
