### ISSUE TITLE
Account action menu unusable

### ISSUE THREAD

**Issue by ChristophWurst** [nextcloud/mail#7446]
### Steps to reproduce

1. Configure an account
2. Open the account's action menu

### Expected behavior

I'm able to see all actions

### Actual behavior

![Bildschirmfoto vom 2022-10-18 09-47-05](https://user-images.githubusercontent.com/1374172/196368902-e5377fa1-0448-4d9b-a924-1852eaa4041e.png)

### Mail app version

2.1.0 alpha 3

**Comment by ChristophWurst** [comment]
This only happens with `@nextcloud/vue` v7.0.1

**Comment by GretaD** [comment]
it happens in all action menus i think
https://github.com/nextcloud/mail/pull/7440#issuecomment-1280435371

**Comment by GretaD** [comment]
i cannot reproduce this error anymore on stable2.0 after releasing 2.0.3 or main

**Comment by ChristophWurst** [comment]
It doesn't exist yet because main uses `@nextcloud/vue:7.0.0`. This only happens once we upgrade or when you link during development.

**Comment by GretaD** [comment]
yes, thats what i did, and i know i tested it right, because i found another regression on 7.0.1 on main :D

**Comment by ChristophWurst** [comment]
let's cross the river when we get there
