### ISSUE TITLE
Form fields in dark mode have white background in settings menu

### ISSUE THREAD

**Issue by miaulalala** [nextcloud/mail#7449]
### Steps to reproduce

![image](https://user-images.githubusercontent.com/7427347/196487844-4d01eead-eaa8-45b4-a688-b604725dc7e6.png)

### Expected behavior

Colour is used throughout

### Actual behavior

White BG is peeking through

### Mail app version

2.0

### Mailserver or service

c.nc

**Comment by ChristophWurst** [comment]
@GretaD is this fixed by https://github.com/nextcloud/mail/pull/7469?

**Comment by GretaD** [comment]
> @GretaD is this fixed by #7469?

it is fixed by this one: https://github.com/nextcloud/mail/pull/7374
