### ISSUE TITLE
Allow users to choose the Inbox that is shown on startup

### ISSUE THREAD

**Issue by bpcurse** [nextcloud/mail#745]
A nice customization option would be letting the user choose a specific Inbox to show on startup rather than "All Inboxes".
*EDIT*
... or even better every accessible folder.

**Comment by ChristophWurst** [comment]
That sounds like a rather specific use case to me and nothing 90% of our users would use as the usually most important folder is the inbox.

cc @nextcloud/mail

**Comment by bpcurse** [comment]
I agree that choosing a special subfolder to open is uncommon (although we have a use case for this).

But enabling the user to select an Inbox to open on start seems to be a helpful feature. In a multi mailbox setup with different priorities the contents of "all inboxes" can be confusing.

**Comment by jancborchardt** [comment]
@bpcurse could you describe your scenario? This might us find a better solution rather than just proposing a solution outright. :)

For example, an alternative and more automatic solution would be to simply remember the last open folder and open that next time you go to the Mail app.

**Comment by bpcurse** [comment]
@jancborchardt First I have to explain the structures we have built and we are using at the moment as they are slowly becoming complex. I will try to keep it as short as possible.
We are a students association and are currently integrating Nextcloud as a central workspace for all students participating in our different teams and work groups. Every member can be active core, active or passive and can be part of one or more work groups and teams.

Regarding mail there are personal mail accounts at our domain.xy for some active people and additional non-personalized accounts for the teams and work groups (like firstname.lastname@domain.xy, workgroup@domain.xy, team@domain.xy and our central info@domain.xy account).
As the credentials to Nextcloud and our personal mail accounts have been standardized, everyone with a personal account now has automated access thanks to mail app's great "default account" feature.
There are postmasters who work through the load of mails on our central account and move the ones to discuss in our weekly meetings to a specific folder "to discuss".

How to automate access to the central account and the team / work group accounts for the different member groups without the need to supply mail server credentials to all users and optionally make the account read only for specific groups / users is another topic, as discussed in https://github.com/nextcloud/mail/issues/572.

Provided that it will be possible to define a default account with stored credentials at admin level for a group or individual (see external storage app) it would be nice to be able to define as well that e.g. the group members of "active" and "passive" simply click on mail immediately showing the "to discuss" folder of our central account mentioned earlier (we have many subfolders and a steady exchange of people). Users who have additional accounts set up should be able to change which folder / inbox is shown on access to mail.

I hope this didn't go too much beyond the scope of this discussion.
