### ISSUE TITLE
Search box on mail should be sticky

### ISSUE THREAD

**Issue by GretaD** [nextcloud/mail#7454]
### Steps to reproduce

1. Open mail and go to inbox
2. Scroll the envelope list
3. See search box move with the envelopes

### Expected behavior

The search box stays always sticky on the top 

### Actual behavior

it scrolls up

### Additional info

![Screenshot from 2022-10-19 11-11-02](https://user-images.githubusercontent.com/12728974/196649957-c215c64c-d849-4c40-8adb-b2df7da8d010.png)

**Comment by GretaD** [comment]
duplication

**Comment by ChristophWurst** [comment]
of?
