### ISSUE TITLE
Signature in mail reply

### ISSUE THREAD

**Issue by Speed7811** [nextcloud/mail#7456]
### Is your feature request related to a problem? Please describe.

1. Configure signature
2. Create new mail -> signature is displayed -> OK
3. Answer a mail -> Signature is not displayed 

### Describe the solution you'd like

When I replay a mail the signature should be added (maybe this can be configurable like in Outlook)

**Comment by GretaD** [comment]
Hello,

We can add a signature via account settings 
![Screenshot from 2022-10-19 15-31-51](https://user-images.githubusercontent.com/12728974/196705909-adfe6b16-1e52-449c-9840-e0b9b2c16b86.png)

and that signature you have added in signature box, should be shown everytime you reply to an email.

**Comment by Speed7811** [comment]
Hi Greta,

this doesn't work for me. Only when I create a new mail it works - not on reply.

![1](https://user-images.githubusercontent.com/25704388/196711716-0b27bbf0-745d-47ca-81d5-c43f9be62391.jpg)
![2](https://user-images.githubusercontent.com/25704388/196711719-905e12c5-63aa-4431-ab32-1254d1d888b6.jpg)

**Comment by GretaD** [comment]
ohh i thought you we were asking for a feature request. Because you used the feature request template and not the bug one. Can you please tell me which version of mail are you using? And if you have any error when you try to reply to an email on your console for example.

**Comment by Speed7811** [comment]
Hi Greata,

I thought this was a missing feature because I don't know that this was already implemented. Therefore it is ok to close this issue. I created a new one with the category "Bug" (#7460). Therefore it is okay to close this issue.
