### ISSUE TITLE
Allow users to choose to not automatically mark E-Mails as "read" or after a period of time

### ISSUE THREAD

**Issue by bpcurse** [nextcloud/mail#746]
The first E-Mail in the list is always marked as read as soon as mail app is accessed. Along with the missing option to mark as unread, this is disadvantageous in co-working settings.

A "Settings" Option "Do not mark as read" or "Mark as read after xxx seconds" could help.
The manual "mark as read" option proposed in https://github.com/nextcloud/mail/issues/744 should then be available for single mails.

**Comment by ChristophWurst** [comment]
> option to mark as unread

Hidden feature: press `u` to mark as unread. This is a duplicate of https://github.com/nextcloud/mail/issues/205

**Comment by bpcurse** [comment]
Thank you and sorry for the duplicate!
