### ISSUE TITLE
Signature in mail reply not working

### ISSUE THREAD

**Issue by Speed7811** [nextcloud/mail#7460]
### Steps to reproduce

1. Configure signature in account setting
2. Reply on mail

### Expected behavior

Signature will be added

### Actual behavior

Signature wasn't added. See attachments.

![1](https://user-images.githubusercontent.com/25704388/196712326-500a1ba6-de04-4d6c-9ac7-4843f578a3f3.jpg)
![2](https://user-images.githubusercontent.com/25704388/196712329-13f63df4-0fc9-4996-b2d4-bfa4d10cb9d1.jpg)

### Mail app version

1.14.1

**Comment by ChristophWurst** [comment]
Summoning our signature connoisseur @kesselb :eyes:

**Comment by kesselb** [comment]
Hi, thanks for your bug report.

Should be fixed by https://github.com/nextcloud/mail/pull/7477 and will be released soon.
