### ISSUE TITLE
2.1.0-rc.1: Server error

### ISSUE THREAD

**Issue by jakobroehrl** [nextcloud/mail#7463]
### Steps to reproduce

1. install the 2.1.0-rc.1 version
2. start the mai app

### Expected behavior

no error

### Actual behavior

error:

[index] Fehler: BadFunctionCallException: archiveMailboxId is not a valid attribute at <<closure>>

 0. /var/www/nextcloud/lib/public/AppFramework/Db/Entity.php line 165
    OCP\AppFramework\Db\Entity->setter()
 1. /var/www/nextcloud/lib/public/AppFramework/Db/Entity.php line 73
    OCP\AppFramework\Db\Entity->__call()
 2. /var/www/nextcloud/lib/public/AppFramework/Db/QBMapper.php line 322
    OCP\AppFramework\Db\Entity::fromRow()
 3. /var/www/nextcloud/lib/public/AppFramework/Db/QBMapper.php line 362
    OCP\AppFramework\Db\QBMapper->mapRowToEntity()
 4. /var/www/nextcloud/apps/mail/lib/Db/MailAccountMapper.php line 115
    OCP\AppFramework\Db\QBMapper->findEntity()
 5. /var/www/nextcloud/apps/mail/lib/Service/Provisioning/Manager.php line 197
    OCA\Mail\Db\MailAccountMapper->findProvisionedAccount()
 6. /var/www/nextcloud/apps/mail/lib/Http/Middleware/ProvisioningMiddleware.php line 71
    OCA\Mail\Service\Provisioning\Manager->provisionSingleUser()
 7. /var/www/nextcloud/lib/private/AppFramework/Middleware/MiddlewareDispatcher.php line 97
    OCA\Mail\Http\Middleware\ProvisioningMiddleware->beforeController()
 8. /var/www/nextcloud/lib/private/AppFramework/Http/Dispatcher.php line 125
    OC\AppFramework\Middleware\MiddlewareDispatcher->beforeController()
 9. /var/www/nextcloud/lib/private/AppFramework/App.php line 172
    OC\AppFramework\Http\Dispatcher->dispatch()
10. /var/www/nextcloud/lib/private/Route/Router.php line 298
    OC\AppFramework\App::main()
11. /var/www/nextcloud/lib/base.php line 1047
    OC\Route\Router->match()
12. /var/www/nextcloud/index.php line 36
    OC::handleRequest()

GET /apps/mail/
from 87.147.192.228 by jakob at 2022-10-19T18:50:09+02:00

**Comment by jakobroehrl** [comment]
Now it's working. 
I activated the app again and now I have no errors.

**Comment by ChristophWurst** [comment]
Did you also restart your server?

**Comment by jakobroehrl** [comment]
I did, how you know?

**Comment by ChristophWurst** [comment]
Because of the findings in https://github.com/nextcloud/mail/issues/7407. This seems to be an opcache issue but if you answer me 

> Do you have https://github.com/nextcloud/mail/blob/stable2.1/lib/Db/MailAccount.php#L141-L142?

I could be more certain about it.

**Comment by jakobroehrl** [comment]
> Do you have https://github.com/nextcloud/mail/blob/stable2.1/lib/Db/MailAccount.php#L141-L142?

What do you mean by that? How can I find out?

**Comment by ChristophWurst** [comment]
Check the file on your installation. Does the class have those lines?

**Comment by jakobroehrl** [comment]
yes, its there

**Comment by ChristophWurst** [comment]
Good. Then it's the fault of opcache.

**Comment by meichthys** [comment]
I'm also seeing a similar issue when I upgraded from 25.0.0RC5 to 25.0.1RC1:

![image](https://user-images.githubusercontent.com/10717998/199759304-a8139758-6433-4de4-9d5c-024e6d44c5dc.png)

I do remember following the tuning guide here: https://docs.nextcloud.com/server/latest/admin_manual/installation/server_tuning.html#enable-php-opcache , but after checking my php-fpm `php.ini` config, `opcache.validate_timestamps` is commented out.

The admin apps page indicates I'm on Mail v 2.0.3
