### ISSUE TITLE
Keep search box and filter menu visible when scrolling

### ISSUE THREAD

**Issue by meichthys** [nextcloud/mail#7474]
### Describe the solution you'd like

It would be nice to keep the search bar and filter menu visible when scrolling down the message list:

Currently:
![image](https://user-images.githubusercontent.com/10717998/197193776-3b1eae58-f55f-46e4-a36e-d6bbc4622319.png)

Proposed:
![image](https://user-images.githubusercontent.com/10717998/197193832-060d99cd-b85b-4e6a-9324-15d0d1332478.png)

### Describe alternatives you've considered

The current solution works, but it always feels strange to have a menu floating above the email list:
![image](https://user-images.githubusercontent.com/10717998/197193947-c32dc09f-9f0f-4fb7-aba2-8117e5e0a189.png)

**Comment by ChristophWurst** [comment]
:eyes: @sazanof @GretaD

**Comment by GretaD** [comment]
yes, duplication of https://github.com/nextcloud/mail/issues/7454 (closing mine since this one has better screenshots)

**Comment by GretaD** [comment]
fixed here btw: https://github.com/nextcloud/mail/pull/7461
