### ISSUE TITLE
Mail Dashboard widgets are larger than other's

### ISSUE THREAD

**Issue by Emporea** [nextcloud/mail#7480]
### Steps to reproduce

1. Use Unread or Important Mail Dashboard Widget
2. Also add other widgets
3. See the height difference

### Expected behavior

Should be the same height

### Actual behavior

Has different heights

### Mail app version

2.0.3

### PHP engine version

PHP 8.1

### Web server

Nginx

### Database

MariaDB

### Additional info

![image](https://user-images.githubusercontent.com/21969523/197337900-b25ba4e7-4d28-42fa-b8a1-b694b189116c.png)

**Comment by ChristophWurst** [comment]
is there a ticket?

**Comment by GretaD** [comment]
> is there a ticket?

i remember a conversation on frontend chat related to this, i couldnt find a ticket. I can open one
