### ISSUE TITLE
"+ New message" button in a left sidebar is cut-off and has a duplicate on mail list sidebar

### ISSUE THREAD

**Issue by JuliaKirschenheuter** [nextcloud/mail#7484]
### Steps to reproduce

1. Open Mail App

![20221024_115404](https://user-images.githubusercontent.com/6078378/197514118-08a47847-be91-4910-8cc5-fc1eb3ff156e.png)

### Expected behavior

Button have no duplicates and isn't cut-off

### Actual behavior

See that button is completely cut-off and duplicate itself

### Mail app version

v2.1.0-rc1

**Comment by ChristophWurst** [comment]
I can not reproduce on our internal instance. It runs 2.1.0 RC1

**Comment by JuliaKirschenheuter** [comment]
> is this on outbox julia? if yes, that is fixed here #7461

I've updated everything, cleared cache, but still have it ;( What could be wrong with my environment?

**Comment by jancborchardt** [comment]
I can reproduce the duplicate button part in the Outbox on currently deployed version on cloud. and tech-preview. @GretaD – is that the issue fixed by #7461?

![image](https://user-images.githubusercontent.com/925062/201355679-4d7d9c0c-6208-43e6-8239-5fc41c8c34f4.png)

**Comment by GretaD** [comment]
this is fixed
