### ISSUE TITLE
Ability to archive emails

### ISSUE THREAD

**Issue by thstyl2000** [nextcloud/mail#7496]
### Is your feature request related to a problem? Please describe.

The app becomes sometimes unresponsive, when working with large mailboxes.

### Describe the solution you'd like

Would be great to be able to archive emails in a date-subfolder structure like thunderbird (and add an extra button "Archive" in the three-dot menu).

### Describe alternatives you've considered

Sieve filtering. But it seems complicated (at least for me...).

**Comment by ChristophWurst** [comment]
Dup of https://github.com/nextcloud/mail/issues/22

This feature will come with v2.1

**Comment by kylecoberly** [comment]
Did this come in 2.1? I'm still not seeing it

**Comment by Quix0r** [comment]
With POP3 you really don't need an archive management with Nextcloud, with IMAP-only servers it makes more sense to have it implemented because people might want to archive their mails (format of folders e.g. `Archive/YYYY-MM/<Inbox|Sent|...>`) with Nextcloud mail client, too.
