### ISSUE TITLE
Encoding problem with outgoing messages

### ISSUE THREAD

**Issue by Thomas-AIRS-Informatique** [nextcloud/mail#7497]
### Steps to reproduce

1.Hello, I just realized that I have a formatting problem with sending emails via the Mail application. I am on version 2.0.3. Formatting is enabled in the app. On Nextcloud version 25.0.0
2.
3.

### Expected behavior

Correct text formatting

### Actual behavior

For exemple : 
`Je reste Ã  votre disposition pour tout complÃ©ment d'information. `

### Mail app version

2.0.3

### Mailserver or service

IMAP

### Operating system

Ubuntu 20.04

### PHP engine version

PHP 7.4

### Web server

Apache (supported)

### Database

PostgreSQL

### Additional info

Hello, I just realized that I have a formatting problem with sending emails via the Mail application. I am on version 2.0.3. Formatting is enabled in the app.
For exemple : `Un exemple : Je reste Ã  votre disposition pour tout complÃ©ment d'information. `

**Comment by Thomas-AIRS-Informatique** [comment]
I performed a test on version 1.6.3 on Nextcloud v24.0.6 and there is no problem.

**Comment by Extarys** [comment]
Happens to me also on Nextcloud 25.0.0 with Mail v2.0.3.
It didn't happen on Nextcloud 24.x

All accents are broken. Let me know if you need someone to test potential fixes/configuration changes.

**Comment by jejusek** [comment]
Does anyone know a way to fix this fault? Let me mention that the national characters in the subject line are correct. Only in the text of the message, the recipient gets strange letters.
I will be grateful. I like to use this app to reply to email.

**Comment by bastien-sansas** [comment]
Hello, it's a critical issue for many people. The application is broken for a lot of non-English communities. We can just send plain text. 

There is also a problem with the content preview of incoming mail (in the mails list). For instance, accent characters are replaced by '?'.

In fact, the problem seems to be appearing when the mail is in rich text mode.

Thanks for your contribution to this project and your work.

**Comment by mvalberto** [comment]
Same problem in spanish, nextcloud 25.0.1, and mail app 2.1.0,  it's a critical issue.

**Comment by ChristophWurst** [comment]
Outgoing messages are temporarily stored in a database table `oc_mail_loca_messages`. Could this be an issue with the utf8 support of your db?

Check https://docs.nextcloud.com/server/stable/admin_manual/configuration_database/mysql_4byte_support.html if you use mysql/mariadb.

**Comment by mvalberto** [comment]
Good morning, that does not seem to be the problem, I have additionally performed the process described in the link, but the problem continues.
![image](https://user-images.githubusercontent.com/81685321/200268861-52e66b49-d3c1-4553-b628-586490e098b1.png)

**Comment by df911** [comment]
Hello,
The mail is correctly formatting in oc_mail_local_messages table but the error is still present after sending the message.


> Compose a new message an schedule it for tomorrow so that it isn't sent immediately. Then inspect the latest row in oc_mail_local_message. Is the message body encoding correct?

**Comment by mvalberto** [comment]
Thanks, I will try it after hours, I have reverted the snapshot to make everything work correctly in version 24.0.7.

**Comment by miaulalala** [comment]
I can reproduce: 
![image](https://user-images.githubusercontent.com/7427347/200317355-5f2ca634-3646-4876-80a9-c904bb5782d0.png)

mail_local_messages body content seems fine:

**Comment by miaulalala** [comment]
Notable: the text part is wrong, the HTML part is fine. So why is the HTML part not displayed?

**Comment by miaulalala** [comment]
Ok, debug finished:

For everyone needing a quick fix, please check your account settings and set your writing mode. That will fix the issue.

As a code fix, looks like the default assumption when the writing mode is not set is `$isHtmlMessage = true` which then mangles your messages through the Html2text filter:

![image](https://user-images.githubusercontent.com/7427347/200336163-d478819b-38e0-445e-9ade-5eebc0e63487.png)

The default writing mode should probably be set to false as a default.

**Comment by Chartman123** [comment]
> set your writing mode. That will fix the issue.

Can't confirm... The mode was already set to Rich Text. I switched it to Plain Text and back to Rich Text, but this didn't fix the issue. In Plain Text mode, everything is correctly encoded.

**Comment by miaulalala** [comment]
Good to know, so the issue is with rich text and possibly CKEditor. @kesselb you're the expert there :)

**Comment by fix** [comment]
Note this is really showstopper for us, as rich text is enabled by default when you answer to html message (whatever the option chosen in the config). You have to think to remove formatting for virtually any answer.... I would rank this as high priority

**Comment by kesselb** [comment]
Thanks for your reports :+1: 

Would you mind trying https://github.com/nextcloud/mail/pull/7575 and tell us if it fixes the encoding issues?

**Comment by Chartman123** [comment]
> tell us if it fixes the encoding issues?

Works for me :)

**Comment by cardaris** [comment]
@kesselb I second that works. Great job!

However, the previews of the incoming HTML messages still need to be fixed as well.
Please let us know when there is a fix for that. Thanks!

**Comment by kesselb** [comment]
Hi,

https://github.com/nextcloud/mail/pull/7586 is another try to fix the preview.

**Comment by kesselb** [comment]
Hi @Thomas-AIRS-Informatique, @fix, @Chartman123 & @cardaris :wave:

Could you help us to test another patch: https://github.com/nextcloud/mail/pull/8499

The old patch, to convert the mail body to html-entities, is deprecated with PHP 8.2, so we need a different solution.
