### ISSUE TITLE
Support CRAM-MD5 and DIGEST-MD5 support for SMTP

### ISSUE THREAD

**Issue by chuck-r** [nextcloud/mail#7505]
### Is your feature request related to a problem? Please describe.

I am trying to integrate several corporate email accounts with NextCloud, but I'm running into an issue with SMTP authentication. It appears that the SMTP server we have to connect to requires the "Encrypted Password" authentication method rather than plain-text password (despite their use of STARTTLS). I was able to determine this with Thunderbird's account setup wizard. Unfortunately, I'm unable to give too much further information.

However, I noticed that NextCloud's Mail app doesn't allow to specify an authentication type on SMTP (or, IMAP). Because I cannot tell NextCloud's Mail app that I want to use the "encrypted password" authentication method, I'm unable to connect our corporate email accounts to it.

### Describe the solution you'd like

1. Ability to authenticate using the "encrypted password" authentication method
2. A combo box to select the authentication type in the "Manual" setup portion of the NextCloud Mail app

### Describe alternatives you've considered

Unfortunately, for me there is no "alternative" since I don't control the SMTP server I'm trying to connect to.

**Comment by ChristophWurst** [comment]
The app, or more specifically the Horde IMAP library, automatically negotiates the best auth method for your IMAP/SMTP connection depending on what the server advertises as its capabilities.

Do you know the technical term fo the "encrypted password" method? Then I could scan the Horde code for it.

**Comment by dl6dbh** [comment]
probably the same problem with office365 and gmail ?

**Comment by ChristophWurst** [comment]
So you are requesting `XOAUTH2` support?

**Comment by chuck-r** [comment]
Another cursory glance over the Horde code suggests that it [requires Horde/Auth availability](https://github.com/nextcloud/horde-smtp/blob/6449ee9e8894876bb796dd9b1d6d995ebe86617d/lib/Horde/Smtp.php#L449). As much as I'd like to see this feature, I don't understand the codebase enough to be able to maintain a new repository.

**Comment by ChristophWurst** [comment]
> it [requires Horde/Auth availability](https://github.com/nextcloud/horde-smtp/blob/6449ee9e8894876bb796dd9b1d6d995ebe86617d/lib/Horde/Smtp.php#L449).

I'm not sure if that is what the code means. 

The SMTP communication starts like this

```
>> Fri, 08 Jan 2021 14:35:29 +0000
>> Connection to: smtp://smtp.hoster.domain:587
S: 220 mx.hoster.domain ESMTP Exim 4.94 Fri, 08 Jan 2021 15:35:29 +0100
C: EHLO localhost
S: 250-mx.hoster.domain Hello localhost [1.2.3.4]
S: 250-SIZE 157286400
S: 250-8BITMIME
S: 250-PIPELINING
S: 250-X_PIPE_CONNECT
S: 250-AUTH PLAIN LOGIN
S: 250-CHUNKING
S: 250-STARTTLS
S: 250 HELP
C: STARTTLS
S: 220 TLS go ahead
>> Successfully completed TLS negotiation.
C: EHLO localhost
S: 250-mx.hoster.domain Hello localhost [1.2.3.4]
```

^ here the `AUTH` parameter has the values `PLAIN` and `LOGIN`. This advertises the supported authentication methods.

Horde will try those in https://github.com/nextcloud/horde-smtp/blob/6449ee9e8894876bb796dd9b1d6d995ebe86617d/lib/Horde/Smtp.php#L912-L1021. 

`CRAM-MD5` is there by default. `DIGEST-MD5` requires the `Horde_Imap_Client_Auth_DigestMD5` class. That class comes with the Horde/ImapClient package, which we ship. So both of the auth methods should work already.

I suggest you look into SMTP logging via https://github.com/nextcloud/mail/blob/main/doc/admin.md#logging to find out what your server advertises for `AUTH` and how Horde tries to connect.

**Comment by chuck-r** [comment]
Well, don't I feel a bit dumb. Turns out, the whole issue was that on my VPS outgoing SMTP is blocked. I hadn't considered that at all. I figured this out when the SMTP log was totally empty, whereas the IMAP log looked good.

Sorry to waste your time.

**Comment by ChristophWurst** [comment]
All good :v:
