### ISSUE TITLE
Attachments not saved to drafts

### ISSUE THREAD

**Issue by MagsMagnoli** [nextcloud/mail#7507]
### Steps to reproduce

1. Create an email with an attachment and wait for it to be saved to drafts
2. View it in drafts and see the attachment is not there

### Expected behavior

Attachments should be saved in draft emails

### Actual behavior

Attachments are lost in draft emails

### Mail app version

1.14.1

### Operating system

Ubuntu

### Web server

Apache (supported)

### Database

MySQL

**Comment by ChristophWurst** [comment]
Dup of https://github.com/nextcloud/mail/issues/458
