### ISSUE TITLE
encoding issue when replying from mail app on mobile browser

### ISSUE THREAD

**Issue by MariusQuabeck** [nextcloud/mail#7508]
### Steps to reproduce

1. receive an email with umlauts
2. reply from safari on ios via mail app, reply also containing umlauts
3. that reply and quoted text will then have encoding issues 
4. important to note, while replying in step 2, umlauts and quoted text looks fine, this happens during sending

this is not only a display bug, this is also what the text will look like when opened in another email app
this is on c.nc.c
![image](https://user-images.githubusercontent.com/17063564/199213247-31a675dd-e8a7-4b4e-bb5f-b072ed38c223.png)

### Expected behavior

umlauts being displayed correctly all the time

### Actual behavior

umlauts in a reply breaking main mail text + quoted text

**Comment by GretaD** [comment]
thank you Marius, theres already a ticket for that: https://github.com/nextcloud/mail/issues/7508 and we will keep track there.
