### ISSUE TITLE
Switching from one mailbox to a different one doesn't load the right thread

### ISSUE THREAD

**Issue by miaulalala** [nextcloud/mail#7511]
### Steps to reproduce

1. Open inbox
2. open a message that is not in the priority inbox
3. go to priority inbox
4. see righmost column still loads the old message 
![image](https://user-images.githubusercontent.com/7427347/199483079-8b718a97-5d26-45f9-87ed-9714fa8a769d.png)

### Expected behavior

The rightmost column loads the first message of the current mailbox

### Actual behavior

The message loaded is the previous message.
The threading GET seems to contain the wrong ID:

```
GET /index.php/apps/mail/api/messages/36152/thread HTTP/1.1
Accept: application/json, text/plain, */*
Accept-Encoding: gzip, deflate
Accept-Language: en-GB,en;q=0.9,de-AT;q=0.8,de;q=0.7,en-US;q=0.6
Cache-Control: no-cache
Connection: keep-alive
Cookie: oc_sessionPassphrase=**********; nc_sameSiteCookielax=true; nc_sameSiteCookiestrict=true; XDEBUG_SESSION=XDEBUG_ECLIPSE; nc_username=admin; ******; nc_token=******; nc_session_id=*******
DNT: 1
Host: nextcloud.local
Pragma: no-cache
User-Agent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/107.0.0.0 Safari/537.36
requesttoken: *******
```

### Mail app version

2.1.0-rc.1

### Mailserver or service

gmx

### Operating system

Ubuntu 20

### PHP engine version

PHP 8.0

### Web server

Apache (supported)

### Database

MySQL

**Comment by ChristophWurst** [comment]
I can't reproduce this. Neither with 1.14 nor 2.2/main. When I navigate to PI the URL changes to `/apps/mail/box/priority` and then opens the first message in PI's *Other*.

**Comment by mat-m** [comment]
With NC25 and Mail 2.0.3, I have the same behavior as Christoph

**Comment by miaulalala** [comment]
Can't reproduce either
