### ISSUE TITLE
Double-scrollbar in certain screenresolutions and threads

### ISSUE THREAD

**Issue by szaimen** [nextcloud/mail#7521]
### Steps to reproduce

1. Open mail
2. open mail with threading
3.

### Expected behavior

Should not show double-scrollbar

### Actual behavior

Shows it

### Mail app version

Latest (dont know, is on c.nc.c)

### Mailserver or service

?

### Operating system

?

### Additional info

![20221104_113926](https://user-images.githubusercontent.com/42591237/199969473-300b2a96-7f71-4cca-bdc7-5aa638c63fae.png)

**Comment by st3iny** [comment]
I successfully reproduced the issue and am working on a fix.
