### ISSUE TITLE
Cannot edit account parameters

### ISSUE THREAD

**Issue by chrisaga** [nextcloud/mail#7537]
### Steps to reproduce

1. Open "Account Parameter" via the account `...` menu
2. Change something (host addres, mail address, user name)
3. The save button remains grayed, you cannot save your new parameters

NB. Add/Delete aliases and signature editing do work.

### Expected behavior

Save button changes color and you could actually save new parameters

### Actual behavior

The save button remains grayed, you cannot save your new parameters

### Mail app version

1.14.2

### Mailserver or service

no relevant

### Operating system

Linux 5.16.12-paas x86_64

### PHP engine version

PHP 8.0

### Web server

Apache (supported)

### Database

MySQL

**Comment by ChristophWurst** [comment]
Condition for the disabled button: 
https://github.com/nextcloud/mail/blob/v1.14.2/src/components/AccountForm.vue#L240
https://github.com/nextcloud/mail/blob/v1.14.2/src/components/AccountForm.vue#L336-L346

so either one of those inputs is missing (password?) or the email address is invalid

**Comment by chrisaga** [comment]
OK. You are right, I didn't enter the passwords. In my defense, it's the first time I have to deal with a profile parameter form which forces to enter password if I doesn't want to change it.
That said It doesn't solve my issue since I wanted to switch the email with an alias, so the alias would be used by default to send and reply to emails.
I will open a more specific issue.
