### ISSUE TITLE
Respect Reply-To headers

### ISSUE THREAD

**Issue by chuck-r** [nextcloud/mail#7538]
### Is your feature request related to a problem? Please describe.

When replying to an email with a Reply-To header, the reply is created with a To address of the original sender (From header).

### Describe the solution you'd like

The Reply button should create a new message with a To address matching the Reply-To header, if set.

### Additional context

Our corporate email server sends us emails from a no-reply address, with a Reply-To header containing the customer's input email address. In other clients when we hit Reply to reply to the message, a reply is sent to the customer's email (rather than the no-reply email address in the From header). However, Nextcloud Mail doesn't appear to respect the Reply-To header and creates a new message directly to the original sender (the From header). This breaks my workflow a bit since I have to change the To address every time.

**Comment by Aonrud** [comment]
FYI, this duplicates #4075
