### ISSUE TITLE
"loading messages" spinner overlays envelope list in Priority Inbox even if messages are already loaded

### ISSUE THREAD

**Issue by miaulalala** [nextcloud/mail#7541]
### Steps to reproduce

Set up a new mail account
Let it load for a bit:

![image](https://user-images.githubusercontent.com/7427347/200311435-c6a5b18b-03d0-4288-917f-2cee64332797.png)

### Expected behavior

as soon as messages are in the envelope list in the spinner disappears OR the spinner hides loaded messages until the request is finished

### Actual behavior

See screenshot - the spinner and the envelope list are both there and overlay each other

### Mail app version

2.1.0-rc.1

### Mailserver or service

GMX

### Operating system

Ubuntu 20

### PHP engine version

PHP 8.0

### Web server

Apache (supported)

### Database

MySQL

**Comment by GretaD** [comment]
and if you leave it for some more an error will be shown: `ConsoleLogger.js:64 [ERROR] mail: Could not fetch envelopes of mailbox unified (is:pi-other) `

![Screenshot from 2022-11-14 14-32-29](https://user-images.githubusercontent.com/12728974/201673070-7adabfd2-6ba5-4748-9a8b-8714961e97d5.png)

**Comment by GretaD** [comment]
i cannot reproduce this anymore. The skeleton is shown the whole time. Anna when you have some time can you please test it again? Not urgent
