### ISSUE TITLE
One of email accounts is non stop refreshing in inbox

### ISSUE THREAD

**Issue by Avrantinis** [nextcloud/mail#7554]
### Steps to reproduce

1. Not sure if anyone can reproduce it.
2. I have some email accounts under 2 different domains. All works fine except one spesific email address but all under the same settings. 
3. This happens in inbox and favorites only. Have tryied in earlier versions with the same behaviour

### Expected behavior

Should just load the list of inbox or favorite mails

### Actual behavior

It is non stop refreshing the inbox and favorites lists.

### Mail app version

2.1.0

### Mailserver or service

Webmail

### PHP engine version

PHP 8.1

### Web server

Apache (supported)

### Database

MySQL

### Additional info

Just happens in a spesific email address that starts label@ there is other difference between setting and email addresses.
Thanks

**Comment by miaulalala** [comment]
Can you look at your logs and copy your imap log? Description on how to get that here: https://github.com/nextcloud/mail/blob/main/doc/admin.md#logging

**Comment by Avrantinis** [comment]
Its an 25Mb file, so i share it in a nextcloud link here:
https://cloud.athensmusic.gr/index.php/s/FJTa4bjM3qADsnH
Thanks!

**Comment by ChristophWurst** [comment]
https://docs.nextcloud.com/server/stable/admin_manual/configuration_database/mysql_4byte_support.html

**Comment by Avrantinis** [comment]
Not solved yet
mysql.utf8mb4 was already to "true" in config.php
MySql collation returns to "utf8mb4_bin" after the whole procedure.
What Im trying through cpanel:
1. Maintenance mode in terminal using php occ maintenance:mode --on
2. Collation to utf8mb4_general_ci in phpMyadmin (seems to keep it after page refresh)
3. 'mysql.utf8mb4' => true, in config.php
4. php occ maintenance:repair in terminal
5. occ maintenance:mode --off in terminal
6. Issue keeps the same

**Comment by nextcloud-command** [comment]
Hi there! It looks like this issue hasn’t seen much activity for a while and might need a bit more information to move forward. If we don’t hear back soon, we may close it to keep things organized. Thanks again for your contributions – we really appreciate it!
