### ISSUE TITLE
Not refreshed after account email edition

### ISSUE THREAD

**Issue by chrisaga** [nextcloud/mail#7563]
### Steps to reproduce

1. Open "Account Parameter" via the account `...` menu
2. Click on the pencil next to the email address
3. The form scrolls to the `email address` field
4. Edit the email address
5. Re-enter your IMAP and SMTP password otherwise you would'd be able to save what you changed (see #7537 )
6. Click on the save button
7. No error, no warnings, everything seems OK
8. Open "Account Parameter" via the account `...` menu again

### Expected behavior

email address changed (new value)

### Actual behavior

email address has not been changed (old value)

The address has actually been updated :-) . You have to quit the Mail app and come back to have it refreshed.

### Mail app version

1.14.2

### Mailserver or service

no relevant

### Operating system

Linux 5.16.12-paas x86_64

### PHP engine version

PHP 8.0

### Web server

Apache (supported)

### Database

MySQL

**Comment by ChristophWurst** [comment]
I can no longer reproduce this
