### ISSUE TITLE
Can't add a new Mail Account in Chrome Browser

### ISSUE THREAD

**Issue by davidpr78** [nextcloud/mail#7564]
### Steps to reproduce

Open settings in Mail app and click on 'new account'.

### Expected behavior

Set up a new mail account in Chrome browser

### Actual behavior

When you click on 'new mail account' in Chrome browser nothing happens.

### Mail app version

1.14.2

### Mailserver or service

WebhostOne

### Operating system

Edudocs

**Comment by ChristophWurst** [comment]
> When you click on 'new mail account' in Chrome browser nothing happens.

Could you check your browser console for error?

**Comment by davidpr78** [comment]
Where can I do that? Is it a plugin?

**Comment by GretaD** [comment]
> Where can I do that? Is it a plugin?

open mail app again, right click anywhere in the page and on the menu that will open, click Inspect, then on the new page that will open click console on top-right of the screen. Then click new mail account and see if any errors are shown there

**Comment by davidpr78** [comment]
Refused to execute script from 'https://xxx/apps/dashboard/' because its MIME type ('text/html') is not executable, and strict MIME type checking is enabled.

ChunkLoadError: Loading chunk 10 failed.
(error: https://xxx/apps/mail/js/mail.10.01ce276afc971e2ccf8e.js)
    at o.e (mail.js:1:1081)
    at component (main.js:117:10)
    at main.js:117:10
    at main.js:117:10
    at Array.map (<anonymous>)
    at main.js:117:10
    at Array.map (<anonymous>)
    at Xe (main.js:117:10)
    at main.js:117:10
    at h (main.js:117:10)

**Comment by ChristophWurst** [comment]
Some scripts must be blocked or missing on the server.

Try another browser or a private browser window. Disable any addons and extensions.

**Comment by davidpr78** [comment]
Same with disabled extensions. Using another browser is not a solution.

**Comment by ChristophWurst** [comment]
Use the browser network console to identify the scripts that can't be loaded and check if they exist on storage.

**Comment by ChristophWurst** [comment]
> (error: https://xxx/apps/mail/js/mail.10.01ce276afc971e2ccf8e.js)

It's probably that file that doesn't exist.

**Comment by davidpr78** [comment]
Ok, but why? And how can I add it?
