### ISSUE TITLE
Attachments buttons have lost it styling

### ISSUE THREAD

**Issue by GretaD** [nextcloud/mail#7573]
### Steps to reproduce

Open a message with attachments
See **save all to files** and **Download zip** buttons

### Expected behavior

They are styled properly

### Actual behavior

![Screenshot from 2022-11-10 15-05-00](https://user-images.githubusercontent.com/12728974/201151245-321288b6-0c92-4d7a-9a17-2a0fbac5e530.png)

### Mail app version

2.2.0-alpha

### Additional info

all looks good on stable1.14

**Comment by sazanof** [comment]
https://github.com/nextcloud/mail/pull/6310#issuecomment-1162979197

I don't think it is a bug
