### ISSUE TITLE
Excessive mail server issue

### ISSUE THREAD

**Issue by dustbro** [nextcloud/mail#7601]
### Steps to reproduce

I recently had my smtp mail account suspended for excessive use. Starting in July, the Nextcloud Mail app has started using 50X the bandwidth is previously used. It appears that refreshing downloads the entire mail box, not just new email. 
My daily average bandwidth usage with the Mail app was 15GB. Switching to SnappyMail dropped daily bandwidth usage to 11MB.

### Expected behavior

New mail is imported to Mail app

### Actual behavior

entire mail box may be downloaded instead

### Mail app version

1.14.2

### Mailserver or service

Directnic

### Operating system

Ubuntu 20.04.5

### PHP engine version

PHP 7.4

### Web server

Apache (supported)

### Database

MariaDB

**Comment by ChristophWurst** [comment]
I think this is related to https://github.com/nextcloud/mail/issues/7770.

Your IMAP server probably lacks the CONDSTORE and QRESYNC capabilities. That means flag changes require a full refetch of the messages. And right now the app keeps a complete index of the messages and their flags.

**Comment by GretaD** [comment]
i cannot reproduce this error anymore. Please upgrade to at least to stable3.7 mail app
