### ISSUE TITLE
Autoresponder doesn't stop after the last day set

### ISSUE THREAD

**Issue by maximelehericy** [nextcloud/mail#7614]
### Steps to reproduce

1. Configure autoresponder
2. Configure the last day option
3. Wait for the last day to be expired

### Expected behavior

Autoresponder should stop sending out of office emails.

### Actual behavior

Autoresponder keeps on sending out of office emails

For example:
![image](https://user-images.githubusercontent.com/87175513/202208281-5788e1de-b52b-4e34-8258-e78f722f33bd.png)

In my case :
- radio button was on Autoresponder on
- first day was set to 2022-11-08
- last day was set to 2022-11-14 (and option was ticked)

until I toggled the radio button to autoresponder off today, the autoresponder was still sending out of office emails.

### Mail app version

c.nc.c

**Comment by st3iny** [comment]
I tried to reproduce it with a local imap/sieve server and wasn't able to reproduce it. The script is generated correctly and the sieve server does what it's supposed to do.

I tried 2 cases:
1. Set start and end dates both in the past.
2. Set start date only to verify that my sieve server is actually working.

I received an automatic reply in the second case only.

This could be a problem the sieve server of c.nc.c.
