### ISSUE TITLE
Sent folder should display the recipient by default, not the sender (it's always me !)

### ISSUE THREAD

**Issue by Mer0me** [nextcloud/mail#7627]
### Is your feature request related to a problem? Please describe.

The Sent folder is useless because it only shows the sender of all emails, and... it's always the owner of the box

### Describe the solution you'd like

By default, the Sent folder should display the recipient(s) of the email.

### Describe alternatives you've considered

Clicking on each mail to see the recipient...

**Comment by GretaD** [comment]
Hello,

The sent mailbox should show all the recipients of that email or thread. And its shown the same everywhere in all mailboxes.

So what you're saying is that the same email on your inbox has at least 2 recipients and in your sent mailbox, the same email has only one, which is you?

**Comment by Mer0me** [comment]
I'm talking about the message list.
On all folders of the mailbox, the message list displays only the sender of the email, and not the recipient(s). It's irrelevant for the Sent folder as I'm (obviously) the sender of all the emails on this folder.

**Comment by GretaD** [comment]
Ah sorry, i misunderstood your request. Yes, that is an intended behavior. We show all the recipients only on the header, but i guess you already know that and this request was a feature request and not a bug, so changing the label.

**Comment by Mer0me** [comment]
It was a feature request. Have I clicked the bug button ? My mistake if it's the case.

**Comment by GretaD** [comment]
> It was a feature request. Have I clicked the bug button ? My mistake if it's the case.

no, i changed the labels because i misunderstood your request. All good.

**Comment by ChristophWurst** [comment]
We show the recipient(s) for mailboxes with the "special use" `sent`: https://github.com/nextcloud/mail/blob/dc415ff0e616992d4728cc8c6aaf6372416c9f35/src/components/Envelope.vue#L408-L418

If this logic doesn't work anymore it has to be fixed.

**Comment by Mer0me** [comment]
Hmm, I think I have a problem with the Sent folder. It appears greyed in the account configuration.

**Comment by Mer0me** [comment]
My account defines the folder "Elements envoyés" as the sent folder :
![image](https://user-images.githubusercontent.com/6248852/202735084-8f44ee81-5459-4fcb-a109-daf889ae3d37.png)

But it seems to not be identified as the sent folder (the icon is not "special", it's a simple folder) :
![image](https://user-images.githubusercontent.com/6248852/202735301-12e61ccb-0c5f-4fe6-b35a-32ab4b5ef596.png)

On another account, it seems to work : 
![image](https://user-images.githubusercontent.com/6248852/202735863-1c54a74d-0bb6-471f-af52-fc2f70390e5f.png)

The icon of the folder is a paper plane :
![image](https://user-images.githubusercontent.com/6248852/202736107-ca129009-a0e5-43cc-bd5d-cc567262458c.png)

Maybe a problem with special chars on the folder (french accentuation on "Eléments Envoyés") ?

**Comment by ChristophWurst** [comment]
I think the problem is that our app doesn't attach the *sent* special use to the IMAP mailbox when the mailbox is selected for sent mail.

**Comment by Mer0me** [comment]
So when this _sent_ special use is attached ? Only by default at account creation ? Or is it retrieved from the imap server somewhere ?

**Comment by ChristophWurst** [comment]
It's retrieved from the IMAP server: https://github.com/nextcloud/mail/blob/dc415ff0e616992d4728cc8c6aaf6372416c9f35/lib/IMAP/FolderMapper.php#L177-L218.

The missing part is *setting* the special use.

**Comment by Mer0me** [comment]
By adding manually ["sent"] on the "special_use" column of the "oc_mail_mailboxes" table, I have the wanted behavior.
