### ISSUE TITLE
Feature Request - Default email server connection added by server admin

### ISSUE THREAD

**Issue by Luticus** [nextcloud/mail#764]
I would LOVE to switch to the mail application for it's deep cloud integration, however one major feature that keeps me from doing so is that all of my users would have to configure their mailboxes manually.  It would be really nice if I could set up the mail app to point to my internal mail server by default and then users would simply supply their login information, much the way Rainloop works.  It's too much of a support nightmare to rely on every user to be able to connect by themselves and it also creates a headache if anything on the mail server changes because everyone has to then update their accounts rather than an admin just updating one admin page in the cloud.

**Comment by ChristophWurst** [comment]
> I would LOVE to switch to the mail application for it's deep cloud integration, however one major feature that keeps me from doing so is that all of my users would have to configure their mailboxes manually.

See https://github.com/nextcloud/mail/blob/master/doc/admin.md#automatic-account-creation 😉

**Comment by Luticus** [comment]
Hah, the one time I don't just RTFM and it bites me.  Just installed the app, checked the GUI options and didn't see a way to do what I wanted.  Didn't even think about the conf file.  Well thanks for pointing it out to me.  :)

**Comment by ChristophWurst** [comment]
yw :)
