### ISSUE TITLE
Mail abruptly stopped connecting to IMAP

### ISSUE THREAD

**Issue by RegExe** [nextcloud/mail#7642]
### Steps to reproduce

1. Spin up VM with Debian 11, Apache2 with mod_sec and mariadb
2. Install NextCloud 25
3. Attempt to connect to any IMAP server...

### Expected behavior

Expect it to connect to an IMAP server...

### Actual behavior

Won't connect to any IMAP server

### Mail app version

2.1.1

### Mailserver or service

Dovecot

### Operating system

Debian 11

### PHP engine version

PHP 8.1

### Web server

Apache (supported)

### Database

MariaDB

### Additional info

Log:

```
[mail] Error: OCA\Mail\Exception\ServiceException: IMAP error synchronizing account 26: Error connecting to mail server. at <<closure>>

0. /xxxxx/public_html/apps/mail/lib/Service/MailManager.php line 140
   OCA\Mail\IMAP\MailboxSync->sync()
1. /xxxxx/public_html/apps/mail/lib/Controller/PageController.php line 122
   OCA\Mail\Service\MailManager->getMailboxes()
2. /xxxxx/public_html/lib/private/AppFramework/Http/Dispatcher.php line 225
   OCA\Mail\Controller\PageController->index()
3. /xxxxx/public_html/lib/private/AppFramework/Http/Dispatcher.php line 133
   OC\AppFramework\Http\Dispatcher->executeController()
4. /xxxxx/public_html/lib/private/AppFramework/App.php line 172
   OC\AppFramework\Http\Dispatcher->dispatch()
5. /xxxxx/public_html/lib/private/Route/Router.php line 298
   OC\AppFramework\App::main()
6. /xxxxx/public_html/lib/base.php line 1047
   OC\Route\Router->match()
7. /xxxxx/public_html/index.php line 36
   OC::handleRequest()

GET /apps/mail/
from xx.xx.xx.xx by xxxxx at 2022-11-20T04:09:02+00:00
```

Note, mail server works, it also will not connect to gmail or any other IMAP mailserver.

RoundCube, installed on any of the VM's I've tested connects just fine.

**Comment by RegExe** [comment]
'allow_local_remote_servers' => true - fixed it.

But why?

**Comment by ChristophWurst** [comment]
> But why?

Read https://github.com/nextcloud/mail/blob/main/doc/admin.md#local-imap-and-smtp-servers
