### ISSUE TITLE
IMAP Related Crash Stack Traces in NextCloud Cron Logs Every Night

### ISSUE THREAD

**Issue by gohrner** [nextcloud/mail#7646]
### Steps to reproduce

Wait for cron.php error notification mails.

### Expected behavior

No error notification mail should appear.

### Actual behavior

Error notification mails appear twice a day (?) with the following stack trace:

```plain
Error: Call to a member function getBodyPart() on null in /var/www/nextcloud/apps/mail/lib/IMAP/MessageMapper.php:727
Stack trace:
#0 [internal function]: OCA\Mail\IMAP\MessageMapper->OCA\Mail\IMAP\{closure}()
#1 /var/www/nextcloud/apps/mail/lib/IMAP/MessageMapper.php(738): array_map()
#2 /var/www/nextcloud/apps/mail/lib/IMAP/PreviewEnhancer.php(86): OCA\Mail\IMAP\MessageMapper->getBodyStructureData()
#3 /var/www/nextcloud/apps/mail/lib/Service/PreprocessingService.php(81): OCA\Mail\IMAP\PreviewEnhancer->process()
#4 /var/www/nextcloud/apps/mail/lib/BackgroundJob/PreviewEnhancementProcessingJob.php(94): OCA\Mail\Service\PreprocessingService->process()
#5 /var/www/nextcloud/lib/public/BackgroundJob/Job.php(78): OCA\Mail\BackgroundJob\PreviewEnhancementProcessingJob->run()
#6 /var/www/nextcloud/lib/public/BackgroundJob/TimedJob.php(103): OCP\BackgroundJob\Job->start()
#7 /var/www/nextcloud/lib/public/BackgroundJob/TimedJob.php(93): OCP\BackgroundJob\TimedJob->start()
#8 /var/www/nextcloud/cron.php(152): OCP\BackgroundJob\TimedJob->execute()
#9 {main}
```

### Mail app version

2.1.1

### Mailserver or service

Dovecot

### Operating system

Debian 11 Bullseye

### PHP engine version

PHP 7.4

### Web server

Apache (supported)

### Database

MariaDB

### Additional info

Errors seem to have started occuring since the upgrade to NextCloud 25.0.1 and maybe a corresponding mail app update implicitly performed then.

Or it may just be a coincidence and maybe started slightly earlier - not sure.

**Comment by miaulalala** [comment]
Can you checkout the linked branch here and see if that fixes the issue?

**Comment by miaulalala** [comment]
If you're up for it you can check out the linked branch to see if that fixes the issue :)

**Comment by gohrner** [comment]
@miaulalala: Unfortunately I'm currently not able to test a separate code branch at the moment.

In case I find some time during the weekend, do I just have to clone the repo, check out the mentioned branch and replace the mail app subdirectory on the server with the new version, or do I have to perform some other steps like DB migration?

**Comment by roliverio** [comment]
I had this issue appear _once_ when i performed a heavy message moving and deleting from outside Nextcloud's Mail app and from my local MUA. (this had never happened until Nextcloud 25 and Mail 2.xx), maybe related?

**Comment by jirireischig** [comment]
Still exists in version 2.2.1

**Comment by ChristophWurst** [comment]
@jirireischig thanks for the info. As long as the ticket stays open you can assume that we know that it hasn't been fixed and still exists.
