### ISSUE TITLE
Inbox and other folder do not show with NC 13 & PHP 7.1

### ISSUE THREAD

**Issue by Kugeleis** [nextcloud/mail#765]
### Steps to reproduce
1. open mail app
2. inbox does not show

### Patch
switch back to PHP 7.0
mail app works as expected

### Expected behaviour
mail in inbox show up

### Actual behaviour
mail in inbox do not show up

## Server configuration detail

**Operating system:** Linux 3.2.0-4-amd64 #1 SMP Debian 3.2.73-2+deb7u1 x86_64

**Webserver:** Apache (apache2handler)

**Database:** mysql 5.5.57

**PHP version:** 7.1.2
Modules loaded: Core, date, libxml, openssl, pcre, sqlite3, zlib, bcmath, bz2, calendar, ctype, curl, dom, hash, fileinfo, filter, ftp, gd, gettext, gmp, SPL, iconv, session, intl, json, ldap, mbstring, mcrypt, standard, PDO, mysqlnd, pdo_sqlite, pgsql, Phar, posix, pspell, Reflection, imap, shmop, SimpleXML, snmp, soap, sockets, pdo_mysql, exif, sysvsem, sysvshm, tidy, tokenizer, wddx, xml, xmlreader, xmlwriter, xsl, zip, mysqli, apache2handler, imagick, ionCube Loader, Zend OPcache

**Nextcloud version:** 13.0.0 - 13.0.0.14

**Updated from an older Nextcloud/ownCloud or fresh install:** 

## Client configuration

**Browser:** Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/65.0.3315.3 Safari/537.36 OPR/52.0.2857.0 (Edition developer)

**Comment by ChristophWurst** [comment]
Hi!

Thank you for your report. It looks like your report is missing some important sections of your [issue template](https://raw.githubusercontent.com/nextcloud/mail/master/.github/issue_template.md). Please complete it so that we get a better understanding of your setup and the problem to be able to fix the issue.

Thank you.

**Comment by Kugeleis** [comment]
Hello Christoph,

the rest of the report contained private or empty data. So I removed it. What section do you need? The only section with reasonable Content was the app list. Is this relevant?

Best regards,
kugeleis

**Comment by ChristophWurst** [comment]
Error logs, mostly.

**Comment by Kugeleis** [comment]
The nextcloud.log is 172MB.

**Comment by Kugeleis** [comment]
In https://github.com/nextcloud/mail/issues/562 I found a hint and disabled the opcache, too. Then mail is working. My opcach settings are thos recommended by nextcloud.
zend_extension=opcache.so
opcache.enable=1
opcache.enable_cli=1
opcache.interned_strings_buffer=8
opcache.max_accelerated_files=10000
opcache.memory_consumption=128
opcache.save_comments=1
opcache.revalidate_freq=1

**Comment by ChristophWurst** [comment]
We just need the those entries that are logged when the error occurs. So run `tail -f data/nextcloud.log`, reproduce the issue and post those new entries.

And please also enable debug log and post your data/horde_imap.log. This shows us the IMAP communication and whether an IMAP error occurred.

**Comment by Kugeleis** [comment]
In set the debug level to 0 but no horde_imap.log appears. I guess this goes beyond my linux/server abilities. I didn't find any info on a "horde_imap.log" on the help pages.  The "tail" command gives a mess on the terminal I can't handle. Sorry, I'm not a linux pro. I tried to select some part which might help:
[nextcloud.log](https://github.com/nextcloud/mail/files/1711796/nextcloud.log)

**Comment by ChristophWurst** [comment]
You have *[enable debug mode](https://docs.nextcloud.com/server/12/developer_manual/general/devenv.html#enabling-debug-mode)*.

**Comment by ChristophWurst** [comment]
> I tried to select some part which might help:
> nextcloud.log

Looks good. No errors seemed to have occurred.

**Comment by Kugeleis** [comment]
here is the horde_log stripped from private data
[horde_imap.log](https://github.com/nextcloud/mail/files/1712182/horde_imap.log)

**Comment by ChristophWurst** [comment]
IMAP log looks good to. Could you please be more precise on what's happening when you load the app? Does it show any error message? Is there any error in the browser's js console? Does any of the requests not return with status 200 (see network tab)?

**Comment by lepool** [comment]
I have a similar problem. I can't view Mails in Inbox but in subfolder of Inbox the problem aren't present. 
The error in apache are : 

Call to a member function getEmail() on null in /var/www/https/cloud/apps/mail/lib/Model/IMAPMessage.php on line 433

**Comment by lepool** [comment]
Here the entry in nextcloud.log:

{"reqId":"4IlTLwqGsEYFTDN3nuVv","level":3,"time":"2018-02-20T19:05:12+00:00","remoteAddr":"10.3.1.2","user":"lepool","app":"PHP","method":"GET","url":"\/cloud\/index.php\/apps\/mail\/api\/accounts\/12\/folders\/SU5CT1g%3D\/messages?filter=","message":"Call to a member function getEmail() on null at \/var\/www\/https\/cloud\/apps\/mail\/lib\/Model\/IMAPMessage.php#433","userAgent":"Mozilla\/5.0 (X11; Ubuntu; Linux x86_64; rv:58.0) Gecko\/20100101 Firefox\/58.0","version":"13.0.0.14"}

**Comment by ChristophWurst** [comment]
So for some reason one of the messages has no sender set, hence it fails to load the sender email address: https://github.com/nextcloud/mail/blob/b0569a3485413411664604cdd4541d411bde095e/lib/Model/IMAPMessage.php#L433

**Comment by lepool** [comment]
I have checked if one mail in inbox doesn't have no sender , but with thunderbird all mails have a sender

**Comment by lepool** [comment]
The strange thing is, that in 2 accounts only the inbox folder can't be view. Subfolders views correct.

**Comment by Kugeleis** [comment]
I just checked the web responses. syncToken returns with error 502.

**Comment by Kugeleis** [comment]
...and messages?filter returns 
Request URL:https://myserver.de/index.php/apps/mail/api/accounts/3/folders/SU5CT1g%3D/messages?filter=
Request Method:GET
Status Code:502 Bad Gateway
Remote Address:31.17.121.77:443
Referrer Policy:no-referrer
