### ISSUE TITLE
*Other* message in my inbox not visible without scrolling

### ISSUE THREAD

**Issue by ChristophWurst** [nextcloud/mail#7659]
### Steps to reproduce

0. Have a 1920x1080 screen
1. Open the app
2. Add an account
3. Open the priority inbox

### Expected behavior

I see the latest message(s) in *Other*

### Actual behavior

I only see important messages

![Bildschirmfoto vom 2022-11-23 09-19-36](https://user-images.githubusercontent.com/1374172/203501083-72bad0e7-69ae-43dd-b201-20faa99114e5.png)

### Mail app version

1.14

### Additional info

Regression of https://github.com/nextcloud/mail/issues/6142

@jancborchardt @nimishavijay is this intended?

**Comment by GretaD** [comment]
Yes, that was intended to show as many important messages as possible, but the header "other" should never disappear from the screen depending on how small is the height size screen. Do you think there should be always 1-2 msg on other no matter the screen size?

**Comment by ChristophWurst** [comment]
> Do you think there should be always 1-2 msg on other no matter the screen size?

Yes. I want to see if I got any new emails, albeit the system thinks they are not important.

**Comment by ChristophWurst** [comment]
At the screenshot below we can see a message in *Other*.

![](https://user-images.githubusercontent.com/52440189/159458613-98761ab7-0b63-4e8e-ac6f-0c101a4399e5.png)

**Comment by GretaD** [comment]
> At the screenshot below we can see a message in _Other_.
> 
yes, its just a mockup for a certain size screen, there was no "rule" that should be at least one. But i can improve that

**Comment by nimishavijay** [comment]
The intention was that at least one message is visible in the "Other" section, but we must have forgotten to explicitly mention it in the spec! It would be great if it could be adjusted so that there are 1-2 messages visible in the "Other" section :)
