### ISSUE TITLE
Content extends message element

### ISSUE THREAD

**Issue by ChristophWurst** [nextcloud/mail#7674]
### Steps to reproduce

1. Open the app
2. Configure an account
3. Open a somewhat longer HTML message

### Expected behavior

Well designed app

### Actual behavior

![Bildschirmfoto vom 2022-11-24 15-23-43](https://user-images.githubusercontent.com/1374172/203807791-8beb88b4-bb60-40ad-978f-78e395752bf8.png)

![Bildschirmfoto vom 2022-11-24 15-23-56](https://user-images.githubusercontent.com/1374172/203807815-51b34631-42fd-420c-8f89-0fd5efbd71d9.png)

### Mail app version

2.2

### Additional info

Git bisect leads me to e86cc894aa3cfa8e1cbbb6451fe87e7e90f86c99.

**Comment by GretaD** [comment]
right, i see that the disappearance of scrolling was a regression of https://github.com/nextcloud/mail/pull/7524

I'm thinking how to add a scroll on the third column on narrow screen, without adding a second one on the 3 column view.
