### ISSUE TITLE
Email preview displayed incorrectly when for Content-Transfer-Encoding: quoted-printable messages

### ISSUE THREAD

**Issue by ilicz** [nextcloud/mail#7687]
### Steps to reproduce

1. Display message encoded with Content-Transfer-Encoding: quoted-printable

### Expected behavior

Correctly displaying encoding of the previewed messages

### Actual behavior

Preview of the message text in the message list as well as in the  "threaded display" in the message window is not decoded correctly and display non-ASCII characters in their encoded form.  
Czech sentence normally displayed as `Přátelé střeleckého sportu a LOSíku`
is then displayed as `P=C5=99=C3=A1tel=C3=A9 st=C5=99eleck=C3=A9ho sportu a LOS=C3=ADku`

This happens only for messages comming with `Content-Transfer-Encoding: quoted-printable` encoding (no matter whether they have Content-type text/html or text/plain)

Preview in the message window:
![image](https://user-images.githubusercontent.com/98597308/204144799-848d04fe-e1ee-46c5-a127-f8caa0d6d3c6.png)
Preview in the message list in the box listing:
![image](https://user-images.githubusercontent.com/98597308/204144723-ce398b68-faae-4daa-b725-bc3e4b0c3624.png)

### Mail app version

2.1.2

### Mailserver or service

IceWarp

### Operating system

DEbian

### PHP engine version

PHP 8.0

### Web server

Apache (supported)

### Database

MariaDB

**Comment by kesselb** [comment]
Hi, can you provide us the message source.

**Comment by miaulalala** [comment]
Thanks I will take a look this week!

**Comment by miaulalala** [comment]
If you are able to, you could give the linked PR a shot @ilicz

**Comment by kesselb** [comment]
Hi,

I cannot reproduce your issue with the provided message source.
It seems to work fine on my dovecot based mail server. Imported the message via thunderbird.

![image](https://user-images.githubusercontent.com/3902676/205335748-13c730eb-00ef-403d-ad81-69e49ea67a6e.png)

![image](https://user-images.githubusercontent.com/3902676/205336337-8e428b8b-4d63-448d-b178-94d37d56f8da.png)

**Comment by kesselb** [comment]
@ilicz could you provide us some more data? 

1. Enable logging for mail: https://github.com/nextcloud/mail/blob/main/doc/admin.md#logging
2. Reset preview text for the broken message: `update oc_mail_messages set structure_analyzed = null and preview_text = null where id = INSERT THE ID OF THE MESSAGE HERE`
3. Reload Nextcloud Mail and wait a few seconds. 
4. Check the imap logs. If you share data with us, please make sure to remove sensitive information.

**Comment by ilicz** [comment]
Hello Daniel. 
I'll get back to this in a few days, but it seems that the patch from above linked PR #7709 did the trick to mitigate the original issue. (Yet I'm not sure if my additional post there about incorrect display of the iso8859-2 message characters has been aknowledged or not.)

David

**Comment by kesselb** [comment]
Hi @ilicz, thanks for your assistance. I think we decoded the issue and your information is not required anymore.
