### ISSUE TITLE
2.1.3: Inbox is gone and Priority inbox is empty

### ISSUE THREAD

**Issue by jakobroehrl** [nextcloud/mail#7699]
After the update there is no inbox any more and the Priority inbox is shown as empty (but I my Inbox is full in fact)

![grafik](https://user-images.githubusercontent.com/24530680/204739315-d5a62541-2d41-47ef-8f02-3770e3a7369e.png)

**Comment by LostinSpacetime** [comment]
Same here. Please fix!

**Comment by ChristophWurst** [comment]
> Please fix!

Thanks for the hint

**Comment by ChristophWurst** [comment]
https://github.com/nextcloud/mail/pull/7677 could be the reason for this breakage according to @GretaD. I'm investigating.

**Comment by LostinSpacetime** [comment]
> > Please fix!
> 
> Thanks for the hint

Sorry, got a bit stressed

**Comment by ChristophWurst** [comment]
I'm not fully able to reproduce the issue myself yet but I notice that our app no longer syncs any mailboxes that are not subscribed. That means the *Show only subscribed mailboxes* has no effect.

**Comment by ChristophWurst** [comment]
If you can, let me allow to propose an experiment.

1) Run ``occ mail:account:export <userid>`` to find the id of the affected account
2) Revert the changes https://github.com/nextcloud/mail/pull/7677 did in ``lib/IMAP/FolderMapper.php`` so that it says ``Horde_Imap_Client::MBOX_ALL_SUBSCRIBED`` again.
3) Run the DB statement ``UPDATE oc_mail_accounts SET last_mailbox_sync=0 WHERE id=<accountid>``
4) Reload the page

The app should sync mailboxes again. This time it will include mailboxes that are not subscribed.

**Comment by ChristophWurst** [comment]
@jakobroehrl please fill in the issue form with your next report.

**Comment by LostinSpacetime** [comment]
> If you can, let me allow to propose an experiment.
> 
>     1. Run `occ mail:account:export <userid>` to find the id of the affected account
> 
>     2. Revert the changes [Show only existing mailboxes, not all subscribed mailboxes #7677](https://github.com/nextcloud/mail/pull/7677) did in `lib/IMAP/FolderMapper.php` so that it says `Horde_Imap_Client::MBOX_ALL_SUBSCRIBED` again.
> 
>     3. Run the DB statement `UPDATE oc_mail_accounts SET last_mailbox_sync=0 WHERE id=<accountid>`
> 
>     4. Reload the page
> 
> 
> The app should sync mailboxes again. This time it will include mailboxes that are not subscribed.

This is the code:

```
$list = $client->listMailboxes($name, Horde_Imap_Client::MBOX_ALL_SUBSCRIBED, [
			'delimiter' => true,
			'attributes' => true,
			'special_use' => true,
		]);
```

Shall I change it to:

```
$list` = $client->listMailboxes($name, Horde_Imap_Client::MBOX_ALL_SUBSCRIBED);
```
?

**Comment by ChristophWurst** [comment]
That doesn't seem right. There is no `$list` variable in the code I linked.

**Comment by ChristophWurst** [comment]
You have to patch L58.

**Comment by ChristophWurst** [comment]
> he problem is still here. Why ? Because the database has changed and can't be reverted ?

Caching.

**Comment by ChristophWurst** [comment]
Follow steps 1+3+4 of https://github.com/nextcloud/mail/issues/7699#issuecomment-1331894864

**Comment by ChristophWurst** [comment]
For those affected in production please follow https://docs.nextcloud.com/server/latest/admin_manual/issues/applying_patch.html with https://patch-diff.githubusercontent.com/raw/nextcloud/mail/pull/7701.patch. Then run ``UPDATE oc_mail_accounts SET last_mailbox_sync=0`` on your DB and the missing mailboxes should return.

**Comment by LostinSpacetime** [comment]
> For those affected in production please follow https://docs.nextcloud.com/server/latest/admin_manual/issues/applying_patch.html with https://patch-diff.githubusercontent.com/raw/nextcloud/mail/pull/7701.patch. Then run `UPDATE oc_mail_accounts SET last_mailbox_sync=0` on your DB and the missing mailboxes should return.

I uploaded the patch to the mail folder and run `patch -p 1 < 7701.patch`. I got this error:

patching file lib/IMAP/FolderMapper.php
can't find file to patch at input line 29
Perhaps you used the wrong -p or --strip option?
The text leading up to this was:
--------------------------
|diff --git a/tests/Unit/IMAP/FolderMapperTest.php b/tests/Unit/IMAP/FolderMapperTest.php
|index f5185f71b5..acaff84db6 100644
|--- a/tests/Unit/IMAP/FolderMapperTest.php
|+++ b/tests/Unit/IMAP/FolderMapperTest.php
--------------------------
File to patch:

**Comment by yostral** [comment]
So how did you manage your previous error ?

**Comment by crazybadger** [comment]
> For those affected in production please follow https://docs.nextcloud.com/server/latest/admin_manual/issues/applying_patch.html with https://patch-diff.githubusercontent.com/raw/nextcloud/mail/pull/7701.patch. Then run `UPDATE oc_mail_accounts SET last_mailbox_sync=0` on your DB and the missing mailboxes should return.

This has worked for me too.  Thank you!

**Comment by joopdo** [comment]
FYI: This issue came up for me AFTER I updated from 2.1.3 to 2.1.4.

**Comment by ChristophWurst** [comment]
Wait 2h and let us know if the issue persists.

**Comment by joopdo** [comment]
I waited 1 hour and the Inbox returned and Priority box populated.
Thank you for the great project.
