### ISSUE TITLE
Broken after 2.1.3 update

### ISSUE THREAD

**Issue by crazybadger** [nextcloud/mail#7704]
### Steps to reproduce

I was running the pervious version this morning and was notified there was an update.  It appeared to run OK and I didn't think any more about it, but I've just noticed I have no inboxes displayed for any of the accounts I have set-up

### Expected behavior

Display mail from a number of IMAP accounts

### Actual behavior

No mail displayed, or even the Inboxes

### Mail app version

2.1.3

### Mailserver or service

Various

### Operating system

TrueNAS 13.0-U3 (FreeBSD 13.1 Jail)

### PHP engine version

PHP 8.0

### Web server

Nginx

### Database

MariaDB

### Additional info

Running Nextcloud 25.0.1 and it was working earlier today!

**Comment by koying** [comment]
Same...
Running self-hosted on Ubuntu 20.04.5 LTS

**Comment by crazybadger** [comment]
Yes, I had looked but couldn't see a duplicate.  There is a patch/fix in https://github.com/nextcloud/mail/issues/7699
