### ISSUE TITLE
No clear documentation on how to start working on the project

### ISSUE THREAD

**Issue by richard457** [nextcloud/mail#771]
### Steps to reproduce
1.make dev-setup
2.everything work well
3.but how to start seeing the app in browser
4.it is not clear

### Expected behaviour
I should see app opening on specific port in browser

### Actual behaviour
it just build stuff do not know what I should do to start debugging. please help

### Mail app

**Mail app version:** (see apps admin page)

**Mailserver or service:** (e.g. Outlook, Yahoo, Gmail, Exchange,...)

**Number of accounts:**

### Server configuration

**Operating system**:
Linux
**Web server:**

**Database:**

**PHP version:**

**Version:** (see admin page)

**Updated from an older version or fresh install:**

**List of activated apps:**

```
If you have access to your command line run e.g.:
sudo -u www-data php occ app:list
from within your server installation folder
```

**The content of config/config.php:**

<details>
```
If you have access to your command line run e.g.:
sudo -u www-data php occ config:list system
from within your Nextcloud installation folder

or

Insert your config.php content here
Make sure to remove all sensitive content such as passwords. (e.g. database password, passwordsalt, secret, smtp password, …)
```
</details>

#### Client configuration
**Browser:**

**Operating system:**

##### Web server error log
```
Insert your webserver log here
```

##### Server log (data/nextcloud.log)
<details>
```
Insert your server log here
```
</details>

##### IMAP log (data/horde_imap.log)
<details>
```
Enable debug mode and insert your horde IMAP log here, see https://docs.nextcloud.com/server/13/developer_manual/general/debugging.html#debug-mode
```
</details>

##### SMTP log (data/horde_smtp.log)
<details>
```
Enable debug mode and insert your horde IMAP log here, see https://docs.nextcloud.com/server/13/developer_manual/general/debugging.html#debug-mode
```
</details>

##### Browser log
<details>
```
Insert your browser log here, this could for example include:

a) The javascript console log
b) The network log 
```
</details>

**Comment by ChristophWurst** [comment]
https://docs.nextcloud.com/server/13/developer_manual/general/devenv.html and https://docs.nextcloud.com/server/13/developer_manual/app/index.html should help you get started 😉

**Comment by ChristophWurst** [comment]
If there's anything else you need help with, feel free to ask. I'm happy to help get you started :)

I'm closing this ticket now.
