### ISSUE TITLE
Advanced search does not scroll

### ISSUE THREAD

**Issue by JakobGode** [nextcloud/mail#7711]
### Steps to reproduce

1. open mail app
2. click on filter icon
3. have an 13 or 15" Display Laptop 
4. can't see and click the "search" button

### Expected behavior

I expacted an scroll bar on right side

### Actual behavior

not possible to scroll and click on search

**Comment by ChristophWurst** [comment]
> 2\. click on filter icon

could you post a screenshot please?

**Comment by JakobGode** [comment]
![mail_popup](https://user-images.githubusercontent.com/61253957/205043945-f9503e3d-e8ae-44a6-bd19-2a7afd7d0cfb.PNG)

**Comment by JakobGode** [comment]
I mean "search parameters"

**Comment by ChristophWurst** [comment]
:eyes: @sazanof :)

**Comment by sazanof** [comment]
> eyes @sazanof :)

Yeah. We need something like that. Fix coming soon =)

![image](https://user-images.githubusercontent.com/3595562/205078207-7b4c878c-7955-4e62-9f86-7142fab0d1de.png)

**Comment by JakobGode** [comment]
right that would be nice
