### ISSUE TITLE
Show results of mail autoconfiguration in the manual config section and later in the interface

### ISSUE THREAD

**Issue by stoecker** [nextcloud/mail#7713]
### Is your feature request related to a problem? Please describe.

Configuring mail servers would be much easier, when mail autoconfiguration is supported. A lot of services already provide such information. It only must be used.

See https://wiki.mozilla.org/Thunderbird:Autoconfiguration for a description of the most advanced service.

It's simply call an URL and extract servername, protocol and username from the resulting XML.

There are also some other less advanced methods in DNS (which e.g. only provide the mail server, ...).

### Describe the solution you'd like

Support Autoconfiguration based on email address.

**Comment by ChristophWurst** [comment]
We support that. There was just a bug that prevented non-admins from using it: https://github.com/nextcloud/mail/pull/7688.

**Comment by stoecker** [comment]
Hmm, but I'm the admin user. Still for my address it seems not to work or it's simply not displayed.

When I go to email and try setup the address is correct there, but when I switch to manual the fields aren't correctly populated. When I enter the password it works, but that could also be due to much guesswork.

Also I find no way once activated to review or edit the email settings.

Note: Version 24.0.7, the newest from openSUSE.

**Comment by ChristophWurst** [comment]
Then you are on Mail 1.14 most likely. That version already has the changes from https://github.com/nextcloud/mail/pull/6831.

Do you use a custom domain or one that is in the ISPDB?

**Comment by stoecker** [comment]
Mail 1.14.4

I'm using a custom domain using our own script which populates the autoconfig xml based on the local e-mail setup. Try stoecker at alberding eu as mail with the URL from http://autoconfig.alberding.eu/mail/config-v1.1.xml?emailaddress=...

Domain supports also some other mechanisms, but my experience shows that these are less helpful.

**Comment by ChristophWurst** [comment]
On my dev env it seems to work just as expected

![Bildschirmfoto vom 2022-12-01 15-14-34](https://user-images.githubusercontent.com/1374172/205075270-d5f22c48-f2ed-4b19-bfdc-2c3ee0535d3c.png)

![Bildschirmfoto vom 2022-12-01 15-14-53](https://user-images.githubusercontent.com/1374172/205075348-0d2ecfd7-60ac-4723-ad56-df71a4a0c6a1.png)

(I don't know your password :wink:)

**Comment by stoecker** [comment]
Is there any way to see the resulting parameters in the interface? Maybe my problem is only that they aren't displayed, but actually work as they should?

**Comment by stoecker** [comment]
Yep, I think that's the issue. The entries in the DB look good, so it's only that you can't see the setup in the interface anywhere as far as I can see.

**Comment by ChristophWurst** [comment]
If I switch to manual the settings from autoconfig are there for the user to fine-tune

![Bildschirmfoto vom 2022-12-01 16-06-25](https://user-images.githubusercontent.com/1374172/205087434-38eb4ad5-b833-4ec4-a1eb-fbf558466380.png)

**Comment by ChristophWurst** [comment]
And once the account is added you can open its settings, adjust and save them.

**Comment by stoecker** [comment]
> And once the account is added you can open its settings, adjust and save them.

That I can't find. The three dots of the account only shows "add folder" and "remove account". The "mail settings" allow to add account. I don't find edit/view anywhere.

Note I translate from German, so the texts are only approximated.

Some configuration missing somewhere?
