### ISSUE TITLE
Expose mailbox ACLs and hide options in frontend according to ACLs

### ISSUE THREAD

**Issue by miaulalala** [nextcloud/mail#7719]
### Is your feature request related to a problem? Please describe.

Currently, we read shared mailboxes as if they are regular mailboxes, but not all actions are possible. For example, if I try to delete a message from a mailbox on which I do not have delete permission, a toast error will be shown.

### Describe the solution you'd like

Expose a mailboxes ACLs to the frontend, either via it's own API method or by attaching it to the GET on a mailbox, and display only the options that are availble to the user in the frontend. If no ACLs are available, assume the server doesn't support this capability and allow all actions like we do currently.

Modifying the ACLs for the mailbox should be ignored for now (ACL permission a - administer).

### Additional context

The ACL permissions are:

```txt
   l - lookup (mailbox is visible to LIST/LSUB commands, SUBSCRIBE
       mailbox)
   r - read (SELECT the mailbox, perform STATUS)
   s - keep seen/unseen information across sessions (set or clear
       \SEEN flag via STORE, also set \SEEN during APPEND/COPY/
       FETCH BODY[...])
   w - write (set or clear flags other than \SEEN and \DELETED via
       STORE, also set them during APPEND/COPY)
   i - insert (perform APPEND, COPY into mailbox)
   p - post (send mail to submission address for mailbox,
       not enforced by IMAP4 itself)
   k - create mailboxes (CREATE new sub-mailboxes in any
       implementation-defined hierarchy, parent mailbox for the new
       mailbox name in RENAME)
   x - delete mailbox (DELETE mailbox, old mailbox name in RENAME)
   t - delete messages (set or clear \DELETED flag via STORE, set
       \DELETED flag during APPEND/COPY)
   e - perform EXPUNGE and expunge as a part of CLOSE
   a - administer (perform SETACL/DELETEACL/GETACL/LISTRIGHTS)
```
OR

```txt
   l - lookup (mailbox is visible to LIST/LSUB commands)
   r - read (SELECT the mailbox, perform CHECK, FETCH, PARTIAL,
       SEARCH, COPY from mailbox)
   s - keep seen/unseen information across sessions (STORE SEEN flag)
   w - write (STORE flags other than SEEN and DELETED)
   i - insert (perform APPEND, COPY into mailbox)
   p - post (send mail to submission address for mailbox,
       not enforced by IMAP4 itself)
   c - create (CREATE new sub-mailboxes in any implementation-defined
       hierarchy)
   d - delete (STORE DELETED flag, perform EXPUNGE)
   a - administer (perform SETACL)
```
Please be aware that there are positive (+) as well as negative (-) rights on a mailbox.

https://github.com/nextcloud/mail/issues/7057

**Comment by miaulalala** [comment]
Test accounts can be obtained from @ChristophWurst

**Comment by ChristophWurst** [comment]
Individual work packages from this ticket could be

1) Adjust frontend mailbox management (navigation)
  * Show/hide mailbox rename option depending on `x`/`k` ACL
  * Show/hide mailbox *Mark all read* depending on `s` ACLs
  * Show/hide mailbox sub mailbox action depending on `k` ACLs
  * Show/hide mailbox delete action depending on `x` ACL
2) Adjust message operations
  * Mark messages as read depending on `s` ACL
  * Show/hide seen toggle action depending on `s` ACL
  * Show/hide message delete action depending on `t` and `e` or `d` ACLs
  * Exclude mailboxes from move and drop target is `w` is missing
  * Exclude mailboxes as Drafts/Sent mailboxes if `w` is missing

**Comment by ChristophWurst** [comment]
- [ ] Blocked by https://github.com/nextcloud/mail/issues/7732
