### ISSUE TITLE
No Folders

### ISSUE THREAD

**Issue by Olgsiolgs** [nextcloud/mail#773]
### Steps to reproduce
1. Open nextcloud mail
2. click "show all folders"
3. folders are hidden, but clickable

### Expected behaviour
The folders should have a black fondcolor, like the others

### Actual behaviour
The foldernames are white and so hidden

### Mail app

**Mail app version:**  0.7.9

**Mailserver or service:** Webhoster (netcup.net)

**Number of accounts:** One

### Server configuration

**Operating system**:
Windows 10

**PHP version:**
7.2

**Version:** (see admin page)
13.0.0

**Updated from an older version or fresh install:**
Fresh install

#### Client configuration
**Browser:** Firefox 58.0.2

**Operating system:**
Windows 10

![12](https://user-images.githubusercontent.com/36405093/36093497-26053920-0feb-11e8-8841-9a2994a1ff7f.JPG)

**Comment by ChristophWurst** [comment]
Possibly a duplicate of https://github.com/nextcloud/mail/issues/732. @Olgsiolgs could you please check?

**Comment by Olgsiolgs** [comment]
Its the same problem. But i cant find a solution at #732 :)

**Comment by ChristophWurst** [comment]
Okay, thanks for checking.

> But i cant find a solution at #732 :)

There is none at the moment as it's still not reproducible for us.
