### ISSUE TITLE
Hide non printable characters from email subject preview text

### ISSUE THREAD

**Issue by andreanidouglas** [nextcloud/mail#7730]
### Steps to reproduce

1. Configure an email account on your nextcloud
2. Send an email to the configure account with some non-printable characters as the first 10 chars
3. Open the email on nextcloud, the preview window should show the non-printable characters as =(ascii code)

### Expected behavior

1. Configure an email account on your nextcloud
2. Send an email to the configure account with some non-printable characters as the first 10 chars
3. Open the email on nextcloud, the preview window should show the non-printable characters as =(ascii code)

### Actual behavior

Do not show any non-printable characters

### Mail app version

mail 2.1.4

### Mailserver or service

gmail

### Operating system

Linux Debian 10

### PHP engine version

PHP 8.0

### Web server

Apache (supported)

### Database

MariaDB

### Additional info

Example below: 
![Screenshot 2022-12-05 122027](https://user-images.githubusercontent.com/684650/205674249-5eb98406-f179-4374-929f-7d76bb1739f1.png)

**Comment by ChristophWurst** [comment]
There is an issue with decoding. The email you see is *quoted printable*. The =20 are spaces. https://en.wikipedia.org/wiki/Quoted-printable.

https://github.com/nextcloud/mail/pull/7486 should address this.

**Comment by ChristophWurst** [comment]
Duplicate of https://github.com/nextcloud/mail/issues/7687

**Comment by andreanidouglas** [comment]
Thanks, I did a brief search but didn't find #7687.
