### ISSUE TITLE
Move thread

### ISSUE THREAD

**Issue by snetat** [nextcloud/mail#7738]
### Steps to reproduce

When i move an email the Choose target mailbox window doesn't close automatically and i can't close it with x either. 

### Expected behavior

window closes

### Actual behavior

window does not close

### Mail app version

2.2.0

### Mailserver or service

IMAP Server

### Operating system

Linux Debian 11

### PHP engine version

PHP 8.1

### Web server

Apache (supported)

### Database

MariaDB

**Comment by mjtbrady** [comment]
I am seeing the same problem with Mail 2.2.1 and PHP 8.0.  It pretty much makes the Mail app unusable for me.

**Comment by snetat** [comment]
I just updated 2 instances to 25.0.2 and it works again.

**Comment by mjtbrady** [comment]
Same here.  Working again after upgrade to 25.0.2

**Comment by kesselb** [comment]
Thanks for reporting back :+1: 

Fixed by https://github.com/nextcloud/server/pull/35530
