### ISSUE TITLE
Text Templates

### ISSUE THREAD

**Issue by Konoa-git** [nextcloud/mail#7747]
### Describe the solution you'd like

Hey,
if you need to send invoices its much easier with a template. Just have a Dropdown with your prefilled templates and choose between your templates.

**Comment by kesselb** [comment]
Sounds similar to GitHub's saved replies (https://docs.github.com/en/get-started/writing-on-github/working-with-saved-replies/about-saved-replies) but for Nextcloud Mail. 

My workaround is to pick the email from the previous week and use "Edit as new message" as template. 

For invoicing I recommend a proper tool (e.g., https://www.invoiceninja.org/) to handle the surrounding process.

**Comment by pbek** [comment]
Isn't that solved by https://apps.nextcloud.com/apps/text_templates?
