### ISSUE TITLE
Signature 

### ISSUE THREAD

**Issue by Konoa-git** [nextcloud/mail#7748]
### Describe the solution you'd like

I'd like to have a Signature Tab, where you can choose between signatures to send proper information to your customor or someone else.
And the cherry on the cream would be to add pictures to the signature.

Like
Leon K
MANAGER at XX
Phone: +49 - xxx

**Comment by GretaD** [comment]
Hello,

can you please explain a bit better how do you expect this feature to look like? What do you mean with tab?

Also, our signature already supports images :)

**Comment by cahyadilumine** [comment]
Hi GretaD, can you tell me where the sign function button in the mail apps? i see no option to add signature on it
![image](https://github.com/nextcloud/mail/assets/141903661/3ea7ba33-626e-4542-963d-d49f5ed692b9)
![image](https://github.com/nextcloud/mail/assets/141903661/6401ccfe-ba11-4c65-8e96-352ce7fe5273)

**Comment by kaystrobach** [comment]
You can add pictures to signatures by marking text and then adding an image from the popover.

But yes we need the fully fledged editor to be available for signatures .... e.g. for tables and so on.

**Comment by ChristophWurst** [comment]
Signatures are supported
