### ISSUE TITLE
auto-config fails/ works fine with T'bird

### ISSUE THREAD

**Issue by xpseudonym** [nextcloud/mail#7761]
### Steps to reproduce

1. Set up Gandi DNS SRV records as Gandi describes
2. Successfully auto-config with T'bird
3. Fail to auto-config with Nextcloud Mail

### Expected behavior

Account auto-config succeeds

### Actual behavior

Account auto-config fails

### Mail app version

2.2.1

### Mailserver or service

Gandi

### Operating system

gun/linux

### PHP engine version

PHP 8.0

### Web server

None

### Database

None

### Additional info

Web server & Database info not found as described above

Does the information provided here still work
https://nextcloud-mail.readthedocs.io/en/v0.19.1/admin/
?
Will adding the following to `config.php` work:
```
   'app.mail.accounts.default' => [
     'email' => '%USERID%@read.nz'',
     'imapHost' => 'mail.gandi.net',
     'imapPort' => 993,
     'imapUser' => '%USERID%@read.nz',
     'imapSslMode' => 'ssl',
     'smtpHost' => 'mail.gandi.net',
     'smtpPort' => 465,
     'smtpUser' => '%USERID%@read.nz'',
     'smtpSslMode' => 'ssl',
   ],

```
?

**Comment by freibadschwimmer** [comment]
Hi, re your latest question:
The setting  'app.mail.accounts.default' is deprecated according to https://github.com/nextcloud/mail/issues/3372#issuecomment-671212930

You may check if you can achieve this from your NC admin settings in
settings/admin/groupware

**Comment by ChristophWurst** [comment]
Try again. I fixed a few edge cases with autoconfig that worked with thunderbird but not with our client

**Comment by xpseudonym** [comment]
Many thanks
M
