### ISSUE TITLE
Message preview messed up (showing e.g. =0D =0D =0D =0D =0D =0D)

### ISSUE THREAD

**Issue by fischer-felix** [nextcloud/mail#7768]
### Steps to reproduce

1. receive email with HTML formatting
2. open the mailbox 
3. see the grey text in the list view underneath the subject text

### Expected behavior

Preview shows only text/whatever is supposed to be shown (see example from Spark on Android)
![tempFileForShare_20221214-215834](https://user-images.githubusercontent.com/65448408/207712453-26514ddf-8655-4651-ba98-8486b0188653.jpg)

### Actual behavior

Preview sometimes only shows things like `=0D =0D ...`, sometimes part of the text with `=` and other letters in between (see screenshot)
![Screenshot_2022 12 14_22:00:33](https://user-images.githubusercontent.com/65448408/207712893-199887f8-bbb0-4680-8359-89d2cbdabdc8.png)

### Mail app version

2.2.1

### Mailserver or service

Gmail, Strato

### Operating system

Docker

### PHP engine version

PHP 8.1

### Web server

Nginx

### Database

MariaDB

**Comment by ChristophWurst** [comment]
Fixed by https://github.com/nextcloud/mail/pull/7709
