### ISSUE TITLE
Unread counter in navigation does not align with actions menu toggle

### ISSUE THREAD

**Issue by ChristophWurst** [nextcloud/mail#7769]
### Steps to reproduce

1. Open the app
2. Configure an account
3. Look at the navigation

### Expected behavior

Unread counter and the toggle (...) for the actions menu align

### Actual behavior

Unread counter and the toggle (...) for the actions menu don't align

### Mail app version

2.x

### PHP engine version

None

### Web server

None

### Database

None

**Comment by GretaD** [comment]
are we talking about this one?
![Screenshot from 2022-12-15 11-07-59](https://user-images.githubusercontent.com/12728974/207831768-36aa6b82-8996-4ef9-9dbc-247de2dd07de.png)

looks good to me

**Comment by ChristophWurst** [comment]
![Bildschirmfoto vom 2022-12-15 11-25-24](https://user-images.githubusercontent.com/1374172/207835296-4a827322-50c9-4dfb-b83e-9b28e337a4cf.png)

**Comment by ChristophWurst** [comment]
Requires a release of `@nextcloud/vue` that ships https://github.com/nextcloud/nextcloud-vue/pull/3572

**Comment by GretaD** [comment]
> Requires a release of `@nextcloud/vue` that ships [nextcloud/nextcloud-vue#3572](https://github.com/nextcloud/nextcloud-vue/pull/3572)

shipped https://github.com/nextcloud/nextcloud-vue/releases/tag/v7.3.0
