### ISSUE TITLE
Unable to connect to Titan Mail on Hostinger

### ISSUE THREAD

**Issue by daveo132** [nextcloud/mail#7845]
### Steps to reproduce

1. Enter details into new account page (IMAP / SMTP etc)

2. Attempt to connect to account

### Expected behavior

Mail app should connect successfully to account

### Actual behavior

Generic error message "There was an error while setting up your account"

### Mail app version

1.15.0

### Mailserver or service

Titan Mail on Hostinger

### Operating system

Unraid 6.11.5

### PHP engine version

None

### Web server

None

### Database

None

### Additional info

Has previously worked with Gmail with no issues noted
Have tried changing the password on Titan Mail to exclude any special character - No effect
Have tried another browser (Vivaldi & Brave) - No effect
Have tried with and with out ad blocking - No effect
Have tried with and with out VPN active - No effect

**Comment by ChristophWurst** [comment]
https://github.com/nextcloud/mail/blob/main/doc/admin.md#logging could help

**Comment by daveo132** [comment]
So... I tired that but I don't seem to have an option for debug.
I opened up "config.php" located here: "appdata\nextcloud\www\nextcloud\config"

There is no debug open to enable to "true" in that file.  Is that the correct config file?
Or, can I just add the entry?

**Comment by ChristophWurst** [comment]
add it

```
  'debug' => true,
```

**Comment by daveo132** [comment]
Thanks, will do

**Comment by daveo132** [comment]
Well, one step forward.
I've enable that in the config file but when I go to the logging page on Nextcloud it flashes some info then goes blank.  
So, I can't set the debug level

**Comment by ChristophWurst** [comment]
Look at the file, not the UI. E.g. using `less`.

**Comment by daveo132** [comment]
oh ok, I was just following the debug documentation.

Assuming this is the correct location for the logs? appdata\nextcloud\log\php

Nothing new is generated.  Last update to the log file was after restarting it following the addition of the debug line.
[error.log](https://github.com/nextcloud/mail/files/10309596/error.log)

**Comment by daveo132** [comment]
Unfortunate I cannot find any of these log files anywhere within appdata/nextcloud

data/nextcloud.log, 
data/horde_imap.log
data/horde_smtp.log

**Comment by ChristophWurst** [comment]
You can use the forums to reach out for help on this: https://help.nextcloud.com/

Once we have the error logs, an engineer can continue here.

**Comment by daveo132** [comment]
Thanks.  I've also just updated on to NC 25 so I'll see if the issue persists there.
Though I've only just got my internet back up and running after an ISP change so will likely be this evening before I can try anything again.

**Comment by daveo132** [comment]
Hi,
Managed to get to it now.
Working as expected now since the update to NC 25.
