### ISSUE TITLE
Save Mails in eml Format in Nextcloud Folder

### ISSUE THREAD

**Issue by ralfi** [nextcloud/mail#7847]
### Is your feature request related to a problem? Please describe.

Save Mails is atm only available for Download 

### Describe the solution you'd like

It would be helpfull to have a mail context menu item to save mail in eml format in NC folder

### Additional context

Thanks a lot and have a great new year!

**Comment by rebootit** [comment]
It would be very usefull for most of my clients that are hôtels, they create a folder for each customer and they save the mails into this folder by downloading them and them uploading them.

**Comment by ChristophWurst** [comment]
This is a duplicate of https://github.com/nextcloud/mail/issues/675.
