### ISSUE TITLE
translation error (german)

### ISSUE THREAD

**Issue by KoMa1012** [nextcloud/mail#7854]
### Steps to reproduce

1.set language to german
2.open nextcloud mail
3.open searchparameters (right to search bar in mail app)
4.in the window which opens you can see that the "Suchbegriff" is called "Scuhbegriff"

### Expected behavior

it should be called "Suchbegriff"

### Actual behavior

it is called "Sucbegriff"

### Mail app version

2.2.2

### Mailserver or service

netcup

### Operating system

docker container

### PHP engine version

PHP 8.1

### Web server

Apache (supported)

### Database

MariaDB

### Additional info

Just double checked, whenever something has been changed a new draft is generated, old draft is never being changed.

**Comment by GretaD** [comment]
Hello, this typo is already fixed. You should get it with the next translation update.
https://github.com/nextcloud/mail/blob/6b0db0f1bce8e4cd855b0d97b6e351a293968c80/l10n/de_DE.js#L331
