### ISSUE TITLE
Where do i change the priority inbox path? It's using the wrong location by default.

### ISSUE THREAD

**Issue by jsellin78** [nextcloud/mail#7869]
### Steps to reproduce

1.
2.
3.

### Expected behavior

Expected to see path of "important" email. Wrong path implementet

### Actual behavior

Location of path to actual "importants" folder

### Mail app version

24.08

### Operating system

Debian 10

### PHP engine version

PHP 8.1

### Web server

Apache (supported)

### Database

MariaDB

**Comment by sejo-ux** [comment]
Changing default priority inbox is only avaiable for nextcloud enterprise i belive.

**Comment by GretaD** [comment]
> Changing default priority inbox is only avaiable for nextcloud enterprise i belive.

No this is not true. Bugs are fixed for everyone, our code is open source for everyone.

@jsellin78 can you please add some more details, im not sure if i completely  understand what is happening here. Can you please add some steps at the ticket so i can reproduce it.
