### ISSUE TITLE
Sent Emails Going To The Wrong Folder

### ISSUE THREAD

**Issue by MattyShires** [nextcloud/mail#787]
### Steps to reproduce
1. Create a pubic inbox via Dovecot.
2. Send an email.

### Expected behaviour
Sent email is placed in the user's sent folder.

### Actual behaviour
Sent email is placed in sent folder of the public inbox.

### Mail app

**Mail app version: 0.7.9

**Mailserver or service: Local IMAP

**Number of accounts: 56

### Server configuration
**Operating system**: CentOS 7.4

**Web server: Apache HTTPD 2.4

**Database: MySQL 5.7

**PHP version: 5.4

Updated from an older version

**Comment by ChristophWurst** [comment]
> Local IMAP

Any chance this is a Dockerized server you could share so I can test this locally?

**Comment by MattyShires** [comment]
Unfortunately this is not a Dockerized server, This is quite a severe issue as it has exposed several confidential emails to the rest of the company.

I could share some configs if require albeit with sensitive info removed.

**Comment by ChristophWurst** [comment]
> I could share some configs if required albeit with sensitive info removed.

That would be great - especially the [IMAP logs](https://raw.githubusercontent.com/nextcloud/mail/master/.github/issue_template.md) when you send a message. Thanks!

**Comment by MattyShires** [comment]
[dovecot.zip](https://github.com/nextcloud/mail/files/1744922/dovecot.zip)

Here's the cleaned up config files, I don't believe it to be a config issue as Rainloop does not have this problem.

**Comment by chuck-m** [comment]
Any update on this bug please.  It is **halting** our role out of NC?

**Comment by ChristophWurst** [comment]
There hasn't been any progress on this ticket. @chuck-m would you be interested in helping getting this fixed?

**Comment by ChristophWurst** [comment]
> **Mail app version: 0.7.9

As there is no feedback since a while I will close this ticket. If this is still happening please make sure to upgrade to the latest version after that, feel free to reopen.
