### ISSUE TITLE
Show senders e-mail adress

### ISSUE THREAD

**Issue by rollanders** [nextcloud/mail#7884]
### Is your feature request related to a problem? Please describe.

I receive a mail. I only see the name of the sender. I have not found anyway to see his e-mail-adress. 

### Describe the solution you'd like

You should be able to show the adresss.

**Comment by rollanders** [comment]
I can find it by klicking on the three dots and then choose Show source.

**Comment by ChristophWurst** [comment]
Yes, but it should also show when the sender name is clicked

**Comment by rollanders** [comment]
But it does not. I updated the mail-app. Same situation.

**Comment by ChristophWurst** [comment]
That is what I meant. You currently can't see the email. But it would be desirable if we could.

**Comment by ufgum** [comment]
Don't forget the recipient address.
The recipient is also important if you use alias addresses. You see only you're name, not the address this email was sent to.
I would go for "mouseover title tag" the sender AND recipient names.

**Comment by JakobGode** [comment]
In my situation i click on the sendes name and the sender adress is shown, but completly covered by an bar.
milliseconds after clicking the senders adress is shown and then the bar pops up.
![sender adress coverd](https://user-images.githubusercontent.com/61253957/213698459-7976d3a3-2d21-47e1-9042-af0abecad258.PNG)

**Comment by ufgum** [comment]
> In my situation i click on the senders name and the sender adress is shown, but completly covered by an bar. Milliseconds after clicking the senders address is shown and then the bar pops up.

And how to see the email in Firefox and Chromium:
1. click the name, wait the bar covers the email-address
2. click on the bar (between the links)
3. click again the name and the email-address is shown

It works, but a bit complicated. Therefore I would prefer the `title` tag, it pop's up without clicking.

**Comment by JakobGode** [comment]
Works, but uncomfortable. And if there are more adresses in the conversation, the mailaderss i missing

**Comment by koying** [comment]
> And how to see the email in Firefox and Chromium

Oh wow. Thanks for this, but extremely cumbersome...

**Comment by KimmoJ** [comment]
Obfuscating any sender info or making it something you have to click through to find is just wrong. Who it is from is a crucial bit of information before you know how to react to an email. In fact, remove the display name if need be and leave only the emal address, even that would be more correct. 

Having to view source on every email is preposterous. Best I found before finding this thread was to click on the sender, and use the copy to clipboard function, and paste it in elsewhere to read it. This is still pretty awful. I need to see the email address on any mail that comes from someone new, and I want to see it on everyone so that the "Joe Smith" that emailed me was actually jsmith @ good place, not noreply @ phishing com. 

Please address this issue, obfuscating critical data is not the way. Making it easier to view mail headers for every email would also be helpful, right now you have to drill down through multiple menus to get to viewing the source, but at the very least please don't hide the sender address. Anyone can set anything they want as display name.

**Comment by goulvench** [comment]
I whole-heartedly second @KimmoJ's comment. The sender address needs to be displayed beside or under their name. Discrepancies between sender email and name are the easiest way to tell phishing/scams from legitimate senders.  
This is a **security** issue, not just a visual preference.

**Comment by Viksie** [comment]
I also whole-heartedly second @KimmoJ 's comment. 

It's critical to have the **_SENDER's ADDRESS_** displayed with the **_SUBJECT_** to be able to quickly eyeball an email as a second means of defense against spam/scams and malware.

The "**_@ Full Address Column_**" add-on for Thunderbird does exactly this, for sender and recipient addresses. As such, we've done away with displaying the sender and receiver in favor of displaying the full sender and full receiver addresses when a newb user allowed malware into the network. 

<img width="497" alt="@FullAddress" src="https://user-images.githubusercontent.com/22875530/229400507-c174e87a-c629-4759-b05f-ded893476497.png">

As such, everyone had been educated on how domains work and therefore to be able to eyeball & immediately identify scam/spam emails from senders such as:

![@sender](https://user-images.githubusercontent.com/22875530/229402129-1057c502-7426-400c-8232-311fad185024.png)

It's not a nice to have, but essential feature.

![@sender2](https://user-images.githubusercontent.com/22875530/229403418-0364852c-bc71-4ecf-8902-46cf673f34c6.png)

**Comment by dbielz** [comment]
I'd like to strongly support the arguments of the comments before: _Every advisor for security_ on your PC sais "Check the sender's (and the recipient's) address thoroughly to make sure they are authentical." Who thinks it could be a good idea to **hide** this essential information? What's the benefit of this behaviour supposed to be?

**Comment by dbielz** [comment]
> > Who thinks it could be a good idea to **hide** this _essential_ information?
> 
> This information was never hidden intentionally.

Sorry, this was not meant to be offending in any way.

> 
> If you look closely you can see a popover with the sender email show for a split second before it is overlapped with another popover that shows the contacts information. This is a regression of #4524. https://nextcloud-vue-components.netlify.app/#/Components/NcUserBubble doesn't allow us to influence the popover position, unfortunately.

Even if the popup worked as expected, this information would be too far away from reach. As already @KimmoJ and the others point out, it should be accessible without any hassle. I dont't think that having to point exactly on every involved email-address and to wait for the popup to show up is a very adequate way to access this essential information. And, as already stated, I can't imagine any use case, where this information would disturb, when beeing visible.

What about the roundcube way of handling this:
![grafik](https://user-images.githubusercontent.com/1905493/231092077-153de293-8d74-46ea-be46-9a3971677706.png)

Or, when clicking on 'Details':
![grafik](https://user-images.githubusercontent.com/1905493/231092854-e4dbd06a-8635-4302-97a0-7bbc22c888a1.png)

**Comment by ChristophWurst** [comment]
See https://github.com/nextcloud/mail/pull/8344 for a minimal-invasive fix that is easy to backport to older releases.

**Comment by koying** [comment]
Definitely better, but still requires an action, which is bad. The address should be at the same level as the name, like in every single modern email reader

Here, google
![image](https://user-images.githubusercontent.com/164740/231096104-d8fadced-4060-4a8e-bd2e-5689346fbf42.png)

**Comment by ChristophWurst** [comment]
We can do an enhanced version for new releases :+1:

**Comment by ChristophWurst** [comment]
Let's continue the discussion of showing the sender email address by default in https://github.com/nextcloud/mail/issues/8379
