### ISSUE TITLE
Wrap long message subjects

### ISSUE THREAD

**Issue by thstyl2000** [nextcloud/mail#7890]
### Is your feature request related to a problem? Please describe.

Long subjects are never wrapped. In order to read the full subject one needs to hover with the mouse, which is not optimal.

### Describe the solution you'd like

Have the subject wrapped.

**Comment by ChristophWurst** [comment]
screenshot?

**Comment by thstyl2000** [comment]
![Screenshot_20230113_124934](https://user-images.githubusercontent.com/18458458/212318031-88a54455-9a76-4dd0-bd08-1d368c39e8fc.png)
