### ISSUE TITLE
Disable drag and drop if not allowed by ACLs

### ISSUE THREAD

**Issue by st3iny** [nextcloud/mail#7916]
### Is your feature request related to a problem? Please describe.

When I move a message to another mailbox via drag and drop, the app should check if the source mailbox supports deleting (`t` + `e`). If not, dragging from this mailbox should be disabled.

### Describe the solution you'd like

Disable dragging if source mailbox does not support deleting messages.

### Additional context

Extracted from https://github.com/nextcloud/mail/issues/7057

**Comment by ChristophWurst** [comment]
Dup of https://github.com/nextcloud/mail/issues/7888?

**Comment by ChristophWurst** [comment]
I think I just realized that https://github.com/nextcloud/mail/issues/7888 is about the drop target. This ticket is more about the "draggability" in the source mailbox.

Let's combine the two tickets into one task.

**Comment by GretaD** [comment]
merged
