### ISSUE TITLE
Compatibility with different namespace prefixes (dovecot default)

### ISSUE THREAD

**Issue by Ninos** [nextcloud/mail#793]
As already written in #782 the mail app is not working well with different prefixes, which does not begin with .INBOX. In Debian Stretch dovecot uses .SENT, .DRAFT, .TRASH as prefix, instead of .INBOX for sent/draft/trash-folders.

Problem which are still available:
- Don't set prefixed folders as subfolders of all forders (inbox, sent, draft, trash, ...)
- Arrow is not displayed well (over the inbox/sent/draft/trash-icon)
- Subsub(sub)-folders are not displayed in correct folder-level (spacing)

**Comment by ChristophWurst** [comment]
I'm closing this ticket because it hasn't received any updates in a long time. If this is still relevant, feel free to re-open or file a new ticket.

Thank you.
