### ISSUE TITLE
No authentification of new mail accounts 

### ISSUE THREAD

**Issue by davidpr78** [nextcloud/mail#7936]
### Steps to reproduce

1. Go to mail app and click new account
2. put all data in (imap, server, port)
3. click connect

### Expected behavior

A new imap account is available

### Actual behavior

Message: an error occurred while setting up the account

### Mail app version

1.15.1

### Mailserver or service

WebhostOne

### Operating system

Edudocs

### PHP engine version

Other

### Web server

None

### Database

None

**Comment by ChristophWurst** [comment]
> Message: an error occurred while setting up the account

Check your nextcloud.log

**Comment by davidpr78** [comment]
[mail] Fehler: Exception: Class "IPLib\Factory" not found in file '/zfsinst/ed_instances/xxx/apps/mail/lib/Net/IpAddressClassifier.php' line 52 at <<closure>>

0. /zfsinst/ed_instances/xxx/lib/private/AppFramework/App.php line 172
   OC\AppFramework\Http\Dispatcher->dispatch()
1. /zfsinst/ed_instances/xxx/lib/private/Route/Router.php line 298
   OC\AppFramework\App::main()
2. /zfsinst/ed_instances/xxx/lib/base.php line 1030
   OC\Route\Router->match()
3. /zfsinst/ed_instances/xxx/index.php line 36
   OC::handleRequest()

POST /xxx/apps/mail/api/accounts
from 109.90.180.213 by xxx at 2023-01-25T09:40:46+00:00

**Comment by ChristophWurst** [comment]
Dup of https://github.com/nextcloud/mail/issues/7816

**Comment by ChristophWurst** [comment]
> version":"24.0.5.1

https://github.com/nextcloud/server/tree/v24.0.5 -> https://github.com/nextcloud/3rdparty/tree/96efba0e1d6918a8c06915b634858a426d07a84f -> the iplib is not there indeed

**Comment by ChristophWurst** [comment]
https://github.com/nextcloud/server/tree/v24.0.8 -> https://github.com/nextcloud/3rdparty/tree/ffeb7436c50cea31bd589047d02242e8dfab659b -> https://github.com/nextcloud/3rdparty/tree/ffeb7436c50cea31bd589047d02242e8dfab659b/mlocati/ip-lib the lib is there

this is why our tests didn't catch the missing class
