### ISSUE TITLE
Error: stream_socket_enable_crypto(): Peer certificate

### ISSUE THREAD

**Issue by nietsmmar** [nextcloud/mail#7943]
### Steps to reproduce

1. Configure basic email 
![image](https://user-images.githubusercontent.com/9265181/214903667-26365516-b04c-4bc4-814a-457551a0440b.png)
2. Click "send mail"

### Expected behavior

Receiving a test mail.

### Actual behavior

Getting the error message `A problem occurred while sending the email. Please revise your settings. (Error: Unable to connect with TLS encryption)`

In the logs I get these errors:

`Return type of ChristophWurst\KItinerary\Itinerary::count() should either be compatible with Countable::count(): int, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice at /var/www/nextcloud/apps/mail/vendor/christophwurst/kitinerary/src/Itinerary.php#48`

```
Error: stream_socket_enable_crypto(): Peer certificate CN=`mail.webclient6.de' did not match expected CN=`smtp.articlett.de' at /var/www/nextcloud/3rdparty/swiftmailer/swiftmailer/lib/classes/Swift/Transport/StreamBuffer.php#94
<<closure>>

OC\Log\ErrorHandler::onError()

/var/www/nextcloud/3rdparty/swiftmailer/swiftmailer/lib/classes/Swift/Transport/StreamBuffer.php - line 94:

stream_socket_enable_crypto()

/var/www/nextcloud/3rdparty/swiftmailer/swiftmailer/lib/classes/Swift/Transport/EsmtpTransport.php - line 348:

Swift_Transport_StreamBuffer->startTLS()

/var/www/nextcloud/3rdparty/swiftmailer/swiftmailer/lib/classes/Swift/Transport/AbstractSmtpTransport.php - line 148:

Swift_Transport_EsmtpTransport->doHeloCommand()

/var/www/nextcloud/3rdparty/swiftmailer/swiftmailer/lib/classes/Swift/Mailer.php - line 65:

Swift_Transport_AbstractSmtpTransport->start()

/var/www/nextcloud/lib/private/Mail/Mailer.php - line 191:

Swift_Mailer->send()

/var/www/nextcloud/apps/settings/lib/Controller/MailSettingsController.php - line 170:

OC\Mail\Mailer->send()

/var/www/nextcloud/lib/private/AppFramework/Http/Dispatcher.php - line 225:

OCA\Settings\Controller\MailSettingsController->sendTestMail()

/var/www/nextcloud/lib/private/AppFramework/Http/Dispatcher.php - line 133:

OC\AppFramework\Http\Dispatcher->executeController()

/var/www/nextcloud/lib/private/AppFramework/App.php - line 172:

OC\AppFramework\Http\Dispatcher->dispatch()

/var/www/nextcloud/lib/private/Route/Router.php - line 298:

OC\AppFramework\App::main()

/var/www/nextcloud/lib/base.php - line 1047:

OC\Route\Router->match()

/var/www/nextcloud/index.php - line 36:

OC::handleRequest()
```

### Mail app version

2.2.2

### Operating system

Ubuntu 22.04 LTS

### PHP engine version

PHP 8.1

### Web server

Apache (supported)

### Database

MySQL

### Additional info

Using the Mail-App and sending e-mails from there works. @ChristophWurst

**Comment by nietsmmar** [comment]
Actually I was able to fix it by using `mail.webclient6.de` instead of smtp.articlett.de.

Although it works with `smtp.articlett.de` in thunderbird etc.

**Comment by ChristophWurst** [comment]
Please report in the https://github.com/nextcloud/server repo. System mail is not handled by the Mail app. The Mail app is the IMAP client.
