### ISSUE TITLE
Add link picker to message composer modal

### ISSUE THREAD

**Issue by ChristophWurst** [nextcloud/mail#7986]
### Is your feature request related to a problem? Please describe.

As a user I want an easy way to pick links for github/giphy/etc in my emails without leaving the page

### Describe the solution you'd like

Preparation work
* Check which versions of Nextcloud the link picker is available. Compare to info.xml Nextcloud version range.

### Todo

0) Dispatch `RenderReferenceEvent` when the page is rendered (PageController)
1) Add a button *Add link* to the actions menu of the message composer
2) Open/render `ReferencePickerModal` from `nextcloud/vue-richtext@^2.1.0-beta.3` when the button is clicked
3) Insert the result of the picker into the editor, at the current cursor position (similar to link shares)

Known challenges
* Modal on top of modal can be tricky. E.g. <kbd>Esc</kbd> event is caught and handled by both instances.

### Describe alternatives you've considered

N/a

### Additional context

Input by @julien-nc 

> So, first things first, if you want to use the link picker in a page, make sure the RenderReferenceEvent is dispatched. Text does it when the viewer is loaded for example: https://github.com/nextcloud/text/blob/1c27b371c1e94079514062051c3df49104102e88/lib/Listeners/LoadViewerListener.php#L52
> 
> Then, the link picker itself. 2 ways to use it:
> - the helper function: https://github.com/nextcloud/text/blob/1c27b371c1e94079514062051c3df49104102e88/src/components/Suggestion/LinkPicker/suggestions.js#L30-L40
> This creates a Vue instance which mounts the ReferencePickerModal somewhere. The function returns a Promise which resolves with the link text
> - directly with the ReferencePickerModal component (exposed by the vue-richtext as well). It emits "submit" (with the link as data) and "cancel" events. You can optionally pass the initial selected provider as prop. In your case, you can use it without any prop.

**Comment by marcelklehr** [comment]
"Add link" -- the reference picker is also already being considered to be used for things other than links, just fyi

**Comment by ChristophWurst** [comment]
What else can it pick? Is there documentation or overview anywhere?

**Comment by julien-nc** [comment]
> Is there documentation or overview anywhere?

In progress, there will be some before 2>6 hopefully. In the meantime there's the code and there's me, sorry :grin:.

> What else can it pick?

There is no validation on what the custom picker components return so they can return any kind of text, not just links.
I made a few providers that return plain text like GPT-3 predictions or Whisper speech-to-text translations/transcriptions.

So I guess the term link picker is not perfect. We will sort this out soon in the team.

**Comment by julien-nc** [comment]
By the way, @marcelklehr had the idea to make a "template" provider so admins and users could define templates in the settings and they could be quickly reachable everywhere one can edit text in NC. That's another (good/bad?) reason to think about naming...

**Comment by ChristophWurst** [comment]
@julien-nc does the picker use APIs new in Nextcloud server 26? Do we need to hide it when this app is deployed to 25?

**Comment by julien-nc** [comment]
@ChristophWurst Yes it relies on some initial state that is only injected since 26. It can only be displayed in NC >= 26.

**Comment by ChristophWurst** [comment]
Makes sense. We'll add a version check.

**Comment by ChristophWurst** [comment]
@hamza221 we can inject the server version as initial state, like we do with debug mode: https://github.com/nextcloud/mail/blob/1eca995e5c3ba3169c77774fddd21ec30d6f10ae/lib/Controller/PageController.php#L123-L126 and https://github.com/nextcloud/mail/blob/1eca995e5c3ba3169c77774fddd21ec30d6f10ae/src/main.js#L61-L64
