### ISSUE TITLE
Delete search ("X") hovering over text in mailbox search

### ISSUE THREAD

**Issue by thstyl2000** [nextcloud/mail#8027]
### Steps to reproduce

1. Go to any mailbox
2. Type more than 1 character in the search

### Expected behavior

"X" appears on the far right of the box.

### Actual behavior

"X" appears on the far left of the box, on top of the search string.

### Mail app version

2.2.3

### Mailserver or service

dovecot

### Operating system

freebsd 13.1

### PHP engine version

PHP 8.1

### Web server

Apache (supported)

### Database

MariaDB

### Additional info

..like that:

![Screenshot_20230215_142722](https://user-images.githubusercontent.com/18458458/219041526-df00d3bc-8acc-48e5-b350-fb99fa044f56.png)

**Comment by ChristophWurst** [comment]
:eyes: @sazanof
