### ISSUE TITLE
Mail says server denied auth when accepted

### ISSUE THREAD

**Issue by virtualdxs** [nextcloud/mail#808]
### Steps to reproduce
1. Create new mail account for Exchange 2007 server

### Expected behaviour
Successful account creation

### Actual behaviour
Error while creating the account: Creating account failed: Server denied authentication.

### Mail app

**Mail app version:** 0.7.8

**Mailserver or service:** Exchange 2007

**Number of accounts:** Creating second one

## Server configuration detail

**Operating system:** Linux 4.14.12-x86_64-linode92 #1 SMP Fri Jan 5 15:34:44 UTC 2018 x86_64

**Webserver:** Caddy/0.10.10 (+9eba91f) (fpm-fcgi)

**Database:** pgsql PostgreSQL 10.1 on x86_64-pc-linux-gnu, compiled by gcc (GCC) 7.2.0, 64-bit

**PHP version:** 7.2.1
Modules loaded: Core, date, libxml, openssl, pcre, zlib, ctype, dom, fileinfo, filter, hash, json, mbstring, pcntl, SPL, PDO, session, posix, readline, Reflection, standard, SimpleXML, Phar, tokenizer, xml, xmlreader, xmlwriter, mysqlnd, cgi-fcgi, curl, gd, pdo_pgsql, zip

**Nextcloud version:** 13.0.0 Beta 3 - 13.0.0.8

**Updated from an older Nextcloud/ownCloud or fresh install:** Updated

Here's the tcpflow output:
```
tcpflow: listening on lo
127.000.000.001.08143-127.000.000.001.38942: * OK The Microsoft Exchange IMAP4 service is ready.

127.000.000.001.38942-127.000.000.001.08143: 1 CAPABILITY

127.000.000.001.08143-127.000.000.001.38942: * CAPABILITY IMAP4 IMAP4rev1 AUTH=NTLM AUTH=GSSAPI AUTH=PLAIN IDLE NAMESPACE LITERAL+
1 OK CAPABILITY completed.

127.000.000.001.38942-127.000.000.001.08143: 2 AUTHENTICATE PLAIN

127.000.000.001.08143-127.000.000.001.38942: +

127.000.000.001.38942-127.000.000.001.08143: [redacted]

127.000.000.001.08143-127.000.000.001.38942: 2 OK AUTHENTICATE completed.

127.000.000.001.38942-127.000.000.001.08143: 3 CAPABILITY

127.000.000.001.08143-127.000.000.001.38942: * CAPABILITY IMAP4 IMAP4rev1 AUTH=NTLM AUTH=GSSAPI AUTH=PLAIN IDLE NAMESPACE LITERAL+
3 OK CAPABILITY completed.

127.000.000.001.38942-127.000.000.001.08143: 4 LOGOUT

127.000.000.001.08143-127.000.000.001.38942: * BYE Microsoft Exchange Server 2007 IMAP4 server signing off.
4 OK LOGOUT completed.
```

Immediately after the logout it returns the error. It does not do anything over SMTP.

**Comment by ChristophWurst** [comment]
I'm closing this ticket because it hasn't received any updates in a long time. If this is still relevant, feel free to re-open or file a new ticket.

Thank you.
