### ISSUE TITLE
S/MIME: Certificate Modal: Size is not reponsive

### ISSUE THREAD

**Issue by st3iny** [nextcloud/mail#8082]
### Steps to reproduce

1. Open the certificate modal
2. Import a certificate with long names
3. Reduce the screen size to a mobile device.
4. Observe the modal.

### Expected behavior

The modal should be responsive and adapt to the content and varying screen sizes.

### Actual behavior

The modal is not responsive.

Its width is being truncated on small screens (goes off screen).
![grafik](https://user-images.githubusercontent.com/1479486/220896100-b8e08650-78ce-45b1-8d38-b92e7ce92a05.png)

Long texts will be truncated (hidden overflow).
![grafik](https://user-images.githubusercontent.com/1479486/220896034-2c6ce5cc-df8d-4569-94b8-df864a36eb1e.png)

### Mail app version

main

**Comment by GretaD** [comment]
on mobile version is slightly cut, otherwise, all good
![Screenshot from 2023-12-19 10-36-55](https://github.com/nextcloud/mail/assets/12728974/b2a7bc9b-f40d-4bdd-95a0-0eb4abc85720)
