### ISSUE TITLE
Folder sync adds new messages of other mailbox to the unified inbox [$30]

### ISSUE THREAD

**Issue by ChristophWurst** [nextcloud/mail#812]
### Steps to reproduce
1. Configure more than one account
2. Switch to the sent folder and send a new message
3. Refresh the folder
4. The sent message appears
5. Switch to unified inbox

### Expected behaviour
Don't see the sent message in the unified inbox.

### Actual behaviour
See the message there, too

**Comment by StCyr** [comment]
Hello @ChristophWurst 

Is this issue still current? 

I've tried to reproduce it here without success.

Cyrille

**Comment by ChristophWurst** [comment]
Nope, I think this was a problem with the old code base.
