### ISSUE TITLE
Content security policy violation

### ISSUE THREAD

**Issue by nickvergessen** [nextcloud/mail#8145]
### Steps to reproduce

1.c.nc.c after the upgrade to 26 beta5 with mail 3.0.0-alpha.0
![Bildschirmfoto vom 2023-02-24 23-35-43](https://user-images.githubusercontent.com/213943/221308777-24851f3f-a48e-41b5-acfa-6cd19afd578c.png)

After cheating `lib/public/AppFramework/Http/ContentSecurityPolicy.php` to allow `eval` those errors are gone, but there is an other

![Bildschirmfoto vom 2023-02-24 23-36-06](https://user-images.githubusercontent.com/213943/221309090-ef79099b-b151-49ce-88bc-da077b4e5e6f.png)

### Expected behavior

Mail should work

### Actual behavior

Mail only works on developer machines and there is a process thingy erroring

### Mail app version

3.0.0-alpha.0

### Operating system

Ubuntu LTS 22.04

### PHP engine version

PHP 8.1

### Web server

Apache (supported)

### Database

MariaDB

**Comment by nickvergessen** [comment]
We "fixed" this by replacing `apps/mail/js/mail.486.79bc1e80cfe84f6b82fd.js`
find:
```js
…if(process.env.NODE_DEBUG){var s=process.env.NODE_DEBUG…
```
with:
```js
…if(false&&process.env.NODE_DEBUG){var s=process.env.NODE_DEBUG…
```

**Comment by kesselb** [comment]
https://github.com/browserify/node-util/issues/57
