### ISSUE TITLE
[Bug]: App update stuck in maintenance mode. Nextcloud 25.0.2

### ISSUE THREAD

**Issue by CSchaefer70** [nextcloud/mail#8148]
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [X] This issue is **not** already reported on Github _(I've searched it)_.
- [X] Nextcloud Server **is** up to date. See [Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) for supported versions.
- [X] Nextcloud Server **is** running on 64bit capable CPU, PHP and OS.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Bug description

Nextcloud was running fine.  No issues.  I recvd notification that two apps needed update: SnappyMail and Mail.

Logged in as admin and proceeded to the APP page and selected update "SnappyMail" and the process finished normally.  Next, I selected "Mail" and the NextCloud 25.0.2 is stuck in maintenance mode.

I tried to reset "maintenance mode" to false; no change.  I tried increasing "Memory limit to 768mb"; no change.
![image](https://user-images.githubusercontent.com/26978180/221351989-b5b2f483-3977-464b-b3b5-498dab71480c.png)

### Steps to reproduce

1. Log in as admin
2. Go to "Apps"
3. Select specific app to update.  In this case it was Mail
4. Update initiates but never completes... stuck in "Maintenance mode"

Config report:
```
Nextcloud or one of the apps require upgrade - only a limited number of commands are available
You may use your browser or the occ upgrade command to do the upgrade
{
    "system": {
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "www.kingdomharvest.club"
        ],
        "datadirectory": "***REMOVED SENSITIVE VALUE***",
        "dbtype": "mysql",
        "version": "25.0.2.3",
        "overwrite.cli.url": "https:\/\/www.kingdomharvest.club\/nc",
        "dbname": "***REMOVED SENSITIVE VALUE***",
        "dbhost": "***REMOVED SENSITIVE VALUE***",
        "dbport": "",
        "dbtableprefix": "oc_",
        "mysql.utf8mb4": true,
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "installed": true,
        "mail_smtpmode": "smtp",
        "mail_smtphost": "***REMOVED SENSITIVE VALUE***",
        "mail_sendmailmode": "smtp",
        "mail_smtpport": "587",
        "mail_smtpsecure": "tls",
        "mail_from_address": "***REMOVED SENSITIVE VALUE***",
        "mail_domain": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpauth": 1,
        "mail_smtpname": "***REMOVED SENSITIVE VALUE***",
        "mail_smtppassword": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpauthtype": "LOGIN",
        "maintenance": true,
        "theme": "",
        "loglevel": 2
    }
}
root@localhost:/var/www/html/nc#
```

*************
APP List
![image](https://user-images.githubusercontent.com/26978180/221352823-42233e2a-c612-4816-8387-cc33420f4ce1.png)

### Expected behavior

The expected behavior is that the update process would confirm all parameter are valid for an update.  If not a warning or simply not proceed with the update with recommendations of what is missing or incompatibilities.

If the update is valid then proceed and upon completion reset "maintenance" to "false"; return to normal operation.

### Installation method

Community Web installer on a VPS or web space

### Operating system

Debian/Ubuntu

### PHP engine version

PHP 8.1

### Web server

Apache (supported)

### Database engine version

MariaDB

### Is this bug present after an update or on a fresh install?

Fresh Nextcloud Server install

### Are you using the Nextcloud Server Encryption module?

Encryption is Enabled

### What user-backends are you using?

- [X] Default user-backend _(database)_
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

### Configuration report

```shell
see above
```

### List of activated Apps

```shell
see above
```

### Nextcloud Signing status

```shell
I can't log in.
```

### Nextcloud Logs

```shell
/contacts/vendor/autoload.php"],"function":"require_once"},{"file":"/var/www/html/nc/lib/private/legacy/OC_App.php","line":285,"args":["/var/www/html/nc/apps/contacts/composer/autoload.php"],"function":"require_once"},{"file":"/var/www/html/nc/lib/private/AppFramework/Bootstrap/Coordinator.php","line":117,"function":"registerAutoloading","class":"OC_App","type":"::"},{"file":"/var/www/html/nc/lib/private/AppFramework/Bootstrap/Coordinator.php","line":91,"function":"registerApps","class":"OC\\AppFramework\\Bootstrap\\Coordinator","type":"->"},{"file":"/var/www/html/nc/lib/base.php","line":671,"function":"runInitialRegistration","class":"OC\\AppFramework\\Bootstrap\\Coordinator","type":"->"},{"file":"/var/www/html/nc/lib/base.php","line":1144,"function":"init","class":"OC","type":"::"},{"file":"/var/www/html/nc/console.php","line":48,"args":["/var/www/html/nc/lib/base.php"],"function":"require_once"},{"file":"/var/www/html/nc/occ","line":11,"args":["/var/www/html/nc/console.php"],"function":"require_once"}],"File":"/var/www/html/nc/lib/private/Log/ErrorHandler.php","Line":92,"CustomMessage":"--"}}
{"reqId":"8818Wi7RMwS99qcFoOsD","level":3,"time":"2023-02-25T10:50:20+00:00","remoteAddr":"","user":"--","app":"PHP","method":"","url":"--","message":"Composer detected issues in your platform: Your Composer dependencies require a PHP version \">= 8.0.0\". You are running 7.4.30. at /var/www/html/nc/apps/contacts/vendor/composer/platform_check.php#24","userAgent":"--","version":"25.0.2.3","exception":{"Exception":"Error","Message":"Composer detected issues in your platform: Your Composer dependencies require a PHP version \">= 8.0.0\". You are running 7.4.30. at /var/www/html/nc/apps/contacts/vendor/composer/platform_check.php#24","Code":0,"Trace":[{"function":"onError","class":"OC\\Log\\ErrorHandler","type":"::"},{"file":"/var/www/html/nc/apps/contacts/vendor/composer/platform_check.php","line":24,"function":"trigger_error"},{"file":"/var/www/html/nc/apps/contacts/vendor/composer/autoload_real.php","line":25,"args":["/var/www/html/nc/apps/contacts/vendor/composer/platform_check.php"],"function":"require"},{"file":"/var/www/html/nc/apps/contacts/vendor/autoload.php","line":25,"function":"getLoader","class":"ComposerAutoloaderInitContacts","type":"::"},{"file":"/var/www/html/nc/apps/contacts/composer/autoload.php","line":5,"args":["/var/www/html/nc/apps/contacts/vendor/autoload.php"],"function":"require_once"},{"file":"/var/www/html/nc/lib/private/legacy/OC_App.php","line":285,"args":["/var/www/html/nc/apps/contacts/composer/autoload.php"],"function":"require_once"},{"file":"/var/www/html/nc/lib/private/AppFramework/Bootstrap/Coordinator.php","line":117,"function":"registerAutoloading","class":"OC_App","type":"::"},{"file":"/var/www/html/nc/lib/private/AppFramework/Bootstrap/Coordinator.php","line":91,"function":"registerApps","class":"OC\\AppFramework\\Bootstrap\\Coordinator","type":"->"},{"file":"/var/www/html/nc/lib/base.php","line":671,"function":"runInitialRegistration","class":"OC\\AppFramework\\Bootstrap\\Coordinator","type":"->"},{"file":"/var/www/html/nc/lib/base.php","line":1144,"function":"init","class":"OC","type":"::"},{"file":"/var/www/html/nc/console.php","line":48,"args":["/var/www/html/nc/lib/base.php"],"function":"require_once"},{"file":"/var/www/html/nc/occ","line":11,"args":["/var/www/html/nc/console.php"],"function":"require_once"}],"File":"/var/www/html/nc/lib/private/Log/ErrorHandler.php","Line":92,"CustomMessage":"--"}}
```

### Additional info

I believe the issue is that "Mail" needs some additional updates.  I believe if I could run the update again it might go, but, I am not familiar with the .occ command.

Is there another way to initiate the update again?

Perhaps if I remove the "updater..." file from my data directory: /var/www/html/nc/data and then set "maintenance mode = false"??

**Comment by kesselb** [comment]
A common problem is that webserver and shell are using different php versions. Run `php -v` to see the php version used by the shell. 

Is there anything else in your nextcloud.log? The loglines do not look related.

**Comment by CSchaefer70** [comment]
Php -v returns:
![image](https://user-images.githubusercontent.com/26978180/221438395-ece45102-51a7-412c-bcb0-2bdedc5d8bd1.png)

**Comment by kesselb** [comment]
You have two options to make occ (the command line utility for nextcloud) work:

1) Change the default php version for the shell. The search engine of your choice will tell you how for your operating system.

2) Use the right php version if you run occ.  For example php8.1 occ instead of php occ.

**Comment by CSchaefer70** [comment]
Yikes, I just noticed 171 Updates available on Ubuntu!!

Should I do this?  I don't want to confuse the troubleshooting isolation.

If you suggest yes, then what is the best command for Ubuntu... I'm new to LINUX. Sorry.
![image](https://user-images.githubusercontent.com/26978180/221438832-93dc6c8e-b744-4804-8627-a15949a5f64c.png)

**Comment by kesselb** [comment]
To turn the maintenance mode off via occ:

`occ maintenance:mode --off` (dont forget to prepend the right php version and/or sudo if applicable).

I cannot provide you help with or how to update your server. 
Feel free to ask your question at https://help.nextcloud.com.

**Comment by CSchaefer70** [comment]
OK.  I found this... is PHP V8.2 OK?
![image](https://user-images.githubusercontent.com/26978180/221439059-e31c9c7a-be4e-42ce-a0bf-091cd00beb4c.png)

**Comment by CSchaefer70** [comment]
Here is the full log file from the NextCloud

[nextcloud.log](https://github.com/nextcloud/mail/files/10834829/nextcloud.log)

**Comment by kesselb** [comment]
Thanks for the log. There are no lines related to mail.

**Comment by BiglifeMatt** [comment]
@CSchaefer70 This may actually be just related to Snappymail.  I've seen this happen with several updates of that including the most recent.  I've reported and it was working fine with the last couple of updates but now this happens again.  It may appear that it worked because you click it and it drops off the list but if you were to have refreshed prior to updating the Mail app, you probably would have found it in maintenance mode already.  That has simply been my experience for what it is worth.

**Comment by CSchaefer70** [comment]
Hey, thx for the feedback.  I have not had the time to resolve, but, I still think it has to do with the "Mail" app (not Snappy).  I do each app update separately and wait for finish/refresh.  Then I actually bounce out to the Dashboard and check the app.  The maintenance mode got stuck on the "Mail" app, which I only had installed to compare to Snappy!

Anyway, still not working.  My next move when I get time is to remove the Mail App in command line; then restart Apache.

**Comment by BiglifeMatt** [comment]
That is strange that I'm only ever noticing this with Snappymail... makes me wonder if it is even any specific app or the way perhaps an app is getting corrupt within the instance.  That said have you just tried going to /path/for/Nextcloud and in the the config folder edit the config.php file, turn the maintenance flag to 'false', then restart php service?  That is what I have to do.  Then I can refresh the website and manually continue the update.

**Comment by CSchaefer70** [comment]
Yes. I have tried to turn the maintenance on and off (true, false) via the "config.php'.  Followed by Apache restart.  No change.

If you like I'll give you access... try!!

I enjoy your interest.  Thank you. I really love NextCloud, especially the latest 25+ version.  More personal and artistic.

**Comment by CSchaefer70** [comment]
Hey, I just tried a SnappyMail update on another NextCloud website (completely different URL) and it got stuck in the "Maintenance Mode" just like the other "Mail" app issue.  So it seems a systemic issue?

**Comment by CSchaefer70** [comment]
I recovered by Server Image recovery.  Now I'm stuck... I cannot trust NextCloud updates. Yikes... very sad.

**Comment by BiglifeMatt** [comment]
For what it is worth, I have only seen this with Snappymail.  I have the Mail app but it has never caused an issue updating.  I do compare them as well.  The Mail app has some better integration between other apps like Calendar and Contacts.  But it doesn't read from my ldap mapping table so I cannot use it to auto suggest name in the to: field.  Otherwise it would be our primary choice.

**Comment by CSchaefer70** [comment]
I updated to the php8+ from a recommendation of my database choice: Maria 10+.  Also, NextCloud recommends php8.1+ with NextCloud version 24+.

"PHP8. 1. Nextcloud 24 is the first major Nextcloud release to work with PHP8. 1."

**Comment by ChristophWurst** [comment]
It's not in the power of apps to dictate if maintenance mode should be on or off.

**Comment by Githopp192** [comment]
> It's not in the power of apps to dictate if maintenance mode should be on or off.

but do not the apps trigger the maintenance mode to ON, when an update will happen ?

**Comment by Githopp192** [comment]
> No

Ok, but everytime an app is "update mode", the cloud switches to Maintenance Mode = ON, that i can say for sure.

Then who will trigger the Cloud to Maintenance Mode in such cases ?

**Comment by ChristophWurst** [comment]
Nextcloud server

**Comment by Githopp192** [comment]
> Nextcloud server

Great - but, when an app is going to upgrade - the app informs the server to enable maint-mode ?
When yes, i do suppose, that the app again will inform the server, when the update is complet to set maint-mode to OFF.

Correct ? When no - how is the procedure - & how it comes to situations, where the cloud keeps maint-mode after an app update ?

**Comment by Githopp192** [comment]
i do not hope, that chatGPT sometimes will replace human interaction :-)

ChatGPT:

Yes, it is possible for Nextcloud apps to keep the maintenance mode enabled after an update, which can be an issue if the maintenance mode is preventing users from accessing the application. Typically, when an app is updated, Nextcloud will automatically disable the maintenance mode. However, in some cases, an app may not properly handle the update process, which can result in the maintenance mode being left enabled.

To address this issue, you can try disabling the maintenance mode manually by logging into your Nextcloud instance via SSH and running the following command:

kotlin
Copy code
sudo -u www-data php /var/www/nextcloud/occ maintenance:mode --off
This command should disable the maintenance mode and allow users to access the application again. If the issue persists or if you encounter any other problems, you may want to reach out to the Nextcloud community for assistance.

**Comment by ChristophWurst** [comment]
> Great - but, when an app is going to upgrade - the app informs the server to enable maint-mode ?
> When yes, i do suppose, that the app again will inform the server, when the update is completed to set maint-mode to OFF.

No, Nextcloud server drives the process.

> how it comes to situations, where the cloud keeps maint-mode after an app update ?

I do not know

**Comment by Githopp192** [comment]
> 

OK, fine - how i can help to debug such situations ?

**Comment by metalcated** [comment]
If anyone is using php fpm, restart the service and see if that helps.

**Comment by joshtrichards** [comment]
@CSchaefer70 All indications are in your final log entries that you're out of storage space. That is a problem. It also may even be preventing further logging.

**Comment by joshtrichards** [comment]
@Githopp192 It appears you're doing some sort of scripted app updates (you mentioned auto updates but we don't do any auto updates). Based on your log output are you doing the updates via `occ`? What are your PHP opcache settings?  In particular, `opcache.revalidate_freq` and `opcache.validate_timestamps`? (see https://docs.nextcloud.com/server/latest/admin_manual/installation/server_tuning.html#enable-php-opcache).

**Comment by kesselb** [comment]
Closing, as I don't see an issue that could be addressed in mail app.

**Comment by Githopp192** [comment]
> @Githopp192 It appears you're doing some sort of scripted app updates (you mentioned auto updates but we don't do any auto updates). Based on your log output are you doing the updates via `occ`? What are your PHP opcache settings? In particular, `opcache.revalidate_freq` and `opcache.validate_timestamps`? (see https://docs.nextcloud.com/server/latest/admin_manual/installation/server_tuning.html#enable-php-opcache).

yes, doing the update via occ (/var/www/html/nextcloud/occ app:update)

PHP opcache settings: 

opcache.revalidate_freq=15

; When disabled, you must reset the OPcache manually or restart the
; webserver for changes to the filesystem to take effect.
;opcache.validate_timestamps=1

(suppose the default value for opcache.validate_timestamps=1 ?!)
