### ISSUE TITLE
Show sharing icon for mailboxes shared with me

### ISSUE THREAD

**Issue by ChristophWurst** [nextcloud/mail#8157]
### Is your feature request related to a problem? Please describe.

As a recipient of mailbox shares I want to be able to visually distinguish between my own and shared mailboxes.

### Describe the solution you'd like

Show a sharing icon like we do in Files
 
![Bildschirmfoto vom 2023-02-28 10-37-31](https://user-images.githubusercontent.com/1374172/221813038-1242ba65-ce09-4b6a-a205-f674aa133557.png)

### Describe alternatives you've considered

N/a

### Additional context

https://github.com/nextcloud/mail/issues/7057

**Comment by ChristophWurst** [comment]
If `myAcls` is not sufficient to distinguish between owned and shared mailbox, we need to fetch more ACL data: https://datatracker.ietf.org/doc/html/rfc4314.html#section-3

**Comment by GretaD** [comment]
While brainstorming with Christoph we realized that:

1) not possible to distinguish based on my ACL rights
2) not possible to distinguish reliably based on mailbox path
