### ISSUE TITLE
Limit remote hosts, or email domains to configured list of allowed

### ISSUE THREAD

**Issue by omitrowski** [nextcloud/mail#8177]
### Is your feature request related to a problem? Please describe.

My problem is, that I am not able to limit, or bind the user to our mail server setup (IMAP Host, SMTP Host, TLS, Cert check). This is from my perspective a security issue if any mail server can be used in a scope of nextcloud. E.g. easy to share files using the wron account.

### Describe the solution you'd like

The solution might be like SnappyMail, where one is able to provide a email domain list and preconfigure the imap/smpt settings.

### Describe alternatives you've considered

SnappyMail

### Additional context

I did not found any settings for now to limit or preconfigure the account, but perhaps the there are some, just not documented?

**Comment by ChristophWurst** [comment]
Provisioning is supported via the admin settings UI. See the *Groupware* section. There is also *Allow additional mail accounts* you can turn off.

For further questions please use the forums at https://help.nextcloud.com/c/apps/mail/35
