### ISSUE TITLE
Request: foldable mail account

### ISSUE THREAD

**Issue by hensschenit** [nextcloud/mail#818]
It would be nice if you could implement a feature that allows me to collapse the top of an email address.
If you set up over 4 e-mail addresses in "Mail" it quickly becomes confusing.

See the attached example...

Thanks!
![unbenannt](https://user-images.githubusercontent.com/37070600/36974034-7de97684-2075-11e8-98c0-f71720aaa746.png)

**Comment by ChristophWurst** [comment]
cc @nextcloud/mail what do you think?

IMO we've already a decent expand/collapse feature that only shows the most commonly used mailboxes and hides the rest. Hence, I'm very hesitant on adding another collapse mechanism. Personally, I prefer it the way it is right now.

**Comment by jancborchardt** [comment]
Agree wih Christoph here, we already only show the important folders. We could additionally only show Drafts and Favorites if there are any drafts or favorites.

**Comment by ChristophWurst** [comment]
> We could additionally only show Drafts and Favorites if there are any drafts or favorites.

Great idea but out of scope as long as we don't have reliable draft counters and reliable folder status on the client-side -> closing as wontfix.

@hensschenit thanks for your feedback!
