### ISSUE TITLE
Allow any of the user profile additional e-mail addresses to be used in the From field

### ISSUE THREAD

**Issue by hunterdrayman** [nextcloud/mail#8183]
### Describe the solution you'd like

A drop down list in the From field

### Describe alternatives you've considered

I don't like creating an account for each alias as this leads to a very cluttered nav bar with much duplication.

### Additional context

I use virtual aliases on my IMAP server which map user7@dom2, user2@dom3 etc. into a primary identity user1@dom1. It would be simply wonderful if any of these aliases could be selectable in the from field when composing or replying. Rainloop achieves this via identities. Nextcloud mail has this possibility tantalizingly out of reach via the additional e-mail addresses on a user's profile.

**Comment by ChristophWurst** [comment]
You can add the aliases in your account settings.

There is no strong relation between nextcloud settings, additional emails and aliases in Mail.
