### ISSUE TITLE
Request: Dashboard/Overview for multiple mail accounts

### ISSUE THREAD

**Issue by hensschenit** [nextcloud/mail#819]
I'm just starting in "Mail" and have used Open-Xchange before.
Maybe you know the portal of OXchange, where it is possible to place widgets that are referencing to an email folder?

It would be great if you could implement something like that, if anyone else needs it!

Thanks -Tommy

**Comment by ChristophWurst** [comment]
> Maybe you know the portal of OXchange, where it is possible to place widgets that are referencing to an email folder?

I don't. Could you please link a screenshot to this software?

**Comment by hensschenit** [comment]
Of course i could...
![oxportal](https://user-images.githubusercontent.com/37070600/36975044-1b928486-2079-11e8-9ad1-27d346a01c57.jpg)

**Comment by ChristophWurst** [comment]
Thanks!

I don't think this would provide any added value to this app. We already have a unified inbox that shows you a combination of all inboxes' new emails. Thus, this would be quite redundant. And having this dashboard configurable sound like a lot of work to implement. Therefore, I'm closing this ticket as 'wontfix'.

Thanks for your feedback, I really appreciate you reporting this here.
