### ISSUE TITLE
Size of new message window flexible or bigger or default size setting

### ISSUE THREAD

**Issue by slu-010101** [nextcloud/mail#8199]
### Is your feature request related to a problem? Please describe.

It is very hard to write longer emails with the small window.

### Describe the solution you'd like

Please make it possible to resize the message window.

### Describe alternatives you've considered

Additional to the bigger window a pop-up window would be perfect.

**Comment by slu-010101** [comment]
![window size](https://user-images.githubusercontent.com/11032756/222759410-b1ef15d0-3930-4dc2-bc31-77275cdcfd38.png)

**Comment by slu-010101** [comment]
The small mail compose window is still a showstopper for nextcloud mail (IMHO)...

**Comment by ChristophWurst** [comment]
Dup of https://github.com/nextcloud/mail/issues/9100

**Comment by roelofz** [comment]
Not to criticize development, you have to make choices based on effect on Enterprise (paying) users.
But...
Do I assume right the mail app is not so often used in Enterprise environments?
This would explain for me you are stating this as not planned as this seems pretty trivial in business usage (I am typing in nc mail during business hours while also using a commercial mail app (not to name it, they forced me to use it).

Again, you have to look at your resources so I understand why development has to make choices.
I really am curious about the background of this choice.

**Comment by ChristophWurst** [comment]
Apologies if my comment was not clear. "Dup" is an abbreviation for "Duplicate". This ticket is a duplicate of the existing ticket https://github.com/nextcloud/mail/issues/9100. When closing as duplicate, github shows the ticket as *not planned*. That is unfortunate and misleading.

**Comment by roelofz** [comment]
Hi Christoph,

You are referring to a closed issue, so I understood the dup, but could not understand this as solved.
To me the client interface is taking too much space with limited effective use of space, and this is the biggest example of it. 
Despite the enlarge window button the interface is still too small for reading back in the conversation.
Comparing with other clients, even Snappymail, this is a big difference in approach, makes me wonder as I did in the earlier post about the Enterprise usage.

**Comment by ChristophWurst** [comment]
Have you seen https://github.com/nextcloud/mail/issues/6589? I think this covers your concern.
