### ISSUE TITLE
[Bug] "Unread Mail" and "Important Mail" widgets taller then other widgets when empty

### ISSUE THREAD

**Issue by jontok** [nextcloud/mail#8210]
### Steps to reproduce

1. Install Nextcloud (e.g. docker)
2. Install Nextcloud Mail
3. Add Widgets without connecting to a Mail account

### Expected behavior

All widgets should be the same height, empty or with items in it.

### Actual behavior

The "Important Mail" and "Unread Mail" widgets are slightly taller than other widgets, if they have no contents.
As soon as an Item is shown in the widget the widget size is the same size as all other widgets

### Mail app version

2.2.4

### Mailserver or service

/

### Operating system

Linux Mint 21.

### PHP engine version

8.1.16

### Web server

apache

### Database

sql-light

**Comment by st3iny** [comment]
Thanks for the report.

May I ask which version of Nextcloud (server) are you using?

**Comment by hamza221** [comment]
[#36498](https://github.com/nextcloud/server/pull/36498)

**Comment by st3iny** [comment]
I can't reproduce it on stable25 so I consider this as fixed.

**Comment by jontok** [comment]
@st3iny Nextcloud Server 25.0.4
