### ISSUE TITLE
Intermittent Error: Mail server denied authentication

### ISSUE THREAD

**Issue by jbkstuff** [nextcloud/mail#822]
So, I am not sure where my setup has gone awry. I can authenticate with the IMAP/SMTP servers and send/receive fine, but performing actions on messages seems to have a 25% failure rate. After looking at the horde_imap logs below, I thought it might just be my IMAP server blowing up, I don't see anything in the logs for that server. Also, none of the other mail clients connected to the IMAP server have had any trouble. So, it certainly might still be a server-side issue, but I thought I would see if anyone else has experienced this error before and knows its cause.  

### Steps to reproduce
1. Using normal IMAP/SMTP setup. (Successfully authenticated).
2. Folders and messages are displayed correctly and everything works some of the time.
3. Sometimes when performing some action on existing messages (such as moving to a different folder or marking as favorite) the action fails due to the following error: "Horde_Imap_Client_Exception: Mail server denied authentication."

### Expected behaviour
All actions should be successful. 

### Actual behaviour
Sometimes an action fails. It does not seem to be tied to the particular action I am trying to perform because often I can refresh the web-page and then successfully perform the same action.  

I have tried various values in the config.php for app.mail.imap.timeout (10-40) and none of them had any apparent effect.

### Mail app

**Mail app version:**: 0.7.9
**Mailserver or service:**: Postfix/Dovecot
**Number of accounts:**: 1

### Server configuration

**Operating system:** Linux 4.4.0-116-generic #140-Ubuntu SMP Mon Feb 12 21:23:04 UTC 2018 x86_64

**Webserver:** Caddy/0.10.10 (fpm-fcgi)

**Database:** pgsql PostgreSQL 9.6.8 on x86_64-pc-linux-gnu (Debian 9.6.8-1.pgdg80+1), compiled by gcc (Debian 4.9.2-10+deb8u1) 4.9.2, 64-bit

**PHP version:** 7.1.14
Modules loaded: Core, date, libxml, openssl, pcre, sqlite3, zlib, ctype, curl, dom, fileinfo, filter, ftp, hash, iconv, json, mbstring, SPL, PDO, session, posix, readline, Reflection, standard, SimpleXML, pdo_sqlite, Phar, tokenizer, xml, xmlreader, xmlwriter, mysqlnd, cgi-fcgi, apcu, exif, gd, intl, ldap, mcrypt, memcached, mysqli, pcntl, pdo_mysql, pdo_pgsql, pgsql, redis, zip, Zend OPcache

**Nextcloud version:** 12.0.5 - 12.0.5.3

**Updated from an older version or fresh install:** Fresh Install

**The content of config/config.php:**

<details>
```
{
    "debug": false,
    "memcache.local": "\\OC\\Memcache\\APCu",
    "apps_paths": [
        {
            "path": "\/var\/www\/html\/apps",
            "url": "\/apps",
            "writable": false
        },
        {
            "path": "\/var\/www\/html\/custom_apps",
            "url": "\/custom_apps",
            "writable": true
        }
    ],
    "instanceid": "***REMOVED SENSITIVE VALUE***",
    "passwordsalt": "***REMOVED SENSITIVE VALUE***",
    "secret": "***REMOVED SENSITIVE VALUE***",
    "trusted_domains": [
        "***REMOVED SENSITIVE VALUE***.com"
    ],
    "datadirectory": "\/var\/www\/html\/data",
    "overwrite.cli.url": "https:\/\/cloud.kuester7.com",
    "dbtype": "pgsql",
    "version": "12.0.5.3",
    "dbname": "nextcloud",
    "dbhost": "nextcloud-db",
    "dbport": "",
    "dbtableprefix": "oc_",
    "dbuser": "***REMOVED SENSITIVE VALUE***",
    "dbpassword": "***REMOVED SENSITIVE VALUE***",
    "installed": true,
    "loglevel": 2,
    "maintenance": false,
    "mail_smtpmode": "smtp",
    "mail_smtpauthtype": "PLAIN",
    "mail_from_address": "***REMOVED SENSITIVE VALUE***",
    "mail_domain": "***REMOVED SENSITIVE VALUE***.com",
    "mail_smtpauth": 1,
    "mail_smtphost": "***REMOVED SENSITIVE VALUE***.com",
    "mail_smtpport": "465",
    "mail_smtpname": "***REMOVED SENSITIVE VALUE***",
    "mail_smtppassword": "***REMOVED SENSITIVE VALUE***",
    "mail_smtpsecure": "ssl",
    "theme": "nextcloud-breeze-dark",
    "app.mail.imap.timeout": 10
}
```
</details>

#### Client configuration
**Browser:** Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/64.0.3282.167 Safari/537.36

##### Server log (data/nextcloud.log)
<details>
```
Horde_Imap_Client_Exception: Error connecting to mail server.
/var/www/html/custom_apps/mail/vendor/pear-pear.horde.org/Horde_Imap_Client/Horde/Imap/Client/Socket.php - line 375: Horde_Imap_Client_Socket->_connect()
/var/www/html/custom_apps/mail/vendor/pear-pear.horde.org/Horde_Imap_Client/Horde/Imap/Client/Base.php - line 833: Horde_Imap_Client_Socket->_login(*** sensitive parameters replaced ***)
/var/www/html/custom_apps/mail/vendor/pear-pear.horde.org/Horde_Imap_Client/Horde/Imap/Client/Base.php - line 1593: Horde_Imap_Client_Base->login(*** sensitive parameters replaced ***)
/var/www/html/custom_apps/mail/vendor/pear-pear.horde.org/Horde_Imap_Client/Horde/Imap/Client/Base.php - line 4033: Horde_Imap_Client_Base->status(Object(Horde_Imap_Client_Mailbox), 8713)
/var/www/html/custom_apps/mail/vendor/pear-pear.horde.org/Horde_Imap_Client/Horde/Imap/Client/Base.php - line 3627: Horde_Imap_Client_Base->_syncStatus(Object(Horde_Imap_Client_Mailbox))
/var/www/html/custom_apps/mail/lib/IMAP/Sync/Synchronizer.php - line 57: Horde_Imap_Client_Base->sync(Object(Horde_Imap_Client_Mailbox), 'U162,V151875384...', Array)
/var/www/html/custom_apps/mail/lib/Service/MailManager.php - line 86: OCA\Mail\IMAP\Sync\Synchronizer->sync(Object(Horde_Imap_Client_Socket), Object(OCA\Mail\IMAP\Sync\Request))
/var/www/html/custom_apps/mail/lib/Controller/FoldersController.php - line 95: OCA\Mail\Service\MailManager->syncMessages(Object(OCA\Mail\Account), Object(OCA\Mail\IMAP\Sync\Request))
[internal function] OCA\Mail\Controller\FoldersController->sync(5, 'SU5CT1g=', 'VTE2MixWMTUxODc...', Array)
/var/www/html/lib/private/AppFramework/Http/Dispatcher.php - line 160: call_user_func_array(Array, Array)
/var/www/html/lib/private/AppFramework/Http/Dispatcher.php - line 90: OC\AppFramework\Http\Dispatcher->executeController(Object(OCA\Mail\Controller\FoldersController), 'sync')
/var/www/html/lib/private/AppFramework/App.php - line 114: OC\AppFramework\Http\Dispatcher->dispatch(Object(OCA\Mail\Controller\FoldersController), 'sync')
/var/www/html/lib/private/AppFramework/Routing/RouteActionHandler.php - line 47: OC\AppFramework\App main('OCA\\Mail\\Contro...', 'sync', Object(OC\AppFramework\DependencyInjection\DIContainer), Array)
[internal function] OC\AppFramework\Routing\RouteActionHandler->__invoke(Array)
/var/www/html/lib/private/Route/Router.php - line 299: call_user_func(Object(OC\AppFramework\Routing\RouteActionHandler), Array)
/var/www/html/lib/base.php - line 1004: OC\Route\Router->match('/apps/mail/api/...')
/var/www/html/index.php - line 48: OC handleRequest()
{main}
```
</details>

##### IMAP log (data/horde_imap.log)
<details>
```
>> Connection to: imap://***REMOVED SENSITIVE VALUE***.com:993/
>> Server connection took 0.2679 seconds.
S: * OK IMAP4 ready
C: 1 CAPABILITY
S: * CAPABILITY IMAP4 IMAP4rev1 UIDPLUS AUTH=PLAIN
S: 1 OK completed
>> Command 1 took 0.0852 seconds.
C: 2 [INITIAL CLIENT RESPONSE (username:***REMOVED SENSITIVE VALUE***.com)]
S: +
C: ***REMOVED SENSITIVE VALUE***==
S: * BAD internal server error
>> ERROR: Server closed the connection.
```
</details>

**Comment by ChristophWurst** [comment]
> seems to have a 25% failure rate

Is this possibly caused by a IMAP/SMTP timeout? Please try to increase it https://github.com/nextcloud/mail/blob/master/doc/admin.md#timeouts and report back whether that helps.

**Comment by jbkstuff** [comment]
Thank you for the suggestion!  I added the timeouts to my NextCloud ./config/config.php. Is there anything special I need to do for them to get picked up besides restarting the service?  I have tried a range of values (SMTP 1-32, IMAP 10-320) and none of them seemed to have any effect. 

One thing I did notice in my testing is that there are pretty clearly defined time ranges in which I get the error. I was testing by just dragging messages from one folder to another one at a time. I saw that the messages would move successfully for ~20-25 seconds and then for the next ~35-40 seconds I would get the above error, then without refreshing the page or doing anything different the messages would start to move successfully again for ~20-25 seconds and the process would start over. (Also, the changing timeout values did not seem to have any effect on these time ranges.)

**Comment by ChristophWurst** [comment]
Thanks for your feedback. Actually, the new configuration is applied right away - you don't even have to restart your server.

Another possible issue could be too many connections to your IMAP server. Do you host it yourself?

**Comment by jbkstuff** [comment]
Yes, I am hosting my own IMAP server. I initially suspected that the problem was there (and still think that it very possible). But, I have not seen any errors come through in the IMAP server's logs.  

However, my IMAP server is behind an instance of NGINX and I ended up looking at those logs today and saw the following get spit out whenever I got the above error in NextCloud Mail:
> 127.0.0.1 - - [06/Mar/2018:23:36:29 +0000] "GET /auth/email HTTP/1.0" 429 143 "-" "-"
> 2018/03/06 23:36:29 [error] 10#10: *47571 auth http server 127.0.0.1:8000 did not send server or port while in http auth state, client: ***NEXTCLOUD_IP_ADDR***, server: 0.0.0.0:993, login: "***MY_EMAIL_ADDR***.com"

Still not entirely sure what this means, but it leads me to suspect that the problem is with my mail server and not Nextcloud Mail.  (Though I would welcome any thoughts you might have as to why I would be seeing this error when using Nectcloud Mail, but not other clients such as Thunderbird...)

**Comment by ChristophWurst** [comment]
> errors come through in the IMAP server's logs.

Have you tried turning on [debug mode](https://docs.nextcloud.com/server/13/developer_manual/general/devenv.html#enabling-debug-mode) and taking a look at the `data/horde_imap.log` file? Maybe the issued IMAP commands can help you.

**Comment by jbkstuff** [comment]
So, after looking through the horde_imap.log file, I noticed that it seemed to be failing when trying to login. I also noticed that when I performed successful actions on messages it was also logging in before performing each action.  

After talking with some other folks I found that my mail server was rate-limiting successful authentications (not just failed auth attempts).  So, after performing a certain number of actions, my mail server would stop accepting auth requests for a period of time and cause any further attempted actions to fail.

At this point, I have just increased my authentication rate limit on the mail server and that solved my problem. Not sure if the Horde libraries require re-authenticating between every action or if that could perhaps be improved in the future... (Supporting some batch operations on messages would also probably help).  Will have to brush up on my JS :)

Thank you for the help!

**Comment by ChristophWurst** [comment]
@jbkstuff thanks for this valuable feedback. There's also the possibility that we're opening more connections than necessary for the move operation. Generally, we're limited in what we can do about this as the way PHP processes work doesn't really allow keeping a connection open across requests. Someone once reported that there is software that proxies the IMAP protocol. That wouldn't help in your scenario though as you're running the IMAP server yourself (and thus assuming it's on the some host and/or network).
