### ISSUE TITLE
Customizable Email Timestamps

### ISSUE THREAD

**Issue by DevynCJohnson** [nextcloud/mail#8220]
### Is your feature request related to a problem? Please describe.

Making the timestamp for emails customizable would be helpful as a timestamp of "Saturday" (using the attached screenshot as an example) is useless as the time of day on Saturday is relevant for my use-cases. I understand some people want a short as possible timestamp, but this does not work for all users. Making this a user-configurable feature would then satisfy the most users.

![Timestamp](https://user-images.githubusercontent.com/4014076/224544310-260fbd01-f975-4047-b9af-16797a686ff1.jpg)

### Describe the solution you'd like

Make the configurable option use strftime format codes

**Comment by DevynCJohnson** [comment]
@GretaD , I tried again, but I do not get such a tooltip. I am not using any custom CSS nor any in-house apps (all installed apps/plugins are some of the featured ones).

I think having a customizable option for having a full timestamp would be best as I have seen some issue/feature requests wanting shorter.

**Comment by ChristophWurst** [comment]
https://github.com/nextcloud/mail/issues/8267 could help with this
