### ISSUE TITLE
Regression: Messages height is very small

### ISSUE THREAD

**Issue by jancborchardt** [nextcloud/mail#8221]
### Steps to reproduce

1. Open any mail, in any mailbox
2. Notice it does not get expanded to proper height

### Expected behavior

Height of mails gets expanded like before.

### Actual behavior

This happens with both Chrome and Firefox (the content is scrollable but as you can see, very boxed in):
![image](https://user-images.githubusercontent.com/925062/224952039-e39eaaae-c9e3-4c75-bbcf-b1afed820afb.png)

### Mail app version

Current on cloud.nc.com

### PHP engine version

None

### Web server

None

### Database

None

**Comment by hamza221** [comment]
Can you reproduce it, on the latest main?

**Comment by GretaD** [comment]
duplication of #8194
