### ISSUE TITLE
rich-text emails not displaying in full height

### ISSUE THREAD

**Issue by hamza221** [nextcloud/mail#8224]
### Steps to reproduce

1. Open a rich-text email
 

### Expected behavior

The message should be displayed in full height at

### Actual behavior

The message is displayed with a scrollbar 
![image](https://user-images.githubusercontent.com/40746210/224974068-50c21d0f-25a0-40dc-8285-264e2be73884.png)

### PHP engine version

None

### Web server

None

### Database

None

**Comment by hamza221** [comment]
duplicate of #8221

**Comment by hamza221** [comment]
duplicate of https://github.com/nextcloud/mail/issues/8221

**Comment by ChristophWurst** [comment]
No
