### ISSUE TITLE
Mail 3.0.0: content window is small

### ISSUE THREAD

**Issue by jakobroehrl** [nextcloud/mail#8246]
### Steps to reproduce

![grafik](https://user-images.githubusercontent.com/24530680/226540819-6d7f8d57-21cf-42ea-a2f2-111ba6bdb34e.png)
Tested with latest Firefox 111.0 (64-Bit) and Brave

### Expected behavior

see more of the mail

### Actual behavior

only see a small amount

### Mail app version

3

### PHP engine version

PHP 8.1

### Web server

Nginx

### Database

PostgreSQL

**Comment by ChristophWurst** [comment]
Dup of https://github.com/nextcloud/mail/issues/8194
