### ISSUE TITLE
Show message timestamp in action menu

### ISSUE THREAD

**Issue by ChristophWurst** [nextcloud/mail#8267]
### Is your feature request related to a problem? Please describe.

If I look at my inbox I see a relative time indicator for when a message was sent, but not always in a precise format. sometimes it is the time, sometimes just the day. As a user I want to see at which time a message was sent, regardless if it's recent old older.

Hovering the time doesn't give more info because then the time is replaced with the menu handle

![Bildschirmfoto vom 2023-03-22 17-21-30](https://user-images.githubusercontent.com/1374172/226971861-d1dfd81c-d54a-4410-b5a3-ba0f26d85fa6.png)

### Describe the solution you'd like

Include the timestamp in the actions menu like Talk does

![Bildschirmfoto vom 2023-03-22 17-18-32](https://user-images.githubusercontent.com/1374172/226971965-567978b0-ec15-4369-afd4-bb2803375b98.png)

ref https://github.com/nextcloud/spreed/pull/9003

### Additional context

@jancborchardt @nimishavijay yay or nay?

**Comment by ChristophWurst** [comment]
@jancborchardt see https://github.com/nextcloud/mail/pull/8294.

**Comment by ChristophWurst** [comment]
@nimishavijay @jancborchardt are you okay with this change?

**Comment by nimishavijay** [comment]
Commented on the PR!
