### ISSUE TITLE
Advanced search for favorites does not work

### ISSUE THREAD

**Issue by alexanderdd** [nextcloud/mail#8301]
### Steps to reproduce

1. open advanced search (button next to search field)
2. activate "favorite" in the "marked as" section at the bottom
3. click search

### Expected behavior

all mail that are tagged "favorite" are displayed

### Actual behavior

all mail are shown just as if there was no filter active

Probably related https://github.com/nextcloud/mail/pull/6546

### Mail app version

2.2.5

### Mailserver or service

goneo.de

### PHP engine version

None

### Web server

None

### Database

None

### Additional info

Nextcloud 25.0.4 (just updated from 24.X)

Also, when I click on Favorites in the left sidebar I get error "E-Mail-Postfach konnte nicht geöffnet werden" (could not connect to inbox).

Everything else works as expected. I know the information about favorites is updated to the mail server because I can see it in Thunderbird, accessing the same mail inbox.

**Comment by JordanDIG** [comment]
> all mail are shown just as if there was no filter active

I have the same problem

**Comment by alexanderdd** [comment]
Cannot reproduce anymore on c.nc.com - seems to be fixed.
