### ISSUE TITLE
The provided PKCS #12 certificate must contain a single certificate and private key | PKCS#12 S/MIME

### ISSUE THREAD

**Issue by joshuniverse** [nextcloud/mail#8302]
### Steps to reproduce

1. Obtain a S/MIME cert from actalis(https://extrassl.actalis.it/portal/uapub/freemail?lang=en)
2. Go to nextcloud mail application
3. Click mail settings
4. Click manage S/MIME certificates
5. Upload PKCS#12 Certificate with .pfx ending with the associated password presented on the actalis confirmation screen
6. See error

### Expected behavior

The certificate should be successfully uploaded to allow S/MIME signing for outbound emails.

### Actual behavior

![image](https://user-images.githubusercontent.com/108092727/227813619-6d083ce5-b332-4750-8a15-53526b0cd7fa.png)

### Mail app version

3.0.2

### Mailserver or service

Fastmail

### Operating system

Ubuntu

### PHP engine version

PHP 8.2

### Web server

Apache (supported)

### Database

MySQL

**Comment by joshuniverse** [comment]
This certificate works in other clients such as thunderbird.

**Comment by st3iny** [comment]
Actalis includes the full chain in the certificate store and we should only care about the leaf subject certificate. I'll fix it.

**Comment by joshuniverse** [comment]
Hi, how do I get this update? I am still experiencing the error. Thanks!

**Comment by Lawkss** [comment]
same problem here.

**Comment by ChristophWurst** [comment]
As you can see from the ticket we *just closed* the bug report. The fix will be released soon. Have some patience.

**Comment by joshuniverse** [comment]
Hi, I am still experiencing this error even after updating to the latest beta that was released(3.0.3-beta.1). Thanks!

**Comment by ChristophWurst** [comment]
This is expected: https://github.com/nextcloud/mail/pull/8304#issuecomment-1485031762

Please be patient. We will release this with v3.1.
