### ISSUE TITLE
Type / on the email field the pop up does not open

### ISSUE THREAD

**Issue by JordanDIG** [nextcloud/mail#8303]
### Steps to reproduce

1. Open mail app in nextcloud 26
2. Create a new email
3. Type /

### Expected behavior

The menu is open

### Actual behavior

The menu does not open

### Mail app version

3.0.2

### Mailserver or service

Infomaniak

### Operating system

Debian 11 (docker)

### PHP engine version

PHP 8.1

### Web server

Apache (supported)

### Database

MySQL

### Additional info

#8300

**Comment by ChristophWurst** [comment]
What menu?

**Comment by ChristophWurst** [comment]
Is this about the smart picker? The smart picker doesn't open like that in Mail. Mail uses a real text editor component. The smart picker is found in the ... menu on the bottom right

![](https://user-images.githubusercontent.com/12728974/226374561-8e7f71b4-4acb-410c-b274-9ba6ce2a3aa5.png)

**Comment by JordanDIG** [comment]
> What menu?

When I say menu I mean 
![image](https://user-images.githubusercontent.com/38187648/227886911-5eb4b810-292f-47e3-98e1-3a6765363685.png)

**Comment by JordanDIG** [comment]
> Is this about the smart picker? The smart picker doesn't open like that in Mail. Mail uses a real text editor component. The smart picker is found in the ... menu on the bottom right

I don't have Smart Picker

**Comment by ChristophWurst** [comment]
> When I say menu I mean
> ![image](https://user-images.githubusercontent.com/38187648/227886911-5eb4b810-292f-47e3-98e1-3a6765363685.png)

This only wroks for apps that use https://nextcloud-vue-components.netlify.app/#/Components/NcRichText. This app does not. Use the action in the menu instead.

**Comment by JordanDIG** [comment]
> > When I say menu I mean
> > ![image](https://user-images.githubusercontent.com/38187648/227886911-5eb4b810-292f-47e3-98e1-3a6765363685.png)
> 
> This only wroks for apps that use https://nextcloud-vue-components.netlify.app/#/Components/NcRichText. This app does not. Use the action in the menu instead.

What action from the menu?

**Comment by ChristophWurst** [comment]
link?

**Comment by JordanDIG** [comment]
Oh okay thanks for all
