### ISSUE TITLE
Allow stacking message list and reading pane vertically

### ISSUE THREAD

**Issue by goulvench** [nextcloud/mail#8309]
### Is your feature request related to a problem? Please describe.

On desktop, the default view is composed of 3 columns: mailbox list, message list, and reading pane.
On tablet/mobile, the view switches between message list and reading pane.

On narrow desktop screens (13"), especially when the accounts pane is open, the message list and reading pane are very narrow and hard to read/use.

### Describe the solution you'd like

Moving to a 2-column design, with the reading pane under the message list, would make better use of vertical available space, and match user expectations (most mail clients offer to have the reading pane either to the side or under the message list). 

The message list preview would have much more breathing room, making it easier to triage messages without opening them for instance.

### Describe alternatives you've considered

- Animation showing how to switch between right pane, stacked panes, and no pane on Gmail https://www.googleworkspaceguides.com/wp-content/uploads/2022/02/Animation.gif
- Reading pane toggler for Outlook https://support.content.office.net/en-us/media/7be78ac1-d931-4ee9-865e-3f5d150290a2.png

### Additional context

This solution would be a solution to #3294, and help users keep track of context (when comparing two different conversations for instance).

**Comment by GretaD** [comment]
@nextcloud/designers I would like to start working on this asap, please add it for review on your backlog and please send me the mockups/insights when you have them :)

**Comment by jancborchardt** [comment]
@GretaD @nimishavijay the way Gmail does it seems best here:
- A layout toggle between: "No split", "Side by side" and "Top and bottom" (or different wording if you can think of some :) Default being "Side by side"
- The side by side view has the resizable message list, so it is necessary for top and bottom layout as well

@GretaD do you need an additional mockup besides that and https://www.googleworkspaceguides.com/wp-content/uploads/2022/02/Animation.gif ?

**Comment by GretaD** [comment]
> @GretaD do you need an additional mockup besides that and https://www.googleworkspaceguides.com/wp-content/uploads/2022/02/Animation.gif ?

So having only one toggle that switch between full view and 3 column design(the one we have now).
I am not sure where to add the toggle, so just that would be my question for now.

**Comment by marcoambrosini** [comment]
I think we should not implement this view. Both the messages list and the email content are vertical scroll containers, so it doesn't make much sense to stack them vertically IMO.

**Comment by ChristophWurst** [comment]
It won't be the default. It does make sense to some people, like me.

**Comment by jancborchardt** [comment]
> So having only one toggle that switch between full view and 3 column design(the one we have now).
> I am not sure where to add the toggle, so just that would be my question for now.

The toggle can be in the global setting, that is the most fitting place.

As said it needs to be between not just full view and 3 column, but:
- Side by side (default)
- No split
- Top and bottom

It would be best to do this as a radio button so all options are visible at the same time, like for Gmail.

**Comment by GretaD** [comment]
released
