### ISSUE TITLE
Dragging Thread to sidebar folder should move all messages in the thread

### ISSUE THREAD

**Issue by meichthys** [nextcloud/mail#8310]
### Steps to reproduce

- Open Mail
- Find Thread in inbox that has multiple unread messages
- Drag thread to Archive (or another sidebar folder)

![image](https://user-images.githubusercontent.com/10717998/228349294-a11dc56c-2742-4fb2-8cb1-1dfb19170e0a.png)

### Expected behavior

The entire thread should be archived.

### Actual behavior

Currently the (last/most recent?) message in the thread is removed from the inbox, but all messages in the thread are not archived, so the thread re-appears in the inbox a minute or so later.

### Mail app version

3.0.2

### Mailserver or service

Zoho

### Operating system

Windows 10

### PHP engine version

PHP 8.1

### Web server

Apache (supported)

### Database

PostgreSQL

**Comment by ChristophWurst** [comment]
Addressed by https://github.com/nextcloud/mail/pull/5674
