### ISSUE TITLE
Unable to Synchronize Large Mailbox

### ISSUE THREAD

**Issue by tiongsengis** [nextcloud/mail#8318]
### Steps to reproduce

1. Mail users have mailbox greater than 9985 mail in single folder. Nextcloud Mail enter endless loading state when access folder.
2. Configuration is based on IMAP and SMTP
3. When issue command on console i.e. mail:account:sync -vvv <uid>, it shows "4. Range for findAll min=1 max=9985 found= 5026 messages, 5000 left after filtering. Highest UID to fetch is 5000" "Mailbox INBOX has more messages to fetch: 1:5000"

Is it there is a limit set for read 5000 email only? If yes, is it possible to adjust up or remove this limit?

### Expected behavior

Able to sync and present all amount of email supported by email server

### Actual behavior

When click on folders contain large amount of email, Nextcloud mail will present in infinite looping state with word "Loading".
When click on folders contain small amount fo email, able to load and view all email inside accurately.

### Mail app version

2.25

### Mailserver or service

Lotus Domino

### Operating system

Debian 11

### PHP engine version

PHP 8.1

### Web server

Apache (supported)

### Database

PostgreSQL

### Additional info

Nextcloud 25.0.5

**Comment by ChristophWurst** [comment]
> Is it there is a limit set for read 5000 email only? If yes, is it possible to adjust up or remove this limit?

We are testing the app with mailboxes of up to 6 million messages. There is no limit.

**Comment by tiongsengis** [comment]
> Could you share the redacted but full output of the cli sync?
> 
> Sync and indexing happens in chunks of 5k messages to not saturate the database with too many writes at a time. The app should fetch roughly 5k messages, then another 5k and repeat until it has seen the highest UID reported by the server.

Noted. Below is a list. Unable to produce the full because it went on for hours:

root@sghqrmisvsvr001:/var/www/nextcloud# sudo -u www-data php -f occ mail:account:sync -vvv 508
[debug] account is up to date, skipping mailbox sync
[debug] Skipping mailbox sync for 5164
[debug] Skipping mailbox sync for 5165
[debug] Skipping mailbox sync for 5166
[debug] Skipping mailbox sync for 5179
[debug] Syncing 5167
[debug] Locking mailbox 5167 for new messages sync
[debug] Locking mailbox 5167 for changed messages sync
[debug] Locking mailbox 5167 for vanished messages sync
[debug] Running initial sync for 5167
[debug] Initial sync 508:INBOX - mailbox meta search took 1s. 30/32MB memory used
[debug] Built range for findAll: min=1 max=9985 total=9936 totalRange=9985 estimatedPageSize=5025 lower=1 upper=5026 highestKnownUid=0
[debug] Initial sync 508:INBOX - fetch UIDs took 1s. 35/36MB memory used
[debug] Initial sync 508:INBOX - calculate UIDs to fetch took 0s. 36/36MB memory used
[debug] Range for findAll min=1 max=9985 found 5026 messages, 5000 left after filtering. Highest UID to fetch is 5000
[debug] Mailbox INBOX has more messages to fetch: 1:5000
[debug] Initial sync 508:INBOX - find IMAP messages by UID took 321s. 109/112MB memory used
[debug] Initial sync 508:INBOX - fetch 3 messages from IMAP took 0s. 106/112MB memory used
[debug] Initial sync 508:INBOX - find number of cached UIDs took 0s. 106/112MB memory used
[debug] Initial sync 508:INBOX took 323s
[debug] Unlocking mailbox 5167 from vanished messages sync
[debug] Unlocking mailbox 5167 from changed messages sync
[debug] Unlocking mailbox 5167 from new messages sync
Batch of new messages sync'ed. 106MB of memory in use
[debug] account is up to date, skipping mailbox sync
[debug] Skipping mailbox sync for 5164
[debug] Skipping mailbox sync for 5165
[debug] Skipping mailbox sync for 5166
[debug] Skipping mailbox sync for 5179
[debug] Syncing 5167
[debug] Locking mailbox 5167 for new messages sync
[debug] Locking mailbox 5167 for changed messages sync
[debug] Locking mailbox 5167 for vanished messages sync
[debug] Running initial sync for 5167
[debug] Initial sync 508:INBOX - mailbox meta search took 1s. 107/112MB memory used
[debug] Built range for findAll: min=1 max=9985 total=9936 totalRange=9985 estimatedPageSize=5025 lower=1 upper=5026 highestKnownUid=0
[debug] Initial sync 508:INBOX - fetch UIDs took 0s. 112/112MB memory used
[debug] Initial sync 508:INBOX - calculate UIDs to fetch took 0s. 112/112MB memory used
[debug] Range for findAll min=1 max=9985 found 5026 messages, 5000 left after filtering. Highest UID to fetch is 5000
[debug] Mailbox INBOX has more messages to fetch: 1:5000
[debug] Initial sync 508:INBOX - find IMAP messages by UID took 71s. 109/127MB memory used
[debug] Initial sync 508:INBOX - fetch 3 messages from IMAP took 0s. 106/127MB memory used
[debug] Initial sync 508:INBOX - find number of cached UIDs took 0s. 106/127MB memory used
[debug] Initial sync 508:INBOX took 72s
[debug] Unlocking mailbox 5167 from vanished messages sync
[debug] Unlocking mailbox 5167 from changed messages sync
[debug] Unlocking mailbox 5167 from new messages sync
Batch of new messages sync'ed. 106MB of memory in use
[debug] account is up to date, skipping mailbox sync
[debug] Skipping mailbox sync for 5164
[debug] Skipping mailbox sync for 5165
[debug] Skipping mailbox sync for 5166
[debug] Skipping mailbox sync for 5179
[debug] Syncing 5167
[debug] Locking mailbox 5167 for new messages sync
[debug] Locking mailbox 5167 for changed messages sync
[debug] Locking mailbox 5167 for vanished messages sync
[debug] Running initial sync for 5167
[debug] Initial sync 508:INBOX - mailbox meta search took 1s. 107/127MB memory used
[debug] Built range for findAll: min=1 max=9985 total=9936 totalRange=9985 estimatedPageSize=5025 lower=1 upper=5026 highestKnownUid=0
[debug] Initial sync 508:INBOX - fetch UIDs took 1s. 112/127MB memory used
[debug] Initial sync 508:INBOX - calculate UIDs to fetch took 0s. 113/127MB memory used
[debug] Range for findAll min=1 max=9985 found 5026 messages, 5000 left after filtering. Highest UID to fetch is 5000
[debug] Mailbox INBOX has more messages to fetch: 1:5000
[debug] Initial sync 508:INBOX - find IMAP messages by UID took 75s. 109/135MB memory used
[debug] Initial sync 508:INBOX - fetch 3 messages from IMAP took 0s. 107/135MB memory used
[debug] Initial sync 508:INBOX - find number of cached UIDs took 0s. 107/135MB memory used
[debug] Initial sync 508:INBOX took 77s
[debug] Unlocking mailbox 5167 from vanished messages sync
[debug] Unlocking mailbox 5167 from changed messages sync
[debug] Unlocking mailbox 5167 from new messages sync
Batch of new messages sync'ed. 106MB of memory in use

**Comment by tiongsengis** [comment]
> 

More from Nextcloud log:

{"reqId":"0gQED73zMBy9FpsYThCz","level":3,"time":"2023-03-30T15:41:25+08:00","remoteAddr":"172.16.8.199","user":"chinhuiliang","app":"mail","method":"POST","url":"/index.php/apps/mail/api/mailboxes/5180/sync","message":"Sync failed for 508:Sent: OCA\\Mail\\Model\\IMAPMessage::__construct(): Argument #3 ($messageId) must be of type int, null given, called in /var/www/nextcloud/apps/mail/lib/IMAP/MessageMapper.php on line 273","userAgent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:109.0) Gecko/20100101 Firefox/109.0","version":"25.0.5.1","exception":{"Exception":"OCA\\Mail\\Exception\\ServiceException","Message":"Sync failed for 508:Sent: OCA\\Mail\\Model\\IMAPMessage::__construct(): Argument #3 ($messageId) must be of type int, null given, called in /var/www/nextcloud/apps/mail/lib/IMAP/MessageMapper.php on line 273","Code":0,"Trace":[{"file":"/var/www/nextcloud/apps/mail/lib/Service/Sync/SyncService.php","line":126,"function":"sync","class":"OCA\\Mail\\Service\\Sync\\ImapToDbSynchronizer","type":"->"},{"file":"/var/www/nextcloud/apps/mail/lib/Controller/MailboxesController.php","line":153,"function":"syncMailbox","class":"OCA\\Mail\\Service\\Sync\\SyncService","type":"->"},{"file":"/var/www/nextcloud/lib/private/AppFramework/Http/Dispatcher.php","line":225,"function":"sync","class":"OCA\\Mail\\Controller\\MailboxesController","type":"->"},{"file":"/var/www/nextcloud/lib/private/AppFramework/Http/Dispatcher.php","line":133,"function":"executeController","class":"OC\\AppFramework\\Http\\Dispatcher","type":"->"},{"file":"/var/www/nextcloud/lib/private/AppFramework/App.php","line":172,"function":"dispatch","class":"OC\\AppFramework\\Http\\Dispatcher","type":"->"},{"file":"/var/www/nextcloud/lib/private/Route/Router.php","line":298,"function":"main","class":"OC\\AppFramework\\App","type":"::"},{"file":"/var/www/nextcloud/lib/base.php","line":1047,"function":"match","class":"OC\\Route\\Router","type":"->"},{"file":"/var/www/nextcloud/index.php","line":36,"function":"handleRequest","class":"OC","type":"::"}],"File":"/var/www/nextcloud/apps/mail/lib/Service/Sync/ImapToDbSynchronizer.php","Line":254,"Previous":{"Exception":"TypeError","Message":"OCA\\Mail\\Model\\IMAPMessage::__construct(): Argument #3 ($messageId) must be of type int, null given, called in /var/www/nextcloud/apps/mail/lib/IMAP/MessageMapper.php on line 273","Code":0,"Trace":[{"file":"/var/www/nextcloud/apps/mail/lib/IMAP/MessageMapper.php","line":273,"function":"__construct","class":"OCA\\Mail\\Model\\IMAPMessage","type":"->"},{"function":"OCA\\Mail\\IMAP\\{closure}","class":"OCA\\Mail\\IMAP\\MessageMapper","type":"->","args":["*** sensitive parameters replaced ***"]},{"file":"/var/www/nextcloud/apps/mail/lib/IMAP/MessageMapper.php","line":279,"function":"array_map"},{"file":"/var/www/nextcloud/apps/mail/lib/IMAP/MessageMapper.php","line":214,"function":"findByIds","class":"OCA\\Mail\\IMAP\\MessageMapper","type":"->"},{"file":"/var/www/nextcloud/apps/mail/lib/Service/Sync/ImapToDbSynchronizer.php","line":300,"function":"findAll","class":"OCA\\Mail\\IMAP\\MessageMapper","type":"->"},{"file":"/var/www/nextcloud/apps/mail/lib/Service/Sync/ImapToDbSynchronizer.php","line":230,"function":"runInitialSync","class":"OCA\\Mail\\Service\\Sync\\ImapToDbSynchronizer","type":"->"},{"file":"/var/www/nextcloud/apps/mail/lib/Service/Sync/SyncService.php","line":126,"function":"sync","class":"OCA\\Mail\\Service\\Sync\\ImapToDbSynchronizer","type":"->"},{"file":"/var/www/nextcloud/apps/mail/lib/Controller/MailboxesController.php","line":153,"function":"syncMailbox","class":"OCA\\Mail\\Service\\Sync\\SyncService","type":"->"},{"file":"/var/www/nextcloud/lib/private/AppFramework/Http/Dispatcher.php","line":225,"function":"sync","class":"OCA\\Mail\\Controller\\MailboxesController","type":"->"},{"file":"/var/www/nextcloud/lib/private/AppFramework/Http/Dispatcher.php","line":133,"function":"executeController","class":"OC\\AppFramework\\Http\\Dispatcher","type":"->"},{"file":"/var/www/nextcloud/lib/private/AppFramework/App.php","line":172,"function":"dispatch","class":"OC\\AppFramework\\Http\\Dispatcher","type":"->"},{"file":"/var/www/nextcloud/lib/private/Route/Router.php","line":298,"function":"main","class":"OC\\AppFramework\\App","type":"::"},{"file":"/var/www/nextcloud/lib/base.php","line":1047,"function":"match","class":"OC\\Route\\Router","type":"->"},{"file":"/var/www/nextcloud/index.php","line":36,"function":"handleRequest","class":"OC","type":"::"}],"File":"/var/www/nextcloud/apps/mail/lib/Model/IMAPMessage.php","Line":84},"message":"Sync failed for 508:Sent: OCA\\Mail\\Model\\IMAPMessage::__construct(): Argument #3 ($messageId) must be of type int, null given, called in /var/www/nextcloud/apps/mail/lib/IMAP/MessageMapper.php on line 273","exception":{},"CustomMessage":"Sync failed for 508:Sent: OCA\\Mail\\Model\\IMAPMessage::__construct(): Argument #3 ($messageId) must be of type int, null given, called in /var/www/nextcloud/apps/mail/lib/IMAP/MessageMapper.php on line 273"}}

**Comment by ChristophWurst** [comment]
Thought dump

1) This is the first sync attempt because the *highst known UID* is 0.
2) The mailbox has messages with UIDs 0 to 9985 with 9936 messages. The UIDs are very *dense*. There aren't many gaps.
3) The algo tries to fetch UID 1 to 5026 but caps at UID 5000. This range should capture close to 5000 messages.
4) We do not see *Range for findAll did not find any messages* so the mailserver did return at least one message for the UID fetch operation.

**Comment by tiongsengis** [comment]
> Thought dump
> 
>     1. This is the first sync attempt because the _highst known UID_ is 0.
> 
>     2. The mailbox has messages with UIDs 0 to 9985 with 9936 messages. The UIDs are very _dense_. There aren't many gaps.
> 
>     3. The algo tries to fetch UID 1 to 5026 but caps at UID 5000. This range should capture close to 5000 messages.
> 
>     4. We do not see _Range for findAll did not find any messages_ so the mailserver did return at least one message for the UID fetch operation.

Nextcloud Mail can reflect correctly the total number of mail for each folder on the menu. However the listing of mail is always in "Loading" state. I left it overnight and it is still loading in the morning. This happens only for mailboxes with large content. Nextcloud server has 20 vCPU and 120GB RAM allocated.

**Comment by ChristophWurst** [comment]
> Nextcloud Mail can reflect correctly the total number of mail for each folder on the menu.

This info comes from IMAP. It is independent of the database index. In this case it's misleading.

I think we need to dive deeper on the error you found in the log. There is at least one message without an ID and that causes a type error.

**Comment by tiongsengis** [comment]
> > Nextcloud Mail can reflect correctly the total number of mail for each folder on the menu.
> 
> This info comes from IMAP. It is independent of the database index. In this case it's misleading.
> 
> I think we need to dive deeper on the error you found in the log. There is at least one message without an ID and that causes a type error.

Appreciate advice what need from my end to dive deeper, in order to determine the error is dervived from Domino IMAP server or Nextcloud Mail or Postgresql database?

**Comment by tiongsengis** [comment]
The issue has resolved now. Solution is to increase the timeout period of php-fpm and increase concurrent limit of Postgresql.
