### ISSUE TITLE
Message previews show in Html format

### ISSUE THREAD

**Issue by hamza221** [nextcloud/mail#8323]
### Steps to reproduce

Not much investigation done yet, doesn't look really deterministic for now but might be caused by #8235

### Expected behavior

message previews should be in text-only format, the same as when you open the message 

### Actual behavior

sometimes message preview contains HTML syntax

![image](https://user-images.githubusercontent.com/40746210/229388312-fd82f494-acdd-49f3-967c-fb60d617ae0e.png)

### Mail app version

3.1.0-alpha.1

### PHP engine version

None

### Web server

None

### Database

None

**Comment by panoskpv** [comment]
Same here. This is the case several realeses back. Do you have any idea how to fix?
