### ISSUE TITLE
Sieve More E-Mail Adresses

### ISSUE THREAD

**Issue by AlexanderZuehr** [nextcloud/mail#8339]
Hello,
is it possible to add a textfield in the automatic replies section, where a user could write down e-mail adresses/aliases which the sieve rule should use? As of know the sieve rule is automatically generated for the mail adress used in the mail account, but our users do have aliases which the sieve rule should serve too.

I know it is possible to change the generated sieve rule, but this would be problematic for our users.

**Comment by ChristophWurst** [comment]
From https://github.com/nextcloud/mail/issues/new/choose

> Ask a question or seek for help 

Please use https://help.nextcloud.com/c/apps/mail/35
