### ISSUE TITLE
Send Later feature not showing in v.25?

### ISSUE THREAD

**Issue by BiglifeMatt** [nextcloud/mail#8374]
### Steps to reproduce

Unless I'm missing something, it appears that the Send Later option is gone when using the version 25 Nextcloud.  Not sure if that is the case or I'm not looking in the right spot.  If that is the case, I am not sure where the code needs to be corrected (NC/Groupware or Mail).

If I'm just missing it, please advise.  Thank you.

### Expected behavior

To see the Send Later option while compsing email.

### Actual behavior

I no longer see the option but still see it on v.24 of Nextcloud.

### Mail app version

2.2.5

### Mailserver or service

Dovecot

### Operating system

Ubuntu 20.04

### PHP engine version

PHP 8.1

### Web server

Apache (supported)

### Database

MariaDB

**Comment by ChristophWurst** [comment]
What type of background job do you use https://docs.nextcloud.com/server/stable/admin_manual/configuration_server/background_jobs_configuration.html?

**Comment by BiglifeMatt** [comment]
Ah, yes.  I was running v.25 on my test server and it was still set to AJAX.  Thank you for thinking of that.  Switched to Cron and it is back.  That being said, this is only able to schedule a one time event.  Can you verify this for me that it doesn't have the ability to schedule a recurring email (For example, the first of each month)?
