### ISSUE TITLE
 Failed to open stream: No such file or directory at [...]/ClassLoader.php#578

### ISSUE THREAD

**Issue by Happyfeet01** [nextcloud/mail#8377]
### Steps to reproduce

1. Install the Mail Plugin
2. add an Mail Acccount at the Email Settings
3. using the Mail Plugin
4. look at the Nextcloud.log 

### Expected behavior

the error should disappear

### Actual behavior

many errors in the Logfile from Nextcloud. Does not interfere in daily use, but spams the logfile too much.

### Mail app version

3.1.0

### Mailserver or service

Mailcow Dockerized

### Operating system

Debian 11

### PHP engine version

PHP 8.2

### Web server

Nginx

### Database

MySQL

### Additional info

```
[PHP] Fehler: include(/var/www/nextcloud/apps/mail/vendor/composer/../../lib/Validation/RemoteHostValidator.php): Failed to open stream: No such file or directory at /var/www/nextcloud/lib/composer/composer/ClassLoader.php#578

GET /apps/mail/api/avatars/image/noreply-cloud%40domain.tld
from 2.247.245.74 by lars at 2023-04-15T06:29:24+00:00

at the ClassLoader.php at Linne 578 i have this 

        self::$includeFile = static function($file) {
            include $file;
        }
```

**Comment by ChristophWurst** [comment]
Sounds related to https://github.com/nextcloud/mail/pull/8312

**Comment by ChristophWurst** [comment]
Scan your /var/www/nextcloud/apps/mail for `OCA\Mail\Validation\RemoteHostValidator`. The class no longer exists but seems referenced somewhere on your installation.

**Comment by ChristophWurst** [comment]
No response -> close
