### ISSUE TITLE
[Bug]: Email sending not working 

### ISSUE THREAD

**Issue by anzestrela** [nextcloud/mail#8407]
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [X] This issue is **not** already reported on Github _(I've searched it)_.
- [X] Nextcloud Server **is** up to date. See [Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) for supported versions.
- [X] Nextcloud Server **is** running on 64bit capable CPU, PHP and OS.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Bug description

when i try to send an email from nextcloud i get: 

`TypeError: Cannot assign null to property OCA\Mail\Controller\OutboxController::$userId of type string`
```
    <<closure>>

    OCA\Mail\Controller\OutboxController->__construct()

    /var/www/nextcloud/lib/private/AppFramework/Utility/SimpleContainer.php - line 116:

    ReflectionClass->newInstanceArgs()

    /var/www/nextcloud/lib/private/AppFramework/Utility/SimpleContainer.php - line 124:

    OC\AppFramework\Utility\SimpleContainer->buildClass()

    /var/www/nextcloud/lib/private/AppFramework/Utility/SimpleContainer.php - line 142:

    OC\AppFramework\Utility\SimpleContainer->resolve()

    /var/www/nextcloud/lib/private/AppFramework/DependencyInjection/DIContainer.php - line 493:

    OC\AppFramework\Utility\SimpleContainer->query()

    /var/www/nextcloud/lib/private/AppFramework/DependencyInjection/DIContainer.php - line 465:

    OC\AppFramework\DependencyInjection\DIContainer->queryNoFallback()

    /var/www/nextcloud/lib/private/AppFramework/App.php - line 162:

    OC\AppFramework\DependencyInjection\DIContainer->query()

    /var/www/nextcloud/lib/private/Route/Router.php - line 315:

    OC\AppFramework\App::main()

    /var/www/nextcloud/lib/base.php - line 1056:

    OC\Route\Router->match()

    /var/www/nextcloud/index.php - line 36:

    OC::handleRequest()
```
but i can recieve emails.

And also i can send emails from another account.

### Steps to reproduce

1. add email account (seperate IMAP and SMTP servers)
2. try to send an email

### Expected behavior

Email should be sent

### Installation method

Official All-in-One appliance

### Nextcloud Server version

26

### Operating system

Debian/Ubuntu

### PHP engine version

PHP 8.1

### Web server

Apache (supported)

### Database engine version

MariaDB

### Is this bug present after an update or on a fresh install?

Updated from a minor version (ex. 22.2.3 to 22.2.4)

### Are you using the Nextcloud Server Encryption module?

Encryption is Disabled

### What user-backends are you using?

- [X] Default user-backend _(database)_
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

### List of activated Apps

```shell
- contactsinteraction: 1.7.0
  - dashboard: 7.6.0
  - dav: 1.25.0
  - federatedfilesharing: 1.16.0
  - federation: 1.16.0
  - files: 1.21.1
  - files_pdfviewer: 2.7.0
  - files_rightclick: 1.5.0
  - files_sharing: 1.18.0
  - files_trashbin: 1.16.0
  - files_versions: 1.19.1
  - fileslibreofficeedit: 1.1.0
  - firstrunwizard: 2.15.0
  - holiday_calendars: 0.3.0
  - integration_openai: 1.0.4
  - logreader: 2.11.0
  - lookup_server_connector: 1.14.0
  - mail: 3.1.1
  - nextcloud_announcements: 1.15.0
  - notes: 4.7.2
  - notifications: 2.14.0
  - oauth2: 1.14.0
  - onlyoffice: 7.8.0
  - password_policy: 1.16.0
  - photos: 2.2.0
  - privacy: 1.10.0
  - provisioning_api: 1.16.0
  - recommendations: 1.5.0
  - related_resources: 1.1.0-alpha1
  - serverinfo: 1.16.0
  - settings: 1.8.0
  - sharebymail: 1.16.0
  - spreed: 16.0.3
  - support: 1.9.0
  - survey_client: 1.14.0
  - systemtags: 1.16.0
  - text: 3.7.2
  - theming: 2.1.1
  - twofactor_backupcodes: 1.15.0
  - updatenotification: 1.16.0
  - user_status: 1.6.0
  - viewer: 1.10.0
  - weather_status: 1.6.0
  - workflowengine: 2.8.0
```

**Comment by ChristophWurst** [comment]
Dear @anzestrela,

Thank you very much for your bug report.

> TypeError: Cannot assign null to property OCA\Mail\Controller\OutboxController::$userId of type string

This "should not happen". It would only happen when an unauthenticated request is sent to the Nextcloud server for this request.

Do you remember if there were any other authentication-related problems last year? Does this still happen?

**Comment by nextcloud-command** [comment]
Hi there! It looks like this issue hasn’t seen much activity for a while and might need a bit more information to move forward. If we don’t hear back soon, we may close it to keep things organized. Thanks again for your contributions – we really appreciate it!
