### ISSUE TITLE
nextcloud mail app shows only plain text emails, however html based emails not

### ISSUE THREAD

**Issue by iberenyi** [nextcloud/mail#8431]
### Steps to reproduce

1. click on an html based mail and the email body is just keep loading, but it never finishes. It works fine for plain text emails even if there are email threads and it include a plain text one that shows without issues meanwhile the others don't

### Expected behavior

HTML emails show same as plain text

### Actual behavior

see above

### nextcloud version

26.0.1

### Mail app version

3.1.1

### Mailserver or service

gmail

### Operating system

Debian GNU/Linux 12 (bookworm)

### PHP engine version

PHP 8.2

### Web server

Apache (supported)

### Database

MariaDB

### Additional info

a strange entry in the log:
[PHP] Debug: Return type of ChristophWurst\KItinerary\Itinerary::jsonSerialize() should either be compatible with JsonSerializable::jsonSerialize(): mixed, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice at /var/www/nextcloud/apps/mail/vendor/christophwurst/kitinerary/src/Itinerary.php#52

GET /index.php/apps/mail/api/messages/7212/itineraries
from 93.218.58.205 by tberenyi at 2023-04-29T14:19:47+00:00

[PHP] Debug: Return type of ChristophWurst\KItinerary\Itinerary::count() should either be compatible with Countable::count(): int, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice at /var/www/nextcloud/apps/mail/vendor/christophwurst/kitinerary/src/Itinerary.php#48

GET /index.php/apps/mail/api/messages/7212/itineraries
from 93.218.58.205 by tberenyi at 2023-04-29T14:19:47+00:00

**Comment by iberenyi** [comment]
Finally I found out the root cause. I use firefox with some addons. one of them is uBlock origin and it blocked something which prevented to display the html messages. I added my nextcloud domain to the exception and it solved the problem. Sorry for the false alarm!

**Comment by logotu** [comment]
In my case cybersecurity hardening of the webserver (CSP X-Frame-Options) caused the issue.
