### ISSUE TITLE
please make css-element "reply-composer" more visually preset

### ISSUE THREAD

**Issue by trueshanti** [nextcloud/mail#846]
### Steps to reproduce
1.
trying to answer an email

### Expected behaviour

good visibility of this important element

### Actual behaviour

- reply-composer is hard to see apart the rest of the theme

- white element on white background without punctuating-css

### Mail app

 0.7.10 @ NC 13.0.1

**Comment by ChristophWurst** [comment]
@jancborchardt

**Comment by jancborchardt** [comment]
> white element on white background without punctuating-css

@trueshanti can you show a screenshot? I assume you themed your Nextcloud to use white as a primary color?

**Comment by trueshanti** [comment]
@jancborchardt you are right .. "theming" app (1.4.1) is active , and while it is, the javascript on the "reply"button is not scrolling to bottom of content to reveal the Reply-Form ..

working normal with default-theme

**Comment by jancborchardt** [comment]
Strange, another instance where the theming app interferes? cc @juliushaertl

**Comment by juliushaertl** [comment]
@trueshanti @jancborchardt A screenshot what is wrong there would be helpful. I cannot see any difference in the reply form with or without theming.

**Comment by vslonska** [comment]
Hello,

So same problem as described in #212 .

And I add that there is a `<div class="submit-message-wrapper-inside"></div>` with `z-index:102;` that put this div above the input fliel, so part of the reply button is not clickable.
![reply_nextcloud](https://user-images.githubusercontent.com/24274243/40606469-bd222580-6265-11e8-9574-3be85ace800b.png)

I had to put manually (with css plugin) `z-index:103;` on `.submit-message.send` to solve that.

Thanks,

**Comment by jancborchardt** [comment]
@vslonska since you have a proposed fix even with the code, could you open a pull request to this repository to fix it? :) That would be awesome :heart:

**Comment by trueshanti** [comment]
@juliushaertl @jancborchardt .. hello .. the issue i am trying to address - i give a possible before/after screenshot:

before:
![before](https://user-images.githubusercontent.com/567801/40885452-88828a2a-6726-11e8-9279-3b877e92c72e.png)

after:
![after](https://user-images.githubusercontent.com/567801/40885453-88d92178-6726-11e8-9933-9b65bba5c567.png)

my point is, that the section to write/reply to emails is IMO not prominent enough for the human eye to recognise easy .. IMO that section should be allowed to be "punctuated optically" somehow

**Comment by jancborchardt** [comment]
@trueshanti right, good point. For a more integrated look, maybe using the `class="section"` would help, as it creates a horizontal line. Also, a `<h2>Reply</h2>` above the fields can make it stand out more. What do you think?

**Comment by trueshanti** [comment]
![grafik](https://user-images.githubusercontent.com/567801/40966332-85c19516-68b0-11e8-854a-1e4d38110435.png)

this may look more like rainloop , but optically intuitive i'd say .. maybe a more sexy approach is needed ;-)

**Comment by jancborchardt** [comment]
@trueshanti your screenshot above looked better – can you try out what I commented with the h2 and the section element? :)

**Comment by trueshanti** [comment]
@jancborchardt  .. indeed i did .. but that didnt apply a border in my case , though gave the div an exaggerated padding .. so i skipped it :-o

**Comment by trueshanti** [comment]
@jancborchardt but I appreciate your hint .. 

```
#reply-composer::before {
    content: "@";
    padding-left: 0.3em;
    color: darkgrey;
    font-weight: bold;
}
#reply-composer {
    border-top: dotted 0.5em darkgrey;
    content: "Reply";
}
```

i implemented it with **Custom CSS**

thanks
-c-
