### ISSUE TITLE
Misplaced actions menues

### ISSUE THREAD

**Issue by gaitjan** [nextcloud/mail#8474]
### Steps to reproduce

1. Go to Mail and login
2. Ad an account and see that there's no configure option
3. Ad another account and see that there is a configure option
4.

### Expected behavior

Configure your first email account.

### Actual behavior

You are unable to configure your first email account.

### Mail app version

3.1.1

### Mailserver or service

IMAP/SMTP

### Operating system

Linux (OpenSuSe Leap 15.4

### PHP engine version

PHP 8.0

### Web server

Apache (supported)

### Database

MySQL

### Additional info

Nextcloud 26.0.1

**Comment by ChristophWurst** [comment]
screenshot?

**Comment by gaitjan** [comment]
reproduce?

**Comment by ChristophWurst** [comment]
I can't

**Comment by ChristophWurst** [comment]
There is also no "configure" in the menu https://github.com/nextcloud/mail/blob/main/src/components/NavigationAccount.vue

**Comment by gaitjan** [comment]
In Dutch, it is called "Accountinstellingen" which I think translates to "account settings"

**Comment by ChristophWurst** [comment]
The code doesn't have an option to hide that menu entry

**Comment by gaitjan** [comment]
I only report what I see / don't see.

**Comment by ChristophWurst** [comment]
I appreciate your report and trust that you are not making this up. Unless I'm able to reproduce this myself or get a screenshot that shows what you are seeing I won't be able to help. Hope this makes sense.

**Comment by gaitjan** [comment]
![context_menu_account_1](https://github.com/nextcloud/mail/assets/12206962/7fdee057-d649-4304-9c7b-98058122dc9e)
![context_menu_account_2](https://github.com/nextcloud/mail/assets/12206962/e06bbcce-1c9a-427b-adbe-0e7fea622869)

**Comment by gaitjan** [comment]
Pardon me: asking for a screenshot without saying you can't reproduce it seems strange to mee.

**Comment by gaitjan** [comment]
Now I see that maybe the top part of the menu gets hidden.
How can I unhide that?
(yes yes, a screenshot is nice)

**Comment by gaitjan** [comment]
No, that's not the case.

When I remove the first instance of the account, the second (and then only) account displays the complete menu correctly, but slightly to the right.

Without getting hid?

**Comment by ChristophWurst** [comment]
I see. It's the menu placement that is bugged.

**Comment by gaitjan** [comment]
![context_menu_account_3](https://github.com/nextcloud/mail/assets/12206962/51ba6ba6-e94a-4880-a003-6876ee99f63d)

**Comment by GretaD** [comment]
> No, that's not the case.
> 
> When I remove the first instance of the account, the second (and then only) account displays the complete menu correctly, but slightly to the right.
> 
> Without getting hid?

Hello,

this my be a shot in the dark, but i tried to reproduce your error and i could see the menu shown wrong, when i tried to open it as soon as the second account was added. Then i did a hard refresh and the menu was placed right and i cannot reproduce the error anymore. Can you please hard refresh when you add the second account and see if that fixes it for you?

**Comment by ChristophWurst** [comment]
possibly related: https://github.com/nextcloud/nextcloud-vue/issues/1384

**Comment by ChristophWurst** [comment]
This is still happening and makes some account actions inaccessible. @GretaD could you dive into this for the Hub 6 stabilization?

![image](https://github.com/nextcloud/mail/assets/1374172/d49c8989-6d50-44d0-88bb-191f4f4cc7f9)

**Comment by ChristophWurst** [comment]
![image](https://github.com/nextcloud/mail/assets/1374172/4371408a-20b6-4f31-b6e2-17ebd1df27b9)

Same bug happens for envelope action, e.g. when creating an event from an email.

**Comment by pongraczi** [comment]
I hit the same issue, but after some maniac clicking everywhere and mail app reload on new browser tab, it started working as expected.

Right after adding new account:  
![kep-160](https://github.com/nextcloud/mail/assets/5891983/fd74cf80-9167-4825-9dc8-b367e84ffb82)

After some time and reload app:  
![kep-161](https://github.com/nextcloud/mail/assets/5891983/348dd990-37d6-40f7-8782-2828e1a92188)

Maybe it is temporary or something.

**Comment by ChristophWurst** [comment]
This should be fine with the upcoming release.
