### ISSUE TITLE
Privacy - Auto-Complete with emails from the instance 

### ISSUE THREAD

**Issue by pierreozoux** [nextcloud/mail#848]
### Steps to reproduce
1. run a shared instance with many users
2. create an email
3. start to fill the `to` field

### Expected behaviour

You should see auto-completion from your address book or your group.

### Actual behaviour
You see auto-completion from the full instance, which is a privacy leak.

### Mail app

**Mail app version:** 0.7.10

This issue is a regression from #171.

[Screenshot from the sharing settings](https://screenshots.firefox.com/azWmo5rT4FyJuoYG/cloud.indie.host)

**Comment by ChristophWurst** [comment]
Looks like the `ContactsManager` provides these entries from the system address book: https://github.com/nextcloud/server/blob/7b4e51dbc71c1112663b65c08b14eed44dcb50a3/lib/private/ContactsManager.php#L41-L54

It's the DAV app that registers both the user's address book and the system address book: https://github.com/nextcloud/server/blob/7b4e51dbc71c1112663b65c08b14eed44dcb50a3/apps/dav/lib/CardDAV/ContactsManager.php#L55-L59

@nextcloud/sharing @schiessle @rullzer should we remove the registration of the system address book if "Allow username autocompletion …" in the admin sharing settings is disabled?

**Comment by rullzer** [comment]
Yes seems like it

**Comment by journey123** [comment]
Can you actually link into anyone's phone?

**Comment by ChristophWurst** [comment]
> Yes seems like it

It kinda feels wrong to hack this into the DAV app. This doesn't seem like the appropriate place. Also, I have the feeling change will cause other problems as well as these address books are not only used for Mail but also for example in the contacts menu … :thinking:

**Comment by ChristophWurst** [comment]
> It kinda feels wrong to hack this into the DAV app. This doesn't seem like the appropriate place. Also, I have the feeling change will cause other problems as well as these address books are not only used for Mail but also for example in the contacts menu … thinking

Fixed (aka hacked) it in the mail app instead. See https://github.com/nextcloud/mail/pull/856 :wink:

**Comment by rullzer** [comment]
Still. mind opening a issue in the server repo? because if the address book is registered in theory anybody could access it all via dav (that is on the server).

**Comment by ChristophWurst** [comment]
@pierreozoux that shoudn't have happened but it's totally possible that there is another bug.

**Comment by ChristophWurst** [comment]
> I checked, I'm using 0.8 and Nc 13.0.2 should we reopen, or create a new issue?

Please open a new ticket. Thanks a lot for your feedback!
