### ISSUE TITLE
Does this work as intended?  Not enough clear documentation or examples to know. No inbox notification, or update to dashboard unless email page open.  And unable to stop tagging emails important?

### ISSUE THREAD

**Issue by daddydaycare** [nextcloud/mail#8485]
### Steps to reproduce

1.turn on computer
2.log into nextcloud dashboard
3.no unread emails and no notificatons

### Expected behavior

Is it expected that the cron job updates the dashboard and puts a red dot in the bell when a new mail arrives?
Also expect it not to flag every email important, and not be able to stop it with the check box in settings. Has zero effect.

### Actual behavior

Email has no inbox notification or refresh unless page open.  I have to imagine this is supposed to happen otherwise whats the point of this? 
And whats the go with not able to stop the tagging of all emails important? this also is a deterent to using as it mucks up all other clients that actually work well.

Nothing happens with the email app unless the screen is open. And even then there is no red dot in bell when an email arrives.
I do not know if this is just my expectation? or if something is wrong.  Just updated aio from 25 to 27. same thing.

Everything works besides that. no errors in any container logs or in nextcloud loggin.

The below info is irrelevent as this has gone through progression of upgrades...

### Mail app version

	3.2.0-beta.2

### Mailserver or service

privateemail

### Operating system

docker aio in proxmox hosted omv

### PHP engine version

PHP 8.0

### Web server

Apache (supported)

### Database

Other

### Additional info

Its the all in one.

**Comment by ChristophWurst** [comment]
> not be able to stop it with the check box in settings. Has zero effect.

https://github.com/nextcloud/mail/issues/8436



> Is it expected that the cron job updates the dashboard and puts a red dot in the bell when a new mail arrives?

The dashboard is not reactive/live. It loads the email data once at page load. There are no further updates. See https://github.com/nextcloud/mail/issues/4399.
