### ISSUE TITLE
Suggested replies for email

### ISSUE THREAD

**Issue by nimishavijay** [nextcloud/mail#8505]
### Is your feature request related to a problem? Please describe.

It could be useful to have some suggested replies for a message to quickly send an email, especially simple replies like "Thank you", "That works for me", or something similar

### Describe the solution you'd like

There could be a few suggested replies at the bottom of the last message in a thread, with some relevant suggestions based on the contents of the message. Clicking on it could send the message immediately (with the option to undo of course). This would save 2 clicks and some typing.

Rough designs and some variations in placement and button style, cc @jancborchardt and @szaimen for feedback
Note that in the mockups the action is reply, we could also do reply all, what do you think?

<img src="https://github.com/nextcloud/mail/assets/52440189/8f2ba42c-3572-44ac-a0de-4775f3921009"  width=50% height=50%>
<img src="https://github.com/nextcloud/mail/assets/52440189/045bf99f-c6f1-4cf3-99d4-9af3809ee37e" width=50% height=50%>
<img src="https://github.com/nextcloud/mail/assets/52440189/f8c3046b-b5ef-4605-92aa-25b5b20a6120"  width=50% height=50%>

## Implementation

* Synchronous mode, like the thread summary. Deployment needs fast LLM. Slow LLM not supported for the first version.
* Use free prompt API if possible, or ask Nextcloud integration team for help with a new backend/API.

## Work packages
* MVP
* Admin docs
* User docs

**Comment by ChristophWurst** [comment]
This requires some sort of machine learning to process and "understand" the text. I guess classification into types of emails could be one approach, where you then suggest an "Ok thank you" for informational messages and "Yes"/"No" for yes-no questions. The more complex approach is to provide replies with actual context information, e.g. confirming/declining a date suggestion.

The ML has to also be able to work with all supported languages, not just english.

The training of this data will be hard to do unsupervised because there is no high quality reference data to train. So I'm afraid we have to ship a pretrained model.

**Comment by ChristophWurst** [comment]
*Smart replies* on Android are a similar feature: https://www.techmesto.com/enable-disable-smart-replies-android-10/

**Comment by ChristophWurst** [comment]
I'm not familiar with it but if there is a way to use the smart reply model together with https://www.tensorflow.org/js it could be possible to process the messages in the browser and therefore have more options than PHP+rubix/ml.

**Comment by ChristophWurst** [comment]
> ## Work packages
> 
>     * MVP
> 
>     * Admin docs
> 
>     * User docs

Just added. @hamza221 I think this feature should be documented

**Comment by hamza221** [comment]
@ChristophWurst  what should be documented on the user side ?

**Comment by ChristophWurst** [comment]
> @ChristophWurst what should be documented on the user side ?
> I couldn't think of anything 😅

Imagine explaining the feature to a friend. For example, tell that it provides a suggested reply based on the thread the user sees and that clicking the button prefills the composer of the reply. Mention that the feature might not be available because admins have to enable it.
