### ISSUE TITLE
.ics import into calendar not working

### ISSUE THREAD

**Issue by nanaksingh13** [nextcloud/mail#8512]
### Steps to reproduce

1. send a invitation mail to yourself including a calendar event
2. i recommend google calendar 
3. if you click on .ics file (attachment) three dots and import into calendar nothing happens.

### Expected behavior

it should create a event in calendar

### Actual behavior

nothing happens

### Mail app version

2.2.6

### Mailserver or service

any

### Operating system

ubuntu 22.04

### PHP engine version

None

### Web server

None

### Database

None

**Comment by ChristophWurst** [comment]
> nothing happens

Open the browser console, import again and watch for any logged errors

**Comment by MuuNU** [comment]
I have same issue.
`XHRPROPFIND
https://cloud.napcat.xyz/remote.php/dav/calendars/admin/
[HTTP/1.1 207 Multi-Status 810ms]

XHRGET
https://cloud.napcat.xyz/ocs/v2.php/apps/notifications/api/v2/notifications
[HTTP/1.1 304 Not Modified 638ms]

No new notification data received NotificationsApp.vue:382
Polling interval updated to 30000 NotificationsApp.vue:414
XHRPOST
https://cloud.napcat.xyz/index.php/apps/mail/api/mailboxes/20/sync
[HTTP/1.1 200 OK 2074ms]

You need to fill either the text or the ariaLabel props in the button component. 
Object { text: undefined, ariaLabel: null }
 
Object { _uid: 927, _isVue: true, __v_skip: true, _scope: {…}, "$options": {…}, _renderProxy: {…}, _self: {…}, "$parent": {…}, "$root": {…}, "$children": (1) […], … }
index.module.js:2:843985
You need to fill either the text or the ariaLabel props in the button component. 
Object { text: undefined, ariaLabel: null }
 
Object { _uid: 929, _isVue: true, __v_skip: true, _scope: {…}, "$options": {…}, _renderProxy: {…}, _self: {…}, "$parent": {…}, "$root": {…}, "$children": (1) […], … }
index.module.js:2:843985
You need to fill either the text or the ariaLabel props in the button component. 
Object { text: undefined, ariaLabel: null }
 
Object { _uid: 931, _isVue: true, __v_skip: true, _scope: {…}, "$options": {…}, _renderProxy: {…}, _self: {…}, "$parent": {…}, "$root": {…}, "$children": (1) […], … }
index.module.js:2:843985
You need to fill either the text or the ariaLabel props in the button component. 
Object { text: undefined, ariaLabel: null }
 
Object { _uid: 933, _isVue: true, __v_skip: true, _scope: {…}, "$options": {…}, _renderProxy: {…}, _self: {…}, "$parent": {…}, "$root": {…}, "$children": (1) […], … }
index.module.js:2:843985
XHRGET
https://cloud.napcat.xyz/ocs/v2.php/apps/notifications/api/v2/notifications
[HTTP/1.1 304 Not Modified 908ms]

No new notification data received NotificationsApp.vue:382
Polling interval updated to 30000 NotificationsApp.vue:414
XHRPOST
https://cloud.napcat.xyz/index.php/apps/mail/api/mailboxes/20/sync
[HTTP/1.1 200 OK 2095ms]

You need to fill either the text or the ariaLabel props in the button component. 
Object { text: undefined, ariaLabel: null }
 
Object { _uid: 927, _isVue: true, __v_skip: true, _scope: {…}, "$options": {…}, _renderProxy: {…}, _self: {…}, "$parent": {…}, "$root": {…}, "$children": (1) […], … }
index.module.js:2:843985
You need to fill either the text or the ariaLabel props in the button component. 
Object { text: undefined, ariaLabel: null }
 
Object { _uid: 929, _isVue: true, __v_skip: true, _scope: {…}, "$options": {…}, _renderProxy: {…}, _self: {…}, "$parent": {…}, "$root": {…}, "$children": (1) […], … }
index.module.js:2:843985
You need to fill either the text or the ariaLabel props in the button component. 
Object { text: undefined, ariaLabel: null }
 
Object { _uid: 931, _isVue: true, __v_skip: true, _scope: {…}, "$options": {…}, _renderProxy: {…}, _self: {…}, "$parent": {…}, "$root": {…}, "$children": (1) […], … }
index.module.js:2:843985
You need to fill either the text or the ariaLabel props in the button component. 
Object { text: undefined, ariaLabel: null }
 
Object { _uid: 933, _isVue: true, __v_skip: true, _scope: {…}, "$options": {…}, _renderProxy: {…}, _self: {…}, "$parent": {…}, "$root": {…}, "$children": (1) […], … }
index.module.js:2:843985
`

**Comment by GretaD** [comment]
double of https://github.com/nextcloud/mail/issues/7444
