### ISSUE TITLE
Warn the user about quota depletion

### ISSUE THREAD

**Issue by ChristophWurst** [nextcloud/mail#8513]
## Is your feature request related to a problem? Please describe.

As a user I do not keep close track of my IMAP quota so I'm possibly using up all my assigned storage space without notice.

## Describe the solution you'd like

The app should notify when I cross 90% quota. The notification should come through a Nextcloud notification so it shows on all devices.

## Implementation

Periodically query the quota. Persist the current value. If the new value crosses 90% but the previous one was below (rising edge) send out a notification. This should ensure that the notification only happens once.

## Describe alternatives you've considered

Show exceeded quota in the account actions menu. This can be done additionally.

## Additional context

We will continue to rely on quota reported by the IMAP server. If there is no quota report we don't notify.

**Comment by miaulalala** [comment]
Any text suggestions? Currently I have `'You are currently using {percentage}% of your mailbox storage. Please make some space by deleting unneeded emails.'`
