### ISSUE TITLE
Unable to re-open account settings

### ISSUE THREAD

**Issue by ZetaTom** [nextcloud/mail#8523]
### Steps to reproduce

1. set up email account
2. open *Account Settings* of said account using three dots menu
3. dismiss dialogue by clicking on background
4. try to open *Account Settings* once again

### Expected behavior

Account settings dialogue should re-appear.

### Actual behavior

Account settings dialogue does not appear.

### Mail app version

3.2.0-rc.3

### PHP engine version

None

### Web server

None

### Database

None

**Comment by ChristophWurst** [comment]
can confirm with 3.2.0-rc.3
