### ISSUE TITLE
Restrict Mail App outside of network

### ISSUE THREAD

**Issue by nanaksingh13** [nextcloud/mail#8554]
### Is your feature request related to a problem? Please describe.

I'm facing issue securing my data. I used file access control to block access to files outside of office network, that does not work with Mail App, So users could save a draft email with attachments and download them outside of network. 

### Describe the solution you'd like

I would Like to block Access to Mail App outside of selected network.

### Describe alternatives you've considered

I couldn't thats why I have reached out for your help.

**Comment by nanaksingh13** [comment]
restrict app to user/group could have enhancement to block app access by ip accessed.

**Comment by ChristophWurst** [comment]
if you need this feature then you probably need it for every app. you could use something like a web application firewall and block the unwanted URLs.

**Comment by nanaksingh13** [comment]
@ChristophWurst That is a great idea, any suggestions how to implement it.

**Comment by ChristophWurst** [comment]
Add a web application firewall and configure so it blocks the requests you don't want to allow

**Comment by nanaksingh13** [comment]
which web application firewall you recommend

**Comment by ChristophWurst** [comment]
I can't give recommendations

**Comment by nanaksingh13** [comment]
how would you do. (opensource only)
