### ISSUE TITLE
Mail shows old (deleted) e-mails

### ISSUE THREAD

**Issue by MarZi235** [nextcloud/mail#8555]
### Steps to reproduce

1. Delete E-Mails through IMAP
2. Login to Mail App (a few days later)
3. Old E-Mails will still show in the list of available E-Mails, although they are already gone. If you click on them, you'll see an error that the item could not be found.
4. The left panel correctly shows the right amount of E-Mails in that folder. It seems there is a session caching issue somewhere. Can you help assess this issue, please?

### Expected behavior

The Mail app should only show the correct available E-Mails and flush existing caches if there is a mismatch.

### Actual behavior

The left panel correctly shows the right amount of E-Mails in that folder. It seems there is a session caching issue somewhere. Can you help assess this issue, please? See Screenshot
![nextcloud_Mail_Caching_Issue](https://github.com/nextcloud/mail/assets/130544282/2f1087c3-6079-4688-b17d-08201c53129d)

### Mail app version

3.2.0

### Operating system

Ubuntu 22 LTS

### PHP engine version

PHP 8.2

### Web server

Apache (supported)

### Database

MySQL

**Comment by ChristophWurst** [comment]
Dup of https://github.com/nextcloud/mail/issues/8223
