### ISSUE TITLE
[PHP] Error: Using ${var} in strings is deprecated

### ISSUE THREAD

**Issue by thstyl2000** [nextcloud/mail#8556]
### Steps to reproduce

1. Look at the nextcloud logs.

### Expected behavior

No php errors.

### Actual behavior

Following error is logged:

```
[PHP] Error: Using ${var} in strings is deprecated, use {$var} instead at /usr/local/www/nextcloud/apps/mail/vendor/voku/portable-utf8/src/voku/helper/UTF8.php#13409

at 2023-06-16T09:05:05+00:00
```

### Mail app version

3.2.1

### Mailserver or service

imap (dovecot)

### Operating system

freebsd 13.1

### PHP engine version

PHP 8.2

### Web server

Apache (supported)

### Database

MariaDB

### Additional info

[https://github.com/nextcloud/server/issues/37362](https://github.com/nextcloud/server/issues/37362)

**Comment by ChristophWurst** [comment]
https://github.com/nextcloud/mail/issues?q=is%3Aissue+%22Using+%24%7Bvar%7D%22+is%3Aclosed

**Comment by ChristophWurst** [comment]
Dup of https://github.com/nextcloud/mail/issues/8317

**Comment by ChristophWurst** [comment]
https://github.com/nextcloud/mail/pull/8558 for a backport to 3.2

**Comment by thstyl2000** [comment]
Sorry for double posting, thanks!
