### ISSUE TITLE
Mail is not syncing

### ISSUE THREAD

**Issue by Markoise** [nextcloud/mail#8561]
### Steps to reproduce

1. Move mail to a subfolder in a mail client (Thunderbird, ...).
2. Alternatively, a mail can be moved to the junk folder in the mail client (Thunderbird, ...).

### Expected behavior

Mail that is moved in another mail client should also be synchronized in the WebClient.

### Actual behavior

However, if you use another mail client at the same time and move mails to a folder there, this will not be taken into account in the app. The e-mail is still in the inbox and must be deleted there manually.
If you want to open this mail, you will be informed that the mail cannot be found.

### Mail app version

3.2.1

### Mailserver or service

GMail, Outlook, IMAP, ...

### Operating system

Webhosting (probably Linux)

### PHP engine version

None

### Web server

None

### Database

None

**Comment by ChristophWurst** [comment]
Dup of https://github.com/nextcloud/mail/issues/8223
