### ISSUE TITLE
Missing error handling for message header parsing

### ISSUE THREAD

**Issue by sergiupapuc** [nextcloud/mail#8568]
### Steps to reproduce

1.error in log
2.foreach() argument must be of type array|object, bool given at /var/www/nextcloud/apps/mail/lib/IMAP/ImapMessageFetcher.php#527
3.

### Expected behavior

foreach() argument must be of type array|object, bool given at /var/www/nextcloud/apps/mail/lib/IMAP/ImapMessageFetcher.php#527

### Actual behavior

foreach() argument must be of type array|object, bool given at /var/www/nextcloud/apps/mail/lib/IMAP/ImapMessageFetcher.php#527

### Mail app version

3.2.2

### Mailserver or service

imap

### Operating system

ubuntu

### PHP engine version

None

### Web server

None

### Database

None

### Additional info

foreach() argument must be of type array|object, bool given at /var/www/nextcloud/apps/mail/lib/IMAP/ImapMessageFetcher.php#527

**Comment by GretaD** [comment]
Hello, can you please explain what where you doing on mail app that this error was shown. Please complete the template with the importation needed

**Comment by sergiupapuc** [comment]
...in the interface of Mail App, no error...but in the logs is the line with error !...nothing special is done, just read mail!

**Comment by ChristophWurst** [comment]
It is probably the loop at https://github.com/nextcloud/mail/blob/3a8cf2dc0abc24b5cae6febdb05f06482302034a/lib/IMAP/ImapMessageFetcher.php#LL528C5-L528C5. ``\Horde_ListHeaders::parse`` returns `false` when the headers can't be parsed.

**Comment by ChristophWurst** [comment]
> error in log

@sergiupapuc please look up the full line in nextcloud.log. We need the complete json entry with its error trace.

**Comment by sergiupapuc** [comment]
foreach() argument must be of type array|object, bool given at /var/www/nextcloud/apps/mail/lib/IMAP/ImapMessageFetcher.php#527

...this is the full line !

**Comment by ChristophWurst** [comment]
> ...this is the full line !

It certainly isn't. nextcloud.log contains json.

**Comment by kesselb** [comment]
```
Index: lib/IMAP/ImapMessageFetcher.php
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
diff --git a/lib/IMAP/ImapMessageFetcher.php b/lib/IMAP/ImapMessageFetcher.php
--- a/lib/IMAP/ImapMessageFetcher.php	(revision f276a6e7d900f37f5a5f9f83508dc5aff9b16885)
+++ b/lib/IMAP/ImapMessageFetcher.php	(date 1687620651442)
@@ -43,7 +43,7 @@
 use OCA\Mail\Model\IMAPMessage;
 use OCA\Mail\Service\Html;
 use OCA\Mail\Service\SmimeService;
-use OCP\AppFramework\Db\DoesNotExistException;
+use OCP\AppFramework\Db\DoesNotExistException;;
 use function str_starts_with;
 use function strtolower;
 
@@ -525,6 +525,14 @@
 			$listHeaders = new Horde_ListHeaders();
 			/** @var Horde_ListHeaders_Base[] $headers */
 			$headers = $listHeaders->parse($listUnsubscribeHeader->name, $listUnsubscribeHeader->value_single);
+			if ($headers === false) {
+				\OCP\Log\logger('mail')->error('failed to parse list-unsubscribe header', [
+					'name' => $listUnsubscribeHeader->name,
+					'value_single' => $listUnsubscribeHeader->value_single,
+				]);
+				$headers = [];
+			}
+
 			foreach ($headers as $header) {
 				if (str_starts_with($header->url, 'http')) {
 					$this->unsubscribeUrl = $header->url;

```

Could you apply the above patch and check your logs afterward? The logger should print the invalid input leading to the parser error.

**Comment by realDayaa** [comment]
@kesselb 

I'm having the same issue. Inserting these lines gives the following new error log message:
**failed to parse list-unsubscribe header**

**Comment by realDayaa** [comment]
@kesselb I'm getting the same error. Inserting these lines gives the following error log message.
**failed to parse list-unsubscribe header**
