### ISSUE TITLE
Send e-mail to all users or members of a user group

### ISSUE THREAD

**Issue by Schmidty2** [nextcloud/mail#861]
Is it possible to include a feature so that all Nextcloud users can be selected as email recipients at once?
Also the function to select all members of a Nextcloud user group as a recipient would be a good complement.

Background: All Nextcloud users or members of a group should be notified by e-mail, e.g. about maintenance or innovations. With the Nextcloud mail app, only one user can be selected at a time, knowing the username or email address so that it is suggested for selection.

**Comment by ChristophWurst** [comment]
> Is it possible to include a feature so that all Nextcloud users can be selected as email recipients at once?

Yes! This was added recently: https://github.com/nextcloud/mail/pull/810. The upcoming v0.8.0 release will offer this feature. Meanwhile, you can test the alpha release and report back any problems that you're facing: https://github.com/nextcloud/mail/releases/tag/v0.8.0-alpha1 :rocket: 

> Background: All Nextcloud users or members of a group should be notified by e-mail, e.g. about maintenance or innovations. With the Nextcloud mail app, only one user can be selected at a time, knowing the username or email address so that it is suggested for selection.

Possibly also relevant for this use case: https://github.com/nextcloud/announcementcenter

**Comment by Schmidty2** [comment]
How to install version 8.0 beta 1 under Nextcloud 13. I only get the version 7.10 offered.

**Comment by ChristophWurst** [comment]
> How to install version 8.0 beta 1 under Nextcloud 13. I only get the version 7.10 offered.

It's a beta and not a release, hence you cannot install it via the admin interface but you have to install it manually.
