### ISSUE TITLE
Reply to sender does not work 

### ISSUE THREAD

**Issue by thstyl2000** [nextcloud/mail#8621]
### Steps to reproduce

1. Receive an email addressed to more than one recipient. 
2. Click on th 3dot menu. 
3. Click on "reply to sender". 

### Expected behavior

Reply only to sender. 

### Actual behavior

Nada. 

### Mail app version

3.2.3

### Mailserver or service

Imap (dovecot) 

### Operating system

FreeBSD 13.1

### PHP engine version

PHP 8.2

### Web server

Apache (supported)

### Database

MariaDB

**Comment by GretaD** [comment]
most probably a regression of the composer changes
