### ISSUE TITLE
Message vanishes after sending it with a schedule

### ISSUE THREAD

**Issue by st3iny** [nextcloud/mail#8630]
### Steps to reproduce

1. Compose a message.
2. Wait until a draft is saved (couple seconds).
3. Schedule the message to be sent later.
4. Send it.

### Expected behavior

The outbox should become visible in the left navigation bar and it should contain the message just sent.

### Actual behavior

The message just vanishes. The outbox won't become visible.

If the outbox is shown (through a hack), it won't contain the message.

### Mail app version

main (and c.nc.c)

**Comment by DanialSh** [comment]
Same issue here! Running nextcloud 27.0.1, mail app version 3.3.0-alpha.1.

**Comment by ChristophWurst** [comment]
Could there be an issue with the new draft handling that also uses a "local mailbox" and the same database table?

**Comment by st3iny** [comment]
> Could there be an issue with the new draft handling that also uses a "local mailbox" and the same database table?

Exactly that is the problem. See https://github.com/nextcloud/mail/issues/8631. Both controllers use the same table but provide 2 separate REST apis.

**Comment by ChristophWurst** [comment]
For data recovery, I think it should be possible to restore messages for a user.

The messages are wrongly saved as type=draft with a send_at value set. The outbox doesn't show them. The draft background job doesn't move them to imap.

If we unset the send_at, the drafts background job will write the messages as IMAP draft.
If we change the type, the message will show in the outbox and also be picked up for sending.

**Comment by st3iny** [comment]
Sounds good. IMO, the first approach (send_at = null) is safer.
