### ISSUE TITLE
New SystemAddressBook is not showing in Mail-App

### ISSUE THREAD

**Issue by AlexanderZuehr** [nextcloud/mail#8639]
I am using Nextcloud 27 to test the new systemwide SystemAddressBook, it is working quite good but sadly it is not working with the mail-app.
If I create a manual address-book the mail-addresses are shown in the mail app to autofill them but the new systemwide SystemAddressBook does not work the same way, its mail-addresses are only shown in the calendar-app and the share feature but it is missing in the mail-app.

At the first picture you can see the feature working with a manual address book.
At the second picture you can see that it isn't working anymore with the systemwide SystemAdressBook.
<img width="605" alt="Bildschirmfoto 2023-07-20 um 09 05 11" src="https://github.com/nextcloud/mail/assets/76497172/2d0f82de-fb8f-4ffc-9314-648247c0c127">

<img width="604" alt="Bildschirmfoto 2023-07-20 um 09 05 24" src="https://github.com/nextcloud/mail/assets/76497172/1c93cc9b-d885-47c2-9c4e-68ee9e59d253">

Is this feature possible planed or already in an alpha version of the mail-app?

### Mail app version

3.1.1

### Operating system

Nextcloud 27

### PHP engine version

8.2

### Web server

Apache

### Database

None

**Comment by ChristophWurst** [comment]
See https://github.com/nextcloud/mail/issues/1215. The fix should be released soon.
