### ISSUE TITLE
Invisible IMAP user folders

### ISSUE THREAD

**Issue by Alvserg** [nextcloud/mail#867]
### Steps to reproduce
1. Open Mail
2. Don't see IMAP user created folders. It's exist and I can open it, but is't invisible. Screensort attached.

### Expected behaviour
I'd like to see users IMAP folders

### Actual behaviour
Don't see IMAP user created folders. It's exist and I can open it, but is't invisible. Screensort attached.

### Mail app

**Mail app version:** 	0.7.10

**Mailserver or service:** Sendmail

**Number of accounts:** 2

## Server configuration detail
![2018-04-10_124914](https://user-images.githubusercontent.com/38246112/38550672-d3a48f12-3cbf-11e8-8413-5df9856af298.jpg)

**Operating system:** Linux 4.4.0-119-generic #143-Ubuntu SMP Mon Apr 2 16:08:24 UTC 2018 x86_64

**Webserver:** Apache/2.4.18 (Ubuntu) (apache2handler)

**Database:** mysql 10.2.14

**PHP version:** 7.0.28-0ubuntu0.16.04.1
Modules loaded: Core, date, libxml, openssl, pcre, zlib, filter, hash, Reflection, SPL, session, standard, apache2handler, redis, mysqlnd, PDO, xml, calendar, ctype, curl, dom, mbstring, fileinfo, ftp, gd, gettext, iconv, imagick, imap, intl, json, ldap, exif, mcrypt, mysqli, pdo_mysql, pdo_pgsql, pdo_sqlite, pgsql, Phar, posix, readline, shmop, SimpleXML, smbclient, sockets, sqlite3, sysvmsg, sysvsem, sysvshm, tokenizer, wddx, xmlreader, xmlwriter, xsl, zip, libsmbclient, Zend OPcache

**Nextcloud version:** 13.0.1 - 13.0.1.1

**Updated from an older Nextcloud/ownCloud or fresh install:** 

**Where did you install Nextcloud from:** unknown

<details><summary>Signing status</summary>

Array
</details>

<details><summary>List of activated apps</summary>

```
Enabled:
 - activity: 2.6.1
 - calendar: 1.6.1
 - caniupdate: 0.1.2
 - comments: 1.3.0
 - contacts: 2.1.3
 - dav: 1.4.6
 - federatedfilesharing: 1.3.1
 - federation: 1.3.0
 - files: 1.8.0
 - files_fulltextsearch: 0.6.0
 - files_pdfviewer: 1.2.0
 - files_sharing: 1.5.0
 - files_texteditor: 2.5.1
 - files_trashbin: 1.3.0
 - files_versions: 1.6.0
 - files_videoplayer: 1.2.0
 - firstrunwizard: 2.2.1
 - fulltextsearch: 0.6.1
 - fulltextsearch_elasticsearch: 0.6.1
 - gallery: 18.0.0
 - issuetemplate: 0.3.0
 - logreader: 2.0.0
 - lookup_server_connector: 1.1.0
 - mail: 0.7.10
 - nextcloud_announcements: 1.2.0
 - notifications: 2.1.2
 - oauth2: 1.1.0
 - passman: 2.1.4
 - password_policy: 1.3.0
 - previewgenerator: 1.0.9
 - provisioning_api: 1.3.0
 - serverinfo: 1.3.0
 - sharebymail: 1.3.0
 - spreed: 3.1.0
 - survey_client: 1.1.0
 - systemtags: 1.3.0
 - theming: 1.4.1
 - twofactor_backupcodes: 1.2.3
 - updatenotification: 1.3.0
 - workflowengine: 1.3.0
Disabled:
 - admin_audit
 - encryption
 - files_external
 - user_external
 - user_ldap

```
</details>

<details><summary>Configuration (config/config.php)</summary>

```
{
    "passwordsalt": "***REMOVED SENSITIVE VALUE***",
    "secret": "***REMOVED SENSITIVE VALUE***",
    "trusted_domains": [
        "192.168.88.130"
    ],
    "datadirectory": "***REMOVED SENSITIVE VALUE***",
    "overwrite.cli.url": "http:\/\/localhost",
    "dbtype": "mysql",
    "version": "13.0.1.1",
    "dbname": "***REMOVED SENSITIVE VALUE***",
    "dbhost": "***REMOVED SENSITIVE VALUE***",
    "dbport": "",
    "dbtableprefix": "oc_",
    "mysql.utf8mb4": true,
    "dbuser": "***REMOVED SENSITIVE VALUE***",
    "dbpassword": "***REMOVED SENSITIVE VALUE***",
    "installed": true,
    "instanceid": "***REMOVED SENSITIVE VALUE***",
    "maintenance": false,
    "mail_smtpmode": "smtp",
    "log_rotate_size": "10485760",
    "memcache.local": "\\OC\\Memcache\\Redis",
    "filelocking.enabled": true,
    "memcache.distributed": "\\OC\\Memcache\\Redis",
    "memcache.locking": "\\OC\\Memcache\\Redis",
    "redis": {
        "host": "***REMOVED SENSITIVE VALUE***",
        "port": 0,
        "timeout": 0,
        "dbindex": 0,
        "password": "***REMOVED SENSITIVE VALUE***"
    },
    "htaccess.RewriteBase": "\/",
    "mail_smtphost": "***REMOVED SENSITIVE VALUE***",
    "mail_smtpauthtype": "PLAIN",
    "mail_smtpport": "25",
    "mail_from_address": "***REMOVED SENSITIVE VALUE***",
    "mail_domain": "***REMOVED SENSITIVE VALUE***"
}
```
</details>

**Are you using external storage, if yes which one:** local/smb/sftp/...

**Are you using encryption:** no

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...

<details><summary>LDAP configuration (delete this part if not used)</summary>

```
With access to your command line run e.g.:
sudo -u www-data php occ ldap:show-config
from within your Nextcloud installation folder

Without access to your command line download the data/owncloud.db to your local
computer or access your SQL server remotely and run the select query:
SELECT * FROM `oc_appconfig` WHERE `appid` = 'user_ldap';


Eventually replace sensitive data as the name/IP-address of your LDAP server or groups.
```
</details>

## Client configuration

**Browser:** Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/65.0.3325.181 Safari/537.36

**Operating system:** 

## Logs

<details><summary>Browser log</summary>

```
Insert your webserver log here 
```
</details>

<details><summary>Nextcloud log</summary>

```
Insert your Nextcloud log here
```
</details>

<details><summary>Browser log</summary>

Insert your browser log here, this could for example include:

	a) The javascript console log
	b) The network log
	c) ...
</details>

**Comment by LukeOwlclaw** [comment]
I tracked the problem down to CSS element:

    #app-navigation > ul > .navigation-account > .folders > li.collapsible:not(.open) > .folders, 

/* line 861, /var/www/nextcloud/apps/mail/css/mail.scss */

Removing that line at least shows the folder. However, it always shows all of them -> button "collapse folder" has no effect.

The collapse button does not set the ``.open`` class, when being clicked. If it did add it to element:

    html.ng-csp body#body-user div#content-wrapper div#content.app-mail div#app div#app-navigation ul#app-navigation-accounts.with-icon div.navigation-account div.folders li.with-counter.special-inbox.collapsible.ui-droppable

the folders would show.

**Comment by ChristophWurst** [comment]
@LukeOwlclaw thank you very much for looking into that. Feel free to submit your changes as pull request so that we can discuss the changes and hopefully fix the reported bug!

**Comment by LukeOwlclaw** [comment]
The issue still exists in Mail app version 0.11.0.

@ChristophWurst I do not understand enough of the details to for a good-quality PR.

**Comment by ChristophWurst** [comment]
This might be fixed with the upcoming v0.12 where the front end has been rewritten.

**Comment by LukeOwlclaw** [comment]
Yeah! In 0.15.2 (maybe before) it is fixed. Thank you!

I assume this tiny glitch (doubled blue highlight indicator) is not worth complaining about, is it?
![image](https://user-images.githubusercontent.com/2737900/62846422-6da10780-bcd0-11e9-8521-8a592225e90a.png)

**Comment by ChristophWurst** [comment]
>  is not worth complaining about, is it?

it is! mind reporting to https://github.com/nextcloud/nextcloud-vue?
