### ISSUE TITLE
Archive hotkey does not work

### ISSUE THREAD

**Issue by xandris** [nextcloud/mail#8675]
### Steps to reproduce

1. View a message outside the archive folder.
2. In English locales, press 'A' (not sure if this varies by locale)

### Expected behavior

The message should move to the configured archive folder and the app should move on to the next message in the current folder.

### Actual behavior

The message disappears. This error toast appears briefly:

![image](https://github.com/nextcloud/mail/assets/1970616/df0805f2-31ea-4a20-be9d-736116327473)

The following error is observed in the JavaScript console:

```
TypeError: i is undefined
    r Mailbox.vue:402
```

The message reappears after a moment.

### Mail app version

3.2.5

### Mailserver or service

Gmail

### Operating system

Linux (Gentoo)

### PHP engine version

PHP 8.2

### Web server

Nginx

### Database

PostgreSQL

### Additional info

The error refers to this line of code:

https://github.com/nextcloud/mail/blob/v3.2.5/src/components/Mailbox.vue#L402

```javascript
			const envelopes = this.envelopes // empty array
			const env = envelopes.find((e) => e.databaseId === currentId) // undefined
			// ...
				if (env.mailboxId === this.account.archiveMailboxId) { // crashes here
```

The archive button works correctly.

This appears to be a different issue from #8047.

**Comment by kesselb** [comment]
Thanks for your bug report :+1: 

If env is empty, we cannot move the message ;)
That's a very weird state.

Do you see a failing xhr request in your console/network inspector?

**Comment by xandris** [comment]
Yes, I saw a POST with an empty request body to the message's URL. It is met with an HTTP 400.

Aug 6, 2023 08:10:47 Daniel ***@***.***>:

**Comment by ChristophWurst** [comment]
It works again
