### ISSUE TITLE
Assistance with connecting mail app to locally hosted mail server

### ISSUE THREAD

**Issue by greavette** [nextcloud/mail#868]
Nextcloud - 13.0.1
mail app - 0.7.10

Hello Team,

I've successfully installed and setup rainloop mail app in our Nextcloud server connecting to our locally hosted mail server in our office.

I'm using the same settings from my rainloop setup in this mail app but I cannot connect this Nextcloud mail app to our mail server?  The app tries to connect and spins for a very long time without connecting.  

Where can I find log files to help me determine why this mail app will not connect to our mail server?
Do I need to set these settings in a config and not set them through the mail app in Nextcloud?

I see reference to editing the config.php file.  Where is this file located?

Thank you.

**Comment by ChristophWurst** [comment]
Hi!

Thank you for your report. It looks like your report is missing some important sections of your [issue template](https://raw.githubusercontent.com/nextcloud/mail/master/.github/issue_template.md). Please complete it so that we get a better understanding of your setup and the problem to be able to fix the issue.

Thank you.

**Comment by rasos** [comment]
If the mail server is on the same host you connect to localhost and if all is behind a firewall you can likely connect without encryption on port 143. You can change all settings from the web interface, in the `/var/www/nextcloud/config/config.php` you just set default settings.

**Comment by ChristophWurst** [comment]
> If the mail server is on the same host you connect to localhost and if all is behind a firewall you can likely connect without encryption on port 143. You can change all settings from the web interface, in the /var/www/nextcloud/config/config.php you just set default settings.

Sound like you're talking about Nextcloud server's mail settings. This repo only covers issues of the mail app.

Since none of the information asked for has been given, I'm closing this ticket now.
