### ISSUE TITLE
TO: and CC: fields dissapear from Reply window when attempting to reply to email. 

### ISSUE THREAD

**Issue by mikejtl** [nextcloud/mail#869]
### Steps to reproduce
1. Open incoming message.
2. Place cursor in reply window as if replying to the email. 

### Expected behaviour
The TO: field and CC: field should remain available to be edited. 

### Actual behaviour
The fields dissapear and do not return unless the a different incoming message is selected and then the original one is reopened. 

This issue only happens on Firefox, on Chrome and Safari it is not an issue.

**Comment by ChristophWurst** [comment]
cannot reproduce. cc @nextcloud/mail

**Comment by jancborchardt** [comment]
Can’t reproduce this either. @mikejtl can you reproduce this with a different instance as well, or on a local dev environment?
