### ISSUE TITLE
Thread envelope actions have misplaced icons on narrow screens

### ISSUE THREAD

**Issue by ChristophWurst** [nextcloud/mail#8695]
### Steps to reproduce

1. Open the app
2. Set up an account
3. Open a thread
4. Make the browser window narrow or have a small screen
5. Open the thread envelope menu

### Expected behavior

Good design

### Actual behavior

| 1 | 2 |
|--------|--------|
| ![Bildschirmfoto vom 2023-08-09 10-34-13](https://github.com/nextcloud/mail/assets/1374172/1f59a833-0ea3-49d3-9a5b-8dcd7bcce0fb) | ![Bildschirmfoto vom 2023-08-09 10-36-22](https://github.com/nextcloud/mail/assets/1374172/1d835322-48de-4bf6-906c-929d8609b2da) |

### Mail app version

3

### PHP engine version

None

### Web server

None

### Database

None

**Comment by auroraanna** [comment]
I meant to post
- https://github.com/nextcloud/mail/issues/8696#issuecomment-1673030537
- https://github.com/nextcloud/mail/issues/8696#issuecomment-1673048423
- https://github.com/nextcloud/mail/issues/8696#issuecomment-1673050622

here.

[In the documentation Christoph provided](https://github.com/nextcloud/mail/issues/8696#issuecomment-1673055175) the button text is always added as a span, not via the `:title` attribute. I assume that is the correct way then.

**Comment by auroraanna** [comment]
Hmm, the way of the documentation produces empty `aria-label` and `title`s when the buttons are in the 3-dot-menu. Since there is already a span with what the button does inside of the button, are `aria-label` and `title` needed for accessibility?

**Comment by ChristophWurst** [comment]
> are `aria-label` and `title` needed for accessibility?

@JuliaKirschenheuter do we need both?
