### ISSUE TITLE
Inline thread envelope actions show in *More actions* as well

### ISSUE THREAD

**Issue by ChristophWurst** [nextcloud/mail#8696]
### Steps to reproduce

1. Open the app
2. Set up an account
3. Open a thread
4. Have a narrow screen or make the browser window narrow
5. Open the actions menu of a thread envelope

### Expected behavior

No inline actions in *More actions*

### Actual behavior

| Primary actions | More actions |
|--------|--------|
| ![Bildschirmfoto vom 2023-08-09 10-34-28](https://github.com/nextcloud/mail/assets/1374172/69094000-6394-4967-af7d-e24c21c11d20) | ![Bildschirmfoto vom 2023-08-09 10-34-35](https://github.com/nextcloud/mail/assets/1374172/73b2210d-c0ae-4bff-a71e-e479b251bebb) | 

### Mail app version

3

### PHP engine version

None

### Web server

None

### Database

None

**Comment by auroraanna** [comment]
I'm confused on why this only happens in this case. I do know how to fix it though.

**Comment by auroraanna** [comment]
As far as I understand it, the misalignment of the button icon and button text only happens when the button text is added via the `:title` attribute on `NcActionButton`. This is how it is done in `ThreadEnvelope` but not in `MenuEnvelope`. In `MenuEnvelope` it is added as a span inside of `NcActionButton`. I am not sure which one is the better way here. Is there any documentation on this? I would like to change both Components to use one way.

**Comment by auroraanna** [comment]
In the case that `:title` should be used over the span, the style `display: flex; align-items: center` would have to be added to the paragraph of the button text.

**Comment by ChristophWurst** [comment]
> Is there any documentation on this?

https://nextcloud-vue-components.netlify.app/#/Components/NcActions?id=ncactionbutton

**Comment by auroraanna** [comment]
Oops, replied to the wrong issue.

**Comment by ChristophWurst** [comment]
> I'm confused on why this only happens in this case. I do know how to fix it though.

Here's my theory. We use an NcActions component. On top there are two modifications:
1) We use the `inline` prop to move n actions out of the menu if there is enough space
2) We toggle the menu contents dynamically to have primary and secondary actions

These two seem to conflict.

We inline up to four actions. On a wide screen that means the 5th to the last primary actions is toggled when switching to secondary actions. On the most narrow screen we have to toggle all primary actions.

**Comment by st3iny** [comment]
Fixed by https://github.com/nextcloud/mail/pull/8850.
