### ISSUE TITLE
Emails from noreply@ addresses not visible in All inboxes view

### ISSUE THREAD

**Issue by brzd** [nextcloud/mail#870]
### Steps to reproduce
1. Receive email from noreply@.... to one of your emails
2. Visible in both all inboxes and individual email box in the beginning
3. All inboxes view is refreshed / logged in again --> noreply@ addressed emails not visible in All inboxes view anymore!
4. Still visible in separate email box

### Expected behaviour
All emails from inboxes defined into nextcloud mail should be visible in "All inboxes" view.

### Actual behaviour
Emails, visible in individual inbox view, are not visible in the all inboxes view.

### Mail app

**Mail app version:** (see apps admin page)
0.7.10

**Mailserver or service:** (e.g. Outlook, Yahoo, Gmail, Exchange,...)
ovh.net / own domain

**Number of accounts:**
2

### Server configuration

**Operating system:** Linux 4.4.0-119-generic #143-Ubuntu SMP Mon Apr 2 16:08:24 UTC 2018 x86_64

**Webserver:** Apache (apache2handler)

**Database:** mysql 10.0.34

**PHP version:** 7.0.28-0ubuntu0.16.04.1
Modules loaded: Core, date, libxml, openssl, pcre, zlib, filter, hash, Reflection, SPL, session, standard, apache2handler, mysqlnd, PDO, xml, calendar, ctype, curl, dom, mbstring, fileinfo, ftp, gd, gettext, iconv, imagick, intl, json, exif, mcrypt, mysqli, pdo_mysql, Phar, posix, readline, shmop, SimpleXML, sockets, sysvmsg, sysvsem, sysvshm, tokenizer, wddx, xmlreader, xmlwriter, xsl, zip, Zend OPcache

**Nextcloud version:** 13.0.1 - 13.0.1.1

**Comment by ChristophWurst** [comment]
cc @jakobsack

**Comment by MG2R** [comment]
As a data point: I'm not able to reproduce this

* nextcloud 13.0.1
* mail app 0.7.10
* Number of accounts: 2
* PHP-FPM 7.2.4-1
* Self-hosted mail server on OVH: Postfix + Dovecot
* Linux <hostname> 4.15.6-1-ARCH #1 SMP PREEMPT Sun Feb 25 12:53:23 UTC 2018 x86_64 GNU/Linux
* Apache 2.4.33-3

**Comment by jakobsack** [comment]
I'll try to reproduce it today
