### ISSUE TITLE
Mail keep loading message from google account with <250 inbox

### ISSUE THREAD

**Issue by cahyadilumine** [nextcloud/mail#8708]
### Steps to reproduce

1. Login with google account after enabling POP/IMAP and less secure app setting
2. At mail dashboard, when click inbox the preview keep loading message

### Expected behavior

It should sync and show the list of inbox message from gmail

### Actual behavior

its keep loading message

### Mail app version

3.2.6

### Mailserver or service

Gmail

### Operating system

Centos 7

### PHP engine version

PHP 8.0

### Web server

Apache (supported)

### Database

MySQL

### Additional info

[mail] Error: OCA\Mail\Exception\ServiceException: Sync failed for 39:[Gmail]/All Mail: Call to undefined function ini_restore() at <<closure>>

0. /www/wwwroot/nx.luminestudio.net/apps/mail/lib/Service/Sync/SyncService.php line 126
   OCA\Mail\Service\Sync\ImapToDbSynchronizer->sync("*** sensitive parameters replaced ***")
1. /www/wwwroot/nx.luminestudio.net/apps/mail/lib/Controller/MailboxesController.php line 154
   OCA\Mail\Service\Sync\SyncService->syncMailbox("*** sensitive parameters replaced ***")
2. /www/wwwroot/nx.luminestudio.net/lib/private/AppFramework/Http/Dispatcher.php line 230
   OCA\Mail\Controller\MailboxesController->sync("*** sensitive parameters replaced ***")
3. /www/wwwroot/nx.luminestudio.net/lib/private/AppFramework/Http/Dispatcher.php line 137
   OC\AppFramework\Http\Dispatcher->executeController()
4. /www/wwwroot/nx.luminestudio.net/lib/private/AppFramework/App.php line 183
   OC\AppFramework\Http\Dispatcher->dispatch()
5. /www/wwwroot/nx.luminestudio.net/lib/private/Route/Router.php line 315
   OC\AppFramework\App::main()
6. /www/wwwroot/nx.luminestudio.net/lib/base.php line 1058
   OC\Route\Router->match()
7. /www/wwwroot/nx.luminestudio.net/index.php line 36
   OC::handleRequest()

Caused by:

Error: Call to undefined function ini_restore() at <<closure>>

 0. /www/wwwroot/nx.luminestudio.net/apps/mail/vendor/bytestream/horde-util/lib/Horde/String.php line 99
    Horde_String::_convertCharset()
 1. /www/wwwroot/nx.luminestudio.net/apps/mail/vendor/bytestream/horde-mime/lib/Horde/Mime.php line 259
    Horde_String::convertCharset()
 2. /www/wwwroot/nx.luminestudio.net/apps/mail/vendor/bytestream/horde-mime/lib/Horde/Mime/Headers/Element/Single.php line 62
    Horde_Mime::decode()
 3. /www/wwwroot/nx.luminestudio.net/apps/mail/vendor/bytestream/horde-mime/lib/Horde/Mime/Headers/Element.php line 79
    Horde_Mime_Headers_Element_Single->_setValue()
 4. /www/wwwroot/nx.luminestudio.net/apps/mail/vendor/bytestream/horde-mime/lib/Horde/Mime/Headers/Element.php line 56
    Horde_Mime_Headers_Element->setValue()
 5. /www/wwwroot/nx.luminestudio.net/apps/mail/vendor/bytestream/horde-mime/lib/Horde/Mime/Headers/Subject.php line 31
    Horde_Mime_Headers_Element->__construct()
 6. /www/wwwroot/nx.luminestudio.net/apps/mail/vendor/bytestream/horde-mime/lib/Horde/Mime/Headers.php line 201
    Horde_Mime_Headers_Subject->__construct()
 7. /www/wwwroot/nx.luminestudio.net/apps/mail/vendor/bytestream/horde-mime/lib/Horde/Mime/Headers.php line 371
    Horde_Mime_Headers->addHeader()
 8. /www/wwwroot/nx.luminestudio.net/apps/mail/lib/IMAP/ImapMessageFetcher.php line 505
    Horde_Mime_Headers::parseHeaders()
 9. /www/wwwroot/nx.luminestudio.net/apps/mail/lib/IMAP/ImapMessageFetcher.php line 232
    OCA\Mail\IMAP\ImapMessageFetcher->parseHeaders()
10. /www/wwwroot/nx.luminestudio.net/apps/mail/lib/IMAP/MessageMapper.php line 314
    OCA\Mail\IMAP\ImapMessageFetcher->fetchMessage()
11. <<closure>>
    OCA\Mail\IMAP\MessageMapper->OCA\Mail\IMAP\{closure}("*** sensitive parameters replaced ***")
12. /www/wwwroot/nx.luminestudio.net/apps/mail/lib/IMAP/MessageMapper.php line 315
    array_map()
13. /www/wwwroot/nx.luminestudio.net/apps/mail/lib/IMAP/MessageMapper.php line 229
    OCA\Mail\IMAP\MessageMapper->findByIds()
14. /www/wwwroot/nx.luminestudio.net/apps/mail/lib/Service/Sync/ImapToDbSynchronizer.php line 309
    OCA\Mail\IMAP\MessageMapper->findAll()
15. /www/wwwroot/nx.luminestudio.net/apps/mail/lib/Service/Sync/ImapToDbSynchronizer.php line 233
    OCA\Mail\Service\Sync\ImapToDbSynchronizer->runInitialSync()
16. /www/wwwroot/nx.luminestudio.net/apps/mail/lib/Service/Sync/SyncService.php line 126
    OCA\Mail\Service\Sync\ImapToDbSynchronizer->sync("*** sensitive parameters replaced ***")
17. /www/wwwroot/nx.luminestudio.net/apps/mail/lib/Controller/MailboxesController.php line 154
    OCA\Mail\Service\Sync\SyncService->syncMailbox("*** sensitive parameters replaced ***")
18. /www/wwwroot/nx.luminestudio.net/lib/private/AppFramework/Http/Dispatcher.php line 230
    OCA\Mail\Controller\MailboxesController->sync("*** sensitive parameters replaced ***")
19. /www/wwwroot/nx.luminestudio.net/lib/private/AppFramework/Http/Dispatcher.php line 137
    OC\AppFramework\Http\Dispatcher->executeController()
20. /www/wwwroot/nx.luminestudio.net/lib/private/AppFramework/App.php line 183
    OC\AppFramework\Http\Dispatcher->dispatch()
21. /www/wwwroot/nx.luminestudio.net/lib/private/Route/Router.php line 315
    OC\AppFramework\App::main()
22. /www/wwwroot/nx.luminestudio.net/lib/base.php line 1058
    OC\Route\Router->match()
23. /www/wwwroot/nx.luminestudio.net/index.php line 36
    OC::handleRequest()

POST /index.php/apps/mail/api/mailboxes/252/sync
from 192.168.11.1 by Administrator at 2023-08-10T06:41:30+00:00

**Comment by ChristophWurst** [comment]
> Call to undefined function ini_restore()

et voila

the function is probably disabled or a php module is missing

**Comment by ChristophWurst** [comment]
https://www.php.net/manual/en/function.ini-restore.php

**Comment by cahyadilumine** [comment]
Hi Chris, Thanks for your help. i just enable ini-restore function on the php, and after few minutes the messages appear. 

but i see that the load of messages is so slow, is there any way to speedup this process?
