### ISSUE TITLE
Autoresponder turns settings modal blank when turned on

### ISSUE THREAD

**Issue by ChristophWurst** [nextcloud/mail#8715]
### Steps to reproduce

1. Set up an account
2. Configure Sieve
3. Open the account settings
4. Scroll to the autoresponder section
5. Turn on autoresponder

### Expected behavior

Form gets enabled

### Actual behavior

The modal becomes blank:
![Bildschirmfoto vom 2023-08-10 17-32-46](https://github.com/nextcloud/mail/assets/1374172/0c83bb21-1c5c-4301-ac0c-1322686a259b)

Inspection shows the contest are still there: 
![image](https://github.com/nextcloud/mail/assets/1374172/830fdea4-bd1a-4da1-8fac-04d63a8df132)

### Mail app version

3.3 or 3.4

### PHP engine version

None

### Web server

None

### Database

None

**Comment by ChristophWurst** [comment]
We had similar issues in the early WIPs of the feature: https://github.com/nextcloud/mail/pull/7102#issuecomment-1235516347. Did they come back?

**Comment by ChristophWurst** [comment]
No errors in the console

**Comment by kesselb** [comment]
We touched the related CSS rules recently to fix the close icon: https://github.com/nextcloud/mail/pull/8665

**Comment by ChristophWurst** [comment]
I'll check a bisect. Good point.

**Comment by ChristophWurst** [comment]
On main the modal already behaves weird when I set up Sieve. It might not be specific to autoresponders.

![Bildschirmfoto vom 2023-08-10 18-47-38](https://github.com/nextcloud/mail/assets/1374172/ea9a3c1c-1280-459e-a111-c8968f133a0a)

**Comment by ChristophWurst** [comment]
```
$ git bisect good
dfbfaa3de38c5faf5a3040db72466ed2e0820c2d is the first bad commit
commit dfbfaa3de38c5faf5a3040db72466ed2e0820c2d
Author: Richard Steinmetz <richard@steinmetz.cloud>
Date:   Thu Aug 3 09:44:54 2023 +0200

    fix(settings): fix account settings modal close button
    
    Signed-off-by: Richard Steinmetz <richard@steinmetz.cloud>

 src/components/AccountSettings.vue | 6 ------
 1 file changed, 6 deletions(-)
```

**Comment by st3iny** [comment]
Hmm, I tested it locally in Firefox. Revert the css at the bottom of `AccountSettings.vue`. The added modal title can stay and is not related.

**Comment by ChristophWurst** [comment]
So we revert https://github.com/nextcloud/mail/pull/8665/commits/dfbfaa3de38c5faf5a3040db72466ed2e0820c2d only
