### ISSUE TITLE
50 shades of icon

### ISSUE THREAD

**Issue by ChristophWurst** [nextcloud/mail#8730]
### Steps to reproduce

1. Open the app
2. Configure an account

### Expected behavior

Consistent icon color

### Actual behavior

Look at the various icons

![image](https://github.com/nextcloud/mail/assets/1374172/03d9d0df-069e-4639-8043-0b23327006d9)

* Account error icon is black
* Mailbox icons are light
* Action icons are black
* Big icon on the right is very light

### PHP engine version

None

### Web server

None

### Database

None

### Additional info

@jancborchardt @marcoambrosini @nimishavijay what is the preferred color for icons and can we add the specs to https://docs.nextcloud.com/server/latest/developer_manual/design/foundations.html#icons? :)

**Comment by nimishavijay** [comment]
All icons should either be `--color-main-text` in full opacity (navigation, action menu icons) or `--color-text-maxcontrast` in full opacity (emptycontent icon). There may be some special cases where the icon is `--color-primary-element`, but those are really one-offs :) Will add it to the documentation, ccing @nextcloud/designers

**Comment by GretaD** [comment]
> All icons should either be `--color-main-text` in full opacity (navigation, action menu icons) or `--color-text-maxcontrast` in full opacity (emptycontent icon). 

How can we tell which cases are these ones? Anna Aurora would like to finish this ticket but im not sure which color/opacity she should follow for mail.

For example, left sidebar, all action menus, empty content, and/or actions on thread envelope, should they look all the same, if yes, which color/opacity?

**Comment by nimishavijay** [comment]
> How can we tell which cases are these ones? Anna Aurora would like to finish this ticket but im not sure which color/opacity she should follow for mail.
>
> For example, left sidebar, all action menus, empty content, and/or actions on thread envelope, should they look all the same, if yes, which color/opacity?

In most cases the icon should be `--color-main-text` actually. For the EmptyContent component it should be `--color-text-maxcontrast`, so wherever there are big icons they would be `--color-text-maxcontrast` as well. When in doubt, use `--color-main-text`.

**Comment by auroraanna** [comment]
What about icons on primary or secondary buttons though? Those buttons don't just have a white background.

**Comment by auroraanna** [comment]
We assumed that the secondary and primary button colors were fine since they weren't changed for mail specifically.
