### ISSUE TITLE
Mailto handler: thread doesn't exist or has been deleted

### ISSUE THREAD

**Issue by ChristophWurst** [nextcloud/mail#8733]
### Steps to reproduce

1. Open the app
2. Set up an account
3. Configure the mailto handler
4. Click on a mailto handler

### Expected behavior

Mailto is handled nicely

### Actual behavior

![image](https://github.com/nextcloud/mail/assets/1374172/4cd8fdd7-f5c8-4112-877d-dd0150a42b1c)

### PHP engine version

None

### Web server

None

### Database

None

### Additional info

Might be related to https://github.com/nextcloud/mail/pull/6863. The mailto feature worked nicely ~2w ago.

**Comment by ChristophWurst** [comment]
cc @GretaD

**Comment by GretaD** [comment]
How it used to look before? I tested it on stable3.3 and 3.2 and same errror is shown.

**Comment by st3iny** [comment]
AFAIK, the composer should open.

**Comment by GretaD** [comment]
> AFAIK, the composer should open.

the composer opens, but in the background the "not found" error is shown

**Comment by GretaD** [comment]
![Screenshot from 2023-08-14 12-47-50](https://github.com/nextcloud/mail/assets/12728974/6393468a-7256-470f-b52b-c7679eebece1)

**Comment by st3iny** [comment]
Ahh right. Then it's probably about not showing the error. The default page should be shown (which was added by the linked PR).

![grafik](https://github.com/nextcloud/mail/assets/1479486/6a47fecc-9f5f-4f95-8895-9948bc83f877)

**Comment by ChristophWurst** [comment]
Correct. It's about what happens behind the composer modal.
