### ISSUE TITLE
Lost update between last draft and sending a message

### ISSUE THREAD

**Issue by ChristophWurst** [nextcloud/mail#8734]
### Steps to reproduce

1. Open the app
2. Set up an account
3. Start composing a new message, pick the sender and add some body text
4. Wait until the draft is saved
5. Enter some more text into the body and click *Send* quickly

### Expected behavior

The last body modifications are saved and go into the message I send

### Actual behavior

My last modifications are lost

### Mail app version

3.4.0-beta.2

### PHP engine version

None

### Web server

None

### Database

None

**Comment by ChristophWurst** [comment]
cc @hamza221 because this could be related to https://github.com/nextcloud/mail/pull/8469

**Comment by hamza221** [comment]
> cc @hamza221 because this could be related to https://github.com/nextcloud/mail/pull/8469



Most probably, I'll give it a look
