### ISSUE TITLE
Active mailbox name barely readable

### ISSUE THREAD

**Issue by ChristophWurst** [nextcloud/mail#8735]
### Steps to reproduce

1. Open the app
2. Set up an account
3. Open a mailbox

### Expected behavior

I can read the mailbox name

### Actual behavior

![image](https://github.com/nextcloud/mail/assets/1374172/631a17e3-afdc-487f-a503-d103369c2bab)

### Mail app version

v3.4.0-beta.2

### PHP engine version

None

### Web server

None

### Database

None

**Comment by ChristophWurst** [comment]
according to @juliushaertl this happens on server 27.1 that ships a nc/vue that has leaking styles

**Comment by juliushaertl** [comment]
Reference upstream ticket https://github.com/nextcloud-libraries/nextcloud-vue/issues/4418

**Comment by auroraanna** [comment]
> according to @juliushaertl this happens on server 27.1 that ships a nc/vue that has leaking styles

What are leaking styles?

@auroraanna is on server 28.0.0 dev and couldn't reproduce this with the same background.

**Comment by ChristophWurst** [comment]
> > according to @juliushaertl this happens on server 27.1 that ships a nc/vue that has leaking styles
> 
> What are leaking styles?
> 
> @auroraanna is on server 28.0.0 dev and couldn't reproduce this with the same background.

Another app ships its own version of nc/vue. The styles injected into the head of the page cause a conflict, because they are not scoped to each nc/vue version.

This seems to be fine now.
