### ISSUE TITLE
Error connecting to mail server. Please help

### ISSUE THREAD

**Issue by freemanwu-tw** [nextcloud/mail#874]
### Steps to reproduce
1. Installed mail app
2. Input account informations
3. Click connect

### Expected behaviour
Shoud connect.
Mail worked fine with thunderbird.

### Actual behaviour
Can not connect.
Can not see any log on mail server, no app (horde) log file produced.
Tried all: None, SSL/TLS, STARTTLS
Help needed, Thanks a lot!
New to NextCloud, forgive me if there're any stupid mistake!

### Mail app
**Mail app version:** 0.7.10
**Mailserver or service:** iRedMail 0.9.8
**Number of accounts:** 10

### Server configuration
**Operating system**: CentOS
**Web server:** Apache 2.4.6
**Database:** MariaDB 5.5.56
**PHP version:** 7.2.2
**Version:** 13.0.1
**Updated from an older version or fresh install:** fresh install
**List of activated apps:**
Enabled:
  - activity: 2.6.1
  - admin_audit: 1.3.0
  - announcementcenter: 3.2.1
  - apporder: 0.4.1
  - bruteforcesettings: 1.0.3
  - calendar: 1.6.1
  - circles: 0.13.6
  - comments: 1.3.0
  - contacts: 2.1.3
  - dav: 1.4.6
  - deck: 0.3.1
  - drawio: 0.8.9
  - external: 3.0.2
  - federatedfilesharing: 1.3.1
  - federation: 1.3.0
  - files: 1.8.0
  - files_accesscontrol: 1.3.0
  - files_automatedtagging: 1.3.0
  - files_pdfviewer: 1.2.1
  - files_retention: 1.2.0
  - files_sharing: 1.5.0
  - files_texteditor: 2.5.1
  - files_trashbin: 1.3.0
  - files_versions: 1.6.0
  - files_videoplayer: 1.2.0
  - firstrunwizard: 2.2.1
  - gallery: 18.0.0
  - groupfolders: 1.2.0
  - logreader: 2.0.0
  - lookup_server_connector: 1.1.0
  - mail: 0.7.10
  - nextcloud_announcements: 1.2.0
  - notifications: 2.1.2
  - oauth2: 1.1.0
  - onlyoffice: 1.3.0
  - password_policy: 1.3.0
  - provisioning_api: 1.3.0
  - serverinfo: 1.3.0
  - sharebymail: 1.3.0
  - socialsharing_email: 1.0.3
  - socialsharing_facebook: 1.0.2
  - socialsharing_googleplus: 1.0.2
  - socialsharing_twitter: 1.0.2
  - spreed: 3.1.0
  - survey_client: 1.1.0
  - systemtags: 1.3.0
  - tasks: 0.9.6
  - theming: 1.4.1
  - twofactor_backupcodes: 1.2.3
  - updatenotification: 1.3.0
  - workflowengine: 1.3.0
Disabled:
  - encryption
  - files_external
  - richdocuments
  - user_external
  - user_ldap

**The content of config/config.php:**
{
    "system": {
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "10.0.100.64",
            "share.thewus.tw",
            "share.cxt.tw"
        ],
        "trusted_proxies": "***REMOVED SENSITIVE VALUE***",
        "datadirectory": "***REMOVED SENSITIVE VALUE***",
        "overwrite.cli.url": "http:\/\/10.0.100.64",
        "dbtype": "mysql",
        "version": "13.0.1.1",
        "dbname": "***REMOVED SENSITIVE VALUE***",
        "dbhost": "***REMOVED SENSITIVE VALUE***",
        "dbport": "",
        "dbtableprefix": "oc_",
        "mysql.utf8mb4": true,
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "defaultapp": "apporder",
        "app.mail.imap.timeout": 120,
        "app.mail.smtp.timeout": 30,
        "installed": true,
        "maintenance": false,
        "memcache.local": "\\OC\\Memcache\\APCu",
        "theme": "",
        "loglevel": 2,
        "app.mail.imaplog.enabled": true,
        "app.mail.smtplog.enabled": true,
        "app.mail.transport": "php-mail"
    }
}

##### Server log (data/nextcloud.log)
OCA\Mail\Exception\ClientException: 建立帳號失敗：Error connecting to mail server.
[internal function] OCA\Mail\Controller\AccountsController->create('Freeman Wu', 'freeman@thewus....', 'PASSWORD', 'mail.thewus.tw', 143, 'tls', 'freeman@thewus....', 'PASSWORD', 'mail.thewus.tw', 587, 'tls', 'freeman@thewus....', 'PASSWORD', false)
/var/www/html/nextcloud/lib/private/AppFramework/Http/Dispatcher.php - line 161: call_user_func_array(Array, Array)
/var/www/html/nextcloud/lib/private/AppFramework/Http/Dispatcher.php - line 91: OC\AppFramework\Http\Dispatcher->executeController(Object(OCA\Mail\Controller\AccountsController), 'create')
/var/www/html/nextcloud/lib/private/AppFramework/App.php - line 115: OC\AppFramework\Http\Dispatcher->dispatch(Object(OCA\Mail\Controller\AccountsController), 'create')
/var/www/html/nextcloud/lib/private/AppFramework/Routing/RouteActionHandler.php - line 47: OC\AppFramework\App main('OCA\\Mail\\Contro...', 'create', Object(OC\AppFramework\DependencyInjection\DIContainer), Array)
[internal function] OC\AppFramework\Routing\RouteActionHandler->__invoke(Array)
/var/www/html/nextcloud/lib/private/Route/Router.php - line 297: call_user_func(Object(OC\AppFramework\Routing\RouteActionHandler), Array)
/var/www/html/nextcloud/lib/base.php - line 998: OC\Route\Router->match('/apps/mail/api/...')
/var/www/html/nextcloud/index.php - line 37: OC handleRequest()
{main}

**Comment by freemanwu-tw** [comment]
It's SELinux Problem, solved. thanks at all!

**Comment by freemanwu-tw** [comment]
setsebool -P httpd_can_network_connect on
setsebool -P httpd_can_sendmail on

**Comment by chenyongwei** [comment]
Perfect!!! Thanks a lot! @freemanwu-tw 
I put almost 2 days to resolve it.
