### ISSUE TITLE
Suggest recipients from address book, not from user base

### ISSUE THREAD

**Issue by rasos** [nextcloud/mail#875]
We run a nextcloud server for several communities. The actual behaviour is a privacy issue and may force us to stop offering the service when the EU GDPR is applicable after 25th of May 2018.

### Steps to reproduce
1. Create an E-Mail message
2. Enter a few letters for the recipient

### Expected behaviour
Show recipients only from the user's address book he/she has access to (if address book app is available for that user), else show no proposal for a recipient. This restriction should be configurable as an option in the config.php for sites, which offers a nextcloud service outside organisational boundaries.

### Actual behaviour
Matching names from the total user base is shown. Any user can read any E-Mail address. 

### Mail app

**Mail app version:** 0.7.10

**Mailserver or service:** dovecot / postfix

**Number of accounts:** several hundreds

### Server configuration

**Version:** nextcloud 13

We have hidden nextclouds user search button with a custom CSS: 
```
#contactsmenu {
 	display: none;
}
```

**Comment by ChristophWurst** [comment]
Fixed by https://github.com/nextcloud/mail/pull/856, dup of https://github.com/nextcloud/mail/issues/848
