### ISSUE TITLE
Modal closes automatically

### ISSUE THREAD

**Issue by kesselb** [nextcloud/mail#8753]
### Steps to reproduce

1. Open Mail
2. Pick a message
3. Click move message (e.g. in the menu envelope)
4. Wait a few seconds
5. 😯

### Expected behavior

Let me choose the mailbox without having to hurry up ;)

### Actual behavior

[Screencast from 2023-08-15 12-41-11.webm](https://github.com/nextcloud/mail/assets/3902676/e57ea6aa-38a0-4a9b-a23b-40df776d5a0a)

### Mail app version

https://github.com/nextcloud/mail/commit/49b34a6c78efe446979ab41c899a4b3c3877e11d

### PHP engine version

None

### Web server

None

### Database

None

**Comment by JohannesGGE** [comment]
I reverted the snooze changes and could reproduce the bug, so this shouldn't be a regression from snooze.
I tried to understand why the modal behave like this, can't relate. The component states `showMoveModal` still seems to be set to true after the the modal disappears.

**Comment by ChristophWurst** [comment]
@GretaD could you look into this please?
