### ISSUE TITLE
3.4.0-beta.2 snooze does not work

### ISSUE THREAD

**Issue by jakobroehrl** [nextcloud/mail#8766]
### Steps to reproduce

1. set snooze (which time does not matter)
2. Could not snooze thread pops up
I have a IMAP account on a hosted mail server
NC 27.0.2

### Expected behavior

mail should be snoozed

### Actual behavior

Error message
Mails is still there

### Mail app version

3.4.0-beta.2

### PHP engine version

None

### Web server

None

### Database

None

**Comment by GretaD** [comment]
cc @JohannesGGE

**Comment by JohannesGGE** [comment]
@jakobroehrl Did you set a snooze mailbox in the account settings? Currently this need to be done manually.
Otherwise, can you check the logs and post them?

**Comment by jakobroehrl** [comment]
Thanks for your support. 
I added a new folder and set this as snooze folder. Now the mails are moved to this folder. :)
