### ISSUE TITLE
Switching Writing mode kills account settings window

### ISSUE THREAD

**Issue by supercoil** [nextcloud/mail#8787]
### Steps to reproduce

1. Open Account settings
2. Switch Writing mode from Plain text to Rich text or vice versa
3. Settings window goes blank

### Expected behavior

Settings remain visible after switching Writing mode

### Actual behavior

Account settings window goes blank and I have to close and re-open it to see the settings

### Mail app version

3.2.7

### Operating system

Ubuntu

### PHP engine version

PHP 8.2

### Web server

Apache (supported)

### Database

MariaDB

**Comment by supercoil** [comment]
Issue remains. When I open the settings window webconsole shows the following error:
`[ERROR] mail: could not find CKEditor translations for "en-GB" 
Object { app: "mail", uid: "xxxxx", level: 0, error: Error }
ConsoleLogger.js:59:18`
And this warning:
`The 'ListStyle' plugin is obsolete. Use 'ListProperties' instead. 
Read more: https://ckeditor.com/docs/ckeditor5/latest/support/error-codes.html#error-The 'ListStyle' plugin is obsolete. Use 'ListProperties' instead. ckeditorerror.js:119:16`

But nothing when I switch rich/plain

**Comment by GretaD** [comment]
Which browser are you using? Looks like its an issue with Chrome. Can you please try to change your browser languge to US english, just to exclude this option? Try some other non-chrome/mium broswer, like FF

**Comment by supercoil** [comment]
I'm actually using Firefox. Changing browser language doesn't do anything. Changing the language to en-US in my Nextcloud account preferences gets rid of the error message, but the problem persists.

**Comment by GretaD** [comment]
I see, ok, can you please send us your nextcloud logs then, remove the sensitive data and try to send only the ones that were generated when you click account settings and rich/plain

**Comment by supercoil** [comment]
Here's the relevant part of my nextcloud log:
[nextcloud.log](https://github.com/nextcloud/mail/files/12409281/nextcloud.log)

**Comment by supercoil** [comment]
Just updated to mail 3.3.0 and this has fixed the issue
