### ISSUE TITLE
Less misleading wording on "Delete thread"/"Delete message" button

### ISSUE THREAD

**Issue by auroraanna** [nextcloud/mail#8788]
### Is your feature request related to a problem? Please describe.

The "Delete thread" and "Delete message" buttons don't actually delete the message or thread as far as the user knows. Instead, the message or thread is moved to the Trash folder (@auroraanna is wondering if the Trash folder is not mandatory, which would make this argument fall apart a bit). This essentially just makes it a shortcut for the "Move thread/message" button.

This might make the user think that the message or thread is actually deleted, which might e.g. cause them to never click the button, because they are afraid that the message will be deleted, clogging up their Inbox.

When you click the button on a message or thread that is already inside of the Trash folder, the message is actually deleted. However, since the user might have been previously made to believe, that the delete button doesn't actually delete anything, the user might click the delete button, expecting something different than it does.

I think most people will infer that when the delete button is used inside of the Trash folder, the message or thread is deleted, …

### Describe the solution you'd like

…but it would be nice to make it more clear and explicit what is going to happen.

I suggest, changing the text of the "delete" button to "Trash message/thread" for threads and messages in every but the Trash folder. The button should stay the same in the Trash folder.

### Describe alternatives you've considered

Changing the text of the "delete" button to "Move message/thread to Trash" for threads and messages in every but the Trash folder. The button should stay the same in the Trash folder.

**Comment by GretaD** [comment]
cc @jancborchardt  :)

**Comment by jancborchardt** [comment]
"Delete" including the trash can icon is the most common wording across mail apps like Gmail, Outlook, K-9, Thunderbird and Apple Mail as well. It would be more confusing if we changed from that. Hope that explains it. :)
