### ISSUE TITLE
Sending mail error: already authenticated

### ISSUE THREAD

**Issue by laurentiu2** [nextcloud/mail#880]
### Steps to reproduce
1. Reply to a mail
2.
3.

### Expected behaviour
The reply should be sent via SMTP

### Actual behaviour
Server error message appears. The message is not sent, just saved as draft.
This is something relatively new, it appeared randomly in the last week or so. Nothing unusual happened, not even an update to server. No other modification in settings was made, I am using unified inbox.
Everything else is working: incoming mails, notifications, saving attachments to Files, etc.

## Server configuration detail

**Operating system:** Linux 4.4.0-119-generic #143-Ubuntu SMP Mon Apr 2 16:08:24 UTC 2018 x86_64

**Webserver:** Apache/2.4.18 (Ubuntu) (apache2handler)

**Database:** mysql 5.7.22

**PHP version:** 7.0.28-0ubuntu0.16.04.1
Modules loaded: Core, date, libxml, openssl, pcre, zlib, filter, hash, Reflection, SPL, session, standard, apache2handler, mysqlnd, PDO, xml, bz2, calendar, ctype, curl, dom, mbstring, fileinfo, ftp, gd, gettext, iconv, imagick, imap, intl, json, exif, mcrypt, mysqli, pdo_mysql, Phar, posix, readline, redis, shmop, SimpleXML, sockets, sysvmsg, sysvsem, sysvshm, tokenizer, wddx, xmlreader, xmlwriter, xsl, zip, Zend OPcache

**Nextcloud version:** 13.0.1 - 13.0.1.1

**Updated from an older Nextcloud/ownCloud or fresh install:** updated long ago from NC 12 😃 

**Where did you install Nextcloud from:**  zip

<details><summary>Signing status</summary>

Array
</details>

<details><summary>List of activated apps</summary>

```
Enabled:
 - activity: 2.6.1
 - bruteforcesettings: 1.0.3
 - calendar: 1.6.1
 - comments: 1.3.0
 - dav: 1.4.6
 - encryption: 2.0.0
 - external: 3.0.2
 - federatedfilesharing: 1.3.1
 - federation: 1.3.0
 - files: 1.8.0
 - files_external: 1.4.1
 - files_pdfviewer: 1.2.1
 - files_sharing: 1.5.0
 - files_texteditor: 2.5.1
 - files_trashbin: 1.3.0
 - files_versions: 1.6.0
 - files_videoplayer: 1.2.0
 - firstrunwizard: 2.2.1
 - gallery: 18.0.0
 - issuetemplate: 0.3.0
 - logreader: 2.0.0
 - lookup_server_connector: 1.1.0
 - mail: 0.7.10
 - metadata: 0.6.0
 - nextcloud_announcements: 1.2.0
 - notifications: 2.1.2
 - oauth2: 1.1.0
 - passman: 2.1.4
 - password_policy: 1.3.0
 - provisioning_api: 1.3.0
 - quota_warning: 1.2.0
 - ransomware_protection: 1.1.0
 - serverinfo: 1.3.0
 - sharebymail: 1.3.0
 - survey_client: 1.1.0
 - systemtags: 1.3.0
 - tasks: 0.9.6
 - theming: 1.4.1
 - twofactor_backupcodes: 1.2.3
 - updatenotification: 1.3.0
 - workflowengine: 1.3.0
Disabled:
 - admin_audit
 - contacts
 - files_clipboard
 - user_external
 - user_ldap

```
</details>

<details><summary>Configuration (config/config.php)</summary>

```
{
    "passwordsalt": "***REMOVED SENSITIVE VALUE***",
    "secret": "***REMOVED SENSITIVE VALUE***",
    "trusted_domains": [
        "*"
    ],
    "datadirectory": "***REMOVED SENSITIVE VALUE***",
    "overwrite.cli.url": "http:\/\/localhost",
    "dbtype": "mysql",
    "version": "13.0.1.1",
    "dbname": "***REMOVED SENSITIVE VALUE***",
    "dbhost": "***REMOVED SENSITIVE VALUE***",
    "dbport": "",
    "dbtableprefix": "oc_",
    "mysql.utf8mb4": true,
    "dbuser": "***REMOVED SENSITIVE VALUE***",
    "dbpassword": "***REMOVED SENSITIVE VALUE***",
    "installed": true,
    "instanceid": "***REMOVED SENSITIVE VALUE***",
    "memcache.local": "\\OC\\Memcache\\Redis",
    "redis": {
        "dbindex": "0",
        "host": "***REMOVED SENSITIVE VALUE***",
        "port": "6379",
        "timeout": "1.5"
    },
    "maintenance": false,
    "theme": "",
    "loglevel": 0,
    "updater.release.channel": "stable",
    "lost_password_link": "disable",
    "mail_smtpmode": "smtp",
    "mail_smtpauthtype": "LOGIN",
    "mail_from_address": "***REMOVED SENSITIVE VALUE***",
    "mail_domain": "***REMOVED SENSITIVE VALUE***",
    "mail_smtpauth": 1,
    "mail_smtphost": "***REMOVED SENSITIVE VALUE***",
    "mail_smtpport": "465",
    "mail_smtpname": "***REMOVED SENSITIVE VALUE***",
    "mail_smtppassword": "***REMOVED SENSITIVE VALUE***",
    "mail_smtpsecure": "ssl"
}
```
</details>

**Are you using external storage, if yes which one:** local/smb/sftp/... no

**Are you using encryption:** yes

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/... no

## Client configuration

**Browser:** Mozilla/5.0 (Macintosh; Intel Mac OS X 10.13; rv:59.0) Gecko/20100101 Firefox/59.0

**Operating system:** high sierra

## Logs

<details><summary>Browser log</summary>

```
[Wed Apr 25 06:25:02.582398 2018] [ssl:warn] [pid 28235] AH01909: 2a01:4f8:c0c:37df::2:443:0 server certificate does NOT include an ID which matches the server name
[Wed Apr 25 06:25:02.582978 2018] [mpm_prefork:notice] [pid 28235] AH00163: Apache/2.4.18 (Ubuntu) OpenSSL/1.0.2g configured -- resuming normal operations
[Wed Apr 25 06:25:02.582988 2018] [core:notice] [pid 28235] AH00094: Command line: '/usr/sbin/apache2'
```
</details>

<details><summary>Nextcloud log</summary>

```
Error	mail	Horde_Mime_Exception: already authenticated

    /var/www/nextcloud/apps/mail/vendor/pear-pear.horde.org/Horde_Mime/Horde/Mime/Mail.php - line 479: Horde_Mime_Part->send('mimi coman <com...', Object(Horde_Mime_Headers), Object(Horde_Mail_Transport_Smtphorde))
    /var/www/nextcloud/apps/mail/lib/Account.php - line 214: Horde_Mime_Mail->send(Object(Horde_Mail_Transport_Smtphorde), false, false)
    /var/www/nextcloud/apps/mail/lib/Service/MailTransmission.php - line 106: OCA\Mail\Account->sendMessage(Object(OCA\Mail\Model\ReplyMessage), Object(Horde_Mail_Transport_Smtphorde), 3693)
    /var/www/nextcloud/apps/mail/lib/Controller/AccountsController.php - line 260: OCA\Mail\Service\MailTransmission->sendMessage('offrc', Object(OCA\Mail\Model\NewMessageData), Object(OCA\Mail\Model\RepliedMessageData), NULL, 3693)
    [internal function] OCA\Mail\Controller\AccountsController->send(6, 'SU5CT1g=', NULL, 'Va rog sa facet...', '"mimi coman" <c...', '', '', 3693, 1691, NULL, '')
    /var/www/nextcloud/lib/private/AppFramework/Http/Dispatcher.php - line 161: call_user_func_array(Array, Array)
    /var/www/nextcloud/lib/private/AppFramework/Http/Dispatcher.php - line 91: OC\AppFramework\Http\Dispatcher->executeController(Object(OCA\Mail\Controller\AccountsController), 'send')
    /var/www/nextcloud/lib/private/AppFramework/App.php - line 115: OC\AppFramework\Http\Dispatcher->dispatch(Object(OCA\Mail\Controller\AccountsController), 'send')
    /var/www/nextcloud/lib/private/AppFramework/Routing/RouteActionHandler.php - line 47: OC\AppFramework\App main('OCA\\Mail\\Contro...', 'send', Object(OC\AppFramework\DependencyInjection\DIContainer), Array)
    [internal function] OC\AppFramework\Routing\RouteActionHandler->__invoke(Array)
    /var/www/nextcloud/lib/private/Route/Router.php - line 297: call_user_func(Object(OC\AppFramework\Routing\RouteActionHandler), Array)
    /var/www/nextcloud/lib/base.php - line 998: OC\Route\Router->match('/apps/mail/api/...')
    /var/www/nextcloud/index.php - line 37: OC handleRequest()
    {main}

	2018-04-25T18:21:16+0300
Error	mail	Sending mail failed: already authenticated	2018-04-25T18:21:16+0300
```
</details>

**Comment by ChristophWurst** [comment]
> Horde_Mime_Exception: already authenticated

That is … weird.

**Comment by ChristophWurst** [comment]
The Nextcloud mail app offers an extensive logging system to make it easier identifying and tracking down bugs. Please enable [debug mode](https://docs.nextcloud.com/server/13/developer_manual/general/devenv.html#enabling-debug-mode) and set the log [level to debug](https://docs.nextcloud.com/server/13/admin_manual/configuration_server/logging_configuration.html) in your admin settings. Then, try to reproduce your issue and take another look at `data/nextcloud.log`, `data/horde_imap.log` and `data/horde_smtp.log`.

**Comment by laurentiu2** [comment]
Hi,

here are the logs:


[logs_errors_mail.txt](https://github.com/nextcloud/mail/files/1966722/logs_errors_mail.txt)

**Comment by laurentiu2** [comment]
For no obvious reason, after deleting the second email address, it works again. After re-enabling the second email address it still works.. Hopefully for a long time :)
If you want to keep investigating, maybe you'll find the problem.. but for me it can be closed.
Thanks.
