### ISSUE TITLE
Marking several mails with Ctrl opens a new tap for each mail

### ISSUE THREAD

**Issue by lp-SRO** [nextcloud/mail#8803]
### Steps to reproduce

1.
2.
3.

### Expected behavior

A new TAP is opened when marking each email with Ctrl in the browser. I would rather expect that you have the possibility to tick the mails and then decide what to do with the marked mails.

And by the way, why can't I move the marked mails all at once?

### Actual behavior

All marked mails cannot be moved, and there is no other way to mark multiple mails than using the Ctrl key, which always creates a new browser tab.

### Mail app version

3.3.0

### PHP engine version

None

### Web server

None

### Database

None

**Comment by GretaD** [comment]
this is fixed here: https://github.com/nextcloud/mail/pull/8798 
we just need to get the backport merged
