### ISSUE TITLE
Full-width mail list 

### ISSUE THREAD

**Issue by marcoambrosini** [nextcloud/mail#8811]
## Feature Request

As a Nextcloud Mail user I may prefer to see as much information about a messages/thread as possible before I open it. The current view, for example, shows only a small part of the subject and preview text:

<img width="354" alt="Screenshot 2023-08-25 at 14 37 17" src="https://github.com/nextcloud/mail/assets/26852655/3107c7e5-7985-48c3-b8f0-1a09b3bcf5e2">

## Describe the solution you'd like

Allow me to switch to a full-width message/thread list. In other words, the three column design (nav + list + content) becomes two column: nav + list or nav + content. The user will see the list. When they navigate to a message/thread, the content shows.

To switch between the views we need a three way button or actions menu. This button is places next to the button for advanced search.

## References

This is the trend in some of the major email apps as UX people realize that the idea of multitasking was a bit overrated.

| Product | Screenshot |
|--------|--------|
| Hey  | <img width="877" alt="Screenshot 2023-08-25 at 15 29 18" src="https://github.com/nextcloud/mail/assets/26852655/e4f05687-1667-4b8f-868a-f430f33c69f9"> | 
| Gmail | <img width="1129" alt="Screenshot 2023-08-25 at 15 22 46" src="https://github.com/nextcloud/mail/assets/26852655/76767fe0-24ca-4b2c-ac77-53ad86a05e15"> |
| Spark Mail | <img width="1331" alt="Screenshot 2023-08-25 at 15 25 36" src="https://github.com/nextcloud/mail/assets/26852655/4b849d49-b7b5-433c-bf85-89990686b80b"> | 

## Implementation

Right now Mail uses the following structure:

```html
<NcContent>
  <Navigation />
  <AppContent>
    <div slot="list">
      <SearchMessages />
      <AppContentList>
        <Mailbox />
      </AppContentList>
    </div>
    <AppContentDetails />
  </AppContent>
</NcContent>
```

*Ideally*, we can keep the structure as-is, but enhance AppContent and ListItem to work with one or two columns:

<table>
<tr>
<th>List + content</th>
<th>List only</th>
<th>Content only</th>
</tr>
<tr>
<td>

```html
<NcContent>
  <Navigation />
  <AppContent layout="vertical-split">
    <div slot="list">
      <SearchMessages />
      <AppContentList>
        <ListItem layout="compact" />
      </AppContentList>
    </div>
    <AppContentDetails />
  </AppContent>
</NcContent>
```

</td>
<td>

```html
<NcContent>
  <Navigation />
  <AppContent layout="list">
    <div slot="list">
      <SearchMessages />
      <AppContentList>
        <ListItem layout="wide" />
      </AppContentList>
    </div>
    <AppContentDetails /><!-- not rendered -->
  </AppContent>
</NcContent>
```

</td>
<td>

```html
<NcContent>
  <Navigation />
  <AppContent layout="content">
    <div slot="list"><!-- not rendered -->
      <SearchMessages />
      <AppContentList>
        <ListItem layout="wide" />
      </AppContentList>
    </div>
    <AppContentDetails />
  </AppContent>
</NcContent>
```

</td>
</tr>
</table>

Long code snipped short, we don't control the rendering, we just tell  AppContent and ListItem the layout to render.

This gives us the following advantages
1) We do not have to rip apart the ListItem with deep selectors or write a completely new component.
2) The new layouts streamlines mobile view with desktop view.
3) Other apps can use this too, e.g. to offer a better mobile view or a layout switch, if desired.
4) It will be easy to implement https://github.com/nextcloud/mail/issues/8309

Challenges
* The table(-like) structure of AppContentList and ListItem for the list-only mode and potential wrapping components between (currently Mailbox, EnvelopeList and transition)

**Comment by dugite-code** [comment]
I used to do fix this with CSS forcing a horizontal layout. Unfortunately this no longer really works well. That said this could be added to the app as the splitpanes supports changing the pane orientation out of the box: https://antoniandre.github.io/splitpanes/#change-direction

**Comment by marcoambrosini** [comment]
Another argument for having this view and making it default is how tall emails have actually gotten over time. My 16-inch laptop fits only a handful. The situation worsens if we use tags. On top of the usability issue, I think this elements just look ugly and disproportionate.

With all that space taken up, I think it's unacceptable that we're truncating subjects over 4-5 words

If we adopt full-width mail elements, we'll be able to use 1 or 2 line tops elements and fit everything in there without wrapping 

ref: current state 
<img width="398" alt="Screenshot 2023-08-30 at 16 40 52" src="https://github.com/nextcloud/mail/assets/26852655/f1bb98de-0df4-4eae-a504-a500a99dfd8a">

**Comment by HLFH** [comment]
That'd be awesome. That would make life easier for people migrating from Google Workspace to Nextcloud, and being too much used to the Gmail UI.

**Comment by GretaD** [comment]
@nextcloud/designers I would like to start working on this asap, please add it for review on your backlog and please send me the mockups/insights when you have them :)

**Comment by nimishavijay** [comment]
So we did a first review of this and here's what we have so far :) 

![image](https://github.com/nextcloud/mail/assets/52440189/ce2ebe0b-3dc1-464a-a57a-d1f6ee086c3c)

Things we know for sure:
- [ ] Full width inbox, clicking on a row opens the message in a full content view
- [ ] Each row will have: read indicator, avatar, sender, subject, body, tags, date (or whatever is there on the right side, for example the "Message could not be sent" indicator)
- [ ] Sender avatar in a smaller size (32px), and next column is the sender 
- [ ] Next column has the subject and body of the letter, separated by a middle dot symbol
- [ ] The color and formatting of sender, subject, body and date/right side content remains the same as reading pane view  
- [ ] Hover feedback can show the checkmark, which allows for easier selection
- [ ] Switching between the 2 views is through a button on the top 
- [ ] On mobile the user shouldn't be allowed to switch between the 2 views

Things that are still up for discussion:
- [ ] Position of unread indicator: Unread indicator can be either on the left like in the screenshot, or on the right side, on the left of the date
- [ ] Actions in the space on top: We decided we don't want a full width search bar, which leaves a lot of space in the top bar which can be used, but it's still a question as to what to fill that space with
- [ ] Placement of the search bar: We are not sure if the search bar is on the left like in the screenshot or on the right
- [ ] placement of the checkmark on hover: We can replace the unread indicator with a checkmark like in the screenshot, or alternatively it could also be like an overlay on the avatar

Will share more info as we confirm, but what do you think about the first version? :) Also pinging @jancborchardt and @szaimen for additional feedback :)

**Comment by GretaD** [comment]
Nice, thanks a lot @nimishavijay, i will start looking into it asap, please if you can send me a mockup that fits the description, would be nice, but this is not a blocker :)

**Comment by jancborchardt** [comment]
> Position of unread indicator: Unread indicator can be either on the left like in the screenshot, or on the right side, on the left of the date

Maybe on the left of the date is nicer so it’s more consistent with the other narrower list view.

> Actions in the space on top: We decided we don't want a full width search bar, which leaves a lot of space in the top bar which can be used, but it's still a question as to what to fill that space with

The view toggle can actually go into the global settings in the bottom left (modal), so no icon necessary for that here. Also because we have no space for that in the other views.

> Placement of the search bar: We are not sure if the search bar is on the left like in the screenshot or on the right

Left is best as the in-app search tends to be to the left in other views.

> placement of the checkmark on hover: We can replace the unread indicator with a checkmark like in the screenshot, or alternatively it could also be like an overlay on the avatar

Going back to point 1, if the unread indicator is on the right then we can replace the avatar with checkmark on hover/focus.

**Comment by ChristophWurst** [comment]
@nimishavijay right now desktop view has a *navigation toggle* allowing users to hide/show the navigation sidebar. It is always visible.
On mobile the users see a navigation toggle when the message list is visible. The toggle disappears when a message is shown. A new toggle is added: the back button.

![image](https://github.com/nextcloud/mail/assets/1374172/456e9721-bedd-4ccf-9e52-c0e5d7888d1a)

When we are in the new full list view, click a message and land in the message view, we would need two buttons on desktop: toggle navigation and *back*. Is that ok design-wise?

**Comment by nimishavijay** [comment]
It is rather unconventional to have the back button and the menu button on the same row (I really couldn't find any other apps where we do that) but since the navigation contains the "New message" item as well as the different folders I'd say it's more important to show it. So yes it would be okay to show the navigation toggle as the leftmost item. next to it there can be the back button. 

ccing @nextcloud/designers for more opinions

**Comment by jancborchardt** [comment]
@ChristophWurst @GretaD this is only about the new view where you either have the list or the mail open, right? Can we have a screenshot of the current state when a mail is opened in detail view?
I would tend to place the back button either right next to the menu button or left next to the title of the mail, but would have to see how it looks like currently.

**Comment by GretaD** [comment]
> @ChristophWurst @GretaD this is only about the new view where you either have the list or the mail open, right? Can we have a screenshot of the current state when a mail is opened in detail view? 

![Screenshot from 2024-02-28 15-03-21](https://github.com/nextcloud/mail/assets/12728974/83932e3f-e0f2-49c4-a5e3-9f4b37bd100c)

**Comment by Mer0me** [comment]
Is list view broken ? Since the last update of the Mail app (3.7.8 on NC 29.0.5) (I think), the list view is shrinked to the left

List view :
![image](https://github.com/user-attachments/assets/7c02b98b-4e9e-463b-b43a-f22343ee458e)

Vertical split :
![image](https://github.com/user-attachments/assets/7f6545eb-3150-4d18-81c0-17769ab32cb9)

**Comment by ChristophWurst** [comment]
@Mer0me can confirm. Would you mind creating a new ticket? @GVodyanov will look into this

**Comment by Mer0me** [comment]
Sure

**Comment by Mer0me** [comment]
https://github.com/nextcloud/mail/issues/10086
