### ISSUE TITLE
Inbox subfolder organizer

### ISSUE THREAD

**Issue by BiglifeMatt** [nextcloud/mail#8812]
### Describe the solution you'd like

It would be nice to have a better view to organize subfolders.  The sidebar should also reflect a nesting tree model to represent the folders.  It appears that everything is just in one singular line even when it belongs under another subfolder.  The nesting drop-down is visible but a type of indention would be nice.

**Comment by da-anda** [comment]
I can second that. The tree view of IMAP folders is visually broken. It does not matter how deeply nested a folder is when you expand it, it always shares the indention of the second nesting level. So you can't really tell to which level any folder belongs when you have a couple of them expanded. Here is a screenshot of the issue:

![image](https://github.com/user-attachments/assets/628d2686-8fef-4409-8dfc-2912a367d3f9)

As you can see, you can't visually tell that `Klettern & Bouldern` is actually a subfolder of `Freizeit`. From a quick dive into the CSS, the main issue seems to be that `.app-navigation-entry__children` is missing a `padding: 16px;`. Once I add this custom CSS rule and remove the now superflouos `.app-navigation-entry__children .app-navigation-entry[data-v-XXXXXX] { padding-left: 16px; }` all nesting levels are properly indented without the need for custom `[data-v-XXXXX]` selectors and rules that only seem to unnecessarily bloat the CSS.

**Comment by da-anda** [comment]
could somebody please assign the "bug" label, since this issue apparently had already been fixed at some point (see https://github.com/nextcloud/mail/pull/3147) and thus whichever change broke it caused a regression
