### ISSUE TITLE
List view for NC Mail

### ISSUE THREAD

**Issue by lp-SRO** [nextcloud/mail#8827]
### Describe the solution you'd like

I would like an adjustable list view. Especially if the first emails in a mailbox are spam emails, it would be much better if they were not opened in the split view right away. In a list view, you could delete them in advance.

**Comment by ChristophWurst** [comment]
Duplicate of https://github.com/nextcloud/mail/issues/8811?

**Comment by ChristophWurst** [comment]
Duplicate and delivered
