### ISSUE TITLE
Thread summaries "Nextcloud assistant" and "Go to newest message" have unbalanced padding

### ISSUE THREAD

**Issue by ChristophWurst** [nextcloud/mail#8837]
### Steps to reproduce

1. Set up the app including text processing
2. Enable thread summaries
3. Open a long thread
4. Look at the summary

### Expected behavior

Good design

### Actual behavior

![Bildschirmfoto vom 2023-09-07 08-16-44](https://github.com/nextcloud/mail/assets/1374172/bbcb686d-1d53-49bd-a1c8-c5435c756509)

### Mail app version

3.4

### PHP engine version

None

### Web server

None

### Database

None

### Additional info

cc @hamza221

**Comment by ChristophWurst** [comment]
Proposal: ![Bildschirmfoto vom 2023-09-07 08-16-31](https://github.com/nextcloud/mail/assets/1374172/2b0c2507-d9b9-4415-b06c-4908370127ed) or similar.

@jancborchardt @marcoambrosini @nimishavijay

**Comment by nimishavijay** [comment]
Agreed! We could also reduce the top and bottom padding for the Nextcloud assistant chip, since it is not a clickable button. In the [original mockups](https://github.com/nextcloud/mail/issues/8508#issuecomment-1634281586) it was rather meant to look like a user bubble :)
