### ISSUE TITLE
🔎 Allow message date and recipient search in advanced search

### ISSUE THREAD

**Issue by ChristophWurst** [nextcloud/mail#8864]
### Is your feature request related to a problem? Please describe.

Extend advanced search in server with Mail specifics, like searching sender and recipients.

### Describe the solution you'd like

Integrate with the new seach in Hub 7 (details follow)

### Additional context

https://github.com/nextcloud/server/issues/39162

**Comment by ChristophWurst** [comment]
API draft is at https://github.com/nextcloud/server/pull/40618.

**Comment by JohannesGGE** [comment]
Current state and more information in this draft-pr: https://github.com/nextcloud/mail/pull/9002
