### ISSUE TITLE
Automatic trash retetion does not work: no effect

### ISSUE THREAD

**Issue by jakobroehrl** [nextcloud/mail#8872]
my setting:
![image](https://github.com/nextcloud/mail/assets/24530680/da9891f4-c7cd-46c1-bad4-770aa67cd897)
I waited some days

### Expected behavior

All mails in trash a younger than a year

### Actual behavior

There are a lot of mails older then a year

### Mail app version

3.4.0

### PHP engine version

PHP 8.2

### Web server

Nginx

### Database

PostgreSQL

**Comment by ChristophWurst** [comment]
Like the UI says

> Only mails deleted after enabling trash retention will be processed.

The app can't know when the message was *deleted* (not sent).
