### ISSUE TITLE
Installing mail on Ubuntu 18.04 crashes system

### ISSUE THREAD

**Issue by strongthany** [nextcloud/mail#888]
### Steps to reproduce
1. browse to mail app in app store
2. click enable on mail app

### Expected behaviour
Mail app should enable itself

### Actual behaviour
nextcloud crashes

### Mail app

v0.7.10

### Server configuration

**Operating system**: Ubuntu server 18.04

**Web server:** Apache 2.4.29 

**Database:** mysql

**PHP version:** 7.3

**Version:** 13.0.0.14

**Updated from an older version or fresh install:** fresh install

**List of activated apps:**

```
If you have access to your command line run e.g.:
sudo -u www-data php occ app:list
from within your server installation folder
```

**Enabled:
  - activity: 2.6.1
  - admin_audit: 1.3.0
  - calendar: 1.6.1
  - comments: 1.3.0
  - contacts: 2.1.3
  - dav: 1.4.6
  - encryption: 2.0.0
  - federatedfilesharing: 1.3.1
  - federation: 1.3.0
  - files: 1.8.0
  - files_accesscontrol: 1.3.0
  - files_automatedtagging: 1.3.0
  - files_sharing: 1.5.0
  - files_texteditor: 2.5.1
  - files_trashbin: 1.3.0
  - files_versions: 1.6.0
  - files_videoplayer: 1.2.0
  - firstrunwizard: 2.2.1
  - gallery: 18.0.0
  - logreader: 2.0.0
  - lookup_server_connector: 1.1.0
  - nextcloud_announcements: 1.2.0
  - notifications: 2.1.2
  - oauth2: 1.1.0
  - password_policy: 1.3.0
  - provisioning_api: 1.3.0
  - richdocuments: 2.0.8
  - serverinfo: 1.3.0
  - sharebymail: 1.3.0
  - spreed: 3.1.0
  - survey_client: 1.1.0
  - systemtags: 1.3.0
  - theming: 1.4.1
  - twofactor_backupcodes: 1.2.3
  - twofactor_totp: 1.4.1
  - updatenotification: 1.3.0
  - workflowengine: 1.3.0
Disabled:
  - files_external
  - files_pdfviewer
  - user_external
  - user_ldap
**

<details>
```
<?php
$CONFIG = array (
  'instanceid' => 'ockxe5sidvp1',
  'passwordsalt' => 'asalt',
  'secret' => 'shhhhitsasecret',
  'trusted_domains' => 
  array (
	  0 => '10.200.1.127',
	  1 => 'cloud.occorp.net',
  ),
  'datadirectory' => '/var/www/nextcloud/data',
  'overwrite.cli.url' => 'http://10.200.1.127/nextcloud',
  'dbtype' => 'mysql',
  'version' => '13.0.2.1',
  'dbname' => 'nextcloud',
  'dbhost' => 'localhost',
  'dbport' => '',
  'dbtableprefix' => 'oc_',
  'dbuser' => 'nc_user',
  'dbpassword' => 'aPassword',
  'installed' => true,
  'memcache.local' => '\OC\Memcache\Redis',
  'memcache.local' => '\OC\Memcache\Redis',
  'memcache.local' => '\OC\Memcache\Redis',
'redis' => array(
     'host' => 'localhost',
     'port' => 6379,
      ),
);

</details>

##### Server log (data/nextcloud.log)
https://cloud.occorp.net/nextcloud/index.php/s/9NedjHpBHYm5iJz

**Comment by ChristophWurst** [comment]
The Nextcloud mail app offers an extensive logging system to make it easier identifying and tracking down bugs. Please enable [debug mode](https://docs.nextcloud.com/server/13/developer_manual/general/devenv.html#enabling-debug-mode) and set the log [level to debug](https://docs.nextcloud.com/server/13/admin_manual/configuration_server/logging_configuration.html) in your admin settings. Then, try to reproduce your issue and take another look at `data/nextcloud.log`, `data/horde_imap.log` and `data/horde_smtp.log`.

**Comment by strongthany** [comment]
1: I put it in debug mode
2: tried to install mail app
3: next cloud crashed, force restart on esxi interface
4: browsed to debugging and gathered the following: 

`

Debug | cron | Run OCA\LookupServerConnector\BackgroundJobs\RetryJob job with ID 77 | 2018-05-08T15:40:40-0500
-- | -- | -- | --
Debug | PHP | is_file() expects parameter 1 to be a valid path, string given at /var/www/nextcloud/lib/private/legacy/image.php#554 | 2018-05-08T15:40:35-0500
Debug | core | OC_Image->loadFromBase64, could not load | 2018-05-08T15:40:35-0500
Debug | PHP | imagecreatefromstring(): Data is not in a recognized format at /var/www/nextcloud/lib/private/legacy/image.php#685 | 2018-05-08T15:40:35-0500
Debug | core | OC_Image->fixOrientation() Orientation: -1 | 2018-05-08T15:40:35-0500
Debug | core | OC_Image->fixOrientation() Image is not a JPEG. | 2018-05-08T15:40:35-0500
Debug | PHP | rewinddir(): 25 is not a valid Directory resource at /var/www/nextcloud/3rdparty/icewind/streams/src/Wrapper.php#31 | 2018-05-08T15:40:35-0500
Debug | PHP | rewinddir(): 17 is not a valid Directory resource at /var/www/nextcloud/lib/private/Files/Stream/Encryption.php#198 | 2018-05-08T15:40:34-0500
Debug | PHP | rewinddir(): 13 is not a valid Directory resource at /var/www/nextcloud/lib/private/Files/Stream/Encryption.php#198 | 2018-05-08T15:40:33-0500
Debug | PHP | is_file() expects parameter 1 to be a valid path, string given at /var/www/nextcloud/lib/private/legacy/image.php#554 | 2018-05-08T15:40:33-0500
Debug | core | OC_Image->loadFromBase64, could not load | 2018-05-08T15:40:33-0500
Debug | PHP | imagecreatefromstring(): Data is not in a recognized format at /var/www/nextcloud/lib/private/legacy/image.php#685 | 2018-05-08T15:40:33-0500
Debug | core | OC_Image->fixOrientation() Orientation: -1 | 2018-05-08T15:40:33-0500
Debug | core | OC_Image->fixOrientation() Image is not a JPEG. | 2018-05-08T15:40:33-0500
Debug | PHP | rewinddir(): 26 is not a valid Directory resource at /var/www/nextcloud/3rdparty/icewind/streams/src/Wrapper.php#31 | 2018-05-08T15:40:33-0500
Debug | PHP | rewinddir(): 18 is not a valid Directory resource at /var/www/nextcloud/lib/private/Files/Stream/Encryption.php#198 | 2018-05-08T15:40:33-0500
Debug | PHP | rewinddir(): 13 is not a valid Directory resource at /var/www/nextcloud/lib/private/Files/Stream/Encryption.php#198 | 2018-05-08T15:40:32-0500
Debug | cron | Finished OC\Settings\BackgroundJobs\VerifyUserData job with ID 76 in 0 seconds | 2018-05-08T15:39:36-0500
Debug | cron | Run OC\Settings\BackgroundJobs\VerifyUserData job with ID 76 | 2018-05-08T15:39:36-0500
Debug | PHP | is_file() expects parameter 1 to be a valid path, string given at /var/www/nextcloud/lib/private/legacy/image.php#554 | 2018-05-08T15:36:55-0500
Debug | core | OC_Image->loadFromBase64, could not load | 2018-05-08T15:36:55-0500
Debug | PHP | imagecreatefromstring(): Data is not in a recognized format at /var/www/nextcloud/lib/private/legacy/image.php#685 | 2018-05-08T15:36:55-0500
Debug | core | OC_Image->fixOrientation() Orientation: -1 | 2018-05-08T15:36:55-0500
Debug | PHP | rewinddir(): 37 is not a valid Directory resource at /var/www/nextcloud/3rdparty/icewind/streams/src/Wrapper.php#31 | 2018-05-08T15:36:55-0500
Debug | PHP | rewinddir(): 29 is not a valid Directory resource at /var/www/nextcloud/lib/private/Files/Stream/Encryption.php#198 | 2018-05-08T15:36:55-0500
Debug | PHP | rewinddir(): 20 is not a valid Directory resource at /var/www/nextcloud/lib/private/Files/Stream/Encryption.php#198 | 2018-05-08T15:36:53-0500
Debug | cron | Finished OCA\LookupServerConnector\BackgroundJobs\RetryJob job with ID 73 in 1 seconds | 2018-05-08T15:28:16-0500
Debug | cron | Run OCA\LookupServerConnector\BackgroundJobs\RetryJob job with ID 73 | 2018-05-08T15:28:15-0500
Debug | cron | Finished OC\Settings\BackgroundJobs\VerifyUserData job with ID 72 in 1 seconds | 2018-05-08T15:04:29-0500
Debug | cron | Run OC\Settings\BackgroundJobs\VerifyUserData job with ID 72 | 2018-05-08T15:04:28-0500
Debug | PHP | is_file() expects parameter 1 to be a valid path, string given at /var/www/nextcloud/lib/private/legacy/image.php#554 | 2018-05-08T14:59:45-0500
Debug | core | OC_Image->loadFromBase64, could not load | 2018-05-08T14:59:45-0500
Debug | PHP | imagecreatefromstring(): Data is not in a recognized format at /var/www/nextcloud/lib/private/legacy/image.php#685 | 2018-05-08T14:59:45-0500
Debug | core | OC_Image->fixOrientation() Orientation: -1 | 2018-05-08T14:59:45-0500
Debug | core | OC_Image->fixOrientation() Image is not a JPEG. | 2018-05-08T14:59:45-0500
Debug | PHP | rewinddir(): 26 is not a valid Directory resource at /var/www/nextcloud/3rdparty/icewind/streams/src/Wrapper.php#31 | 2018-05-08T14:59:45-0500
Debug | PHP | rewinddir(): 18 is not a valid Directory resource at /var/www/nextcloud/lib/private/Files/Stream/Encryption.php#198 | 2018-05-08T14:59:45-0500
Debug | PHP | rewinddir(): 13 is not a valid Directory resource at /var/www/nextcloud/lib/private/Files/Stream/Encryption.php#198 | 2018-05-08T14:59:44-0500
Debug | PHP | rewinddir(): 17 is not a valid Directory resource at /var/www/nextcloud/lib/private/Files/Stream/Encryption.php#198 | 2018-05-08T14:59:41-0500
Debug | PHP | rewinddir(): 17 is not a valid Directory resource at /var/www/nextcloud/lib/private/Files/Stream/Encryption.php#198 | 2018-05-08T14:59:37-0500
Debug | PHP | rewinddir(): 17 is not a valid Directory resource at /var/www/nextcloud/lib/private/Files/Stream/Encryption.php#198 | 2018-05-08T14:59:34-0500
Debug | PHP | is_file() expects parameter 1 to be a valid path, string given at /var/www/nextcloud/lib/private/legacy/image.php#554 | 2018-05-08T14:59:29-0500
Debug | core | OC_Image->loadFromBase64, could not load | 2018-05-08T14:59:29-0500
Debug | PHP | imagecreatefromstring(): Data is not in a recognized format at /var/www/nextcloud/lib/private/legacy/image.php#685 | 2018-05-08T14:59:29-0500
Debug | core | OC_Image->fixOrientation() Orientation: -1 | 2018-05-08T14:59:28-0500
Debug | PHP | rewinddir(): 25 is not a valid Directory resource at /var/www/nextcloud/3rdparty/icewind/streams/src/Wrapper.php#31 | 2018-05-08T14:59:28-0500
Debug | PHP | rewinddir(): 17 is not a valid Directory resource at /var/www/nextcloud/lib/private/Files/Stream/Encryption.php#198 | 2018-05-08T14:59:28-0500
Debug | PHP | rewinddir(): 13 is not a valid Directory resource at /var/www/nextcloud/lib/private/Files/Stream/Encryption.php#198 | 2018-05-08T14:59:27-0500
Debug | PHP | is_file() expects parameter 1 to be a valid path, string given at /var/www/nextcloud/lib/private/legacy/image.php#554 | 2018-05-08T14:59:27-0500
Debug | core | OC_Image->loadFromBase64, could not load | 2018-05-08T14:59:27-0500
Debug | PHP | imagecreatefromstring(): Data is not in a recognized format at /var/www/nextcloud/lib/private/legacy/image.php#685 | 2018-05-08T14:59:27-0500
Debug | core | OC_Image->fixOrientation() Orientation: -1 | 2018-05-08T14:59:26-0500
Debug | PHP | rewinddir(): 35 is not a valid Directory resource at /var/www/nextcloud/3rdparty/icewind/streams/src/Wrapper.php#31 | 2018-05-08T14:59:26-0500
Debug | PHP | rewinddir(): 27 is not a valid Directory resource at /var/www/nextcloud/lib/private/Files/Stream/Encryption.php#198 | 2018-05-08T14:59:26-0500
Debug | PHP | rewinddir(): 29 is not a valid Directory resource at /var/www/nextcloud/lib/private/Files/Stream/Encryption.php#198 | 2018-05-08T14:59:23-0500
Debug | cron | Finished OCA\UpdateNotification\Notification\BackgroundJob job with ID 9 in 11 seconds | 2018-05-08T14:47:29-0500
Debug | cron | Run OCA\UpdateNotification\Notification\BackgroundJob job with ID 9 | 2018-05-08T14:47:18-0500
Debug | cron | Finished OCA\Federation\SyncJob job with ID 8 in 0 seconds | 2018-05-08T14:36:48-0500
Debug | cron | Run OCA\Federation\SyncJob job with ID 8 | 2018-05-08T14:36:48-0500

`

**Comment by ChristophWurst** [comment]
Woah, if the whole machine crashes (I thought you meant web server crashes or just blank pages) than it's very likely to be caused by a PHP or operating system error.

> becomes unresponsive

Is there any chance you could investigate on what exactly is happening to the machine? Does the kernel panic or is it unresponsive due to overloading?

**Comment by strongthany** [comment]
I was going to post the kernel logs, but when looking at them I noticed that the date was very off. I checked the time and noticed I was hours off. I tried setting the time to the correct time and rebooting but to no avail.

I'm not sure if it's kernel panic because I don't get any response from my ssh session, web page, or console on ESXi console. I don't belive it's overloading, as the ESXi page doesn't show it having higher resource usage.

What logs would you need to better troubleshoot this?

**Comment by ChristophWurst** [comment]
I don't know what to do here, but it's definitely out of scope for this app and Nextcloud in general.

**Comment by strongthany** [comment]
Understood. I'll close this and file a report with nextcloud itself. Thank you for the help.
