### ISSUE TITLE
Menus in mail are cut off exactly at entries, making it not obvious there are further actions

### ISSUE THREAD

**Issue by jancborchardt** [nextcloud/mail#8900]
### Steps to reproduce

1. Open a menu in Mail, either in the message list or the message itself
2. Look at it and wonder if there are further actions down the list
3. (There are)

### Expected behavior

1. If the viewport is high enough, we can show the whole menu.
2. If the viewport is not high enough, any action menu needs to be cut off at 1/2 of an entry so it is obvious there is still stuff below.

### Actual behavior

Menus are cut off exactly so it appears the last entry here is the last in the menu, which is not the case:
Example in message list | Example in message itself on narrower viewports
-|-
![image](https://github.com/nextcloud/mail/assets/925062/3617eb03-c700-409f-b523-6d81095ccc45)|![image](https://github.com/nextcloud/mail/assets/925062/4d17a984-e86c-4e15-83fb-73f372e1c7bc)

### Mail app version

Current on cloud.nextcloud.com

### PHP engine version

None

### Web server

None

### Database

None

**Comment by ChristophWurst** [comment]
This has to be fixed in https://github.com/nextcloud-libraries/nextcloud-vue

**Comment by jancborchardt** [comment]
Closing in favor of the existing component issue at https://github.com/nextcloud-libraries/nextcloud-vue/issues/3920
