### ISSUE TITLE
Composer action menu doesnt close when you click outside

### ISSUE THREAD

**Issue by GretaD** [nextcloud/mail#8924]
### Steps to reproduce

1. go to Nextcloud Mail
2. click on new message
3. click on the three dots
4. click elsewhere on the screen
5. the email modal disappear but the three dot menu stays open

### Expected behavior

The action menu is closed

### Actual behavior

The action menu stays open

### PHP engine version

None

### Web server

None

### Database

None

**Comment by ChristophWurst** [comment]
And firefox freezes with a busy script.

**Comment by GretaD** [comment]
yay, i cannot reproduce this anymore. It is most probably fixed when we split the attachment menu.
