### ISSUE TITLE
Out-of-office: Apply user info to auto responder settings (if enabled)

### ISSUE THREAD

**Issue by st3iny** [nextcloud/mail#8925]
### Is your feature request related to a problem? Please describe.

There will be a global absence form in the personal settings. Those settings should be integrated with our autoresponder.

Tracked in https://github.com/nextcloud/server/issues/40397

Probably requires https://github.com/nextcloud/server/issues/40650 to fetch the actual data

### Describe the solution you'd like

Global out-of-office data should be applied to the autoresponder form.

### Describe alternatives you've considered

_None_

**Comment by ChristophWurst** [comment]
Idea for the Mail settings: make the switch ternary:
1) Auto responder off
2) Auto responder enabled
3) Auto responder follows system setting

Default should be on off, I think.

For provisioning we have an option to enable Sieve. There could be a checkbox to enable system autoresponders by default.

**Comment by jancborchardt** [comment]
@ChristophWurst is the main intention of this to have it translated? Because e.g. for mail autoreply, this is not something which can be translated for the sender anyway, right?
But I don’t have strong feelings about the subject being the short message, it would be fine to have a generic subject. It would still be useful for other places where it appears, right?

**Comment by ChristophWurst** [comment]
Fair enough. L10n is indeed tricky here. Sometimes the user's own language is fine. Other times you want to internationalize.

> But I don’t have strong feelings about the subject being the short message, it would be fine to have a generic subject. It would still be useful for other places where it appears, right?

In my personal use case, I do want other Nextcloud users to see why I'm out, like when I'm sick. Other Nextcloud users are colleagues and people I work with. The autoresponder is on for anyone who knows my email. I don't want my short message (status) sent to them.

We could also just prepend `Re: ` to the original message's subject and avoid the l10n dilemma.

**Comment by jancborchardt** [comment]
Ah right, got it. Yes, the status is indeed a bit more private. Then let's go with the generic "Out of office" subject as you suggest.
