### ISSUE TITLE
Undefined array keys "m.mailbox_id" and "m.uid"

### ISSUE THREAD

**Issue by solracsf** [nextcloud/mail#8934]
### Steps to reproduce

Check logs

### Expected behavior

No undefined keys

### Actual behavior

```
Undefined array key "m.mailbox_id" at /var/www/nextcloud/apps/mail/lib/Db/MessageRetentionMapper.php#105
Undefined array key "m.uid" at /var/www/nextcloud/apps/mail/lib/Db/MessageRetentionMapper.php#106
```

### Mail app version

3.4.1

### PHP engine version

PHP 8.1

### Web server

None

### Database

MariaDB

### Additional info

Wonder if these should read instead (mr. instead of m.)

```
$deleteQb->setParameter('mailbox_id', $row['mr.mailbox_id'], IQueryBuilder::PARAM_INT);
$deleteQb->setParameter('uid', $row['mr.uid'], IQueryBuilder::PARAM_INT);
```

https://github.com/nextcloud/mail/blob/d69257c4629637e3874ff0de4aff123cc8d01656/lib/Db/MessageRetentionMapper.php#L105-L106

**Comment by ChristophWurst** [comment]
the query only selects `m.id`. `m.mailbox_id` and `m.uid` are missing.
