### ISSUE TITLE
Mail-App Advanced Search Error

### ISSUE THREAD

**Issue by AlexanderZuehr** [nextcloud/mail#8952]
### Steps to reproduce

Hey if I try to search in the mail-app with the advanced mail-app search function I am getting an error if I use one of the following fields.

To:
Cc:
Bcc:

I'll attach pictures and the log from nextcloud.

<img width="600" alt="Bildschirmfoto 2023-10-11 um 11 43 32" src="https://github.com/nextcloud/mail/assets/76497172/f98b81e1-9936-4659-96e1-0464fc314997">
<img width="605" alt="Bildschirmfoto 2023-10-11 um 11 43 14" src="https://github.com/nextcloud/mail/assets/76497172/59ee05a5-afaf-4117-9cfb-b6395f98f2f8">
<img width="602" alt="Bildschirmfoto 2023-10-11 um 11 42 55" src="https://github.com/nextcloud/mail/assets/76497172/b9e2cbef-4e7e-4743-9cd7-77c6d145b7b6">
<img width="300" alt="Bildschirmfoto 2023-10-11 um 11 42 48" src="https://github.com/nextcloud/mail/assets/76497172/2e8ebb89-4f6f-4304-8dfb-955aed4358ed">

### Mail app version

3.4.0

### PHP engine version

None

### Web server

None

### Database

None

### Additional info

[mail] Fehler: OC\DB\Exceptions\DbalException: An exception occurred while executing a query: SQLSTATE[42S22]: Column not found: 1054 Unknown column 'r0.email' in 'where clause' at <<closure>>

 0. /var/www/html/lib/private/DB/QueryBuilder/QueryBuilder.php line 295
    OC\DB\Exceptions\DbalException::wrap()
 1. /var/www/html/lib/public/AppFramework/Db/QBMapper.php line 335
    OC\DB\QueryBuilder\QueryBuilder->executeQuery()
 2. /var/www/html/apps/mail/lib/Db/MessageMapper.php line 869
    OCP\AppFramework\Db\QBMapper->findEntities()
 3. /var/www/html/apps/mail/lib/Service/Search/MailSearch.php line 169
    OCA\Mail\Db\MessageMapper->findIdsByQuery()
 4. /var/www/html/apps/mail/lib/Service/Search/MailSearch.php line 133
    OCA\Mail\Service\Search\MailSearch->getIdsLocally()
 5. /var/www/html/apps/mail/lib/Controller/MessagesController.php line 159
    OCA\Mail\Service\Search\MailSearch->findMessages()
 6. /var/www/html/lib/private/AppFramework/Http/Dispatcher.php line 230
    OCA\Mail\Controller\MessagesController->index()
 7. /var/www/html/lib/private/AppFramework/Http/Dispatcher.php line 137
    OC\AppFramework\Http\Dispatcher->executeController()
 8. /var/www/html/lib/private/AppFramework/App.php line 183
    OC\AppFramework\Http\Dispatcher->dispatch()
 9. /var/www/html/lib/private/Route/Router.php line 315
    OC\AppFramework\App::main()
10. /var/www/html/lib/base.php line 1068
    OC\Route\Router->match()
11. /var/www/html/index.php line 36
    OC::handleRequest()

Caused by:

Doctrine\DBAL\Exception\InvalidFieldNameException: An exception occurred while executing a query: SQLSTATE[42S22]: Column not found: 1054 Unknown column 'r0.email' in 'where clause' at <<closure>>

 0. /var/www/html/3rdparty/doctrine/dbal/src/Connection.php line 1814
    Doctrine\DBAL\Driver\API\MySQL\ExceptionConverter->convert()
 1. /var/www/html/3rdparty/doctrine/dbal/src/Connection.php line 1749
    Doctrine\DBAL\Connection->handleDriverException()
 2. /var/www/html/3rdparty/doctrine/dbal/src/Connection.php line 1055
    Doctrine\DBAL\Connection->convertExceptionDuringQuery()
 3. /var/www/html/lib/private/DB/Connection.php line 262
    Doctrine\DBAL\Connection->executeQuery()
 4. /var/www/html/3rdparty/doctrine/dbal/src/Query/QueryBuilder.php line 345
    OC\DB\Connection->executeQuery()
 5. /var/www/html/lib/private/DB/QueryBuilder/QueryBuilder.php line 280
    Doctrine\DBAL\Query\QueryBuilder->execute()
 6. /var/www/html/lib/private/DB/QueryBuilder/QueryBuilder.php line 293
    OC\DB\QueryBuilder\QueryBuilder->execute()
 7. /var/www/html/lib/public/AppFramework/Db/QBMapper.php line 335
    OC\DB\QueryBuilder\QueryBuilder->executeQuery()
 8. /var/www/html/apps/mail/lib/Db/MessageMapper.php line 869
    OCP\AppFramework\Db\QBMapper->findEntities()
 9. /var/www/html/apps/mail/lib/Service/Search/MailSearch.php line 169
    OCA\Mail\Db\MessageMapper->findIdsByQuery()
10. /var/www/html/apps/mail/lib/Service/Search/MailSearch.php line 133
    OCA\Mail\Service\Search\MailSearch->getIdsLocally()
11. /var/www/html/apps/mail/lib/Controller/MessagesController.php line 159
    OCA\Mail\Service\Search\MailSearch->findMessages()
12. /var/www/html/lib/private/AppFramework/Http/Dispatcher.php line 230
    OCA\Mail\Controller\MessagesController->index()
13. /var/www/html/lib/private/AppFramework/Http/Dispatcher.php line 137
    OC\AppFramework\Http\Dispatcher->executeController()
14. /var/www/html/lib/private/AppFramework/App.php line 183
    OC\AppFramework\Http\Dispatcher->dispatch()
15. /var/www/html/lib/private/Route/Router.php line 315
    OC\AppFramework\App::main()
16. /var/www/html/lib/base.php line 1068
    OC\Route\Router->match()
17. /var/www/html/index.php line 36
    OC::handleRequest()

Caused by:

Doctrine\DBAL\Driver\PDO\Exception: SQLSTATE[42S22]: Column not found: 1054 Unknown column 'r0.email' in 'where clause' at <<closure>>

 0. /var/www/html/3rdparty/doctrine/dbal/src/Driver/PDO/Statement.php line 103
    Doctrine\DBAL\Driver\PDO\Exception::new()
 1. /var/www/html/3rdparty/doctrine/dbal/src/Connection.php line 1045
    Doctrine\DBAL\Driver\PDO\Statement->execute()
 2. /var/www/html/lib/private/DB/Connection.php line 262
    Doctrine\DBAL\Connection->executeQuery()
 3. /var/www/html/3rdparty/doctrine/dbal/src/Query/QueryBuilder.php line 345
    OC\DB\Connection->executeQuery()
 4. /var/www/html/lib/private/DB/QueryBuilder/QueryBuilder.php line 280
    Doctrine\DBAL\Query\QueryBuilder->execute()
 5. /var/www/html/lib/private/DB/QueryBuilder/QueryBuilder.php line 293
    OC\DB\QueryBuilder\QueryBuilder->execute()
 6. /var/www/html/lib/public/AppFramework/Db/QBMapper.php line 335
    OC\DB\QueryBuilder\QueryBuilder->executeQuery()
 7. /var/www/html/apps/mail/lib/Db/MessageMapper.php line 869
    OCP\AppFramework\Db\QBMapper->findEntities()
 8. /var/www/html/apps/mail/lib/Service/Search/MailSearch.php line 169
    OCA\Mail\Db\MessageMapper->findIdsByQuery()
 9. /var/www/html/apps/mail/lib/Service/Search/MailSearch.php line 133
    OCA\Mail\Service\Search\MailSearch->getIdsLocally()
10. /var/www/html/apps/mail/lib/Controller/MessagesController.php line 159
    OCA\Mail\Service\Search\MailSearch->findMessages()
11. /var/www/html/lib/private/AppFramework/Http/Dispatcher.php line 230
    OCA\Mail\Controller\MessagesController->index()
12. /var/www/html/lib/private/AppFramework/Http/Dispatcher.php line 137
    OC\AppFramework\Http\Dispatcher->executeController()
13. /var/www/html/lib/private/AppFramework/App.php line 183
    OC\AppFramework\Http\Dispatcher->dispatch()
14. /var/www/html/lib/private/Route/Router.php line 315
    OC\AppFramework\App::main()
15. /var/www/html/lib/base.php line 1068
    OC\Route\Router->match()
16. /var/www/html/index.php line 36
    OC::handleRequest()

Caused by:

PDOException: SQLSTATE[42S22]: Column not found: 1054 Unknown column 'r0.email' in 'where clause' at <<closure>>

 0. /var/www/html/3rdparty/doctrine/dbal/src/Driver/PDO/Statement.php line 101
    PDOStatement->execute()
 1. /var/www/html/3rdparty/doctrine/dbal/src/Connection.php line 1045
    Doctrine\DBAL\Driver\PDO\Statement->execute()
 2. /var/www/html/lib/private/DB/Connection.php line 262
    Doctrine\DBAL\Connection->executeQuery()
 3. /var/www/html/3rdparty/doctrine/dbal/src/Query/QueryBuilder.php line 345
    OC\DB\Connection->executeQuery()
 4. /var/www/html/lib/private/DB/QueryBuilder/QueryBuilder.php line 280
    Doctrine\DBAL\Query\QueryBuilder->execute()
 5. /var/www/html/lib/private/DB/QueryBuilder/QueryBuilder.php line 293
    OC\DB\QueryBuilder\QueryBuilder->execute()
 6. /var/www/html/lib/public/AppFramework/Db/QBMapper.php line 335
    OC\DB\QueryBuilder\QueryBuilder->executeQuery()
 7. /var/www/html/apps/mail/lib/Db/MessageMapper.php line 869
    OCP\AppFramework\Db\QBMapper->findEntities()
 8. /var/www/html/apps/mail/lib/Service/Search/MailSearch.php line 169
    OCA\Mail\Db\MessageMapper->findIdsByQuery()
 9. /var/www/html/apps/mail/lib/Service/Search/MailSearch.php line 133
    OCA\Mail\Service\Search\MailSearch->getIdsLocally()
10. /var/www/html/apps/mail/lib/Controller/MessagesController.php line 159
    OCA\Mail\Service\Search\MailSearch->findMessages()
11. /var/www/html/lib/private/AppFramework/Http/Dispatcher.php line 230
    OCA\Mail\Controller\MessagesController->index()
12. /var/www/html/lib/private/AppFramework/Http/Dispatcher.php line 137
    OC\AppFramework\Http\Dispatcher->executeController()
13. /var/www/html/lib/private/AppFramework/App.php line 183
    OC\AppFramework\Http\Dispatcher->dispatch()
14. /var/www/html/lib/private/Route/Router.php line 315
    OC\AppFramework\App::main()
15. /var/www/html/lib/base.php line 1068
    OC\Route\Router->match()
16. /var/www/html/index.php line 36
    OC::handleRequest()

GET /apps/mail/api/messages?mailboxId=417&filter=to:alexander.zuehr%40ariva.de&limit=20
from 172.17.51.100 by alz at 2023-10-11T09:56:41+00:00

**Comment by ChristophWurst** [comment]
@AlexanderZuehr try https://github.com/nextcloud/mail/pull/8953.

https://docs.nextcloud.com/server/latest/admin_manual/issues/applying_patch.html#patching-apps

**Comment by AlexanderZuehr** [comment]
@ChristophWurst can I manually patch this in the mail-app on the server? 
Are you releasing this fix for the stable 3.4 version of the mail-app?

**Comment by ChristophWurst** [comment]
Yes https://docs.nextcloud.com/server/latest/admin_manual/issues/applying_patch.html#patching-apps and probably yes

**Comment by ChristophWurst** [comment]
But please help us validate the fix. Let me know if the bug is resolved after patching.

**Comment by AlexanderZuehr** [comment]
I will patch this evening and after that I am going to comment here.

**Comment by AlexanderZuehr** [comment]
@ChristophWurst  I've set up a clone of our environment and tested the patch and it is solving this ticket for me. The error is not occurring anymore but #8954 is not resolved
