### ISSUE TITLE
Horde_Imap_Client_Exception: No password provided.

### ISSUE THREAD

**Issue by ChristophWurst** [nextcloud/mail#8963]
### Steps to reproduce

1. Configure provisioning
2. Run background jobs (the mail quota job specifically)

### Expected behavior

No errors in background job

### Actual behavior

Errors in background job

### Mail app version

3.4.1

### PHP engine version

None

### Web server

None

### Database

None

### Additional info

```json
{
  "reqId": "mGo2SKQDoouOUDvlFtlc",
  "level": 3,
  "time": "2023-10-12T04:11:44+00:00",
  "remoteAddr": "",
  "user": "--",
  "app": "core",
  "method": "",
  "url": "--",
  "message": "Error while running background job (class: OCA\\Mail\\BackgroundJob\\QuotaJob, arguments: Array\n(\n    [accountId] => 81\n)\n)",
  "userAgent": "--",
  "version": "27.1.2.1",
  "exception": {
    "Exception": "Horde_Imap_Client_Exception",
    "Message": "No password provided.",
    "Code": 102,
    "Trace": [
      {
        "file": "/var/www/nextcloud/apps/mail/vendor/bytestream/horde-imap-client/lib/Horde/Imap/Client/Base.php",
        "line": 853,
        "function": "_login",
        "class": "Horde_Imap_Client_Socket",
        "type": "->",
        "args": [
          "*** sensitive parameters replaced ***"
        ]
      },
      {
        "file": "/var/www/nextcloud/apps/mail/vendor/bytestream/horde-imap-client/lib/Horde/Imap/Client/Base.php",
        "line": 1404,
        "function": "login",
        "class": "Horde_Imap_Client_Base",
        "type": "->",
        "args": [
          "*** sensitive parameters replaced ***"
        ]
      },
      {
        "file": "/var/www/nextcloud/apps/mail/lib/IMAP/FolderMapper.php",
        "line": 59,
        "function": "listMailboxes",
        "class": "Horde_Imap_Client_Base",
        "type": "->",
        "args": [
          "*",
          5,
          [
            true,
            true,
            true
          ]
        ]
      },
      {
        "file": "/var/www/nextcloud/apps/mail/lib/Service/MailManager.php",
        "line": 562,
        "function": "getFolders",
        "class": "OCA\\Mail\\IMAP\\FolderMapper",
        "type": "->",
        "args": [
          [
            "OCA\\Mail\\Account"
          ],
          [
            "Horde_Imap_Client_Socket",
            [
              "HICenv",
              "HICflags",
              "HIChdrs",
              "HICdate",
              "HICsize",
              "And 1 more entries, set log level to debug to see all entries"
            ],
            true,
            true
          ]
        ]
      },
      {
        "file": "/var/www/nextcloud/apps/mail/lib/BackgroundJob/QuotaJob.php",
        "line": 92,
        "function": "getQuota",
        "class": "OCA\\Mail\\Service\\MailManager",
        "type": "->",
        "args": [
          [
            "OCA\\Mail\\Account"
          ]
        ]
      },
      {
        "file": "/var/www/nextcloud/lib/public/BackgroundJob/Job.php",
        "line": 81,
        "function": "run",
        "class": "OCA\\Mail\\BackgroundJob\\QuotaJob",
        "type": "->",
        "args": [
          [
            81
          ]
        ]
      },
      {
        "file": "/var/www/nextcloud/lib/public/BackgroundJob/TimedJob.php",
        "line": 103,
        "function": "start",
        "class": "OCP\\BackgroundJob\\Job",
        "type": "->",
        "args": [
          [
            "OC\\BackgroundJob\\JobList"
          ]
        ]
      },
      {
        "file": "/var/www/nextcloud/lib/public/BackgroundJob/TimedJob.php",
        "line": 93,
        "function": "start",
        "class": "OCP\\BackgroundJob\\TimedJob",
        "type": "->",
        "args": [
          [
            "OC\\BackgroundJob\\JobList"
          ]
        ]
      },
      {
        "file": "/var/www/nextcloud/cron.php",
        "line": 152,
        "function": "execute",
        "class": "OCP\\BackgroundJob\\TimedJob",
        "type": "->",
        "args": [
          [
            "OC\\BackgroundJob\\JobList"
          ],
          [
            "OC\\Log"
          ]
        ]
      }
    ],
    "File": "/var/www/nextcloud/apps/mail/vendor/bytestream/horde-imap-client/lib/Horde/Imap/Client/Socket.php",
    "Line": 369,
    "message": "Error while running background job (class: OCA\\Mail\\BackgroundJob\\QuotaJob, arguments: Array\n(\n    [accountId] => 81\n)\n)",
    "exception": {
      "details": null,
      "logged": false,
      "raw_msg": "No password provided."
    },
    "CustomMessage": "Error while running background job (class: OCA\\Mail\\BackgroundJob\\QuotaJob, arguments: Array\n(\n    [accountId] => 81\n)\n)"
  },
  "id": "6527a65ecb7a6"
}
```

**Comment by ChristophWurst** [comment]
Private Sentry https://nextcloud-gmbh.sentry.io/issues/4362077441 shows that this happens every week at the very same time. That probably has to do with the quota background job interval.

I think it happens for all the quota jobs of provisioned accounts without a password.

``\OCA\Mail\BackgroundJob\SyncJob::run``, ``\OCA\Mail\BackgroundJob\TrainImportanceClassifierJob::run`` and ``\OCA\Mail\BackgroundJob\PreviewEnhancementProcessingJob::run``  has a provisioning and null password check, ``\OCA\Mail\BackgroundJob\QuotaJob::run`` doesn't, so an IMAP client with an empty *password* parameter is created, which can't authenticate.

@miaulalala could you please add a check for the quota job? :)

**Comment by JRGonz** [comment]
I am seeing this in 3.5.4 with 28.0.1.1... 

{"reqId":"y3gJDssu3W5DGle7ppLi","level":3,"time":"2024-01-17T23:30:20+00:00","remoteAddr":"","user":"--","app":"core","method":"","url":"--","message":"Error while running background job (class: OCA\\Mail\\BackgroundJob\\QuotaJob, arguments: Array\n(\n    [accountId] => 77\n)\n)","userAgent":"--","version":"28.0.1.1","exception":{"Exception":"Horde_Imap_Client_Exception","Message":"No password provided.","Code":102,"Trace":[{"file":"/var/www/cloud.domain.tld/apps/mail/lib/IMAP/ImapClientRateLimitingDecorator.php","line":73,"function":"_login","class":"Horde_Imap_Client_Socket","type":"->","args":["*** sensitive parameters replaced ***"]},{"file":"/var/www/cloud.domain.tld/apps/mail/vendor/bytestream/horde-imap-client/lib/Horde/Imap/Client/Base.php","line":853,"function":"_login","class":"OCA\\Mail\\IMAP\\ImapClientRateLimitingDecorator","type":"->","args":["*** sensitive parameters replaced ***"]},{"file":"/var/www/cloud.domain.tld/apps/mail/vendor/bytestream/horde-imap-client/lib/Horde/Imap/Client/Base.php","line":1404,"function":"login","class":"Horde_Imap_Client_Base","type":"->","args":["*** sensitive parameters replaced ***"]},{"file":"/var/www/cloud.domain.tld/apps/mail/lib/IMAP/FolderMapper.php","line":58,"function":"listMailboxes","class":"Horde_Imap_Client_Base","type":"->"},{"file":"/var/www/cloud.domain.tld/apps/mail/lib/Service/MailManager.php","line":598,"function":"getFolders","class":"OCA\\Mail\\IMAP\\FolderMapper","type":"->"},{"file":"/var/www/cloud.domain.tld/apps/mail/lib/BackgroundJob/QuotaJob.php","line":92,"function":"getQuota","class":"OCA\\Mail\\Service\\MailManager","type":"->"},{"file":"/var/www/cloud.domain.tld/lib/public/BackgroundJob/Job.php","line":81,"function":"run","class":"OCA\\Mail\\BackgroundJob\\QuotaJob","type":"->"},{"file":"/var/www/cloud.domain.tld/lib/public/BackgroundJob/TimedJob.php","line":102,"function":"start","class":"OCP\\BackgroundJob\\Job","type":"->"},{"file":"/var/www/cloud.domain.tld/lib/public/BackgroundJob/TimedJob.php","line":92,"function":"start","class":"OCP\\BackgroundJob\\TimedJob","type":"->"},{"file":"/var/www/cloud.domain.tld/cron.php","line":152,"function":"execute","class":"OCP\\BackgroundJob\\TimedJob","type":"->"}],"File":"/var/www/cloud.domain.tld/apps/mail/vendor/bytestream/horde-imap-client/lib/Horde/Imap/Client/Socket.php","Line":369,"message":"Error while running background job (class: OCA\\Mail\\BackgroundJob\\QuotaJob, arguments: Array\n(\n    [accountId] => 77\n)\n)","exception":{"details":null,"logged":false,"raw_msg":"No password provided."},"CustomMessage":"Error while running background job (class: OCA\\Mail\\BackgroundJob\\QuotaJob, arguments: Array\n(\n    [accountId] => 77\n)\n)"}}
