### ISSUE TITLE
Configuring the mail for all accounts using the config.php is not working

### ISSUE THREAD

**Issue by MohammedNoureldin** [nextcloud/mail#8964]
### Steps to reproduce

- Deploy Nextcloud (in my case using Helm chart) with Mail app installed.
- The following config are in the helm chart's values:

```
    mail.config.php: |-
      <?php
      $CONFIG = array (
        'app.mail.accounts.default' => [
            'email' => '%USERID%@DOMAIN.com',
            'imapHost' => 'mail.DOMAIN.com',
            'imapPort' => 993,
            'imapUser' => '%USERID%',
            'imapSslMode' => 'ssl',
            'smtpHost' => 'mail.DOMAIN.com',
            'smtpPort' => 465,
            'smtpUser' => '%USERID%',
            'smtpSslMode' => 'ssl',
        ],
      );
```

- Login using any user and navigate to the mail or to the administration panel of groupware.

The mail is **not** configured.

### Expected behavior

The email should be configured for all users.

### Actual behavior

No email is configured. Neither in the Mail windows directly nor in the administration window of Groupware.

### Mail app version

3.4.2

### Operating system

Ubuntu

### PHP engine version

None

### Web server

None

### Database

None

### Additional info

Checking the config`:list` shows that my configuration is is there:

```
root@nextcloud-765f454fd5-mgqhm:/var/www/html# sudo -u www-data PHP_MEMORY_LIMIT=512M /var/www/html/occ config:list
{
    "system": {
        "htaccess.RewriteBase": "\/",
        "memcache.local": "\\OC\\Memcache\\APCu",
        "apps_paths": [
            ...
        ],
        "app.mail.accounts.default": {
            "email": "%USERID%@DOMAIN.com",
            "imapHost": "mail.DOMAIN.com",
            "imapPort": 993,
            "imapUser": "%USERID%",
            "imapSslMode": "ssl",
            "smtpHost": "mail.DOMAIN.com",
            "smtpPort": 465,
            "smtpUser": "%USERID%",
            "smtpSslMode": "ssl"
        },
    ...
```

However, as mentioned, the mail is still unconfigured in the mail Window and I see no config in the Adminsitration -> Groupware. What could be wrong here?

Is it correct that this config is part of the `system`? Or should it be somewhere else?

**Comment by MohammedNoureldin** [comment]
I am just pushing this up, in case something changed. Can anybody confirm if this is a bug or if I am doing something wrong?

**Comment by ChristophWurst** [comment]
The config.php option does not work anymore. The info is stored in the database, configured via the UI.

**Comment by MohammedNoureldin** [comment]
OK thanks for the info. Here is the SQL command to automate the configuration of this

```
mysql -u${MYSQL_USER} -p${MYSQL_PASSWORD} -h${MYSQL_HOST} -D${MYSQL_DATABASE} -e "
    INSERT INTO oc_mail_provisionings(
        id,
        provisioning_domain,
        email_template,
        imap_user,
        imap_host,
        imap_port,
        imap_ssl_mode,
        smtp_user,
        smtp_host,
        smtp_port,
        smtp_ssl_mode,
        ldap_aliases_provisioning,
        ldap_aliases_attribute
    ) 
    VALUES (
        1,
        '${MAIL_DOMAIN}',
        '%EMAIL%',
        '%EMAIL%',
        '${MAIL_IMAP_HOST}',
        '${MAIL_IMAP_PORT}',
        '${MAIL_IMAP_SSL_MODE}',
        '%EMAIL%',
        '${MAIL_SMTP_HOST}',
        '${MAIL_SMTP_PORT}',
        '${MAIL_SMTP_SSL_MODE}',
        '${MAIL_LDAP_ALIASES_PROVISIONING}',
        '${MAIL_LDAP_ALIASES_ATTRIBUTE}'
    );
"
```

I haven't tested it yet, but it seems to be tested by others. Take from here: https://help.nextcloud.com/t/configuring-and-provisioning-imap-for-all-accounts-does-not-work/172184/3

**Comment by ChristophWurst** [comment]
Proceed at your risk. I'm not sure if this will work as intended. Typically accounts are materialized when the provisioning config is saved. That step is missing if you write to the database directly.

**Comment by MohammedNoureldin** [comment]
To be honest I am also absolutely not happy with direct writing to the DB. As said I did not test it but somewhen reported that he used this method. It would be great if we could automate this config also some.
