### ISSUE TITLE
how can i make a static html file

### ISSUE THREAD

**Issue by ZHANGYUKA** [nextcloud/mail#8965]
### Is your feature request related to a problem? Please describe.

Your interface is beautiful, but I want to generate a static html file without PHP and port it to my phone, how can I solve it?

**Comment by strugee** [comment]
@ZHANGYUKA GitHub issues are for reporting bugs and feature requests. This question would be better suited for Nextcloud forums: https://help.nextcloud.com/

However before you post there I will note that your question doesn't really make sense. If you want a static HTML version of the page, you can just use Ctrl-S in your browser to save a copy, but it won't be interactive anymore. What you are asking for sounds like an [XY problem](https://meta.stackexchange.com/q/66377/223177).
