### ISSUE TITLE
Detect mail signature from mail server

### ISSUE THREAD

**Issue by codePau** [nextcloud/mail#8969]
### Is your feature request related to a problem? Please describe.

I synchronise email accounts for users in my Nextcloud instance. These email accounts have a mail signature configured in the mail server, but this configuration is not added when a new email account is synchronised.

### Describe the solution you'd like

Solution 1: Nextcloud mail adds configuration of mail signature when a new email account is synchronised on a Nextcloud user account.
Solution 2: Nextcloud mail provides a command for adding a digital signature to one, several or all Nextcloud users within an instance.

### Additional context

Thanks!

**Comment by ChristophWurst** [comment]
How is that information accessible?

**Comment by codePau** [comment]
Hi @ChristophWurst, thanks for your response and sorry about the delay. This information is stored in the mail server.

**Comment by ChristophWurst** [comment]
How can a client access the information? IMAP?

**Comment by codePau** [comment]
After doing some research, I have checked with an email provider and they don't know how to pass this information, so I am closing the issue. Thanks for your time!

**Comment by codePau** [comment]
After doing some research, I have checked with an email provider and they don't know how to pass this information, so I am closing the issue. Thanks for your time!
