### ISSUE TITLE
default mail settings for new users

### ISSUE THREAD

**Issue by Weltenstoeberer** [nextcloud/mail#8984]
### Is your feature request related to a problem? Please describe.

The beauty of Nextcloud lies in its consolidated app, making everything accessible at one place. Most tasks are pre-configured by the administrator, so new users can get up to speed quickly. 
However, at my workplace, multiple users require access to the same email address. To be able to use the Nextcloud mail application for this, each user has to create the email configuration again independently. This tends to be a daunting task and ends up consuming a lot of time.

### Describe the solution you'd like

Allowing the administrator to pre-set email account settings would be fantastic. It would be simpler to utilise user groups for this purpose. To achieve this, it may be recommended to include a distinct "Mail" option within the administration settings. This makes the mail app accessible for new users, who do not need to enter the login details for the shared email account manually.

### Describe alternatives you've considered

If you cannot change the settings using the user interface, you could also define the mail configuration in the backend. Perhaps through a hidden configuration file in the default user directory, or in the configuration of user groups?

### Additional context

Maybe I didn't look properly but I only found this thread on the subject:
https://github.com/nextcloud/mail/issues/8964

**Comment by ChristophWurst** [comment]
We have provisioning. For account sharing see https://github.com/nextcloud/mail/issues/572
