### ISSUE TITLE
Restore IMAP search feature: add an option for Nextcloud admins to activate it

### ISSUE THREAD

**Issue by HLFH** [nextcloud/mail#9037]
### Is your feature request related to a problem? Please describe.

On February 3rd, 2020, a regression was brought into Nextcloud Mail: https://github.com/nextcloud/mail/pull/2064.
Setting up in place full-text-search for IMAP was easy and search results were fast, but after the regression, IMAP FTS plugins are no longer used by Nextcloud Mail as it seems Nextcloud Mail no longer operates on IMAP directly.

### Describe the solution you'd like

IMAP search feature should be restored: add an option for Nextcloud admins to activate it, so Nextcloud Mail could directly operate on IMAP directly for the search feature.

### Describe alternatives you've considered

Using other webmails that work with IMAP SEARCH such as Roundcube but the third-party Nextcloud - Roundcube integration is broken. https://github.com/rotdrop/nextcloud-roundcube/

### Additional context

Currently, it has been 3 years that search is broken.

**Comment by ChristophWurst** [comment]
Fixed by https://github.com/nextcloud/mail/pull/8897
