### ISSUE TITLE
"Add share link from Nextcloud files" wrong window position

### ISSUE THREAD

**Issue by supercoil** [nextcloud/mail#9038]
### Steps to reproduce

1. Start writing an email
2. Click the three dots at the bottom of the compose window to open the menu for extra actions
3. Choose "Add share link from Nextcloud files"

### Expected behavior

The "Choose a file" window should appear on top

### Actual behavior

Window appears behind the menu:
![mail_insert_share_link](https://github.com/nextcloud/mail/assets/18485489/3b8e4c89-637e-442b-ae84-5e3d5c44db9f)

### Mail app version

3.4.3

### Operating system

Linux

### PHP engine version

PHP 8.2

### Web server

Apache (supported)

### Database

MariaDB

### Additional info

The same thing happens when choosing "Add attachment from Files". "Upload attachment" and "Smart picker" are OK, though.

**Comment by ChristophWurst** [comment]
What version of Nextcloud is that?

**Comment by supercoil** [comment]
Nextcloud 27.1.3

**Comment by GretaD** [comment]
Is this issue still relevant. I cannot reproduce it anymore

**Comment by supercoil** [comment]
You're right, works correctly now. Thanks for picking up on it.
