### ISSUE TITLE
Horde_Imap_Client_Exception_ServerResponse: IMAP error reported by server.

### ISSUE THREAD

**Issue by docmcfly** [nextcloud/mail#904]
### Steps to reproduce
1. I have create a test mail account: abc@cylancer.net 
   Password is abcabcabc
2. if i configure the mail account: 
   imap / smtp server: mail.cylancer.net with ssl and the user name is the mail address
3. the mail app can not connect to mail mailbox. 

The mail server is a postfix / courier combination. Other mail clients (evolution, outlook, roundcube, thunderbird) works.  But the webserver is the same server of the imap and postfix server. 

### Expected behaviour
i open the mail account and the app display the folder and mails... 

### Actual behaviour
but the mail app display the message: "Fehler beim Laden des ausgewählten Kontos."

### Mail app

**Mail app version:**  0.7.10

**Mailserver or service:** my courier / postfix server

**Number of accounts:** > 10 

### Server configuration
**Operating system**: Debian / ubuntu

**Web server:** apache
 
**Database:** maria

**PHP version:** 7

**Version:** 13.0.1

**Updated from an older version or fresh install:** upgrade from older version

**List of activated apps:**

<details>
Enabled:
  - activity: 2.6.1
  - calendar: 1.6.1
  - comments: 1.3.0
  - contacts: 2.1.3
  - dav: 1.4.6
  - federatedfilesharing: 1.3.1
  - federation: 1.3.0
  - files: 1.8.0
  - files_pdfviewer: 1.2.1
  - files_sharing: 1.5.0
  - files_texteditor: 2.5.1
  - files_trashbin: 1.3.0
  - files_versions: 1.6.0
  - files_videoplayer: 1.2.0
  - firstrunwizard: 2.2.1
  - gallery: 18.0.0
  - logreader: 2.0.0
  - lookup_server_connector: 1.1.0
  - mail: 0.7.10
  - nextcloud_announcements: 1.2.0
  - notes: 2.3.2
  - notifications: 2.1.2
  - oauth2: 1.1.0
  - password_policy: 1.3.0
  - provisioning_api: 1.3.0
  - ransomware_protection: 1.1.0
  - serverinfo: 1.3.0
  - sharebymail: 1.3.0
  - spreed: 3.2.0
  - survey_client: 1.1.0
  - theming: 1.4.1
  - twofactor_backupcodes: 1.2.3
  - updatenotification: 1.3.0
  - workflowengine: 1.3.0
Disabled:
  - admin_audit
  - bruteforcesettings
  - encryption
  - files_downloadactivity
  - files_external
  - onlyoffice
  - richdocuments
  - systemtags
  - user_external
  - user_ldap
</details>

**The content of config/config.php:**

<details>
{
    "system": {
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "datadirectory": "***REMOVED SENSITIVE VALUE***",
        "dbtype": "mysql",
        "version": "13.0.1.1",
        "dbname": "***REMOVED SENSITIVE VALUE***",
        "dbhost": "***REMOVED SENSITIVE VALUE***",
        "dbtableprefix": "",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "installed": true,
        "maintenance": false,
        "forcessl": true,
        "theme": "",
        "debug": true,
        "trusted_domains": [
            "cloud.cylancer.net"
        ],
        "mail_smtpmode": "php",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trashbin_retention_obligation": "auto",
        "updater.secret": "***REMOVED SENSITIVE VALUE***",
        "overwrite.cli.url": "https:\/\/cloud.cylancer.net",
        "loglevel": 2,
        "app.mail.imaplog.enabled": true,
        "app.mail.smtplog.enabled": true,
        "app.mail.transport": "php-mail"
    },
    "apps": {
        "activity": {
            "enabled": "yes",
            "installed_version": "2.6.1",
            "types": "filesystem"
        },
        "admin_migrate": {
            "enabled": "no",
            "installed_version": "0.1"
        },
        "backgroundjob": {
            "lastjob": "1101"
        },
        "bruteforcesettings": {
            "enabled": "no",
            "installed_version": "1.0.3",
            "types": ""
        },
        "calendar": {
            "enabled": "yes",
            "installed_version": "1.6.1",
            "signed": "true",
            "types": ""
        },
        "comments": {
            "enabled": "yes",
            "installed_version": "1.3.0",
            "types": "logging"
        },
        "contacts": {
            "enabled": "yes",
            "installed_version": "2.1.3",
            "types": ""
        },
        "core": {
            "OC_Channel": "stable",
            "backgroundjobs_mode": "cron",
            "backgroundjobs_step": "regular_tasks",
            "backgroundjobs_task": "",
            "global_cache_gc_lastrun": "1440011701",
            "installed.bundles": "[\"CoreBundle\"]",
            "installedat": "1368273601.72",
            "lastcron": "1510436193",
            "lastupdateResult": "{\"version\":\"13.0.2.1\",\"versionstring\":\"Nextcloud 13.0.2\",\"url\":\"https:\\\/\\\/download.nextcloud.com\\\/server\\\/releases\\\/nextcloud-13.0.2.zip\",\"web\":\"https:\\\/\\\/docs.nextcloud.com\\\/server\\\/13\\\/admin_manual\\\/maintenance\\\/upgrade.html\",\"autoupdater\":\"1\"}",
            "lastupdatedat": "1526140805",
            "moveavatarsdone": "yes",
            "oc.integritycheck.checker": "[]",
            "previewsCleanedUp": "1",
            "public_caldav": "calendar\/share.php",
            "public_calendar": "calendar\/share.php",
            "public_documents": "documents\/public.php",
            "public_files": "files_sharing\/public.php",
            "public_gallery": "gallery\/public.php",
            "public_webdav": "dav\/appinfo\/v1\/publicwebdav.php",
            "remote_ampache": "media\/remote.php",
            "remote_caldav": "dav\/appinfo\/v1\/caldav.php",
            "remote_calendar": "dav\/appinfo\/v1\/caldav.php",
            "remote_carddav": "dav\/appinfo\/v1\/carddav.php",
            "remote_contacts": "dav\/appinfo\/v1\/carddav.php",
            "remote_contactthumbnail": "contacts\/thumbnail.php",
            "remote_core.css": "\/core\/minimizer.php",
            "remote_core.js": "\/core\/minimizer.php",
            "remote_dav": "dav\/appinfo\/v2\/remote.php",
            "remote_files": "dav\/appinfo\/v1\/webdav.php",
            "remote_filesync": "files\/appinfo\/filesync.php",
            "remote_webdav": "dav\/appinfo\/v1\/webdav.php",
            "repairlegacystoragesdone": "yes",
            "scss.variables": "aaff6e43fbd240120614d07e637a5b3c",
            "shareapi_allow_resharing": "no",
            "updater.secret.created": "1526140907",
            "vendor": "nextcloud"
        },
        "dav": {
            "buildCalendarSearchIndex": "yes",
            "enabled": "yes",
            "installed_version": "1.4.6",
            "types": "filesystem"
        },
        "deck": {
            "enabled": "no",
            "installed_version": "0.3.1",
            "types": ""
        },
        "documents": {
            "enabled": "no",
            "installed_version": "0.16.0",
            "ocsid": "168711",
            "types": ""
        },
        "federatedfilesharing": {
            "enabled": "yes",
            "installed_version": "1.3.1",
            "types": ""
        },
        "federation": {
            "enabled": "yes",
            "installed_version": "1.3.0",
            "types": "authentication"
        },
        "files": {
            "backgroundwatcher_previous_file": "418",
            "backgroundwatcher_previous_folder": "688",
            "cronjob_scan_files": "500",
            "default_quota": "10 GB",
            "enabled": "yes",
            "installed_version": "1.8.0",
            "types": "filesystem"
        },
        "files_downloadactivity": {
            "enabled": "no",
            "installed_version": "1.2.0",
            "types": "filesystem"
        },
        "files_imageviewer": {
            "enabled": "no",
            "installed_version": "1.0"
        },
        "files_mv": {
            "enabled": "no",
            "installed_version": "0.6.0",
            "ocsid": "150271",
            "types": "filesystem"
        },
        "files_odfviewer": {
            "enabled": "no",
            "installed_version": "0.1"
        },
        "files_pdfviewer": {
            "enabled": "yes",
            "installed_version": "1.2.1",
            "types": ""
        },
        "files_sharing": {
            "enabled": "yes",
            "installed_version": "1.5.0",
            "types": "filesystem"
        },
        "files_texteditor": {
            "enabled": "yes",
            "installed_version": "2.5.1",
            "types": ""
        },
        "files_trashbin": {
            "enabled": "yes",
            "installed_version": "1.3.0",
            "types": "filesystem"
        },
        "files_versions": {
            "enabled": "yes",
            "installed_version": "1.6.0",
            "types": "filesystem"
        },
        "files_videoplayer": {
            "enabled": "yes",
            "installed_version": "1.2.0",
            "types": ""
        },
        "files_videoviewer": {
            "enabled": "no",
            "installed_version": "0.1.3",
            "ocsid": "166054",
            "types": ""
        },
        "firstrunwizard": {
            "enabled": "yes",
            "installed_version": "2.2.1",
            "types": "logging"
        },
        "gallery": {
            "enabled": "yes",
            "installed_version": "18.0.0",
            "types": ""
        },
        "galleryplus": {
            "enabled": "no",
            "installed_version": "0",
            "ocsid": "169116",
            "signed": "true",
            "types": ""
        },
        "logreader": {
            "enabled": "yes",
            "installed_version": "2.0.0",
            "ocsid": "170871",
            "relativedates": "1",
            "types": ""
        },
        "lookup_server_connector": {
            "enabled": "yes",
            "installed_version": "1.1.0",
            "types": "authentication"
        },
        "mail": {
            "enabled": "yes",
            "installed_version": "0.7.10",
            "types": ""
        },
        "media": {
            "enabled": "no",
            "installed_version": "0.4.3"
        },
        "music": {
            "enabled": "no",
            "installed_version": "0.3.11",
            "ocsid": "164319",
            "types": "filesystem"
        },
        "nextant": {
            "enabled": "no",
            "installed_version": "1.0.9",
            "types": "filesystem"
        },
        "nextcloud_announcements": {
            "enabled": "yes",
            "installed_version": "1.2.0",
            "types": "logging"
        },
        "notes": {
            "enabled": "yes",
            "installed_version": "2.3.2",
            "ocsid": "160567",
            "types": ""
        },
        "notifications": {
            "enabled": "yes",
            "installed_version": "2.1.2",
            "types": "logging"
        },
        "oauth2": {
            "enabled": "yes",
            "installed_version": "1.1.0",
            "types": "authentication"
        },
        "onlyoffice": {
            "DocumentServerInternalUrl": "",
            "DocumentServerSecret": "",
            "DocumentServerUrl": "",
            "StorageUrl": "",
            "defFormats": "{\"docx\":\"true\",\"xlsx\":\"true\",\"pptx\":\"true\",\"ppsx\":\"true\",\"txt\":\"true\",\"csv\":\"true\"}",
            "enabled": "no",
            "installed_version": "1.3.0",
            "ocsid": "174798",
            "sameTab": "false",
            "skey": "1508661628460",
            "types": "filesystem"
        },
        "ownnote": {
            "enabled": "no",
            "installed_version": "1.0",
            "types": ""
        },
        "ownpad": {
            "enabled": "no",
            "installed_version": "0.6.6",
            "types": ""
        },
        "password_policy": {
            "enabled": "yes",
            "installed_version": "1.3.0",
            "types": ""
        },
        "provisioning_api": {
            "enabled": "yes",
            "installed_version": "1.3.0",
            "types": "prevent_group_restriction"
        },
        "ransomware_protection": {
            "enabled": "yes",
            "installed_version": "1.1.0",
            "types": "logging"
        },
        "richdocuments": {
            "enabled": "no",
            "installed_version": "2.0.8",
            "types": "prevent_group_restriction"
        },
        "search_lucene": {
            "enabled": "no",
            "installed_version": "0.5.3",
            "ocsid": "168709",
            "types": "filesystem"
        },
        "serverinfo": {
            "enabled": "yes",
            "installed_version": "1.3.0",
            "types": ""
        },
        "sharebymail": {
            "enabled": "yes",
            "installed_version": "1.3.0",
            "types": "filesystem"
        },
        "spreed": {
            "enabled": "yes",
            "installed_version": "3.2.0",
            "stun_servers": "[\"stun.nextcloud.com:443\"]",
            "types": "prevent_group_restriction"
        },
        "survey_client": {
            "enabled": "yes",
            "installed_version": "1.1.0",
            "last_report": "{\"id\":\"518e234e350bf\",\"items\":[[\"server\",\"version\",\"9.1.0.16\"],[\"server\",\"code\",\"other\"],[\"server\",\"enable_avatars\",\"yes\"],[\"server\",\"enable_previews\",\"yes\"],[\"server\",\"memcache.local\",\"\\\\OC\\\\Memcache\\\\APCu\"],[\"server\",\"memcache.distributed\",\"none\"],[\"server\",\"asset-pipeline.enabled\",\"no\"],[\"server\",\"filelocking.enabled\",\"yes\"],[\"server\",\"memcache.locking\",\"none\"],[\"server\",\"debug\",\"no\"],[\"php\",\"version\",\"5.6.27\"],[\"php\",\"memory_limit\",536870912],[\"php\",\"max_execution_time\",3600],[\"php\",\"upload_max_filesize\",537919488],[\"database\",\"type\",\"mysql\"],[\"database\",\"version\",\"5.5.52\"],[\"database\",\"size\",46202880],[\"apps\",\"activity\",\"disabled\"],[\"apps\",\"admin_migrate\",\"disabled\"],[\"apps\",\"calendar\",\"1.4.0\"],[\"apps\",\"comments\",\"1.0.0\"],[\"apps\",\"contacts\",\"1.4.0.0\"],[\"apps\",\"dav\",\"1.0.0\"],[\"apps\",\"documents\",\"0.13.1\"],[\"apps\",\"federatedfilesharing\",\"1.0.1\"],[\"apps\",\"federation\",\"1.0.1\"],[\"apps\",\"files\",\"1.5.2\"],[\"apps\",\"files_imageviewer\",\"disabled\"],[\"apps\",\"files_mv\",\"disabled\"],[\"apps\",\"files_odfviewer\",\"disabled\"],[\"apps\",\"files_pdfviewer\",\"0.8.1\"],[\"apps\",\"files_sharing\",\"1.0.0\"],[\"apps\",\"files_texteditor\",\"2.1\"],[\"apps\",\"files_trashbin\",\"1.0.0\"],[\"apps\",\"files_versions\",\"1.3.0\"],[\"apps\",\"files_videoplayer\",\"0.9.8\"],[\"apps\",\"files_videoviewer\",\"disabled\"],[\"apps\",\"firstrunwizard\",\"1.1\"],[\"apps\",\"gallery\",\"15.0.0\"],[\"apps\",\"galleryplus\",\"disabled\"],[\"apps\",\"media\",\"disabled\"],[\"apps\",\"music\",\"disabled\"],[\"apps\",\"notes\",\"disabled\"],[\"apps\",\"notifications\",\"0.3.0\"],[\"apps\",\"ownnote\",\"disabled\"],[\"apps\",\"password_policy\",\"1.0.0\"],[\"apps\",\"provisioning_api\",\"1.0.0\"],[\"apps\",\"search_lucene\",\"disabled\"],[\"apps\",\"serverinfo\",\"1.1.1\"],[\"apps\",\"survey_client\",\"0.1.5\"],[\"apps\",\"systemtags\",\"1.0.2\"],[\"apps\",\"tasks\",\"disabled\"],[\"apps\",\"templateeditor\",\"0.1\"],[\"apps\",\"theming\",\"1.0.1\"],[\"apps\",\"updatenotification\",\"1.0.1\"],[\"apps\",\"updater\",\"disabled\"],[\"apps\",\"user_migrate\",\"disabled\"],[\"apps\",\"workflowengine\",\"1.0.1\"],[\"stats\",\"num_files\",74904],[\"stats\",\"num_users\",7],[\"stats\",\"num_storages\",10],[\"stats\",\"num_storages_local\",1],[\"stats\",\"num_storages_home\",7],[\"stats\",\"num_storages_other\",2],[\"files_sharing\",\"num_shares\",9],[\"files_sharing\",\"num_shares_user\",1],[\"files_sharing\",\"num_shares_groups\",0],[\"files_sharing\",\"num_shares_link\",8],[\"files_sharing\",\"num_shares_link_no_password\",3],[\"files_sharing\",\"num_fed_shares_sent\",0],[\"files_sharing\",\"num_fed_shares_received\",0],[\"files_sharing\",\"permissions_0_1\",\"1\"],[\"files_sharing\",\"permissions_3_1\",\"6\"],[\"files_sharing\",\"permissions_3_15\",\"2\"],[\"encryption\",\"enabled\",\"no\"],[\"encryption\",\"default_module\",\"no\"]]}",
            "last_sent": "1479327824",
            "types": ""
        },
        "systemtags": {
            "enabled": "no",
            "installed_version": "1.3.0",
            "types": "logging"
        },
        "tasks": {
            "enabled": "no",
            "installed_version": "0.1",
            "types": ""
        },
        "templateeditor": {
            "enabled": "no",
            "installed_version": "0.2",
            "types": ""
        },
        "theming": {
            "cachebuster": "2",
            "enabled": "yes",
            "installed_version": "1.4.1",
            "name": "theCloud",
            "types": "logging",
            "url": "https:\/\/cloud.cylancer.net"
        },
        "twofactor_backupcodes": {
            "enabled": "yes",
            "installed_version": "1.2.3",
            "types": ""
        },
        "updatenotification": {
            "enabled": "yes",
            "installed_version": "1.3.0",
            "types": ""
        },
        "updater": {
            "4570e7ca1c5fe868a56deb513d6d26db": "",
            "79a093857e575da22e8a5ca5468559fb": "",
            "enabled": "no",
            "installed_version": "0.6",
            "types": ""
        },
        "user_migrate": {
            "enabled": "no",
            "installed_version": "0.1"
        },
        "workflowengine": {
            "enabled": "yes",
            "installed_version": "1.3.0",
            "types": "filesystem"
        }
    }
}

</details>

#### Client configuration
**Browser:** Firefox, Chromium, Firefox Nightly

**Operating system:** ubuntu

##### Server log (data/nextcloud.log)
<details>
{"reqId":"bw08HuHM03lMBiYBn664","level":3,"time":"2018-05-12T16:12:32+00:00","remoteAddr":"31.16.228.81","user":"root","app":"mail","method":"GET","url":"\/index.php\/apps\/mail\/api\/accounts\/7\/folders","message":"Exception: {\"Exception\":\"Horde_Imap_Client_Exception_ServerResponse\",\"Message\":\"IMAP error reported by server.\",\"Code\":0,\"Trace\":\"#0 \\\/var\\\/www\\\/public\\\/cloud.cylancer.net\\\/htdocs\\\/apps\\\/mail\\\/vendor\\\/pear-pear.horde.org\\\/Horde_Imap_Client\\\/Horde\\\/Imap\\\/Client\\\/Socket.php(4302): Horde_Imap_Client_Socket->_getLine(Object(Horde_Imap_Client_Interaction_Pipeline))\\n#1 \\\/var\\\/www\\\/public\\\/cloud.cylancer.net\\\/htdocs\\\/apps\\\/mail\\\/vendor\\\/pear-pear.horde.org\\\/Horde_Imap_Client\\\/Horde\\\/Imap\\\/Client\\\/Socket.php(4230): Horde_Imap_Client_Socket->_sendCmdChunk(Object(Horde_Imap_Client_Interaction_Pipeline), Array)\\n#2 \\\/var\\\/www\\\/public\\\/cloud.cylancer.net\\\/htdocs\\\/apps\\\/mail\\\/vendor\\\/pear-pear.horde.org\\\/Horde_Imap_Client\\\/Horde\\\/Imap\\\/Client\\\/Socket.php(1751): Horde_Imap_Client_Socket->_sendCmd(Object(Horde_Imap_Client_Interaction_Pipeline))\\n#3 \\\/var\\\/www\\\/public\\\/cloud.cylancer.net\\\/htdocs\\\/apps\\\/mail\\\/vendor\\\/pear-pear.horde.org\\\/Horde_Imap_Client\\\/Horde\\\/Imap\\\/Client\\\/Base.php(1728): Horde_Imap_Client_Socket->_status(Array, 8205)\\n#4 \\\/var\\\/www\\\/public\\\/cloud.cylancer.net\\\/htdocs\\\/apps\\\/mail\\\/vendor\\\/pear-pear.horde.org\\\/Horde_Imap_Client\\\/Horde\\\/Imap\\\/Client\\\/Base.php(4033): Horde_Imap_Client_Base->status(Array, 8205)\\n#5 \\\/var\\\/www\\\/public\\\/cloud.cylancer.net\\\/htdocs\\\/apps\\\/mail\\\/vendor\\\/pear-pear.horde.org\\\/Horde_Imap_Client\\\/Horde\\\/Imap\\\/Client\\\/Base.php(3585): Horde_Imap_Client_Base->_syncStatus('INBOX.Trash')\\n#6 \\\/var\\\/www\\\/public\\\/cloud.cylancer.net\\\/htdocs\\\/apps\\\/mail\\\/lib\\\/IMAP\\\/FolderMapper.php(65): Horde_Imap_Client_Base->getSyncToken('INBOX.Trash')\\n#7 \\\/var\\\/www\\\/public\\\/cloud.cylancer.net\\\/htdocs\\\/apps\\\/mail\\\/lib\\\/Service\\\/MailManager.php(84): OCA\\\\Mail\\\\IMAP\\\\FolderMapper->getFolders(Object(OCA\\\\Mail\\\\Account), Object(Horde_Imap_Client_Socket))\\n#8 \\\/var\\\/www\\\/public\\\/cloud.cylancer.net\\\/htdocs\\\/apps\\\/mail\\\/lib\\\/Controller\\\/FoldersController.php(72): OCA\\\\Mail\\\\Service\\\\MailManager->getFolders(Object(OCA\\\\Mail\\\\Account))\\n#9 [internal function]: OCA\\\\Mail\\\\Controller\\\\FoldersController->index(7)\\n#10 \\\/var\\\/www\\\/public\\\/cloud.cylancer.net\\\/htdocs\\\/lib\\\/private\\\/AppFramework\\\/Http\\\/Dispatcher.php(161): call_user_func_array(Array, Array)\\n#11 \\\/var\\\/www\\\/public\\\/cloud.cylancer.net\\\/htdocs\\\/lib\\\/private\\\/AppFramework\\\/Http\\\/Dispatcher.php(91): OC\\\\AppFramework\\\\Http\\\\Dispatcher->executeController(Object(OCA\\\\Mail\\\\Controller\\\\FoldersController), 'index')\\n#12 \\\/var\\\/www\\\/public\\\/cloud.cylancer.net\\\/htdocs\\\/lib\\\/private\\\/AppFramework\\\/App.php(115): OC\\\\AppFramework\\\\Http\\\\Dispatcher->dispatch(Object(OCA\\\\Mail\\\\Controller\\\\FoldersController), 'index')\\n#13 \\\/var\\\/www\\\/public\\\/cloud.cylancer.net\\\/htdocs\\\/lib\\\/private\\\/AppFramework\\\/Routing\\\/RouteActionHandler.php(47): OC\\\\AppFramework\\\\App::main('OCA\\\\\\\\Mail\\\\\\\\Contro...', 'index', Object(OC\\\\AppFramework\\\\DependencyInjection\\\\DIContainer), Array)\\n#14 [internal function]: OC\\\\AppFramework\\\\Routing\\\\RouteActionHandler->__invoke(Array)\\n#15 \\\/var\\\/www\\\/public\\\/cloud.cylancer.net\\\/htdocs\\\/lib\\\/private\\\/Route\\\/Router.php(297): call_user_func(Object(OC\\\\AppFramework\\\\Routing\\\\RouteActionHandler), Array)\\n#16 \\\/var\\\/www\\\/public\\\/cloud.cylancer.net\\\/htdocs\\\/lib\\\/base.php(998): OC\\\\Route\\\\Router->match('\\\/apps\\\/mail\\\/api\\\/...')\\n#17 \\\/var\\\/www\\\/public\\\/cloud.cylancer.net\\\/htdocs\\\/index.php(37): OC::handleRequest()\\n#18 {main}\",\"File\":\"\\\/var\\\/www\\\/public\\\/cloud.cylancer.net\\\/htdocs\\\/apps\\\/mail\\\/vendor\\\/pear-pear.horde.org\\\/Horde_Imap_Client\\\/Horde\\\/Imap\\\/Client\\\/Socket.php\",\"Line\":4590}","userAgent":"Mozilla\/5.0 (X11; Ubuntu; Linux x86_64; rv:61.0) Gecko\/20100101 Firefox\/61.0","version":"13.0.1.1"}

</details>

##### IMAP log (data/horde_imap.log)
<details>
can not find the horde imap log.
</details>

##### SMTP log (data/horde_smtp.log)
<details>
can not find the horde smtp log.
</details>

##### Browser log
<details>
?
</details>

**Comment by ChristophWurst** [comment]
The Nextcloud mail app offers an extensive logging system to make it easier identifying and tracking down bugs. Please enable [debug mode](https://docs.nextcloud.com/server/13/developer_manual/general/devenv.html#enabling-debug-mode) and set the log [level to debug](https://docs.nextcloud.com/server/13/admin_manual/configuration_server/logging_configuration.html) in your admin settings. Then, try to reproduce your issue and take another look at `data/nextcloud.log`, `data/horde_imap.log` and `data/horde_smtp.log`.

**Comment by ChristophWurst** [comment]
> Then, try to reproduce your issue and take another look at data/nextcloud.log, data/horde_imap.log and data/horde_smtp.log.

Please make sure to remove all sensitive information. Watch out for the IMAP login commands, your password will can be found there (it's base64 encoded).

**Comment by docmcfly** [comment]
Thx for your fast help. It's more complicated than I thought.

My test mailbox abc@... works and generate now hordeimap.log entries. But my private big mailbox generates only the error message in the browser and an horde exception. That made me very puzzled.

I have set the maximum mailbox size of the abc mailbox to 4GB -> the abc mailbox is usable.  It's not the maximum size. The abc mailbox is deleted. It's not help. :(

The configuration of my private big mailbox is okay. The mailbox properties dialog save the configuration. The dialog displays an error if the password or the server are wrong and the saving create an entry in the horder_imap.log file: 
<details>
------------------------------
>> Mon, 14 May 2018 08:06:58 +0000
>> Connection to: imap://mail.cylancer.net:993/
>> Server connection took 0.012 seconds.
S: * OK [CAPABILITY IMAP4rev1 UIDPLUS CHILDREN NAMESPACE THREAD=ORDEREDSUBJECT THREAD=REFERENCES SORT QUOTA IDLE AUTH=PLAIN] Courier-IMAP ready. Copyright 1998-2016 Double Precision, Inc.  See COPYING for distribution information.
C: 1 [INITIAL CLIENT RESPONSE (username: private@xyz.abc]
S: +
C: [secretPassword]
S: 1 OK LOGIN Ok.
>> Command 1 took 0.0045 seconds.
C: 2 CAPABILITY
S: * CAPABILITY IMAP4rev1 UIDPLUS CHILDREN NAMESPACE THREAD=ORDEREDSUBJECT THREAD=REFERENCES SORT QUOTA IDLE AUTH=PLAIN
S: 2 OK CAPABILITY completed
>> Command 2 took 0.0004 seconds.
C: 3 LOGOUT
S: * BYE Courier-IMAP server shutting down
S: 3 OK LOGOUT completed
>> Command 3 took 0.0008 seconds.
</details>

My guess is: 
The exception prevents entries in the horde_imap.log file. 

It is also very interesting that there is nothing noticeable in the server log: 
<details>
May 14 10:26:20 host-167 imapd-ssl: Connection, ip=[2a02:c205:3001:9357::1]
May 14 10:26:20 host-167 imapd-ssl: LOGIN, user=private@xyz.abc, ip=[2a02:c205:3001:9357::1], port=[35118], protocol=IMAP
May 14 10:26:20 host-167 imapd-ssl: LOGOUT, user=private@xyz.abc, ip=[2a02:c205:3001:9357::1], headers=0, body=0, rcvd=1863, sent=17197, time=0, starttls=1
</details>


What is wrong with my private big mailbox. How can I get more information about this exception?

**Comment by ChristophWurst** [comment]
So, the IMAP part looks good from what I can tell from the provided logs. Is it possible that the SMTP connection check fails? Maybe the SMTP connection times out. In that case, you could try to increase the maximum connection timeout: https://github.com/nextcloud/mail/blob/master/doc/admin.md#smtp-timeout

> My guess is:
> The exception prevents entries in the horde_imap.log file.

I don't think that's the case. IIRC the horde log is written via a RAII pattern where a destructor makes sure to flush the logs when the horde client is destroyed/GCed.

**Comment by docmcfly** [comment]
My config.php contains now: 
<details>
  'app.mail.imaplog.enabled' => true,
  'app.mail.smtplog.enabled' => true,
  'app.mail.transport' => 'php-mail',
  'app.mail.imap.timeout' => 600,
  'app.mail.smtp.timeout' => 150,
  'debug' => true
</details>
but the error still persists.

The error message (the exception) has no time delay. Horde can not communicate via imap. Therefore, there are no log entries.

If the properties save and the mail app check the connction data, the imap process needs only 0.0045 seconds. (see the imap log) 

Do you have more ideas?

**Comment by ChristophWurst** [comment]
> Do you have more ideas?

Right now I have no clue what might cause these problems.

**Comment by docmcfly** [comment]
It is possible to patch the horde class and get out more information from this exception?

**Comment by ChristophWurst** [comment]
The easiest way to analyze this is to attach a debugger and set a break point.

**Comment by docmcfly** [comment]
Yippy - I found the solution. I copied my large private mailbox to a new mailbox. Then I removed all folders step by step. 
And at the end I found an empty".trash" folder. The normal content is missing.
The files and folders: "courierimapkeywords", "courierimapuiddb", "cur", "new", "tmp",.... did not exist. 

I fixed my private mailbox. 

Thanks for your help.
