### ISSUE TITLE
Add opt-in features in the advanced search settings for basic search

### ISSUE THREAD

**Issue by HLFH** [nextcloud/mail#9044]
### Is your feature request related to a problem? Please describe.

It would be great to add opt-in features in the advanced search settings for basic search to improve search usability.

### Describe the solution you'd like

Here is how Roundcube does it.

<img width="372" alt="Screenshot 2023-10-31 at 20 51 52" src="https://github.com/nextcloud/mail/assets/2359059/18220abb-882e-4dcb-ac10-8085c032af6a">

### Describe alternatives you've considered

Using Roundcube with Nextcloud? (with this PR: https://github.com/rotdrop/nextcloud-roundcube/pull/18)

### Additional context

Following discussion in: https://github.com/nextcloud/mail/pull/8897#issuecomment-1747393411

**Comment by ChristophWurst** [comment]
@HLFH I'm not sure I understand your request. What features can user opt-in to?

**Comment by nextcloud-command** [comment]
Hi there! It looks like this issue hasn’t seen much activity for a while and might need a bit more information to move forward. If we don’t hear back soon, we may close it to keep things organized. Thanks again for your contributions – we really appreciate it!
