### ISSUE TITLE
Slash command/emoji picker follows system theme instead of NC instance theme 

### ISSUE THREAD

**Issue by nimishavijay** [nextcloud/mail#9054]
### Steps to reproduce

1. Set your system theme to dark mode
2. Set NC theme to light mode
3. Open the slash command/emoji picker in the mail composer

(similar behaviour with system light + NC dark)

### Expected behavior

- [ ] Slash command/emoji picker popup should be the same as the nextcloud theme
- [ ] In light mode the text should be `var(--color-main-text)`

### Actual behavior

| | NC follow system theme | NC light | NC dark |
| -- | -- | -- | -- |
| System light | ![image](https://github.com/nextcloud/mail/assets/52440189/7b21e643-65de-4aa8-955f-f7deb666d078) | ![image](https://github.com/nextcloud/mail/assets/52440189/5ca13580-2022-4abc-9f9a-43fdb429c360) | ![image](https://github.com/nextcloud/mail/assets/52440189/4f555a22-158c-4760-9f3c-0ec04502437d)
| System dark | ![image](https://github.com/nextcloud/mail/assets/52440189/3640d147-7e18-4d7c-b377-183841a88205) | ![image](https://github.com/nextcloud/mail/assets/52440189/29d68843-cddf-420e-a7b6-a7843f951f76) | ![image](https://github.com/nextcloud/mail/assets/52440189/f3d3e584-322a-4395-a24f-1d3257ade9cd) |

### PHP engine version

None

### Web server

None

### Database

None

**Comment by ChristophWurst** [comment]
cc @hamza221

**Comment by ChristophWurst** [comment]
This issue might have a wider scope: https://github.com/nextcloud/mail/issues/6378
