### ISSUE TITLE
QuotaJob: Division by zero

### ISSUE THREAD

**Issue by kesselb** [nextcloud/mail#9061]
### Steps to reproduce

1. Run the quota job
2. See a division by zero error
3. :disappointed: 

### Expected behavior

No division by zero ;)

### Actual behavior

From a customer log:

```json
{
  "reqId": "",
  "level": 3,
  "time": "October 31, 2023 04:02:52",
  "remoteAddr": "",
  "user": "",
  "app": "core",
  "method": "",
  "url": "--",
  "message": "Error while running background job (class: OCA\\Mail\\BackgroundJob\\QuotaJob, arguments: Array\n(\n    [accountId] => someAccount\n)\n)",
  "userAgent": "--",
  "version": "27.1.2.2",
  "exception": {
    "Exception": "DivisionByZeroError",
    "Message": "Division by zero",
    "Code": 0,
    "Trace": [
      {
        "file": "/var/www/html/apps/mail/lib/BackgroundJob/QuotaJob.php",
        "line": 98,
        "function": "calculateAndSetQuotaPercentage",
        "class": "OCA\\Mail\\Account",
        "type": "->"
      },
      {
        "file": "/var/www/html/lib/public/BackgroundJob/Job.php",
        "line": 81,
        "function": "run",
        "class": "OCA\\Mail\\BackgroundJob\\QuotaJob",
        "type": "->"
      },
      {
        "file": "/var/www/html/lib/public/BackgroundJob/TimedJob.php",
        "line": 103,
        "function": "start",
        "class": "OCP\\BackgroundJob\\Job",
        "type": "->"
      },
      {
        "file": "/var/www/html/lib/public/BackgroundJob/TimedJob.php",
        "line": 93,
        "function": "start",
        "class": "OCP\\BackgroundJob\\TimedJob",
        "type": "->"
      },
      {
        "file": "/var/www/html/cron.php",
        "line": 152,
        "function": "execute",
        "class": "OCP\\BackgroundJob\\TimedJob",
        "type": "->"
      }
    ],
    "File": "/var/www/html/apps/mail/lib/Account.php",
    "Line": 240,
    "message": "Error while running background job (class: OCA\\Mail\\BackgroundJob\\QuotaJob, arguments: Array\n(\n    [accountId] => someAccount\n)\n)",
    "exception": {},
    "CustomMessage": "Error while running background job (class: OCA\\Mail\\BackgroundJob\\QuotaJob, arguments: Array\n(\n    [accountId] => someAccount\n)\n)"
  }
}
```

### Mail app version

They are using Nextcloud 27.
Unsure about the mail app version.

### PHP engine version

PHP 8.1

### Web server

Apache (supported)

### Database

MySQL

**Comment by kesselb** [comment]
cc @ChristophWurst @miaulalala

**Comment by ChristophWurst** [comment]
> ```json
> "time": "October 31, 2023
> ```

spooky

**Comment by joshtrichards** [comment]
Looks like we set the limit to `0` if there isn't a quota: 

https://github.com/nextcloud/mail/blob/fcfaa2c525cac651b4364066d117e63a29855e87/lib/Service/MailManager.php#L605-L617

https://github.com/nextcloud/mail/blob/fcfaa2c525cac651b4364066d117e63a29855e87/lib/Service/Quota.php#L38-L49

And this flows through to here:

https://github.com/nextcloud/mail/blob/fcfaa2c525cac651b4364066d117e63a29855e87/lib/Account.php#L220-L223

Where we do bad math.

Might just make sense to add simple 0 check right at the bad math (setting the quota percentage to, in fact, 0 in the end - which for some reason makes me laugh).

But also might be worth a deeper look to see if we're making any similar assumptions elsewhere.
