### ISSUE TITLE
Slow tag orphan cleanup due to missing index

### ISSUE THREAD

**Issue by ChristophWurst** [nextcloud/mail#9160]
### Steps to reproduce

1. Run `SELECT mt.id FROM oc_mail_messages m
    RIGHT JOIN oc_mail_message_tags mt ON mt.imap_message_id = m.message_id
    WHERE m.message_id IS NULL;`

### Expected behavior

Fast result

### Actual behavior

Slow result

### PHP engine version

None

### Web server

None

### Database

None

### Additional info

Suggested index is
```sql
create index oc_mail_messages_msgid_idx
    on oc_mail_messages (`message_id(128)`);
```

**Comment by miaulalala** [comment]
Applied on a large instance, worked well.

**Comment by nickvergessen** [comment]
Correct syntax seems to be:
```sql
ALTER TABLE `oc_mail_messages` ADD INDEX `oc_mail_messages_msgid_idx` (`message_id`(128)); 
```

**Comment by ChristophWurst** [comment]
Adding the index can take a few minutes. Let's use the optional indices API and not add the index in a migration. But let's still add the index to the existing migrations so it's added for new installations.

**Comment by nickvergessen** [comment]
> Adding the index can take a few minutes. Let's use the optional indices API and not add the index in a migration. 

4.22 seconds with 1.28m mails here. Sure you can try the new API, but we did worse things in the past

**Comment by ChristophWurst** [comment]
It took 5mins for an affected customer
