### ISSUE TITLE
Cross link app settings to account settings for discoverability

### ISSUE THREAD

**Issue by ChristophWurst** [nextcloud/mail#9161]
### Is your feature request related to a problem? Please describe.

As a new Nextcloud user I'm trying to change settings of my mail account. I open the menu in the bottom left and see a settings modal thanks to https://github.com/nextcloud/mail/issues/6896. However, it doesn't allow me to change settings of my account.

### Describe the solution you'd like

List the accounts in the app settings navigation and offer a way to jump into the account settings dialog. This would close the app settings modal and open the account settings modal.

### Describe alternatives you've considered

N/a

### Additional context

@jancborchardt as discussed.

@nimishavijay we will need some specs/mockup for how accounts should be listed in the app settings modal and what kind of elements trigger the cross links. E.g. buttons, pencil icon, etc.

**Comment by jancborchardt** [comment]
A simple entry at the bottom of the navigation inside the modal would work for both cases.
If there are multiple accounts, then in the Mail settings modal we need to either have:
- Multiple entries: Might be an issue with text length and naming if we include the email address
- An action menu, if possible

![image](https://github.com/nextcloud/mail/assets/925062/4e7016c6-619e-4507-8d98-8fd61cf25975)
