### ISSUE TITLE
Can't open E-Mail Editor in Firefox Browser

### ISSUE THREAD

**Issue by davidpr78** [nextcloud/mail#9173]
### Steps to reproduce

1. Click on send Mail in Firefox Browser

### Expected behavior

The mail editor opens and you can start writing

### Actual behavior

The mail editor window does not open.

### Mail app version

3.5.0

### PHP engine version

None

### Web server

None

### Database

None

**Comment by GretaD** [comment]
Hello,

do you see any error on your web console when you click "New message"? What about in your nextcloud log?

**Comment by davidpr78** [comment]
Hi Greta,
I'm a nextcloud customer. It seems that it is a problem with my Nextcloud or browser settings.
Thanks

**Comment by Forsskieken** [comment]
Hi there,

I have the same issue, the mail app is at version 3.5.5 
In Chrome I have no issue and in Firefox the popup doesn't show.  I allowed popups in the Firefox settings

![image](https://github.com/nextcloud/mail/assets/3041025/c54fb429-9837-464c-9cd1-2f654c5ee274)
