### ISSUE TITLE
Add filter shortcuts (like Has attachment, Last 7 days and From me)

### ISSUE THREAD

**Issue by GretaD** [nextcloud/mail#9182]
### Is your feature request related to a problem? Please describe.

To make mail app more efficient we should add some more filter on the advance search modal.
3 proposals would be:

1. Has attachment, 
2. Last 7 days  
3. From me

**Comment by GretaD** [comment]
Google has:
1. Has the words
2. Doesnt have
3. Size - grater than - MB
4. Has attachment
5. Don't include chats
Outlook has:
1. Has attachment
2. This week
3. Sent to me, or cc: me

I will start working on the 3 mentioned on our description and we can move on from there

**Comment by ChristophWurst** [comment]
We only add what our search backend can currently do.

**Comment by ChristophWurst** [comment]
![image](https://github.com/nextcloud/mail/assets/1374172/77925c57-5295-4940-999b-86403d44e41a)

What if we add the shortcuts here? Buried in the advanced search menu they are not really a shortcut

**Comment by GretaD** [comment]
> ![image](https://private-user-images.githubusercontent.com/1374172/321525957-77925c57-5295-4940-999b-86403d44e41a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTI4MjU2MjUsIm5iZiI6MTcxMjgyNTMyNSwicGF0aCI6Ii8xMzc0MTcyLzMyMTUyNTk1Ny03NzkyNWM1Ny01Mjk1LTQ5NDAtOTk5Yi04NjQwM2Q0NGU0MWEucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDQxMSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA0MTFUMDg0ODQ1WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9Yzk1NjFiZWNlZTY1MzJkYTdjM2NhNGIyYzVhZDRkOWY0ODAxMGY1Yzc4YTQ0MzFiOGE2ZmYyOTI5ZGUyM2ZiMCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.v19hLghkOnwPJ0eN6GrL-yXyYVkLFIT60ThFIEZdDZk)
> 
> What if we add the shortcuts here? Buried in the advanced search menu they are not really a shortcut

yes, thats what i have done with the last fixup. Now i just need to make the buttons work :)
