### ISSUE TITLE
more compact folder tree

### ISSUE THREAD

**Issue by da-anda** [nextcloud/mail#9183]
### Is your feature request related to a problem? Please describe.

when on a desktop system, the sidepanel is pretty much not usable if you
a) have multiple email accounts
b) work with many folders to organize stuff over multiple accounts

because the folder nodes in the tree are waaaaaaaaaaay to large (especially when browsing/expanding folders). So you can't find anything without scrolling for ages. And if you have multiple nesting levels, it is veeeery hard to tell which folder belongs to which level as they are not indented (only first level is indented)

### Describe the solution you'd like

either make the folder nodes of each mailbox in general smaller (less top/bottom padding and margins), or provide a setting for a more "desktop" like folder view, compared to the default "touch" style.

### Describe alternatives you've considered

I tried to customize it via custom CSS, but this is a huge PITA to do. Size values and offsets are hardcoded with fixed values (no CSS variables) all over the place for dozens of nested HTML nodes, icons and what not.

**Comment by Pahl-IT** [comment]
+1

Im also struggeling with the customization of the Mail App.

I should be more lightweight.

I try to make everything smaller, so you have more overview, but its not easy.

**Comment by ChristophWurst** [comment]
The navigation and other elements will be more compact with Mail v4 / Nextcloud 30

**Comment by Pahl-IT** [comment]
Is there an ETA for that?

**Comment by ChristophWurst** [comment]
https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule

**Comment by da-anda** [comment]
the spacing is way better now in the new version, thanks much (it seems to get bloated though the second you try to drag a mail into a specific archive folder).
However, a clear indication of the nesting level of folders (also mentioned in the description above) is still missing. Only the first level is indented when expanding the folder, every sublevel has the same indention and there is no way for you to tell which folder belongs to which level anymore. Should I create a separate issue for this, or would you like to keep this issue open?

**Comment by ChristophWurst** [comment]
Create a separate issue. Multi level hieararchy should work since https://github.com/nextcloud/mail/pull/3147

**Comment by da-anda** [comment]
you can navigate, but the indention is missing for sublevels

**Comment by da-anda** [comment]
looks like there already is a ticket, but it does not have a good description of the actually issue at hand https://github.com/nextcloud/mail/issues/8812
