### ISSUE TITLE
When moving mail to folder, allow folder search and favourites folders

### ISSUE THREAD

**Issue by pedroponte** [nextcloud/mail#9187]
### Is your feature request related to a problem? Please describe.

Improving the mail move to folder functionality and useability

### Describe the solution you'd like

It would help a lot if the move mail to folder functionality would allow searching for a specific folder and also have a tab to show favourites folders, frequently used or all.
This is common in outlook, nine mail etc.

**Comment by pedroponte** [comment]
similar to https://github.com/nextcloud/mail/issues/7536

**Comment by ChristophWurst** [comment]
> similar to #7536

what is the difference?

**Comment by ChristophWurst** [comment]
Added to the other ticket :+1: 

Closing as duplicate
