### ISSUE TITLE
emails are tagged as important which should not

### ISSUE THREAD

**Issue by damnms** [nextcloud/mail#9188]
### Steps to reproduce

1. i dont know, i installed nc for testing. it has very likely something to do with the cron because thats the only thing that is running, and suddenly again, some emails are marked as important even tho i a2dissite nextcloud

### Expected behavior

no important flagged emails

### Actual behavior

some emails are marked as important

### Mail app version

thunderbird latest

### Mailserver or service

postfix/dovecot

### Operating system

debian stable

### PHP engine version

PHP 8.2

### Web server

Apache (supported)

### Database

PostgreSQL

**Comment by ChristophWurst** [comment]
Disable cron for a clean shutdown of Nextcloud

**Comment by damnms** [comment]
when i disable cron, then i get big fat warnings in the dashboard telling me i should configure my system correctly as described in the guide. the guide says cron is the recommended way to do that. now i should disable cron?

**Comment by ChristophWurst** [comment]
> even tho i a2dissite nextcloud

you either run nextcloud or you don't. if you run it, run cron. if you don't run it, don't run cron.

Please consult https://help.nextcloud.com/c/support/7 for support.

If this app is active and importance classification is turned on, marking messages as important is expected.

**Comment by damnms** [comment]
> you either run nextcloud or you don't.

wt... of course i had it running. but as it starts to psychopatic mark any new email as important, i disabled the apache site but forgot the cron. new messages where again flagged as important so i was very sure its because of the cron.
i did not activate anything in the mail app, its a regular installation. 
i thougth i´ll test nextcloud as alternative to m$ cloud and co. - but after that ticket i start to believe nc is not what i am looking for.

**Comment by ChristophWurst** [comment]
Then I must have misunderstood your original report. It sounded like you tested Nextcloud, turned if off and were surprised that is was will running.

https://docs.nextcloud.com/server/latest/user_manual/en/groupware/mail.html#priority-inbox for the feature. It's on by default but can be turned off.

**Comment by damnms** [comment]
i created now https://help.nextcloud.com/t/emails-are-tagged-as-important/177109 
can you explain why it is on by default? i mean, regular messages should not be tagged as important when the sender did not send them as important, shouldnt they?

**Comment by ChristophWurst** [comment]
it was decided that the feature should be opt-out. https://github.com/nextcloud/mail/issues/6390 for the FR of changing that.

importance classification is about whether the email is important to the *recipient*. this is not controlled by the sender. the feature took inspiration from gmail.

**Comment by damnms** [comment]
thanks, i will read that FR
