### ISSUE TITLE
Nextcloud mail 3.5.0 generates invalid smime signature

### ISSUE THREAD

**Issue by gvansanden** [nextcloud/mail#9190]
### Steps to reproduce

1. Set up a mailaccount and add a certificate
2. Send a mail (to self) and smime sign it
3. Look at the mail in the app AND external apps like Thunderbird

### Expected behavior

The signature should be valid

### Actual behavior

The mail is signed with the correct key/cert but the signature is invalid

### Mail app version

3.5.0

### Mailserver or service

Dovecot

### Operating system

Ubuntu 22.04

### PHP engine version

PHP 8.1

### Web server

Apache (supported)

### Database

PostgreSQL

**Comment by joshtrichards** [comment]
Same as #9178?

**Comment by ChristophWurst** [comment]
https://github.com/nextcloud/mail/issues/9178 seems to be about *received* emails, this ticket is about *sent* ones.

**Comment by gvansanden** [comment]
Still here on latest version

**Comment by Sergeij2000** [comment]
The problem still exists in my NC setup (NC 30.0.2, Mail 4.0.7). SMIME-encryption works well, signature generates a faulty hash-value (see screenshots, mail client eM Client)

![Image](https://github.com/user-attachments/assets/94eaf34d-d1d0-41c4-82e7-7b1a7fbcf504)
![Image](https://github.com/user-attachments/assets/70e029b9-ea07-4680-a5f6-4abeb91825b7)

**Comment by ChristophWurst** [comment]
Dear @Sergeij2000,
Thank you very much for your report. It seems this ticket has previously been closed as resolved, so it would be best if you report your findings in a new ticket. Please link this ticket for reference.

**Comment by Sergeij2000** [comment]
https://github.com/nextcloud/mail/issues/10440

**Comment by TruncatedDinoSour** [comment]
bump
