### ISSUE TITLE
master password is requested even if checkbox is unselected

### ISSUE THREAD

**Issue by damnms** [nextcloud/mail#9191]
### Steps to reproduce

1. configure the mail app for auto provisioning
2. click on save

### Expected behavior

no error to appear

### Actual behavior

it asks for master password, even if the checkbox for master password is not selected

### Mail app version

3.5.0

### Mailserver or service

postfix/dovecot

### Operating system

debian 12

### PHP engine version

PHP 8.1

### Web server

Apache (supported)

### Database

PostgreSQL

### Additional info

i am not sure if this is another feature or really a bug, maybe one can shed some light onto that. for me as regular user, it looks like a  bug.

![Bildschirmfoto_2023-12-22_18-38-54](https://github.com/nextcloud/mail/assets/40913090/65fcca20-88b4-49c8-a79e-41f870a35d6e)

**Comment by nagmat84** [comment]
I am also affected by this bug.

**Comment by damnms** [comment]
wondering if there is a simple workaround. i only have 1 week vacation. would love to test nc a bit more.

**Comment by ChristophWurst** [comment]
cc @mickenordin

**Comment by ChristophWurst** [comment]
https://github.com/nextcloud/mail/blob/7bca28e934ceca85b93df33d142a91425a1fd45d/src/components/settings/ProvisioningSettings.vue#L199 is always set, hence the browser asks for the password.

**Comment by ChristophWurst** [comment]
Fix is at https://github.com/nextcloud/mail/pull/9197

**Comment by damnms** [comment]
for me as noob: how can i install this? reinstall the mail app 3.5? i have seen its backported. or can i somehow modify a few files? i guess because its .vue, its somehow processed to produce html/js, right. so probably modifying html/js is not such a good idea?

**Comment by ChristophWurst** [comment]
The patch can't be applied on a production installation

**Comment by damnms** [comment]
i have a testing installation, how can i install it?

**Comment by ChristophWurst** [comment]
https://github.com/nextcloud/mail#development-setup

**Comment by damnms** [comment]
is there any roadmap when this will released? i guess it will be 3.5.1?
