### ISSUE TITLE
Unable to select alias to send from

### ISSUE THREAD

**Issue by beanaroo** [nextcloud/mail#9196]
### Steps to reproduce

1. Add alias to existing account
2. Compose new message
3. Attempt to select alias in "From" dropdown

### Expected behavior

Selecting the alias in the dropdown should work

### Actual behavior

Clicking on the alias in the dropdown has no effect. Unable to send as alias.

### Mail app version

3.5.0

### Mailserver or service

ISP

### Operating system

Linux

### PHP engine version

PHP 8.2

### Web server

Apache (supported)

### Database

PostgreSQL

### Additional info

No errors or warnings produced in backend or frontend, even with debug logging enabled.

**Comment by GretaD** [comment]
I can reproduce this and i have an error:
```
vue.runtime.esm.js:4609 [Vue warn]: Duplicate keys detected: '1'. This may cause an update error.

found in

---> <VueSelect>
       <NcSelect>
         <Composer> at src/components/Composer.vue
           <NcModal>
             <NewMessageModal> at src/components/NewMessageModal.vue
               <NcContent>
                 <Home> at src/views/Home.vue
```
