### ISSUE TITLE
Connect a deck card to an email

### ISSUE THREAD

**Issue by yougotborked** [nextcloud/mail#9204]
### Is your feature request related to a problem? Please describe.

My Band has a shared email account where we get gig requests. We end up having to manually create deck cards for each request and then track them and update them through the booking process

### Describe the solution you'd like

1. Let me share the imap mail account with multiple users/a group
2. Let me create or connect a deck card to an email thread in some way.

**Comment by ChristophWurst** [comment]
Dup of https://github.com/nextcloud/mail/issues/572 and https://github.com/nextcloud/mail/issues/5900
