### ISSUE TITLE
Check indices on mail_messages table

### ISSUE THREAD

**Issue by JohannesGGE** [nextcloud/mail#9245]
### Steps to reproduce

1. Check the db scheme of oc_mail_messages
2. See `mail_messages_mb_id_uid` as index on `['uid','mailbox_id']` and no `mail_msg_sent_idx` on `sent_at`.
3. Before this migration:
https://github.com/nextcloud/mail/blob/f50605daaa5e21fde1e46abd645b22589b628276/lib/Migration/Version1130Date20220412111833.php#L160-L165 
There was a unique index `mail_msg_mb_uid_idx` on `['uid','mailbox_id']` and a normal index `mail_msg_sent_idx` on `sent_at`.
4. Question: Should be `mail_messages_mb_id_uid` made unique and `mail_msg_sent_idx` added to improve performance?

### Expected behavior

Better performance with `mail_messages_mb_id_uid` as unique index and `mail_msg_sent_idx` as index?

### Actual behavior

worse performance?

### Mail app version

main

### PHP engine version

None

### Web server

None

### Database

None

### Additional info

Occurred in https://github.com/nextcloud/mail/pull/9206

**Comment by JohannesGGE** [comment]
`mail_msg_sent_idx` on `sent_at` seems to make no big difference because there is the index `mail_msg_thrd_root_snt_idx` on `[mailbox_id,thread_root_id,sent_at]`. I would leave it like it is, without `mail_msg_sent_idx`.


But I see no reason not to make `mail_messages_mb_id_uid` unique here.

**Comment by ChristophWurst** [comment]
Done with https://github.com/nextcloud/mail/pull/9295
