### ISSUE TITLE
Update to 3.5.3 updating indices causes error in occ

### ISSUE THREAD

**Issue by JRGonz** [nextcloud/mail#9247]
### Steps to reproduce

1. Update mail app to 3.5.3
2. Go to admin page and see instructions to add indices. 
3. Run occ db:add-missing-indices and receive error. 

### Expected behavior

The indices should be added without issue.

### Actual behavior

After upgrading the mail app to 3.5.3 the nextcloud admin page states that the indices must be added. When running the occ command this happens: 

---
Adding additional mail_messages_msgid_idx index to the oc_mail_messages table, this can take some time...

In ExceptionConverter.php line 119:
                                                                                                   
An exception occurred while executing a query: SQLSTATE[42000]: Syntax error or access violation: 1071 Specified key was too long; max key length is 3072 bytes                                 
                                                                                                   

In Exception.php line 30:
                                                                                                   
SQLSTATE[42000]: Syntax error or access violation: 1071 Specified key was too long; max key length is 3072 bytes                                                                                
                                                                                                   

In Connection.php line 72:
                                                                                                   
SQLSTATE[42000]: Syntax error or access violation: 1071 Specified key was too long; max key length is 3072 bytes 
---

This is a fairly new issue and I have been using the mail app for a long long time and have never come across this. I can't seem to find anything concrete to fix it either other than using utf8mb4 which I have been forever. Maybe this is an issue with the actual mail app? 

### Mail app version

3.5.3

### Mailserver or service

dovecot/postfix

### Operating system

debian (bookworm)

### PHP engine version

PHP 8.2

### Web server

Apache (supported)

### Database

MySQL

### Additional info

This happened on two nextcloud servers. Although.. they use the same mysql server. Prior to the update the mail app worked fine and there was no error in the admin page. Currently it seems as though the mail app is working but I haven't tested it extensively yet.

**Comment by JRGonz** [comment]
I disabled the mail app just to see if db:add-missing-indices works without issue and the administration page clears up and it seems to have done so. Re-enabling mail caused the same error(s) to reoccur.

**Comment by JRGonz** [comment]
So I upgraded to 28.0.1 for one of the servers and it seems to have worked without a problem. The indices updated. Now I am bumping into another issue but that is unrelated to this one. So I guess the problem lies in the mail update + older ver of nextcloud?

**Comment by ChristophWurst** [comment]
Sounds like it. We have to check if older versions take the length option into account.

**Comment by bjoernv** [comment]
A work-around is to create the index manually:
`CREATE INDEX mail_messages_msgid_idx ON oc_mail_messages (message_id(128));`

**Comment by ChristophWurst** [comment]
@bjoernv did you run into this with 27, too?

**Comment by bjoernv** [comment]
> @ChristophWurst: @bjoernv did you run into this with 27, too?
Yes, 27.1.5.

**Comment by JohannesGGE** [comment]
The length option we use is added with 28:

https://github.com/nextcloud/server/blob/11ed33a4e0615c4cee5e36c516b4001a64e7c5b4/lib/public/DB/Events/AddMissingIndicesEvent.php#L44-L50

**Comment by ChristophWurst** [comment]
https://github.com/nextcloud/server/blob/81d49265c68aad15541d2bbd149e2d15edc96eb6/core/Command/Db/AddMissingIndices.php#L97

vs

https://github.com/nextcloud/server/blob/11ed33a4e0615c4cee5e36c516b4001a64e7c5b4/core/Command/Db/AddMissingIndices.php#L98

https://github.com/nextcloud/server/commit/00d483585bf7bdfced0c78f35603266c628d683a is missing.

This is tricky …

**Comment by ChristophWurst** [comment]
If anyone is still on 27 please try applying https://github.com/nextcloud/mail/pull/9254 as patch and run occ again.
