### ISSUE TITLE
Changing the alias in the "from" field is not possible

### ISSUE THREAD

**Issue by thrommel1980** [nextcloud/mail#9258]
### Steps to reproduce

1. Choose "New Mail"
2. When I click in the "from" field, I see the selection of the two aliases stored. If I click on the second one, it is not selected and the first one remains.

### Expected behavior

Since then, it has been possible to change aliases

### Actual behavior

Pre-selected alias remains

### Mail app version

3.5.4

### Operating system

Nextcloud 28.0.1

### PHP engine version

PHP 8.1

### Web server

Nginx

### Database

MariaDB

**Comment by GretaD** [comment]
I switched between aliases and i can change them and send an email without any issues. The setup is same as on the ticket, the difference is that im on NC29th.

![Screenshot from 2024-01-22 10-42-13](https://github.com/nextcloud/mail/assets/12728974/98c8d1de-86f0-43f3-a8ed-dd857642682f)
![Screenshot from 2024-01-22 10-41-26](https://github.com/nextcloud/mail/assets/12728974/a815ab91-d99d-4515-9445-fa998c10616f)
![Screenshot from 2024-01-22 10-43-59](https://github.com/nextcloud/mail/assets/12728974/0f4788ec-4ae6-4933-8216-11a1834d4277)

**Comment by ChristophWurst** [comment]
Possibly fixed by https://github.com/nextcloud/mail/pull/9208 and missing the backport

**Comment by GretaD** [comment]
> Possibly fixed by #9208 and missing the backport

fixed. please upgrade when the next patch release is released
