### ISSUE TITLE
The Mail app still showing IMAP emails that are already deleted on the server

### ISSUE THREAD

**Issue by DagNygren** [nextcloud/mail#9259]
### Steps to reproduce

1.Delete some IMAP emails from your desktop client
2.Check the emails in Newtcloud
3.Still see the deleted emails in the listing for that folder

### Expected behavior

The emails should disappear from the Nextcloud app as they do not exist any more

### Actual behavior

Deleted emails still hanging around

### Mail app version

3.5.4

### Mailserver or service

Dovecot

### Operating system

Linux

### PHP engine version

PHP 8.2

### Web server

Apache (supported)

### Database

MySQL

**Comment by joshtrichards** [comment]
Duplicate of #9168
