### ISSUE TITLE
Support for right click on the message list to bring a drop down menu

### ISSUE THREAD

**Issue by vagner-dias** [nextcloud/mail#9268]
### Is your feature request related to a problem? Please describe.

The Files app allows right-clicking in the file list, triggering a dropdown menu. However, the Mail app lacks this functionality. To enhance user experience, it would be beneficial for the Mail app to behave similarly to the Files app, displaying a dropdown menu when users right-click on a message.

**Comment by ChristophWurst** [comment]
https://nextcloud-vue-components.netlify.app/#/Components/NcListItems?id=nclistitem is used for the list of threads. I think this should be solved upstream. Could you file a feature request in https://github.com/nextcloud-libraries/nextcloud-vue/ please?

**Comment by vagner-dias** [comment]
> https://nextcloud-vue-components.netlify.app/#/Components/NcListItems?id=nclistitem is used for the list of threads. I think this should be solved upstream. Could you file a feature request in https://github.com/nextcloud-libraries/nextcloud-vue/ please?

Done >>  https://github.com/nextcloud-libraries/nextcloud-vue/issues/5122

**Comment by ChristophWurst** [comment]
Thank you
