### ISSUE TITLE
Error 504 overtime

### ISSUE THREAD

**Issue by MILLERMPGH** [nextcloud/mail#9277]
### Steps to reproduce

1. We start on the dashboard
2. when i click on the Mail app the loading window opens 
3. after seconds the screen show´s me "504" overtime 

### Expected behavior

Should open the Mail app

### Actual behavior

Not possible to enter the Mail app

### PHP engine version

None

### Web server

None

### Database

None

**Comment by ChristophWurst** [comment]
> 504 Gateway Timeout
>    The server was acting as a gateway or proxy and did not receive a timely response from the upstream server.

Check any proxy or nginx using php-fpm. Consult https://help.nextcloud.com/c/support/7 for support.
