### ISSUE TITLE
mailto link opens blank window

### ISSUE THREAD

**Issue by Solar-Simon** [nextcloud/mail#9281]
### Steps to reproduce

1. open a mailto Link: [mailto:name@domain.org?subject=Subject&body=Hello%20World](mailto:name@domain.org?subject=Subject&body=Hello%20World)
2. Choose nextcloud Mail to open
3. See the blank window

### Expected behavior

1. open a mailto Link: [mailto:name@domain.org?subject=Subject&body=Hello%20World](mailto:name@domain.org?subject=Subject&body=Hello%20World)
2. Choose nextcloud Mail to open
6. New Message with mailto-data will appear

### Actual behavior

1. open a mailto Link: [mailto:name@domain.org?subject=Subject&body=Hello%20World](mailto:name@domain.org?subject=Subject&body=Hello%20World)
2. Choose nextcloud Mail to open
3. See the blank window
4. click outside of the box
5. click "New message", "Discard changes" window will open, click "Continue editing message"
6. New Message with mailto-data will appear

### Mail app version

3.5.5

### Operating system

Windows, Browser Firefox

### PHP engine version

None

### Web server

None

### Database

None

**Comment by ChristophWurst** [comment]
![image](https://github.com/nextcloud/mail/assets/1374172/fcc47127-f504-446d-abfa-bca3cd9d59af)

can confirm
