### ISSUE TITLE
Action menu on envelope and threads is broken

### ISSUE THREAD

**Issue by GretaD** [nextcloud/mail#9282]
### Steps to reproduce

1. Go to mail app
2. Click the action menu of ann envelope or thread
3. Try to find create tasks for example, you will see the right icon, but _move thread_ text
4. Click more actions on threads

### Expected behavior

I have the order correctly

### Actual behavior

![Screenshot from 2024-01-30 18-44-45](https://github.com/nextcloud/mail/assets/12728974/363e9134-cf93-4e83-be16-61b63cc23a7a)
![Screenshot from 2024-01-30 18-44-13](https://github.com/nextcloud/mail/assets/12728974/3956c85b-76d9-4bbc-8d59-10dfb5030c87)

### Mail app version

main

### PHP engine version

None

### Web server

None

### Database

None

### Additional info

This must be the nc/vue 8 migration. I probably tested it before rebase and squash, and something happened there. I dont see any other reason what could have happened.

@st3iny when you found this bug: https://github.com/nextcloud/mail/issues/9279 were you on nc/vue 8? While bisecting this bug with action menu, i found out that your bug was shown for the first time on 0d9e4a8 commit.

**Comment by st3iny** [comment]
I tested this on main before the nc/vue 8 update.

**Comment by st3iny** [comment]
The icons and descriptions seem to be off but I have no idea why.

I only found this: https://github.com/nextcloud-libraries/nextcloud-vue/pull/5178
(But it should be related to the v8 branch AFAICT.)

**Comment by st3iny** [comment]
> @st3iny when you found this bug: https://github.com/nextcloud/mail/issues/9279 were you on nc/vue 8? While bisecting this bug with action menu, i found out that your bug was shown for the first time on https://github.com/nextcloud/mail/commit/0d9e4a8a4feba3cbd7749b13ebc9de3536ddd7de commit.

I also tested the linked issue with nc/vue v8 applied.

**Comment by GretaD** [comment]
> The icons and descriptions seem to be off but I have no idea why.
> 
> I only found this: [nextcloud-libraries/nextcloud-vue#5178](https://github.com/nextcloud-libraries/nextcloud-vue/pull/5178)

thats on 8.6.0, we are on 8.5.0

**Comment by st3iny** [comment]
Right, I even tried to update to 8.6.0 locally and it's still broken so it must be something else.

**Comment by ShGKme** [comment]
I didn't understand from the screenshot, is the only issue - error in the console, or something is working incorrectly?

**Comment by st3iny** [comment]
> I didn't understand from the screenshot, is the only issue - error in the console, or something is working incorrectly?

The icons and button titles are incorrect and mixed up. It seems like the action buttons in the menu are not updated correctly.


For example
- "Move thread" should be "Create task"
- "Archive thread" should be "Create event"
- "Delete thread" has a plus icon
- etc.

**Comment by st3iny** [comment]
https://github.com/nextcloud/mail/assets/1479486/835ecba5-4a1a-4f28-a87e-f9061e789973

**Comment by ShGKme** [comment]
Hmm, I cannot reproduce on `master`...

**Comment by ShGKme** [comment]
I can reproduce
