### ISSUE TITLE
pre-load messages to speed up message display

### ISSUE THREAD

**Issue by vagner-dias** [nextcloud/mail#9293]
### Is your feature request related to a problem? Please describe.

every time a user clicks a message on the message list, it seems that the server makes a request to the server to display the message, which can take some seconds to happen, sometimes several seconds

### Describe the solution you'd like

Taking the GMail web app or Outlook web app as example, the messages could be pre-loaded in the mail app to speed up the display every time the user clicks on it. this will save a lot of time and stress to the user.

**Comment by ChristophWurst** [comment]
Duplicate of https://github.com/nextcloud/mail/issues/4824
