### ISSUE TITLE
Deleted attachment is also sent

### ISSUE THREAD

**Issue by handkerchief333** [nextcloud/mail#9299]
### Steps to reproduce

1. create a message
2. upload a PDF as an attachment
3. delete the attachment by clicking on the X 
4. upload a new PDF
5. send the message
6. both PDFs are attached in the sent message

### Expected behavior

The attachment that was deleted again should not be sent.

### Actual behavior

The previously uploaded and subsequently deleted attachment is also sent.

### Mail app version

3.5.4

### Mailserver or service

Hostpoint

### Operating system

FreeBSD 13.2

### PHP engine version

PHP 8.1

### Web server

Apache (supported)

### Database

MariaDB

### Additional info

Nextcloud 27.1.4

**Comment by GretaD** [comment]
after removing attachment called Eirini. 
the result is this: 

![Screenshot from 2024-02-07 17-22-35](https://github.com/nextcloud/mail/assets/12728974/2e6460a0-fc1b-4de2-86a0-e21f679adb6e)

**Comment by handkerchief333** [comment]
@GretaD Thank you. Does this confirm my report or do I need to provide further information?

**Comment by GretaD** [comment]
> @GretaD Thank you. Does this confirm my report

yes, i can reproduce your issue so no more data is needed
