### ISSUE TITLE
Print e-mail or export as PDF

### ISSUE THREAD

**Issue by handkerchief333** [nextcloud/mail#9301]
### Is your feature request related to a problem? Please describe.

It is currently not possible to print an e-mail via the context menu or to export it as a PDF.

### Describe the solution you'd like

It would be great if you could print every e-mail via the context menu, as with Gmail or Thunderbird, and if there was a similar template.

### Describe alternatives you've considered

Currently, every e-mail that you want to print has to be exported as an eml file and imported back into Thunderbird in order to print it there or save it as a PDF.

**Comment by ChristophWurst** [comment]
Duplicate of https://github.com/nextcloud/mail/issues/8866 and https://github.com/nextcloud/mail/issues/7265
