### ISSUE TITLE
Broken styling in slash command

### ISSUE THREAD

**Issue by hamza221** [nextcloud/mail#9310]
### Steps to reproduce

1. Click on (+ New message)
2. Type / in the composer

### Expected behavior

<img width="310" alt="image" src="https://github.com/nextcloud/mail/assets/40746210/5b41c633-01bc-4b28-ab4a-a13d22b0d637">

### Actual behavior

<img width="595" alt="image" src="https://github.com/nextcloud/mail/assets/40746210/af606efd-f907-4d8e-ab1f-892100d96eae">

### Mail app version

latest main

### PHP engine version

None

### Web server

None

### Database

None

**Comment by JuliaKirschenheuter** [comment]
same as https://github.com/nextcloud/server/issues/43478

**Comment by JuliaKirschenheuter** [comment]
see https://github.com/nextcloud/server/issues/43478#issuecomment-1935903746
