### ISSUE TITLE
Log full of mail messages

### ISSUE THREAD

**Issue by handkerchief333** [nextcloud/mail#9312]
### Steps to reproduce

1. Use mail app
2. Go to /index.php/settings/admin/logging
3. Log list is filled by mail messages

### Expected behavior

Fewer log entries in the same time. So my question is, is something going wrong?

### Actual behavior

Full of messages like this:
```
partial sync 5:Max Muster - Updated message took 0s. 6/6MB memory used
findByIds in INBOX got 0 UIDs but found none
Locking mailbox 73 for changed messages sync
```
![log-messages](https://github.com/nextcloud/mail/assets/41755733/ef98365c-934d-4510-80c4-8a879d00a857)

### Mail app version

3.5.4

### Operating system

FreeBSD 13.2

### PHP engine version

PHP 8.1

### Web server

Apache (supported)

### Database

MariaDB

### Additional info

Is this normal?

**Comment by ChristophWurst** [comment]
It's debug log
