### ISSUE TITLE
Delete collected addresses and attachments when deleting account

### ISSUE THREAD

**Issue by PanCakeConnaisseur** [nextcloud/mail#932]
### Feature Request

At the moment when you delete a mail account that account's attachments and collected addresses are not deleted. The same is true for the aliases, but for this I already created a [pull request](https://github.com/nextcloud/mail/pull/931)

#### Summary

Whenever a user deletes a mail account all of its associated attachments in (table *oc_mail_attachments*) and collected addresses (table *oc_mail_collected_addresses*) should be deleted as well.

#### Implementation

I already checked the code but it seems that `AccountsController` does not have a link to `AdressCollector` or `AttachmentService` which is where afaics the deletion should be implemented. Can you suggest where this deletion should be made instead? Afaics more coupling has to be introduced to make this work.

Or is there some kind of cleanup service that periodically purges old db entries?

**Comment by ChristophWurst** [comment]
done in https://github.com/nextcloud/mail/pull/1411
