### ISSUE TITLE
Envelope layout is broken

### ISSUE THREAD

**Issue by ChristophWurst** [nextcloud/mail#9334]
### Steps to reproduce

1. Set up an account
2. Open a mailbox

### Expected behavior

Working app

### Actual behavior

![image](https://github.com/nextcloud/mail/assets/1374172/e4b70fa2-9522-401d-bb64-13560211e0cc)

### Mail app version

main

### PHP engine version

None

### Web server

None

### Database

None

### Additional info

cc @GretaD @hamza221. this is probably related to the nextcloud/vue upgrade to v8.

**Comment by hamza221** [comment]
caused by https://github.com/nextcloud-libraries/nextcloud-vue/commit/0886575b67aba13d8c3355e0488c39bc5c9456ce#diff-cbfe769e5feb615760691c0a2117d4c118edd07df4961d7b24914ae749b325c3R735

**Comment by ChristophWurst** [comment]
Branch off and first round of pre-releases is scheduled for March 7th: https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule. This is a blocker.

**Comment by ChristophWurst** [comment]
Here we go ~~again~~ still

![Bildschirmfoto vom 2024-07-18 17-02-26](https://github.com/user-attachments/assets/970ce9ce-fb08-468f-9d65-05b55bf370a9)
![Bildschirmfoto vom 2024-07-18 17-02-17](https://github.com/user-attachments/assets/9e030d42-8631-40ea-8c5d-d34fcc783c27)

**Comment by ChristophWurst** [comment]
This is probably related to https://github.com/nextcloud/mail/issues/9334. It's best tackled together.
