### ISSUE TITLE
Hover styles of threads lost

### ISSUE THREAD

**Issue by ChristophWurst** [nextcloud/mail#9338]
### Steps to reproduce

1. Open the app
2. Open a mailbox
3. Hover over a thread

### Expected behavior

https://github.com/nextcloud/mail/assets/1374172/1e7107fe-096a-413c-a4f4-e3778e5f7767

(from a prod instance running 3.5)

### Actual behavior

https://github.com/nextcloud/mail/assets/1374172/a72ebfd1-ee87-4d26-8778-86db2e5511f2

### Mail app version

3.6 (main)

### PHP engine version

None

### Web server

None

### Database

None

### Additional info

Probably caused by the nextcloud/vue 8 upgrade

**Comment by GretaD** [comment]
I cannot reproduce this. I am on main mail, and on latest server.

**Comment by arublov** [comment]
> I cannot reproduce this. I am on main mail, and on latest server.

I confirm this, @ChristophWurst could you please provide more information (maybe custom styles).

**Comment by ChristophWurst** [comment]
Tested again on commit 447a0997d504ed4a3f81f6d506ef0c6a301a3ab6. With my previous custom color and default blue. Light mode and dark mode. It's reproducible for me everywhere. Server is on bb87232882f99c025ef224fb24aefd240b7d0c96

**Comment by ChristophWurst** [comment]
They have returned for me too
