### ISSUE TITLE
Event and task timezone pickers look broken

### ISSUE THREAD

**Issue by ChristophWurst** [nextcloud/mail#9339]
### Steps to reproduce

1. Open the app
2. Open a mailbox
3. Open the actions menu of a thread
4. Click *More actions*
5. Click *Create event*
6. Click the globe icon of the start time
7. Focus the timezone input

### Expected behavior

![image](https://github.com/nextcloud/mail/assets/1374172/1b70ec8d-558c-4871-a36b-319de451c391)

From https://nextcloud-vue-components.netlify.app/#/Components/NcPickers?id=ncdatetimepicker

### Actual behavior

![Bildschirmfoto vom 2024-02-15 13-38-40](https://github.com/nextcloud/mail/assets/1374172/5b3bd3b5-900b-4e7c-a798-dfcc50b68e60)

### Mail app version

3.6

### PHP engine version

None

### Web server

None

### Database

None

**Comment by ChristophWurst** [comment]
Same for tasks

![image](https://github.com/nextcloud/mail/assets/1374172/b4ba4190-f59d-4ae0-b62a-e386163b840d)

**Comment by GretaD** [comment]
this need to be !important,
https://github.com/nextcloud-libraries/nextcloud-vue/blob/bf0be91baa1c33b6e900f65e842d38211ab1cd74/src/components/NcDateTimePicker/NcDateTimePicker.vue#L501

because otherwise, its overlapped by the vue-select dropdown-menu style.

**Comment by ChristophWurst** [comment]
Until this is fixed here.

**Comment by GretaD** [comment]
> Until this is fixed here.

we just need to upgrade to nc/vue 8.7. My Pr is merged and released there

**Comment by GretaD** [comment]
issue is fixed after upgrade to nc/vue 8.10
