### ISSUE TITLE
Misplaced *Loading thread* element

### ISSUE THREAD

**Issue by ChristophWurst** [nextcloud/mail#9343]
### Steps to reproduce

1. Open the app
2. Open a mailbox
3. Click on a thread

### Expected behavior

![Bildschirmfoto vom 2024-02-15 13-59-53](https://github.com/nextcloud/mail/assets/1374172/3dec8bd9-a243-45cf-9b7c-6796b44aac0e)

3.5 prod

### Actual behavior

![Bildschirmfoto vom 2024-02-15 13-58-57](https://github.com/nextcloud/mail/assets/1374172/f8cae8df-9f36-4019-9e2b-9802ea4e6bed)

### Mail app version

3.6 (main)

### PHP engine version

None

### Web server

None

### Database

None

### Additional info

@GretaD @hamza221 nextcloud/vue 8 regression?

**Comment by GretaD** [comment]
yes, most probably a height:100% is missing
