### ISSUE TITLE
Add Folders

### ISSUE THREAD

**Issue by ArchdukeNavaron** [nextcloud/mail#935]
Hi,
it would be great, if you could add folders to your mailbox.
As far as I saw, it's just possible to list all available folders but not to create new ones.

**Comment by ChristophWurst** [comment]
Yes, that would be a great enhancement.

Btw, I'm curious why you didn't use the template for feature requests? Did you see the issue template chooser at https://github.com/nextcloud/mail/issues/new/choose? I'd like to gain some feedback on why people choose to ignore it. Your ticket is fine as it is, I'm just trying to get more structure into our tickets :wink:

**Comment by ArchdukeNavaron** [comment]
Sorry for not useing your template.
I am rather new to Github and just used the "New Issue" Button which didn't give me a choice, as it does now.

**Comment by ChristophWurst** [comment]
No problem. Thank you for your feedback :)

**Comment by ChristophWurst** [comment]
Duplicate of https://github.com/nextcloud/mail/issues/199

**Comment by pwepwe973** [comment]
Hello
Yes, this is it planned in the future because it's been 1 year since this post has been posted and I face the same problem
cordially

**Comment by ChristophWurst** [comment]
It's done and shipped https://github.com/nextcloud/mail/pull/1698
