### ISSUE TITLE
mailto composer does not show content

### ISSUE THREAD

**Issue by jancborchardt** [nextcloud/mail#9363]
### Steps to reproduce

1. Have Nextcloud Mail set up as your mail handler in the browser
2. Click any mailto link like [mailto:test@example.com](mailto:test@example.com)
3. See empty composer

### Expected behavior

Show the composer filled out with the correct mailto info.

### Actual behavior

The composer stays empty. A workaround is to minimize and open the composer again, then everything shows correctly.
![image](https://github.com/nextcloud/mail/assets/925062/5d9c90bd-485a-4cff-9fe2-047bcf2ea44f)

Possibly relevant errors:
```
TypeError: this.accounts is null
    aliases Composer.vue:695
    VueJS 72
[sentry.js:2:90273](https://cloud.nextcloud.com/apps/sentry/js/sentry.js?v=6ce0b0af-1764)
TypeError: this.accounts is null
    aliases Composer.vue:695
    VueJS 3
    Ot Composer.vue:1
    VueJS 65
[sentry.js:2:90273](https://cloud.nextcloud.com/apps/sentry/js/sentry.js?v=6ce0b0af-1764)
TypeError: this.accounts is null
    aliases Composer.vue:695
    VueJS 3
    setAlias Composer.vue:979
    beforeMount Composer.vue:908
    VueJS 63
[sentry.js:2:90273](https://cloud.nextcloud.com/apps/sentry/js/sentry.js?v=6ce0b0af-1764)
TypeError: this.$refs.toLabel is undefined
    mounted Composer.vue:914
    VueJS 2
[sentry.js:2:90273](https://cloud.nextcloud.com/apps/sentry/js/sentry.js?v=6ce0b0af-1764)
```

### Mail app version

Current on cloud.nc

### Mailserver or service

Our own

### PHP engine version

None

### Web server

None

### Database

None

**Comment by ChristophWurst** [comment]
Can confirm on the same instance
![image](https://github.com/nextcloud/mail/assets/1374172/a63dbdf2-cbf9-472d-af2e-d7b976784087)

Another instance with v3.5.6 too works fine

**Comment by arublov** [comment]
Related to : #9281

**Comment by ChristophWurst** [comment]
It did feel like a dejavu. Thanks!

**Comment by ChristophWurst** [comment]
It's probably fixed
