### ISSUE TITLE
MDN Requests are not honoured

### ISSUE THREAD

**Issue by miaulalala** [nextcloud/mail#9365]
### Steps to reproduce

Try to send MDN mail and see that it doesn't request a read receipt

### Expected behavior

MDN request is added to the mail

### Actual behavior

MDN request is not added to the mail as the value is always `false`:

https://github.com/nextcloud/mail/blob/7109f998fa34e1920b917c1fb1e8859b957ba112/lib/Service/MailTransmission.php#L323-L336

### Mail app version

3.6.0-alpha3

### PHP engine version

PHP 8.2

### Web server

Apache (supported)

### Database

MySQL

**Comment by ChristophWurst** [comment]
@miaulalala was this broken between v3.5 and v3.6? That would make it a potential blocker. Asking because of the assigned milestone. https://github.com/nextcloud/groupware/blob/main/processes/milestones.md#apps

**Comment by miaulalala** [comment]
> @miaulalala was this broken between v3.5 and v3.6? That would make it a potential blocker. Asking because of the assigned milestone. [nextcloud/groupware@`main`/processes/milestones.md#apps](https://github.com/nextcloud/groupware/blob/main/processes/milestones.md?rgh-link-date=2024-02-28T07%3A34%3A33Z#apps)

I'm not sure, I think this has been broken for a while. Stable3.4 has it too:
https://github.com/nextcloud/mail/blob/stable3.4/lib/Service/MailTransmission.php#L332

**Comment by ChristophWurst** [comment]
Indeed seems to be missing since https://github.com/nextcloud/mail/commit/49470b953023d26704de517ea48be1516773bb05.

So not a blocker for 3.6 but still a high priority fix.
