### ISSUE TITLE
Envelope needs whitespace for empty div.list-item__extra element

### ISSUE THREAD

**Issue by ChristophWurst** [nextcloud/mail#9444]
### Steps to reproduce

1. Open a mailbox

### Expected behavior

Good design

### Actual behavior

![image](https://github.com/nextcloud/mail/assets/1374172/3d39f7b0-3c56-4635-8d0a-8eb7a6b9aae8)

### Mail app version

3.6.x

### PHP engine version

None

### Web server

None

### Database

None

**Comment by ChristophWurst** [comment]
It's coming from https://github.com/nextcloud/mail/blob/ca153f5a7a8de14c859f0cd55213e1a9e48e1758/src/components/Envelope.vue#L1023.

**Comment by GretaD** [comment]
I think this is outdated because with the new nc/vue changes the list-item__extra is shown on the right side and not below(as a 4th line)
