### ISSUE TITLE
Make sending / receiving Mail optional

### ISSUE THREAD

**Issue by ulph0** [nextcloud/mail#9449]
### Is your feature request related to a problem? Please describe.

Now scheduled sending of Emails is possible. I tried to use it confronted me with this:
- i have to use nextcloud as incoming mail client to use it to send scheduled email which confronted me with more problems:
- my raspberry is to small to handle my big amount of email
- nextcloud mail does strange things with my mail and thjeir priority
- i already have webmail clients for each of my mail account
- i just need the possibitity to send sheduled mail.

### Describe the solution you'd like

Make sending / receiving of Mail optional as i can do it with my E-Mail-Client (Evolution). Then i could create for each of my accounts a send-only Setup in Nextcloud.

### Describe alternatives you've considered

I don't know an alternative. Maybe a nextcloud which don't do strange things to Mails and tzheir priority and has very defensive default settings (no automatic pulling of emails, very limited number of puilled emails (best  0, maximum 10) per email-check, no changes to pulled emails on imap setrver) could also help.

**Comment by ChristophWurst** [comment]
I don't think this app can support the use case.

**Comment by ulph0** [comment]
> I don't think this app can support the use case.

I don't think that either. That is the reason for my feature request :)

**Comment by small1** [comment]
Better with a dedicated app for this. Mailsender/mailinglist/script.  I havent seen any changed to priorities in my mail box  If you have open a separate ticket for it.

**Comment by ChristophWurst** [comment]
Realistically this won't be added to the app, so I'm closing the feature request.

**Comment by ulph0** [comment]
:'(

**Comment by ChristophWurst** [comment]
Could you please elaborate?

**Comment by ulph0** [comment]
> Could you please elaborate?

if you want. that emoji was an expression of sadness. it's years ago i sent the feature request for scheduled sending. then it was there and i was happy. then after half a year of writing this ticket i mentioned that i can't use the scheduled sending without letting nextcloud access my imap account. what i  even tried but what it was superslow on my raspberry and also did strange things like automatically erratically value the importance of my mails what led to thousands of tagged emails which i had to untag for WEEKS. so i am sad. maybe i will do something like setting up a mail account for nextcloud only. nevertheless thanks, christoph.

**Comment by ChristophWurst** [comment]
Thank you for sharing your feedback
