### ISSUE TITLE
Mail import

### ISSUE THREAD

**Issue by brandy000** [nextcloud/mail#945]
I´m very happy with the mail app on Nextcloud.
I have been looking for a good mailsolution on my personal cloud and I found it with your app.

But as I was working local on Thunderbird for years, my question is, if I can move these mails to the cloud?
Ok, one way could be, that I put all mails back to the server and then in folder on the cloud.

Maybe you have a shorter way to solve the problem.
Then my dream comes true, and I do have everything on my cloud :-)
Thanks a lot!

**Comment by ChristophWurst** [comment]
> Ok, one way could be, that I put all mails back to the server and then in folder on the cloud.

That's currently the only way to do that because this app does not persist any data. It acts as a simple interface for an IMAP directory.

> I´m very happy with the mail app on Nextcloud.
> I have been looking for a good mailsolution on my personal cloud and I found it with your app.

Thank you very much for this positive feedback :rocket:

**Comment by brandy000** [comment]
Ok, I understand - the folder are just the IMAP-folders!

Thanks for the answer!

**Comment by ChristophWurst** [comment]
You're welcome :)
