### ISSUE TITLE
OCS API to send a message

### ISSUE THREAD

**Issue by ChristophWurst** [nextcloud/mail#9450]
### Is your feature request related to a problem? Please describe.

As a Nextcloud developer I want to automate processes and trigger emails. Right now there is no way to integrate with this app.

### Describe the solution you'd like

Add an OCS endpoint to send a message. 

Outbox is where we're going to add these messages.

Only create is needed for now.

### Work packages

- [ ] API
- [ ] API docs

### Describe alternatives you've considered

N/a

### Additional context

Deliver automation and workflow capabilities across the product suite

**Comment by ChristophWurst** [comment]
API docs pending

**Comment by miaulalala** [comment]
Send api already has documentation
