### ISSUE TITLE
Bug: Username needs to be sanitized before requesting avatars

### ISSUE THREAD

**Issue by D3nnis3n** [nextcloud/mail#9456]
Exception in the logs - InvalidParameterException: Parameter "guestName" for route "core.GuestAvatar.getAvatar"

The user name needs to be sanitized by replacing slash with e.g. a space before requesting the guest avatar from the API.

### Steps to reproduce

I was asked in https://github.com/nextcloud/contacts/issues/3479 to report this here and attach the server PR that was seemingly fixing something similar in nextcloud server for reference: https://github.com/nextcloud/server/pull/43317

The exception seems to be written on the dashboard, e.g. when I open the main page of the cloud.

### Expected behavior

No exception.

### Actual behavior

Exception.

### Mail app version

3.5.7

### Operating system

Ubuntu 22.04 LTS

### PHP engine version

PHP 8.2

### Web server

Apache (supported)

### Database

MariaDB

### Additional info

`{"reqId":"ZeeIH8VNK1ymbZQmMOcg2gAAAAA","level":3,"time":"2024-03-05T21:01:20+00:00","remoteAddr":"2a02:810d:640:1df9:fd0f:49ca:b0b2:5dea","user":"Dennis","app":"no app in context","method":"GET","url":"/ocs/v2.php/apps/dashboard/api/v2/widget-items?widgets%5B%5D=mail","message":"Exception thrown: Symfony\\Component\\Routing\\Exception\\InvalidParameterException","userAgent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/122.0.0.0 Safari/537.36","version":"28.0.3.2","exception":{"Exception":"Symfony\\Component\\Routing\\Exception\\InvalidParameterException","Message":"Parameter \"guestName\" for route \"core.GuestAvatar.getAvatar\" must match \"[^/]++\" (\"Kulturgespräche 2022/23\" given) to generate a corresponding URL.","Code":0,"Trace":[{"file":"/var/www/vhosts/domain.com/subdomains/cloud/3rdparty/symfony/routing/Generator/UrlGenerator.php","line":161,"function":"doGenerate","class":"Symfony\\Component\\Routing\\Generator\\UrlGenerator","type":"->"},{"file":"/var/www/vhosts/domain.com/subdomains/cloud/lib/private/Route/Router.php","line":372,"function":"generate","class":"Symfony\\Component\\Routing\\Generator\\UrlGenerator","type":"->"},{"file":"/var/www/vhosts/domain.com/subdomains/cloud/lib/private/URLGenerator.php","line":103,"function":"generate","class":"OC\\Route\\Router","type":"->"},{"file":"/var/www/vhosts/domain.com/subdomains/cloud/apps/mail/lib/Dashboard/MailWidget.php","line":161,"function":"linkToRoute","class":"OC\\URLGenerator","type":"->"},{"function":"OCA\\Mail\\Dashboard\\{closure}","class":"OCA\\Mail\\Dashboard\\MailWidget","type":"->","args":["*** sensitive parameters replaced ***"]},{"file":"/var/www/vhosts/domain.com/subdomains/cloud/apps/mail/lib/Dashboard/MailWidget.php","line":152,"function":"array_map"},{"file":"/var/www/vhosts/domain.com/subdomains/cloud/apps/mail/lib/Dashboard/MailWidgetV2.php","line":43,"function":"getItems","class":"OCA\\Mail\\Dashboard\\MailWidget","type":"->"},{"file":"/var/www/vhosts/domain.com/subdomains/cloud/apps/dashboard/lib/Controller/DashboardApiController.php","line":142,"function":"getItemsV2","class":"OCA\\Mail\\Dashboard\\MailWidgetV2","type":"->"},{"file":"/var/www/vhosts/domain.com/subdomains/cloud/lib/private/AppFramework/Http/Dispatcher.php","line":230,"function":"getWidgetItemsV2","class":"OCA\\Dashboard\\Controller\\DashboardApiController","type":"->"},{"file":"/var/www/vhosts/domain.com/subdomains/cloud/lib/private/AppFramework/Http/Dispatcher.php","line":137,"function":"executeController","class":"OC\\AppFramework\\Http\\Dispatcher","type":"->"},{"file":"/var/www/vhosts/domain.com/subdomains/cloud/lib/private/AppFramework/App.php","line":184,"function":"dispatch","class":"OC\\AppFramework\\Http\\Dispatcher","type":"->"},{"file":"/var/www/vhosts/domain.com/subdomains/cloud/lib/private/Route/Router.php","line":315,"function":"main","class":"OC\\AppFramework\\App","type":"::"},{"file":"/var/www/vhosts/domain.com/subdomains/cloud/ocs/v1.php","line":65,"function":"match","class":"OC\\Route\\Router","type":"->"},{"file":"/var/www/vhosts/domain.com/subdomains/cloud/ocs/v2.php","line":23,"args":["/var/www/vhosts/domain.com/subdomains/cloud/ocs/v1.php"],"function":"require_once"}],"File":"/var/www/vhosts/domain.com/subdomains/cloud/3rdparty/symfony/routing/Generator/UrlGenerator.php","Line":194,"CustomMessage":"Exception thrown: Symfony\\Component\\Routing\\Exception\\InvalidParameterException"},"id":"65e86052bf280"}`

**Comment by ChristophWurst** [comment]
Dup of https://github.com/nextcloud/mail/issues/9172?

**Comment by D3nnis3n** [comment]
Thanks for editing the title, though I have no idea what username is meant, we don't have Nextcloud users with a slash in their name. The thing mentioned in the log seems to be the title of an e-mail or some such.
