### ISSUE TITLE
Unellipsised subjects in vertical split view have a middle dot symbol (·) at the end 

### ISSUE THREAD

**Issue by nimishavijay** [nextcloud/mail#9465]
### Steps to reproduce

1. Send a message from another account with a very short subject 
2. Open Mail app in vertical split view

### Expected behavior

![image](https://github.com/nextcloud/mail/assets/52440189/b01c4b3d-46f2-45cf-a900-ac26e9f3b6e1)

### Actual behavior

Middle dot symbol at the end

![image](https://github.com/nextcloud/mail/assets/52440189/16664d65-1230-4bcb-ae57-1425199dac46)

### PHP engine version

None

### Web server

None

### Database

None

**Comment by GretaD** [comment]
I added that during full width layout Pr because of your mockup:
![294915796-5c44e7c7-7be0-4769-a8bf-531c0793a02e](https://github.com/nextcloud/mail/assets/12728974/af4e6e8d-a89b-4e46-9ba9-51eb1a8fd968)

but i guess you wanted that only on one line view, right? @nimishavijay

**Comment by nimishavijay** [comment]
@GretaD yep, the vertical split view can stay as it was :)
