### ISSUE TITLE
message body in message list for current message does not have enough contrast

### ISSUE THREAD

**Issue by nimishavijay** [nextcloud/mail#9466]
### Steps to reproduce

1. Open Mail app in vertical split view
2. click on any message

### Expected behavior

Third row containing body text should be white or another suitable color depending on primary color (as far as I understand `--color-primary-element-text` should work)

![image](https://github.com/nextcloud/mail/assets/52440189/ca0edd6e-3c51-42b6-a3dc-2e23f917c6f8)

### Actual behavior

third row is always maxcontrast leading to insufficient contrast between background and text

![image](https://github.com/nextcloud/mail/assets/52440189/18dedfa8-6cce-4f3a-90fb-5b953ca9b71a)

### PHP engine version

None

### Web server

None

### Database

None

**Comment by ChristophWurst** [comment]
https://github.com/nextcloud/mail/pull/9144/files#diff-f9aaae02cb71a5d2f08c77d7a13d5249464738736dd86a447dbdf54e44669f3dL874 where it was fixed

https://github.com/nextcloud/mail/commit/f509bf6fdad678e2e7b2c0146dcf4f6958ecbee9#diff-f9aaae02cb71a5d2f08c77d7a13d5249464738736dd86a447dbdf54e44669f3dR882 where it came back
