### ISSUE TITLE
Contact federation to use contacts from addressbooks on other (NC/carddav) servers

### ISSUE THREAD

**Issue by janklostermann** [nextcloud/mail#9487]
### Is your feature request related to a problem? Please describe.

Context:
I do have, for several reasons, more than one Nextcloud (or for this usecase important: Contact (=carddav) servers).
One of these NCs I use with the different apps in the Webbrowser. 
In that NC-Mail client instance I have all my mail accounts registered to be able to work with just a webbrowser available.
I do have, for various reasons, different addressbooks on different servers (NCs) in use, synced to different devices.

Problem:
When I now write an email in NC-Mail to a recipient whoms contact is stored in an addressbook from another NC server, I cannot use it. I have to go to another place to read out the email address and copy it into the Mail-App, or know it by heart.
Mail uses the data stored in the NC database by the Contacts app, which makes a lot of sense and should (from my point of view) not be changed. But there is currently no way that the Contacts app knows about other carddav servers and can integrate/make available their data. 
Other email clients have solved this problem by allowing to access addressbooks from different (carddav) servers themselves, or by using the respective system service (e.g. Android). 
In NCs case the system service is provided by the Contacts app, which does not provide this feature of integrating (carddav) addressbooks from other servers.

### Describe the solution you'd like

My prefered solution is the enablement of federation for contacts (carddav servers, maybe only NC servers for a start).
Would be the best solution, to my understanding. Making the NC Federation feature more complete.

This way the Mail-App would not need to change anything. There would be simply more addressbooks available for look-up. 
The Contacts app would handle the integration of the federated addressbooks from other servers. And provide all these (internal and federated) addressbooks to the NC environment (the other apps, like Mail) on this NC server.

### Describe alternatives you've considered

Integrating various addressbooks from different carddav servers in Mail itself (as done in many other email clients) would be a workaround, considering the whole NC ecosystem.
It has the advantage that the Mail-team can solve the problem in Mail alone. 
The disadvantage would be, that Contact federation still would not work and the availability of these federated contacts would be limited to the mail app.

### Additional context

Unfortunately the current situation does not allow me to use NC-Mail as a full-blown email client. The manual workaround to handle the situation, which is now needed, is just too cumbersome.

**Comment by ChristophWurst** [comment]
This app uses the Nextcloud server's contact search API to find recipients from Contacts. If this is a missing feature, it's to be added there.

**Comment by janklostermann** [comment]
You are probably right. At least for my prefered solution.

But they might not feel the problem. The problem occurs here in the Mail app. Maybe in other apps too. 
For the Contacts app it might be just a "nice to have" feature ... 
That's why I chose to place it here.

I will have a look how to place it with the Contacts app and reference this issue there.

**Comment by ChristophWurst** [comment]
This can be solved with federation as discussed in https://github.com/nextcloud/contacts/issues/3855
