### ISSUE TITLE
Editor toolbar not usable with dark theme

### ISSUE THREAD

**Issue by ChristophWurst** [nextcloud/mail#9489]
### Steps to reproduce

1. Enable the dark theme
2. Set up an account
3. Compose a message

### Expected behavior

Good design

### Actual behavior

![image](https://github.com/nextcloud/mail/assets/1374172/8c154c7b-7917-439a-b026-9c05932d5e9e)

### PHP engine version

None

### Web server

None

### Database

None

**Comment by ChristophWurst** [comment]
![image](https://github.com/nextcloud/mail/assets/1374172/584730ff-d762-488b-ad28-1b7428ebf52d)

for me with Mail 3.6 and Nextcloud 27

**Comment by ChristophWurst** [comment]
| System \ Firefox | Firefox bright | Firefox dark |
|--------|--------|--------|
| System bright | Works | Works |
| System dark | Works | Works |

@miaulalala what are your settings in nextcloud, browser and system? do you use any dark theme plugins?

**Comment by JuliaKirschenheuter** [comment]
Found a bad commit in PR: https://github.com/nextcloud/mail/pull/9469
