### ISSUE TITLE
Tags are not wrapped into a separate line

### ISSUE THREAD

**Issue by st3iny** [nextcloud/mail#9497]
### Steps to reproduce

1. Have some mails in your account.
2. Tag a mail.
3. Observe that tags are not wrapped.

### Expected behavior

Tags should be displayed in a separate line below the subject and preview.

### Actual behavior

The tags are shown at the right.

![grafik](https://github.com/nextcloud/mail/assets/1479486/10c114db-7c0b-4479-a113-9614341c8609)

### Mail app version

main

**Comment by hamza221** [comment]
#9425 is broken ?

**Comment by hamza221** [comment]
duplicate of #9334 ?

**Comment by st3iny** [comment]
Closing in favour of #9334.
