### ISSUE TITLE
Could not extract app mail

### ISSUE THREAD

**Issue by ifrx** [nextcloud/mail#951]
Installed current nextcloud via "setup-nextcloud.php" on a  shared hosting space with PHP 7.0.30 and MySQL 5.6.40 and enabled some Apps without any hassle, except for the Mail app.

Clicking on "Enable" ends with "Could not extract app mail".
Do you have an idea why that could be?

The enabled apps are:
- Activity
- Admin notifications
- Audio Player
- Auditing / Logging
- Brute
- Calendar
- Collaborative tags
- Comments
- Contacts
- Deleted files
- External storage support
- Federation
- File sharing
- First run wizard
- Gallery
- Log Reader
- Markdown Editor
- Mindmaps
- Monitoring
- Nextcloud announcements
- Notes
- Notifications
- Password policy
- PDF viewer
- Quota warning
- Reader (ebook reader)
- Share by mail
- Text editor
- Theming
- Update notification
- Usage survey
- Versions
- Video player

By the way, your hint "Be sure to review the [contributing guidelines](https://github.com/nextcloud/mail/blob/master/.github/CONTRIBUTING.md)." proposing "The [issue template can be found here](https://raw.github.com/nextcloud/mail/master/.github/issue_template.md)" produces "404: Not Found".

Hope, my message is neverthless sufficiently complete.

**Comment by ChristophWurst** [comment]
> Do you have an idea why that could be?

Not really. Do you have any logs (e.g. Nextcloud's `nextcloud.log` from the `data` directory)?

> By the way, your hint "Be sure to review the contributing guidelines." proposing "The issue template can be found here" produces "404: Not Found".

Thanks for this feedback. I'll update the URL.

> Hope, my message is neverthless sufficiently complete.

We now have dedicated issue templates for bug reports: https://github.com/nextcloud/mail/issues/new?template=bug.md

**Comment by ifrx** [comment]
> any logs

I have attached yesterday's data/[nextcloud.log](https://github.com/nextcloud/mail/files/2134352/nextcloud.log).
Hope it helps. Seems there is no other log available.

**Comment by ChristophWurst** [comment]
> "opendir(\/var\/tmp\/): failed to open dir: Permission denied at \/mnt\/webq\/a0\/68\/54281468\/htdocs\/afrivonk\/lib\/private\/TempManager.php#190"

-> Nextcloud is unable to write to the temporary directory. Please report this issue at https://github.com/nextcloud/web-installer or try to simply fix your permissions accordingly or configure Nextcloud properly.

**Comment by ifrx** [comment]
Thank you for taking a look. Did a fresh nextcloud install via "setup-nextcloud.php" as it "[checks the dependencies on your enviroment and unpacks the files with the right permissions](https://github.com/nextcloud/web-installer)".
Went well again without any hassle, except for enabling the Mail app which still fails with "Could not extract app mail". 

My nextcloud.log says
`{"reqId":"WzZyQCBbVfcifmdGd10O1wAAAmo","level":3,"time":"2018-06-29T17:54:21+00:00","remoteAddr":"185.##.###.###","user":"#####","app":"core","method":"POST","url":"\/nc\/index.php\/settings\/ajax\/enableapp.php","message":"Could not extract app mail","userAgent":"Mozilla\/5.0 (X11; Linux x86_64) AppleWebKit\/537.36 (KHTML, like Gecko) Chrome\/66.0.3359.170 Safari\/537.36 OPR\/53.0.2907.99","version":"13.0.4.0"}`

I guess it is an Mail app issue for I could flawlessly enable different other apps.
Now, I use the RainLoop Webmail app as a substitute for the Mail app.
