### ISSUE TITLE
I think this is an inconsistency between vanilla HTML `<input>` elements and Nc* components.

### ISSUE THREAD

**Issue by JuliaKirschenheuter** [nextcloud/mail#9558]
Please harmonize input fields in Modal Dialog (Settings) and login mask.

I think this is an inconsistency between vanilla HTML `<input>` elements and Nc* components.

The same happens in Mail:

![image](https://github.com/nextcloud/calendar/assets/1374172/25a046f4-16be-4b9c-8c5a-af41ce70421a)

(password is taller than email)

_Originally posted by @ChristophWurst in https://github.com/nextcloud/calendar/issues/5864#issuecomment-2022882796_

**Comment by ChristophWurst** [comment]
This should be fixed in server then if we want vanilla input elements to look like NcInput

**Comment by JuliaKirschenheuter** [comment]
Thanks @ChristophWurst! 

Why we should not use NcInput in that place?

**Comment by ChristophWurst** [comment]
because using ncinput is not mandatory, so vanilla inputs should work too
