### ISSUE TITLE
Move a mail from spam box (outside mail app) without having it immediately moved back

### ISSUE THREAD

**Issue by franshst** [nextcloud/mail#9562]
### Is your feature request related to a problem? Please describe.

I have a setup where we use multiple mail clients to access mail. One of the clients is Nextcloud mail, other clients could be thunderbird, IOS mail, Google mail (Android).
When Nextcloud mail finds a suspicious mail, it moves it to the spam folder.
When I use one of the other mail clients to put the mail back in the inbox, Nextcloud mail immediately moves it back. I have to login to Nextcloud to get the mail where I want it. This is a hassle and I notice I miss mails because of this behaviour.

### Describe the solution you'd like

Note that most mail servers already have a built-in spam filter. So, the most easy solution is to have an option not to scan the mail for suspicious content, and not move mail at all.

### Describe alternatives you've considered

- Not using Nextcloud mail at all, but only the other clients.
- A better alternative might be that Nextcloud mail keeps track of the mails it marked as spam. If another mail client is used to remove the mail from the spam folder, then Nextcloud mail should honor this action.

**Comment by ChristophWurst** [comment]
> When Nextcloud mail finds a suspicious mail, it moves it to the spam folder.
> When I use one of the other mail clients to put the mail back in the inbox, Nextcloud mail immediately moves it back.

There is no such feature in this app

**Comment by franshst** [comment]
Is there any progress on this issue? We have a shared mailbox and it is impossible to move a mail from the spambucket to the inbox. It is immediately moved back. Presumably because the nextcloud mail of one of the other users of the mailbox finds it to be spam.

**Comment by kesselb** [comment]
Hi @franshst,

As Christoph mentioned, messages are only moved when you click the "Mark as Spam" button.

If https://github.com/nextcloud/mail/issues/9168 caused the message to appear in the wrong folder, please update to the latest maintenance release, as this issue should now be resolved.

If the problem persists after updating, please create a new bug report so we can investigate further.
