### ISSUE TITLE
ordered & unordered list formatting does not work

### ISSUE THREAD

**Issue by alexanderdd** [nextcloud/mail#9608]
### Steps to reproduce

since about a week I noticed that ordered & unordered list formatting does not work on cloud.nextcloud.com mail webinterface. Other formatting like bold, quotation works fine.

![324926716-2cf37fd7-a19d-4544-bdde-4c1f17a4602e](https://github.com/nextcloud/mail/assets/28591861/302d306c-9ba0-43db-b6e8-5db0c0ed2088)

### Expected behavior

list formatting works

### Actual behavior

list formatting doesn't work

### PHP engine version

None

### Web server

None

### Database

None

**Comment by ChristophWurst** [comment]
@GretaD could you please check if the Nextcloud server styles influence these?

**Comment by BiglifeMatt** [comment]
@alexanderdd I'm having the same result.

**Comment by GitBaer** [comment]
I have the same problem. Is there a workaround? Thank you.

**Comment by alexanderdd** [comment]
@GitBaer @BiglifeMatt please react with :+1: to the first post to show that this affects you.

**Comment by BiglifeMatt** [comment]
Possibly related, I find it you under an image, the resize handles are barely accessible.  It is like there is space beyond the window where these elements are just out of view.

**Comment by Aveyron-RetD** [comment]
i receive mails with some code blocks related to lists i believe this is related to this bug 
![image](https://github.com/nextcloud/mail/assets/53221471/ab66be76-0975-487b-b244-354185f639bd)

**Comment by Aveyron-RetD** [comment]
> i receive mails with some code blocks related to lists i believe this is related to this bug ![image](https://private-user-images.githubusercontent.com/53221471/336344335-ab66be76-0975-487b-b244-354185f639bd.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjEzMTU2NDcsIm5iZiI6MTcyMTMxNTM0NywicGF0aCI6Ii81MzIyMTQ3MS8zMzYzNDQzMzUtYWI2NmJlNzYtMDk3NS00ODdiLWIyNDQtMzU0MTg1ZjYzOWJkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MTglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzE4VDE1MDkwN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTNmZjJjZThjNDllN2FjZWFmZGRkOGMzNjUwYWEzODkyYTJlNzc0MGM4NDMxNDEyNjJlZWM2ZTQwNTBhOTVkNzcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.D286bZw0yd9QJMEqMLaEjrdO8NNn3Xt0LQzR5rBfP-U)


Would this solved previously generated emails because i am still seeing the behaviour above on my old emails
