### ISSUE TITLE
Unable to save attachement to files

### ISSUE THREAD

**Issue by brocococonut** [nextcloud/mail#9613]
### Steps to reproduce

Honestly I'm not too sure..

### Expected behavior

A modal should open allowing you to save an attachment to a specified directory.

### Actual behavior

Nothing. An error is thrown in the console which I'll put in the extra details section.

### Mail app version

3.6.0

### Operating system

AIO Nextcloud docker (NextCloud 28 & 29)

### PHP engine version

None

### Web server

None

### Database

None

### Additional info

Error that gets thrown (verified the same across Firefox and Chrome)

```log
vue.runtime.esm.js:3065 TypeError: (0 , V.a1)(...).setMultiSelect(...).addMimeTypeFilter(...).setModal is not a function
    at o.saveToCloud (MessageAttachment.vue:196:1)
    at click (MessageAttachment.vue:1:1899)
    at an (vue.runtime.esm.js:3033:30)
    at o.n (vue.runtime.esm.js:1832:20)
    at an (vue.runtime.esm.js:3033:30)
    at e.$emit (vue.runtime.esm.js:3732:17)
    at o.onClick (actionText-jLsEBszD.mjs:118:16)
    at o.handleClick (NcActionButton.mjs:113:12)
    at an (vue.runtime.esm.js:3033:30)
    at HTMLButtonElement.n (vue.runtime.esm.js:1832:20)
on @ vue.runtime.esm.js:3065
sn @ vue.runtime.esm.js:3057
rn @ vue.runtime.esm.js:3024
an @ vue.runtime.esm.js:3040
n @ vue.runtime.esm.js:1832
an @ vue.runtime.esm.js:3033
e.$emit @ vue.runtime.esm.js:3732
onClick @ actionText-jLsEBszD.mjs:118
handleClick @ NcActionButton.mjs:113
an @ vue.runtime.esm.js:3033
n @ vue.runtime.esm.js:1832
Ya.s._wrapper @ vue.runtime.esm.js:7500
Show 12 more frames
Show less
MessageService.js:71
```

This has been happening for a little while now. It's important to note that it did work a few months ago. Upgrading to a beta version of 3.5.x a while ago seems to be what did it, but even being on the latest stable version seems to be broken. It looks like the "setModal" is deprecated in the @nextcloud/vue and @nextcloud/dialogue repositories, so I'm surprised this hasn't been altered or reported before.

- [Suspect bit of code in repo](https://github.com/nextcloud/mail/blob/a6ec3c14af92f78da22c1bfe2de8a2730d66c8f3/src/components/MessageAttachment.vue#L196)

Feel free to reach out if you need more info. I'll provide whatever I can.

**Comment by ChristophWurst** [comment]
:eyes: @hamza221

**Comment by ChristophWurst** [comment]
> It looks like the "setModal" is deprecated in the @nextcloud/vue and @nextcloud/dialogue repositories, so I'm surprised this hasn't been altered or reported before.
> 
>     * [Suspect bit of code in repo](https://github.com/nextcloud/mail/blob/a6ec3c14af92f78da22c1bfe2de8a2730d66c8f3/src/components/MessageAttachment.vue#L196)

Looks like we did not replace all file picker usages in https://github.com/nextcloud/mail/issues/8707.

**Comment by admorgan** [comment]
This just started happening to me with the update to 3.6.0. It had been working fine before that and I keep this app as up to date as possible.

**Comment by Aveyron-RetD** [comment]
Could this be released in a hotfix ?  We are not able to open files other than pdf and images..

**Comment by marko3122** [comment]
> Could this be released in a hotfix ? We are not able to open files other than pdf and images..

Hi, we have the same problem. Was this resolved with new versions,? We are unfortunately on IONOS Nextcloud and currently still on v28.0.7.5
