### ISSUE TITLE
All incoming email is classified as important

### ISSUE THREAD

**Issue by jurgenhaas** [nextcloud/mail#9634]
### Steps to reproduce

I'm on the latest release of NC and also the mail app, and I experience that all incoming emails are classified as important. I haven't found any settings, where I could either tailor that behaviour or even turn classification completely off.

### Expected behavior

I don't want my emails to be classified. I'll do that on my own, since I've managed to keep the amount of incoming email low a long while ago.

### Actual behavior

All incoming email s classified as important.

### Mail app version

3.7.0-beta.1

### Mailserver or service

DomainFactory

### Operating system

Ubuntu

### PHP engine version

PHP 8.1

### Web server

Apache (supported)

### Database

MySQL

**Comment by the-djmaze** [comment]
See #6390
