### ISSUE TITLE
Optional parameter $bcc declared before required parameter $body is implicitly treated as a required parameter at /var/www/nextcloud/apps/mail/lib/Model/NewMessageData.php#120

### ISSUE THREAD

**Issue by dustbro** [nextcloud/mail#9654]
### Steps to reproduce

      
 public static function fromRequest(Account $account,
                ?string $to = null,
                ?string $cc = null,
                ?string $bcc = null,
                string $subject,
                string $body,
                array $attachments = [],
                bool $isHtml = true,
                bool $requestMdn = false,
                ?int $smimeCertificateId = null,
                bool $smimeSign = false,
                bool $smimeEncrypt = false): NewMessageData {
                $toList = AddressList::parse($to ?: '');
                $ccList = AddressList::parse($cc ?: '');
                $bccList = AddressList::parse($bcc ?: '');

                return new self(
                        $account,
                        $toList,
                        $ccList,
                        $bccList,
                        $subject,
                        $body,
                        $attachments,
                        $isHtml,
                        $requestMdn,
                        $smimeCertificateId,
                        $smimeSign,
                        $smimeEncrypt,
                );
        }

### Expected behavior

optional parameters are declared after all required parameters

### Actual behavior

optional parameters are declared before all required parameters

### Mail app version

3.6.1

### Mailserver or service

DirectNic

### Operating system

Ubuntu 22.04

### PHP engine version

Other

### Web server

Apache (supported)

### Database

MariaDB

### Additional info

PHP 8.3.7

**Comment by joshtrichards** [comment]
Fixed in #9526
