### ISSUE TITLE
Can't sign in to QQ mailbox

### ISSUE THREAD

**Issue by a15355447898a** [nextcloud/mail#9662]
### Steps to reproduce

1. Trying to add qq mailbox account fails

### Expected behavior

Account should be added normally

### Actual behavior

![image](https://github.com/nextcloud/mail/assets/62456287/44ea0d22-f772-487e-8659-53cf9d7b14a2)

![image](https://github.com/nextcloud/mail/assets/62456287/3c49f317-95b6-479d-bdee-56ef05be86f8)

### Mail app version

3.6.1

### Mailserver or service

qq

### Operating system

arch

### PHP engine version

None

### Web server

Nginx

### Database

SQLite

**Comment by ChristophWurst** [comment]
Once auto mode has failed, switch to manual mode and review the detected settings. Are they correct?

**Comment by a15355447898a** [comment]
> Once auto mode has failed, switch to manual mode and review the detected settings. Are they correct?

I tried to switch to manual mode and check the configuration, and I'm sure it's correct.

**Comment by ChristophWurst** [comment]
Good! Then look into debug logs: https://github.com/nextcloud/mail/blob/main/doc/admin.md#logging. horde_imap.log should contain information about why the app can not connect to the server.

**Comment by a15355447898a** [comment]
> Good! Then look into debug logs: https://github.com/nextcloud/mail/blob/main/doc/admin.md#logging. horde_imap.log should contain information about why the app can not connect to the server.好！然后查看调试日志：https://github.com/nextcloud/mail/blob/main/doc/admin.md#logging。horde_imap.log应包含有关应用无法连接到服务器的原因的信息。

I don't know what happened, but he suddenly started working! Thank you for your guidance.
