### ISSUE TITLE
Mails do not load since 3.6.1 mailboxlocked error

### ISSUE THREAD

**Issue by Aveyron-RetD** [nextcloud/mail#9667]
### Steps to reproduce

1.Since 3.6.1 my mails do not load 
2.
3.
[INFO] mail: Mailbox 38 (undefined) is locked 
Object { app: "mail", uid: "36EB499E-980B-46B4-AA2D-F8CA0CD69914", level: 0, error: MailboxLockedError }

### Expected behavior

Mails are displayed..

### Actual behavior

![image](https://github.com/nextcloud/mail/assets/53221471/67439762-8e51-4c35-b454-8448aafdc62c)

### Mail app version

3.6.1

### Mailserver or service

internal Kerio

### Operating system

Nextcloud AIO on docker ubuntu 20.04

### PHP engine version

None

### Web server

None

### Database

None

**Comment by Aveyron-RetD** [comment]
What is weird is new mails do appear on the dashboard...

**Comment by ChristophWurst** [comment]
Check the nextcloud log for any other errors before the locking started. Locks should be released automatically, but in the case of an error they might get stuck.

**Comment by Aveyron-RetD** [comment]
Ok problem resolved by an unexpected upgrade to 29.0.1. :-)
not reproducible in 29.0.1
