### ISSUE TITLE
Show number of unread emails and format number according to available space

### ISSUE THREAD

**Issue by kevgathuku** [nextcloud/mail#967]
### Expected behavior
Email count should not go beyond the end of the column

### Actual behavior
![output 1](https://user-images.githubusercontent.com/3721994/42534991-ed48fcc2-8496-11e8-9f44-49babb626973.png)

### Mail app

**Mail app version:** 0.8.2

**Mailserver or service:** Gmail

**Number of accounts:**  1

**Comment by ChristophWurst** [comment]
Good catch. cc @jancborchardt @skjnldsv

**Comment by jancborchardt** [comment]
Let's simply display "99+" as a maximum to limit it. :) (Think that's also said in the guidelines?)

**Comment by skjnldsv** [comment]
999+ I think :)

**Comment by RobertZenz** [comment]
It's, at least for me, not being displayed at all anymore on the latest version and NC 16. Is that by design or a problem on my end?

**Comment by skjnldsv** [comment]
I think it's fixed now :)

**Comment by ChristophWurst** [comment]
The counters were removed as the logic to keep them in sync was more than buggy. We're working on a new logic (#2064) that will eventually make this more reliable.

**Comment by benks-io** [comment]
@ChristophWurst 
As IMAP Caching to DB is working since April 2020, this useful feature could be implemented again, I guess.

**Comment by ChristophWurst** [comment]
Ah yes. I had this on my mental todo

**Comment by benks-io** [comment]
I propose to rename this Issue "Show Email count, and format Number according to space"

**Comment by ChristophWurst** [comment]
This is actually a duplicate of https://github.com/nextcloud/mail/issues/1400 now. Let's continue there as it also explains the context of why this was dropped as known regression.
