### ISSUE TITLE
multiple attachments

### ISSUE THREAD

**Issue by fvkn** [nextcloud/mail#968]
it is currently not possible to attach several files from the same folder in a mail at the same time. We have to pick them up one by one, each time starting from the root folder, which is quite annoying when working with files buried deep within the structure.

**Comment by ChristophWurst** [comment]
This is a limitation of the Nextcloud server's file picker. Could you please file a feature request at https://github.com/nextcloud/server/issues/new? Thanks!

(For future tickets please follow the issue templates)
