### ISSUE TITLE
Filter always shows red dot overlay

### ISSUE THREAD

**Issue by Chartman123** [nextcloud/mail#9682]
The filter button in SearchMessages.vue always shows the red dot overlay, even if now filters are active. The class will only be added to the corresponding `span` element if `filterChanged == true`:

https://github.com/nextcloud/mail/blob/981db11eb87ab737d08db59138405fb40859b4c3/src/components/SearchMessages.vue#L18-L19

The prop is computed here:

https://github.com/nextcloud/mail/blob/981db11eb87ab737d08db59138405fb40859b4c3/src/components/SearchMessages.vue#L394-L397

Screenshot:

![image](https://github.com/nextcloud/mail/assets/16020496/9c2b0124-acf4-45d1-a7e9-f7b9bcac5767)

I'm using latest Mail release on NC 29

**Comment by ChristophWurst** [comment]
I noticed it too :+1:

**Comment by Chartman123** [comment]
@GretaD @ChristophWurst the red dot is back ;)
