### ISSUE TITLE
Tidy up mail UI

### ISSUE THREAD

**Issue by marcoambrosini** [nextcloud/mail#9683]
- [x] #9752
- [ ] #9753
- [x] #9754
- [x] #9755
- [x] #9786
- [ ] Only show border of outbox mailbox when scrollheight > clientheight
- [x] #9756
- [x] Less space around priority inbox
- [x] https://github.com/nextcloud/mail/issues/9707

Other small fixes that came up in internal design feedback calls: 
- [x] #9823
- [x] #9804

In the end it would look like this 
![image](https://github.com/nextcloud/mail/assets/52440189/9f77b63d-d88a-4082-b021-7ac81a21f37c)

**Comment by GretaD** [comment]
all done
