### ISSUE TITLE
Subfolders to Inbox are not shown using GMX IMAP account

### ISSUE THREAD

**Issue by e-alfred** [nextcloud/mail#969]
### Expected behavior
User created subfolders to the inbox (Posteingang) folder in a GMX IMAP account should be shown in the Mail app. Other providers work (Live Mail, Gmail).

### Actual behavior
Subfolders are not shown.

### Mail app

**Mail app version:** 0.8.2

**Mailserver or service:** Gmx.net

**Number of accounts:** 1 Gmx.net account amongst others

### Server configuration

**Operating system**: Ubuntu 16.04

**Web server:** Apache 2.4

**Database:** Mariadb 10

**PHP version:** 7.0

**Nextcloud Version:** 13.0.4

**Updated from an older version or fresh install:** Updated from 12

#### Client configuration
**Browser:** Firefox, Vivaldi, Chrome (latest version)

**Operating system:** Debian 9, Windows 10, Ubuntu 18.04

**Comment by e-alfred** [comment]
Screenshot: 

![screenshot mail bug](https://user-images.githubusercontent.com/10073629/42690086-9730af4e-8692-11e8-8c60-d0d42565a987.PNG)

**Comment by ChristophWurst** [comment]
Could you please try clicking the house icon on your inbox? That might be a styling issue and there is a expand/collapse icon hiding behind the icon of this special mailbox :see_no_evil:

**Comment by Luticus** [comment]
I actually came here thinking this was a problem too.  Yes, clicking on the house works. I think the icon should probably be updated to indicate that it can be expanded as it's not very intuitive at the moment.

**Comment by e-alfred** [comment]
Yes, it is just a UI/UX bug. There is no indication that there are subfolders hidden beneath the inbox because all other folders show up below the inbox. Maybe an arrow pointing right and, if expanded, showing downwards can solve this issue?
