### ISSUE TITLE
Automatically mark mail as read and remove important tag  when manually marked as junk

### ISSUE THREAD

**Issue by sgofferj** [nextcloud/mail#9710]
### Is your feature request related to a problem? Please describe.

I am just moving to NC mail as my desktop mail client and I noticed that when marking a mail as spam/junk, it is moved to the junk folder but it remains unread and a potential important classification is not removed. That needs to be done manually, increasing the workload for high volume accounts.

### Describe the solution you'd like

NC mail should automatically mark a mail as read and remove a potential important classification when a mail is manually marked as junk.

### Describe alternatives you've considered

The alternative is to do it manually, which - as described - increases the workload on high volume accounts.

**Comment by ChristophWurst** [comment]
I tend to agree with the important flag but am unsure about *read*. Because if you move without reading the message is in fact unread.

Do you know other clients that mark every spam message as read without reading?

**Comment by sgofferj** [comment]
Thunderbird and KMail do. That's how I was inspired to open this issue :).
I currently see a xxxx-load of spam getting by the DNSBLs and spamassassin and three vs. one mouse actions make a big difference in this case...
