### ISSUE TITLE
mail:account:train - not enough messages to train a classifier in account with thousands of messages

### ISSUE THREAD

**Issue by sgofferj** [nextcloud/mail#9712]
### Steps to reproduce

1. Run  ./occ mail:account:train

### Expected behavior

That might be due to a lack of easily available documentation on the ML system of mail...
I would expect the ML model to be able to learn from an account with thousands of message..

### Actual behavior

```
www-data@615d745f46a0:~/html$ ./occ mail:account:train 2   
[info] not enough messages to train a classifier
58MB of memory used
www-data@615d745f46a0:~/html$ ./occ mail:account:diagnose 2
IMAP capabilities:
- ACL
- ANNOTATEMORE
- BINARY
- CATENATE
- CHILDREN
- COMPRESS
- CONDSTORE
- ENABLE
- ESEARCH
- ID
- IDLE
- IMAP4REV1
- LIST-EXTENDED
- LITERAL+
- LOGINDISABLED
- MAILBOX-REFERRALS
- MULTIAPPEND
- NAMESPACE
- NO_ATOMIC_RENAME
- QRESYNC
- QUOTA
- RIGHTS
- SCAN
- SORT
- THREAD
- UIDPLUS
- UNSELECT
- URLAUTH
- WITHIN
- XLIST

Account has 41588 messages in 154 mailboxes
```

### Mail app version

3.7.0

### Mailserver or service

postfix/cyrus

### Operating system

Linux/docker

### PHP engine version

PHP 8.2

### Web server

Nginx

### Database

MariaDB

**Comment by ChristophWurst** [comment]
> Account has 41588 messages in 154 mailboxes

This information is taken from IMAP. The ML training takes data found in the local database cache. If the messages have not been cached yet, you may get this warning. Give the background sync some time.

**Comment by sgofferj** [comment]
Can I manually trigger sync?

**Comment by sgofferj** [comment]
> Give the background sync some time.

Jep, that's it.
