### ISSUE TITLE
Some files have not passed the integrity check.

### ISSUE THREAD

**Issue by sgofferj** [nextcloud/mail#9731]
### Steps to reproduce

1. Check admin settings
2.
3.

### Expected behavior

Integrity check should pass clean

### Actual behavior

Integrity check reports extra files. Manually deleting helps but they are back at least after an update of Mail,

### Mail app version

3.7.1

### Mailserver or service

postfix/cyrus

### Operating system

Linux/docker

### PHP engine version

PHP 8.2

### Web server

Nginx

### Database

MySQL

### Additional info

```
Technical information
=====================
The following list covers which files have failed the integrity check. Please read
the previous linked documentation to learn more about the errors and how to fix
them.

Results
=======
- mail
	- EXTRA_FILE
		- vendor/ezyang/htmlpurifier/library/HTMLPurifier/DefinitionCache/Serializer/HTML/4.15.0,100a0d442686872045400b774dcb082c945a1908,2019080701.ser

Raw output
==========
Array
(
    [mail] => Array
        (
            [EXTRA_FILE] => Array
                (
                    [vendor/ezyang/htmlpurifier/library/HTMLPurifier/DefinitionCache/Serializer/HTML/4.15.0,100a0d442686872045400b774dcb082c945a1908,2019080701.ser] => Array
                        (
                            [expected] => 
                            [current] => c68d95b7adc0174b7dcdc500b4480d4e29378ecda31c124be014323035795d47678e4d77629e7cfc8a667f6ec49863274ee48654b0a93d18e3a20c9f0febcdbf
                        )

                )

        )

)
```

**Comment by joshtrichards** [comment]
Do you happen to have cms_pico installed? It's also possible it's another app that uses the same dependency. Just dealt with this on the forum:

https://help.nextcloud.com/t/some-files-have-not-passed-the-integrity-check-upgrade-to-28-0-4-mail-app/186622/3

The `mail` app itself doesn't use caching within HTMLPurifier so this isn't technically coming from mail, but it ends up showing as if it is `mail`'s problem.

**Comment by sgofferj** [comment]
I do have pico_cms enabled, yes.

**Comment by joshtrichards** [comment]
Then this can only be fixed by pico_cms. They're using the cache in HTMLPurifier without setting the path for it so it's defaulting to "wherever the library is installed": 

http://htmlpurifier.org/live/configdoc/plain.html

`Cache.SerializerPath`

**Comment by joshtrichards** [comment]
nextcloud/cms_pico#248 should address this.
You can test the proposed fix by manually patch your cms_pico (it's a single line change) or following the patch install instructions: https://docs.nextcloud.com/server/latest/admin_manual/issues/applying_patch.html

You'll also need to delete the extra files show in the integrity report.
