### ISSUE TITLE
Badly designed account removal confirmation dialogue

### ISSUE THREAD

**Issue by ChristophWurst** [nextcloud/mail#9734]
### Steps to reproduce

1. Add an account
2. Remove the account

### Expected behavior

See a well designed confirmation dialogue

### Actual behavior

See 
![Bildschirmfoto vom 2024-06-12 13-07-10](https://github.com/nextcloud/mail/assets/1374172/27c1d315-3ee8-4b54-bf40-8ff066af95cb)

* Heading wraps with a lot of whitespace between the lines
* Heading and content touch
* Buttons are badly aligned, right side touches outer border of the modal

### Mail app version

3.8

### PHP engine version

None

### Web server

None

### Database

None

**Comment by ChristophWurst** [comment]
@st3iny could you tackle this?

**Comment by st3iny** [comment]
On it

**Comment by st3iny** [comment]
Can't reproduce locally. I tried stable3.7 on Nextcloud main, stable27 and stable29.

![grafik](https://github.com/nextcloud/mail/assets/1479486/6f6edd94-8d74-4072-b1c0-18b183b66348)

**Comment by ChristophWurst** [comment]
Ok, sorry. I tried with main, not stable3.7 :grimacing: 

3.7 seems fine. It uses oc dialogs. main is broken.
