### ISSUE TITLE
JSCS is deprecated. Migrate from JSCS to ESLint

### ISSUE THREAD

**Issue by kevgathuku** [nextcloud/mail#974]
Move to ESLint for JS linting instead of JSCS since [JSCS is now deprecated](https://eslint.org/blog/2016/07/jscs-end-of-life)

Useful links:
[Migrating from JSCS to ESLint](https://eslint.org/docs/user-guide/migrating-from-jscs)

**Comment by ChristophWurst** [comment]
:+1: sounds good, I guess.

Would you be interested in helping with the migration?

**Comment by kevgathuku** [comment]
Sure. I'll help out with the migration 👍

**Comment by ChristophWurst** [comment]
Thank you :rocket:

**Comment by ChristophWurst** [comment]
Is this fixed now?

**Comment by kevgathuku** [comment]
It should be, since eslint is already set up. I think the remaining bit is removing the jscs config file

**Comment by ChristophWurst** [comment]
Awesome! Would you be up for that task? Otherwise I can do that soonish, so we can finally close this ticket ;)

**Comment by kevgathuku** [comment]
Go for it!

**Comment by kevgathuku** [comment]
Hi @ChristophWurst I was able to finally get around to doing this. I created a PR that should address this. 

On the same note, should we also get rid of `jshint` since we're using `eslint` instead?

**Comment by ChristophWurst** [comment]
> Hi @ChristophWurst I was able to finally get around to doing this. I created a PR that should address this.

Thanks :v: 

> On the same note, should we also get rid of `jshint` since we're using `eslint` instead?

Yes, that makes sense :+1:
