### ISSUE TITLE
Unable to show images from an email and then the client’s ip gets blocked for sometime

### ISSUE THREAD

**Issue by ankitpsaraogi** [nextcloud/mail#980]
I configured mail client and sent a test email from my personal mail box to the configured one. As soon as I clicked on show images, nothing happened and then the entire domain becomes inaccessible for sometime.

The same thing happened when I installed contact and clicked on create new

**Comment by ChristophWurst** [comment]
Hello,

this sounds like a wrongly configured setup. May I ask you to take a look at the [configuration documentation](https://docs.nextcloud.com/server/12/admin_manual/configuration_server/) of the Nextcloud server?

Also check your web server logs and `data/nextcloud.log` for logged errors.

For community help, visit https://help.nextcloud.com/.

If you encounter a bug, please see the existing bug reports at https://github.com/nextcloud/server/issues/ and if there's no ticket for your problem, please file a new one.

Thank you.
