### ISSUE TITLE
The three dots aren't in a line with the E-Mail adress

### ISSUE THREAD

**Issue by PeterJGDe** [nextcloud/mail#9803]
### Steps to reproduce

1. Open Mail
2. log in with your E-Mail account
3. Look on your E-Mail adress

### Expected behavior

The three dots should be in a line with the E-Mail adress

### Actual behavior

The three dots aren't be in a line with the E-Mail adress

### Mail app version

latest

### Operating system

Ubuntu / Docker

### PHP engine version

PHP 8.3

### Web server

Apache (supported)

### Database

MySQL

### Screenshot
![Bildschirmfoto vom 2024-07-05 11-26-39](https://github.com/nextcloud/mail/assets/107960207/449b800b-b5ee-4e36-ae15-25ccc866dbca)

**Comment by GretaD** [comment]
this is fixed with the nc/vue upgrade 8.14
