### ISSUE TITLE
Search mail by "From" or "To" doesn't work

### ISSUE THREAD

**Issue by fmcwebs** [nextcloud/mail#9808]
### Steps to reproduce

1. Press on advanced search button
2. Write a mail on To or From 
3. Press Search
4. Nothing is searched

https://github.com/nextcloud/mail/assets/70668254/14ffdb1e-bd43-4f3b-a631-672747b26c29

### Expected behavior

It just show the mails with the correct from or to.

### Actual behavior

The search function on mail app works fine for all fields except From and To, when you push the button "From Me" it appear to work fine, but when you click on Advanced search and dialog open, you write the mail on From or To, then click "search" and the first time the search reload the folder on you are, showing all the mails, then you make the search again deleting de filter pressing "Delete" on the advanced search and writing again the From or To, and in this situation the dialog of advanced search is closed without doing anything.
To Repeat the behavior we need to reload the site.

![busqueda1](https://github.com/nextcloud/mail/assets/70668254/c8b53865-8752-4eb1-939c-a22fc10f120c)

![busqueda2](https://github.com/nextcloud/mail/assets/70668254/1c09cb0c-815b-4957-9d96-2efba75388e9)

### Mail app version

3.7.2

### Mailserver or service

Dovecot 2.3

### Operating system

Debian

### PHP engine version

PHP 8.2

### Web server

Apache (supported)

### Database

PostgreSQL

### Additional info

We test this on Nextcloud 27.0.2 and in 28.0.7 still ocurr.

**Comment by GretaD** [comment]
fixed here https://github.com/nextcloud/mail/pull/9883

**Comment by fmcwebs** [comment]
@GretaD if you see in this issue, we test it on 3.7.2 and the problem is not fixed. Then we update 3.7.4 and the issue persist, few moments ago we update to 3.7.5, but still persist.

**Comment by GretaD** [comment]
> @GretaD if you see in this issue, we test it on 3.7.2 and the problem is not fixed. Then we update 3.7.4 and the issue persist, few moments ago we update to 3.7.5, but still persist.

thats true, this fixup its not released yet. We will release it soon.

**Comment by fmcwebs** [comment]
Hi @GretaD how are you? do you have an ETA to release this fix?.
