### ISSUE TITLE
App structure incompatible with Nextcloud 14

### ISSUE THREAD

**Issue by ChristophWurst** [nextcloud/mail#981]
### Expected behavior
See a properly working app structure.

### Actual behavior
Structure is pretty much borked. The content element is moved underneath the left sidebar.

Ref https://github.com/nextcloud/mail/pull/973#issuecomment-407044413
Ref https://github.com/nextcloud/server/pull/9982

cc @skjnldsv

**Comment by ChristophWurst** [comment]
@nextcloud/mail I have the feeling this breaking change will make it quite hard to support Nextcloud 13 and 14 at the same time.

I'd therefore suggest to do one final release for Nextcloud 13 and jump to 14+ afterwards. Objections?

**Comment by ChristophWurst** [comment]
@skjnldsv do you know a specific commit where the structure is still compatible with Nextcloud 13? I'd like to temporarily check that out to be able to give the app a good test run.

**Comment by skjnldsv** [comment]
@ChristophWurst just before https://github.com/nextcloud/server/pull/9982 :p

**Comment by ChristophWurst** [comment]
> @ChristophWurst just before nextcloud/server#9982 :p

hehe, tried that. Didn't quite work :man_shrugging:

**Comment by skjnldsv** [comment]
@ChristophWurst then it must be something else than the structure cleanup :/
What does not work exactly?

**Comment by ChristophWurst** [comment]
Nvm, I'm testing 0.8.3 on a separate instance now. This should be fine since there were hardly any changes since the last release and there weren't many bug reports either :)
