### ISSUE TITLE
Advanced search icon does not use CSS var for border radius

### ISSUE THREAD

**Issue by ChristophWurst** [nextcloud/mail#9817]
### Steps to reproduce

1. Open the app
2. Add an account
3. Hover the *Advanced search* icon in a mailbox

### Expected behavior

The new corner radius of Nextcloud server shows effect

### Actual behavior

The corner is fully round

![image](https://github.com/nextcloud/mail/assets/1374172/be686f99-7f55-4fc4-9da6-d1c02ce37460)

For comparison, the rest of the UI:

![image](https://github.com/nextcloud/mail/assets/1374172/91c0f62b-95c7-4514-a2f4-e313aa1e2168)

### Mail app version

main

### PHP engine version

None

### Web server

None

### Database

None

**Comment by ChristophWurst** [comment]
https://docs.nextcloud.com/server/latest/developer_manual/html_css_design/css.html#css-variables should help.

@GVodyanov could you tackle this? I'm sure we'll also find more places with hard-coded radiuses that should migrate to using variables.

**Comment by st3iny** [comment]
We seem to use `var(--border-radius-element)` as the border radius on buttons.
