### ISSUE TITLE
Call to undefined method OCA\Mail\Db\MessageMapper::deleteDuplicateUids()

### ISSUE THREAD

**Issue by RainerEmrich** [nextcloud/mail#9854]
### Steps to reproduce

1. NC 29.0.3
2. Update Mail app: sudo -u www-data php8.3 ./occ app:update --all
3.

### Expected behavior

The mail app should be updated from version 3.7.2 to 3.7.4

### Actual behavior

An exception is thrown:
mail new version available: 3.7.4
```
An unhandled exception has been thrown:
Error: Call to undefined method OCA\Mail\Db\MessageMapper::deleteDuplicateUids() in /var/www/nc_01/nextcloud/apps/mail/lib/Migration/DeleteDuplicateUids.php:27
Stack trace:
#0 /var/www/nc_01/nextcloud/lib/private/Repair.php(125): OCA\Mail\Migration\DeleteDuplicateUids->run()
#1 /var/www/nc_01/nextcloud/lib/private/legacy/OC_App.php(838): OC\Repair->run()
#2 /var/www/nc_01/nextcloud/lib/private/legacy/OC_App.php(779): OC_App::executeRepairSteps()
#3 /var/www/nc_01/nextcloud/lib/private/Installer.php(184): OC_App::updateApp()
#4 /var/www/nc_01/nextcloud/core/Command/App/Update.php(106): OC\Installer->updateAppstoreApp()
#5 /var/www/nc_01/nextcloud/3rdparty/symfony/console/Command/Command.php(298): OC\Core\Command\App\Update->execute()
#6 /var/www/nc_01/nextcloud/3rdparty/symfony/console/Application.php(1040): Symfony\Component\Console\Command\Command->run()
#7 /var/www/nc_01/nextcloud/3rdparty/symfony/console/Application.php(301): Symfony\Component\Console\Application->doRunCommand()
#8 /var/www/nc_01/nextcloud/3rdparty/symfony/console/Application.php(171): Symfony\Component\Console\Application->doRun()
#9 /var/www/nc_01/nextcloud/lib/private/Console/Application.php(213): Symfony\Component\Console\Application->run()
#10 /var/www/nc_01/nextcloud/console.php(102): OC\Console\Application->run()
#11 /var/www/nc_01/nextcloud/occ(11): require_once('...')
```

### PHP engine version

PHP 8.3

### Web server

Apache (supported)

### Database

MariaDB

**Comment by ChristophWurst** [comment]
The code is replaced within the same process that previously loaded the old version then tries to run the new code. This doesn't work in PHP. We'll have to skip the repair or dispatch a background job for it.

**Comment by st3iny** [comment]
Damn, that one is on me. I forgot that repair steps are run on upgrades and we can't use new code.

**Comment by ChristophWurst** [comment]
v3.7.4 taken offline to avoid more instances running into this

**Comment by sebix** [comment]
We had the issue with NC version 28.0.4 and can confirm that a `occ upgrade` call fixed the issue for us.

**Comment by jjasoncool** [comment]
I have uninstalled the app at version 3.7.4. When I install v3.7.2 now, the server still calls it an unstable app that can't be enabled.

**Comment by ChristophWurst** [comment]
You can just stay on 3.7.4 and re-enable the app. Downgrades are not supported. If you still do them, make sure to fully replace the directly. There must not be any extra files.

**Comment by jjasoncool** [comment]
> v3.7.4 taken offline to avoid more instances running into this

I can't find it anymore.

**Comment by jjasoncool** [comment]
> > v3.7.4 taken offline to avoid more instances running into this
> 
> I can't find it anymore. In #9860 I had already removed the whole app from my Nextcloud in the web GUI.
> 
> `[mail] Warning: itinerary file doesn't exist POST /settings/apps/enable`

I fixed it by using the command line install method.
But it still fails in the web GUI.

I have noted this down for the development team to reference in the future.
