### ISSUE TITLE
nextcloud 28.0.7 upgrade mail app to 3.7.4 error

### ISSUE THREAD

**Issue by jjasoncool** [nextcloud/mail#9860]
### Steps to reproduce

1. open app upgrade page
2. upgrade mail app to v3.7.4
3. error occur

### Expected behavior

upgrade successfully

### Actual behavior

[mail] Warning: itinerary file doesn't exist
	POST /settings/apps/enable

[index] Error: Call to undefined method OCA\Mail\Db\MessageMapper::deleteDuplicateUids() in file '/var/www/html/custom_apps/mail/lib/Migration/DeleteDuplicateUids.php' line 27
	GET /settings/apps/update/mail

### Mail app version

3.7.2

### PHP engine version

PHP 8.2

### Web server

Nginx

### Database

MariaDB

### Additional info

My mail app doesn't have any mails.
I removed the whole app and reinstalled it, but it still failed.
It shows me that this app causes the server to be unstable, so I can't install it.

**Comment by mkiah** [comment]
It looks like this is being tracked on [#9854](https://github.com/nextcloud/mail/issues/9854)
