### ISSUE TITLE
In some cases, the attached file is not displayed.

### ISSUE THREAD

**Issue by LaurentGui** [nextcloud/mail#9866]
### Steps to reproduce

In some emails, the attached file is not displayed, and this happens systematically.

### Expected behavior

For example in this case, you can see that there is an attachment
![image](https://github.com/user-attachments/assets/e0233947-4b85-4922-ae66-ec798a05e054)
But in the email, it's impossible to open the attachment
![image](https://github.com/user-attachments/assets/5c622324-1ab8-4f4a-b068-e220921f1b10)

### Actual behavior

 the attached file is not displayed

### Mail app version

3.7.4

### Mailserver or service

ionos

### Operating system

Linux 5.15.149-1-pve x86_64

### PHP engine version

PHP 8.2

### Web server

None

### Database

MySQL

**Comment by ChristophWurst** [comment]
Do you have a non-sensitive email that you could export as .eml, rename to .txt and upload here?

**Comment by LaurentGui** [comment]
[Stat tournaments.eml.txt](https://github.com/user-attachments/files/16250983/Stat.tournaments.eml.txt)
Voici un mail d'exemple

**Comment by LaurentGui** [comment]
I think the problem was linked to javascript problems present on my instance because since I had these problems corrected, the attachments are displayed correctly.
Sincerely
