### ISSUE TITLE
Displaying email with localized GUI elements -> TO and email address are overlapped

### ISSUE THREAD

**Issue by pongraczi** [nextcloud/mail#989]
It is a css/field positioning problem only, occurs with translated GUI.

### Expected behavior
Should look like:  
címzett   "GEKKO Computer GmbH"....

*címzett means: To*

### Actual behavior
![kijeloles_739](https://user-images.githubusercontent.com/5891983/43133866-5ff43cb0-8f40-11e8-9607-eab78696226a.png)

### Mail app

**Mail app version:** 8.5.3 (and earlier)

#### Client configuration
**Browser:** Brave, Chromium etc.

#### Screenshot

![kijeloles_738](https://user-images.githubusercontent.com/5891983/43134123-3ab38f72-8f41-11e8-9a7c-bdd064b66be0.png)

**Comment by jancborchardt** [comment]
This is fixed with the new compser which has plenty more space for the labels :)
![image](https://user-images.githubusercontent.com/925062/75445043-360d5a80-5997-11ea-8e85-8dd7d045e8a1.png)
