### ISSUE TITLE
Email composer menu not aligned properly

### ISSUE THREAD

**Issue by GVodyanov** [nextcloud/mail#9892]
### Steps to reproduce

1. Open mail
2. Open new email modal
3. Click on 3 dotted menu in bottom right corner

### Expected behavior

`NcActionButton` to be aligned with `NcActionCheckbox`

### Actual behavior

![image](https://github.com/user-attachments/assets/ddc48bd9-3886-4dfd-9744-0b4f2ded92c7)

### Mail app version

main

### PHP engine version

None

### Web server

None

### Database

None

**Comment by GretaD** [comment]
the checkboxes, are shown as misaligned everywhere actually
