### ISSUE TITLE
[Bug]: .dovecot.* files presence generates 'Error'

### ISSUE THREAD

**Issue by shaman007** [nextcloud/mail#9893]
### Steps to reproduce

1. Enable 'Mail' app
2. Enable SIEVE in the Dovecot
3. Have  "Undefined array key ".dovecot.sieve" at /nextcloud/apps/mail/lib/IMAP/MailboxSync.php#297" and other .dovecot.* related errors in the log

### Expected behavior

No errors or 'Info' messages

### Actual behavior

"Undefined array key ".dovecot.sieve" at /nextcloud/apps/mail/lib/IMAP/MailboxSync.php#297" and other .dovecot.* errors in log.

### Mail app version

3.7.5

### Mailserver or service

Dovecot self-hosted

### Operating system

Linux

### PHP engine version

PHP 8.2

### Web server

Nginx

### Database

MariaDB

### Additional info

 .dovecot.* files ideally should be ignored by the Mail app.

**Comment by kesselb** [comment]
Thanks for your bug report 👍 

Are you sure that's not a problem with your dovecot configuration? The mailbox sync is fetching a list of folders from the imap server, those *.dovecot files should not be there?

**Comment by shaman007** [comment]
.dovecot.* files are supplimentary, they're starting with dot and should be ignored by the IMAP server/client, but they're needed to work with the sieve extention of the Dovecot (that sorts mail to folders when it comes). No, I don't think there are any issues with my config, I'd used it for years. I think the fix is rather simpte - ignoring dot-files.

**Comment by kesselb** [comment]
Thanks, I'm closing your report as won't fix. 

I'm running a pretty basic postfix/dovecot setup[^1] and folders/files starting with dovecot.* / .dovecot.sieve are not returned by dovecot when asking for a list of folders.

![Image](https://github.com/user-attachments/assets/81a52bf9-4489-4640-a338-c7a2efb7552f)
![Image](https://github.com/user-attachments/assets/030b572d-45ac-47f5-9726-3eb7eaeed25c)



[^1]: https://workaround.org/ispmail-bullseye/
