### ISSUE TITLE
Sieve security buttons in account settings look bad

### ISSUE THREAD

**Issue by GVodyanov** [nextcloud/mail#9894]
### Steps to reproduce

1. Open mail app in Firefox
2. Add an account
3. Open account settings
4. Under "Sieve filter server", enable it
5. See the buttons

### Expected behavior

Buttons should be thinner and have a smaller border radius

### Actual behavior

![image](https://github.com/user-attachments/assets/510b2c10-90c1-4969-b807-427c601eed0c)

### Mail app version

Main

### PHP engine version

None

### Web server

None

### Database

None

**Comment by ChristophWurst** [comment]
Duplicate of https://github.com/nextcloud/mail/issues/9467 or we reintroduced the bug

**Comment by GVodyanov** [comment]
> Duplicate of #9467 or we reintroduced the bug

I guess reintroduced, but I nextcloud vued it now so it shouldn't happen again
