### ISSUE TITLE
Email Client issue - Max Connection exceeds - Top Level Domain access temporarily revoked.

### ISSUE THREAD

**Issue by ankitpsaraogi** [nextcloud/mail#990]
The Top level domain gets temporarily blocked when I open the email client in NextCloud.
### Expected behavior
It should show me the contents of the email
### Actual behavior
Error after sometime when the access is restored:
GuzzleHttp\Exception\RequestException: cURL error 3: malformed
/home/agarwegg/public_html/files/3rdparty/guzzlehttp/guzzle/src/RequestFsm.php - line 103: GuzzleHttp\Exception\RequestException wrapException(Object(GuzzleHttp\Message\Request), Object(GuzzleHttp\Ring\Exception\RingException))
/home/agarwegg/public_html/files/3rdparty/guzzlehttp/guzzle/src/RequestFsm.php - line 132: GuzzleHttp\RequestFsm->__invoke(Object(GuzzleHttp\Transaction))
/home/agarwegg/public_html/files/3rdparty/react/promise/src/FulfilledPromise.php - line 25: GuzzleHttp\RequestFsm->GuzzleHttp{closure}(*** sensitive parameters replaced ***)
/home/agarwegg/public_html/files/3rdparty/guzzlehttp/ringphp/src/Future/CompletedFutureValue.php - line 55: React\Promise\FulfilledPromise->then(Object(Closure), NULL, NULL)
/home/agarwegg/public_html/files/3rdparty/guzzlehttp/guzzle/src/Message/FutureResponse.php - line 43: GuzzleHttp\Ring\Future\CompletedFutureValue->then(Object(Closure), NULL, NULL)
/home/agarwegg/public_html/files/3rdparty/guzzlehttp/guzzle/src/RequestFsm.php - line 134: GuzzleHttp\Message\FutureResponse proxy(Object(GuzzleHttp\Ring\Future\CompletedFutureArray), Object(Closure))
/home/agarwegg/public_html/files/3rdparty/guzzlehttp/guzzle/src/Client.php - line 165: GuzzleHttp\RequestFsm->__invoke(Object(GuzzleHttp\Transaction))
/home/agarwegg/public_html/files/3rdparty/guzzlehttp/guzzle/src/Client.php - line 125: GuzzleHttp\Client->send(Object(GuzzleHttp\Message\Request))
/home/agarwegg/public_html/files/lib/private/Http/Client/Client.php - line 138: GuzzleHttp\Client->get(NULL, Array)
/home/agarwegg/public_html/files/apps/mail/lib/Controller/ProxyController.php - line 124: OC\Http\Client\Client->get(NULL)
[internal function] OCA\Mail\Controller\ProxyController->proxy(NULL)
/home/agarwegg/public_html/files/lib/private/AppFramework/Http/Dispatcher.php - line 161: call_user_func_array(Array, Array)
/home/agarwegg/public_html/files/lib/private/AppFramework/Http/Dispatcher.php - line 91: OC\AppFramework\Http\Dispatcher->executeController(Object(OCA\Mail\Controller\ProxyController), 'proxy')
/home/agarwegg/public_html/files/lib/private/AppFramework/App.php - line 115: OC\AppFramework\Http\Dispatcher->dispatch(Object(OCA\Mail\Controller\ProxyController), 'proxy')
/home/agarwegg/public_html/files/lib/private/AppFramework/Routing/RouteActionHandler.php - line 47: OC\AppFramework\App main('OCA\Mail\Contro...', 'proxy', Object(OC\AppFramework\DependencyInjection\DIContainer), Array)
[internal function] OC\AppFramework\Routing\RouteActionHandler->__invoke(Array)
/home/agarwegg/public_html/files/lib/private/Route/Router.php - line 297: call_user_func(Object(OC\AppFramework\Routing\RouteActionHandler), Array)
/home/agarwegg/public_html/files/lib/base.php - line 999: OC\Route\Router->match('/apps/mail/prox...')
/home/agarwegg/public_html/files/index.php - line 42: OC handleRequest()
{main}

### Mail app

**Mail app version:** (see apps admin page, e.g. 0.5.3)
0.8.3
**Mailserver or service:** (e.g. Outlook, Yahoo, Gmail, Exchange,...)

**Number of accounts:** (e.g. 1 or 2)

### Server configuration

**Operating system**: (e.g. Debian 8)

**Web server:** (e.g. Apache, Nginx,...)

**Database:** (e.g. MariaDB, SQLite, PostgreSQL,...)

**PHP version:** (e.g. 7.0)

**Nextcloud Version:** (see admin page, e.g. 13.0.2)

**Updated from an older version or fresh install:**

**List of activated apps:**
```
If you have access to your command line run e.g.:
sudo -u www-data php occ app:list
from within your server installation folder
```

**The content of config/config.php:**
```
If you have access to your command line run e.g.:
sudo -u www-data php occ config:list system
from within your Nextcloud installation folder

or

Insert your config.php content here
Make sure to remove all sensitive content such as passwords. (e.g. database password, passwordsalt, secret, smtp password, …)
```

#### Client configuration
**Browser:** (e.g. Firefox 48)

**Operating system:** (e.g. Arch Linux)

##### Web server error log
```
Insert your webserver log here (e.g. /var/log/apache2/...)
```

##### Server log (data/nextcloud.log)
```
Insert your server log here
```

##### IMAP log (data/horde_imap.log)
```
Enable debug mode and insert your horde IMAP log here, see https://docs.nextcloud.com/server/13/developer_manual/general/debugging.html#debug-mode
```

##### SMTP log (data/horde_smtp.log)
```
Enable debug mode and insert your horde IMAP log here, see https://docs.nextcloud.com/server/13/developer_manual/general/debugging.html#debug-mode
```

##### Browser log
```
Insert your browser log here, this could for example include:

a) The javascript console log
b) The network log 
```

**Comment by ChristophWurst** [comment]
As a (temporary) solution you could try setting up an IMAP proxy that pools IMAP connections.

**Comment by ankitpsaraogi** [comment]
Hi, but I wish to configure the mail client and the contacts app as well. And same issue happened when I clicked on create contact after installing the contacts app.

**Comment by ChristophWurst** [comment]
Whoops, sorry. I misread your report. I thought you were talking about too many *IMAP connections*. Of course this is a completely different problem then. Your instance might be unable to make outgoing connections.

May I ask you to take a look at the admin documentation? https://docs.nextcloud.com/server/13/admin_manual/configuration_server/ I have the feeling that your server might be misconfigured.

For community help, please see help.nextcloud.com for similar problems. In case this might be a bug, take a look at the [existing server issues](https://github.com/nextcloud/server/issues) and file a new one if this problem is new.

Thank you!

**Comment by ankitpsaraogi** [comment]
I checked the configuration. I didn't find any error there.

**Comment by ChristophWurst** [comment]
Okay then please see their forum or the server issue tracker.

Make sure you provide some helpful information about your setup (e.g. which server, shared hosting or root server, …).
