### ISSUE TITLE
Some mails are displaying block code for  lists <![if !supportLists]>1.    <![endif]>

### ISSUE THREAD

**Issue by Aveyron-RetD** [nextcloud/mail#9913]
### Steps to reproduce

Some mails are received with list numbers in block code

### Expected behavior

Received as list with normal formatting

### Actual behavior

<![if !supportLists]>1.    <![endif]>
see screenshot
![image](https://github.com/user-attachments/assets/e7728b1c-1b03-4e91-9f39-876be4a95fef)

### Mail app version

3.7.5

### Operating system

Nextcloud AIO on docker ubuntu 20.04

### PHP engine version

None

### Web server

None

### Database

None

**Comment by ChristophWurst** [comment]
Export the email as .eml, rename to .txt and upload it here for an engineer to try and reproduce.

**Comment by Aveyron-RetD** [comment]
[gestion documentaire.eml.txt](https://github.com/user-attachments/files/16377917/gestion.documentaire.eml.txt)

**Comment by Aveyron-RetD** [comment]
[gestion documentaire.eml.txt](https://github.com/user-attachments/files/16378057/gestion.documentaire.eml.txt)

**Comment by Aveyron-RetD** [comment]
[
[gestion.documentaire.eml(1).txt](https://github.com/user-attachments/files/16378074/gestion.documentaire.eml.1.txt)
](url)

**Comment by Aveyron-RetD** [comment]
Could it be linked to the lack of MS fonts ? https://github.com/nextcloud/richdocuments/issues/3297

**Comment by Aveyron-RetD** [comment]
in a diffusion list they are correctly displayed.

Original mail
![image](https://github.com/user-attachments/assets/d092aa56-10f2-4633-b39d-b367b302d88d)

in a diffusion list
![image](https://github.com/user-attachments/assets/fb69606f-2705-4251-bf42-d6c5661ee155)

**Comment by Aveyron-RetD** [comment]
Ok mail received today with following behaviour
Mail received today with the cryptic message 
![image](https://github.com/user-attachments/assets/c5aa895b-470e-4791-a5b6-e294ec77fe6f)

I think this is linked to #9913 same person/same client 

HR persons sends me some fancy emails jobs with lots of styling in the mail from MS 
![image](https://github.com/user-attachments/assets/4c4a2aaf-d392-48e0-a049-d934149c7ce5)

I can see the mail in the source

Downloading it and displaying it in thunderbird works


After righting a bug report the mail displayed again with those code blocks so adding to this bug

**Comment by Aveyron-RetD** [comment]
@ChristophWurst  bug filled with email. See above.

**Comment by ChristophWurst** [comment]
I see your notifications @Aveyron-RetD, thanks. We will look into this. Please be patient.

**Comment by Aveyron-RetD** [comment]
i have this advert showing this <![if !mso]><![endif]>
![image](https://github.com/user-attachments/assets/1434f474-da27-40a5-a913-5be88152a4ec)

**Comment by Aveyron-RetD** [comment]
Some readings about this
[https://stackoverflow.com/questions/18254711/html-emails-fallback-for-mso-conditional/35422479#35422479](url)

https://www.litmus.com/blog/a-guide-to-rendering-differences-in-microsoft-outlook-clients

https://www.emailonacid.com/blog/article/email-development/conditional-css-code/

tempting to rename this

**Comment by nextcloud-command** [comment]
Hi there! It looks like this issue hasn’t seen much activity for a while and might need a bit more information to move forward. If we don’t hear back soon, we may close it to keep things organized. Thanks again for your contributions – we really appreciate it!

**Comment by Aveyron-RetD** [comment]
@ChristophWurst This is still happening on a daily basis. Should this issue be closed ?
The main error is ^^ see above (<![if !supportLists]>·         <![endif]>)

**Comment by Aveyron-RetD** [comment]
Sorry did not see properly your response.
You did test with the email provided ... 

The weird stuff if i reply to myself with the mail with mso problems => On the replied section it is working...
Do i need MS font installed ?

**Comment by Aveyron-RetD** [comment]
I am still seing this bug in 5.9.3.

I have a claude conversation with a suggested fix ...  https://claude.ai/share/8c9b4c2b-1615-4b28-944a-06969268007b

Looks like this mso is quite common in mail clients 
https://github.com/frappe/frappe/issues/26396
https://github.com/thunderbird/thunderbird-android/issues/2559
