### ISSUE TITLE
Scrolling *+ New message* button

### ISSUE THREAD

**Issue by ChristophWurst** [nextcloud/mail#9916]
### Steps to reproduce

1. Open the app
2. Set up an account

### Expected behavior

Good design

### Actual behavior

![image](https://github.com/user-attachments/assets/e874f981-d6d8-4482-9ddf-f7242c643bc2)

### Mail app version

v4.0.0-alpha1

### PHP engine version

None

### Web server

None

### Database

None

**Comment by ChristophWurst** [comment]
https://github.com/nextcloud-libraries/nextcloud-vue/pull/5831#discussion_r1691995939

**Comment by ChristophWurst** [comment]
It still happens

**Comment by hamza221** [comment]
<img width="323" alt="image" src="https://github.com/user-attachments/assets/c392ca1f-75a3-4f24-85e1-eb34dd40d109">

Any steps to reproduce ?

**Comment by st3iny** [comment]
Yeah, I wasn't able to reproduce on latest main neither.

**Comment by ChristophWurst** [comment]
Try the company cloud. Perhaps it was fixed in nextcloud/vue and we don't run the update yet

**Comment by hamza221** [comment]
| cloud | main |
|--------|--------|
| <img width="767" alt="image" src="https://github.com/user-attachments/assets/32bc3668-998a-4f27-af94-ec5bd72e381f"> | <img width="991" alt="image" src="https://github.com/user-attachments/assets/04503d75-2e2f-4c1f-bb71-f60332c0ad2a"> | 

@GVodyanov 's fix is not on nc.c yet
