### ISSUE TITLE
Show *Rely*/*Reply all* in toolbar

### ISSUE THREAD

**Issue by ChristophWurst** [nextcloud/mail#9920]
### Is your feature request related to a problem? Please describe.

![Bildschirmfoto vom 2024-07-25 21-10-25](https://github.com/user-attachments/assets/4aa22bcf-1012-4459-9b2b-dea812d5cf27)
![Bildschirmfoto vom 2024-07-25 21-10-39](https://github.com/user-attachments/assets/a9b30aae-6369-45d6-ac3b-3af37560b93c)

### Describe the solution you'd like

A (reply to all) button should be in the toolbar. Currently it’s only on the bottom of the mail.

**Comment by ChristophWurst** [comment]
@jancborchardt @nimishavijay we need your input here. Shall we show *two* Reply buttons? One in the toolbar and one at the bottom?

**Comment by nimishavijay** [comment]
Good point, makes sense to me too show it as an icon only button in the toolbar, and as a full button at the bottom 👍🏼
