### ISSUE TITLE
Attachement Preview / Viewer

### ISSUE THREAD

**Issue by SebastianKrupinski** [nextcloud/mail#9929]
### Is your feature request related to a problem? Please describe.

No

### Describe the solution you'd like

![Attachment Preview](https://github.com/user-attachments/assets/d1c1090a-61c0-444c-ac67-0edfd94ffed7)

To generate a preview when you hover over a attachment.

Also to have the option to view the attachment in the browser verses downloading it and using locally installed software.

This would be a great feature for sensitive attachments as they would NOT need to be stored locally to be viewed. Would also be great when viewing attachments on systems that don't belong to the user.

### Describe alternatives you've considered

Download file and use local software

**Comment by ChristophWurst** [comment]
How is this different to the existing integration with Viewer where you can view images, videos and PDFs in place?

**Comment by SebastianKrupinski** [comment]
Morning @ChristophWurst,

So at the moment (unless I am missing an extension) the only options in mail are to "Download Attachment" or "Save to Files". 

What I am suggesting is, when you hover over the attachment for a second+ a preview of the attachment is opened (hover modal), and if you lets say double click the attachment it opens a preview in a new tab (no downloading or saving).

**Comment by ChristophWurst** [comment]
Install and enable the *viewer* and *files_pdfviewer* apps, then try again pls

**Comment by SebastianKrupinski** [comment]
That app does not work...

![image](https://github.com/user-attachments/assets/52b81b41-9eeb-44ee-90f8-9d129f169893)

Says it hasn't been touched in 6 years

![image](https://github.com/user-attachments/assets/78e09564-44e0-4130-bad0-270a28768587)

**Comment by SebastianKrupinski** [comment]
Tested again:
With viewer enabled and files_pdfviewer cloned and enabled (this package is now included in the server package therefore not available in the store).

Tested with: 
Image, PDF, Plain Text File, and Spread Sheet File

Test results:
- Clicking on Image or PDF does show preview viewer on top of mail app with content.
- Clicking on Plain Text File, and Spread Sheet File does NOT show any preview

Possible improvements:
- Hovering over a file could show larger preview in modal that does not need to be closed (x). (Like the image from the desktop client above) This would make it easier to find which file is relevant to save, edit or fully read/review.
- Double clicking a file could open the file in a new tab with the appropriate editor/viewer. This would make it easier to open files needed to be referenced, in communications, e.g. Commenting on changes need in contract or spreadsheet that is sent as an attachment. The contract/spreed sheet can be open in one tab for reference and the existing tab can be used to write the response.

**Comment by ChristophWurst** [comment]
@SebastianKrupinski could you put the two last suggestions into separate feature requests so we can close this one? Previews are supported and do work

**Comment by SebastianKrupinski** [comment]
@ChristophWurst 

Done.

https://github.com/nextcloud/mail/issues/10289
https://github.com/nextcloud/mail/issues/10291
