### ISSUE TITLE
Behavior on mail server error

### ISSUE THREAD

**Issue by mat-m** [nextcloud/mail#9932]
### Is your feature request related to a problem? Please describe.

When I click on a message, the body area says "Not Found". If I select Delete, I got a toaster "Could not delete message".
I can't know if error is from NC or from the mail server.
When the error comes from the mail server, an indication would be great, and maybe even a behavior change for better visualization. Clicking on the refresh button when in the mailbox does nothing

### Describe the solution you'd like

At least an error toaster saying mail server is not responding.
Add a warning sign before the account.
Maybe disable commands, and add or replace them with a "retry connection" button, more visible than the default one ?

### Describe alternatives you've considered

Reading the logs, I can see "Error when communicating with the mail server."
But I only can do this as I am an admin. Standard users cannot.

### Additional context

Error from server could be very temporary (wrong second) or longer (server crash needing a cold restart). I can't tell what is the best way to handle all cases.

**Comment by ChristophWurst** [comment]
Is the mail server down or is this an artifact of https://github.com/nextcloud/mail/issues/9168 and the mail server actually not finding the requested message?

**Comment by ChristophWurst** [comment]
Closing due to the lack of response
