### ISSUE TITLE
Attachments not visible

### ISSUE THREAD

**Issue by h4knet** [nextcloud/mail#9957]
### Steps to reproduce

1. Receive an email with an attachment file like a .zip file
2. Try to open the email

### Expected behavior

Being able to see and download the attachment.
Example with email containing PDF files :
![image](https://github.com/user-attachments/assets/6ef012cf-4b0f-42a8-9d0d-f71af88ab41e)
paper clip visible.

![image](https://github.com/user-attachments/assets/30cfec73-2100-4afe-a041-d1c2c89025e0)

### Actual behavior

Attachment not shown.

Here the paper clip is not shown :
![image](https://github.com/user-attachments/assets/de2c4cc8-1e3a-4a80-99d8-e69572fa8b4a)

The email appears empty :
![image](https://github.com/user-attachments/assets/b5167ede-9000-414b-835d-11eac3320c8d)

Actual email seen with another webmail (Roundcube) :
![image](https://github.com/user-attachments/assets/8876a053-db9c-40f4-b891-a63fb309ecae)

### Mail app version

3.7.6

### Mailserver or service

Postfix / Dovecot

### Operating system

Ubuntu LTS

### PHP engine version

PHP 8.1

### Web server

Apache (supported)

### Database

MariaDB

### Additional info

Nextcloud 28.0.8

**Comment by h4knet** [comment]
Hello,
Bug still present in `28.0.9`

**Comment by ChristophWurst** [comment]
Thanks @h4knet. Nobody has looked into this yet, hence it's not fixed.

Please share the sources of the email, especially the part headers with content type and content disposition.

**Comment by nextcloud-command** [comment]
Hi there! It looks like this issue hasn’t seen much activity for a while and might need a bit more information to move forward. If we don’t hear back soon, we may close it to keep things organized. Thanks again for your contributions – we really appreciate it!
