### ISSUE TITLE
UI - New message button misaligned

### ISSUE THREAD

**Issue by h4knet** [nextcloud/mail#9959]
### Is your feature request related to a problem? Please describe.

The new message icon is misaligned :
![image](https://github.com/user-attachments/assets/15fbc236-218e-40a9-8d0e-47bc34dec854)

### Describe the solution you'd like

Best solution imho would be to align the icon with the others and to slightly enlarge the text.
UX wise, having all theses blue wide and look-alike buttons make it less obvious to know what is what.

Here is some suggestion :
![image](https://github.com/user-attachments/assets/a3afa58c-8500-40ad-82b2-40914d4bffe1)

Here is an example with Gmail :
![image](https://github.com/user-attachments/assets/578e5408-aa05-4f6a-a6d1-05df7d6c5627)

**Comment by ChristophWurst** [comment]
![Image](https://github.com/user-attachments/assets/60c639ef-df7d-4e7e-8a51-9e74a48d3065)

^ this is what it looked like now, as specified by Nextcloud designers. The *+ New message* is centered, other navigation entries are left-aligned.
